{
  "abstract": [
    {
      "text": "Metadata keys for the Camera Image File Format (CIFF) image format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CIFF Image Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Adobe Photoshop image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "8BIM Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/8bim-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Camera Image File Format (CIFF) image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/ciff-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Digital Negative (DNG) archival format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/dng-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Graphics Interchange Format (GIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/gif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the High Efficiency Image Container (HEIC) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEIC Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/heic-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the JPEG File Interchange Format (JFIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "JFIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/jfif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFCameraSerialNumber": {
      "abstract": [
        {
          "text": "The camera serial number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFCameraSerialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFCameraSerialNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFCameraSerialNumber"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFCameraSerialNumber",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffcameraserialnumber"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFContinuousDrive": {
      "abstract": [
        {
          "text": "The continuous drive mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFContinuousDrive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFContinuousDrive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFContinuousDrive"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFContinuousDrive",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffcontinuousdrive"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFDescription": {
      "abstract": [
        {
          "text": "The camera description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFDescription"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFDescription",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffdescription"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that uses Camera Image File Format (CIFF). See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFirmware": {
      "abstract": [
        {
          "text": "The firmware version of the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFFirmware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFirmware",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFFirmware"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFFirmware",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertycifffirmware"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFlashExposureComp": {
      "abstract": [
        {
          "text": "The flash exposure compensation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFFlashExposureComp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFlashExposureComp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFFlashExposureComp"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFFlashExposureComp",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffflashexposurecomp"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFocusMode": {
      "abstract": [
        {
          "text": "The focus mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFFocusMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFocusMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFFocusMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFFocusMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertycifffocusmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageFileName": {
      "abstract": [
        {
          "text": "The image file name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFImageFileName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageFileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFImageFileName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFImageFileName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffimagefilename"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageName": {
      "abstract": [
        {
          "text": "The image name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFImageName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFImageName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFImageName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffimagename"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageSerialNumber": {
      "abstract": [
        {
          "text": "The image serial number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFImageSerialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageSerialNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFImageSerialNumber"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFImageSerialNumber",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffimageserialnumber"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensMaxMM": {
      "abstract": [
        {
          "text": "The maximum lens length in millimeters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFLensMaxMM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensMaxMM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFLensMaxMM"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFLensMaxMM",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertycifflensmaxmm"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensMinMM": {
      "abstract": [
        {
          "text": "The minimum lens length in millimeters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFLensMinMM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensMinMM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFLensMinMM"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFLensMinMM",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertycifflensminmm"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensModel": {
      "abstract": [
        {
          "text": "The lens model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFLensModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFLensModel"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFLensModel",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertycifflensmodel"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFMeasuredEV": {
      "abstract": [
        {
          "text": "The measured exposure value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFMeasuredEV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFMeasuredEV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFMeasuredEV"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFMeasuredEV",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffmeasuredev"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFMeteringMode": {
      "abstract": [
        {
          "text": "The metering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFMeteringMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFMeteringMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFMeteringMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFMeteringMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffmeteringmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFOwnerName": {
      "abstract": [
        {
          "text": "The name of the camera’s owner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFOwnerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFOwnerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFOwnerName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFOwnerName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffownername"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFRecordID": {
      "abstract": [
        {
          "text": "The number of images taken since the camera shipped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFRecordID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFRecordID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFRecordID"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFRecordID",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffrecordid"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFReleaseMethod": {
      "abstract": [
        {
          "text": "The method of shutter release—single-shot or continuous.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFReleaseMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFReleaseMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFReleaseMethod"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFReleaseMethod",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffreleasemethod"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFReleaseTiming": {
      "abstract": [
        {
          "text": "The priority for shutter release timing—shutter or focus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFReleaseTiming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFReleaseTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFReleaseTiming"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFReleaseTiming",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffreleasetiming"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFSelfTimingTime": {
      "abstract": [
        {
          "text": "The time in milliseconds until shutter release when using the self-timer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFSelfTimingTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFSelfTimingTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFSelfTimingTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFSelfTimingTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffselftimingtime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFShootingMode": {
      "abstract": [
        {
          "text": "The shooting mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFShootingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFShootingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFShootingMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFShootingMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffshootingmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFWhiteBalanceIndex": {
      "abstract": [
        {
          "text": "The white balance index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFWhiteBalanceIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFWhiteBalanceIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyCIFFWhiteBalanceIndex"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyCIFFWhiteBalanceIndex",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyciffwhitebalanceindex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/png-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Portable Network Graphics (PNG) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/png-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Truevision Graphics Adapter (TGA) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TGA Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tga-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Tagged Image File Format (TIFF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tiff-image-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Specific-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
      ],
      "title": "Format-Specific Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "Image-Details",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFDescription",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageFileName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageSerialNumber"
      ],
      "title": "Image Details"
    },
    {
      "anchor": "Exposure",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFWhiteBalanceIndex",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFlashExposureComp",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFMeasuredEV",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFMeteringMode"
      ],
      "title": "Exposure"
    },
    {
      "anchor": "Shutter-Information",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFReleaseTiming",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFSelfTimingTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFReleaseMethod",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFContinuousDrive",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFShootingMode"
      ],
      "title": "Shutter Information"
    },
    {
      "anchor": "Lens-and-Focus",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFocusMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensMaxMM",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensMinMM",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensModel"
      ],
      "title": "Lens and Focus"
    },
    {
      "anchor": "Camera-Information",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFirmware",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFOwnerName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFCameraSerialNumber",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFRecordID"
      ],
      "title": "Camera Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "Image-Details",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFDescription",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageFileName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFImageSerialNumber"
              ],
              "title": "Image Details"
            },
            {
              "anchor": "Exposure",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFWhiteBalanceIndex",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFlashExposureComp",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFMeasuredEV",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFMeteringMode"
              ],
              "title": "Exposure"
            },
            {
              "anchor": "Shutter-Information",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFReleaseTiming",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFSelfTimingTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFReleaseMethod",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFContinuousDrive",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFShootingMode"
              ],
              "title": "Shutter Information"
            },
            {
              "anchor": "Lens-and-Focus",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFocusMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensMaxMM",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensMinMM",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFLensModel"
              ],
              "title": "Lens and Focus"
            },
            {
              "anchor": "Camera-Information",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFFirmware",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFOwnerName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFCameraSerialNumber",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyCIFFRecordID"
              ],
              "title": "Camera Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Specific-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
              ],
              "title": "Format-Specific Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFImageFileName/title",
          "value": "kCGImagePropertyCIFFImageFileName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFImageFileName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFImageFileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFFocusMode/title",
          "value": "kCGImagePropertyCIFFFocusMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFFocusMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFFocusMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFLensModel/title",
          "value": "kCGImagePropertyCIFFLensModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFLensModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFLensModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFDictionary/title",
          "value": "kCGImagePropertyCIFFDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFReleaseMethod/title",
          "value": "kCGImagePropertyCIFFReleaseMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFReleaseMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFReleaseMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFLensMinMM/title",
          "value": "kCGImagePropertyCIFFLensMinMM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFLensMinMM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFLensMinMM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFWhiteBalanceIndex/title",
          "value": "kCGImagePropertyCIFFWhiteBalanceIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFWhiteBalanceIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFWhiteBalanceIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFCameraSerialNumber/title",
          "value": "kCGImagePropertyCIFFCameraSerialNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFCameraSerialNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFCameraSerialNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFReleaseTiming/title",
          "value": "kCGImagePropertyCIFFReleaseTiming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFReleaseTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFReleaseTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFContinuousDrive/title",
          "value": "kCGImagePropertyCIFFContinuousDrive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFContinuousDrive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFContinuousDrive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFLensMaxMM/title",
          "value": "kCGImagePropertyCIFFLensMaxMM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFLensMaxMM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFLensMaxMM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFDescription/title",
          "value": "kCGImagePropertyCIFFDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFShootingMode/title",
          "value": "kCGImagePropertyCIFFShootingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFShootingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFShootingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFFlashExposureComp/title",
          "value": "kCGImagePropertyCIFFFlashExposureComp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFFlashExposureComp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFFlashExposureComp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFMeasuredEV/title",
          "value": "kCGImagePropertyCIFFMeasuredEV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFMeasuredEV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFMeasuredEV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFRecordID/title",
          "value": "kCGImagePropertyCIFFRecordID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFRecordID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFOwnerName/title",
          "value": "kCGImagePropertyCIFFOwnerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFOwnerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFOwnerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFFirmware/title",
          "value": "kCGImagePropertyCIFFFirmware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFFirmware/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFFirmware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFImageSerialNumber/title",
          "value": "kCGImagePropertyCIFFImageSerialNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFImageSerialNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFImageSerialNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFImageName/title",
          "value": "kCGImagePropertyCIFFImageName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFImageName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFImageName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFMeteringMode/title",
          "value": "kCGImagePropertyCIFFMeteringMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFMeteringMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFMeteringMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFSelfTimingTime/title",
          "value": "kCGImagePropertyCIFFSelfTimingTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyCIFFSelfTimingTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyCIFFSelfTimingTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/ciff-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/ciff-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
