{
  "abstract": [
    {
      "text": "Metadata keys for the Graphics Interchange Format (GIF).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GIF Image Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Adobe Photoshop image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "8BIM Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/8bim-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Camera Image File Format (CIFF) image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/ciff-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Digital Negative (DNG) archival format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/dng-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Graphics Interchange Format (GIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/gif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the High Efficiency Image Container (HEIC) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEIC Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/heic-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the JPEG File Interchange Format (JFIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "JFIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/jfif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFCanvasPixelHeight": {
      "abstract": [
        {
          "text": "The height of the main image, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFCanvasPixelHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFCanvasPixelHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFCanvasPixelHeight"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGIFCanvasPixelHeight",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygifcanvaspixelheight"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFCanvasPixelWidth": {
      "abstract": [
        {
          "text": "The width of the main image, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFCanvasPixelWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFCanvasPixelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFCanvasPixelWidth"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGIFCanvasPixelWidth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygifcanvaspixelwidth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFDelayTime": {
      "abstract": [
        {
          "text": "The number of seconds to wait before displaying the next image in an animated sequence, clamped to a minimum of 100 milliseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFDelayTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGIFDelayTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygifdelaytime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that uses Graphics Interchange Format (GIF). See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGIFDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygifdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFFrameInfoArray": {
      "abstract": [
        {
          "text": "An array of dictionaries that contain timing information for the image sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFFrameInfoArray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFFrameInfoArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFFrameInfoArray"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGIFFrameInfoArray",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygifframeinfoarray"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFHasGlobalColorMap": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GIF has a global color map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFHasGlobalColorMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFHasGlobalColorMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFHasGlobalColorMap"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGIFHasGlobalColorMap",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygifhasglobalcolormap"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFImageColorMap": {
      "abstract": [
        {
          "text": "The image color map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFImageColorMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFImageColorMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFImageColorMap"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGIFImageColorMap",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygifimagecolormap"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFLoopCount": {
      "abstract": [
        {
          "text": "The number of times to repeat an animated sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFLoopCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFLoopCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFLoopCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGIFLoopCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygifloopcount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFUnclampedDelayTime": {
      "abstract": [
        {
          "text": "The number of seconds to wait before displaying the next image in an animated sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFUnclampedDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFUnclampedDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGIFUnclampedDelayTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGIFUnclampedDelayTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygifunclampeddelaytime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/png-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Portable Network Graphics (PNG) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/png-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Truevision Graphics Adapter (TGA) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TGA Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tga-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Tagged Image File Format (TIFF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tiff-image-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Specific-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
      ],
      "title": "Format-Specific Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "Image-Properties",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFCanvasPixelHeight",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFCanvasPixelWidth",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFHasGlobalColorMap",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFImageColorMap"
      ],
      "title": "Image Properties"
    },
    {
      "anchor": "Sequence-Timing",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFFrameInfoArray",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFDelayTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFUnclampedDelayTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFLoopCount"
      ],
      "title": "Sequence Timing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "Image-Properties",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFCanvasPixelHeight",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFCanvasPixelWidth",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFHasGlobalColorMap",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFImageColorMap"
              ],
              "title": "Image Properties"
            },
            {
              "anchor": "Sequence-Timing",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFFrameInfoArray",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFDelayTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFUnclampedDelayTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGIFLoopCount"
              ],
              "title": "Sequence Timing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Specific-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
              ],
              "title": "Format-Specific Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFFrameInfoArray/title",
          "value": "kCGImagePropertyGIFFrameInfoArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFFrameInfoArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGIFFrameInfoArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFHasGlobalColorMap/title",
          "value": "kCGImagePropertyGIFHasGlobalColorMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFHasGlobalColorMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGIFHasGlobalColorMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFCanvasPixelHeight/title",
          "value": "kCGImagePropertyGIFCanvasPixelHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFCanvasPixelHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGIFCanvasPixelHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFLoopCount/title",
          "value": "kCGImagePropertyGIFLoopCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFLoopCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGIFLoopCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFDelayTime/title",
          "value": "kCGImagePropertyGIFDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGIFDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFCanvasPixelWidth/title",
          "value": "kCGImagePropertyGIFCanvasPixelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFCanvasPixelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGIFCanvasPixelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFImageColorMap/title",
          "value": "kCGImagePropertyGIFImageColorMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFImageColorMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGIFImageColorMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFUnclampedDelayTime/title",
          "value": "kCGImagePropertyGIFUnclampedDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFUnclampedDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGIFUnclampedDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFDictionary/title",
          "value": "kCGImagePropertyGIFDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGIFDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGIFDictionary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/gif-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/gif-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
