{
  "abstract": [
    {
      "text": "Keys for Global Positioning System (GPS) information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GPS Dictionary Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for Exchangeable Image File Format (EXIF) data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EXIF Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/exif-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-properties": {
      "abstract": [
        {
          "text": "Properties that apply to the container in general, and not necessarily to an individual image in the container.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for International Press Telecommunications Council (IPTC) data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPTC Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/iptc-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAltitude": {
      "abstract": [
        {
          "text": "The altitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSAltitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAltitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSAltitude"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSAltitude",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsaltitude"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAltitudeRef": {
      "abstract": [
        {
          "text": "The altitude point of reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSAltitudeRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAltitudeRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSAltitudeRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSAltitudeRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsaltituderef"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAreaInformation": {
      "abstract": [
        {
          "text": "The name of the GPS area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSAreaInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAreaInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSAreaInformation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSAreaInformation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsareainformation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDOP": {
      "abstract": [
        {
          "text": "The degree of precision (DOP) of the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDOP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDOP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDOP"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDOP",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdop"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDateStamp": {
      "abstract": [
        {
          "text": "The date and time information relative to Coordinated Universal Time (UTC).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDateStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDateStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDateStamp"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDateStamp",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdatestamp"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestBearing": {
      "abstract": [
        {
          "text": "The bearing to the destination point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestBearing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestBearing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestBearing"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDestBearing",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdestbearing"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestBearingRef": {
      "abstract": [
        {
          "text": "The reference for giving the bearing to the destination point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestBearingRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestBearingRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestBearingRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDestBearingRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdestbearingref"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestDistance": {
      "abstract": [
        {
          "text": "The distance to the destination point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestDistance"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDestDistance",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdestdistance"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestDistanceRef": {
      "abstract": [
        {
          "text": "The units for expressing the distance to the destination point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestDistanceRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestDistanceRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestDistanceRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDestDistanceRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdestdistanceref"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLatitude": {
      "abstract": [
        {
          "text": "The latitude of the destination point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestLatitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLatitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestLatitude"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDestLatitude",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdestlatitude"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLatitudeRef": {
      "abstract": [
        {
          "text": "An indication of whether the latitude of the destination point is northern or southern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestLatitudeRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLatitudeRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestLatitudeRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDestLatitudeRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdestlatituderef"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLongitude": {
      "abstract": [
        {
          "text": "The longitude of the destination point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestLongitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLongitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestLongitude"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDestLongitude",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdestlongitude"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLongitudeRef": {
      "abstract": [
        {
          "text": "An indication of whether the longitude of the destination point is east or west.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestLongitudeRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLongitudeRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDestLongitudeRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDestLongitudeRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdestlongituderef"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that has Global Positioning System (GPS) information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDifferental": {
      "abstract": [
        {
          "text": "An indication of whether differential correction is applied to the GPS receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDifferental"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDifferental",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDifferental"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDifferental",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdifferental"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSHPositioningError": {
      "abstract": [
        {
          "text": "The horizontal error in the GPS position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSHPositioningError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSHPositioningError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSHPositioningError"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSHPositioningError",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpshpositioningerror"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSImgDirection": {
      "abstract": [
        {
          "text": "The direction of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSImgDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSImgDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSImgDirection"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSImgDirection",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsimgdirection"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSImgDirectionRef": {
      "abstract": [
        {
          "text": "The reference for the direction of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSImgDirectionRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSImgDirectionRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSImgDirectionRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSImgDirectionRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsimgdirectionref"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLatitude": {
      "abstract": [
        {
          "text": "The latitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSLatitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLatitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSLatitude"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSLatitude",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpslatitude"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLatitudeRef": {
      "abstract": [
        {
          "text": "An indication of whether the latitude is north or south.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSLatitudeRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLatitudeRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSLatitudeRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSLatitudeRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpslatituderef"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLongitude": {
      "abstract": [
        {
          "text": "The longitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSLongitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLongitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSLongitude"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSLongitude",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpslongitude"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLongitudeRef": {
      "abstract": [
        {
          "text": "An indication of whether the longitude is east or west.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSLongitudeRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLongitudeRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSLongitudeRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSLongitudeRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpslongituderef"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMapDatum": {
      "abstract": [
        {
          "text": "The geodetic survey data used by the GPS receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSMapDatum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMapDatum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSMapDatum"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSMapDatum",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsmapdatum"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMeasureMode": {
      "abstract": [
        {
          "text": "The measurement mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSMeasureMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMeasureMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSMeasureMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSMeasureMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsmeasuremode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSProcessingMethod": {
      "abstract": [
        {
          "text": "The name of the method used to find a location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSProcessingMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSProcessingMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSProcessingMethod"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSProcessingMethod",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsprocessingmethod"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSatellites": {
      "abstract": [
        {
          "text": "The satellites used for GPS measurements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSatellites"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSatellites",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSatellites"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSSatellites",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpssatellites"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeed": {
      "abstract": [
        {
          "text": "The GPS receiver’s speed of movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSpeed"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSSpeed",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsspeed"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeedRef": {
      "abstract": [
        {
          "text": "The unit for expressing the GPS receiver’s speed of movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSpeedRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeedRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSpeedRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSSpeedRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsspeedref"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSStatus": {
      "abstract": [
        {
          "text": "The status of the GPS receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSStatus"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSStatus",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsstatus"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTimeStamp": {
      "abstract": [
        {
          "text": "The time in UTC (Coordinated Universal Time).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSTimeStamp",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpstimestamp"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrack": {
      "abstract": [
        {
          "text": "The direction of GPS receiver’s movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSTrack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSTrack"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSTrack",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpstrack"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrackRef": {
      "abstract": [
        {
          "text": "The reference for the direction of GPS receiver’s movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSTrackRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrackRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSTrackRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSTrackRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpstrackref"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSVersion": {
      "abstract": [
        {
          "text": "The GPS version information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSVersion"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSVersion",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsversion"
    },
    "doc://com.apple.imageio/documentation/ImageIO/webp-data": {
      "abstract": [
        {
          "text": "Metadata keys for WebP metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/webp-data",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebP Data",
      "type": "topic",
      "url": "/documentation/imageio/webp-data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common-Image-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/webp-data"
      ],
      "title": "Common Image Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "GPS-Coordinate",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLatitude",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLongitude",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAltitude",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLatitudeRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLongitudeRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAltitudeRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSHPositioningError"
      ],
      "title": "GPS Coordinate"
    },
    {
      "anchor": "Destinations",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLatitude",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLongitude",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestBearing",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestDistance",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLatitudeRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLongitudeRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestBearingRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestDistanceRef"
      ],
      "title": "Destinations"
    },
    {
      "anchor": "Image-Orientation",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSImgDirectionRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSImgDirection"
      ],
      "title": "Image Orientation"
    },
    {
      "anchor": "Measurement-Details",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSStatus",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSatellites",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMeasureMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDOP",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeedRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeed",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrackRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrack",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMapDatum",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSProcessingMethod",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAreaInformation",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDifferental"
      ],
      "title": "Measurement Details"
    },
    {
      "anchor": "Timestamp-Information",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTimeStamp",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDateStamp"
      ],
      "title": "Timestamp Information"
    },
    {
      "anchor": "GPS-Version",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSVersion"
      ],
      "title": "GPS Version"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "GPS-Coordinate",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLatitude",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLongitude",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAltitude",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLatitudeRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSLongitudeRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAltitudeRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSHPositioningError"
              ],
              "title": "GPS Coordinate"
            },
            {
              "anchor": "Destinations",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLatitude",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLongitude",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestBearing",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestDistance",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLatitudeRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestLongitudeRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestBearingRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDestDistanceRef"
              ],
              "title": "Destinations"
            },
            {
              "anchor": "Image-Orientation",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSImgDirectionRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSImgDirection"
              ],
              "title": "Image Orientation"
            },
            {
              "anchor": "Measurement-Details",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSStatus",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSatellites",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMeasureMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDOP",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeedRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeed",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrackRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrack",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMapDatum",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSProcessingMethod",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAreaInformation",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDifferental"
              ],
              "title": "Measurement Details"
            },
            {
              "anchor": "Timestamp-Information",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTimeStamp",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDateStamp"
              ],
              "title": "Timestamp Information"
            },
            {
              "anchor": "GPS-Version",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSVersion"
              ],
              "title": "GPS Version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common-Image-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/webp-data"
              ],
              "title": "Common Image Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSLatitude/title",
          "value": "kCGImagePropertyGPSLatitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSLatitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSLatitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSpeedRef/title",
          "value": "kCGImagePropertyGPSSpeedRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSpeedRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSSpeedRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSLongitudeRef/title",
          "value": "kCGImagePropertyGPSLongitudeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSLongitudeRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSLongitudeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSMapDatum/title",
          "value": "kCGImagePropertyGPSMapDatum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSMapDatum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSMapDatum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestDistanceRef/title",
          "value": "kCGImagePropertyGPSDestDistanceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestDistanceRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDestDistanceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSAreaInformation/title",
          "value": "kCGImagePropertyGPSAreaInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSAreaInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSAreaInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSAltitude/title",
          "value": "kCGImagePropertyGPSAltitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSAltitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSAltitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSStatus/title",
          "value": "kCGImagePropertyGPSStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSMeasureMode/title",
          "value": "kCGImagePropertyGPSMeasureMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSMeasureMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSMeasureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSImgDirection/title",
          "value": "kCGImagePropertyGPSImgDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSImgDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSImgDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestBearingRef/title",
          "value": "kCGImagePropertyGPSDestBearingRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestBearingRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDestBearingRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSLongitude/title",
          "value": "kCGImagePropertyGPSLongitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSLongitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSLongitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSTimeStamp/title",
          "value": "kCGImagePropertyGPSTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDifferental/title",
          "value": "kCGImagePropertyGPSDifferental"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDifferental/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDifferental"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestLatitude/title",
          "value": "kCGImagePropertyGPSDestLatitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestLatitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDestLatitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDictionary/title",
          "value": "kCGImagePropertyGPSDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSLatitudeRef/title",
          "value": "kCGImagePropertyGPSLatitudeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSLatitudeRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSLatitudeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSProcessingMethod/title",
          "value": "kCGImagePropertyGPSProcessingMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSProcessingMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSProcessingMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSHPositioningError/title",
          "value": "kCGImagePropertyGPSHPositioningError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSHPositioningError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSHPositioningError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestLongitude/title",
          "value": "kCGImagePropertyGPSDestLongitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestLongitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDestLongitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestBearing/title",
          "value": "kCGImagePropertyGPSDestBearing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestBearing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDestBearing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSTrack/title",
          "value": "kCGImagePropertyGPSTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSTrackRef/title",
          "value": "kCGImagePropertyGPSTrackRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSTrackRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSTrackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestDistance/title",
          "value": "kCGImagePropertyGPSDestDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDestDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDOP/title",
          "value": "kCGImagePropertyGPSDOP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDOP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDOP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSVersion/title",
          "value": "kCGImagePropertyGPSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDateStamp/title",
          "value": "kCGImagePropertyGPSDateStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDateStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDateStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestLatitudeRef/title",
          "value": "kCGImagePropertyGPSDestLatitudeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestLatitudeRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDestLatitudeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSatellites/title",
          "value": "kCGImagePropertyGPSSatellites"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSatellites/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSSatellites"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSpeed/title",
          "value": "kCGImagePropertyGPSSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSImgDirectionRef/title",
          "value": "kCGImagePropertyGPSImgDirectionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSImgDirectionRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSImgDirectionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestLongitudeRef/title",
          "value": "kCGImagePropertyGPSDestLongitudeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDestLongitudeRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDestLongitudeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSAltitudeRef/title",
          "value": "kCGImagePropertyGPSAltitudeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSAltitudeRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSAltitudeRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/gps-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/gps-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
