{
  "abstract": [
    {
      "text": "Metadata keys for the High Efficiency Image Container (HEIC) format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "HEIC Image Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Adobe Photoshop image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "8BIM Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/8bim-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Camera Image File Format (CIFF) image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/ciff-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Digital Negative (DNG) archival format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/dng-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Graphics Interchange Format (GIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/gif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the JPEG File Interchange Format (JFIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "JFIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/jfif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSCanvasPixelHeight": {
      "abstract": [
        {
          "text": "The height of the main image, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSCanvasPixelHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSCanvasPixelHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSCanvasPixelHeight"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyHEICSCanvasPixelHeight",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyheicscanvaspixelheight"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSCanvasPixelWidth": {
      "abstract": [
        {
          "text": "The width of the main image, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSCanvasPixelWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSCanvasPixelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSCanvasPixelWidth"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyHEICSCanvasPixelWidth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyheicscanvaspixelwidth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSDelayTime": {
      "abstract": [
        {
          "text": "The number of seconds to wait before displaying the next image in the sequence, clamped to a minimum of ",
          "type": "text"
        },
        {
          "code": "0.1",
          "type": "codeVoice"
        },
        {
          "text": " seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSDelayTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyHEICSDelayTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyheicsdelaytime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSDictionary": {
      "abstract": [
        {
          "text": "A dictionary of properties related to an HEIC container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyHEICSDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyheicsdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSFrameInfoArray": {
      "abstract": [
        {
          "text": "An array of dictionaries that contain timing information for the image sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSFrameInfoArray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSFrameInfoArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSFrameInfoArray"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyHEICSFrameInfoArray",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyheicsframeinfoarray"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSLoopCount": {
      "abstract": [
        {
          "text": "The number of times to play the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSLoopCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSLoopCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSLoopCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyHEICSLoopCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyheicsloopcount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSUnclampedDelayTime": {
      "abstract": [
        {
          "text": "The unclamped number of seconds to wait before displaying the next image in the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSUnclampedDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSUnclampedDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEICSUnclampedDelayTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyHEICSUnclampedDelayTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyheicsunclampeddelaytime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyNamedColorSpace": {
      "abstract": [
        {
          "text": "The name of the image’s color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyNamedColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyNamedColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyNamedColorSpace"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyNamedColorSpace",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertynamedcolorspace"
    },
    "doc://com.apple.imageio/documentation/ImageIO/png-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Portable Network Graphics (PNG) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/png-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Truevision Graphics Adapter (TGA) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TGA Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tga-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Tagged Image File Format (TIFF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tiff-image-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Specific-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
      ],
      "title": "Format-Specific Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "Image-Properties",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSCanvasPixelHeight",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSCanvasPixelWidth",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyNamedColorSpace"
      ],
      "title": "Image Properties"
    },
    {
      "anchor": "Sequence-Timing",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSFrameInfoArray",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSDelayTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSUnclampedDelayTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSLoopCount"
      ],
      "title": "Sequence Timing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "Image-Properties",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSCanvasPixelHeight",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSCanvasPixelWidth",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyNamedColorSpace"
              ],
              "title": "Image Properties"
            },
            {
              "anchor": "Sequence-Timing",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSFrameInfoArray",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSDelayTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSUnclampedDelayTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEICSLoopCount"
              ],
              "title": "Sequence Timing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Specific-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
              ],
              "title": "Format-Specific Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSUnclampedDelayTime/title",
          "value": "kCGImagePropertyHEICSUnclampedDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSUnclampedDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyHEICSUnclampedDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSLoopCount/title",
          "value": "kCGImagePropertyHEICSLoopCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSLoopCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyHEICSLoopCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSCanvasPixelWidth/title",
          "value": "kCGImagePropertyHEICSCanvasPixelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSCanvasPixelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyHEICSCanvasPixelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSFrameInfoArray/title",
          "value": "kCGImagePropertyHEICSFrameInfoArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSFrameInfoArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyHEICSFrameInfoArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSDelayTime/title",
          "value": "kCGImagePropertyHEICSDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyHEICSDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSDictionary/title",
          "value": "kCGImagePropertyHEICSDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyHEICSDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyNamedColorSpace/title",
          "value": "kCGImagePropertyNamedColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyNamedColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyNamedColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSCanvasPixelHeight/title",
          "value": "kCGImagePropertyHEICSCanvasPixelHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEICSCanvasPixelHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyHEICSCanvasPixelHeight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/heic-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/heic-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
