{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/image-i-o-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Image I/O Macros"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/GET_IMAGEIO_AVAIL_BUT_DEPR_MACRO": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GET_IMAGEIO_AVAIL_BUT_DEPR_MACRO"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/GET_IMAGEIO_AVAIL_BUT_DEPR_MACRO",
      "kind": "symbol",
      "role": "symbol",
      "title": "GET_IMAGEIO_AVAIL_BUT_DEPR_MACRO",
      "type": "topic",
      "url": "/documentation/imageio/get_imageio_avail_but_depr_macro"
    },
    "doc://com.apple.imageio/documentation/ImageIO/GET_IMAGEIO_AVAIL_MACRO": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GET_IMAGEIO_AVAIL_MACRO"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/GET_IMAGEIO_AVAIL_MACRO",
      "kind": "symbol",
      "role": "symbol",
      "title": "GET_IMAGEIO_AVAIL_MACRO",
      "type": "topic",
      "url": "/documentation/imageio/get_imageio_avail_macro"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IIO_BRIDGED_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IIO_BRIDGED_TYPE"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IIO_BRIDGED_TYPE",
      "kind": "symbol",
      "role": "symbol",
      "title": "IIO_BRIDGED_TYPE",
      "type": "topic",
      "url": "/documentation/imageio/iio_bridged_type"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IIO_HAS_IOSURFACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IIO_HAS_IOSURFACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IIO_HAS_IOSURFACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IIO_HAS_IOSURFACE"
        }
      ],
      "role": "symbol",
      "title": "IIO_HAS_IOSURFACE",
      "type": "topic",
      "url": "/documentation/imageio/iio_has_iosurface"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_BUT_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_BUT_DEPRECATED",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_but_deprecated"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_BUT_DEPRECATED1"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED1",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_BUT_DEPRECATED1",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_but_deprecated1"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_BUT_DEPRECATED2"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED2",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_BUT_DEPRECATED2",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_but_deprecated2"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_BUT_DEPRECATED3"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED3",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_BUT_DEPRECATED3",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_but_deprecated3"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_BUT_DEPRECATED4"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED4",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_BUT_DEPRECATED4",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_but_deprecated4"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_BUT_DEPRECATED5"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED5",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_BUT_DEPRECATED5",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_but_deprecated5"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_STARTING"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_STARTING",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_starting"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_STARTING1"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING1",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_STARTING1",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_starting1"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_STARTING2"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING2",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_STARTING2",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_starting2"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_STARTING3"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING3",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_STARTING3",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_starting3"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_AVAILABLE_STARTING4"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING4",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_AVAILABLE_STARTING4",
      "type": "topic",
      "url": "/documentation/imageio/imageio_available_starting4"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_EXTERN",
      "type": "topic",
      "url": "/documentation/imageio/imageio_extern"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_EXTERN_C_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_EXTERN_C_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_EXTERN_C_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_EXTERN_C_BEGIN",
      "type": "topic",
      "url": "/documentation/imageio/imageio_extern_c_begin"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_EXTERN_C_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_EXTERN_C_END"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_EXTERN_C_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_EXTERN_C_END",
      "type": "topic",
      "url": "/documentation/imageio/imageio_extern_c_end"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_UNAVAILABLE_DESKTOP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_UNAVAILABLE_DESKTOP"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_UNAVAILABLE_DESKTOP",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_UNAVAILABLE_DESKTOP",
      "type": "topic",
      "url": "/documentation/imageio/imageio_unavailable_desktop"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_UNAVAILABLE_EMBEDDED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_UNAVAILABLE_EMBEDDED"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_UNAVAILABLE_EMBEDDED",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_UNAVAILABLE_EMBEDDED",
      "type": "topic",
      "url": "/documentation/imageio/imageio_unavailable_embedded"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-i-o-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-i-o-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image I/O Constants",
      "type": "topic",
      "url": "/documentation/imageio/image-i-o-constants"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image I/O Functions",
      "type": "topic",
      "url": "/documentation/imageio/image-i-o-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/image-i-o-constants",
        "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/IIO_HAS_IOSURFACE"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/GET_IMAGEIO_AVAIL_BUT_DEPR_MACRO",
                "doc://com.apple.imageio/documentation/ImageIO/GET_IMAGEIO_AVAIL_MACRO",
                "doc://com.apple.imageio/documentation/ImageIO/IIO_BRIDGED_TYPE",
                "doc://com.apple.imageio/documentation/ImageIO/IIO_HAS_IOSURFACE",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED1",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED2",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED3",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED4",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_BUT_DEPRECATED5",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING1",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING2",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING3",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_AVAILABLE_STARTING4",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_EXTERN",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_EXTERN_C_BEGIN",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_EXTERN_C_END",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_UNAVAILABLE_DESKTOP",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_UNAVAILABLE_EMBEDDED"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/image-i-o-constants",
                "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IIO_HAS_IOSURFACE/title",
          "value": "IIO_HAS_IOSURFACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IIO_HAS_IOSURFACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IIO_HAS_IOSURFACE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/image-i-o-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/image-i-o-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
