{
  "abstract": [
    {
      "text": "Properties that apply to the container in general, and not necessarily to an individual image in the container.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/image-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Image Properties"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Access these properties using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyProperties(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation": {
      "abstract": [
        {
          "text": "A value describing the intended display orientation for an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImagePropertyOrientation"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImagePropertyOrientation"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyProperties(_:_:)": {
      "abstract": [
        {
          "text": "Returns the properties of the image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyProperties(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyProperties"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCopyProperties(_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecopyproperties(_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for Exchangeable Image File Format (EXIF) data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EXIF Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/exif-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys for Global Positioning System (GPS) information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GPS Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/gps-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/individual-image-properties": {
      "abstract": [
        {
          "text": "Properties that apply to an individual image in an image source.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/individual-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Individual Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/individual-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for International Press Telecommunications Council (IPTC) data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPTC Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/iptc-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModel": {
      "abstract": [
        {
          "text": "The color model of the image, such as RGB, CMYK, grayscale, or Lab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyColorModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyColorModel"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyColorModel",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertycolormodel"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelCMYK": {
      "abstract": [
        {
          "text": "A Cyan Magenta Yellow Black (CMYK) color model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyColorModelCMYK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelCMYK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyColorModelCMYK"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyColorModelCMYK",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertycolormodelcmyk"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelGray": {
      "abstract": [
        {
          "text": "A grayscale color model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyColorModelGray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelGray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyColorModelGray"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyColorModelGray",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertycolormodelgray"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelLab": {
      "abstract": [
        {
          "text": "A Lab color model, where color values contain the amount of light and the amounts of four human-perceivable colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyColorModelLab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelLab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyColorModelLab"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyColorModelLab",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertycolormodellab"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelRGB": {
      "abstract": [
        {
          "text": "A Red Green Blue (RGB) color model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyColorModelRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyColorModelRGB"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyColorModelRGB",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertycolormodelrgb"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDPIHeight": {
      "abstract": [
        {
          "text": "The resolution, in dots per inch, in the y dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDPIHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDPIHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDPIHeight"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDPIHeight",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydpiheight"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDPIWidth": {
      "abstract": [
        {
          "text": "The resolution, in dots per inch, in the x dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDPIWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDPIWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDPIWidth"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDPIWidth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydpiwidth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDepth": {
      "abstract": [
        {
          "text": "The number of bits in the color sample of a pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDepth"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDepth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydepth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyFileContentsDictionary": {
      "abstract": [
        {
          "text": "A dictionary of properties related to the image’s on-disk file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyFileContentsDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyFileContentsDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyFileContentsDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyFileContentsDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyfilecontentsdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyFileSize": {
      "abstract": [
        {
          "text": "The size of the image file in bytes, if known.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyFileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyFileSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyFileSize"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyFileSize",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyfilesize"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHasAlpha": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image has an alpha channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHasAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHasAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHasAlpha"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyHasAlpha",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyhasalpha"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount": {
      "abstract": [
        {
          "text": "The number of images in the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImageCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImageCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyImageCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyimagecount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages": {
      "abstract": [
        {
          "text": "An array of dictionaries, each of which contains metadata for one of the images in the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImages"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImages"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyImages",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyimages"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image contains floating-point pixel samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsFloat"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIsFloat",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyisfloat"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image contains indexed pixel samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsIndexed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsIndexed"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIsIndexed",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyisindexed"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyNamedColorSpace": {
      "abstract": [
        {
          "text": "The name of the image’s color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyNamedColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyNamedColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyNamedColorSpace"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyNamedColorSpace",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertynamedcolorspace"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation": {
      "abstract": [
        {
          "text": "The intended display orientation of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyOrientation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyorientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelFormat": {
      "abstract": [
        {
          "text": "The format of the image’s individual pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPixelFormat",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypixelformat"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelHeight": {
      "abstract": [
        {
          "text": "The number of pixels along the y-axis of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPixelHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPixelHeight"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPixelHeight",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypixelheight"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelWidth": {
      "abstract": [
        {
          "text": "The number of pixels along the x-axis of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPixelWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPixelWidth"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPixelWidth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypixelwidth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage": {
      "abstract": [
        {
          "text": "The index of the primary image in the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPrimaryImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPrimaryImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPrimaryImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyprimaryimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyProfileName": {
      "abstract": [
        {
          "text": "The name of the optional International Color Consortium (ICC) profile embedded in the image, if known.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyProfileName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyProfileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyProfileName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyProfileName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyprofilename"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyThumbnailImages"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyThumbnailImages"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyThumbnailImages",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertythumbnailimages"
    },
    "doc://com.apple.imageio/documentation/ImageIO/webp-data": {
      "abstract": [
        {
          "text": "Metadata keys for WebP metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/webp-data",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebP Data",
      "type": "topic",
      "url": "/documentation/imageio/webp-data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common-Image-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/webp-data"
      ],
      "title": "Common Image Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyFileContentsDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "Container-File-Size",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyFileSize"
      ],
      "title": "Container File Size"
    },
    {
      "anchor": "Image-Information",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation",
        "doc://com.apple.imageio/documentation/ImageIO/individual-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation"
      ],
      "title": "Image Information"
    },
    {
      "anchor": "Pixel-Information",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelFormat",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelWidth",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelHeight",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDPIHeight",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDPIWidth",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDepth"
      ],
      "title": "Pixel Information"
    },
    {
      "anchor": "Color-Information",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHasAlpha",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyNamedColorSpace",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyProfileName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModel",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelRGB",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelCMYK",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelGray",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelLab"
      ],
      "title": "Color Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyFileContentsDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "Container-File-Size",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyFileSize"
              ],
              "title": "Container File Size"
            },
            {
              "anchor": "Image-Information",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation",
                "doc://com.apple.imageio/documentation/ImageIO/individual-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation"
              ],
              "title": "Image Information"
            },
            {
              "anchor": "Pixel-Information",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelFormat",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelWidth",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPixelHeight",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDPIHeight",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDPIWidth",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDepth"
              ],
              "title": "Pixel Information"
            },
            {
              "anchor": "Color-Information",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHasAlpha",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyNamedColorSpace",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyProfileName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModel",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelRGB",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelCMYK",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelGray",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyColorModelLab"
              ],
              "title": "Color Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common-Image-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/webp-data"
              ],
              "title": "Common Image Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyProperties(_:_:)/title",
          "value": "CGImageSourceCopyProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyProperties(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCopyProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyColorModelCMYK/title",
          "value": "kCGImagePropertyColorModelCMYK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyColorModelCMYK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyColorModelCMYK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPixelHeight/title",
          "value": "kCGImagePropertyPixelHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPixelHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPixelHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImageCount/title",
          "value": "kCGImagePropertyImageCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImageCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyImageCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyColorModel/title",
          "value": "kCGImagePropertyColorModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyColorModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyColorModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsFloat/title",
          "value": "kCGImagePropertyIsFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIsFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPrimaryImage/title",
          "value": "kCGImagePropertyPrimaryImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPrimaryImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPrimaryImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyFileSize/title",
          "value": "kCGImagePropertyFileSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyFileSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyFileSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyOrientation/title",
          "value": "kCGImagePropertyOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyFileContentsDictionary/title",
          "value": "kCGImagePropertyFileContentsDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyFileContentsDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyFileContentsDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyColorModelGray/title",
          "value": "kCGImagePropertyColorModelGray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyColorModelGray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyColorModelGray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDepth/title",
          "value": "kCGImagePropertyDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/title",
          "value": "CGImagePropertyOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPixelWidth/title",
          "value": "kCGImagePropertyPixelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPixelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPixelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyColorModelRGB/title",
          "value": "kCGImagePropertyColorModelRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyColorModelRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyColorModelRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyNamedColorSpace/title",
          "value": "kCGImagePropertyNamedColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyNamedColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyNamedColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDPIHeight/title",
          "value": "kCGImagePropertyDPIHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDPIHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDPIHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPixelFormat/title",
          "value": "kCGImagePropertyPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHasAlpha/title",
          "value": "kCGImagePropertyHasAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHasAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyHasAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyColorModelLab/title",
          "value": "kCGImagePropertyColorModelLab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyColorModelLab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyColorModelLab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDPIWidth/title",
          "value": "kCGImagePropertyDPIWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDPIWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDPIWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImages/title",
          "value": "kCGImagePropertyImages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyImages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyProfileName/title",
          "value": "kCGImagePropertyProfileName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyProfileName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyProfileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsIndexed/title",
          "value": "kCGImagePropertyIsIndexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsIndexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIsIndexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyThumbnailImages/title",
          "value": "kCGImagePropertyThumbnailImages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyThumbnailImages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyThumbnailImages"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
