{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/image-i-o-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Image I/O Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image I/O Functions",
      "type": "topic",
      "url": "/documentation/imageio/image-i-o-functions"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-i-o-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-i-o-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image I/O Macros",
      "type": "topic",
      "url": "/documentation/imageio/image-i-o-macros"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoColorSpace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataInfoColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataInfoColorSpace"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataInfoColorSpace",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatainfocolorspace"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeISOGainMap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeISOGainMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeISOGainMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeISOGainMap"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeISOGainMap",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypeisogainmap"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAVISDictionary": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAVISDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAVISDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAVISDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyAVISDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyavisdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageBaseline": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageBaseline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageBaseline"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageBaseline",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimagebaseline"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageDisparityAdjustment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageDisparityAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageDisparityAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageDisparityAdjustment"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageDisparityAdjustment",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimagedisparityadjustment"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexLeft"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIndexLeft",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageindexleft"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexMonoscopic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexMonoscopic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexMonoscopic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexMonoscopic"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIndexMonoscopic",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageindexmonoscopic"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexRight"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIndexRight",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageindexright"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsAlternateImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsAlternateImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsAlternateImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsAlternateImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIsAlternateImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageisalternateimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsLeftImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsLeftImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsLeftImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsLeftImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIsLeftImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageisleftimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsMonoscopicImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsMonoscopicImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsMonoscopicImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsMonoscopicImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIsMonoscopicImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageismonoscopicimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsRightImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsRightImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsRightImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsRightImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIsRightImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageisrightimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageStereoAggressors": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageStereoAggressors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageStereoAggressors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageStereoAggressors"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageStereoAggressors",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimagestereoaggressors"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImagesAlternate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImagesAlternate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImagesAlternate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImagesAlternate"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImagesAlternate",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimagesalternate"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupIndex"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupIndex",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupindex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupMonoscopicImageLocation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupMonoscopicImageLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupMonoscopicImageLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupMonoscopicImageLocation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupMonoscopicImageLocation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupmonoscopicimagelocation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupType"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupType",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygrouptype"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupTypeAlternate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupTypeAlternate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupTypeAlternate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupTypeAlternate"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupTypeAlternate",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygrouptypealternate"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupTypeStereoPair": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupTypeStereoPair"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupTypeStereoPair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupTypeStereoPair"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupTypeStereoPair",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygrouptypestereopair"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroups": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroups"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroups"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroups",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroups"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEIFDictionary": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEIFDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEIFDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHEIFDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyHEIFDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyheifdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImageIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImageIndex"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyImageIndex",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyimageindex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGPixelsAspectRatio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGPixelsAspectRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGPixelsAspectRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGPixelsAspectRatio"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGPixelsAspectRatio",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngpixelsaspectratio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTransparency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGTransparency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTransparency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGTransparency"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGTransparency",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngtransparency"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXPosition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFXPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFXPosition"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFXPosition",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffxposition"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYPosition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFYPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFYPosition"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFYPosition",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffyposition"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceDecodeRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceDecodeRequest"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceDecodeRequest",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcedecoderequest"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeRequestOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceDecodeRequestOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceDecodeRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceDecodeRequestOptions",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcedecoderequestoptions"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeToHDR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceDecodeToHDR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeToHDR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceDecodeToHDR"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceDecodeToHDR",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcedecodetohdr"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeToSDR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceDecodeToSDR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeToSDR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceDecodeToSDR"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceDecodeToSDR",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcedecodetosdr"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_CoordinateSystemID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOCameraExtrinsics_CoordinateSystemID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_CoordinateSystemID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOCameraExtrinsics_CoordinateSystemID"
        }
      ],
      "role": "symbol",
      "title": "kIIOCameraExtrinsics_CoordinateSystemID",
      "type": "topic",
      "url": "/documentation/imageio/kiiocameraextrinsics_coordinatesystemid"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_Position": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOCameraExtrinsics_Position"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_Position",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOCameraExtrinsics_Position"
        }
      ],
      "role": "symbol",
      "title": "kIIOCameraExtrinsics_Position",
      "type": "topic",
      "url": "/documentation/imageio/kiiocameraextrinsics_position"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_Rotation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOCameraExtrinsics_Rotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_Rotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOCameraExtrinsics_Rotation"
        }
      ],
      "role": "symbol",
      "title": "kIIOCameraExtrinsics_Rotation",
      "type": "topic",
      "url": "/documentation/imageio/kiiocameraextrinsics_rotation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModelType_GenericPinhole": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOCameraModelType_GenericPinhole"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModelType_GenericPinhole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOCameraModelType_GenericPinhole"
        }
      ],
      "role": "symbol",
      "title": "kIIOCameraModelType_GenericPinhole",
      "type": "topic",
      "url": "/documentation/imageio/kiiocameramodeltype_genericpinhole"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModelType_SimplifiedPinhole": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOCameraModelType_SimplifiedPinhole"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModelType_SimplifiedPinhole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOCameraModelType_SimplifiedPinhole"
        }
      ],
      "role": "symbol",
      "title": "kIIOCameraModelType_SimplifiedPinhole",
      "type": "topic",
      "url": "/documentation/imageio/kiiocameramodeltype_simplifiedpinhole"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModel_Intrinsics": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOCameraModel_Intrinsics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModel_Intrinsics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOCameraModel_Intrinsics"
        }
      ],
      "role": "symbol",
      "title": "kIIOCameraModel_Intrinsics",
      "type": "topic",
      "url": "/documentation/imageio/kiiocameramodel_intrinsics"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModel_ModelType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOCameraModel_ModelType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModel_ModelType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOCameraModel_ModelType"
        }
      ],
      "role": "symbol",
      "title": "kIIOCameraModel_ModelType",
      "type": "topic",
      "url": "/documentation/imageio/kiiocameramodel_modeltype"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOMetadata_CameraExtrinsicsKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOMetadata_CameraExtrinsicsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOMetadata_CameraExtrinsicsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOMetadata_CameraExtrinsicsKey"
        }
      ],
      "role": "symbol",
      "title": "kIIOMetadata_CameraExtrinsicsKey",
      "type": "topic",
      "url": "/documentation/imageio/kiiometadata_cameraextrinsicskey"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOMetadata_CameraModelKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOMetadata_CameraModelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOMetadata_CameraModelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOMetadata_CameraModelKey"
        }
      ],
      "role": "symbol",
      "title": "kIIOMetadata_CameraModelKey",
      "type": "topic",
      "url": "/documentation/imageio/kiiometadata_cameramodelkey"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Center": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOMonoscopicImageLocation_Center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOMonoscopicImageLocation_Center"
        }
      ],
      "role": "symbol",
      "title": "kIIOMonoscopicImageLocation_Center",
      "type": "topic",
      "url": "/documentation/imageio/kiiomonoscopicimagelocation_center"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Left": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOMonoscopicImageLocation_Left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOMonoscopicImageLocation_Left"
        }
      ],
      "role": "symbol",
      "title": "kIIOMonoscopicImageLocation_Left",
      "type": "topic",
      "url": "/documentation/imageio/kiiomonoscopicimagelocation_left"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Right": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOMonoscopicImageLocation_Right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOMonoscopicImageLocation_Right"
        }
      ],
      "role": "symbol",
      "title": "kIIOMonoscopicImageLocation_Right",
      "type": "topic",
      "url": "/documentation/imageio/kiiomonoscopicimagelocation_right"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOMonoscopicImageLocation_Unspecified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOMonoscopicImageLocation_Unspecified"
        }
      ],
      "role": "symbol",
      "title": "kIIOMonoscopicImageLocation_Unspecified",
      "type": "topic",
      "url": "/documentation/imageio/kiiomonoscopicimagelocation_unspecified"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_Severity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOStereoAggressors_Severity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_Severity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOStereoAggressors_Severity"
        }
      ],
      "role": "symbol",
      "title": "kIIOStereoAggressors_Severity",
      "type": "topic",
      "url": "/documentation/imageio/kiiostereoaggressors_severity"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_SubTypeURI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOStereoAggressors_SubTypeURI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_SubTypeURI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOStereoAggressors_SubTypeURI"
        }
      ],
      "role": "symbol",
      "title": "kIIOStereoAggressors_SubTypeURI",
      "type": "topic",
      "url": "/documentation/imageio/kiiostereoaggressors_subtypeuri"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_Type": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIIOStereoAggressors_Type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIIOStereoAggressors_Type"
        }
      ],
      "role": "symbol",
      "title": "kIIOStereoAggressors_Type",
      "type": "topic",
      "url": "/documentation/imageio/kiiostereoaggressors_type"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions",
        "doc://com.apple.imageio/documentation/ImageIO/image-i-o-macros"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoColorSpace",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeISOGainMap",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupMonoscopicImageLocation",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAVISDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageBaseline",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageDisparityAdjustment",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexLeft",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexRight",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexMonoscopic",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsAlternateImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsLeftImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsRightImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsMonoscopicImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageStereoAggressors",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImagesAlternate",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupIndex",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupType",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupTypeAlternate",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupTypeStereoPair",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroups",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEIFDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageIndex",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGPixelsAspectRatio",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTransparency",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXPosition",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYPosition",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeRequest",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeRequestOptions",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeToHDR",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeToSDR",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_CoordinateSystemID",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_Position",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_Rotation",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModelType_GenericPinhole",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModelType_SimplifiedPinhole",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModel_Intrinsics",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModel_ModelType",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOMetadata_CameraExtrinsicsKey",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOMetadata_CameraModelKey",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Center",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Left",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Right",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Unspecified",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_Severity",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_SubTypeURI",
        "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_Type"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoColorSpace",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeISOGainMap",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupMonoscopicImageLocation",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAVISDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageBaseline",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageDisparityAdjustment",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexLeft",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexRight",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexMonoscopic",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsAlternateImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsLeftImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsRightImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsMonoscopicImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageStereoAggressors",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImagesAlternate",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupIndex",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupType",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupTypeAlternate",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupTypeStereoPair",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroups",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHEIFDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageIndex",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGPixelsAspectRatio",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTransparency",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXPosition",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYPosition",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeRequest",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeRequestOptions",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeToHDR",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceDecodeToSDR",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_CoordinateSystemID",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_Position",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraExtrinsics_Rotation",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModelType_GenericPinhole",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModelType_SimplifiedPinhole",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModel_Intrinsics",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOCameraModel_ModelType",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOMetadata_CameraExtrinsicsKey",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOMetadata_CameraModelKey",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Center",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Left",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Right",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOMonoscopicImageLocation_Unspecified",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_Severity",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_SubTypeURI",
                "doc://com.apple.imageio/documentation/ImageIO/kIIOStereoAggressors_Type"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions",
                "doc://com.apple.imageio/documentation/ImageIO/image-i-o-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataInfoColorSpace/title",
          "value": "kCGImageAuxiliaryDataInfoColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataInfoColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataInfoColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOStereoAggressors_SubTypeURI/title",
          "value": "kIIOStereoAggressors_SubTypeURI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOStereoAggressors_SubTypeURI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOStereoAggressors_SubTypeURI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAVISDictionary/title",
          "value": "kCGImagePropertyAVISDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAVISDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyAVISDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGTransparency/title",
          "value": "kCGImagePropertyPNGTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGTransparency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraModelType_GenericPinhole/title",
          "value": "kIIOCameraModelType_GenericPinhole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraModelType_GenericPinhole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOCameraModelType_GenericPinhole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceDecodeToHDR/title",
          "value": "kCGImageSourceDecodeToHDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceDecodeToHDR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceDecodeToHDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupMonoscopicImageLocation/title",
          "value": "kCGImagePropertyGroupMonoscopicImageLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupMonoscopicImageLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupMonoscopicImageLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMonoscopicImageLocation_Left/title",
          "value": "kIIOMonoscopicImageLocation_Left"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMonoscopicImageLocation_Left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOMonoscopicImageLocation_Left"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraExtrinsics_Rotation/title",
          "value": "kIIOCameraExtrinsics_Rotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraExtrinsics_Rotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOCameraExtrinsics_Rotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsLeftImage/title",
          "value": "kCGImagePropertyGroupImageIsLeftImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsLeftImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIsLeftImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroups/title",
          "value": "kCGImagePropertyGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFXPosition/title",
          "value": "kCGImagePropertyTIFFXPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFXPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFXPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMonoscopicImageLocation_Right/title",
          "value": "kIIOMonoscopicImageLocation_Right"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMonoscopicImageLocation_Right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOMonoscopicImageLocation_Right"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsAlternateImage/title",
          "value": "kCGImagePropertyGroupImageIsAlternateImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsAlternateImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIsAlternateImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupType/title",
          "value": "kCGImagePropertyGroupType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOStereoAggressors_Severity/title",
          "value": "kIIOStereoAggressors_Severity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOStereoAggressors_Severity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOStereoAggressors_Severity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageStereoAggressors/title",
          "value": "kCGImagePropertyGroupImageStereoAggressors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageStereoAggressors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageStereoAggressors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageBaseline/title",
          "value": "kCGImagePropertyGroupImageBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMonoscopicImageLocation_Center/title",
          "value": "kIIOMonoscopicImageLocation_Center"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMonoscopicImageLocation_Center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOMonoscopicImageLocation_Center"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexRight/title",
          "value": "kCGImagePropertyGroupImageIndexRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIndexRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEIFDictionary/title",
          "value": "kCGImagePropertyHEIFDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHEIFDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyHEIFDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceDecodeToSDR/title",
          "value": "kCGImageSourceDecodeToSDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceDecodeToSDR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceDecodeToSDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsRightImage/title",
          "value": "kCGImagePropertyGroupImageIsRightImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsRightImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIsRightImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupTypeStereoPair/title",
          "value": "kCGImagePropertyGroupTypeStereoPair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupTypeStereoPair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupTypeStereoPair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMonoscopicImageLocation_Unspecified/title",
          "value": "kIIOMonoscopicImageLocation_Unspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMonoscopicImageLocation_Unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOMonoscopicImageLocation_Unspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOStereoAggressors_Type/title",
          "value": "kIIOStereoAggressors_Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOStereoAggressors_Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOStereoAggressors_Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexMonoscopic/title",
          "value": "kCGImagePropertyGroupImageIndexMonoscopic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexMonoscopic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIndexMonoscopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImageIndex/title",
          "value": "kCGImagePropertyImageIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImageIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyImageIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMetadata_CameraExtrinsicsKey/title",
          "value": "kIIOMetadata_CameraExtrinsicsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMetadata_CameraExtrinsicsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOMetadata_CameraExtrinsicsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGPixelsAspectRatio/title",
          "value": "kCGImagePropertyPNGPixelsAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGPixelsAspectRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGPixelsAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraExtrinsics_CoordinateSystemID/title",
          "value": "kIIOCameraExtrinsics_CoordinateSystemID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraExtrinsics_CoordinateSystemID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOCameraExtrinsics_CoordinateSystemID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceDecodeRequestOptions/title",
          "value": "kCGImageSourceDecodeRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceDecodeRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceDecodeRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupTypeAlternate/title",
          "value": "kCGImagePropertyGroupTypeAlternate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupTypeAlternate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupTypeAlternate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraExtrinsics_Position/title",
          "value": "kIIOCameraExtrinsics_Position"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraExtrinsics_Position/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOCameraExtrinsics_Position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeISOGainMap/title",
          "value": "kCGImageAuxiliaryDataTypeISOGainMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeISOGainMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeISOGainMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImagesAlternate/title",
          "value": "kCGImagePropertyGroupImagesAlternate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImagesAlternate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImagesAlternate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraModel_Intrinsics/title",
          "value": "kIIOCameraModel_Intrinsics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraModel_Intrinsics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOCameraModel_Intrinsics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraModel_ModelType/title",
          "value": "kIIOCameraModel_ModelType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraModel_ModelType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOCameraModel_ModelType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsMonoscopicImage/title",
          "value": "kCGImagePropertyGroupImageIsMonoscopicImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsMonoscopicImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIsMonoscopicImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFYPosition/title",
          "value": "kCGImagePropertyTIFFYPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFYPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFYPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMetadata_CameraModelKey/title",
          "value": "kIIOMetadata_CameraModelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOMetadata_CameraModelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOMetadata_CameraModelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageDisparityAdjustment/title",
          "value": "kCGImagePropertyGroupImageDisparityAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageDisparityAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageDisparityAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexLeft/title",
          "value": "kCGImagePropertyGroupImageIndexLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIndexLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceDecodeRequest/title",
          "value": "kCGImageSourceDecodeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceDecodeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceDecodeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupIndex/title",
          "value": "kCGImagePropertyGroupIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraModelType_SimplifiedPinhole/title",
          "value": "kIIOCameraModelType_SimplifiedPinhole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kIIOCameraModelType_SimplifiedPinhole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIIOCameraModelType_SimplifiedPinhole"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/image-i-o-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/image-i-o-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
