{
  "abstract": [
    {
      "text": "All PNG filters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_ALL_FILTERS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@IMAGEIO_PNG_ALL_FILTERS",
    "fragments": [
      {
        "kind": "identifier",
        "text": "IMAGEIO_PNG_ALL_FILTERS"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IMAGEIO_PNG_ALL_FILTERS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "IMAGEIO_PNG_ALL_FILTERS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_ALL_FILTERS"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_ALL_FILTERS": {
      "abstract": [
        {
          "text": "All PNG filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_ALL_FILTERS"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_ALL_FILTERS",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_PNG_ALL_FILTERS",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_all_filters"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_AVG": {
      "abstract": [
        {
          "text": "A filter in which each byte is replaced with the difference between it and the average of the bytes above it and to its left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_AVG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_AVG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_AVG"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_FILTER_AVG",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_filter_avg"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_NONE": {
      "abstract": [
        {
          "text": "A filter in which each byte is unchanged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_NONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_NONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_NONE"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_FILTER_NONE",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_filter_none"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_PAETH": {
      "abstract": [
        {
          "text": "A filter in which each byte is replaced with the difference between it and the Paeth predictor of the bytes to its left, above, and upper left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_PAETH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_PAETH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_PAETH"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_FILTER_PAETH",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_filter_paeth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_SUB": {
      "abstract": [
        {
          "text": "A filter in which each byte is replaced with the difference between it and the corresponding byte to its left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_SUB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_SUB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_SUB"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_FILTER_SUB",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_filter_sub"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_UP": {
      "abstract": [
        {
          "text": "A filter in which each byte is replaced with the difference between it and the byte above it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_UP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_UP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_UP"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_FILTER_UP",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_filter_up"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_NO_FILTERS": {
      "abstract": [
        {
          "text": "No PNG filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_NO_FILTERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_NO_FILTERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_NO_FILTERS"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_NO_FILTERS",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_no_filters"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCompressionFilter": {
      "abstract": [
        {
          "text": "The PNG filter to apply prior to compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCompressionFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCompressionFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCompressionFilter"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGCompressionFilter",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngcompressionfilter"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pre-Compression-Filters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCompressionFilter",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_NO_FILTERS",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_NONE",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_SUB",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_UP",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_AVG",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_PAETH"
      ],
      "title": "Pre-Compression Filters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_NONE/title",
          "value": "IMAGEIO_PNG_FILTER_NONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_NONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_FILTER_NONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCompressionFilter/title",
          "value": "kCGImagePropertyPNGCompressionFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCompressionFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGCompressionFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_UP/title",
          "value": "IMAGEIO_PNG_FILTER_UP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_UP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_FILTER_UP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_NO_FILTERS/title",
          "value": "IMAGEIO_PNG_NO_FILTERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_NO_FILTERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_NO_FILTERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_PAETH/title",
          "value": "IMAGEIO_PNG_FILTER_PAETH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_PAETH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_FILTER_PAETH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_AVG/title",
          "value": "IMAGEIO_PNG_FILTER_AVG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_AVG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_FILTER_AVG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_SUB/title",
          "value": "IMAGEIO_PNG_FILTER_SUB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_SUB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_FILTER_SUB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/imageio_png_all_filters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
