{
  "abstract": [
    {
      "text": "Properties that apply to an individual image in an image source.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO",
        "doc://com.apple.imageio/documentation/ImageIO/image-properties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/individual-image-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Individual Image Properties"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Access these properties using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyPropertiesAtIndex(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation": {
      "abstract": [
        {
          "text": "A value describing the intended display orientation for an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImagePropertyOrientation"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImagePropertyOrientation"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns auxiliary data, such as mattes and depth information, that accompany the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyAuxiliaryDataInfoAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyAuxiliaryDataInfoAtIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecopyauxiliarydatainfoatindex(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyPropertiesAtIndex(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the properties of the image at a specified location in an image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyPropertiesAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyPropertiesAtIndex(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyPropertiesAtIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCopyPropertiesAtIndex(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecopypropertiesatindex(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-properties": {
      "abstract": [
        {
          "text": "Properties that apply to the container in general, and not necessarily to an individual image in the container.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoData": {
      "abstract": [
        {
          "text": "The auxiliary data for the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataInfoData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataInfoData"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataInfoData",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatainfodata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoDataDescription": {
      "abstract": [
        {
          "text": "A dictionary of keys that describe the auxiliary data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataInfoDataDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoDataDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataInfoDataDescription"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataInfoDataDescription",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatainfodatadescription"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoMetadata": {
      "abstract": [
        {
          "text": "The metadata for any auxiliary data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataInfoMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataInfoMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataInfoMetadata",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatainfometadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDepth": {
      "abstract": [
        {
          "text": "The type for depth map information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeDepth"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeDepth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypedepth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDisparity": {
      "abstract": [
        {
          "text": "The type for image disparity information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeDisparity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDisparity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeDisparity"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeDisparity",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypedisparity"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeHDRGainMap": {
      "abstract": [
        {
          "text": "The type for High Dynamic Range (HDR) gain map information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeHDRGainMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeHDRGainMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeHDRGainMap"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeHDRGainMap",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypehdrgainmap"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypePortraitEffectsMatte": {
      "abstract": [
        {
          "text": "The type for portrait effects matte information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypePortraitEffectsMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypePortraitEffectsMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypeportraiteffectsmatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte": {
      "abstract": [
        {
          "text": "The type for glasses matte informaton.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypesemanticsegmentationglassesmatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte": {
      "abstract": [
        {
          "text": "The type for hair matte information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypesemanticsegmentationhairmatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte": {
      "abstract": [
        {
          "text": "The type for skin matte informaton.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypesemanticsegmentationskinmatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte": {
      "abstract": [
        {
          "text": "The type for sky matte information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypesemanticsegmentationskymatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte": {
      "abstract": [
        {
          "text": "The type for teeth matte information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypesemanticsegmentationteethmatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAuxiliaryData": {
      "abstract": [
        {
          "text": "An array of dictionaries that contain auxiliary data for the images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAuxiliaryData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAuxiliaryData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAuxiliaryData"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyAuxiliaryData",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyauxiliarydata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAuxiliaryDataType": {
      "abstract": [
        {
          "text": "The type of the auxiliary data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAuxiliaryDataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAuxiliaryDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAuxiliaryDataType"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyAuxiliaryDataType",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyauxiliarydatatype"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyBytesPerRow": {
      "abstract": [
        {
          "text": "The total number of bytes in each row of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyBytesPerRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyBytesPerRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyBytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyBytesPerRow",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertybytesperrow"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHeight": {
      "abstract": [
        {
          "text": "The height of the image, in the image’s coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyHeight"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyHeight",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyheight"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount": {
      "abstract": [
        {
          "text": "The number of images in the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImageCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImageCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyImageCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyimagecount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages": {
      "abstract": [
        {
          "text": "An array of dictionaries, each of which contains metadata for one of the images in the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImages"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImages"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyImages",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyimages"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image contains floating-point pixel samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsFloat"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIsFloat",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyisfloat"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image contains indexed pixel samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsIndexed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsIndexed"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIsIndexed",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyisindexed"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOpenEXRAspectRatio": {
      "abstract": [
        {
          "text": "The aspect ratio of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOpenEXRAspectRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOpenEXRAspectRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOpenEXRAspectRatio"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyOpenEXRAspectRatio",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyopenexraspectratio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOpenEXRDictionary": {
      "abstract": [
        {
          "text": "A dictionary of properties specific to the OpenEXR metadata standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOpenEXRDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOpenEXRDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOpenEXRDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyOpenEXRDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyopenexrdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation": {
      "abstract": [
        {
          "text": "The intended display orientation of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyOrientation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyorientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage": {
      "abstract": [
        {
          "text": "The index of the primary image in the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPrimaryImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPrimaryImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPrimaryImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyprimaryimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyThumbnailImages"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyThumbnailImages"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyThumbnailImages",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertythumbnailimages"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWidth": {
      "abstract": [
        {
          "text": "The width of the image, in the image’s coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWidth"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyWidth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertywidth"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation"
      ],
      "title": "Image Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Image-Size",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHeight",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWidth",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyBytesPerRow"
      ],
      "title": "Image Size"
    },
    {
      "anchor": "Auxiliary-Data-Types",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDepth",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDisparity",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeHDRGainMap",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypePortraitEffectsMatte",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
      ],
      "title": "Auxiliary Data Types"
    },
    {
      "anchor": "Auxiliary-Image-Data",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAuxiliaryData",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAuxiliaryDataType",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoData",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoDataDescription",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoMetadata"
      ],
      "title": "Auxiliary Image Data"
    },
    {
      "anchor": "Open-EXR-Properties",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOpenEXRDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOpenEXRAspectRatio"
      ],
      "title": "Open EXR Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Image-Size",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyHeight",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWidth",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyBytesPerRow"
              ],
              "title": "Image Size"
            },
            {
              "anchor": "Auxiliary-Data-Types",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDepth",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDisparity",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeHDRGainMap",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypePortraitEffectsMatte",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
              ],
              "title": "Auxiliary Data Types"
            },
            {
              "anchor": "Auxiliary-Image-Data",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAuxiliaryData",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAuxiliaryDataType",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoData",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoDataDescription",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoMetadata"
              ],
              "title": "Auxiliary Image Data"
            },
            {
              "anchor": "Open-EXR-Properties",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOpenEXRDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOpenEXRAspectRatio"
              ],
              "title": "Open EXR Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation"
              ],
              "title": "Image Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyOrientation/title",
          "value": "kCGImagePropertyOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyOpenEXRDictionary/title",
          "value": "kCGImagePropertyOpenEXRDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyOpenEXRDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOpenEXRDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte/title",
          "value": "kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsIndexed/title",
          "value": "kCGImagePropertyIsIndexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsIndexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIsIndexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataInfoMetadata/title",
          "value": "kCGImageAuxiliaryDataInfoMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataInfoMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataInfoMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWidth/title",
          "value": "kCGImagePropertyWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeDepth/title",
          "value": "kCGImageAuxiliaryDataTypeDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)/title",
          "value": "CGImageSourceCopyAuxiliaryDataInfoAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCopyAuxiliaryDataInfoAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte/title",
          "value": "kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyOpenEXRAspectRatio/title",
          "value": "kCGImagePropertyOpenEXRAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyOpenEXRAspectRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOpenEXRAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte/title",
          "value": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPrimaryImage/title",
          "value": "kCGImagePropertyPrimaryImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPrimaryImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPrimaryImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsFloat/title",
          "value": "kCGImagePropertyIsFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIsFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyThumbnailImages/title",
          "value": "kCGImagePropertyThumbnailImages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyThumbnailImages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyThumbnailImages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyPropertiesAtIndex(_:_:_:)/title",
          "value": "CGImageSourceCopyPropertiesAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyPropertiesAtIndex(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCopyPropertiesAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypePortraitEffectsMatte/title",
          "value": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypePortraitEffectsMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAuxiliaryDataType/title",
          "value": "kCGImagePropertyAuxiliaryDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAuxiliaryDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyAuxiliaryDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHeight/title",
          "value": "kCGImagePropertyHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte/title",
          "value": "kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeHDRGainMap/title",
          "value": "kCGImageAuxiliaryDataTypeHDRGainMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeHDRGainMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeHDRGainMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeDisparity/title",
          "value": "kCGImageAuxiliaryDataTypeDisparity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeDisparity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeDisparity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/title",
          "value": "CGImagePropertyOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataInfoDataDescription/title",
          "value": "kCGImageAuxiliaryDataInfoDataDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataInfoDataDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataInfoDataDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImages/title",
          "value": "kCGImagePropertyImages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyImages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAuxiliaryData/title",
          "value": "kCGImagePropertyAuxiliaryData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAuxiliaryData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyAuxiliaryData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyBytesPerRow/title",
          "value": "kCGImagePropertyBytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyBytesPerRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyBytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImageCount/title",
          "value": "kCGImagePropertyImageCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImageCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyImageCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte/title",
          "value": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataInfoData/title",
          "value": "kCGImageAuxiliaryDataInfoData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataInfoData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataInfoData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/individual-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/individual-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
