{
  "abstract": [
    {
      "text": "Metadata keys for the JPEG File Interchange Format (JFIF).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "JFIF Image Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Adobe Photoshop image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "8BIM Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/8bim-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Camera Image File Format (CIFF) image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/ciff-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Digital Negative (DNG) archival format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/dng-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Graphics Interchange Format (GIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/gif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the High Efficiency Image Container (HEIC) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEIC Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/heic-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the JPEG File Interchange Format (JFIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "JFIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/jfif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFDensityUnit": {
      "abstract": [
        {
          "text": "The units for the x and y density fields.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFDensityUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFDensityUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFDensityUnit"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyJFIFDensityUnit",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyjfifdensityunit"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that uses JPEG File Interchange Format (JFIF). See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyJFIFDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyjfifdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFIsProgressive": {
      "abstract": [
        {
          "text": "Whether there are versions of the image of increasing quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFIsProgressive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFIsProgressive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFIsProgressive"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyJFIFIsProgressive",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyjfifisprogressive"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFVersion": {
      "abstract": [
        {
          "text": "The version of JFIF.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFVersion"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyJFIFVersion",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyjfifversion"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFXDensity": {
      "abstract": [
        {
          "text": "The x pixel density.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFXDensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFXDensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFXDensity"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyJFIFXDensity",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyjfifxdensity"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFYDensity": {
      "abstract": [
        {
          "text": "The y pixel density.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFYDensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFYDensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyJFIFYDensity"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyJFIFYDensity",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyjfifydensity"
    },
    "doc://com.apple.imageio/documentation/ImageIO/png-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Portable Network Graphics (PNG) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/png-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Truevision Graphics Adapter (TGA) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TGA Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tga-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Tagged Image File Format (TIFF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tiff-image-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Specific-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
      ],
      "title": "Format-Specific Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "Quality-Information",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFXDensity",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFYDensity",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFDensityUnit",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFIsProgressive"
      ],
      "title": "Quality Information"
    },
    {
      "anchor": "Version-Information",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFVersion"
      ],
      "title": "Version Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "Quality-Information",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFXDensity",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFYDensity",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFDensityUnit",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFIsProgressive"
              ],
              "title": "Quality Information"
            },
            {
              "anchor": "Version-Information",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyJFIFVersion"
              ],
              "title": "Version Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Specific-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
              ],
              "title": "Format-Specific Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFVersion/title",
          "value": "kCGImagePropertyJFIFVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyJFIFVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFYDensity/title",
          "value": "kCGImagePropertyJFIFYDensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFYDensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyJFIFYDensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFDictionary/title",
          "value": "kCGImagePropertyJFIFDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyJFIFDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFIsProgressive/title",
          "value": "kCGImagePropertyJFIFIsProgressive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFIsProgressive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyJFIFIsProgressive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFXDensity/title",
          "value": "kCGImagePropertyJFIFXDensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFXDensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyJFIFXDensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFDensityUnit/title",
          "value": "kCGImagePropertyJFIFDensityUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyJFIFDensityUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyJFIFDensityUnit"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/jfif-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/jfif-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
