{
  "abstract": [
    {
      "text": "A string that contains image comments.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGComment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyPNGComment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyPNGComment"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyPNGComment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyPNGComment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGComment"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGAuthor": {
      "abstract": [
        {
          "text": "A string that identifies the author of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGAuthor"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGAuthor",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngauthor"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGComment": {
      "abstract": [
        {
          "text": "A string that contains image comments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGComment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGComment"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGComment",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngcomment"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCopyright": {
      "abstract": [
        {
          "text": "A string that identifies the copyright of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCopyright"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGCopyright",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngcopyright"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCreationTime": {
      "abstract": [
        {
          "text": "A string that identifies the date and time the image was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCreationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCreationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCreationTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGCreationTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngcreationtime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDescription": {
      "abstract": [
        {
          "text": "A string that describes the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGDescription"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGDescription",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngdescription"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDisclaimer": {
      "abstract": [
        {
          "text": "A disclaimer string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGDisclaimer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDisclaimer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGDisclaimer"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGDisclaimer",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngdisclaimer"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGModificationTime": {
      "abstract": [
        {
          "text": "A string that identifies the last date and time the image was modified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGModificationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGModificationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGModificationTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGModificationTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngmodificationtime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSoftware": {
      "abstract": [
        {
          "text": "A string that identifies the software used to create the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGSoftware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSoftware",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGSoftware"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGSoftware",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngsoftware"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTitle": {
      "abstract": [
        {
          "text": "A string that holds the image’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGTitle"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGTitle",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngtitle"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGWarning": {
      "abstract": [
        {
          "text": "A warning string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGWarning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGWarning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGWarning"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGWarning",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngwarning"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Descriptive-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTitle",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDescription",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDisclaimer",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGWarning",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGAuthor",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCopyright",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCreationTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGModificationTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSoftware"
      ],
      "title": "Descriptive Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyPNGComment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Descriptive-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTitle",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDescription",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDisclaimer",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGWarning",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGAuthor",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCopyright",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCreationTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGModificationTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSoftware"
              ],
              "title": "Descriptive Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyPNGComment"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGSoftware/title",
          "value": "kCGImagePropertyPNGSoftware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGSoftware/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGSoftware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCopyright/title",
          "value": "kCGImagePropertyPNGCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGModificationTime/title",
          "value": "kCGImagePropertyPNGModificationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGModificationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGModificationTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGComment/title",
          "value": "kCGImagePropertyPNGComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGTitle/title",
          "value": "kCGImagePropertyPNGTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGDescription/title",
          "value": "kCGImagePropertyPNGDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCreationTime/title",
          "value": "kCGImagePropertyPNGCreationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCreationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGCreationTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGAuthor/title",
          "value": "kCGImagePropertyPNGAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGWarning/title",
          "value": "kCGImagePropertyPNGWarning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGWarning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGWarning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGDisclaimer/title",
          "value": "kCGImagePropertyPNGDisclaimer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGDisclaimer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGDisclaimer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertypngcomment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertypngcomment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
