{
  "abstract": [
    {
      "text": "An editorial update.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCEditorialUpdate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyIPTCEditorialUpdate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyIPTCEditorialUpdate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyIPTCEditorialUpdate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyIPTCEditorialUpdate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCEditorialUpdate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCCategory": {
      "abstract": [
        {
          "text": "The category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCCategory"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCCategory",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptccategory"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCContentLocationCode": {
      "abstract": [
        {
          "text": "The content location code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCContentLocationCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCContentLocationCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCContentLocationCode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCContentLocationCode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptccontentlocationcode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCContentLocationName": {
      "abstract": [
        {
          "text": "The content location name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCContentLocationName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCContentLocationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCContentLocationName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCContentLocationName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptccontentlocationname"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCEditStatus": {
      "abstract": [
        {
          "text": "The edit status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCEditStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCEditStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCEditStatus"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCEditStatus",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptceditstatus"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCEditorialUpdate": {
      "abstract": [
        {
          "text": "An editorial update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCEditorialUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCEditorialUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCEditorialUpdate"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCEditorialUpdate",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptceditorialupdate"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCFixtureIdentifier": {
      "abstract": [
        {
          "text": "A fixture identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCFixtureIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCFixtureIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCFixtureIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCFixtureIdentifier",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcfixtureidentifier"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCKeywords": {
      "abstract": [
        {
          "text": "Keywords relevant to the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCKeywords"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCKeywords",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCKeywords"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCKeywords",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptckeywords"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCObjectCycle": {
      "abstract": [
        {
          "text": "The editorial cycle (morning, evening, or both) of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCObjectCycle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCObjectCycle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCObjectCycle"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCObjectCycle",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcobjectcycle"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSubjectReference": {
      "abstract": [
        {
          "text": "The subject.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCSubjectReference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSubjectReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCSubjectReference"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCSubjectReference",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcsubjectreference"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSupplementalCategory": {
      "abstract": [
        {
          "text": "A supplemental category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCSupplementalCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSupplementalCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCSupplementalCategory"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCSupplementalCategory",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcsupplementalcategory"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCUrgency": {
      "abstract": [
        {
          "text": "The urgency level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCUrgency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCUrgency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCUrgency"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCUrgency",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcurgency"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Categorization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCUrgency",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSubjectReference",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCCategory",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSupplementalCategory",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCFixtureIdentifier",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCKeywords",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCContentLocationCode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCContentLocationName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCEditStatus",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCObjectCycle"
      ],
      "title": "Image Categorization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyIPTCEditorialUpdate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCEditorialUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-Categorization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCUrgency",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSubjectReference",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCCategory",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSupplementalCategory",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCFixtureIdentifier",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCKeywords",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCContentLocationCode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCContentLocationName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCEditStatus",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCObjectCycle"
              ],
              "title": "Image Categorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyIPTCEditorialUpdate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCEditStatus/title",
          "value": "kCGImagePropertyIPTCEditStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCEditStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCEditStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCContentLocationName/title",
          "value": "kCGImagePropertyIPTCContentLocationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCContentLocationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCContentLocationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCKeywords/title",
          "value": "kCGImagePropertyIPTCKeywords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCKeywords/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCKeywords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCSubjectReference/title",
          "value": "kCGImagePropertyIPTCSubjectReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCSubjectReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCSubjectReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCContentLocationCode/title",
          "value": "kCGImagePropertyIPTCContentLocationCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCContentLocationCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCContentLocationCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCEditorialUpdate/title",
          "value": "kCGImagePropertyIPTCEditorialUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCEditorialUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCEditorialUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCObjectCycle/title",
          "value": "kCGImagePropertyIPTCObjectCycle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCObjectCycle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCObjectCycle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCUrgency/title",
          "value": "kCGImagePropertyIPTCUrgency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCUrgency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCUrgency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCCategory/title",
          "value": "kCGImagePropertyIPTCCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCSupplementalCategory/title",
          "value": "kCGImagePropertyIPTCSupplementalCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCSupplementalCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCSupplementalCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCFixtureIdentifier/title",
          "value": "kCGImagePropertyIPTCFixtureIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCFixtureIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCFixtureIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyiptceditorialupdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyiptceditorialupdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
