{
  "abstract": [
    {
      "text": "The image adjustment setting.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonImageAdjustment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyMakerNikonImageAdjustment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyMakerNikonImageAdjustment"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyMakerNikonImageAdjustment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyMakerNikonImageAdjustment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonImageAdjustment"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonColorMode": {
      "abstract": [
        {
          "text": "The color mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonColorMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonColorMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonColorMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonColorMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikoncolormode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDigitalZoom": {
      "abstract": [
        {
          "text": "The digital zoom setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonDigitalZoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDigitalZoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonDigitalZoom"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonDigitalZoom",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikondigitalzoom"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashExposureComp": {
      "abstract": [
        {
          "text": "The flash exposure compensation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFlashExposureComp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashExposureComp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFlashExposureComp"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonFlashExposureComp",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonflashexposurecomp"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashSetting": {
      "abstract": [
        {
          "text": "The flash setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFlashSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFlashSetting"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonFlashSetting",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonflashsetting"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusDistance": {
      "abstract": [
        {
          "text": "The focus distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFocusDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFocusDistance"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonFocusDistance",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonfocusdistance"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusMode": {
      "abstract": [
        {
          "text": "The focus mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFocusMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFocusMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonFocusMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonfocusmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSelection": {
      "abstract": [
        {
          "text": "The ISO selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonISOSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonISOSelection"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonISOSelection",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonisoselection"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSetting": {
      "abstract": [
        {
          "text": "The ISO setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonISOSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonISOSetting"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonISOSetting",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonisosetting"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonImageAdjustment": {
      "abstract": [
        {
          "text": "The image adjustment setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonImageAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonImageAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonImageAdjustment"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonImageAdjustment",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonimageadjustment"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonQuality": {
      "abstract": [
        {
          "text": "The quality setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonQuality"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonQuality",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonquality"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonSharpenMode": {
      "abstract": [
        {
          "text": "The sharpening mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonSharpenMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonSharpenMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonSharpenMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonSharpenMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonsharpenmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShootingMode": {
      "abstract": [
        {
          "text": "The shooting mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonShootingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShootingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonShootingMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonShootingMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonshootingmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShutterCount": {
      "abstract": [
        {
          "text": "The number of times the shutter has been actuated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonShutterCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShutterCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonShutterCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonShutterCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonshuttercount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonWhiteBalanceMode": {
      "abstract": [
        {
          "text": "The white balance mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonWhiteBalanceMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonWhiteBalanceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonWhiteBalanceMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonWhiteBalanceMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonwhitebalancemode"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Program-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSetting",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSelection",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonColorMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonQuality",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonWhiteBalanceMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonSharpenMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashSetting",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShootingMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDigitalZoom",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShutterCount",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashExposureComp",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusDistance"
      ],
      "title": "Program Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyMakerNikonImageAdjustment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonImageAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Program-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSetting",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSelection",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonColorMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonQuality",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonWhiteBalanceMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonSharpenMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashSetting",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShootingMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDigitalZoom",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShutterCount",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashExposureComp",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusDistance"
              ],
              "title": "Program Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyMakerNikonImageAdjustment"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonColorMode/title",
          "value": "kCGImagePropertyMakerNikonColorMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonColorMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonColorMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonWhiteBalanceMode/title",
          "value": "kCGImagePropertyMakerNikonWhiteBalanceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonWhiteBalanceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonWhiteBalanceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonDigitalZoom/title",
          "value": "kCGImagePropertyMakerNikonDigitalZoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonDigitalZoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonDigitalZoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonImageAdjustment/title",
          "value": "kCGImagePropertyMakerNikonImageAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonImageAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonImageAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonISOSelection/title",
          "value": "kCGImagePropertyMakerNikonISOSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonISOSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonISOSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFlashSetting/title",
          "value": "kCGImagePropertyMakerNikonFlashSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFlashSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonFlashSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonShootingMode/title",
          "value": "kCGImagePropertyMakerNikonShootingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonShootingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonShootingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonQuality/title",
          "value": "kCGImagePropertyMakerNikonQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFocusMode/title",
          "value": "kCGImagePropertyMakerNikonFocusMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFocusMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonFocusMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonSharpenMode/title",
          "value": "kCGImagePropertyMakerNikonSharpenMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonSharpenMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonSharpenMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFlashExposureComp/title",
          "value": "kCGImagePropertyMakerNikonFlashExposureComp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFlashExposureComp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonFlashExposureComp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFocusDistance/title",
          "value": "kCGImagePropertyMakerNikonFocusDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFocusDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonFocusDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonISOSetting/title",
          "value": "kCGImagePropertyMakerNikonISOSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonISOSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonISOSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonShutterCount/title",
          "value": "kCGImagePropertyMakerNikonShutterCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonShutterCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonShutterCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertymakernikonimageadjustment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertymakernikonimageadjustment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
