{
  "abstract": [
    {
      "text": "The data for the first hue/saturation/value mapping table.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapData1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyDNGProfileHueSatMapData1",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyDNGProfileHueSatMapData1"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyDNGProfileHueSatMapData1"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyDNGProfileHueSatMapData1"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileHueSatMapData1"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotProfileName": {
      "abstract": [
        {
          "text": "A string containing the name of the “as shot” camera profile, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAsShotProfileName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotProfileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAsShotProfileName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGAsShotProfileName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngasshotprofilename"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGExtraCameraProfiles": {
      "abstract": [
        {
          "text": "A list of file offsets to extra camera profiles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGExtraCameraProfiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGExtraCameraProfiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGExtraCameraProfiles"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGExtraCameraProfiles",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngextracameraprofiles"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileCopyright": {
      "abstract": [
        {
          "text": "The copyright information for the camera profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileCopyright"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileCopyright",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofilecopyright"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileEmbedPolicy": {
      "abstract": [
        {
          "text": "The usage rules for the camera profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileEmbedPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileEmbedPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileEmbedPolicy"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileEmbedPolicy",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofileembedpolicy"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapData1": {
      "abstract": [
        {
          "text": "The data for the first hue/saturation/value mapping table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileHueSatMapData1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapData1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileHueSatMapData1"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileHueSatMapData1",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofilehuesatmapdata1"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapData2": {
      "abstract": [
        {
          "text": "The data for the second hue/saturation/value mapping table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileHueSatMapData2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapData2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileHueSatMapData2"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileHueSatMapData2",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofilehuesatmapdata2"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapDims": {
      "abstract": [
        {
          "text": "The number of input samples in each dimension of the hue/saturation/value mapping tables.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileHueSatMapDims"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapDims",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileHueSatMapDims"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileHueSatMapDims",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofilehuesatmapdims"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapEncoding": {
      "abstract": [
        {
          "text": "The encoding option to use when indexing into a 3D look table during raw conversion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileHueSatMapEncoding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapEncoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileHueSatMapEncoding"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileHueSatMapEncoding",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofilehuesatmapencoding"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableData": {
      "abstract": [
        {
          "text": "The default “look” table to apply when processing the image as a starting point for user adjustment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileLookTableData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileLookTableData"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileLookTableData",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofilelooktabledata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableDims": {
      "abstract": [
        {
          "text": "The number of input samples in each dimentsion of a default “look” table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileLookTableDims"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableDims",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileLookTableDims"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileLookTableDims",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofilelooktabledims"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableEncoding": {
      "abstract": [
        {
          "text": "The encoding option to use when indexing into a 3D look table during raw conversion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileLookTableEncoding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableEncoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileLookTableEncoding"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileLookTableEncoding",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofilelooktableencoding"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileName": {
      "abstract": [
        {
          "text": "A string containing the name of the camera profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofilename"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileToneCurve": {
      "abstract": [
        {
          "text": "The default tone curve to apply when processing the image as a starting point for user adjustments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileToneCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileToneCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGProfileToneCurve"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGProfileToneCurve",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngprofiletonecurve"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Profile-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGExtraCameraProfiles",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotProfileName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapDims",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapData2",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapEncoding",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileToneCurve",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileEmbedPolicy",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileCopyright",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableDims",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableData",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableEncoding"
      ],
      "title": "Profile Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyDNGProfileHueSatMapData1"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileHueSatMapData1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Profile-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGExtraCameraProfiles",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotProfileName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapDims",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapData2",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileHueSatMapEncoding",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileToneCurve",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileEmbedPolicy",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileCopyright",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableDims",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableData",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGProfileLookTableEncoding"
              ],
              "title": "Profile Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyDNGProfileHueSatMapData1"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileLookTableDims/title",
          "value": "kCGImagePropertyDNGProfileLookTableDims"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileLookTableDims/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileLookTableDims"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileName/title",
          "value": "kCGImagePropertyDNGProfileName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGExtraCameraProfiles/title",
          "value": "kCGImagePropertyDNGExtraCameraProfiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGExtraCameraProfiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGExtraCameraProfiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileLookTableEncoding/title",
          "value": "kCGImagePropertyDNGProfileLookTableEncoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileLookTableEncoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileLookTableEncoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileHueSatMapDims/title",
          "value": "kCGImagePropertyDNGProfileHueSatMapDims"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileHueSatMapDims/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileHueSatMapDims"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileToneCurve/title",
          "value": "kCGImagePropertyDNGProfileToneCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileToneCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileToneCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileHueSatMapData1/title",
          "value": "kCGImagePropertyDNGProfileHueSatMapData1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileHueSatMapData1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileHueSatMapData1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileHueSatMapEncoding/title",
          "value": "kCGImagePropertyDNGProfileHueSatMapEncoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileHueSatMapEncoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileHueSatMapEncoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAsShotProfileName/title",
          "value": "kCGImagePropertyDNGAsShotProfileName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAsShotProfileName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGAsShotProfileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileHueSatMapData2/title",
          "value": "kCGImagePropertyDNGProfileHueSatMapData2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileHueSatMapData2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileHueSatMapData2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileEmbedPolicy/title",
          "value": "kCGImagePropertyDNGProfileEmbedPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileEmbedPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileEmbedPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileLookTableData/title",
          "value": "kCGImagePropertyDNGProfileLookTableData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileLookTableData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileLookTableData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileCopyright/title",
          "value": "kCGImagePropertyDNGProfileCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGProfileCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGProfileCopyright"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertydngprofilehuesatmapdata1"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertydngprofilehuesatmapdata1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
