{
  "abstract": [
    {
      "text": "The namespace for the IPTC format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceIPTCCore"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImageMetadataNamespaceIPTCCore",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImageMetadataNamespaceIPTCCore"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImageMetadataNamespaceIPTCCore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImageMetadataNamespaceIPTCCore"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceIPTCCore"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceDublinCore": {
      "abstract": [
        {
          "text": "The namespace for the Dublin Core Metadata Element Set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceDublinCore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceDublinCore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceDublinCore"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceDublinCore",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespacedublincore"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExif": {
      "abstract": [
        {
          "text": "The namespace for the Exchangeable Image File (EXIF) format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExif"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceExif",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespaceexif"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifAux": {
      "abstract": [
        {
          "text": "The namespace for EXIF auxiliary keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExifAux"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifAux",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExifAux"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceExifAux",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespaceexifaux"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifEX": {
      "abstract": [
        {
          "text": "The namespace for the exifEX format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExifEX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifEX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExifEX"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceExifEX",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespaceexifex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceIPTCCore": {
      "abstract": [
        {
          "text": "The namespace for the IPTC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceIPTCCore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceIPTCCore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceIPTCCore"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceIPTCCore",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespaceiptccore"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespacePhotoshop": {
      "abstract": [
        {
          "text": "The namespace for Photoshop image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespacePhotoshop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespacePhotoshop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespacePhotoshop"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespacePhotoshop",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespacephotoshop"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceTIFF": {
      "abstract": [
        {
          "text": "The namespace for TIFF image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceTIFF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceTIFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceTIFF"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceTIFF",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespacetiff"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPBasic": {
      "abstract": [
        {
          "text": "The namespace for the Extensible Metadata Platform (XMP) format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceXMPBasic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPBasic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceXMPBasic"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceXMPBasic",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespacexmpbasic"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPRights": {
      "abstract": [
        {
          "text": "The namespace for XMP metadata that conveys legal restrictions associated with a resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceXMPRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPRights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceXMPRights"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceXMPRights",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespacexmprights"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Public-Namespaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceDublinCore",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExif",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifAux",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifEX",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespacePhotoshop",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceTIFF",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPBasic",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPRights"
      ],
      "title": "Public Namespaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImageMetadataNamespaceIPTCCore"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceIPTCCore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Public-Namespaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceDublinCore",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExif",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifAux",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifEX",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespacePhotoshop",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceTIFF",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPBasic",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPRights"
              ],
              "title": "Public Namespaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImageMetadataNamespaceIPTCCore"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceXMPBasic/title",
          "value": "kCGImageMetadataNamespaceXMPBasic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceXMPBasic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceXMPBasic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceDublinCore/title",
          "value": "kCGImageMetadataNamespaceDublinCore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceDublinCore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceDublinCore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceIPTCCore/title",
          "value": "kCGImageMetadataNamespaceIPTCCore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceIPTCCore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceIPTCCore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExifAux/title",
          "value": "kCGImageMetadataNamespaceExifAux"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExifAux/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceExifAux"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExif/title",
          "value": "kCGImageMetadataNamespaceExif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceExif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceXMPRights/title",
          "value": "kCGImageMetadataNamespaceXMPRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceXMPRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceXMPRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceTIFF/title",
          "value": "kCGImageMetadataNamespaceTIFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceTIFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceTIFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExifEX/title",
          "value": "kCGImageMetadataNamespaceExifEX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExifEX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceExifEX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespacePhotoshop/title",
          "value": "kCGImageMetadataNamespacePhotoshop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespacePhotoshop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespacePhotoshop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagemetadatanamespaceiptccore"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagemetadatanamespaceiptccore"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
