{
  "abstract": [
    {
      "text": "The aperture value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifApertureValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyExifApertureValue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyExifApertureValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyExifApertureValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyExifApertureValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifApertureValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifApertureValue": {
      "abstract": [
        {
          "text": "The aperture value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifApertureValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifApertureValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifApertureValue"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifApertureValue",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifaperturevalue"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDeviceSettingDescription": {
      "abstract": [
        {
          "text": "For a particular camera mode, indicates the conditions for taking the picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifDeviceSettingDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDeviceSettingDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifDeviceSettingDescription"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifDeviceSettingDescription",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifdevicesettingdescription"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDigitalZoomRatio": {
      "abstract": [
        {
          "text": "The digital zoom ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifDigitalZoomRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDigitalZoomRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifDigitalZoomRatio"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifDigitalZoomRatio",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifdigitalzoomratio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFNumber": {
      "abstract": [
        {
          "text": "The F-number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFNumber"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifFNumber",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexiffnumber"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalLenIn35mmFilm": {
      "abstract": [
        {
          "text": "The equivalent focal length in 35 mm film.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFocalLenIn35mmFilm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalLenIn35mmFilm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFocalLenIn35mmFilm"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifFocalLenIn35mmFilm",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexiffocallenin35mmfilm"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalLength": {
      "abstract": [
        {
          "text": "The focal length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFocalLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFocalLength"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifFocalLength",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexiffocallength"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedRatings": {
      "abstract": [
        {
          "text": "The ISO speed ratings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifISOSpeedRatings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedRatings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifISOSpeedRatings"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifISOSpeedRatings",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifisospeedratings"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifMaxApertureValue": {
      "abstract": [
        {
          "text": "The maximum aperture value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifMaxApertureValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifMaxApertureValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifMaxApertureValue"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifMaxApertureValue",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifmaxaperturevalue"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifMeteringMode": {
      "abstract": [
        {
          "text": "The metering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifMeteringMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifMeteringMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifMeteringMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifMeteringMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifmeteringmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSceneType": {
      "abstract": [
        {
          "text": "The scene type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSceneType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSceneType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSceneType"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifSceneType",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifscenetype"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSensingMethod": {
      "abstract": [
        {
          "text": "The sensor type of the camera or input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSensingMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSensingMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSensingMethod"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifSensingMethod",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifsensingmethod"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifShutterSpeedValue": {
      "abstract": [
        {
          "text": "The shutter speed value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifShutterSpeedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifShutterSpeedValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifShutterSpeedValue"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifShutterSpeedValue",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifshutterspeedvalue"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSpectralSensitivity": {
      "abstract": [
        {
          "text": "The spectral sensitivity of each channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSpectralSensitivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSpectralSensitivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSpectralSensitivity"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifSpectralSensitivity",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifspectralsensitivity"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectArea": {
      "abstract": [
        {
          "text": "The subject area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSubjectArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSubjectArea"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifSubjectArea",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifsubjectarea"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectDistance": {
      "abstract": [
        {
          "text": "The distance to the subject, in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSubjectDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSubjectDistance"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifSubjectDistance",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifsubjectdistance"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectLocation": {
      "abstract": [
        {
          "text": "The location of the image’s primary subject.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSubjectLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSubjectLocation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifSubjectLocation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifsubjectlocation"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Camera-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDeviceSettingDescription",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFNumber",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifShutterSpeedValue",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifMaxApertureValue",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalLength",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSpectralSensitivity",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedRatings",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectDistance",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifMeteringMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectArea",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectLocation",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSensingMethod",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSceneType",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDigitalZoomRatio",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalLenIn35mmFilm"
      ],
      "title": "Camera Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyExifApertureValue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifApertureValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Camera-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDeviceSettingDescription",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFNumber",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifShutterSpeedValue",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifMaxApertureValue",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalLength",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSpectralSensitivity",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedRatings",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectDistance",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifMeteringMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectArea",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSubjectLocation",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSensingMethod",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSceneType",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDigitalZoomRatio",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalLenIn35mmFilm"
              ],
              "title": "Camera Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyExifApertureValue"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifDigitalZoomRatio/title",
          "value": "kCGImagePropertyExifDigitalZoomRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifDigitalZoomRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifDigitalZoomRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifApertureValue/title",
          "value": "kCGImagePropertyExifApertureValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifApertureValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifApertureValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSceneType/title",
          "value": "kCGImagePropertyExifSceneType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSceneType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSceneType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSubjectLocation/title",
          "value": "kCGImagePropertyExifSubjectLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSubjectLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSubjectLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifDeviceSettingDescription/title",
          "value": "kCGImagePropertyExifDeviceSettingDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifDeviceSettingDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifDeviceSettingDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSubjectDistance/title",
          "value": "kCGImagePropertyExifSubjectDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSubjectDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSubjectDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSubjectArea/title",
          "value": "kCGImagePropertyExifSubjectArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSubjectArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSubjectArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSensingMethod/title",
          "value": "kCGImagePropertyExifSensingMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSensingMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSensingMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFocalLenIn35mmFilm/title",
          "value": "kCGImagePropertyExifFocalLenIn35mmFilm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFocalLenIn35mmFilm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifFocalLenIn35mmFilm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifMeteringMode/title",
          "value": "kCGImagePropertyExifMeteringMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifMeteringMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifMeteringMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFocalLength/title",
          "value": "kCGImagePropertyExifFocalLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFocalLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifFocalLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSpectralSensitivity/title",
          "value": "kCGImagePropertyExifSpectralSensitivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSpectralSensitivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSpectralSensitivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifMaxApertureValue/title",
          "value": "kCGImagePropertyExifMaxApertureValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifMaxApertureValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifMaxApertureValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifShutterSpeedValue/title",
          "value": "kCGImagePropertyExifShutterSpeedValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifShutterSpeedValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifShutterSpeedValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifISOSpeedRatings/title",
          "value": "kCGImagePropertyExifISOSpeedRatings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifISOSpeedRatings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifISOSpeedRatings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFNumber/title",
          "value": "kCGImagePropertyExifFNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifFNumber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyexifaperturevalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyexifaperturevalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
