{
  "abstract": [
    {
      "text": "The units of resolution.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFResolutionUnit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyTIFFResolutionUnit",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyTIFFResolutionUnit"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyTIFFResolutionUnit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyTIFFResolutionUnit"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFResolutionUnit"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation": {
      "abstract": [
        {
          "text": "The image orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFOrientation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytifforientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPrimaryChromaticities": {
      "abstract": [
        {
          "text": "The chromaticities of the primaries of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFPrimaryChromaticities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPrimaryChromaticities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFPrimaryChromaticities"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFPrimaryChromaticities",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffprimarychromaticities"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFResolutionUnit": {
      "abstract": [
        {
          "text": "The units of resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFResolutionUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFResolutionUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFResolutionUnit"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFResolutionUnit",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffresolutionunit"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFTileLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFTileLength"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFTileLength",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytifftilelength"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileWidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFTileWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFTileWidth"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFTileWidth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytifftilewidth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFWhitePoint": {
      "abstract": [
        {
          "text": "The white point of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFWhitePoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFWhitePoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFWhitePoint"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFWhitePoint",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffwhitepoint"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXResolution": {
      "abstract": [
        {
          "text": "The number of pixels per resolution unit in the image width direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFXResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFXResolution"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFXResolution",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffxresolution"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYResolution": {
      "abstract": [
        {
          "text": "The number of pixels per resolution unit in the image height direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFYResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFYResolution"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFYResolution",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffyresolution"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Canvas-Details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXResolution",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYResolution",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFWhitePoint",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPrimaryChromaticities",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileLength",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileWidth"
      ],
      "title": "Canvas Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyTIFFResolutionUnit"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFResolutionUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Canvas-Details",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXResolution",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYResolution",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFWhitePoint",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPrimaryChromaticities",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileLength",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileWidth"
              ],
              "title": "Canvas Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyTIFFResolutionUnit"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFResolutionUnit/title",
          "value": "kCGImagePropertyTIFFResolutionUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFResolutionUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFResolutionUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFWhitePoint/title",
          "value": "kCGImagePropertyTIFFWhitePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFWhitePoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFWhitePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFOrientation/title",
          "value": "kCGImagePropertyTIFFOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFTileLength/title",
          "value": "kCGImagePropertyTIFFTileLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFTileLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFTileLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFYResolution/title",
          "value": "kCGImagePropertyTIFFYResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFYResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFYResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFPrimaryChromaticities/title",
          "value": "kCGImagePropertyTIFFPrimaryChromaticities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFPrimaryChromaticities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFPrimaryChromaticities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFXResolution/title",
          "value": "kCGImagePropertyTIFFXResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFXResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFXResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFTileWidth/title",
          "value": "kCGImagePropertyTIFFTileWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFTileWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFTileWidth"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertytiffresolutionunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertytiffresolutionunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
