{
  "abstract": [
    {
      "text": "An opcode to apply a warp to an image to correct for geometric distortion and lateral chromatic aberration for rectilinear lenses.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGWarpRectilinear"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyDNGWarpRectilinear",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyDNGWarpRectilinear"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyDNGWarpRectilinear"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyDNGWarpRectilinear"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGWarpRectilinear"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCFALayout": {
      "abstract": [
        {
          "text": "The spatial layout of the CFA.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCFALayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCFALayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCFALayout"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGCFALayout",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngcfalayout"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCFAPlaneColor": {
      "abstract": [
        {
          "text": "A mapping between the values in the CFA pattern tag and the plane numbers in linear raw space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCFAPlaneColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCFAPlaneColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCFAPlaneColor"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGCFAPlaneColor",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngcfaplanecolor"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNewRawImageDigest": {
      "abstract": [
        {
          "text": "An MD5 digest of the raw image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGNewRawImageDigest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNewRawImageDigest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGNewRawImageDigest"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGNewRawImageDigest",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngnewrawimagedigest"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNoiseProfile": {
      "abstract": [
        {
          "text": "The amount of noise in the raw image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGNoiseProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNoiseProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGNoiseProfile"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGNoiseProfile",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngnoiseprofile"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNoiseReductionApplied": {
      "abstract": [
        {
          "text": "The amount of noise reduction applied to the raw data on a scale of 0.0 to 1.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGNoiseReductionApplied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNoiseReductionApplied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGNoiseReductionApplied"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGNoiseReductionApplied",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngnoisereductionapplied"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOpcodeList1": {
      "abstract": [
        {
          "text": "The list of opcodes to apply to the raw image, as read directly from the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOpcodeList1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOpcodeList1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOpcodeList1"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGOpcodeList1",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngopcodelist1"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOpcodeList2": {
      "abstract": [
        {
          "text": "THe list of opcodes to apply to the raw image, after mapping it to linear reference values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOpcodeList2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOpcodeList2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOpcodeList2"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGOpcodeList2",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngopcodelist2"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalBestQualityFinalSize": {
      "abstract": [
        {
          "text": "The best-quality final size of the larger original file that was the source of this proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalBestQualityFinalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalBestQualityFinalSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalBestQualityFinalSize"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGOriginalBestQualityFinalSize",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngoriginalbestqualityfinalsize"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalDefaultCropSize": {
      "abstract": [
        {
          "text": "The default crop size of the larger original file that was the source of this proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalDefaultCropSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalDefaultCropSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalDefaultCropSize"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGOriginalDefaultCropSize",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngoriginaldefaultcropsize"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalDefaultFinalSize": {
      "abstract": [
        {
          "text": "THe default final size of the larger original file that was the source of this proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalDefaultFinalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalDefaultFinalSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalDefaultFinalSize"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGOriginalDefaultFinalSize",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngoriginaldefaultfinalsize"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileData": {
      "abstract": [
        {
          "text": "The compressed contents of the original raw file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalRawFileData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalRawFileData"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGOriginalRawFileData",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngoriginalrawfiledata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileDigest": {
      "abstract": [
        {
          "text": "An MD5 digest of the data stored for the original raw file data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalRawFileDigest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileDigest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalRawFileDigest"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGOriginalRawFileDigest",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngoriginalrawfiledigest"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileName": {
      "abstract": [
        {
          "text": "The file name of the original raw file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalRawFileName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGOriginalRawFileName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGOriginalRawFileName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngoriginalrawfilename"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGRawImageDigest": {
      "abstract": [
        {
          "text": "A modified MD5 digest of the raw image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGRawImageDigest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGRawImageDigest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGRawImageDigest"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGRawImageDigest",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngrawimagedigest"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGRawToPreviewGain": {
      "abstract": [
        {
          "text": "The gain between the main raw IFD and the preview IFD that contains this tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGRawToPreviewGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGRawToPreviewGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGRawToPreviewGain"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGRawToPreviewGain",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngrawtopreviewgain"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGWarpRectilinear": {
      "abstract": [
        {
          "text": "An opcode to apply a warp to an image to correct for geometric distortion and lateral chromatic aberration for rectilinear lenses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGWarpRectilinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGWarpRectilinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGWarpRectilinear"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGWarpRectilinear",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngwarprectilinear"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "RAW-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileData",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNoiseReductionApplied",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNewRawImageDigest",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileDigest",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGRawImageDigest",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalDefaultFinalSize",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalBestQualityFinalSize",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalDefaultCropSize",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGRawToPreviewGain",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNoiseProfile",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCFALayout",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCFAPlaneColor",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOpcodeList1",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOpcodeList2"
      ],
      "title": "RAW Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyDNGWarpRectilinear"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGWarpRectilinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "RAW-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileData",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNoiseReductionApplied",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNewRawImageDigest",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalRawFileDigest",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGRawImageDigest",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalDefaultFinalSize",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalBestQualityFinalSize",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOriginalDefaultCropSize",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGRawToPreviewGain",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGNoiseProfile",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCFALayout",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCFAPlaneColor",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOpcodeList1",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGOpcodeList2"
              ],
              "title": "RAW Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyDNGWarpRectilinear"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalBestQualityFinalSize/title",
          "value": "kCGImagePropertyDNGOriginalBestQualityFinalSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalBestQualityFinalSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGOriginalBestQualityFinalSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalDefaultFinalSize/title",
          "value": "kCGImagePropertyDNGOriginalDefaultFinalSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalDefaultFinalSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGOriginalDefaultFinalSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGRawToPreviewGain/title",
          "value": "kCGImagePropertyDNGRawToPreviewGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGRawToPreviewGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGRawToPreviewGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOpcodeList2/title",
          "value": "kCGImagePropertyDNGOpcodeList2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOpcodeList2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGOpcodeList2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGNewRawImageDigest/title",
          "value": "kCGImagePropertyDNGNewRawImageDigest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGNewRawImageDigest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGNewRawImageDigest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCFAPlaneColor/title",
          "value": "kCGImagePropertyDNGCFAPlaneColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCFAPlaneColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGCFAPlaneColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalRawFileDigest/title",
          "value": "kCGImagePropertyDNGOriginalRawFileDigest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalRawFileDigest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGOriginalRawFileDigest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGNoiseReductionApplied/title",
          "value": "kCGImagePropertyDNGNoiseReductionApplied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGNoiseReductionApplied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGNoiseReductionApplied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGRawImageDigest/title",
          "value": "kCGImagePropertyDNGRawImageDigest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGRawImageDigest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGRawImageDigest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalRawFileName/title",
          "value": "kCGImagePropertyDNGOriginalRawFileName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalRawFileName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGOriginalRawFileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalRawFileData/title",
          "value": "kCGImagePropertyDNGOriginalRawFileData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalRawFileData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGOriginalRawFileData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOpcodeList1/title",
          "value": "kCGImagePropertyDNGOpcodeList1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOpcodeList1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGOpcodeList1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCFALayout/title",
          "value": "kCGImagePropertyDNGCFALayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCFALayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGCFALayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGWarpRectilinear/title",
          "value": "kCGImagePropertyDNGWarpRectilinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGWarpRectilinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGWarpRectilinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGNoiseProfile/title",
          "value": "kCGImagePropertyDNGNoiseProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGNoiseProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGNoiseProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalDefaultCropSize/title",
          "value": "kCGImagePropertyDNGOriginalDefaultCropSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGOriginalDefaultCropSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGOriginalDefaultCropSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertydngwarprectilinear"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertydngwarprectilinear"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
