{
  "abstract": [
    {
      "text": "A sound file related to the image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifRelatedSoundFile"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyExifRelatedSoundFile",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyExifRelatedSoundFile"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyExifRelatedSoundFile"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyExifRelatedSoundFile"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifRelatedSoundFile"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifColorSpace": {
      "abstract": [
        {
          "text": "The color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifColorSpace"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifColorSpace",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifcolorspace"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifComponentsConfiguration": {
      "abstract": [
        {
          "text": "The components configuration for compressed data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifComponentsConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifComponentsConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifComponentsConfiguration"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifComponentsConfiguration",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifcomponentsconfiguration"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCompositeImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifCompositeImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCompositeImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifCompositeImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifCompositeImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifcompositeimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCompressedBitsPerPixel": {
      "abstract": [
        {
          "text": "The bits per pixel of the compression mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifCompressedBitsPerPixel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCompressedBitsPerPixel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifCompressedBitsPerPixel"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifCompressedBitsPerPixel",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifcompressedbitsperpixel"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCustomRendered": {
      "abstract": [
        {
          "text": "Special  rendering performed on the image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifCustomRendered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCustomRendered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifCustomRendered"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifCustomRendered",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifcustomrendered"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFileSource": {
      "abstract": [
        {
          "text": "The image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFileSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFileSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFileSource"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifFileSource",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexiffilesource"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneResolutionUnit": {
      "abstract": [
        {
          "text": "The unit of measurement for the focal plane x and y resolutions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFocalPlaneResolutionUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneResolutionUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFocalPlaneResolutionUnit"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifFocalPlaneResolutionUnit",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexiffocalplaneresolutionunit"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneXResolution": {
      "abstract": [
        {
          "text": "The number of image-width pixels (x-axis) per focal plane resolution unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFocalPlaneXResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneXResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFocalPlaneXResolution"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifFocalPlaneXResolution",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexiffocalplanexresolution"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneYResolution": {
      "abstract": [
        {
          "text": "The number of image-height pixels (y-axis) per focal plane resolution unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFocalPlaneYResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneYResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifFocalPlaneYResolution"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifFocalPlaneYResolution",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexiffocalplaneyresolution"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifGainControl": {
      "abstract": [
        {
          "text": "The gain adjustment setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifGainControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifGainControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifGainControl"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifGainControl",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifgaincontrol"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifImageUniqueID": {
      "abstract": [
        {
          "text": "The unique ID of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifImageUniqueID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifImageUniqueID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifImageUniqueID"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifImageUniqueID",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifimageuniqueid"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifOECF": {
      "abstract": [
        {
          "text": "The opto-electric conversion function (OECF) that defines the relationship between the optical input of the camera and the resulting image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifOECF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifOECF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifOECF"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifOECF",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifoecf"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifPixelXDimension": {
      "abstract": [
        {
          "text": "The x dimension of a pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifPixelXDimension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifPixelXDimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifPixelXDimension"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifPixelXDimension",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifpixelxdimension"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifPixelYDimension": {
      "abstract": [
        {
          "text": "The y dimension of a pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifPixelYDimension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifPixelYDimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifPixelYDimension"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifPixelYDimension",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifpixelydimension"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifRelatedSoundFile": {
      "abstract": [
        {
          "text": "A sound file related to the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifRelatedSoundFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifRelatedSoundFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifRelatedSoundFile"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifRelatedSoundFile",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifrelatedsoundfile"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSourceImageNumberOfCompositeImage": {
      "abstract": [
        {
          "text": "The number of images that make up a composite image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSourceImageNumberOfCompositeImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSourceImageNumberOfCompositeImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSourceImageNumberOfCompositeImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifSourceImageNumberOfCompositeImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifsourceimagenumberofcompositeimage"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifGainControl",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifImageUniqueID",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCompressedBitsPerPixel",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifColorSpace",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifPixelXDimension",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifPixelYDimension",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneXResolution",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneYResolution",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneResolutionUnit",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCustomRendered",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCompositeImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifOECF",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifComponentsConfiguration",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSourceImageNumberOfCompositeImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFileSource"
      ],
      "title": "Image Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyExifRelatedSoundFile"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifRelatedSoundFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifGainControl",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifImageUniqueID",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCompressedBitsPerPixel",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifColorSpace",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifPixelXDimension",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifPixelYDimension",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneXResolution",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneYResolution",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFocalPlaneResolutionUnit",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCustomRendered",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifCompositeImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifOECF",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifComponentsConfiguration",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSourceImageNumberOfCompositeImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifFileSource"
              ],
              "title": "Image Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyExifRelatedSoundFile"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFocalPlaneXResolution/title",
          "value": "kCGImagePropertyExifFocalPlaneXResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFocalPlaneXResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifFocalPlaneXResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifRelatedSoundFile/title",
          "value": "kCGImagePropertyExifRelatedSoundFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifRelatedSoundFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifRelatedSoundFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifComponentsConfiguration/title",
          "value": "kCGImagePropertyExifComponentsConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifComponentsConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifComponentsConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSourceImageNumberOfCompositeImage/title",
          "value": "kCGImagePropertyExifSourceImageNumberOfCompositeImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSourceImageNumberOfCompositeImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSourceImageNumberOfCompositeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifGainControl/title",
          "value": "kCGImagePropertyExifGainControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifGainControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifGainControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifColorSpace/title",
          "value": "kCGImagePropertyExifColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifOECF/title",
          "value": "kCGImagePropertyExifOECF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifOECF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifOECF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifCompositeImage/title",
          "value": "kCGImagePropertyExifCompositeImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifCompositeImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifCompositeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifCompressedBitsPerPixel/title",
          "value": "kCGImagePropertyExifCompressedBitsPerPixel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifCompressedBitsPerPixel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifCompressedBitsPerPixel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifPixelYDimension/title",
          "value": "kCGImagePropertyExifPixelYDimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifPixelYDimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifPixelYDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifCustomRendered/title",
          "value": "kCGImagePropertyExifCustomRendered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifCustomRendered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifCustomRendered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifImageUniqueID/title",
          "value": "kCGImagePropertyExifImageUniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifImageUniqueID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifImageUniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFocalPlaneYResolution/title",
          "value": "kCGImagePropertyExifFocalPlaneYResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFocalPlaneYResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifFocalPlaneYResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFileSource/title",
          "value": "kCGImagePropertyExifFileSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFileSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifFileSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFocalPlaneResolutionUnit/title",
          "value": "kCGImagePropertyExifFocalPlaneResolutionUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifFocalPlaneResolutionUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifFocalPlaneResolutionUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifPixelXDimension/title",
          "value": "kCGImagePropertyExifPixelXDimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifPixelXDimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifPixelXDimension"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyexifrelatedsoundfile"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyexifrelatedsoundfile"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
