{
  "abstract": [
    {
      "text": "The exposure times for composite images.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyExifSourceExposureTimesOfCompositeImage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15.1",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureBiasValue": {
      "abstract": [
        {
          "text": "The exposure bias value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifExposureBiasValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureBiasValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifExposureBiasValue"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifExposureBiasValue",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifexposurebiasvalue"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureIndex": {
      "abstract": [
        {
          "text": "The selected exposure index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifExposureIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifExposureIndex"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifExposureIndex",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifexposureindex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureMode": {
      "abstract": [
        {
          "text": "The exposure mode setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifExposureMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifExposureMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifExposureMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifexposuremode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureProgram": {
      "abstract": [
        {
          "text": "The exposure program.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifExposureProgram"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureProgram",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifExposureProgram"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifExposureProgram",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifexposureprogram"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureTime": {
      "abstract": [
        {
          "text": "The exposure time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifExposureTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifExposureTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifExposureTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifexposuretime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeed": {
      "abstract": [
        {
          "text": "The ISO speed setting used to capture the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifISOSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifISOSpeed"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifISOSpeed",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifisospeed"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedLatitudeyyy": {
      "abstract": [
        {
          "text": "The ISO speed latitude yyy value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifISOSpeedLatitudeyyy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedLatitudeyyy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifISOSpeedLatitudeyyy"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifISOSpeedLatitudeyyy",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifisospeedlatitudeyyy"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedLatitudezzz": {
      "abstract": [
        {
          "text": "The ISO speed latitude zzz value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifISOSpeedLatitudezzz"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedLatitudezzz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifISOSpeedLatitudezzz"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifISOSpeedLatitudezzz",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifisospeedlatitudezzz"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifRecommendedExposureIndex": {
      "abstract": [
        {
          "text": "The recommended exposure index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifRecommendedExposureIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifRecommendedExposureIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifRecommendedExposureIndex"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifRecommendedExposureIndex",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifrecommendedexposureindex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSensitivityType": {
      "abstract": [
        {
          "text": "The type of sensitivity data stored for the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSensitivityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSensitivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSensitivityType"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifSensitivityType",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifsensitivitytype"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSourceExposureTimesOfCompositeImage": {
      "abstract": [
        {
          "text": "The exposure times for composite images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSourceExposureTimesOfCompositeImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifsourceexposuretimesofcompositeimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifStandardOutputSensitivity": {
      "abstract": [
        {
          "text": "The sensitivity data for the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifStandardOutputSensitivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifStandardOutputSensitivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifStandardOutputSensitivity"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifStandardOutputSensitivity",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifstandardoutputsensitivity"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Exposure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureProgram",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureIndex",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeed",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedLatitudeyyy",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedLatitudezzz",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifRecommendedExposureIndex",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureBiasValue",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSensitivityType",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifStandardOutputSensitivity"
      ],
      "title": "Exposure"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15.1",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Exposure",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureProgram",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureIndex",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeed",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedLatitudeyyy",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifISOSpeedLatitudezzz",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifRecommendedExposureIndex",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifExposureBiasValue",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifSensitivityType",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifStandardOutputSensitivity"
              ],
              "title": "Exposure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSensitivityType/title",
          "value": "kCGImagePropertyExifSensitivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSensitivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSensitivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifExposureBiasValue/title",
          "value": "kCGImagePropertyExifExposureBiasValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifExposureBiasValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifExposureBiasValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifStandardOutputSensitivity/title",
          "value": "kCGImagePropertyExifStandardOutputSensitivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifStandardOutputSensitivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifStandardOutputSensitivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifRecommendedExposureIndex/title",
          "value": "kCGImagePropertyExifRecommendedExposureIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifRecommendedExposureIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifRecommendedExposureIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifExposureIndex/title",
          "value": "kCGImagePropertyExifExposureIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifExposureIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifExposureIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifISOSpeedLatitudeyyy/title",
          "value": "kCGImagePropertyExifISOSpeedLatitudeyyy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifISOSpeedLatitudeyyy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifISOSpeedLatitudeyyy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifISOSpeedLatitudezzz/title",
          "value": "kCGImagePropertyExifISOSpeedLatitudezzz"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifISOSpeedLatitudezzz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifISOSpeedLatitudezzz"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifExposureMode/title",
          "value": "kCGImagePropertyExifExposureMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifExposureMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifExposureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifExposureProgram/title",
          "value": "kCGImagePropertyExifExposureProgram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifExposureProgram/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifExposureProgram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifISOSpeed/title",
          "value": "kCGImagePropertyExifISOSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifISOSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifISOSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifExposureTime/title",
          "value": "kCGImagePropertyExifExposureTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifExposureTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifExposureTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSourceExposureTimesOfCompositeImage/title",
          "value": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifSourceExposureTimesOfCompositeImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifSourceExposureTimesOfCompositeImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyexifsourceexposuretimesofcompositeimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyexifsourceexposuretimesofcompositeimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
