{
  "abstract": [
    {
      "text": "The reference number.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceNumber"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyIPTCReferenceNumber",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyIPTCReferenceNumber"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyIPTCReferenceNumber"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyIPTCReferenceNumber"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCReferenceNumber"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCActionAdvised": {
      "abstract": [
        {
          "text": "The advised action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCActionAdvised"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCActionAdvised",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCActionAdvised"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCActionAdvised",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcactionadvised"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDateCreated": {
      "abstract": [
        {
          "text": "The creation date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCDateCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDateCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCDateCreated"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCDateCreated",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcdatecreated"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDigitalCreationDate": {
      "abstract": [
        {
          "text": "The digital creation date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCDigitalCreationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDigitalCreationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCDigitalCreationDate"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCDigitalCreationDate",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcdigitalcreationdate"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDigitalCreationTime": {
      "abstract": [
        {
          "text": "The digital creation time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCDigitalCreationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDigitalCreationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCDigitalCreationTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCDigitalCreationTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcdigitalcreationtime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExpirationDate": {
      "abstract": [
        {
          "text": "The latest date you can use the image, in the form CCYYMMDD.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExpirationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExpirationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExpirationDate"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExpirationDate",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcexpirationdate"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExpirationTime": {
      "abstract": [
        {
          "text": "The latest time on the expiration date you can use the image, in the form HHMMSS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExpirationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExpirationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExpirationTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExpirationTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcexpirationtime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceDate": {
      "abstract": [
        {
          "text": "The reference date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCReferenceDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCReferenceDate"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCReferenceDate",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcreferencedate"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceNumber": {
      "abstract": [
        {
          "text": "The reference number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCReferenceNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCReferenceNumber"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCReferenceNumber",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcreferencenumber"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceService": {
      "abstract": [
        {
          "text": "The reference service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCReferenceService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCReferenceService"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCReferenceService",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcreferenceservice"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReleaseDate": {
      "abstract": [
        {
          "text": "The earliest day on which you can use the image, in the form CCYYMMDD.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCReleaseDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReleaseDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCReleaseDate"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCReleaseDate",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcreleasedate"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReleaseTime": {
      "abstract": [
        {
          "text": "The earliest time at which you can use the image, in the form HHMMSS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCReleaseTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReleaseTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCReleaseTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCReleaseTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcreleasetime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSpecialInstructions": {
      "abstract": [
        {
          "text": "Special instructions about the use of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCSpecialInstructions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSpecialInstructions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCSpecialInstructions"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCSpecialInstructions",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcspecialinstructions"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCTimeCreated": {
      "abstract": [
        {
          "text": "The creation time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCTimeCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCTimeCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCTimeCreated"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCTimeCreated",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptctimecreated"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Release-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReleaseDate",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReleaseTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExpirationDate",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExpirationTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSpecialInstructions",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCActionAdvised",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceService",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceDate",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDateCreated",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCTimeCreated",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDigitalCreationDate",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDigitalCreationTime"
      ],
      "title": "Release Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyIPTCReferenceNumber"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCReferenceNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Release-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReleaseDate",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReleaseTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExpirationDate",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExpirationTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCSpecialInstructions",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCActionAdvised",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceService",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCReferenceDate",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDateCreated",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCTimeCreated",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDigitalCreationDate",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCDigitalCreationTime"
              ],
              "title": "Release Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyIPTCReferenceNumber"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCReleaseDate/title",
          "value": "kCGImagePropertyIPTCReleaseDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCReleaseDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCReleaseDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCReferenceDate/title",
          "value": "kCGImagePropertyIPTCReferenceDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCReferenceDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCReferenceDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCActionAdvised/title",
          "value": "kCGImagePropertyIPTCActionAdvised"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCActionAdvised/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCActionAdvised"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCDigitalCreationTime/title",
          "value": "kCGImagePropertyIPTCDigitalCreationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCDigitalCreationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCDigitalCreationTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCDateCreated/title",
          "value": "kCGImagePropertyIPTCDateCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCDateCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCDateCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExpirationDate/title",
          "value": "kCGImagePropertyIPTCExpirationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExpirationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExpirationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCSpecialInstructions/title",
          "value": "kCGImagePropertyIPTCSpecialInstructions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCSpecialInstructions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCSpecialInstructions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCTimeCreated/title",
          "value": "kCGImagePropertyIPTCTimeCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCTimeCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCTimeCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCDigitalCreationDate/title",
          "value": "kCGImagePropertyIPTCDigitalCreationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCDigitalCreationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCDigitalCreationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCReleaseTime/title",
          "value": "kCGImagePropertyIPTCReleaseTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCReleaseTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCReleaseTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCReferenceNumber/title",
          "value": "kCGImagePropertyIPTCReferenceNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCReferenceNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCReferenceNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCReferenceService/title",
          "value": "kCGImagePropertyIPTCReferenceService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCReferenceService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCReferenceService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExpirationTime/title",
          "value": "kCGImagePropertyIPTCExpirationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExpirationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExpirationTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyiptcreferencenumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyiptcreferencenumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
