{
  "abstract": [
    {
      "text": "A matrix that maps white balanced camera colors to XYZ D50 colors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGForwardMatrix1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyDNGForwardMatrix1",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyDNGForwardMatrix1"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyDNGForwardMatrix1"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyDNGForwardMatrix1"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGForwardMatrix1"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAnalogBalance": {
      "abstract": [
        {
          "text": "The analog or digital gain that applies to the stored raw values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAnalogBalance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAnalogBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAnalogBalance"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGAnalogBalance",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydnganalogbalance"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotNeutral": {
      "abstract": [
        {
          "text": "The selected white balance at the time of capture, encoded as the coordinates of a neutral color in linear reference space values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAsShotNeutral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotNeutral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAsShotNeutral"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGAsShotNeutral",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngasshotneutral"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotWhiteXY": {
      "abstract": [
        {
          "text": "The selected white balance at the time of capture, encoded as x-y chromaticity coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAsShotWhiteXY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotWhiteXY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAsShotWhiteXY"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGAsShotWhiteXY",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngasshotwhitexy"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBayerGreenSplit": {
      "abstract": [
        {
          "text": "A value that specifies how closely green pixels in the blue/green rows track the green pixels in red/green rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGBayerGreenSplit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBayerGreenSplit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGBayerGreenSplit"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGBayerGreenSplit",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngbayergreensplit"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGDefaultBlackRender": {
      "abstract": [
        {
          "text": "A hint to the raw converter about how to handle the black point during rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGDefaultBlackRender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGDefaultBlackRender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGDefaultBlackRender"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGDefaultBlackRender",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngdefaultblackrender"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGForwardMatrix1": {
      "abstract": [
        {
          "text": "A matrix that maps white balanced camera colors to XYZ D50 colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGForwardMatrix1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGForwardMatrix1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGForwardMatrix1"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGForwardMatrix1",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngforwardmatrix1"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGForwardMatrix2": {
      "abstract": [
        {
          "text": "A matrix that maps white balanced camera colors to XYZ D50 colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGForwardMatrix2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGForwardMatrix2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGForwardMatrix2"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGForwardMatrix2",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngforwardmatrix2"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Color-Balance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAnalogBalance",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotNeutral",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotWhiteXY",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBayerGreenSplit",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGForwardMatrix2",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGDefaultBlackRender"
      ],
      "title": "Color Balance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyDNGForwardMatrix1"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGForwardMatrix1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Color-Balance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAnalogBalance",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotNeutral",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotWhiteXY",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBayerGreenSplit",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGForwardMatrix2",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGDefaultBlackRender"
              ],
              "title": "Color Balance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyDNGForwardMatrix1"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAsShotNeutral/title",
          "value": "kCGImagePropertyDNGAsShotNeutral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAsShotNeutral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGAsShotNeutral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAnalogBalance/title",
          "value": "kCGImagePropertyDNGAnalogBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAnalogBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGAnalogBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGForwardMatrix1/title",
          "value": "kCGImagePropertyDNGForwardMatrix1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGForwardMatrix1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGForwardMatrix1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGBayerGreenSplit/title",
          "value": "kCGImagePropertyDNGBayerGreenSplit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGBayerGreenSplit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGBayerGreenSplit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGDefaultBlackRender/title",
          "value": "kCGImagePropertyDNGDefaultBlackRender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGDefaultBlackRender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGDefaultBlackRender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAsShotWhiteXY/title",
          "value": "kCGImagePropertyDNGAsShotWhiteXY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAsShotWhiteXY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGAsShotWhiteXY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGForwardMatrix2/title",
          "value": "kCGImagePropertyDNGForwardMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGForwardMatrix2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGForwardMatrix2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertydngforwardmatrix1"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertydngforwardmatrix1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
