{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtDataOnScreenRegionH"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyIPTCExtDataOnScreenRegionH",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.3",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTerm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAboutCvTerm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTerm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAboutCvTerm"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtAboutCvTerm",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextaboutcvterm"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermCvId": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAboutCvTermCvId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermCvId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAboutCvTermCvId"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtAboutCvTermCvId",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextaboutcvtermcvid"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermId": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAboutCvTermId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAboutCvTermId"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtAboutCvTermId",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextaboutcvtermid"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAboutCvTermName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAboutCvTermName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtAboutCvTermName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextaboutcvtermname"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermRefinedAbout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAboutCvTermRefinedAbout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermRefinedAbout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAboutCvTermRefinedAbout"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtAboutCvTermRefinedAbout",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextaboutcvtermrefinedabout"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAddlModelInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAddlModelInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAddlModelInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtAddlModelInfo"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtAddlModelInfo",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextaddlmodelinfo"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCircaDateCreated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCircaDateCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCircaDateCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCircaDateCreated"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtArtworkCircaDateCreated",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextartworkcircadatecreated"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkContentDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkContentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkContentDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkContentDescription"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtArtworkContentDescription",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextartworkcontentdescription"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkContributionDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkContributionDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkContributionDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkContributionDescription"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtArtworkContributionDescription",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextartworkcontributiondescription"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightNotice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCopyrightNotice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightNotice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCopyrightNotice"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtArtworkCopyrightNotice",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextartworkcopyrightnotice"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightOwnerID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCopyrightOwnerID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightOwnerID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCopyrightOwnerID"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtArtworkCopyrightOwnerID",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextartworkcopyrightownerid"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightOwnerName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCopyrightOwnerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightOwnerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCopyrightOwnerName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtArtworkCopyrightOwnerName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextartworkcopyrightownername"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCreator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCreator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCreator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCreator"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtArtworkCreator",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextartworkcreator"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCreatorID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCreatorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCreatorID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkCreatorID"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtArtworkCreatorID",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextartworkcreatorid"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkDateCreated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkDateCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkDateCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtArtworkDateCreated"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtArtworkDateCreated",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextartworkdatecreated"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtDataOnScreenRegionH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtDataOnScreenRegionH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCExtDataOnScreenRegionH",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptcextdataonscreenregionh"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Extended-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTerm",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermCvId",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermId",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermRefinedAbout",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAddlModelInfo",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCircaDateCreated",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkContentDescription",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkContributionDescription",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightNotice",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightOwnerID",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightOwnerName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCreator",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCreatorID",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkDateCreated"
      ],
      "title": "Extended Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.3",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Extended-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTerm",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermCvId",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermId",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAboutCvTermRefinedAbout",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtAddlModelInfo",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCircaDateCreated",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkContentDescription",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkContributionDescription",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightNotice",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightOwnerID",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCopyrightOwnerName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCreator",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkCreatorID",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCExtArtworkDateCreated"
              ],
              "title": "Extended Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAddlModelInfo/title",
          "value": "kCGImagePropertyIPTCExtAddlModelInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAddlModelInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtAddlModelInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCreator/title",
          "value": "kCGImagePropertyIPTCExtArtworkCreator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCreator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtArtworkCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCreatorID/title",
          "value": "kCGImagePropertyIPTCExtArtworkCreatorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCreatorID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtArtworkCreatorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCopyrightOwnerName/title",
          "value": "kCGImagePropertyIPTCExtArtworkCopyrightOwnerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCopyrightOwnerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtArtworkCopyrightOwnerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtDataOnScreenRegionH/title",
          "value": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtDataOnScreenRegionH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtDataOnScreenRegionH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAboutCvTerm/title",
          "value": "kCGImagePropertyIPTCExtAboutCvTerm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAboutCvTerm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtAboutCvTerm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAboutCvTermId/title",
          "value": "kCGImagePropertyIPTCExtAboutCvTermId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAboutCvTermId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtAboutCvTermId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCopyrightNotice/title",
          "value": "kCGImagePropertyIPTCExtArtworkCopyrightNotice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCopyrightNotice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtArtworkCopyrightNotice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkDateCreated/title",
          "value": "kCGImagePropertyIPTCExtArtworkDateCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkDateCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtArtworkDateCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAboutCvTermCvId/title",
          "value": "kCGImagePropertyIPTCExtAboutCvTermCvId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAboutCvTermCvId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtAboutCvTermCvId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAboutCvTermName/title",
          "value": "kCGImagePropertyIPTCExtAboutCvTermName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAboutCvTermName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtAboutCvTermName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkContentDescription/title",
          "value": "kCGImagePropertyIPTCExtArtworkContentDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkContentDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtArtworkContentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCircaDateCreated/title",
          "value": "kCGImagePropertyIPTCExtArtworkCircaDateCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCircaDateCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtArtworkCircaDateCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkContributionDescription/title",
          "value": "kCGImagePropertyIPTCExtArtworkContributionDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkContributionDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtArtworkContributionDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAboutCvTermRefinedAbout/title",
          "value": "kCGImagePropertyIPTCExtAboutCvTermRefinedAbout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtAboutCvTermRefinedAbout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtAboutCvTermRefinedAbout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCopyrightOwnerID/title",
          "value": "kCGImagePropertyIPTCExtArtworkCopyrightOwnerID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCExtArtworkCopyrightOwnerID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCExtArtworkCopyrightOwnerID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyiptcextdataonscreenregionh"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertyiptcextdataonscreenregionh"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
