{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageStereoAggressors"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyGroupImageStereoAggressors",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyGroupImageStereoAggressors"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyGroupImageStereoAggressors"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyGroupImageStereoAggressors"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageStereoAggressors"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoColorSpace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataInfoColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataInfoColorSpace"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataInfoColorSpace",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatainfocolorspace"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeISOGainMap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeISOGainMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeISOGainMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeISOGainMap"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeISOGainMap",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypeisogainmap"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAVISDictionary": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAVISDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAVISDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAVISDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyAVISDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyavisdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageBaseline": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageBaseline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageBaseline"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageBaseline",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimagebaseline"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageDisparityAdjustment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageDisparityAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageDisparityAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageDisparityAdjustment"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageDisparityAdjustment",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimagedisparityadjustment"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexLeft"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIndexLeft",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageindexleft"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexMonoscopic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexMonoscopic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexMonoscopic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexMonoscopic"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIndexMonoscopic",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageindexmonoscopic"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIndexRight"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIndexRight",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageindexright"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsAlternateImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsAlternateImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsAlternateImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsAlternateImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIsAlternateImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageisalternateimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsLeftImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsLeftImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsLeftImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsLeftImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIsLeftImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageisleftimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsMonoscopicImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsMonoscopicImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsMonoscopicImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsMonoscopicImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIsMonoscopicImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageismonoscopicimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsRightImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsRightImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsRightImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageIsRightImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageIsRightImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimageisrightimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageStereoAggressors": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageStereoAggressors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageStereoAggressors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImageStereoAggressors"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImageStereoAggressors",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimagestereoaggressors"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImagesAlternate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImagesAlternate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImagesAlternate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupImagesAlternate"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupImagesAlternate",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupimagesalternate"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupIndex"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupIndex",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupindex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupMonoscopicImageLocation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupMonoscopicImageLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupMonoscopicImageLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGroupMonoscopicImageLocation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGroupMonoscopicImageLocation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygroupmonoscopicimagelocation"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoColorSpace",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeISOGainMap",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupMonoscopicImageLocation",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAVISDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageBaseline",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageDisparityAdjustment",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexLeft",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexRight",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexMonoscopic",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsAlternateImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsLeftImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsRightImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsMonoscopicImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImagesAlternate",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupIndex"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyGroupImageStereoAggressors"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageStereoAggressors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataInfoColorSpace",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeISOGainMap",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupMonoscopicImageLocation",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAVISDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageBaseline",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageDisparityAdjustment",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexLeft",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexRight",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIndexMonoscopic",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsAlternateImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsLeftImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsRightImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImageIsMonoscopicImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupImagesAlternate",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGroupIndex"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyGroupImageStereoAggressors"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageBaseline/title",
          "value": "kCGImagePropertyGroupImageBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsRightImage/title",
          "value": "kCGImagePropertyGroupImageIsRightImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsRightImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIsRightImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsMonoscopicImage/title",
          "value": "kCGImagePropertyGroupImageIsMonoscopicImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsMonoscopicImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIsMonoscopicImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageDisparityAdjustment/title",
          "value": "kCGImagePropertyGroupImageDisparityAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageDisparityAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageDisparityAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsLeftImage/title",
          "value": "kCGImagePropertyGroupImageIsLeftImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsLeftImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIsLeftImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsAlternateImage/title",
          "value": "kCGImagePropertyGroupImageIsAlternateImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIsAlternateImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIsAlternateImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeISOGainMap/title",
          "value": "kCGImageAuxiliaryDataTypeISOGainMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeISOGainMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeISOGainMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageStereoAggressors/title",
          "value": "kCGImagePropertyGroupImageStereoAggressors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageStereoAggressors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageStereoAggressors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexLeft/title",
          "value": "kCGImagePropertyGroupImageIndexLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIndexLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupIndex/title",
          "value": "kCGImagePropertyGroupIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataInfoColorSpace/title",
          "value": "kCGImageAuxiliaryDataInfoColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataInfoColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataInfoColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexMonoscopic/title",
          "value": "kCGImagePropertyGroupImageIndexMonoscopic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexMonoscopic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIndexMonoscopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAVISDictionary/title",
          "value": "kCGImagePropertyAVISDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAVISDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyAVISDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexRight/title",
          "value": "kCGImagePropertyGroupImageIndexRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImageIndexRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImageIndexRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupMonoscopicImageLocation/title",
          "value": "kCGImagePropertyGroupMonoscopicImageLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupMonoscopicImageLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupMonoscopicImageLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImagesAlternate/title",
          "value": "kCGImagePropertyGroupImagesAlternate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGroupImagesAlternate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGroupImagesAlternate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertygroupimagestereoaggressors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertygroupimagestereoaggressors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
