{
  "abstract": [
    {
      "text": "A matrix that transforms reference camera native space values to camera-native space values under the second calibration illuminant.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCameraCalibration2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyDNGCameraCalibration2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyDNGCameraCalibration2"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyDNGCameraCalibration2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyDNGCameraCalibration2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGCameraCalibration2"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotICCProfile": {
      "abstract": [
        {
          "text": "A profile that specifies default color rendering from camera color-space coordinates into the ICC profile space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAsShotICCProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotICCProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAsShotICCProfile"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGAsShotICCProfile",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngasshoticcprofile"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotPreProfileMatrix": {
      "abstract": [
        {
          "text": "A matrix to apply to the camera color-space coordinates before processing values through the ICC profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAsShotPreProfileMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotPreProfileMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGAsShotPreProfileMatrix"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGAsShotPreProfileMatrix",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngasshotpreprofilematrix"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevel": {
      "abstract": [
        {
          "text": "The zero light encoding level, specified as a repeating pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGBlackLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGBlackLevel"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGBlackLevel",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngblacklevel"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelDeltaH": {
      "abstract": [
        {
          "text": "The difference between the zero-light encoding level for each column and the baseline zero-light encoding level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGBlackLevelDeltaH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelDeltaH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGBlackLevelDeltaH"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGBlackLevelDeltaH",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngblackleveldeltah"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelDeltaV": {
      "abstract": [
        {
          "text": "The difference between the zero-light encodoing level for each row and the baseline zero-light encoding level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGBlackLevelDeltaV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelDeltaV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGBlackLevelDeltaV"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGBlackLevelDeltaV",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngblackleveldeltav"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelRepeatDim": {
      "abstract": [
        {
          "text": "The repeat pattern size for the black level tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGBlackLevelRepeatDim"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelRepeatDim",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGBlackLevelRepeatDim"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGBlackLevelRepeatDim",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngblacklevelrepeatdim"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCalibrationIlluminant1": {
      "abstract": [
        {
          "text": "The illuminant for the first set of color calibration tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCalibrationIlluminant1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCalibrationIlluminant1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCalibrationIlluminant1"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGCalibrationIlluminant1",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngcalibrationilluminant1"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCalibrationIlluminant2": {
      "abstract": [
        {
          "text": "The illuminant for an optional second set of color calibration tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCalibrationIlluminant2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCalibrationIlluminant2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCalibrationIlluminant2"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGCalibrationIlluminant2",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngcalibrationilluminant2"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCameraCalibration1": {
      "abstract": [
        {
          "text": "A matrix that transforms reference camera native space values to camera-native space values under the first calibration illuminant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCameraCalibration1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCameraCalibration1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCameraCalibration1"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGCameraCalibration1",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngcameracalibration1"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCameraCalibration2": {
      "abstract": [
        {
          "text": "A matrix that transforms reference camera native space values to camera-native space values under the second calibration illuminant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCameraCalibration2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCameraCalibration2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCameraCalibration2"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGCameraCalibration2",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngcameracalibration2"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGColorMatrix1": {
      "abstract": [
        {
          "text": "A transformation matrix that converts XYZ values to reference camera native color spaces, under the first calibration illuminant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGColorMatrix1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGColorMatrix1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGColorMatrix1"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGColorMatrix1",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngcolormatrix1"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGColorMatrix2": {
      "abstract": [
        {
          "text": "A transformation matrix that converts XYZ values to reference camera native color spaces, under the second calibration illuminant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGColorMatrix2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGColorMatrix2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGColorMatrix2"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGColorMatrix2",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngcolormatrix2"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCurrentICCProfile": {
      "abstract": [
        {
          "text": "A profile that specifies default color rendering from camera color-space coordinates into the ICC profile space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCurrentICCProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCurrentICCProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGCurrentICCProfile"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGCurrentICCProfile",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngcurrenticcprofile"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGReductionMatrix1": {
      "abstract": [
        {
          "text": "A reduction matrix that converts color camera-native space values to XYZ values, under the first calibration illuminant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGReductionMatrix1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGReductionMatrix1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGReductionMatrix1"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGReductionMatrix1",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngreductionmatrix1"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGReductionMatrix2": {
      "abstract": [
        {
          "text": "A reduction matrix that converts color camera-native space values to XYZ values, under the second calibration illuminant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGReductionMatrix2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGReductionMatrix2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGReductionMatrix2"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGReductionMatrix2",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngreductionmatrix2"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGWhiteLevel": {
      "abstract": [
        {
          "text": "The saturated encoding level for the raw sample values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGWhiteLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGWhiteLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyDNGWhiteLevel"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyDNGWhiteLevel",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertydngwhitelevel"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Color-Calibration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelRepeatDim",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevel",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelDeltaH",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelDeltaV",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGWhiteLevel",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCalibrationIlluminant1",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCalibrationIlluminant2",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGColorMatrix1",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGColorMatrix2",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCameraCalibration1",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGReductionMatrix1",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGReductionMatrix2",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotICCProfile",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotPreProfileMatrix",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCurrentICCProfile"
      ],
      "title": "Color Calibration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyDNGCameraCalibration2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGCameraCalibration2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Color-Calibration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelRepeatDim",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevel",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelDeltaH",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGBlackLevelDeltaV",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGWhiteLevel",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCalibrationIlluminant1",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCalibrationIlluminant2",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGColorMatrix1",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGColorMatrix2",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCameraCalibration1",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGReductionMatrix1",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGReductionMatrix2",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotICCProfile",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGAsShotPreProfileMatrix",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyDNGCurrentICCProfile"
              ],
              "title": "Color Calibration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyDNGCameraCalibration2"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGBlackLevelDeltaH/title",
          "value": "kCGImagePropertyDNGBlackLevelDeltaH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGBlackLevelDeltaH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGBlackLevelDeltaH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGColorMatrix2/title",
          "value": "kCGImagePropertyDNGColorMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGColorMatrix2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGColorMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGWhiteLevel/title",
          "value": "kCGImagePropertyDNGWhiteLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGWhiteLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGWhiteLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGBlackLevelRepeatDim/title",
          "value": "kCGImagePropertyDNGBlackLevelRepeatDim"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGBlackLevelRepeatDim/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGBlackLevelRepeatDim"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAsShotICCProfile/title",
          "value": "kCGImagePropertyDNGAsShotICCProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAsShotICCProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGAsShotICCProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGColorMatrix1/title",
          "value": "kCGImagePropertyDNGColorMatrix1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGColorMatrix1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGColorMatrix1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAsShotPreProfileMatrix/title",
          "value": "kCGImagePropertyDNGAsShotPreProfileMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGAsShotPreProfileMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGAsShotPreProfileMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGBlackLevelDeltaV/title",
          "value": "kCGImagePropertyDNGBlackLevelDeltaV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGBlackLevelDeltaV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGBlackLevelDeltaV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCalibrationIlluminant1/title",
          "value": "kCGImagePropertyDNGCalibrationIlluminant1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCalibrationIlluminant1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGCalibrationIlluminant1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGReductionMatrix2/title",
          "value": "kCGImagePropertyDNGReductionMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGReductionMatrix2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGReductionMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGBlackLevel/title",
          "value": "kCGImagePropertyDNGBlackLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGBlackLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGBlackLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCalibrationIlluminant2/title",
          "value": "kCGImagePropertyDNGCalibrationIlluminant2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCalibrationIlluminant2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGCalibrationIlluminant2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCameraCalibration2/title",
          "value": "kCGImagePropertyDNGCameraCalibration2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCameraCalibration2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGCameraCalibration2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGReductionMatrix1/title",
          "value": "kCGImagePropertyDNGReductionMatrix1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGReductionMatrix1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGReductionMatrix1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCameraCalibration1/title",
          "value": "kCGImagePropertyDNGCameraCalibration1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCameraCalibration1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGCameraCalibration1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCurrentICCProfile/title",
          "value": "kCGImagePropertyDNGCurrentICCProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyDNGCurrentICCProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyDNGCurrentICCProfile"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertydngcameracalibration2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertydngcameracalibration2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
