{
  "abstract": [
    {
      "text": "The type for portrait effects matte information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypePortraitEffectsMatte"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImageAuxiliaryDataTypePortraitEffectsMatte",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDepth": {
      "abstract": [
        {
          "text": "The type for depth map information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeDepth"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeDepth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypedepth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDisparity": {
      "abstract": [
        {
          "text": "The type for image disparity information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeDisparity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDisparity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeDisparity"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeDisparity",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypedisparity"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeHDRGainMap": {
      "abstract": [
        {
          "text": "The type for High Dynamic Range (HDR) gain map information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeHDRGainMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeHDRGainMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeHDRGainMap"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeHDRGainMap",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypehdrgainmap"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypePortraitEffectsMatte": {
      "abstract": [
        {
          "text": "The type for portrait effects matte information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypePortraitEffectsMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypePortraitEffectsMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypeportraiteffectsmatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte": {
      "abstract": [
        {
          "text": "The type for glasses matte informaton.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypesemanticsegmentationglassesmatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte": {
      "abstract": [
        {
          "text": "The type for hair matte information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypesemanticsegmentationhairmatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte": {
      "abstract": [
        {
          "text": "The type for skin matte informaton.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypesemanticsegmentationskinmatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte": {
      "abstract": [
        {
          "text": "The type for sky matte information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypesemanticsegmentationskymatte"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte": {
      "abstract": [
        {
          "text": "The type for teeth matte information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageauxiliarydatatypesemanticsegmentationteethmatte"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Auxiliary-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDepth",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDisparity",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeHDRGainMap",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
      ],
      "title": "Auxiliary Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Auxiliary-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDepth",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeDisparity",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeHDRGainMap",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
              ],
              "title": "Auxiliary Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte/title",
          "value": "kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypePortraitEffectsMatte/title",
          "value": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypePortraitEffectsMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypePortraitEffectsMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeDisparity/title",
          "value": "kCGImageAuxiliaryDataTypeDisparity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeDisparity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeDisparity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte/title",
          "value": "kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationGlassesMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte/title",
          "value": "kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte/title",
          "value": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkyMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte/title",
          "value": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeHDRGainMap/title",
          "value": "kCGImageAuxiliaryDataTypeHDRGainMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeHDRGainMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeHDRGainMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeDepth/title",
          "value": "kCGImageAuxiliaryDataTypeDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAuxiliaryDataTypeDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAuxiliaryDataTypeDepth"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimageauxiliarydatatypeportraiteffectsmatte"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimageauxiliarydatatypeportraiteffectsmatte"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
