{
  "abstract": [
    {
      "text": "A dictionary of key-value pairs for an image from a Olympus camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyMakerOlympusDictionary",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyMakerOlympusDictionary"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyMakerOlympusDictionary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyMakerOlympusDictionary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerOlympusDictionary"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for an image from a Canon camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Canon Camera Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/canon-camera-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from an Apple camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerAppleDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerAppleDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerAppleDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerappledictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Fuji camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerFujiDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerFujiDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerFujiDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerfujidictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Minolta camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerMinoltaDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerMinoltaDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerMinoltaDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerminoltadictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Olympus camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerOlympusDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerOlympusDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerOlympusDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerolympusdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Pentax camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerPentaxDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerPentaxDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerPentaxDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerpentaxdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that contains minimally processed, or raw, data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyRawDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyRawDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyRawDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyrawdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for an image from a Nikon camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nikon Camera Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/nikon-camera-dictionary-keys"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Manufacturer-Specific-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary"
      ],
      "title": "Manufacturer-Specific Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyMakerOlympusDictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerOlympusDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Manufacturer-Specific-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary"
              ],
              "title": "Manufacturer-Specific Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyMakerOlympusDictionary"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerOlympusDictionary/title",
          "value": "kCGImagePropertyMakerOlympusDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerOlympusDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerOlympusDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerFujiDictionary/title",
          "value": "kCGImagePropertyMakerFujiDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerFujiDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerFujiDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerAppleDictionary/title",
          "value": "kCGImagePropertyMakerAppleDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerAppleDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerAppleDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyRawDictionary/title",
          "value": "kCGImagePropertyRawDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyRawDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyRawDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerMinoltaDictionary/title",
          "value": "kCGImagePropertyMakerMinoltaDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerMinoltaDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerMinoltaDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerPentaxDictionary/title",
          "value": "kCGImagePropertyMakerPentaxDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerPentaxDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerPentaxDictionary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertymakerolympusdictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertymakerolympusdictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
