{
  "abstract": [
    {
      "text": "The name of the GPS area.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAreaInformation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImagePropertyGPSAreaInformation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImagePropertyGPSAreaInformation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyGPSAreaInformation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImagePropertyGPSAreaInformation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSAreaInformation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAreaInformation": {
      "abstract": [
        {
          "text": "The name of the GPS area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSAreaInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSAreaInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSAreaInformation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSAreaInformation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsareainformation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDOP": {
      "abstract": [
        {
          "text": "The degree of precision (DOP) of the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDOP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDOP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDOP"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDOP",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdop"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDifferental": {
      "abstract": [
        {
          "text": "An indication of whether differential correction is applied to the GPS receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDifferental"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDifferental",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSDifferental"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSDifferental",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsdifferental"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMapDatum": {
      "abstract": [
        {
          "text": "The geodetic survey data used by the GPS receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSMapDatum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMapDatum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSMapDatum"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSMapDatum",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsmapdatum"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMeasureMode": {
      "abstract": [
        {
          "text": "The measurement mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSMeasureMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMeasureMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSMeasureMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSMeasureMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsmeasuremode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSProcessingMethod": {
      "abstract": [
        {
          "text": "The name of the method used to find a location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSProcessingMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSProcessingMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSProcessingMethod"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSProcessingMethod",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsprocessingmethod"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSatellites": {
      "abstract": [
        {
          "text": "The satellites used for GPS measurements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSatellites"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSatellites",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSatellites"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSSatellites",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpssatellites"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeed": {
      "abstract": [
        {
          "text": "The GPS receiver’s speed of movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSpeed"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSSpeed",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsspeed"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeedRef": {
      "abstract": [
        {
          "text": "The unit for expressing the GPS receiver’s speed of movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSpeedRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeedRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSSpeedRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSSpeedRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsspeedref"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSStatus": {
      "abstract": [
        {
          "text": "The status of the GPS receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSStatus"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSStatus",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpsstatus"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrack": {
      "abstract": [
        {
          "text": "The direction of GPS receiver’s movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSTrack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSTrack"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSTrack",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpstrack"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrackRef": {
      "abstract": [
        {
          "text": "The reference for the direction of GPS receiver’s movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSTrackRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrackRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyGPSTrackRef"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyGPSTrackRef",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertygpstrackref"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measurement-Details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSStatus",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSatellites",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMeasureMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDOP",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeedRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeed",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrackRef",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrack",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMapDatum",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSProcessingMethod",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDifferental"
      ],
      "title": "Measurement Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyGPSAreaInformation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSAreaInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measurement-Details",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSStatus",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSatellites",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMeasureMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDOP",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeedRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSSpeed",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrackRef",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSTrack",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSMapDatum",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSProcessingMethod",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyGPSDifferental"
              ],
              "title": "Measurement Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyGPSAreaInformation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSatellites/title",
          "value": "kCGImagePropertyGPSSatellites"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSatellites/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSSatellites"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSMapDatum/title",
          "value": "kCGImagePropertyGPSMapDatum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSMapDatum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSMapDatum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSProcessingMethod/title",
          "value": "kCGImagePropertyGPSProcessingMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSProcessingMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSProcessingMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSpeed/title",
          "value": "kCGImagePropertyGPSSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSpeedRef/title",
          "value": "kCGImagePropertyGPSSpeedRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSSpeedRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSSpeedRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDOP/title",
          "value": "kCGImagePropertyGPSDOP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDOP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDOP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSMeasureMode/title",
          "value": "kCGImagePropertyGPSMeasureMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSMeasureMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSMeasureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDifferental/title",
          "value": "kCGImagePropertyGPSDifferental"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSDifferental/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSDifferental"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSTrack/title",
          "value": "kCGImagePropertyGPSTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSTrackRef/title",
          "value": "kCGImagePropertyGPSTrackRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSTrackRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSTrackRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSAreaInformation/title",
          "value": "kCGImagePropertyGPSAreaInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSAreaInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSAreaInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSStatus/title",
          "value": "kCGImagePropertyGPSStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyGPSStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyGPSStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertygpsareainformation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagepropertygpsareainformation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
