{
  "abstract": [
    {
      "text": "The prefix string for tags in the exifEX metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifEX"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImageMetadataPrefixExifEX",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImageMetadataPrefixExifEX"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImageMetadataPrefixExifEX"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImageMetadataPrefixExifEX"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixExifEX"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixDublinCore": {
      "abstract": [
        {
          "text": "The prefix string for tags in the Dublin Core Metadata Element Set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixDublinCore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixDublinCore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixDublinCore"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixDublinCore",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixdublincore"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExif": {
      "abstract": [
        {
          "text": "The prefix string for tags in the Exchangeable Image File (EXIF) metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExif"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixExif",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixexif"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifAux": {
      "abstract": [
        {
          "text": "The prefix string for tags in the EXIF auxiliary metadata collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExifAux"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifAux",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExifAux"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixExifAux",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixexifaux"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifEX": {
      "abstract": [
        {
          "text": "The prefix string for tags in the exifEX metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExifEX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifEX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExifEX"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixExifEX",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixexifex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixIPTCCore": {
      "abstract": [
        {
          "text": "The prefix string for tags in the IPTC metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixIPTCCore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixIPTCCore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixIPTCCore"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixIPTCCore",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixiptccore"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixPhotoshop": {
      "abstract": [
        {
          "text": "The prefix string for tags in the Photoshop image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixPhotoshop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixPhotoshop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixPhotoshop"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixPhotoshop",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixphotoshop"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixTIFF": {
      "abstract": [
        {
          "text": "The prefix string for tags in the TIFF image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixTIFF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixTIFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixTIFF"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixTIFF",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixtiff"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPBasic": {
      "abstract": [
        {
          "text": "The prefix string for tags in the XMP metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixXMPBasic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPBasic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixXMPBasic"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixXMPBasic",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixxmpbasic"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPRights": {
      "abstract": [
        {
          "text": "The prefix string for tags in the XMP metadata that convey legal restrictions for the resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixXMPRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPRights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixXMPRights"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixXMPRights",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixxmprights"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Public-Prefixes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixDublinCore",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExif",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifAux",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixIPTCCore",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixPhotoshop",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixTIFF",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPBasic",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPRights"
      ],
      "title": "Public Prefixes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImageMetadataPrefixExifEX"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixExifEX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Public-Prefixes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixDublinCore",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExif",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifAux",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixIPTCCore",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixPhotoshop",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixTIFF",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPBasic",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPRights"
              ],
              "title": "Public Prefixes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImageMetadataPrefixExifEX"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExifEX/title",
          "value": "kCGImageMetadataPrefixExifEX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExifEX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixExifEX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixDublinCore/title",
          "value": "kCGImageMetadataPrefixDublinCore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixDublinCore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixDublinCore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixTIFF/title",
          "value": "kCGImageMetadataPrefixTIFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixTIFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixTIFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixXMPRights/title",
          "value": "kCGImageMetadataPrefixXMPRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixXMPRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixXMPRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExifAux/title",
          "value": "kCGImageMetadataPrefixExifAux"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExifAux/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixExifAux"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixPhotoshop/title",
          "value": "kCGImageMetadataPrefixPhotoshop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixPhotoshop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixPhotoshop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixIPTCCore/title",
          "value": "kCGImageMetadataPrefixIPTCCore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixIPTCCore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixIPTCCore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExif/title",
          "value": "kCGImageMetadataPrefixExif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixExif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixXMPBasic/title",
          "value": "kCGImageMetadataPrefixXMPBasic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixXMPBasic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixXMPBasic"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagemetadataprefixexifex"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagemetadataprefixexifex"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
