{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether to merge new metadata with the image’s existing metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMergeMetadata"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCGImageDestinationMergeMetadata",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCGImageDestinationMergeMetadata"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImageDestinationMergeMetadata"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCGImageDestinationMergeMetadata"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCGImageDestinationMergeMetadata"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this key must be a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfboolean",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value. The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you set this key to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the image destination merges the information in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMetadata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key with the image’s existing metadata. Specifically, if a tag doesn’t exist in the source, the destination adds it. If the tag exists in the source, the destination updates its value. To remove a tag, set the value of the appropriate key to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfnull",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cfboolean": {
      "abstract": [
        {
          "text": "A reference to a CFBoolean object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFBoolean"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfboolean",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFBoolean",
      "type": "topic",
      "url": "/documentation/corefoundation/cfboolean"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse": {
      "abstract": [
        {
          "text": "Boolean false value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanFalse"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanFalse",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleanfalse"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue": {
      "abstract": [
        {
          "text": "Boolean true value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanTrue"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanTrue",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleantrue"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfnull": {
      "abstract": [
        {
          "text": "The singleton CFNull object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFNull"
        },
        {
          "kind": "text",
          "text": ": CFNull!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfnull",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFNull",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfnull"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationBackgroundColor": {
      "abstract": [
        {
          "text": "The background color to use when the image has an alpha component, but the destination format doesn’t support alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationBackgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationBackgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationBackgroundColor",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationbackgroundcolor"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationDateTime": {
      "abstract": [
        {
          "text": "The date and time information to associate with the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationDateTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationDateTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationDateTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationDateTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationdatetime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEmbedThumbnail": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to embed a thumbnail for JPEG and HEIF images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEmbedThumbnail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEmbedThumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEmbedThumbnail"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationEmbedThumbnail",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationembedthumbnail"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationImageMaxPixelSize": {
      "abstract": [
        {
          "text": "The maximum width and height of the image, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationImageMaxPixelSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationImageMaxPixelSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationImageMaxPixelSize"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationImageMaxPixelSize",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationimagemaxpixelsize"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationLossyCompressionQuality": {
      "abstract": [
        {
          "text": "The desired compression quality to use when writing the image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationLossyCompressionQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationLossyCompressionQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationLossyCompressionQuality"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationLossyCompressionQuality",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationlossycompressionquality"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMergeMetadata": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to merge new metadata with the image’s existing metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationMergeMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMergeMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationMergeMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationMergeMetadata",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationmergemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMetadata": {
      "abstract": [
        {
          "text": "The metadata tags to include with the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationMetadata",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationmetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOptimizeColorForSharing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to create the image using a colorspace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationOptimizeColorForSharing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOptimizeColorForSharing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationOptimizeColorForSharing"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationOptimizeColorForSharing",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationoptimizecolorforsharing"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOrientation": {
      "abstract": [
        {
          "text": "The orientation of the image, specified as an EXIF value in the range 1 to 8.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationOrientation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationorientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationPreserveGainMap": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to include a HEIF-embedded gain map in the image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationPreserveGainMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationPreserveGainMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationPreserveGainMap"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationPreserveGainMap",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationpreservegainmap"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeGPS": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to exclude GPS metadata from EXIF data or the corresponding XMP tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataShouldExcludeGPS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeGPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataShouldExcludeGPS"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataShouldExcludeGPS",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatashouldexcludegps"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeXMP": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to exclude XMP data from the destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataShouldExcludeXMP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeXMP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataShouldExcludeXMP"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataShouldExcludeXMP",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatashouldexcludexmp"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Image-Behaviors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationLossyCompressionQuality",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationBackgroundColor",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationDateTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEmbedThumbnail",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationImageMaxPixelSize",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOptimizeColorForSharing",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOrientation",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationPreserveGainMap",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeGPS",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeXMP"
      ],
      "title": "Configuring the Image Behaviors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImageDestinationMergeMetadata"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationMergeMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Image-Behaviors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationLossyCompressionQuality",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationBackgroundColor",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationDateTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEmbedThumbnail",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationImageMaxPixelSize",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOptimizeColorForSharing",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOrientation",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationPreserveGainMap",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeGPS",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeXMP"
              ],
              "title": "Configuring the Image Behaviors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCGImageDestinationMergeMetadata"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataShouldExcludeGPS/title",
          "value": "kCGImageMetadataShouldExcludeGPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataShouldExcludeGPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataShouldExcludeGPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationOrientation/title",
          "value": "kCGImageDestinationOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationPreserveGainMap/title",
          "value": "kCGImageDestinationPreserveGainMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationPreserveGainMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationPreserveGainMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationBackgroundColor/title",
          "value": "kCGImageDestinationBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationBackgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfboolean/title",
          "value": "CFBooleanRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationMetadata/title",
          "value": "kCGImageDestinationMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationLossyCompressionQuality/title",
          "value": "kCGImageDestinationLossyCompressionQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationLossyCompressionQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationLossyCompressionQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationOptimizeColorForSharing/title",
          "value": "kCGImageDestinationOptimizeColorForSharing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationOptimizeColorForSharing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationOptimizeColorForSharing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationDateTime/title",
          "value": "kCGImageDestinationDateTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationDateTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationDateTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationImageMaxPixelSize/title",
          "value": "kCGImageDestinationImageMaxPixelSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationImageMaxPixelSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationImageMaxPixelSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataShouldExcludeXMP/title",
          "value": "kCGImageMetadataShouldExcludeXMP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataShouldExcludeXMP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataShouldExcludeXMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEmbedThumbnail/title",
          "value": "kCGImageDestinationEmbedThumbnail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEmbedThumbnail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationEmbedThumbnail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationMergeMetadata/title",
          "value": "kCGImageDestinationMergeMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationMergeMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationMergeMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/kcgimagedestinationmergemetadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/kcgimagedestinationmergemetadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
