{
  "abstract": [
    {
      "text": "Metadata keys for an image from a Nikon camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Nikon Camera Dictionary Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for an image from a Canon camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Canon Camera Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/canon-camera-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from an Apple camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerAppleDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerAppleDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerAppleDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerappledictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Fuji camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerFujiDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerFujiDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerFujiDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerfujidictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Minolta camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerMinoltaDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerMinoltaDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerMinoltaDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerminoltadictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonCameraSerialNumber": {
      "abstract": [
        {
          "text": "The camera serial number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonCameraSerialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonCameraSerialNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonCameraSerialNumber"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonCameraSerialNumber",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikoncameraserialnumber"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonColorMode": {
      "abstract": [
        {
          "text": "The color mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonColorMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonColorMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonColorMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonColorMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikoncolormode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Nikon camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikondictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDigitalZoom": {
      "abstract": [
        {
          "text": "The digital zoom setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonDigitalZoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDigitalZoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonDigitalZoom"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonDigitalZoom",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikondigitalzoom"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashExposureComp": {
      "abstract": [
        {
          "text": "The flash exposure compensation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFlashExposureComp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashExposureComp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFlashExposureComp"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonFlashExposureComp",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonflashexposurecomp"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashSetting": {
      "abstract": [
        {
          "text": "The flash setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFlashSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFlashSetting"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonFlashSetting",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonflashsetting"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusDistance": {
      "abstract": [
        {
          "text": "The focus distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFocusDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFocusDistance"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonFocusDistance",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonfocusdistance"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusMode": {
      "abstract": [
        {
          "text": "The focus mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFocusMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonFocusMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonFocusMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonfocusmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSelection": {
      "abstract": [
        {
          "text": "The ISO selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonISOSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonISOSelection"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonISOSelection",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonisoselection"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSetting": {
      "abstract": [
        {
          "text": "The ISO setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonISOSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonISOSetting"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonISOSetting",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonisosetting"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonImageAdjustment": {
      "abstract": [
        {
          "text": "The image adjustment setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonImageAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonImageAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonImageAdjustment"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonImageAdjustment",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonimageadjustment"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensAdapter": {
      "abstract": [
        {
          "text": "The lens adapter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonLensAdapter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensAdapter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonLensAdapter"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonLensAdapter",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonlensadapter"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensInfo": {
      "abstract": [
        {
          "text": "Lens information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonLensInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonLensInfo"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonLensInfo",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonlensinfo"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensType": {
      "abstract": [
        {
          "text": "The lens type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonLensType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonLensType"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonLensType",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonlenstype"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonQuality": {
      "abstract": [
        {
          "text": "The quality setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonQuality"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonQuality",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonquality"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonSharpenMode": {
      "abstract": [
        {
          "text": "The sharpening mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonSharpenMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonSharpenMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonSharpenMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonSharpenMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonsharpenmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShootingMode": {
      "abstract": [
        {
          "text": "The shooting mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonShootingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShootingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonShootingMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonShootingMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonshootingmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShutterCount": {
      "abstract": [
        {
          "text": "The number of times the shutter has been actuated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonShutterCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShutterCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonShutterCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonShutterCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonshuttercount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonWhiteBalanceMode": {
      "abstract": [
        {
          "text": "The white balance mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonWhiteBalanceMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonWhiteBalanceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerNikonWhiteBalanceMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerNikonWhiteBalanceMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakernikonwhitebalancemode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Olympus camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerOlympusDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerOlympusDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerOlympusDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerolympusdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Pentax camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerPentaxDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerPentaxDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerPentaxDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerpentaxdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that contains minimally processed, or raw, data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyRawDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyRawDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyRawDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyrawdictionary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Manufacturer-Specific-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary"
      ],
      "title": "Manufacturer-Specific Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "Program-Settings",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSetting",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSelection",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonColorMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonQuality",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonWhiteBalanceMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonSharpenMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashSetting",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonImageAdjustment",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShootingMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDigitalZoom",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShutterCount",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashExposureComp",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusDistance"
      ],
      "title": "Program Settings"
    },
    {
      "anchor": "Camera-Details",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensAdapter",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensType",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensInfo",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonCameraSerialNumber"
      ],
      "title": "Camera Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "Program-Settings",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSetting",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonISOSelection",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonColorMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonQuality",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonWhiteBalanceMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonSharpenMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashSetting",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonImageAdjustment",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShootingMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonDigitalZoom",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonShutterCount",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFlashExposureComp",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonFocusDistance"
              ],
              "title": "Program Settings"
            },
            {
              "anchor": "Camera-Details",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensAdapter",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensType",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonLensInfo",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerNikonCameraSerialNumber"
              ],
              "title": "Camera Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Manufacturer-Specific-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary"
              ],
              "title": "Manufacturer-Specific Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonSharpenMode/title",
          "value": "kCGImagePropertyMakerNikonSharpenMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonSharpenMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonSharpenMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonDictionary/title",
          "value": "kCGImagePropertyMakerNikonDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonLensAdapter/title",
          "value": "kCGImagePropertyMakerNikonLensAdapter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonLensAdapter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonLensAdapter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyRawDictionary/title",
          "value": "kCGImagePropertyRawDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyRawDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyRawDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonColorMode/title",
          "value": "kCGImagePropertyMakerNikonColorMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonColorMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonColorMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerAppleDictionary/title",
          "value": "kCGImagePropertyMakerAppleDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerAppleDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerAppleDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFocusMode/title",
          "value": "kCGImagePropertyMakerNikonFocusMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFocusMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonFocusMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerFujiDictionary/title",
          "value": "kCGImagePropertyMakerFujiDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerFujiDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerFujiDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonWhiteBalanceMode/title",
          "value": "kCGImagePropertyMakerNikonWhiteBalanceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonWhiteBalanceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonWhiteBalanceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFocusDistance/title",
          "value": "kCGImagePropertyMakerNikonFocusDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFocusDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonFocusDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerOlympusDictionary/title",
          "value": "kCGImagePropertyMakerOlympusDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerOlympusDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerOlympusDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFlashExposureComp/title",
          "value": "kCGImagePropertyMakerNikonFlashExposureComp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFlashExposureComp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonFlashExposureComp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonCameraSerialNumber/title",
          "value": "kCGImagePropertyMakerNikonCameraSerialNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonCameraSerialNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonCameraSerialNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonISOSetting/title",
          "value": "kCGImagePropertyMakerNikonISOSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonISOSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonISOSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonShootingMode/title",
          "value": "kCGImagePropertyMakerNikonShootingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonShootingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonShootingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonShutterCount/title",
          "value": "kCGImagePropertyMakerNikonShutterCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonShutterCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonShutterCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonLensInfo/title",
          "value": "kCGImagePropertyMakerNikonLensInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonLensInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonLensInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerMinoltaDictionary/title",
          "value": "kCGImagePropertyMakerMinoltaDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerMinoltaDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerMinoltaDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonImageAdjustment/title",
          "value": "kCGImagePropertyMakerNikonImageAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonImageAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonImageAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonQuality/title",
          "value": "kCGImagePropertyMakerNikonQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonLensType/title",
          "value": "kCGImagePropertyMakerNikonLensType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonLensType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonLensType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonDigitalZoom/title",
          "value": "kCGImagePropertyMakerNikonDigitalZoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonDigitalZoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonDigitalZoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerPentaxDictionary/title",
          "value": "kCGImagePropertyMakerPentaxDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerPentaxDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerPentaxDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFlashSetting/title",
          "value": "kCGImagePropertyMakerNikonFlashSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonFlashSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonFlashSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonISOSelection/title",
          "value": "kCGImagePropertyMakerNikonISOSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerNikonISOSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerNikonISOSelection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/nikon-camera-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/nikon-camera-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
