{
  "abstract": [
    {
      "text": "Metadata keys for the Portable Network Graphics (PNG) format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/png-image-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "PNG Image Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Adobe Photoshop image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "8BIM Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/8bim-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_ALL_FILTERS": {
      "abstract": [
        {
          "text": "All PNG filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_ALL_FILTERS"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_ALL_FILTERS",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGEIO_PNG_ALL_FILTERS",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_all_filters"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_AVG": {
      "abstract": [
        {
          "text": "A filter in which each byte is replaced with the difference between it and the average of the bytes above it and to its left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_AVG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_AVG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_AVG"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_FILTER_AVG",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_filter_avg"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_NONE": {
      "abstract": [
        {
          "text": "A filter in which each byte is unchanged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_NONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_NONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_NONE"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_FILTER_NONE",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_filter_none"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_PAETH": {
      "abstract": [
        {
          "text": "A filter in which each byte is replaced with the difference between it and the Paeth predictor of the bytes to its left, above, and upper left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_PAETH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_PAETH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_PAETH"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_FILTER_PAETH",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_filter_paeth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_SUB": {
      "abstract": [
        {
          "text": "A filter in which each byte is replaced with the difference between it and the corresponding byte to its left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_SUB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_SUB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_SUB"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_FILTER_SUB",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_filter_sub"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_UP": {
      "abstract": [
        {
          "text": "A filter in which each byte is replaced with the difference between it and the byte above it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_UP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_UP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_FILTER_UP"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_FILTER_UP",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_filter_up"
    },
    "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_NO_FILTERS": {
      "abstract": [
        {
          "text": "No PNG filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_NO_FILTERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_NO_FILTERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMAGEIO_PNG_NO_FILTERS"
        }
      ],
      "role": "symbol",
      "title": "IMAGEIO_PNG_NO_FILTERS",
      "type": "topic",
      "url": "/documentation/imageio/imageio_png_no_filters"
    },
    "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Camera Image File Format (CIFF) image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/ciff-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Digital Negative (DNG) archival format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/dng-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Graphics Interchange Format (GIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/gif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the High Efficiency Image Container (HEIC) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEIC Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/heic-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the JPEG File Interchange Format (JFIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "JFIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/jfif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGCanvasPixelHeight": {
      "abstract": [
        {
          "text": "The height of the main image, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGCanvasPixelHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGCanvasPixelHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGCanvasPixelHeight"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyAPNGCanvasPixelHeight",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyapngcanvaspixelheight"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGCanvasPixelWidth": {
      "abstract": [
        {
          "text": "The width of the main image, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGCanvasPixelWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGCanvasPixelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGCanvasPixelWidth"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyAPNGCanvasPixelWidth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyapngcanvaspixelwidth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGDelayTime": {
      "abstract": [
        {
          "text": "The number of seconds to wait before displaying the next image in an animated sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGDelayTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyAPNGDelayTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyapngdelaytime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGFrameInfoArray": {
      "abstract": [
        {
          "text": "An array of dictionaries that contain timing information for the image sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGFrameInfoArray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGFrameInfoArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGFrameInfoArray"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyAPNGFrameInfoArray",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyapngframeinfoarray"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGLoopCount": {
      "abstract": [
        {
          "text": "The number of times that an animated PNG should play through its frames before stopping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGLoopCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGLoopCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGLoopCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyAPNGLoopCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyapngloopcount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGUnclampedDelayTime": {
      "abstract": [
        {
          "text": "The number of seconds to wait before displaying the next image in an animated sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGUnclampedDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGUnclampedDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyAPNGUnclampedDelayTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyAPNGUnclampedDelayTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyapngunclampeddelaytime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGAuthor": {
      "abstract": [
        {
          "text": "A string that identifies the author of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGAuthor"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGAuthor",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngauthor"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGChromaticities": {
      "abstract": [
        {
          "text": "The chromaticities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGChromaticities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGChromaticities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGChromaticities"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGChromaticities",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngchromaticities"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGComment": {
      "abstract": [
        {
          "text": "A string that contains image comments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGComment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGComment"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGComment",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngcomment"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCompressionFilter": {
      "abstract": [
        {
          "text": "The PNG filter to apply prior to compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCompressionFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCompressionFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCompressionFilter"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGCompressionFilter",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngcompressionfilter"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCopyright": {
      "abstract": [
        {
          "text": "A string that identifies the copyright of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCopyright"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGCopyright",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngcopyright"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCreationTime": {
      "abstract": [
        {
          "text": "A string that identifies the date and time the image was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCreationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCreationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGCreationTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGCreationTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngcreationtime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDescription": {
      "abstract": [
        {
          "text": "A string that describes the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGDescription"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGDescription",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngdescription"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that uses Portable Network Graphics (PNG) format. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDisclaimer": {
      "abstract": [
        {
          "text": "A disclaimer string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGDisclaimer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDisclaimer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGDisclaimer"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGDisclaimer",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngdisclaimer"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGGamma": {
      "abstract": [
        {
          "text": "The gamma value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGGamma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGGamma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGGamma"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGGamma",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypnggamma"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGInterlaceType": {
      "abstract": [
        {
          "text": "The interlace type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGInterlaceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGInterlaceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGInterlaceType"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGInterlaceType",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypnginterlacetype"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGModificationTime": {
      "abstract": [
        {
          "text": "A string that identifies the last date and time the image was modified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGModificationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGModificationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGModificationTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGModificationTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngmodificationtime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSoftware": {
      "abstract": [
        {
          "text": "A string that identifies the software used to create the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGSoftware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSoftware",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGSoftware"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGSoftware",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngsoftware"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGSource"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGSource",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngsource"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTitle": {
      "abstract": [
        {
          "text": "A string that holds the image’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGTitle"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGTitle",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngtitle"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGWarning": {
      "abstract": [
        {
          "text": "A warning string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGWarning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGWarning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGWarning"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGWarning",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngwarning"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGXPixelsPerMeter": {
      "abstract": [
        {
          "text": "The number of x pixels per meter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGXPixelsPerMeter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGXPixelsPerMeter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGXPixelsPerMeter"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGXPixelsPerMeter",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngxpixelspermeter"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGYPixelsPerMeter": {
      "abstract": [
        {
          "text": "The number of y pixels per meter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGYPixelsPerMeter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGYPixelsPerMeter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGYPixelsPerMeter"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGYPixelsPerMeter",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngypixelspermeter"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGsRGBIntent": {
      "abstract": [
        {
          "text": "The sRGB intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGsRGBIntent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGsRGBIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPNGsRGBIntent"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPNGsRGBIntent",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertypngsrgbintent"
    },
    "doc://com.apple.imageio/documentation/ImageIO/png-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Portable Network Graphics (PNG) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/png-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Truevision Graphics Adapter (TGA) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TGA Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tga-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Tagged Image File Format (TIFF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tiff-image-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Specific-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
      ],
      "title": "Format-Specific Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSource"
      ],
      "title": "Properties"
    },
    {
      "anchor": "Image-Properties",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGCanvasPixelHeight",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGCanvasPixelWidth",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGXPixelsPerMeter",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGYPixelsPerMeter",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGGamma",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGInterlaceType",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGsRGBIntent",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGChromaticities"
      ],
      "title": "Image Properties"
    },
    {
      "anchor": "Sequence-Timing",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGFrameInfoArray",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGDelayTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGUnclampedDelayTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGLoopCount"
      ],
      "title": "Sequence Timing"
    },
    {
      "anchor": "Descriptive-Information",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTitle",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDescription",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGComment",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDisclaimer",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGWarning",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGAuthor",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCopyright",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCreationTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGModificationTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSoftware"
      ],
      "title": "Descriptive Information"
    },
    {
      "anchor": "Pre-Compression-Filters",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCompressionFilter",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_NO_FILTERS",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_NONE",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_SUB",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_UP",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_AVG",
        "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_PAETH"
      ],
      "title": "Pre-Compression Filters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSource"
              ],
              "title": "Properties"
            },
            {
              "anchor": "Image-Properties",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGCanvasPixelHeight",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGCanvasPixelWidth",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGXPixelsPerMeter",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGYPixelsPerMeter",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGGamma",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGInterlaceType",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGsRGBIntent",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGChromaticities"
              ],
              "title": "Image Properties"
            },
            {
              "anchor": "Sequence-Timing",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGFrameInfoArray",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGDelayTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGUnclampedDelayTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyAPNGLoopCount"
              ],
              "title": "Sequence Timing"
            },
            {
              "anchor": "Descriptive-Information",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGTitle",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDescription",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGComment",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGDisclaimer",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGWarning",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGAuthor",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCopyright",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCreationTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGModificationTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGSoftware"
              ],
              "title": "Descriptive Information"
            },
            {
              "anchor": "Pre-Compression-Filters",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPNGCompressionFilter",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_NO_FILTERS",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_NONE",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_SUB",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_UP",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_AVG",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_FILTER_PAETH",
                "doc://com.apple.imageio/documentation/ImageIO/IMAGEIO_PNG_ALL_FILTERS"
              ],
              "title": "Pre-Compression Filters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Specific-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
              ],
              "title": "Format-Specific Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCopyright/title",
          "value": "kCGImagePropertyPNGCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGModificationTime/title",
          "value": "kCGImagePropertyPNGModificationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGModificationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGModificationTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGsRGBIntent/title",
          "value": "kCGImagePropertyPNGsRGBIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGsRGBIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGsRGBIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGDescription/title",
          "value": "kCGImagePropertyPNGDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGCanvasPixelHeight/title",
          "value": "kCGImagePropertyAPNGCanvasPixelHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGCanvasPixelHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyAPNGCanvasPixelHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGYPixelsPerMeter/title",
          "value": "kCGImagePropertyPNGYPixelsPerMeter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGYPixelsPerMeter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGYPixelsPerMeter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGCanvasPixelWidth/title",
          "value": "kCGImagePropertyAPNGCanvasPixelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGCanvasPixelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyAPNGCanvasPixelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_NO_FILTERS/title",
          "value": "IMAGEIO_PNG_NO_FILTERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_NO_FILTERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_NO_FILTERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGAuthor/title",
          "value": "kCGImagePropertyPNGAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGFrameInfoArray/title",
          "value": "kCGImagePropertyAPNGFrameInfoArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGFrameInfoArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyAPNGFrameInfoArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGDisclaimer/title",
          "value": "kCGImagePropertyPNGDisclaimer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGDisclaimer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGDisclaimer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_PAETH/title",
          "value": "IMAGEIO_PNG_FILTER_PAETH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_PAETH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_FILTER_PAETH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGInterlaceType/title",
          "value": "kCGImagePropertyPNGInterlaceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGInterlaceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGInterlaceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGDictionary/title",
          "value": "kCGImagePropertyPNGDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_UP/title",
          "value": "IMAGEIO_PNG_FILTER_UP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_UP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_FILTER_UP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_NONE/title",
          "value": "IMAGEIO_PNG_FILTER_NONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_NONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_FILTER_NONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGLoopCount/title",
          "value": "kCGImagePropertyAPNGLoopCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGLoopCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyAPNGLoopCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGSource/title",
          "value": "kCGImagePropertyPNGSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGTitle/title",
          "value": "kCGImagePropertyPNGTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGDelayTime/title",
          "value": "kCGImagePropertyAPNGDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyAPNGDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGChromaticities/title",
          "value": "kCGImagePropertyPNGChromaticities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGChromaticities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGChromaticities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGXPixelsPerMeter/title",
          "value": "kCGImagePropertyPNGXPixelsPerMeter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGXPixelsPerMeter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGXPixelsPerMeter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGComment/title",
          "value": "kCGImagePropertyPNGComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_AVG/title",
          "value": "IMAGEIO_PNG_FILTER_AVG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_AVG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_FILTER_AVG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGSoftware/title",
          "value": "kCGImagePropertyPNGSoftware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGSoftware/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGSoftware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCreationTime/title",
          "value": "kCGImagePropertyPNGCreationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCreationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGCreationTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGGamma/title",
          "value": "kCGImagePropertyPNGGamma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGGamma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGGamma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCompressionFilter/title",
          "value": "kCGImagePropertyPNGCompressionFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGCompressionFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGCompressionFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGUnclampedDelayTime/title",
          "value": "kCGImagePropertyAPNGUnclampedDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyAPNGUnclampedDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyAPNGUnclampedDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_SUB/title",
          "value": "IMAGEIO_PNG_FILTER_SUB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1IMAGEIO_PNG_FILTER_SUB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMAGEIO_PNG_FILTER_SUB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGWarning/title",
          "value": "kCGImagePropertyPNGWarning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPNGWarning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPNGWarning"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/png-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/png-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
