{
  "abstract": [
    {
      "text": "Metadata keys for the Tagged Image File Format (TIFF).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "TIFF Image Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Adobe Photoshop image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "8BIM Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/8bim-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Camera Image File Format (CIFF) image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/ciff-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Digital Negative (DNG) archival format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/dng-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Graphics Interchange Format (GIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/gif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the High Efficiency Image Container (HEIC) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEIC Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/heic-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the JPEG File Interchange Format (JFIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "JFIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/jfif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFArtist": {
      "abstract": [
        {
          "text": "The artist who created the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFArtist"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFArtist",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffartist"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFCompression": {
      "abstract": [
        {
          "text": "The compression scheme used on the image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFCompression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFCompression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFCompression"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFCompression",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffcompression"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFCopyright": {
      "abstract": [
        {
          "text": "Copyright information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFCopyright"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFCopyright",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffcopyright"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDateTime": {
      "abstract": [
        {
          "text": "The date and time that the image was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFDateTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDateTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFDateTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFDateTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffdatetime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that uses Tagged Image File Format (TIFF). See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDocumentName": {
      "abstract": [
        {
          "text": "The document name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFDocumentName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDocumentName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFDocumentName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFDocumentName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffdocumentname"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFHostComputer": {
      "abstract": [
        {
          "text": "The computer or operating system used when the image was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFHostComputer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFHostComputer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFHostComputer"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFHostComputer",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffhostcomputer"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFImageDescription": {
      "abstract": [
        {
          "text": "The image description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFImageDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFImageDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFImageDescription"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFImageDescription",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffimagedescription"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFMake": {
      "abstract": [
        {
          "text": "The name of the manufacturer of the camera or input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFMake"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFMake",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFMake"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFMake",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffmake"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFModel": {
      "abstract": [
        {
          "text": "The camera or input device model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFModel"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFModel",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffmodel"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation": {
      "abstract": [
        {
          "text": "The image orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFOrientation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytifforientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPhotometricInterpretation": {
      "abstract": [
        {
          "text": "The color space of the image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFPhotometricInterpretation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPhotometricInterpretation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFPhotometricInterpretation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFPhotometricInterpretation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffphotometricinterpretation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPrimaryChromaticities": {
      "abstract": [
        {
          "text": "The chromaticities of the primaries of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFPrimaryChromaticities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPrimaryChromaticities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFPrimaryChromaticities"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFPrimaryChromaticities",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffprimarychromaticities"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFResolutionUnit": {
      "abstract": [
        {
          "text": "The units of resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFResolutionUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFResolutionUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFResolutionUnit"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFResolutionUnit",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffresolutionunit"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFSoftware": {
      "abstract": [
        {
          "text": "The name and version of the software used for image creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFSoftware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFSoftware",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFSoftware"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFSoftware",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffsoftware"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFTileLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFTileLength"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFTileLength",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytifftilelength"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileWidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFTileWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFTileWidth"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFTileWidth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytifftilewidth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTransferFunction": {
      "abstract": [
        {
          "text": "The transfer function, in tabular format, used to map pixel components from a nonlinear form into a linear form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFTransferFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTransferFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFTransferFunction"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFTransferFunction",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytifftransferfunction"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFWhitePoint": {
      "abstract": [
        {
          "text": "The white point of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFWhitePoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFWhitePoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFWhitePoint"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFWhitePoint",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffwhitepoint"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXResolution": {
      "abstract": [
        {
          "text": "The number of pixels per resolution unit in the image width direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFXResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFXResolution"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFXResolution",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffxresolution"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYResolution": {
      "abstract": [
        {
          "text": "The number of pixels per resolution unit in the image height direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFYResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFYResolution"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFYResolution",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytiffyresolution"
    },
    "doc://com.apple.imageio/documentation/ImageIO/png-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Portable Network Graphics (PNG) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/png-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Truevision Graphics Adapter (TGA) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TGA Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tga-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Tagged Image File Format (TIFF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tiff-image-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Specific-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
      ],
      "title": "Format-Specific Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "Image-Quality",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFCompression",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPhotometricInterpretation",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTransferFunction"
      ],
      "title": "Image Quality"
    },
    {
      "anchor": "Canvas-Details",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXResolution",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYResolution",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFResolutionUnit",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFWhitePoint",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPrimaryChromaticities",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileLength",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileWidth"
      ],
      "title": "Canvas Details"
    },
    {
      "anchor": "Descriptive-Information",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDocumentName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFImageDescription",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFArtist",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFCopyright",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDateTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFMake",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFModel",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFSoftware",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFHostComputer"
      ],
      "title": "Descriptive Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "Image-Quality",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFCompression",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPhotometricInterpretation",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTransferFunction"
              ],
              "title": "Image Quality"
            },
            {
              "anchor": "Canvas-Details",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFXResolution",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFYResolution",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFResolutionUnit",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFWhitePoint",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFPrimaryChromaticities",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileLength",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFTileWidth"
              ],
              "title": "Canvas Details"
            },
            {
              "anchor": "Descriptive-Information",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDocumentName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFImageDescription",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFArtist",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFCopyright",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFDateTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFMake",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFModel",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFSoftware",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFHostComputer"
              ],
              "title": "Descriptive Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Specific-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
              ],
              "title": "Format-Specific Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFSoftware/title",
          "value": "kCGImagePropertyTIFFSoftware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFSoftware/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFSoftware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFArtist/title",
          "value": "kCGImagePropertyTIFFArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFWhitePoint/title",
          "value": "kCGImagePropertyTIFFWhitePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFWhitePoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFWhitePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFDateTime/title",
          "value": "kCGImagePropertyTIFFDateTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFDateTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFDateTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFYResolution/title",
          "value": "kCGImagePropertyTIFFYResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFYResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFYResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFPrimaryChromaticities/title",
          "value": "kCGImagePropertyTIFFPrimaryChromaticities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFPrimaryChromaticities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFPrimaryChromaticities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFTransferFunction/title",
          "value": "kCGImagePropertyTIFFTransferFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFTransferFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFModel/title",
          "value": "kCGImagePropertyTIFFModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFResolutionUnit/title",
          "value": "kCGImagePropertyTIFFResolutionUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFResolutionUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFResolutionUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFXResolution/title",
          "value": "kCGImagePropertyTIFFXResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFXResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFXResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFCopyright/title",
          "value": "kCGImagePropertyTIFFCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFTileLength/title",
          "value": "kCGImagePropertyTIFFTileLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFTileLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFTileLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFTileWidth/title",
          "value": "kCGImagePropertyTIFFTileWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFTileWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFTileWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFPhotometricInterpretation/title",
          "value": "kCGImagePropertyTIFFPhotometricInterpretation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFPhotometricInterpretation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFPhotometricInterpretation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFHostComputer/title",
          "value": "kCGImagePropertyTIFFHostComputer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFHostComputer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFHostComputer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFMake/title",
          "value": "kCGImagePropertyTIFFMake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFMake/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFMake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFDictionary/title",
          "value": "kCGImagePropertyTIFFDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFCompression/title",
          "value": "kCGImagePropertyTIFFCompression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFCompression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFCompression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFImageDescription/title",
          "value": "kCGImagePropertyTIFFImageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFImageDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFImageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFOrientation/title",
          "value": "kCGImagePropertyTIFFOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFDocumentName/title",
          "value": "kCGImagePropertyTIFFDocumentName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFDocumentName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFDocumentName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/tiff-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/tiff-image-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
