{
  "abstract": [
    {
      "text": "Metadata keys for WebP metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/webp-data"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "WebP Data"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for Exchangeable Image File Format (EXIF) data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EXIF Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/exif-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys for Global Positioning System (GPS) information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GPS Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/gps-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-properties": {
      "abstract": [
        {
          "text": "Properties that apply to the container in general, and not necessarily to an individual image in the container.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for International Press Telecommunications Council (IPTC) data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPTC Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/iptc-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPCanvasPixelHeight": {
      "abstract": [
        {
          "text": "The height of the main image, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPCanvasPixelHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPCanvasPixelHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPCanvasPixelHeight"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyWebPCanvasPixelHeight",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertywebpcanvaspixelheight"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPCanvasPixelWidth": {
      "abstract": [
        {
          "text": "The width of the main image, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPCanvasPixelWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPCanvasPixelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPCanvasPixelWidth"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyWebPCanvasPixelWidth",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertywebpcanvaspixelwidth"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPDelayTime": {
      "abstract": [
        {
          "text": "The number of seconds to wait before displaying the next image in the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPDelayTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyWebPDelayTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertywebpdelaytime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPDictionary": {
      "abstract": [
        {
          "text": "A dictionary of properties related to a WebP container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyWebPDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertywebpdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPFrameInfoArray": {
      "abstract": [
        {
          "text": "An array of dictionaries that contain timing information for the image sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPFrameInfoArray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPFrameInfoArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPFrameInfoArray"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyWebPFrameInfoArray",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertywebpframeinfoarray"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPLoopCount": {
      "abstract": [
        {
          "text": "The number of times to play the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPLoopCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPLoopCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPLoopCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyWebPLoopCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertywebploopcount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPUnclampedDelayTime": {
      "abstract": [
        {
          "text": "The unadjusted number of seconds to wait before displaying the next image in the sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPUnclampedDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPUnclampedDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyWebPUnclampedDelayTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyWebPUnclampedDelayTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertywebpunclampeddelaytime"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common-Image-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys"
      ],
      "title": "Common Image Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "Image-Properties",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPCanvasPixelHeight",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPCanvasPixelWidth"
      ],
      "title": "Image Properties"
    },
    {
      "anchor": "Sequence-Timing",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPFrameInfoArray",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPDelayTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPUnclampedDelayTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPLoopCount"
      ],
      "title": "Sequence Timing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "Image-Properties",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPCanvasPixelHeight",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPCanvasPixelWidth"
              ],
              "title": "Image Properties"
            },
            {
              "anchor": "Sequence-Timing",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPFrameInfoArray",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPDelayTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPUnclampedDelayTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyWebPLoopCount"
              ],
              "title": "Sequence Timing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common-Image-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys"
              ],
              "title": "Common Image Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPCanvasPixelWidth/title",
          "value": "kCGImagePropertyWebPCanvasPixelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPCanvasPixelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyWebPCanvasPixelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPUnclampedDelayTime/title",
          "value": "kCGImagePropertyWebPUnclampedDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPUnclampedDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyWebPUnclampedDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPDictionary/title",
          "value": "kCGImagePropertyWebPDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyWebPDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPDelayTime/title",
          "value": "kCGImagePropertyWebPDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyWebPDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPLoopCount/title",
          "value": "kCGImagePropertyWebPLoopCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPLoopCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyWebPLoopCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPCanvasPixelHeight/title",
          "value": "kCGImagePropertyWebPCanvasPixelHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPCanvasPixelHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyWebPCanvasPixelHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPFrameInfoArray/title",
          "value": "kCGImagePropertyWebPFrameInfoArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyWebPFrameInfoArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyWebPFrameInfoArray"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/webp-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/webp-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
