{
  "abstract": [
    {
      "text": "Discover the public namespaces and prefixes that exist in XMP metadata tags.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/xmp-namespaces-and-prefixes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "XMP Namespaces and Prefixes"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata": {
      "abstract": [
        {
          "text": "An immutable object that contains the XMP metadata associated with an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadata"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadata"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadata",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors": {
      "abstract": [
        {
          "text": "Constants for errors that occur when getting or setting metadata information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataErrors"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataErrors"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataErrors",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadataerrors"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag": {
      "abstract": [
        {
          "text": "An immutable type that contains information about a single piece of image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataTag"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataTag"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataTag",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatag"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata": {
      "abstract": [
        {
          "text": "An opaque type for adding or modifying image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGMutableImageMetadata"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGMutableImageMetadata"
        }
      ],
      "role": "symbol",
      "title": "CGMutableImageMetadata",
      "type": "topic",
      "url": "/documentation/imageio/cgmutableimagemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata": {
      "abstract": [
        {
          "text": "The domain for metadata-related errors that originate in the Image I/O framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCGImageMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCGImageMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCFErrorDomainCGImageMetadata",
      "type": "topic",
      "url": "/documentation/imageio/kcferrordomaincgimagemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceDublinCore": {
      "abstract": [
        {
          "text": "The namespace for the Dublin Core Metadata Element Set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceDublinCore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceDublinCore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceDublinCore"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceDublinCore",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespacedublincore"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExif": {
      "abstract": [
        {
          "text": "The namespace for the Exchangeable Image File (EXIF) format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExif"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceExif",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespaceexif"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifAux": {
      "abstract": [
        {
          "text": "The namespace for EXIF auxiliary keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExifAux"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifAux",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExifAux"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceExifAux",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespaceexifaux"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifEX": {
      "abstract": [
        {
          "text": "The namespace for the exifEX format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExifEX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifEX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceExifEX"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceExifEX",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespaceexifex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceIPTCCore": {
      "abstract": [
        {
          "text": "The namespace for the IPTC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceIPTCCore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceIPTCCore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceIPTCCore"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceIPTCCore",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespaceiptccore"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespacePhotoshop": {
      "abstract": [
        {
          "text": "The namespace for Photoshop image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespacePhotoshop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespacePhotoshop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespacePhotoshop"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespacePhotoshop",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespacephotoshop"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceTIFF": {
      "abstract": [
        {
          "text": "The namespace for TIFF image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceTIFF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceTIFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceTIFF"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceTIFF",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespacetiff"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPBasic": {
      "abstract": [
        {
          "text": "The namespace for the Extensible Metadata Platform (XMP) format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceXMPBasic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPBasic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceXMPBasic"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceXMPBasic",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespacexmpbasic"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPRights": {
      "abstract": [
        {
          "text": "The namespace for XMP metadata that conveys legal restrictions associated with a resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceXMPRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPRights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataNamespaceXMPRights"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataNamespaceXMPRights",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatanamespacexmprights"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixDublinCore": {
      "abstract": [
        {
          "text": "The prefix string for tags in the Dublin Core Metadata Element Set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixDublinCore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixDublinCore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixDublinCore"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixDublinCore",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixdublincore"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExif": {
      "abstract": [
        {
          "text": "The prefix string for tags in the Exchangeable Image File (EXIF) metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExif"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixExif",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixexif"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifAux": {
      "abstract": [
        {
          "text": "The prefix string for tags in the EXIF auxiliary metadata collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExifAux"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifAux",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExifAux"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixExifAux",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixexifaux"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifEX": {
      "abstract": [
        {
          "text": "The prefix string for tags in the exifEX metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExifEX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifEX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixExifEX"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixExifEX",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixexifex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixIPTCCore": {
      "abstract": [
        {
          "text": "The prefix string for tags in the IPTC metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixIPTCCore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixIPTCCore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixIPTCCore"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixIPTCCore",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixiptccore"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixPhotoshop": {
      "abstract": [
        {
          "text": "The prefix string for tags in the Photoshop image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixPhotoshop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixPhotoshop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixPhotoshop"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixPhotoshop",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixphotoshop"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixTIFF": {
      "abstract": [
        {
          "text": "The prefix string for tags in the TIFF image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixTIFF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixTIFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixTIFF"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixTIFF",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixtiff"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPBasic": {
      "abstract": [
        {
          "text": "The prefix string for tags in the XMP metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixXMPBasic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPBasic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixXMPBasic"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixXMPBasic",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixxmpbasic"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPRights": {
      "abstract": [
        {
          "text": "The prefix string for tags in the XMP metadata that convey legal restrictions for the resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixXMPRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPRights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataPrefixXMPRights"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataPrefixXMPRights",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadataprefixxmprights"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "XMP-Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag",
        "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors"
      ],
      "title": "XMP Metadata"
    }
  ],
  "topicSections": [
    {
      "anchor": "Public-Namespaces",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceDublinCore",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExif",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifAux",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifEX",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceIPTCCore",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespacePhotoshop",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceTIFF",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPBasic",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPRights"
      ],
      "title": "Public Namespaces"
    },
    {
      "anchor": "Public-Prefixes",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixDublinCore",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExif",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifAux",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifEX",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixIPTCCore",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixPhotoshop",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixTIFF",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPBasic",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPRights"
      ],
      "title": "Public Prefixes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Public-Namespaces",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceDublinCore",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExif",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifAux",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceExifEX",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceIPTCCore",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespacePhotoshop",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceTIFF",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPBasic",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataNamespaceXMPRights"
              ],
              "title": "Public Namespaces"
            },
            {
              "anchor": "Public-Prefixes",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixDublinCore",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExif",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifAux",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixExifEX",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixIPTCCore",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixPhotoshop",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixTIFF",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPBasic",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataPrefixXMPRights"
              ],
              "title": "Public Prefixes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "XMP-Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag",
                "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors"
              ],
              "title": "XMP Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataTag/title",
          "value": "CGImageMetadataTagRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataTagRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataTagRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataErrors/title",
          "value": "CGImageMetadataErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataErrors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataErrors/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixXMPRights/title",
          "value": "kCGImageMetadataPrefixXMPRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixXMPRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixXMPRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCFErrorDomainCGImageMetadata/title",
          "value": "kCFErrorDomainCGImageMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCFErrorDomainCGImageMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFErrorDomainCGImageMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExifAux/title",
          "value": "kCGImageMetadataNamespaceExifAux"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExifAux/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceExifAux"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExifAux/title",
          "value": "kCGImageMetadataPrefixExifAux"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExifAux/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixExifAux"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceTIFF/title",
          "value": "kCGImageMetadataNamespaceTIFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceTIFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceTIFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixTIFF/title",
          "value": "kCGImageMetadataPrefixTIFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixTIFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixTIFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixPhotoshop/title",
          "value": "kCGImageMetadataPrefixPhotoshop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixPhotoshop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixPhotoshop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixXMPBasic/title",
          "value": "kCGImageMetadataPrefixXMPBasic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixXMPBasic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixXMPBasic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceDublinCore/title",
          "value": "kCGImageMetadataNamespaceDublinCore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceDublinCore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceDublinCore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExif/title",
          "value": "kCGImageMetadataPrefixExif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixExif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceXMPBasic/title",
          "value": "kCGImageMetadataNamespaceXMPBasic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceXMPBasic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceXMPBasic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExif/title",
          "value": "kCGImageMetadataNamespaceExif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceExif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixIPTCCore/title",
          "value": "kCGImageMetadataPrefixIPTCCore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixIPTCCore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixIPTCCore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespacePhotoshop/title",
          "value": "kCGImageMetadataNamespacePhotoshop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespacePhotoshop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespacePhotoshop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixDublinCore/title",
          "value": "kCGImageMetadataPrefixDublinCore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixDublinCore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixDublinCore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceXMPRights/title",
          "value": "kCGImageMetadataNamespaceXMPRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceXMPRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceXMPRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExifEX/title",
          "value": "kCGImageMetadataNamespaceExifEX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceExifEX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceExifEX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExifEX/title",
          "value": "kCGImageMetadataPrefixExifEX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataPrefixExifEX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataPrefixExifEX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/title",
          "value": "CGMutableImageMetadataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceIPTCCore/title",
          "value": "kCGImageMetadataNamespaceIPTCCore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataNamespaceIPTCCore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataNamespaceIPTCCore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadata/title",
          "value": "CGImageMetadataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/xmp-namespaces-and-prefixes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/xmp-namespaces-and-prefixes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
