{
  "abstract": [
    {
      "text": "The selection moves to the next word boundary ignoring punctuation, whitespace, and format characters preceding the next word.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/word"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextSelectionNavigationDestination@NSTextSelectionNavigationDestinationWord",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "word"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextSelectionNavigationDestinationWord"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTextSelectionNavigation.Destination.word"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "word"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation": {
      "abstract": [
        {
          "text": "An interface you use to expose methods for obtaining results from actions performed on text selections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigation"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination": {
      "abstract": [
        {
          "text": "Values that affect how the framework handles navigation across different textual boundaries during a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Destination"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Destination"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Destination",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/destination"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/character": {
      "abstract": [
        {
          "text": "The selection moves to the next extended grapheme cluster boundary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "character"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/character",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDestinationCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Destination.character",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/destination/character"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/container": {
      "abstract": [
        {
          "text": "The selection moves to the next container or page boundary after boundary of the current container, ignoring the end of line elastic characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "container"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/container",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDestinationContainer"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Destination.container",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/destination/container"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/document": {
      "abstract": [
        {
          "text": "The selection moves to the document boundary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "document"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/document",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDestinationDocument"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Destination.document",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/destination/document"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/line": {
      "abstract": [
        {
          "text": "The selection moves to the next line boundary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/line",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDestinationLine"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Destination.line",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/destination/line"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/paragraph": {
      "abstract": [
        {
          "text": "The selection moves to the next paragraph boundary, ignoring the end of line elastic characters and paragraph separators.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraph"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/paragraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDestinationParagraph"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Destination.paragraph",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/destination/paragraph"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/sentence": {
      "abstract": [
        {
          "text": "The selection moves to the next sentence boundary, ignoring punctuation, whitespace, and format characters preceding the next sentence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentence"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/sentence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDestinationSentence"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Destination.sentence",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/destination/sentence"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/word": {
      "abstract": [
        {
          "text": "The selection moves to the next word boundary ignoring punctuation, whitespace, and format characters preceding the next word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "word"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/word",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigationDestinationWord"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Destination.word",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/destination/word"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selection-destinations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/character",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/line",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/sentence",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/paragraph",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/container",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/document"
      ],
      "title": "Selection destinations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextSelectionNavigationDestinationWord"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestinationWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selection-destinations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/character",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/line",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/sentence",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/paragraph",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/container",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/Destination/document"
              ],
              "title": "Selection destinations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTextSelectionNavigationDestinationWord"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1line/title",
          "value": "NSTextSelectionNavigationDestinationLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1line/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestinationLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1character/title",
          "value": "NSTextSelectionNavigationDestinationCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1character/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestinationCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation/title",
          "value": "NSTextSelectionNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1word/title",
          "value": "NSTextSelectionNavigationDestinationWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1word/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestinationWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1document/title",
          "value": "NSTextSelectionNavigationDestinationDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1document/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestinationDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination/title",
          "value": "NSTextSelectionNavigationDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1sentence/title",
          "value": "NSTextSelectionNavigationDestinationSentence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1sentence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestinationSentence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1paragraph/title",
          "value": "NSTextSelectionNavigationDestinationParagraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1paragraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestinationParagraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1container/title",
          "value": "NSTextSelectionNavigationDestinationContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1Destination~1container/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestinationContainer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextselectionnavigation/destination/word"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextselectionnavigation/destination/word"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
