{
  "abstract": [
    {
      "text": "The interval between the time playback ends and automatic acceptance of this content proposal.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/automaticAcceptanceInterval"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVContentProposal(py)automaticAcceptanceInterval",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "automaticAcceptanceInterval"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTimeInterval",
        "text": "TimeInterval"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "automaticAcceptanceInterval"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "automaticAcceptanceInterval"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "automaticAcceptanceInterval"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTimeInterval",
              "text": "TimeInterval"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The content proposal displays a countdown timer to reflect this value. Set this value to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/Double/nan",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to disable the default, which is automatic acceptance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal": {
      "abstract": [
        {
          "text": "An object that describes the content to propose playing after the current item finishes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentProposal"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentProposal"
        }
      ],
      "role": "symbol",
      "title": "AVContentProposal",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/automaticAcceptanceInterval": {
      "abstract": [
        {
          "text": "The interval between the time playback ends and automatic acceptance of this content proposal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticAcceptanceInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/automaticAcceptanceInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticAcceptanceInterval"
        }
      ],
      "role": "symbol",
      "title": "automaticAcceptanceInterval",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/automaticacceptanceinterval"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/contentTimeForTransition": {
      "abstract": [
        {
          "text": "The time within the timeline of the current player item when the content proposal presentation should begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentTimeForTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/contentTimeForTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentTimeForTransition"
        }
      ],
      "role": "symbol",
      "title": "contentTimeForTransition",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/contenttimefortransition"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/metadata": {
      "abstract": [
        {
          "text": "Optional custom metadata associated with the proposed item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/metadata"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/previewImage": {
      "abstract": [
        {
          "text": "The preview image of the proposed item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/previewImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewImage"
        }
      ],
      "role": "symbol",
      "title": "previewImage",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/previewimage"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/title": {
      "abstract": [
        {
          "text": "The title of the proposed content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/title"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/url": {
      "abstract": [
        {
          "text": "The URL of the proposed content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/url"
    },
    "doc://com.apple.documentation/documentation/Swift/Double/nan": {
      "abstract": [
        {
          "text": "A quiet NaN (“not a number”).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Double/nan",
      "kind": "symbol",
      "role": "symbol",
      "title": "nan",
      "type": "topic",
      "url": "/documentation/Swift/Double/nan"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "TimeInterval",
      "type": "topic",
      "url": "/documentation/foundation/timeinterval"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Content-Proposal",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/contentTimeForTransition",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/title",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/previewImage",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/metadata",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/url"
      ],
      "title": "Configuring the Content Proposal"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "automaticAcceptanceInterval"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticAcceptanceInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Content-Proposal",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/contentTimeForTransition",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/title",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/previewImage",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/metadata",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/url"
              ],
              "title": "Configuring the Content Proposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSTimeInterval",
                    "text": "NSTimeInterval"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "automaticAcceptanceInterval"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title",
          "value": "NSTimeInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1automaticAcceptanceInterval/title",
          "value": "automaticAcceptanceInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1automaticAcceptanceInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticAcceptanceInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1previewImage/title",
          "value": "previewImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1previewImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1contentTimeForTransition/title",
          "value": "contentTimeForTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1contentTimeForTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentTimeForTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal/title",
          "value": "AVContentProposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avcontentproposal/automaticacceptanceinterval"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avcontentproposal/automaticacceptanceinterval"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
