{
  "abstract": [
    {
      "text": "A configuration that specifies the appearance and behavior of a button and its contents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIButton"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:So8UIButtonC5UIKitE13ConfigurationV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Configuration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Configuration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIButton.Configuration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Configuration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can configure and update a button with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". A button configuration contains all the customization options available with other methods, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/setTitle(_:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and can serve as a replacement for those methods. Alternatively, you can use a configuration in combination with these other methods and adopt new button behaviors and appearance without rewriting your customized ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton": {
      "abstract": [
        {
          "text": "A control that executes your custom code in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "role": "symbol",
      "title": "UIButton",
      "type": "topic",
      "url": "/documentation/uikit/uibutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct": {
      "abstract": [
        {
          "text": "A configuration that specifies the appearance and behavior of a button and its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "UIButton.Configuration",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum": {
      "abstract": [
        {
          "text": "Settings that determine the appearance of the background corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CornerStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CornerStyle"
        }
      ],
      "role": "symbol",
      "title": "UIButton.Configuration.CornerStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/cornerstyle-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/Indicator-swift.enum": {
      "abstract": [
        {
          "text": "Constants that determine the style of the indicator that appears on a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Indicator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/Indicator-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Indicator"
        }
      ],
      "role": "symbol",
      "title": "UIButton.Configuration.Indicator",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/indicator-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/MacIdiomStyle-swift.enum": {
      "abstract": [
        {
          "text": "The button style your app uses when running in macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MacIdiomStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/MacIdiomStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MacIdiomStyle"
        }
      ],
      "role": "symbol",
      "title": "UIButton.Configuration.MacIdiomStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/macidiomstyle-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/Size": {
      "abstract": [
        {
          "text": "A predefined size for button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Size"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/Size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Size"
        }
      ],
      "role": "symbol",
      "title": "UIButton.Configuration.Size",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/size"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/TitleAlignment-swift.enum": {
      "abstract": [
        {
          "text": "Specifies how to align a button’s title and subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TitleAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/TitleAlignment-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TitleAlignment"
        }
      ],
      "role": "symbol",
      "title": "UIButton.Configuration.TitleAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/titlealignment-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/activityIndicatorColorTransformer": {
      "abstract": [
        {
          "text": "The color transformer for resolving the color of the activity indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityIndicatorColorTransformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit31UIConfigurationColorTransformerV",
          "text": "UIConfigurationColorTransformer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/activityIndicatorColorTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "activityIndicatorColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/activityindicatorcolortransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedSubtitle": {
      "abstract": [
        {
          "text": "The text and style attributes for the button’s subtitle label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedSubtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation16AttributedStringV",
          "text": "AttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedSubtitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedSubtitle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/attributedsubtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedTitle": {
      "abstract": [
        {
          "text": "The text and style attributes for the button’s title label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation16AttributedStringV",
          "text": "AttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedTitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedTitle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/attributedtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/automaticallyUpdateForSelection": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the style automatically updates when the button is in a selected state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallyUpdateForSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/automaticallyUpdateForSelection",
      "kind": "symbol",
      "role": "symbol",
      "title": "automaticallyUpdateForSelection",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/automaticallyupdateforselection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/background": {
      "abstract": [
        {
          "text": "The configuration to customize the button background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "background"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit25UIBackgroundConfigurationV",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/background",
      "kind": "symbol",
      "role": "symbol",
      "title": "background",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/background"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/baseBackgroundColor": {
      "abstract": [
        {
          "text": "The untransformed color for background views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseBackgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/baseBackgroundColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "baseBackgroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/basebackgroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/baseForegroundColor": {
      "abstract": [
        {
          "text": "The untransformed color for foreground views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseForegroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/baseForegroundColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "baseForegroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/baseforegroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/bordered()": {
      "abstract": [
        {
          "text": "Creates a configuration for a button that has a bordered style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bordered"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/bordered()",
      "kind": "symbol",
      "role": "symbol",
      "title": "bordered()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/bordered()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/borderedProminent()": {
      "abstract": [
        {
          "text": "Creates a configuration for a button that has a prominent, bordered style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderedProminent"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/borderedProminent()",
      "kind": "symbol",
      "role": "symbol",
      "title": "borderedProminent()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/borderedprominent()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/borderedTinted()": {
      "abstract": [
        {
          "text": "Creates a configuration for a button that has a tinted, bordered style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderedTinted"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/borderedTinted()",
      "kind": "symbol",
      "role": "symbol",
      "title": "borderedTinted()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/borderedtinted()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/borderless()": {
      "abstract": [
        {
          "text": "Creates a configuration for a button that has a borderless style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderless"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/borderless()",
      "kind": "symbol",
      "role": "symbol",
      "title": "borderless()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/borderless()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/buttonSize": {
      "abstract": [
        {
          "text": "A size that requests a preferred size for the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV4SizeO",
          "text": "Size"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/buttonSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "buttonSize",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/buttonsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/contentInsets": {
      "abstract": [
        {
          "text": "The distance from the button’s content area to its bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/contentInsets",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentInsets",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/contentinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/cornerStyle-swift.property": {
      "abstract": [
        {
          "text": "The button style that controls the display behavior of the background corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cornerStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV11CornerStyleO",
          "text": "CornerStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/cornerStyle-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "cornerStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/cornerstyle-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/filled()": {
      "abstract": [
        {
          "text": "Creates a configuration for a button with a background filled with the button’s tint color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/filled()",
      "kind": "symbol",
      "role": "symbol",
      "title": "filled()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/filled()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/gray()": {
      "abstract": [
        {
          "text": "Creates a configuration for a button with a gray background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gray"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/gray()",
      "kind": "symbol",
      "role": "symbol",
      "title": "gray()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/gray()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/image": {
      "abstract": [
        {
          "text": "The foreground image the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/image",
      "kind": "symbol",
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imageColorTransformer": {
      "abstract": [
        {
          "text": "A block that transforms the image color when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageColorTransformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit31UIConfigurationColorTransformerV",
          "text": "UIConfigurationColorTransformer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imageColorTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/imagecolortransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imagePadding": {
      "abstract": [
        {
          "text": "The distance between the button’s image and text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imagePadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imagePadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "imagePadding",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/imagepadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imagePlacement": {
      "abstract": [
        {
          "text": "The edge against which the button places the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imagePlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDirectionalRectEdge",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imagePlacement",
      "kind": "symbol",
      "role": "symbol",
      "title": "imagePlacement",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/imageplacement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imageReservation": {
      "abstract": [
        {
          "text": "A value that reserves space for the image in the same axis as the edge against which the button places the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageReservation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imageReservation",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageReservation",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/imagereservation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/indicator-swift.property": {
      "abstract": [
        {
          "text": "The style of the indicator that appears on the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indicator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV9IndicatorO",
          "text": "Indicator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/indicator-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "indicator",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/indicator-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/indicatorColorTransformer": {
      "abstract": [
        {
          "text": "The color transformer for resolving the indicator color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indicatorColorTransformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit31UIConfigurationColorTransformerV",
          "text": "UIConfigurationColorTransformer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/indicatorColorTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "indicatorColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/indicatorcolortransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/macIdiomStyle-swift.property": {
      "abstract": [
        {
          "text": "The style to use when this button appears in macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macIdiomStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV13MacIdiomStyleO",
          "text": "MacIdiomStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/macIdiomStyle-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "macIdiomStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/macidiomstyle-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/plain()": {
      "abstract": [
        {
          "text": "Creates a configuration for a button with a transparent background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plain"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/plain()",
      "kind": "symbol",
      "role": "symbol",
      "title": "plain()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/plain()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/preferredSymbolConfigurationForImage": {
      "abstract": [
        {
          "text": "A requested configuration object for the button symbol image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredSymbolConfigurationForImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImageSymbolConfiguration",
          "text": "SymbolConfiguration"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/preferredSymbolConfigurationForImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredSymbolConfigurationForImage",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/preferredsymbolconfigurationforimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/setDefaultContentInsets()": {
      "abstract": [
        {
          "text": "Restores the default content insets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDefaultContentInsets"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/setDefaultContentInsets()",
      "kind": "symbol",
      "role": "symbol",
      "title": "setDefaultContentInsets()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/setdefaultcontentinsets()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/showsActivityIndicator": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the button displays an activity indicator instead of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsActivityIndicator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/showsActivityIndicator",
      "kind": "symbol",
      "role": "symbol",
      "title": "showsActivityIndicator",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/showsactivityindicator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitle": {
      "abstract": [
        {
          "text": "The text the subtitle label of the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/subtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleLineBreakMode": {
      "abstract": [
        {
          "text": "The line break mode the button uses to lay out the button’s subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitleLineBreakMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakMode",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleLineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitleLineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/subtitlelinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleTextAttributesTransformer": {
      "abstract": [
        {
          "text": "A structure to update the attributed subtitle when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitleTextAttributesTransformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit40UIConfigurationTextAttributesTransformerV",
          "text": "UIConfigurationTextAttributesTransformer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleTextAttributesTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitleTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/subtitletextattributestransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/tinted()": {
      "abstract": [
        {
          "text": "Creates a configuration for a button with a tinted background color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tinted"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/tinted()",
      "kind": "symbol",
      "role": "symbol",
      "title": "tinted()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/tinted()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/title": {
      "abstract": [
        {
          "text": "The text of the title label the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/title",
      "kind": "symbol",
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/title"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleAlignment-swift.property": {
      "abstract": [
        {
          "text": "The text alignment the button uses to lay out the title and subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV14TitleAlignmentO",
          "text": "TitleAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleAlignment-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/titlealignment-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleLineBreakMode": {
      "abstract": [
        {
          "text": "The line break mode the button uses to lay out the button’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleLineBreakMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakMode",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleLineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleLineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/titlelinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titlePadding": {
      "abstract": [
        {
          "text": "The distance between the title and subtitle labels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titlePadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titlePadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "titlePadding",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/titlepadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleTextAttributesTransformer": {
      "abstract": [
        {
          "text": "A structure to update the attributed title when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleTextAttributesTransformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit40UIConfigurationTextAttributesTransformerV",
          "text": "UIConfigurationTextAttributesTransformer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleTextAttributesTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/titletextattributestransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/updated(for:)": {
      "abstract": [
        {
          "text": "Returns a copy of the configuration, updated for the given button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updated"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/updated(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updated(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/updated(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/init(configuration:primaryAction:)": {
      "abstract": [
        {
          "text": "Creates a new button with the specified configuration and registers the primary action event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "primaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/init(configuration:primaryAction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(configuration:primaryAction:)",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/init(configuration:primaryaction:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/setTitle(_:for:)": {
      "abstract": [
        {
          "text": "Sets the title to use for the specified state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTitle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/setTitle(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitle:forState:"
        }
      ],
      "role": "symbol",
      "title": "setTitle(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/settitle(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-swift.struct": {
      "abstract": [
        {
          "text": "Defines a text transformation that can affect the visual appearance of a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIConfigurationTextAttributesTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIConfigurationTextAttributesTransformer"
        }
      ],
      "role": "symbol",
      "title": "UIConfigurationTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationtextattributestransformer-swift.struct"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-buttons-from-a-configuration-object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/init(configuration:primaryAction:)"
      ],
      "title": "Creating buttons from a configuration object"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-configurations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/plain()",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/gray()",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/tinted()",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/filled()",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/borderless()",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/bordered()",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/borderedTinted()",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/borderedProminent()",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/updated(for:)"
      ],
      "title": "Creating configurations"
    },
    {
      "anchor": "Configuring-titles",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/title",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedTitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedSubtitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleTextAttributesTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleTextAttributesTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titlePadding",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleAlignment-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/TitleAlignment-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleLineBreakMode",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleLineBreakMode"
      ],
      "title": "Configuring titles"
    },
    {
      "anchor": "Configuring-images",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/image",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imagePadding",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imagePlacement",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imageReservation",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/imageColorTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/preferredSymbolConfigurationForImage"
      ],
      "title": "Configuring images"
    },
    {
      "anchor": "Configuring-layout",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/buttonSize",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/Size",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/contentInsets",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/setDefaultContentInsets()"
      ],
      "title": "Configuring layout"
    },
    {
      "anchor": "Configuring-button-colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/baseBackgroundColor",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/baseForegroundColor"
      ],
      "title": "Configuring button colors"
    },
    {
      "anchor": "Configuring-the-button-background",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/background",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/cornerStyle-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum"
      ],
      "title": "Configuring the button background"
    },
    {
      "anchor": "Configuring-the-indicator",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/indicator-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/Indicator-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/indicatorColorTransformer"
      ],
      "title": "Configuring the indicator"
    },
    {
      "anchor": "Configuring-the-activity-indicator",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/showsActivityIndicator",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/activityIndicatorColorTransformer"
      ],
      "title": "Configuring the activity indicator"
    },
    {
      "anchor": "Configuring-selection-behavior",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/automaticallyUpdateForSelection"
      ],
      "title": "Configuring selection behavior"
    },
    {
      "anchor": "Configuring-the-appearance-on-macOS",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/macIdiomStyle-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/MacIdiomStyle-swift.enum"
      ],
      "title": "Configuring the appearance on macOS"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title",
          "value": "UIButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1setTitle(_:for:)/title",
          "value": "setTitle:forState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1setTitle(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTitle:forState:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibutton/configuration-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
