{"variants":[{"paths":["/documentation/uikit/uibutton/configurationupdatehandler-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uibutton/configurationupdatehandler-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIButton"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configurationUpdateHandler","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIButton","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton","preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ConfigurationUpdateHandler","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/ConfigurationUpdateHandler-swift.typealias","preciseIdentifier":"c:@T@UIButtonConfigurationUpdateHandler","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Use this property as an alternative to overriding "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()"},{"type":"text","text":". Set a closure to respond to button state changes by updating the button configuration."}],"type":"paragraph"},{"inlineContent":[{"text":"In iOS 18 and later, UIKit supports automatic trait tracking inside this closure for traits from this button’s ","type":"text"},{"type":"codeVoice","code":"traitCollection"},{"text":". For more information, see ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIButton/configurationUpdateHandler-swift.property"},"seeAlsoSections":[{"title":"Buttons","anchor":"Buttons","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A closure that executes when the button state changes.","type":"text"}],"sections":[],"metadata":{"externalID":"c:objc(cs)UIButton(py)configurationUpdateHandler","symbolKind":"property","platforms":[{"introducedAt":"15.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"15.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"15.0","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"15.0","unavailable":false,"beta":false,"deprecated":false,"name":"tvOS"},{"introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"}],"title":"configurationUpdateHandler","modules":[{"name":"UIKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"configurationUpdateHandler"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationUpdateHandler"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier","text":"UIButton"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@UIButtonConfigurationUpdateHandler","kind":"typeIdentifier","text":"ConfigurationUpdateHandler"},{"kind":"text","text":"?"}],"role":"symbol"},"references":{"doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()":{"navigatorTitle":[{"text":"updateConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateConfiguration","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()","url":"/documentation/uikit/uibutton/updateconfiguration()","title":"updateConfiguration()","abstract":[{"text":"Updates the button configuration in response to a button state change.","type":"text"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIButton/ConfigurationUpdateHandler-swift.typealias":{"type":"topic","role":"symbol","kind":"symbol","title":"UIButton.ConfigurationUpdateHandler","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/ConfigurationUpdateHandler-swift.typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConfigurationUpdateHandler","kind":"identifier"}],"abstract":[{"text":"A closure to update the configuration of a button.","type":"text"}],"url":"/documentation/uikit/uibutton/configurationupdatehandler-swift.typealias","navigatorTitle":[{"text":"ConfigurationUpdateHandler","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIButton/configurationUpdateHandler-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"configurationUpdateHandler"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configurationUpdateHandler","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIButtonConfigurationUpdateHandler","text":"ConfigurationUpdateHandler"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/configurationUpdateHandler-swift.property","url":"/documentation/uikit/uibutton/configurationupdatehandler-swift.property","title":"configurationUpdateHandler","abstract":[{"text":"A closure that executes when the button state changes.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIButton":{"role":"symbol","abstract":[{"type":"text","text":"A control that executes your custom code in response to user interactions."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIButton"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton","title":"UIButton","navigatorTitle":[{"kind":"identifier","text":"UIButton"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uibutton"},"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking":{"kind":"article","abstract":[{"text":"Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.","type":"text"}],"url":"/documentation/uikit/automatic-trait-tracking","identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","title":"Automatic trait tracking","role":"collectionGroup","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"15.0"},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"15.0"},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"15.0"},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"15.0"},{"introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"configurationUpdateHandler"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"configurationUpdateHandler"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIButton"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()"],"anchor":"Buttons","title":"Buttons"}]},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/ConfigurationUpdateHandler-swift.typealias","preciseIdentifier":"c:@T@UIButtonConfigurationUpdateHandler","kind":"typeIdentifier","text":"UIButtonConfigurationUpdateHandler"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationUpdateHandler"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1updateConfiguration()/title","op":"replace","value":"updateConfiguration"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1updateConfiguration()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateConfiguration","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ConfigurationUpdateHandler-swift.typealias/title","op":"replace","value":"UIButtonConfigurationUpdateHandler"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ConfigurationUpdateHandler-swift.typealias/fragments","op":"replace","value":[{"kind":"identifier","text":"UIButtonConfigurationUpdateHandler"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1ConfigurationUpdateHandler-swift.typealias/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIButtonConfigurationUpdateHandler"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1configurationUpdateHandler-swift.property/title","op":"replace","value":"configurationUpdateHandler"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1configurationUpdateHandler-swift.property/fragments","op":"replace","value":[{"text":"configurationUpdateHandler","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title","op":"replace","value":"UIButton"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments","op":"replace","value":[{"kind":"identifier","text":"UIButton"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}