{"abstract":[{"text":"The current styled title that is displayed on the button.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIButton"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentAttributedTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The value for this property reflects the title associated with the control’s current state. For states that do not have a custom title string associated with them, this method returns the attributed title that is currently displayed, which is typically the one associated with the "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","isActive":true,"type":"reference"},{"type":"text","text":" state."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIButton/currentAttributedTitle"},"metadata":{"title":"currentAttributedTitle","platforms":[{"name":"iOS","introducedAt":"6.0","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","introducedAt":"6.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentAttributedTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:objc(cs)UIButton(py)currentAttributedTitle","modules":[{"name":"UIKit"}],"navigatorTitle":[{"text":"currentAttributedTitle","kind":"identifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uibutton/currentattributedtitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uibutton/currentattributedtitle"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","seeAlsoSections":[{"title":"Getting the current state","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIButton/buttonType-swift.property","doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitle","doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitleColor","doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitleShadowColor","doc://com.apple.uikit/documentation/UIKit/UIButton/currentImage","doc://com.apple.uikit/documentation/UIKit/UIButton/currentBackgroundImage","doc://com.apple.uikit/documentation/UIKit/UIButton/currentPreferredSymbolConfiguration","doc://com.apple.uikit/documentation/UIKit/UIButton/imageView","doc://com.apple.uikit/documentation/UIKit/UIButton/subtitleLabel"],"generated":true,"anchor":"Getting-the-current-state"}],"sections":[],"references":{"doc://com.apple.uikit/documentation/UIKit/UIButton/currentImage":{"title":"currentImage","url":"/documentation/uikit/uibutton/currentimage","abstract":[{"type":"text","text":"The current image displayed on the button."}],"navigatorTitle":[{"kind":"identifier","text":"currentImage"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/currentImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitle":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentTitle"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uibutton/currenttitle","title":"currentTitle","abstract":[{"type":"text","text":"The current title that is displayed on the button."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitle","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"currentTitle","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal":{"title":"normal","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState","text":"State"}],"navigatorTitle":[{"kind":"identifier","text":"UIControlStateNormal"}],"url":"/documentation/uikit/uicontrol/state-swift.struct/normal","abstract":[{"type":"text","text":"The normal, or default, state of a control where the control is enabled but neither selected nor highlighted."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIButton/imageView":{"title":"imageView","url":"/documentation/uikit/uibutton/imageview","abstract":[{"type":"text","text":"The button’s image view."}],"navigatorTitle":[{"kind":"identifier","text":"imageView"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/imageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIButton/buttonType-swift.property":{"type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/buttonType-swift.property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"text":".","kind":"text"},{"text":"ButtonType","preciseIdentifier":"c:@E@UIButtonType","kind":"typeIdentifier"}],"title":"buttonType","kind":"symbol","navigatorTitle":[{"text":"buttonType","kind":"identifier"}],"abstract":[{"type":"text","text":"The button type."}],"url":"/documentation/uikit/uibutton/buttontype-swift.property"},"doc://com.apple.uikit/documentation/UIKit/UIButton/currentPreferredSymbolConfiguration":{"role":"symbol","url":"/documentation/uikit/uibutton/currentpreferredsymbolconfiguration","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/currentPreferredSymbolConfiguration","title":"currentPreferredSymbolConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentPreferredSymbolConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageSymbolConfiguration","text":"SymbolConfiguration"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The current symbol size, style, and weight."}],"navigatorTitle":[{"kind":"identifier","text":"currentPreferredSymbolConfiguration"}]},"doc://com.apple.uikit/documentation/UIKit/UIButton/currentBackgroundImage":{"role":"symbol","url":"/documentation/uikit/uibutton/currentbackgroundimage","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/currentBackgroundImage","title":"currentBackgroundImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentBackgroundImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The current background image displayed on the button."}],"navigatorTitle":[{"kind":"identifier","text":"currentBackgroundImage"}]},"doc://com.apple.uikit/documentation/UIKit/UIButton/currentAttributedTitle":{"role":"symbol","url":"/documentation/uikit/uibutton/currentattributedtitle","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/currentAttributedTitle","title":"currentAttributedTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentAttributedTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The current styled title that is displayed on the button."}],"navigatorTitle":[{"kind":"identifier","text":"currentAttributedTitle"}]},"doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitleShadowColor":{"role":"symbol","url":"/documentation/uikit/uibutton/currenttitleshadowcolor","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitleShadowColor","title":"currentTitleShadowColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentTitleShadowColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The color of the title’s shadow."}],"navigatorTitle":[{"kind":"identifier","text":"currentTitleShadowColor"}]},"doc://com.apple.uikit/documentation/UIKit/UIButton/subtitleLabel":{"role":"symbol","url":"/documentation/uikit/uibutton/subtitlelabel","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/subtitleLabel","title":"subtitleLabel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitleLabel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The label that displays the text of the subtitle."}],"navigatorTitle":[{"kind":"identifier","text":"subtitleLabel"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString":{"abstract":[{"text":"A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","url":"/documentation/foundation/nsattributedstring","kind":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSAttributedString","kind":"identifier"}],"role":"symbol","title":"NSAttributedString","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIButton":{"role":"symbol","abstract":[{"type":"text","text":"A control that executes your custom code in response to user interactions."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIButton"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton","title":"UIButton","navigatorTitle":[{"kind":"identifier","text":"UIButton"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uibutton"},"doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitleColor":{"role":"symbol","url":"/documentation/uikit/uibutton/currenttitlecolor","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitleColor","title":"currentTitleColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentTitleColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"abstract":[{"type":"text","text":"The color used to display the title."}],"navigatorTitle":[{"kind":"identifier","text":"currentTitleColor"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"unavailable":false,"introducedAt":"6.0","beta":false,"name":"iOS"},{"deprecated":false,"unavailable":false,"introducedAt":"6.0","beta":false,"name":"iPadOS"},{"deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false,"name":"visionOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"currentAttributedTitle","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"currentAttributedTitle","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIButton"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Getting-the-current-state","generated":true,"title":"Getting the current state","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIButton/buttonType-swift.property","doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitle","doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitleColor","doc://com.apple.uikit/documentation/UIKit/UIButton/currentTitleShadowColor","doc://com.apple.uikit/documentation/UIKit/UIButton/currentImage","doc://com.apple.uikit/documentation/UIKit/UIButton/currentBackgroundImage","doc://com.apple.uikit/documentation/UIKit/UIButton/currentPreferredSymbolConfiguration","doc://com.apple.uikit/documentation/UIKit/UIButton/imageView","doc://com.apple.uikit/documentation/UIKit/UIButton/subtitleLabel"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"currentAttributedTitle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"currentImage","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentImage/title"},{"value":[{"kind":"identifier","text":"currentImage"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentImage/fragments"},{"value":"currentTitle","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentTitle/title"},{"value":[{"kind":"identifier","text":"currentTitle"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentTitle/fragments"},{"value":"UIControlStateNormal","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1normal/title"},{"value":[{"text":"UIControlStateNormal","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1normal/fragments"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1imageView/title","op":"replace","value":"imageView"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1imageView/fragments","op":"replace","value":[{"text":"imageView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1buttonType-swift.property/title","op":"replace","value":"buttonType"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1buttonType-swift.property/fragments","op":"replace","value":[{"text":"buttonType","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentPreferredSymbolConfiguration/title","op":"replace","value":"currentPreferredSymbolConfiguration"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentPreferredSymbolConfiguration/fragments","op":"replace","value":[{"kind":"identifier","text":"currentPreferredSymbolConfiguration"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentBackgroundImage/title","op":"replace","value":"currentBackgroundImage"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentBackgroundImage/fragments","op":"replace","value":[{"kind":"identifier","text":"currentBackgroundImage"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentAttributedTitle/title","op":"replace","value":"currentAttributedTitle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentAttributedTitle/fragments","op":"replace","value":[{"kind":"identifier","text":"currentAttributedTitle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentTitleShadowColor/title","op":"replace","value":"currentTitleShadowColor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentTitleShadowColor/fragments","op":"replace","value":[{"kind":"identifier","text":"currentTitleShadowColor"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1subtitleLabel/title","op":"replace","value":"subtitleLabel"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1subtitleLabel/fragments","op":"replace","value":[{"kind":"identifier","text":"subtitleLabel"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title","op":"replace","value":"UIButton"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments","op":"replace","value":[{"kind":"identifier","text":"UIButton"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle","op":"replace","value":[{"text":"UIButton","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentTitleColor/title","op":"replace","value":"currentTitleColor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1currentTitleColor/fragments","op":"replace","value":[{"text":"currentTitleColor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}