{
  "abstract": [
    {
      "text": "The line break mode to use when drawing text.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "lineBreakMode",
          "type": "codeVoice"
        },
        {
          "text": " property of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/titleLabel",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIButton"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIButton/lineBreakMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIButton(py)lineBreakMode",
    "fragments": [
      {
        "kind": "identifier",
        "text": "lineBreakMode"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "lineBreakMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "3.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "3.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "lineBreakMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLineBreakMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSLineBreakMode",
              "text": "NSLineBreakMode"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lineBreakMode"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property is one of the constants described in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enumeration in NSString UIKit Additions Reference. The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeMiddleTruncation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLineBreakMode": {
      "abstract": [
        {
          "text": "Constants that specify what happens when a line is too long for a container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/nslinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton": {
      "abstract": [
        {
          "text": "A control that executes your custom code in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "role": "symbol",
      "title": "UIButton",
      "type": "topic",
      "url": "/documentation/uikit/uibutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/font": {
      "abstract": [
        {
          "text": "The font used to display text on the button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "font"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/font",
      "kind": "symbol",
      "role": "symbol",
      "title": "font",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/font"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/lineBreakMode": {
      "abstract": [
        {
          "text": "The line break mode to use when drawing text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/lineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "lineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/linebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/reversesTitleShadowWhenHighlighted": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the title shadow changes when the button is highlighted.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reversesTitleShadowWhenHighlighted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/reversesTitleShadowWhenHighlighted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reversesTitleShadowWhenHighlighted"
        }
      ],
      "role": "symbol",
      "title": "reversesTitleShadowWhenHighlighted",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/reversestitleshadowwhenhighlighted"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/titleLabel": {
      "abstract": [
        {
          "text": "A view that displays the value of the ",
          "type": "text"
        },
        {
          "code": "currentTitle",
          "type": "codeVoice"
        },
        {
          "text": " property for a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILabel",
          "text": "UILabel"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/titleLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleLabel"
        }
      ],
      "role": "symbol",
      "title": "titleLabel",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/titlelabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/titleShadowOffset": {
      "abstract": [
        {
          "text": "The offset of the shadow used to display the receiver’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "titleShadowOffset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/titleShadowOffset",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleShadowOffset",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/titleshadowoffset"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode": {
      "abstract": [
        {
          "text": "Options for wrapping and truncating text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeMiddleTruncation": {
      "abstract": [
        {
          "text": "Truncate text (as necessary) from the middle of the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakModeMiddleTruncation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeMiddleTruncation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakModeMiddleTruncation",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode/uilinebreakmodemiddletruncation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Title-effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/font",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/titleShadowOffset",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/reversesTitleShadowWhenHighlighted"
      ],
      "title": "Title effects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1reversesTitleShadowWhenHighlighted/title",
          "value": "reversesTitleShadowWhenHighlighted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1reversesTitleShadowWhenHighlighted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reversesTitleShadowWhenHighlighted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1titleLabel/title",
          "value": "titleLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1titleLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLineBreakMode/title",
          "value": "NSLineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLineBreakMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title",
          "value": "UIButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibutton/linebreakmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
