{
  "abstract": [
    {
      "text": "A type alias defining a closure that returns a pointer style to apply to a button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIButton"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIButton/PointerStyleProvider-swift.typealias"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:So8UIButtonC5UIKitE20PointerStyleProvidera",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PointerStyleProvider"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PointerStyleProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "UIButton.PointerStyleProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PointerStyleProvider"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIButton",
              "text": "UIButton"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit15UIPointerEffectO",
              "text": "UIPointerEffect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit14UIPointerShapeO",
              "text": "UIPointerShape"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIPointerStyle",
              "text": "UIPointerStyle"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The button requesting the pointer style.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "button"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The content effect that the system suggests.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "proposedEffect"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The shape of the pointer that the system suggests.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "proposedShape"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The pointer style to apply to the button when the pointer hovers over it. Return ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " when you don’t want to apply a pointer style to the button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To change the appearance of the pointer when it hovers over the button, create a pointer style provider closure and assign it to the button’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/pointerStyleProvider-y4eb",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. For instance, the following code listing increases the size of the pointer, while keeping the proposed content effect, to provide better highlighting of the button when the pointer hovers over it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "straightLineModeButton?.pointerStyleProvider = { button, proposedEffect, proposedShape -> UIPointerStyle? in",
            "    var rect = button.bounds.insetBy(dx: -12.0, dy: -14.0)",
            "    rect = button.convert(rect, to: proposedEffect.preview.target.container)",
            "    return UIPointerStyle(effect: proposedEffect, shape: .roundedRect(rect))",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton": {
      "abstract": [
        {
          "text": "A control that executes your custom code in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "role": "symbol",
      "title": "UIButton",
      "type": "topic",
      "url": "/documentation/uikit/uibutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/PointerStyleProvider-swift.typealias": {
      "abstract": [
        {
          "text": "A type alias defining a closure that returns a pointer style to apply to a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PointerStyleProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/PointerStyleProvider-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PointerStyleProvider"
        }
      ],
      "role": "symbol",
      "title": "UIButton.PointerStyleProvider",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/pointerstyleprovider-swift.typealias"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/isHovered": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a pointer effect is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHovered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/isHovered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hovered"
        }
      ],
      "role": "symbol",
      "title": "isHovered",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/ishovered"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/isPointerInteractionEnabled": {
      "abstract": [
        {
          "text": "A Boolean that enables pointer interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPointerInteractionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/isPointerInteractionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointerInteractionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isPointerInteractionEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/ispointerinteractionenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/pointerStyleProvider-y4eb": {
      "abstract": [
        {
          "text": "A closure that returns the pointer style to use when the pointer hovers over the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointerStyleProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE20PointerStyleProvidera",
          "text": "PointerStyleProvider"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/pointerStyleProvider-y4eb",
      "kind": "symbol",
      "role": "symbol",
      "title": "pointerStyleProvider",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/pointerstyleprovider-y4eb"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonPointerStyleProvider": {
      "abstract": [
        {
          "text": "A type alias defining a block that returns a pointer style to apply to a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButtonPointerStyleProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonPointerStyleProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButtonPointerStyleProvider"
        }
      ],
      "role": "symbol",
      "title": "UIButtonPointerStyleProvider",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonpointerstyleprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum": {
      "abstract": [
        {
          "text": "An effect that alters a view’s appearance when a pointer enters the current region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerEffect"
        }
      ],
      "role": "symbol",
      "title": "UIPointerEffect",
      "type": "topic",
      "url": "/documentation/uikit/uipointereffect-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-swift.enum": {
      "abstract": [
        {
          "text": "An object that defines the shape of custom pointers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerShape"
        }
      ],
      "role": "symbol",
      "title": "UIPointerShape",
      "type": "topic",
      "url": "/documentation/uikit/uipointershape-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerStyle": {
      "abstract": [
        {
          "text": "An object that defines the pointer shape and effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerStyle"
        }
      ],
      "role": "symbol",
      "title": "UIPointerStyle",
      "type": "topic",
      "url": "/documentation/uikit/uipointerstyle"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-pointer-interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/isPointerInteractionEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/isHovered",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/pointerStyleProvider-y4eb",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonPointerStyleProvider"
      ],
      "title": "Supporting pointer interactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1isHovered/title",
          "value": "hovered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1isHovered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hovered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerStyle/title",
          "value": "UIPointerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButtonPointerStyleProvider/title",
          "value": "UIButtonPointerStyleProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButtonPointerStyleProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonPointerStyleProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButtonPointerStyleProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButtonPointerStyleProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title",
          "value": "UIButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1isPointerInteractionEnabled/title",
          "value": "pointerInteractionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1isPointerInteractionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointerInteractionEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibutton/pointerstyleprovider-swift.typealias"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
