{"metadata":{"roleHeading":"Instance Property","platforms":[{"introducedAt":"2.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false,"message":"This property is ignored when using UIButtonConfiguration","deprecatedAt":"15.0"},{"introducedAt":"2.0","unavailable":false,"message":"This property is ignored when using UIButtonConfiguration","name":"iPadOS","deprecated":false,"deprecatedAt":"15.0","beta":false},{"introducedAt":"13.1","unavailable":false,"message":"This property is ignored when using UIButtonConfiguration","name":"Mac Catalyst","deprecated":false,"deprecatedAt":"15.0","beta":false},{"introducedAt":"2.0","unavailable":false,"message":"This property is ignored when using UIButtonConfiguration","name":"tvOS","deprecated":false,"deprecatedAt":"15.0","beta":false},{"introducedAt":"1.0","unavailable":false,"message":"This property is ignored when using UIButtonConfiguration","name":"visionOS","deprecated":false,"deprecatedAt":"1.0","beta":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleEdgeInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"titleEdgeInsets","kind":"identifier"}],"extendedModule":"UIKit","externalID":"c:objc(cs)UIButton(py)titleEdgeInsets","modules":[{"name":"UIKit"}],"role":"symbol","title":"titleEdgeInsets","symbolKind":"property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIButton"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uibutton/titleedgeinsets"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uibutton/titleedgeinsets"]}],"kind":"symbol","seeAlsoSections":[{"title":"Edge insets","generated":true,"anchor":"Edge-insets","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIButton/contentEdgeInsets","doc://com.apple.uikit/documentation/UIKit/UIButton/imageEdgeInsets"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleEdgeInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this property to resize and reposition the effective drawing rectangle for the button title. You can specify a different value for each of the four insets (top, left, bottom, right). A positive value shrinks, or insets, that edge—moving it closer to the center of the button. A negative value expands, or outsets, that edge. Use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets/init(top:left:bottom:right:)-1s1t9"},{"text":" function to construct a value for this property. The default value is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets/zero"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The insets you specify are applied to the title rectangle after that rectangle has been sized to fit the button’s text. Thus, positive inset values may actually clip the title text."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property is used only for positioning the title during layout. The button does not use this property to determine "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView/intrinsicContentSize"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView/sizeThatFits(_:)"},{"type":"text","text":"."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIButton/titleEdgeInsets"},"sections":[],"abstract":[{"text":"The inset or outset margins for the rectangle around the button’s title text.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit/UIButton/contentEdgeInsets":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/contentEdgeInsets","navigatorTitle":[{"text":"contentEdgeInsets","kind":"identifier"}],"abstract":[{"text":"The inset or outset margins for the rectangle surrounding all of the button’s content.","type":"text"}],"kind":"symbol","url":"/documentation/uikit/uibutton/contentedgeinsets","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentEdgeInsets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"}],"type":"topic","title":"contentEdgeInsets","role":"symbol","deprecated":true},"doc://com.apple.uikit/documentation/UIKit/UIView/intrinsicContentSize":{"role":"symbol","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"url":"/documentation/uikit/uiview/intrinsiccontentsize","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView/intrinsicContentSize","title":"intrinsicContentSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"abstract":[{"text":"The natural size for the receiving view, considering only properties of the view itself.","type":"text"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIView/sizeThatFits(_:)":{"url":"/documentation/uikit/uiview/sizethatfits(_:)","role":"symbol","title":"sizeThatFits(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"sizeThatFits:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView/sizeThatFits(_:)","abstract":[{"text":"Asks the view to calculate and return the size that best fits the specified size.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets":{"kind":"symbol","abstract":[{"text":"The inset distances for views.","type":"text"}],"url":"/documentation/uikit/uiedgeinsets","navigatorTitle":[{"text":"UIEdgeInsets","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEdgeInsets","kind":"identifier"}],"title":"UIEdgeInsets","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIButton":{"role":"symbol","abstract":[{"type":"text","text":"A control that executes your custom code in response to user interactions."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIButton"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton","title":"UIButton","navigatorTitle":[{"kind":"identifier","text":"UIButton"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uibutton"},"doc://com.apple.uikit/documentation/UIKit/UIButton/titleEdgeInsets":{"url":"/documentation/uikit/uibutton/titleedgeinsets","deprecated":true,"role":"symbol","title":"titleEdgeInsets","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleEdgeInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}],"navigatorTitle":[{"kind":"identifier","text":"titleEdgeInsets"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/titleEdgeInsets","abstract":[{"text":"The inset or outset margins for the rectangle around the button’s title text.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets/init(top:left:bottom:right:)-1s1t9":{"abstract":[{"type":"text","text":"Creates an edge insets structure with the specified edges."}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"top"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(top:left:bottom:right:)","navigatorTitle":[{"kind":"identifier","text":"UIEdgeInsetsMake"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets/init(top:left:bottom:right:)-1s1t9","url":"/documentation/uikit/uiedgeinsets/init(top:left:bottom:right:)-1s1t9"},"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets/zero":{"title":"zero","type":"topic","navigatorTitle":[{"text":"UIEdgeInsetsZero","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"zero","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets/zero","role":"symbol","url":"/documentation/uikit/uiedgeinsets/zero","kind":"symbol","abstract":[{"text":"An edge insets struct whose top, left, bottom, and right fields are all set to ","type":"text"},{"code":"0","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIButton/imageEdgeInsets":{"url":"/documentation/uikit/uibutton/imageedgeinsets","deprecated":true,"role":"symbol","title":"imageEdgeInsets","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEdgeInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageEdgeInsets","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/imageEdgeInsets","abstract":[{"text":"The inset or outset margins for the rectangle around the button’s image.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"2.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false,"deprecatedAt":"15.0"},{"introducedAt":"2.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"deprecatedAt":"15.0"},{"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","deprecated":false,"deprecatedAt":"15.0","beta":false},{"introducedAt":"2.0","unavailable":false,"name":"tvOS","deprecated":false,"deprecatedAt":"15.0","beta":false},{"introducedAt":"1.0","unavailable":false,"name":"visionOS","deprecated":false,"deprecatedAt":"1.0","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"titleEdgeInsets","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"titleEdgeInsets","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIButton"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Edge-insets","generated":true,"title":"Edge insets","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIButton/contentEdgeInsets","doc://com.apple.uikit/documentation/UIKit/UIButton/imageEdgeInsets"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"titleEdgeInsets","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"op":"add","value":[],"path":"/deprecationSummary"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1contentEdgeInsets/title","value":"contentEdgeInsets"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1contentEdgeInsets/fragments","value":[{"text":"contentEdgeInsets","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1intrinsicContentSize/title","value":"intrinsicContentSize"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1intrinsicContentSize/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1sizeThatFits(_:)/title","value":"sizeThatFits:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1sizeThatFits(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeThatFits:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/title","value":"UIEdgeInsets"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/fragments","value":[{"kind":"identifier","text":"UIEdgeInsets"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/navigatorTitle","value":[{"text":"UIEdgeInsets","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title","value":"UIButton"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments","value":[{"kind":"identifier","text":"UIButton"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle","value":[{"kind":"identifier","text":"UIButton"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1titleEdgeInsets/title","value":"titleEdgeInsets"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1titleEdgeInsets/fragments","value":[{"kind":"identifier","text":"titleEdgeInsets"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets~1init(top:left:bottom:right:)-1s1t9/title","value":"UIEdgeInsetsMake"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets~1init(top:left:bottom:right:)-1s1t9/fragments","value":[{"text":"UIEdgeInsetsMake","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets~1zero/title","value":"UIEdgeInsetsZero"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets~1zero/fragments","value":[{"kind":"identifier","text":"UIEdgeInsetsZero"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1imageEdgeInsets/title","value":"imageEdgeInsets"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1imageEdgeInsets/fragments","value":[{"text":"imageEdgeInsets","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}