{
  "abstract": [
    {
      "text": "Provides any errors that occur during processing of the request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/request(_:didFailWithError:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SNResultsObserving(im)request:didFailWithError:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "request"
      },
      {
        "kind": "text",
        "text": "(any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)SNRequest",
        "text": "SNRequest"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didFailWithError"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Sound Analysis"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "request:didFailWithError:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "request(_:didFailWithError:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "request"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "request"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)SNRequest",
              "text": "SNRequest"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didFailWithError"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The request that produces the error.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "request"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The error that occurs during the request.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The analyzer stops processing a specific request when it encounters an error, and doesn’t call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/requestDidComplete(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis": {
      "abstract": [
        {
          "text": "Classify various sounds by analyzing audio files or streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
      "kind": "symbol",
      "role": "collection",
      "title": "Sound Analysis",
      "type": "topic",
      "url": "/documentation/soundanalysis"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNRequest": {
      "abstract": [
        {
          "text": "A protocol that represents sound analysis requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNRequest"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNRequest"
        }
      ],
      "role": "symbol",
      "title": "SNRequest",
      "type": "topic",
      "url": "/documentation/soundanalysis/snrequest"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResult": {
      "abstract": [
        {
          "text": "A protocol that represents sound analysis results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNResult"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNResult"
        }
      ],
      "role": "symbol",
      "title": "SNResult",
      "type": "topic",
      "url": "/documentation/soundanalysis/snresult"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving": {
      "abstract": [
        {
          "text": "The interface your app implements to receive the results of an analysis request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNResultsObserving"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNResultsObserving"
        }
      ],
      "role": "symbol",
      "title": "SNResultsObserving",
      "type": "topic",
      "url": "/documentation/soundanalysis/snresultsobserving"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/request(_:didFailWithError:)": {
      "abstract": [
        {
          "text": "Provides any errors that occur during processing of the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "request"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SNRequest",
          "text": "SNRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/request(_:didFailWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "request:didFailWithError:"
        }
      ],
      "role": "symbol",
      "title": "request(_:didFailWithError:)",
      "type": "topic",
      "url": "/documentation/soundanalysis/snresultsobserving/request(_:didfailwitherror:)"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/request(_:didProduce:)": {
      "abstract": [
        {
          "text": "Provides a new analysis result to your app with the specified time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "request"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SNRequest",
          "text": "SNRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didProduce"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SNResult",
          "text": "SNResult"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/request(_:didProduce:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "request:didProduceResult:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "request(_:didProduce:)",
      "type": "topic",
      "url": "/documentation/soundanalysis/snresultsobserving/request(_:didproduce:)"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/requestDidComplete(_:)": {
      "abstract": [
        {
          "text": "Notifies your app when the analysis request completes normally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestDidComplete"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SNRequest",
          "text": "SNRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/requestDidComplete(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestDidComplete:"
        }
      ],
      "role": "symbol",
      "title": "requestDidComplete(_:)",
      "type": "topic",
      "url": "/documentation/soundanalysis/snresultsobserving/requestdidcomplete(_:)"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Requests",
      "generated": true,
      "identifiers": [
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/request(_:didProduce:)",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResult",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/requestDidComplete(_:)"
      ],
      "title": "Handling Requests"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "request:didFailWithError:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "request:didFailWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Requests",
              "generated": true,
              "identifiers": [
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/request(_:didProduce:)",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResult",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNResultsObserving/requestDidComplete(_:)"
              ],
              "title": "Handling Requests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "request:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)SNRequest",
                    "text": "id<SNRequest>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "request"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didFailWithError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The request that produces the error.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "request"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The error that occurs during the request.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResultsObserving~1request(_:didFailWithError:)/title",
          "value": "request:didFailWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResultsObserving~1request(_:didFailWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "request:didFailWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResultsObserving/title",
          "value": "SNResultsObserving"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResultsObserving/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNResultsObserving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResultsObserving/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNResultsObserving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResultsObserving~1requestDidComplete(_:)/title",
          "value": "requestDidComplete:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResultsObserving~1requestDidComplete(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestDidComplete:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResult/title",
          "value": "SNResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResultsObserving~1request(_:didProduce:)/title",
          "value": "request:didProduceResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNResultsObserving~1request(_:didProduce:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "request:didProduceResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNRequest/title",
          "value": "SNRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/soundanalysis/snresultsobserving/request(_:didfailwitherror:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/soundanalysis/snresultsobserving/request(_:didfailwitherror:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
