{
  "abstract": [
    {
      "text": "Specifies the size, in bytes, of the ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "lpvInBuffer",
          "type": "text"
        }
      ],
      "type": "strong"
    },
    {
      "text": " buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/cbInBuffer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@FFEFFESCAPE@FI@cbInBuffer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cbInBuffer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DWORD",
        "text": "DWORD"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cbInBuffer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "cbInBuffer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cbInBuffer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DWORD",
              "text": "DWORD"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DWORD"
        }
      ],
      "role": "symbol",
      "title": "DWORD",
      "type": "topic",
      "url": "/documentation/forcefeedback/dword"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE": {
      "abstract": [
        {
          "text": "The FFEFFESCAPE structure passes hardware-specific data directly to the Force Feedback plugIn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFFESCAPE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFFESCAPE"
        }
      ],
      "role": "symbol",
      "title": "FFEFFESCAPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffescape"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/cbInBuffer": {
      "abstract": [
        {
          "text": "Specifies the size, in bytes, of the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lpvInBuffer",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cbInBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/cbInBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cbInBuffer"
        }
      ],
      "role": "symbol",
      "title": "cbInBuffer",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffescape/cbinbuffer"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/cbOutBuffer": {
      "abstract": [
        {
          "text": "On entry, specifies the size, in bytes, of the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lpvOutBuffer",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " buffer. On exit, specifies the number of bytes actually produced by the command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cbOutBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/cbOutBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cbOutBuffer"
        }
      ],
      "role": "symbol",
      "title": "cbOutBuffer",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffescape/cboutbuffer"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/dwCommand": {
      "abstract": [
        {
          "text": "Specifies a plugIn specific command number. Contact the hardware vendor for a list of valid commands and their parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/dwCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwCommand"
        }
      ],
      "role": "symbol",
      "title": "dwCommand",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffescape/dwcommand"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/dwSize": {
      "abstract": [
        {
          "text": "Size, in bytes, of this structure. This member must be initialized before the structure is used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/dwSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwSize"
        }
      ],
      "role": "symbol",
      "title": "dwSize",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffescape/dwsize"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/lpvInBuffer": {
      "abstract": [
        {
          "text": "Buffer containing the data required to perform the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lpvInBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/lpvInBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lpvInBuffer"
        }
      ],
      "role": "symbol",
      "title": "lpvInBuffer",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffescape/lpvinbuffer"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/lpvOutBuffer": {
      "abstract": [
        {
          "text": "Buffer in which the operation’s output data is returned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lpvOutBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/lpvOutBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lpvOutBuffer"
        }
      ],
      "role": "symbol",
      "title": "lpvOutBuffer",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffescape/lpvoutbuffer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/cbOutBuffer",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/dwCommand",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/dwSize",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/lpvInBuffer",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/lpvOutBuffer"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "cbInBuffer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cbInBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/cbOutBuffer",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/dwCommand",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/dwSize",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/lpvInBuffer",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE/lpvOutBuffer"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DWORD",
                    "text": "DWORD"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "cbInBuffer"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1cbInBuffer/title",
          "value": "cbInBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1cbInBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cbInBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1cbOutBuffer/title",
          "value": "cbOutBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1cbOutBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cbOutBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1DWORD/title",
          "value": "DWORD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1DWORD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DWORD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1DWORD/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DWORD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1dwCommand/title",
          "value": "dwCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1dwCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1lpvInBuffer/title",
          "value": "lpvInBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1lpvInBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lpvInBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1lpvOutBuffer/title",
          "value": "lpvOutBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1lpvOutBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lpvOutBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/title",
          "value": "FFEFFESCAPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFESCAPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFESCAPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1dwSize/title",
          "value": "dwSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE~1dwSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffeffescape/cbinbuffer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffeffescape/cbinbuffer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
