{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchos-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "watchOS 7 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The watchOS 7 SDK provides support to develop watchOS apps for Apple Watch devices running watchOS 7. The SDK comes bundled with Xcode 12, available from the Mac App Store. For information on the compatibility requirements for Xcode 12, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12-release-notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Clock",
          "level": 3,
          "text": "Clock",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Kaleidoscope faces created using the Photos app on watchOS 7 beta 4 or earlier might cause your watch to repeatedly restart unexpectedly. (65224164)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Use the Watch app on your phone to remove the Kaleidoscope face.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Watch faces created using watchOS 7 beta 5 and earlier are no longer compatible with watchOS. Use watchOS 7 beta 6 or later to generate new ",
                      "type": "text"
                    },
                    {
                      "code": ".watchface",
                      "type": "codeVoice"
                    },
                    {
                      "text": " files. (66592614)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you added a Sleep complication to a Watch face in watchOS 7 beta, it might disappear after updating to watchOS 7 beta 2 or later. (63699282)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Add the Sleep complication again.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The Sleep complication might appear twice in the complication picker when editing a Watch face. (64709508)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Remove the Sleep app, then reinstall it using App Store on your watch.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Logging",
          "level": 3,
          "text": "Logging",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "New APIs are available for using ",
                      "type": "text"
                    },
                    {
                      "code": "os_log",
                      "type": "codeVoice"
                    },
                    {
                      "text": " from Swift as part of the framework ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/os",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". A new type, ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/os/Logger",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", can be instantiated using a subsystem and category and provides methods for logging at different levels (",
                      "type": "text"
                    },
                    {
                      "code": "Logger.debug",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "Logger.error",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "Logger.fault",
                      "type": "codeVoice"
                    },
                    {
                      "text": ").",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/os/Logger",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " APIs support specifying most formatting and privacy options supported by legacy ",
                      "type": "text"
                    },
                    {
                      "code": "os_log",
                      "type": "codeVoice"
                    },
                    {
                      "text": " APIs. The new APIs provide significant performance improvements over the legacy APIs. You can now pass Swift string interpolation to the ",
                      "type": "text"
                    },
                    {
                      "code": "os_log",
                      "type": "codeVoice"
                    },
                    {
                      "text": " function.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Note:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " The new APIs can’t be back deployed; however, the existing ",
                      "type": "text"
                    },
                    {
                      "code": "os_log",
                      "type": "codeVoice"
                    },
                    {
                      "text": " API remains available for back deployment. (22539144)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Networking",
          "level": 3,
          "text": "Networking",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlsession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " metrics support is now available. (29448748)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Software-Update",
          "level": 3,
          "text": "Software Update",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You might be unable to update Apple Watch Series 3 to watchOS 7 due to limited storage. (64793483)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Unpair your watch, then pair it again with your phone. Set it up as a new watch rather than restoring from a backup. Use General > Software Update in the Watch app to update to watchOS 7. If you want to restore your watch from its latest backup after the update is complete, repeat these steps while choosing to restore from a backup rather than setting up as new.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "SwiftUI",
          "level": 3,
          "text": "SwiftUI",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Color",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " can be converted to and from ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/uikit/uicolor/1621943-cgcolor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ColorPicker",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " can also now be configured with a binding to a ",
                      "type": "text"
                    },
                    {
                      "code": "CGColor",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". (56939085)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Introduced ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ToolbarItemGroup",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " as a convenient way to place multiple items in a specific location of non-customizable toolbars. (64178863)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " now supports adding a secondary “current value label” that describes the current progress level of the task. Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/label-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to describe the overall task, and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/currentValueLabel-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to provide more specific details about the progress of the task. (63580200)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Image",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is now redacted when the ",
                      "type": "text"
                    },
                    {
                      "text": "doc://com.apple.documentation/documentation/swiftui/anyview/redacted(reason:)",
                      "type": "text"
                    },
                    {
                      "text": " modifier is applied. (65047189)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/InlinePickerStyle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is now available and allows a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Picker",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to appear in-line with the rest of the content in its surrounding container. The style will adapt its appearance for different containers and platforms, such as individual menu items in a menu. (59868844)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/List",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " may now be used with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ScrollViewReader",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (35471164)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " gains a new initializer accepting a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/formatter",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (63641785)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "doc://com.apple.documentation/documentation/swiftui/view/body-swift.property",
                      "type": "text"
                    },
                    {
                      "text": " is now implicitly a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ViewBuilder",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/App/body-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is now implicitly a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/SceneBuilder",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (63606493)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/SwiftUI/App/body-swift.property": {
      "abstract": [
        {
          "text": "The content and behavior of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:7SwiftUI12SceneBuilderV",
          "text": "SceneBuilder"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI3AppP4BodyQa",
          "text": "Body"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/App/body-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "body",
      "type": "topic",
      "url": "/documentation/SwiftUI/App/body-swift.property"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Color": {
      "abstract": [
        {
          "text": "A representation of a color that adapts to a given context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Color"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Color",
      "kind": "symbol",
      "role": "symbol",
      "title": "Color",
      "type": "topic",
      "url": "/documentation/SwiftUI/Color"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ColorPicker": {
      "abstract": [
        {
          "text": "A control used to select a color from the system color picker UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorPicker"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ColorPicker",
      "kind": "symbol",
      "role": "symbol",
      "title": "ColorPicker",
      "type": "topic",
      "url": "/documentation/SwiftUI/ColorPicker"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Image": {
      "abstract": [
        {
          "text": "A view that displays an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Image"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Image",
      "kind": "symbol",
      "role": "symbol",
      "title": "Image",
      "type": "topic",
      "url": "/documentation/SwiftUI/Image"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/InlinePickerStyle": {
      "abstract": [
        {
          "text": "A `PickerStyle` where each option is displayed inline with other views in the current container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InlinePickerStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/InlinePickerStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "InlinePickerStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/InlinePickerStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/List": {
      "abstract": [
        {
          "text": "A container that presents rows of data arranged in a single column, optionally providing the ability to select one or more members.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "List"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/List",
      "kind": "symbol",
      "role": "symbol",
      "title": "List",
      "type": "topic",
      "url": "/documentation/SwiftUI/List"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Picker": {
      "abstract": [
        {
          "text": "A control for selecting from a set of mutually exclusive values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Picker"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Picker",
      "kind": "symbol",
      "role": "symbol",
      "title": "Picker",
      "type": "topic",
      "url": "/documentation/SwiftUI/Picker"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ProgressView": {
      "abstract": [
        {
          "text": "A view that shows the progress toward completion of a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProgressView"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "CurrentValueLabel"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "CurrentValueLabel"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressView",
      "kind": "symbol",
      "role": "symbol",
      "title": "ProgressView",
      "type": "topic",
      "url": "/documentation/SwiftUI/ProgressView"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/currentValueLabel-swift.property": {
      "abstract": [
        {
          "text": "A view that describes the current value of a progress view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentValueLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI30ProgressViewStyleConfigurationV",
          "text": "ProgressViewStyleConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI30ProgressViewStyleConfigurationV17CurrentValueLabelV",
          "text": "CurrentValueLabel"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/currentValueLabel-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "currentValueLabel",
      "type": "topic",
      "url": "/documentation/SwiftUI/ProgressViewStyleConfiguration/currentValueLabel-swift.property"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/label-swift.property": {
      "abstract": [
        {
          "text": "A view that describes the task represented by the progress view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI30ProgressViewStyleConfigurationV",
          "text": "ProgressViewStyleConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI30ProgressViewStyleConfigurationV5LabelV",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/label-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/SwiftUI/ProgressViewStyleConfiguration/label-swift.property"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/SceneBuilder": {
      "abstract": [
        {
          "text": "A result builder for composing a collection of scenes into a single composite scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@resultBuilder"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneBuilder"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/SceneBuilder",
      "kind": "symbol",
      "role": "symbol",
      "title": "SceneBuilder",
      "type": "topic",
      "url": "/documentation/SwiftUI/SceneBuilder"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ScrollViewReader": {
      "abstract": [
        {
          "text": "A view that provides programmatic scrolling, by working with a proxy to scroll to known child views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScrollViewReader"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ScrollViewReader",
      "kind": "symbol",
      "role": "symbol",
      "title": "ScrollViewReader",
      "type": "topic",
      "url": "/documentation/SwiftUI/ScrollViewReader"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text": {
      "abstract": [
        {
          "text": "A view that displays one or more lines of read-only text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text",
      "kind": "symbol",
      "role": "symbol",
      "title": "Text",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ToolbarItemGroup": {
      "abstract": [
        {
          "text": "A model that represents a group of `ToolbarItem`s which can be placed in the toolbar or navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ToolbarItemGroup"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ToolbarItemGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "ToolbarItemGroup",
      "type": "topic",
      "url": "/documentation/SwiftUI/ToolbarItemGroup"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ViewBuilder": {
      "abstract": [
        {
          "text": "A custom parameter attribute that constructs views from closures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@resultBuilder"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ViewBuilder"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ViewBuilder",
      "kind": "symbol",
      "role": "symbol",
      "title": "ViewBuilder",
      "type": "topic",
      "url": "/documentation/SwiftUI/ViewBuilder"
    },
    "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12 Release Notes",
      "type": "topic",
      "url": "/documentation/Xcode-Release-Notes/xcode-12-release-notes"
    },
    "doc://com.apple.documentation/documentation/foundation/formatter": {
      "abstract": [
        {
          "text": "An abstract class that declares an interface for objects that create, interpret, and validate the textual representation of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Formatter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/formatter",
      "kind": "symbol",
      "role": "symbol",
      "title": "Formatter",
      "type": "topic",
      "url": "/documentation/foundation/formatter"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurlsession": {
      "abstract": [
        {
          "text": "An object that coordinates a group of related, network data transfer tasks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlsession",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURLSession",
      "type": "topic",
      "url": "/documentation/foundation/nsurlsession"
    },
    "doc://com.apple.documentation/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.documentation/documentation/os/Logger": {
      "abstract": [
        {
          "text": "An object for writing interpolated string messages to the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Logger"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/Logger",
      "kind": "symbol",
      "role": "symbol",
      "title": "Logger",
      "type": "topic",
      "url": "/documentation/os/Logger"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/uikit/uicolor/1621943-cgcolor": {
      "abstract": [
        {
          "text": "The Quartz color that corresponds to the color object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/uikit/uicolor/1621943-cgcolor",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/1621943-cgcolor"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 7.1 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-7_1-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_2-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 7.2 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-7_2-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_3-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_3-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 7.3 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-7_3-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_4-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_4-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 7.4 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-7_4-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_5-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_5-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 7.5 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-7_5-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_6-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_6-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 7.6 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-7_6-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchos-release-notes": {
      "abstract": [
        {
          "text": "Learn about changes to the watchOS SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchos-release-notes",
      "kind": "article",
      "role": "collection",
      "title": "watchOS Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "watchOS-7",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_6-release-notes",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_5-release-notes",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_4-release-notes",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_3-release-notes",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_2-release-notes",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-7_1-release-notes"
      ],
      "title": "watchOS 7"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurlsession/title",
          "value": "URLSession"
        },
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurlsession/fragments",
          "value": [
            {
              "kind": "text",
              "text": "class "
            },
            {
              "kind": "identifier",
              "text": "URLSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1formatter/title",
          "value": "NSFormatter"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
