{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchos-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_1-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "watchOS 8.1 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The watchOS 8 SDK provides support to develop watchOS apps for Apple Watch devices running watchOS 8.1. The SDK comes bundled with Xcode 13, available from the Mac App Store. For information on the compatibility requirements for Xcode 13, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-13-release-notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "CoreData",
          "level": 3,
          "text": "CoreData",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "NSExpression",
                      "type": "codeVoice"
                    },
                    {
                      "text": " immediately forbids certain operations that have significant side effects, like creating and destroying objects. Additionally, casting string class names into Class objects with ",
                      "type": "text"
                    },
                    {
                      "code": "NSConstantValueExpression",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is deprecated. (84017178)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Pass temporary objects to ",
                      "type": "text"
                    },
                    {
                      "code": "NSExpression",
                      "type": "codeVoice"
                    },
                    {
                      "text": " in the context parameter of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexpression/1410363-expressionvaluewithobject",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", or with ",
                      "type": "text"
                    },
                    {
                      "code": "NSPredicate",
                      "type": "codeVoice"
                    },
                    {
                      "text": " as the ",
                      "type": "text"
                    },
                    {
                      "code": "substitutionVariables",
                      "type": "codeVoice"
                    },
                    {
                      "text": " parameter of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nspredicate/1407759-evaluatewithobject",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". You can create a derived predicate with all the substitution variables replaced (bound), using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nspredicate/1413227-withsubstitutionvariables",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " on an existing ",
                      "type": "text"
                    },
                    {
                      "code": "NSPredicate",
                      "type": "codeVoice"
                    },
                    {
                      "text": " so that code using the object can continue to use a simple ",
                      "type": "text"
                    },
                    {
                      "code": "evaluate(with object: Any?)",
                      "type": "codeVoice"
                    },
                    {
                      "text": " invocation.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-13-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-13-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 13 Release Notes",
      "type": "topic",
      "url": "/documentation/Xcode-Release-Notes/xcode-13-release-notes"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexpression/1410363-expressionvaluewithobject": {
      "abstract": [
        {
          "text": "Evaluates an expression using a specified object and context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexpression/1410363-expressionvaluewithobject",
      "kind": "symbol",
      "role": "symbol",
      "title": "expressionValueWithObject:context:",
      "type": "topic",
      "url": "/documentation/foundation/nsexpression/1410363-expressionvaluewithobject"
    },
    "doc://com.apple.documentation/documentation/foundation/nspredicate/1407759-evaluatewithobject": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the specified object matches the conditions that the predicate specifies after substituting in the values from a specified variables dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nspredicate/1407759-evaluatewithobject",
      "kind": "symbol",
      "role": "symbol",
      "title": "evaluateWithObject:substitutionVariables:",
      "type": "topic",
      "url": "/documentation/foundation/nspredicate/1407759-evaluatewithobject"
    },
    "doc://com.apple.documentation/documentation/foundation/nspredicate/1413227-withsubstitutionvariables": {
      "abstract": [
        {
          "text": "Returns a copy of the predicate and substitutes the predicates variables with specified values from a specified substitution variables dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "withSubstitutionVariables"
        },
        {
          "kind": "text",
          "text": "([String : Any]) -> Self"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nspredicate/1413227-withsubstitutionvariables",
      "kind": "symbol",
      "role": "symbol",
      "title": "withSubstitutionVariables(_:)",
      "type": "topic",
      "url": "/documentation/foundation/nspredicate/1413227-withsubstitutionvariables"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 8 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-8-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_3-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_3-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 8.3 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-8_3-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_4-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_4-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 8.4 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-8_4-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_5-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_5-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 8.5 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-8_5-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_6-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_6-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 8.6 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-8_6-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_7-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_7-release-notes",
      "kind": "article",
      "role": "article",
      "title": "watchOS 8.7 Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes/watchos-8_7-release-notes"
    },
    "doc://com.apple.watchOS-Release-Notes/documentation/watchos-release-notes": {
      "abstract": [
        {
          "text": "Learn about changes to the watchOS SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Release-Notes/documentation/watchos-release-notes",
      "kind": "article",
      "role": "collection",
      "title": "watchOS Release Notes",
      "type": "topic",
      "url": "/documentation/watchos-release-notes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "watchOS-8",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_7-release-notes",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_6-release-notes",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_5-release-notes",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_4-release-notes",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8_3-release-notes",
        "doc://com.apple.watchOS-Release-Notes/documentation/watchOS-Release-Notes/watchos-8-release-notes"
      ],
      "title": "watchOS 8"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nspredicate~11413227-withsubstitutionvariables/title",
          "value": "predicateWithSubstitutionVariables:"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    },
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexpression~11410363-expressionvaluewithobject/title",
          "value": "expressionValue(with:context:)"
        },
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexpression~11410363-expressionvaluewithobject/fragments",
          "value": [
            {
              "kind": "text",
              "text": "func "
            },
            {
              "kind": "identifier",
              "text": "expressionValue"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "identifier",
              "text": "with"
            },
            {
              "kind": "text",
              "text": ": Any?, "
            },
            {
              "kind": "identifier",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ": NSMutableDictionary?) -> Any?"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nspredicate~11407759-evaluatewithobject/title",
          "value": "evaluate(with:substitutionVariables:)"
        },
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nspredicate~11407759-evaluatewithobject/fragments",
          "value": [
            {
              "kind": "text",
              "text": "func "
            },
            {
              "kind": "identifier",
              "text": "evaluate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "identifier",
              "text": "with"
            },
            {
              "kind": "text",
              "text": ": Any?, "
            },
            {
              "kind": "identifier",
              "text": "substitutionVariables"
            },
            {
              "kind": "text",
              "text": ": [String : Any]?) -> Bool"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
