{
  "abstract": [
    {
      "text": "The find panel includes the total number of results the session reports and the index of the target result.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/currentAndTotal"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIFindSessionSearchResultDisplayStyle@UIFindSessionSearchResultDisplayStyleCurrentAndTotal",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "currentAndTotal"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIFindSessionSearchResultDisplayStyleCurrentAndTotal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIFindSession.SearchResultDisplayStyle.currentAndTotal"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentAndTotal"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession": {
      "abstract": [
        {
          "text": "An abstract base class that manages the state, presentation, and behavior for a search that the find interaction initiates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindSession"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the results summary the find panel UI includes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession.SearchResultDisplayStyle",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/currentAndTotal": {
      "abstract": [
        {
          "text": "The find panel includes the total number of results the session reports and the index of the target result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentAndTotal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/currentAndTotal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindSessionSearchResultDisplayStyleCurrentAndTotal"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession.SearchResultDisplayStyle.currentAndTotal",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.enum/currentandtotal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/none": {
      "abstract": [
        {
          "text": "The find panel doesn’t include the number of results the session reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindSessionSearchResultDisplayStyleNone"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession.SearchResultDisplayStyle.none",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.enum/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/total": {
      "abstract": [
        {
          "text": "The find panel includes the total number of results the session reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "total"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/total",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindSessionSearchResultDisplayStyleTotal"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession.SearchResultDisplayStyle.total",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.enum/total"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/total",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/none"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIFindSessionSearchResultDisplayStyleCurrentAndTotal"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyleCurrentAndTotal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/total",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum/none"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIFindSessionSearchResultDisplayStyleCurrentAndTotal"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/title",
          "value": "UIFindSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum~1currentAndTotal/title",
          "value": "UIFindSessionSearchResultDisplayStyleCurrentAndTotal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum~1currentAndTotal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyleCurrentAndTotal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/title",
          "value": "UIFindSessionSearchResultDisplayStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum~1none/title",
          "value": "UIFindSessionSearchResultDisplayStyleNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyleNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum~1total/title",
          "value": "UIFindSessionSearchResultDisplayStyleTotal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum~1total/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyleTotal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.enum/currentandtotal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.enum/currentandtotal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
