{
  "abstract": [
    {
      "text": "Add support for universal links and a Shared with You shelf to support shared content in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/making-your-app-content-shareable"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Shared With You"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Making your app content shareable"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "System apps like Safari, News, Music, Photos, and Podcasts use Shared with You to make it easier to share content with friends and family. By adopting universal links and adding a Shared with You shelf to your app, you can also share your content using Messages. When you add views to showcase shared content activity, your app allows people to view Messages conversations that contain your shared content and still stay focused on your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your app can also manage who can view or share your content using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This adds a new level of collaboration to your app. You can customize your content’s contextual menu to add even more functionality to shared content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Adopt-universal-links",
          "level": 3,
          "text": "Adopt universal links",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app uses universal links to share content with other apps. When a user activates a universal link, the system launches your app and sends it an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Query this object to take actions for your shared content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To support universal links in your app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a two-way association between your app and your website and specify the URLs that your app handles. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Update your app delegate to respond when it receives an ",
                      "type": "text"
                    },
                    {
                      "code": "NSUserActivity",
                      "type": "codeVoice"
                    },
                    {
                      "text": " object with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity/1409611-activitytype",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " set to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivitytypebrowsingweb",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-universal-links-in-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-Shared-with-You-capability",
          "level": 3,
          "text": "Add Shared with You capability",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To add the Shared with You capability in Xcode, follow these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select your project target.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the Signing & Capabilities pane.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click + Capability to bring up the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Xcode/capabilities",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " library.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose the Shared with You capability.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-Shared-with-You-shelf",
          "level": 3,
          "text": "Add Shared with You shelf",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Instead of relying on Messages to display shared content activity, you can add a Shared with You shelf to your app. This is a custom view your app creates and manages to display ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " activity. People can see new content shares and interact with existing ones from your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Enumerate Shared with You shelf.",
            "",
            "class SharedWithYouViewController: UIViewController, SWHighlightCenterDelegate {",
            "    let highlightCenter = SWHighlightCenter()",
            "    ",
            "    override func viewDidLoad() {",
            "        super.viewDidLoad()",
            "        highlightCenter.delegate = self",
            "    }",
            "    ",
            "    func highlightCenterHighlightsDidChange(_ highlightCenter: SWHighlightCenter) {",
            "        for highlight in highlightCenter.highlights {",
            "            let highlightURL = highlight.url",
            "            // Generate a rich preview for this highlight.",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Add-an-SWAttributionView-to-your-content",
          "level": 3,
          "text": "Add an SWAttributionView to your content",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is the user interface your app customizes to give people a way to interact with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlight",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " events, like the addition of a new participant or a title change to the shared content. You can adjust the alignment of the content, the width, and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/DisplayContext-swift.enum",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " format.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Set the horizontal alignment for an attribution view.",
            "",
            "let attributionView = SWAttributionView()",
            "attributionView.highlight = self.highlightCenter.highlights[index]",
            "attributionView.preferredMaxLayoutWidth = maximumWidthForView",
            "attributionView.horizontalAlignment = .leading"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You can show the ",
              "type": "text"
            },
            {
              "code": "displayContext",
              "type": "codeVoice"
            },
            {
              "text": " as an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/DisplayContext-swift.enum/summary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/DisplayContext-swift.enum/detail",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " view. The detail view is ideal if you have more vertical space in your app to provide a larger image of the shared content and more related information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Set the display context for an attribution view.",
            "",
            "let attributionView = SWAttributionView()",
            "attributionView.highlight = self.highlightCenter.highlights[index]",
            "attributionView.preferredMaxLayoutWidth = maximumWidthForView",
            "attributionView.horizontalAlignment = .center",
            "attributionView.displayContext = .summary"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You can also customize the highlight menu text and add additional menu items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Add Shared with You content menu to your app’s content.",
            "",
            "let attributionView = SWAttributionView()",
            "attributionView.highlight = self.highlightCenter.highlights[index]",
            "attributionView.menuTitleForHideAction = \"Remove Item\"",
            "",
            "let contextMenuConfig = UIContextMenuConfiguration(identifier: nil,previewProvider: nil) { [weak self] _ in",
            "        let additionalMenu = attributionView.supplementalMenu",
            "        // Append additional menu items to your content menu.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app": {
      "abstract": [
        {
          "text": "Configure your target to include and customize capabilities that provide access to Apple’s app services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding capabilities to your app",
      "type": "topic",
      "url": "/documentation/Xcode/adding-capabilities-to-your-app"
    },
    "doc://com.apple.documentation/documentation/Xcode/capabilities": {
      "abstract": [
        {
          "text": "Enable services that Apple provides, such as In-App Purchase, Push Notifications, Apple Pay, iCloud, and many others.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/capabilities",
      "kind": "article",
      "role": "article",
      "title": "Capabilities",
      "type": "topic",
      "url": "/documentation/Xcode/capabilities"
    },
    "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains": {
      "abstract": [
        {
          "text": "Connect your app and a website to provide both a native app and a browser experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
      "kind": "article",
      "role": "article",
      "title": "Supporting associated domains",
      "type": "topic",
      "url": "/documentation/Xcode/supporting-associated-domains"
    },
    "doc://com.apple.documentation/documentation/Xcode/supporting-universal-links-in-your-app": {
      "abstract": [
        {
          "text": "Prepare your app to respond to an incoming universal link.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-universal-links-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting universal links in your app",
      "type": "topic",
      "url": "/documentation/Xcode/supporting-universal-links-in-your-app"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity": {
      "abstract": [
        {
          "text": "A representation of the state of your app at a moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivity",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity/1409611-activitytype": {
      "abstract": [
        {
          "text": "The user activity object’s activity type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "activityType"
        },
        {
          "kind": "text",
          "text": ": String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity/1409611-activitytype",
      "kind": "symbol",
      "role": "symbol",
      "title": "activityType",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity/1409611-activitytype"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivitytypebrowsingweb": {
      "abstract": [
        {
          "text": "An activity that continues from Handoff or a universal link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivityTypeBrowsingWeb"
        },
        {
          "kind": "text",
          "text": ": String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivitytypebrowsingweb",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivityTypeBrowsingWeb",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivitytypebrowsingweb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You",
      "type": "topic",
      "url": "/documentation/sharedwithyou"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView": {
      "abstract": [
        {
          "text": "A view that displays the sender who shares a highlight and provides related actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWAttributionView"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionView"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/DisplayContext-swift.enum": {
      "abstract": [
        {
          "text": "The context for the content that influences the ranking of this view’s highlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayContext"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/DisplayContext-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayContext"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.DisplayContext",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/displaycontext-swift.enum"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/DisplayContext-swift.enum/detail": {
      "abstract": [
        {
          "text": "Indicates that the attributed content shown along with this view is being actively consumed by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detail"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/DisplayContext-swift.enum/detail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionViewDisplayContextDetail"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.DisplayContext.detail",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/displaycontext-swift.enum/detail"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/DisplayContext-swift.enum/summary": {
      "abstract": [
        {
          "text": "Indicates that the system is offering the attributed content shown along with this view to the user for consumption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "summary"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/DisplayContext-swift.enum/summary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionViewDisplayContextSummary"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.DisplayContext.summary",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/displaycontext-swift.enum/summary"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlight": {
      "abstract": [
        {
          "text": "An object that represents a universal link to share by any number of contacts in one or more conversations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWHighlight"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlight"
        }
      ],
      "role": "symbol",
      "title": "SWHighlight",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlight"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenter": {
      "abstract": [
        {
          "text": "An object that contains a priority-ordered list of universal links to share with the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWHighlightCenter"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightCenter"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightCenter",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightcenter"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/shared-content-interactions": {
      "abstract": [
        {
          "text": "Use highlights and attribution views to manage participants and trigger events for shared content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/shared-content-interactions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Shared content interactions",
      "type": "topic",
      "url": "/documentation/sharedwithyou/shared-content-interactions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shared-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/shared-content-interactions"
      ],
      "title": "Shared content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/title",
          "value": "SWAttributionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenter/title",
          "value": "SWHighlightCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1DisplayContext-swift.enum~1detail/title",
          "value": "SWAttributionViewDisplayContextDetail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1DisplayContext-swift.enum~1detail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewDisplayContextDetail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1DisplayContext-swift.enum/title",
          "value": "SWAttributionViewDisplayContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1DisplayContext-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewDisplayContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1DisplayContext-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewDisplayContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1DisplayContext-swift.enum~1summary/title",
          "value": "SWAttributionViewDisplayContextSummary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1DisplayContext-swift.enum~1summary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewDisplayContextSummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlight/title",
          "value": "SWHighlight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
