{
  "abstract": [
    {
      "text": "The type of change event for the highlight",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SWHighlightChangeEventTrigger",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SWHighlightChangeEventTrigger"
      }
    ],
    "modules": [
      {
        "name": "Shared With You"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SWHighlightChangeEventTrigger"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SWHighlightChangeEventTrigger"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SWHighlightChangeEventTrigger"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-shared-content-collaboration-to-your-app"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You",
      "type": "topic",
      "url": "/documentation/sharedwithyou"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEvent/changeEventTrigger": {
      "abstract": [
        {
          "text": "The type of change event for the highlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeEventTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SWHighlightChangeEventTrigger",
          "text": "SWHighlightChangeEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEvent/changeEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "changeEventTrigger",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightchangeevent/changeeventtrigger"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEvent/highlightURL": {
      "abstract": [
        {
          "text": "The URL of the hightlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlightURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEvent/highlightURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highlightURL"
        }
      ],
      "role": "symbol",
      "title": "highlightURL",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightchangeevent/highlighturl"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger": {
      "abstract": [
        {
          "text": "The type of change event for the highlight",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWHighlightChangeEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightChangeEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightChangeEventTrigger",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightchangeeventtrigger"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/comment": {
      "abstract": [
        {
          "text": "Signifies a highlight comment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comment"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/comment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightChangeEventTriggerComment"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightChangeEventTrigger.comment",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightchangeeventtrigger/comment"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/edit": {
      "abstract": [
        {
          "text": "Signifies a highlight edit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edit"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/edit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightChangeEventTriggerEdit"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightChangeEventTrigger.edit",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightchangeeventtrigger/edit"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightchangeeventtrigger/init(rawvalue:)"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-shared-content-collaboration-to-your-app": {
      "abstract": [
        {
          "text": "Manage shared content collaboration in your app using CloudKit and iCloud Drive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-shared-content-collaboration-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding shared content collaboration to your app",
      "type": "topic",
      "url": "/documentation/sharedwithyou/adding-shared-content-collaboration-to-your-app"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-event-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEvent/highlightURL",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEvent/changeEventTrigger"
      ],
      "title": "Accessing event attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Change-actions",
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/edit",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/comment"
      ],
      "title": "Change actions"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SWHighlightChangeEventTrigger"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightChangeEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightChangeEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Change-actions",
              "identifiers": [
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/edit",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEventTrigger/comment"
              ],
              "title": "Change actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-event-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEvent/highlightURL",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightChangeEvent/changeEventTrigger"
              ],
              "title": "Accessing event attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SWHighlightChangeEventTrigger"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEventTrigger/title",
          "value": "SWHighlightChangeEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightChangeEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEventTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightChangeEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEventTrigger~1comment/title",
          "value": "SWHighlightChangeEventTriggerComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEventTrigger~1comment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightChangeEventTriggerComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEvent~1highlightURL/title",
          "value": "highlightURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEvent~1highlightURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highlightURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEventTrigger~1edit/title",
          "value": "SWHighlightChangeEventTriggerEdit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEventTrigger~1edit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightChangeEventTriggerEdit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEvent~1changeEventTrigger/title",
          "value": "changeEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightChangeEvent~1changeEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "changeEventTrigger"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyou/swhighlightchangeeventtrigger"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sharedwithyou/swhighlightchangeeventtrigger"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
