{
  "abstract": [
    {
      "text": "A structure that describes the types of activities for which the system has built-in support.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@T@UIActivityType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ActivityType"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ActivityType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIActivity.ActivityType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ActivityType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants represent the values that can be stored in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityType-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of system-defined activity objects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity": {
      "abstract": [
        {
          "text": "An abstract class that you subclass to implement app-specific services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivity"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivity"
        }
      ],
      "role": "symbol",
      "title": "UIActivity",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct": {
      "abstract": [
        {
          "text": "A structure that describes the types of activities for which the system has built-in support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivityType"
        }
      ],
      "role": "symbol",
      "title": "UIActivity.ActivityType",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/addToHomeScreen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addToHomeScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/addToHomeScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeAddToHomeScreen"
        }
      ],
      "role": "symbol",
      "title": "addToHomeScreen",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/addtohomescreen"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/addToReadingList": {
      "abstract": [
        {
          "text": "A type of activity that adds the URL to Safari’s reading list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addToReadingList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/addToReadingList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeAddToReadingList"
        }
      ],
      "role": "symbol",
      "title": "addToReadingList",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/addtoreadinglist"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/airDrop": {
      "abstract": [
        {
          "text": "A type of activity that makes the provided content available through AirDrop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airDrop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/airDrop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeAirDrop"
        }
      ],
      "role": "symbol",
      "title": "airDrop",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/airdrop"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/assignToContact": {
      "abstract": [
        {
          "text": "A type of activity that assigns the image to a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assignToContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/assignToContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeAssignToContact"
        }
      ],
      "role": "symbol",
      "title": "assignToContact",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/assigntocontact"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/collaborationCopyLink": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collaborationCopyLink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/collaborationCopyLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeCollaborationCopyLink"
        }
      ],
      "role": "symbol",
      "title": "collaborationCopyLink",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/collaborationcopylink"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/collaborationInviteWithLink": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collaborationInviteWithLink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/collaborationInviteWithLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeCollaborationInviteWithLink"
        }
      ],
      "role": "symbol",
      "title": "collaborationInviteWithLink",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/collaborationinvitewithlink"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/copyToPasteboard": {
      "abstract": [
        {
          "text": "A type of activity that posts the provided content to the pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyToPasteboard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/copyToPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeCopyToPasteboard"
        }
      ],
      "role": "symbol",
      "title": "copyToPasteboard",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/copytopasteboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/init(_:)": {
      "abstract": [
        {
          "text": "Creates an activity type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/init(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/mail": {
      "abstract": [
        {
          "text": "A type of activity that posts the provided content to a new email message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/mail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeMail"
        }
      ],
      "role": "symbol",
      "title": "mail",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/mail"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/markupAsPDF": {
      "abstract": [
        {
          "text": "A type of activity that marks up the provided content as a PDF file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markupAsPDF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/markupAsPDF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeMarkupAsPDF"
        }
      ],
      "role": "symbol",
      "title": "markupAsPDF",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/markupaspdf"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/message": {
      "abstract": [
        {
          "text": "A type of activity that posts the provided content to the Messages app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "message"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/message",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeMessage"
        }
      ],
      "role": "symbol",
      "title": "message",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/message"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/openInIBooks": {
      "abstract": [
        {
          "text": "A type of activity that opens the content in iBooks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openInIBooks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/openInIBooks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeOpenInIBooks"
        }
      ],
      "role": "symbol",
      "title": "openInIBooks",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/openinibooks"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToFacebook": {
      "abstract": [
        {
          "text": "A type of activity that posts the provided content to the user’s wall on Facebook.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postToFacebook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToFacebook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypePostToFacebook"
        }
      ],
      "role": "symbol",
      "title": "postToFacebook",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/posttofacebook"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToFlickr": {
      "abstract": [
        {
          "text": "A type of activity that posts the provided image to the user’s Flickr account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postToFlickr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToFlickr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypePostToFlickr"
        }
      ],
      "role": "symbol",
      "title": "postToFlickr",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/posttoflickr"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToTencentWeibo": {
      "abstract": [
        {
          "text": "A type of activity that posts the provided content to the user’s Tencent Weibo feed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postToTencentWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToTencentWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypePostToTencentWeibo"
        }
      ],
      "role": "symbol",
      "title": "postToTencentWeibo",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/posttotencentweibo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToTwitter": {
      "abstract": [
        {
          "text": "A type of activity that posts the provided content to the user’s Twitter feed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postToTwitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToTwitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypePostToTwitter"
        }
      ],
      "role": "symbol",
      "title": "postToTwitter",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/posttotwitter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToVimeo": {
      "abstract": [
        {
          "text": "A type of activity that posts the provided video to the user’s Vimeo account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postToVimeo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToVimeo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypePostToVimeo"
        }
      ],
      "role": "symbol",
      "title": "postToVimeo",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/posttovimeo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToWeibo": {
      "abstract": [
        {
          "text": "A type of activity that posts the provided content to the user’s Weibo feed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postToWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypePostToWeibo"
        }
      ],
      "role": "symbol",
      "title": "postToWeibo",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/posttoweibo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/print": {
      "abstract": [
        {
          "text": "A type of activity that prints the provided content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "print"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/print",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypePrint"
        }
      ],
      "role": "symbol",
      "title": "print",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/print"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/saveToCameraRoll": {
      "abstract": [
        {
          "text": "A type of activity that assigns the image or video to the user’s camera roll.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveToCameraRoll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/saveToCameraRoll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeSaveToCameraRoll"
        }
      ],
      "role": "symbol",
      "title": "saveToCameraRoll",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/savetocameraroll"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/sharePlay": {
      "abstract": [
        {
          "text": "A type of activity that makes the provided content available through SharePlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sharePlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/sharePlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityTypeSharePlay"
        }
      ],
      "role": "symbol",
      "title": "sharePlay",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.struct/shareplay"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/Category": {
      "abstract": [
        {
          "text": "An enumeration that defines categories of activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/Category",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Category"
        }
      ],
      "role": "symbol",
      "title": "UIActivity.Category",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/category"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityCategory": {
      "abstract": [
        {
          "text": "The category of the activity, which may be used to group activities in the UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIActivityCategory",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityCategory"
        }
      ],
      "role": "symbol",
      "title": "activityCategory",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitycategory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityImage": {
      "abstract": [
        {
          "text": "An image that identifies the service to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityImage"
        }
      ],
      "role": "symbol",
      "title": "activityImage",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activityimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityTitle": {
      "abstract": [
        {
          "text": "A user-readable string that describes the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityTitle"
        }
      ],
      "role": "symbol",
      "title": "activityTitle",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityType-swift.property": {
      "abstract": [
        {
          "text": "The type of service being provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityType",
          "text": "ActivityType"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityType"
        }
      ],
      "role": "symbol",
      "title": "activityType",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity/activitytype-swift.property"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-activity-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityCategory",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/Category",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityType-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityTitle",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityImage"
      ],
      "title": "Getting the activity information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/addToHomeScreen",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/addToReadingList",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/airDrop",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/assignToContact",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/collaborationCopyLink",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/collaborationInviteWithLink",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/copyToPasteboard",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/mail",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/markupAsPDF",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/message",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/openInIBooks",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToFacebook",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToFlickr",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToTencentWeibo",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToTwitter",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToVimeo",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToWeibo",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/print",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/saveToCameraRoll",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/sharePlay"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/init(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIActivityType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/addToHomeScreen",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/addToReadingList",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/airDrop",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/assignToContact",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/collaborationCopyLink",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/collaborationInviteWithLink",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/copyToPasteboard",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/mail",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/markupAsPDF",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/message",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/openInIBooks",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToFacebook",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToFlickr",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToTencentWeibo",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToTwitter",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToVimeo",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/postToWeibo",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/print",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/saveToCameraRoll",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/ActivityType-swift.struct/sharePlay"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-activity-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityCategory",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/Category",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityType-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityTitle",
                "doc://com.apple.uikit/documentation/UIKit/UIActivity/activityImage"
              ],
              "title": "Getting the activity information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIActivityType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToTwitter/title",
          "value": "UIActivityTypePostToTwitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToTwitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypePostToTwitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1activityCategory/title",
          "value": "activityCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1activityCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToVimeo/title",
          "value": "UIActivityTypePostToVimeo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToVimeo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypePostToVimeo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1message/title",
          "value": "UIActivityTypeMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1message/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct/title",
          "value": "UIActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1copyToPasteboard/title",
          "value": "UIActivityTypeCopyToPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1copyToPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeCopyToPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1assignToContact/title",
          "value": "UIActivityTypeAssignToContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1assignToContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeAssignToContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1sharePlay/title",
          "value": "UIActivityTypeSharePlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1sharePlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeSharePlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1saveToCameraRoll/title",
          "value": "UIActivityTypeSaveToCameraRoll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1saveToCameraRoll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeSaveToCameraRoll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1addToHomeScreen/title",
          "value": "UIActivityTypeAddToHomeScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1addToHomeScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeAddToHomeScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToTencentWeibo/title",
          "value": "UIActivityTypePostToTencentWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToTencentWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypePostToTencentWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1Category/title",
          "value": "UIActivityCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1Category/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1Category/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1collaborationInviteWithLink/title",
          "value": "UIActivityTypeCollaborationInviteWithLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1collaborationInviteWithLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeCollaborationInviteWithLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1activityImage/title",
          "value": "activityImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1activityImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1collaborationCopyLink/title",
          "value": "UIActivityTypeCollaborationCopyLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1collaborationCopyLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeCollaborationCopyLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1mail/title",
          "value": "UIActivityTypeMail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1mail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeMail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1airDrop/title",
          "value": "UIActivityTypeAirDrop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1airDrop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeAirDrop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToFacebook/title",
          "value": "UIActivityTypePostToFacebook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToFacebook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypePostToFacebook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1activityTitle/title",
          "value": "activityTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1activityTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1print/title",
          "value": "UIActivityTypePrint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1print/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypePrint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1openInIBooks/title",
          "value": "UIActivityTypeOpenInIBooks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1openInIBooks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeOpenInIBooks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1markupAsPDF/title",
          "value": "UIActivityTypeMarkupAsPDF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1markupAsPDF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeMarkupAsPDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToWeibo/title",
          "value": "UIActivityTypePostToWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypePostToWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity/title",
          "value": "UIActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1addToReadingList/title",
          "value": "UIActivityTypeAddToReadingList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1addToReadingList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypeAddToReadingList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1activityType-swift.property/title",
          "value": "activityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1activityType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToFlickr/title",
          "value": "UIActivityTypePostToFlickr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity~1ActivityType-swift.struct~1postToFlickr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityTypePostToFlickr"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiactivity/activitytype-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiactivity/activitytype-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
