{
  "abstract": [
    {
      "text": "A structure that contains options for filtering results in a search.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MapKit",
    "externalID": "c:@E@MKAddressFilterOption",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Options"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Options"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MKAddressFilter.Options"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Options"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter": {
      "abstract": [
        {
          "text": "An object that filters which address options to include or exclude in search results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKAddressFilter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilter"
        }
      ],
      "role": "symbol",
      "title": "MKAddressFilter",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options": {
      "abstract": [
        {
          "text": "A structure that contains options for filtering results in a search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "MKAddressFilter.Options",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea": {
      "abstract": [
        {
          "text": "The primary administrative divisions of countries or regions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "administrativeArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionAdministrativeArea"
        }
      ],
      "role": "symbol",
      "title": "administrativeArea",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/administrativearea"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/country": {
      "abstract": [
        {
          "text": "Countries and regions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "country"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/country",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionCountry"
        }
      ],
      "role": "symbol",
      "title": "country",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/country"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a filter options object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/init(rawvalue:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality": {
      "abstract": [
        {
          "text": "Local administrative divisions, postal cities, and populated places.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionLocality"
        }
      ],
      "role": "symbol",
      "title": "locality",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/locality"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode": {
      "abstract": [
        {
          "text": "An address code for mail sorting and delivery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionPostalCode"
        }
      ],
      "role": "symbol",
      "title": "postalCode",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/postalcode"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea": {
      "abstract": [
        {
          "text": "The secondary administrative divisions of countries or regions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subAdministrativeArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionSubAdministrativeArea"
        }
      ],
      "role": "symbol",
      "title": "subAdministrativeArea",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/subadministrativearea"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality": {
      "abstract": [
        {
          "text": "Local administrative subdivisions, postal city subdistricts, and neighborhoods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subLocality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionSubLocality"
        }
      ],
      "role": "symbol",
      "title": "subLocality",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/sublocality"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalPointsOfInterestRequest": {
      "abstract": [
        {
          "text": "A structured request to use when searching for points of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLocalPointsOfInterestRequest"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalPointsOfInterestRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLocalPointsOfInterestRequest"
        }
      ],
      "role": "symbol",
      "title": "MKLocalPointsOfInterestRequest",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalpointsofinterestrequest"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch": {
      "abstract": [
        {
          "text": "A utility object for initiating map-based searches and processing the results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLocalSearch"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLocalSearch"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearch",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearch"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch/ResultType": {
      "abstract": [
        {
          "text": "Options that indicate types of search results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResultType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch/ResultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResultType"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearch.ResultType",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearch/resulttype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter": {
      "abstract": [
        {
          "text": "A utility object for generating a list of completion strings based on a partial search string that you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLocalSearchCompleter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLocalSearchCompleter"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType": {
      "abstract": [
        {
          "text": "Options that indicate types of search completions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResultType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResultType"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter.ResultType",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/resulttype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion": {
      "abstract": [
        {
          "text": "A fully formed string that completes a partial string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLocalSearchCompletion"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLocalSearchCompletion"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompletion",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompletion"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchRegionPriority": {
      "abstract": [
        {
          "text": "A value that indicates the importance of the configured region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLocalSearchRegionPriority"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchRegionPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLocalSearchRegionPriority"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchRegionPriority",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchregionpriority"
    },
    "doc://com.apple.mapkit/documentation/MapKit/interacting-with-nearby-points-of-interest": {
      "abstract": [
        {
          "text": "Provide automatic search completions for a partial search query, search the map for relevant locations nearby, and retrieve details for selected points of interest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/interacting-with-nearby-points-of-interest",
      "kind": "article",
      "role": "sampleCode",
      "title": "Interacting with nearby points of interest",
      "type": "topic",
      "url": "/documentation/mapkit/interacting-with-nearby-points-of-interest"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Local-search",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/interacting-with-nearby-points-of-interest",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchRegionPriority",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch/ResultType",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalPointsOfInterestRequest"
      ],
      "title": "Local search"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-filter-result",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/init(rawValue:)"
      ],
      "title": "Creating a filter result"
    },
    {
      "anchor": "Getting-search-filter-options",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/country",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/country",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality"
      ],
      "title": "Getting search filter options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKAddressFilterOption"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-search-filter-options",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/country",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/country",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality"
              ],
              "title": "Getting search filter options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Local-search",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/interacting-with-nearby-points-of-interest",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchRegionPriority",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch/ResultType",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalPointsOfInterestRequest"
              ],
              "title": "Local search"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKAddressFilterOption"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch/title",
          "value": "MKLocalSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchRegionPriority/title",
          "value": "MKLocalSearchRegionPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchRegionPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchRegionPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchRegionPriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchRegionPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options/title",
          "value": "MKAddressFilterOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/title",
          "value": "MKLocalSearchCompleter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch~1ResultType/title",
          "value": "MKLocalSearchResultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch~1ResultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch~1ResultType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter/title",
          "value": "MKAddressFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalPointsOfInterestRequest/title",
          "value": "MKLocalPointsOfInterestRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalPointsOfInterestRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalPointsOfInterestRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalPointsOfInterestRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalPointsOfInterestRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion/title",
          "value": "MKLocalSearchCompletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1locality/title",
          "value": "MKAddressFilterOptionLocality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1locality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionLocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1subLocality/title",
          "value": "MKAddressFilterOptionSubLocality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1subLocality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionSubLocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1administrativeArea/title",
          "value": "MKAddressFilterOptionAdministrativeArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1administrativeArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionAdministrativeArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1subAdministrativeArea/title",
          "value": "MKAddressFilterOptionSubAdministrativeArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1subAdministrativeArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionSubAdministrativeArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/title",
          "value": "MKLocalSearchCompleterResultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleterResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleterResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1country/title",
          "value": "MKAddressFilterOptionCountry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1country/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionCountry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1postalCode/title",
          "value": "MKAddressFilterOptionPostalCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1postalCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionPostalCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkaddressfilter/options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkaddressfilter/options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
