{
  "abstract": [
    {
      "text": "A medium weight.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIImage",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/medium"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIImageSymbolWeight@UIImageSymbolWeightMedium",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "medium"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIImageSymbolWeightMedium"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIImage.SymbolWeight.medium"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "medium"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight": {
      "abstract": [
        {
          "text": "Constants that indicate which weight variant of a symbol image to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolWeight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SymbolWeight"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/black": {
      "abstract": [
        {
          "text": "An ultra-heavy weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "black"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/black",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageSymbolWeightBlack"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight.black",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight/black"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/bold": {
      "abstract": [
        {
          "text": "A bold weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bold"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/bold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageSymbolWeightBold"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight.bold",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight/bold"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/heavy": {
      "abstract": [
        {
          "text": "A heavy weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heavy"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/heavy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageSymbolWeightHeavy"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight.heavy",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight/heavy"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/light": {
      "abstract": [
        {
          "text": "A light weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "light"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/light",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageSymbolWeightLight"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight.light",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight/light"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/medium": {
      "abstract": [
        {
          "text": "A medium weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageSymbolWeightMedium"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight.medium",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight/medium"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/regular": {
      "abstract": [
        {
          "text": "A regular weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regular"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/regular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageSymbolWeightRegular"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight.regular",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight/regular"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/semibold": {
      "abstract": [
        {
          "text": "A semibold weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "semibold"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/semibold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageSymbolWeightSemibold"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight.semibold",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight/semibold"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/thin": {
      "abstract": [
        {
          "text": "A thin weight",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thin"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/thin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageSymbolWeightThin"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight.thin",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight/thin"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/ultraLight": {
      "abstract": [
        {
          "text": "An ultralight weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ultraLight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/ultraLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageSymbolWeightUltraLight"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight.ultraLight",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight/ultralight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/unspecified": {
      "abstract": [
        {
          "text": "An unspecified symbol image weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageSymbolWeightUnspecified"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolWeight.unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolweight/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Symbol-image-weights",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/unspecified",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/ultraLight",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/thin",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/light",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/regular",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/semibold",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/bold",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/heavy",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/black"
      ],
      "title": "Symbol image weights"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIImageSymbolWeightMedium"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Symbol-image-weights",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/unspecified",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/ultraLight",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/thin",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/light",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/regular",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/semibold",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/bold",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/heavy",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight/black"
              ],
              "title": "Symbol image weights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIImageSymbolWeightMedium"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1light/title",
          "value": "UIImageSymbolWeightLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1light/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1heavy/title",
          "value": "UIImageSymbolWeightHeavy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1heavy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightHeavy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1ultraLight/title",
          "value": "UIImageSymbolWeightUltraLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1ultraLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightUltraLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1black/title",
          "value": "UIImageSymbolWeightBlack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1black/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightBlack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1thin/title",
          "value": "UIImageSymbolWeightThin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1thin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightThin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight/title",
          "value": "UIImageSymbolWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1regular/title",
          "value": "UIImageSymbolWeightRegular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1regular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightRegular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1unspecified/title",
          "value": "UIImageSymbolWeightUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1bold/title",
          "value": "UIImageSymbolWeightBold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1bold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightBold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1medium/title",
          "value": "UIImageSymbolWeightMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1semibold/title",
          "value": "UIImageSymbolWeightSemibold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight~1semibold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolWeightSemibold"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiimage/symbolweight/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiimage/symbolweight/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
