{
  "abstract": [
    {
      "text": "Error code constants for framework operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/error-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError": {
      "abstract": [
        {
          "text": "A structure that represents a framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPError"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPError"
        }
      ],
      "role": "symbol",
      "title": "MPError",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code": {
      "abstract": [
        {
          "text": "An enumeration that represents error codes for framework operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MPError.Code",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/code"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/cancelled": {
      "abstract": [
        {
          "text": "The system cancels the requested operation before it completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MPErrorCodeLeV",
          "text": "MPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/cancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "cancelled",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/cancelled"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/cloudServiceCapabilityMissing": {
      "abstract": [
        {
          "text": "The operation can’t complete because iCloud services aren’t in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServiceCapabilityMissing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MPErrorCodeLeV",
          "text": "MPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/cloudServiceCapabilityMissing",
      "kind": "symbol",
      "role": "symbol",
      "title": "cloudServiceCapabilityMissing",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/cloudservicecapabilitymissing"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/networkConnectionFailed": {
      "abstract": [
        {
          "text": "The operation fails because the device can’t connect to the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkConnectionFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MPErrorCodeLeV",
          "text": "MPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/networkConnectionFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkConnectionFailed",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/networkconnectionfailed"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/notFound": {
      "abstract": [
        {
          "text": "The operation fails because the system can’t find the requested identifier in the current storefront.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MPErrorCodeLeV",
          "text": "MPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/notFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "notFound",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/notfound"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/notSupported": {
      "abstract": [
        {
          "text": "The requested operation fails because the system doesn’t support it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MPErrorCodeLeV",
          "text": "MPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/notSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "notSupported",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/notsupported"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/permissionDenied": {
      "abstract": [
        {
          "text": "The operation can’t complete because the user doesn’t have permission for the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MPErrorCodeLeV",
          "text": "MPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/permissionDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "permissionDenied",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/permissiondenied"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/requestTimedOut": {
      "abstract": [
        {
          "text": "The requested operation times out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestTimedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MPErrorCodeLeV",
          "text": "MPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/requestTimedOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestTimedOut",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/requesttimedout"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/unknown": {
      "abstract": [
        {
          "text": "The requested operation can’t complete due to an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MPErrorCodeLeV",
          "text": "MPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-an-error",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code"
      ],
      "title": "Inspecting an error"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-code-constants",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/cancelled",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/cloudServiceCapabilityMissing",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/unknown",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/networkConnectionFailed",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/notFound",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/notSupported",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/permissionDenied",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/requestTimedOut"
      ],
      "title": "Error code constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-an-error",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code"
              ],
              "title": "Inspecting an error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code/title",
          "value": "MPErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/error-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/error-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
