{
  "abstract": [
    {
      "text": "Respond to incoming feedback and rating events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Feedback and rating events"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPFeedbackCommand": {
      "abstract": [
        {
          "text": "An object that reflects the feedback state for the playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPFeedbackCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPFeedbackCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPFeedbackCommand"
        }
      ],
      "role": "symbol",
      "title": "MPFeedbackCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpfeedbackcommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPFeedbackCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the feedback setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPFeedbackCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPFeedbackCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPFeedbackCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPFeedbackCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpfeedbackcommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRatingCommand": {
      "abstract": [
        {
          "text": "An object that provides a detailed rating for the playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRatingCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRatingCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRatingCommand"
        }
      ],
      "role": "symbol",
      "title": "MPRatingCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpratingcommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRatingCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the rating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRatingCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRatingCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRatingCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPRatingCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpratingcommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications": {
      "abstract": [
        {
          "text": "Handle events for external media players.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
      "kind": "article",
      "role": "article",
      "title": "Handling external player events notifications",
      "type": "topic",
      "url": "/documentation/mediaplayer/handling-external-player-events-notifications"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events": {
      "abstract": [
        {
          "text": "Respond to changes in the way media items play.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media playback mode events",
      "type": "topic",
      "url": "/documentation/mediaplayer/media-playback-mode-events"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events": {
      "abstract": [
        {
          "text": "Set up the remote command center to handle media player events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Remote command center events",
      "type": "topic",
      "url": "/documentation/mediaplayer/remote-command-center-events"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events": {
      "abstract": [
        {
          "text": "Respond to requests to change which part of a media item plays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Track navigation events",
      "type": "topic",
      "url": "/documentation/mediaplayer/track-navigation-events"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "External-player-and-system-event-handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events"
      ],
      "title": "External player and system event handling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-feedback-and-rating-events",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPFeedbackCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPFeedbackCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRatingCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRatingCommandEvent"
      ],
      "title": "Responding to feedback and rating events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-feedback-and-rating-events",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPFeedbackCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPFeedbackCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRatingCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRatingCommandEvent"
              ],
              "title": "Responding to feedback and rating events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "External-player-and-system-event-handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events"
              ],
              "title": "External player and system event handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRatingCommandEvent/title",
          "value": "MPRatingCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRatingCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRatingCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRatingCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRatingCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPFeedbackCommand/title",
          "value": "MPFeedbackCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPFeedbackCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPFeedbackCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPFeedbackCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPFeedbackCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPFeedbackCommandEvent/title",
          "value": "MPFeedbackCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPFeedbackCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPFeedbackCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPFeedbackCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPFeedbackCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRatingCommand/title",
          "value": "MPRatingCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRatingCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRatingCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRatingCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRatingCommand"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/feedback-and-rating-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/feedback-and-rating-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
