{
  "abstract": [
    {
      "text": "System-defined properties for obtaining the metadata for a media item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/general-media-item-property-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "General media item property keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Obtain metadata for a media item by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaEntity/value(forProperty:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method with these property keys. You can use the filterable property keys to build media property predicates, which ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPropertyPredicate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " describes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaEntity/value(forProperty:)": {
      "abstract": [
        {
          "text": "Retrieves the value for a specified media property key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaEntity/value(forProperty:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForProperty:"
        }
      ],
      "role": "symbol",
      "title": "value(forProperty:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaentity/value(forproperty:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem": {
      "abstract": [
        {
          "text": "A collection of properties that represents a single item in the media library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItem"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItem"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItem",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitem"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtist": {
      "abstract": [
        {
          "text": "The primary performing artist for an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumArtist"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumArtist",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumartist"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtistPersistentID": {
      "abstract": [
        {
          "text": "The persistent identifier for an album artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumArtistPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtistPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumArtistPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumArtistPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumartistpersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumPersistentID": {
      "abstract": [
        {
          "text": "The key for the persistent identifier for an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumpersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTitle": {
      "abstract": [
        {
          "text": "The title of an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTitle"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumTitle",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumtitle"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackCount": {
      "abstract": [
        {
          "text": "The number of tracks for the album that contains the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTrackCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTrackCount"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumTrackCount",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumtrackcount"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackNumber": {
      "abstract": [
        {
          "text": "The track number of the media item, for a media item that is part of an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTrackNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTrackNumber"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumTrackNumber",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumtracknumber"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtist": {
      "abstract": [
        {
          "text": "The performing artists for a media item — which may vary from the primary artist for the album that a media item belongs to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtist"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyArtist",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyartist"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtistPersistentID": {
      "abstract": [
        {
          "text": "The key for the persistent identifier for an artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtistPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtistPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtistPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyArtistPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyartistpersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtwork": {
      "abstract": [
        {
          "text": "The artwork image for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtwork"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyArtwork",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyartwork"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAssetURL": {
      "abstract": [
        {
          "text": "A URL that points to the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAssetURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAssetURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAssetURL"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAssetURL",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyasseturl"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBeatsPerMinute": {
      "abstract": [
        {
          "text": "The number of musical beats per minute for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyBeatsPerMinute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBeatsPerMinute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyBeatsPerMinute"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyBeatsPerMinute",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertybeatsperminute"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComments": {
      "abstract": [
        {
          "text": "Textual information about the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComments"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyComments",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertycomments"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposer": {
      "abstract": [
        {
          "text": "The musical composer for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComposer"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyComposer",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertycomposer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposerPersistentID": {
      "abstract": [
        {
          "text": "The persistent identifier for a composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComposerPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposerPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComposerPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyComposerPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertycomposerpersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscCount": {
      "abstract": [
        {
          "text": "The number of discs for the album that contains the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyDiscCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyDiscCount"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyDiscCount",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertydisccount"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscNumber": {
      "abstract": [
        {
          "text": "The disc number of the media item, for a media item that is part of a multidisc album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyDiscNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyDiscNumber"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyDiscNumber",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertydiscnumber"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenre": {
      "abstract": [
        {
          "text": "The music or film genre of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyGenre"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyGenre"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyGenre",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertygenre"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenrePersistentID": {
      "abstract": [
        {
          "text": "The persistent identifier for a genre.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyGenrePersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenrePersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyGenrePersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyGenrePersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertygenrepersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyHasProtectedAsset": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the media item has DRM protection so it can’t play through a standard playback API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyHasProtectedAsset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyHasProtectedAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyHasProtectedAsset"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyHasProtectedAsset",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyhasprotectedasset"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCloudItem": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media item is an iCloud item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsCloudItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCloudItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsCloudItem"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyIsCloudItem",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyisclouditem"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCompilation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media item is part of a compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsCompilation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCompilation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsCompilation"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyIsCompilation",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyiscompilation"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsExplicit": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media item contains explicit (adult) lyrics or language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsExplicit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsExplicit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsExplicit"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyIsExplicit",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyisexplicit"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsPreorder": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media item is a preorder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsPreorder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsPreorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsPreorder"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyIsPreorder",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyispreorder"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLyrics": {
      "abstract": [
        {
          "text": "The lyrics for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyLyrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLyrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyLyrics"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyLyrics",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertylyrics"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyMediaType": {
      "abstract": [
        {
          "text": "The media type of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyMediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyMediaType"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyMediaType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertymediatype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPersistentID": {
      "abstract": [
        {
          "text": "The key for the persistent identifier for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertypersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlayCount": {
      "abstract": [
        {
          "text": "The number of times the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlayCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlayCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlayCount"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyPlayCount",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyplaycount"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackDuration": {
      "abstract": [
        {
          "text": "The playback duration of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlaybackDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlaybackDuration"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyPlaybackDuration",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyplaybackduration"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackStoreID": {
      "abstract": [
        {
          "text": "The identifier for enqueueing store tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlaybackStoreID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackStoreID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlaybackStoreID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyPlaybackStoreID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyplaybackstoreid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPodcastPersistentID": {
      "abstract": [
        {
          "text": "The persistent identifier for an audio podcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPodcastPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPodcastPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPodcastPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyPodcastPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertypodcastpersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPodcastTitle": {
      "abstract": [
        {
          "text": "The title of a podcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPodcastTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPodcastTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPodcastTitle"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyPodcastTitle",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertypodcasttitle"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyReleaseDate": {
      "abstract": [
        {
          "text": "The date of the media item’s first public release.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyReleaseDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyReleaseDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyReleaseDate"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyReleaseDate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyreleasedate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyTitle": {
      "abstract": [
        {
          "text": "The title or name of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyTitle"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyTitle",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertytitle"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPropertyPredicate": {
      "abstract": [
        {
          "text": "A set of predicates for defining a filter in a media query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaPropertyPredicate"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPropertyPredicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaPropertyPredicate"
        }
      ],
      "role": "symbol",
      "title": "MPMediaPropertyPredicate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediapropertypredicate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType": {
      "abstract": [
        {
          "text": "The properties for defining the type for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaType"
        }
      ],
      "role": "symbol",
      "title": "MPMediaType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/user-defined-property-keys": {
      "abstract": [
        {
          "text": "Properties for obtaining user-defined metadata for a media item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/user-defined-property-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "User-defined property keys",
      "type": "topic",
      "url": "/documentation/mediaplayer/user-defined-property-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-item-types-and-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/user-defined-property-keys"
      ],
      "title": "Media item types and keys"
    }
  ],
  "topicSections": [
    {
      "anchor": "Property-keys",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackDuration",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackNumber",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackCount",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscNumber",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscCount",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtwork",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLyrics",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyReleaseDate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBeatsPerMinute",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComments",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAssetURL",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsExplicit",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsPreorder",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackStoreID"
      ],
      "title": "Property keys"
    },
    {
      "anchor": "Filterable-property-keys",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtist",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtistPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTitle",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtist",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtistPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposerPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenre",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenrePersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyHasProtectedAsset",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCompilation",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCloudItem",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyMediaType",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlayCount",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPodcastPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPodcastTitle",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyTitle"
      ],
      "title": "Filterable property keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Property-keys",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackDuration",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackNumber",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackCount",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscNumber",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscCount",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtwork",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLyrics",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyReleaseDate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBeatsPerMinute",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComments",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAssetURL",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsExplicit",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsPreorder",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackStoreID"
              ],
              "title": "Property keys"
            },
            {
              "anchor": "Filterable-property-keys",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtist",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtistPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTitle",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtist",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtistPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposerPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenre",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenrePersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyHasProtectedAsset",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCompilation",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCloudItem",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyMediaType",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlayCount",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPodcastPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPodcastTitle",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyTitle"
              ],
              "title": "Filterable property keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-item-types-and-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/user-defined-property-keys"
              ],
              "title": "Media item types and keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumArtistPersistentID/title",
          "value": "MPMediaItemPropertyAlbumArtistPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumArtistPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumArtistPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlaybackStoreID/title",
          "value": "MPMediaItemPropertyPlaybackStoreID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlaybackStoreID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPlaybackStoreID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPodcastTitle/title",
          "value": "MPMediaItemPropertyPodcastTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPodcastTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPodcastTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyHasProtectedAsset/title",
          "value": "MPMediaItemPropertyHasProtectedAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyHasProtectedAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyHasProtectedAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyGenre/title",
          "value": "MPMediaItemPropertyGenre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyGenre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyGenre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsExplicit/title",
          "value": "MPMediaItemPropertyIsExplicit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsExplicit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyIsExplicit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPersistentID/title",
          "value": "MPMediaItemPropertyPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPropertyPredicate/title",
          "value": "MPMediaPropertyPredicate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPropertyPredicate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPropertyPredicate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPropertyPredicate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPropertyPredicate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType/title",
          "value": "MPMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumArtist/title",
          "value": "MPMediaItemPropertyAlbumArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAssetURL/title",
          "value": "MPMediaItemPropertyAssetURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAssetURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAssetURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyDiscCount/title",
          "value": "MPMediaItemPropertyDiscCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyDiscCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyDiscCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyBeatsPerMinute/title",
          "value": "MPMediaItemPropertyBeatsPerMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyBeatsPerMinute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyBeatsPerMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem/title",
          "value": "MPMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyTitle/title",
          "value": "MPMediaItemPropertyTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtistPersistentID/title",
          "value": "MPMediaItemPropertyArtistPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtistPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyArtistPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlayCount/title",
          "value": "MPMediaItemPropertyPlayCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlayCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPlayCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyDiscNumber/title",
          "value": "MPMediaItemPropertyDiscNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyDiscNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyDiscNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumPersistentID/title",
          "value": "MPMediaItemPropertyAlbumPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComments/title",
          "value": "MPMediaItemPropertyComments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyComments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTitle/title",
          "value": "MPMediaItemPropertyAlbumTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsCompilation/title",
          "value": "MPMediaItemPropertyIsCompilation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsCompilation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyIsCompilation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyReleaseDate/title",
          "value": "MPMediaItemPropertyReleaseDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyReleaseDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyReleaseDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsPreorder/title",
          "value": "MPMediaItemPropertyIsPreorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsPreorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyIsPreorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComposer/title",
          "value": "MPMediaItemPropertyComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlaybackDuration/title",
          "value": "MPMediaItemPropertyPlaybackDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlaybackDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPlaybackDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtwork/title",
          "value": "MPMediaItemPropertyArtwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyArtwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaEntity~1value(forProperty:)/title",
          "value": "valueForProperty:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaEntity~1value(forProperty:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueForProperty:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyLyrics/title",
          "value": "MPMediaItemPropertyLyrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyLyrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyLyrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyGenrePersistentID/title",
          "value": "MPMediaItemPropertyGenrePersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyGenrePersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyGenrePersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyMediaType/title",
          "value": "MPMediaItemPropertyMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsCloudItem/title",
          "value": "MPMediaItemPropertyIsCloudItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsCloudItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyIsCloudItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPodcastPersistentID/title",
          "value": "MPMediaItemPropertyPodcastPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPodcastPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPodcastPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComposerPersistentID/title",
          "value": "MPMediaItemPropertyComposerPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComposerPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyComposerPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtist/title",
          "value": "MPMediaItemPropertyArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTrackNumber/title",
          "value": "MPMediaItemPropertyAlbumTrackNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTrackNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumTrackNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTrackCount/title",
          "value": "MPMediaItemPropertyAlbumTrackCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTrackCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumTrackCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/general-media-item-property-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/general-media-item-property-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
