{
  "abstract": [
    {
      "text": "The constants for defining language characteristics.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/language-option-characteristic-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Language option characteristic constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles": {
      "abstract": [
        {
          "text": "Indicates that the language option presents only forced subtitles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristiccontainsonlyforcedsubtitles"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesMusicAndSound": {
      "abstract": [
        {
          "text": "Indicates that the language option includes legible content in the language of its specified locale that describes music and sound effects occurring in program audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesMusicAndSound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicDescribesMusicAndSound",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicdescribesmusicandsound"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesVideo": {
      "abstract": [
        {
          "text": "Indicates that the language option includes audible content that describes the visual portion of the presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDescribesVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDescribesVideo"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicDescribesVideo",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicdescribesvideo"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDubbedTranslation": {
      "abstract": [
        {
          "text": "Indicates that the language option includes content that contains a dubbed translation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDubbedTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDubbedTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDubbedTranslation"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicDubbedTranslation",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicdubbedtranslation"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicEasyToRead": {
      "abstract": [
        {
          "text": "Indicates that the language option provides legible content in the language of its specified locale and that the content was edited for ease of reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicEasyToRead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicEasyToRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicEasyToRead"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicEasyToRead",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristiceasytoread"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsAuxiliaryContent": {
      "abstract": [
        {
          "text": "Indicates that the language option includes content that’s marked by the content author as auxiliary to the presentation of the language option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicIsAuxiliaryContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsAuxiliaryContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicIsAuxiliaryContent"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicIsAuxiliaryContent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicisauxiliarycontent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsMainProgramContent": {
      "abstract": [
        {
          "text": "Indicates that the language option includes content that’s marked by the content author as intrinsic to the presentation of the language option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicIsMainProgramContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsMainProgramContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicIsMainProgramContent"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicIsMainProgramContent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicismainprogramcontent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicLanguageTranslation": {
      "abstract": [
        {
          "text": "Indicates that the language option contains a translation in the language of its specified locale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicLanguageTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicLanguageTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicLanguageTranslation"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicLanguageTranslation",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristiclanguagetranslation"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicTranscribesSpokenDialog": {
      "abstract": [
        {
          "text": "Indicates that the language option includes legible content in the language of its specified locale that transcribes spoken dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicTranscribesSpokenDialog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicTranscribesSpokenDialog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicTranscribesSpokenDialog"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicTranscribesSpokenDialog",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristictranscribesspokendialog"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicVoiceOverTranslation": {
      "abstract": [
        {
          "text": "Indicates that the language option includes voice over content in the language of its specified locale describes translated dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicVoiceOverTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicVoiceOverTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicVoiceOverTranslation"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicVoiceOverTranslation",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicvoiceovertranslation"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoCenter": {
      "abstract": [
        {
          "text": "An object for setting the Now Playing information for media that your app plays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoCenter"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoCenter"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoCenter",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfocenter"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoLanguageOption": {
      "abstract": [
        {
          "text": "A set of interfaces for setting the language option for the Now Playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoLanguageOption"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoLanguageOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoLanguageOption"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoLanguageOption",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfolanguageoption"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoLanguageOptionGroup": {
      "abstract": [
        {
          "text": "A grouped set of language options where only a single language option can be active at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoLanguageOptionGroup"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoLanguageOptionGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoLanguageOptionGroup"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoLanguageOptionGroup",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfolanguageoptiongroup"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession": {
      "abstract": [
        {
          "text": "An object that manages Now Playing information and remote commands for multiple players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingSession"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingSession"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingSession",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayingsession"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/becoming-a-now-playable-app": {
      "abstract": [
        {
          "text": "Ensure your app is eligible to become the Now Playing app by adopting best practices for providing Now Playing info and registering for remote command center actions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/becoming-a-now-playable-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Becoming a now playable app",
      "type": "topic",
      "url": "/documentation/mediaplayer/becoming-a-now-playable-app"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Now-Playing-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/becoming-a-now-playable-app",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoCenter",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoLanguageOption",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoLanguageOptionGroup"
      ],
      "title": "Now Playing information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Language-option-characteristic-constants",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesMusicAndSound",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesVideo",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDubbedTranslation",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicEasyToRead",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsAuxiliaryContent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsMainProgramContent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicLanguageTranslation",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicTranscribesSpokenDialog",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicVoiceOverTranslation"
      ],
      "title": "Language option characteristic constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Language-option-characteristic-constants",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesMusicAndSound",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesVideo",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDubbedTranslation",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicEasyToRead",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsAuxiliaryContent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsMainProgramContent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicLanguageTranslation",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicTranscribesSpokenDialog",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicVoiceOverTranslation"
              ],
              "title": "Language option characteristic constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Now-Playing-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/becoming-a-now-playable-app",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingSession",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoCenter",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoLanguageOption",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoLanguageOptionGroup"
              ],
              "title": "Now Playing information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicIsAuxiliaryContent/title",
          "value": "MPLanguageOptionCharacteristicIsAuxiliaryContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicIsAuxiliaryContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicIsAuxiliaryContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDubbedTranslation/title",
          "value": "MPLanguageOptionCharacteristicDubbedTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDubbedTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicDubbedTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoLanguageOption/title",
          "value": "MPNowPlayingInfoLanguageOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoLanguageOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoLanguageOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoLanguageOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoLanguageOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicIsMainProgramContent/title",
          "value": "MPLanguageOptionCharacteristicIsMainProgramContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicIsMainProgramContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicIsMainProgramContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicTranscribesSpokenDialog/title",
          "value": "MPLanguageOptionCharacteristicTranscribesSpokenDialog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicTranscribesSpokenDialog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicTranscribesSpokenDialog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession/title",
          "value": "MPNowPlayingSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicLanguageTranslation/title",
          "value": "MPLanguageOptionCharacteristicLanguageTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicLanguageTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicLanguageTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDescribesVideo/title",
          "value": "MPLanguageOptionCharacteristicDescribesVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDescribesVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicDescribesVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicEasyToRead/title",
          "value": "MPLanguageOptionCharacteristicEasyToRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicEasyToRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicEasyToRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles/title",
          "value": "MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicVoiceOverTranslation/title",
          "value": "MPLanguageOptionCharacteristicVoiceOverTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicVoiceOverTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicVoiceOverTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoLanguageOptionGroup/title",
          "value": "MPNowPlayingInfoLanguageOptionGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoLanguageOptionGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoLanguageOptionGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoLanguageOptionGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoLanguageOptionGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDescribesMusicAndSound/title",
          "value": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDescribesMusicAndSound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoCenter/title",
          "value": "MPNowPlayingInfoCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoCenter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/language-option-characteristic-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/language-option-characteristic-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
