{
  "abstract": [
    {
      "text": "Respond to changes in the way media items play.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Media playback mode events"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeLanguageOptionCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the language option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeLanguageOptionCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeLanguageOptionCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangeLanguageOptionCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPChangeLanguageOptionCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangelanguageoptioncommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommand": {
      "abstract": [
        {
          "text": "An object that responds to requests to change the playback rate of the playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangePlaybackRateCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangePlaybackRateCommand"
        }
      ],
      "role": "symbol",
      "title": "MPChangePlaybackRateCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangeplaybackratecommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the playback rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangePlaybackRateCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangePlaybackRateCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPChangePlaybackRateCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangeplaybackratecommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommand": {
      "abstract": [
        {
          "text": "An object that responds to requests to change the current repeat mode used during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeRepeatModeCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangeRepeatModeCommand"
        }
      ],
      "role": "symbol",
      "title": "MPChangeRepeatModeCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangerepeatmodecommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the repeat mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeRepeatModeCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangeRepeatModeCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPChangeRepeatModeCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangerepeatmodecommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommand": {
      "abstract": [
        {
          "text": "An object that responds to requests to change the current shuffle mode used during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeShuffleModeCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangeShuffleModeCommand"
        }
      ],
      "role": "symbol",
      "title": "MPChangeShuffleModeCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangeshufflemodecommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the shuffle mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeShuffleModeCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangeShuffleModeCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPChangeShuffleModeCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangeshufflemodecommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRepeatType": {
      "abstract": [
        {
          "text": "Indicates which items to play repeatedly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRepeatType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRepeatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRepeatType"
        }
      ],
      "role": "symbol",
      "title": "MPRepeatType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mprepeattype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType": {
      "abstract": [
        {
          "text": "Indicates which item types to shuffle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPShuffleType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPShuffleType"
        }
      ],
      "role": "symbol",
      "title": "MPShuffleType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpshuffletype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events": {
      "abstract": [
        {
          "text": "Respond to incoming feedback and rating events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Feedback and rating events",
      "type": "topic",
      "url": "/documentation/mediaplayer/feedback-and-rating-events"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications": {
      "abstract": [
        {
          "text": "Handle events for external media players.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
      "kind": "article",
      "role": "article",
      "title": "Handling external player events notifications",
      "type": "topic",
      "url": "/documentation/mediaplayer/handling-external-player-events-notifications"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events": {
      "abstract": [
        {
          "text": "Set up the remote command center to handle media player events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Remote command center events",
      "type": "topic",
      "url": "/documentation/mediaplayer/remote-command-center-events"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events": {
      "abstract": [
        {
          "text": "Respond to requests to change which part of a media item plays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Track navigation events",
      "type": "topic",
      "url": "/documentation/mediaplayer/track-navigation-events"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "External-player-and-system-event-handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events"
      ],
      "title": "External player and system event handling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-changes-to-media-playback-mode-events",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeLanguageOptionCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRepeatType",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType"
      ],
      "title": "Responding to changes to media playback mode events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-changes-to-media-playback-mode-events",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeLanguageOptionCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRepeatType",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType"
              ],
              "title": "Responding to changes to media playback mode events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "External-player-and-system-event-handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events"
              ],
              "title": "External player and system event handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommandEvent/title",
          "value": "MPChangeRepeatModeCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeRepeatModeCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeRepeatModeCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeLanguageOptionCommandEvent/title",
          "value": "MPChangeLanguageOptionCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeLanguageOptionCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeLanguageOptionCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeLanguageOptionCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeLanguageOptionCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommand/title",
          "value": "MPChangePlaybackRateCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackRateCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackRateCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommandEvent/title",
          "value": "MPChangePlaybackRateCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackRateCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackRateCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommand/title",
          "value": "MPChangeRepeatModeCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeRepeatModeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeRepeatModeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommandEvent/title",
          "value": "MPChangeShuffleModeCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeShuffleModeCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeShuffleModeCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommand/title",
          "value": "MPChangeShuffleModeCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeShuffleModeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeShuffleModeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType/title",
          "value": "MPShuffleType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPShuffleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPShuffleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRepeatType/title",
          "value": "MPRepeatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRepeatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRepeatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRepeatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRepeatType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/media-playback-mode-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/media-playback-mode-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
