{
  "abstract": [
    {
      "text": "Indicates that the language option includes legible content in the language of its specified locale that describes music and sound effects occurring in program audio.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesMusicAndSound"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MPLanguageOptionCharacteristicDescribesMusicAndSound",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "It’s possible for a legible language option to include both transcriptions of spoken dialog and descriptions of music and sound effects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles": {
      "abstract": [
        {
          "text": "Indicates that the language option presents only forced subtitles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristiccontainsonlyforcedsubtitles"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesMusicAndSound": {
      "abstract": [
        {
          "text": "Indicates that the language option includes legible content in the language of its specified locale that describes music and sound effects occurring in program audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesMusicAndSound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicDescribesMusicAndSound",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicdescribesmusicandsound"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesVideo": {
      "abstract": [
        {
          "text": "Indicates that the language option includes audible content that describes the visual portion of the presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDescribesVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDescribesVideo"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicDescribesVideo",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicdescribesvideo"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDubbedTranslation": {
      "abstract": [
        {
          "text": "Indicates that the language option includes content that contains a dubbed translation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDubbedTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDubbedTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicDubbedTranslation"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicDubbedTranslation",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicdubbedtranslation"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicEasyToRead": {
      "abstract": [
        {
          "text": "Indicates that the language option provides legible content in the language of its specified locale and that the content was edited for ease of reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicEasyToRead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicEasyToRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicEasyToRead"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicEasyToRead",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristiceasytoread"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsAuxiliaryContent": {
      "abstract": [
        {
          "text": "Indicates that the language option includes content that’s marked by the content author as auxiliary to the presentation of the language option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicIsAuxiliaryContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsAuxiliaryContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicIsAuxiliaryContent"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicIsAuxiliaryContent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicisauxiliarycontent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsMainProgramContent": {
      "abstract": [
        {
          "text": "Indicates that the language option includes content that’s marked by the content author as intrinsic to the presentation of the language option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicIsMainProgramContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsMainProgramContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicIsMainProgramContent"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicIsMainProgramContent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicismainprogramcontent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicLanguageTranslation": {
      "abstract": [
        {
          "text": "Indicates that the language option contains a translation in the language of its specified locale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicLanguageTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicLanguageTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicLanguageTranslation"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicLanguageTranslation",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristiclanguagetranslation"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicTranscribesSpokenDialog": {
      "abstract": [
        {
          "text": "Indicates that the language option includes legible content in the language of its specified locale that transcribes spoken dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicTranscribesSpokenDialog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicTranscribesSpokenDialog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicTranscribesSpokenDialog"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicTranscribesSpokenDialog",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristictranscribesspokendialog"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicVoiceOverTranslation": {
      "abstract": [
        {
          "text": "Indicates that the language option includes voice over content in the language of its specified locale describes translated dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicVoiceOverTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicVoiceOverTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPLanguageOptionCharacteristicVoiceOverTranslation"
        }
      ],
      "role": "symbol",
      "title": "MPLanguageOptionCharacteristicVoiceOverTranslation",
      "type": "topic",
      "url": "/documentation/mediaplayer/mplanguageoptioncharacteristicvoiceovertranslation"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Language-option-characteristic-constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesVideo",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDubbedTranslation",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicEasyToRead",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsAuxiliaryContent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsMainProgramContent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicLanguageTranslation",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicTranscribesSpokenDialog",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicVoiceOverTranslation"
      ],
      "title": "Language option characteristic constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Language-option-characteristic-constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDescribesVideo",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicDubbedTranslation",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicEasyToRead",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsAuxiliaryContent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicIsMainProgramContent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicLanguageTranslation",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicTranscribesSpokenDialog",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPLanguageOptionCharacteristicVoiceOverTranslation"
              ],
              "title": "Language option characteristic constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicIsMainProgramContent/title",
          "value": "MPLanguageOptionCharacteristicIsMainProgramContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicIsMainProgramContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicIsMainProgramContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicVoiceOverTranslation/title",
          "value": "MPLanguageOptionCharacteristicVoiceOverTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicVoiceOverTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicVoiceOverTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDescribesMusicAndSound/title",
          "value": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDescribesMusicAndSound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicDescribesMusicAndSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicEasyToRead/title",
          "value": "MPLanguageOptionCharacteristicEasyToRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicEasyToRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicEasyToRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles/title",
          "value": "MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicContainsOnlyForcedSubtitles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicLanguageTranslation/title",
          "value": "MPLanguageOptionCharacteristicLanguageTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicLanguageTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicLanguageTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDescribesVideo/title",
          "value": "MPLanguageOptionCharacteristicDescribesVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDescribesVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicDescribesVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDubbedTranslation/title",
          "value": "MPLanguageOptionCharacteristicDubbedTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicDubbedTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicDubbedTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicIsAuxiliaryContent/title",
          "value": "MPLanguageOptionCharacteristicIsAuxiliaryContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicIsAuxiliaryContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicIsAuxiliaryContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicTranscribesSpokenDialog/title",
          "value": "MPLanguageOptionCharacteristicTranscribesSpokenDialog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPLanguageOptionCharacteristicTranscribesSpokenDialog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPLanguageOptionCharacteristicTranscribesSpokenDialog"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mplanguageoptioncharacteristicdescribesmusicandsound"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mplanguageoptioncharacteristicdescribesmusicandsound"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
