{
  "abstract": [
    {
      "text": "The persistent identifier for a genre.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenrePersistentID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MPMediaItemPropertyGenrePersistentID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MPMediaItemPropertyGenrePersistentID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMediaItemPropertyGenrePersistentID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MPMediaItemPropertyGenrePersistentID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyGenrePersistentID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This value is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that contains a ",
              "type": "text"
            },
            {
              "code": "uint64_t",
              "type": "codeVoice"
            },
            {
              "text": " (unsigned long long). The value of the ",
              "type": "text"
            },
            {
              "code": "MPMediaItemPropertyGenrePersistentID",
              "type": "codeVoice"
            },
            {
              "text": " identifier persists across application launches and across syncs that do not change the sync status of the media item. The value is not guaranteed to persist across a sync/unsync/sync cycle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Can be used to build a media property predicate as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPropertyPredicate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtist": {
      "abstract": [
        {
          "text": "The primary performing artist for an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumArtist"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumArtist",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumartist"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtistPersistentID": {
      "abstract": [
        {
          "text": "The persistent identifier for an album artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumArtistPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtistPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumArtistPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumArtistPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumartistpersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumPersistentID": {
      "abstract": [
        {
          "text": "The key for the persistent identifier for an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumpersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTitle": {
      "abstract": [
        {
          "text": "The title of an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTitle"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumTitle",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumtitle"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtist": {
      "abstract": [
        {
          "text": "The performing artists for a media item — which may vary from the primary artist for the album that a media item belongs to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtist"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyArtist",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyartist"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtistPersistentID": {
      "abstract": [
        {
          "text": "The key for the persistent identifier for an artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtistPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtistPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtistPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyArtistPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyartistpersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposer": {
      "abstract": [
        {
          "text": "The musical composer for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComposer"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyComposer",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertycomposer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposerPersistentID": {
      "abstract": [
        {
          "text": "The persistent identifier for a composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComposerPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposerPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComposerPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyComposerPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertycomposerpersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenre": {
      "abstract": [
        {
          "text": "The music or film genre of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyGenre"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyGenre"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyGenre",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertygenre"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenrePersistentID": {
      "abstract": [
        {
          "text": "The persistent identifier for a genre.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyGenrePersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenrePersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyGenrePersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyGenrePersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertygenrepersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyHasProtectedAsset": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the media item has DRM protection so it can’t play through a standard playback API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyHasProtectedAsset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyHasProtectedAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyHasProtectedAsset"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyHasProtectedAsset",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyhasprotectedasset"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCloudItem": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media item is an iCloud item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsCloudItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCloudItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsCloudItem"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyIsCloudItem",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyisclouditem"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCompilation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media item is part of a compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsCompilation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCompilation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsCompilation"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyIsCompilation",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyiscompilation"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyMediaType": {
      "abstract": [
        {
          "text": "The media type of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyMediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyMediaType"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyMediaType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertymediatype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPersistentID": {
      "abstract": [
        {
          "text": "The key for the persistent identifier for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPersistentID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyPersistentID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertypersistentid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlayCount": {
      "abstract": [
        {
          "text": "The number of times the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlayCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlayCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlayCount"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyPlayCount",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyplaycount"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPropertyPredicate": {
      "abstract": [
        {
          "text": "A set of predicates for defining a filter in a media query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaPropertyPredicate"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPropertyPredicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaPropertyPredicate"
        }
      ],
      "role": "symbol",
      "title": "MPMediaPropertyPredicate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediapropertypredicate"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Filterable-property-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtist",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtistPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTitle",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtist",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtistPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposerPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenre",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyHasProtectedAsset",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCompilation",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCloudItem",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyMediaType",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPersistentID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlayCount"
      ],
      "title": "Filterable property keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPMediaItemPropertyGenrePersistentID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyGenrePersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Filterable-property-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtist",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumArtistPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTitle",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtist",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtistPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComposerPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyGenre",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyHasProtectedAsset",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCompilation",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsCloudItem",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyMediaType",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPersistentID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlayCount"
              ],
              "title": "Filterable property keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MPMediaItemPropertyGenrePersistentID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumPersistentID/title",
          "value": "MPMediaItemPropertyAlbumPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtistPersistentID/title",
          "value": "MPMediaItemPropertyArtistPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtistPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyArtistPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlayCount/title",
          "value": "MPMediaItemPropertyPlayCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlayCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPlayCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComposerPersistentID/title",
          "value": "MPMediaItemPropertyComposerPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComposerPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyComposerPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyHasProtectedAsset/title",
          "value": "MPMediaItemPropertyHasProtectedAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyHasProtectedAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyHasProtectedAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumArtist/title",
          "value": "MPMediaItemPropertyAlbumArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyMediaType/title",
          "value": "MPMediaItemPropertyMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyGenrePersistentID/title",
          "value": "MPMediaItemPropertyGenrePersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyGenrePersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyGenrePersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyGenre/title",
          "value": "MPMediaItemPropertyGenre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyGenre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyGenre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComposer/title",
          "value": "MPMediaItemPropertyComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPersistentID/title",
          "value": "MPMediaItemPropertyPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumArtistPersistentID/title",
          "value": "MPMediaItemPropertyAlbumArtistPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumArtistPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumArtistPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsCompilation/title",
          "value": "MPMediaItemPropertyIsCompilation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsCompilation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyIsCompilation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtist/title",
          "value": "MPMediaItemPropertyArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPropertyPredicate/title",
          "value": "MPMediaPropertyPredicate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPropertyPredicate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPropertyPredicate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPropertyPredicate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPropertyPredicate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsCloudItem/title",
          "value": "MPMediaItemPropertyIsCloudItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsCloudItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyIsCloudItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTitle/title",
          "value": "MPMediaItemPropertyAlbumTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumTitle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmediaitempropertygenrepersistentid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmediaitempropertygenrepersistentid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
