{
  "abstract": [
    {
      "text": "A protocol that defines the interface for controlling audio media playback.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MPMediaPlayback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MPMediaPlayback"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMediaPlayback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MPMediaPlayback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPMediaPlayback"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/playing-audio-using-the-built-in-music-player"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This protocol supports basic transport operations including start, stop, and pause, and also lets you seek forward and back through media or to a specific point in its timeline.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback": {
      "abstract": [
        {
          "text": "A protocol that defines the interface for controlling audio media playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaPlayback"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaPlayback"
        }
      ],
      "role": "symbol",
      "title": "MPMediaPlayback",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/beginSeekingBackward()": {
      "abstract": [
        {
          "text": "Begins seeking backward through the media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginSeekingBackward"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/beginSeekingBackward()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSeekingBackward"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "beginSeekingBackward()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback/beginseekingbackward()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/beginSeekingForward()": {
      "abstract": [
        {
          "text": "Begins seeking forward through the media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginSeekingForward"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/beginSeekingForward()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSeekingForward"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "beginSeekingForward()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback/beginseekingforward()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/currentPlaybackRate": {
      "abstract": [
        {
          "text": "The current playback rate for the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentPlaybackRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/currentPlaybackRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentPlaybackRate"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "currentPlaybackRate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback/currentplaybackrate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/currentPlaybackTime": {
      "abstract": [
        {
          "text": "The current position of the playhead.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentPlaybackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/currentPlaybackTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentPlaybackTime"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "currentPlaybackTime",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback/currentplaybacktime"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/endSeeking()": {
      "abstract": [
        {
          "text": "Ends forward and backward seeking through the media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endSeeking"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/endSeeking()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endSeeking"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "endSeeking()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback/endseeking()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/isPreparedToPlay": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a media player is ready to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPreparedToPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/isPreparedToPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isPreparedToPlay"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isPreparedToPlay",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback/ispreparedtoplay"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/pause()": {
      "abstract": [
        {
          "text": "Pauses playback of the current item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/pause()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pause()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback/pause()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/play()": {
      "abstract": [
        {
          "text": "Initiates playback of the current item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/play()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "play"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "play()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback/play()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/prepareToPlay()": {
      "abstract": [
        {
          "text": "Prepares a media player for playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareToPlay"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/prepareToPlay()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareToPlay"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "prepareToPlay()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback/preparetoplay()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/stop()": {
      "abstract": [
        {
          "text": "Ends playback of the current item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/stop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stop"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "stop()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplayback/stop()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlaybackIsPreparedToPlayDidChangeNotification": {
      "abstract": [
        {
          "text": "Indicates that the prepared to play status of the media player has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMediaPlaybackIsPreparedToPlayDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlaybackIsPreparedToPlayDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMediaPlaybackIsPreparedToPlayDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaplaybackispreparedtoplaydidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController": {
      "abstract": [
        {
          "text": "A type of movie player that manages the playback of a movie from a file or a network stream.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerController"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerApplicationController": {
      "abstract": [
        {
          "text": "A media player object that you use to revise the queue that’s currently playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMusicPlayerApplicationController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerApplicationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlayerApplicationController"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlayerApplicationController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayerapplicationcontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController": {
      "abstract": [
        {
          "text": "An object that plays audio media items from the device’s Music app library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMusicPlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlayerController"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlayerController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSystemMusicPlayerController": {
      "abstract": [
        {
          "text": "A protocol for playing videos in the Music app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSystemMusicPlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSystemMusicPlayerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSystemMusicPlayerController"
        }
      ],
      "role": "symbol",
      "title": "MPSystemMusicPlayerController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpsystemmusicplayercontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/playing-audio-using-the-built-in-music-player": {
      "abstract": [
        {
          "text": "Create a media player inside your app to play audio from the user’s media library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/playing-audio-using-the-built-in-music-player",
      "kind": "article",
      "role": "article",
      "title": "Playing audio using the built-in music player",
      "type": "topic",
      "url": "/documentation/mediaplayer/playing-audio-using-the-built-in-music-player"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerApplicationController",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Built-in-music-playback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/playing-audio-using-the-built-in-music-player",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSystemMusicPlayerController"
      ],
      "title": "Built-in music playback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Starting-and-stopping-playback",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/play()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/pause()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/stop()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/prepareToPlay()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/isPreparedToPlay"
      ],
      "title": "Starting and stopping playback"
    },
    {
      "anchor": "Seeking-within-media",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/beginSeekingBackward()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/beginSeekingForward()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/endSeeking()"
      ],
      "title": "Seeking within media"
    },
    {
      "anchor": "Accessing-playback-attributes",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/currentPlaybackRate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/currentPlaybackTime"
      ],
      "title": "Accessing playback attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPMediaPlayback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Starting-and-stopping-playback",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/play()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/pause()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/stop()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/prepareToPlay()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/isPreparedToPlay"
              ],
              "title": "Starting and stopping playback"
            },
            {
              "anchor": "Seeking-within-media",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/beginSeekingBackward()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/beginSeekingForward()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/endSeeking()"
              ],
              "title": "Seeking within media"
            },
            {
              "anchor": "Accessing-playback-attributes",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/currentPlaybackRate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlayback/currentPlaybackTime"
              ],
              "title": "Accessing playback attributes"
            },
            {
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPlaybackIsPreparedToPlayDidChangeNotification"
              ],
              "title": "Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Built-in-music-playback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/playing-audio-using-the-built-in-music-player",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSystemMusicPlayerController"
              ],
              "title": "Built-in music playback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MPMediaPlayback"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/title",
          "value": "MPMoviePlayerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerApplicationController/title",
          "value": "MPMusicPlayerApplicationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerApplicationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlayerApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerApplicationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlayerApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback/title",
          "value": "MPMediaPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1prepareToPlay()/title",
          "value": "prepareToPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1prepareToPlay()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareToPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1beginSeekingBackward()/title",
          "value": "beginSeekingBackward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1beginSeekingBackward()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginSeekingBackward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1pause()/title",
          "value": "pause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1pause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1isPreparedToPlay/title",
          "value": "isPreparedToPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1isPreparedToPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isPreparedToPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1currentPlaybackTime/title",
          "value": "currentPlaybackTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1currentPlaybackTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentPlaybackTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1beginSeekingForward()/title",
          "value": "beginSeekingForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1beginSeekingForward()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginSeekingForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSystemMusicPlayerController/title",
          "value": "MPSystemMusicPlayerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSystemMusicPlayerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSystemMusicPlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSystemMusicPlayerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSystemMusicPlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController/title",
          "value": "MPMusicPlayerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1endSeeking()/title",
          "value": "endSeeking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1endSeeking()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endSeeking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1play()/title",
          "value": "play"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1play()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "play"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1currentPlaybackRate/title",
          "value": "currentPlaybackRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1currentPlaybackRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentPlaybackRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1stop()/title",
          "value": "stop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPlayback~1stop()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmediaplayback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmediaplayback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
