{
  "abstract": [
    {
      "text": "The identifier for enqueueing store tracks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackStoreID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MPMediaItemPropertyPlaybackStoreID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MPMediaItemPropertyPlaybackStoreID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMediaItemPropertyPlaybackStoreID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MPMediaItemPropertyPlaybackStoreID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPlaybackStoreID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Matches the identifier used by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to enqueue store tracks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackCount": {
      "abstract": [
        {
          "text": "The number of tracks for the album that contains the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTrackCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTrackCount"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumTrackCount",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumtrackcount"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackNumber": {
      "abstract": [
        {
          "text": "The track number of the media item, for a media item that is part of an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTrackNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAlbumTrackNumber"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAlbumTrackNumber",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyalbumtracknumber"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtwork": {
      "abstract": [
        {
          "text": "The artwork image for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyArtwork"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyArtwork",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyartwork"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAssetURL": {
      "abstract": [
        {
          "text": "A URL that points to the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAssetURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAssetURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyAssetURL"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyAssetURL",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyasseturl"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBeatsPerMinute": {
      "abstract": [
        {
          "text": "The number of musical beats per minute for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyBeatsPerMinute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBeatsPerMinute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyBeatsPerMinute"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyBeatsPerMinute",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertybeatsperminute"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComments": {
      "abstract": [
        {
          "text": "Textual information about the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyComments"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyComments",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertycomments"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscCount": {
      "abstract": [
        {
          "text": "The number of discs for the album that contains the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyDiscCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyDiscCount"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyDiscCount",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertydisccount"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscNumber": {
      "abstract": [
        {
          "text": "The disc number of the media item, for a media item that is part of a multidisc album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyDiscNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyDiscNumber"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyDiscNumber",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertydiscnumber"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsExplicit": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media item contains explicit (adult) lyrics or language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsExplicit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsExplicit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsExplicit"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyIsExplicit",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyisexplicit"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsPreorder": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media item is a preorder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsPreorder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsPreorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyIsPreorder"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyIsPreorder",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyispreorder"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLyrics": {
      "abstract": [
        {
          "text": "The lyrics for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyLyrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLyrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyLyrics"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyLyrics",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertylyrics"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackDuration": {
      "abstract": [
        {
          "text": "The playback duration of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlaybackDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlaybackDuration"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyPlaybackDuration",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyplaybackduration"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackStoreID": {
      "abstract": [
        {
          "text": "The identifier for enqueueing store tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlaybackStoreID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackStoreID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyPlaybackStoreID"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyPlaybackStoreID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyplaybackstoreid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyReleaseDate": {
      "abstract": [
        {
          "text": "The date of the media item’s first public release.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyReleaseDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyReleaseDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyReleaseDate"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyReleaseDate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyreleasedate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController": {
      "abstract": [
        {
          "text": "An object that plays audio media items from the device’s Music app library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMusicPlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlayerController"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlayerController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontroller"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Property-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackDuration",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackNumber",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackCount",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscNumber",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscCount",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtwork",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLyrics",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyReleaseDate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBeatsPerMinute",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComments",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAssetURL",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsExplicit",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsPreorder"
      ],
      "title": "Property keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPMediaItemPropertyPlaybackStoreID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPlaybackStoreID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Property-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyPlaybackDuration",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackNumber",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAlbumTrackCount",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscNumber",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDiscCount",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyArtwork",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLyrics",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyReleaseDate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBeatsPerMinute",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyComments",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyAssetURL",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsExplicit",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyIsPreorder"
              ],
              "title": "Property keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MPMediaItemPropertyPlaybackStoreID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyReleaseDate/title",
          "value": "MPMediaItemPropertyReleaseDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyReleaseDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyReleaseDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyDiscNumber/title",
          "value": "MPMediaItemPropertyDiscNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyDiscNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyDiscNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController/title",
          "value": "MPMusicPlayerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtwork/title",
          "value": "MPMediaItemPropertyArtwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyArtwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyArtwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyDiscCount/title",
          "value": "MPMediaItemPropertyDiscCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyDiscCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyDiscCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTrackNumber/title",
          "value": "MPMediaItemPropertyAlbumTrackNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTrackNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumTrackNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlaybackDuration/title",
          "value": "MPMediaItemPropertyPlaybackDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlaybackDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPlaybackDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsExplicit/title",
          "value": "MPMediaItemPropertyIsExplicit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsExplicit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyIsExplicit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsPreorder/title",
          "value": "MPMediaItemPropertyIsPreorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyIsPreorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyIsPreorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyBeatsPerMinute/title",
          "value": "MPMediaItemPropertyBeatsPerMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyBeatsPerMinute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyBeatsPerMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyLyrics/title",
          "value": "MPMediaItemPropertyLyrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyLyrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyLyrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComments/title",
          "value": "MPMediaItemPropertyComments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyComments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyComments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlaybackStoreID/title",
          "value": "MPMediaItemPropertyPlaybackStoreID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyPlaybackStoreID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyPlaybackStoreID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAssetURL/title",
          "value": "MPMediaItemPropertyAssetURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAssetURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAssetURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTrackCount/title",
          "value": "MPMediaItemPropertyAlbumTrackCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyAlbumTrackCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyAlbumTrackCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmediaitempropertyplaybackstoreid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmediaitempropertyplaybackstoreid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
