{
  "abstract": [
    {
      "text": "A single piece of information for a movie access log.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use AVFoundation.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPMovieAccessLogEvent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MPMovieAccessLogEvent"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMovieAccessLogEvent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "4.3",
        "message": "Use AVFoundation.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "4.3",
        "message": "Use AVFoundation.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use AVFoundation.",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MPMovieAccessLogEvent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPMovieAccessLogEvent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For a description of movie access logs, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLog",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/imageCropRect": {
      "abstract": [
        {
          "text": "The bounds, in points, of the content area for the full size image associated with the media item artwork.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageCropRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/imageCropRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageCropRect"
        }
      ],
      "role": "symbol",
      "title": "imageCropRect",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitemartwork/imagecroprect"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/init(image:)": {
      "abstract": [
        {
          "text": "Initializes a media item artwork instance with a full-size image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/init(image:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithImage:"
        }
      ],
      "role": "symbol",
      "title": "init(image:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitemartwork/init(image:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLog": {
      "abstract": [
        {
          "text": "Key metrics about network playback for an associated movie player that’s playing streamed content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieAccessLog"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieAccessLog"
        }
      ],
      "role": "symbol",
      "title": "MPMovieAccessLog",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslog"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent": {
      "abstract": [
        {
          "text": "A single piece of information for a movie access log.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieAccessLogEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieAccessLogEvent"
        }
      ],
      "role": "symbol",
      "title": "MPMovieAccessLogEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/durationWatched": {
      "abstract": [
        {
          "text": "The accumulated duration of the media played, in seconds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "durationWatched"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/durationWatched",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "durationWatched"
        }
      ],
      "role": "symbol",
      "title": "durationWatched",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/durationwatched"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/indicatedBitrate": {
      "abstract": [
        {
          "text": "The throughput required to play the stream, as advertised by the web server, in bits per second.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indicatedBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/indicatedBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indicatedBitrate"
        }
      ],
      "role": "symbol",
      "title": "indicatedBitrate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/indicatedbitrate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfBytesTransferred": {
      "abstract": [
        {
          "text": "The accumulated number of bytes transferred.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfBytesTransferred"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfBytesTransferred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfBytesTransferred"
        }
      ],
      "role": "symbol",
      "title": "numberOfBytesTransferred",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/numberofbytestransferred"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfDroppedVideoFrames": {
      "abstract": [
        {
          "text": "The total number of dropped video frames.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfDroppedVideoFrames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfDroppedVideoFrames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfDroppedVideoFrames"
        }
      ],
      "role": "symbol",
      "title": "numberOfDroppedVideoFrames",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/numberofdroppedvideoframes"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfSegmentsDownloaded": {
      "abstract": [
        {
          "text": "A count of media segments downloaded from the web server to your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfSegmentsDownloaded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfSegmentsDownloaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfSegmentsDownloaded"
        }
      ],
      "role": "symbol",
      "title": "numberOfSegmentsDownloaded",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/numberofsegmentsdownloaded"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfServerAddressChanges": {
      "abstract": [
        {
          "text": "A count of changes to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property over the last uninterrupted period of playback.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfServerAddressChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfServerAddressChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfServerAddressChanges"
        }
      ],
      "role": "symbol",
      "title": "numberOfServerAddressChanges",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/numberofserveraddresschanges"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfStalls": {
      "abstract": [
        {
          "text": "The total number of playback stalls encountered.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfStalls"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfStalls",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfStalls"
        }
      ],
      "role": "symbol",
      "title": "numberOfStalls",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/numberofstalls"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/observedBitrate": {
      "abstract": [
        {
          "text": "The empirical throughput across all media downloaded for the movie player, in bits per second.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/observedBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedBitrate"
        }
      ],
      "role": "symbol",
      "title": "observedBitrate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/observedbitrate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackSessionID": {
      "abstract": [
        {
          "text": "A GUID that identifies the playback session to use in HTTP requests.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackSessionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackSessionID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackSessionID"
        }
      ],
      "role": "symbol",
      "title": "playbackSessionID",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/playbacksessionid"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartDate": {
      "abstract": [
        {
          "text": "The timestamp for when playback began for the movie log access event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackStartDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackStartDate"
        }
      ],
      "role": "symbol",
      "title": "playbackStartDate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/playbackstartdate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartOffset": {
      "abstract": [
        {
          "text": "An offset into the playlist where the last uninterrupted period of playback began, in seconds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackStartOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackStartOffset"
        }
      ],
      "role": "symbol",
      "title": "playbackStartOffset",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/playbackstartoffset"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/segmentsDownloadedDuration": {
      "abstract": [
        {
          "text": "The accumulated duration of the media downloaded, in seconds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "segmentsDownloadedDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/segmentsDownloadedDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "segmentsDownloadedDuration"
        }
      ],
      "role": "symbol",
      "title": "segmentsDownloadedDuration",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/segmentsdownloadedduration"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress": {
      "abstract": [
        {
          "text": "The IPv4 or IPv6 address of the web server that was the source of the last delivered media segment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serverAddress"
        }
      ],
      "role": "symbol",
      "title": "serverAddress",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/serveraddress"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/uri": {
      "abstract": [
        {
          "text": "The URI of the playback item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uri"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/uri",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URI"
        }
      ],
      "role": "symbol",
      "title": "uri",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent/uri"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLog": {
      "abstract": [
        {
          "text": "Data describing network resource playback failures for the associated movie player, including timestamps indicating when each failure occurred.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieErrorLog"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieErrorLog"
        }
      ],
      "role": "symbol",
      "title": "MPMovieErrorLog",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieerrorlog"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLogEvent": {
      "abstract": [
        {
          "text": "A single piece of information for a movie error log.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieErrorLogEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLogEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieErrorLogEvent"
        }
      ],
      "role": "symbol",
      "title": "MPMovieErrorLogEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieerrorlogevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState": {
      "abstract": [
        {
          "text": "Constants describing the network load state of the movie player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieLoadState"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieLoadState"
        }
      ],
      "role": "symbol",
      "title": "MPMovieLoadState",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieloadstate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask": {
      "abstract": [
        {
          "text": "The types of content available in the movie file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieMediaTypeMask"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieMediaTypeMask"
        }
      ],
      "role": "symbol",
      "title": "MPMovieMediaTypeMask",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmoviemediatypemask"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController": {
      "abstract": [
        {
          "text": "A type of movie player that manages the playback of a movie from a file or a network stream.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerController"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerViewController": {
      "abstract": [
        {
          "text": "A simple view controller for displaying full-screen movies.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerViewController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerViewController"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerViewController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerviewcontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/iPodMusicPlayer": {
      "abstract": [
        {
          "text": "Returns the iPod music player, which controls the iPod app’s state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iPodMusicPlayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMusicPlayerController",
          "text": "MPMusicPlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/iPodMusicPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iPodMusicPlayer"
        }
      ],
      "role": "symbol",
      "title": "iPodMusicPlayer",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontroller/ipodmusicplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager": {
      "abstract": [
        {
          "text": "A shared content manager for controlling interactions between your media app and system-provided or external media player interfaces.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPPlayableContentManager"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPPlayableContentManager"
        }
      ],
      "role": "symbol",
      "title": "MPPlayableContentManager",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanager"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManagerContext": {
      "abstract": [
        {
          "text": "An object representing the current state of the playable endpoint.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPPlayableContentManagerContext"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManagerContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPPlayableContentManagerContext"
        }
      ],
      "role": "symbol",
      "title": "MPPlayableContentManagerContext",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanagercontext"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "timed metadata object that",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " carries time-based information within HTTP streamed media.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPTimedMetadata"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPTimedMetadata"
        }
      ],
      "role": "symbol",
      "title": "MPTimedMetadata",
      "type": "topic",
      "url": "/documentation/mediaplayer/mptimedmetadata"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/routeButtonImage(for:)": {
      "abstract": [
        {
          "text": "Returns the button image associated with the specified control state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routeButtonImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/routeButtonImage(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routeButtonImageForState:"
        }
      ],
      "role": "symbol",
      "title": "routeButtonImage(for:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpvolumeview/routebuttonimage(for:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/showsRouteButton": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the route button is visible in the volume view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsRouteButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/showsRouteButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsRouteButton"
        }
      ],
      "role": "symbol",
      "title": "showsRouteButton",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpvolumeview/showsroutebutton"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-symbols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLog",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLog",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLogEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerViewController",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManagerContext",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/iPodMusicPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/init(image:)",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/imageCropRect",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/showsRouteButton",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/routeButtonImage(for:)"
      ],
      "title": "Deprecated symbols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Movie-access-log-event-properties",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfSegmentsDownloaded",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartDate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/uri",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfServerAddressChanges",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackSessionID",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartOffset",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/segmentsDownloadedDuration",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/durationWatched",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfStalls",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfBytesTransferred",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/observedBitrate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/indicatedBitrate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfDroppedVideoFrames"
      ],
      "title": "Movie access log event properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPMovieAccessLogEvent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Movie-access-log-event-properties",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfSegmentsDownloaded",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartDate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/uri",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/serverAddress",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfServerAddressChanges",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackSessionID",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/playbackStartOffset",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/segmentsDownloadedDuration",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/durationWatched",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfStalls",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfBytesTransferred",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/observedBitrate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/indicatedBitrate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent/numberOfDroppedVideoFrames"
              ],
              "title": "Movie access log event properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-symbols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLog",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLog",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLogEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerViewController",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManagerContext",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/iPodMusicPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/init(image:)",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/imageCropRect",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/showsRouteButton",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/routeButtonImage(for:)"
              ],
              "title": "Deprecated symbols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MPMovieAccessLogEvent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use AVFoundation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfBytesTransferred/title",
          "value": "numberOfBytesTransferred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfBytesTransferred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfBytesTransferred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent/title",
          "value": "MPMovieAccessLogEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfStalls/title",
          "value": "numberOfStalls"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfStalls/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfStalls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1serverAddress/title",
          "value": "serverAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1serverAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serverAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1durationWatched/title",
          "value": "durationWatched"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1durationWatched/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "durationWatched"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPVolumeView~1routeButtonImage(for:)/title",
          "value": "routeButtonImageForState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPVolumeView~1routeButtonImage(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "routeButtonImageForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfDroppedVideoFrames/title",
          "value": "numberOfDroppedVideoFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfDroppedVideoFrames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfDroppedVideoFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfSegmentsDownloaded/title",
          "value": "numberOfSegmentsDownloaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfSegmentsDownloaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfSegmentsDownloaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPVolumeView~1showsRouteButton/title",
          "value": "showsRouteButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPVolumeView~1showsRouteButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsRouteButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/title",
          "value": "MPMovieLoadState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1indicatedBitrate/title",
          "value": "indicatedBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1indicatedBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indicatedBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/title",
          "value": "MPMoviePlayerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerViewController/title",
          "value": "MPMoviePlayerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieMediaTypeMask/title",
          "value": "MPMovieMediaTypeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieMediaTypeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieMediaTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieMediaTypeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieMediaTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackStartDate/title",
          "value": "playbackStartDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackStartDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackStartDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemArtwork~1imageCropRect/title",
          "value": "imageCropRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemArtwork~1imageCropRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageCropRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackStartOffset/title",
          "value": "playbackStartOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackStartOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackStartOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1uri/title",
          "value": "URI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1uri/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemArtwork~1init(image:)/title",
          "value": "initWithImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemArtwork~1init(image:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata/title",
          "value": "MPTimedMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPTimedMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPTimedMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLog/title",
          "value": "MPMovieErrorLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieErrorLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieErrorLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager/title",
          "value": "MPPlayableContentManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfServerAddressChanges/title",
          "value": "numberOfServerAddressChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1numberOfServerAddressChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfServerAddressChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1segmentsDownloadedDuration/title",
          "value": "segmentsDownloadedDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1segmentsDownloadedDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "segmentsDownloadedDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackSessionID/title",
          "value": "playbackSessionID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1playbackSessionID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackSessionID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1observedBitrate/title",
          "value": "observedBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent~1observedBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManagerContext/title",
          "value": "MPPlayableContentManagerContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManagerContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentManagerContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManagerContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentManagerContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1iPodMusicPlayer/title",
          "value": "iPodMusicPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1iPodMusicPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iPodMusicPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLog/title",
          "value": "MPMovieAccessLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLogEvent/title",
          "value": "MPMovieErrorLogEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLogEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieErrorLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLogEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieErrorLogEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmovieaccesslogevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmovieaccesslogevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
