{
  "abstract": [
    {
      "text": "Posted when a movie player is about to enter full-screen mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerWillEnterFullscreenNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MPMoviePlayerWillEnterFullscreenNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MPMoviePlayerWillEnterFullscreenNotification"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMoviePlayerWillEnterFullscreenNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MPMoviePlayerWillEnterFullscreenNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPMoviePlayerWillEnterFullscreenNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary contains keys whose values describe the transition animation used to enter full-screen mode. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/fullscreen-notification-keys",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A movie player can enter full screen mode programmatically (see the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/setFullscreen(_:animated:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method) or by user interaction. The movie player whose state has changed is available as the object associated with the notification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieDurationAvailableNotification": {
      "abstract": [
        {
          "text": "Posted when the duration of a movie has been determined. There is no ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMovieDurationAvailableNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieDurationAvailableNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMovieDurationAvailableNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmoviedurationavailablenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypesAvailableNotification": {
      "abstract": [
        {
          "text": "Posted when the available media types in a movie are determined. There is no ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMovieMediaTypesAvailableNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypesAvailableNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMovieMediaTypesAvailableNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmoviemediatypesavailablenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieNaturalSizeAvailableNotification": {
      "abstract": [
        {
          "text": "Posted when the natural frame size of a movie is first determined or subsequently changes. There is no ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMovieNaturalSizeAvailableNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieNaturalSizeAvailableNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMovieNaturalSizeAvailableNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovienaturalsizeavailablenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/setFullscreen(_:animated:)": {
      "abstract": [
        {
          "text": "Causes the movie player to enter or exit full-screen mode.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFullscreen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/setFullscreen(_:animated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFullscreen:animated:"
        }
      ],
      "role": "symbol",
      "title": "setFullscreen(_:animated:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/setfullscreen(_:animated:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerDidEnterFullscreenNotification": {
      "abstract": [
        {
          "text": "Posted when a movie player has entered full-screen mode. There is no ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerDidEnterFullscreenNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerDidEnterFullscreenNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerDidEnterFullscreenNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerdidenterfullscreennotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerDidExitFullscreenNotification": {
      "abstract": [
        {
          "text": "Posted when a movie player has exited full-screen mode. There is no ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerDidExitFullscreenNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerDidExitFullscreenNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerDidExitFullscreenNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerdidexitfullscreennotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerIsAirPlayVideoActiveDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when a movie player has started or ended playing a movie via AirPlay. There is no ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerIsAirPlayVideoActiveDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerIsAirPlayVideoActiveDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerIsAirPlayVideoActiveDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerisairplayvideoactivedidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerLoadStateDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when a movie player’s network buffering state has changed. There is no ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerLoadStateDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerLoadStateDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerLoadStateDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerloadstatedidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerNowPlayingMovieDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the currently playing movie has changed. There is no ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerNowPlayingMovieDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerNowPlayingMovieDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerNowPlayingMovieDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayernowplayingmoviedidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackDidFinishNotification": {
      "abstract": [
        {
          "text": "Posted when a movie has finished playing. The ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary of this notification contains the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackDidFinishReasonUserInfoKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key, which indicates the reason that playback finished. This notification is also sent when playback fails because of an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerPlaybackDidFinishNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackDidFinishNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerPlaybackDidFinishNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerplaybackdidfinishnotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackDidFinishReasonUserInfoKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerPlaybackDidFinishReasonUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackDidFinishReasonUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerPlaybackDidFinishReasonUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerPlaybackDidFinishReasonUserInfoKey",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerplaybackdidfinishreasonuserinfokey"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackStateDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when a movie player’s playback state has changed. There is no ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerPlaybackStateDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackStateDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerPlaybackStateDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerplaybackstatedidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerReadyForDisplayDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the ready for display state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerReadyForDisplayDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerReadyForDisplayDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerReadyForDisplayDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerreadyfordisplaydidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerScalingModeDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the scaling mode of a movie player has changed. There is no ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerScalingModeDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerScalingModeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerScalingModeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerscalingmodedidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailImageRequestDidFinishNotification": {
      "abstract": [
        {
          "text": "Posted when a request to capture a thumbnail from a movie has finished whether the request succeeded or failed. Upon successful capture of a thumbnail, the ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary contains values for the following keys:",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerThumbnailImageRequestDidFinishNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailImageRequestDidFinishNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerThumbnailImageRequestDidFinishNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerthumbnailimagerequestdidfinishnotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataUpdatedNotification": {
      "abstract": [
        {
          "text": "Posted when new timed metadata arrives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataUpdatedNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataUpdatedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerTimedMetadataUpdatedNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayertimedmetadataupdatednotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerWillEnterFullscreenNotification": {
      "abstract": [
        {
          "text": "Posted when a movie player is about to enter full-screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerWillEnterFullscreenNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerWillEnterFullscreenNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerWillEnterFullscreenNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerwillenterfullscreennotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerWillExitFullscreenNotification": {
      "abstract": [
        {
          "text": "Posted when a movie player is about to exit full-screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerWillExitFullscreenNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerWillExitFullscreenNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerWillExitFullscreenNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerwillexitfullscreennotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/fullscreen-notification-keys": {
      "abstract": [
        {
          "text": "The following keys may be found in the ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary of notifications for transitioning in or out of full-screen mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/fullscreen-notification-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Fullscreen notification keys",
      "type": "topic",
      "url": "/documentation/mediaplayer/fullscreen-notification-keys"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerDidEnterFullscreenNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerDidExitFullscreenNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerIsAirPlayVideoActiveDidChangeNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerLoadStateDidChangeNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerNowPlayingMovieDidChangeNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackDidFinishNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackStateDidChangeNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerReadyForDisplayDidChangeNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerScalingModeDidChangeNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailImageRequestDidFinishNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataUpdatedNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerWillExitFullscreenNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieDurationAvailableNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypesAvailableNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieNaturalSizeAvailableNotification"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1setFullscreen(_:animated:)/title",
          "value": "setFullscreen:animated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1setFullscreen(_:animated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFullscreen:animated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerPlaybackDidFinishReasonUserInfoKey/title",
          "value": "MPMoviePlayerPlaybackDidFinishReasonUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerPlaybackDidFinishReasonUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerPlaybackDidFinishReasonUserInfoKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmovieplayerwillenterfullscreennotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
