{
  "abstract": [
    {
      "text": "Posted when the playback state changes programmatically or by user action.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerPlaybackStateDidChangeNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MPMusicPlayerControllerPlaybackStateDidChangeNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MPMusicPlayerControllerPlaybackStateDidChangeNotification"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMusicPlayerControllerPlaybackStateDidChangeNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MPMusicPlayerControllerPlaybackStateDidChangeNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSNotificationName",
              "text": "NSNotificationName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPMusicPlayerControllerPlaybackStateDidChangeNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The object associated with the notification is the music player whose playback state changed. The notification has no ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/beginGeneratingPlaybackNotifications()": {
      "abstract": [
        {
          "text": "Starts the generation of playback notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginGeneratingPlaybackNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/beginGeneratingPlaybackNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginGeneratingPlaybackNotifications"
        }
      ],
      "role": "symbol",
      "title": "beginGeneratingPlaybackNotifications()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontroller/begingeneratingplaybacknotifications()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/endGeneratingPlaybackNotifications()": {
      "abstract": [
        {
          "text": "Ends the generation of playback notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endGeneratingPlaybackNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/endGeneratingPlaybackNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endGeneratingPlaybackNotifications"
        }
      ],
      "role": "symbol",
      "title": "endGeneratingPlaybackNotifications()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontroller/endgeneratingplaybacknotifications()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerNowPlayingItemDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the currently playing media item has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMusicPlayerControllerNowPlayingItemDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerNowPlayingItemDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMusicPlayerControllerNowPlayingItemDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontrollernowplayingitemdidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerPlaybackStateDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the playback state changes programmatically or by user action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMusicPlayerControllerPlaybackStateDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerPlaybackStateDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMusicPlayerControllerPlaybackStateDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontrollerplaybackstatedidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerVolumeDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the audio playback volume for the music player has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMusicPlayerControllerVolumeDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerVolumeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMusicPlayerControllerVolumeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontrollervolumedidchangenotification"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSNotificationName": {
      "abstract": [
        {
          "text": "A structure that defines the name of a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSNotification.Name"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification.Name",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Using-music-player-notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/beginGeneratingPlaybackNotifications()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/endGeneratingPlaybackNotifications()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerNowPlayingItemDidChangeNotification",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerVolumeDidChangeNotification"
      ],
      "title": "Using music player notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title",
          "value": "NSNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1endGeneratingPlaybackNotifications()/title",
          "value": "endGeneratingPlaybackNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1endGeneratingPlaybackNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endGeneratingPlaybackNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1beginGeneratingPlaybackNotifications()/title",
          "value": "beginGeneratingPlaybackNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1beginGeneratingPlaybackNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginGeneratingPlaybackNotifications"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmusicplayercontrollerplaybackstatedidchangenotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
