{
  "abstract": [
    {
      "text": "The date associated with the current elapsed playback time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCurrentPlaybackDate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MPNowPlayingInfoPropertyCurrentPlaybackDate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13.1",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsdate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsdate": {
      "abstract": [
        {
          "text": "A representation of a specific point in time, for use when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDate"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDate",
      "type": "topic",
      "url": "/documentation/foundation/nsdate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoCollectionIdentifier": {
      "abstract": [
        {
          "text": "The identifier of the collection the Now Playing item belongs to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoCollectionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoCollectionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoCollectionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoCollectionIdentifier",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfocollectionidentifier"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAdTimeRanges": {
      "abstract": [
        {
          "text": "A list of ad breaks in the Now Playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyAdTimeRanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAdTimeRanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyAdTimeRanges"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyAdTimeRanges",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertyadtimeranges"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAssetURL": {
      "abstract": [
        {
          "text": "The URL pointing to the Now Playing item’s underlying asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyAssetURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAssetURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyAssetURL"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyAssetURL",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertyasseturl"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAvailableLanguageOptions": {
      "abstract": [
        {
          "text": "The available language option groups for the Now Playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyAvailableLanguageOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAvailableLanguageOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyAvailableLanguageOptions"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyAvailableLanguageOptions",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertyavailablelanguageoptions"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyChapterCount": {
      "abstract": [
        {
          "text": "The total number of chapters in the Now Playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyChapterCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyChapterCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyChapterCount"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyChapterCount",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertychaptercount"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyChapterNumber": {
      "abstract": [
        {
          "text": "The number corresponding to the currently playing chapter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyChapterNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyChapterNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyChapterNumber"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyChapterNumber",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertychapternumber"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCreditsStartTime": {
      "abstract": [
        {
          "text": "The start time for the credits, in seconds, without ads, for the Now Playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyCreditsStartTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCreditsStartTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyCreditsStartTime"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyCreditsStartTime",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertycreditsstarttime"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCurrentLanguageOptions": {
      "abstract": [
        {
          "text": "The currently active language options for the Now Playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyCurrentLanguageOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCurrentLanguageOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyCurrentLanguageOptions"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyCurrentLanguageOptions",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertycurrentlanguageoptions"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCurrentPlaybackDate": {
      "abstract": [
        {
          "text": "The date associated with the current elapsed playback time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCurrentPlaybackDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyCurrentPlaybackDate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertycurrentplaybackdate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyDefaultPlaybackRate": {
      "abstract": [
        {
          "text": "The default playback rate for the Now Playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyDefaultPlaybackRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyDefaultPlaybackRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyDefaultPlaybackRate"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyDefaultPlaybackRate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertydefaultplaybackrate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyElapsedPlaybackTime": {
      "abstract": [
        {
          "text": "The elapsed time of the Now Playing item, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyElapsedPlaybackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyElapsedPlaybackTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyElapsedPlaybackTime"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyElapsedPlaybackTime",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertyelapsedplaybacktime"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExcludeFromSuggestions": {
      "abstract": [
        {
          "text": "A number that denotes whether to exclude the Now Playing item from content suggestions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyExcludeFromSuggestions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExcludeFromSuggestions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyExcludeFromSuggestions"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyExcludeFromSuggestions",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertyexcludefromsuggestions"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExternalContentIdentifier": {
      "abstract": [
        {
          "text": "The opaque identifier that uniquely identifies the Now Playing item, even through app relaunches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyExternalContentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExternalContentIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyExternalContentIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyExternalContentIdentifier",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertyexternalcontentidentifier"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExternalUserProfileIdentifier": {
      "abstract": [
        {
          "text": "The opaque identifier that uniquely identifies the profile the Now Playing item plays from, even through app relaunches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyExternalUserProfileIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExternalUserProfileIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyExternalUserProfileIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyExternalUserProfileIdentifier",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertyexternaluserprofileidentifier"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyInternationalStandardRecordingCode": {
      "abstract": [
        {
          "text": "The International Standard Recording Code (ISRC) of the Now Playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyInternationalStandardRecordingCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyInternationalStandardRecordingCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyInternationalStandardRecordingCode"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyInternationalStandardRecordingCode",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertyinternationalstandardrecordingcode"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyIsLiveStream": {
      "abstract": [
        {
          "text": "A number that denotes whether the Now Playing item is a live stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyIsLiveStream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyIsLiveStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoPropertyIsLiveStream"
        }
      ],
      "role": "symbol",
      "title": "MPNowPlayingInfoPropertyIsLiveStream",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpnowplayinginfopropertyislivestream"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Now-Playing-metadata-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoCollectionIdentifier",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAdTimeRanges",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAvailableLanguageOptions",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAssetURL",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyChapterCount",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyChapterNumber",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCreditsStartTime",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCurrentLanguageOptions",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyDefaultPlaybackRate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyElapsedPlaybackTime",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExcludeFromSuggestions",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExternalContentIdentifier",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExternalUserProfileIdentifier",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyInternationalStandardRecordingCode",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyIsLiveStream"
      ],
      "title": "Accessing Now Playing metadata properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13.1",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Now-Playing-metadata-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoCollectionIdentifier",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAdTimeRanges",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAvailableLanguageOptions",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyAssetURL",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyChapterCount",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyChapterNumber",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCreditsStartTime",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyCurrentLanguageOptions",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyDefaultPlaybackRate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyElapsedPlaybackTime",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExcludeFromSuggestions",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExternalContentIdentifier",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyExternalUserProfileIdentifier",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyInternationalStandardRecordingCode",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPNowPlayingInfoPropertyIsLiveStream"
              ],
              "title": "Accessing Now Playing metadata properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyCreditsStartTime/title",
          "value": "MPNowPlayingInfoPropertyCreditsStartTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyCreditsStartTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyCreditsStartTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyInternationalStandardRecordingCode/title",
          "value": "MPNowPlayingInfoPropertyInternationalStandardRecordingCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyInternationalStandardRecordingCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyInternationalStandardRecordingCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyChapterCount/title",
          "value": "MPNowPlayingInfoPropertyChapterCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyChapterCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyChapterCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyAvailableLanguageOptions/title",
          "value": "MPNowPlayingInfoPropertyAvailableLanguageOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyAvailableLanguageOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyAvailableLanguageOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyDefaultPlaybackRate/title",
          "value": "MPNowPlayingInfoPropertyDefaultPlaybackRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyDefaultPlaybackRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyDefaultPlaybackRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyElapsedPlaybackTime/title",
          "value": "MPNowPlayingInfoPropertyElapsedPlaybackTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyElapsedPlaybackTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyElapsedPlaybackTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyAssetURL/title",
          "value": "MPNowPlayingInfoPropertyAssetURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyAssetURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyAssetURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyAdTimeRanges/title",
          "value": "MPNowPlayingInfoPropertyAdTimeRanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyAdTimeRanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyAdTimeRanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoCollectionIdentifier/title",
          "value": "MPNowPlayingInfoCollectionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoCollectionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoCollectionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdate/abstract",
          "value": [
            {
              "text": "A representation of a specific point in time, independent of any calendar or time zone.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyChapterNumber/title",
          "value": "MPNowPlayingInfoPropertyChapterNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyChapterNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyChapterNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyCurrentPlaybackDate/title",
          "value": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyCurrentPlaybackDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyCurrentPlaybackDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyExcludeFromSuggestions/title",
          "value": "MPNowPlayingInfoPropertyExcludeFromSuggestions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyExcludeFromSuggestions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyExcludeFromSuggestions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyExternalUserProfileIdentifier/title",
          "value": "MPNowPlayingInfoPropertyExternalUserProfileIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyExternalUserProfileIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyExternalUserProfileIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyExternalContentIdentifier/title",
          "value": "MPNowPlayingInfoPropertyExternalContentIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyExternalContentIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyExternalContentIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyIsLiveStream/title",
          "value": "MPNowPlayingInfoPropertyIsLiveStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyIsLiveStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyIsLiveStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyCurrentLanguageOptions/title",
          "value": "MPNowPlayingInfoPropertyCurrentLanguageOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPNowPlayingInfoPropertyCurrentLanguageOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoPropertyCurrentLanguageOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpnowplayinginfopropertycurrentplaybackdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpnowplayinginfopropertycurrentplaybackdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
