{
  "abstract": [
    {
      "text": "A shared content manager for controlling interactions between your media app and system-provided or external media player interfaces.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use CarPlay framework",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPPlayableContentManager",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MPPlayableContentManager"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPPlayableContentManager"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "7.1",
        "message": "Use CarPlay framework",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "7.1",
        "message": "Use CarPlay framework",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.1",
        "message": "Use CarPlay framework",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use CarPlay framework",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MPPlayableContentManager"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPPlayableContentManager"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Some features of this class are specific to CarPlay, which requires a special entitlement issued by Apple. Apps without the correct entitlement won’t appear on the CarPlay home screen. See ",
                  "type": "text"
                },
                {
                  "identifier": "http://www.apple.com/ios/carplay/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for more information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The app provides data to the content manager so that the media player can browse the content provided. A delegate provides the media player the ability to perform actions that manage the app’s playback queue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t create a new content manager directly, instead you grab the shared content manager using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/shared()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. After getting the shared content manager, your next step depends on the features your app supports:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To provide content navigation and suggested content for CarPlay, immediately set both the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/dataSource",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/delegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties. After setting these properties, use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/beginUpdates()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/endUpdates()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " methods to load the information from the data source.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To provide suggested content when the user connects headphones, a Bluetooth stereo, or another output device, set only the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/delegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property. After you set a delegate, iOS automatically calls methods in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentDelegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol allowing you to suggest appropriate content.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/imageCropRect": {
      "abstract": [
        {
          "text": "The bounds, in points, of the content area for the full size image associated with the media item artwork.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageCropRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/imageCropRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageCropRect"
        }
      ],
      "role": "symbol",
      "title": "imageCropRect",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitemartwork/imagecroprect"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/init(image:)": {
      "abstract": [
        {
          "text": "Initializes a media item artwork instance with a full-size image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/init(image:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithImage:"
        }
      ],
      "role": "symbol",
      "title": "init(image:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitemartwork/init(image:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLog": {
      "abstract": [
        {
          "text": "Key metrics about network playback for an associated movie player that’s playing streamed content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieAccessLog"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieAccessLog"
        }
      ],
      "role": "symbol",
      "title": "MPMovieAccessLog",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslog"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent": {
      "abstract": [
        {
          "text": "A single piece of information for a movie access log.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieAccessLogEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieAccessLogEvent"
        }
      ],
      "role": "symbol",
      "title": "MPMovieAccessLogEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieaccesslogevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLog": {
      "abstract": [
        {
          "text": "Data describing network resource playback failures for the associated movie player, including timestamps indicating when each failure occurred.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieErrorLog"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieErrorLog"
        }
      ],
      "role": "symbol",
      "title": "MPMovieErrorLog",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieerrorlog"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLogEvent": {
      "abstract": [
        {
          "text": "A single piece of information for a movie error log.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieErrorLogEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLogEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieErrorLogEvent"
        }
      ],
      "role": "symbol",
      "title": "MPMovieErrorLogEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieerrorlogevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState": {
      "abstract": [
        {
          "text": "Constants describing the network load state of the movie player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieLoadState"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieLoadState"
        }
      ],
      "role": "symbol",
      "title": "MPMovieLoadState",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieloadstate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask": {
      "abstract": [
        {
          "text": "The types of content available in the movie file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieMediaTypeMask"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieMediaTypeMask"
        }
      ],
      "role": "symbol",
      "title": "MPMovieMediaTypeMask",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmoviemediatypemask"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController": {
      "abstract": [
        {
          "text": "A type of movie player that manages the playback of a movie from a file or a network stream.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerController"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerViewController": {
      "abstract": [
        {
          "text": "A simple view controller for displaying full-screen movies.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerViewController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerViewController"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerViewController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerviewcontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/iPodMusicPlayer": {
      "abstract": [
        {
          "text": "Returns the iPod music player, which controls the iPod app’s state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iPodMusicPlayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMusicPlayerController",
          "text": "MPMusicPlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/iPodMusicPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iPodMusicPlayer"
        }
      ],
      "role": "symbol",
      "title": "iPodMusicPlayer",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontroller/ipodmusicplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentDataSource": {
      "abstract": [
        {
          "text": "The data source providing media metadata to external media players so they can build user interfaces displaying your app’s content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPPlayableContentDataSource"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPPlayableContentDataSource"
        }
      ],
      "role": "symbol",
      "title": "MPPlayableContentDataSource",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentdatasource"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentDelegate": {
      "abstract": [
        {
          "text": "The protocol used to let external media players send playback commands to an app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPPlayableContentDelegate"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPPlayableContentDelegate"
        }
      ],
      "role": "symbol",
      "title": "MPPlayableContentDelegate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentdelegate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager": {
      "abstract": [
        {
          "text": "A shared content manager for controlling interactions between your media app and system-provided or external media player interfaces.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPPlayableContentManager"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPPlayableContentManager"
        }
      ],
      "role": "symbol",
      "title": "MPPlayableContentManager",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanager"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/beginUpdates()": {
      "abstract": [
        {
          "text": "Updates several Media Player content items at once.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/beginUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginUpdates"
        }
      ],
      "role": "symbol",
      "title": "beginUpdates()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanager/beginupdates()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/context": {
      "abstract": [
        {
          "text": "The current state of the playable content endpoint.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPPlayableContentManagerContext",
          "text": "MPPlayableContentManagerContext"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "context"
        }
      ],
      "role": "symbol",
      "title": "context",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanager/context"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/dataSource": {
      "abstract": [
        {
          "text": "The data source provided by the app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataSource"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MPPlayableContentDataSource",
          "text": "MPPlayableContentDataSource"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/dataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataSource"
        }
      ],
      "role": "symbol",
      "title": "dataSource",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanager/datasource"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/delegate": {
      "abstract": [
        {
          "text": "A delegate that lets the media player manage the app’s playback queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MPPlayableContentDelegate",
          "text": "MPPlayableContentDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanager/delegate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/endUpdates()": {
      "abstract": [
        {
          "text": "Ends a synchronized update.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/endUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endUpdates"
        }
      ],
      "role": "symbol",
      "title": "endUpdates()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanager/endupdates()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/nowPlayingIdentifiers": {
      "abstract": [
        {
          "text": "The content items currently playing based on their identifiers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nowPlayingIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/nowPlayingIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nowPlayingIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "nowPlayingIdentifiers",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanager/nowplayingidentifiers"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/reloadData()": {
      "abstract": [
        {
          "text": "Reloads the data from the data source.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reloadData"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/reloadData()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reloadData"
        }
      ],
      "role": "symbol",
      "title": "reloadData()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanager/reloaddata()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/shared()": {
      "abstract": [
        {
          "text": "Returns the current content manager instance.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/shared()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedContentManager"
        }
      ],
      "role": "symbol",
      "title": "shared()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanager/shared()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManagerContext": {
      "abstract": [
        {
          "text": "An object representing the current state of the playable endpoint.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPPlayableContentManagerContext"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManagerContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPPlayableContentManagerContext"
        }
      ],
      "role": "symbol",
      "title": "MPPlayableContentManagerContext",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpplayablecontentmanagercontext"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "timed metadata object that",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " carries time-based information within HTTP streamed media.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPTimedMetadata"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPTimedMetadata"
        }
      ],
      "role": "symbol",
      "title": "MPTimedMetadata",
      "type": "topic",
      "url": "/documentation/mediaplayer/mptimedmetadata"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/routeButtonImage(for:)": {
      "abstract": [
        {
          "text": "Returns the button image associated with the specified control state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routeButtonImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/routeButtonImage(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routeButtonImageForState:"
        }
      ],
      "role": "symbol",
      "title": "routeButtonImage(for:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpvolumeview/routebuttonimage(for:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/showsRouteButton": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the route button is visible in the volume view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsRouteButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/showsRouteButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsRouteButton"
        }
      ],
      "role": "symbol",
      "title": "showsRouteButton",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpvolumeview/showsroutebutton"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "http://www.apple.com/ios/carplay/": {
      "identifier": "http://www.apple.com/ios/carplay/",
      "title": "http://www.apple.com/ios/carplay/",
      "titleInlineContent": [
        {
          "text": "http://www.apple.com/ios/carplay/",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.apple.com/ios/carplay/"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-symbols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLog",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLog",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLogEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerViewController",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManagerContext",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/iPodMusicPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/init(image:)",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/imageCropRect",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/showsRouteButton",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/routeButtonImage(for:)"
      ],
      "title": "Deprecated symbols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-playable-content",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/dataSource",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentDataSource"
      ],
      "title": "Providing playable content"
    },
    {
      "anchor": "Responding-to-playback-events",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/delegate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentDelegate"
      ],
      "title": "Responding to playback events"
    },
    {
      "anchor": "Setting-the-content-manager",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/shared()"
      ],
      "title": "Setting the content manager"
    },
    {
      "anchor": "Updating-data",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/beginUpdates()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/endUpdates()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/reloadData()"
      ],
      "title": "Updating data"
    },
    {
      "anchor": "Retrieving-information-on-currently-playing-items",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/context",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/nowPlayingIdentifiers"
      ],
      "title": "Retrieving information on currently playing items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "7.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "7.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPPlayableContentManager"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-playable-content",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/dataSource",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentDataSource"
              ],
              "title": "Providing playable content"
            },
            {
              "anchor": "Responding-to-playback-events",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/delegate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentDelegate"
              ],
              "title": "Responding to playback events"
            },
            {
              "anchor": "Setting-the-content-manager",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/shared()"
              ],
              "title": "Setting the content manager"
            },
            {
              "anchor": "Updating-data",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/beginUpdates()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/endUpdates()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/reloadData()"
              ],
              "title": "Updating data"
            },
            {
              "anchor": "Retrieving-information-on-currently-playing-items",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/context",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManager/nowPlayingIdentifiers"
              ],
              "title": "Retrieving information on currently playing items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-symbols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLog",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieAccessLogEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLog",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieErrorLogEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerViewController",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPPlayableContentManagerContext",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/iPodMusicPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/init(image:)",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemArtwork/imageCropRect",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/showsRouteButton",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPVolumeView/routeButtonImage(for:)"
              ],
              "title": "Deprecated symbols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MPPlayableContentManager"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use CarPlay framework",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent/title",
          "value": "MPMovieAccessLogEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLogEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemArtwork~1imageCropRect/title",
          "value": "imageCropRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemArtwork~1imageCropRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageCropRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1iPodMusicPlayer/title",
          "value": "iPodMusicPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1iPodMusicPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iPodMusicPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager/title",
          "value": "MPPlayableContentManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/title",
          "value": "MPMoviePlayerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata/title",
          "value": "MPTimedMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPTimedMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPTimedMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1dataSource/title",
          "value": "dataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1dataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1nowPlayingIdentifiers/title",
          "value": "nowPlayingIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1nowPlayingIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nowPlayingIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPVolumeView~1routeButtonImage(for:)/title",
          "value": "routeButtonImageForState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPVolumeView~1routeButtonImage(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "routeButtonImageForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLogEvent/title",
          "value": "MPMovieErrorLogEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLogEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieErrorLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLogEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieErrorLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerViewController/title",
          "value": "MPMoviePlayerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemArtwork~1init(image:)/title",
          "value": "initWithImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemArtwork~1init(image:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1shared()/title",
          "value": "sharedContentManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1shared()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1reloadData()/title",
          "value": "reloadData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1reloadData()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reloadData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1context/title",
          "value": "context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLog/title",
          "value": "MPMovieAccessLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieAccessLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieAccessLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentDelegate/title",
          "value": "MPPlayableContentDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPVolumeView~1showsRouteButton/title",
          "value": "showsRouteButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPVolumeView~1showsRouteButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsRouteButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1beginUpdates()/title",
          "value": "beginUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1beginUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManagerContext/title",
          "value": "MPPlayableContentManagerContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManagerContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentManagerContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManagerContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentManagerContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieMediaTypeMask/title",
          "value": "MPMovieMediaTypeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieMediaTypeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieMediaTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieMediaTypeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieMediaTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1endUpdates()/title",
          "value": "endUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentManager~1endUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLog/title",
          "value": "MPMovieErrorLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieErrorLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieErrorLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieErrorLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentDataSource/title",
          "value": "MPPlayableContentDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPPlayableContentDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPPlayableContentDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/title",
          "value": "MPMovieLoadState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpplayablecontentmanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpplayablecontentmanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
