{
  "abstract": [
    {
      "text": "Constants indicating the status of a command.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPRemoteCommandHandlerStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MPRemoteCommandHandlerStatus"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPRemoteCommandHandlerStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MPRemoteCommandHandlerStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/addTarget(_:action:)": {
      "abstract": [
        {
          "text": "Adds a target object to be called when an event is received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTarget"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/addTarget(_:action:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addTarget:action:"
        }
      ],
      "role": "symbol",
      "title": "addTarget(_:action:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommand/addtarget(_:action:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/addTarget(handler:)": {
      "abstract": [
        {
          "text": "Adds a block to be called when an event is received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTarget"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPRemoteCommandEvent",
          "text": "MPRemoteCommandEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPRemoteCommandHandlerStatus",
          "text": "MPRemoteCommandHandlerStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/addTarget(handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addTargetWithHandler:"
        }
      ],
      "role": "symbol",
      "title": "addTarget(handler:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommand/addtarget(handler:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/removeTarget(_:)": {
      "abstract": [
        {
          "text": "Removes a target from the remote command object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTarget"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/removeTarget(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeTarget:"
        }
      ],
      "role": "symbol",
      "title": "removeTarget(_:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommand/removetarget(_:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/removeTarget(_:action:)": {
      "abstract": [
        {
          "text": "Removes a target and action from a remote command object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTarget"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/removeTarget(_:action:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeTarget:action:"
        }
      ],
      "role": "symbol",
      "title": "removeTarget(_:action:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommand/removetarget(_:action:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus": {
      "abstract": [
        {
          "text": "Constants indicating the status of a command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatus"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/commandFailed": {
      "abstract": [
        {
          "text": "The requested command failed to execute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commandFailed"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/commandFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatusCommandFailed"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus.commandFailed",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/commandfailed"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/deviceNotFound": {
      "abstract": [
        {
          "text": "The requested command couldn’t execute because a required device isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotFound"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/deviceNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatusDeviceNotFound"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus.deviceNotFound",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/devicenotfound"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/init(rawvalue:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noActionableNowPlayingItem": {
      "abstract": [
        {
          "text": "The requested command couldn’t execute because no Now Playing item is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noActionableNowPlayingItem"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noActionableNowPlayingItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatusNoActionableNowPlayingItem"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus.noActionableNowPlayingItem",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/noactionablenowplayingitem"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noSuchContent": {
      "abstract": [
        {
          "text": "The requested command couldn’t execute because its required content isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuchContent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noSuchContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatusNoSuchContent"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus.noSuchContent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/nosuchcontent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/success": {
      "abstract": [
        {
          "text": "The requested command executed successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatusSuccess"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus.success",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/success"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/addTarget(handler:)",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/addTarget(_:action:)",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/removeTarget(_:)",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/removeTarget(_:action:)"
      ],
      "title": "Handling events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/success",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noSuchContent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noActionableNowPlayingItem",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/deviceNotFound",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/commandFailed"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPRemoteCommandHandlerStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/success",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noSuchContent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noActionableNowPlayingItem",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/deviceNotFound",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/commandFailed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/addTarget(handler:)",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/addTarget(_:action:)",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/removeTarget(_:)",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand/removeTarget(_:action:)"
              ],
              "title": "Handling events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MPRemoteCommandHandlerStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand~1removeTarget(_:)/title",
          "value": "removeTarget:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand~1removeTarget(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeTarget:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1deviceNotFound/title",
          "value": "MPRemoteCommandHandlerStatusDeviceNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1deviceNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusDeviceNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1noActionableNowPlayingItem/title",
          "value": "MPRemoteCommandHandlerStatusNoActionableNowPlayingItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1noActionableNowPlayingItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusNoActionableNowPlayingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1commandFailed/title",
          "value": "MPRemoteCommandHandlerStatusCommandFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1commandFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusCommandFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus/title",
          "value": "MPRemoteCommandHandlerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand~1addTarget(handler:)/title",
          "value": "addTargetWithHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand~1addTarget(handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addTargetWithHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand~1removeTarget(_:action:)/title",
          "value": "removeTarget:action:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand~1removeTarget(_:action:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeTarget:action:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand~1addTarget(_:action:)/title",
          "value": "addTarget:action:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand~1addTarget(_:action:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addTarget:action:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1success/title",
          "value": "MPRemoteCommandHandlerStatusSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1noSuchContent/title",
          "value": "MPRemoteCommandHandlerStatusNoSuchContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1noSuchContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusNoSuchContent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpremotecommandhandlerstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpremotecommandhandlerstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
