{
  "abstract": [
    {
      "text": "Indicates which item types to shuffle.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPShuffleType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MPShuffleType"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPShuffleType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MPShuffleType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPShuffleType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeLanguageOptionCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the language option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeLanguageOptionCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeLanguageOptionCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangeLanguageOptionCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPChangeLanguageOptionCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangelanguageoptioncommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommand": {
      "abstract": [
        {
          "text": "An object that responds to requests to change the playback rate of the playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangePlaybackRateCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangePlaybackRateCommand"
        }
      ],
      "role": "symbol",
      "title": "MPChangePlaybackRateCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangeplaybackratecommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the playback rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangePlaybackRateCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangePlaybackRateCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPChangePlaybackRateCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangeplaybackratecommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommand": {
      "abstract": [
        {
          "text": "An object that responds to requests to change the current repeat mode used during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeRepeatModeCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangeRepeatModeCommand"
        }
      ],
      "role": "symbol",
      "title": "MPChangeRepeatModeCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangerepeatmodecommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the repeat mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeRepeatModeCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangeRepeatModeCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPChangeRepeatModeCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangerepeatmodecommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommand": {
      "abstract": [
        {
          "text": "An object that responds to requests to change the current shuffle mode used during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeShuffleModeCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangeShuffleModeCommand"
        }
      ],
      "role": "symbol",
      "title": "MPChangeShuffleModeCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangeshufflemodecommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the shuffle mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeShuffleModeCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangeShuffleModeCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPChangeShuffleModeCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangeshufflemodecommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRepeatType": {
      "abstract": [
        {
          "text": "Indicates which items to play repeatedly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRepeatType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRepeatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRepeatType"
        }
      ],
      "role": "symbol",
      "title": "MPRepeatType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mprepeattype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType": {
      "abstract": [
        {
          "text": "Indicates which item types to shuffle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPShuffleType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPShuffleType"
        }
      ],
      "role": "symbol",
      "title": "MPShuffleType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpshuffletype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/collections": {
      "abstract": [
        {
          "text": "Collections of items are shuffled during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collections"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/collections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPShuffleTypeCollections"
        }
      ],
      "role": "symbol",
      "title": "MPShuffleType.collections",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpshuffletype/collections"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpshuffletype/init(rawvalue:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/items": {
      "abstract": [
        {
          "text": "Individual items are shuffled during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "items"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/items",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPShuffleTypeItems"
        }
      ],
      "role": "symbol",
      "title": "MPShuffleType.items",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpshuffletype/items"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/off": {
      "abstract": [
        {
          "text": "Nothing is shuffled during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "off"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/off",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPShuffleTypeOff"
        }
      ],
      "role": "symbol",
      "title": "MPShuffleType.off",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpshuffletype/off"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-changes-to-media-playback-mode-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeLanguageOptionCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRepeatType"
      ],
      "title": "Responding to changes to media playback mode events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Shuffle-types",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/off",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/items",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/collections"
      ],
      "title": "Shuffle types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPShuffleType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPShuffleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPShuffleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Shuffle-types",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/off",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/items",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPShuffleType/collections"
              ],
              "title": "Shuffle types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-changes-to-media-playback-mode-events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackRateCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeLanguageOptionCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeRepeatModeCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangeShuffleModeCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRepeatType"
              ],
              "title": "Responding to changes to media playback mode events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MPShuffleType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommand/title",
          "value": "MPChangePlaybackRateCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackRateCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackRateCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommandEvent/title",
          "value": "MPChangeRepeatModeCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeRepeatModeCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeRepeatModeCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeLanguageOptionCommandEvent/title",
          "value": "MPChangeLanguageOptionCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeLanguageOptionCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeLanguageOptionCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeLanguageOptionCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeLanguageOptionCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType~1collections/title",
          "value": "MPShuffleTypeCollections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType~1collections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPShuffleTypeCollections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType/title",
          "value": "MPShuffleType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPShuffleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPShuffleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType~1off/title",
          "value": "MPShuffleTypeOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType~1off/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPShuffleTypeOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommand/title",
          "value": "MPChangeRepeatModeCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeRepeatModeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeRepeatModeCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeRepeatModeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType~1items/title",
          "value": "MPShuffleTypeItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPShuffleType~1items/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPShuffleTypeItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommand/title",
          "value": "MPChangeShuffleModeCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeShuffleModeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeShuffleModeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRepeatType/title",
          "value": "MPRepeatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRepeatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRepeatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRepeatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRepeatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommandEvent/title",
          "value": "MPChangeShuffleModeCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeShuffleModeCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangeShuffleModeCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangeShuffleModeCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommandEvent/title",
          "value": "MPChangePlaybackRateCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackRateCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackRateCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackRateCommandEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpshuffletype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpshuffletype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
