{
  "abstract": [
    {
      "text": "Set up the remote command center to handle media player events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Remote command center events"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand": {
      "abstract": [
        {
          "text": "An object that responds to remote command events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRemoteCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommand"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter": {
      "abstract": [
        {
          "text": "An object that responds to remote control events sent by external accessories and system controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRemoteCommandCenter"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandCenter"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandCenter",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandcenter"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandEvent": {
      "abstract": [
        {
          "text": "A description of a command sent by an external media player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRemoteCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/becoming-a-now-playable-app": {
      "abstract": [
        {
          "text": "Ensure your app is eligible to become the Now Playing app by adopting best practices for providing Now Playing info and registering for remote command center actions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/becoming-a-now-playable-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Becoming a now playable app",
      "type": "topic",
      "url": "/documentation/mediaplayer/becoming-a-now-playable-app"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events": {
      "abstract": [
        {
          "text": "Respond to incoming feedback and rating events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Feedback and rating events",
      "type": "topic",
      "url": "/documentation/mediaplayer/feedback-and-rating-events"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications": {
      "abstract": [
        {
          "text": "Handle events for external media players.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
      "kind": "article",
      "role": "article",
      "title": "Handling external player events notifications",
      "type": "topic",
      "url": "/documentation/mediaplayer/handling-external-player-events-notifications"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events": {
      "abstract": [
        {
          "text": "Respond to changes in the way media items play.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media playback mode events",
      "type": "topic",
      "url": "/documentation/mediaplayer/media-playback-mode-events"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events": {
      "abstract": [
        {
          "text": "Respond to requests to change which part of a media item plays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Track navigation events",
      "type": "topic",
      "url": "/documentation/mediaplayer/track-navigation-events"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "External-player-and-system-event-handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events"
      ],
      "title": "External player and system event handling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-up-the-remote-event-handler",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/becoming-a-now-playable-app",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandEvent"
      ],
      "title": "Setting up the remote event handler"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-up-the-remote-event-handler",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/becoming-a-now-playable-app",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandCenter",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandEvent"
              ],
              "title": "Setting up the remote event handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "External-player-and-system-event-handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events"
              ],
              "title": "External player and system event handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter/title",
          "value": "MPRemoteCommandCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandEvent/title",
          "value": "MPRemoteCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand/title",
          "value": "MPRemoteCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommand"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/remote-command-center-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/remote-command-center-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
