{
  "abstract": [
    {
      "text": "The following keys may be found in the ",
      "type": "text"
    },
    {
      "code": "userInfo",
      "type": "codeVoice"
    },
    {
      "text": " dictionary of a ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailImageRequestDidFinishNotification",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " notification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/deprecated-types",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/thumbnail-notification-user-info-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Thumbnail notification user info keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieControlStyle": {
      "abstract": [
        {
          "text": "Constants describing the style of the playback controls.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieControlStyle"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieControlStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieControlStyle"
        }
      ],
      "role": "symbol",
      "title": "MPMovieControlStyle",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmoviecontrolstyle"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieFinishReason": {
      "abstract": [
        {
          "text": "Constants describing the reason that playback ended.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieFinishReason"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieFinishReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieFinishReason"
        }
      ],
      "role": "symbol",
      "title": "MPMovieFinishReason",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmoviefinishreason"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState": {
      "abstract": [
        {
          "text": "Constants describing the network load state of the movie player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieLoadState"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieLoadState"
        }
      ],
      "role": "symbol",
      "title": "MPMovieLoadState",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieloadstate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask": {
      "abstract": [
        {
          "text": "The types of content available in the movie file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieMediaTypeMask"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieMediaTypeMask"
        }
      ],
      "role": "symbol",
      "title": "MPMovieMediaTypeMask",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmoviemediatypemask"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlaybackState": {
      "abstract": [
        {
          "text": "Constants describing the current playback state of the movie player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlaybackState"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlaybackState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlaybackState"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlaybackState",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplaybackstate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController": {
      "abstract": [
        {
          "text": "A type of movie player that manages the playback of a movie from a file or a network stream.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerController"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackDidFinishNotification": {
      "abstract": [
        {
          "text": "Posted when a movie has finished playing. The ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary of this notification contains the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackDidFinishReasonUserInfoKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key, which indicates the reason that playback finished. This notification is also sent when playback fails because of an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerPlaybackDidFinishNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackDidFinishNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerPlaybackDidFinishNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerplaybackdidfinishnotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailErrorKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerThumbnailErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerThumbnailErrorKey"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerThumbnailErrorKey",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerthumbnailerrorkey"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailImageKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerThumbnailImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerThumbnailImageKey"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerThumbnailImageKey",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerthumbnailimagekey"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailImageRequestDidFinishNotification": {
      "abstract": [
        {
          "text": "Posted when a request to capture a thumbnail from a movie has finished whether the request succeeded or failed. Upon successful capture of a thumbnail, the ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary contains values for the following keys:",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerThumbnailImageRequestDidFinishNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailImageRequestDidFinishNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMoviePlayerThumbnailImageRequestDidFinishNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerthumbnailimagerequestdidfinishnotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailTimeKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerThumbnailTimeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailTimeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerThumbnailTimeKey"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerThumbnailTimeKey",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayerthumbnailtimekey"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieRepeatMode": {
      "abstract": [
        {
          "text": "Constants describing how the movie player repeats content at the end of playback.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieRepeatMode"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieRepeatMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieRepeatMode"
        }
      ],
      "role": "symbol",
      "title": "MPMovieRepeatMode",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovierepeatmode"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieScalingMode": {
      "abstract": [
        {
          "text": "Constants describing how the movie content is scaled to fit the frame of its view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieScalingMode"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieScalingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieScalingMode"
        }
      ],
      "role": "symbol",
      "title": "MPMovieScalingMode",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmoviescalingmode"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieSourceType": {
      "abstract": [
        {
          "text": "Specifies the type of the movie file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieSourceType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieSourceType"
        }
      ],
      "role": "symbol",
      "title": "MPMovieSourceType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmoviesourcetype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieTimeOption": {
      "abstract": [
        {
          "text": "Constants describing which frame to use when generating thumbnail images.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMovieTimeOption"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieTimeOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMovieTimeOption"
        }
      ],
      "role": "symbol",
      "title": "MPMovieTimeOption",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovietimeoption"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/deprecated-types": {
      "abstract": [
        {
          "text": "Review deprecated symbols and avoid using them in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/deprecated-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated types",
      "type": "topic",
      "url": "/documentation/mediaplayer/deprecated-types"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/fullscreen-notification-keys": {
      "abstract": [
        {
          "text": "The following keys may be found in the ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary of notifications for transitioning in or out of full-screen mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/fullscreen-notification-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Fullscreen notification keys",
      "type": "topic",
      "url": "/documentation/mediaplayer/fullscreen-notification-keys"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/playback-finished-notification-key": {
      "abstract": [
        {
          "text": "The following key may be found in the userInfo dictionary of a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerPlaybackDidFinishNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " notification.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/playback-finished-notification-key",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Playback finished notification key",
      "type": "topic",
      "url": "/documentation/mediaplayer/playback-finished-notification-key"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieControlStyle",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieFinishReason",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlaybackState",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieRepeatMode",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieScalingMode",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieTimeOption",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieSourceType",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/fullscreen-notification-keys",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/playback-finished-notification-key"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailImageKey",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailTimeKey",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailErrorKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailImageKey",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailTimeKey",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerThumbnailErrorKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieLoadState",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieControlStyle",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieFinishReason",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlaybackState",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieRepeatMode",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieScalingMode",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieTimeOption",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieMediaTypeMask",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMovieSourceType",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/fullscreen-notification-keys",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/playback-finished-notification-key"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieTimeOption/title",
          "value": "MPMovieTimeOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieTimeOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieTimeOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieTimeOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieTimeOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/title",
          "value": "MPMovieLoadState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieLoadState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieLoadState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieScalingMode/title",
          "value": "MPMovieScalingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieScalingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieScalingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieScalingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieScalingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieSourceType/title",
          "value": "MPMovieSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieControlStyle/title",
          "value": "MPMovieControlStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieControlStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieControlStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieControlStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieControlStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerThumbnailTimeKey/title",
          "value": "MPMoviePlayerThumbnailTimeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerThumbnailTimeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerThumbnailTimeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieRepeatMode/title",
          "value": "MPMovieRepeatMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieRepeatMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieRepeatMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerThumbnailImageKey/title",
          "value": "MPMoviePlayerThumbnailImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerThumbnailImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerThumbnailImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieFinishReason/title",
          "value": "MPMovieFinishReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieFinishReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieFinishReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieFinishReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieFinishReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/title",
          "value": "MPMoviePlayerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlaybackState/title",
          "value": "MPMoviePlaybackState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlaybackState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlaybackState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieMediaTypeMask/title",
          "value": "MPMovieMediaTypeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieMediaTypeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieMediaTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMovieMediaTypeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMovieMediaTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerThumbnailErrorKey/title",
          "value": "MPMoviePlayerThumbnailErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerThumbnailErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerThumbnailErrorKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/thumbnail-notification-user-info-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/thumbnail-notification-user-info-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
