{
  "abstract": [
    {
      "text": "Dictionary keys for use with the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata/allMetadata",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property. All keys are optional.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/deprecated-types",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/timed-metadata-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Timed metadata dictionary keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyDataType": {
      "abstract": [
        {
          "text": "The data type of the timed metadata.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataKeyDataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataKeyDataType"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerTimedMetadataKeyDataType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayertimedmetadatakeydatatype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyInfo": {
      "abstract": [
        {
          "text": "Arbitrary information about the timed metadata.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataKeyInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataKeyInfo"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerTimedMetadataKeyInfo",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayertimedmetadatakeyinfo"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyLanguageCode": {
      "abstract": [
        {
          "text": "The metadata language, expressed using ISO 639-2, in a string object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataKeyLanguageCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyLanguageCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataKeyLanguageCode"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerTimedMetadataKeyLanguageCode",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayertimedmetadatakeylanguagecode"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyMIMEType": {
      "abstract": [
        {
          "text": "The MIME type for the timed metadata.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataKeyMIMEType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyMIMEType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataKeyMIMEType"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerTimedMetadataKeyMIMEType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayertimedmetadatakeymimetype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyName": {
      "abstract": [
        {
          "text": "The name of the timed metadata key.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataKeyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerTimedMetadataKeyName"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerTimedMetadataKeyName",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayertimedmetadatakeyname"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "timed metadata object that",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " carries time-based information within HTTP streamed media.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPTimedMetadata"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPTimedMetadata"
        }
      ],
      "role": "symbol",
      "title": "MPTimedMetadata",
      "type": "topic",
      "url": "/documentation/mediaplayer/mptimedmetadata"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata/allMetadata": {
      "abstract": [
        {
          "text": "A dictionary containing all the metadata in the object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allMetadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPTimedMetadata/allMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allMetadata"
        }
      ],
      "role": "symbol",
      "title": "allMetadata",
      "type": "topic",
      "url": "/documentation/mediaplayer/mptimedmetadata/allmetadata"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/deprecated-types": {
      "abstract": [
        {
          "text": "Review deprecated symbols and avoid using them in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/deprecated-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated types",
      "type": "topic",
      "url": "/documentation/mediaplayer/deprecated-types"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyName",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyInfo",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyMIMEType",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyDataType",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyLanguageCode"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyName",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyInfo",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyMIMEType",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyDataType",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerTimedMetadataKeyLanguageCode"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerTimedMetadataKeyDataType/title",
          "value": "MPMoviePlayerTimedMetadataKeyDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerTimedMetadataKeyDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerTimedMetadataKeyDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerTimedMetadataKeyLanguageCode/title",
          "value": "MPMoviePlayerTimedMetadataKeyLanguageCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerTimedMetadataKeyLanguageCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerTimedMetadataKeyLanguageCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerTimedMetadataKeyInfo/title",
          "value": "MPMoviePlayerTimedMetadataKeyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerTimedMetadataKeyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerTimedMetadataKeyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata~1allMetadata/title",
          "value": "allMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata~1allMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata/title",
          "value": "MPTimedMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPTimedMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPTimedMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPTimedMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerTimedMetadataKeyMIMEType/title",
          "value": "MPMoviePlayerTimedMetadataKeyMIMEType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerTimedMetadataKeyMIMEType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerTimedMetadataKeyMIMEType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerTimedMetadataKeyName/title",
          "value": "MPMoviePlayerTimedMetadataKeyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerTimedMetadataKeyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerTimedMetadataKeyName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/timed-metadata-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/timed-metadata-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
