{
  "abstract": [
    {
      "text": "Respond to requests to change which part of a media item plays.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/track-navigation-events"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Track navigation events"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackPositionCommand": {
      "abstract": [
        {
          "text": "An object that responds to requests to change the current playback position of the playing item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangePlaybackPositionCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackPositionCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangePlaybackPositionCommand"
        }
      ],
      "role": "symbol",
      "title": "MPChangePlaybackPositionCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangeplaybackpositioncommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackPositionCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the playback position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangePlaybackPositionCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackPositionCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPChangePlaybackPositionCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPChangePlaybackPositionCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpchangeplaybackpositioncommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSeekCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting that the player seek to a new position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSeekCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSeekCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSeekCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPSeekCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpseekcommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSkipIntervalCommand": {
      "abstract": [
        {
          "text": "An object that defines the skip intervals for the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSkipIntervalCommand"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSkipIntervalCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSkipIntervalCommand"
        }
      ],
      "role": "symbol",
      "title": "MPSkipIntervalCommand",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpskipintervalcommand"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSkipIntervalCommandEvent": {
      "abstract": [
        {
          "text": "An event requesting a change in the current skip interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSkipIntervalCommandEvent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSkipIntervalCommandEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSkipIntervalCommandEvent"
        }
      ],
      "role": "symbol",
      "title": "MPSkipIntervalCommandEvent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpskipintervalcommandevent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events": {
      "abstract": [
        {
          "text": "Respond to incoming feedback and rating events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Feedback and rating events",
      "type": "topic",
      "url": "/documentation/mediaplayer/feedback-and-rating-events"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications": {
      "abstract": [
        {
          "text": "Handle events for external media players.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
      "kind": "article",
      "role": "article",
      "title": "Handling external player events notifications",
      "type": "topic",
      "url": "/documentation/mediaplayer/handling-external-player-events-notifications"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events": {
      "abstract": [
        {
          "text": "Respond to changes in the way media items play.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media playback mode events",
      "type": "topic",
      "url": "/documentation/mediaplayer/media-playback-mode-events"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events": {
      "abstract": [
        {
          "text": "Set up the remote command center to handle media player events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Remote command center events",
      "type": "topic",
      "url": "/documentation/mediaplayer/remote-command-center-events"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "External-player-and-system-event-handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events"
      ],
      "title": "External player and system event handling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-track-navigation-events",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackPositionCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackPositionCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSeekCommandEvent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSkipIntervalCommand",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSkipIntervalCommandEvent"
      ],
      "title": "Responding to track navigation events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-track-navigation-events",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackPositionCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPChangePlaybackPositionCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSeekCommandEvent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSkipIntervalCommand",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPSkipIntervalCommandEvent"
              ],
              "title": "Responding to track navigation events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "External-player-and-system-event-handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/handling-external-player-events-notifications",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/remote-command-center-events",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/media-playback-mode-events",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/feedback-and-rating-events"
              ],
              "title": "External player and system event handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackPositionCommand/title",
          "value": "MPChangePlaybackPositionCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackPositionCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackPositionCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackPositionCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackPositionCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSkipIntervalCommand/title",
          "value": "MPSkipIntervalCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSkipIntervalCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSkipIntervalCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSkipIntervalCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSkipIntervalCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSeekCommandEvent/title",
          "value": "MPSeekCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSeekCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSeekCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSeekCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSeekCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackPositionCommandEvent/title",
          "value": "MPChangePlaybackPositionCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackPositionCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackPositionCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPChangePlaybackPositionCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPChangePlaybackPositionCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSkipIntervalCommandEvent/title",
          "value": "MPSkipIntervalCommandEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSkipIntervalCommandEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSkipIntervalCommandEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPSkipIntervalCommandEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSkipIntervalCommandEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/track-navigation-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/track-navigation-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
