{
  "abstract": [
    {
      "text": "Properties for obtaining user-defined metadata for a media item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/user-defined-property-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "User-defined property keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Obtain user-defined metadata for a media item by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaEntity/value(forProperty:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method with these property keys. Don’t use user-defined properties to build media property predicates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaEntity/value(forProperty:)": {
      "abstract": [
        {
          "text": "Retrieves the value for a specified media property key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaEntity/value(forProperty:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForProperty:"
        }
      ],
      "role": "symbol",
      "title": "value(forProperty:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaentity/value(forproperty:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem": {
      "abstract": [
        {
          "text": "A collection of properties that represents a single item in the media library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItem"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItem"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItem",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitem"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBookmarkTime": {
      "abstract": [
        {
          "text": "The user’s place in the media item the most recent time it was played.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyBookmarkTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBookmarkTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyBookmarkTime"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyBookmarkTime",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertybookmarktime"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDateAdded": {
      "abstract": [
        {
          "text": "The date the media item was added to the user’s Media library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyDateAdded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDateAdded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyDateAdded"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyDateAdded",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertydateadded"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLastPlayedDate": {
      "abstract": [
        {
          "text": "The most recent calendar date on which the user played the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyLastPlayedDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLastPlayedDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyLastPlayedDate"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyLastPlayedDate",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertylastplayeddate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyRating": {
      "abstract": [
        {
          "text": "The user-specified rating of the object in the range ",
          "type": "text"
        },
        {
          "code": "[0...5]",
          "type": "codeVoice"
        },
        {
          "text": ", where a value of 5 indicates the most favorable rating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyRating"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyRating",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyrating"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertySkipCount": {
      "abstract": [
        {
          "text": "The number of times the user has skipped playing the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertySkipCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertySkipCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertySkipCount"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertySkipCount",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyskipcount"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyUserGrouping": {
      "abstract": [
        {
          "text": "Corresponds to the “Grouping” field in the Info tab in the Get Info dialog in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyUserGrouping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyUserGrouping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaItemPropertyUserGrouping"
        }
      ],
      "role": "symbol",
      "title": "MPMediaItemPropertyUserGrouping",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaitempropertyusergrouping"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType": {
      "abstract": [
        {
          "text": "The properties for defining the type for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaType"
        }
      ],
      "role": "symbol",
      "title": "MPMediaType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/general-media-item-property-keys": {
      "abstract": [
        {
          "text": "System-defined properties for obtaining the metadata for a media item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/general-media-item-property-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General media item property keys",
      "type": "topic",
      "url": "/documentation/mediaplayer/general-media-item-property-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-item-types-and-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/general-media-item-property-keys"
      ],
      "title": "Media item types and keys"
    }
  ],
  "topicSections": [
    {
      "anchor": "User-defined-property-keys",
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertySkipCount",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyRating",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLastPlayedDate",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyUserGrouping",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBookmarkTime",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDateAdded"
      ],
      "title": "User-defined property keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "User-defined-property-keys",
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertySkipCount",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyRating",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyLastPlayedDate",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyUserGrouping",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyBookmarkTime",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItemPropertyDateAdded"
              ],
              "title": "User-defined property keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-item-types-and-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/general-media-item-property-keys"
              ],
              "title": "Media item types and keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyDateAdded/title",
          "value": "MPMediaItemPropertyDateAdded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyDateAdded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyDateAdded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyBookmarkTime/title",
          "value": "MPMediaItemPropertyBookmarkTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyBookmarkTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyBookmarkTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyLastPlayedDate/title",
          "value": "MPMediaItemPropertyLastPlayedDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyLastPlayedDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyLastPlayedDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType/title",
          "value": "MPMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyRating/title",
          "value": "MPMediaItemPropertyRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertySkipCount/title",
          "value": "MPMediaItemPropertySkipCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertySkipCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertySkipCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyUserGrouping/title",
          "value": "MPMediaItemPropertyUserGrouping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItemPropertyUserGrouping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItemPropertyUserGrouping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem/title",
          "value": "MPMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaEntity~1value(forProperty:)/title",
          "value": "valueForProperty:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaEntity~1value(forProperty:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueForProperty:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/user-defined-property-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/user-defined-property-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
