{
  "abstract": [
    {
      "text": "The insets for the content portion of the popover.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods/contentViewInsets()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIPopoverBackgroundViewMethods(cm)contentViewInsets",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "contentViewInsets"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@UIEdgeInsets",
        "text": "UIEdgeInsets"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "contentViewInsets"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "contentViewInsets()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "contentViewInsets"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@UIEdgeInsets",
              "text": "UIEdgeInsets"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Consider your popover background view without the arrow, and the insets in this property represent the distance from a given edge of your background content to the corresponding edge of the popover’s content view. (This edges of the background content should be flush with the frame rectangle of your view, except on the side containing the arrow, of course.) The popover controller uses these values (in combination with the value returned by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods/arrowHeight()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method) to determine where to position the popover content view. Because the arrow height is accounted for separately, your implementation of this method should return a set of constant values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets": {
      "abstract": [
        {
          "text": "The inset distances for views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "UIEdgeInsets",
      "type": "topic",
      "url": "/documentation/uikit/uiedgeinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods": {
      "abstract": [
        {
          "text": "A set of methods that popover background view subclasses must implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverBackgroundViewMethods"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverBackgroundViewMethods"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverBackgroundViewMethods",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverbackgroundviewmethods"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods/arrowHeight()": {
      "abstract": [
        {
          "text": "The height of the arrow (measured in points) from its base to its tip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrowHeight"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods/arrowHeight()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrowHeight"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "arrowHeight()",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverbackgroundviewmethods/arrowheight()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods/contentViewInsets()": {
      "abstract": [
        {
          "text": "The insets for the content portion of the popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentViewInsets"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods/contentViewInsets()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentViewInsets"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "contentViewInsets()",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverbackgroundviewmethods/contentviewinsets()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods/arrowHeight()"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "contentViewInsets"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "contentViewInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods/arrowHeight()"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@UIEdgeInsets",
                    "text": "UIEdgeInsets"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "contentViewInsets"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundViewMethods/title",
          "value": "UIPopoverBackgroundViewMethods"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundViewMethods/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverBackgroundViewMethods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundViewMethods/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverBackgroundViewMethods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundViewMethods~1contentViewInsets()/title",
          "value": "contentViewInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundViewMethods~1contentViewInsets()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "contentViewInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/title",
          "value": "UIEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundViewMethods~1arrowHeight()/title",
          "value": "arrowHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundViewMethods~1arrowHeight()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "arrowHeight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipopoverbackgroundviewmethods/contentviewinsets()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipopoverbackgroundviewmethods/contentviewinsets()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
