{
  "abstract": [
    {
      "text": "A rate of time in which 1 minute in the test environment represents one day.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneMinuteIsOneDay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKTestTimeRate@SKTestTimeRateOneMinuteIsOneDay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "oneMinuteIsOneDay"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKTestTimeRateOneMinuteIsOneDay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.2",
        "introducedAt": "14.0",
        "name": "iOS",
        "renamed": "SKTestSession.TimeRate.monthlyRenewalEveryThirtyMinutes",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.2",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "renamed": "SKTestSession.TimeRate.monthlyRenewalEveryThirtyMinutes",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.2",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "renamed": "SKTestSession.TimeRate.monthlyRenewalEveryThirtyMinutes",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.1",
        "introducedAt": "11.0",
        "name": "macOS",
        "renamed": "SKTestSession.TimeRate.monthlyRenewalEveryThirtyMinutes",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.2",
        "introducedAt": "14.0",
        "name": "tvOS",
        "renamed": "SKTestSession.TimeRate.monthlyRenewalEveryThirtyMinutes",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.3",
        "introducedAt": "7.0",
        "name": "watchOS",
        "renamed": "SKTestSession.TimeRate.monthlyRenewalEveryThirtyMinutes",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKTestSession.TimeRate.oneMinuteIsOneDay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "oneMinuteIsOneDay"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession": {
      "abstract": [
        {
          "text": "The controls and environment configuration you use to test StoreKit transactions in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum": {
      "abstract": [
        {
          "text": "The values for rates of time passing in the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TimeRate"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TimeRate"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/fiveMinutesIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 5 minutes in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fiveMinutesIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/fiveMinutesIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateFiveMinutesIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.fiveMinutesIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/fiveminutesisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every 30 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryThirtyMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryThirtyMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryThirtyMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleverythirtyminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneHourIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 1 hour in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneHourIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneHourIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneHourIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneHourIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onehourisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneMinuteIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 1 minute in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinuteIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneMinuteIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneMinuteIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneMinuteIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/oneminuteisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneSecondIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 1 second in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneSecondIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneSecondIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneSecondIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneSecondIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onesecondisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtyMinutesIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 30 minutes in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirtyMinutesIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtyMinutesIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateThirtyMinutesIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.thirtyMinutesIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/thirtyminutesisoneday"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtySecondsIsOneDay": {
      "abstract": [
        {
          "text": "A rate of time in which 30 seconds in the test environment represents one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirtySecondsIsOneDay"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtySecondsIsOneDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateThirtySecondsIsOneDay"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.thirtySecondsIsOneDay",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/thirtysecondsisoneday"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneHourIsOneDay",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtyMinutesIsOneDay",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/fiveMinutesIsOneDay",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtySecondsIsOneDay",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneSecondIsOneDay"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.2",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.2",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.2",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.1",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.2",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.3",
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKTestTimeRateOneMinuteIsOneDay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneMinuteIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneHourIsOneDay",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtyMinutesIsOneDay",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/fiveMinutesIsOneDay",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/thirtySecondsIsOneDay",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneSecondIsOneDay"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKTestTimeRateOneMinuteIsOneDay"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1thirtyMinutesIsOneDay/title",
          "value": "SKTestTimeRateThirtyMinutesIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1thirtyMinutesIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateThirtyMinutesIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneMinuteIsOneDay/title",
          "value": "SKTestTimeRateOneMinuteIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneMinuteIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneMinuteIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1fiveMinutesIsOneDay/title",
          "value": "SKTestTimeRateFiveMinutesIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1fiveMinutesIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateFiveMinutesIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1thirtySecondsIsOneDay/title",
          "value": "SKTestTimeRateThirtySecondsIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1thirtySecondsIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateThirtySecondsIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/title",
          "value": "SKTestSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneHourIsOneDay/title",
          "value": "SKTestTimeRateOneHourIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneHourIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneHourIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneSecondIsOneDay/title",
          "value": "SKTestTimeRateOneSecondIsOneDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneSecondIsOneDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneSecondIsOneDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryThirtyMinutes/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryThirtyMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryThirtyMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryThirtyMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/title",
          "value": "SKTestTimeRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/sktestsession/timerate-swift.enum/oneminuteisoneday"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/sktestsession/timerate-swift.enum/oneminuteisoneday"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
