{
  "abstract": [
    {
      "text": "A rate of time in the test environment in which subscriptions of any time length renew every 10 seconds.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTenSeconds"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKTestTimeRate@SKTestTimeRateOneRenewalEveryTenSeconds",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "oneRenewalEveryTenSeconds"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKTestTimeRateOneRenewalEveryTenSeconds"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKTestSession.TimeRate.oneRenewalEveryTenSeconds"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "oneRenewalEveryTenSeconds"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This time rate renews subscriptions every ten seconds in the testing environment, regardless of actual renewal periods for each subscription.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sandbox environment does not support this subscription renewal rate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This time rate also affects the billing grace period and the billing retry period in the testing environment, as the table below shows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Time Period",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Grace period for subscriptions with all renewal periods",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "10 seconds",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Billing retry period",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "20 seconds",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession": {
      "abstract": [
        {
          "text": "The controls and environment configuration you use to test StoreKit transactions in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum": {
      "abstract": [
        {
          "text": "The values for rates of time passing in the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TimeRate"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TimeRate"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFifteenMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every 15 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryFifteenMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFifteenMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryFifteenMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryFifteenMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleveryfifteenminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFiveMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every 5 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryFiveMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFiveMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryFiveMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryFiveMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleveryfiveminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryMinute": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every minute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryMinute"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryMinute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryMinute"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryMinute",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleveryminute"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTenSeconds": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every 10 seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryTenSeconds"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTenSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryTenSeconds"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryTenSeconds",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleverytenseconds"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryThirtySeconds": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every 30 seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryThirtySeconds"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryThirtySeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryThirtySeconds"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryThirtySeconds",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleverythirtyseconds"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTwoSeconds": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which subscriptions of any time length renew every 2 seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneRenewalEveryTwoSeconds"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTwoSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateOneRenewalEveryTwoSeconds"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.oneRenewalEveryTwoSeconds",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleverytwoseconds"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Fixed-time-rates-for-subscription-renewals",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFifteenMinutes",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFiveMinutes",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryMinute",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryThirtySeconds",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTwoSeconds"
      ],
      "title": "Fixed time rates for subscription renewals"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKTestTimeRateOneRenewalEveryTenSeconds"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryTenSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Fixed-time-rates-for-subscription-renewals",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFifteenMinutes",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryFiveMinutes",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryMinute",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryThirtySeconds",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/oneRenewalEveryTwoSeconds"
              ],
              "title": "Fixed time rates for subscription renewals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKTestTimeRateOneRenewalEveryTenSeconds"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryMinute/title",
          "value": "SKTestTimeRateOneRenewalEveryMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryMinute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryFiveMinutes/title",
          "value": "SKTestTimeRateOneRenewalEveryFiveMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryFiveMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryFiveMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryTwoSeconds/title",
          "value": "SKTestTimeRateOneRenewalEveryTwoSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryTwoSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryTwoSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/title",
          "value": "SKTestSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryThirtySeconds/title",
          "value": "SKTestTimeRateOneRenewalEveryThirtySeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryThirtySeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryThirtySeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/title",
          "value": "SKTestTimeRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryTenSeconds/title",
          "value": "SKTestTimeRateOneRenewalEveryTenSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryTenSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryTenSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryFifteenMinutes/title",
          "value": "SKTestTimeRateOneRenewalEveryFifteenMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1oneRenewalEveryFifteenMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateOneRenewalEveryFifteenMinutes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleverytenseconds"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/sktestsession/timerate-swift.enum/onerenewaleverytenseconds"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
