{
  "abstract": [
    {
      "text": "A rate of time in which the test environment runs in real time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/realTime"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKTestTimeRate@SKTestTimeRateRealTime",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "realTime"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKTestTimeRateRealTime"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKTestSession.TimeRate.realTime"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "realTime"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With this time rate, subscriptions in the testing environment renew in real time. For example, a weekly subscription renews in one week.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The time rate also affects the billing grace period and the billing retry period in the testing environment. The table below shows the real-time rates:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Time period",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Grace period for subscriptions with a weekly renewal period",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "6 days",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Grace period for subscriptions with all other renewal periods",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "16 days",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Billing retry period",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "60 days",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession": {
      "abstract": [
        {
          "text": "The controls and environment configuration you use to test StoreKit transactions in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum": {
      "abstract": [
        {
          "text": "The values for rates of time passing in the test environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TimeRate"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TimeRate"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFifteenMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every 15 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryFifteenMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFifteenMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryFifteenMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryFifteenMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleveryfifteenminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFiveMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every 5 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryFiveMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFiveMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryFiveMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryFiveMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleveryfiveminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryHour": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every hour.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryHour"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryHour",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryHour"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryHour",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleveryhour"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every 30 minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryThirtyMinutes"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryThirtyMinutes"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryThirtyMinutes",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleverythirtyminutes"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtySeconds": {
      "abstract": [
        {
          "text": "A rate of time in the test environment in which monthly subscriptions renew every 30 seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthlyRenewalEveryThirtySeconds"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtySeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateMonthlyRenewalEveryThirtySeconds"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.monthlyRenewalEveryThirtySeconds",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/monthlyrenewaleverythirtyseconds"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/realTime": {
      "abstract": [
        {
          "text": "A rate of time in which the test environment runs in real time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "realTime"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/realTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestTimeRateRealTime"
        }
      ],
      "role": "symbol",
      "title": "SKTestSession.TimeRate.realTime",
      "type": "topic",
      "url": "/documentation/storekittest/sktestsession/timerate-swift.enum/realtime"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scaled-time-rates-for-subscription-renewals",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryHour",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFifteenMinutes",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFiveMinutes",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtySeconds"
      ],
      "title": "Scaled time rates for subscription renewals"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKTestTimeRateRealTime"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateRealTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scaled-time-rates-for-subscription-renewals",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryHour",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtyMinutes",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFifteenMinutes",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryFiveMinutes",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestSession/TimeRate-swift.enum/monthlyRenewalEveryThirtySeconds"
              ],
              "title": "Scaled time rates for subscription renewals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKTestTimeRateRealTime"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryFiveMinutes/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryFiveMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryFiveMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryFiveMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryHour/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryHour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryHour/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryHour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/title",
          "value": "SKTestTimeRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1realTime/title",
          "value": "SKTestTimeRateRealTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1realTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateRealTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryFifteenMinutes/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryFifteenMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryFifteenMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryFifteenMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryThirtyMinutes/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryThirtyMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryThirtyMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryThirtyMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryThirtySeconds/title",
          "value": "SKTestTimeRateMonthlyRenewalEveryThirtySeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession~1TimeRate-swift.enum~1monthlyRenewalEveryThirtySeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestTimeRateMonthlyRenewalEveryThirtySeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/title",
          "value": "SKTestSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/sktestsession/timerate-swift.enum/realtime"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/sktestsession/timerate-swift.enum/realtime"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
