{
  "abstract": [
    {
      "text": "The delegate of the app controller object.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/delegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVApplicationController(py)delegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "delegate"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)TVApplicationControllerDelegate",
        "text": "TVApplicationControllerDelegate"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "delegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "delegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "weak"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "delegate"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)TVApplicationControllerDelegate",
              "text": "TVApplicationControllerDelegate"
            },
            {
              "kind": "text",
              "text": ")? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The delegate provides methods for observing and managing different ",
              "type": "text"
            },
            {
              "code": "TVApplicationController",
              "type": "codeVoice"
            },
            {
              "text": " object states. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides callbacks during the launch of the JavaScript application.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController": {
      "abstract": [
        {
          "text": "An object that bridges the UI, navigation stack, storage, and event handling from JavaScript.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVApplicationController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVApplicationController"
        }
      ],
      "role": "symbol",
      "title": "TVApplicationController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/delegate": {
      "abstract": [
        {
          "text": "The delegate of the app controller object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)TVApplicationControllerDelegate",
          "text": "TVApplicationControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller/delegate"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate": {
      "abstract": [
        {
          "text": "A protocol used to observe and manage the different states of an application controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVApplicationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVApplicationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "TVApplicationControllerDelegate",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontrollerdelegate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Delegate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate"
      ],
      "title": "Getting the Delegate"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Delegate",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate"
              ],
              "title": "Getting the Delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "weak"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)TVApplicationControllerDelegate",
                    "text": "id<TVApplicationControllerDelegate>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "delegate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/title",
          "value": "TVApplicationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/title",
          "value": "TVApplicationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvapplicationcontroller/delegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvapplicationcontroller/delegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
