{
  "abstract": [
    {
      "text": "Initializes and returns an app controller.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/init(context:window:delegate:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVApplicationController(im)initWithContext:window:delegate:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "context"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)TVApplicationControllerContext",
        "text": "TVApplicationControllerContext"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "window"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIWindow",
        "text": "UIWindow"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "delegate"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)TVApplicationControllerDelegate",
        "text": "TVApplicationControllerDelegate"
      },
      {
        "kind": "text",
        "text": ")?)"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithContext:window:delegate:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(context:window:delegate:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)TVApplicationControllerContext",
              "text": "TVApplicationControllerContext"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "window"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIWindow",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIWindow",
              "text": "UIWindow"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "delegate"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)TVApplicationControllerDelegate",
              "text": "TVApplicationControllerDelegate"
            },
            {
              "kind": "text",
              "text": ")?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object containing information about the JavaScript app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIWindow",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object that presents the application controller’s navigation controller.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "window"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The app controller delegate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "delegate"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The initialized ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An app controller coordinates activity between the JavaScript environments and tvOS. There are three options when presenting the application controller. If you provide a valid ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIWindow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, the application controller’s navigation controller is presented immediately and managed by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If no window is provided, the navigation controller can be presented and dismissed manually within the binary app. Finally, if you wish to present native view controllers alongside a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, you can push additional view controllers onto ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/navigationController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UIWindow": {
      "abstract": [
        {
          "text": "The backdrop for your app’s user interface and the object that dispatches events to your views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindow"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIWindow",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindow",
      "type": "topic",
      "url": "/documentation/UIKit/UIWindow"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController": {
      "abstract": [
        {
          "text": "An object that bridges the UI, navigation stack, storage, and event handling from JavaScript.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVApplicationController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVApplicationController"
        }
      ],
      "role": "symbol",
      "title": "TVApplicationController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/init(context:window:delegate:)": {
      "abstract": [
        {
          "text": "Initializes and returns an app controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVApplicationControllerContext",
          "text": "TVApplicationControllerContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "window"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)TVApplicationControllerDelegate",
          "text": "TVApplicationControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/init(context:window:delegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContext:window:delegate:"
        }
      ],
      "role": "symbol",
      "title": "init(context:window:delegate:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller/init(context:window:delegate:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/navigationController": {
      "abstract": [
        {
          "text": "The navigation controller that is bridged from JavaScript to tvOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationController",
          "text": "UINavigationController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/navigationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "navigationController"
        }
      ],
      "role": "symbol",
      "title": "navigationController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller/navigationcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext": {
      "abstract": [
        {
          "text": "Launch information provided to the TV application controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVApplicationControllerContext"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVApplicationControllerContext"
        }
      ],
      "role": "symbol",
      "title": "TVApplicationControllerContext",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontrollercontext"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate": {
      "abstract": [
        {
          "text": "A protocol used to observe and manage the different states of an application controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVApplicationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVApplicationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "TVApplicationControllerDelegate",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontrollerdelegate"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIWindow": {
      "abstract": [
        {
          "text": "The backdrop for your app’s user interface and the object that dispatches events to your views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindow"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIWindow",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIWindow",
      "type": "topic",
      "url": "/documentation/UIKit/UIWindow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithContext:window:delegate:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithContext:window:delegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithContext:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)TVApplicationControllerContext",
                    "text": "TVApplicationControllerContext"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "context"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "window:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIWindow",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIWindow",
                    "text": "UIWindow"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "window"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "delegate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)TVApplicationControllerDelegate",
                    "text": "id<TVApplicationControllerDelegate>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "delegate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object containing information about the JavaScript app.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "context"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/UIKit/UIWindow",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object that presents the application controller’s navigation controller.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "window"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The app controller delegate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "delegate"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The initialized ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/title",
          "value": "TVApplicationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/title",
          "value": "TVApplicationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIWindow/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIWindow"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1init(context:window:delegate:)/title",
          "value": "initWithContext:window:delegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1init(context:window:delegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithContext:window:delegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1navigationController/title",
          "value": "navigationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1navigationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "navigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIWindow/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIWindow"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerContext/title",
          "value": "TVApplicationControllerContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvapplicationcontroller/init(context:window:delegate:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvapplicationcontroller/init(context:window:delegate:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
