{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/corewlanconstants-h"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "role": "collectionGroup",
    "title": "CoreWLANConstants.h"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Included-Headers",
          "level": 3,
          "text": "Included Headers",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<Foundation/Foundation.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreWLAN Enumerations",
      "type": "topic",
      "url": "/documentation/corewlan/corewlan-enumerations"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreWLAN Functions",
      "type": "topic",
      "url": "/documentation/corewlan/corewlan-functions"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/corewlantypes-h": {
      "abstract": [],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/corewlantypes-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreWLANTypes.h",
      "type": "topic",
      "url": "/documentation/corewlan/corewlantypes-h"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/corewlanutil-h": {
      "abstract": [],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/corewlanutil-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreWLANUtil.h",
      "type": "topic",
      "url": "/documentation/corewlan/corewlanutil-h"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/global-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/global-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Global Constants",
      "type": "topic",
      "url": "/documentation/corewlan/global-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/corewlantypes-h",
        "doc://com.apple.corewlan/documentation/CoreWLAN/corewlanutil-h",
        "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-enumerations",
        "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/global-constants"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/global-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/corewlantypes-h",
                "doc://com.apple.corewlan/documentation/CoreWLAN/corewlanutil-h",
                "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-enumerations",
                "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-functions"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/corewlanconstants-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/corewlanconstants-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
