{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/corewlanutil-h"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CoreWLANUtil.h"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Included-Headers",
          "level": 3,
          "text": "Included Headers",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<Foundation/Foundation.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentity": {
      "abstract": [
        {
          "text": "Finds and returns the identity stored for corresponding network with the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainCopyEAPIdentity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentity",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainCopyEAPIdentity",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaincopyeapidentity"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentityList(_:)": {
      "abstract": [
        {
          "text": "Finds and returns the available identities stored in the keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWKeychainCopyEAPIdentityList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentityList(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWKeychainCopyEAPIdentityList"
        }
      ],
      "role": "symbol",
      "title": "CWKeychainCopyEAPIdentityList(_:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaincopyeapidentitylist(_:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPUsernameAndPassword": {
      "abstract": [
        {
          "text": "Finds and returns the username and password stored for corresponding network with the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainCopyEAPUsernameAndPassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPUsernameAndPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainCopyEAPUsernameAndPassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaincopyeapusernameandpassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyPassword": {
      "abstract": [
        {
          "text": "Finds and returns the keychain password stored for the corresponding network with the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainCopyPassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainCopyPassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaincopypassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeleteEAPUsernameAndPassword": {
      "abstract": [
        {
          "text": "Deletes the keychain item containing the 802.1X username and password for the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainDeleteEAPUsernameAndPassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeleteEAPUsernameAndPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainDeleteEAPUsernameAndPassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaindeleteeapusernameandpassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeletePassword": {
      "abstract": [
        {
          "text": "Deletes the network password for the specified SSID from the default keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainDeletePassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeletePassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainDeletePassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaindeletepassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPIdentity": {
      "abstract": [
        {
          "text": "Associates an exisiting identity item to the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainSetEAPIdentity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPIdentity",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainSetEAPIdentity",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychainseteapidentity"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPUsernameAndPassword": {
      "abstract": [
        {
          "text": "Sets the keychain item containing the 802.1X username and password for the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainSetEAPUsernameAndPassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPUsernameAndPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainSetEAPUsernameAndPassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychainseteapusernameandpassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetPassword": {
      "abstract": [
        {
          "text": "Sets the network keychain password for the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainSetPassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainSetPassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychainsetpassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWMergeNetworks(_:)": {
      "abstract": [
        {
          "text": "Merges the specified set of CWNetwork objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWMergeNetworks"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CWNetwork",
          "text": "CWNetwork"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CWNetwork",
          "text": "CWNetwork"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWMergeNetworks(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWMergeNetworks"
        }
      ],
      "role": "symbol",
      "title": "CWMergeNetworks(_:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwmergenetworks(_:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreWLAN Enumerations",
      "type": "topic",
      "url": "/documentation/corewlan/corewlan-enumerations"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreWLAN Functions",
      "type": "topic",
      "url": "/documentation/corewlan/corewlan-functions"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/corewlanconstants-h": {
      "abstract": [],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/corewlanconstants-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreWLANConstants.h",
      "type": "topic",
      "url": "/documentation/corewlan/corewlanconstants-h"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/corewlantypes-h": {
      "abstract": [],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/corewlantypes-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreWLANTypes.h",
      "type": "topic",
      "url": "/documentation/corewlan/corewlantypes-h"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/corewlanconstants-h",
        "doc://com.apple.corewlan/documentation/CoreWLAN/corewlantypes-h",
        "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-enumerations",
        "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Utility-Methods",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentityList(_:)",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWMergeNetworks(_:)"
      ],
      "title": "Utility Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Utility-Methods",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentity",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentityList(_:)",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPUsernameAndPassword",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyPassword",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeleteEAPUsernameAndPassword",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeletePassword",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPIdentity",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPUsernameAndPassword",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetPassword",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWMergeNetworks(_:)"
              ],
              "title": "Utility Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/corewlanconstants-h",
                "doc://com.apple.corewlan/documentation/CoreWLAN/corewlantypes-h",
                "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-enumerations",
                "doc://com.apple.corewlan/documentation/CoreWLAN/corewlan-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainCopyEAPIdentityList(_:)/title",
          "value": "CWKeychainCopyEAPIdentityList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainCopyEAPIdentityList(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWKeychainCopyEAPIdentityList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWMergeNetworks(_:)/title",
          "value": "CWMergeNetworks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWMergeNetworks(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWMergeNetworks"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/corewlanutil-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/corewlanutil-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
