{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CWErr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CWErr"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CWErr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CWErr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand": {
      "abstract": [
        {
          "text": "CoreWLAN channel bands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWChannelBand"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWChannelBand"
        }
      ],
      "role": "symbol",
      "title": "CWChannelBand",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelband"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth": {
      "abstract": [
        {
          "text": "CoreWLAN channel widths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWChannelWidth"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWChannelWidth"
        }
      ],
      "role": "symbol",
      "title": "CWChannelWidth",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelwidth"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags": {
      "abstract": [
        {
          "text": "Cipher key flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWCipherKeyFlags"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWCipherKeyFlags"
        }
      ],
      "role": "symbol",
      "title": "CWCipherKeyFlags",
      "type": "topic",
      "url": "/documentation/corewlan/cwcipherkeyflags"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAssociationDeniedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwAssociationDeniedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAssociationDeniedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWAssociationDeniedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwAssociationDeniedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwassociationdeniederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAuthenticationAlgorithmUnsupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwAuthenticationAlgorithmUnsupportedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAuthenticationAlgorithmUnsupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWAuthenticationAlgorithmUnsupportedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwAuthenticationAlgorithmUnsupportedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwauthenticationalgorithmunsupportederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwChallengeFailureErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwChallengeFailureErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwChallengeFailureErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWChallengeFailureErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwChallengeFailureErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwchallengefailureerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwCipherSuiteRejectedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwCipherSuiteRejectedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwCipherSuiteRejectedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWCipherSuiteRejectedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwCipherSuiteRejectedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwciphersuiterejectederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAKMPErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidAKMPErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAKMPErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidAKMPErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidAKMPErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidakmperr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAuthenticationSequenceNumberErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidAuthenticationSequenceNumberErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAuthenticationSequenceNumberErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidAuthenticationSequenceNumberErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidAuthenticationSequenceNumberErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidauthenticationsequencenumbererr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidFormatErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidFormatErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidFormatErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidFormatErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidFormatErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidformaterr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidGroupCipherErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidGroupCipherErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidGroupCipherErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidGroupCipherErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidGroupCipherErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidgroupciphererr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidInformationElementErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidInformationElementErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidInformationElementErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidInformationElementErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidInformationElementErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidinformationelementerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidPMKErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidPMKErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidPMKErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidPMKErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidPMKErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidpmkerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidPairwiseCipherErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidPairwiseCipherErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidPairwiseCipherErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidPairwiseCipherErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidPairwiseCipherErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidpairwiseciphererr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidParameterErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidParameterErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidParameterErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidParameterErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidParameterErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidparametererr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidRSNCapabilitiesErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidRSNCapabilitiesErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidRSNCapabilitiesErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidRSNCapabilitiesErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidRSNCapabilitiesErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidrsncapabilitieserr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNoErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwNoErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNoErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWNoErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwNoErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwnoerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNoMemoryErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwNoMemoryErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNoMemoryErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWNoMemoryErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwNoMemoryErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwnomemoryerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwNotSupportedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwNotSupportedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwnotsupportederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwOperationNotPermittedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwOperationNotPermittedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwOperationNotPermittedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWOperationNotPermittedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwOperationNotPermittedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwoperationnotpermittederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwReassociationDeniedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwReassociationDeniedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwReassociationDeniedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWReassociationDeniedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwReassociationDeniedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwreassociationdeniederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwReferenceNotBoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwReferenceNotBoundErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwReferenceNotBoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWReferenceNotBoundErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwReferenceNotBoundErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwreferencenotbounderr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwShortSlotUnsupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwShortSlotUnsupportedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwShortSlotUnsupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWShortSlotUnsupportedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwShortSlotUnsupportedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwshortslotunsupportederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwSupplicantTimeoutErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwSupplicantTimeoutErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwSupplicantTimeoutErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSupplicantTimeoutErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwSupplicantTimeoutErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwsupplicanttimeouterr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwTimeoutErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwTimeoutErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwTimeoutErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWTimeoutErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwTimeoutErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwtimeouterr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnknownErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwUnknownErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnknownErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWUnknownErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwUnknownErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwunknownerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnspecifiedFailureErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwUnspecifiedFailureErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnspecifiedFailureErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWUnspecifiedFailureErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwUnspecifiedFailureErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwunspecifiedfailureerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedCapabilitiesErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwUnsupportedCapabilitiesErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedCapabilitiesErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWUnsupportedCapabilitiesErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwUnsupportedCapabilitiesErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwunsupportedcapabilitieserr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedRSNVersionErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwUnsupportedRSNVersionErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedRSNVersionErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWUnsupportedRSNVersionErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwUnsupportedRSNVersionErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwunsupportedrsnversionerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedRateSetErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwUnsupportedRateSetErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedRateSetErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWUnsupportedRateSetErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwUnsupportedRateSetErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwunsupportedrateseterr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwapFullErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwapFullErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwapFullErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWAPFullErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwapFullErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwapfullerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwdsssofdmUnsupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwdsssofdmUnsupportedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwdsssofdmUnsupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWDSSSOFDMUnsupportedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwdsssofdmUnsupportedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwdsssofdmunsupportederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cweapolErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cweapolErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cweapolErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWEAPOLErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cweapolErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cweapolerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwhtFeaturesNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwhtFeaturesNotSupportedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwhtFeaturesNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWHTFeaturesNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwhtFeaturesNotSupportedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwhtfeaturesnotsupportederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwipcFailureErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwipcFailureErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwipcFailureErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWIPCFailureErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwipcFailureErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwipcfailureerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwpcoTransitionTimeNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwpcoTransitionTimeNotSupportedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwpcoTransitionTimeNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPCOTransitionTimeNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwpcoTransitionTimeNotSupportedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwpcotransitiontimenotsupportederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/init(rawvalue:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType": {
      "abstract": [
        {
          "text": "Wi-Fi event types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWEventType"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventType"
        }
      ],
      "role": "symbol",
      "title": "CWEventType",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity": {
      "abstract": [
        {
          "text": "IBSS mode security types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWIBSSModeSecurity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWIBSSModeSecurity"
        }
      ],
      "role": "symbol",
      "title": "CWIBSSModeSecurity",
      "type": "topic",
      "url": "/documentation/corewlan/cwibssmodesecurity"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode": {
      "abstract": [
        {
          "text": "Wi-Fi interface operating modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWInterfaceMode"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWInterfaceMode"
        }
      ],
      "role": "symbol",
      "title": "CWInterfaceMode",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterfacemode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain": {
      "abstract": [
        {
          "text": "Keychain domain types that CoreWLAN keychain methods use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWKeychainDomain"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWKeychainDomain"
        }
      ],
      "role": "symbol",
      "title": "CWKeychainDomain",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaindomain"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode": {
      "abstract": [
        {
          "text": "CoreWLAN physical layer modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWPHYMode"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWPHYMode"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity": {
      "abstract": [
        {
          "text": "CoreWLAN security types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWSecurity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWSecurity"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwapFullErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAssociationDeniedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAuthenticationAlgorithmUnsupportedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwChallengeFailureErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwCipherSuiteRejectedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwdsssofdmUnsupportedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cweapolErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwhtFeaturesNotSupportedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwipcFailureErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAKMPErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAuthenticationSequenceNumberErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidFormatErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidGroupCipherErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidInformationElementErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidPMKErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidPairwiseCipherErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidParameterErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidRSNCapabilitiesErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNoErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNoMemoryErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNotSupportedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwOperationNotPermittedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwpcoTransitionTimeNotSupportedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwReassociationDeniedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwReferenceNotBoundErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwShortSlotUnsupportedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwSupplicantTimeoutErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwTimeoutErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnknownErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnspecifiedFailureErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedCapabilitiesErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedRSNVersionErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedRateSetErr"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CWErr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwapFullErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAssociationDeniedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAuthenticationAlgorithmUnsupportedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwChallengeFailureErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwCipherSuiteRejectedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwdsssofdmUnsupportedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cweapolErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwhtFeaturesNotSupportedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwipcFailureErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAKMPErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAuthenticationSequenceNumberErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidFormatErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidGroupCipherErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidInformationElementErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidPMKErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidPairwiseCipherErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidParameterErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidRSNCapabilitiesErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNoErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNoMemoryErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwNotSupportedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwOperationNotPermittedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwpcoTransitionTimeNotSupportedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwReassociationDeniedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwReferenceNotBoundErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwShortSlotUnsupportedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwSupplicantTimeoutErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwTimeoutErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnknownErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnspecifiedFailureErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedCapabilitiesErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedRSNVersionErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedRateSetErr"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CWErr"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwErr/title",
          "value": "kCWErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidInformationElementErr/title",
          "value": "kCWInvalidInformationElementErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidInformationElementErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidInformationElementErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnsupportedRSNVersionErr/title",
          "value": "kCWUnsupportedRSNVersionErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnsupportedRSNVersionErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWUnsupportedRSNVersionErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/title",
          "value": "CWInterfaceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterfaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterfaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwTimeoutErr/title",
          "value": "kCWTimeoutErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwTimeoutErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWTimeoutErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwipcFailureErr/title",
          "value": "kCWIPCFailureErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwipcFailureErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWIPCFailureErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidAuthenticationSequenceNumberErr/title",
          "value": "kCWInvalidAuthenticationSequenceNumberErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidAuthenticationSequenceNumberErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidAuthenticationSequenceNumberErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidFormatErr/title",
          "value": "kCWInvalidFormatErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidFormatErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidFormatErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwAssociationDeniedErr/title",
          "value": "kCWAssociationDeniedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwAssociationDeniedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWAssociationDeniedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwOperationNotPermittedErr/title",
          "value": "kCWOperationNotPermittedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwOperationNotPermittedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWOperationNotPermittedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwChallengeFailureErr/title",
          "value": "kCWChallengeFailureErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwChallengeFailureErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWChallengeFailureErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidPairwiseCipherErr/title",
          "value": "kCWInvalidPairwiseCipherErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidPairwiseCipherErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidPairwiseCipherErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/title",
          "value": "CWChannelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidAKMPErr/title",
          "value": "kCWInvalidAKMPErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidAKMPErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidAKMPErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/title",
          "value": "CWIBSSModeSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWIBSSModeSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWIBSSModeSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnsupportedRateSetErr/title",
          "value": "kCWUnsupportedRateSetErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnsupportedRateSetErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWUnsupportedRateSetErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwpcoTransitionTimeNotSupportedErr/title",
          "value": "kCWPCOTransitionTimeNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwpcoTransitionTimeNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPCOTransitionTimeNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwNoMemoryErr/title",
          "value": "kCWNoMemoryErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwNoMemoryErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWNoMemoryErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwSupplicantTimeoutErr/title",
          "value": "kCWSupplicantTimeoutErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwSupplicantTimeoutErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSupplicantTimeoutErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnknownErr/title",
          "value": "kCWUnknownErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnknownErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWUnknownErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/title",
          "value": "CWPHYMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/title",
          "value": "CWErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwReassociationDeniedErr/title",
          "value": "kCWReassociationDeniedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwReassociationDeniedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWReassociationDeniedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/title",
          "value": "CWEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/title",
          "value": "CWSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwReferenceNotBoundErr/title",
          "value": "kCWReferenceNotBoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwReferenceNotBoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWReferenceNotBoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwCipherSuiteRejectedErr/title",
          "value": "kCWCipherSuiteRejectedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwCipherSuiteRejectedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWCipherSuiteRejectedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidParameterErr/title",
          "value": "kCWInvalidParameterErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidParameterErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidParameterErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnsupportedCapabilitiesErr/title",
          "value": "kCWUnsupportedCapabilitiesErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnsupportedCapabilitiesErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWUnsupportedCapabilitiesErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwdsssofdmUnsupportedErr/title",
          "value": "kCWDSSSOFDMUnsupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwdsssofdmUnsupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWDSSSOFDMUnsupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnspecifiedFailureErr/title",
          "value": "kCWUnspecifiedFailureErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnspecifiedFailureErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWUnspecifiedFailureErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/title",
          "value": "CWChannelBand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidPMKErr/title",
          "value": "kCWInvalidPMKErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidPMKErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidPMKErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwhtFeaturesNotSupportedErr/title",
          "value": "kCWHTFeaturesNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwhtFeaturesNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWHTFeaturesNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwShortSlotUnsupportedErr/title",
          "value": "kCWShortSlotUnsupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwShortSlotUnsupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWShortSlotUnsupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwNotSupportedErr/title",
          "value": "kCWNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwNoErr/title",
          "value": "kCWNoErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwNoErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWNoErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidRSNCapabilitiesErr/title",
          "value": "kCWInvalidRSNCapabilitiesErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidRSNCapabilitiesErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidRSNCapabilitiesErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwAuthenticationAlgorithmUnsupportedErr/title",
          "value": "kCWAuthenticationAlgorithmUnsupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwAuthenticationAlgorithmUnsupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWAuthenticationAlgorithmUnsupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwapFullErr/title",
          "value": "kCWAPFullErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwapFullErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWAPFullErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/title",
          "value": "CWKeychainDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWKeychainDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWKeychainDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidGroupCipherErr/title",
          "value": "kCWInvalidGroupCipherErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidGroupCipherErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidGroupCipherErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/title",
          "value": "CWCipherKeyFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWCipherKeyFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWCipherKeyFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cweapolErr/title",
          "value": "kCWEAPOLErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cweapolErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWEAPOLErr"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwerr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwerr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
