{
  "abstract": [
    {
      "text": "Wi-Fi event types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CWEventType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CWEventType"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CWEventType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CWEventType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand": {
      "abstract": [
        {
          "text": "CoreWLAN channel bands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWChannelBand"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWChannelBand"
        }
      ],
      "role": "symbol",
      "title": "CWChannelBand",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelband"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth": {
      "abstract": [
        {
          "text": "CoreWLAN channel widths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWChannelWidth"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWChannelWidth"
        }
      ],
      "role": "symbol",
      "title": "CWChannelWidth",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelwidth"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags": {
      "abstract": [
        {
          "text": "Cipher key flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWCipherKeyFlags"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWCipherKeyFlags"
        }
      ],
      "role": "symbol",
      "title": "CWCipherKeyFlags",
      "type": "topic",
      "url": "/documentation/corewlan/cwcipherkeyflags"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType": {
      "abstract": [
        {
          "text": "Wi-Fi event types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWEventType"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventType"
        }
      ],
      "role": "symbol",
      "title": "CWEventType",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/bssidDidChange": {
      "abstract": [
        {
          "text": "Posts when the current BSSID of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bssidDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/bssidDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeBSSIDDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.bssidDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/bssiddidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/btCoexStats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "btCoexStats"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/btCoexStats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeBtCoexStats"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.btCoexStats",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/btcoexstats"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/countryCodeDidChange": {
      "abstract": [
        {
          "text": "Posts when the adopted country code of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "countryCodeDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/countryCodeDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeCountryCodeDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.countryCodeDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/countrycodedidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/init(rawvalue:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkDidChange": {
      "abstract": [
        {
          "text": "Posts when the link state for any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeLinkDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.linkDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/linkdidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkQualityDidChange": {
      "abstract": [
        {
          "text": "Posts when the RSSI or transmit rate for any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkQualityDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkQualityDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeLinkQualityDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.linkQualityDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/linkqualitydidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/modeDidChange": {
      "abstract": [
        {
          "text": "Posts when the operating mode of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modeDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/modeDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeModeDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.modeDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/modedidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/none": {
      "abstract": [
        {
          "text": "No specified event type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeNone"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.none",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/none"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange": {
      "abstract": [
        {
          "text": "Posts when the power state of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypePowerDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.powerDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/powerdidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/scanCacheUpdated": {
      "abstract": [
        {
          "text": "Posts when the scan cache of any Wi-Fi interface is updated with new scan results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scanCacheUpdated"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/scanCacheUpdated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeScanCacheUpdated"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.scanCacheUpdated",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/scancacheupdated"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/ssidDidChange": {
      "abstract": [
        {
          "text": "Posts when the current SSID of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ssidDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/ssidDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeSSIDDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.ssidDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/ssiddidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/unknown": {
      "abstract": [
        {
          "text": "Unknown event type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.unknown",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/unknown"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity": {
      "abstract": [
        {
          "text": "IBSS mode security types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWIBSSModeSecurity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWIBSSModeSecurity"
        }
      ],
      "role": "symbol",
      "title": "CWIBSSModeSecurity",
      "type": "topic",
      "url": "/documentation/corewlan/cwibssmodesecurity"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode": {
      "abstract": [
        {
          "text": "Wi-Fi interface operating modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWInterfaceMode"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWInterfaceMode"
        }
      ],
      "role": "symbol",
      "title": "CWInterfaceMode",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterfacemode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain": {
      "abstract": [
        {
          "text": "Keychain domain types that CoreWLAN keychain methods use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWKeychainDomain"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWKeychainDomain"
        }
      ],
      "role": "symbol",
      "title": "CWKeychainDomain",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaindomain"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode": {
      "abstract": [
        {
          "text": "CoreWLAN physical layer modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWPHYMode"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWPHYMode"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity": {
      "abstract": [
        {
          "text": "CoreWLAN security types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWSecurity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWSecurity"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/none",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/ssidDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/bssidDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/countryCodeDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkQualityDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/modeDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/scanCacheUpdated",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/unknown"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/btCoexStats"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CWEventType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/none",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/ssidDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/bssidDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/countryCodeDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkQualityDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/modeDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/scanCacheUpdated",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/unknown"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/btCoexStats"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CWEventType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/title",
          "value": "CWIBSSModeSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWIBSSModeSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWIBSSModeSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1none/title",
          "value": "CWEventTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1ssidDidChange/title",
          "value": "CWEventTypeSSIDDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1ssidDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeSSIDDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/title",
          "value": "CWKeychainDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWKeychainDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWKeychainDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1linkDidChange/title",
          "value": "CWEventTypeLinkDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1linkDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeLinkDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1powerDidChange/title",
          "value": "CWEventTypePowerDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1powerDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypePowerDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/title",
          "value": "CWEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1btCoexStats/title",
          "value": "CWEventTypeBtCoexStats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1btCoexStats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeBtCoexStats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1countryCodeDidChange/title",
          "value": "CWEventTypeCountryCodeDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1countryCodeDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeCountryCodeDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1bssidDidChange/title",
          "value": "CWEventTypeBSSIDDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1bssidDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeBSSIDDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1modeDidChange/title",
          "value": "CWEventTypeModeDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1modeDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeModeDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/title",
          "value": "CWCipherKeyFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWCipherKeyFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWCipherKeyFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/title",
          "value": "CWChannelBand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/title",
          "value": "CWSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1linkQualityDidChange/title",
          "value": "CWEventTypeLinkQualityDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1linkQualityDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeLinkQualityDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/title",
          "value": "CWPHYMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/title",
          "value": "CWChannelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/title",
          "value": "CWErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/title",
          "value": "CWInterfaceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterfaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterfaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1unknown/title",
          "value": "CWEventTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1scanCacheUpdated/title",
          "value": "CWEventTypeScanCacheUpdated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1scanCacheUpdated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeScanCacheUpdated"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cweventtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cweventtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
