{
  "abstract": [
    {
      "text": "Sets the network keychain password for the specified SSID.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetPassword"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CWKeychainSetPassword",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CWKeychainSetPassword"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CWKeychainSetPassword"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.9",
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CWKeychainSetPassword"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CWKeychainSetPassword"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDataRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDataRef",
              "text": "CFDataRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ssidData"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "password"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The network password.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "password"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An OSStatus error code which will indicate whether or not a failure occurred during execution. ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "errSecSuccess",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " indicates no error occurred.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentity": {
      "abstract": [
        {
          "text": "Finds and returns the identity stored for corresponding network with the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainCopyEAPIdentity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentity",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainCopyEAPIdentity",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaincopyeapidentity"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentityList(_:)": {
      "abstract": [
        {
          "text": "Finds and returns the available identities stored in the keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWKeychainCopyEAPIdentityList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentityList(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWKeychainCopyEAPIdentityList"
        }
      ],
      "role": "symbol",
      "title": "CWKeychainCopyEAPIdentityList(_:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaincopyeapidentitylist(_:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPUsernameAndPassword": {
      "abstract": [
        {
          "text": "Finds and returns the username and password stored for corresponding network with the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainCopyEAPUsernameAndPassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPUsernameAndPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainCopyEAPUsernameAndPassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaincopyeapusernameandpassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyPassword": {
      "abstract": [
        {
          "text": "Finds and returns the keychain password stored for the corresponding network with the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainCopyPassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainCopyPassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaincopypassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeleteEAPUsernameAndPassword": {
      "abstract": [
        {
          "text": "Deletes the keychain item containing the 802.1X username and password for the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainDeleteEAPUsernameAndPassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeleteEAPUsernameAndPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainDeleteEAPUsernameAndPassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaindeleteeapusernameandpassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeletePassword": {
      "abstract": [
        {
          "text": "Deletes the network password for the specified SSID from the default keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainDeletePassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeletePassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainDeletePassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaindeletepassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPIdentity": {
      "abstract": [
        {
          "text": "Associates an exisiting identity item to the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainSetEAPIdentity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPIdentity",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainSetEAPIdentity",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychainseteapidentity"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPUsernameAndPassword": {
      "abstract": [
        {
          "text": "Sets the keychain item containing the 802.1X username and password for the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainSetEAPUsernameAndPassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPUsernameAndPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainSetEAPUsernameAndPassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychainseteapusernameandpassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetPassword": {
      "abstract": [
        {
          "text": "Sets the network keychain password for the specified SSID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWKeychainSetPassword"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWKeychainSetPassword",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychainsetpassword"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWMergeNetworks(_:)": {
      "abstract": [
        {
          "text": "Merges the specified set of CWNetwork objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWMergeNetworks"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CWNetwork",
          "text": "CWNetwork"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CWNetwork",
          "text": "CWNetwork"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWMergeNetworks(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWMergeNetworks"
        }
      ],
      "role": "symbol",
      "title": "CWMergeNetworks(_:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwmergenetworks(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDataRef": {
      "abstract": [
        {
          "text": "A reference to an immutable CFData object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFData"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDataRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFData",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdata"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Utility-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentity",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPIdentityList(_:)",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyEAPUsernameAndPassword",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainCopyPassword",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeleteEAPUsernameAndPassword",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDeletePassword",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPIdentity",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainSetEAPUsernameAndPassword",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWMergeNetworks(_:)"
      ],
      "title": "Utility Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWMergeNetworks(_:)/title",
          "value": "CWMergeNetworks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWMergeNetworks(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWMergeNetworks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDataRef/title",
          "value": "CFDataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainCopyEAPIdentityList(_:)/title",
          "value": "CWKeychainCopyEAPIdentityList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainCopyEAPIdentityList(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWKeychainCopyEAPIdentityList"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwkeychainsetpassword"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
