{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use -[CWWiFiClient startMonitoringEventWithType:error:] with the CWEventTypeLinkQualityDidChange event type",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkQualityNotificationTransmitRateKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CWLinkQualityNotificationTransmitRateKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CWLinkQualityNotificationTransmitRateKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CWLinkQualityNotificationTransmitRateKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.10",
        "introducedAt": "10.6",
        "message": "Use -[CWWiFiClient startMonitoringEventWithType:error:] with the CWEventTypeLinkQualityDidChange event type",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CWLinkQualityNotificationTransmitRateKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CWLinkQualityNotificationTransmitRateKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "NSNumber containing the current transmit rate value for the WLAN interface. Found in the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "userInfo",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " dictionary for the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "CWLinkQualityChangedNotification",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWBSSIDDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWBSSIDDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWBSSIDDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWBSSIDDidChangeNotification",
      "type": "topic",
      "url": "/documentation/corewlan/cwbssiddidchangenotification"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWCountryCodeDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWCountryCodeDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWCountryCodeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWCountryCodeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/corewlan/cwcountrycodedidchangenotification"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErrorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CWErrorDomain",
      "type": "topic",
      "url": "/documentation/corewlan/cwerrordomain"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWLinkDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWLinkDidChangeNotification",
      "type": "topic",
      "url": "/documentation/corewlan/cwlinkdidchangenotification"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkQualityDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWLinkQualityDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkQualityDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWLinkQualityDidChangeNotification",
      "type": "topic",
      "url": "/documentation/corewlan/cwlinkqualitydidchangenotification"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkQualityNotificationRSSIKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWLinkQualityNotificationRSSIKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkQualityNotificationRSSIKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWLinkQualityNotificationRSSIKey"
        }
      ],
      "role": "symbol",
      "title": "CWLinkQualityNotificationRSSIKey",
      "type": "topic",
      "url": "/documentation/corewlan/cwlinkqualitynotificationrssikey"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkQualityNotificationTransmitRateKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWLinkQualityNotificationTransmitRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkQualityNotificationTransmitRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWLinkQualityNotificationTransmitRateKey"
        }
      ],
      "role": "symbol",
      "title": "CWLinkQualityNotificationTransmitRateKey",
      "type": "topic",
      "url": "/documentation/corewlan/cwlinkqualitynotificationtransmitratekey"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWModeDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWModeDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWModeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWModeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/corewlan/cwmodedidchangenotification"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPowerDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWPowerDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPowerDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWPowerDidChangeNotification",
      "type": "topic",
      "url": "/documentation/corewlan/cwpowerdidchangenotification"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSSIDDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWSSIDDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSSIDDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWSSIDDidChangeNotification",
      "type": "topic",
      "url": "/documentation/corewlan/cwssiddidchangenotification"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWScanCacheDidUpdateNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CWScanCacheDidUpdateNotification"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWScanCacheDidUpdateNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CWScanCacheDidUpdateNotification",
      "type": "topic",
      "url": "/documentation/corewlan/cwscancachedidupdatenotification"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErrorDomain",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkQualityNotificationRSSIKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.10",
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CWLinkQualityNotificationTransmitRateKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWLinkQualityNotificationTransmitRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWBSSIDDidChangeNotification",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWCountryCodeDidChangeNotification",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErrorDomain",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkDidChangeNotification",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkQualityDidChangeNotification",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWLinkQualityNotificationRSSIKey",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWModeDidChangeNotification",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPowerDidChangeNotification",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWScanCacheDidUpdateNotification",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSSIDDidChangeNotification"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CWLinkQualityNotificationTransmitRateKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use -[CWWiFiClient startMonitoringEventWithType:error:] with the CWEventTypeLinkQualityDidChange event type",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWLinkQualityNotificationRSSIKey/title",
          "value": "CWLinkQualityNotificationRSSIKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWLinkQualityNotificationRSSIKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWLinkQualityNotificationRSSIKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWLinkQualityNotificationTransmitRateKey/title",
          "value": "CWLinkQualityNotificationTransmitRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWLinkQualityNotificationTransmitRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWLinkQualityNotificationTransmitRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErrorDomain/title",
          "value": "CWErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwlinkqualitynotificationtransmitratekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwlinkqualitynotificationtransmitratekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
