{
  "abstract": [
    {
      "text": "Encapsulates an immutable network profile entry.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CWNetworkProfile",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CWNetworkProfile"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CWNetworkProfile"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CWNetworkProfile"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CWNetworkProfile"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannel": {
      "abstract": [
        {
          "text": "Encapsulates an IEEE 802.11 channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWChannel"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWChannel"
        }
      ],
      "role": "symbol",
      "title": "CWChannel",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannel"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWConfiguration": {
      "abstract": [
        {
          "text": "Encapsulates an immutable configuration for an AirPort WLAN interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWConfiguration"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CWConfiguration",
      "type": "topic",
      "url": "/documentation/corewlan/cwconfiguration"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface": {
      "abstract": [
        {
          "text": "Encapsulates an IEEE 802.11 interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWInterface"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWInterface"
        }
      ],
      "role": "symbol",
      "title": "CWInterface",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterface"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWMutableConfiguration": {
      "abstract": [
        {
          "text": "Encapsulates a mutable configuration for an AirPort WLAN interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWMutableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWMutableConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWMutableConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CWMutableConfiguration",
      "type": "topic",
      "url": "/documentation/corewlan/cwmutableconfiguration"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWMutableNetworkProfile": {
      "abstract": [
        {
          "text": "Encapsulates a mutable network profile entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWMutableNetworkProfile"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWMutableNetworkProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWMutableNetworkProfile"
        }
      ],
      "role": "symbol",
      "title": "CWMutableNetworkProfile",
      "type": "topic",
      "url": "/documentation/corewlan/cwmutablenetworkprofile"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork": {
      "abstract": [
        {
          "text": "Encapsulates an IEEE 802.11 network, providing read-only accessors to various properties of the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWNetwork"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWNetwork"
        }
      ],
      "role": "symbol",
      "title": "CWNetwork",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile": {
      "abstract": [
        {
          "text": "Encapsulates an immutable network profile entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWNetworkProfile"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWNetworkProfile"
        }
      ],
      "role": "symbol",
      "title": "CWNetworkProfile",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetworkprofile"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/init()": {
      "abstract": [
        {
          "text": "Creates and returns a CWNetworkProfile object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetworkprofile/init()"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/init(networkProfile:)": {
      "abstract": [
        {
          "text": "Creates and returns a CWNetworkProfile object initialized with the given CWNetworkProfile object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "networkProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CWNetworkProfile",
          "text": "CWNetworkProfile"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/init(networkProfile:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithNetworkProfile:"
        }
      ],
      "role": "symbol",
      "title": "init(networkProfile:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetworkprofile/init(networkprofile:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/isEqual(to:)": {
      "abstract": [
        {
          "text": "Determine CWNetworkProfile object equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEqual"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CWNetworkProfile",
          "text": "CWNetworkProfile"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/isEqual(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isEqualToNetworkProfile:"
        }
      ],
      "role": "symbol",
      "title": "isEqual(to:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetworkprofile/isequal(to:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/networkProfile": {
      "abstract": [
        {
          "text": "Convenience method for getting a CWNetworkProfile object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "networkProfile"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/networkProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkProfile"
        }
      ],
      "role": "symbol",
      "title": "networkProfile",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetworkprofile/networkprofile"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/networkProfileWithNetworkProfile:": {
      "abstract": [
        {
          "text": "Convenience method for getting a CWNetworkProfile object initialized with the given CWNetworkProfile object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "networkProfileWithNetworkProfile:"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/networkProfileWithNetworkProfile:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkProfileWithNetworkProfile:"
        }
      ],
      "role": "symbol",
      "title": "networkProfileWithNetworkProfile:",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetworkprofile/networkprofilewithnetworkprofile:"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/security": {
      "abstract": [
        {
          "text": "The security mode for the network profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "security"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CWSecurity",
          "text": "CWSecurity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/security",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "security"
        }
      ],
      "role": "symbol",
      "title": "security",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetworkprofile/security"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/ssid": {
      "abstract": [
        {
          "text": "The service set identifier (SSID) for the network profile, encoded as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ssid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/ssid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ssid"
        }
      ],
      "role": "symbol",
      "title": "ssid",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetworkprofile/ssid"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/ssidData": {
      "abstract": [
        {
          "text": "The service set identifier (SSID) for the network profile, returned as data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ssidData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/ssidData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ssidData"
        }
      ],
      "role": "symbol",
      "title": "ssidData",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetworkprofile/ssiddata"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient": {
      "abstract": [
        {
          "text": "A wrapper around the entire Wi-Fi subsystem that you use to access interfaces and set up event notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWWiFiClient"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWWiFiClient"
        }
      ],
      "role": "symbol",
      "title": "CWWiFiClient",
      "type": "topic",
      "url": "/documentation/corewlan/cwwificlient"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying": {
      "abstract": [
        {
          "text": "A protocol that mutable objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSMutableCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableCopying",
      "type": "topic",
      "url": "/documentation/foundation/nsmutablecopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWMutableNetworkProfile"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannel",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWConfiguration",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWMutableConfiguration",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWMutableNetworkProfile",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-a-network-profile",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/init()",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/init(networkProfile:)"
      ],
      "title": "Getting a network profile"
    },
    {
      "anchor": "Comparing-network-profiles",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/isEqual(to:)"
      ],
      "title": "Comparing network profiles"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/security",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/ssid",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/ssidData"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CWNetworkProfile"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWNetworkProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWNetworkProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-a-network-profile",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/init()",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/init(networkProfile:)",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/networkProfile",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/networkProfileWithNetworkProfile:"
              ],
              "title": "Getting a network profile"
            },
            {
              "anchor": "Comparing-network-profiles",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/isEqual(to:)"
              ],
              "title": "Comparing network profiles"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/security",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/ssid",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetworkProfile/ssidData"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWMutableNetworkProfile"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannel",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWConfiguration",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWMutableConfiguration",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWMutableNetworkProfile",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWWiFiClient"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CWNetworkProfile"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1init(networkProfile:)/title",
          "value": "initWithNetworkProfile:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1init(networkProfile:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithNetworkProfile:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWMutableNetworkProfile/title",
          "value": "CWMutableNetworkProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWMutableNetworkProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWMutableNetworkProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWMutableNetworkProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWMutableNetworkProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1ssid/title",
          "value": "ssid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1ssid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ssid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWMutableConfiguration/title",
          "value": "CWMutableConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWMutableConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWMutableConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWMutableConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWMutableConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannel/title",
          "value": "CWChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface/title",
          "value": "CWInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWWiFiClient/title",
          "value": "CWWiFiClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWWiFiClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWWiFiClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWWiFiClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWWiFiClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1ssidData/title",
          "value": "ssidData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1ssidData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ssidData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile/title",
          "value": "CWNetworkProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWNetworkProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWNetworkProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork/title",
          "value": "CWNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1security/title",
          "value": "security"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1security/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "security"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWConfiguration/title",
          "value": "CWConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1isEqual(to:)/title",
          "value": "isEqualToNetworkProfile:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetworkProfile~1isEqual(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isEqualToNetworkProfile:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwnetworkprofile"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwnetworkprofile"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
