{
  "abstract": [
    {
      "text": "CoreWLAN physical layer modes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CWPHYMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CWPHYMode"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CWPHYMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CWPHYMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand": {
      "abstract": [
        {
          "text": "CoreWLAN channel bands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWChannelBand"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWChannelBand"
        }
      ],
      "role": "symbol",
      "title": "CWChannelBand",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelband"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth": {
      "abstract": [
        {
          "text": "CoreWLAN channel widths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWChannelWidth"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWChannelWidth"
        }
      ],
      "role": "symbol",
      "title": "CWChannelWidth",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelwidth"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags": {
      "abstract": [
        {
          "text": "Cipher key flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWCipherKeyFlags"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWCipherKeyFlags"
        }
      ],
      "role": "symbol",
      "title": "CWCipherKeyFlags",
      "type": "topic",
      "url": "/documentation/corewlan/cwcipherkeyflags"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType": {
      "abstract": [
        {
          "text": "Wi-Fi event types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWEventType"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventType"
        }
      ],
      "role": "symbol",
      "title": "CWEventType",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity": {
      "abstract": [
        {
          "text": "IBSS mode security types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWIBSSModeSecurity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWIBSSModeSecurity"
        }
      ],
      "role": "symbol",
      "title": "CWIBSSModeSecurity",
      "type": "topic",
      "url": "/documentation/corewlan/cwibssmodesecurity"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode": {
      "abstract": [
        {
          "text": "Wi-Fi interface operating modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWInterfaceMode"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWInterfaceMode"
        }
      ],
      "role": "symbol",
      "title": "CWInterfaceMode",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterfacemode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain": {
      "abstract": [
        {
          "text": "Keychain domain types that CoreWLAN keychain methods use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWKeychainDomain"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWKeychainDomain"
        }
      ],
      "role": "symbol",
      "title": "CWKeychainDomain",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaindomain"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode": {
      "abstract": [
        {
          "text": "CoreWLAN physical layer modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWPHYMode"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWPHYMode"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/init(rawvalue:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11a": {
      "abstract": [
        {
          "text": "IEEE 802.11a PHY.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11a"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11a"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11a",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11a"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ac": {
      "abstract": [
        {
          "text": "IEEE 802.11ac PHY.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11ac"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11ac"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11ac",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11ac"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11ax"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11ax"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11ax",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11ax"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11b": {
      "abstract": [
        {
          "text": "IEEE 802.11b PHY.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11b"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11b"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11b",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11b"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11g": {
      "abstract": [
        {
          "text": "IEEE 802.11g PHY.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11g"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11g"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11g",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11g"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11n": {
      "abstract": [
        {
          "text": "IEEE 802.11n PHY.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11n"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11n"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11n",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11n"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/modeNone": {
      "abstract": [
        {
          "text": "No specified mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modeNone"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/modeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYModeNone"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.modeNone",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/modenone"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity": {
      "abstract": [
        {
          "text": "CoreWLAN security types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWSecurity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWSecurity"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/modeNone",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11a",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11b",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11g",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11n",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ac"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ax"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CWPHYMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/modeNone",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11a",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11b",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11g",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11n",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ac"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ax"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CWPHYMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/title",
          "value": "CWCipherKeyFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWCipherKeyFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWCipherKeyFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/title",
          "value": "CWIBSSModeSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWIBSSModeSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWIBSSModeSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/title",
          "value": "CWInterfaceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterfaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterfaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11ax/title",
          "value": "kCWPHYMode11ax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11ax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11ax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11g/title",
          "value": "kCWPHYMode11g"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11g"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11n/title",
          "value": "kCWPHYMode11n"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11n"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/title",
          "value": "CWEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/title",
          "value": "CWErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/title",
          "value": "CWKeychainDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWKeychainDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWKeychainDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1modeNone/title",
          "value": "kCWPHYModeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1modeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYModeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/title",
          "value": "CWChannelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/title",
          "value": "CWPHYMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11ac/title",
          "value": "kCWPHYMode11ac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11ac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11ac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/title",
          "value": "CWChannelBand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/title",
          "value": "CWSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11b/title",
          "value": "kCWPHYMode11b"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11b/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11b"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11a/title",
          "value": "kCWPHYMode11a"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11a/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11a"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwphymode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwphymode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
