{
  "abstract": [
    {
      "text": "CoreWLAN security types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CWSecurity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CWSecurity"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CWSecurity"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CWSecurity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand": {
      "abstract": [
        {
          "text": "CoreWLAN channel bands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWChannelBand"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWChannelBand"
        }
      ],
      "role": "symbol",
      "title": "CWChannelBand",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelband"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth": {
      "abstract": [
        {
          "text": "CoreWLAN channel widths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWChannelWidth"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWChannelWidth"
        }
      ],
      "role": "symbol",
      "title": "CWChannelWidth",
      "type": "topic",
      "url": "/documentation/corewlan/cwchannelwidth"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags": {
      "abstract": [
        {
          "text": "Cipher key flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWCipherKeyFlags"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWCipherKeyFlags"
        }
      ],
      "role": "symbol",
      "title": "CWCipherKeyFlags",
      "type": "topic",
      "url": "/documentation/corewlan/cwcipherkeyflags"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType": {
      "abstract": [
        {
          "text": "Wi-Fi event types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWEventType"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventType"
        }
      ],
      "role": "symbol",
      "title": "CWEventType",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity": {
      "abstract": [
        {
          "text": "IBSS mode security types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWIBSSModeSecurity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWIBSSModeSecurity"
        }
      ],
      "role": "symbol",
      "title": "CWIBSSModeSecurity",
      "type": "topic",
      "url": "/documentation/corewlan/cwibssmodesecurity"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode": {
      "abstract": [
        {
          "text": "Wi-Fi interface operating modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWInterfaceMode"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWInterfaceMode"
        }
      ],
      "role": "symbol",
      "title": "CWInterfaceMode",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterfacemode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain": {
      "abstract": [
        {
          "text": "Keychain domain types that CoreWLAN keychain methods use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWKeychainDomain"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWKeychainDomain"
        }
      ],
      "role": "symbol",
      "title": "CWKeychainDomain",
      "type": "topic",
      "url": "/documentation/corewlan/cwkeychaindomain"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode": {
      "abstract": [
        {
          "text": "CoreWLAN physical layer modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWPHYMode"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWPHYMode"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity": {
      "abstract": [
        {
          "text": "CoreWLAN security types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWSecurity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWSecurity"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/OWE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OWE"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/OWE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityOWE"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.OWE",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/owe"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/WEP": {
      "abstract": [
        {
          "text": "WEP security.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WEP"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/WEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWEP"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.WEP",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wep"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/dynamicWEP": {
      "abstract": [
        {
          "text": "Dynamic WEP security.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dynamicWEP"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/dynamicWEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityDynamicWEP"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.dynamicWEP",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/dynamicwep"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/enterprise": {
      "abstract": [
        {
          "text": "Enterprise authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enterprise"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/enterprise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityEnterprise"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.enterprise",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/enterprise"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/init(rawvalue:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/none": {
      "abstract": [
        {
          "text": "Open System authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityNone"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.none",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/none"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/oweTransition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oweTransition"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/oweTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityOWETransition"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.oweTransition",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/owetransition"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/personal": {
      "abstract": [
        {
          "text": "Personal authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "personal"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/personal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityPersonal"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.personal",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/personal"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/unknown": {
      "abstract": [
        {
          "text": "Unknown security type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityUnknown"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.unknown",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/unknown"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Enterprise": {
      "abstract": [
        {
          "text": "WPA2 Enterprise authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpa2Enterprise"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Enterprise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPA2Enterprise"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpa2Enterprise",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpa2enterprise"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Personal": {
      "abstract": [
        {
          "text": "WPA2 Personal authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpa2Personal"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Personal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPA2Personal"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpa2Personal",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpa2personal"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Enterprise": {
      "abstract": [
        {
          "text": "WPA3 Enterprise authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpa3Enterprise"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Enterprise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPA3Enterprise"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpa3Enterprise",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpa3enterprise"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Personal": {
      "abstract": [
        {
          "text": "WPA3 Personal authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpa3Personal"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Personal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPA3Personal"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpa3Personal",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpa3personal"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Transition": {
      "abstract": [
        {
          "text": "WPA3 Transition (WPA3/WPA2 Personal) authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpa3Transition"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Transition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPA3Transition"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpa3Transition",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpa3transition"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterprise": {
      "abstract": [
        {
          "text": "WPA Enterprise authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpaEnterprise"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterprise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPAEnterprise"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpaEnterprise",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpaenterprise"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterpriseMixed": {
      "abstract": [
        {
          "text": "WPA/WPA2 Enterprise authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpaEnterpriseMixed"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterpriseMixed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPAEnterpriseMixed"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpaEnterpriseMixed",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpaenterprisemixed"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonal": {
      "abstract": [
        {
          "text": "WPA Personal authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpaPersonal"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPAPersonal"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpaPersonal",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpapersonal"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonalMixed": {
      "abstract": [
        {
          "text": "WPA/WPA2 Personal authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpaPersonalMixed"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonalMixed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPAPersonalMixed"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpaPersonalMixed",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpapersonalmixed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/none",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/WEP",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonal",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonalMixed",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Personal",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/personal",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/dynamicWEP",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterprise",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterpriseMixed",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Enterprise",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/enterprise",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Personal",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Enterprise",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Transition",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/unknown"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/OWE",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/oweTransition"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CWSecurity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/none",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/WEP",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonal",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonalMixed",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Personal",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/personal",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/dynamicWEP",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterprise",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterpriseMixed",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Enterprise",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/enterprise",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Personal",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Enterprise",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Transition",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/unknown"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/OWE",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/oweTransition"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelBand",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWChannelWidth",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWCipherKeyFlags",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWIBSSModeSecurity",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWKeychainDomain",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CWSecurity"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaEnterprise/title",
          "value": "kCWSecurityWPAEnterprise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaEnterprise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPAEnterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1none/title",
          "value": "kCWSecurityNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/title",
          "value": "CWEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1dynamicWEP/title",
          "value": "kCWSecurityDynamicWEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1dynamicWEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityDynamicWEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/title",
          "value": "CWPHYMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/title",
          "value": "CWInterfaceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterfaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterfaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/title",
          "value": "CWErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1OWE/title",
          "value": "kCWSecurityOWE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1OWE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityOWE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/title",
          "value": "CWKeychainDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWKeychainDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWKeychainDomain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWKeychainDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Transition/title",
          "value": "kCWSecurityWPA3Transition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Transition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPA3Transition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/title",
          "value": "CWIBSSModeSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWIBSSModeSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWIBSSModeSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWIBSSModeSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaEnterpriseMixed/title",
          "value": "kCWSecurityWPAEnterpriseMixed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaEnterpriseMixed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPAEnterpriseMixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/title",
          "value": "CWChannelBand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelBand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1enterprise/title",
          "value": "kCWSecurityEnterprise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1enterprise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityEnterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1unknown/title",
          "value": "kCWSecurityUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/title",
          "value": "CWCipherKeyFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWCipherKeyFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWCipherKeyFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWCipherKeyFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1personal/title",
          "value": "kCWSecurityPersonal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1personal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityPersonal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Personal/title",
          "value": "kCWSecurityWPA3Personal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Personal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPA3Personal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa2Enterprise/title",
          "value": "kCWSecurityWPA2Enterprise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa2Enterprise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPA2Enterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Enterprise/title",
          "value": "kCWSecurityWPA3Enterprise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Enterprise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPA3Enterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1oweTransition/title",
          "value": "kCWSecurityOWETransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1oweTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityOWETransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/title",
          "value": "CWSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1WEP/title",
          "value": "kCWSecurityWEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1WEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaPersonalMixed/title",
          "value": "kCWSecurityWPAPersonalMixed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaPersonalMixed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPAPersonalMixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/title",
          "value": "CWChannelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWChannelWidth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWChannelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaPersonal/title",
          "value": "kCWSecurityWPAPersonal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaPersonal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPAPersonal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa2Personal/title",
          "value": "kCWSecurityWPA2Personal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa2Personal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPA2Personal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwsecurity"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwsecurity"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
