{
  "abstract": [
    {
      "text": "The input data that is passed to the first action in the workflow.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator",
        "doc://com.apple.automator/documentation/Automator/AMWorkflow"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMWorkflow/input"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AMWorkflow(py)input",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "input"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "input"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "input"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "input"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The input for the first action in the workflow. Should be a data type the action can use, or a type that can be converted to one the action can use. Use ",
              "type": "text"
            },
            {
              "code": "setInput:",
              "type": "codeVoice"
            },
            {
              "text": " to set the input data for the workflow.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow": {
      "abstract": [
        {
          "text": "An object that lets you use an Automator workflow in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflow"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflow"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflow",
      "type": "topic",
      "url": "/documentation/automator/amworkflow"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/input": {
      "abstract": [
        {
          "text": "The input data that is passed to the first action in the workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/input",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "input"
        }
      ],
      "role": "symbol",
      "title": "input",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/input"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/output": {
      "abstract": [
        {
          "text": "The output data that is provided by the last action in the workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/output",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "output"
        }
      ],
      "role": "symbol",
      "title": "output",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/output"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-the-Workflows-Input-and-Output",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/output"
      ],
      "title": "Working with the Workflow’s Input and Output"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "input"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.automator/documentation/Automator",
                "doc://com.apple.automator/documentation/Automator/AMWorkflow"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-the-Workflows-Input-and-Output",
              "generated": true,
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/output"
              ],
              "title": "Working with the Workflow’s Input and Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "input"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1output/title",
          "value": "output"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1output/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/title",
          "value": "AMWorkflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1input/title",
          "value": "input"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1input/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "input"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amworkflow/input"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator/amworkflow/input"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
