{
  "abstract": [
    {
      "text": "Error codes for StoreKit errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SKError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.storekit/documentation/StoreKit/handling-errors"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError": {
      "abstract": [
        {
          "text": "StoreKit error descriptions, codes, and domains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKError"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKError"
        }
      ],
      "role": "symbol",
      "title": "SKError",
      "type": "topic",
      "url": "/documentation/storekit/skerror"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code": {
      "abstract": [
        {
          "text": "Error codes for StoreKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/clientInvalid": {
      "abstract": [
        {
          "text": "Error code indicating that the client is not allowed to perform the attempted action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientInvalid"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/clientInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorClientInvalid"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.clientInvalid",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/clientinvalid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServiceNetworkConnectionFailed": {
      "abstract": [
        {
          "text": "Error code indicating that the device could not connect to the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServiceNetworkConnectionFailed"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServiceNetworkConnectionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorCloudServiceNetworkConnectionFailed"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.cloudServiceNetworkConnectionFailed",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/cloudservicenetworkconnectionfailed"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServicePermissionDenied": {
      "abstract": [
        {
          "text": "Error code indicating that the user has not allowed access to Cloud service information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServicePermissionDenied"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServicePermissionDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorCloudServicePermissionDenied"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.cloudServicePermissionDenied",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/cloudservicepermissiondenied"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServiceRevoked": {
      "abstract": [
        {
          "text": "Error code indicating that the user has revoked permission to use this cloud service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServiceRevoked"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServiceRevoked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorCloudServiceRevoked"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.cloudServiceRevoked",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/cloudservicerevoked"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/ineligibleForOffer": {
      "abstract": [
        {
          "text": "An error code that indicates the user is ineligible for the subscription offer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ineligibleForOffer"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/ineligibleForOffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorIneligibleForOffer"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.ineligibleForOffer",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/ineligibleforoffer"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/init(rawvalue:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidOfferIdentifier": {
      "abstract": [
        {
          "text": "Error code indicating that the offer identifier is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOfferIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidOfferIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorInvalidOfferIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.invalidOfferIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/invalidofferidentifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidOfferPrice": {
      "abstract": [
        {
          "text": "Error code indicating that the price you specified in App Store Connect is no longer valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOfferPrice"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidOfferPrice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorInvalidOfferPrice"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.invalidOfferPrice",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/invalidofferprice"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidSignature": {
      "abstract": [
        {
          "text": "Error code indicating that the signature in a payment discount isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSignature"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorInvalidSignature"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.invalidSignature",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/invalidsignature"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/missingOfferParams": {
      "abstract": [
        {
          "text": "Error code indicating that parameters are missing in a payment discount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingOfferParams"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/missingOfferParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorMissingOfferParams"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.missingOfferParams",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/missingofferparams"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayCancelled": {
      "abstract": [
        {
          "text": "An error code that indicates the cancellation of an overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlayCancelled"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorOverlayCancelled"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.overlayCancelled",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/overlaycancelled"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayInvalidConfiguration": {
      "abstract": [
        {
          "text": "An error code that indicates the overlay’s configuration is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlayInvalidConfiguration"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayInvalidConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorOverlayInvalidConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.overlayInvalidConfiguration",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/overlayinvalidconfiguration"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayPresentedInBackgroundScene": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlayPresentedInBackgroundScene"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayPresentedInBackgroundScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorOverlayPresentedInBackgroundScene"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.overlayPresentedInBackgroundScene",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/overlaypresentedinbackgroundscene"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlayTimeout"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorOverlayTimeout"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.overlayTimeout",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/overlaytimeout"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentCancelled": {
      "abstract": [
        {
          "text": "Error code indicating that the user canceled a payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentCancelled"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorPaymentCancelled"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.paymentCancelled",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/paymentcancelled"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentInvalid": {
      "abstract": [
        {
          "text": "Error code indicating that one of the payment parameters wasn’t recognized by the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentInvalid"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorPaymentInvalid"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.paymentInvalid",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/paymentinvalid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentNotAllowed": {
      "abstract": [
        {
          "text": "Error code indicating that the user is not allowed to authorize payments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorPaymentNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.paymentNotAllowed",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/paymentnotallowed"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/privacyAcknowledgementRequired": {
      "abstract": [
        {
          "text": "Error code indicating that the user has not yet acknowledged Apple’s privacy policy for Apple Music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "privacyAcknowledgementRequired"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/privacyAcknowledgementRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorPrivacyAcknowledgementRequired"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.privacyAcknowledgementRequired",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/privacyacknowledgementrequired"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/storeProductNotAvailable": {
      "abstract": [
        {
          "text": "Error code indicating that the requested product is not available in the store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeProductNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/storeProductNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorStoreProductNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.storeProductNotAvailable",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/storeproductnotavailable"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unauthorizedRequestData": {
      "abstract": [
        {
          "text": "Error code indicating that the app is attempting to use a property for which it does not have the required entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unauthorizedRequestData"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unauthorizedRequestData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorUnauthorizedRequestData"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.unauthorizedRequestData",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/unauthorizedrequestdata"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unknown": {
      "abstract": [
        {
          "text": "Error code indicating that an unknown or unexpected error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.unknown",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/unknown"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unsupportedPlatform": {
      "abstract": [
        {
          "text": "An error code that indicates the current platform doesn’t support overlays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedPlatform"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unsupportedPlatform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorUnsupportedPlatform"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code.unsupportedPlatform",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code/unsupportedplatform"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain": {
      "abstract": [
        {
          "text": "The error domain name for StoreKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SKErrorDomain",
      "type": "topic",
      "url": "/documentation/storekit/skerrordomain"
    },
    "doc://com.apple.storekit/documentation/StoreKit/handling-errors": {
      "abstract": [
        {
          "text": "Determine the underlying cause of errors that result from StoreKit requests.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/handling-errors",
      "kind": "article",
      "role": "article",
      "title": "Handling errors",
      "type": "topic",
      "url": "/documentation/storekit/handling-errors"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/handling-errors",
        "doc://com.apple.storekit/documentation/StoreKit/SKError",
        "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unknown",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/clientInvalid",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentCancelled",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentInvalid",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentNotAllowed",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/storeProductNotAvailable",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServicePermissionDenied",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServiceNetworkConnectionFailed",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServiceRevoked",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/privacyAcknowledgementRequired",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unauthorizedRequestData",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidOfferIdentifier",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidOfferPrice",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidSignature",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/missingOfferParams",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/ineligibleForOffer",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayCancelled",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayInvalidConfiguration",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayPresentedInBackgroundScene",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayTimeout",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unsupportedPlatform"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unknown",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/clientInvalid",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentCancelled",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentInvalid",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/paymentNotAllowed",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/storeProductNotAvailable",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServicePermissionDenied",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServiceNetworkConnectionFailed",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/cloudServiceRevoked",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/privacyAcknowledgementRequired",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unauthorizedRequestData",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidOfferIdentifier",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidOfferPrice",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/invalidSignature",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/missingOfferParams",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/ineligibleForOffer",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayCancelled",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayInvalidConfiguration",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayPresentedInBackgroundScene",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/overlayTimeout",
                "doc://com.apple.storekit/documentation/StoreKit/SKError/Code/unsupportedPlatform"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/handling-errors",
                "doc://com.apple.storekit/documentation/StoreKit/SKErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1paymentInvalid/title",
          "value": "SKErrorPaymentInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1paymentInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorPaymentInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKErrorDomain/title",
          "value": "SKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code/title",
          "value": "SKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1paymentNotAllowed/title",
          "value": "SKErrorPaymentNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1paymentNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorPaymentNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1missingOfferParams/title",
          "value": "SKErrorMissingOfferParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1missingOfferParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorMissingOfferParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1invalidOfferIdentifier/title",
          "value": "SKErrorInvalidOfferIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1invalidOfferIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorInvalidOfferIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1unknown/title",
          "value": "SKErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1cloudServicePermissionDenied/title",
          "value": "SKErrorCloudServicePermissionDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1cloudServicePermissionDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCloudServicePermissionDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1cloudServiceRevoked/title",
          "value": "SKErrorCloudServiceRevoked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1cloudServiceRevoked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCloudServiceRevoked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1clientInvalid/title",
          "value": "SKErrorClientInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1clientInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorClientInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1overlayPresentedInBackgroundScene/title",
          "value": "SKErrorOverlayPresentedInBackgroundScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1overlayPresentedInBackgroundScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorOverlayPresentedInBackgroundScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1privacyAcknowledgementRequired/title",
          "value": "SKErrorPrivacyAcknowledgementRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1privacyAcknowledgementRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorPrivacyAcknowledgementRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1cloudServiceNetworkConnectionFailed/title",
          "value": "SKErrorCloudServiceNetworkConnectionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1cloudServiceNetworkConnectionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCloudServiceNetworkConnectionFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1invalidOfferPrice/title",
          "value": "SKErrorInvalidOfferPrice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1invalidOfferPrice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorInvalidOfferPrice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1overlayTimeout/title",
          "value": "SKErrorOverlayTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1overlayTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorOverlayTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1unsupportedPlatform/title",
          "value": "SKErrorUnsupportedPlatform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1unsupportedPlatform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorUnsupportedPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1invalidSignature/title",
          "value": "SKErrorInvalidSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1invalidSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorInvalidSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1overlayCancelled/title",
          "value": "SKErrorOverlayCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1overlayCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorOverlayCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1storeProductNotAvailable/title",
          "value": "SKErrorStoreProductNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1storeProductNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorStoreProductNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1unauthorizedRequestData/title",
          "value": "SKErrorUnauthorizedRequestData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1unauthorizedRequestData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorUnauthorizedRequestData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1ineligibleForOffer/title",
          "value": "SKErrorIneligibleForOffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1ineligibleForOffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorIneligibleForOffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1paymentCancelled/title",
          "value": "SKErrorPaymentCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1paymentCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorPaymentCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1overlayInvalidConfiguration/title",
          "value": "SKErrorOverlayInvalidConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code~1overlayInvalidConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorOverlayInvalidConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
