{
  "abstract": [
    {
      "text": "Error code indicating that the app is attempting to use a property for which it does not have the required entitlement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKError/unauthorizedRequestData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11SKErrorCodeLeV23unauthorizedRequestDataSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unauthorizedRequestData"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11SKErrorCodeLeV",
        "text": "SKError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SKErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "unauthorizedRequestData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unauthorizedRequestData"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11SKErrorCodeLeV",
              "text": "SKError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SKErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPayment/requestData",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", an app must have a required entitlement.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError": {
      "abstract": [
        {
          "text": "StoreKit error descriptions, codes, and domains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKError"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKError"
        }
      ],
      "role": "symbol",
      "title": "SKError",
      "type": "topic",
      "url": "/documentation/storekit/skerror"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/Code": {
      "abstract": [
        {
          "text": "Error codes for StoreKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKError.Code",
      "type": "topic",
      "url": "/documentation/storekit/skerror/code"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/clientInvalid": {
      "abstract": [
        {
          "text": "Error code indicating that the client is not allowed to perform the attempted action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/clientInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientInvalid",
      "type": "topic",
      "url": "/documentation/storekit/skerror/clientinvalid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceNetworkConnectionFailed": {
      "abstract": [
        {
          "text": "Error code indicating that the device could not connect to the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServiceNetworkConnectionFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceNetworkConnectionFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "cloudServiceNetworkConnectionFailed",
      "type": "topic",
      "url": "/documentation/storekit/skerror/cloudservicenetworkconnectionfailed"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServicePermissionDenied": {
      "abstract": [
        {
          "text": "Error code indicating that the user has not allowed access to Cloud service information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServicePermissionDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServicePermissionDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "cloudServicePermissionDenied",
      "type": "topic",
      "url": "/documentation/storekit/skerror/cloudservicepermissiondenied"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceRevoked": {
      "abstract": [
        {
          "text": "Error code indicating that the user has revoked permission to use this cloud service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServiceRevoked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceRevoked",
      "kind": "symbol",
      "role": "symbol",
      "title": "cloudServiceRevoked",
      "type": "topic",
      "url": "/documentation/storekit/skerror/cloudservicerevoked"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferIdentifier": {
      "abstract": [
        {
          "text": "Error code indicating that the offer identifier cannot be found or is not active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOfferIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidOfferIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skerror/invalidofferidentifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferPrice": {
      "abstract": [
        {
          "text": "Error code indicating that the price you specified in App Store Connect is no longer valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOfferPrice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferPrice",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidOfferPrice",
      "type": "topic",
      "url": "/documentation/storekit/skerror/invalidofferprice"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidSignature": {
      "abstract": [
        {
          "text": "Error code indicating that the signature in a payment discount is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidSignature",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidSignature",
      "type": "topic",
      "url": "/documentation/storekit/skerror/invalidsignature"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/missingOfferParams": {
      "abstract": [
        {
          "text": "Error code indicating that parameters are missing in a payment discount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingOfferParams"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/missingOfferParams",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingOfferParams",
      "type": "topic",
      "url": "/documentation/storekit/skerror/missingofferparams"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentCancelled": {
      "abstract": [
        {
          "text": "Error code indicating that the user canceled a payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "paymentCancelled",
      "type": "topic",
      "url": "/documentation/storekit/skerror/paymentcancelled"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentInvalid": {
      "abstract": [
        {
          "text": "Error code indicating that one of the payment parameters was not recognized by the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "paymentInvalid",
      "type": "topic",
      "url": "/documentation/storekit/skerror/paymentinvalid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentNotAllowed": {
      "abstract": [
        {
          "text": "Error code indicating that the user is not allowed to authorize payments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentNotAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "paymentNotAllowed",
      "type": "topic",
      "url": "/documentation/storekit/skerror/paymentnotallowed"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/privacyAcknowledgementRequired": {
      "abstract": [
        {
          "text": "Error code indicating that the user has not yet acknowledged Apple’s privacy policy for Apple Music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "privacyAcknowledgementRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/privacyAcknowledgementRequired",
      "kind": "symbol",
      "role": "symbol",
      "title": "privacyAcknowledgementRequired",
      "type": "topic",
      "url": "/documentation/storekit/skerror/privacyacknowledgementrequired"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/storeProductNotAvailable": {
      "abstract": [
        {
          "text": "Error code indicating that the requested product is not available in the store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeProductNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/storeProductNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "storeProductNotAvailable",
      "type": "topic",
      "url": "/documentation/storekit/skerror/storeproductnotavailable"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/unauthorizedRequestData": {
      "abstract": [
        {
          "text": "Error code indicating that the app is attempting to use a property for which it does not have the required entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unauthorizedRequestData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/unauthorizedRequestData",
      "kind": "symbol",
      "role": "symbol",
      "title": "unauthorizedRequestData",
      "type": "topic",
      "url": "/documentation/storekit/skerror/unauthorizedrequestdata"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKError/unknown": {
      "abstract": [
        {
          "text": "Error code indicating that an unknown or unexpected error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11SKErrorCodeLeV",
          "text": "SKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/storekit/skerror/unknown"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPayment/requestData": {
      "abstract": [
        {
          "text": "Reserved for future use.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPayment/requestData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestData"
        }
      ],
      "role": "symbol",
      "title": "requestData",
      "type": "topic",
      "url": "/documentation/storekit/skpayment/requestdata"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKError/Code",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/unknown",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/clientInvalid",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentCancelled",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentInvalid",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/paymentNotAllowed",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/storeProductNotAvailable",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServicePermissionDenied",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceNetworkConnectionFailed",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/cloudServiceRevoked",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/privacyAcknowledgementRequired",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferIdentifier",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidOfferPrice",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/invalidSignature",
        "doc://com.apple.storekit/documentation/StoreKit/SKError/missingOfferParams"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code/title",
          "value": "SKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPayment~1requestData/title",
          "value": "requestData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPayment~1requestData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skerror/unauthorizedrequestdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
