{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "EndpointSecurity Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Constants",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-constants"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Enumerations",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-enumerations"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Functions",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-functions"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Structures",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-structures"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_cdhash_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_cdhash_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_cdhash_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_cdhash_t"
        }
      ],
      "role": "symbol",
      "title": "es_cdhash_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_cdhash_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_graphical_session_id_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_graphical_session_id_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_graphical_session_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_graphical_session_id_t"
        }
      ],
      "role": "symbol",
      "title": "es_graphical_session_id_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_graphical_session_id_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sha256_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_sha256_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sha256_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_sha256_t"
        }
      ],
      "role": "symbol",
      "title": "es_sha256_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_sha256_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_cdhash_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_graphical_session_id_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sha256_t"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_cdhash_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_graphical_session_id_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sha256_t"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_sha256_t/title",
          "value": "es_sha256_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_sha256_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_sha256_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_sha256_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_sha256_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_graphical_session_id_t/title",
          "value": "es_graphical_session_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_graphical_session_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_graphical_session_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_graphical_session_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_graphical_session_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_cdhash_t/title",
          "value": "es_cdhash_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_cdhash_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_cdhash_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_cdhash_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_cdhash_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/endpointsecurity-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/endpointsecurity-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
