{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "EndpointSecurity Functions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Constants",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-constants"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Data Types",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-data-types"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Enumerations",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-enumerations"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Structures",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-structures"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_invert_muting(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_invert_muting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_mute_inversion_type_t",
          "text": "es_mute_inversion_type_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_invert_muting(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_invert_muting"
        }
      ],
      "role": "symbol",
      "title": "es_invert_muting(_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_invert_muting(_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muting_inverted(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_muting_inverted"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_mute_inversion_type_t",
          "text": "es_mute_inversion_type_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_mute_inverted_return_t",
          "text": "es_mute_inverted_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muting_inverted(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_muting_inverted"
        }
      ],
      "role": "symbol",
      "title": "es_muting_inverted(_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muting_inverted(_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_unmute_all_target_paths(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_unmute_all_target_paths"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_unmute_all_target_paths(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_unmute_all_target_paths"
        }
      ],
      "role": "symbol",
      "title": "es_unmute_all_target_paths(_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_unmute_all_target_paths(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_invert_muting(_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muting_inverted(_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_unmute_all_target_paths(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_invert_muting(_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muting_inverted(_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_unmute_all_target_paths(_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_invert_muting(_:_:)/title",
          "value": "es_invert_muting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_invert_muting(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_invert_muting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muting_inverted(_:_:)/title",
          "value": "es_muting_inverted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muting_inverted(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muting_inverted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_unmute_all_target_paths(_:)/title",
          "value": "es_unmute_all_target_paths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_unmute_all_target_paths(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_unmute_all_target_paths"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/endpointsecurity-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/endpointsecurity-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
