{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "EndpointSecurity Structures"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Constants",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-constants"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Data Types",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-data-types"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Enumerations",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-enumerations"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Functions",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-functions"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_authorization_result_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_authorization_result_t"
        }
      ],
      "role": "symbol",
      "title": "es_authorization_result_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authorization_result_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_btm_launch_item_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_btm_launch_item_t"
        }
      ],
      "role": "symbol",
      "title": "es_btm_launch_item_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_btm_launch_item_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_auto_unlock_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_auto_unlock_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_auto_unlock_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_auto_unlock_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_od_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_od_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_od_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_od_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_token_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_token_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_token_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_touchid_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_touchid_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_touchid_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_touchid_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authorization_judgement_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authorization_judgement_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authorization_judgement_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authorization_judgement_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authorization_petition_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authorization_petition_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authorization_petition_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authorization_petition_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_add_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_add_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_btm_launch_item_add_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_btm_launch_item_add_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_remove_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_remove_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_btm_launch_item_remove_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_btm_launch_item_remove_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_gatekeeper_user_override_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_gatekeeper_user_override_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_gatekeeper_user_override_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_gatekeeper_user_override_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_login_login_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_login_login_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_login_login_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_login_login_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_login_logout_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_login_logout_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_login_logout_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_login_logout_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_lw_session_lock_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_lw_session_lock_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_lw_session_lock_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_lw_session_lock_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_login_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_lw_session_login_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_login_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_lw_session_login_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_lw_session_login_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_lw_session_login_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_logout_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_lw_session_logout_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_logout_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_lw_session_logout_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_lw_session_logout_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_lw_session_logout_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_unlock_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_lw_session_unlock_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_unlock_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_lw_session_unlock_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_lw_session_unlock_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_lw_session_unlock_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_set_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_attribute_set_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_set_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_attribute_set_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_attribute_set_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_set_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_add_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_attribute_value_add_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_add_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_attribute_value_add_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_attribute_value_add_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_add_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_attribute_value_remove_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_attribute_value_remove_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_attribute_value_remove_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_create_group_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_create_group_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_create_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_create_group_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_create_group_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_create_group_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_create_user_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_create_user_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_create_user_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_create_user_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_create_user_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_create_user_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_delete_group_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_delete_group_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_delete_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_delete_group_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_delete_group_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_delete_group_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_delete_user_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_delete_user_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_delete_user_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_delete_user_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_delete_user_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_delete_user_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_disable_user_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_disable_user_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_disable_user_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_disable_user_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_disable_user_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_disable_user_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_enable_user_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_enable_user_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_enable_user_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_enable_user_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_enable_user_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_enable_user_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_add_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_group_add_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_add_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_group_add_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_group_add_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_group_add_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_remove_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_group_remove_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_remove_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_group_remove_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_group_remove_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_group_remove_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_set_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_group_set_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_set_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_group_set_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_group_set_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_group_set_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_modify_password_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_modify_password_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_modify_password_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_modify_password_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_modify_password_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_modify_password_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_openssh_login_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_openssh_login_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_openssh_login_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_openssh_login_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_openssh_login_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_openssh_login_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_openssh_logout_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_openssh_logout_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_openssh_logout_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_openssh_logout_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_openssh_logout_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_openssh_logout_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_profile_add_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_profile_add_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_profile_add_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_profile_add_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_profile_add_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_profile_add_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_profile_remove_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_profile_remove_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_profile_remove_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_profile_remove_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_profile_remove_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_profile_remove_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_screensharing_attach_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_screensharing_attach_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_screensharing_attach_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_screensharing_attach_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_screensharing_attach_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_screensharing_attach_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_screensharing_detach_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_screensharing_detach_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_screensharing_detach_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_screensharing_detach_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_screensharing_detach_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_screensharing_detach_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_su_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_su_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_su_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_su_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_su_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_su_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_sudo_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_sudo_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_sudo_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xp_malware_detected_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_xp_malware_detected_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xp_malware_detected_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_xp_malware_detected_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_xp_malware_detected_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_xp_malware_detected_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xp_malware_remediated_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_xp_malware_remediated_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xp_malware_remediated_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_xp_malware_remediated_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_xp_malware_remediated_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_xp_malware_remediated_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xpc_connect_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_xpc_connect_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xpc_connect_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_xpc_connect_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_xpc_connect_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_xpc_connect_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_id_array_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_od_member_id_array_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_id_array_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_od_member_id_array_t"
        }
      ],
      "role": "symbol",
      "title": "es_od_member_id_array_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_od_member_id_array_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_id_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_od_member_id_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_od_member_id_t"
        }
      ],
      "role": "symbol",
      "title": "es_od_member_id_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_od_member_id_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_profile_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_profile_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_profile_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_profile_t"
        }
      ],
      "role": "symbol",
      "title": "es_profile_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_profile_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_signed_file_info_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_signed_file_info_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_signed_file_info_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_signed_file_info_t"
        }
      ],
      "role": "symbol",
      "title": "es_signed_file_info_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_signed_file_info_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sudo_reject_info_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_sudo_reject_info_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sudo_reject_info_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_sudo_reject_info_t"
        }
      ],
      "role": "symbol",
      "title": "es_sudo_reject_info_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_sudo_reject_info_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_login_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_logout_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_unlock_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_set_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_add_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_create_group_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_create_user_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_delete_group_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_delete_user_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_disable_user_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_enable_user_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_add_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_remove_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_set_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_modify_password_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_openssh_login_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_openssh_logout_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_profile_add_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_profile_remove_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_screensharing_attach_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_screensharing_detach_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_su_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xp_malware_detected_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xp_malware_remediated_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xpc_connect_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_id_array_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_id_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_profile_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_signed_file_info_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sudo_reject_info_t"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_login_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_logout_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_unlock_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_set_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_add_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_create_group_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_create_user_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_delete_group_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_delete_user_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_disable_user_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_enable_user_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_add_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_remove_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_group_set_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_modify_password_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_openssh_login_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_openssh_logout_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_profile_add_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_profile_remove_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_screensharing_attach_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_screensharing_detach_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_su_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xp_malware_detected_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xp_malware_remediated_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_xpc_connect_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_id_array_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_id_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_profile_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_signed_file_info_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sudo_reject_info_t"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_profile_t/title",
          "value": "es_profile_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_profile_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_profile_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_profile_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_profile_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_logout_t/title",
          "value": "es_event_lw_session_logout_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_logout_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_logout_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_logout_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_logout_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_login_t/title",
          "value": "es_event_login_login_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_login_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_login_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_login_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_login_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_t/title",
          "value": "es_event_authentication_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_add_t/title",
          "value": "es_event_btm_launch_item_add_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_add_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_add_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_sudo_reject_info_t/title",
          "value": "es_sudo_reject_info_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_sudo_reject_info_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_sudo_reject_info_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_sudo_reject_info_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_sudo_reject_info_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_group_set_t/title",
          "value": "es_event_od_group_set_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_group_set_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_group_set_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_group_set_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_group_set_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_member_id_array_t/title",
          "value": "es_od_member_id_array_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_member_id_array_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_od_member_id_array_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_member_id_array_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_od_member_id_array_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_token_t/title",
          "value": "es_event_authentication_token_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_token_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_token_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_token_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_token_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_add_t/title",
          "value": "es_event_od_attribute_value_add_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_add_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_value_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_add_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_value_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_auto_unlock_t/title",
          "value": "es_event_authentication_auto_unlock_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_auto_unlock_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_auto_unlock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_auto_unlock_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_auto_unlock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_launch_item_t/title",
          "value": "es_btm_launch_item_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_launch_item_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_btm_launch_item_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_launch_item_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_btm_launch_item_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_profile_add_t/title",
          "value": "es_event_profile_add_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_profile_add_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_profile_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_profile_add_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_profile_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_openssh_logout_t/title",
          "value": "es_event_openssh_logout_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_openssh_logout_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_openssh_logout_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_openssh_logout_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_openssh_logout_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_disable_user_t/title",
          "value": "es_event_od_disable_user_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_disable_user_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_disable_user_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_disable_user_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_disable_user_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_unlock_t/title",
          "value": "es_event_lw_session_unlock_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_unlock_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_unlock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_unlock_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_unlock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_screensharing_detach_t/title",
          "value": "es_event_screensharing_detach_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_screensharing_detach_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_screensharing_detach_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_screensharing_detach_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_screensharing_detach_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_openssh_login_t/title",
          "value": "es_event_openssh_login_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_openssh_login_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_openssh_login_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_openssh_login_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_openssh_login_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_xp_malware_detected_t/title",
          "value": "es_event_xp_malware_detected_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_xp_malware_detected_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_xp_malware_detected_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_xp_malware_detected_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_xp_malware_detected_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_delete_user_t/title",
          "value": "es_event_od_delete_user_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_delete_user_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_delete_user_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_delete_user_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_delete_user_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_gatekeeper_user_override_t/title",
          "value": "es_event_gatekeeper_user_override_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_gatekeeper_user_override_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_gatekeeper_user_override_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_gatekeeper_user_override_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_gatekeeper_user_override_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_logout_t/title",
          "value": "es_event_login_logout_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_logout_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_logout_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_logout_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_logout_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_login_t/title",
          "value": "es_event_lw_session_login_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_login_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_login_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_login_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_login_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_set_t/title",
          "value": "es_event_od_attribute_set_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_set_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_set_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_set_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_set_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_touchid_t/title",
          "value": "es_event_authentication_touchid_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_touchid_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_touchid_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_touchid_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_touchid_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_group_remove_t/title",
          "value": "es_event_od_group_remove_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_group_remove_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_group_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_group_remove_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_group_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_signed_file_info_t/title",
          "value": "es_signed_file_info_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_signed_file_info_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_signed_file_info_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_signed_file_info_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_signed_file_info_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_member_id_t/title",
          "value": "es_od_member_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_member_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_od_member_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_member_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_od_member_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_xp_malware_remediated_t/title",
          "value": "es_event_xp_malware_remediated_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_xp_malware_remediated_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_xp_malware_remediated_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_xp_malware_remediated_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_xp_malware_remediated_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_result_t/title",
          "value": "es_authorization_result_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_result_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_authorization_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_result_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_authorization_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_od_t/title",
          "value": "es_event_authentication_od_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_od_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_od_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_od_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_od_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_enable_user_t/title",
          "value": "es_event_od_enable_user_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_enable_user_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_enable_user_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_enable_user_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_enable_user_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_remove_t/title",
          "value": "es_event_btm_launch_item_remove_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_remove_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_remove_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_su_t/title",
          "value": "es_event_su_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_su_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_su_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_su_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_su_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_screensharing_attach_t/title",
          "value": "es_event_screensharing_attach_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_screensharing_attach_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_screensharing_attach_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_screensharing_attach_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_screensharing_attach_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_create_group_t/title",
          "value": "es_event_od_create_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_create_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_create_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_create_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_create_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_create_user_t/title",
          "value": "es_event_od_create_user_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_create_user_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_create_user_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_create_user_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_create_user_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_xpc_connect_t/title",
          "value": "es_event_xpc_connect_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_xpc_connect_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_xpc_connect_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_xpc_connect_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_xpc_connect_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t/title",
          "value": "es_event_sudo_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_sudo_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_sudo_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_petition_t/title",
          "value": "es_event_authorization_petition_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_petition_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_petition_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_petition_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_petition_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_group_add_t/title",
          "value": "es_event_od_group_add_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_group_add_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_group_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_group_add_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_group_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_lock_t/title",
          "value": "es_event_lw_session_lock_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_lock_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_lock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_lock_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_lock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_judgement_t/title",
          "value": "es_event_authorization_judgement_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_judgement_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_judgement_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_judgement_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_judgement_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_modify_password_t/title",
          "value": "es_event_od_modify_password_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_modify_password_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_modify_password_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_modify_password_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_modify_password_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_profile_remove_t/title",
          "value": "es_event_profile_remove_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_profile_remove_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_profile_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_profile_remove_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_profile_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t/title",
          "value": "es_event_od_attribute_value_remove_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_value_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_value_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_delete_group_t/title",
          "value": "es_event_od_delete_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_delete_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_delete_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_delete_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_delete_group_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/endpointsecurity-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/endpointsecurity-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
