{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "EndpointSecurity Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Constants",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-constants"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Data Types",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-data-types"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Functions",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-functions"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Structures",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-structures"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_address_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_address_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_address_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_address_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_address_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_address_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authentication_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_authentication_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authentication_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_authentication_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_authentication_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authentication_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_rule_class_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_authorization_rule_class_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_rule_class_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_authorization_rule_class_t"
        }
      ],
      "role": "symbol",
      "title": "es_authorization_rule_class_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authorization_rule_class_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_auto_unlock_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_auto_unlock_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_auto_unlock_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_auto_unlock_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_auto_unlock_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_auto_unlock_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_item_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_btm_item_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_item_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_btm_item_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_btm_item_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_btm_item_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_gatekeeper_user_override_file_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_gatekeeper_user_override_file_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_gatekeeper_user_override_file_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_gatekeeper_user_override_file_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_gatekeeper_user_override_file_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_gatekeeper_user_override_file_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_get_task_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_get_task_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_get_task_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_get_task_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_get_task_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_get_task_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mount_disposition_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mount_disposition_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mount_disposition_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mount_disposition_t"
        }
      ],
      "role": "symbol",
      "title": "es_mount_disposition_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mount_disposition_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_inversion_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_inversion_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_inversion_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_inversion_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_mute_inversion_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_inversion_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_inverted_return_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_inverted_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_inverted_return_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_inverted_return_t"
        }
      ],
      "role": "symbol",
      "title": "es_mute_inverted_return_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_inverted_return_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_account_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_od_account_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_account_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_od_account_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_od_account_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_od_account_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_od_member_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_od_member_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_od_member_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_od_member_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_record_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_od_record_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_record_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_od_record_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_od_record_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_od_record_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_openssh_login_result_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_openssh_login_result_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_openssh_login_result_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_openssh_login_result_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_openssh_login_result_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_openssh_login_result_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_profile_source_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_profile_source_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_profile_source_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_profile_source_t"
        }
      ],
      "role": "symbol",
      "title": "es_profile_source_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_profile_source_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sudo_plugin_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_sudo_plugin_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sudo_plugin_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_sudo_plugin_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_sudo_plugin_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_sudo_plugin_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_touchid_mode_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_touchid_mode_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_touchid_mode_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_touchid_mode_t"
        }
      ],
      "role": "symbol",
      "title": "es_touchid_mode_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_touchid_mode_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_xpc_domain_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_xpc_domain_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_xpc_domain_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_xpc_domain_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_xpc_domain_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_xpc_domain_type_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_address_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authentication_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_rule_class_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_auto_unlock_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_item_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_gatekeeper_user_override_file_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_get_task_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mount_disposition_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_inversion_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_inverted_return_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_account_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_record_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_openssh_login_result_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_profile_source_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sudo_plugin_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_touchid_mode_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_xpc_domain_type_t"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_address_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authentication_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_rule_class_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_auto_unlock_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_item_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_gatekeeper_user_override_file_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_get_task_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mount_disposition_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_inversion_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_inverted_return_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_account_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_member_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_od_record_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_openssh_login_result_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_profile_source_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_sudo_plugin_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_touchid_mode_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_xpc_domain_type_t"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_account_type_t/title",
          "value": "es_od_account_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_account_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_od_account_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_account_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_od_account_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_record_type_t/title",
          "value": "es_od_record_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_record_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_od_record_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_record_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_od_record_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_rule_class_t/title",
          "value": "es_authorization_rule_class_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_rule_class_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_authorization_rule_class_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_rule_class_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_authorization_rule_class_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_item_type_t/title",
          "value": "es_btm_item_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_item_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_btm_item_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_item_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_btm_item_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mount_disposition_t/title",
          "value": "es_mount_disposition_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mount_disposition_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mount_disposition_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mount_disposition_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mount_disposition_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_openssh_login_result_type_t/title",
          "value": "es_openssh_login_result_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_openssh_login_result_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_openssh_login_result_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_openssh_login_result_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_openssh_login_result_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_profile_source_t/title",
          "value": "es_profile_source_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_profile_source_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_profile_source_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_profile_source_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_profile_source_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_sudo_plugin_type_t/title",
          "value": "es_sudo_plugin_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_sudo_plugin_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_sudo_plugin_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_sudo_plugin_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_sudo_plugin_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_member_type_t/title",
          "value": "es_od_member_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_member_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_od_member_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_od_member_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_od_member_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_gatekeeper_user_override_file_type_t/title",
          "value": "es_gatekeeper_user_override_file_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_gatekeeper_user_override_file_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_gatekeeper_user_override_file_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_gatekeeper_user_override_file_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_gatekeeper_user_override_file_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_inverted_return_t/title",
          "value": "es_mute_inverted_return_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_inverted_return_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_inverted_return_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_inverted_return_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_inverted_return_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_get_task_type_t/title",
          "value": "es_get_task_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_get_task_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_get_task_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_get_task_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_get_task_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_touchid_mode_t/title",
          "value": "es_touchid_mode_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_touchid_mode_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_touchid_mode_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_touchid_mode_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_touchid_mode_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_address_type_t/title",
          "value": "es_address_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_address_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_address_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_address_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_address_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_auto_unlock_type_t/title",
          "value": "es_auto_unlock_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_auto_unlock_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_auto_unlock_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_auto_unlock_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_auto_unlock_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_inversion_type_t/title",
          "value": "es_mute_inversion_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_inversion_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_inversion_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_inversion_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_inversion_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_xpc_domain_type_t/title",
          "value": "es_xpc_domain_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_xpc_domain_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_xpc_domain_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_xpc_domain_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_xpc_domain_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authentication_type_t/title",
          "value": "es_authentication_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authentication_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_authentication_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authentication_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_authentication_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/endpointsecurity-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/endpointsecurity-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
