{
  "abstract": [
    {
      "text": "The notification action type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ACTION_TYPE_NOTIFY"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@es_action_type_t@ES_ACTION_TYPE_NOTIFY",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ES_ACTION_TYPE_NOTIFY"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@es_action_type_t",
        "text": "es_action_type_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ES_ACTION_TYPE_NOTIFY"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "ES_ACTION_TYPE_NOTIFY"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ES_ACTION_TYPE_NOTIFY"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_action_type_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@es_action_type_t",
              "text": "es_action_type_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ACTION_TYPE_AUTH": {
      "abstract": [
        {
          "text": "The authentication action type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_ACTION_TYPE_AUTH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_action_type_t",
          "text": "es_action_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ACTION_TYPE_AUTH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_ACTION_TYPE_AUTH"
        }
      ],
      "role": "symbol",
      "title": "ES_ACTION_TYPE_AUTH",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_action_type_auth"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ACTION_TYPE_NOTIFY": {
      "abstract": [
        {
          "text": "The notification action type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_ACTION_TYPE_NOTIFY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_action_type_t",
          "text": "es_action_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ACTION_TYPE_NOTIFY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_ACTION_TYPE_NOTIFY"
        }
      ],
      "role": "symbol",
      "title": "ES_ACTION_TYPE_NOTIFY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_action_type_notify"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_action_type_t": {
      "abstract": [
        {
          "text": "The type of the message’s action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_action_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_action_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_action_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_action_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_action_type_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Action-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ACTION_TYPE_AUTH"
      ],
      "title": "Action Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ES_ACTION_TYPE_NOTIFY"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_ACTION_TYPE_NOTIFY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_action_type_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Action-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ACTION_TYPE_AUTH"
              ],
              "title": "Action Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ES_ACTION_TYPE_NOTIFY"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_action_type_t/title",
          "value": "es_action_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_action_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_action_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_action_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_action_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ACTION_TYPE_NOTIFY/title",
          "value": "ES_ACTION_TYPE_NOTIFY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ACTION_TYPE_NOTIFY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_ACTION_TYPE_NOTIFY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ACTION_TYPE_AUTH/title",
          "value": "ES_ACTION_TYPE_AUTH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ACTION_TYPE_AUTH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_ACTION_TYPE_AUTH"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_action_type_notify"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_action_type_notify"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
