{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@es_event_type_t@ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@es_event_type_t",
        "text": "es_event_type_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_type_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@es_event_type_t",
              "text": "es_event_type_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_IPV4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_ADDRESS_TYPE_IPV4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_address_type_t",
          "text": "es_address_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_IPV4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_ADDRESS_TYPE_IPV4"
        }
      ],
      "role": "symbol",
      "title": "ES_ADDRESS_TYPE_IPV4",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_address_type_ipv4"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_IPV6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_ADDRESS_TYPE_IPV6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_address_type_t",
          "text": "es_address_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_IPV6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_ADDRESS_TYPE_IPV6"
        }
      ],
      "role": "symbol",
      "title": "ES_ADDRESS_TYPE_IPV6",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_address_type_ipv6"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_NAMED_SOCKET": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_ADDRESS_TYPE_NAMED_SOCKET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_address_type_t",
          "text": "es_address_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_NAMED_SOCKET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_ADDRESS_TYPE_NAMED_SOCKET"
        }
      ],
      "role": "symbol",
      "title": "ES_ADDRESS_TYPE_NAMED_SOCKET",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_address_type_named_socket"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_NONE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_ADDRESS_TYPE_NONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_address_type_t",
          "text": "es_address_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_NONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_ADDRESS_TYPE_NONE"
        }
      ],
      "role": "symbol",
      "title": "ES_ADDRESS_TYPE_NONE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_address_type_none"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_AUTO_UNLOCK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHENTICATION_TYPE_AUTO_UNLOCK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authentication_type_t",
          "text": "es_authentication_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_AUTO_UNLOCK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHENTICATION_TYPE_AUTO_UNLOCK"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHENTICATION_TYPE_AUTO_UNLOCK",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authentication_type_auto_unlock"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_LAST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHENTICATION_TYPE_LAST"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authentication_type_t",
          "text": "es_authentication_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_LAST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHENTICATION_TYPE_LAST"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHENTICATION_TYPE_LAST",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authentication_type_last"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_OD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHENTICATION_TYPE_OD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authentication_type_t",
          "text": "es_authentication_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_OD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHENTICATION_TYPE_OD"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHENTICATION_TYPE_OD",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authentication_type_od"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_TOKEN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHENTICATION_TYPE_TOKEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authentication_type_t",
          "text": "es_authentication_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_TOKEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHENTICATION_TYPE_TOKEN"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHENTICATION_TYPE_TOKEN",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authentication_type_token"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_TOUCHID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHENTICATION_TYPE_TOUCHID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authentication_type_t",
          "text": "es_authentication_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_TOUCHID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHENTICATION_TYPE_TOUCHID"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHENTICATION_TYPE_TOUCHID",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authentication_type_touchid"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_ALLOW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_ALLOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authorization_rule_class_t",
          "text": "es_authorization_rule_class_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_ALLOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_ALLOW"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHORIZATION_RULE_CLASS_ALLOW",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authorization_rule_class_allow"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_DENY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_DENY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authorization_rule_class_t",
          "text": "es_authorization_rule_class_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_DENY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_DENY"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHORIZATION_RULE_CLASS_DENY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authorization_rule_class_deny"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_INVALID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_INVALID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authorization_rule_class_t",
          "text": "es_authorization_rule_class_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_INVALID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_INVALID"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHORIZATION_RULE_CLASS_INVALID",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authorization_rule_class_invalid"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_MECHANISM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_MECHANISM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authorization_rule_class_t",
          "text": "es_authorization_rule_class_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_MECHANISM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_MECHANISM"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHORIZATION_RULE_CLASS_MECHANISM",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authorization_rule_class_mechanism"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_RULE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_RULE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authorization_rule_class_t",
          "text": "es_authorization_rule_class_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_RULE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_RULE"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHORIZATION_RULE_CLASS_RULE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authorization_rule_class_rule"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_UNKNOWN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_UNKNOWN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_authorization_rule_class_t",
          "text": "es_authorization_rule_class_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_UNKNOWN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_AUTHORIZATION_RULE_CLASS_UNKNOWN"
        }
      ],
      "role": "symbol",
      "title": "ES_AUTHORIZATION_RULE_CLASS_UNKNOWN",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authorization_rule_class_unknown"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_btm_launch_item_add"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_type_t": {
      "abstract": [
        {
          "text": "A type used to identify a message’s event type and subscribe to events of that type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_IPV4",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_IPV6",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_NAMED_SOCKET",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_NONE",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_AUTO_UNLOCK",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_LAST",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_OD",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_TOKEN",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_TOUCHID",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_ALLOW",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_DENY",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_INVALID",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_MECHANISM",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_RULE",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_UNKNOWN"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_type_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_IPV4",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_IPV6",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_NAMED_SOCKET",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_ADDRESS_TYPE_NONE",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_AUTO_UNLOCK",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_LAST",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_OD",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_TOKEN",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHENTICATION_TYPE_TOUCHID",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_ALLOW",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_DENY",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_INVALID",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_MECHANISM",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_RULE",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_AUTHORIZATION_RULE_CLASS_UNKNOWN"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHENTICATION_TYPE_AUTO_UNLOCK/title",
          "value": "ES_AUTHENTICATION_TYPE_AUTO_UNLOCK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHENTICATION_TYPE_AUTO_UNLOCK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHENTICATION_TYPE_AUTO_UNLOCK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_ALLOW/title",
          "value": "ES_AUTHORIZATION_RULE_CLASS_ALLOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_ALLOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHORIZATION_RULE_CLASS_ALLOW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHENTICATION_TYPE_TOUCHID/title",
          "value": "ES_AUTHENTICATION_TYPE_TOUCHID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHENTICATION_TYPE_TOUCHID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHENTICATION_TYPE_TOUCHID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_DENY/title",
          "value": "ES_AUTHORIZATION_RULE_CLASS_DENY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_DENY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHORIZATION_RULE_CLASS_DENY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHENTICATION_TYPE_LAST/title",
          "value": "ES_AUTHENTICATION_TYPE_LAST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHENTICATION_TYPE_LAST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHENTICATION_TYPE_LAST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ADDRESS_TYPE_IPV4/title",
          "value": "ES_ADDRESS_TYPE_IPV4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ADDRESS_TYPE_IPV4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_ADDRESS_TYPE_IPV4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ADDRESS_TYPE_NAMED_SOCKET/title",
          "value": "ES_ADDRESS_TYPE_NAMED_SOCKET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ADDRESS_TYPE_NAMED_SOCKET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_ADDRESS_TYPE_NAMED_SOCKET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ADDRESS_TYPE_IPV6/title",
          "value": "ES_ADDRESS_TYPE_IPV6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ADDRESS_TYPE_IPV6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_ADDRESS_TYPE_IPV6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHENTICATION_TYPE_OD/title",
          "value": "ES_AUTHENTICATION_TYPE_OD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHENTICATION_TYPE_OD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHENTICATION_TYPE_OD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHENTICATION_TYPE_TOKEN/title",
          "value": "ES_AUTHENTICATION_TYPE_TOKEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHENTICATION_TYPE_TOKEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHENTICATION_TYPE_TOKEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_type_t/title",
          "value": "es_event_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_RULE/title",
          "value": "ES_AUTHORIZATION_RULE_CLASS_RULE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_RULE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHORIZATION_RULE_CLASS_RULE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_MECHANISM/title",
          "value": "ES_AUTHORIZATION_RULE_CLASS_MECHANISM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_MECHANISM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHORIZATION_RULE_CLASS_MECHANISM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_UNKNOWN/title",
          "value": "ES_AUTHORIZATION_RULE_CLASS_UNKNOWN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_UNKNOWN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHORIZATION_RULE_CLASS_UNKNOWN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD/title",
          "value": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_BTM_LAUNCH_ITEM_ADD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_INVALID/title",
          "value": "ES_AUTHORIZATION_RULE_CLASS_INVALID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_AUTHORIZATION_RULE_CLASS_INVALID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_AUTHORIZATION_RULE_CLASS_INVALID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ADDRESS_TYPE_NONE/title",
          "value": "ES_ADDRESS_TYPE_NONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_ADDRESS_TYPE_NONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_ADDRESS_TYPE_NONE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_type_notify_btm_launch_item_add"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_type_notify_btm_launch_item_add"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
