{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@es_event_sudo_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "es_event_sudo_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "es_event_sudo_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "es_event_sudo_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "es_event_sudo_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_authorization_result_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_authorization_result_t"
        }
      ],
      "role": "symbol",
      "title": "es_authorization_result_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authorization_result_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_btm_launch_item_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_btm_launch_item_t"
        }
      ],
      "role": "symbol",
      "title": "es_btm_launch_item_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_btm_launch_item_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_auto_unlock_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_auto_unlock_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_auto_unlock_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_auto_unlock_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_od_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_od_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_od_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_od_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_token_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_token_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_token_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_touchid_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_touchid_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_touchid_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_touchid_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authorization_judgement_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authorization_judgement_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authorization_judgement_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authorization_judgement_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authorization_petition_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authorization_petition_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authorization_petition_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authorization_petition_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_add_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_add_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_btm_launch_item_add_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_btm_launch_item_add_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_remove_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_remove_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_btm_launch_item_remove_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_btm_launch_item_remove_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_gatekeeper_user_override_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_gatekeeper_user_override_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_gatekeeper_user_override_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_gatekeeper_user_override_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_login_login_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_login_login_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_login_login_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_login_login_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_login_logout_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_login_logout_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_login_logout_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_login_logout_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_lw_session_lock_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_lw_session_lock_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_lw_session_lock_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_lw_session_lock_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_sudo_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_sudo_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_sudo_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/command": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "command"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/command",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "command"
        }
      ],
      "role": "symbol",
      "title": "command",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/command"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/from_uid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "from_uid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_sudo_t",
          "text": "es_event_sudo_t"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union_from_uid"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/from_uid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "from_uid"
        }
      ],
      "role": "symbol",
      "title": "from_uid",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/from_uid"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/from_username": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "from_username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/from_username",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "from_username"
        }
      ],
      "role": "symbol",
      "title": "from_username",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/from_username"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/has_from_uid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "has_from_uid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/has_from_uid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "has_from_uid"
        }
      ],
      "role": "symbol",
      "title": "has_from_uid",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/has_from_uid"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/has_to_uid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "has_to_uid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/has_to_uid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "has_to_uid"
        }
      ],
      "role": "symbol",
      "title": "has_to_uid",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/has_to_uid"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/init()"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/init(success:reject_info:has_from_uid:from_uid:from_username:has_to_uid:to_uid:to_username:command:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "success"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reject_info"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_sudo_reject_info_t",
          "text": "es_sudo_reject_info_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "has_from_uid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from_uid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_sudo_t",
          "text": "es_event_sudo_t"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union_from_uid"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from_username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "has_to_uid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to_uid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_sudo_t",
          "text": "es_event_sudo_t"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union_to_uid"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to_username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "command"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/init(success:reject_info:has_from_uid:from_uid:from_username:has_to_uid:to_uid:to_username:command:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(success:reject_info:has_from_uid:from_uid:from_username:has_to_uid:to_uid:to_username:command:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/init(success:reject_info:has_from_uid:from_uid:from_username:has_to_uid:to_uid:to_username:command:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/reject_info": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reject_info"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_sudo_reject_info_t",
          "text": "es_sudo_reject_info_t"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/reject_info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reject_info"
        }
      ],
      "role": "symbol",
      "title": "reject_info",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/reject_info"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/success": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "role": "symbol",
      "title": "success",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/success"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/to_uid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "to_uid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_sudo_t",
          "text": "es_event_sudo_t"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union_to_uid"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/to_uid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "to_uid"
        }
      ],
      "role": "symbol",
      "title": "to_uid",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/to_uid"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/to_username": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "to_username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/to_username",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "to_username"
        }
      ],
      "role": "symbol",
      "title": "to_username",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_sudo_t/to_username"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/init()",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/init(success:reject_info:has_from_uid:from_uid:from_username:has_to_uid:to_uid:to_username:command:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/command",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/from_uid",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/from_username",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/has_from_uid",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/has_to_uid",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/reject_info",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/success",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/to_uid",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/to_username"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "es_event_sudo_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_sudo_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_sudo_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/command",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/from_uid",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/from_username",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/has_from_uid",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/has_to_uid",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/reject_info",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/success",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/to_uid",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_sudo_t/to_username"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "es_event_sudo_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_remove_t/title",
          "value": "es_event_btm_launch_item_remove_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_remove_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_remove_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_petition_t/title",
          "value": "es_event_authorization_petition_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_petition_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_petition_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_petition_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_petition_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_logout_t/title",
          "value": "es_event_login_logout_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_logout_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_logout_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_logout_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_logout_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1to_uid/title",
          "value": "to_uid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1to_uid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "to_uid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1reject_info/title",
          "value": "reject_info"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1reject_info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reject_info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_od_t/title",
          "value": "es_event_authentication_od_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_od_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_od_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_od_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_od_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_launch_item_t/title",
          "value": "es_btm_launch_item_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_launch_item_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_btm_launch_item_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_launch_item_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_btm_launch_item_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_auto_unlock_t/title",
          "value": "es_event_authentication_auto_unlock_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_auto_unlock_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_auto_unlock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_auto_unlock_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_auto_unlock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_t/title",
          "value": "es_event_authentication_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1to_username/title",
          "value": "to_username"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1to_username/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "to_username"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_gatekeeper_user_override_t/title",
          "value": "es_event_gatekeeper_user_override_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_gatekeeper_user_override_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_gatekeeper_user_override_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_gatekeeper_user_override_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_gatekeeper_user_override_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_login_t/title",
          "value": "es_event_login_login_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_login_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_login_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_login_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_login_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_lock_t/title",
          "value": "es_event_lw_session_lock_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_lock_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_lock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_lock_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_lock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_result_t/title",
          "value": "es_authorization_result_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_result_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_authorization_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_result_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_authorization_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t/title",
          "value": "es_event_sudo_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_sudo_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_sudo_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1has_from_uid/title",
          "value": "has_from_uid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1has_from_uid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "has_from_uid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_add_t/title",
          "value": "es_event_btm_launch_item_add_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_add_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_add_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_touchid_t/title",
          "value": "es_event_authentication_touchid_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_touchid_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_touchid_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_touchid_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_touchid_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1success/title",
          "value": "success"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "success"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1from_uid/title",
          "value": "from_uid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1from_uid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "from_uid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_judgement_t/title",
          "value": "es_event_authorization_judgement_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_judgement_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_judgement_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_judgement_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_judgement_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1from_username/title",
          "value": "from_username"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1from_username/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "from_username"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1command/title",
          "value": "command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1command/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1has_to_uid/title",
          "value": "has_to_uid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_sudo_t~1has_to_uid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "has_to_uid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_token_t/title",
          "value": "es_event_authentication_token_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_token_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_token_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_token_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_token_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_sudo_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_sudo_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
