{
  "abstract": [
    {
      "text": "A type for an event that indicates the copying of a file by use of a system call.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@es_event_copyfile_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "es_event_copyfile_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "es_event_copyfile_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "es_event_copyfile_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "es_event_copyfile_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Be aware that the ",
              "type": "text"
            },
            {
              "code": "copyfile",
              "type": "codeVoice"
            },
            {
              "text": " system call isn’t the same thing as the ",
              "type": "text"
            },
            {
              "code": "copyfile(3)",
              "type": "codeVoice"
            },
            {
              "text": " function in the standard library. Its semantics depend on the specific filesystem in use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_access_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the checking of a file’s access permission.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_access_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_access_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_access_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_access_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_access_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_clone_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the cloning of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_clone_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_clone_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_clone_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_clone_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_clone_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_close_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the closing of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_close_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_close_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_close_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_close_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_close_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the copying of a file by use of a system call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_copyfile_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_copyfile_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_copyfile_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_copyfile_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/flags": {
      "abstract": [
        {
          "text": "The flags argument of the system call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flags"
        }
      ],
      "role": "symbol",
      "title": "flags",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_copyfile_t/flags"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/init(source:target_file:target_dir:target_name:mode:flags:reserved:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_file_t",
          "text": "es_file_t"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "target_file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_file_t",
          "text": "es_file_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "target_dir"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_file_t",
          "text": "es_file_t"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "target_name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mode_t",
          "text": "mode_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": "))"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/init(source:target_file:target_dir:target_name:mode:flags:reserved:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(source:target_file:target_dir:target_name:mode:flags:reserved:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_copyfile_t/init(source:target_file:target_dir:target_name:mode:flags:reserved:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/mode": {
      "abstract": [
        {
          "text": "The mode argument of the system call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mode_t",
          "text": "mode_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/mode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mode"
        }
      ],
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_copyfile_t/mode"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/reserved": {
      "abstract": [
        {
          "text": "An unused field reserved for future use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved"
        }
      ],
      "role": "symbol",
      "title": "reserved",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_copyfile_t/reserved"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/source": {
      "abstract": [
        {
          "text": "The file to clone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_file_t",
          "text": "es_file_t"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/source",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "source"
        }
      ],
      "role": "symbol",
      "title": "source",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_copyfile_t/source"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_dir": {
      "abstract": [
        {
          "text": "The directory that contains the copied file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target_dir"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_file_t",
          "text": "es_file_t"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_dir",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "target_dir"
        }
      ],
      "role": "symbol",
      "title": "target_dir",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_copyfile_t/target_dir"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_file": {
      "abstract": [
        {
          "text": "The file, if any, that exists at the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target_file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_file_t",
          "text": "es_file_t"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_file",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "target_file"
        }
      ],
      "role": "symbol",
      "title": "target_file",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_copyfile_t/target_file"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_name": {
      "abstract": [
        {
          "text": "The name of the newly copied file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target_name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "target_name"
        }
      ],
      "role": "symbol",
      "title": "target_name",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_copyfile_t/target_name"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_create_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the creation of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_create_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_create_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_create_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_create_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_create_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_dup_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the duplication of a file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_dup_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_dup_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_dup_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_dup_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_dup_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_exchangedata_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the exchange of data between two files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_exchangedata_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_exchangedata_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_exchangedata_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_exchangedata_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_exchangedata_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_fcntl_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the manipulation of a file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_fcntl_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_fcntl_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_fcntl_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_fcntl_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_fcntl_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lookup_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the lookup of a file’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_lookup_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lookup_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_lookup_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_lookup_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_lookup_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_open_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the opening of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_open_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_open_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_open_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_open_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_open_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_rename_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the renaming of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_rename_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_rename_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_rename_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_rename_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_rename_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_searchfs_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates searching a volume or mounted file system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_searchfs_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_searchfs_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_searchfs_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_searchfs_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_searchfs_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_truncate_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the truncation of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_truncate_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_truncate_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_truncate_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_truncate_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_truncate_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_write_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the writing of data to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_write_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_write_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_write_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_write_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_write_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_file_t": {
      "abstract": [
        {
          "text": "A type that represents a file related to an Endpoint Security event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_file_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_file_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_file_t"
        }
      ],
      "role": "symbol",
      "title": "es_file_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_file_t"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-System-Event-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_file_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_access_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_clone_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_create_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_dup_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_fcntl_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_open_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_close_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_rename_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_truncate_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_exchangedata_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_write_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lookup_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_searchfs_t"
      ],
      "title": "File-System Event Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-Event-Properties",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/source",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_file",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_dir",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_name",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/mode",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/flags",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/reserved"
      ],
      "title": "Inspecting Event Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/init(source:target_file:target_dir:target_name:mode:flags:reserved:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "es_event_copyfile_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_copyfile_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_copyfile_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-Event-Properties",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/source",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_file",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_dir",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/target_name",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/mode",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/flags",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t/reserved"
              ],
              "title": "Inspecting Event Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-System-Event-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_file_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_access_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_clone_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_create_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_dup_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_fcntl_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_open_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_close_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_rename_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_truncate_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_exchangedata_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_write_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lookup_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_searchfs_t"
              ],
              "title": "File-System Event Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "es_event_copyfile_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_dup_t/title",
          "value": "es_event_dup_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_dup_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_dup_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_dup_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_dup_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_open_t/title",
          "value": "es_event_open_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_open_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_open_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_open_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_open_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1flags/title",
          "value": "flags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1flags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_exchangedata_t/title",
          "value": "es_event_exchangedata_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_exchangedata_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_exchangedata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_exchangedata_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_exchangedata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_searchfs_t/title",
          "value": "es_event_searchfs_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_searchfs_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_searchfs_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_searchfs_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_searchfs_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_clone_t/title",
          "value": "es_event_clone_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_clone_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_clone_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_clone_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_clone_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_write_t/title",
          "value": "es_event_write_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_write_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_write_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_write_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_write_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_file_t/title",
          "value": "es_file_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_file_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_file_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_file_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_file_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1target_file/title",
          "value": "target_file"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1target_file/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "target_file"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1source/title",
          "value": "source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1source/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1target_name/title",
          "value": "target_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1target_name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "target_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lookup_t/title",
          "value": "es_event_lookup_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lookup_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lookup_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lookup_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lookup_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_close_t/title",
          "value": "es_event_close_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_close_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_close_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_close_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_close_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_truncate_t/title",
          "value": "es_event_truncate_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_truncate_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_truncate_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_truncate_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_truncate_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_create_t/title",
          "value": "es_event_create_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_create_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_create_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_create_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_create_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1mode/title",
          "value": "mode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1mode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_rename_t/title",
          "value": "es_event_rename_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_rename_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_rename_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_rename_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_rename_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1reserved/title",
          "value": "reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1target_dir/title",
          "value": "target_dir"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t~1target_dir/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "target_dir"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t/title",
          "value": "es_event_copyfile_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_copyfile_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_copyfile_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_fcntl_t/title",
          "value": "es_event_fcntl_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_fcntl_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_fcntl_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_fcntl_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_fcntl_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_access_t/title",
          "value": "es_event_access_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_access_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_access_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_access_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_access_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_copyfile_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_copyfile_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
