{
  "abstract": [
    {
      "text": "An identifier for a process that notifies endpoint security that it is setting its effective group ID.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_SETEGID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@es_event_type_t@ES_EVENT_TYPE_NOTIFY_SETEGID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ES_EVENT_TYPE_NOTIFY_SETEGID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@es_event_type_t",
        "text": "es_event_type_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ES_EVENT_TYPE_NOTIFY_SETEGID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "ES_EVENT_TYPE_NOTIFY_SETEGID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_SETEGID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_type_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@es_event_type_t",
              "text": "es_event_type_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This identifier corresponds to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " union member ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setegid",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which has the type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_setegid_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_ACCESS": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is checking a file’s access permission.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_ACCESS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_ACCESS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_ACCESS"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_ACCESS",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_access"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CHDIR": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is changing the working directory for the process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CHDIR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CHDIR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CHDIR"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_CHDIR",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_chdir"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CHROOT": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is changing the root directory for the process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CHROOT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CHROOT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CHROOT"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_CHROOT",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_chroot"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CLONE": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is cloning a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CLONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CLONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CLONE"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_CLONE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_clone"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CLOSE": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is closing a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CLOSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CLOSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CLOSE"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_CLOSE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_close"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_COPYFILE": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is copying a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_COPYFILE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_COPYFILE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_COPYFILE"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_COPYFILE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_copyfile"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CREATE": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is creating a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CREATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CREATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CREATE"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_CREATE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_create"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that its code signing status is now invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_cs_invalidated"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is deleting an extended attribute from a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_deleteextattr"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_DUP": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is duplicating a file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_DUP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_DUP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_DUP"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_DUP",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_dup"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is exchanging data between two files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_exchangedata"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXEC": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is executing an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_EXEC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXEC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_EXEC"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_EXEC",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_exec"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXIT": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is exiting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_EXIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_EXIT"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_EXIT",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_exit"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_FCNTL": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is manipulating a file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_FCNTL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_FCNTL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_FCNTL"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_FCNTL",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_fcntl"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that a file provider returned a reference to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_file_provider_materialize"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_SETEGID": {
      "abstract": [
        {
          "text": "An identifier for a process that notifies endpoint security that it is setting its effective group ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_SETEGID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_SETEGID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_SETEGID"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_SETEGID",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_setegid"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_setegid_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the setting of a process’s effective group ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_setegid_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_setegid_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_setegid_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_setegid_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_setegid_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_type_t": {
      "abstract": [
        {
          "text": "A type used to identify a message’s event type and subscribe to events of that type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t": {
      "abstract": [
        {
          "text": "A C union of event-specific types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_events_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_events_t"
        }
      ],
      "role": "symbol",
      "title": "es_events_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setegid": {
      "abstract": [
        {
          "text": "Properties of an event that indicates a change to a process’s effective group ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setegid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_setegid_t",
          "text": "es_event_setegid_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setegid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setegid"
        }
      ],
      "role": "symbol",
      "title": "setegid",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/setegid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notification-Event-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_ACCESS",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CHDIR",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CHROOT",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CLONE",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CLOSE",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_COPYFILE",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CREATE",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_DUP",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXEC",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXIT",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_FCNTL",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE"
      ],
      "title": "Notification Event Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ES_EVENT_TYPE_NOTIFY_SETEGID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_SETEGID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_type_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Notification-Event-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_ACCESS",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CHDIR",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CHROOT",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CLONE",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CLOSE",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_COPYFILE",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CREATE",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_DUP",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXEC",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_EXIT",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_FCNTL",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE"
              ],
              "title": "Notification Event Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ES_EVENT_TYPE_NOTIFY_SETEGID"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/title",
          "value": "es_events_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_events_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_events_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_DUP/title",
          "value": "ES_EVENT_TYPE_NOTIFY_DUP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_DUP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_DUP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CHROOT/title",
          "value": "ES_EVENT_TYPE_NOTIFY_CHROOT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CHROOT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_CHROOT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_EXIT/title",
          "value": "ES_EVENT_TYPE_NOTIFY_EXIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_EXIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_EXIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CLONE/title",
          "value": "ES_EVENT_TYPE_NOTIFY_CLONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CLONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_CLONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED/title",
          "value": "ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_CS_INVALIDATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CREATE/title",
          "value": "ES_EVENT_TYPE_NOTIFY_CREATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CREATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_CREATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE/title",
          "value": "ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_FILE_PROVIDER_MATERIALIZE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CHDIR/title",
          "value": "ES_EVENT_TYPE_NOTIFY_CHDIR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CHDIR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_CHDIR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setegid/title",
          "value": "setegid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setegid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "setegid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_EXEC/title",
          "value": "ES_EVENT_TYPE_NOTIFY_EXEC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_EXEC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_EXEC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_COPYFILE/title",
          "value": "ES_EVENT_TYPE_NOTIFY_COPYFILE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_COPYFILE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_COPYFILE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR/title",
          "value": "ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_DELETEEXTATTR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_setegid_t/title",
          "value": "es_event_setegid_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_setegid_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_setegid_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_setegid_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_setegid_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CLOSE/title",
          "value": "ES_EVENT_TYPE_NOTIFY_CLOSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_CLOSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_CLOSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_SETEGID/title",
          "value": "ES_EVENT_TYPE_NOTIFY_SETEGID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_SETEGID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_SETEGID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_ACCESS/title",
          "value": "ES_EVENT_TYPE_NOTIFY_ACCESS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_ACCESS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_ACCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_FCNTL/title",
          "value": "ES_EVENT_TYPE_NOTIFY_FCNTL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_FCNTL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_FCNTL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA/title",
          "value": "ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_EXCHANGEDATA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_type_t/title",
          "value": "es_event_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_type_notify_setegid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_type_notify_setegid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
