{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@es_event_od_attribute_value_remove_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "es_event_od_attribute_value_remove_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "es_event_od_attribute_value_remove_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "es_event_od_attribute_value_remove_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_value_remove_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_authorization_result_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_authorization_result_t"
        }
      ],
      "role": "symbol",
      "title": "es_authorization_result_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_authorization_result_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_btm_launch_item_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_btm_launch_item_t"
        }
      ],
      "role": "symbol",
      "title": "es_btm_launch_item_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_btm_launch_item_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_auto_unlock_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_auto_unlock_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_auto_unlock_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_auto_unlock_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_od_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_od_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_od_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_od_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_token_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_token_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_token_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authentication_touchid_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authentication_touchid_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authentication_touchid_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authentication_touchid_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authorization_judgement_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authorization_judgement_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authorization_judgement_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authorization_judgement_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_authorization_petition_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_authorization_petition_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_authorization_petition_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_authorization_petition_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_add_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_add_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_btm_launch_item_add_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_btm_launch_item_add_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_remove_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_btm_launch_item_remove_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_btm_launch_item_remove_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_btm_launch_item_remove_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_gatekeeper_user_override_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_gatekeeper_user_override_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_gatekeeper_user_override_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_gatekeeper_user_override_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_login_login_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_login_login_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_login_login_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_login_login_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_login_logout_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_login_logout_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_login_logout_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_login_logout_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_lw_session_lock_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_lw_session_lock_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_lw_session_lock_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_lw_session_lock_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_od_attribute_value_remove_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_od_attribute_value_remove_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_od_attribute_value_remove_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/attribute_name": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attribute_name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/attribute_name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attribute_name"
        }
      ],
      "role": "symbol",
      "title": "attribute_name",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/attribute_name"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/attribute_value": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attribute_value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/attribute_value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attribute_value"
        }
      ],
      "role": "symbol",
      "title": "attribute_value",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/attribute_value"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/db_path": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "db_path"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/db_path",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "db_path"
        }
      ],
      "role": "symbol",
      "title": "db_path",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/db_path"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/error_code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error_code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/error_code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "error_code"
        }
      ],
      "role": "symbol",
      "title": "error_code",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/error_code"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/init()"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/init(instigator:error_code:record_type:record_name:attribute_name:attribute_value:node_name:db_path:instigator_token:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "instigator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_process_t",
          "text": "es_process_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "error_code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "record_type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_od_record_type_t",
          "text": "es_od_record_type_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "record_name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attribute_name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attribute_value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "node_name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "db_path"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "instigator_token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/init(instigator:error_code:record_type:record_name:attribute_name:attribute_value:node_name:db_path:instigator_token:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(instigator:error_code:record_type:record_name:attribute_name:attribute_value:node_name:db_path:instigator_token:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/init(instigator:error_code:record_type:record_name:attribute_name:attribute_value:node_name:db_path:instigator_token:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/instigator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instigator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_process_t",
          "text": "es_process_t"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/instigator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instigator"
        }
      ],
      "role": "symbol",
      "title": "instigator",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/instigator"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/instigator_token": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instigator_token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/instigator_token",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instigator_token"
        }
      ],
      "role": "symbol",
      "title": "instigator_token",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/instigator_token"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/node_name": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "node_name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/node_name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "node_name"
        }
      ],
      "role": "symbol",
      "title": "node_name",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/node_name"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/record_name": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "record_name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/record_name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "record_name"
        }
      ],
      "role": "symbol",
      "title": "record_name",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/record_name"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/record_type": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "record_type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_od_record_type_t",
          "text": "es_od_record_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/record_type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "record_type"
        }
      ],
      "role": "symbol",
      "title": "record_type",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t/record_type"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/init()",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/init(instigator:error_code:record_type:record_name:attribute_name:attribute_value:node_name:db_path:instigator_token:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/attribute_name",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/attribute_value",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/db_path",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/error_code",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/instigator",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/instigator_token",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/node_name",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/record_name",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/record_type"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "es_event_od_attribute_value_remove_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_value_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_value_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/attribute_name",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/attribute_value",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/db_path",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/error_code",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/instigator",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/instigator_token",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/node_name",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/record_name",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_od_attribute_value_remove_t/record_type"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_authorization_result_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_btm_launch_item_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_auto_unlock_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_od_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_token_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authentication_touchid_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_judgement_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_authorization_petition_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_add_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_btm_launch_item_remove_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_gatekeeper_user_override_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_login_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_login_logout_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_lw_session_lock_t"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "es_event_od_attribute_value_remove_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_od_t/title",
          "value": "es_event_authentication_od_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_od_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_od_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_od_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_od_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_token_t/title",
          "value": "es_event_authentication_token_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_token_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_token_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_token_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_token_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1instigator/title",
          "value": "instigator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1instigator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instigator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_add_t/title",
          "value": "es_event_btm_launch_item_add_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_add_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_add_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_add_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_remove_t/title",
          "value": "es_event_btm_launch_item_remove_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_remove_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_btm_launch_item_remove_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_btm_launch_item_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_t/title",
          "value": "es_event_authentication_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1db_path/title",
          "value": "db_path"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1db_path/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "db_path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_launch_item_t/title",
          "value": "es_btm_launch_item_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_launch_item_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_btm_launch_item_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_btm_launch_item_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_btm_launch_item_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1node_name/title",
          "value": "node_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1node_name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "node_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_auto_unlock_t/title",
          "value": "es_event_authentication_auto_unlock_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_auto_unlock_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_auto_unlock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_auto_unlock_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_auto_unlock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_judgement_t/title",
          "value": "es_event_authorization_judgement_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_judgement_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_judgement_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_judgement_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_judgement_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1attribute_value/title",
          "value": "attribute_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1attribute_value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attribute_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_login_t/title",
          "value": "es_event_login_login_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_login_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_login_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_login_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_login_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1attribute_name/title",
          "value": "attribute_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1attribute_name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attribute_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_petition_t/title",
          "value": "es_event_authorization_petition_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_petition_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_petition_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authorization_petition_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authorization_petition_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_logout_t/title",
          "value": "es_event_login_logout_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_logout_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_logout_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_login_logout_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_login_logout_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_lock_t/title",
          "value": "es_event_lw_session_lock_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_lock_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_lock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_lw_session_lock_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_lw_session_lock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_gatekeeper_user_override_t/title",
          "value": "es_event_gatekeeper_user_override_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_gatekeeper_user_override_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_gatekeeper_user_override_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_gatekeeper_user_override_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_gatekeeper_user_override_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1error_code/title",
          "value": "error_code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1error_code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "error_code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1record_type/title",
          "value": "record_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1record_type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "record_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t/title",
          "value": "es_event_od_attribute_value_remove_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_value_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_od_attribute_value_remove_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1record_name/title",
          "value": "record_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1record_name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "record_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_touchid_t/title",
          "value": "es_event_authentication_touchid_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_touchid_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_touchid_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_authentication_touchid_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_authentication_touchid_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_result_t/title",
          "value": "es_authorization_result_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_result_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_authorization_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_authorization_result_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_authorization_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1instigator_token/title",
          "value": "instigator_token"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_od_attribute_value_remove_t~1instigator_token/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instigator_token"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_od_attribute_value_remove_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
