{
  "abstract": [
    {
      "text": "A structure for a set of muted processes.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@es_muted_processes_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "es_muted_processes_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "es_muted_processes_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "es_muted_processes_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "es_muted_processes_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path(_:_:_:)": {
      "abstract": [
        {
          "text": "Suppresses events from executables that match a given path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_path"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_mute_path_type_t",
          "text": "es_mute_path_type_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_path"
        }
      ],
      "role": "symbol",
      "title": "es_mute_path(_:_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_path(_:_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_events(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Suppresses a subset of events from executables that match a given path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_path_events"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_mute_path_type_t",
          "text": "es_mute_path_type_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_events(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_path_events"
        }
      ],
      "role": "symbol",
      "title": "es_mute_path_events(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_path_events(_:_:_:_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_type_t": {
      "abstract": [
        {
          "text": "The type of a path argument, such as a prefix or a path literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_path_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_path_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_mute_path_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_path_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process(_:_:)": {
      "abstract": [
        {
          "text": "Suppresses events from a given process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_process"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_process"
        }
      ],
      "role": "symbol",
      "title": "es_mute_process(_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_process(_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process_events(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Suppresses a subset of events from a given process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_process_events"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process_events(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_process_events"
        }
      ],
      "role": "symbol",
      "title": "es_mute_process_events(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_process_events(_:_:_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_events(_:_:)": {
      "abstract": [
        {
          "text": "Retrieve a list of all muted paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_muted_paths_events"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_muted_paths_t",
          "text": "es_muted_paths_t"
        },
        {
          "kind": "text",
          "text": ">>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_events(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_muted_paths_events"
        }
      ],
      "role": "symbol",
      "title": "es_muted_paths_events(_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_paths_events(_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t": {
      "abstract": [
        {
          "text": "A structure for a set of muted paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_muted_paths_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_muted_paths_t"
        }
      ],
      "role": "symbol",
      "title": "es_muted_paths_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_paths_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_process_t": {
      "abstract": [
        {
          "text": "A structure that describes a process’s muted events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_muted_process_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_process_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_muted_process_t"
        }
      ],
      "role": "symbol",
      "title": "es_muted_process_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_process_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_events(_:_:)": {
      "abstract": [
        {
          "text": "Retrieve a list of all muted processes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_muted_processes_events"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_muted_processes_t",
          "text": "es_muted_processes_t"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_events(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_muted_processes_events"
        }
      ],
      "role": "symbol",
      "title": "es_muted_processes_events(_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_processes_events(_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t": {
      "abstract": [
        {
          "text": "A structure for a set of muted processes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_muted_processes_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_muted_processes_t"
        }
      ],
      "role": "symbol",
      "title": "es_muted_processes_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_processes_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/count": {
      "abstract": [
        {
          "text": "The number of elements in the processes array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/count",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_processes_t/count"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_processes_t/init()"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/init(count:processes:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "processes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_muted_process_t",
          "text": "es_muted_process_t"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/init(count:processes:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(count:processes:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_processes_t/init(count:processes:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/processes": {
      "abstract": [
        {
          "text": "An array containing the muted processes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_muted_process_t",
          "text": "es_muted_process_t"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/processes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processes"
        }
      ],
      "role": "symbol",
      "title": "processes",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_processes_t/processes"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_paths(_:)": {
      "abstract": [
        {
          "text": "Frees resources associated with a set of previously-retrieved muted paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_release_muted_paths"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_muted_paths_t",
          "text": "es_muted_paths_t"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_paths(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_release_muted_paths"
        }
      ],
      "role": "symbol",
      "title": "es_release_muted_paths(_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_release_muted_paths(_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_processes(_:)": {
      "abstract": [
        {
          "text": "Frees resources associated with a set of previously-retrieved muted processes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_release_muted_processes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_muted_processes_t",
          "text": "es_muted_processes_t"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_processes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_release_muted_processes"
        }
      ],
      "role": "symbol",
      "title": "es_release_muted_processes(_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_release_muted_processes(_:)"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Muting-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process(_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process_events(_:_:_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_processes(_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_events(_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path(_:_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_events(_:_:_:_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_events(_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_paths(_:)"
      ],
      "title": "Muting Events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Muted-Processes",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/processes",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_process_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/count"
      ],
      "title": "Accessing Muted Processes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/init()",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/init(count:processes:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "es_muted_processes_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_processes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_processes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Muted-Processes",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/processes",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_process_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t/count"
              ],
              "title": "Accessing Muted Processes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Muting-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process(_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process_events(_:_:_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_processes(_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_events(_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path(_:_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_events(_:_:_:_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_events(_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_paths(_:)"
              ],
              "title": "Muting Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "es_muted_processes_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_paths_events(_:_:)/title",
          "value": "es_muted_paths_events"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_paths_events(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_paths_events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path(_:_:_:)/title",
          "value": "es_mute_path"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_t~1processes/title",
          "value": "processes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_t~1processes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "processes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_process_events(_:_:_:_:)/title",
          "value": "es_mute_process_events"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_process_events(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_process_events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_t~1count/title",
          "value": "count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_t~1count/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path_events(_:_:_:_:_:)/title",
          "value": "es_mute_path_events"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path_events(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_path_events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_release_muted_processes(_:)/title",
          "value": "es_release_muted_processes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_release_muted_processes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_release_muted_processes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_t/title",
          "value": "es_muted_processes_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_processes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_processes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_process(_:_:)/title",
          "value": "es_mute_process"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_process(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_process"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path_type_t/title",
          "value": "es_mute_path_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_path_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_path_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_release_muted_paths(_:)/title",
          "value": "es_release_muted_paths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_release_muted_paths(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_release_muted_paths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_process_t/title",
          "value": "es_muted_process_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_process_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_process_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_process_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_process_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_events(_:_:)/title",
          "value": "es_muted_processes_events"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_events(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_processes_events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_paths_t/title",
          "value": "es_muted_paths_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_paths_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_paths_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_paths_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_paths_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_muted_processes_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_muted_processes_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
