{
  "abstract": [
    {
      "text": "A type that describes a process, as delivered by an Endpoint Security message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@es_process_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "es_process_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "es_process_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "es_process_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "es_process_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For process events, this type also indicates the newly-executing process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can extract values such as the process identifier (",
              "type": "text"
            },
            {
              "code": "PID",
              "type": "codeVoice"
            },
            {
              "text": "), user identifier (",
              "type": "text"
            },
            {
              "code": "UID",
              "type": "codeVoice"
            },
            {
              "text": "), and group identifier (",
              "type": "text"
            },
            {
              "code": "GID",
              "type": "codeVoice"
            },
            {
              "text": ") from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/audit_token",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " field by using functions defined in ",
              "type": "text"
            },
            {
              "code": "libbsm.h",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Working-with-Code-Signing",
          "level": 3,
          "text": "Working with Code Signing",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Fields related to code signing, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/cdhash",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/signing_id",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", reflect the state of the process at the time Endpoint Security generated the message. In the specific case of process execution, this is after the ",
              "type": "text"
            },
            {
              "code": "exec",
              "type": "codeVoice"
            },
            {
              "text": " completes in the kernel, but before any code in the process starts executing. At that point, XNU has validated the signature itself and has verified that the ",
              "type": "text"
            },
            {
              "code": "cdhash",
              "type": "codeVoice"
            },
            {
              "text": " is correct. This second validation means that the hash of all individual page hashes in the Code Directory match the signed ",
              "type": "text"
            },
            {
              "code": "cdhash",
              "type": "codeVoice"
            },
            {
              "text": ", essentially verifying the signature wasn’t tampered with. However, XNU doesn’t verify individual page hashes until the binary executes and pages in the corresponding pages. XNU doesn’t determine a binary shows signs of tampering until the individual pages page in, at which point XNU updates the code signing flags.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Endpoint Security provides clients the current state of the CS flags in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/codesigning_flags",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " member of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure. Keep the following points in mind when evaluating this field:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "CS_VALID",
                      "type": "codeVoice"
                    },
                    {
                      "text": " bit in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/codesigning_flags",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " means that everything the kernel has validated up to that point in time was valid. However, this doesn’t mean there’s been a full validation of all the pages in the executable file. If a page’s content has been tampered with, XNU won’t know until that page pages in.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When XNU detects a tampered page, it clears the ",
                      "type": "text"
                    },
                    {
                      "code": "CS_VALID",
                      "type": "codeVoice"
                    },
                    {
                      "text": " bit. With the ",
                      "type": "text"
                    },
                    {
                      "code": "CS_KILL",
                      "type": "codeVoice"
                    },
                    {
                      "text": " bit set, Endpoint Security terminates the process, preventing the tampered code from executing. Platform binaries and binaries that opted into the hardened runtime typically have the ",
                      "type": "text"
                    },
                    {
                      "code": "CS_KILL",
                      "type": "codeVoice"
                    },
                    {
                      "text": " bit set.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you want your Endpoint Security client to detect tampered code before it pages in, such as at execution time, you can do so with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Security",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " framework. However, this may impose a significant performance cost.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Endpoint Security plays no role in verifying the validity of code signatures.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/Security"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_exec_t/target": {
      "abstract": [
        {
          "text": "The process to execute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_process_t",
          "text": "es_process_t"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_exec_t/target",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "target"
        }
      ],
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_exec_t/target"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t": {
      "abstract": [
        {
          "text": "A type that describes a process, as delivered by an Endpoint Security message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_process_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_process_t"
        }
      ],
      "role": "symbol",
      "title": "es_process_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/audit_token": {
      "abstract": [
        {
          "text": "A token for use with Basic Security Module auditing functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audit_token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/audit_token",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audit_token"
        }
      ],
      "role": "symbol",
      "title": "audit_token",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/audit_token"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/cdhash": {
      "abstract": [
        {
          "text": "The code directory hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cdhash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@es_cdhash_t",
          "text": "es_cdhash_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/cdhash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cdhash"
        }
      ],
      "role": "symbol",
      "title": "cdhash",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/cdhash"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/codesigning_flags": {
      "abstract": [
        {
          "text": "The flags used to sign the process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codesigning_flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/codesigning_flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "codesigning_flags"
        }
      ],
      "role": "symbol",
      "title": "codesigning_flags",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/codesigning_flags"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/executable": {
      "abstract": [
        {
          "text": "The file containing the executed process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "executable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_file_t",
          "text": "es_file_t"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/executable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executable"
        }
      ],
      "role": "symbol",
      "title": "executable",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/executable"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/group_id": {
      "abstract": [
        {
          "text": "The process group identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group_id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/group_id",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "group_id"
        }
      ],
      "role": "symbol",
      "title": "group_id",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/group_id"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/init(audit_token:ppid:original_ppid:group_id:session_id:codesigning_flags:is_platform_binary:is_es_client:cdhash:signing_id:team_id:executable:tty:start_time:responsible_audit_token:parent_audit_token:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "audit_token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ppid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "original_ppid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "group_id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "session_id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "codesigning_flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "is_platform_binary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "is_es_client"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cdhash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@es_cdhash_t",
          "text": "es_cdhash_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "signing_id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "team_id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "executable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_file_t",
          "text": "es_file_t"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "tty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_file_t",
          "text": "es_file_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "start_time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@timeval",
          "text": "timeval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "responsible_audit_token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "parent_audit_token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/init(audit_token:ppid:original_ppid:group_id:session_id:codesigning_flags:is_platform_binary:is_es_client:cdhash:signing_id:team_id:executable:tty:start_time:responsible_audit_token:parent_audit_token:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(audit_token:ppid:original_ppid:group_id:session_id:codesigning_flags:is_platform_binary:is_es_client:cdhash:signing_id:team_id:executable:tty:start_time:responsible_audit_token:parent_audit_token:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/init(audit_token:ppid:original_ppid:group_id:session_id:codesigning_flags:is_platform_binary:is_es_client:cdhash:signing_id:team_id:executable:tty:start_time:responsible_audit_token:parent_audit_token:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/is_es_client": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the process connects to the Endpoint Security subsystem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "is_es_client"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/is_es_client",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "is_es_client"
        }
      ],
      "role": "symbol",
      "title": "is_es_client",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/is_es_client"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/is_platform_binary": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the process is a platform binary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "is_platform_binary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/is_platform_binary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "is_platform_binary"
        }
      ],
      "role": "symbol",
      "title": "is_platform_binary",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/is_platform_binary"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/original_ppid": {
      "abstract": [
        {
          "text": "The original parent process ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "original_ppid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/original_ppid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "original_ppid"
        }
      ],
      "role": "symbol",
      "title": "original_ppid",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/original_ppid"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/parent_audit_token": {
      "abstract": [
        {
          "text": "The audit token of the parent process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parent_audit_token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/parent_audit_token",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parent_audit_token"
        }
      ],
      "role": "symbol",
      "title": "parent_audit_token",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/parent_audit_token"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/ppid": {
      "abstract": [
        {
          "text": "The parent process identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ppid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/ppid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ppid"
        }
      ],
      "role": "symbol",
      "title": "ppid",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/ppid"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/responsible_audit_token": {
      "abstract": [
        {
          "text": "The audit token of the process responsible for this process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "responsible_audit_token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/responsible_audit_token",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "responsible_audit_token"
        }
      ],
      "role": "symbol",
      "title": "responsible_audit_token",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/responsible_audit_token"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/session_id": {
      "abstract": [
        {
          "text": "The identifier of the session that contains the process group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session_id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/session_id",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session_id"
        }
      ],
      "role": "symbol",
      "title": "session_id",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/session_id"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/signing_id": {
      "abstract": [
        {
          "text": "The identifier used to sign the process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signing_id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/signing_id",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signing_id"
        }
      ],
      "role": "symbol",
      "title": "signing_id",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/signing_id"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/start_time": {
      "abstract": [
        {
          "text": "The time the process started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start_time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@timeval",
          "text": "timeval"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/start_time",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "start_time"
        }
      ],
      "role": "symbol",
      "title": "start_time",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/start_time"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/team_id": {
      "abstract": [
        {
          "text": "The team identifier used to sign the process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "team_id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/team_id",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "team_id"
        }
      ],
      "role": "symbol",
      "title": "team_id",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/team_id"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/tty": {
      "abstract": [
        {
          "text": "The TTY associated with the process sending the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_file_t",
          "text": "es_file_t"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/tty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tty"
        }
      ],
      "role": "symbol",
      "title": "tty",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t/tty"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Event-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_exec_t/target"
      ],
      "title": "Inspecting Event Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-the-Source-Process",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/audit_token",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/executable",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/is_es_client",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/is_platform_binary",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/start_time"
      ],
      "title": "Inspecting the Source Process"
    },
    {
      "anchor": "Inspecting-Process-IDs",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/ppid",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/original_ppid",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/group_id",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/session_id",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/tty"
      ],
      "title": "Inspecting Process IDs"
    },
    {
      "anchor": "Inspecting-Code-Signing-Properties",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/codesigning_flags",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/cdhash",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/signing_id",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/team_id"
      ],
      "title": "Inspecting Code Signing Properties"
    },
    {
      "anchor": "Inspecting-Audit-Tokens",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/responsible_audit_token",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/parent_audit_token"
      ],
      "title": "Inspecting Audit Tokens"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/init(audit_token:ppid:original_ppid:group_id:session_id:codesigning_flags:is_platform_binary:is_es_client:cdhash:signing_id:team_id:executable:tty:start_time:responsible_audit_token:parent_audit_token:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "es_process_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_process_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_process_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-the-Source-Process",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/audit_token",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/executable",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/is_es_client",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/is_platform_binary",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/start_time"
              ],
              "title": "Inspecting the Source Process"
            },
            {
              "anchor": "Inspecting-Process-IDs",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/ppid",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/original_ppid",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/group_id",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/session_id",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/tty"
              ],
              "title": "Inspecting Process IDs"
            },
            {
              "anchor": "Inspecting-Code-Signing-Properties",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/codesigning_flags",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/cdhash",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/signing_id",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/team_id"
              ],
              "title": "Inspecting Code Signing Properties"
            },
            {
              "anchor": "Inspecting-Audit-Tokens",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/responsible_audit_token",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t/parent_audit_token"
              ],
              "title": "Inspecting Audit Tokens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-Event-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_exec_t/target"
              ],
              "title": "Inspecting Event Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "es_process_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1group_id/title",
          "value": "group_id"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1group_id/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "group_id"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1ppid/title",
          "value": "ppid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1ppid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ppid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1original_ppid/title",
          "value": "original_ppid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1original_ppid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "original_ppid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1session_id/title",
          "value": "session_id"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1session_id/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "session_id"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1is_es_client/title",
          "value": "is_es_client"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1is_es_client/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "is_es_client"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1executable/title",
          "value": "executable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1executable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "executable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1team_id/title",
          "value": "team_id"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1team_id/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "team_id"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1responsible_audit_token/title",
          "value": "responsible_audit_token"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1responsible_audit_token/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "responsible_audit_token"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1audit_token/title",
          "value": "audit_token"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1audit_token/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audit_token"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1start_time/title",
          "value": "start_time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1start_time/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "start_time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1signing_id/title",
          "value": "signing_id"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1signing_id/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signing_id"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1codesigning_flags/title",
          "value": "codesigning_flags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1codesigning_flags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "codesigning_flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1cdhash/title",
          "value": "cdhash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1cdhash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cdhash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1tty/title",
          "value": "tty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1tty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1parent_audit_token/title",
          "value": "parent_audit_token"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1parent_audit_token/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parent_audit_token"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t/title",
          "value": "es_process_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_process_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_process_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1is_platform_binary/title",
          "value": "is_platform_binary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t~1is_platform_binary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "is_platform_binary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_exec_t~1target/title",
          "value": "target"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_exec_t~1target/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "target"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_process_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_process_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
