{
  "abstract": [
    {
      "text": "Frees resources associated with a set of previously-retrieved muted paths.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_paths(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@es_release_muted_paths",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "es_release_muted_paths"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@es_muted_paths_t",
        "text": "es_muted_paths_t"
      },
      {
        "kind": "text",
        "text": ">)"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "es_release_muted_paths"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "es_release_muted_paths(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "es_release_muted_paths"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "muted_paths"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@es_muted_paths_t",
              "text": "es_muted_paths_t"
            },
            {
              "kind": "text",
              "text": ">)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure, previously populated by a call to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_events(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", to release.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "muted_paths"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path(_:_:_:)": {
      "abstract": [
        {
          "text": "Suppresses events from executables that match a given path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_path"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_mute_path_type_t",
          "text": "es_mute_path_type_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_path"
        }
      ],
      "role": "symbol",
      "title": "es_mute_path(_:_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_path(_:_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_events(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Suppresses a subset of events from executables that match a given path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_path_events"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_mute_path_type_t",
          "text": "es_mute_path_type_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_events(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_path_events"
        }
      ],
      "role": "symbol",
      "title": "es_mute_path_events(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_path_events(_:_:_:_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_type_t": {
      "abstract": [
        {
          "text": "The type of a path argument, such as a prefix or a path literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_path_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_path_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_mute_path_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_path_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process(_:_:)": {
      "abstract": [
        {
          "text": "Suppresses events from a given process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_process"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_process"
        }
      ],
      "role": "symbol",
      "title": "es_mute_process(_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_process(_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process_events(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Suppresses a subset of events from a given process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_mute_process_events"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process_events(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_mute_process_events"
        }
      ],
      "role": "symbol",
      "title": "es_mute_process_events(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_mute_process_events(_:_:_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_events(_:_:)": {
      "abstract": [
        {
          "text": "Retrieve a list of all muted paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_muted_paths_events"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_muted_paths_t",
          "text": "es_muted_paths_t"
        },
        {
          "kind": "text",
          "text": ">>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_events(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_muted_paths_events"
        }
      ],
      "role": "symbol",
      "title": "es_muted_paths_events(_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_paths_events(_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t": {
      "abstract": [
        {
          "text": "A structure for a set of muted paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_muted_paths_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_muted_paths_t"
        }
      ],
      "role": "symbol",
      "title": "es_muted_paths_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_paths_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_events(_:_:)": {
      "abstract": [
        {
          "text": "Retrieve a list of all muted processes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_muted_processes_events"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_muted_processes_t",
          "text": "es_muted_processes_t"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_return_t",
          "text": "es_return_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_events(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_muted_processes_events"
        }
      ],
      "role": "symbol",
      "title": "es_muted_processes_events(_:_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_processes_events(_:_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t": {
      "abstract": [
        {
          "text": "A structure for a set of muted processes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_muted_processes_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_muted_processes_t"
        }
      ],
      "role": "symbol",
      "title": "es_muted_processes_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_muted_processes_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_paths(_:)": {
      "abstract": [
        {
          "text": "Frees resources associated with a set of previously-retrieved muted paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_release_muted_paths"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_muted_paths_t",
          "text": "es_muted_paths_t"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_paths(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_release_muted_paths"
        }
      ],
      "role": "symbol",
      "title": "es_release_muted_paths(_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_release_muted_paths(_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_processes(_:)": {
      "abstract": [
        {
          "text": "Frees resources associated with a set of previously-retrieved muted processes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_release_muted_processes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_muted_processes_t",
          "text": "es_muted_processes_t"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_processes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_release_muted_processes"
        }
      ],
      "role": "symbol",
      "title": "es_release_muted_processes(_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_release_muted_processes(_:)"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Muting-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process(_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process_events(_:_:_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_processes(_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_events(_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path(_:_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_events(_:_:_:_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_events(_:_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t"
      ],
      "title": "Muting Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "es_release_muted_paths"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_release_muted_paths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Muting-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process(_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_process_events(_:_:_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_release_muted_processes(_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_processes_events(_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path(_:_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_events(_:_:_:_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_mute_path_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_events(_:_:)",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t"
              ],
              "title": "Muting Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "es_release_muted_paths"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@es_muted_paths_t",
                    "text": "es_muted_paths_t"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "muted_paths"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_t",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " structure, previously populated by a call to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_muted_paths_events(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", to release.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "muted_paths"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path_type_t/title",
          "value": "es_mute_path_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_path_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_path_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_process(_:_:)/title",
          "value": "es_mute_process"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_process(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_process"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_release_muted_paths(_:)/title",
          "value": "es_release_muted_paths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_release_muted_paths(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_release_muted_paths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_release_muted_processes(_:)/title",
          "value": "es_release_muted_processes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_release_muted_processes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_release_muted_processes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_paths_events(_:_:)/title",
          "value": "es_muted_paths_events"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_paths_events(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_paths_events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path_events(_:_:_:_:_:)/title",
          "value": "es_mute_path_events"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path_events(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_path_events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_t/title",
          "value": "es_muted_processes_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_processes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_processes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path(_:_:_:)/title",
          "value": "es_mute_path"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_path(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_process_events(_:_:_:_:)/title",
          "value": "es_mute_process_events"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_mute_process_events(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_mute_process_events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_paths_t/title",
          "value": "es_muted_paths_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_paths_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_paths_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_paths_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_paths_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_events(_:_:)/title",
          "value": "es_muted_processes_events"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_muted_processes_events(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_muted_processes_events"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_release_muted_paths(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_release_muted_paths(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
