{
  "abstract": [
    {
      "text": "ess_tcc_authorization_reason_t",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@es_tcc_authorization_reason_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "es_tcc_authorization_reason_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "es_tcc_authorization_reason_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "es_tcc_authorization_reason_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_reason_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Represents the reason a TCC permission was updated.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_app_type_policy"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ENTITLED": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_ENTITLED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ENTITLED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_ENTITLED"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_ENTITLED",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_entitled"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_ERROR"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_ERROR",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_error"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MDM_POLICY": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_MDM_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MDM_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_MDM_POLICY"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_MDM_POLICY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_mdm_policy"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_missing_usage_string"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_NONE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_NONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_NONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_NONE"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_NONE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_none"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_preflight_unknown"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_prompt_cancel"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_prompt_timeout"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_service_override_policy"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_service_policy"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET": {
      "abstract": [
        {
          "text": "User changed the authorization right via Preferences",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_system_set"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_CONSENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_USER_CONSENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_CONSENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_USER_CONSENT"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_USER_CONSENT",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_user_consent"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_SET": {
      "abstract": [
        {
          "text": "User answered a prompt",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_USER_SET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_SET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_USER_SET"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_USER_SET",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_user_set"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t": {
      "abstract": [
        {
          "text": "ess_tcc_authorization_reason_t",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "role": "symbol",
      "title": "es_tcc_authorization_reason_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_t/init(_:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_t/init(rawvalue:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_t/rawvalue"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t/init(_:)",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t/rawValue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "es_tcc_authorization_reason_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ENTITLED",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ERROR",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MDM_POLICY",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_NONE",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_CONSENT",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_SET"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "es_tcc_authorization_reason_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_USER_CONSENT/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_USER_CONSENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_USER_CONSENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_USER_CONSENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_ERROR/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_MDM_POLICY/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_MDM_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_MDM_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_MDM_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_reason_t/title",
          "value": "es_tcc_authorization_reason_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_reason_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_reason_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_USER_SET/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_USER_SET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_USER_SET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_USER_SET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_NONE/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_NONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_NONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_NONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_ENTITLED/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_ENTITLED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_ENTITLED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_ENTITLED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_tcc_authorization_reason_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_tcc_authorization_reason_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
