{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@es_tcc_authorization_right_t@ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
        "text": "es_tcc_authorization_right_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
              "text": "es_tcc_authorization_right_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_learn_more"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t": {
      "abstract": [
        {
          "text": "ess_tcc_authorization_right_t",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "role": "symbol",
      "title": "es_tcc_authorization_right_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE/title",
          "value": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_right_t/title",
          "value": "es_tcc_authorization_right_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_right_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_right_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_right_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_right_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_tcc_authorization_right_learn_more"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_tcc_authorization_right_learn_more"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
