{
  "abstract": [
    {
      "text": "An RGB565 format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit",
        "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/RGB565"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GLKViewDrawableColorFormat@GLKViewDrawableColorFormatRGB565",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "RGB565"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKViewDrawableColorFormatRGB565"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GLKViewDrawableColorFormat.RGB565"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "RGB565"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat": {
      "abstract": [
        {
          "text": "The format of the color renderbuffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKViewDrawableColorFormat"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKViewDrawableColorFormat"
        }
      ],
      "role": "symbol",
      "title": "GLKViewDrawableColorFormat",
      "type": "topic",
      "url": "/documentation/glkit/glkviewdrawablecolorformat"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/RGB565": {
      "abstract": [
        {
          "text": "An RGB565 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RGB565"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/RGB565",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKViewDrawableColorFormatRGB565"
        }
      ],
      "role": "symbol",
      "title": "GLKViewDrawableColorFormat.RGB565",
      "type": "topic",
      "url": "/documentation/glkit/glkviewdrawablecolorformat/rgb565"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/RGBA8888": {
      "abstract": [
        {
          "text": "An RGBA8888 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RGBA8888"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/RGBA8888",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKViewDrawableColorFormatRGBA8888"
        }
      ],
      "role": "symbol",
      "title": "GLKViewDrawableColorFormat.RGBA8888",
      "type": "topic",
      "url": "/documentation/glkit/glkviewdrawablecolorformat/rgba8888"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/SRGBA8888": {
      "abstract": [
        {
          "text": "An sRGBA8888 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRGBA8888"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/SRGBA8888",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKViewDrawableColorFormatSRGBA8888"
        }
      ],
      "role": "symbol",
      "title": "GLKViewDrawableColorFormat.SRGBA8888",
      "type": "topic",
      "url": "/documentation/glkit/glkviewdrawablecolorformat/srgba8888"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/RGBA8888",
        "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/SRGBA8888"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKViewDrawableColorFormatRGB565"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableColorFormatRGB565"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit",
                "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/RGBA8888",
                "doc://com.apple.glkit/documentation/GLKit/GLKViewDrawableColorFormat/SRGBA8888"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GLKViewDrawableColorFormatRGB565"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat~1SRGBA8888/title",
          "value": "GLKViewDrawableColorFormatSRGBA8888"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat~1SRGBA8888/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableColorFormatSRGBA8888"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat~1RGBA8888/title",
          "value": "GLKViewDrawableColorFormatRGBA8888"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat~1RGBA8888/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableColorFormatRGBA8888"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat~1RGB565/title",
          "value": "GLKViewDrawableColorFormatRGB565"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat~1RGB565/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableColorFormatRGB565"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat/title",
          "value": "GLKViewDrawableColorFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableColorFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKViewDrawableColorFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKViewDrawableColorFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glkviewdrawablecolorformat/rgb565"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glkviewdrawablecolorformat/rgb565"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
