{
  "abstract": [
    {
      "text": "Asks Apple to attest to the validity of a generated cryptographic key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/attestKey(_:clientDataHash:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)DCAppAttestService(im)attestKey:clientDataHash:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "attestKey"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "clientDataHash"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DataV",
        "text": "Data"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DataV",
        "text": "Data"
      },
      {
        "kind": "text",
        "text": "?, (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "DeviceCheck"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "attestKey:clientDataHash:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "attestKey(_:clientDataHash:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "attestKey"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "keyId"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "clientDataHash"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DataV",
              "text": "Data"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DataV",
              "text": "Data"
            },
            {
              "kind": "text",
              "text": "?, (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "attestKey"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "keyId"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "clientDataHash"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DataV",
              "text": "Data"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DataV",
              "text": "Data"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identifier you received when generating a cryptographic key by",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "calling the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/generateKey(completionHandler:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "keyId"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A SHA256 hash of a unique, single-use data block that",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "embeds a challenge from your server. Should be at least 16 bytes in length.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "clientDataHash"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A closure that the method calls upon completion with",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "the following parameters:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "code": "attestationObject",
                          "type": "codeVoice"
                        },
                        {
                          "text": ": A statement from Apple about the validity of the key",
                          "type": "text"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "text": "associated with ",
                          "type": "text"
                        },
                        {
                          "code": "keyId",
                          "type": "codeVoice"
                        },
                        {
                          "text": ". Send this to your server for processing.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "code": "error",
                          "type": "codeVoice"
                        },
                        {
                          "text": ": A ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCError-swift.struct",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " instance that indicates the reason for",
                          "type": "text"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "text": "failure, or ",
                          "type": "text"
                        },
                        {
                          "code": "nil",
                          "type": "codeVoice"
                        },
                        {
                          "text": " on success.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                }
              ],
              "type": "unorderedList"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/preparing-to-use-the-app-attest-service"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "You can call this method from synchronous code using a completion handler,",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "as shown on this page, or you can call it as an asynchronous method that has the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "following declaration:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "code": [
                "func attestKey(_ keyId: String, clientDataHash: Data) async throws -> Data"
              ],
              "syntax": "swift",
              "type": "codeListing"
            },
            {
              "inlineContent": [
                {
                  "text": "For information about concurrency and asynchronous code in Swift, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Concurrency Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "This method asks Apple to attest to the validity of a key that you",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "previously generated with a call to the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/generateKey(completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Provide the method with both the key identifier and a computed hash of a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "data block that includes a one-time challenge from your server to prevent",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "replay attacks. For example, you can use CryptoKit to create a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CryptoKit/SHA256",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " hash of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "challenge data:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import CryptoKit let hash = Data(SHA256.hash(data: challenge)) // A",
            "challenge from your server."
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The attest method calls its completion handler to return an attestation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "object to you, which you must send to your server for verification. A",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "compromised version of your app could falsify the verification result, thus",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "circumventing App Attest.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you successfully verify the attestation object on your server, as",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", then you can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "associate the key identifier with the user on the device for future",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "reference. You’ll need the identifier to generate assertions with calls to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/generateAssertion(_:clientDataHash:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If your server fails to verify the attestation object, discard the key",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "identifier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the method’s completion handler returns the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCError-swift.struct/serverUnavailable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " error — typically due to network",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "connectivity issues — it means that the framework failed to reach the App",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Attest service to complete the attestation. In this case, retry attestation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "again using the same key and client data hash later to avoid unnecessarily",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "generating new keys. Retrying with the same inputs helps to preserve the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "risk metric for a given device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck": {
      "abstract": [
        {
          "text": "Reduce fraudulent use of your services by managing device state and asserting app",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "integrity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck",
      "kind": "symbol",
      "role": "collection",
      "title": "DeviceCheck",
      "type": "topic",
      "url": "/documentation/devicecheck"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService": {
      "abstract": [
        {
          "text": "A service that you use to validate the instance of your app running on a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DCAppAttestService"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DCAppAttestService"
        }
      ],
      "role": "symbol",
      "title": "DCAppAttestService",
      "type": "topic",
      "url": "/documentation/devicecheck/dcappattestservice"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/attestKey(_:clientDataHash:completionHandler:)": {
      "abstract": [
        {
          "text": "Asks Apple to attest to the validity of a generated cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attestKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/attestKey(_:clientDataHash:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attestKey:clientDataHash:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "attestKey(_:clientDataHash:completionHandler:)",
      "type": "topic",
      "url": "/documentation/devicecheck/dcappattestservice/attestkey(_:clientdatahash:completionhandler:)"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/generateAssertion(_:clientDataHash:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a block of data that demonstrates the legitimacy of an instance of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your app running on a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generateAssertion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/generateAssertion(_:clientDataHash:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "generateAssertion:clientDataHash:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "generateAssertion(_:clientDataHash:completionHandler:)",
      "type": "topic",
      "url": "/documentation/devicecheck/dcappattestservice/generateassertion(_:clientdatahash:completionhandler:)"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/generateKey(completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a new cryptographic key for use with the App Attest service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generateKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/generateKey(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "generateKeyWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "generateKey(completionHandler:)",
      "type": "topic",
      "url": "/documentation/devicecheck/dcappattestservice/generatekey(completionhandler:)"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCError-swift.struct": {
      "abstract": [
        {
          "text": "A type that indicates when DeviceCheck encounters an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DCError"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DCError"
        }
      ],
      "role": "symbol",
      "title": "DCError",
      "type": "topic",
      "url": "/documentation/devicecheck/dcerror-swift.struct"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCError-swift.struct/serverUnavailable": {
      "abstract": [
        {
          "text": "An error that indicates a failed attempt to contact the App Attest service during an attestation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7DCErrorLeV",
          "text": "DCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@DCError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCError-swift.struct/serverUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "serverUnavailable",
      "type": "topic",
      "url": "/documentation/devicecheck/dcerror-swift.struct/serverunavailable"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity": {
      "abstract": [
        {
          "text": "Ensure that requests your server receives come from legitimate instances of your",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity",
      "kind": "article",
      "role": "article",
      "title": "Establishing your app’s integrity",
      "type": "topic",
      "url": "/documentation/devicecheck/establishing-your-app-s-integrity"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/preparing-to-use-the-app-attest-service": {
      "abstract": [
        {
          "text": "Test your implementation in a development environment and onboard users gradually.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/preparing-to-use-the-app-attest-service",
      "kind": "article",
      "role": "article",
      "title": "Preparing to use the app attest service",
      "type": "topic",
      "url": "/documentation/devicecheck/preparing-to-use-the-app-attest-service"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server": {
      "abstract": [
        {
          "text": "Verify that connections to your server come from legitimate instances of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server",
      "kind": "article",
      "role": "article",
      "title": "Validating apps that connect to your server",
      "type": "topic",
      "url": "/documentation/devicecheck/validating-apps-that-connect-to-your-server"
    },
    "doc://com.apple.documentation/documentation/CryptoKit/SHA256": {
      "abstract": [
        {
          "text": "An implementation of Secure Hashing Algorithm 2 (SHA-2) hashing with a 256-bit digest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA256"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CryptoKit/SHA256",
      "kind": "symbol",
      "role": "symbol",
      "title": "SHA256",
      "type": "topic",
      "url": "/documentation/CryptoKit/SHA256"
    },
    "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously": {
      "abstract": [
        {
          "text": "Learn how functions and methods that take a completion handler are converted to Swift asynchronous functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
      "kind": "article",
      "role": "article",
      "title": "Calling Objective-C APIs Asynchronously",
      "type": "topic",
      "url": "/documentation/Swift/calling-objective-c-apis-asynchronously"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DataV": {
      "abstract": [
        {
          "text": "A byte buffer in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Data",
      "type": "topic",
      "url": "/documentation/foundation/data"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Preparing-a-key",
      "generated": true,
      "identifiers": [
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/generateKey(completionHandler:)"
      ],
      "title": "Preparing a key"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "attestKey:clientDataHash:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attestKey:clientDataHash:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck",
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Preparing-a-key",
              "generated": true,
              "identifiers": [
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/generateKey(completionHandler:)"
              ],
              "title": "Preparing a key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "attestKey:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "keyId"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "clientDataHash:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSData",
                    "text": "NSData"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "clientDataHash"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSData",
                    "text": "NSData"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "attestationObject"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The identifier you received when generating a cryptographic key by",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "calling the",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/generateKey(completionHandler:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " method.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "keyId"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A SHA256 hash of a unique, single-use data block that",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "embeds a challenge from your server. Should be at least 16 bytes in length.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "clientDataHash"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A closure that the method calls upon completion with",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "the following parameters:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "code": "attestationObject",
                                "type": "codeVoice"
                              },
                              {
                                "text": ": A statement from Apple about the validity of the key",
                                "type": "text"
                              },
                              {
                                "text": " ",
                                "type": "text"
                              },
                              {
                                "text": "associated with ",
                                "type": "text"
                              },
                              {
                                "code": "keyId",
                                "type": "codeVoice"
                              },
                              {
                                "text": ". Send this to your server for processing.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "code": "error",
                                "type": "codeVoice"
                              },
                              {
                                "text": ": A ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCError-swift.struct",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " instance that indicates the reason for",
                                "type": "text"
                              },
                              {
                                "text": " ",
                                "type": "text"
                              },
                              {
                                "text": "failure, or ",
                                "type": "text"
                              },
                              {
                                "code": "nil",
                                "type": "codeVoice"
                              },
                              {
                                "text": " on success.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      }
                    ],
                    "type": "unorderedList"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService~1generateAssertion(_:clientDataHash:completionHandler:)/title",
          "value": "generateAssertion:clientDataHash:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService~1generateAssertion(_:clientDataHash:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "generateAssertion:clientDataHash:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService/title",
          "value": "DCAppAttestService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DCAppAttestService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DCAppAttestService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService~1generateKey(completionHandler:)/title",
          "value": "generateKeyWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService~1generateKey(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "generateKeyWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService~1attestKey(_:clientDataHash:completionHandler:)/title",
          "value": "attestKey:clientDataHash:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService~1attestKey(_:clientDataHash:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attestKey:clientDataHash:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/devicecheck/dcappattestservice/attestkey(_:clientdatahash:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/devicecheck/dcappattestservice/attestkey(_:clientdatahash:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
