{
  "abstract": [
    {
      "text": "An event type that represents a MIDI channel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/midiChannel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVMIDIMetaEventType@AVMIDIMetaEventTypeMidiChannel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "midiChannel"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMIDIMetaEventTypeMidiChannel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVMIDIMetaEvent.EventType.midiChannel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "midiChannel"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent": {
      "abstract": [
        {
          "text": "An object that represents MIDI meta event messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEvent"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType": {
      "abstract": [
        {
          "text": "Constants that represent the types of meta events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/copyright": {
      "abstract": [
        {
          "text": "An event type that represents a copyright.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyright"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/copyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeCopyright"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.copyright",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/copyright"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/cuePoint": {
      "abstract": [
        {
          "text": "An event type that represents a cue point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cuePoint"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/cuePoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeCuePoint"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.cuePoint",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/cuepoint"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/endOfTrack": {
      "abstract": [
        {
          "text": "An event type that represents the end of the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endOfTrack"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/endOfTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeEndOfTrack"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.endOfTrack",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/endoftrack"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/instrument": {
      "abstract": [
        {
          "text": "An event type that represents an instrument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instrument"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/instrument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeInstrument"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.instrument",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/instrument"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/keySignature": {
      "abstract": [
        {
          "text": "An event type that represents a key signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keySignature"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/keySignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeKeySignature"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.keySignature",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/keysignature"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/lyric": {
      "abstract": [
        {
          "text": "An event type that represents a lyric.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lyric"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/lyric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeLyric"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.lyric",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/lyric"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/marker": {
      "abstract": [
        {
          "text": "An event type that represents a marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "marker"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/marker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeMarker"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.marker",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/marker"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/midiChannel": {
      "abstract": [
        {
          "text": "An event type that represents a MIDI channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiChannel"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/midiChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeMidiChannel"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.midiChannel",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/midichannel"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/midiPort": {
      "abstract": [
        {
          "text": "An event type that represents a MIDI port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiPort"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/midiPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeMidiPort"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.midiPort",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/midiport"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/proprietaryEvent": {
      "abstract": [
        {
          "text": "An event type that represents a proprietary event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proprietaryEvent"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/proprietaryEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeProprietaryEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.proprietaryEvent",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/proprietaryevent"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/sequenceNumber": {
      "abstract": [
        {
          "text": "An event type that represents a sequence number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sequenceNumber"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/sequenceNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeSequenceNumber"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.sequenceNumber",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/sequencenumber"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/smpteOffset": {
      "abstract": [
        {
          "text": "An event type that represents a SMPTE time offset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smpteOffset"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/smpteOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeSmpteOffset"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.smpteOffset",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/smpteoffset"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/tempo": {
      "abstract": [
        {
          "text": "An event type that represents a tempo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tempo"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/tempo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeTempo"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.tempo",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/tempo"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/text": {
      "abstract": [
        {
          "text": "An event type that represents text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeText"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.text",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/text"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/timeSignature": {
      "abstract": [
        {
          "text": "An event type that represents a time signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeSignature"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/timeSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeTimeSignature"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.timeSignature",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/timesignature"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/trackName": {
      "abstract": [
        {
          "text": "An event type that represents a track name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackName"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/trackName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIMetaEventTypeTrackName"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIMetaEvent.EventType.trackName",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidimetaevent/eventtype/trackname"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Event-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/copyright",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/cuePoint",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/endOfTrack",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/instrument",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/keySignature",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/lyric",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/marker",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/midiPort",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/proprietaryEvent",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/sequenceNumber",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/smpteOffset",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/tempo",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/text",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/timeSignature",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/trackName"
      ],
      "title": "Event Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMIDIMetaEventTypeMidiChannel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeMidiChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Event-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/copyright",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/cuePoint",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/endOfTrack",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/instrument",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/keySignature",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/lyric",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/marker",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/midiPort",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/proprietaryEvent",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/sequenceNumber",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/smpteOffset",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/tempo",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/text",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/timeSignature",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIMetaEvent/EventType/trackName"
              ],
              "title": "Event Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVMIDIMetaEventTypeMidiChannel"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1midiPort/title",
          "value": "AVMIDIMetaEventTypeMidiPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1midiPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeMidiPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1midiChannel/title",
          "value": "AVMIDIMetaEventTypeMidiChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1midiChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeMidiChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1tempo/title",
          "value": "AVMIDIMetaEventTypeTempo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1tempo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeTempo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1timeSignature/title",
          "value": "AVMIDIMetaEventTypeTimeSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1timeSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeTimeSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1text/title",
          "value": "AVMIDIMetaEventTypeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1endOfTrack/title",
          "value": "AVMIDIMetaEventTypeEndOfTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1endOfTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeEndOfTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1proprietaryEvent/title",
          "value": "AVMIDIMetaEventTypeProprietaryEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1proprietaryEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeProprietaryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1keySignature/title",
          "value": "AVMIDIMetaEventTypeKeySignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1keySignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeKeySignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1instrument/title",
          "value": "AVMIDIMetaEventTypeInstrument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1instrument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeInstrument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1lyric/title",
          "value": "AVMIDIMetaEventTypeLyric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1lyric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeLyric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType/title",
          "value": "AVMIDIMetaEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1trackName/title",
          "value": "AVMIDIMetaEventTypeTrackName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1trackName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeTrackName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1marker/title",
          "value": "AVMIDIMetaEventTypeMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1marker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1copyright/title",
          "value": "AVMIDIMetaEventTypeCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1copyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1cuePoint/title",
          "value": "AVMIDIMetaEventTypeCuePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1cuePoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeCuePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1sequenceNumber/title",
          "value": "AVMIDIMetaEventTypeSequenceNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1sequenceNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeSequenceNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent/title",
          "value": "AVMIDIMetaEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1smpteOffset/title",
          "value": "AVMIDIMetaEventTypeSmpteOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIMetaEvent~1EventType~1smpteOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIMetaEventTypeSmpteOffset"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avmidimetaevent/eventtype/midichannel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avmidimetaevent/eventtype/midichannel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
