{
  "abstract": [
    {
      "text": "A record of the source from which an altitude came.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitudeSource-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARGeoAnchor(py)altitudeSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "altitudeSource"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARGeoAnchor",
        "text": "ARGeoAnchor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ARAltitudeSource",
        "text": "AltitudeSource"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "altitudeSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "altitudeSource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "altitudeSource"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARGeoAnchor",
              "text": "ARGeoAnchor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ARAltitudeSource",
              "text": "AltitudeSource"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/userDefined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if you set the altitude yourself (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession/getGeoLocation(forPoint:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app doesn’t set the altitude, ARKit populates this property to indicate the altitude’s expected accuracy (either ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/precise",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/coarse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), depending on the level of confidence ARKit has with the altitude data that’s available at the time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor": {
      "abstract": [
        {
          "text": "An anchor that identifies a geographic location using latitude, longitude, and altitude data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARGeoAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum": {
      "abstract": [
        {
          "text": "Options for setting a location anchor’s altitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AltitudeSource"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AltitudeSource"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor.AltitudeSource",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitudesource-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/coarse": {
      "abstract": [
        {
          "text": "The framework sets the altitude using a coarse digital-elevation model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coarse"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/coarse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAltitudeSourceCoarse"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor.AltitudeSource.coarse",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitudesource-swift.enum/coarse"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/precise": {
      "abstract": [
        {
          "text": "The framework sets the altitude using a high-resolution digital-elevation model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "precise"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/precise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAltitudeSourcePrecise"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor.AltitudeSource.precise",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitudesource-swift.enum/precise"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/userDefined": {
      "abstract": [
        {
          "text": "The app defines the altitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDefined"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/userDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAltitudeSourceUserDefined"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor.AltitudeSource.userDefined",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitudesource-swift.enum/userdefined"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitude-89k4x": {
      "abstract": [
        {
          "text": "Vertical distance, in meters, between this anchor and sea level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "altitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitude-89k4x",
      "kind": "symbol",
      "role": "symbol",
      "title": "altitude",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitude-89k4x"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitude-9kges": {
      "abstract": [
        {
          "text": "Vertical distance, in meters, between this anchor and sea level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "altitude"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitude-9kges",
      "kind": "symbol",
      "role": "symbol",
      "title": "altitude",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitude-9kges"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitudeSource-swift.property": {
      "abstract": [
        {
          "text": "A record of the source from which an altitude came.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "altitudeSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARGeoAnchor",
          "text": "ARGeoAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARAltitudeSource",
          "text": "AltitudeSource"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitudeSource-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "altitudeSource"
        }
      ],
      "role": "symbol",
      "title": "altitudeSource",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitudesource-swift.property"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSession/getGeoLocation(forPoint:completionHandler:)": {
      "abstract": [
        {
          "text": "Converts a position in the framework’s local coordinate system to latitude, longitude and altitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getGeoLocation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float3",
          "text": "simd_float3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession/getGeoLocation(forPoint:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getGeoLocationForPoint:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getGeoLocation(forPoint:completionHandler:)",
      "type": "topic",
      "url": "/documentation/arkit/arsession/getgeolocation(forpoint:completionhandler:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defining-Altitude",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitude-89k4x",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum"
      ],
      "title": "Defining Altitude"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "altitudeSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "altitudeSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Defining-Altitude",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitude-9kges",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum"
              ],
              "title": "Defining Altitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@ARAltitudeSource",
                    "text": "ARAltitudeSource"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "altitudeSource"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1altitudeSource-swift.property/title",
          "value": "altitudeSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1altitudeSource-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "altitudeSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1coarse/title",
          "value": "ARAltitudeSourceCoarse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1coarse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSourceCoarse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum/title",
          "value": "ARAltitudeSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1getGeoLocation(forPoint:completionHandler:)/title",
          "value": "getGeoLocationForPoint:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1getGeoLocation(forPoint:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getGeoLocationForPoint:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor/title",
          "value": "ARGeoAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1userDefined/title",
          "value": "ARAltitudeSourceUserDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1userDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSourceUserDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1precise/title",
          "value": "ARAltitudeSourcePrecise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1precise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSourcePrecise"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/argeoanchor/altitudesource-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/argeoanchor/altitudesource-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
