{
  "abstract": [
    {
      "text": "Initializes a named location anchor with the given coordinates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/initWithName:coordinate:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARGeoAnchor(im)initWithName:coordinate:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "initWithName:coordinate:"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithName:coordinate:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "initWithName:coordinate:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithName:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "coordinate:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
              "text": "CLLocationCoordinate2D"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "coordinate"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Name of the anchor.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "name"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Lattitude and longitude of the anchor’s geographic location.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "coordinate"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Because this initializer does not take an altitude argument, ARKit will determine (and set) the anchor’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitude-9kges",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " at runtime.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor": {
      "abstract": [
        {
          "text": "An anchor that identifies a geographic location using latitude, longitude, and altitude data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARGeoAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitude-9kges": {
      "abstract": [
        {
          "text": "Vertical distance, in meters, between this anchor and sea level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "altitude"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/altitude-9kges",
      "kind": "symbol",
      "role": "symbol",
      "title": "altitude",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitude-9kges"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/init(name:coordinate:altitude:)-8sbh4": {
      "abstract": [
        {
          "text": "Initializes a named location anchor with the given coordinates and altitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "coordinate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "altitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/init(name:coordinate:altitude:)-8sbh4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:coordinate:altitude:"
        }
      ],
      "role": "symbol",
      "title": "init(name:coordinate:altitude:)",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/init(name:coordinate:altitude:)-8sbh4"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/initWithCoordinate:": {
      "abstract": [
        {
          "text": "Initializes a new location anchor with the given coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCoordinate:"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/initWithCoordinate:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoordinate:"
        }
      ],
      "role": "symbol",
      "title": "initWithCoordinate:",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/initwithcoordinate:"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/initWithCoordinate:altitude:": {
      "abstract": [
        {
          "text": "Initializes a location anchor with the given coordinate and altitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCoordinate:altitude:"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/initWithCoordinate:altitude:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoordinate:altitude:"
        }
      ],
      "role": "symbol",
      "title": "initWithCoordinate:altitude:",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/initwithcoordinate:altitude:"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/initWithName:coordinate:": {
      "abstract": [
        {
          "text": "Initializes a named location anchor with the given coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithName:coordinate:"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/initWithName:coordinate:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:coordinate:"
        }
      ],
      "role": "symbol",
      "title": "initWithName:coordinate:",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/initwithname:coordinate:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D": {
      "abstract": [
        {
          "text": "The latitude and longitude associated with a location, specified using the WGS 84 reference frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLLocationCoordinate2D",
      "type": "topic",
      "url": "/documentation/CoreLocation/CLLocationCoordinate2D"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Geo-Anchor",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/initWithCoordinate:",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/initWithCoordinate:altitude:",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/init(name:coordinate:altitude:)-8sbh4"
      ],
      "title": "Creating a Geo Anchor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1init(name:coordinate:altitude:)-8sbh4/title",
          "value": "initWithName:coordinate:altitude:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1init(name:coordinate:altitude:)-8sbh4/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:coordinate:altitude:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@CLLocationCoordinate2D/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor/title",
          "value": "ARGeoAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/argeoanchor/initwithname:coordinate:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
