{
  "abstract": [
    {
      "text": "Called by the app when a tab is moved to fire appropriate events with only this extension.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext/didMoveTab(_:from:in:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "WebKit",
    "externalID": "s:So21WKWebExtensionContextC6WebKitE10didMoveTab_4from2inySo0abH0_p_SiSo0aB6Window_pSgtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "didMoveTab"
      },
      {
        "kind": "text",
        "text": "(any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)WKWebExtensionTab",
        "text": "WKWebExtensionTab"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "from"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "in"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)WKWebExtensionWindow",
        "text": "WKWebExtensionWindow"
      },
      {
        "kind": "text",
        "text": ")?)"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "didMoveTab(_:from:in:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didMoveTab"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "movedTab"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionTab",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)WKWebExtensionTab",
              "text": "WKWebExtensionTab"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "index"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "in"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "oldWindow"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionWindow",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)WKWebExtensionWindow",
              "text": "WKWebExtensionWindow"
            },
            {
              "kind": "text",
              "text": ")? = nil)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tab that was moved.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "movedTab"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The old index of the tab within the window.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "index"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The window that the tab was moved from, or ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " if the tab isn’t moving from an open window.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "oldWindow"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the window is staying the same, the current window should be specified. This method informs only the specific extension that a tab has been moved. If the intention is to inform all loaded extensions consistently, you should use the respective method on the extension controller instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext": {
      "abstract": [
        {
          "text": "An object that represents the runtime environment for a web extension.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtensionContext",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextensioncontext"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext/didMoveTab(_:from:in:)": {
      "abstract": [
        {
          "text": "Called by the app when a tab is moved to fire appropriate events with only this extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didMoveTab"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKWebExtensionTab",
          "text": "WKWebExtensionTab"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKWebExtensionWindow",
          "text": "WKWebExtensionWindow"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext/didMoveTab(_:from:in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "didMoveTab(_:from:in:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextensioncontext/didmovetab(_:from:in:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionTab": {
      "abstract": [
        {
          "text": "A protocol with methods that represent a tab to web extensions.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebExtensionTab"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionTab"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtensionTab",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextensiontab"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionWindow": {
      "abstract": [
        {
          "text": "A protocol with methods that represent a window to web extensions.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebExtensionWindow"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionWindow"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtensionWindow",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextensionwindow"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionContext/title",
          "value": "WKWebExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionWindow/title",
          "value": "WKWebExtensionWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionTab/title",
          "value": "WKWebExtensionTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionTab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionTab"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebextensioncontext/didmovetab(_:from:in:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
