{
  "abstract": [
    {
      "text": "The event flags changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/flagsChanged"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSEventType@NSEventTypeFlagsChanged",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "flagsChanged"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSEventTypeFlagsChanged"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSEvent.EventType.flagsChanged"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "flagsChanged"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType": {
      "abstract": [
        {
          "text": "Constants for the types of events that responder objects can handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined": {
      "abstract": [
        {
          "text": "An AppKit-related event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appKitDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeAppKitDefined"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.appKitDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/appkitdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/applicationDefined": {
      "abstract": [
        {
          "text": "An app-defined event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/applicationDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeApplicationDefined"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.applicationDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/applicationdefined"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/cursorUpdate": {
      "abstract": [
        {
          "text": "An event that updates the cursor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursorUpdate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/cursorUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeCursorUpdate"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.cursorUpdate",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/cursorupdate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/flagsChanged": {
      "abstract": [
        {
          "text": "The event flags changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flagsChanged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/flagsChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeFlagsChanged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.flagsChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/flagschanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/periodic": {
      "abstract": [
        {
          "text": "An event that provides execution time to periodic tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "periodic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/periodic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypePeriodic"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.periodic",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/periodic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/quickLook": {
      "abstract": [
        {
          "text": "An event that initiates a Quick Look request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickLook"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/quickLook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeQuickLook"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.quickLook",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/quicklook"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined": {
      "abstract": [
        {
          "text": "A system-related event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemDefined"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeSystemDefined"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.systemDefined",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/systemdefined"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-System-Event-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/applicationDefined",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/cursorUpdate",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/periodic",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/quickLook",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined"
      ],
      "title": "Getting System Event Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSEventTypeFlagsChanged"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeFlagsChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-System-Event-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/appKitDefined",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/applicationDefined",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/cursorUpdate",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/periodic",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/quickLook",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/systemDefined"
              ],
              "title": "Getting System Event Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSEventTypeFlagsChanged"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1periodic/title",
          "value": "NSEventTypePeriodic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1periodic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypePeriodic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/title",
          "value": "NSEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1systemDefined/title",
          "value": "NSEventTypeSystemDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1systemDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeSystemDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1flagsChanged/title",
          "value": "NSEventTypeFlagsChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1flagsChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeFlagsChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1applicationDefined/title",
          "value": "NSEventTypeApplicationDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1applicationDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeApplicationDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1cursorUpdate/title",
          "value": "NSEventTypeCursorUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1cursorUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeCursorUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1appKitDefined/title",
          "value": "NSEventTypeAppKitDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1appKitDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeAppKitDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1quickLook/title",
          "value": "NSEventTypeQuickLook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1quickLook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeQuickLook"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/eventtype/flagschanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/eventtype/flagschanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
