{
  "abstract": [
    {
      "text": "The user moved the mouse while holding down the left mouse button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDragged"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSEventType@NSEventTypeLeftMouseDragged",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "leftMouseDragged"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSEventTypeLeftMouseDragged"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSEvent.EventType.leftMouseDragged"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "leftMouseDragged"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType": {
      "abstract": [
        {
          "text": "Constants for the types of events that responder objects can handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDown": {
      "abstract": [
        {
          "text": "The user pressed the left mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeLeftMouseDown"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.leftMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/leftmousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDragged": {
      "abstract": [
        {
          "text": "The user moved the mouse while holding down the left mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDragged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeLeftMouseDragged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.leftMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/leftmousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseUp": {
      "abstract": [
        {
          "text": "The user released the left mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeLeftMouseUp"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.leftMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/leftmouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered": {
      "abstract": [
        {
          "text": "The cursor entered a well-defined area, such as a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseEntered"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeMouseEntered"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.mouseEntered",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/mouseentered"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseExited": {
      "abstract": [
        {
          "text": "The cursor exited a well-defined area, such as a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseExited"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseExited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeMouseExited"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.mouseExited",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/mouseexited"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseMoved": {
      "abstract": [
        {
          "text": "The user moved the mouse in a way that caused the cursor to move onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseMoved"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseMoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeMouseMoved"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.mouseMoved",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/mousemoved"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDown": {
      "abstract": [
        {
          "text": "The user pressed a tertiary mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeOtherMouseDown"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.otherMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/othermousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged": {
      "abstract": [
        {
          "text": "The user moved the mouse while holding down a tertiary mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeOtherMouseDragged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.otherMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/othermousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseUp": {
      "abstract": [
        {
          "text": "The user released a tertiary mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeOtherMouseUp"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.otherMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/othermouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDown": {
      "abstract": [
        {
          "text": "The user pressed the right mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeRightMouseDown"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.rightMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/rightmousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDragged": {
      "abstract": [
        {
          "text": "The user moved the mouse while holding down the right mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDragged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeRightMouseDragged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.rightMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/rightmousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseUp": {
      "abstract": [
        {
          "text": "The user released the right mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeRightMouseUp"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.rightMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/rightmouseup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Mouse-Related-Event-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDown",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseUp",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDown",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseUp",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDragged",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDown",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseUp",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseMoved",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseExited"
      ],
      "title": "Getting Mouse-Related Event Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSEventTypeLeftMouseDragged"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeLeftMouseDragged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Mouse-Related-Event-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseDown",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/leftMouseUp",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDown",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseUp",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rightMouseDragged",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDown",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseUp",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseMoved",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseExited"
              ],
              "title": "Getting Mouse-Related Event Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSEventTypeLeftMouseDragged"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseDown/title",
          "value": "NSEventTypeLeftMouseDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeLeftMouseDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseDragged/title",
          "value": "NSEventTypeOtherMouseDragged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseDragged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeOtherMouseDragged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/title",
          "value": "NSEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseUp/title",
          "value": "NSEventTypeRightMouseUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeRightMouseUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseDragged/title",
          "value": "NSEventTypeRightMouseDragged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseDragged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeRightMouseDragged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseUp/title",
          "value": "NSEventTypeLeftMouseUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeLeftMouseUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseDown/title",
          "value": "NSEventTypeOtherMouseDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeOtherMouseDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseMoved/title",
          "value": "NSEventTypeMouseMoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseMoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeMouseMoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseDown/title",
          "value": "NSEventTypeRightMouseDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rightMouseDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeRightMouseDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseDragged/title",
          "value": "NSEventTypeLeftMouseDragged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1leftMouseDragged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeLeftMouseDragged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseUp/title",
          "value": "NSEventTypeOtherMouseUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeOtherMouseUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseExited/title",
          "value": "NSEventTypeMouseExited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseExited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeMouseExited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseEntered/title",
          "value": "NSEventTypeMouseEntered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseEntered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeMouseEntered"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/eventtype/leftmousedragged"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/eventtype/leftmousedragged"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
