{
  "abstract": [
    {
      "text": "A pointing device is near, but not touching, the associated tablet.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletProximity"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSEventType@NSEventTypeTabletProximity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tabletProximity"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSEventTypeTabletProximity"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSEvent.EventType.tabletProximity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tabletProximity"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType": {
      "abstract": [
        {
          "text": "Constants for the types of events that responder objects can handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/beginGesture": {
      "abstract": [
        {
          "text": "An event marking the beginning of a gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginGesture"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/beginGesture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeBeginGesture"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.beginGesture",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/begingesture"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/directTouch": {
      "abstract": [
        {
          "text": "The user touched a portion of the touch bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directTouch"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/directTouch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeDirectTouch"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.directTouch",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/directtouch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/endGesture": {
      "abstract": [
        {
          "text": "An event that marks the end of a gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endGesture"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/endGesture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeEndGesture"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.endGesture",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/endgesture"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/gesture": {
      "abstract": [
        {
          "text": "The user performed a nonspecific type of gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gesture"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/gesture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeGesture"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.gesture",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/gesture"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/magnify": {
      "abstract": [
        {
          "text": "The user performed a pinch-open or pinch-close gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magnify"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/magnify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeMagnify"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.magnify",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/magnify"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure": {
      "abstract": [
        {
          "text": "An event that reports a change in pressure on a pressure-sensitive device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pressure"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypePressure"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.pressure",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/pressure"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rotate": {
      "abstract": [
        {
          "text": "The user performed a rotate gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rotate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeRotate"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.rotate",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/rotate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/smartMagnify": {
      "abstract": [
        {
          "text": "The user performed a smart-zoom gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartMagnify"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/smartMagnify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeSmartMagnify"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.smartMagnify",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/smartmagnify"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/swipe": {
      "abstract": [
        {
          "text": "The user performed a swipe gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipe"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/swipe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeSwipe"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.swipe",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/swipe"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletPoint": {
      "abstract": [
        {
          "text": "The user touched a point on a tablet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabletPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeTabletPoint"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.tabletPoint",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/tabletpoint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletProximity": {
      "abstract": [
        {
          "text": "A pointing device is near, but not touching, the associated tablet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabletProximity"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletProximity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeTabletProximity"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.tabletProximity",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/tabletproximity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Touch-Based-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/beginGesture",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/endGesture",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/magnify",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/smartMagnify",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/swipe",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rotate",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/gesture",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/directTouch",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletPoint",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure"
      ],
      "title": "Getting Touch-Based Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSEventTypeTabletProximity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeTabletProximity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Touch-Based-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/beginGesture",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/endGesture",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/magnify",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/smartMagnify",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/swipe",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/rotate",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/gesture",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/directTouch",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/tabletPoint",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/pressure"
              ],
              "title": "Getting Touch-Based Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSEventTypeTabletProximity"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1beginGesture/title",
          "value": "NSEventTypeBeginGesture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1beginGesture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeBeginGesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1tabletPoint/title",
          "value": "NSEventTypeTabletPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1tabletPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeTabletPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/title",
          "value": "NSEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1gesture/title",
          "value": "NSEventTypeGesture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1gesture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeGesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1magnify/title",
          "value": "NSEventTypeMagnify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1magnify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeMagnify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1tabletProximity/title",
          "value": "NSEventTypeTabletProximity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1tabletProximity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeTabletProximity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1endGesture/title",
          "value": "NSEventTypeEndGesture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1endGesture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeEndGesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rotate/title",
          "value": "NSEventTypeRotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1rotate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeRotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1smartMagnify/title",
          "value": "NSEventTypeSmartMagnify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1smartMagnify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeSmartMagnify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1pressure/title",
          "value": "NSEventTypePressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1pressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypePressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1swipe/title",
          "value": "NSEventTypeSwipe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1swipe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeSwipe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1directTouch/title",
          "value": "NSEventTypeDirectTouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1directTouch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeDirectTouch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/eventtype/tabletproximity"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/eventtype/tabletproximity"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
