{
  "abstract": [
    {
      "text": "Returns a Boolean value indicating whether the voxel array contains voxel data for the specified index.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelExists(atIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLVoxelArray(im)voxelExistsAtIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "voxelExists"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "atIndex"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MDLVoxelIndex",
        "text": "MDLVoxelIndex"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "allowAnyX"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "allowAnyY"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "allowAnyZ"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "allowAnyShell"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "voxelExistsAtIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "voxelExists(atIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "voxelExists"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "atIndex"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "index"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelIndex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MDLVoxelIndex",
              "text": "MDLVoxelIndex"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "allowAnyX"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "allowAnyY"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "allowAnyZ"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "allowAnyShell"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An index describing both the location of the voxel within the three-dimensional grid of the voxel array and its relationship to the volume of the object modeled by the voxel array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "index"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", this method treats the x component of the index parameter as a wildcard. If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", this method requires an exact match for the x component.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allowAnyX"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", this method treats the y component of the index parameter as a wildcard. If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", this method requires an exact match for the y component.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allowAnyY"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", this method treats the z component of the index parameter as a wildcard. If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", this method requires an exact match for the z component.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allowAnyZ"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", this method treats the w (shell level) component of the index parameter as a wildcard. If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", this method requires an exact match for the shell level component.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allowAnyShell"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the voxel array contains at least one voxel index matching the specified parameters; otherwise ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "allowAnyX",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "allowAnyY",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "allowAnyZ",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "allowAnyShell",
              "type": "codeVoice"
            },
            {
              "text": " parameters to perform wildcard searches. For example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "// Does a voxel exist at exactly the specified X, Y, Z, and shell level?",
                    "exists = voxelArray.voxelExists(atIndex: index, allowAnyX: false, allowAnyY: false, allowAnyZ: false, allowAnyShell: false)",
                    "// Does a voxel exist at the specified X, Y, and Z, regardless of shell level?",
                    "exists = voxelArray.voxelExists(atIndex: index, allowAnyX: false, allowAnyY: false, allowAnyZ: false, allowAnyShell: true)",
                    "// Are there surface voxels anywhere on the XY plane at a specific Z index?",
                    "index.w = 0",
                    "exists = voxelArray.voxelExists(atIndex: index, allowAnyX: true, allowAnyY: true, allowAnyZ: false, allowAnyShell: false)",
                    "// Are there any voxels three layers deep inside the object modeled by the voxel array, regardless of location?",
                    "index.w = -3",
                    "exists = voxelArray.voxelExists(atIndex: index, allowAnyX: true, allowAnyY: true, allowAnyZ: true, allowAnyShell: false)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "// Does a voxel exist at exactly the specified X, Y, Z, and shell level?",
                    "exists = [voxelArray voxelExistsAtIndex:index allowAnyX:NO allowAnyY:NO allowAnyZ:NO allowAnyShell:NO];",
                    "// Does a voxel exist at the specified X, Y, and Z, regardless of shell level?",
                    "exists = [voxelArray voxelExistsAtIndex:index allowAnyX:NO allowAnyY:NO allowAnyZ:NO allowAnyShell:YES];",
                    "// Are there surface voxels anywhere on the XY plane at a specific Z index?",
                    "index.w = 0;",
                    "exists = [voxelArray voxelExistsAtIndex:index allowAnyX:YES allowAnyY:YES allowAnyZ:NO allowAnyShell:NO];",
                    "// Are there any voxels three layers deep inside the object modeled by the voxel array, regardless of location?",
                    "index.w = -3;",
                    "exists = [voxelArray voxelExistsAtIndex:index allowAnyX:YES allowAnyY:YES allowAnyZ:YES allowAnyShell:NO];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray": {
      "abstract": [
        {
          "text": "A model of a 3D object’s solid volume as a collection of ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "voxels",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", or cubic units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVoxelArray"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVoxelArray"
        }
      ],
      "role": "symbol",
      "title": "MDLVoxelArray",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelarray"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/count": {
      "abstract": [
        {
          "text": "The number of voxels in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/count",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelarray/count"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelExists(atIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the voxel array contains voxel data for the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voxelExists"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MDLVoxelIndex",
          "text": "MDLVoxelIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allowAnyX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allowAnyY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allowAnyZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allowAnyShell"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelExists(atIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "voxelExistsAtIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:"
        }
      ],
      "role": "symbol",
      "title": "voxelExists(atIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelarray/voxelexists(atindex:allowanyx:allowanyy:allowanyz:allowanyshell:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndexExtent": {
      "abstract": [
        {
          "text": "The indexes that define the corners of the three-dimensional voxel grid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voxelIndexExtent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MDLVoxelIndexExtent",
          "text": "MDLVoxelIndexExtent"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndexExtent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "voxelIndexExtent"
        }
      ],
      "role": "symbol",
      "title": "voxelIndexExtent",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelarray/voxelindexextent"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndices()": {
      "abstract": [
        {
          "text": "Returns a data object containing all voxels within the voxel array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voxelIndices"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndices()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "voxelIndices"
        }
      ],
      "role": "symbol",
      "title": "voxelIndices()",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelarray/voxelindices()"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxels(within:)": {
      "abstract": [
        {
          "text": "Returns a data object containing all voxels within the specified volume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voxels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "within"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MDLVoxelIndexExtent",
          "text": "MDLVoxelIndexExtent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxels(within:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "voxelsWithinExtent:"
        }
      ],
      "role": "symbol",
      "title": "voxels(within:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelarray/voxels(within:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelIndex": {
      "abstract": [
        {
          "text": "A 4-component vector encoding the location of a voxel in a voxel array and describing its relation to an object’s volume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVoxelIndex"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVoxelIndex"
        }
      ],
      "role": "symbol",
      "title": "MDLVoxelIndex",
      "type": "topic",
      "url": "/documentation/modelio/mdlvoxelindex"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Examining-Voxels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/count",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndexExtent",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxels(within:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndices()"
      ],
      "title": "Examining Voxels"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "voxelExistsAtIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "voxelExistsAtIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Examining-Voxels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/count",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndexExtent",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxels(within:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelArray/voxelIndices()"
              ],
              "title": "Examining Voxels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "voxelExistsAtIndex:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVoxelIndex",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MDLVoxelIndex",
                    "text": "MDLVoxelIndex"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "index"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "allowAnyX:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "allowAnyX"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "allowAnyY:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "allowAnyY"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "allowAnyZ:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "allowAnyZ"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "allowAnyShell:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "allowAnyShell"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An index describing both the location of the voxel within the three-dimensional grid of the voxel array and its relationship to the volume of the object modeled by the voxel array.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "index"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/true",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", this method treats the x component of the index parameter as a wildcard. If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", this method requires an exact match for the x component.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "allowAnyX"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/true",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", this method treats the y component of the index parameter as a wildcard. If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", this method requires an exact match for the y component.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "allowAnyY"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/true",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", this method treats the z component of the index parameter as a wildcard. If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", this method requires an exact match for the z component.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "allowAnyZ"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/true",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", this method treats the w (shell level) component of the index parameter as a wildcard. If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", this method requires an exact match for the shell level component.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "allowAnyShell"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the voxel array contains at least one voxel index matching the specified parameters; otherwise ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxelExists(atIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:)/title",
          "value": "voxelExistsAtIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxelExists(atIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "voxelExistsAtIndex:allowAnyX:allowAnyY:allowAnyZ:allowAnyShell:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxels(within:)/title",
          "value": "voxelsWithinExtent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxels(within:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "voxelsWithinExtent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxelIndexExtent/title",
          "value": "voxelIndexExtent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxelIndexExtent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "voxelIndexExtent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1count/title",
          "value": "count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1count/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray/title",
          "value": "MDLVoxelArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVoxelArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVoxelArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelIndex/title",
          "value": "MDLVoxelIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVoxelIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelIndex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVoxelIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxelIndices()/title",
          "value": "voxelIndices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVoxelArray~1voxelIndices()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "voxelIndices"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlvoxelarray/voxelexists(atindex:allowanyx:allowanyy:allowanyz:allowanyshell:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlvoxelarray/voxelexists(atindex:allowanyx:allowanyy:allowanyz:allowanyshell:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
