{
  "abstract": [
    {
      "text": "A custom tap handler block that handles user interaction with a configuration item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.social/documentation/Social",
        "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItem/tapHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SLComposeSheetConfigurationItem(py)tapHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tapHandler"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SLComposeSheetConfigurationItemTapHandler",
        "text": "SLComposeSheetConfigurationItemTapHandler"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Social"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tapHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "tapHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tapHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItemTapHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SLComposeSheetConfigurationItemTapHandler",
              "text": "SLComposeSheetConfigurationItemTapHandler"
            },
            {
              "kind": "text",
              "text": "! { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Called when the user taps the configuration item. Note that ",
              "type": "text"
            },
            {
              "code": "tapHandler",
              "type": "codeVoice"
            },
            {
              "text": " is called on the main queue; to avoid a possible retain cycle, your block should not keep a strong reference to either the configuration item or the compose view controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.social/documentation/Social": {
      "abstract": [
        {
          "text": "Post content to supported social networking services, using standard system interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social",
      "kind": "symbol",
      "role": "collection",
      "title": "Social",
      "type": "topic",
      "url": "/documentation/social"
    },
    "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItem": {
      "abstract": [
        {
          "text": "An object that provides additional configuration details to use when configuring a composition interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLComposeSheetConfigurationItem"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeSheetConfigurationItem"
        }
      ],
      "role": "symbol",
      "title": "SLComposeSheetConfigurationItem",
      "type": "topic",
      "url": "/documentation/social/slcomposesheetconfigurationitem"
    },
    "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItem/tapHandler": {
      "abstract": [
        {
          "text": "A custom tap handler block that handles user interaction with a configuration item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SLComposeSheetConfigurationItemTapHandler",
          "text": "SLComposeSheetConfigurationItemTapHandler"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItem/tapHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tapHandler"
        }
      ],
      "role": "symbol",
      "title": "tapHandler",
      "type": "topic",
      "url": "/documentation/social/slcomposesheetconfigurationitem/taphandler"
    },
    "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItemTapHandler": {
      "abstract": [
        {
          "text": "The method signature for a configuration item’s tap handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLComposeSheetConfigurationItemTapHandler"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItemTapHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeSheetConfigurationItemTapHandler"
        }
      ],
      "role": "symbol",
      "title": "SLComposeSheetConfigurationItemTapHandler",
      "type": "topic",
      "url": "/documentation/social/slcomposesheetconfigurationitemtaphandler"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-User-Interaction",
      "generated": true,
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItemTapHandler"
      ],
      "title": "Responding to User Interaction"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "tapHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tapHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.social/documentation/Social",
                "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-User-Interaction",
              "generated": true,
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItemTapHandler"
              ],
              "title": "Responding to User Interaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.social/documentation/Social/SLComposeSheetConfigurationItemTapHandler",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SLComposeSheetConfigurationItemTapHandler",
                    "text": "SLComposeSheetConfigurationItemTapHandler"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "tapHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeSheetConfigurationItem/title",
          "value": "SLComposeSheetConfigurationItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeSheetConfigurationItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeSheetConfigurationItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeSheetConfigurationItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeSheetConfigurationItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeSheetConfigurationItem~1tapHandler/title",
          "value": "tapHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeSheetConfigurationItem~1tapHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tapHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeSheetConfigurationItemTapHandler/title",
          "value": "SLComposeSheetConfigurationItemTapHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeSheetConfigurationItemTapHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeSheetConfigurationItemTapHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeSheetConfigurationItemTapHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeSheetConfigurationItemTapHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/social/slcomposesheetconfigurationitem/taphandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/social/slcomposesheetconfigurationitem/taphandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
