{"kind":"symbol","variants":[{"paths":["/documentation/uikit/uibaritem/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uibaritem/image"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This image can be used to create other images to represent this item on the bar—for example, a selected and unselected image may be derived from this image. You should set this property before adding the item to a bar. The default value is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"image"}],"modules":[{"name":"UIKit"}],"platforms":[{"introducedAt":"2.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"introducedAt":"2.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0"}],"externalID":"c:objc(cs)UIBarItem(py)image","symbolKind":"property"},"seeAlsoSections":[{"generated":true,"title":"Getting and setting properties","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIBarItem/title","doc://com.apple.uikit/documentation/UIKit/UIBarItem/landscapeImagePhone","doc://com.apple.uikit/documentation/UIKit/UIBarItem/largeContentSizeImage","doc://com.apple.uikit/documentation/UIKit/UIBarItem/imageInsets","doc://com.apple.uikit/documentation/UIKit/UIBarItem/landscapeImagePhoneInsets","doc://com.apple.uikit/documentation/UIKit/UIBarItem/largeContentSizeImageInsets","doc://com.apple.uikit/documentation/UIKit/UIBarItem/isEnabled","doc://com.apple.uikit/documentation/UIKit/UIBarItem/tag"],"anchor":"Getting-and-setting-properties"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIBarItem"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/image"},"abstract":[{"text":"The image used to represent the item.","type":"text"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIBarItem/tag":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The bar item’s tag, an app-supplied integer that you can use to identify bar item objects in your app."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/tag","title":"tag","url":"/documentation/uikit/uibaritem/tag","navigatorTitle":[{"kind":"identifier","text":"tag"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tag"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBarItem/largeContentSizeImage":{"kind":"symbol","type":"topic","abstract":[{"text":"The image to display for users who are blind or have low vision.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/largeContentSizeImage","title":"largeContentSizeImage","url":"/documentation/uikit/uibaritem/largecontentsizeimage","navigatorTitle":[{"kind":"identifier","text":"largeContentSizeImage"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"largeContentSizeImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit/UIBarItem/isEnabled":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A Boolean value indicating whether the item is enabled."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/isEnabled","title":"isEnabled","url":"/documentation/uikit/uibaritem/isenabled","navigatorTitle":[{"text":"enabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIBarItem/imageInsets":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The image inset or outset for each edge."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/imageInsets","title":"imageInsets","url":"/documentation/uikit/uibaritem/imageinsets","navigatorTitle":[{"kind":"identifier","text":"imageInsets"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIBarItem/landscapeImagePhoneInsets":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The image inset or outset for each edge of the image in landscape orientation when using the iPhone appearance idiom."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/landscapeImagePhoneInsets","title":"landscapeImagePhoneInsets","url":"/documentation/uikit/uibaritem/landscapeimagephoneinsets","navigatorTitle":[{"kind":"identifier","text":"landscapeImagePhoneInsets"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapeImagePhoneInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBarItem/title":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The title displayed on the item."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/title","title":"title","url":"/documentation/uikit/uibaritem/title","navigatorTitle":[{"text":"title","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIBarItem":{"url":"/documentation/uikit/uibaritem","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem","role":"symbol","navigatorTitle":[{"text":"UIBarItem","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIBarItem","kind":"identifier"}],"type":"topic","title":"UIBarItem","kind":"symbol","abstract":[{"text":"An abstract superclass for items that you can add to a bar that appears at the bottom of the screen.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIBarItem/image":{"role":"symbol","kind":"symbol","url":"/documentation/uikit/uibaritem/image","type":"topic","abstract":[{"type":"text","text":"The image used to represent the item."}],"navigatorTitle":[{"kind":"identifier","text":"image"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/image","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBarItem/landscapeImagePhone":{"url":"/documentation/uikit/uibaritem/landscapeimagephone","abstract":[{"type":"text","text":"The image to use to represent the item in landscape orientation when using the iPhone appearance idiom."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapeImagePhone"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"landscapeImagePhone"}],"title":"landscapeImagePhone","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/landscapeImagePhone","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBarItem/largeContentSizeImageInsets":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The insets to apply to the bar item’s large image when displaying the image in an assistive UI."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarItem/largeContentSizeImageInsets","title":"largeContentSizeImageInsets","url":"/documentation/uikit/uibaritem/largecontentsizeimageinsets","navigatorTitle":[{"text":"largeContentSizeImageInsets","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"largeContentSizeImageInsets"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.1"},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"image"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"image"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIBarItem"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Getting-and-setting-properties","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIBarItem/title","doc://com.apple.uikit/documentation/UIKit/UIBarItem/landscapeImagePhone","doc://com.apple.uikit/documentation/UIKit/UIBarItem/largeContentSizeImage","doc://com.apple.uikit/documentation/UIKit/UIBarItem/imageInsets","doc://com.apple.uikit/documentation/UIKit/UIBarItem/landscapeImagePhoneInsets","doc://com.apple.uikit/documentation/UIKit/UIBarItem/largeContentSizeImageInsets","doc://com.apple.uikit/documentation/UIKit/UIBarItem/isEnabled","doc://com.apple.uikit/documentation/UIKit/UIBarItem/tag"],"generated":true,"title":"Getting and setting properties"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"image"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1tag/title","value":"tag"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1tag/fragments","value":[{"kind":"identifier","text":"tag"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","value":"UIImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","value":[{"kind":"identifier","text":"UIImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","value":[{"kind":"identifier","text":"UIImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1largeContentSizeImage/title","value":"largeContentSizeImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1largeContentSizeImage/fragments","value":[{"text":"largeContentSizeImage","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1isEnabled/title","value":"enabled"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1isEnabled/fragments","value":[{"kind":"identifier","text":"enabled"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1imageInsets/title","value":"imageInsets"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1imageInsets/fragments","value":[{"text":"imageInsets","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1landscapeImagePhoneInsets/title","value":"landscapeImagePhoneInsets"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1landscapeImagePhoneInsets/fragments","value":[{"kind":"identifier","text":"landscapeImagePhoneInsets"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1title/title","value":"title"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1title/fragments","value":[{"kind":"identifier","text":"title"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem/title","value":"UIBarItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem/fragments","value":[{"kind":"identifier","text":"UIBarItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem/navigatorTitle","value":[{"text":"UIBarItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1image/title","value":"image"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1image/fragments","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1landscapeImagePhone/title","value":"landscapeImagePhone"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1landscapeImagePhone/fragments","value":[{"kind":"identifier","text":"landscapeImagePhone"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1largeContentSizeImageInsets/title","value":"largeContentSizeImageInsets"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarItem~1largeContentSizeImageInsets/fragments","value":[{"kind":"identifier","text":"largeContentSizeImageInsets"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}