{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:So30UITextFormattingViewControllerC5UIKitE11ChangeValueO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ChangeValue"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ChangeValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UITextFormattingViewController.ChangeValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ChangeValue"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextFormattingViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewController"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ChangeValue"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ChangeValue"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/bold(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bold"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/bold(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.bold(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/bold(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/decreaseFontSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decreaseFontSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/decreaseFontSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.decreaseFontSize",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/decreasefontsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/decreaseIndentation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decreaseIndentation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/decreaseIndentation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.decreaseIndentation",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/decreaseindentation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/font(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "font"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/font(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.font(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/font(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/fontSize(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/fontSize(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.fontSize(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/fontsize(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/formattingStyle(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formattingStyle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/formattingStyle(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.formattingStyle(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/formattingstyle(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/highlight(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerHighlight",
          "text": "Highlight"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/highlight(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.highlight(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/highlight(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/increaseFontSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "increaseFontSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/increaseFontSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.increaseFontSize",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/increasefontsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/increaseIndentation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "increaseIndentation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/increaseIndentation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.increaseIndentation",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/increaseindentation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/italic(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "italic"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/italic(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.italic(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/italic(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/lineHeightPointSize(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineHeightPointSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/lineHeightPointSize(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.lineHeightPointSize(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/lineheightpointsize(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/strikethrough(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strikethrough"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/strikethrough(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.strikethrough(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/strikethrough(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/textAlignment(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textAlignment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerTextAlignment",
          "text": "TextAlignment"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/textAlignment(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.textAlignment(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/textalignment(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/textColor(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/textColor(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.textColor(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/textcolor(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/textList(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerTextList",
          "text": "TextList"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/textList(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.textList(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/textlist(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/undefined": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/undefined",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.undefined",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/undefined"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/underline(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/underline(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewController.ChangeValue.underline(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/changevalue/underline(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/bold(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/decreaseFontSize",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/decreaseIndentation",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/font(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/fontSize(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/formattingStyle(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/highlight(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/increaseFontSize",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/increaseIndentation",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/italic(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/lineHeightPointSize(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/strikethrough(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/textAlignment(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/textColor(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/textList(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/undefined",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ChangeValue/underline(_:)"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/title",
          "value": "UITextFormattingViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextformattingviewcontroller/changevalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
