{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UITextFormattingViewControllerComponentSize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ComponentSize"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ComponentSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UITextFormattingViewController.ComponentSize"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ComponentSize"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpandedStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExpandedStatus"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.ExpandedStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/expandedstatus"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusItemDeferralMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusItemDeferralMode"
        }
      ],
      "role": "symbol",
      "title": "UIFocusItemDeferralMode",
      "type": "topic",
      "url": "/documentation/uikit/uifocusitemdeferralmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle": {
      "abstract": [
        {
          "text": "The presentation styles that determine how a view shows an item provider’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPreferredPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPreferredPresentationStyle",
      "type": "topic",
      "url": "/documentation/uikit/uipreferredpresentationstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextFormattingViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewController"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComponentSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComponentSize"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentSize",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/automatic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerComponentSizeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentSize.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentsize/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/extraLarge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraLarge"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/extraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerComponentSizeExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentSize.extraLarge",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentsize/extralarge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentsize/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/large": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "large"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/large",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerComponentSizeLarge"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentSize.large",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentsize/large"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/mini": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mini"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/mini",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerComponentSizeMini"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentSize.mini",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentsize/mini"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/regular": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regular"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/regular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerComponentSizeRegular"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentSize.regular",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentsize/regular"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/small": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "small"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/small",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerComponentSizeSmall"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentSize.small",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentsize/small"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/extraLarge",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/large",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/mini",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/regular",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/small"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextFormattingViewControllerComponentSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/extraLarge",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/large",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/mini",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/regular",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize/small"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus",
                "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITextFormattingViewControllerComponentSize"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ExpandedStatus/title",
          "value": "UIAccessibilityExpandedStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ExpandedStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityExpandedStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ExpandedStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityExpandedStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1extraLarge/title",
          "value": "UITextFormattingViewControllerComponentSizeExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1extraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSizeExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize/title",
          "value": "UITextFormattingViewControllerComponentSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1large/title",
          "value": "UITextFormattingViewControllerComponentSizeLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1large/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSizeLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1automatic/title",
          "value": "UITextFormattingViewControllerComponentSizeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSizeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1mini/title",
          "value": "UITextFormattingViewControllerComponentSizeMini"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1mini/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSizeMini"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemDeferralMode/title",
          "value": "UIFocusItemDeferralMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemDeferralMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusItemDeferralMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemDeferralMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusItemDeferralMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1regular/title",
          "value": "UITextFormattingViewControllerComponentSizeRegular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1regular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSizeRegular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1small/title",
          "value": "UITextFormattingViewControllerComponentSizeSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize~1small/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSizeSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/title",
          "value": "UITextFormattingViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextformattingviewcontroller/componentsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextformattingviewcontroller/componentsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
