{
  "abstract": [
    {
      "text": "Indexes the provided entities into the system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndex"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndex/indexAppEntities(_:priority:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreSpotlight",
    "externalID": "s:So17CSSearchableIndexC10AppIntentsE05indexC8Entities_8priorityySayxG_SitYaKAC13IndexedEntityRzlF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "indexAppEntities"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "keyword",
        "text": "some"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10AppIntents13IndexedEntityP",
        "text": "IndexedEntity"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "priority"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "async"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "indexAppEntities(_:priority:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "indexAppEntities"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "appEntities"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "kind": "keyword",
              "text": "some"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10AppIntents13IndexedEntityP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10AppIntents13IndexedEntityP",
              "text": "IndexedEntity"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "priority"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " = 0) "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A list of donated entities to add to the index of donated entities.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "appEntities"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The importance of this item compared to the other donated items.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "priority"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndex": {
      "abstract": [
        {
          "text": "An on-device index for your app’s searchable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableIndex"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchableIndex"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableIndex",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableindex"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndex/indexAppEntities(_:priority:)": {
      "abstract": [
        {
          "text": "Indexes the provided entities into the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexAppEntities"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents13IndexedEntityP",
          "text": "IndexedEntity"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "priority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndex/indexAppEntities(_:priority:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "indexAppEntities(_:priority:)",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableindex/indexappentities(_:priority:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10AppIntents13IndexedEntityP": {
      "abstract": [
        {
          "text": "`IndexedEntity` represents an App Entity decorated with an attribute set. A set of attributes that enable the system to perform structured indexing  and queries of entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IndexedEntity"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents0A6EntityP",
          "text": "AppEntity"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10AppIntents13IndexedEntityP",
      "kind": "symbol",
      "role": "symbol",
      "title": "IndexedEntity",
      "type": "topic",
      "url": "/documentation/AppIntents/IndexedEntity"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableIndex/title",
          "value": "CSSearchableIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableIndex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableIndex"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/cssearchableindex/indexappentities(_:priority:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
