{
  "abstract": [
    {
      "text": "The preview displays a full-color watch face.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "On watchOS 9.0 or later, use WidgetKit instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/multicolor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV10multicolorAEvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "multicolor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
        "text": "CLKComplicationTemplate"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
        "text": "PreviewFaceColor"
      }
    ],
    "modules": [
      {
        "name": "ClockKit",
        "relatedModules": [
          "SwiftUI"
        ]
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "7.0",
        "message": "On watchOS 9.0 or later, use WidgetKit instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "multicolor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "multicolor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
              "text": "CLKComplicationTemplate"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
              "text": "PreviewFaceColor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate": {
      "abstract": [
        {
          "text": "An abstract class that defines the base behavior for all templates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplate",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor": {
      "abstract": [
        {
          "text": "The valid face colors for complication templates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PreviewFaceColor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PreviewFaceColor"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplate.PreviewFaceColor",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/allColors": {
      "abstract": [
        {
          "text": "An array containing all valid face colors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allColors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
          "text": "CLKComplicationTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
          "text": "PreviewFaceColor"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/allColors",
      "kind": "symbol",
      "role": "symbol",
      "title": "allColors",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor/allcolors"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/blue": {
      "abstract": [
        {
          "text": "The preview displays a watch face with a blue tint color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
          "text": "CLKComplicationTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
          "text": "PreviewFaceColor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/blue",
      "kind": "symbol",
      "role": "symbol",
      "title": "blue",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor/blue"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/green": {
      "abstract": [
        {
          "text": "The preview displays a watch face with a green tint color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
          "text": "CLKComplicationTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
          "text": "PreviewFaceColor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/green",
      "kind": "symbol",
      "role": "symbol",
      "title": "green",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor/green"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/multicolor": {
      "abstract": [
        {
          "text": "The preview displays a full-color watch face.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multicolor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
          "text": "CLKComplicationTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
          "text": "PreviewFaceColor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/multicolor",
      "kind": "symbol",
      "role": "symbol",
      "title": "multicolor",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor/multicolor"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/orange": {
      "abstract": [
        {
          "text": "The preview displays a watch face with an orange tint color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
          "text": "CLKComplicationTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
          "text": "PreviewFaceColor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/orange",
      "kind": "symbol",
      "role": "symbol",
      "title": "orange",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor/orange"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/pink": {
      "abstract": [
        {
          "text": "The preview displays a watch face with a pink tint color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
          "text": "CLKComplicationTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
          "text": "PreviewFaceColor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/pink",
      "kind": "symbol",
      "role": "symbol",
      "title": "pink",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor/pink"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/purple": {
      "abstract": [
        {
          "text": "The preview displays a watch face with a purple tint color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
          "text": "CLKComplicationTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
          "text": "PreviewFaceColor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/purple",
      "kind": "symbol",
      "role": "symbol",
      "title": "purple",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor/purple"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/red": {
      "abstract": [
        {
          "text": "The preview displays a watch face with a red tint color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
          "text": "CLKComplicationTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
          "text": "PreviewFaceColor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/red",
      "kind": "symbol",
      "role": "symbol",
      "title": "red",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor/red"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/yellow": {
      "abstract": [
        {
          "text": "The preview displays a watch face with a yellow tint color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yellow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
          "text": "CLKComplicationTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So23CLKComplicationTemplateC17_ClockKit_SwiftUIE16PreviewFaceColorV",
          "text": "PreviewFaceColor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/yellow",
      "kind": "symbol",
      "role": "symbol",
      "title": "yellow",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor/yellow"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Colors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/allColors",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/pink",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/red",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/orange",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/yellow",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/green",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/blue",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate/PreviewFaceColor/purple"
      ],
      "title": "Colors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/title",
          "value": "CLKComplicationTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationtemplate/previewfacecolor/multicolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
