{
  "abstract": [
    {
      "text": "The view controller should present the dashboard.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/dashboard"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKGameCenterViewControllerState@GKGameCenterViewControllerStateDashboard",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dashboard"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKGameCenterViewControllerStateDashboard"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GKGameCenterViewControllerState.dashboard"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dashboard"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState": {
      "abstract": [
        {
          "text": "The type of content for the view controller to present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerState"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerState"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/achievements": {
      "abstract": [
        {
          "text": "The view controller should present a list of achievements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "achievements"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/achievements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateAchievements"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.achievements",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/achievements"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/challenges": {
      "abstract": [
        {
          "text": "The view controller should present a list of challenges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "challenges"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/challenges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateChallenges"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.challenges",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/challenges"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/dashboard": {
      "abstract": [
        {
          "text": "The view controller should present the dashboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dashboard"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/dashboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateDashboard"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.dashboard",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/dashboard"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/default": {
      "abstract": [
        {
          "text": "The view controller should present the default screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateDefault"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.default",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/default"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/leaderboards": {
      "abstract": [
        {
          "text": "The view controller should present leaderboard sets or leaderboards if there are no sets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leaderboards"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/leaderboards",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateLeaderboards"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.leaderboards",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/leaderboards"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerFriendsList": {
      "abstract": [
        {
          "text": "The view controller should present the friends list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPlayerFriendsList"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerFriendsList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateLocalPlayerFriendsList"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.localPlayerFriendsList",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/localplayerfriendslist"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerProfile": {
      "abstract": [
        {
          "text": "The view controller should present the local player’s profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPlayerProfile"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateLocalPlayerProfile"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.localPlayerProfile",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/localplayerprofile"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "States",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/default",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/leaderboards",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/achievements",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/challenges",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerProfile",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerFriendsList"
      ],
      "title": "States"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKGameCenterViewControllerStateDashboard"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateDashboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "States",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/default",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/leaderboards",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/achievements",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/challenges",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerProfile",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerFriendsList"
              ],
              "title": "States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GKGameCenterViewControllerStateDashboard"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1localPlayerProfile/title",
          "value": "GKGameCenterViewControllerStateLocalPlayerProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1localPlayerProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateLocalPlayerProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState/title",
          "value": "GKGameCenterViewControllerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1achievements/title",
          "value": "GKGameCenterViewControllerStateAchievements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1achievements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateAchievements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1challenges/title",
          "value": "GKGameCenterViewControllerStateChallenges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1challenges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateChallenges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1dashboard/title",
          "value": "GKGameCenterViewControllerStateDashboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1dashboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateDashboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1leaderboards/title",
          "value": "GKGameCenterViewControllerStateLeaderboards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1leaderboards/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateLeaderboards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1localPlayerFriendsList/title",
          "value": "GKGameCenterViewControllerStateLocalPlayerFriendsList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1localPlayerFriendsList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateLocalPlayerFriendsList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1default/title",
          "value": "GKGameCenterViewControllerStateDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateDefault"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkgamecenterviewcontrollerstate/dashboard"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkgamecenterviewcontrollerstate/dashboard"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
