{
  "abstract": [
    {
      "text": "Draws the contents of the overlay view.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayRenderer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/drawMapRect:zoomScale:inContext:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKOverlayView(im)drawMapRect:zoomScale:inContext:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "drawMapRect:zoomScale:inContext:"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "drawMapRect:zoomScale:inContext:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "7.0",
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "7.0",
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "drawMapRect:zoomScale:inContext:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "drawMapRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@MKMapRect",
              "text": "MKMapRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "mapRect"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "zoomScale:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKZoomScale",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MKZoomScale",
              "text": "MKZoomScale"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "zoomScale"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inContext:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGContextRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGContextRef",
              "text": "CGContextRef"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The map rectangle that needs to be updated. You can use this rectangle to limit drawing to only the portion of the view that changed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mapRect"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The current scale factor applied to the map content. You can use this value for configuring the stroke width of lines or other attributes that might be affected by the scale of the view’s content.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "zoomScale"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The graphics context to use for drawing the view’s content.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default implementation of this method does nothing. Subclasses are expected to override this method (instead of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/draw(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method) and use it to draw the contents of the view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In your drawing code, you should specify the position of any rendered content relative to the map itself and not relative to the view’s bounds or frame. In other words, compute the position and size of any overlay content using map points and map rectangles, convert those values to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgpoint",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgrect",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " types (using the methods of this class), and then use the converted points to build paths or specify the rendering location for items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You should also not make assumptions that the view’s frame matches the bounding rectangle of the overlay. The view’s frame is actually bigger than the bounding rectangle to allow you to draw lines for things like roads that might be located directly on the border of that rectangle. For some types of content, such as gradients, this also means that you might need to apply a clipping rectangle to ",
              "type": "text"
            },
            {
              "code": "context",
              "type": "codeVoice"
            },
            {
              "text": " to ensure drawing is contained to the correct area.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It is recommended that you use Core Graphics to draw any content for your overlays. If you choose to use UIKit classes and methods for drawing instead, you must push the specified graphics context onto the context stack (using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGraphicsPushContext(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function) before making any drawing calls. When you are done drawing, you must similarly pop the graphics context off the stack using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGraphicsPopContext()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". During drawing, you may draw content normally but should avoid manipulating views and other classes that are safe to use only from the application’s main thread.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To improve drawing performance, the map view may tile overlays that become large enough and render the tiles from separate threads. Your implementation of this method must therefore be capable of safely running from multiple threads simultaneously. In addition, you should avoid drawing the entire contents of the overlay each time this method is called. Instead, your implementation should always take the ",
              "type": "text"
            },
            {
              "code": "mapRect",
              "type": "codeVoice"
            },
            {
              "text": " parameter into consideration and avoid drawing content outside that rectangle. Failure to do so could lead to performance problems.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UIGraphicsPopContext()": {
      "abstract": [
        {
          "text": "Removes the current graphics context from the top of the stack, restoring the previous context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPopContext"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGraphicsPopContext()",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIGraphicsPopContext()",
      "type": "topic",
      "url": "/documentation/UIKit/UIGraphicsPopContext()"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIGraphicsPushContext(_:)": {
      "abstract": [
        {
          "text": "Makes the specified graphics context the current context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPushContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGContextRef",
          "text": "CGContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGraphicsPushContext(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIGraphicsPushContext(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIGraphicsPushContext(_:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIView/draw(_:)": {
      "abstract": [
        {
          "text": "Draws the view’s image within the passed-in rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/draw(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "draw(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIView/draw(_:)"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cgpoint": {
      "abstract": [
        {
          "text": "A structure that contains a point in a two-dimensional coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgpoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGPoint",
      "type": "topic",
      "url": "/documentation/corefoundation/cgpoint"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cgrect": {
      "abstract": [
        {
          "text": "A structure that contains the location and dimensions of a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgrect",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGRect",
      "type": "topic",
      "url": "/documentation/corefoundation/cgrect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapRect": {
      "abstract": [
        {
          "text": "A rectangular area on a two-dimensional map projection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapRect"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapRect"
        }
      ],
      "role": "symbol",
      "title": "MKMapRect",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaprect"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayRenderer": {
      "abstract": [
        {
          "text": "The shared infrastructure for drawing overlays on the map surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayrenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView": {
      "abstract": [
        {
          "text": "Defines the basic behavior associated with all overlay views.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayView"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayView",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/canDrawMapRect:zoomScale:": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the overlay view is ready to draw its content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "canDrawMapRect:zoomScale:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/canDrawMapRect:zoomScale:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canDrawMapRect:zoomScale:"
        }
      ],
      "role": "symbol",
      "title": "canDrawMapRect:zoomScale:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/candrawmaprect:zoomscale:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/drawMapRect:zoomScale:inContext:": {
      "abstract": [
        {
          "text": "Draws the contents of the overlay view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "drawMapRect:zoomScale:inContext:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/drawMapRect:zoomScale:inContext:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawMapRect:zoomScale:inContext:"
        }
      ],
      "role": "symbol",
      "title": "drawMapRect:zoomScale:inContext:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/drawmaprect:zoomscale:incontext:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/pointForMapPoint:": {
      "abstract": [
        {
          "text": "Returns the point in the overlay view that corresponds to specified point on the map.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "pointForMapPoint:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/pointForMapPoint:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointForMapPoint:"
        }
      ],
      "role": "symbol",
      "title": "pointForMapPoint:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/pointformappoint:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/rectForMapRect:": {
      "abstract": [
        {
          "text": "Returns the rectangle in the overlay view that corresponds to the specified rectangle on the map.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "rectForMapRect:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/rectForMapRect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectForMapRect:"
        }
      ],
      "role": "symbol",
      "title": "rectForMapRect:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/rectformaprect:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:": {
      "abstract": [
        {
          "text": "Invalidates the view in the given map rectangle at all zoom scales.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setNeedsDisplayInMapRect:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsDisplayInMapRect:"
        }
      ],
      "role": "symbol",
      "title": "setNeedsDisplayInMapRect:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/setneedsdisplayinmaprect:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:zoomScale:": {
      "abstract": [
        {
          "text": "Invalidates the view in the given map rectangle but only at the specified zoom scale.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setNeedsDisplayInMapRect:zoomScale:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:zoomScale:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsDisplayInMapRect:zoomScale:"
        }
      ],
      "role": "symbol",
      "title": "setNeedsDisplayInMapRect:zoomScale:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/setneedsdisplayinmaprect:zoomscale:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKZoomScale": {
      "abstract": [
        {
          "text": "A scale factor to use in conjunction with a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKZoomScale"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKZoomScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKZoomScale"
        }
      ],
      "role": "symbol",
      "title": "MKZoomScale",
      "type": "topic",
      "url": "/documentation/mapkit/mkzoomscale"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGContextRef": {
      "abstract": [
        {
          "text": "A Quartz 2D drawing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGContext"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGContextRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGContext",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcontext"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/pointForMapPoint:",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/rectForMapRect:"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Drawing-the-overlay",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/canDrawMapRect:zoomScale:",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:zoomScale:"
      ],
      "title": "Drawing the overlay"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/title",
          "value": "MKMapRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayRenderer/title",
          "value": "MKOverlayRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKZoomScale/title",
          "value": "MKZoomScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKZoomScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKZoomScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKZoomScale/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKZoomScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGraphicsPopContext()/title",
          "value": "UIGraphicsPopContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGraphicsPopContext()/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIGraphicsPopContext"
            },
            {
              "kind": "text",
              "text": "();"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CGContextRef/title",
          "value": "CGContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1draw(_:)/title",
          "value": "drawRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1draw(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "drawRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGRect",
              "text": "CGRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/title",
          "value": "MKOverlayView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGraphicsPushContext(_:)/title",
          "value": "UIGraphicsPushContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGraphicsPushContext(_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIGraphicsPushContext"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGContextRef",
              "text": "CGContextRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkoverlayview/drawmaprect:zoomscale:incontext:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
