{
  "abstract": [
    {
      "text": "Invalidates the view in the given map rectangle at all zoom scales.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayRenderer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKOverlayView(im)setNeedsDisplayInMapRect:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "setNeedsDisplayInMapRect:"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setNeedsDisplayInMapRect:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "7.0",
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "7.0",
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setNeedsDisplayInMapRect:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setNeedsDisplayInMapRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@MKMapRect",
              "text": "MKMapRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "mapRect"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The portion of the overlay that needs to be updated. This value is specified using a map rectangle and not view coordinates. You can convert from a view rectangle to a map rectangle using the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/mapRectForRect:",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mapRect"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Marking a rectangle as invalid causes that portion of the view to be redrawn during the next update cycle. This method invalidates the overlay regardless of the current zoom scale associated with the map.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapRect": {
      "abstract": [
        {
          "text": "A rectangular area on a two-dimensional map projection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapRect"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapRect"
        }
      ],
      "role": "symbol",
      "title": "MKMapRect",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaprect"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayRenderer": {
      "abstract": [
        {
          "text": "The shared infrastructure for drawing overlays on the map surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayrenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView": {
      "abstract": [
        {
          "text": "Defines the basic behavior associated with all overlay views.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayView"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayView",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/canDrawMapRect:zoomScale:": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the overlay view is ready to draw its content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "canDrawMapRect:zoomScale:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/canDrawMapRect:zoomScale:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canDrawMapRect:zoomScale:"
        }
      ],
      "role": "symbol",
      "title": "canDrawMapRect:zoomScale:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/candrawmaprect:zoomscale:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/drawMapRect:zoomScale:inContext:": {
      "abstract": [
        {
          "text": "Draws the contents of the overlay view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "drawMapRect:zoomScale:inContext:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/drawMapRect:zoomScale:inContext:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawMapRect:zoomScale:inContext:"
        }
      ],
      "role": "symbol",
      "title": "drawMapRect:zoomScale:inContext:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/drawmaprect:zoomscale:incontext:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/mapRectForRect:": {
      "abstract": [
        {
          "text": "Returns the map rectangle that corresponds to the rectangle in the overlay view’s coordinate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mapRectForRect:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/mapRectForRect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapRectForRect:"
        }
      ],
      "role": "symbol",
      "title": "mapRectForRect:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/maprectforrect:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:": {
      "abstract": [
        {
          "text": "Invalidates the view in the given map rectangle at all zoom scales.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setNeedsDisplayInMapRect:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsDisplayInMapRect:"
        }
      ],
      "role": "symbol",
      "title": "setNeedsDisplayInMapRect:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/setneedsdisplayinmaprect:"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:zoomScale:": {
      "abstract": [
        {
          "text": "Invalidates the view in the given map rectangle but only at the specified zoom scale.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setNeedsDisplayInMapRect:zoomScale:"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:zoomScale:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsDisplayInMapRect:zoomScale:"
        }
      ],
      "role": "symbol",
      "title": "setNeedsDisplayInMapRect:zoomScale:",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview/setneedsdisplayinmaprect:zoomscale:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drawing-the-overlay",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/canDrawMapRect:zoomScale:",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/drawMapRect:zoomScale:inContext:",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView/setNeedsDisplayInMapRect:zoomScale:"
      ],
      "title": "Drawing the overlay"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/title",
          "value": "MKOverlayView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/title",
          "value": "MKMapRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayRenderer/title",
          "value": "MKOverlayRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayRenderer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkoverlayview/setneedsdisplayinmaprect:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
