{
  "abstract": [
    {
      "text": "An option that specifies that Metal should use its default behavior when creating the function object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.metal/documentation/Metal/MTLFunctionOptions/MTLFunctionOptionNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLFunctionOptions@MTLFunctionOptionNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MTLFunctionOptionNone"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLFunctionOptionNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "MTLFunctionOptionNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "MTLFunctionOptionNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionOptions": {
      "abstract": [
        {
          "text": "Options that define how Metal creates the function object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionOptions/MTLFunctionOptionNone": {
      "abstract": [
        {
          "text": "An option that specifies that Metal should use its default behavior when creating the function object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLFunctionOptionNone"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionOptions/MTLFunctionOptionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLFunctionOptionNone",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionoptions/mtlfunctionoptionnone"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionOptions/compileToBinary": {
      "abstract": [
        {
          "text": "An option that tells Metal to compile the function to a binary format for dynamic linking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compileToBinary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFunctionOptions",
          "text": "MTLFunctionOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionOptions/compileToBinary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionOptionCompileToBinary"
        }
      ],
      "role": "symbol",
      "title": "compileToBinary",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionoptions/compiletobinary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Function-Option-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFunctionOptions/compileToBinary"
      ],
      "title": "Function Option Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionOptions/title",
          "value": "MTLFunctionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionOptions~1compileToBinary/title",
          "value": "MTLFunctionOptionCompileToBinary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionOptions~1compileToBinary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionOptionCompileToBinary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlfunctionoptions/mtlfunctionoptionnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
