{
  "abstract": [
    {
      "text": "Return an SDK that matches the host’s major OS version.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcselect/documentation/xcselect",
        "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingOnly"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@xcselect_host_sdk_policy_t@XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "matchingOnly"
      }
    ],
    "modules": [
      {
        "name": "xcselect"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HostSDKPolicy.matchingOnly"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "matchingOnly"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcselect/documentation/xcselect": {
      "abstract": [
        {
          "text": "Access the path of the macOS SDK available on the host system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect",
      "kind": "symbol",
      "role": "collection",
      "title": "xcselect",
      "type": "topic",
      "url": "/documentation/xcselect"
    },
    "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy": {
      "abstract": [
        {
          "text": "Describe the preferred policy for locating an SDK appropriate for building host content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostSDKPolicy"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostSDKPolicy"
        }
      ],
      "role": "symbol",
      "title": "HostSDKPolicy",
      "type": "topic",
      "url": "/documentation/xcselect/hostsdkpolicy"
    },
    "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingOnly": {
      "abstract": [
        {
          "text": "Return an SDK that matches the host’s major OS version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchingOnly"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY"
        }
      ],
      "role": "symbol",
      "title": "HostSDKPolicy.matchingOnly",
      "type": "topic",
      "url": "/documentation/xcselect/hostsdkpolicy/matchingonly"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcselect/documentation/xcselect",
                "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy~1matchingOnly/title",
          "value": "XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy~1matchingOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/title",
          "value": "xcselect_host_sdk_policy_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_policy_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_policy_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcselect/hostsdkpolicy/matchingonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcselect/hostsdkpolicy/matchingonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
