{"seeAlsoSections":[{"identifiers":["doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/state","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/KeyPressState","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/timestamp"],"anchor":"Getting-information-about-the-keypress","generated":true,"title":"Getting information about the keypress"}],"abstract":[{"type":"text","text":"Represents whether the event is repeating."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyRepeating","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","tvOS","visionOS"]}]},{"kind":"mentions","mentions":["doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit"]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example, a continued press and hold on a key may result in its repeated insertion."}]},{"type":"paragraph","inlineContent":[{"text":"A Boolean value that indicates whether the person is holding the key down to repeat the key event.","type":"text"}]}]}],"kind":"symbol","variants":[{"paths":["/documentation/browserenginekit/bekeyentry/iskeyrepeating"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/browserenginekit/bekeyentry/iskeyrepeating"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/isKeyRepeating"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"isKeyRepeating","roleHeading":"Instance Property","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"17.4","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"17.4","beta":false},{"beta":false,"introducedAt":"17.4","deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"introducedAt":"1.1","deprecated":false,"name":"visionOS","unavailable":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isKeyRepeating"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"BrowserEngineKit"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"keyRepeating"}],"role":"symbol","externalID":"c:objc(cs)BEKeyEntry(py)keyRepeating"},"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","title":"Technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","abstract":[{"text":"","type":"text"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/state":{"url":"/documentation/browserenginekit/bekeyentry/state","title":"state","type":"topic","navigatorTitle":[{"text":"state","kind":"identifier"}],"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/state","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BEKeyEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)BEKeyEntry"},{"text":".","kind":"text"},{"text":"KeyPressState","kind":"typeIdentifier","preciseIdentifier":"c:@E@BEKeyPressState"}],"abstract":[{"text":"Type of the event, indicating whether it represents when the key is pressed or released.","type":"text"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit","type":"topic","title":"Integrating custom browser text views with UIKit","kind":"article","url":"/documentation/browserenginekit/integrating-custom-browser-text-views-with-uikit","role":"article","abstract":[{"text":"Process keyboard interactions asynchronously in your iOS browser app’s text view.","type":"text"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/timestamp":{"kind":"symbol","abstract":[{"type":"text","text":"Time at which the key event occurred."}],"title":"timestamp","url":"/documentation/browserenginekit/bekeyentry/timestamp","identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/timestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"type":"topic","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"identifier":"doc://com.externally.resolved.symbol/s:Sb","type":"topic","title":"Bool","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"url":"/documentation/Swift/Bool","role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/isKeyRepeating":{"url":"/documentation/browserenginekit/bekeyentry/iskeyrepeating","title":"isKeyRepeating","type":"topic","navigatorTitle":[{"text":"keyRepeating","kind":"identifier"}],"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/isKeyRepeating","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyRepeating","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Represents whether the event is repeating.","type":"text"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry":{"navigatorTitle":[{"text":"BEKeyEntry","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BEKeyEntry","kind":"identifier"}],"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry","title":"BEKeyEntry","type":"topic","url":"/documentation/browserenginekit/bekeyentry","abstract":[{"text":"A class that represents a keyboard event in the text system.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"type":"topic","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","title":"BOOL","role":"symbol","kind":"symbol","abstract":[{"text":"Type to represent a Boolean value.","type":"text"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit":{"kind":"symbol","url":"/documentation/browserenginekit","title":"BrowserEngineKit","type":"topic","identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit","role":"collection","abstract":[{"text":"Create a browser that renders content using an alternative browser engine.","type":"text"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/KeyPressState":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/KeyPressState","role":"symbol","title":"BEKeyEntry.KeyPressState","abstract":[{"type":"text","text":"An enumeration that represents the possible states of a key-press in a keyboard event."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyPressState"}],"type":"topic","url":"/documentation/browserenginekit/bekeyentry/keypressstate","navigatorTitle":[{"kind":"identifier","text":"KeyPressState"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"name":"iOS","introducedAt":"17.4","beta":false,"deprecated":false},{"beta":false,"introducedAt":"17.4","deprecated":false,"name":"iPadOS","unavailable":false},{"beta":false,"introducedAt":"17.4","deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"introducedAt":"1.1","deprecated":false,"name":"visionOS","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"keyRepeating","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"keyRepeating"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry"]]},"op":"replace","path":"/hierarchy"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Getting-information-about-the-keypress","identifiers":["doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/state","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/KeyPressState","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEKeyEntry/timestamp"],"title":"Getting information about the keypress","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isKeyRepeating"},{"kind":"text","text":") "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyRepeating"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"state","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry~1state/title","op":"replace"},{"value":[{"text":"state","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry~1state/fragments","op":"replace"},{"value":"timestamp","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry~1timestamp/title","op":"replace"},{"value":[{"text":"timestamp","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry~1timestamp/fragments","op":"replace"},{"value":"keyRepeating","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry~1isKeyRepeating/title","op":"replace"},{"value":[{"kind":"identifier","text":"keyRepeating"}],"path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry~1isKeyRepeating/fragments","op":"replace"},{"value":"BEKeyEntry","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry/title","op":"replace"},{"value":[{"text":"BEKeyEntry","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BEKeyEntry"}],"path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry/navigatorTitle","op":"replace"},{"value":"BEKeyPressState","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry~1KeyPressState/title","op":"replace"},{"value":[{"kind":"identifier","text":"BEKeyPressState"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry~1KeyPressState/fragments"},{"value":[{"kind":"identifier","text":"BEKeyPressState"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEKeyEntry~1KeyPressState/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}