{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"categoryBitMask","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"You can assign each node in a scene to one or more categories, where each category corresponds to a bit in the bit mask. You define the mask values used in your app. When SceneKit renders a scene, it compares each node’s "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/categoryBitMask","type":"reference","isActive":true},{"type":"text","text":" property with the category bit masks of every other object that participates in the rendering process—lights, cameras, and techniques—using a bitwise AND operation. If the result is a nonzero value, SceneKit includes the node when rendering. The default category bit mask is "},{"type":"codeVoice","code":"1"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Use a node’s category bit mask together with:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"An "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNLight","isActive":true,"type":"reference"},{"type":"text","text":" object’s "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNLight/categoryBitMask","isActive":true,"type":"reference"},{"type":"text","text":" property to exclude the node from that light’s illumination"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCamera","type":"reference"},{"text":" object’s ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCamera/categoryBitMask","type":"reference"},{"text":" property to make the node invisible to that camera","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The category bit masks in an ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique","type":"reference"},{"text":" object’s definition dictionary to include or exclude the node from phases of a multipass rendering technique","type":"text"}]}]}],"type":"unorderedList"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"This property doesn’t affect SceneKit’s physics simulation. To include or exclude a node from physics interactions, use the ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask","isActive":true,"type":"reference"},{"text":" property of the node’s ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsBody","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsField","isActive":true,"type":"reference"},{"text":" objects.","type":"text"}]}],"name":"Note","type":"aside"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/scenekit/scnnode/categorybitmask"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/scenekit/scnnode/categorybitmask"]}],"metadata":{"navigatorTitle":[{"text":"categoryBitMask","kind":"identifier"}],"title":"categoryBitMask","symbolKind":"property","modules":[{"name":"SceneKit"}],"roleHeading":"Instance Property","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.10","name":"macOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"watchOS"}],"externalID":"c:objc(cs)SCNNode(py)categoryBitMask","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"categoryBitMask","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/categoryBitMask","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"kind":"symbol","abstract":[{"text":"A mask that defines which categories the node belongs to.","type":"text"}],"sections":[],"seeAlsoSections":[{"title":"Managing Node Content","generated":true,"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/name","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/light","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/camera","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/morpher","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner","doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume"],"anchor":"Managing-Node-Content"}],"references":{"doc://com.apple.scenekit/documentation/SceneKit/SCNCamera/categoryBitMask":{"type":"topic","url":"/documentation/scenekit/scncamera/categorybitmask","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCamera/categoryBitMask","abstract":[{"text":"A mask that defines which categories this camera belongs to.","type":"text"}],"navigatorTitle":[{"text":"categoryBitMask","kind":"identifier"}],"title":"categoryBitMask","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"categoryBitMask","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsField":{"url":"/documentation/scenekit/scnnode/physicsfield","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsField","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"physicsField"}],"title":"physicsField","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"physicsField","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SCNPhysicsField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SCNPhysicsField"},{"text":"?","kind":"text"}],"abstract":[{"text":"The physics field associated with the node.","type":"text"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask":{"kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryBitMask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"categoryBitMask","navigatorTitle":[{"kind":"identifier","text":"categoryBitMask"}],"url":"/documentation/scenekit/scnphysicsbody/categorybitmask","abstract":[{"type":"text","text":"A mask that defines which categories this physics body belongs to."}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/camera":{"url":"/documentation/scenekit/scnnode/camera","role":"symbol","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/camera","title":"camera","navigatorTitle":[{"text":"camera","kind":"identifier"}],"abstract":[{"text":"The camera attached to the node.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SCNCamera","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SCNCamera"},{"text":"?","kind":"text"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry":{"role":"symbol","kind":"symbol","title":"SCNGeometry","navigatorTitle":[{"text":"SCNGeometry","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNGeometry","kind":"identifier"}],"url":"/documentation/scenekit/scngeometry","abstract":[{"text":"A three-dimensional shape (also called a model or mesh) that can be displayed in a scene, with attached materials that define its appearance.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode":{"role":"symbol","kind":"symbol","title":"SCNNode","navigatorTitle":[{"kind":"identifier","text":"SCNNode"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNNode"}],"url":"/documentation/scenekit/scnnode","abstract":[{"text":"A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsBody":{"type":"topic","url":"/documentation/scenekit/scnnode/physicsbody","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"physicsBody"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SCNPhysicsBody","preciseIdentifier":"c:objc(cs)SCNPhysicsBody"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"physicsBody"}],"abstract":[{"type":"text","text":"The physics body associated with the node."}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsBody","kind":"symbol","role":"symbol","title":"physicsBody"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/light":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"light"}],"type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/light","title":"light","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SCNLight","preciseIdentifier":"c:objc(cs)SCNLight"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"The light attached to the node."}],"url":"/documentation/scenekit/scnnode/light"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner":{"abstract":[{"text":"The skinner object responsible for skeletal animations of node’s contents.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"skinner","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SCNSkinner","text":"SCNSkinner","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"skinner","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"skinner","type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner","url":"/documentation/scenekit/scnnode/skinner"},"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SCNTechnique","kind":"identifier"}],"title":"SCNTechnique","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique","navigatorTitle":[{"kind":"identifier","text":"SCNTechnique"}],"abstract":[{"text":"A specification for augmenting or postprocessing SceneKit’s rendering of a scene using additional drawing passes with custom Metal or OpenGL shaders.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"/documentation/scenekit/scntechnique"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/name":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/name","title":"name","navigatorTitle":[{"kind":"identifier","text":"name"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"A name associated with the node."}],"url":"/documentation/scenekit/scnnode/name","type":"topic"},"doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume":{"url":"/documentation/scenekit/scnboundingvolume","role":"symbol","title":"SCNBoundingVolume","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SCNBoundingVolume"}],"navigatorTitle":[{"kind":"identifier","text":"SCNBoundingVolume"}],"type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume","abstract":[{"text":"Methods common to the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry","isActive":true},{"type":"text","text":" classes for measuring location and size."}],"kind":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/morpher":{"title":"morpher","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/morpher","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"morpher","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SCNMorpher","text":"SCNMorpher","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/scenekit/scnnode/morpher","abstract":[{"text":"The morpher object responsible for blending the node’s geometry.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"morpher","kind":"identifier"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry":{"type":"topic","url":"/documentation/scenekit/scnnode/geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SCNGeometry","preciseIdentifier":"c:objc(cs)SCNGeometry"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"geometry"}],"abstract":[{"type":"text","text":"The geometry attached to the node."}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry","kind":"symbol","role":"symbol","title":"geometry"},"doc://com.apple.scenekit/documentation/SceneKit/SCNLight":{"url":"/documentation/scenekit/scnlight","title":"SCNLight","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SCNLight","kind":"identifier"}],"abstract":[{"type":"text","text":"A light source that can be attached to a node to illuminate the scene."}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNLight","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNLight","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Si":{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"role":"symbol","title":"Int","type":"topic","abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/categoryBitMask":{"abstract":[{"type":"text","text":"A mask that defines which categories the node belongs to."}],"url":"/documentation/scenekit/scnnode/categorybitmask","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"categoryBitMask","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"categoryBitMask","type":"topic","kind":"symbol","navigatorTitle":[{"text":"categoryBitMask","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/categoryBitMask"},"doc://com.apple.scenekit/documentation/SceneKit/SCNCamera":{"title":"SCNCamera","type":"topic","url":"/documentation/scenekit/scncamera","abstract":[{"text":"A set of camera attributes that can be attached to a node to provide a point of view for displaying the scene.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SCNCamera"}],"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCamera","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNCamera"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNLight/categoryBitMask":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryBitMask"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNLight/categoryBitMask","url":"/documentation/scenekit/scnlight/categorybitmask","type":"topic","kind":"symbol","navigatorTitle":[{"text":"categoryBitMask","kind":"identifier"}],"abstract":[{"type":"text","text":"A mask that defines which categories this light belongs to."}],"title":"categoryBitMask"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.10","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"beta":false},{"name":"watchOS","deprecated":false,"unavailable":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"categoryBitMask","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"categoryBitMask","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Managing Node Content","anchor":"Managing-Node-Content","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/name","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/light","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/camera","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/morpher","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner","doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryBitMask"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera~1categoryBitMask/title","value":"categoryBitMask","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera~1categoryBitMask/fragments","value":[{"text":"categoryBitMask","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1physicsField/title","value":"physicsField","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1physicsField/fragments","value":[{"kind":"identifier","text":"physicsField"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1categoryBitMask/title","value":"categoryBitMask","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1categoryBitMask/fragments","value":[{"text":"categoryBitMask","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1camera/title","value":"camera","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1camera/fragments","value":[{"text":"camera","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/title","value":"SCNGeometry","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/fragments","value":[{"text":"SCNGeometry","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/navigatorTitle","value":[{"kind":"identifier","text":"SCNGeometry"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title","value":"SCNNode","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments","value":[{"text":"SCNNode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SCNNode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle"},{"op":"replace","value":"physicsBody","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1physicsBody/title"},{"op":"replace","value":[{"text":"physicsBody","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1physicsBody/fragments"},{"op":"replace","value":"light","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1light/title"},{"op":"replace","value":[{"kind":"identifier","text":"light"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1light/fragments"},{"op":"replace","value":"skinner","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1skinner/title"},{"op":"replace","value":[{"kind":"identifier","text":"skinner"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1skinner/fragments"},{"op":"replace","value":"SCNTechnique","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique/title"},{"op":"replace","value":[{"text":"SCNTechnique","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SCNTechnique"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique/navigatorTitle"},{"op":"replace","value":"name","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1name/title"},{"op":"replace","value":[{"kind":"identifier","text":"name"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1name/fragments"},{"op":"replace","value":"SCNBoundingVolume","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/title"},{"op":"replace","value":[{"kind":"identifier","text":"SCNBoundingVolume"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/fragments"},{"op":"replace","value":[{"text":"SCNBoundingVolume","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/navigatorTitle"},{"op":"replace","value":"morpher","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1morpher/title"},{"op":"replace","value":[{"kind":"identifier","text":"morpher"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1morpher/fragments"},{"op":"replace","value":"geometry","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1geometry/title"},{"op":"replace","value":[{"kind":"identifier","text":"geometry"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1geometry/fragments"},{"op":"replace","value":"SCNLight","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight/title"},{"op":"replace","value":[{"kind":"identifier","text":"SCNLight"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight/fragments"},{"op":"replace","value":[{"text":"SCNLight","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight/navigatorTitle"},{"op":"replace","value":"categoryBitMask","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1categoryBitMask/title"},{"op":"replace","value":[{"text":"categoryBitMask","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1categoryBitMask/fragments"},{"op":"replace","value":"SCNCamera","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera/title"},{"op":"replace","value":[{"text":"SCNCamera","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera/fragments"},{"op":"replace","value":[{"text":"SCNCamera","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera/navigatorTitle"},{"op":"replace","value":"categoryBitMask","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight~1categoryBitMask/title"},{"op":"replace","value":[{"text":"categoryBitMask","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight~1categoryBitMask/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}