{"metadata":{"modules":[{"name":"SceneKit"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"eulerAngles"}],"platforms":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"13.1","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"10.10","deprecated":false,"beta":false,"name":"macOS","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false},{"deprecated":false,"beta":false,"name":"watchOS","unavailable":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eulerAngles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@SCNVector3","text":"SCNVector3"}],"title":"eulerAngles","externalID":"c:objc(cs)SCNNode(py)eulerAngles","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/transform","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/position","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/pivot"],"generated":true,"anchor":"Managing-the-Nodes-Transform-SceneKit-Types","title":"Managing the Node’s Transform (SceneKit Types)"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eulerAngles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3","preciseIdentifier":"c:@S@SCNVector3","text":"SCNVector3"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The order of components in this vector matches the axes of rotation:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Pitch (the "},{"code":"x","type":"codeVoice"},{"type":"text","text":" component) is the rotation about the node’s x-axis."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Yaw (the "},{"type":"codeVoice","code":"y"},{"type":"text","text":" component) is the rotation about the node’s y-axis."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Roll (the ","type":"text"},{"code":"z","type":"codeVoice"},{"text":" component) is the rotation about the node’s z-axis.","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"SceneKit applies these rotations relative to the node’s ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/pivot"},{"text":" property in the reverse order of the components: first roll, then yaw, then pitch. The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation"},{"text":", ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/eulerAngles"},{"text":", and ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation"},{"text":" properties all affect the rotational aspect of the node’s ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/transform"},{"text":" property. Any change to one of these properties is reflected in the others.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can animate changes to this property’s value. See "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content"},{"type":"text","text":"."}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"variants":[{"paths":["/documentation/scenekit/scnnode/eulerangles"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/scenekit/scnnode/eulerangles"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/eulerAngles"},"abstract":[{"type":"text","text":"The node’s orientation, expressed as pitch, yaw, and roll angles in radians. Animatable."}],"kind":"symbol","references":{"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation":{"navigatorTitle":[{"text":"rotation","kind":"identifier"}],"role":"symbol","type":"topic","url":"/documentation/scenekit/scnnode/rotation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rotation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@SCNVector4","text":"SCNVector4","kind":"typeIdentifier"}],"abstract":[{"text":"The node’s orientation, expressed as a rotation angle about an axis. Animatable.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation","kind":"symbol","title":"rotation"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale":{"title":"scale","role":"symbol","type":"topic","navigatorTitle":[{"text":"scale","kind":"identifier"}],"abstract":[{"text":"The scale factor applied to the node. Animatable.","type":"text"}],"url":"/documentation/scenekit/scnnode/scale","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@SCNVector3","text":"SCNVector3","kind":"typeIdentifier"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode":{"role":"symbol","kind":"symbol","title":"SCNNode","navigatorTitle":[{"kind":"identifier","text":"SCNNode"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNNode"}],"url":"/documentation/scenekit/scnnode","abstract":[{"text":"A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/eulerAngles":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/eulerAngles","title":"eulerAngles","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The node’s orientation, expressed as pitch, yaw, and roll angles in radians. Animatable."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eulerAngles","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@SCNVector3","text":"SCNVector3","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"eulerAngles","kind":"identifier"}],"url":"/documentation/scenekit/scnnode/eulerangles"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/pivot":{"title":"pivot","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pivot"}],"abstract":[{"text":"The pivot point for the node’s position, rotation, and scale. Animatable.","type":"text"}],"url":"/documentation/scenekit/scnnode/pivot","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pivot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@SCNMatrix4","text":"SCNMatrix4"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/pivot"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/position":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/position","title":"position","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"position"}],"role":"symbol","type":"topic","abstract":[{"text":"The translation applied to the node. Animatable.","type":"text"}],"url":"/documentation/scenekit/scnnode/position","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SCNVector3","preciseIdentifier":"c:@S@SCNVector3"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3":{"kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SCNVector3","kind":"identifier"}],"title":"SCNVector3","navigatorTitle":[{"text":"SCNVector3","kind":"identifier"}],"url":"/documentation/scenekit/scnvector3","abstract":[{"type":"text","text":"A representation of a three-component vector."}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles","url":"/documentation/scenekit/scnnode/simdeulerangles","type":"topic","title":"simdEulerAngles","navigatorTitle":[{"kind":"identifier","text":"simdEulerAngles"}],"abstract":[{"type":"text","text":"The node’s orientation, expressed as pitch, yaw, and roll angles in radians. Animatable."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdEulerAngles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float3","text":"simd_float3"}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/transform":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/transform","role":"symbol","navigatorTitle":[{"text":"transform","kind":"identifier"}],"title":"transform","abstract":[{"text":"The transform applied to the node relative to its parent. Animatable.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transform"},{"text":": ","kind":"text"},{"text":"SCNMatrix4","kind":"typeIdentifier","preciseIdentifier":"c:@S@SCNMatrix4"}],"url":"/documentation/scenekit/scnnode/transform"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content":{"type":"topic","kind":"article","identifier":"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content","abstract":[{"text":"Learn about implicit animations, explicit animations, and actions, and when to choose each in your app.","type":"text"}],"url":"/documentation/scenekit/animating-scenekit-content","role":"article","title":"Animating SceneKit Content"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"role":"symbol","title":"orientation","url":"/documentation/scenekit/scnnode/orientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@SCNQuaternion","text":"SCNQuaternion"}],"abstract":[{"type":"text","text":"The node’s orientation, expressed as a quaternion. Animatable."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1"},{"deprecated":false,"beta":false,"name":"macOS","unavailable":false,"introducedAt":"10.10"},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false},{"deprecated":false,"beta":false,"name":"watchOS","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"eulerAngles"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"eulerAngles"}]},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles"]},{"title":"Managing the Node’s Transform (SceneKit Types)","anchor":"Managing-the-Nodes-Transform-SceneKit-Types","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/transform","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/position","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/pivot"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@SCNVector3","kind":"typeIdentifier","text":"SCNVector3","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3"},{"kind":"text","text":" "},{"kind":"identifier","text":"eulerAngles"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"rotation","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1rotation/title"},{"value":[{"text":"rotation","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1rotation/fragments"},{"op":"replace","value":"scale","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1scale/title"},{"op":"replace","value":[{"kind":"identifier","text":"scale"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1scale/fragments"},{"op":"replace","value":"SCNNode","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title"},{"op":"replace","value":[{"kind":"identifier","text":"SCNNode"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments"},{"op":"replace","value":[{"text":"SCNNode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle"},{"op":"replace","value":"eulerAngles","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1eulerAngles/title"},{"op":"replace","value":[{"kind":"identifier","text":"eulerAngles"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1eulerAngles/fragments"},{"op":"replace","value":"pivot","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1pivot/title"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1pivot/fragments","op":"replace","value":[{"kind":"identifier","text":"pivot"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1position/title","op":"replace","value":"position"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1position/fragments","op":"replace","value":[{"kind":"identifier","text":"position"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/title","op":"replace","value":"SCNVector3"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/fragments","op":"replace","value":[{"kind":"identifier","text":"SCNVector3"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SCNVector3"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdEulerAngles/title","op":"replace","value":"simdEulerAngles"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdEulerAngles/fragments","op":"replace","value":[{"kind":"identifier","text":"simdEulerAngles"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1transform/title","op":"replace","value":"transform"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1transform/fragments","op":"replace","value":[{"text":"transform","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1orientation/title","op":"replace","value":"orientation"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1orientation/fragments","op":"replace","value":[{"kind":"identifier","text":"orientation"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}