{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/scenekit/scnnode/name"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/scenekit/scnnode/name"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNodes(passingTest:)","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNode(withName:recursively:)"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/light","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/camera","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/morpher","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/categoryBitMask","doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume"],"title":"Managing Node Content","anchor":"Managing-Node-Content","generated":true}],"identifier":{"url":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/name","interfaceLanguage":"swift"},"abstract":[{"text":"A name associated with the node.","type":"text"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"metadata":{"platforms":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false},{"name":"watchOS","deprecated":false,"beta":false,"unavailable":false}],"title":"name","navigatorTitle":[{"kind":"identifier","text":"name"}],"externalID":"c:objc(cs)SCNNode(py)name","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"modules":[{"name":"SceneKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"You can provide a descriptive name for a node to make managing your scene graph easier. Nodes loaded from a scene file may have names assigned by an artist using a 3D authoring tool. Use the "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNode(withName:recursively:)","type":"reference","isActive":true},{"type":"text","text":" or "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNodes(passingTest:)","type":"reference","isActive":true},{"type":"text","text":" method to retrieve a node from a scene graph by its name, or the "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource","type":"reference","isActive":true},{"type":"text","text":" class to examine nodes in a scene file without loading its scene graph."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The names of nodes and their attached objects are saved when you export a scene to a file using its "},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNScene/write(to:options:delegate:progressHandler:)","type":"reference"},{"type":"text","text":" method, and appear in the Xcode scene editor. The SceneKit statistics view (see "},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/showsStatistics","type":"reference"},{"type":"text","text":") also shows the names of nodes with attached cameras."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry":{"role":"symbol","kind":"symbol","title":"SCNGeometry","navigatorTitle":[{"text":"SCNGeometry","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNGeometry","kind":"identifier"}],"url":"/documentation/scenekit/scngeometry","abstract":[{"text":"A three-dimensional shape (also called a model or mesh) that can be displayed in a scene, with attached materials that define its appearance.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/morpher":{"title":"morpher","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/morpher","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"morpher","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SCNMorpher","text":"SCNMorpher","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/scenekit/scnnode/morpher","abstract":[{"text":"The morpher object responsible for blending the node’s geometry.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"morpher","kind":"identifier"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/camera":{"url":"/documentation/scenekit/scnnode/camera","role":"symbol","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/camera","title":"camera","navigatorTitle":[{"text":"camera","kind":"identifier"}],"abstract":[{"text":"The camera attached to the node.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SCNCamera","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SCNCamera"},{"text":"?","kind":"text"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode":{"role":"symbol","kind":"symbol","title":"SCNNode","navigatorTitle":[{"kind":"identifier","text":"SCNNode"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNNode"}],"url":"/documentation/scenekit/scnnode","abstract":[{"text":"A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/name":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/name","title":"name","navigatorTitle":[{"kind":"identifier","text":"name"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"A name associated with the node."}],"url":"/documentation/scenekit/scnnode/name","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"title":"NSString","type":"topic","url":"/documentation/foundation/nsstring"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry":{"type":"topic","url":"/documentation/scenekit/scnnode/geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SCNGeometry","preciseIdentifier":"c:objc(cs)SCNGeometry"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"geometry"}],"abstract":[{"type":"text","text":"The geometry attached to the node."}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry","kind":"symbol","role":"symbol","title":"geometry"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNodes(passingTest:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"childNodesPassingTest:"}],"type":"topic","title":"childNodes(passingTest:)","url":"/documentation/scenekit/scnnode/childnodes(passingtest:)","role":"symbol","abstract":[{"type":"text","text":"Returns all nodes in the node’s child node subtree that satisfy the test applied by a block."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"childNodes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"passingTest","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SCNNode","text":"SCNNode"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","text":"ObjCBool","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SCNNode","text":"SCNNode"},{"kind":"text","text":"]"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNodes(passingTest:)"},"doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume":{"url":"/documentation/scenekit/scnboundingvolume","role":"symbol","title":"SCNBoundingVolume","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SCNBoundingVolume"}],"navigatorTitle":[{"kind":"identifier","text":"SCNBoundingVolume"}],"type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume","abstract":[{"text":"Methods common to the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry","isActive":true},{"type":"text","text":" classes for measuring location and size."}],"kind":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/categoryBitMask":{"abstract":[{"type":"text","text":"A mask that defines which categories the node belongs to."}],"url":"/documentation/scenekit/scnnode/categorybitmask","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"categoryBitMask","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"categoryBitMask","type":"topic","kind":"symbol","navigatorTitle":[{"text":"categoryBitMask","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/categoryBitMask"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.externally.resolved.symbol/s:SS":{"type":"topic","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"url":"/documentation/Swift/String","role":"symbol","title":"String","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/light":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"light"}],"type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/light","title":"light","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SCNLight","preciseIdentifier":"c:objc(cs)SCNLight"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"The light attached to the node."}],"url":"/documentation/scenekit/scnnode/light"},"doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource":{"navigatorTitle":[{"text":"SCNSceneSource","kind":"identifier"}],"role":"symbol","url":"/documentation/scenekit/scnscenesource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNSceneSource","kind":"identifier"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource","abstract":[{"type":"text","text":"An object that manages the data-reading tasks associated with loading scene contents from a file or data."}],"kind":"symbol","title":"SCNSceneSource","type":"topic"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner":{"abstract":[{"text":"The skinner object responsible for skeletal animations of node’s contents.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"skinner","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SCNSkinner","text":"SCNSkinner","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"skinner","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"skinner","type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner","url":"/documentation/scenekit/scnnode/skinner"},"doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/showsStatistics":{"url":"/documentation/scenekit/scnscenerenderer/showsstatistics","role":"symbol","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/showsStatistics","title":"showsStatistics","navigatorTitle":[{"text":"showsStatistics","kind":"identifier"}],"abstract":[{"text":"A Boolean value that determines whether SceneKit displays rendering performance statistics in an accessory view.","type":"text"}],"type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsStatistics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit/SCNScene/write(to:options:delegate:progressHandler:)":{"title":"write(to:options:delegate:progressHandler:)","navigatorTitle":[{"kind":"identifier","text":"writeToURL:options:delegate:progressHandler:"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNScene/write(to:options:delegate:progressHandler:)","role":"symbol","url":"/documentation/scenekit/scnscene/write(to:options:delegate:progresshandler:)","type":"topic","abstract":[{"type":"text","text":"Exports the scene and its contents to a file at the specified URL."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SCNSceneExportDelegate","text":"SCNSceneExportDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"progressHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@SCNSceneExportProgressHandler","text":"SCNSceneExportProgressHandler"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNode(withName:recursively:)":{"kind":"symbol","navigatorTitle":[{"text":"childNodeWithName:recursively:","kind":"identifier"}],"type":"topic","title":"childNode(withName:recursively:)","url":"/documentation/scenekit/scnnode/childnode(withname:recursively:)","role":"symbol","abstract":[{"type":"text","text":"Returns the first node in the node’s child node subtree with the specified name."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"childNode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recursively","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)SCNNode","text":"SCNNode","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNode(withName:recursively:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false},{"unavailable":false,"name":"watchOS","deprecated":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"name"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Related-Documentation","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNodes(passingTest:)","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNode(withName:recursively:)"],"title":"Related Documentation"},{"anchor":"Managing-Node-Content","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/light","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/camera","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/morpher","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/categoryBitMask","doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume"],"generated":true,"title":"Managing Node Content"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"name","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SCNGeometry","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/title","op":"replace"},{"value":[{"text":"SCNGeometry","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SCNGeometry"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/navigatorTitle","op":"replace"},{"value":"morpher","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1morpher/title","op":"replace"},{"value":[{"kind":"identifier","text":"morpher"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1morpher/fragments","op":"replace"},{"value":"camera","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1camera/title","op":"replace"},{"value":[{"kind":"identifier","text":"camera"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1camera/fragments","op":"replace"},{"value":"SCNNode","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title","op":"replace"},{"value":[{"kind":"identifier","text":"SCNNode"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments","op":"replace"},{"value":[{"text":"SCNNode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle","op":"replace"},{"value":"name","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1name/title","op":"replace"},{"value":[{"text":"name","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1name/fragments","op":"replace"},{"value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace"},{"value":"geometry","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1geometry/title","op":"replace"},{"value":[{"text":"geometry","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1geometry/fragments","op":"replace"},{"value":"childNodesPassingTest:","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1childNodes(passingTest:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"childNodesPassingTest:"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1childNodes(passingTest:)/fragments","op":"replace"},{"value":"SCNBoundingVolume","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/title","op":"replace"},{"value":[{"kind":"identifier","text":"SCNBoundingVolume"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SCNBoundingVolume"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/navigatorTitle","op":"replace"},{"value":"categoryBitMask","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1categoryBitMask/title","op":"replace"},{"value":[{"kind":"identifier","text":"categoryBitMask"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1categoryBitMask/fragments","op":"replace"},{"value":"light","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1light/title","op":"replace"},{"value":[{"text":"light","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1light/fragments","op":"replace"},{"value":"SCNSceneSource","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/title","op":"replace"},{"value":[{"text":"SCNSceneSource","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/fragments","op":"replace"},{"value":[{"text":"SCNSceneSource","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/navigatorTitle","op":"replace"},{"value":"skinner","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1skinner/title","op":"replace"},{"value":[{"text":"skinner","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1skinner/fragments","op":"replace"},{"value":"showsStatistics","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1showsStatistics/title","op":"replace"},{"value":[{"kind":"identifier","text":"showsStatistics"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1showsStatistics/fragments","op":"replace"},{"value":"writeToURL:options:delegate:progressHandler:","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene~1write(to:options:delegate:progressHandler:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeToURL:options:delegate:progressHandler:"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene~1write(to:options:delegate:progressHandler:)/fragments","op":"replace"},{"value":"childNodeWithName:recursively:","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1childNode(withName:recursively:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"childNodeWithName:recursively:"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1childNode(withName:recursively:)/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}