{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"physicsBody"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SCNPhysicsBody","kind":"typeIdentifier","text":"SCNPhysicsBody","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The default value is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", specifying that the node does not participate in the physics simulation at all. If you provide a physics body, SceneKit updates the node’s position and orientation each time it processes a step of its physics simulation. For more information on SceneKit’s physics system, see ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld","type":"reference"},{"text":".","type":"text"}]}]}],"sections":[],"kind":"symbol","metadata":{"externalID":"c:objc(cs)SCNNode(py)physicsBody","role":"symbol","title":"physicsBody","modules":[{"name":"SceneKit"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"13.1","beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"10.10","beta":false,"deprecated":false,"unavailable":false,"name":"macOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"watchOS"}],"navigatorTitle":[{"kind":"identifier","text":"physicsBody"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"physicsBody"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SCNPhysicsBody","kind":"typeIdentifier","text":"SCNPhysicsBody"},{"kind":"text","text":"?"}]},"abstract":[{"type":"text","text":"The physics body associated with the node."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/scenekit/scnnode/physicsbody"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/scenekit/scnnode/physicsbody"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsBody"},"seeAlsoSections":[{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsField"],"anchor":"Adding-Physics-to-a-Node","generated":true,"title":"Adding Physics to a Node"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode":{"role":"symbol","kind":"symbol","title":"SCNNode","navigatorTitle":[{"kind":"identifier","text":"SCNNode"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNNode"}],"url":"/documentation/scenekit/scnnode","abstract":[{"text":"A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsBody":{"type":"topic","url":"/documentation/scenekit/scnnode/physicsbody","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"physicsBody"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SCNPhysicsBody","preciseIdentifier":"c:objc(cs)SCNPhysicsBody"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"physicsBody"}],"abstract":[{"type":"text","text":"The physics body associated with the node."}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsBody","kind":"symbol","role":"symbol","title":"physicsBody"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsField":{"url":"/documentation/scenekit/scnnode/physicsfield","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsField","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"physicsField"}],"title":"physicsField","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"physicsField","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SCNPhysicsField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SCNPhysicsField"},{"text":"?","kind":"text"}],"abstract":[{"text":"The physics field associated with the node.","type":"text"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld":{"role":"symbol","kind":"symbol","title":"SCNPhysicsWorld","navigatorTitle":[{"kind":"identifier","text":"SCNPhysicsWorld"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNPhysicsWorld"}],"url":"/documentation/scenekit/scnphysicsworld","abstract":[{"type":"text","text":"The global simulation of collisions, gravity, joints, and other physics effects in a scene."}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld"},"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody","abstract":[{"type":"text","text":"The physics simulation attributes attached to a scene graph node."}],"url":"/documentation/scenekit/scnphysicsbody","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCNPhysicsBody"}],"title":"SCNPhysicsBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNPhysicsBody"}]},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"introducedAt":"10.10","unavailable":false,"name":"macOS","deprecated":false,"beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false},{"unavailable":false,"name":"watchOS","deprecated":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"physicsBody","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"physicsBody"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Adding Physics to a Node","anchor":"Adding-Physics-to-a-Node","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsField"],"generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"retain"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)SCNPhysicsBody","kind":"typeIdentifier","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody","text":"SCNPhysicsBody"},{"kind":"text","text":" * "},{"kind":"identifier","text":"physicsBody"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title","value":"SCNNode","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments","value":[{"kind":"identifier","text":"SCNNode"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle","value":[{"kind":"identifier","text":"SCNNode"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1physicsBody/title","value":"physicsBody","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1physicsBody/fragments","value":[{"kind":"identifier","text":"physicsBody"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1physicsField/title","value":"physicsField","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1physicsField/fragments","value":[{"kind":"identifier","text":"physicsField"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsWorld/title","value":"SCNPhysicsWorld","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsWorld/fragments","value":[{"text":"SCNPhysicsWorld","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsWorld/navigatorTitle","value":[{"text":"SCNPhysicsWorld","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SCNPhysicsBody","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/title"},{"op":"replace","value":[{"kind":"identifier","text":"SCNPhysicsBody"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/fragments"},{"op":"replace","value":[{"text":"SCNPhysicsBody","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}