{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SCNNode","kind":"typeIdentifier","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode","preciseIdentifier":"c:objc(cs)SCNNode"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"When you use implicit animation (see ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction"},{"text":") to change a node’s properties, those node properties are set immediately to their target values, even though the animated node content appears to transition from the old property values to the new. During the animation SceneKit maintains a copy of the node, called the ","type":"text"},{"type":"strong","inlineContent":[{"text":"presentation node","type":"text"}]},{"text":", whose properties reflect the transitory values determined by any in-flight animations currently affecting the node. The presentation node’s properties provide a close approximation to the version of the node that is currently displayed. SceneKit also uses the presentation node when computing the results of explicit animations, physics, and constraints.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Do not modify the properties of the presentation node. (Attempting to do so results in undefined behavior.) Instead, you use the presentation node to read current animation values—for example, to create a new animation starting at those values."}],"type":"paragraph"},{"inlineContent":[{"text":"The presentation node has no parent or child nodes. To access animated properties of related nodes, use the node’s own ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/parent","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNodes","isActive":true,"type":"reference"},{"text":" properties and the ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/presentation","isActive":true,"type":"reference"},{"text":" property of each related node.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"paths":["/documentation/scenekit/scnnode/presentation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/scenekit/scnnode/presentation"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Working with Node Animation","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/isPaused"],"anchor":"Working-with-Node-Animation","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"sections":[],"metadata":{"title":"presentation","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"presentation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SCNNode","preciseIdentifier":"c:objc(cs)SCNNode","kind":"typeIdentifier"}],"modules":[{"name":"SceneKit"}],"platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"unavailable":false,"deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false},{"unavailable":false,"deprecated":false,"name":"watchOS","beta":false}],"navigatorTitle":[{"text":"presentationNode","kind":"identifier"}],"externalID":"c:objc(cs)SCNNode(py)presentationNode","roleHeading":"Instance Property"},"abstract":[{"text":"A node object representing the state of the node as it currently appears onscreen.","type":"text"}],"identifier":{"url":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/presentation","interfaceLanguage":"swift"},"references":{"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction":{"abstract":[{"text":"A mechanism for creating implicit animations and combining scene graph changes into atomic updates.","type":"text"}],"title":"SCNTransaction","type":"topic","navigatorTitle":[{"text":"SCNTransaction","kind":"identifier"}],"url":"/documentation/scenekit/scntransaction","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNTransaction","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/parent":{"title":"parent","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"parentNode","kind":"identifier"}],"type":"topic","abstract":[{"text":"The node’s parent in the scene graph hierarchy.","type":"text"}],"url":"/documentation/scenekit/scnnode/parent","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/parent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SCNNode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SCNNode"},{"text":"?","kind":"text"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode":{"role":"symbol","kind":"symbol","title":"SCNNode","navigatorTitle":[{"kind":"identifier","text":"SCNNode"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNNode"}],"url":"/documentation/scenekit/scnnode","abstract":[{"text":"A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/presentation":{"url":"/documentation/scenekit/scnnode/presentation","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/presentation","title":"presentation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SCNNode","text":"SCNNode"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"presentationNode"}],"abstract":[{"type":"text","text":"A node object representing the state of the node as it currently appears onscreen."}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/isPaused":{"url":"/documentation/scenekit/scnnode/ispaused","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/isPaused","title":"isPaused","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPaused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paused"}],"abstract":[{"type":"text","text":"A Boolean value that determines whether to run actions and animations attached to the node and its child nodes."}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNodes":{"role":"symbol","url":"/documentation/scenekit/scnnode/childnodes","type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/childNodes","title":"childNodes","kind":"symbol","abstract":[{"type":"text","text":"An array of the node’s children in the scene graph hierarchy."}],"navigatorTitle":[{"kind":"identifier","text":"childNodes"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childNodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SCNNode","preciseIdentifier":"c:objc(cs)SCNNode"},{"kind":"text","text":"]"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"name":"macOS","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false},{"beta":false,"name":"watchOS","deprecated":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"presentationNode","path":"/metadata/title"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"presentationNode","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]}},{"op":"add","path":"/topicSections","value":null},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Working with Node Animation","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/isPaused"],"generated":true,"anchor":"Working-with-Node-Animation"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)SCNNode","kind":"typeIdentifier","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode","text":"SCNNode"},{"kind":"text","text":" * "},{"kind":"identifier","text":"presentationNode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction/title","op":"replace","value":"SCNTransaction"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction/fragments","op":"replace","value":[{"kind":"identifier","text":"SCNTransaction"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SCNTransaction"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1parent/title","op":"replace","value":"parentNode"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1parent/fragments","op":"replace","value":[{"kind":"identifier","text":"parentNode"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title","op":"replace","value":"SCNNode"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments","op":"replace","value":[{"kind":"identifier","text":"SCNNode"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle","op":"replace","value":[{"text":"SCNNode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1presentation/title","op":"replace","value":"presentationNode"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1presentation/fragments","op":"replace","value":[{"kind":"identifier","text":"presentationNode"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1isPaused/title","op":"replace","value":"paused"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1isPaused/fragments","op":"replace","value":[{"kind":"identifier","text":"paused"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1childNodes/title","op":"replace","value":"childNodes"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1childNodes/fragments","op":"replace","value":[{"text":"childNodes","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}