{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale"],"anchor":"Related-Documentation"},{"title":"Managing the Node’s Transform (SceneKit Types)","generated":true,"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/transform","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/position","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/eulerAngles","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/pivot"],"anchor":"Managing-the-Nodes-Transform-SceneKit-Types"}],"variants":[{"paths":["/documentation/scenekit/scnnode/scale"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/scenekit/scnnode/scale"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"platforms":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"name":"macOS","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false},{"deprecated":false,"name":"watchOS","beta":false,"unavailable":false}],"role":"symbol","modules":[{"name":"SceneKit"}],"title":"scale","externalID":"c:objc(cs)SCNNode(py)scale","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"scale"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scale"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@SCNVector3","kind":"typeIdentifier","text":"SCNVector3"}],"roleHeading":"Instance Property"},"abstract":[{"text":"The scale factor applied to the node. Animatable.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@SCNVector3","text":"SCNVector3","kind":"typeIdentifier","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each component of the scale vector multiplies the corresponding dimension of the node’s geometry. The default scale is "},{"code":"1.0","type":"codeVoice"},{"type":"text","text":" in all three dimensions. For example, applying a scale of (2.0, 0.5, 2.0) to a node containing a cube geometry reduces its height and increases its width and depth. Scaling is applied relative to the node’s "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/pivot","isActive":true,"type":"reference"},{"type":"text","text":" property."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can animate changes to this property’s value. See "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content","type":"reference","isActive":true},{"type":"text","text":"."}]}]}],"references":{"doc://com.apple.scenekit/documentation/SceneKit/SCNNode":{"role":"symbol","kind":"symbol","title":"SCNNode","navigatorTitle":[{"kind":"identifier","text":"SCNNode"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNNode"}],"url":"/documentation/scenekit/scnnode","abstract":[{"text":"A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation":{"navigatorTitle":[{"text":"rotation","kind":"identifier"}],"role":"symbol","type":"topic","url":"/documentation/scenekit/scnnode/rotation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rotation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@SCNVector4","text":"SCNVector4","kind":"typeIdentifier"}],"abstract":[{"text":"The node’s orientation, expressed as a rotation angle about an axis. Animatable.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation","kind":"symbol","title":"rotation"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale":{"title":"scale","role":"symbol","type":"topic","navigatorTitle":[{"text":"scale","kind":"identifier"}],"abstract":[{"text":"The scale factor applied to the node. Animatable.","type":"text"}],"url":"/documentation/scenekit/scnnode/scale","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@SCNVector3","text":"SCNVector3","kind":"typeIdentifier"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/pivot":{"title":"pivot","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pivot"}],"abstract":[{"text":"The pivot point for the node’s position, rotation, and scale. Animatable.","type":"text"}],"url":"/documentation/scenekit/scnnode/pivot","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pivot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@SCNMatrix4","text":"SCNMatrix4"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/pivot"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"role":"symbol","title":"orientation","url":"/documentation/scenekit/scnnode/orientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@SCNQuaternion","text":"SCNQuaternion"}],"abstract":[{"type":"text","text":"The node’s orientation, expressed as a quaternion. Animatable."}],"kind":"symbol","type":"topic"},"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content":{"type":"topic","kind":"article","identifier":"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content","abstract":[{"text":"Learn about implicit animations, explicit animations, and actions, and when to choose each in your app.","type":"text"}],"url":"/documentation/scenekit/animating-scenekit-content","role":"article","title":"Animating SceneKit Content"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/eulerAngles":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/eulerAngles","title":"eulerAngles","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The node’s orientation, expressed as pitch, yaw, and roll angles in radians. Animatable."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eulerAngles","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@SCNVector3","text":"SCNVector3","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"eulerAngles","kind":"identifier"}],"url":"/documentation/scenekit/scnnode/eulerangles"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/transform":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/transform","role":"symbol","navigatorTitle":[{"text":"transform","kind":"identifier"}],"title":"transform","abstract":[{"text":"The transform applied to the node relative to its parent. Animatable.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transform"},{"text":": ","kind":"text"},{"text":"SCNMatrix4","kind":"typeIdentifier","preciseIdentifier":"c:@S@SCNMatrix4"}],"url":"/documentation/scenekit/scnnode/transform"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale","navigatorTitle":[{"kind":"identifier","text":"simdScale"}],"role":"symbol","title":"simdScale","url":"/documentation/scenekit/scnnode/simdscale","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float3","text":"simd_float3"}],"abstract":[{"type":"text","text":"The scale factor applied to the node. Animatable."}],"kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/position":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/position","title":"position","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"position"}],"role":"symbol","type":"topic","abstract":[{"text":"The translation applied to the node. Animatable.","type":"text"}],"url":"/documentation/scenekit/scnnode/position","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SCNVector3","preciseIdentifier":"c:@S@SCNVector3"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3":{"kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SCNVector3","kind":"identifier"}],"title":"SCNVector3","navigatorTitle":[{"text":"SCNVector3","kind":"identifier"}],"url":"/documentation/scenekit/scnvector3","abstract":[{"type":"text","text":"A representation of a three-component vector."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"name":"macOS","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false},{"deprecated":false,"name":"watchOS","beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"scale"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"scale","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/transform","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/position","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/eulerAngles","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/pivot"],"title":"Managing the Node’s Transform (SceneKit Types)","generated":true,"anchor":"Managing-the-Nodes-Transform-SceneKit-Types"}]},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@S@SCNVector3","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3","text":"SCNVector3","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"scale","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"SCNNode","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title","op":"replace"},{"value":[{"kind":"identifier","text":"SCNNode"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SCNNode"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle","op":"replace"},{"value":"rotation","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1rotation/title","op":"replace"},{"value":[{"kind":"identifier","text":"rotation"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1rotation/fragments","op":"replace"},{"value":"scale","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1scale/title","op":"replace"},{"value":[{"kind":"identifier","text":"scale"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1scale/fragments","op":"replace"},{"value":"pivot","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1pivot/title","op":"replace"},{"value":[{"text":"pivot","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1pivot/fragments","op":"replace"},{"value":"orientation","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1orientation/title","op":"replace"},{"value":[{"text":"orientation","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1orientation/fragments","op":"replace"},{"value":"eulerAngles","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1eulerAngles/title","op":"replace"},{"value":[{"text":"eulerAngles","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1eulerAngles/fragments","op":"replace"},{"value":"transform","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1transform/title","op":"replace"},{"op":"replace","value":[{"text":"transform","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1transform/fragments"},{"op":"replace","value":"simdScale","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdScale/title"},{"op":"replace","value":[{"kind":"identifier","text":"simdScale"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdScale/fragments"},{"op":"replace","value":"position","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1position/title"},{"op":"replace","value":[{"kind":"identifier","text":"position"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1position/fragments"},{"op":"replace","value":"SCNVector3","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/title"},{"op":"replace","value":[{"text":"SCNVector3","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/fragments"},{"op":"replace","value":[{"text":"SCNVector3","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}