{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdRotation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@simd_float4","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@simd_float4","text":"simd_float4"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The four-component rotation vector specifies the direction of the rotation axis in the first three components and the angle of rotation (in radians) in the fourth. The default rotation is the zero vector, specifying no rotation. Rotation is applied relative to the node’s "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPivot","type":"reference","isActive":true},{"type":"text","text":" property."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdRotation"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles"},{"type":"text","text":", and "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdOrientation"},{"type":"text","text":" properties all affect the rotational aspect of the node’s "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform"},{"type":"text","text":" property. Any change to one of these properties is reflected in the others."}]},{"type":"paragraph","inlineContent":[{"text":"You can animate changes to this property’s value. See ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content","type":"reference"},{"text":".","type":"text"}]}],"kind":"content"}],"metadata":{"roleHeading":"Instance Property","platforms":[{"beta":false,"introducedAt":"11.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"11.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.1","deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"beta":false,"introducedAt":"10.13","deprecated":false,"unavailable":false,"name":"macOS"},{"beta":false,"introducedAt":"11.0","deprecated":false,"unavailable":false,"name":"tvOS"},{"beta":false,"introducedAt":"1.0","deprecated":false,"unavailable":false,"name":"visionOS"},{"beta":false,"introducedAt":"4.0","deprecated":false,"unavailable":false,"name":"watchOS"}],"title":"simdRotation","symbolKind":"property","extendedModule":"SceneKit","role":"symbol","navigatorTitle":[{"text":"simdRotation","kind":"identifier"}],"modules":[{"name":"SceneKit"}],"externalID":"c:objc(cs)SCNNode(py)simdRotation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simdRotation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"simd_float4","kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float4"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdRotation","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/scenekit/scnnode/simdrotation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/scenekit/scnnode/simdrotation"]}],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation"]},{"anchor":"Managing-the-Nodes-Transform","generated":true,"title":"Managing the Node’s Transform","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdOrientation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPivot"]}],"abstract":[{"type":"text","text":"The node’s orientation, expressed as a rotation angle about an axis. Animatable."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPivot":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdPivot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@simd_float4x4","text":"simd_float4x4"}],"title":"simdPivot","type":"topic","url":"/documentation/scenekit/scnnode/simdpivot","abstract":[{"type":"text","text":"The pivot point for the node’s position, rotation, and scale. Animatable."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"simdPivot"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPivot"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdRotation":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdRotation","abstract":[{"type":"text","text":"The node’s orientation, expressed as a rotation angle about an axis. Animatable."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float4","text":"simd_float4"}],"role":"symbol","type":"topic","title":"simdRotation","navigatorTitle":[{"kind":"identifier","text":"simdRotation"}],"url":"/documentation/scenekit/scnnode/simdrotation"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform","navigatorTitle":[{"kind":"identifier","text":"simdTransform"}],"role":"symbol","title":"simdTransform","url":"/documentation/scenekit/scnnode/simdtransform","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdTransform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@simd_float4x4","text":"simd_float4x4"}],"abstract":[{"type":"text","text":"The transform applied to the node relative to its parent. Animatable."}],"kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@simd_float4":{"url":"/documentation/simd/simd_float4","title":"simd_float4","abstract":[{"type":"text","text":"A vector of four 32-bit floating-point elements."}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@simd_float4","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"simd_float4"},{"kind":"text","text":" = "},{"preciseIdentifier":"s:s5SIMD4V","text":"SIMD4","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles","url":"/documentation/scenekit/scnnode/simdeulerangles","type":"topic","title":"simdEulerAngles","navigatorTitle":[{"kind":"identifier","text":"simdEulerAngles"}],"abstract":[{"type":"text","text":"The node’s orientation, expressed as pitch, yaw, and roll angles in radians. Animatable."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdEulerAngles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float3","text":"simd_float3"}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode":{"role":"symbol","kind":"symbol","title":"SCNNode","navigatorTitle":[{"kind":"identifier","text":"SCNNode"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNNode"}],"url":"/documentation/scenekit/scnnode","abstract":[{"text":"A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content":{"type":"topic","kind":"article","identifier":"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content","abstract":[{"text":"Learn about implicit animations, explicit animations, and actions, and when to choose each in your app.","type":"text"}],"url":"/documentation/scenekit/animating-scenekit-content","role":"article","title":"Animating SceneKit Content"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdOrientation":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdOrientation","navigatorTitle":[{"kind":"identifier","text":"simdOrientation"}],"role":"symbol","title":"simdOrientation","url":"/documentation/scenekit/scnnode/simdorientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@simd_quatf","text":"simd_quatf"}],"abstract":[{"type":"text","text":"The node’s orientation, expressed as a quaternion. Animatable."}],"kind":"symbol","type":"topic"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation":{"navigatorTitle":[{"text":"rotation","kind":"identifier"}],"role":"symbol","type":"topic","url":"/documentation/scenekit/scnnode/rotation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rotation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@SCNVector4","text":"SCNVector4","kind":"typeIdentifier"}],"abstract":[{"text":"The node’s orientation, expressed as a rotation angle about an axis. Animatable.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation","kind":"symbol","title":"rotation"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale","navigatorTitle":[{"kind":"identifier","text":"simdScale"}],"role":"symbol","title":"simdScale","url":"/documentation/scenekit/scnnode/simdscale","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float3","text":"simd_float3"}],"abstract":[{"type":"text","text":"The scale factor applied to the node. Animatable."}],"kind":"symbol","type":"topic"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition","abstract":[{"type":"text","text":"The translation applied to the node. Animatable."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float3","text":"simd_float3"}],"role":"symbol","type":"topic","title":"simdPosition","navigatorTitle":[{"kind":"identifier","text":"simdPosition"}],"url":"/documentation/scenekit/scnnode/simdposition"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"11.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"11.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.1"},{"name":"macOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.13"},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"11.0"},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0"},{"name":"watchOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"4.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"simdRotation","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"simdRotation"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Related Documentation","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/rotation"],"anchor":"Related-Documentation"},{"title":"Managing the Node’s Transform","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdOrientation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPivot"],"anchor":"Managing-the-Nodes-Transform","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"simd_float4","preciseIdentifier":"c:@T@simd_float4","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@simd_float4"},{"text":" ","kind":"text"},{"text":"simdRotation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdPivot/title","value":"simdPivot","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdPivot/fragments","value":[{"text":"simdPivot","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdRotation/title","value":"simdRotation","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdRotation/fragments","value":[{"kind":"identifier","text":"simdRotation"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdTransform/title","value":"simdTransform","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdTransform/fragments","value":[{"kind":"identifier","text":"simdTransform"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@simd_float4/fragments","value":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:]4f","text":"float __attribute__((ext_vector_type(4)))"},{"kind":"text","text":" "},{"kind":"identifier","text":"simd_float4"},{"kind":"text","text":";"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdEulerAngles/title","value":"simdEulerAngles","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdEulerAngles/fragments","value":[{"text":"simdEulerAngles","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title","value":"SCNNode","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments","value":[{"kind":"identifier","text":"SCNNode"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle","op":"replace","value":[{"text":"SCNNode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdOrientation/title","op":"replace","value":"simdOrientation"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdOrientation/fragments","op":"replace","value":[{"kind":"identifier","text":"simdOrientation"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1rotation/title","op":"replace","value":"rotation"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1rotation/fragments","op":"replace","value":[{"text":"rotation","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdScale/title","op":"replace","value":"simdScale"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdScale/fragments","op":"replace","value":[{"kind":"identifier","text":"simdScale"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdPosition/title","op":"replace","value":"simdPosition"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdPosition/fragments","op":"replace","value":[{"kind":"identifier","text":"simdPosition"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}