{"abstract":[{"text":"The scale factor applied to the node. Animatable.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/scenekit/scnnode/simdscale"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/scenekit/scnnode/simdscale"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale"],"anchor":"Related-Documentation","title":"Related Documentation"},{"anchor":"Managing-the-Nodes-Transform","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdRotation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdOrientation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPivot"],"generated":true,"title":"Managing the Node’s Transform"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simdScale","kind":"identifier"},{"text":": ","kind":"text"},{"text":"simd_float3","identifier":"doc://com.externally.resolved.symbol/c:@T@simd_float3","kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float3"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Each component of the scale vector multiplies the corresponding dimension of the node’s geometry. The default scale is "},{"code":"1.0","type":"codeVoice"},{"type":"text","text":" in all three dimensions. For example, applying a scale of (2.0, 0.5, 2.0) to a node containing a cube geometry reduces its height and increases its width and depth. Scaling is applied relative to the node’s "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPivot","type":"reference","isActive":true},{"type":"text","text":" property."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can animate changes to this property’s value. See "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float3","text":"simd_float3"}],"role":"symbol","externalID":"c:objc(cs)SCNNode(py)simdScale","platforms":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"11.0","deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"11.0","deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","deprecated":false},{"unavailable":false,"name":"macOS","beta":false,"introducedAt":"10.13","deprecated":false},{"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"11.0","deprecated":false},{"deprecated":false,"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"4.0","name":"watchOS","unavailable":false}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"simdScale"}],"extendedModule":"SceneKit","modules":[{"name":"SceneKit"}],"title":"simdScale"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale","interfaceLanguage":"swift"},"references":{"doc://com.externally.resolved.symbol/c:@T@simd_float3":{"role":"symbol","kind":"symbol","title":"simd_float3","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"simd_float3"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5SIMD3V","text":"SIMD3"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":">"}],"url":"/documentation/simd/simd_float3","abstract":[{"type":"text","text":"A vector of three 32-bit floating-point elements."}],"identifier":"doc://com.externally.resolved.symbol/c:@T@simd_float3"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform","navigatorTitle":[{"kind":"identifier","text":"simdTransform"}],"role":"symbol","title":"simdTransform","url":"/documentation/scenekit/scnnode/simdtransform","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdTransform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@simd_float4x4","text":"simd_float4x4"}],"abstract":[{"type":"text","text":"The transform applied to the node relative to its parent. Animatable."}],"kind":"symbol","type":"topic"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPivot":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdPivot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@simd_float4x4","text":"simd_float4x4"}],"title":"simdPivot","type":"topic","url":"/documentation/scenekit/scnnode/simdpivot","abstract":[{"type":"text","text":"The pivot point for the node’s position, rotation, and scale. Animatable."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"simdPivot"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPivot"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition","abstract":[{"type":"text","text":"The translation applied to the node. Animatable."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float3","text":"simd_float3"}],"role":"symbol","type":"topic","title":"simdPosition","navigatorTitle":[{"kind":"identifier","text":"simdPosition"}],"url":"/documentation/scenekit/scnnode/simdposition"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles","url":"/documentation/scenekit/scnnode/simdeulerangles","type":"topic","title":"simdEulerAngles","navigatorTitle":[{"kind":"identifier","text":"simdEulerAngles"}],"abstract":[{"type":"text","text":"The node’s orientation, expressed as pitch, yaw, and roll angles in radians. Animatable."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdEulerAngles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float3","text":"simd_float3"}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale":{"title":"scale","role":"symbol","type":"topic","navigatorTitle":[{"text":"scale","kind":"identifier"}],"abstract":[{"text":"The scale factor applied to the node. Animatable.","type":"text"}],"url":"/documentation/scenekit/scnnode/scale","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@SCNVector3","text":"SCNVector3","kind":"typeIdentifier"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode":{"role":"symbol","kind":"symbol","title":"SCNNode","navigatorTitle":[{"kind":"identifier","text":"SCNNode"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNNode"}],"url":"/documentation/scenekit/scnnode","abstract":[{"text":"A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdScale","navigatorTitle":[{"kind":"identifier","text":"simdScale"}],"role":"symbol","title":"simdScale","url":"/documentation/scenekit/scnnode/simdscale","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float3","text":"simd_float3"}],"abstract":[{"type":"text","text":"The scale factor applied to the node. Animatable."}],"kind":"symbol","type":"topic"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdOrientation":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdOrientation","navigatorTitle":[{"kind":"identifier","text":"simdOrientation"}],"role":"symbol","title":"simdOrientation","url":"/documentation/scenekit/scnnode/simdorientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@simd_quatf","text":"simd_quatf"}],"abstract":[{"type":"text","text":"The node’s orientation, expressed as a quaternion. Animatable."}],"kind":"symbol","type":"topic"},"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content":{"type":"topic","kind":"article","identifier":"doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content","abstract":[{"text":"Learn about implicit animations, explicit animations, and actions, and when to choose each in your app.","type":"text"}],"url":"/documentation/scenekit/animating-scenekit-content","role":"article","title":"Animating SceneKit Content"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdRotation":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdRotation","abstract":[{"type":"text","text":"The node’s orientation, expressed as a rotation angle about an axis. Animatable."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float4","text":"simd_float4"}],"role":"symbol","type":"topic","title":"simdRotation","navigatorTitle":[{"kind":"identifier","text":"simdRotation"}],"url":"/documentation/scenekit/scnnode/simdrotation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"introducedAt":"11.0","name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"11.0","name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"10.13","name":"macOS","deprecated":false,"beta":false},{"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"11.0","deprecated":false},{"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"1.0","deprecated":false},{"unavailable":false,"name":"watchOS","beta":false,"introducedAt":"4.0","deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"simdScale","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"simdScale"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNNode"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/scale"],"title":"Related Documentation","anchor":"Related-Documentation"},{"generated":true,"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdRotation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdEulerAngles","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdOrientation","doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPivot"],"title":"Managing the Node’s Transform","anchor":"Managing-the-Nodes-Transform"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"simd_float3","identifier":"doc://com.externally.resolved.symbol/c:@T@simd_float3","preciseIdentifier":"c:@T@simd_float3"},{"kind":"text","text":" "},{"kind":"identifier","text":"simdScale"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@simd_float3/fragments","op":"replace","value":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"float __attribute__((ext_vector_type(3)))","preciseIdentifier":"c:]3f","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"simd_float3","kind":"identifier"},{"text":";","kind":"text"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdTransform/title","op":"replace","value":"simdTransform"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdTransform/fragments","op":"replace","value":[{"kind":"identifier","text":"simdTransform"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdPivot/title","op":"replace","value":"simdPivot"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdPivot/fragments","op":"replace","value":[{"text":"simdPivot","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdPosition/title","op":"replace","value":"simdPosition"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdPosition/fragments","op":"replace","value":[{"text":"simdPosition","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdEulerAngles/title","op":"replace","value":"simdEulerAngles"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdEulerAngles/fragments","op":"replace","value":[{"text":"simdEulerAngles","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1scale/title","op":"replace","value":"scale"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1scale/fragments","op":"replace","value":[{"kind":"identifier","text":"scale"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title","op":"replace","value":"SCNNode"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments","op":"replace","value":[{"kind":"identifier","text":"SCNNode"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SCNNode"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdScale/title","op":"replace","value":"simdScale"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdScale/fragments","op":"replace","value":[{"kind":"identifier","text":"simdScale"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdOrientation/title","op":"replace","value":"simdOrientation"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdOrientation/fragments","op":"replace","value":[{"text":"simdOrientation","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdRotation/title","op":"replace","value":"simdRotation"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdRotation/fragments","op":"replace","value":[{"text":"simdRotation","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}