{
  "abstract": [
    {
      "text": "Returns the bounds of the object that the on-screen control applies to.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/objectBounds()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FxOnScreenControlAPI_v2(im)objectBounds",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "objectBounds"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSRect",
        "text": "NSRect"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "objectBounds"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.1",
        "name": "FxPlug"
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "objectBounds()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "objectBounds"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The rectangle of the on-screen control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "FxOnScreenControlAPI_v2",
          "type": "codeVoice"
        },
        {
          "text": " protocol specifies additions to the ",
          "type": "text"
        },
        {
          "code": "FxOnScreenControlAPI",
          "type": "codeVoice"
        },
        {
          "text": " protocol which defines the methods the host application provides to manage conversions between various on-screen coordinate spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxOnScreenControlAPI_v2"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxOnScreenControlAPI_v2"
        }
      ],
      "role": "symbol",
      "title": "FxOnScreenControlAPI_v2",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi_v2"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/canvasPixelAspectRatio()": {
      "abstract": [
        {
          "text": "Returns the pixel aspect ratio of the canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canvasPixelAspectRatio"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/canvasPixelAspectRatio()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canvasPixelAspectRatio"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "canvasPixelAspectRatio()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi_v2/canvaspixelaspectratio()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/canvasZoom()": {
      "abstract": [
        {
          "text": "Returns the zoom factor the user has set the canvas",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canvasZoom"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/canvasZoom()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canvasZoom"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "canvasZoom()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi_v2/canvaszoom()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/objectBounds()": {
      "abstract": [
        {
          "text": "Returns the bounds of the object that the on-screen control applies to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectBounds"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/objectBounds()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectBounds"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "objectBounds()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi_v2/objectbounds()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/objectToScreenTransform()": {
      "abstract": [
        {
          "text": "Returns a 4x4 matrix describing the transformation from object normalized space",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectToScreenTransform"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FxMatrix44",
          "text": "FxMatrix44"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/objectToScreenTransform()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectToScreenTransform"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "objectToScreenTransform()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi_v2/objecttoscreentransform()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/pixelAspectRatio()": {
      "abstract": [
        {
          "text": "Returns the pixel aspect ratio for which the on-screen control applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelAspectRatio"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/pixelAspectRatio()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelAspectRatio"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pixelAspectRatio()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi_v2/pixelaspectratio()"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSRect": {
      "abstract": [
        {
          "text": "A rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRect",
      "type": "topic",
      "url": "/documentation/foundation/nsrect"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Canvas-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/canvasZoom()",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/canvasPixelAspectRatio()",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/pixelAspectRatio()",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/objectToScreenTransform()"
      ],
      "title": "Canvas Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "objectBounds"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Canvas-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/canvasZoom()",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/canvasPixelAspectRatio()",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/pixelAspectRatio()",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2/objectToScreenTransform()"
              ],
              "title": "Canvas Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSRect",
                    "text": "NSRect"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "objectBounds"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The rectangle of the on-screen control.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2~1canvasPixelAspectRatio()/title",
          "value": "canvasPixelAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2~1canvasPixelAspectRatio()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canvasPixelAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2~1objectToScreenTransform()/title",
          "value": "objectToScreenTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2~1objectToScreenTransform()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectToScreenTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2~1pixelAspectRatio()/title",
          "value": "pixelAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2~1pixelAspectRatio()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pixelAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2/title",
          "value": "FxOnScreenControlAPI_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2~1canvasZoom()/title",
          "value": "canvasZoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2~1canvasZoom()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canvasZoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2~1objectBounds()/title",
          "value": "objectBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2~1objectBounds()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectBounds"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxonscreencontrolapi_v2/objectbounds()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxonscreencontrolapi_v2/objectbounds()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
