{
  "abstract": [
    {
      "text": "Tells the delegate when the synthesizer finishes speaking an utterance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didFinish:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVSpeechSynthesizerDelegate(im)speechSynthesizer:didFinishSpeechUtterance:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "speechSynthesizer"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
        "text": "AVSpeechSynthesizer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didFinish"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
        "text": "AVSpeechUtterance"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "speechSynthesizer:didFinishSpeechUtterance:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "speechSynthesizer(_:didFinish:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "speechSynthesizer"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "synthesizer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
              "text": "AVSpeechSynthesizer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didFinish"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "utterance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
              "text": "AVSpeechUtterance"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The speech synthesizer that finishes speaking the utterance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "synthesizer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The utterance that the speech synthesizer finishes speaking.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "utterance"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system ignores the final utterance’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance/postUtteranceDelay",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and calls this method immediately when speech ends.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer": {
      "abstract": [
        {
          "text": "An object that produces synthesized speech from text utterances and enables monitoring or controlling of ongoing speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesizer"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesizer"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesizer",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol that contains optional methods you can implement to respond to events that occur during speech synthesis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesizerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesizerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesizerDelegate",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizerdelegate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didCancel:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the synthesizer cancels speaking an utterance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechSynthesizer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didCancel:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speechSynthesizer:didCancelSpeechUtterance:"
        }
      ],
      "role": "symbol",
      "title": "speechSynthesizer(_:didCancel:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizerdelegate/speechsynthesizer(_:didcancel:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didContinue:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the synthesizer resumes speaking an utterance after pausing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechSynthesizer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didContinue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didContinue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speechSynthesizer:didContinueSpeechUtterance:"
        }
      ],
      "role": "symbol",
      "title": "speechSynthesizer(_:didContinue:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizerdelegate/speechsynthesizer(_:didcontinue:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didFinish:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the synthesizer finishes speaking an utterance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechSynthesizer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinish"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didFinish:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speechSynthesizer:didFinishSpeechUtterance:"
        }
      ],
      "role": "symbol",
      "title": "speechSynthesizer(_:didFinish:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizerdelegate/speechsynthesizer(_:didfinish:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didPause:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the synthesizer pauses while speaking an utterance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechSynthesizer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didPause"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didPause:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speechSynthesizer:didPauseSpeechUtterance:"
        }
      ],
      "role": "symbol",
      "title": "speechSynthesizer(_:didPause:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizerdelegate/speechsynthesizer(_:didpause:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didStart:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the synthesizer begins speaking an utterance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechSynthesizer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didStart:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speechSynthesizer:didStartSpeechUtterance:"
        }
      ],
      "role": "symbol",
      "title": "speechSynthesizer(_:didStart:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizerdelegate/speechsynthesizer(_:didstart:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:willSpeak:utterance:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the synthesizer is about to speak a marker of an utterance’s text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechSynthesizer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willSpeak"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesisMarker",
          "text": "AVSpeechSynthesisMarker"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "utterance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:willSpeak:utterance:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speechSynthesizer:willSpeakMarker:utterance:"
        }
      ],
      "role": "symbol",
      "title": "speechSynthesizer(_:willSpeak:utterance:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizerdelegate/speechsynthesizer(_:willspeak:utterance:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:willSpeakRangeOfSpeechString:utterance:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the synthesizer is about to speak a portion of an utterance’s text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechSynthesizer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willSpeakRangeOfSpeechString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "utterance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:willSpeakRangeOfSpeechString:utterance:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speechSynthesizer:willSpeakRangeOfSpeechString:utterance:"
        }
      ],
      "role": "symbol",
      "title": "speechSynthesizer(_:willSpeakRangeOfSpeechString:utterance:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizerdelegate/speechsynthesizer(_:willspeakrangeofspeechstring:utterance:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance": {
      "abstract": [
        {
          "text": "An object that encapsulates the text for speech synthesis and parameters that affect the speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechUtterance"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechUtterance"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechUtterance",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechutterance"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance/postUtteranceDelay": {
      "abstract": [
        {
          "text": "The amount of time the speech synthesizer pauses after speaking an utterance before handling the next utterance in the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postUtteranceDelay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance/postUtteranceDelay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postUtteranceDelay"
        }
      ],
      "role": "symbol",
      "title": "postUtteranceDelay",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechutterance/postutterancedelay"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-speech-synthesis-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didStart:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:willSpeakRangeOfSpeechString:utterance:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:willSpeak:utterance:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didPause:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didContinue:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didCancel:)"
      ],
      "title": "Responding to speech synthesis events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "speechSynthesizer:didFinishSpeechUtterance:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "speechSynthesizer:didFinishSpeechUtterance:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-speech-synthesis-events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didStart:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:willSpeakRangeOfSpeechString:utterance:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:willSpeak:utterance:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didPause:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didContinue:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate/speechSynthesizer(_:didCancel:)"
              ],
              "title": "Responding to speech synthesis events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "speechSynthesizer:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
                    "text": "AVSpeechSynthesizer"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "synthesizer"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didFinishSpeechUtterance:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
                    "text": "AVSpeechUtterance"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "utterance"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The speech synthesizer that finishes speaking the utterance.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "synthesizer"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The utterance that the speech synthesizer finishes speaking.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "utterance"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:willSpeak:utterance:)/title",
          "value": "speechSynthesizer:willSpeakMarker:utterance:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:willSpeak:utterance:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "speechSynthesizer:willSpeakMarker:utterance:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:didPause:)/title",
          "value": "speechSynthesizer:didPauseSpeechUtterance:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:didPause:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "speechSynthesizer:didPauseSpeechUtterance:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance/title",
          "value": "AVSpeechUtterance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechUtterance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechUtterance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:didCancel:)/title",
          "value": "speechSynthesizer:didCancelSpeechUtterance:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:didCancel:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "speechSynthesizer:didCancelSpeechUtterance:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:didStart:)/title",
          "value": "speechSynthesizer:didStartSpeechUtterance:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:didStart:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "speechSynthesizer:didStartSpeechUtterance:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer/title",
          "value": "AVSpeechSynthesizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:didFinish:)/title",
          "value": "speechSynthesizer:didFinishSpeechUtterance:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:didFinish:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "speechSynthesizer:didFinishSpeechUtterance:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance~1postUtteranceDelay/title",
          "value": "postUtteranceDelay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance~1postUtteranceDelay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postUtteranceDelay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:willSpeakRangeOfSpeechString:utterance:)/title",
          "value": "speechSynthesizer:willSpeakRangeOfSpeechString:utterance:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:willSpeakRangeOfSpeechString:utterance:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "speechSynthesizer:willSpeakRangeOfSpeechString:utterance:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:didContinue:)/title",
          "value": "speechSynthesizer:didContinueSpeechUtterance:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate~1speechSynthesizer(_:didContinue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "speechSynthesizer:didContinueSpeechUtterance:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate/title",
          "value": "AVSpeechSynthesizerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesizerdelegate/speechsynthesizer(_:didfinish:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesizerdelegate/speechsynthesizer(_:didfinish:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
