{
  "abstract": [
    {
      "text": "A type that stores the texture formats, layout information, and other details you use to configure your rendering loop code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CompositorServices",
    "externalID": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE13ConfigurationV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Configuration"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Configuration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "LayerRenderer.Configuration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Configuration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type stores the configuration options for your app’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. When configuring your app’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type, use this type to specify information about the texture layouts, pixel formats, and rendering options you want. The system uses the provided information to initialize the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. It also uses the information to create the Metal textures and other data structures that you use for each frame of content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t create this type directly. When implementing the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration/makeConfiguration(capabilities:configuration:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type, the system passes a set of default configuration values for you to modify.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer": {
      "abstract": [
        {
          "text": "A type that you use with an immersive space to display fully immersive content using Metal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompositorLayer"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompositorLayer"
        }
      ],
      "role": "symbol",
      "title": "CompositorLayer",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorlayer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration": {
      "abstract": [
        {
          "text": "An interface for specifying the texture configurations and rendering behaviors to use with your Metal rendering engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompositorLayerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompositorLayerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CompositorLayerConfiguration",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorlayerconfiguration"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration/makeConfiguration(capabilities:configuration:)": {
      "abstract": [
        {
          "text": "Creates and returns a type that contains the rendering options for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Compositor Services to use when configuring a layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "capabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE12CapabilitiesV",
          "text": "Capabilities"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE13ConfigurationV",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration/makeConfiguration(capabilities:configuration:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "makeConfiguration(capabilities:configuration:)",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorlayerconfiguration/makeconfiguration(capabilities:configuration:)"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer": {
      "abstract": [
        {
          "text": "A type that provides the Metal types and timing information you need to draw your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities": {
      "abstract": [
        {
          "text": "The color formats, depth formats, and features that you can use to configure your rendering engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Capabilities"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Capabilities"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Capabilities",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/capabilities"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct": {
      "abstract": [
        {
          "text": "A type that stores the texture formats, layout information, and other details you use to configure your rendering loop code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Configuration",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.struct"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/colorFormat": {
      "abstract": [
        {
          "text": "The pixel format to use for color textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/colorFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "colorFormat",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.struct/colorformat"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/colorUsage": {
      "abstract": [
        {
          "text": "The texture usage value to apply to the layer’s color textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/colorUsage",
      "kind": "symbol",
      "role": "symbol",
      "title": "colorUsage",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.struct/colorusage"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/defaultDepthRange": {
      "abstract": [
        {
          "text": "The distances to the far and near clipping planes that define the bounds of your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultDepthRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/defaultDepthRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultDepthRange",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.struct/defaultdepthrange"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/depthFormat": {
      "abstract": [
        {
          "text": "The pixel format to use for the layer’s depth textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/depthFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "depthFormat",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.struct/depthformat"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/depthUsage": {
      "abstract": [
        {
          "text": "The texture usage value to apply to the layer’s depth textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/depthUsage",
      "kind": "symbol",
      "role": "symbol",
      "title": "depthUsage",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.struct/depthusage"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/generateFlippedRasterizationRateMaps": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the layer renderer provides rasterization rate maps flipped around the y-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generateFlippedRasterizationRateMaps"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/generateFlippedRasterizationRateMaps",
      "kind": "symbol",
      "role": "symbol",
      "title": "generateFlippedRasterizationRateMaps",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.struct/generateflippedrasterizationratemaps"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/isFoveationEnabled": {
      "abstract": [
        {
          "text": "A value that indicates if the layer is using variable rasterization rates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFoveationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/isFoveationEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isFoveationEnabled",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.struct/isfoveationenabled"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/layout": {
      "abstract": [
        {
          "text": "The layout being used by the layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@cp_layer_renderer_layout",
          "text": "Layout"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/layout",
      "kind": "symbol",
      "role": "symbol",
      "title": "layout",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.struct/layout"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Layout": {
      "abstract": [
        {
          "text": "Constants that specify the organization of the textures you use for drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Layout"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Layout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Layout"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Layout",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/layout"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/configuration-swift.property": {
      "abstract": [
        {
          "text": "The configuration details for the specified layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/configuration-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/configuration-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-layer-renderer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/configuration-swift.property",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities"
      ],
      "title": "Configuring the layer renderer"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-color-textures",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/colorFormat",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/colorUsage"
      ],
      "title": "Configuring the color textures"
    },
    {
      "anchor": "Configuring-the-depth-information",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/depthFormat",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/depthUsage",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/defaultDepthRange"
      ],
      "title": "Configuring the depth information"
    },
    {
      "anchor": "Configuring-the-texture-layout",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/layout",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Layout"
      ],
      "title": "Configuring the texture layout"
    },
    {
      "anchor": "Configuring-the-foveation-setting",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/isFoveationEnabled",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Configuration-swift.struct/generateFlippedRasterizationRateMaps"
      ],
      "title": "Configuring the foveation setting"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/title",
          "value": "CP_OBJECT_cp_layer_renderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Layout/title",
          "value": "cp_layer_renderer_layout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Layout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_layout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Layout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_layer_renderer_layout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/layerrenderer/configuration-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
