{
  "abstract": [
    {
      "text": "An exponential attenuation curve.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Exponential"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AU3DMixerAttenuationCurve@k3DMixerAttenuationCurve_Exponential",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "k3DMixerAttenuationCurve_Exponential"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "k3DMixerAttenuationCurve_Exponential"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AU3DMixerAttenuationCurve.k3DMixerAttenuationCurve_Exponential"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "k3DMixerAttenuationCurve_Exponential"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AU3DMixerAttenuationCurve"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Exponential": {
      "abstract": [
        {
          "text": "An exponential attenuation curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerAttenuationCurve_Exponential"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Exponential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerAttenuationCurve_Exponential"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve.k3DMixerAttenuationCurve_Exponential",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve/k3dmixerattenuationcurve_exponential"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Inverse": {
      "abstract": [
        {
          "text": "An inverse attenuation curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerAttenuationCurve_Inverse"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Inverse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerAttenuationCurve_Inverse"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve.k3DMixerAttenuationCurve_Inverse",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve/k3dmixerattenuationcurve_inverse"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Linear": {
      "abstract": [
        {
          "text": "A linear attenuation curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerAttenuationCurve_Linear"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerAttenuationCurve_Linear"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve.k3DMixerAttenuationCurve_Linear",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve/k3dmixerattenuationcurve_linear"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Power": {
      "abstract": [
        {
          "text": "An equal-power-based attenuation curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerAttenuationCurve_Power"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Power",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerAttenuationCurve_Power"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerAttenuationCurve.k3DMixerAttenuationCurve_Power",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerattenuationcurve/k3dmixerattenuationcurve_power"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Inverse",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Linear",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Power"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "k3DMixerAttenuationCurve_Exponential"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerAttenuationCurve_Exponential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Inverse",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Linear",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerAttenuationCurve/k3DMixerAttenuationCurve_Power"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "k3DMixerAttenuationCurve_Exponential"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve~1k3DMixerAttenuationCurve_Inverse/title",
          "value": "k3DMixerAttenuationCurve_Inverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve~1k3DMixerAttenuationCurve_Inverse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerAttenuationCurve_Inverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/title",
          "value": "AU3DMixerAttenuationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerAttenuationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve~1k3DMixerAttenuationCurve_Linear/title",
          "value": "k3DMixerAttenuationCurve_Linear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve~1k3DMixerAttenuationCurve_Linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerAttenuationCurve_Linear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve~1k3DMixerAttenuationCurve_Exponential/title",
          "value": "k3DMixerAttenuationCurve_Exponential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve~1k3DMixerAttenuationCurve_Exponential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerAttenuationCurve_Exponential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve~1k3DMixerAttenuationCurve_Power/title",
          "value": "k3DMixerAttenuationCurve_Power"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerAttenuationCurve~1k3DMixerAttenuationCurve_Power/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerAttenuationCurve_Power"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/au3dmixerattenuationcurve/k3dmixerattenuationcurve_exponential"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/au3dmixerattenuationcurve/k3dmixerattenuationcurve_exponential"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
