{
  "abstract": [
    {
      "text": "The error code that the parent class issues.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AdServices/documentation/AdServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC22AAAttributionErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AAAttributionError"
      }
    ],
    "modules": [
      {
        "name": "AdServices"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AAAttributionError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.1",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AAAttributionError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AAAttributionError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.AdServices/documentation/AdServices": {
      "abstract": [
        {
          "text": "Attribute app-download campaigns that originate from the App Store, Apple News, or",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Stocks on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices",
      "kind": "symbol",
      "role": "collection",
      "title": "AdServices",
      "type": "topic",
      "url": "/documentation/adservices"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError": {
      "abstract": [
        {
          "text": "The error code that the parent class issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAAttributionError"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionError"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code": {
      "abstract": [
        {
          "text": "The error code that the parent class issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError.Code",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/code"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/errorDomain": {
      "abstract": [
        {
          "text": "The error domain the framework uses when returning errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/errordomain"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/internalError": {
      "abstract": [
        {
          "text": "The server is unable to provide a token because of an internal error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22AAAttributionErrorCodeLeV",
          "text": "AAAttributionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AAAttributionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/internalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalError",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/internalerror"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/networkError": {
      "abstract": [
        {
          "text": "The server is unable to provide a token because the internet isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22AAAttributionErrorCodeLeV",
          "text": "AAAttributionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AAAttributionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/networkError",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkError",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/networkerror"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/platformNotSupported": {
      "abstract": [
        {
          "text": "The server is unable to provide a token because of an unsupported operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "platformNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22AAAttributionErrorCodeLeV",
          "text": "AAAttributionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AAAttributionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/platformNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "platformNotSupported",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/platformnotsupported"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionErrorDomain": {
      "abstract": [
        {
          "text": "The framework attribution error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAAttributionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionErrorDomain",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionErrorDomain",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-domain",
      "identifiers": [
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/errorDomain"
      ],
      "title": "Error domain"
    },
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/internalError",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/networkError",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/platformNotSupported",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code/title",
          "value": "AAAttributionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionErrorDomain/title",
          "value": "AAAttributionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/adservices/aaattributionerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
