{
  "abstract": [
    {
      "text": "A log of Ad Services framework updates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AdServices/documentation/AdServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.AdServices/documentation/AdServices/Changelog"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AdServices"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Changelog"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Release date",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Release details",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "November, 2024",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The payload returns a new ",
                      "type": "text"
                    },
                    {
                      "code": "claimType",
                      "type": "codeVoice"
                    },
                    {
                      "text": " attribute with a value of ",
                      "type": "text"
                    },
                    {
                      "code": "Click",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", specifying that the app download was from a tap on an ad. Note that the tap-through attribution window is 30 days.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "May, 2024",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "To reduce the rate of delayed attribution responses resulting in 404 errors, The Ad Services API will hold connections for up to 1 second before responding with a 404 error code. Doing this allows more time for the request to be processed and correct data delivered as a part of the response, increasing the number of successful API requests. The impact on the API caller could result in an increased number of client-side connection timeouts in cases if timeout is configured for less than 1 second.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "March, 2023",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Updated ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.AdServices/documentation/AdServices",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " workflow and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttribution/attributionToken()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "October, 2022",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Updated ",
                      "type": "text"
                    },
                    {
                      "code": "adId",
                      "type": "codeVoice"
                    },
                    {
                      "text": " in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttribution/attributionToken()#Attribution-payload-descriptions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "January, 2022",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Apple_Search_Ads/custom-product-pages",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " replaces Creative Sets functionality. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " Apple Search Ads no longer supports Creative Sets and ",
                      "type": "text"
                    },
                    {
                      "code": "AdGroupCreativeSets",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".  Creative Sets API calls return 200 OK responses with an invalid state. Your Creative Sets data remains available through ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/apple_search_ads/get_creative_set-level_reports",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and through the ",
                      "type": "text"
                    },
                    {
                      "code": "AdServices",
                      "type": "codeVoice"
                    },
                    {
                      "text": " attribution framework for devices running running iOS versions earlier than 15.2 where ",
                      "type": "text"
                    },
                    {
                      "code": "creativeSetId",
                      "type": "codeVoice"
                    },
                    {
                      "text": " returns in payloads. For devices running iOS version 15.2 and later, ",
                      "type": "text"
                    },
                    {
                      "code": "adId",
                      "type": "codeVoice"
                    },
                    {
                      "text": " returns in campaigns using a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/apple_search_ads/SupplySource",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " of ",
                      "type": "text"
                    },
                    {
                      "code": "APPSTORE_TODAY_TAB",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "APPSTORE_SEARCH_RESULTS.",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.AdServices/documentation/AdServices": {
      "abstract": [
        {
          "text": "Attribute app-download campaigns that originate from the App Store, Apple News, or",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Stocks on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices",
      "kind": "symbol",
      "role": "collection",
      "title": "AdServices",
      "type": "topic",
      "url": "/documentation/adservices"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttribution/attributionToken()": {
      "abstract": [
        {
          "text": "Generates a token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributionToken"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttribution/attributionToken()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributionTokenWithError:"
        }
      ],
      "role": "symbol",
      "title": "attributionToken()",
      "type": "topic",
      "url": "/documentation/adservices/aaattribution/attributiontoken()"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttribution/attributionToken()#Attribution-payload-descriptions": {
      "abstract": [],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttribution/attributionToken()#Attribution-payload-descriptions",
      "kind": "section",
      "title": "Attribution payload descriptions",
      "type": "topic",
      "url": "/documentation/adservices/aaattribution/attributiontoken()#Attribution-payload-descriptions"
    },
    "doc://com.apple.documentation/documentation/Apple_Search_Ads/custom-product-pages": {
      "abstract": [
        {
          "text": "View Custom Product Page details.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Apple_Search_Ads/custom-product-pages",
      "kind": "article",
      "role": "article",
      "title": "Custom Product Pages",
      "type": "topic",
      "url": "/documentation/Apple_Search_Ads/custom-product-pages"
    },
    "doc://com.apple.documentation/documentation/apple_search_ads/SupplySource": {
      "abstract": [
        {
          "text": "The ad placements for a campaign.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "string "
        },
        {
          "kind": "identifier",
          "text": "SupplySource"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple_search_ads/SupplySource",
      "kind": "symbol",
      "role": "symbol",
      "title": "SupplySource",
      "type": "topic",
      "url": "/documentation/apple_search_ads/SupplySource"
    },
    "doc://com.apple.documentation/documentation/apple_search_ads/get_creative_set-level_reports": {
      "abstract": [
        {
          "text": "Fetches reports for Creative Sets within a campaign.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/apple_search_ads/get_creative_set-level_reports",
      "kind": "article",
      "role": "symbol",
      "title": "Get Creative Set-Level Reports",
      "type": "topic",
      "url": "/documentation/apple_search_ads/get_creative_set-level_reports"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e5f51b2395970bdf7acf42b6603b53c9/spacer.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttribution~1attributionToken()/title",
          "value": "attributionTokenWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttribution~1attributionToken()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attributionTokenWithError:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/adservices/changelog"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/adservices/changelog"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
