{
  "abstract": [
    {
      "text": "The controller’s paddle 1 button element, which has a P1 label on the back of the controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GCXboxGamepad(py)paddleButton1",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "paddleButton1"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
        "text": "GCControllerButtonInput"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "paddleButton1"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "paddleButton1"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "paddleButton1"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
              "text": "GCControllerButtonInput"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput": {
      "abstract": [
        {
          "text": "A control element that represents a button touch or press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerButtonInput"
        }
      ],
      "role": "symbol",
      "title": "GCControllerButtonInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerbuttoninput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the Xbox controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCXboxGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCXboxGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCXboxGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcxboxgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/buttonShare": {
      "abstract": [
        {
          "text": "The share button on an Xbox Series X|S controller or later.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonShare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/buttonShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonShare"
        }
      ],
      "role": "symbol",
      "title": "buttonShare",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcxboxgamepad/buttonshare"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton1": {
      "abstract": [
        {
          "text": "The controller’s paddle 1 button element, which has a P1 label on the back of the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paddleButton1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paddleButton1"
        }
      ],
      "role": "symbol",
      "title": "paddleButton1",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcxboxgamepad/paddlebutton1"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton2": {
      "abstract": [
        {
          "text": "The paddle 2 button element, which has a P2 label on the back of the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paddleButton2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paddleButton2"
        }
      ],
      "role": "symbol",
      "title": "paddleButton2",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcxboxgamepad/paddlebutton2"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton3": {
      "abstract": [
        {
          "text": "The paddle 3 button element, which has a P3 label on the back of the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paddleButton3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paddleButton3"
        }
      ],
      "role": "symbol",
      "title": "paddleButton3",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcxboxgamepad/paddlebutton3"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton4": {
      "abstract": [
        {
          "text": "The paddle 4 button element, which has a P4 label on the back of the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paddleButton4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paddleButton4"
        }
      ],
      "role": "symbol",
      "title": "paddleButton4",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcxboxgamepad/paddlebutton4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-button-inputs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton2",
        "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton3",
        "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton4",
        "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/buttonShare"
      ],
      "title": "Getting button inputs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "paddleButton1"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paddleButton1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController",
                "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-button-inputs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton2",
                "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton3",
                "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/paddleButton4",
                "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad/buttonShare"
              ],
              "title": "Getting button inputs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
                    "text": "GCControllerButtonInput"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "paddleButton1"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/title",
          "value": "GCControllerButtonInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerButtonInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerButtonInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad~1paddleButton3/title",
          "value": "paddleButton3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad~1paddleButton3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paddleButton3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad~1buttonShare/title",
          "value": "buttonShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad~1buttonShare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad~1paddleButton1/title",
          "value": "paddleButton1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad~1paddleButton1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paddleButton1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad~1paddleButton4/title",
          "value": "paddleButton4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad~1paddleButton4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paddleButton4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad/title",
          "value": "GCXboxGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCXboxGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCXboxGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad~1paddleButton2/title",
          "value": "paddleButton2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad~1paddleButton2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paddleButton2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcxboxgamepad/paddlebutton1"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcxboxgamepad/paddlebutton1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
