{
  "abstract": [
    {
      "text": "Returns the integer value associated with the specified key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/intForKey:inTable:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPrinter(im)intForKey:inTable:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "intForKey:inTable:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "intForKey:inTable:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.9",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "intForKey:inTable:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "intForKey:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inTable:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "table"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The key whose value you want.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "key"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of a table from the printer’s PPD file.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "table"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The integer value. Returns ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " if the key is not in the table or the receiver lacks a PPD file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter": {
      "abstract": [
        {
          "text": "An object that describes a printer’s capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrinter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrinter"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus": {
      "abstract": [
        {
          "text": "Constants that describe the state of a printer information table stored by a printer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TableStatus"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TableStatus"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter.TableStatus",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/tablestatus"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/acceptsBinary": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "acceptsBinary"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/acceptsBinary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptsBinary"
        }
      ],
      "role": "symbol",
      "title": "acceptsBinary",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/acceptsbinary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/booleanForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the Boolean value associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "booleanForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/booleanForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "booleanForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "booleanForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/booleanforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/domain": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "domain"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/domain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "domain"
        }
      ],
      "role": "symbol",
      "title": "domain",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/domain"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/floatForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the floating-point value associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "floatForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/floatForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "floatForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "floatForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/floatforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/host": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "host"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/host",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "host"
        }
      ],
      "role": "symbol",
      "title": "host",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/host"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/imageRectForPaper:": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "imageRectForPaper:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/imageRectForPaper:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageRectForPaper:"
        }
      ],
      "role": "symbol",
      "title": "imageRectForPaper:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/imagerectforpaper:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/intForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the integer value associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "intForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/intForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "intForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/intforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isColor": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isColor"
        }
      ],
      "role": "symbol",
      "title": "isColor",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/iscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isKey:inTable:": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the specified key is in the specified table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "isKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/iskey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerWithName:domain:includeUnavailable:": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "printerWithName:domain:includeUnavailable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerWithName:domain:includeUnavailable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerWithName:domain:includeUnavailable:"
        }
      ],
      "role": "symbol",
      "title": "printerWithName:domain:includeUnavailable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/printerwithname:domain:includeunavailable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/rectForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the rectangle associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "rectForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/rectForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "rectForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/rectforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/sizeForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the size data type associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "sizeForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/sizeForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sizeForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "sizeForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/sizeforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/statusForTable:": {
      "abstract": [
        {
          "text": "Returns the status of the specified table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "statusForTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/statusForTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusForTable:"
        }
      ],
      "role": "symbol",
      "title": "statusForTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/statusfortable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the first occurrence of a value associated with specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "stringForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "stringForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/stringforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringListForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns an array of strings, one for each occurrence, associated with specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "stringListForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringListForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringListForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "stringListForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/stringlistforkey:intable:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isKey:inTable:",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringForKey:inTable:",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringListForKey:inTable:",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/booleanForKey:inTable:",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/floatForKey:inTable:",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/rectForKey:inTable:",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/sizeForKey:inTable:",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/statusForTable:",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerWithName:domain:includeUnavailable:",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/acceptsBinary",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/domain",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/host",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/imageRectForPaper:",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isColor"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter/title",
          "value": "NSPrinter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus/title",
          "value": "NSPrinterTableStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprinter/intforkey:intable:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
