{
  "abstract": [
    {
      "text": "Constants that describe the state of a printer information table stored by a printer object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSPrinterTableStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TableStatus"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TableStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSPrinter.TableStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TableStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants are used by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/statusForTable:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter": {
      "abstract": [
        {
          "text": "An object that describes a printer’s capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrinter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrinter"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus": {
      "abstract": [
        {
          "text": "Constants that describe the state of a printer information table stored by a printer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TableStatus"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TableStatus"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter.TableStatus",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/tablestatus"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/error": {
      "abstract": [
        {
          "text": "Printer table is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrinterTableError"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter.TableStatus.error",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/tablestatus/error"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/tablestatus/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/notFound": {
      "abstract": [
        {
          "text": "Printer table was not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFound"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/notFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrinterTableNotFound"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter.TableStatus.notFound",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/tablestatus/notfound"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/ok": {
      "abstract": [
        {
          "text": "Printer table was found and is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ok"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/ok",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrinterTableOK"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter.TableStatus.ok",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/tablestatus/ok"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/acceptsBinary": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "acceptsBinary"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/acceptsBinary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptsBinary"
        }
      ],
      "role": "symbol",
      "title": "acceptsBinary",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/acceptsbinary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/booleanForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the Boolean value associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "booleanForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/booleanForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "booleanForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "booleanForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/booleanforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/domain": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "domain"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/domain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "domain"
        }
      ],
      "role": "symbol",
      "title": "domain",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/domain"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/floatForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the floating-point value associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "floatForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/floatForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "floatForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "floatForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/floatforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/host": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "host"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/host",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "host"
        }
      ],
      "role": "symbol",
      "title": "host",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/host"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/imageRectForPaper:": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "imageRectForPaper:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/imageRectForPaper:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageRectForPaper:"
        }
      ],
      "role": "symbol",
      "title": "imageRectForPaper:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/imagerectforpaper:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/intForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the integer value associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "intForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/intForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "intForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/intforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isColor": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isColor"
        }
      ],
      "role": "symbol",
      "title": "isColor",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/iscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isKey:inTable:": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the specified key is in the specified table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "isKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/iskey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerWithName:domain:includeUnavailable:": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "printerWithName:domain:includeUnavailable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerWithName:domain:includeUnavailable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerWithName:domain:includeUnavailable:"
        }
      ],
      "role": "symbol",
      "title": "printerWithName:domain:includeUnavailable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/printerwithname:domain:includeunavailable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/rectForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the rectangle associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "rectForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/rectForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "rectForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/rectforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/sizeForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the size data type associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "sizeForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/sizeForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sizeForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "sizeForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/sizeforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/statusForTable:": {
      "abstract": [
        {
          "text": "Returns the status of the specified table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "statusForTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/statusForTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusForTable:"
        }
      ],
      "role": "symbol",
      "title": "statusForTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/statusfortable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the first occurrence of a value associated with specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "stringForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "stringForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/stringforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringListForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns an array of strings, one for each occurrence, associated with specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "stringListForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringListForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringListForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "stringListForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/stringlistforkey:intable:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/ok",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/notFound",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/error"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrinterTableStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/ok",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/notFound",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus/error"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringListForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/booleanForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/floatForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/intForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/rectForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/sizeForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/statusForTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerWithName:domain:includeUnavailable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/acceptsBinary",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/domain",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/host",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/imageRectForPaper:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isColor"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPrinterTableStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus~1notFound/title",
          "value": "NSPrinterTableNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus~1notFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter/title",
          "value": "NSPrinter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus~1ok/title",
          "value": "NSPrinterTableOK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus~1ok/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableOK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus/title",
          "value": "NSPrinterTableStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus~1error/title",
          "value": "NSPrinterTableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprinter/tablestatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsprinter/tablestatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
