{
  "abstract": [
    {
      "text": "A local asset shouldn’t follow references to remote media.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidLocalReferenceToRemote"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAssetReferenceRestrictions@AVAssetReferenceRestrictionForbidLocalReferenceToRemote",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "forbidLocalReferenceToRemote"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVAssetReferenceRestrictions",
        "text": "AVAssetReferenceRestrictions"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAssetReferenceRestrictionForbidLocalReferenceToRemote"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "forbidLocalReferenceToRemote"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "forbidLocalReferenceToRemote"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVAssetReferenceRestrictions",
              "text": "AVAssetReferenceRestrictions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions": {
      "abstract": [
        {
          "text": "Restrictions to use when resolving references to external media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictions"
        }
      ],
      "role": "symbol",
      "title": "AVAssetReferenceRestrictions",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreferencerestrictions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/AVAssetReferenceRestrictionForbidNone": {
      "abstract": [
        {
          "text": "The asset should follow all media references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictionForbidNone"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/AVAssetReferenceRestrictionForbidNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetReferenceRestrictionForbidNone",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreferencerestrictions/avassetreferencerestrictionforbidnone"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/defaultPolicy": {
      "abstract": [
        {
          "text": "The asset should use the default reference restrictions policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAssetReferenceRestrictions",
          "text": "AVAssetReferenceRestrictions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/defaultPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictionDefaultPolicy"
        }
      ],
      "role": "symbol",
      "title": "defaultPolicy",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreferencerestrictions/defaultpolicy"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidAll": {
      "abstract": [
        {
          "text": "The asset can only reference media stored within its container file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forbidAll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAssetReferenceRestrictions",
          "text": "AVAssetReferenceRestrictions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictionForbidAll"
        }
      ],
      "role": "symbol",
      "title": "forbidAll",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreferencerestrictions/forbidall"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidCrossSiteReference": {
      "abstract": [
        {
          "text": "A remote asset shouldn’t follow references to remote media data stored at a different host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forbidCrossSiteReference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAssetReferenceRestrictions",
          "text": "AVAssetReferenceRestrictions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidCrossSiteReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictionForbidCrossSiteReference"
        }
      ],
      "role": "symbol",
      "title": "forbidCrossSiteReference",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreferencerestrictions/forbidcrosssitereference"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidLocalReferenceToLocal": {
      "abstract": [
        {
          "text": "A local asset shouldn’t follow references to local media data stored outside its container file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forbidLocalReferenceToLocal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAssetReferenceRestrictions",
          "text": "AVAssetReferenceRestrictions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidLocalReferenceToLocal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictionForbidLocalReferenceToLocal"
        }
      ],
      "role": "symbol",
      "title": "forbidLocalReferenceToLocal",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreferencerestrictions/forbidlocalreferencetolocal"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidLocalReferenceToRemote": {
      "abstract": [
        {
          "text": "A local asset shouldn’t follow references to remote media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forbidLocalReferenceToRemote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAssetReferenceRestrictions",
          "text": "AVAssetReferenceRestrictions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidLocalReferenceToRemote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictionForbidLocalReferenceToRemote"
        }
      ],
      "role": "symbol",
      "title": "forbidLocalReferenceToRemote",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreferencerestrictions/forbidlocalreferencetoremote"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidRemoteReferenceToLocal": {
      "abstract": [
        {
          "text": "A remote asset shouldn’t follow references to local media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forbidRemoteReferenceToLocal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAssetReferenceRestrictions",
          "text": "AVAssetReferenceRestrictions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidRemoteReferenceToLocal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictionForbidRemoteReferenceToLocal"
        }
      ],
      "role": "symbol",
      "title": "forbidRemoteReferenceToLocal",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreferencerestrictions/forbidremotereferencetolocal"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference-Restrictions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidAll",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidRemoteReferenceToLocal",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidCrossSiteReference",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidLocalReferenceToLocal",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/defaultPolicy"
      ],
      "title": "Reference Restrictions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAssetReferenceRestrictionForbidLocalReferenceToRemote"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictionForbidLocalReferenceToRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference-Restrictions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/AVAssetReferenceRestrictionForbidNone",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidAll",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidRemoteReferenceToLocal",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidCrossSiteReference",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/forbidLocalReferenceToLocal",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions/defaultPolicy"
              ],
              "title": "Reference Restrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAssetReferenceRestrictionForbidLocalReferenceToRemote"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions/title",
          "value": "AVAssetReferenceRestrictions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1forbidLocalReferenceToRemote/title",
          "value": "AVAssetReferenceRestrictionForbidLocalReferenceToRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1forbidLocalReferenceToRemote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictionForbidLocalReferenceToRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1forbidRemoteReferenceToLocal/title",
          "value": "AVAssetReferenceRestrictionForbidRemoteReferenceToLocal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1forbidRemoteReferenceToLocal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictionForbidRemoteReferenceToLocal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1defaultPolicy/title",
          "value": "AVAssetReferenceRestrictionDefaultPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1defaultPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictionDefaultPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1forbidAll/title",
          "value": "AVAssetReferenceRestrictionForbidAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1forbidAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictionForbidAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1forbidCrossSiteReference/title",
          "value": "AVAssetReferenceRestrictionForbidCrossSiteReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1forbidCrossSiteReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictionForbidCrossSiteReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1forbidLocalReferenceToLocal/title",
          "value": "AVAssetReferenceRestrictionForbidLocalReferenceToLocal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions~1forbidLocalReferenceToLocal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictionForbidLocalReferenceToLocal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avassetreferencerestrictions/forbidlocalreferencetoremote"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avassetreferencerestrictions/forbidlocalreferencetoremote"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
