{
  "abstract": [
    {
      "text": "Constants that represent the status of a participant.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CloudKit",
    "externalID": "c:@E@CKShareParticipantAcceptanceStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ParticipantAcceptanceStatus"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ParticipantAcceptanceStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CKShare.ParticipantAcceptanceStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ParticipantAcceptanceStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare": {
      "abstract": [
        {
          "text": "A specialized record type that manages a collection of shared records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "role": "symbol",
      "title": "CKShare",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/Participant/AcceptanceStatus-swift.typealias": {
      "abstract": [
        {
          "text": "A type that represents the acceptance status of the participant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AcceptanceStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/Participant/AcceptanceStatus-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AcceptanceStatus"
        }
      ],
      "role": "symbol",
      "title": "CKShare.Participant.AcceptanceStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare/participant/acceptancestatus-swift.typealias"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/Participant/acceptanceStatus-swift.property": {
      "abstract": [
        {
          "text": "The current state of the user’s acceptance of the share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceptanceStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKShare",
          "text": "CKShare"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKShareParticipantAcceptanceStatus",
          "text": "ParticipantAcceptanceStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/Participant/acceptanceStatus-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptanceStatus"
        }
      ],
      "role": "symbol",
      "title": "acceptanceStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare/participant/acceptancestatus-swift.property"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus": {
      "abstract": [
        {
          "text": "Constants that represent the status of a participant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ParticipantAcceptanceStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ParticipantAcceptanceStatus"
        }
      ],
      "role": "symbol",
      "title": "CKShare.ParticipantAcceptanceStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare/participantacceptancestatus"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/accepted": {
      "abstract": [
        {
          "text": "The participant accepted the share request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accepted"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/accepted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShareParticipantAcceptanceStatusAccepted"
        }
      ],
      "role": "symbol",
      "title": "CKShare.ParticipantAcceptanceStatus.accepted",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare/participantacceptancestatus/accepted"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare/participantacceptancestatus/init(rawvalue:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/pending": {
      "abstract": [
        {
          "text": "The participant’s acceptance of the share request is pending.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pending"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/pending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShareParticipantAcceptanceStatusPending"
        }
      ],
      "role": "symbol",
      "title": "CKShare.ParticipantAcceptanceStatus.pending",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare/participantacceptancestatus/pending"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/removed": {
      "abstract": [
        {
          "text": "The system removed the participant from the share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removed"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/removed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShareParticipantAcceptanceStatusRemoved"
        }
      ],
      "role": "symbol",
      "title": "CKShare.ParticipantAcceptanceStatus.removed",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare/participantacceptancestatus/removed"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/unknown": {
      "abstract": [
        {
          "text": "The participant’s status is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShareParticipantAcceptanceStatusUnknown"
        }
      ],
      "role": "symbol",
      "title": "CKShare.ParticipantAcceptanceStatus.unknown",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare/participantacceptancestatus/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Participants-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/Participant/acceptanceStatus-swift.property",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/Participant/AcceptanceStatus-swift.typealias"
      ],
      "title": "Accessing the Participant’s Status"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/unknown",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/pending",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/accepted",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/removed"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKShareParticipantAcceptanceStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShareParticipantAcceptanceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShareParticipantAcceptanceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/unknown",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/pending",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/accepted",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/ParticipantAcceptanceStatus/removed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-Participants-Status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKShare/Participant/acceptanceStatus-swift.property"
              ],
              "title": "Accessing the Participant’s Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKShareParticipantAcceptanceStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus~1removed/title",
          "value": "CKShareParticipantAcceptanceStatusRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus~1removed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShareParticipantAcceptanceStatusRemoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus/title",
          "value": "CKShareParticipantAcceptanceStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShareParticipantAcceptanceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShareParticipantAcceptanceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/title",
          "value": "CKShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus~1pending/title",
          "value": "CKShareParticipantAcceptanceStatusPending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus~1pending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShareParticipantAcceptanceStatusPending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus~1unknown/title",
          "value": "CKShareParticipantAcceptanceStatusUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShareParticipantAcceptanceStatusUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1Participant~1acceptanceStatus-swift.property/title",
          "value": "acceptanceStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1Participant~1acceptanceStatus-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceptanceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus~1accepted/title",
          "value": "CKShareParticipantAcceptanceStatusAccepted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare~1ParticipantAcceptanceStatus~1accepted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShareParticipantAcceptanceStatusAccepted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckshare/participantacceptancestatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckshare/participantacceptancestatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
