{
  "abstract": [
    {
      "text": "Values that describe the kinds of features visible on the map.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MapKit",
    "externalID": "c:@E@MKMapFeatureType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FeatureType"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FeatureType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MKMapFeatureAnnotation.FeatureType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FeatureType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation": {
      "abstract": [
        {
          "text": "A class that describes an annotation element on the map’s display such as a point of interest, territorial boundary, or physical feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapFeatureAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapFeatureAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum": {
      "abstract": [
        {
          "text": "Values that describe the kinds of features visible on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FeatureType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FeatureType"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation.FeatureType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/physicalFeature": {
      "abstract": [
        {
          "text": "A physical feature on the Earth such as a mountain range, river, or ocean basin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicalFeature"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/physicalFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapFeatureTypePhysicalFeature"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation.FeatureType.physicalFeature",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.enum/physicalfeature"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/pointOfInterest": {
      "abstract": [
        {
          "text": "A point of interest, such as a museum, cafe, park, or school.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointOfInterest"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/pointOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapFeatureTypePointOfInterest"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation.FeatureType.pointOfInterest",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.enum/pointofinterest"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/territory": {
      "abstract": [
        {
          "text": "A territorial or regional boundary, such as a national border, a state boundary, or a neighborhood.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "territory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/territory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapFeatureTypeTerritory"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation.FeatureType.territory",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.enum/territory"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property": {
      "abstract": [
        {
          "text": "The type of map feature this annotation represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapFeatureAnnotation",
          "text": "MKMapFeatureAnnotation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapFeatureType",
          "text": "FeatureType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "featureType"
        }
      ],
      "role": "symbol",
      "title": "featureType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.property"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle": {
      "abstract": [
        {
          "text": "The icon style of a feature annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKIconStyle",
          "text": "MKIconStyle"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconStyle"
        }
      ],
      "role": "symbol",
      "title": "iconStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/iconstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory": {
      "abstract": [
        {
          "text": "The feature annotation’s point of interest category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointOfInterestCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointOfInterestCategory"
        }
      ],
      "role": "symbol",
      "title": "pointOfInterestCategory",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/pointofinterestcategory"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-annotation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory"
      ],
      "title": "Customizing the annotation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Kinds-of-annotations",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/physicalFeature",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/pointOfInterest",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/territory",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/physicalFeature",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/pointOfInterest",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/territory"
      ],
      "title": "Kinds of annotations"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKMapFeatureType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Kinds-of-annotations",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/physicalFeature",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/pointOfInterest",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/territory",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/physicalFeature",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/pointOfInterest",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum/territory"
              ],
              "title": "Kinds of annotations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-annotation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory"
              ],
              "title": "Customizing the annotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKMapFeatureType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1iconStyle/title",
          "value": "iconStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1iconStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iconStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum/title",
          "value": "MKMapFeatureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1featureType-swift.property/title",
          "value": "featureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1featureType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "featureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum~1physicalFeature/title",
          "value": "MKMapFeatureTypePhysicalFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum~1physicalFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureTypePhysicalFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/title",
          "value": "MKMapFeatureAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1pointOfInterestCategory/title",
          "value": "pointOfInterestCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1pointOfInterestCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointOfInterestCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum~1pointOfInterest/title",
          "value": "MKMapFeatureTypePointOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum~1pointOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureTypePointOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum~1territory/title",
          "value": "MKMapFeatureTypeTerritory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum~1territory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureTypeTerritory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
