{
  "abstract": [
    {
      "text": "The type of map feature this annotation represents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKMapFeatureAnnotation(py)featureType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "featureType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKMapFeatureAnnotation",
        "text": "MKMapFeatureAnnotation"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MKMapFeatureType",
        "text": "FeatureType"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "featureType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "featureType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "featureType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKMapFeatureAnnotation",
              "text": "MKMapFeatureAnnotation"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MKMapFeatureType",
              "text": "FeatureType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation": {
      "abstract": [
        {
          "text": "A class that describes an annotation element on the map’s display such as a point of interest, territorial boundary, or physical feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapFeatureAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapFeatureAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum": {
      "abstract": [
        {
          "text": "Values that describe the kinds of features visible on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FeatureType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FeatureType"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation.FeatureType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property": {
      "abstract": [
        {
          "text": "The type of map feature this annotation represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapFeatureAnnotation",
          "text": "MKMapFeatureAnnotation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapFeatureType",
          "text": "FeatureType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "featureType"
        }
      ],
      "role": "symbol",
      "title": "featureType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.property"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle": {
      "abstract": [
        {
          "text": "The icon style of a feature annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKIconStyle",
          "text": "MKIconStyle"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconStyle"
        }
      ],
      "role": "symbol",
      "title": "iconStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/iconstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory": {
      "abstract": [
        {
          "text": "The feature annotation’s point of interest category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointOfInterestCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointOfInterestCategory"
        }
      ],
      "role": "symbol",
      "title": "pointOfInterestCategory",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/pointofinterestcategory"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-annotation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory"
      ],
      "title": "Customizing the annotation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "featureType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "featureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-annotation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory"
              ],
              "title": "Customizing the annotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MKMapFeatureType",
                    "text": "MKMapFeatureType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "featureType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1iconStyle/title",
          "value": "iconStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1iconStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iconStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum/title",
          "value": "MKMapFeatureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1featureType-swift.property/title",
          "value": "featureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1featureType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "featureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/title",
          "value": "MKMapFeatureAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1pointOfInterestCategory/title",
          "value": "pointOfInterestCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1pointOfInterestCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointOfInterestCategory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
