{
  "abstract": [
    {
      "text": "An invalid argument error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/invalidArgument"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC17WatchKitErrorCodeLeV15invalidArgumentSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidArgument"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
        "text": "WatchKitError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@WatchKitErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "invalidArgument"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidArgument"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
              "text": "WatchKitError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@WatchKitErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "WatchKit reports this error when you specify invalid settings for one of the system supplied interfaces.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError": {
      "abstract": [
        {
          "text": "An error reported by WatchKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WatchKitError"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitError"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code": {
      "abstract": [
        {
          "text": "Error codes reported by WatchKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError.Code",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/code"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/applicationDelegateWatchKitRequestReplyNotCalled": {
      "abstract": [
        {
          "text": "An unresponsive delegate error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDelegateWatchKitRequestReplyNotCalled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/applicationDelegateWatchKitRequestReplyNotCalled",
      "kind": "symbol",
      "role": "symbol",
      "title": "applicationDelegateWatchKitRequestReplyNotCalled",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/applicationdelegatewatchkitrequestreplynotcalled"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/downloadFailed": {
      "abstract": [
        {
          "text": "A download error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/downloadFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "downloadFailed",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/downloadfailed"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/invalidArgument": {
      "abstract": [
        {
          "text": "An invalid argument error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/invalidArgument",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidArgument",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/invalidargument"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/mediaPlayerFailed": {
      "abstract": [
        {
          "text": "A media player error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPlayerFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/mediaPlayerFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaPlayerFailed",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/mediaplayerfailed"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/recordingFailed": {
      "abstract": [
        {
          "text": "An audio recording error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/recordingFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "recordingFailed",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/recordingfailed"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/unknown": {
      "abstract": [
        {
          "text": "An unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17WatchKitErrorCodeLeV",
          "text": "WatchKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WatchKitErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/downloadFailed",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/mediaPlayerFailed",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/recordingFailed",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/unknown",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/applicationDelegateWatchKitRequestReplyNotCalled"
      ],
      "title": "Accessing Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/title",
          "value": "WatchKitErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/watchkiterror/invalidargument"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
