{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the accessibility option to invert colors is in an enabled state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldInvertColors"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSWorkspace(py)accessibilityDisplayShouldInvertColors",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessibilityDisplayShouldInvertColors"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accessibilityDisplayShouldInvertColors"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "accessibilityDisplayShouldInvertColors"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityDisplayShouldInvertColors"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If this property’s value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the system inverts the display. In this case, you may need to adjust your app’s drawing for optimal display.  To receive updates when this setting changes, register for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayOptionsDidChangeNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notification using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/notificationCenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace": {
      "abstract": [
        {
          "text": "A workspace that can launch other apps and perform a variety of file-handling services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspace",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayOptionsDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when any of the accessibility display options change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityDisplayOptionsDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayOptionsDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceAccessibilityDisplayOptionsDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "accessibilityDisplayOptionsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/accessibilitydisplayoptionsdidchangenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldDifferentiateWithoutColor": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app avoids conveying information through color alone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityDisplayShouldDifferentiateWithoutColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldDifferentiateWithoutColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityDisplayShouldDifferentiateWithoutColor"
        }
      ],
      "role": "symbol",
      "title": "accessibilityDisplayShouldDifferentiateWithoutColor",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/accessibilitydisplayshoulddifferentiatewithoutcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldIncreaseContrast": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app presents a high-contrast user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityDisplayShouldIncreaseContrast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldIncreaseContrast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityDisplayShouldIncreaseContrast"
        }
      ],
      "role": "symbol",
      "title": "accessibilityDisplayShouldIncreaseContrast",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/accessibilitydisplayshouldincreasecontrast"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldInvertColors": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the accessibility option to invert colors is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityDisplayShouldInvertColors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldInvertColors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityDisplayShouldInvertColors"
        }
      ],
      "role": "symbol",
      "title": "accessibilityDisplayShouldInvertColors",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/accessibilitydisplayshouldinvertcolors"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldReduceMotion": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the accessibility option to reduce motion is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityDisplayShouldReduceMotion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldReduceMotion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityDisplayShouldReduceMotion"
        }
      ],
      "role": "symbol",
      "title": "accessibilityDisplayShouldReduceMotion",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/accessibilitydisplayshouldreducemotion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldReduceTransparency": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app avoids using semitransparent backgrounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityDisplayShouldReduceTransparency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldReduceTransparency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityDisplayShouldReduceTransparency"
        }
      ],
      "role": "symbol",
      "title": "accessibilityDisplayShouldReduceTransparency",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/accessibilitydisplayshouldreducetransparency"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/isSwitchControlEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Switch Control is currently running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSwitchControlEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/isSwitchControlEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "switchControlEnabled"
        }
      ],
      "role": "symbol",
      "title": "isSwitchControlEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/isswitchcontrolenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/isVoiceOverEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether VoiceOver is currently running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isVoiceOverEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/isVoiceOverEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "voiceOverEnabled"
        }
      ],
      "role": "symbol",
      "title": "isVoiceOverEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/isvoiceoverenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/notificationCenter": {
      "abstract": [
        {
          "text": "The notification center for workspace notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotificationCenter",
          "text": "NotificationCenter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/notificationCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationCenter"
        }
      ],
      "role": "symbol",
      "title": "notificationCenter",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/notificationcenter"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-Accessibility",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldDifferentiateWithoutColor",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldIncreaseContrast",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldReduceTransparency",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldReduceMotion",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/isSwitchControlEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/isVoiceOverEnabled"
      ],
      "title": "Supporting Accessibility"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "accessibilityDisplayShouldInvertColors"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessibilityDisplayShouldInvertColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-Accessibility",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldDifferentiateWithoutColor",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldIncreaseContrast",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldReduceTransparency",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/accessibilityDisplayShouldReduceMotion",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/isSwitchControlEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/isVoiceOverEnabled"
              ],
              "title": "Supporting Accessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessibilityDisplayShouldInvertColors"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1isVoiceOverEnabled/title",
          "value": "voiceOverEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1isVoiceOverEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "voiceOverEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayShouldInvertColors/title",
          "value": "accessibilityDisplayShouldInvertColors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayShouldInvertColors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessibilityDisplayShouldInvertColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayOptionsDidChangeNotification/title",
          "value": "NSWorkspaceAccessibilityDisplayOptionsDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayOptionsDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceAccessibilityDisplayOptionsDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/title",
          "value": "NSWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayShouldIncreaseContrast/title",
          "value": "accessibilityDisplayShouldIncreaseContrast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayShouldIncreaseContrast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessibilityDisplayShouldIncreaseContrast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1isSwitchControlEnabled/title",
          "value": "switchControlEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1isSwitchControlEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "switchControlEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayShouldDifferentiateWithoutColor/title",
          "value": "accessibilityDisplayShouldDifferentiateWithoutColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayShouldDifferentiateWithoutColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessibilityDisplayShouldDifferentiateWithoutColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1notificationCenter/title",
          "value": "notificationCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1notificationCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayShouldReduceTransparency/title",
          "value": "accessibilityDisplayShouldReduceTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayShouldReduceTransparency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessibilityDisplayShouldReduceTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayShouldReduceMotion/title",
          "value": "accessibilityDisplayShouldReduceMotion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1accessibilityDisplayShouldReduceMotion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessibilityDisplayShouldReduceMotion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsworkspace/accessibilitydisplayshouldinvertcolors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsworkspace/accessibilitydisplayshouldinvertcolors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
