{
  "abstract": [
    {
      "text": "The configuration options for opening URLs or launching apps.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSWorkspaceOpenConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OpenConfiguration"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OpenConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSWorkspace.OpenConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OpenConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object before launching an app or opening a URL using the shared ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Use the properties of this object to customize the behavior of the launched app or the handling of the URLs. For example, you might tell the app to hide itself immediately after launch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion": {
      "abstract": [
        {
          "text": "Constants for determining which version of AppKit is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersion"
        }
      ],
      "role": "symbol",
      "title": "NSAppKitVersion",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace": {
      "abstract": [
        {
          "text": "A workspace that can launch other apps and perform a variety of file-handling services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspace",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration": {
      "abstract": [
        {
          "text": "The configuration options for opening URLs or launching apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpenConfiguration"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OpenConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspace.OpenConfiguration",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/activates": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the system activates the app and brings it to the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/activates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activates"
        }
      ],
      "role": "symbol",
      "title": "activates",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/activates"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/addsToRecentItems": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to add the app or documents to the Recent Items menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addsToRecentItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/addsToRecentItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addsToRecentItems"
        }
      ],
      "role": "symbol",
      "title": "addsToRecentItems",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/addstorecentitems"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/allowsRunningApplicationSubstitution": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to use a running instance of an application even if it’s at a different URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsRunningApplicationSubstitution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/allowsRunningApplicationSubstitution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsRunningApplicationSubstitution"
        }
      ],
      "role": "symbol",
      "title": "allowsRunningApplicationSubstitution",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/allowsrunningapplicationsubstitution"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/appleEvent": {
      "abstract": [
        {
          "text": "The first Apple event to send to the new app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAppleEventDescriptor",
          "text": "NSAppleEventDescriptor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/appleEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleEvent"
        }
      ],
      "role": "symbol",
      "title": "appleEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/appleevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/architecture": {
      "abstract": [
        {
          "text": "The architecture version of the app to launch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "architecture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@cpu_type_t",
          "text": "cpu_type_t"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/architecture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "architecture"
        }
      ],
      "role": "symbol",
      "title": "architecture",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/architecture"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/arguments": {
      "abstract": [
        {
          "text": "The set of command-line arguments to pass to a new app instance at launch time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arguments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/arguments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arguments"
        }
      ],
      "role": "symbol",
      "title": "arguments",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/arguments"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/createsNewApplicationInstance": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you want the system to launch a new instance of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createsNewApplicationInstance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/createsNewApplicationInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createsNewApplicationInstance"
        }
      ],
      "role": "symbol",
      "title": "createsNewApplicationInstance",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/createsnewapplicationinstance"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/environment": {
      "abstract": [
        {
          "text": "The set of environment variables to set in a new app instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "environment"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/environment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "environment"
        }
      ],
      "role": "symbol",
      "title": "environment",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/environment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/hides": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you want the app to hide itself after it launches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hides"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/hides",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hides"
        }
      ],
      "role": "symbol",
      "title": "hides",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/hides"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/hidesOthers": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you want to hide all apps except the one that launched.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hidesOthers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/hidesOthers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidesOthers"
        }
      ],
      "role": "symbol",
      "title": "hidesOthers",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/hidesothers"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/isForPrinting": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you want to print the contents of documents and URLs instead of opening them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isForPrinting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/isForPrinting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "forPrinting"
        }
      ],
      "role": "symbol",
      "title": "isForPrinting",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/isforprinting"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/promptsUserIfNeeded": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to display errors, authentication requests, or other UI elements to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "promptsUserIfNeeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/promptsUserIfNeeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "promptsUserIfNeeded"
        }
      ],
      "role": "symbol",
      "title": "promptsUserIfNeeded",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/promptsuserifneeded"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/requiresUniversalLinks": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you require the URL to have an associated universal link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresUniversalLinks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/requiresUniversalLinks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresUniversalLinks"
        }
      ],
      "role": "symbol",
      "title": "requiresUniversalLinks",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/openconfiguration/requiresuniversallinks"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceOpenConfiguration/configuration": {
      "abstract": [
        {
          "text": "Creates and returns a new workspace configuration object containing default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceOpenConfiguration/configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspaceopenconfiguration/configuration"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion": {
      "abstract": [
        {
          "text": "The minimum version of the operating system required for the app to run in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "LSMinimumSystemVersion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Environment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion"
      ],
      "title": "Environment"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-URLs",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/requiresUniversalLinks",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/isForPrinting",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/requiresUniversalLinks",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/isForPrinting"
      ],
      "title": "Handling URLs"
    },
    {
      "anchor": "Specifying-App-Related-Behaviors",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/activates",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/addsToRecentItems",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/allowsRunningApplicationSubstitution",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/createsNewApplicationInstance",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/hides",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/hidesOthers"
      ],
      "title": "Specifying App-Related Behaviors"
    },
    {
      "anchor": "Prompting-the-User",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/promptsUserIfNeeded",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/promptsUserIfNeeded"
      ],
      "title": "Prompting the User"
    },
    {
      "anchor": "Specifying-Launch-Attributes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/appleEvent",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/arguments",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/environment",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/architecture"
      ],
      "title": "Specifying Launch Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWorkspaceOpenConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceOpenConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceOpenConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Workspace-Configuration-Object",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceOpenConfiguration/configuration"
              ],
              "title": "Creating a Workspace Configuration Object"
            },
            {
              "anchor": "Handling-URLs",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/requiresUniversalLinks",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/isForPrinting",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/requiresUniversalLinks",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/isForPrinting"
              ],
              "title": "Handling URLs"
            },
            {
              "anchor": "Specifying-App-Related-Behaviors",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/activates",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/addsToRecentItems",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/allowsRunningApplicationSubstitution",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/createsNewApplicationInstance",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/hides",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/hidesOthers"
              ],
              "title": "Specifying App-Related Behaviors"
            },
            {
              "anchor": "Prompting-the-User",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/promptsUserIfNeeded",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/promptsUserIfNeeded"
              ],
              "title": "Prompting the User"
            },
            {
              "anchor": "Specifying-Launch-Attributes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/appleEvent",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/arguments",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/environment",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/OpenConfiguration/architecture"
              ],
              "title": "Specifying Launch Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Environment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion"
              ],
              "title": "Environment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSWorkspaceOpenConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1hidesOthers/title",
          "value": "hidesOthers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1hidesOthers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidesOthers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1createsNewApplicationInstance/title",
          "value": "createsNewApplicationInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1createsNewApplicationInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "createsNewApplicationInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1requiresUniversalLinks/title",
          "value": "requiresUniversalLinks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1requiresUniversalLinks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresUniversalLinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1activates/title",
          "value": "activates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1activates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1environment/title",
          "value": "environment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1environment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "environment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/title",
          "value": "NSAppKitVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1allowsRunningApplicationSubstitution/title",
          "value": "allowsRunningApplicationSubstitution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1allowsRunningApplicationSubstitution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsRunningApplicationSubstitution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1hides/title",
          "value": "hides"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1hides/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hides"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration/title",
          "value": "NSWorkspaceOpenConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceOpenConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceOpenConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1isForPrinting/title",
          "value": "forPrinting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1isForPrinting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "forPrinting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/title",
          "value": "NSWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1appleEvent/title",
          "value": "appleEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1appleEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1addsToRecentItems/title",
          "value": "addsToRecentItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1addsToRecentItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addsToRecentItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1promptsUserIfNeeded/title",
          "value": "promptsUserIfNeeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1promptsUserIfNeeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "promptsUserIfNeeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1architecture/title",
          "value": "architecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1architecture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "architecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1arguments/title",
          "value": "arguments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1OpenConfiguration~1arguments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arguments"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsworkspace/openconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsworkspace/openconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
