{
  "abstract": [
    {
      "text": "Sets the icon for the file or directory at the specified path.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/setIcon(_:forFile:options:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSWorkspace(im)setIcon:forFile:options:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setIcon"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSImage",
        "text": "NSImage"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "forFile"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSWorkspace",
        "text": "NSWorkspace"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSWorkspaceIconCreationOptions",
        "text": "IconCreationOptions"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setIcon:forFile:options:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setIcon(_:forFile:options:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setIcon"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "image"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSImage",
              "text": "NSImage"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "forFile"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "fullPath"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWorkspace",
              "text": "NSWorkspace"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSWorkspaceIconCreationOptions",
              "text": "IconCreationOptions"
            },
            {
              "kind": "text",
              "text": " = []) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The image to use as the icon for the file or directory.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "image"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The full path of the file or directory.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "fullPath"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The icon representations to generate from the image. You specify this value by combining the appropriate ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " constants, using the C bitwise ",
                  "type": "text"
                },
                {
                  "code": "OR",
                  "type": "codeVoice"
                },
                {
                  "text": " operator. Specify ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": " if you want to generate icons in all available icon representation formats.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the icon was set; otherwise, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "image",
              "type": "codeVoice"
            },
            {
              "text": " can be an arbitrary image, with or without transparency. The method automatically scales this image (as needed) to generate the icon representations. The file or folder must exist and be writable by the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This method uses the image to set an icon with a size of 512 pixels by 512 pixels. If you specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions/exclude10_4ElementsIconCreationOption",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " option (not recommended), this method creates an icon that is compatible with the Finder from macOS 10.2 or earlier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can safely call this method from any of your app’s threads, but you must call it from only one thread at a time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/appkit/nsimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace": {
      "abstract": [
        {
          "text": "A workspace that can launch other apps and perform a variety of file-handling services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspace",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions": {
      "abstract": [
        {
          "text": "Constants that describe options for creating icons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IconCreationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IconCreationOptions"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspace.IconCreationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/iconcreationoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions/exclude10_4ElementsIconCreationOption": {
      "abstract": [
        {
          "text": "An option to suppress generation of the new higher resolution icon representations that are supported in macOS 10.4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exclude10_4ElementsIconCreationOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceIconCreationOptions",
          "text": "IconCreationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions/exclude10_4ElementsIconCreationOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExclude10_4ElementsIconCreationOption"
        }
      ],
      "role": "symbol",
      "title": "exclude10_4ElementsIconCreationOption",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/iconcreationoptions/exclude10_4elementsiconcreationoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(for:)": {
      "abstract": [
        {
          "text": "Returns an image containing the icon for the specified content type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "icon"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconForContentType:"
        }
      ],
      "role": "symbol",
      "title": "icon(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/icon(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFile:)": {
      "abstract": [
        {
          "text": "Returns an image containing the icon for the specified file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "icon"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFile:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconForFile:"
        }
      ],
      "role": "symbol",
      "title": "icon(forFile:)",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/icon(forfile:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFiles:)": {
      "abstract": [
        {
          "text": "Returns an image containing the icon for the specified files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "icon"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFiles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFiles:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconForFiles:"
        }
      ],
      "role": "symbol",
      "title": "icon(forFiles:)",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/icon(forfiles:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/setIcon(_:forFile:options:)": {
      "abstract": [
        {
          "text": "Sets the icon for the file or directory at the specified path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIcon"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWorkspaceIconCreationOptions",
          "text": "IconCreationOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/setIcon(_:forFile:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIcon:forFile:options:"
        }
      ],
      "role": "symbol",
      "title": "setIcon(_:forFile:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/seticon(_:forfile:options:)"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Icons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFile:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFiles:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions"
      ],
      "title": "Managing Icons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setIcon:forFile:options:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIcon:forFile:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Icons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFile:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFiles:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions"
              ],
              "title": "Managing Icons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setIcon:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSImage",
                    "text": "NSImage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "image"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forFile:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "fullPath"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "options:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSWorkspaceIconCreationOptions",
                    "text": "NSWorkspaceIconCreationOptions"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The image to use as the icon for the file or directory.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "image"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The full path of the file or directory.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "fullPath"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The icon representations to generate from the image. You specify this value by combining the appropriate ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/IconCreationOptions",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " constants, using the C bitwise ",
                        "type": "text"
                      },
                      {
                        "code": "OR",
                        "type": "codeVoice"
                      },
                      {
                        "text": " operator. Specify ",
                        "type": "text"
                      },
                      {
                        "code": "0",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if you want to generate icons in all available icon representation formats.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the icon was set; otherwise, ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1icon(for:)/title",
          "value": "iconForContentType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1icon(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "iconForContentType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/title",
          "value": "NSWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1IconCreationOptions/title",
          "value": "NSWorkspaceIconCreationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1IconCreationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceIconCreationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1IconCreationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceIconCreationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1setIcon(_:forFile:options:)/title",
          "value": "setIcon:forFile:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1setIcon(_:forFile:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIcon:forFile:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1icon(forFiles:)/title",
          "value": "iconForFiles:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1icon(forFiles:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "iconForFiles:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1icon(forFile:)/title",
          "value": "iconForFile:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1icon(forFile:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "iconForFile:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1IconCreationOptions~1exclude10_4ElementsIconCreationOption/title",
          "value": "NSExclude10_4ElementsIconCreationOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1IconCreationOptions~1exclude10_4ElementsIconCreationOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExclude10_4ElementsIconCreationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsworkspace/seticon(_:forfile:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsworkspace/seticon(_:forfile:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
