{
  "abstract": [
    {
      "text": "A URL containing the mount path of the volume.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/volumeURLUserInfoKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSWorkspaceVolumeURLKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "volumeURLUserInfoKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWorkspaceVolumeURLKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "volumeURLUserInfoKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "volumeURLUserInfoKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace": {
      "abstract": [
        {
          "text": "A workspace that can launch other apps and perform a variety of file-handling services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspace",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/activeSpaceDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when a Spaces change occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeSpaceDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/activeSpaceDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceActiveSpaceDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "activeSpaceDidChangeNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/activespacedidchangenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didActivateApplicationNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when the Finder is about to activate an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didActivateApplicationNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didActivateApplicationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDidActivateApplicationNotification"
        }
      ],
      "role": "symbol",
      "title": "didActivateApplicationNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/didactivateapplicationnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didChangeFileLabelsNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when the Finder file labels or colors change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeFileLabelsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didChangeFileLabelsNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDidChangeFileLabelsNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeFileLabelsNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/didchangefilelabelsnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didDeactivateApplicationNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when the Finder deactivates an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didDeactivateApplicationNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didDeactivateApplicationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDidDeactivateApplicationNotification"
        }
      ],
      "role": "symbol",
      "title": "didDeactivateApplicationNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/diddeactivateapplicationnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didHideApplicationNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when the Finder hides an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didHideApplicationNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didHideApplicationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDidHideApplicationNotification"
        }
      ],
      "role": "symbol",
      "title": "didHideApplicationNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/didhideapplicationnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didLaunchApplicationNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when a new app starts up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didLaunchApplicationNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didLaunchApplicationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDidLaunchApplicationNotification"
        }
      ],
      "role": "symbol",
      "title": "didLaunchApplicationNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/didlaunchapplicationnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didMountNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when a new device mounts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didMountNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didMountNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDidMountNotification"
        }
      ],
      "role": "symbol",
      "title": "didMountNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/didmountnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didRenameVolumeNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when a volume changes its name or mount path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didRenameVolumeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didRenameVolumeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDidRenameVolumeNotification"
        }
      ],
      "role": "symbol",
      "title": "didRenameVolumeNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/didrenamevolumenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didTerminateApplicationNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when an app finishes executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didTerminateApplicationNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didTerminateApplicationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDidTerminateApplicationNotification"
        }
      ],
      "role": "symbol",
      "title": "didTerminateApplicationNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/didterminateapplicationnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didUnhideApplicationNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when the Finder unhides an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didUnhideApplicationNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didUnhideApplicationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDidUnhideApplicationNotification"
        }
      ],
      "role": "symbol",
      "title": "didUnhideApplicationNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/didunhideapplicationnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didUnmountNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when the Finder unmounts a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didUnmountNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didUnmountNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceDidUnmountNotification"
        }
      ],
      "role": "symbol",
      "title": "didUnmountNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/didunmountnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/sessionDidBecomeActiveNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts after a user session switches in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionDidBecomeActiveNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/sessionDidBecomeActiveNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceSessionDidBecomeActiveNotification"
        }
      ],
      "role": "symbol",
      "title": "sessionDidBecomeActiveNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/sessiondidbecomeactivenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/sessionDidResignActiveNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts before a user session switches out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionDidResignActiveNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/sessionDidResignActiveNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceSessionDidResignActiveNotification"
        }
      ],
      "role": "symbol",
      "title": "sessionDidResignActiveNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/sessiondidresignactivenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/volumeURLUserInfoKey": {
      "abstract": [
        {
          "text": "A URL containing the mount path of the volume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "volumeURLUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/volumeURLUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceVolumeURLKey"
        }
      ],
      "role": "symbol",
      "title": "volumeURLUserInfoKey",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/volumeurluserinfokey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/willLaunchApplicationNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when the Finder is about to launch an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willLaunchApplicationNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/willLaunchApplicationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceWillLaunchApplicationNotification"
        }
      ],
      "role": "symbol",
      "title": "willLaunchApplicationNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/willlaunchapplicationnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/willUnmountNotification": {
      "abstract": [
        {
          "text": "A notification that the workspace posts when the Finder is about to unmount a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willUnmountNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/willUnmountNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceWillUnmountNotification"
        }
      ],
      "role": "symbol",
      "title": "willUnmountNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspace/willunmountnotification"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-Environment-Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/willLaunchApplicationNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didLaunchApplicationNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didTerminateApplicationNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/sessionDidBecomeActiveNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/sessionDidResignActiveNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didHideApplicationNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didUnhideApplicationNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didActivateApplicationNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didDeactivateApplicationNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didRenameVolumeNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didMountNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/willUnmountNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didUnmountNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didChangeFileLabelsNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/activeSpaceDidChangeNotification"
      ],
      "title": "Responding to Environment Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWorkspaceVolumeURLKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceVolumeURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-Environment-Notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/willLaunchApplicationNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didLaunchApplicationNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didTerminateApplicationNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/sessionDidBecomeActiveNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/sessionDidResignActiveNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didHideApplicationNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didUnhideApplicationNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didActivateApplicationNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didDeactivateApplicationNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didRenameVolumeNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didMountNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/willUnmountNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didUnmountNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/didChangeFileLabelsNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSWorkspace/activeSpaceDidChangeNotification"
              ],
              "title": "Responding to Environment Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSWorkspaceVolumeURLKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didMountNotification/title",
          "value": "NSWorkspaceDidMountNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didMountNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDidMountNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didActivateApplicationNotification/title",
          "value": "NSWorkspaceDidActivateApplicationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didActivateApplicationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDidActivateApplicationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didLaunchApplicationNotification/title",
          "value": "NSWorkspaceDidLaunchApplicationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didLaunchApplicationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDidLaunchApplicationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1activeSpaceDidChangeNotification/title",
          "value": "NSWorkspaceActiveSpaceDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1activeSpaceDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceActiveSpaceDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/title",
          "value": "NSWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didChangeFileLabelsNotification/title",
          "value": "NSWorkspaceDidChangeFileLabelsNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didChangeFileLabelsNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDidChangeFileLabelsNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didUnhideApplicationNotification/title",
          "value": "NSWorkspaceDidUnhideApplicationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didUnhideApplicationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDidUnhideApplicationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didHideApplicationNotification/title",
          "value": "NSWorkspaceDidHideApplicationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didHideApplicationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDidHideApplicationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1sessionDidBecomeActiveNotification/title",
          "value": "NSWorkspaceSessionDidBecomeActiveNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1sessionDidBecomeActiveNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceSessionDidBecomeActiveNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1willLaunchApplicationNotification/title",
          "value": "NSWorkspaceWillLaunchApplicationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1willLaunchApplicationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceWillLaunchApplicationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didTerminateApplicationNotification/title",
          "value": "NSWorkspaceDidTerminateApplicationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didTerminateApplicationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDidTerminateApplicationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1sessionDidResignActiveNotification/title",
          "value": "NSWorkspaceSessionDidResignActiveNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1sessionDidResignActiveNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceSessionDidResignActiveNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didDeactivateApplicationNotification/title",
          "value": "NSWorkspaceDidDeactivateApplicationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didDeactivateApplicationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDidDeactivateApplicationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didRenameVolumeNotification/title",
          "value": "NSWorkspaceDidRenameVolumeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didRenameVolumeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDidRenameVolumeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1volumeURLUserInfoKey/title",
          "value": "NSWorkspaceVolumeURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1volumeURLUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceVolumeURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1willUnmountNotification/title",
          "value": "NSWorkspaceWillUnmountNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1willUnmountNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceWillUnmountNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didUnmountNotification/title",
          "value": "NSWorkspaceDidUnmountNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1didUnmountNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceDidUnmountNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsworkspace/volumeurluserinfokey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsworkspace/volumeurluserinfokey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
