{
  "abstract": [
    {
      "text": "Payment from a savings account.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/savings"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INPaymentMethodType@INPaymentMethodTypeSavings",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "savings"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPaymentMethodTypeSavings"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INPaymentMethodType.savings"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "savings"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType": {
      "abstract": [
        {
          "text": "Constants describing the available payment options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentMethodType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodType"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodType",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/applePay": {
      "abstract": [
        {
          "text": "Payment using Apple Pay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applePay"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/applePay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodTypeApplePay"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodType.applePay",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodtype/applepay"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/brokerage": {
      "abstract": [
        {
          "text": "Payment from a brokerage account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "brokerage"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/brokerage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodTypeBrokerage"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodType.brokerage",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodtype/brokerage"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/checking": {
      "abstract": [
        {
          "text": "Payment from a checking account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checking"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/checking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodTypeChecking"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodType.checking",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodtype/checking"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/credit": {
      "abstract": [
        {
          "text": "Payment using a credit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credit"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/credit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodTypeCredit"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodType.credit",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodtype/credit"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/debit": {
      "abstract": [
        {
          "text": "Payment using a debit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debit"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/debit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodTypeDebit"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodType.debit",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodtype/debit"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/prepaid": {
      "abstract": [
        {
          "text": "Payment using a prepaid card or account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepaid"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/prepaid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodTypePrepaid"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodType.prepaid",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodtype/prepaid"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/savings": {
      "abstract": [
        {
          "text": "Payment from a savings account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "savings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/savings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodTypeSavings"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodType.savings",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodtype/savings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/store": {
      "abstract": [
        {
          "text": "Payment using a store charge card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "store"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/store",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodTypeStore"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodType.store",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodtype/store"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/unknown": {
      "abstract": [
        {
          "text": "An unspecified payment type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodType.unknown",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodtype/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/checking",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/brokerage",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/debit",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/credit",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/prepaid",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/store",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/applePay"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPaymentMethodTypeSavings"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodTypeSavings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/checking",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/brokerage",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/debit",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/credit",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/prepaid",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/store",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodType/applePay"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INPaymentMethodTypeSavings"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1checking/title",
          "value": "INPaymentMethodTypeChecking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1checking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodTypeChecking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1savings/title",
          "value": "INPaymentMethodTypeSavings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1savings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodTypeSavings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1debit/title",
          "value": "INPaymentMethodTypeDebit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1debit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodTypeDebit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1store/title",
          "value": "INPaymentMethodTypeStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1store/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodTypeStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1prepaid/title",
          "value": "INPaymentMethodTypePrepaid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1prepaid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodTypePrepaid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1brokerage/title",
          "value": "INPaymentMethodTypeBrokerage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1brokerage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodTypeBrokerage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1unknown/title",
          "value": "INPaymentMethodTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1credit/title",
          "value": "INPaymentMethodTypeCredit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1credit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodTypeCredit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1applePay/title",
          "value": "INPaymentMethodTypeApplePay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType~1applePay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodTypeApplePay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType/title",
          "value": "INPaymentMethodType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inpaymentmethodtype/savings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inpaymentmethodtype/savings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
