{
  "abstract": [
    {
      "text": "Network EAPTTLS inner authentication type is CHAP.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationCHAP"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEHotspotConfigurationTTLSInnerAuthenticationType@NEHotspotConfigurationEAPTTLSInnerAuthenticationCHAP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "eapttlsInnerAuthenticationCHAP"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationCHAP"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEHotspotEAPSettings.TTLSInnerAuthenticationType.eapttlsInnerAuthenticationCHAP"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "eapttlsInnerAuthenticationCHAP"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings": {
      "abstract": [
        {
          "text": "Extensible Authentication Protocol settings for configuring WPA and WPA2 enterprise Wi-Fi networks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotEAPSettings"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotEAPSettings"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum": {
      "abstract": [
        {
          "text": "The TTLS Inner Authentication Types that may be specified by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TTLSInnerAuthenticationType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TTLSInnerAuthenticationType"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.TTLSInnerAuthenticationType",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/ttlsinnerauthenticationtype-swift.enum"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationCHAP": {
      "abstract": [
        {
          "text": "Network EAPTTLS inner authentication type is CHAP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eapttlsInnerAuthenticationCHAP"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationCHAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationCHAP"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.TTLSInnerAuthenticationType.eapttlsInnerAuthenticationCHAP",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/ttlsinnerauthenticationtype-swift.enum/eapttlsinnerauthenticationchap"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationEAP": {
      "abstract": [
        {
          "text": "Network EAPTTLS inner authentication type is EAP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eapttlsInnerAuthenticationEAP"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationEAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationEAP"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.TTLSInnerAuthenticationType.eapttlsInnerAuthenticationEAP",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/ttlsinnerauthenticationtype-swift.enum/eapttlsinnerauthenticationeap"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationMSCHAP": {
      "abstract": [
        {
          "text": "Network EAPTTLS inner authentication type is MSCHAP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eapttlsInnerAuthenticationMSCHAP"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationMSCHAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationMSCHAP"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.TTLSInnerAuthenticationType.eapttlsInnerAuthenticationMSCHAP",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/ttlsinnerauthenticationtype-swift.enum/eapttlsinnerauthenticationmschap"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationMSCHAPv2": {
      "abstract": [
        {
          "text": "Network EAPTTLS inner authentication type is MSCHAP, version 2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eapttlsInnerAuthenticationMSCHAPv2"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationMSCHAPv2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationMSCHAPv2"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.TTLSInnerAuthenticationType.eapttlsInnerAuthenticationMSCHAPv2",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/ttlsinnerauthenticationtype-swift.enum/eapttlsinnerauthenticationmschapv2"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationPAP": {
      "abstract": [
        {
          "text": "Network EAPTTLS inner authentication type is PAP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eapttlsInnerAuthenticationPAP"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationPAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationPAP"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.TTLSInnerAuthenticationType.eapttlsInnerAuthenticationPAP",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/ttlsinnerauthenticationtype-swift.enum/eapttlsinnerauthenticationpap"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationPAP",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationMSCHAP",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationMSCHAPv2",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationEAP"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEHotspotConfigurationEAPTTLSInnerAuthenticationCHAP"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationCHAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationPAP",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationMSCHAP",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationMSCHAPv2",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum/eapttlsInnerAuthenticationEAP"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationCHAP"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum~1eapttlsInnerAuthenticationEAP/title",
          "value": "NEHotspotConfigurationEAPTTLSInnerAuthenticationEAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum~1eapttlsInnerAuthenticationEAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationEAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum~1eapttlsInnerAuthenticationMSCHAP/title",
          "value": "NEHotspotConfigurationEAPTTLSInnerAuthenticationMSCHAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum~1eapttlsInnerAuthenticationMSCHAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationMSCHAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum~1eapttlsInnerAuthenticationCHAP/title",
          "value": "NEHotspotConfigurationEAPTTLSInnerAuthenticationCHAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum~1eapttlsInnerAuthenticationCHAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationCHAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum/title",
          "value": "NEHotspotConfigurationTTLSInnerAuthenticationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationTTLSInnerAuthenticationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationTTLSInnerAuthenticationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum~1eapttlsInnerAuthenticationPAP/title",
          "value": "NEHotspotConfigurationEAPTTLSInnerAuthenticationPAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum~1eapttlsInnerAuthenticationPAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationPAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum~1eapttlsInnerAuthenticationMSCHAPv2/title",
          "value": "NEHotspotConfigurationEAPTTLSInnerAuthenticationMSCHAPv2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum~1eapttlsInnerAuthenticationMSCHAPv2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTTLSInnerAuthenticationMSCHAPv2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings/title",
          "value": "NEHotspotEAPSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotEAPSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotEAPSettings"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nehotspoteapsettings/ttlsinnerauthenticationtype-swift.enum/eapttlsinnerauthenticationchap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nehotspoteapsettings/ttlsinnerauthenticationtype-swift.enum/eapttlsinnerauthenticationchap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
