{
  "abstract": [
    {
      "text": "A per-patch step function. For all instances, the tessellation factor for all patches in a patch draw call is at the ",
      "type": "text"
    },
    {
      "code": "offset + (drawPatchIndex * tessellationFactorStride)",
      "type": "codeVoice"
    },
    {
      "text": " location in the tessellation factor buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLTessellationFactorStepFunction@MTLTessellationFactorStepFunctionPerPatch",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "perPatch"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLTessellationFactorStepFunctionPerPatch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLTessellationFactorStepFunction.perPatch"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "perPatch"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction": {
      "abstract": [
        {
          "text": "Options for specifying the step function that determines the tessellation factors for a patch from the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunction"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/constant": {
      "abstract": [
        {
          "text": "A constant step function. For all instances, the tessellation factor for all patches in a patch draw call is at the ",
          "type": "text"
        },
        {
          "code": "offset",
          "type": "codeVoice"
        },
        {
          "text": " location in the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constant"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/constant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunctionConstant"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction.constant",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction/constant"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perInstance": {
      "abstract": [
        {
          "text": "A per-instance step function. For a given instance ID, the tessellation factor for a patch in a patch draw call is at the ",
          "type": "text"
        },
        {
          "code": "offset + (instanceID * instanceStride)",
          "type": "codeVoice"
        },
        {
          "text": " location in the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perInstance"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunctionPerInstance"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction.perInstance",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction/perinstance"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatch": {
      "abstract": [
        {
          "text": "A per-patch step function. For all instances, the tessellation factor for all patches in a patch draw call is at the ",
          "type": "text"
        },
        {
          "code": "offset + (drawPatchIndex * tessellationFactorStride)",
          "type": "codeVoice"
        },
        {
          "text": " location in the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perPatch"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunctionPerPatch"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction.perPatch",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction/perpatch"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatchAndPerInstance": {
      "abstract": [
        {
          "text": "A per-patch and per-instance step function. For a given instance ID, the tessellation factor for a patch in a patch draw call is at the ",
          "type": "text"
        },
        {
          "code": "offset + (drawPatchIndex * tessellationFactorStride + instanceID * instanceStride)",
          "type": "codeVoice"
        },
        {
          "text": " location in the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perPatchAndPerInstance"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatchAndPerInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunctionPerPatchAndPerInstance"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction.perPatchAndPerInstance",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction/perpatchandperinstance"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/constant",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perInstance",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatchAndPerInstance"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLTessellationFactorStepFunctionPerPatch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunctionPerPatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/constant",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perInstance",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatchAndPerInstance"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLTessellationFactorStepFunctionPerPatch"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1constant/title",
          "value": "MTLTessellationFactorStepFunctionConstant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1constant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunctionConstant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perPatch/title",
          "value": "MTLTessellationFactorStepFunctionPerPatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perPatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunctionPerPatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perInstance/title",
          "value": "MTLTessellationFactorStepFunctionPerInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunctionPerInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction/title",
          "value": "MTLTessellationFactorStepFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perPatchAndPerInstance/title",
          "value": "MTLTessellationFactorStepFunctionPerPatchAndPerInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perPatchAndPerInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunctionPerPatchAndPerInstance"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtltessellationfactorstepfunction/perpatch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtltessellationfactorstepfunction/perpatch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
