{
  "abstract": [
    {
      "text": "Live Photo processing was canceled by the Processing an Editing Context’s Live Photo method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode/aborted"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHLivePhotoEditingErrorCode@PHLivePhotoEditingErrorCodeAborted",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "aborted"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHLivePhotoEditingErrorCodeAborted"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.12",
        "name": "macOS",
        "renamed": "PHPhotosError.userCancelled",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHLivePhotoEditingErrorCode.aborted"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "aborted"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode": {
      "abstract": [
        {
          "text": "Error codes for Live Photo editing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoEditingErrorCode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoEditingErrorCode"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoEditingErrorCode",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoeditingerrorcode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode/aborted": {
      "abstract": [
        {
          "text": "Live Photo processing was canceled by the Processing an Editing Context’s Live Photo method.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aborted"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode/aborted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoEditingErrorCodeAborted"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoEditingErrorCode.aborted",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoeditingerrorcode/aborted"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode/unknown": {
      "abstract": [
        {
          "text": "No further information is available about the cause of the error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoEditingErrorCodeUnknown"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoEditingErrorCode.unknown",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoeditingerrorcode/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode/unknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHLivePhotoEditingErrorCodeAborted"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoEditingErrorCodeAborted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingErrorCode/unknown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHLivePhotoEditingErrorCodeAborted"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingErrorCode~1unknown/title",
          "value": "PHLivePhotoEditingErrorCodeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingErrorCode~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoEditingErrorCodeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingErrorCode~1aborted/title",
          "value": "PHLivePhotoEditingErrorCodeAborted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingErrorCode~1aborted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoEditingErrorCodeAborted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingErrorCode/title",
          "value": "PHLivePhotoEditingErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoEditingErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoEditingErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phlivephotoeditingerrorcode/aborted"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phlivephotoeditingerrorcode/aborted"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
