{
  "abstract": [
    {
      "text": "Causes the receiver to finish loading a resource for which a resource loader’s delegate took responsibility .",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This method is deprecated. Use the following methods and properties instead: the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/response",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property to provide the response object, the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/redirect",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property when redirecting a request, invoking the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/dataRequest",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instance’s",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/respond(with:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method to provide data, and the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method to indicate that loading is finished.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:data:redirect:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVAssetResourceLoadingRequest(im)finishLoadingWithResponse:data:redirect:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "finishLoading"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSURLResponse",
        "text": "URLResponse"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "data"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DataV",
        "text": "Data"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "redirect"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation10URLRequestV",
        "text": "URLRequest"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "finishLoadingWithResponse:data:redirect:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.15",
        "message": "Use -[AVAssetResourceLoadingRequest setResponse:], -[AVAssetResourceLoadingRequest setRedirect:], -[AVAssetResourceLoadingDataRequest respondWithData:], -[AVAssetResourceLoadingRequest finishLoading]",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "9.0",
        "message": "Use -[AVAssetResourceLoadingRequest setResponse:], -[AVAssetResourceLoadingRequest setRedirect:], -[AVAssetResourceLoadingDataRequest respondWithData:], -[AVAssetResourceLoadingRequest finishLoading]",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "finishLoading(with:data:redirect:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "finishLoading"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "response"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURLResponse",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURLResponse",
              "text": "URLResponse"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "data"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DataV",
              "text": "Data"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "redirect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation10URLRequestV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation10URLRequestV",
              "text": "URLRequest"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The response object for the requested resource. Use the request object in the receiver’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/request",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property to get information about the requested resource.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "response"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The data of the resource. If no data is available, specify ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "data"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "When redirecting a resource request, use this parameter to specify the corresponding ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlrequest",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object. If you are handling the request and not redirecting it, specify ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "redirect"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a resource loader’s delegate takes responsibility for loading a resource, it calls this method to indicate that the resource was loaded successfully. This method marks the loading request as finished and returns the provided data back to the resource loader object for processing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/respond(with:)": {
      "abstract": [
        {
          "text": "Provides data to the loading request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "respond"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/respond(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "respondWithData:"
        }
      ],
      "role": "symbol",
      "title": "respond(with:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingdatarequest/respond(with:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates information about a resource request from a resource loader object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetResourceLoadingRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetResourceLoadingRequest"
        }
      ],
      "role": "symbol",
      "title": "AVAssetResourceLoadingRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/dataRequest": {
      "abstract": [
        {
          "text": "The range of requested resource data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetResourceLoadingDataRequest",
          "text": "AVAssetResourceLoadingDataRequest"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/dataRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataRequest"
        }
      ],
      "role": "symbol",
      "title": "dataRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/datarequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()": {
      "abstract": [
        {
          "text": "Causes the receiver to treat the processing of the request as complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishLoading"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishLoading"
        }
      ],
      "role": "symbol",
      "title": "finishLoading()",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/finishloading()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:)": {
      "abstract": [
        {
          "text": "Causes the receiver to handle the failure to load a resource for which a resource loader’s delegate took responsibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishLoading"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishLoadingWithError:"
        }
      ],
      "role": "symbol",
      "title": "finishLoading(with:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/finishloading(with:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:data:redirect:)": {
      "abstract": [
        {
          "text": "Causes the receiver to finish loading a resource for which a resource loader’s delegate took responsibility .",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishLoading"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSURLResponse",
          "text": "URLResponse"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "redirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:data:redirect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishLoadingWithResponse:data:redirect:"
        }
      ],
      "role": "symbol",
      "title": "finishLoading(with:data:redirect:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/finishloading(with:data:redirect:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isCancelled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the request has been cancelled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "role": "symbol",
      "title": "isCancelled",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/iscancelled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isFinished": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether loading of the resource has finished.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFinished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isFinished",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finished"
        }
      ],
      "role": "symbol",
      "title": "isFinished",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/isfinished"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/redirect": {
      "abstract": [
        {
          "text": "An URL request instance if the loading request was redirected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/redirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "redirect"
        }
      ],
      "role": "symbol",
      "title": "redirect",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/redirect"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/request": {
      "abstract": [
        {
          "text": "The URL request object for the resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "request"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/request",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "request"
        }
      ],
      "role": "symbol",
      "title": "request",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/request"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/response": {
      "abstract": [
        {
          "text": "The URL response for the loading request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "response"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSURLResponse",
          "text": "URLResponse"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/response",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "response"
        }
      ],
      "role": "symbol",
      "title": "response",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/response"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurlrequest": {
      "abstract": [
        {
          "text": "A representation of a URL load request that you use when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURLRequest"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlrequest",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURLRequest",
      "type": "topic",
      "url": "/documentation/foundation/nsurlrequest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSData": {
      "abstract": [
        {
          "text": "A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSData"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSData",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSData",
      "type": "topic",
      "url": "/documentation/foundation/nsdata"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSURLResponse": {
      "abstract": [
        {
          "text": "The metadata associated with the response to a URL load request, independent of protocol and URL scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "URLResponse"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURLResponse",
      "kind": "symbol",
      "role": "symbol",
      "title": "URLResponse",
      "type": "topic",
      "url": "/documentation/foundation/urlresponse"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation10URLRequestV": {
      "abstract": [
        {
          "text": "A URL load request that is independent of protocol or URL scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URLRequest"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation10URLRequestV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URLRequest",
      "type": "topic",
      "url": "/documentation/foundation/urlrequest"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DataV": {
      "abstract": [
        {
          "text": "A byte buffer in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Data",
      "type": "topic",
      "url": "/documentation/foundation/data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reporting-the-Result-of-the-Request",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/response",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isCancelled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isFinished"
      ],
      "title": "Reporting the Result of the Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "finishLoadingWithResponse:data:redirect:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishLoadingWithResponse:data:redirect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reporting-the-Result-of-the-Request",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/response",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isCancelled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isFinished"
              ],
              "title": "Reporting the Result of the Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "finishLoadingWithResponse:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURLResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURLResponse",
                    "text": "NSURLResponse"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "response"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "data:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSData",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSData",
                    "text": "NSData"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "data"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "redirect:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURLRequest",
                    "text": "NSURLRequest"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "redirect"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The response object for the requested resource. Use the request object in the receiver’s ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/request",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property to get information about the requested resource.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "response"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The data of the resource. If no data is available, specify ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "data"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "When redirecting a resource request, use this parameter to specify the corresponding ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlrequest",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object. If you are handling the request and not redirecting it, specify ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "redirect"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This method is deprecated. Use the following methods and properties instead: the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/response",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property to provide the response object, the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/redirect",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property when redirecting a request, invoking the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/dataRequest",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance’s",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/respond(with:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method to provide data, and the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method to indicate that loading is finished.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading(with:)/title",
          "value": "finishLoadingWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishLoadingWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading(with:data:redirect:)/title",
          "value": "finishLoadingWithResponse:data:redirect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading(with:data:redirect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishLoadingWithResponse:data:redirect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurlrequest/abstract",
          "value": [
            {
              "text": "A URL load request that is independent of protocol or URL scheme.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1respond(with:)/title",
          "value": "respondWithData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1respond(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "respondWithData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading()/title",
          "value": "finishLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1response/title",
          "value": "response"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1response/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "response"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1isFinished/title",
          "value": "finished"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1isFinished/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "finished"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1redirect/title",
          "value": "redirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1redirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "redirect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest/title",
          "value": "AVAssetResourceLoadingRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetResourceLoadingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetResourceLoadingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURLResponse/title",
          "value": "NSURLResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1dataRequest/title",
          "value": "dataRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1dataRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1request/title",
          "value": "request"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1request/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1isCancelled/title",
          "value": "cancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1isCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSData/abstract",
          "value": [
            {
              "text": "A static byte buffer in memory.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avassetresourceloadingrequest/finishloading(with:data:redirect:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avassetresourceloadingrequest/finishloading(with:data:redirect:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
