{
  "abstract": [
    {
      "text": "The URL response for the loading request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/response"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAssetResourceLoadingRequest(py)response",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "response"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSURLResponse",
        "text": "URLResponse"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "response"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "response"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "response"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURLResponse",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURLResponse",
              "text": "URLResponse"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property is an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/urlresponse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", indicating a response to the loading request. If no response is needed, the value of this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates information about a resource request from a resource loader object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetResourceLoadingRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetResourceLoadingRequest"
        }
      ],
      "role": "symbol",
      "title": "AVAssetResourceLoadingRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()": {
      "abstract": [
        {
          "text": "Causes the receiver to treat the processing of the request as complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishLoading"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishLoading"
        }
      ],
      "role": "symbol",
      "title": "finishLoading()",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/finishloading()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:)": {
      "abstract": [
        {
          "text": "Causes the receiver to handle the failure to load a resource for which a resource loader’s delegate took responsibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishLoading"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishLoadingWithError:"
        }
      ],
      "role": "symbol",
      "title": "finishLoading(with:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/finishloading(with:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:data:redirect:)": {
      "abstract": [
        {
          "text": "Causes the receiver to finish loading a resource for which a resource loader’s delegate took responsibility .",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishLoading"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSURLResponse",
          "text": "URLResponse"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "redirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:data:redirect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishLoadingWithResponse:data:redirect:"
        }
      ],
      "role": "symbol",
      "title": "finishLoading(with:data:redirect:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/finishloading(with:data:redirect:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isCancelled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the request has been cancelled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "role": "symbol",
      "title": "isCancelled",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/iscancelled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isFinished": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether loading of the resource has finished.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFinished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isFinished",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finished"
        }
      ],
      "role": "symbol",
      "title": "isFinished",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/isfinished"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/response": {
      "abstract": [
        {
          "text": "The URL response for the loading request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "response"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSURLResponse",
          "text": "URLResponse"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/response",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "response"
        }
      ],
      "role": "symbol",
      "title": "response",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/response"
    },
    "doc://com.apple.documentation/documentation/foundation/urlresponse": {
      "abstract": [
        {
          "text": "The metadata associated with the response to a URL load request, independent of protocol and URL scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "URLResponse"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlresponse",
      "kind": "symbol",
      "role": "symbol",
      "title": "URLResponse",
      "type": "topic",
      "url": "/documentation/foundation/urlresponse"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSURLResponse": {
      "abstract": [
        {
          "text": "The metadata associated with the response to a URL load request, independent of protocol and URL scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "URLResponse"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURLResponse",
      "kind": "symbol",
      "role": "symbol",
      "title": "URLResponse",
      "type": "topic",
      "url": "/documentation/foundation/urlresponse"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reporting-the-Result-of-the-Request",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isCancelled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isFinished",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:data:redirect:)"
      ],
      "title": "Reporting the Result of the Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "response"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "response"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reporting-the-Result-of-the-Request",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isCancelled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/isFinished",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading(with:data:redirect:)"
              ],
              "title": "Reporting the Result of the Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURLResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURLResponse",
                    "text": "NSURLResponse"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "response"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest/title",
          "value": "AVAssetResourceLoadingRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetResourceLoadingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetResourceLoadingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1response/title",
          "value": "response"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1response/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "response"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURLResponse/title",
          "value": "NSURLResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading(with:)/title",
          "value": "finishLoadingWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishLoadingWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlresponse/title",
          "value": "NSURLResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1isFinished/title",
          "value": "finished"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1isFinished/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "finished"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading()/title",
          "value": "finishLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1isCancelled/title",
          "value": "cancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1isCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading(with:data:redirect:)/title",
          "value": "finishLoadingWithResponse:data:redirect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading(with:data:redirect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishLoadingWithResponse:data:redirect:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avassetresourceloadingrequest/response"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avassetresourceloadingrequest/response"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
