{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredOutputSegmentInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CMTime","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@SA@CMTime","preciseIdentifier":"c:@SA@CMTime"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The default value is ","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/CoreMedia/CMTime/invalid","isActive":true},{"text":", which indicates that the asset writer chooses an appropriate default value. You may also set a positive numeric or ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/CoreMedia/CMTime/indefinite","type":"reference","isActive":true},{"text":" time. When the value is ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/CoreMedia/CMTime/indefinite","type":"reference","isActive":true},{"text":", each call you make to ","type":"text"},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/flushSegment()","type":"reference","isActive":true},{"text":" outputs a segment data.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can’t change this value after writing starts.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["/documentation/avfoundation/avassetwriter/preferredoutputsegmentinterval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avassetwriter/preferredoutputsegmentinterval"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The interval of output segments that you prefer."}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preferredOutputSegmentInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CMTime","preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier"}],"extendedModule":"AVFoundation","externalID":"c:objc(cs)AVAssetWriter(py)preferredOutputSegmentInterval","modules":[{"name":"AVFoundation"}],"symbolKind":"property","roleHeading":"Instance Property","title":"preferredOutputSegmentInterval","navigatorTitle":[{"text":"preferredOutputSegmentInterval","kind":"identifier"}],"platforms":[{"introducedAt":"14.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"11.0","name":"macOS","beta":false,"unavailable":false},{"introducedAt":"14.0","name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false,"deprecated":false}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Configuring Segment Writing","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/delegate","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterDelegate","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/initialSegmentStartTime","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/outputFileTypeProfile","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/flushSegment()"],"anchor":"Configuring-Segment-Writing","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/preferredOutputSegmentInterval"},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterDelegate":{"url":"/documentation/avfoundation/avassetwriterdelegate","navigatorTitle":[{"kind":"identifier","text":"AVAssetWriterDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVAssetWriterDelegate"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A delegate protocol that defines the methods to implement to respond to asset-writing events."}],"title":"AVAssetWriterDelegate","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterDelegate"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/initialSegmentStartTime":{"role":"symbol","type":"topic","title":"initialSegmentStartTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialSegmentStartTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime","text":"CMTime"}],"url":"/documentation/avfoundation/avassetwriter/initialsegmentstarttime","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/initialSegmentStartTime","kind":"symbol","abstract":[{"text":"The start time of the initial segment.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initialSegmentStartTime"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/delegate":{"role":"symbol","type":"topic","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)AVAssetWriterDelegate","kind":"typeIdentifier","text":"AVAssetWriterDelegate"},{"kind":"text","text":")?"}],"url":"/documentation/avfoundation/avassetwriter/delegate","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/delegate","kind":"symbol","abstract":[{"text":"A delegate object that responds to asset-writing events.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/preferredOutputSegmentInterval":{"role":"symbol","type":"topic","title":"preferredOutputSegmentInterval","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredOutputSegmentInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"}],"url":"/documentation/avfoundation/avassetwriter/preferredoutputsegmentinterval","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/preferredOutputSegmentInterval","kind":"symbol","abstract":[{"text":"The interval of output segments that you prefer.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"preferredOutputSegmentInterval"}]},"doc://com.externally.resolved.symbol/c:@SA@CMTime":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@SA@CMTime","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMTime","kind":"identifier"}],"abstract":[{"type":"text","text":"A structure that represents time."}],"type":"topic","title":"CMTime","url":"/documentation/CoreMedia/CMTime","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter":{"url":"/documentation/avfoundation/avassetwriter","title":"AVAssetWriter","abstract":[{"text":"An object that writes media data to a container file.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVAssetWriter","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAssetWriter","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/flushSegment()":{"title":"flushSegment()","url":"/documentation/avfoundation/avassetwriter/flushsegment()","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flushSegment"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/flushSegment()","navigatorTitle":[{"text":"flushSegment","kind":"identifier"}],"abstract":[{"text":"Closes the current segment and outputs it to a delegate method.","type":"text"}],"type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/outputFileTypeProfile":{"role":"symbol","type":"topic","title":"outputFileTypeProfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputFileTypeProfile"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AVFileTypeProfile","kind":"typeIdentifier","text":"AVFileTypeProfile"},{"kind":"text","text":"?"}],"url":"/documentation/avfoundation/avassetwriter/outputfiletypeprofile","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/outputFileTypeProfile","kind":"symbol","abstract":[{"text":"A profile for the output file type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"outputFileTypeProfile"}]},"doc://com.apple.documentation/documentation/CoreMedia/CMTime/invalid":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/CoreMedia/CMTime/invalid","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CMTime","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime"}],"abstract":[{"type":"text","text":"A value that represents an invalid time."}],"type":"topic","title":"invalid","url":"/documentation/CoreMedia/CMTime/invalid","kind":"symbol"},"doc://com.apple.documentation/documentation/CoreMedia/CMTime/indefinite":{"title":"indefinite","type":"topic","identifier":"doc://com.apple.documentation/documentation/CoreMedia/CMTime/indefinite","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"indefinite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"}],"abstract":[{"text":"A value that represents an indefinite time.","type":"text"}],"kind":"symbol","url":"/documentation/CoreMedia/CMTime/indefinite","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","beta":false,"introducedAt":"14.0","unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"introducedAt":"14.0","unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"14.0","unavailable":false,"deprecated":false},{"unavailable":false,"introducedAt":"11.0","beta":false,"name":"macOS","deprecated":false},{"unavailable":false,"introducedAt":"14.0","beta":false,"name":"tvOS","deprecated":false},{"unavailable":false,"introducedAt":"1.0","beta":false,"name":"visionOS","deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"preferredOutputSegmentInterval","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"preferredOutputSegmentInterval","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Configuring Segment Writing","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/delegate","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterDelegate","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/initialSegmentStartTime","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/outputFileTypeProfile","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter/flushSegment()"],"anchor":"Configuring-Segment-Writing"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"identifier":"doc://com.externally.resolved.symbol/c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredOutputSegmentInterval"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterDelegate/title","value":"AVAssetWriterDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterDelegate/fragments","value":[{"kind":"identifier","text":"AVAssetWriterDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterDelegate/navigatorTitle","value":[{"kind":"identifier","text":"AVAssetWriterDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter~1initialSegmentStartTime/title","value":"initialSegmentStartTime"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter~1initialSegmentStartTime/fragments","value":[{"text":"initialSegmentStartTime","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter~1delegate/title","value":"delegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter~1delegate/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter~1preferredOutputSegmentInterval/title","value":"preferredOutputSegmentInterval"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter~1preferredOutputSegmentInterval/fragments","value":[{"text":"preferredOutputSegmentInterval","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@CMTime/fragments","value":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" { ... } "},{"kind":"identifier","text":"CMTime"},{"kind":"text","text":";"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter/title","value":"AVAssetWriter","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter/fragments","value":[{"text":"AVAssetWriter","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter/navigatorTitle","value":[{"text":"AVAssetWriter","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter~1flushSegment()/title","value":"flushSegment","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter~1flushSegment()/fragments","value":[{"text":"- ","kind":"text"},{"text":"flushSegment","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter~1outputFileTypeProfile/title","value":"outputFileTypeProfile","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter~1outputFileTypeProfile/fragments","value":[{"text":"outputFileTypeProfile","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTime~1invalid/title","value":"kCMTimeInvalid","op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTime~1invalid/fragments","value":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMTime","preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"kCMTimeInvalid","kind":"identifier"},{"text":";","kind":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTime~1indefinite/title","value":"kCMTimeIndefinite","op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMTime~1indefinite/fragments","value":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMTime","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime"},{"text":" ","kind":"text"},{"text":"kCMTimeIndefinite","kind":"identifier"},{"text":";","kind":"text"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}