{
  "abstract": [
    {
      "text": "A type alias defining a closure that provides an activation configuration for the activation action.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction/ConfigurationProvider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@T@UIWindowSceneActivationActionConfigurationProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ConfigurationProvider"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ConfigurationProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "UIWindowScene.ActivationAction.ConfigurationProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ConfigurationProvider"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIWindowScene",
              "text": "UIWindowScene"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIWindowSceneActivationAction",
              "text": "ActivationAction"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIWindowScene",
              "text": "UIWindowScene"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIWindowSceneActivationConfiguration",
              "text": "ActivationConfiguration"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " requesting a configuration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "action"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An activation configuration you can use to request a window scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene": {
      "abstract": [
        {
          "text": "A scene that manages one or more windows for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction": {
      "abstract": [
        {
          "text": "A menu element that requests a window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationAction"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationAction",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction/ConfigurationProvider": {
      "abstract": [
        {
          "text": "A type alias defining a closure that provides an activation configuration for the activation action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ConfigurationProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction/ConfigurationProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ConfigurationProvider"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationAction.ConfigurationProvider",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationaction/configurationprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction/init(title:subtitle:image:identifier:discoverabilityTitle:attributes:alternate:_:)": {
      "abstract": [
        {
          "text": "Creates an activation action using the specified parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "subtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActionIdentifier",
          "text": "Identifier"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "discoverabilityTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenuElement",
          "text": "UIMenuElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIMenuElementAttributes",
          "text": "Attributes"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alternate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowSceneActivationAction",
          "text": "ActivationAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIWindowSceneActivationActionConfigurationProvider",
          "text": "ConfigurationProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction/init(title:subtitle:image:identifier:discoverabilityTitle:attributes:alternate:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(title:subtitle:image:identifier:discoverabilityTitle:attributes:alternate:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationaction/init(title:subtitle:image:identifier:discoverabilitytitle:attributes:alternate:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration": {
      "abstract": [
        {
          "text": "An object that provides configuration options for a window scene request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationAction/actionWithIdentifier:alternateAction:configurationProvider:": {
      "abstract": [
        {
          "text": "Creates an activation action with the specified parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "actionWithIdentifier:alternateAction:configurationProvider:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationAction/actionWithIdentifier:alternateAction:configurationProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "actionWithIdentifier:alternateAction:configurationProvider:"
        }
      ],
      "role": "symbol",
      "title": "actionWithIdentifier:alternateAction:configurationProvider:",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowsceneactivationaction/actionwithidentifier:alternateaction:configurationprovider:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-activation-action",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationAction/init(title:subtitle:image:identifier:discoverabilityTitle:attributes:alternate:_:)"
      ],
      "title": "Creating an activation action"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIWindowSceneActivationActionConfigurationProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationActionConfigurationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationActionConfigurationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-an-activation-action",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneActivationAction/actionWithIdentifier:alternateAction:configurationProvider:"
              ],
              "title": "Creating an activation action"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BF*$objc(cs)UIWindowSceneActivationConfiguration(#*Q$objc(cs)UIWindowSceneActivationAction)",
                    "text": "UIWindowSceneActivationConfiguration *(^)(__kindof UIWindowSceneActivationAction *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIWindowSceneActivationActionConfigurationProvider"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration/title",
          "value": "UIWindowSceneActivationConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction/title",
          "value": "UIWindowSceneActivationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/title",
          "value": "UIWindowScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction~1ConfigurationProvider/title",
          "value": "UIWindowSceneActivationActionConfigurationProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction~1ConfigurationProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationActionConfigurationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationAction~1ConfigurationProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationActionConfigurationProvider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwindowscene/activationaction/configurationprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiwindowscene/activationaction/configurationprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
