{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/magicCookie"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So22CMFormatDescriptionRefa9CoreMediaE12EqualityMaskV11magicCookieAEvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "magicCookie"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
        "text": "CMFormatDescription"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE12EqualityMaskV",
        "text": "EqualityMask"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "magicCookie"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "magicCookie"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
              "text": "CMFormatDescription"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE12EqualityMaskV",
              "text": "EqualityMask"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription": {
      "abstract": [
        {
          "text": "An object that describes a media format descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask": {
      "abstract": [
        {
          "text": "A type that describes format description equality masks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EqualityMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EqualityMask"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.EqualityMask",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/equalitymask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/all": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE12EqualityMaskV",
          "text": "EqualityMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/all",
      "kind": "symbol",
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/equalitymask/all"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/channelLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE12EqualityMaskV",
          "text": "EqualityMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/channelLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "channelLayout",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/equalitymask/channellayout"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/extensions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE12EqualityMaskV",
          "text": "EqualityMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/extensions",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/equalitymask/extensions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/magicCookie": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE12EqualityMaskV",
          "text": "EqualityMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/magicCookie",
      "kind": "symbol",
      "role": "symbol",
      "title": "magicCookie",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/equalitymask/magiccookie"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/streamBasicDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamBasicDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE12EqualityMaskV",
          "text": "EqualityMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/streamBasicDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "streamBasicDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/equalitymask/streambasicdescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Equality-Masks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/all",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/channelLayout",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/extensions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask/streamBasicDescription"
      ],
      "title": "Equality Masks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/title",
          "value": "CMFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmformatdescription/equalitymask/magiccookie"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
