{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/Results-swift.struct",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/Results-swift.struct/Item"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/Results-swift.struct/Item/item"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So13CSSearchQueryC13CoreSpotlightE7ResultsV4ItemV4itemSo012CSSearchableF0Cvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "item"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CSSearchableItem",
        "text": "CSSearchableItem"
      }
    ],
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "item"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "item"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CSSearchableItem",
              "text": "CSSearchableItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery": {
      "abstract": [
        {
          "text": "A type you use to programmatically search the indexed app content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQuery"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQuery"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQuery",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/Results-swift.struct": {
      "abstract": [
        {
          "text": "An asynchronous sequence that contains the results that match the query string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Results"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/Results-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Results"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQuery.Results",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery/results-swift.struct"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/Results-swift.struct/Item": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Item"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/Results-swift.struct/Item",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Item"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQuery.Results.Item",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery/results-swift.struct/item"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/Results-swift.struct/Item/item": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "item"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSSearchableItem",
          "text": "CSSearchableItem"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery/Results-swift.struct/Item/item",
      "kind": "symbol",
      "role": "symbol",
      "title": "item",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery/results-swift.struct/item/item"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem": {
      "abstract": [
        {
          "text": "The details of your app-specific content that someone might search",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "for on their devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableItem"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchableItem"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableItem",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/title",
          "value": "CSSearchQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem/title",
          "value": "CSSearchableItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/cssearchquery/results-swift.struct/item/item"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
