{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/userPreference"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CPInstrumentClusterSetting@CPInstrumentClusterSettingUserPreference",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "userPreference"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPInstrumentClusterSettingUserPreference"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CPInstrumentClusterSetting.userPreference"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "userPreference"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSetting"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSetting"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/disabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSettingDisabled"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting.disabled",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting/disabled"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/enabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/enabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSettingEnabled"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting.enabled",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting/enabled"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSettingUnspecified"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting.unspecified",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting/unspecified"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/userPreference": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userPreference"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/userPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSettingUserPreference"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting.userPreference",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting/userpreference"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/disabled",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/enabled",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/unspecified"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPInstrumentClusterSettingUserPreference"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSettingUserPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/disabled",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/enabled",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/unspecified"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CPInstrumentClusterSettingUserPreference"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1userPreference/title",
          "value": "CPInstrumentClusterSettingUserPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1userPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSettingUserPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1unspecified/title",
          "value": "CPInstrumentClusterSettingUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSettingUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1enabled/title",
          "value": "CPInstrumentClusterSettingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1enabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSettingEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/title",
          "value": "CPInstrumentClusterSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1disabled/title",
          "value": "CPInstrumentClusterSettingDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSettingDisabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpinstrumentclustersetting/userpreference"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpinstrumentclustersetting/userpreference"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
