{
  "abstract": [
    {
      "text": "Passes commands that are not generated as part of the text input process.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController/doCommand(by:command:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IMKInputController(im)doCommandBySelector:commandDictionary:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "doCommand"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "by"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10ObjectiveC8SelectorV",
        "text": "Selector"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "command"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s11AnyHashableV",
        "text": "AnyHashable"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "]!)"
      }
    ],
    "modules": [
      {
        "name": "InputMethodKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "doCommandBySelector:commandDictionary:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "doCommand(by:command:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "doCommand"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "by"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "aSelector"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10ObjectiveC8SelectorV",
              "text": "Selector"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "command"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "infoDictionary"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s11AnyHashableV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s11AnyHashableV",
              "text": "AnyHashable"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "]!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A selector that represents a command from the text input menu.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "aSelector"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A dictionary that contains two key-value pairs:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKCommandMenuItemName",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ", whose value is an ",
                          "type": "text"
                        },
                        {
                          "code": "NSMenuItem",
                          "type": "codeVoice"
                        },
                        {
                          "text": " object. That is, the item selected by the user.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKCommandClientName",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ", whose value is the current client—",
                          "type": "text"
                        },
                        {
                          "code": "id<IMKTextInput, NSObject>",
                          "type": "codeVoice"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                }
              ],
              "type": "unorderedList"
            }
          ],
          "name": "infoDictionary"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default implementation checks if the input controller object (that is, self) responds to the selector. If so, it sends the message ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418764-perform",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to the input controller class. The object parameter in that case is the ",
              "type": "text"
            },
            {
              "code": "infoDictionary",
              "type": "codeVoice"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called when a user selects a command from the text input menu. To support this, an input method must provide actions for each menu item that is placed in the menu. For example, ",
              "type": "text"
            },
            {
              "code": "(void)menuAction:(id)sender",
              "type": "codeVoice"
            },
            {
              "text": ". Note that the sender in this instance is the info dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418764-perform": {
      "abstract": [
        {
          "text": "Sends a message to the receiver with an object as the argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "(Selector!, "
        },
        {
          "kind": "identifier",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": Any!) -> Unmanaged<AnyObject>!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418764-perform",
      "kind": "symbol",
      "role": "symbol",
      "title": "perform(_:with:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol/1418764-perform"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit": {
      "abstract": [
        {
          "text": "Develop input methods and manage communication with client applications, candidates windows, and input method modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
      "kind": "symbol",
      "role": "collection",
      "title": "InputMethodKit",
      "type": "topic",
      "url": "/documentation/inputmethodkit"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IMKInputController",
          "type": "codeVoice"
        },
        {
          "text": " class provides a base class for custom input controller classes. The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKServer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "  class, which is allocated in the main function of an input method, creates an input controller object for each input session created by a client application. For every input session there is a corresponding ",
          "type": "text"
        },
        {
          "code": "IMKInputController",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKInputController"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKInputController"
        }
      ],
      "role": "symbol",
      "title": "IMKInputController",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkinputcontroller"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController/doCommand(by:command:)": {
      "abstract": [
        {
          "text": "Passes commands that are not generated as part of the text input process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doCommand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "by"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "command"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController/doCommand(by:command:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doCommandBySelector:commandDictionary:"
        }
      ],
      "role": "symbol",
      "title": "doCommand(by:command:)",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkinputcontroller/docommand(by:command:)"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController/menu()": {
      "abstract": [
        {
          "text": "Returns a menu of commands that are specific to an input method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController/menu()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menu"
        }
      ],
      "role": "symbol",
      "title": "menu()",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkinputcontroller/menu()"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKServer": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "IMKServer",
          "type": "codeVoice"
        },
        {
          "text": " class manages client connections to your input method.  When you write the main function for your input method, you create an ",
          "type": "text"
        },
        {
          "code": "IMKServer",
          "type": "codeVoice"
        },
        {
          "text": " object.  You should never need to override this class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IMKServer"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKServer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IMKServer"
        }
      ],
      "role": "symbol",
      "title": "IMKServer",
      "type": "topic",
      "url": "/documentation/inputmethodkit/imkserver"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKCommandClientName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIMKCommandClientName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKCommandClientName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIMKCommandClientName"
        }
      ],
      "role": "symbol",
      "title": "kIMKCommandClientName",
      "type": "topic",
      "url": "/documentation/inputmethodkit/kimkcommandclientname"
    },
    "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKCommandMenuItemName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIMKCommandMenuItemName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKCommandMenuItemName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIMKCommandMenuItemName"
        }
      ],
      "role": "symbol",
      "title": "kIMKCommandMenuItemName",
      "type": "topic",
      "url": "/documentation/inputmethodkit/kimkcommandmenuitemname"
    },
    "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Selector"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Selector",
      "type": "topic",
      "url": "/documentation/objectivec/selector"
    },
    "doc://com.externally.resolved.symbol/s:s11AnyHashableV": {
      "abstract": [
        {
          "text": "A type-erased hashable value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnyHashable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s11AnyHashableV",
      "kind": "symbol",
      "role": "symbol",
      "title": "AnyHashable",
      "type": "topic",
      "url": "/documentation/Swift/AnyHashable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Custom-Commands",
      "generated": true,
      "identifiers": [
        "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController/menu()"
      ],
      "title": "Working with Custom Commands"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "doCommandBySelector:commandDictionary:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "doCommandBySelector:commandDictionary:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit",
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Custom-Commands",
              "generated": true,
              "identifiers": [
                "doc://com.apple.inputmethodkit/documentation/InputMethodKit/IMKInputController/menu()"
              ],
              "title": "Working with Custom Commands"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "doCommandBySelector:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SEL",
                    "text": "SEL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "aSelector"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "commandDictionary:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDictionary",
                    "text": "NSDictionary"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "infoDictionary"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A selector that represents a command from the text input menu.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "aSelector"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary that contains two key-value pairs:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKCommandMenuItemName",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ", whose value is an ",
                                "type": "text"
                              },
                              {
                                "code": "NSMenuItem",
                                "type": "codeVoice"
                              },
                              {
                                "text": " object. That is, the item selected by the user.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "identifier": "doc://com.apple.inputmethodkit/documentation/InputMethodKit/kIMKCommandClientName",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ", whose value is the current client—",
                                "type": "text"
                              },
                              {
                                "code": "id<IMKTextInput, NSObject>",
                                "type": "codeVoice"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      }
                    ],
                    "type": "unorderedList"
                  }
                ],
                "name": "infoDictionary"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKInputController/title",
          "value": "IMKInputController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKInputController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKInputController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKInputController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKInputController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKInputController~1doCommand(by:command:)/title",
          "value": "doCommandBySelector:commandDictionary:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKInputController~1doCommand(by:command:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "doCommandBySelector:commandDictionary:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKServer/title",
          "value": "IMKServer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKServer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKServer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IMKServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKCommandMenuItemName/title",
          "value": "kIMKCommandMenuItemName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKCommandMenuItemName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIMKCommandMenuItemName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobjectprotocol~11418764-perform/title",
          "value": "performSelector:withObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKCommandClientName/title",
          "value": "kIMKCommandClientName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1kIMKCommandClientName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIMKCommandClientName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKInputController~1menu()/title",
          "value": "menu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.inputmethodkit~1documentation~1InputMethodKit~1IMKInputController~1menu()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "menu"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/inputmethodkit/imkinputcontroller/docommand(by:command:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/inputmethodkit/imkinputcontroller/docommand(by:command:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
