{
  "abstract": [
    {
      "text": "WPA/WPA2 Enterprise authentication.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterpriseMixed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CWSecurity@kCWSecurityWPAEnterpriseMixed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "wpaEnterpriseMixed"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCWSecurityWPAEnterpriseMixed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CWSecurity.wpaEnterpriseMixed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "wpaEnterpriseMixed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity": {
      "abstract": [
        {
          "text": "CoreWLAN security types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWSecurity"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWSecurity"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/WEP": {
      "abstract": [
        {
          "text": "WEP security.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WEP"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/WEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWEP"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.WEP",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wep"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/dynamicWEP": {
      "abstract": [
        {
          "text": "Dynamic WEP security.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dynamicWEP"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/dynamicWEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityDynamicWEP"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.dynamicWEP",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/dynamicwep"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/enterprise": {
      "abstract": [
        {
          "text": "Enterprise authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enterprise"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/enterprise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityEnterprise"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.enterprise",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/enterprise"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/none": {
      "abstract": [
        {
          "text": "Open System authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityNone"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.none",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/none"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/personal": {
      "abstract": [
        {
          "text": "Personal authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "personal"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/personal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityPersonal"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.personal",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/personal"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/unknown": {
      "abstract": [
        {
          "text": "Unknown security type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityUnknown"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.unknown",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/unknown"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Enterprise": {
      "abstract": [
        {
          "text": "WPA2 Enterprise authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpa2Enterprise"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Enterprise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPA2Enterprise"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpa2Enterprise",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpa2enterprise"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Personal": {
      "abstract": [
        {
          "text": "WPA2 Personal authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpa2Personal"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Personal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPA2Personal"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpa2Personal",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpa2personal"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Enterprise": {
      "abstract": [
        {
          "text": "WPA3 Enterprise authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpa3Enterprise"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Enterprise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPA3Enterprise"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpa3Enterprise",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpa3enterprise"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Personal": {
      "abstract": [
        {
          "text": "WPA3 Personal authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpa3Personal"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Personal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPA3Personal"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpa3Personal",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpa3personal"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Transition": {
      "abstract": [
        {
          "text": "WPA3 Transition (WPA3/WPA2 Personal) authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpa3Transition"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Transition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPA3Transition"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpa3Transition",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpa3transition"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterprise": {
      "abstract": [
        {
          "text": "WPA Enterprise authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpaEnterprise"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterprise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPAEnterprise"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpaEnterprise",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpaenterprise"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterpriseMixed": {
      "abstract": [
        {
          "text": "WPA/WPA2 Enterprise authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpaEnterpriseMixed"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterpriseMixed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPAEnterpriseMixed"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpaEnterpriseMixed",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpaenterprisemixed"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonal": {
      "abstract": [
        {
          "text": "WPA Personal authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpaPersonal"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPAPersonal"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpaPersonal",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpapersonal"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonalMixed": {
      "abstract": [
        {
          "text": "WPA/WPA2 Personal authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wpaPersonalMixed"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonalMixed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWSecurityWPAPersonalMixed"
        }
      ],
      "role": "symbol",
      "title": "CWSecurity.wpaPersonalMixed",
      "type": "topic",
      "url": "/documentation/corewlan/cwsecurity/wpapersonalmixed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/none",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/WEP",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonal",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonalMixed",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Personal",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/personal",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/dynamicWEP",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterprise",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Enterprise",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/enterprise",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Personal",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Enterprise",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Transition",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/unknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCWSecurityWPAEnterpriseMixed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPAEnterpriseMixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/none",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/WEP",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonal",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaPersonalMixed",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Personal",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/personal",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/dynamicWEP",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpaEnterprise",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa2Enterprise",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/enterprise",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Personal",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Enterprise",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/wpa3Transition",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWSecurity/unknown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCWSecurityWPAEnterpriseMixed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Transition/title",
          "value": "kCWSecurityWPA3Transition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Transition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPA3Transition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Enterprise/title",
          "value": "kCWSecurityWPA3Enterprise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Enterprise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPA3Enterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1enterprise/title",
          "value": "kCWSecurityEnterprise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1enterprise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityEnterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaPersonalMixed/title",
          "value": "kCWSecurityWPAPersonalMixed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaPersonalMixed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPAPersonalMixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1personal/title",
          "value": "kCWSecurityPersonal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1personal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityPersonal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/title",
          "value": "CWSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa2Personal/title",
          "value": "kCWSecurityWPA2Personal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa2Personal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPA2Personal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaEnterprise/title",
          "value": "kCWSecurityWPAEnterprise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaEnterprise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPAEnterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1WEP/title",
          "value": "kCWSecurityWEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1WEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaPersonal/title",
          "value": "kCWSecurityWPAPersonal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaPersonal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPAPersonal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1dynamicWEP/title",
          "value": "kCWSecurityDynamicWEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1dynamicWEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityDynamicWEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1none/title",
          "value": "kCWSecurityNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaEnterpriseMixed/title",
          "value": "kCWSecurityWPAEnterpriseMixed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpaEnterpriseMixed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPAEnterpriseMixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1unknown/title",
          "value": "kCWSecurityUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa2Enterprise/title",
          "value": "kCWSecurityWPA2Enterprise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa2Enterprise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPA2Enterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Personal/title",
          "value": "kCWSecurityWPA3Personal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWSecurity~1wpa3Personal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWSecurityWPA3Personal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwsecurity/wpaenterprisemixed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwsecurity/wpaenterprisemixed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
