{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPicker(_:didPickDocumentsAt:)","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/uikit/uidocumentpickerdelegate/documentpicker(_:didpickdocumentsat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uidocumentpickerdelegate/documentpicker(_:didpickdocumentsat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPicker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPickDocumentsAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"urls"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The document picker that called this method.","type":"text"}],"type":"paragraph"}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URLs of the selected documents."}]}],"name":"urls"}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/providing-access-to-directories"]},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The meaning of the provided URLs varies depending on the document picker’s mode:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"UIDocumentPickerModeImport","type":"codeVoice"}]}]}]},{"inlineContent":[{"type":"text","text":"The URLs refer to a copy of the selected documents. These documents are temporary files. They remain available only until your application terminates. To keep a permanent copy, move these files to a permanent location inside your sandbox."}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"UIDocumentPickerModeOpen","type":"codeVoice"}]}]}]},{"inlineContent":[{"type":"text","text":"The URLs refer to the selected documents."}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"UIDocumentPickerModeExportToService"}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"text","text":"The URLs refer to new copies of the exported documents at the selected destination."}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"UIDocumentPickerModeMoveToService"}],"type":"paragraph"}]}]},{"inlineContent":[{"text":"The URLs refer to the documents’ new locations.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The provided URLs are security-scoped, referring to files outside your app’s sandbox. For more about working with external, security-scoped URLs, see "},{"type":"reference","identifier":"https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentPickerProgrammingGuide/AccessingDocuments/AccessingDocuments.html#//apple_ref/doc/uid/TP40014451-CH2-SW3","isActive":true},{"type":"text","text":" in the "},{"type":"reference","identifier":"https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentPickerProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40014451","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"metadata":{"externalID":"c:objc(pl)UIDocumentPickerDelegate(im)documentPicker:didPickDocumentsAtURLs:","symbolKind":"method","platforms":[{"introducedAt":"11.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"11.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"introducedAt":"13.1","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"}],"modules":[{"name":"UIKit"}],"roleHeading":"Instance Method","title":"documentPicker(_:didPickDocumentsAt:)","navigatorTitle":[{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDocumentPickerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController"},{"text":", ","kind":"text"},{"text":"didPickDocumentsAt","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"])","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Tells the delegate that the user has selected one or more documents."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPickerWasCancelled(_:)","doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPicker(_:didPickDocumentAt:)"],"generated":true,"anchor":"Responding-to-user-actions","title":"Responding to user actions"}],"kind":"symbol","references":{"https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentPickerProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40014451":{"title":"Document Picker Programming Guide","url":"https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentPickerProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40014451","titleInlineContent":[{"type":"text","text":"Document Picker Programming Guide"}],"identifier":"https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentPickerProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40014451","type":"link"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPicker(_:didPickDocumentAt:)":{"title":"documentPicker(_:didPickDocumentAt:)","abstract":[{"text":"Tells the delegate that the user has selected a document or a destination.","type":"text"}],"type":"topic","url":"/documentation/uikit/uidocumentpickerdelegate/documentpicker(_:didpickdocumentat:)","kind":"symbol","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"documentPicker:didPickDocumentAtURL:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPicker","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didPickDocumentAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPicker(_:didPickDocumentAt:)"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/providing-access-to-directories":{"url":"/documentation/uikit/providing-access-to-directories","abstract":[{"text":"Use a document picker to access the content of a directory outside your app’s container.","type":"text"}],"type":"topic","kind":"article","role":"article","identifier":"doc://com.apple.uikit/documentation/UIKit/providing-access-to-directories","title":"Providing access to directories"},"https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentPickerProgrammingGuide/AccessingDocuments/AccessingDocuments.html#//apple_ref/doc/uid/TP40014451-CH2-SW3":{"title":"Requirements","url":"https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentPickerProgrammingGuide/AccessingDocuments/AccessingDocuments.html#//apple_ref/doc/uid/TP40014451-CH2-SW3","titleInlineContent":[{"type":"text","text":"Requirements"}],"identifier":"https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentPickerProgrammingGuide/AccessingDocuments/AccessingDocuments.html#//apple_ref/doc/uid/TP40014451-CH2-SW3","type":"link"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController":{"navigatorTitle":[{"kind":"identifier","text":"UIDocumentPickerViewController"}],"url":"/documentation/uikit/uidocumentpickerviewcontroller","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIDocumentPickerViewController"}],"kind":"symbol","abstract":[{"type":"text","text":"A view controller that provides access to documents or destinations outside your app’s sandbox."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController","title":"UIDocumentPickerViewController","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPickerWasCancelled(_:)":{"title":"documentPickerWasCancelled(_:)","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPickerWasCancelled(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPickerWasCancelled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the user canceled the document picker."}],"url":"/documentation/uikit/uidocumentpickerdelegate/documentpickerwascancelled(_:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentPickerWasCancelled:"}]},"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate":{"title":"UIDocumentPickerDelegate","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate","abstract":[{"type":"text","text":"A set of methods for tracking when the user selects a document or destination, or cancels the operation."}],"type":"topic","navigatorTitle":[{"text":"UIDocumentPickerDelegate","kind":"identifier"}],"url":"/documentation/uikit/uidocumentpickerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDocumentPickerDelegate","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPicker(_:didPickDocumentsAt:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPicker"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPickDocumentsAt"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"type":"topic","title":"documentPicker(_:didPickDocumentsAt:)","abstract":[{"type":"text","text":"Tells the delegate that the user has selected one or more documents."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPicker(_:didPickDocumentsAt:)","url":"/documentation/uikit/uidocumentpickerdelegate/documentpicker(_:didpickdocumentsat:)"},"doc://com.externally.resolved.symbol/s:10Foundation3URLV":{"title":"URL","type":"topic","fragments":[{"text":"struct ","kind":"text"},{"text":"URL","kind":"identifier"}],"abstract":[{"text":"A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","url":"/documentation/foundation/url","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false,"introducedAt":"11.0"},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"11.0"},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1"},{"deprecated":false,"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"documentPicker:didPickDocumentsAtURLs:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentPicker:didPickDocumentsAtURLs:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Responding to user actions","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPickerWasCancelled(_:)","doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerDelegate/documentPicker(_:didPickDocumentAt:)"],"generated":true,"anchor":"Responding-to-user-actions"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentPicker:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPickDocumentsAtURLs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSURL *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"urls"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The document picker that called this method."}],"type":"paragraph"}]},{"name":"urls","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URLs of the selected documents."}]}]}]}},{"op":"replace","value":"documentPicker:didPickDocumentAtURL:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerDelegate~1documentPicker(_:didPickDocumentAt:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentPicker:didPickDocumentAtURL:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerDelegate~1documentPicker(_:didPickDocumentAt:)/fragments"},{"op":"replace","value":"UIDocumentPickerViewController","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIDocumentPickerViewController"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIDocumentPickerViewController"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController/navigatorTitle"},{"op":"replace","value":"documentPickerWasCancelled:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerDelegate~1documentPickerWasCancelled(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentPickerWasCancelled:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerDelegate~1documentPickerWasCancelled(_:)/fragments"},{"op":"replace","value":"UIDocumentPickerDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerDelegate/title"},{"op":"replace","value":[{"text":"UIDocumentPickerDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerDelegate/fragments"},{"op":"replace","value":[{"text":"UIDocumentPickerDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerDelegate/navigatorTitle"},{"op":"replace","value":"documentPicker:didPickDocumentsAtURLs:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerDelegate~1documentPicker(_:didPickDocumentsAt:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerDelegate~1documentPicker(_:didPickDocumentsAt:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}