{
  "abstract": [
    {
      "text": "A set of reasons for pausing a trip.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CarPlay",
    "externalID": "c:@E@CPTripPauseReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PauseReason"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PauseReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CPNavigationSession.PauseReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PauseReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession": {
      "abstract": [
        {
          "text": "An object that represents an active route guidance session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNavigationSession"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNavigationSession"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationSession",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason": {
      "abstract": [
        {
          "text": "A set of reasons for pausing a trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PauseReason"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PauseReason"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationSession.PauseReason",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausereason"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/arrived": {
      "abstract": [
        {
          "text": "The user arrived at the destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrived"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/arrived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTripPauseReasonArrived"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationSession.PauseReason.arrived",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausereason/arrived"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausereason/init(rawvalue:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/loading": {
      "abstract": [
        {
          "text": "The system is loading the route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loading"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/loading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTripPauseReasonLoading"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationSession.PauseReason.loading",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausereason/loading"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/locating": {
      "abstract": [
        {
          "text": "The system is locating the destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locating"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/locating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTripPauseReasonLocating"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationSession.PauseReason.locating",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausereason/locating"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/proceedToRoute": {
      "abstract": [
        {
          "text": "The system is waiting for the user to proceed to the route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proceedToRoute"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/proceedToRoute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTripPauseReasonProceedToRoute"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationSession.PauseReason.proceedToRoute",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausereason/proceedtoroute"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/rerouting": {
      "abstract": [
        {
          "text": "The system is rerouting the trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rerouting"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/rerouting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTripPauseReasonRerouting"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationSession.PauseReason.rerouting",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausereason/rerouting"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/cancelTrip()": {
      "abstract": [
        {
          "text": "Tells the navigation session to cancel the trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelTrip"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/cancelTrip()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelTrip"
        }
      ],
      "role": "symbol",
      "title": "cancelTrip()",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/canceltrip()"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/finishTrip()": {
      "abstract": [
        {
          "text": "Tells the navigation session to finish the trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishTrip"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/finishTrip()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishTrip"
        }
      ],
      "role": "symbol",
      "title": "finishTrip()",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/finishtrip()"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:)": {
      "abstract": [
        {
          "text": "Tells the navigation session to pause the trip for the specified reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseTrip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationSession",
          "text": "CPNavigationSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPTripPauseReason",
          "text": "PauseReason"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "description"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseTripForReason:description:"
        }
      ],
      "role": "symbol",
      "title": "pauseTrip(for:description:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausetrip(for:description:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:turnCardColor:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseTrip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationSession",
          "text": "CPNavigationSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPTripPauseReason",
          "text": "PauseReason"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "description"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "turnCardColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:turnCardColor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseTripForReason:description:turnCardColor:"
        }
      ],
      "role": "symbol",
      "title": "pauseTrip(for:description:turnCardColor:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausetrip(for:description:turncardcolor:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/resumeTrip(updatedRouteInformation:)": {
      "abstract": [
        {
          "text": "Resumes the current trip with updated route information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumeTrip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "updatedRouteInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPRouteInformation",
          "text": "CPRouteInformation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/resumeTrip(updatedRouteInformation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resumeTripWithUpdatedRouteInformation:"
        }
      ],
      "role": "symbol",
      "title": "resumeTrip(updatedRouteInformation:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/resumetrip(updatedrouteinformation:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Trip-Navigation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/cancelTrip()",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/finishTrip()",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:turnCardColor:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/resumeTrip(updatedRouteInformation:)"
      ],
      "title": "Managing Trip Navigation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reasons",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/arrived",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/loading",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/locating",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/proceedToRoute",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/rerouting"
      ],
      "title": "Reasons"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPTripPauseReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reasons",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/arrived",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/loading",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/locating",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/proceedToRoute",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason/rerouting"
              ],
              "title": "Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Trip-Navigation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/cancelTrip()",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/finishTrip()",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:turnCardColor:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/resumeTrip(updatedRouteInformation:)"
              ],
              "title": "Managing Trip Navigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPTripPauseReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason/title",
          "value": "CPTripPauseReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1resumeTrip(updatedRouteInformation:)/title",
          "value": "resumeTripWithUpdatedRouteInformation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1resumeTrip(updatedRouteInformation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resumeTripWithUpdatedRouteInformation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason~1locating/title",
          "value": "CPTripPauseReasonLocating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason~1locating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReasonLocating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession/title",
          "value": "CPNavigationSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason~1arrived/title",
          "value": "CPTripPauseReasonArrived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason~1arrived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReasonArrived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1finishTrip()/title",
          "value": "finishTrip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1finishTrip()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishTrip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason~1proceedToRoute/title",
          "value": "CPTripPauseReasonProceedToRoute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason~1proceedToRoute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReasonProceedToRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason~1rerouting/title",
          "value": "CPTripPauseReasonRerouting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason~1rerouting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReasonRerouting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1pauseTrip(for:description:turnCardColor:)/title",
          "value": "pauseTripForReason:description:turnCardColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1pauseTrip(for:description:turnCardColor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pauseTripForReason:description:turnCardColor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1pauseTrip(for:description:)/title",
          "value": "pauseTripForReason:description:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1pauseTrip(for:description:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pauseTripForReason:description:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason~1loading/title",
          "value": "CPTripPauseReasonLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason~1loading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReasonLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1cancelTrip()/title",
          "value": "cancelTrip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1cancelTrip()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelTrip"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpnavigationsession/pausereason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpnavigationsession/pausereason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
