{
  "abstract": [
    {
      "text": "Resumes the current trip with updated route information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/resumeTrip(updatedRouteInformation:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPNavigationSession(im)resumeTripWithUpdatedRouteInformation:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resumeTrip"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "updatedRouteInformation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPRouteInformation",
        "text": "CPRouteInformation"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "resumeTripWithUpdatedRouteInformation:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "resumeTrip(updatedRouteInformation:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resumeTrip"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "updatedRouteInformation"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "routeInformation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPRouteInformation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPRouteInformation",
              "text": "CPRouteInformation"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The updated route information for the current trip.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "routeInformation"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession": {
      "abstract": [
        {
          "text": "An object that represents an active route guidance session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNavigationSession"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNavigationSession"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationSession",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason": {
      "abstract": [
        {
          "text": "A set of reasons for pausing a trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PauseReason"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PauseReason"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationSession.PauseReason",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausereason"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/cancelTrip()": {
      "abstract": [
        {
          "text": "Tells the navigation session to cancel the trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelTrip"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/cancelTrip()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelTrip"
        }
      ],
      "role": "symbol",
      "title": "cancelTrip()",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/canceltrip()"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/finishTrip()": {
      "abstract": [
        {
          "text": "Tells the navigation session to finish the trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishTrip"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/finishTrip()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishTrip"
        }
      ],
      "role": "symbol",
      "title": "finishTrip()",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/finishtrip()"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:)": {
      "abstract": [
        {
          "text": "Tells the navigation session to pause the trip for the specified reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseTrip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationSession",
          "text": "CPNavigationSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPTripPauseReason",
          "text": "PauseReason"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "description"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseTripForReason:description:"
        }
      ],
      "role": "symbol",
      "title": "pauseTrip(for:description:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausetrip(for:description:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:turnCardColor:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseTrip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationSession",
          "text": "CPNavigationSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPTripPauseReason",
          "text": "PauseReason"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "description"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "turnCardColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:turnCardColor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseTripForReason:description:turnCardColor:"
        }
      ],
      "role": "symbol",
      "title": "pauseTrip(for:description:turnCardColor:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/pausetrip(for:description:turncardcolor:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/resumeTrip(updatedRouteInformation:)": {
      "abstract": [
        {
          "text": "Resumes the current trip with updated route information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumeTrip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "updatedRouteInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPRouteInformation",
          "text": "CPRouteInformation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/resumeTrip(updatedRouteInformation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resumeTripWithUpdatedRouteInformation:"
        }
      ],
      "role": "symbol",
      "title": "resumeTrip(updatedRouteInformation:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationsession/resumetrip(updatedrouteinformation:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPRouteInformation": {
      "abstract": [
        {
          "text": "A class that describes the characteristic elements of a route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPRouteInformation"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPRouteInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPRouteInformation"
        }
      ],
      "role": "symbol",
      "title": "CPRouteInformation",
      "type": "topic",
      "url": "/documentation/carplay/cprouteinformation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Trip-Navigation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/cancelTrip()",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/finishTrip()",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:turnCardColor:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason"
      ],
      "title": "Managing Trip Navigation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "resumeTripWithUpdatedRouteInformation:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resumeTripWithUpdatedRouteInformation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Trip-Navigation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/cancelTrip()",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/finishTrip()",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/pauseTrip(for:description:turnCardColor:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationSession/PauseReason"
              ],
              "title": "Managing Trip Navigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "resumeTripWithUpdatedRouteInformation:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPRouteInformation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPRouteInformation",
                    "text": "CPRouteInformation"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "routeInformation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The updated route information for the current trip.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "routeInformation"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1pauseTrip(for:description:)/title",
          "value": "pauseTripForReason:description:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1pauseTrip(for:description:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pauseTripForReason:description:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1resumeTrip(updatedRouteInformation:)/title",
          "value": "resumeTripWithUpdatedRouteInformation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1resumeTrip(updatedRouteInformation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resumeTripWithUpdatedRouteInformation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1finishTrip()/title",
          "value": "finishTrip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1finishTrip()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishTrip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason/title",
          "value": "CPTripPauseReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1PauseReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTripPauseReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession/title",
          "value": "CPNavigationSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1cancelTrip()/title",
          "value": "cancelTrip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1cancelTrip()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelTrip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPRouteInformation/title",
          "value": "CPRouteInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPRouteInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPRouteInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPRouteInformation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPRouteInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1pauseTrip(for:description:turnCardColor:)/title",
          "value": "pauseTripForReason:description:turnCardColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationSession~1pauseTrip(for:description:turnCardColor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pauseTripForReason:description:turnCardColor:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpnavigationsession/resumetrip(updatedrouteinformation:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpnavigationsession/resumetrip(updatedrouteinformation:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
