{
  "abstract": [
    {
      "text": "An error that occurs while processing the permission request.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported. Please see Sharing CloudKit Data with Other iCloud Users.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/couldNotComplete"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CKApplicationPermissionStatus@CKApplicationPermissionStatusCouldNotComplete",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "couldNotComplete"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKApplicationPermissionStatusCouldNotComplete"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "8.0",
        "message": "No longer supported. Please see Sharing CloudKit Data with Other iCloud Users.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "8.0",
        "message": "No longer supported. Please see Sharing CloudKit Data with Other iCloud Users.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "13.1",
        "message": "No longer supported. Please see Sharing CloudKit Data with Other iCloud Users.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "10.10",
        "message": "No longer supported. Please see Sharing CloudKit Data with Other iCloud Users.",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "9.0",
        "message": "No longer supported. Please see Sharing CloudKit Data with Other iCloud Users.",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "No longer supported. Please see Sharing CloudKit Data with Other iCloud Users.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "3.0",
        "message": "No longer supported. Please see Sharing CloudKit Data with Other iCloud Users.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CKContainer.ApplicationPermissionStatus.couldNotComplete"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "couldNotComplete"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer": {
      "abstract": [
        {
          "text": "A conduit to your app’s databases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "role": "symbol",
      "title": "CKContainer",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus": {
      "abstract": [
        {
          "text": "Constants that represent the status of a permission.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ApplicationPermissionStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ApplicationPermissionStatus"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.ApplicationPermissionStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/applicationpermissionstatus"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/couldNotComplete": {
      "abstract": [
        {
          "text": "An error that occurs while processing the permission request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couldNotComplete"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/couldNotComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKApplicationPermissionStatusCouldNotComplete"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.ApplicationPermissionStatus.couldNotComplete",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/applicationpermissionstatus/couldnotcomplete"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/denied": {
      "abstract": [
        {
          "text": "The user denies the permission.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKApplicationPermissionStatusDenied"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.ApplicationPermissionStatus.denied",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/applicationpermissionstatus/denied"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/granted": {
      "abstract": [
        {
          "text": "The user grants the permission.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "granted"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/granted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKApplicationPermissionStatusGranted"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.ApplicationPermissionStatus.granted",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/applicationpermissionstatus/granted"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/initialState": {
      "abstract": [
        {
          "text": "The app is yet to request the permission.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialState"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/initialState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKApplicationPermissionStatusInitialState"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.ApplicationPermissionStatus.initialState",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/applicationpermissionstatus/initialstate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Permission-Statuses",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/initialState",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/denied",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/granted"
      ],
      "title": "Permission Statuses"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKApplicationPermissionStatusCouldNotComplete"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissionStatusCouldNotComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Permission-Statuses",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/initialState",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/denied",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus/granted"
              ],
              "title": "Permission Statuses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CKApplicationPermissionStatusCouldNotComplete"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported. Please see Sharing CloudKit Data with Other iCloud Users.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus/title",
          "value": "CKApplicationPermissionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus~1initialState/title",
          "value": "CKApplicationPermissionStatusInitialState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus~1initialState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissionStatusInitialState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus~1couldNotComplete/title",
          "value": "CKApplicationPermissionStatusCouldNotComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus~1couldNotComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissionStatusCouldNotComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus~1denied/title",
          "value": "CKApplicationPermissionStatusDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissionStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus~1granted/title",
          "value": "CKApplicationPermissionStatusGranted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus~1granted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissionStatusGranted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/title",
          "value": "CKContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckcontainer/applicationpermissionstatus/couldnotcomplete"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckcontainer/applicationpermissionstatus/couldnotcomplete"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
