{
  "abstract": [
    {
      "text": "The lower-left corner of the screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/bottomLeading"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKAccessPointLocation@GKAccessPointLocationBottomLeading",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bottomLeading"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKAccessPointLocationBottomLeading"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GKAccessPoint.Location.bottomLeading"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bottomLeading"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint": {
      "abstract": [
        {
          "text": "An object that allows players to view and manage their Game Center information from within your game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAccessPoint"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAccessPoint"
        }
      ],
      "role": "symbol",
      "title": "GKAccessPoint",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum": {
      "abstract": [
        {
          "text": "Specifies the corner of the screen to display the access point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Location"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Location"
        }
      ],
      "role": "symbol",
      "title": "GKAccessPoint.Location",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/location-swift.enum"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/bottomLeading": {
      "abstract": [
        {
          "text": "The lower-left corner of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeading"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/bottomLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAccessPointLocationBottomLeading"
        }
      ],
      "role": "symbol",
      "title": "GKAccessPoint.Location.bottomLeading",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/location-swift.enum/bottomleading"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/bottomTrailing": {
      "abstract": [
        {
          "text": "The lower-right corner of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomTrailing"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/bottomTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAccessPointLocationBottomTrailing"
        }
      ],
      "role": "symbol",
      "title": "GKAccessPoint.Location.bottomTrailing",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/location-swift.enum/bottomtrailing"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/topLeading": {
      "abstract": [
        {
          "text": "The upper-left corner of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeading"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/topLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAccessPointLocationTopLeading"
        }
      ],
      "role": "symbol",
      "title": "GKAccessPoint.Location.topLeading",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/location-swift.enum/topleading"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/topTrailing": {
      "abstract": [
        {
          "text": "The upper-right corner of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topTrailing"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/topTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAccessPointLocationTopTrailing"
        }
      ],
      "role": "symbol",
      "title": "GKAccessPoint.Location.topTrailing",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/location-swift.enum/toptrailing"
    },
    "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game": {
      "abstract": [
        {
          "text": "Provide your users a convenient connection to the Game Center dashboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game",
      "kind": "article",
      "role": "article",
      "title": "Adding an access point to your game",
      "type": "topic",
      "url": "/documentation/gamekit/adding-an-access-point-to-your-game"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Corners",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/bottomTrailing",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/topLeading",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/topTrailing"
      ],
      "title": "Corners"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKAccessPointLocationBottomLeading"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPointLocationBottomLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Corners",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/bottomTrailing",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/topLeading",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum/topTrailing"
              ],
              "title": "Corners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GKAccessPointLocationBottomLeading"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum~1topTrailing/title",
          "value": "GKAccessPointLocationTopTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum~1topTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPointLocationTopTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum~1bottomLeading/title",
          "value": "GKAccessPointLocationBottomLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum~1bottomLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPointLocationBottomLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum~1topLeading/title",
          "value": "GKAccessPointLocationTopLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum~1topLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPointLocationTopLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum/title",
          "value": "GKAccessPointLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPointLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPointLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint/title",
          "value": "GKAccessPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum~1bottomTrailing/title",
          "value": "GKAccessPointLocationBottomTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum~1bottomTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPointLocationBottomTrailing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkaccesspoint/location-swift.enum/bottomleading"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkaccesspoint/location-swift.enum/bottomleading"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
