{
  "abstract": [
    {
      "text": "A name identifier for a joint.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ARKit",
    "externalID": "c:@T@ARSkeletonJointName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JointName"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JointName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "ARSkeleton.JointName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JointName"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this class to access information about a named joint, such as its index in a skeleton’s array of joints, or its position on the screen or in the physical environment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you’re tracking a body in 2D space, you get the screen-space position of a named joint by using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/landmark(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you’re tracking a body in 3D space, you get a named joint’s position in either local or model space by using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton3D/localTransform(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton3D/modelTransform(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions, respectively.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton": {
      "abstract": [
        {
          "text": "The interface for the skeleton of a tracked body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSkeleton"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeleton"
        }
      ],
      "role": "symbol",
      "title": "ARSkeleton",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName": {
      "abstract": [
        {
          "text": "A name identifier for a joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "role": "symbol",
      "title": "ARSkeleton.JointName",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/head": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the head.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "head"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/head",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameHead"
        }
      ],
      "role": "symbol",
      "title": "head",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/head"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(_:)": {
      "abstract": [
        {
          "text": "Returns a joint name that corresponds to a key point defined in a human body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameForRecognizedPointKey"
        }
      ],
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/init(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new joint name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/init(rawvalue:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftFoot": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the left foot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftFoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftFoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameLeftFoot"
        }
      ],
      "role": "symbol",
      "title": "leftFoot",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/leftfoot"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftHand": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the left hand.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftHand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameLeftHand"
        }
      ],
      "role": "symbol",
      "title": "leftHand",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/lefthand"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftShoulder": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the left shoulder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftShoulder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameLeftShoulder"
        }
      ],
      "role": "symbol",
      "title": "leftShoulder",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/leftshoulder"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightFoot": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the right foot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightFoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightFoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameRightFoot"
        }
      ],
      "role": "symbol",
      "title": "rightFoot",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/rightfoot"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightHand": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the right hand.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightHand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameRightHand"
        }
      ],
      "role": "symbol",
      "title": "rightHand",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/righthand"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightShoulder": {
      "abstract": [
        {
          "text": "A skeletal joint that ARKit tracks representing the right shoulder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightShoulder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameRightShoulder"
        }
      ],
      "role": "symbol",
      "title": "rightShoulder",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/rightshoulder"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/root": {
      "abstract": [
        {
          "text": "A skeletal joint that’s the root of all other joints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "root"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/root",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonJointNameRoot"
        }
      ],
      "role": "symbol",
      "title": "root",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointname/root"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/definition": {
      "abstract": [
        {
          "text": "The particular configuration of joints that define a body’s current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "definition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeletonDefinition",
          "text": "ARSkeletonDefinition"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/definition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "definition"
        }
      ],
      "role": "symbol",
      "title": "definition",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/definition"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/isJointTracked(_:)": {
      "abstract": [
        {
          "text": "Tells you whether ARKit tracks a joint at a particular index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isJointTracked"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/isJointTracked(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isJointTracked:"
        }
      ],
      "role": "symbol",
      "title": "isJointTracked(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/isjointtracked(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/jointCount": {
      "abstract": [
        {
          "text": "The skeleton’s total number of joints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "jointCount"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/jointCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "jointCount",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton/jointcount"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/landmark(for:)": {
      "abstract": [
        {
          "text": "Returns the location of a joint with a given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landmark"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/landmark(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "landmark(for:)",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton2d/landmark(for:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton3D/localTransform(for:)": {
      "abstract": [
        {
          "text": "Returns the local transform for a joint with a given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localTransform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton3D/localTransform(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "localTransform(for:)",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton3d/localtransform(for:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton3D/modelTransform(for:)": {
      "abstract": [
        {
          "text": "Returns the model transform for a joint with a given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelTransform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton3D/modelTransform(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "modelTransform(for:)",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton3d/modeltransform(for:)"
    },
    "doc://com.apple.documentation/documentation/Vision/VNRecognizedPointKey": {
      "abstract": [
        {
          "text": "The data type for all recognized point keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Vision/VNRecognizedPointKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "VNRecognizedPointKey",
      "type": "topic",
      "url": "/documentation/Vision/VNRecognizedPointKey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Joint-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/definition",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/isJointTracked(_:)"
      ],
      "title": "Getting Joint Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Joint-Name",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(rawValue:)",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(_:)",
        "doc://com.apple.documentation/documentation/Vision/VNRecognizedPointKey"
      ],
      "title": "Creating a Joint Name"
    },
    {
      "anchor": "Identifying-Joints",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/root",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/head",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftFoot",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftHand",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftShoulder",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightFoot",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightHand",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightShoulder"
      ],
      "title": "Identifying Joints"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARSkeletonJointName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Joint-Name",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/init(_:)",
                "doc://com.apple.documentation/documentation/Vision/VNRecognizedPointKey"
              ],
              "title": "Creating a Joint Name"
            },
            {
              "anchor": "Identifying-Joints",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/root",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/head",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftFoot",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftHand",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/leftShoulder",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightFoot",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightHand",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/JointName/rightShoulder"
              ],
              "title": "Identifying Joints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Joint-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/definition",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/jointCount",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton/isJointTracked(_:)"
              ],
              "title": "Getting Joint Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARSkeletonJointName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftShoulder/title",
          "value": "ARSkeletonJointNameLeftShoulder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftShoulder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameLeftShoulder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Vision~1VNRecognizedPointKey/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightShoulder/title",
          "value": "ARSkeletonJointNameRightShoulder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightShoulder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameRightShoulder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName/title",
          "value": "ARSkeletonJointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1head/title",
          "value": "ARSkeletonJointNameHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1head/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftHand/title",
          "value": "ARSkeletonJointNameLeftHand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftHand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameLeftHand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightFoot/title",
          "value": "ARSkeletonJointNameRightFoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightFoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameRightFoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1definition/title",
          "value": "definition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1definition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/title",
          "value": "ARSkeleton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1root/title",
          "value": "ARSkeletonJointNameRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1root/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightHand/title",
          "value": "ARSkeletonJointNameRightHand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1rightHand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameRightHand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1isJointTracked(_:)/title",
          "value": "isJointTracked:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1isJointTracked(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isJointTracked:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1init(_:)/title",
          "value": "ARSkeletonJointNameForRecognizedPointKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1init(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameForRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftFoot/title",
          "value": "ARSkeletonJointNameLeftFoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton~1JointName~1leftFoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonJointNameLeftFoot"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arskeleton/jointname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arskeleton/jointname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
