{
  "abstract": [
    {
      "text": "The error code that the parent class issues.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AdServices/documentation/AdServices",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AAAttributionErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "AdServices"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.1",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AAAttributionError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.AdServices/documentation/AdServices": {
      "abstract": [
        {
          "text": "Attribute app-download campaigns that originate from the App Store, Apple News, or",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Stocks on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices",
      "kind": "symbol",
      "role": "collection",
      "title": "AdServices",
      "type": "topic",
      "url": "/documentation/adservices"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError": {
      "abstract": [
        {
          "text": "The error code that the parent class issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAAttributionError"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionError"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code": {
      "abstract": [
        {
          "text": "The error code that the parent class issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError.Code",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/code"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates an error code structure with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/code/init(rawvalue:)"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/internalError": {
      "abstract": [
        {
          "text": "The server is unable to provide a token because of an internal error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionErrorCodeInternalError"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError.Code.internalError",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/code/internalerror"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/networkError": {
      "abstract": [
        {
          "text": "The server is unable to provide a token because the internet isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkError"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/networkError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionErrorCodeNetworkError"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError.Code.networkError",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/code/networkerror"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/platformNotSupported": {
      "abstract": [
        {
          "text": "The server is unable to provide a token because of an unsupported operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "platformNotSupported"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/platformNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionErrorCodePlatformNotSupported"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError.Code.platformNotSupported",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/code/platformnotsupported"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionErrorDomain": {
      "abstract": [
        {
          "text": "The framework attribution error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAAttributionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionErrorDomain",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-error-code",
      "identifiers": [
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/init(rawValue:)"
      ],
      "title": "Creating an error code"
    },
    {
      "anchor": "Determining-the-cause-of-an-error",
      "identifiers": [
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/internalError",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/networkError",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/platformNotSupported"
      ],
      "title": "Determining the cause of an error"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.3",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.1",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AAAttributionErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.AdServices/documentation/AdServices"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-the-cause-of-an-error",
              "identifiers": [
                "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/internalError",
                "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/networkError",
                "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/platformNotSupported"
              ],
              "title": "Determining the cause of an error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.AdServices/documentation/AdServices/AAAttributionErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AAAttributionErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code/title",
          "value": "AAAttributionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1internalError/title",
          "value": "AAAttributionErrorCodeInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCodeInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionErrorDomain/title",
          "value": "AAAttributionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1platformNotSupported/title",
          "value": "AAAttributionErrorCodePlatformNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1platformNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCodePlatformNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1networkError/title",
          "value": "AAAttributionErrorCodeNetworkError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1networkError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCodeNetworkError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/adservices/aaattributionerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/adservices/aaattributionerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
