{
  "abstract": [
    {
      "text": "A type indicating that the payload contains well-known NFC record type data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcWellKnown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NFCTypeNameFormat@NFCTypeNameFormatNFCWellKnown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nfcWellKnown"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCTypeNameFormatNFCWellKnown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NFCTypeNameFormat.nfcWellKnown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nfcWellKnown"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.corenfc/documentation/CoreNFC/adding-support-for-background-tag-reading"
      ]
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat": {
      "abstract": [
        {
          "text": "The Type Name Format values that specify the content type for the payload data in an NFC NDEF message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormat"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormat"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/absoluteURI": {
      "abstract": [
        {
          "text": "A type indicating that the payload contains a uniform resource identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "absoluteURI"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/absoluteURI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatAbsoluteURI"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.absoluteURI",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/absoluteuri"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/empty": {
      "abstract": [
        {
          "text": "A type indicating that the payload contains no data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "empty"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/empty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatEmpty"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.empty",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/empty"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/media": {
      "abstract": [
        {
          "text": "A type indicating that the payload contains media data as defined by RFC 2046.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "media"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/media",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatMedia"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.media",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/media"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcExternal": {
      "abstract": [
        {
          "text": "A type indicating that the payload contains NFC external type data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nfcExternal"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcExternal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatNFCExternal"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.nfcExternal",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/nfcexternal"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcWellKnown": {
      "abstract": [
        {
          "text": "A type indicating that the payload contains well-known NFC record type data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nfcWellKnown"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcWellKnown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatNFCWellKnown"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.nfcWellKnown",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/nfcwellknown"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unchanged": {
      "abstract": [
        {
          "text": "A type indicating that the payload is part of a series of records containing chunked data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unchanged"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unchanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatUnchanged"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.unchanged",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/unchanged"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unknown": {
      "abstract": [
        {
          "text": "A type indicating that the payload data type is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatUnknown"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.unknown",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/unknown"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/adding-support-for-background-tag-reading": {
      "abstract": [
        {
          "text": "Allow users to scan NFC tags without an app using background tag reading.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/adding-support-for-background-tag-reading",
      "kind": "article",
      "role": "article",
      "title": "Adding Support for Background Tag Reading",
      "type": "topic",
      "url": "/documentation/corenfc/adding-support-for-background-tag-reading"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/absoluteURI",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/empty",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/media",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcExternal",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unchanged",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unknown"
      ],
      "title": "Content Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCTypeNameFormatNFCWellKnown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatNFCWellKnown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Content-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/absoluteURI",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/empty",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/media",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcExternal",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unchanged",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unknown"
              ],
              "title": "Content Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NFCTypeNameFormatNFCWellKnown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1absoluteURI/title",
          "value": "NFCTypeNameFormatAbsoluteURI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1absoluteURI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatAbsoluteURI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1empty/title",
          "value": "NFCTypeNameFormatEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1empty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1unchanged/title",
          "value": "NFCTypeNameFormatUnchanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1unchanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatUnchanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1nfcExternal/title",
          "value": "NFCTypeNameFormatNFCExternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1nfcExternal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatNFCExternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1media/title",
          "value": "NFCTypeNameFormatMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1media/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatMedia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat/title",
          "value": "NFCTypeNameFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1nfcWellKnown/title",
          "value": "NFCTypeNameFormatNFCWellKnown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1nfcWellKnown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatNFCWellKnown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1unknown/title",
          "value": "NFCTypeNameFormatUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfctypenameformat/nfcwellknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfctypenameformat/nfcwellknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
