{
  "abstract": [
    {
      "text": "Creates a  renderer object  with a composition object and a color space.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/QCRenderer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(composition:colorSpace:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)QCRenderer(im)initWithComposition:colorSpace:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "!("
      },
      {
        "kind": "externalParam",
        "text": "composition"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)QCComposition",
        "text": "QCComposition"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "colorSpace"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CGColorSpaceRef",
        "text": "CGColorSpace"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithComposition:colorSpace:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.4",
        "message": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(composition:colorSpace:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "!("
            },
            {
              "kind": "externalParam",
              "text": "composition"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)QCComposition",
              "text": "QCComposition"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "colorSpace"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGColorSpaceRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGColorSpaceRef",
              "text": "CGColorSpace"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object. The composition must  not contain any consumer patches. That is, the composition can receive data, process it, and produce output values, but it cannot perform any rendering.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "composition"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Quartz color space object. This must be an RGB color space. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to use the default RGB color space. The color space is used only for the images produced by the  output image ports of the composition. For more information on Quartz color spaces, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Introduction/Introduction.html#//apple_ref/doc/uid/TP30001066",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "colorSpace"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The initialized ",
              "type": "text"
            },
            {
              "code": "QCRenderer",
              "type": "codeVoice"
            },
            {
              "text": " object or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if initialization is not successful.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Note that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer/snapshotImage()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer/createSnapshotImage(ofType:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " always returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " on such ",
              "type": "text"
            },
            {
              "code": "QCRenderer",
              "type": "codeVoice"
            },
            {
              "text": " instances.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCComposition": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCComposition",
          "type": "codeVoice"
        },
        {
          "text": " class represents a Quartz Composer composition that either:",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCComposition"
        }
      ],
      "role": "symbol",
      "title": "QCComposition",
      "type": "topic",
      "url": "/documentation/quartz/qccomposition"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCRenderer": {
      "abstract": [
        {
          "text": "A base class for low-level rendering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCRenderer"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCRenderer"
        }
      ],
      "role": "symbol",
      "title": "QCRenderer",
      "type": "topic",
      "url": "/documentation/quartz/qcrenderer"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCRenderer/createSnapshotImage(ofType:)": {
      "abstract": [
        {
          "text": "Returns the current image in the OpenGL context associated with the renderer, as an image object of the provided image type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createSnapshotImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer/createSnapshotImage(ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createSnapshotImageOfType:"
        }
      ],
      "role": "symbol",
      "title": "createSnapshotImage(ofType:)",
      "type": "topic",
      "url": "/documentation/quartz/qcrenderer/createsnapshotimage(oftype:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(cglContext:pixelFormat:colorSpace:composition:)": {
      "abstract": [
        {
          "text": "Creates a  renderer object  with a ",
          "type": "text"
        },
        {
          "code": "CGLContextObj",
          "type": "codeVoice"
        },
        {
          "text": " object, a pixel format, a color space, and a composition object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "cglContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGLContextObj",
          "text": "CGLContextObj"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "pixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGLPixelFormatObj",
          "text": "CGLPixelFormatObj"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "colorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "composition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QCComposition",
          "text": "QCComposition"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(cglContext:pixelFormat:colorSpace:composition:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCGLContext:pixelFormat:colorSpace:composition:"
        }
      ],
      "role": "symbol",
      "title": "init(cglContext:pixelFormat:colorSpace:composition:)",
      "type": "topic",
      "url": "/documentation/quartz/qcrenderer/init(cglcontext:pixelformat:colorspace:composition:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(composition:colorSpace:)": {
      "abstract": [
        {
          "text": "Creates a  renderer object  with a composition object and a color space.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "composition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QCComposition",
          "text": "QCComposition"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "colorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(composition:colorSpace:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithComposition:colorSpace:"
        }
      ],
      "role": "symbol",
      "title": "init(composition:colorSpace:)",
      "type": "topic",
      "url": "/documentation/quartz/qcrenderer/init(composition:colorspace:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(offScreenWith:colorSpace:composition:)": {
      "abstract": [
        {
          "text": "Creates an offscreen renderer of a given size with the provided color space and composition object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "offScreenWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "colorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "composition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QCComposition",
          "text": "QCComposition"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(offScreenWith:colorSpace:composition:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initOffScreenWithSize:colorSpace:composition:"
        }
      ],
      "role": "symbol",
      "title": "init(offScreenWith:colorSpace:composition:)",
      "type": "topic",
      "url": "/documentation/quartz/qcrenderer/init(offscreenwith:colorspace:composition:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(openGLContext:pixelFormat:file:)": {
      "abstract": [
        {
          "text": "Creates a  renderer object with an ",
          "type": "text"
        },
        {
          "code": "NSOpenGLContext",
          "type": "codeVoice"
        },
        {
          "text": " object and a composition file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "openGLContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLContext",
          "text": "NSOpenGLContext"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "pixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLPixelFormat",
          "text": "NSOpenGLPixelFormat"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(openGLContext:pixelFormat:file:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOpenGLContext:pixelFormat:file:"
        }
      ],
      "role": "symbol",
      "title": "init(openGLContext:pixelFormat:file:)",
      "type": "topic",
      "url": "/documentation/quartz/qcrenderer/init(openglcontext:pixelformat:file:)"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCRenderer/snapshotImage()": {
      "abstract": [
        {
          "text": "Returns an ",
          "type": "text"
        },
        {
          "code": "NSImage",
          "type": "codeVoice"
        },
        {
          "text": " object of the current image in the OpenGL context associated with the renderer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "snapshotImage"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCRenderer/snapshotImage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "snapshotImage"
        }
      ],
      "role": "symbol",
      "title": "snapshotImage()",
      "type": "topic",
      "url": "/documentation/quartz/qcrenderer/snapshotimage()"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGColorSpaceRef": {
      "abstract": [
        {
          "text": "A profile that specifies how to interpret a color value for display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGColorSpace"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGColorSpaceRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGColorSpace",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcolorspace"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Introduction/Introduction.html#//apple_ref/doc/uid/TP30001066": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Introduction/Introduction.html#//apple_ref/doc/uid/TP30001066",
      "title": "Quartz 2D Programming Guide",
      "titleInlineContent": [
        {
          "text": "Quartz 2D Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Introduction/Introduction.html#//apple_ref/doc/uid/TP30001066"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-and-Initializing-a-Renderer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(openGLContext:pixelFormat:file:)",
        "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(cglContext:pixelFormat:colorSpace:composition:)",
        "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(offScreenWith:colorSpace:composition:)"
      ],
      "title": "Creating and Initializing a Renderer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithComposition:colorSpace:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithComposition:colorSpace:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz",
                "doc://com.apple.quartz/documentation/Quartz/QCRenderer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-and-Initializing-a-Renderer",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(openGLContext:pixelFormat:file:)",
                "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(cglContext:pixelFormat:colorSpace:composition:)",
                "doc://com.apple.quartz/documentation/Quartz/QCRenderer/init(offScreenWith:colorSpace:composition:)"
              ],
              "title": "Creating and Initializing a Renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithComposition:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)QCComposition",
                    "text": "QCComposition"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "composition"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "colorSpace:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGColorSpaceRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGColorSpaceRef",
                    "text": "CGColorSpaceRef"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "colorSpace"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.quartz/documentation/Quartz/QCComposition",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object. The composition must  not contain any consumer patches. That is, the composition can receive data, process it, and produce output values, but it cannot perform any rendering.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "composition"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A Quartz color space object. This must be an RGB color space. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to use the default RGB color space. The color space is used only for the images produced by the  output image ports of the composition. For more information on Quartz color spaces, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Introduction/Introduction.html#//apple_ref/doc/uid/TP30001066",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "colorSpace"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The initialized ",
                    "type": "text"
                  },
                  {
                    "code": "QCRenderer",
                    "type": "codeVoice"
                  },
                  {
                    "text": " object or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if initialization is not successful.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1init(cglContext:pixelFormat:colorSpace:composition:)/title",
          "value": "initWithCGLContext:pixelFormat:colorSpace:composition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1init(cglContext:pixelFormat:colorSpace:composition:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCGLContext:pixelFormat:colorSpace:composition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1init(openGLContext:pixelFormat:file:)/title",
          "value": "initWithOpenGLContext:pixelFormat:file:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1init(openGLContext:pixelFormat:file:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOpenGLContext:pixelFormat:file:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/title",
          "value": "QCRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/title",
          "value": "QCComposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCComposition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1snapshotImage()/title",
          "value": "snapshotImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1snapshotImage()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "snapshotImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1init(composition:colorSpace:)/title",
          "value": "initWithComposition:colorSpace:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1init(composition:colorSpace:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithComposition:colorSpace:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CGColorSpaceRef/title",
          "value": "CGColorSpaceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1createSnapshotImage(ofType:)/title",
          "value": "createSnapshotImageOfType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1createSnapshotImage(ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createSnapshotImageOfType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1init(offScreenWith:colorSpace:composition:)/title",
          "value": "initOffScreenWithSize:colorSpace:composition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCRenderer~1init(offScreenWith:colorSpace:composition:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initOffScreenWithSize:colorSpace:composition:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/qcrenderer/init(composition:colorspace:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/qcrenderer/init(composition:colorspace:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
