{
  "abstract": [
    {
      "text": "The default ducking level for typical voice chat.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioVoiceProcessingOtherAudioDuckingLevel@AVAudioVoiceProcessingOtherAudioDuckingLevelDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level.default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration": {
      "abstract": [
        {
          "text": "The configuration of ducking non-voice audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level": {
      "abstract": [
        {
          "text": "Constants that define the supported ducking levels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Level"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/default": {
      "abstract": [
        {
          "text": "The default ducking level for typical voice chat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelDefault"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level.default",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/default"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/max": {
      "abstract": [
        {
          "text": "Applies maximum ducking to other audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMax"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level.max",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/max"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/mid": {
      "abstract": [
        {
          "text": "Applies medium ducking to other audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mid"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/mid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMid"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level.mid",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/mid"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/min": {
      "abstract": [
        {
          "text": "Applies minimum ducking to other audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMin"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level.min",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/min"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ducking-levels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/max",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/mid",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/min"
      ],
      "title": "Ducking levels"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevelDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ducking-levels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/max",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/mid",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/min"
              ],
              "title": "Ducking levels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1min/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevelMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1default/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevelDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1mid/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevelMid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1mid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1max/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevelMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMax"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
