{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.applearchive/documentation/AppleArchive"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Apple Archive"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Apple Archive structures"
  },
  "references": {
    "doc://com.apple.applearchive/documentation/AppleArchive": {
      "abstract": [
        {
          "text": "Perform multithreaded lossless compression of directories, files, and data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Archive",
      "type": "topic",
      "url": "/documentation/applearchive"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/AAAccessControlEntry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AAAccessControlEntry"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/AAAccessControlEntry",
      "kind": "symbol",
      "role": "symbol",
      "title": "AAAccessControlEntry",
      "type": "topic",
      "url": "/documentation/applearchive/aaaccesscontrolentry"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/AAEntryAttributes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AAEntryAttributes"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/AAEntryAttributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "AAEntryAttributes",
      "type": "topic",
      "url": "/documentation/applearchive/aaentryattributes"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/AAFieldKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AAFieldKey"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/AAFieldKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "AAFieldKey",
      "type": "topic",
      "url": "/documentation/applearchive/aafieldkey"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/AEAContextTraits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AEAContextTraits"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/AEAContextTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AEAContextTraits"
        }
      ],
      "role": "symbol",
      "title": "AEAContextTraits",
      "type": "topic",
      "url": "/documentation/applearchive/aeacontexttraits"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArchiveFlags"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArchiveFlags"
        }
      ],
      "role": "symbol",
      "title": "ArchiveFlags",
      "type": "topic",
      "url": "/documentation/applearchive/archiveflags"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveHash": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArchiveHash"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveHash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArchiveHash"
        }
      ],
      "role": "symbol",
      "title": "ArchiveHash",
      "type": "topic",
      "url": "/documentation/applearchive/archivehash"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Apple Archive data types",
      "type": "topic",
      "url": "/documentation/applearchive/apple-archive-data-types"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Apple Archive functions",
      "type": "topic",
      "url": "/documentation/applearchive/apple-archive-functions"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Apple Archive macros",
      "type": "topic",
      "url": "/documentation/applearchive/apple-archive-macros"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.applearchive/documentation/AppleArchive/AEAContextTraits",
        "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveFlags",
        "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveHash"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.applearchive/documentation/AppleArchive/AAAccessControlEntry",
                "doc://com.apple.applearchive/documentation/AppleArchive/AAFieldKey",
                "doc://com.apple.applearchive/documentation/AppleArchive/AAEntryAttributes"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-data-types",
                "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-functions",
                "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-macros"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/applearchive/apple-archive-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/applearchive/apple-archive-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
