{
  "abstract": [
    {
      "text": "Compress and encrypt the contents of an entire directory or decompress and decrypt an archived directory  using Apple Encrypted Archive.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.applearchive/documentation/AppleArchive"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-directories"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Apple Archive"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Encrypting and Decrypting Directories"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC21 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10233/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.applearchive/documentation/AppleArchive": {
      "abstract": [
        {
          "text": "Perform multithreaded lossless compression of directories, files, and data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Archive",
      "type": "topic",
      "url": "/documentation/applearchive"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveEncryptionContext": {
      "abstract": [
        {
          "text": "An object that encapsulates all parameters, keys, and data necessary to open an encrypted archive for both encryption and decryption streams.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArchiveEncryptionContext"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveEncryptionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArchiveEncryptionContext"
        }
      ],
      "role": "symbol",
      "title": "ArchiveEncryptionContext",
      "type": "topic",
      "url": "/documentation/applearchive/archiveencryptioncontext"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-single-file": {
      "abstract": [
        {
          "text": "Encrypt a single file and save the result to the file system, then decrypt and recreate the original file from the archive file using Apple Encrypted Archive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-single-file",
      "kind": "article",
      "role": "sampleCode",
      "title": "Encrypting and Decrypting a Single File",
      "type": "topic",
      "url": "/documentation/applearchive/encrypting-and-decrypting-a-single-file"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-string": {
      "abstract": [
        {
          "text": "Encrypt the contents of a string and save the result to the file system, then decrypt and recreate the string from the archive file using Apple Encrypted Archive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-string",
      "kind": "article",
      "role": "sampleCode",
      "title": "Encrypting and Decrypting a String",
      "type": "topic",
      "url": "/documentation/applearchive/encrypting-and-decrypting-a-string"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "f8f2c97ac41e/EncryptingAndDecryptingDirectories.zip": {
      "checksum": "f8f2c97ac41ec19bbc771fc5a6d4684b700233913694c2880fb209cfe16452a3f673745ef07d031e15273fffcb31730ee97e0aec93caf2f554fcc300efac0d13",
      "identifier": "f8f2c97ac41e/EncryptingAndDecryptingDirectories.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/f8f2c97ac41e/EncryptingAndDecryptingDirectories.zip"
    },
    "https://developer.apple.com/wwdc21/10233/": {
      "identifier": "https://developer.apple.com/wwdc21/10233/",
      "title": "10233: Bring Encrypted Archives and Performance Improvements to Your App with Accelerate",
      "titleInlineContent": [
        {
          "text": "10233: Bring Encrypted Archives and Performance Improvements to Your App with Accelerate",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10233/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "f8f2c97ac41e/EncryptingAndDecryptingDirectories.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Apple-Encrypted-Archive-essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-string",
        "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-single-file",
        "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveEncryptionContext"
      ],
      "title": "Apple Encrypted Archive essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Apple-Encrypted-Archive-essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-string",
                "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-single-file"
              ],
              "title": "Apple Encrypted Archive essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/applearchive/encrypting-and-decrypting-directories"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/applearchive/encrypting-and-decrypting-directories"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
