{
  "abstract": [
    {
      "text": "An object representing counts for the different types of background app exits.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXBackgroundExitData",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MXBackgroundExitData"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MXBackgroundExitData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MXBackgroundExitData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MXBackgroundExitData"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric/backgroundExitData": {
      "abstract": [
        {
          "text": "The metrics for the background app exits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundExitData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXBackgroundExitData",
          "text": "MXBackgroundExitData"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric/backgroundExitData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundExitData"
        }
      ],
      "role": "symbol",
      "title": "backgroundExitData",
      "type": "topic",
      "url": "/documentation/metrickit/mxappexitmetric/backgroundexitdata"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData": {
      "abstract": [
        {
          "text": "An object representing counts for the different types of background app exits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXBackgroundExitData"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXBackgroundExitData"
        }
      ],
      "role": "symbol",
      "title": "MXBackgroundExitData",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeAbnormalExitCount": {
      "abstract": [
        {
          "text": "The number of times the app exited abnormally from the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeAbnormalExitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeAbnormalExitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeAbnormalExitCount"
        }
      ],
      "role": "symbol",
      "title": "cumulativeAbnormalExitCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata/cumulativeabnormalexitcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeAppWatchdogExitCount": {
      "abstract": [
        {
          "text": "The number of times the system watchdog terminated the app from the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeAppWatchdogExitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeAppWatchdogExitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeAppWatchdogExitCount"
        }
      ],
      "role": "symbol",
      "title": "cumulativeAppWatchdogExitCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata/cumulativeappwatchdogexitcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeBackgroundTaskAssertionTimeoutExitCount": {
      "abstract": [
        {
          "text": "The number of times the system terminated the app from the background for exceeding the allocated time for a background task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeBackgroundTaskAssertionTimeoutExitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeBackgroundTaskAssertionTimeoutExitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeBackgroundTaskAssertionTimeoutExitCount"
        }
      ],
      "role": "symbol",
      "title": "cumulativeBackgroundTaskAssertionTimeoutExitCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata/cumulativebackgroundtaskassertiontimeoutexitcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeBadAccessExitCount": {
      "abstract": [
        {
          "text": "The number of times the system terminated the app from the background for attempting an invalid memory access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeBadAccessExitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeBadAccessExitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeBadAccessExitCount"
        }
      ],
      "role": "symbol",
      "title": "cumulativeBadAccessExitCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata/cumulativebadaccessexitcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeCPUResourceLimitExitCount": {
      "abstract": [
        {
          "text": "The number of times the system terminated the app from the background for using too much CPU time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeCPUResourceLimitExitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeCPUResourceLimitExitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeCPUResourceLimitExitCount"
        }
      ],
      "role": "symbol",
      "title": "cumulativeCPUResourceLimitExitCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata/cumulativecpuresourcelimitexitcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeIllegalInstructionExitCount": {
      "abstract": [
        {
          "text": "The number of times the system terminated the app from the background for attempting to execute an illegal or undefined instruction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeIllegalInstructionExitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeIllegalInstructionExitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeIllegalInstructionExitCount"
        }
      ],
      "role": "symbol",
      "title": "cumulativeIllegalInstructionExitCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata/cumulativeillegalinstructionexitcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeMemoryPressureExitCount": {
      "abstract": [
        {
          "text": "The number of times the system terminated the app from the background to free up memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeMemoryPressureExitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeMemoryPressureExitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeMemoryPressureExitCount"
        }
      ],
      "role": "symbol",
      "title": "cumulativeMemoryPressureExitCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata/cumulativememorypressureexitcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeMemoryResourceLimitExitCount": {
      "abstract": [
        {
          "text": "The number of times the system terminated the app from the background for using too much memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeMemoryResourceLimitExitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeMemoryResourceLimitExitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeMemoryResourceLimitExitCount"
        }
      ],
      "role": "symbol",
      "title": "cumulativeMemoryResourceLimitExitCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata/cumulativememoryresourcelimitexitcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeNormalAppExitCount": {
      "abstract": [
        {
          "text": "The number of times the app exited normally from the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeNormalAppExitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeNormalAppExitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeNormalAppExitCount"
        }
      ],
      "role": "symbol",
      "title": "cumulativeNormalAppExitCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata/cumulativenormalappexitcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeSuspendedWithLockedFileExitCount": {
      "abstract": [
        {
          "text": "The number of times the system terminated the app from the background while being suspended and having file locks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeSuspendedWithLockedFileExitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeSuspendedWithLockedFileExitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeSuspendedWithLockedFileExitCount"
        }
      ],
      "role": "symbol",
      "title": "cumulativeSuspendedWithLockedFileExitCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxbackgroundexitdata/cumulativesuspendedwithlockedfileexitcount"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-the-background-exit-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric/backgroundExitData"
      ],
      "title": "Reading the background exit data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reading-the-Normal-Exit-Count",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeNormalAppExitCount"
      ],
      "title": "Reading the Normal Exit Count"
    },
    {
      "anchor": "Reading-the-Abnormal-Exit-Count",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeAbnormalExitCount"
      ],
      "title": "Reading the Abnormal Exit Count"
    },
    {
      "anchor": "Reading-the-System-Termination-Count",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeAppWatchdogExitCount",
        "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeCPUResourceLimitExitCount",
        "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeMemoryResourceLimitExitCount",
        "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeMemoryPressureExitCount",
        "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeSuspendedWithLockedFileExitCount"
      ],
      "title": "Reading the System Termination Count"
    },
    {
      "anchor": "Reading-the-Crash-Count",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeBadAccessExitCount",
        "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeIllegalInstructionExitCount"
      ],
      "title": "Reading the Crash Count"
    },
    {
      "anchor": "Reading-the-Timeout-Count",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeBackgroundTaskAssertionTimeoutExitCount"
      ],
      "title": "Reading the Timeout Count"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MXBackgroundExitData"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXBackgroundExitData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXBackgroundExitData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reading-the-Normal-Exit-Count",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeNormalAppExitCount"
              ],
              "title": "Reading the Normal Exit Count"
            },
            {
              "anchor": "Reading-the-Abnormal-Exit-Count",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeAbnormalExitCount"
              ],
              "title": "Reading the Abnormal Exit Count"
            },
            {
              "anchor": "Reading-the-System-Termination-Count",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeAppWatchdogExitCount",
                "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeCPUResourceLimitExitCount",
                "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeMemoryResourceLimitExitCount",
                "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeMemoryPressureExitCount",
                "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeSuspendedWithLockedFileExitCount"
              ],
              "title": "Reading the System Termination Count"
            },
            {
              "anchor": "Reading-the-Crash-Count",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeBadAccessExitCount",
                "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeIllegalInstructionExitCount"
              ],
              "title": "Reading the Crash Count"
            },
            {
              "anchor": "Reading-the-Timeout-Count",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXBackgroundExitData/cumulativeBackgroundTaskAssertionTimeoutExitCount"
              ],
              "title": "Reading the Timeout Count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-the-background-exit-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric/backgroundExitData"
              ],
              "title": "Reading the background exit data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MXBackgroundExitData"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeNormalAppExitCount/title",
          "value": "cumulativeNormalAppExitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeNormalAppExitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeNormalAppExitCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeAbnormalExitCount/title",
          "value": "cumulativeAbnormalExitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeAbnormalExitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeAbnormalExitCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeAppWatchdogExitCount/title",
          "value": "cumulativeAppWatchdogExitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeAppWatchdogExitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeAppWatchdogExitCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeMemoryResourceLimitExitCount/title",
          "value": "cumulativeMemoryResourceLimitExitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeMemoryResourceLimitExitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeMemoryResourceLimitExitCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeBadAccessExitCount/title",
          "value": "cumulativeBadAccessExitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeBadAccessExitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeBadAccessExitCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeMemoryPressureExitCount/title",
          "value": "cumulativeMemoryPressureExitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeMemoryPressureExitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeMemoryPressureExitCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData/title",
          "value": "MXBackgroundExitData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXBackgroundExitData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXBackgroundExitData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeCPUResourceLimitExitCount/title",
          "value": "cumulativeCPUResourceLimitExitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeCPUResourceLimitExitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeCPUResourceLimitExitCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeBackgroundTaskAssertionTimeoutExitCount/title",
          "value": "cumulativeBackgroundTaskAssertionTimeoutExitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeBackgroundTaskAssertionTimeoutExitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeBackgroundTaskAssertionTimeoutExitCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeSuspendedWithLockedFileExitCount/title",
          "value": "cumulativeSuspendedWithLockedFileExitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeSuspendedWithLockedFileExitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeSuspendedWithLockedFileExitCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeIllegalInstructionExitCount/title",
          "value": "cumulativeIllegalInstructionExitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXBackgroundExitData~1cumulativeIllegalInstructionExitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeIllegalInstructionExitCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppExitMetric~1backgroundExitData/title",
          "value": "backgroundExitData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppExitMetric~1backgroundExitData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundExitData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxbackgroundexitdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxbackgroundexitdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
