{
  "abstract": [
    {
      "text": "An object representing a diagnostic report for an app crash.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXCrashDiagnostic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MXCrashDiagnostic"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MXCrashDiagnostic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MXCrashDiagnostic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MXCrashDiagnostic"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the types of foreground and background app exits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXAppExitMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXAppExitMetric"
        }
      ],
      "role": "symbol",
      "title": "MXAppExitMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxappexitmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAppLaunchDiagnostic": {
      "abstract": [
        {
          "text": "A diagnostic subclass that encapsulates app launch diagnostic reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXAppLaunchDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAppLaunchDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXAppLaunchDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "MXAppLaunchDiagnostic",
      "type": "topic",
      "url": "/documentation/metrickit/mxapplaunchdiagnostic"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAppRunTimeMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the amount of time the app is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXAppRunTimeMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAppRunTimeMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXAppRunTimeMetric"
        }
      ],
      "role": "symbol",
      "title": "MXAppRunTimeMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxappruntimemetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic": {
      "abstract": [
        {
          "text": "An object representing a diagnostic report for an app crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCrashDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCrashDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "MXCrashDiagnostic",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/callStackTree": {
      "abstract": [
        {
          "text": "The call stack for the crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callStackTree"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXCallStackTree",
          "text": "MXCallStackTree"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/callStackTree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callStackTree"
        }
      ],
      "role": "symbol",
      "title": "callStackTree",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/callstacktree"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionCode": {
      "abstract": [
        {
          "text": "The encoded processor-specific information for the crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exceptionCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exceptionCode"
        }
      ],
      "role": "symbol",
      "title": "exceptionCode",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/exceptioncode"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exceptionReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXCrashDiagnosticObjectiveCExceptionReason",
          "text": "MXCrashDiagnosticObjectiveCExceptionReason"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exceptionReason"
        }
      ],
      "role": "symbol",
      "title": "exceptionReason",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/exceptionreason"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionType": {
      "abstract": [
        {
          "text": "The Mach exception type of the crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exceptionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exceptionType"
        }
      ],
      "role": "symbol",
      "title": "exceptionType",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/exceptiontype"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/signal": {
      "abstract": [
        {
          "text": "The signal associated with the crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/signal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signal"
        }
      ],
      "role": "symbol",
      "title": "signal",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/signal"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/terminationReason": {
      "abstract": [
        {
          "text": "The reason the app was terminated as a human-readable string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "terminationReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/terminationReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "terminationReason"
        }
      ],
      "role": "symbol",
      "title": "terminationReason",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/terminationreason"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/virtualMemoryRegionInfo": {
      "abstract": [
        {
          "text": "Information about the region of memory an app accessed incorrectly, resulting in a bad-access crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "virtualMemoryRegionInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/virtualMemoryRegionInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "virtualMemoryRegionInfo"
        }
      ],
      "role": "symbol",
      "title": "virtualMemoryRegionInfo",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/virtualmemoryregioninfo"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic": {
      "abstract": [
        {
          "text": "An abstract data class for a diagnostic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "MXDiagnostic",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnostic"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMemoryMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the app’s memory use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMemoryMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMemoryMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMemoryMetric"
        }
      ],
      "role": "symbol",
      "title": "MXMemoryMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxmemorymetric"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performance-metrics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXAppLaunchDiagnostic",
        "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXAppRunTimeMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMemoryMetric"
      ],
      "title": "Performance metrics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Viewing-exception-details",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionType",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionCode",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/signal",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionReason",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/terminationReason",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/virtualMemoryRegionInfo"
      ],
      "title": "Viewing exception details"
    },
    {
      "anchor": "Viewing-the-call-stack",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/callStackTree"
      ],
      "title": "Viewing the call stack"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MXCrashDiagnostic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCrashDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCrashDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Viewing-exception-details",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionType",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionCode",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/signal",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionReason",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/terminationReason",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/virtualMemoryRegionInfo"
              ],
              "title": "Viewing exception details"
            },
            {
              "anchor": "Viewing-the-call-stack",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/callStackTree"
              ],
              "title": "Viewing the call stack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Performance-metrics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXAppLaunchDiagnostic",
                "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXAppRunTimeMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMemoryMetric"
              ],
              "title": "Performance metrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MXCrashDiagnostic"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MXDiagnostic",
                    "text": "MXDiagnostic"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionCode/title",
          "value": "exceptionCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exceptionCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/title",
          "value": "MXDiagnostic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppRunTimeMetric/title",
          "value": "MXAppRunTimeMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppRunTimeMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppRunTimeMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppRunTimeMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppRunTimeMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppLaunchDiagnostic/title",
          "value": "MXAppLaunchDiagnostic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppLaunchDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppLaunchDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppLaunchDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppLaunchDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1virtualMemoryRegionInfo/title",
          "value": "virtualMemoryRegionInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1virtualMemoryRegionInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "virtualMemoryRegionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMemoryMetric/title",
          "value": "MXMemoryMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMemoryMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMemoryMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMemoryMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMemoryMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1signal/title",
          "value": "signal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1signal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppExitMetric/title",
          "value": "MXAppExitMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppExitMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppExitMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppExitMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppExitMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic/title",
          "value": "MXCrashDiagnostic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCrashDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCrashDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionReason/title",
          "value": "exceptionReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exceptionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1terminationReason/title",
          "value": "terminationReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1terminationReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "terminationReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionType/title",
          "value": "exceptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exceptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1callStackTree/title",
          "value": "callStackTree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1callStackTree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callStackTree"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxcrashdiagnostic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxcrashdiagnostic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
