{
  "abstract": [
    {
      "text": "An object that encapsulates a diagnostic report.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXDiagnosticPayload",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MXDiagnosticPayload"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MXDiagnosticPayload"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MXDiagnosticPayload"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system delivers a diagnostic report as soon as it’s available.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload": {
      "abstract": [
        {
          "text": "An object that encapsulates a diagnostic report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiagnosticPayload"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiagnosticPayload"
        }
      ],
      "role": "symbol",
      "title": "MXDiagnosticPayload",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/appLaunchDiagnostics": {
      "abstract": [
        {
          "text": "The diagnostic reports for the app launch time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appLaunchDiagnostics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXAppLaunchDiagnostic",
          "text": "MXAppLaunchDiagnostic"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/appLaunchDiagnostics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appLaunchDiagnostics"
        }
      ],
      "role": "symbol",
      "title": "appLaunchDiagnostics",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/applaunchdiagnostics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/cpuExceptionDiagnostics": {
      "abstract": [
        {
          "text": "The diagnostic reports for fatal and nonfatal CPU exceptions for the app during the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cpuExceptionDiagnostics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXCPUExceptionDiagnostic",
          "text": "MXCPUExceptionDiagnostic"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/cpuExceptionDiagnostics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cpuExceptionDiagnostics"
        }
      ],
      "role": "symbol",
      "title": "cpuExceptionDiagnostics",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/cpuexceptiondiagnostics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/crashDiagnostics": {
      "abstract": [
        {
          "text": "The diagnostic reports for app crashes during the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crashDiagnostics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXCrashDiagnostic",
          "text": "MXCrashDiagnostic"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/crashDiagnostics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "crashDiagnostics"
        }
      ],
      "role": "symbol",
      "title": "crashDiagnostics",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/crashdiagnostics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/dictionaryRepresentation()": {
      "abstract": [
        {
          "text": "Returns the results of the payload as a dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dictionaryRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/dictionaryRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dictionaryRepresentation"
        }
      ],
      "role": "symbol",
      "title": "dictionaryRepresentation()",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/dictionaryrepresentation()"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/diskWriteExceptionDiagnostics": {
      "abstract": [
        {
          "text": "The diagnostic reports for disk write exceptions for the app during the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diskWriteExceptionDiagnostics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXDiskWriteExceptionDiagnostic",
          "text": "MXDiskWriteExceptionDiagnostic"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/diskWriteExceptionDiagnostics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "diskWriteExceptionDiagnostics"
        }
      ],
      "role": "symbol",
      "title": "diskWriteExceptionDiagnostics",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/diskwriteexceptiondiagnostics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/hangDiagnostics": {
      "abstract": [
        {
          "text": "The diagnostic reports for times when the app was too busy to handle input responsively during the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hangDiagnostics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXHangDiagnostic",
          "text": "MXHangDiagnostic"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/hangDiagnostics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hangDiagnostics"
        }
      ],
      "role": "symbol",
      "title": "hangDiagnostics",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/hangdiagnostics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/jsonRepresentation()": {
      "abstract": [
        {
          "text": "Returns the contents of the payload in JSON format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jsonRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/jsonRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSONRepresentation"
        }
      ],
      "role": "symbol",
      "title": "jsonRepresentation()",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/jsonrepresentation()"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampBegin": {
      "abstract": [
        {
          "text": "The starting time of the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStampBegin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampBegin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeStampBegin"
        }
      ],
      "role": "symbol",
      "title": "timeStampBegin",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/timestampbegin"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampEnd": {
      "abstract": [
        {
          "text": "The ending time of the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStampEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeStampEnd"
        }
      ],
      "role": "symbol",
      "title": "timeStampEnd",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/timestampend"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager": {
      "abstract": [
        {
          "text": "The shared object that registers you to receive metrics, creates logs for custom metrics, and gives access to past reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetricManager"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetricManager"
        }
      ],
      "role": "symbol",
      "title": "MXMetricManager",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber": {
      "abstract": [
        {
          "text": "A protocol defining a method for receiving a daily metrics report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetricManagerSubscriber"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetricManagerSubscriber"
        }
      ],
      "role": "symbol",
      "title": "MXMetricManagerSubscriber",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanagersubscriber"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload": {
      "abstract": [
        {
          "text": "An object that encapsulates a daily metrics report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetricPayload"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetricPayload"
        }
      ],
      "role": "symbol",
      "title": "MXMetricPayload",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reading-performance-metrics",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/crashDiagnostics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/cpuExceptionDiagnostics"
      ],
      "title": "Reading performance metrics"
    },
    {
      "anchor": "Reading-responsiveness-metrics",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/appLaunchDiagnostics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/hangDiagnostics"
      ],
      "title": "Reading responsiveness metrics"
    },
    {
      "anchor": "Reading-disk-access-metrics",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/diskWriteExceptionDiagnostics"
      ],
      "title": "Reading disk access metrics"
    },
    {
      "anchor": "Generating-a-report",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/jsonRepresentation()",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/dictionaryRepresentation()"
      ],
      "title": "Generating a report"
    },
    {
      "anchor": "Reading-information-about-the-payload",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampBegin",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampEnd"
      ],
      "title": "Reading information about the payload"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MXDiagnosticPayload"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reading-performance-metrics",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/crashDiagnostics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/cpuExceptionDiagnostics"
              ],
              "title": "Reading performance metrics"
            },
            {
              "anchor": "Reading-responsiveness-metrics",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/appLaunchDiagnostics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/hangDiagnostics"
              ],
              "title": "Reading responsiveness metrics"
            },
            {
              "anchor": "Reading-disk-access-metrics",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/diskWriteExceptionDiagnostics"
              ],
              "title": "Reading disk access metrics"
            },
            {
              "anchor": "Generating-a-report",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/jsonRepresentation()",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/dictionaryRepresentation()"
              ],
              "title": "Generating a report"
            },
            {
              "anchor": "Reading-information-about-the-payload",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampBegin",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampEnd"
              ],
              "title": "Reading information about the payload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MXDiagnosticPayload"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1timeStampEnd/title",
          "value": "timeStampEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1timeStampEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStampEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1hangDiagnostics/title",
          "value": "hangDiagnostics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1hangDiagnostics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hangDiagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/title",
          "value": "MXMetricPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManagerSubscriber/title",
          "value": "MXMetricManagerSubscriber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManagerSubscriber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManagerSubscriber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManagerSubscriber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManagerSubscriber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager/title",
          "value": "MXMetricManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1cpuExceptionDiagnostics/title",
          "value": "cpuExceptionDiagnostics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1cpuExceptionDiagnostics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cpuExceptionDiagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1crashDiagnostics/title",
          "value": "crashDiagnostics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1crashDiagnostics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "crashDiagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1appLaunchDiagnostics/title",
          "value": "appLaunchDiagnostics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1appLaunchDiagnostics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appLaunchDiagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/title",
          "value": "MXDiagnosticPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1diskWriteExceptionDiagnostics/title",
          "value": "diskWriteExceptionDiagnostics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1diskWriteExceptionDiagnostics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "diskWriteExceptionDiagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1jsonRepresentation()/title",
          "value": "JSONRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1jsonRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "JSONRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1timeStampBegin/title",
          "value": "timeStampBegin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1timeStampBegin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStampBegin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1dictionaryRepresentation()/title",
          "value": "dictionaryRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1dictionaryRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dictionaryRepresentation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxdiagnosticpayload"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxdiagnosticpayload"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
