{
  "abstract": [
    {
      "text": "An object representing a diagnostic report for a disk write exception.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXDiskWriteExceptionDiagnostic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MXDiskWriteExceptionDiagnostic"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MXDiskWriteExceptionDiagnostic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MXDiskWriteExceptionDiagnostic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MXDiskWriteExceptionDiagnostic"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A disk write exception occurs when the app writes an excessive amount of data to the disk.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic": {
      "abstract": [
        {
          "text": "An abstract data class for a diagnostic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "MXDiagnostic",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnostic"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiskIOMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about disk usage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiskIOMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiskIOMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiskIOMetric"
        }
      ],
      "role": "symbol",
      "title": "MXDiskIOMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiskiometric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic": {
      "abstract": [
        {
          "text": "An object representing a diagnostic report for a disk write exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiskWriteExceptionDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiskWriteExceptionDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "MXDiskWriteExceptionDiagnostic",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiskwriteexceptiondiagnostic"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic/callStackTree": {
      "abstract": [
        {
          "text": "The call stack for the disk write exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callStackTree"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXCallStackTree",
          "text": "MXCallStackTree"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic/callStackTree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callStackTree"
        }
      ],
      "role": "symbol",
      "title": "callStackTree",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiskwriteexceptiondiagnostic/callstacktree"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic/totalWritesCaused": {
      "abstract": [
        {
          "text": "The total amount of data written to disk or other long-term storage during the disk write exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalWritesCaused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitInformationStorage",
          "text": "UnitInformationStorage"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic/totalWritesCaused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalWritesCaused"
        }
      ],
      "role": "symbol",
      "title": "totalWritesCaused",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiskwriteexceptiondiagnostic/totalwritescaused"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Disk-access-metrics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiskIOMetric"
      ],
      "title": "Disk access metrics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reading-total-disk-writes",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic/totalWritesCaused"
      ],
      "title": "Reading total disk writes"
    },
    {
      "anchor": "Viewing-the-call-stack",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic/callStackTree"
      ],
      "title": "Viewing the call stack"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MXDiskWriteExceptionDiagnostic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiskWriteExceptionDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiskWriteExceptionDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reading-total-disk-writes",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic/totalWritesCaused"
              ],
              "title": "Reading total disk writes"
            },
            {
              "anchor": "Viewing-the-call-stack",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiskWriteExceptionDiagnostic/callStackTree"
              ],
              "title": "Viewing the call stack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Disk-access-metrics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiskIOMetric"
              ],
              "title": "Disk access metrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MXDiskWriteExceptionDiagnostic"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MXDiagnostic",
                    "text": "MXDiagnostic"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskWriteExceptionDiagnostic~1callStackTree/title",
          "value": "callStackTree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskWriteExceptionDiagnostic~1callStackTree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callStackTree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskIOMetric/title",
          "value": "MXDiskIOMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskIOMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiskIOMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskIOMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiskIOMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/title",
          "value": "MXDiagnostic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskWriteExceptionDiagnostic/title",
          "value": "MXDiskWriteExceptionDiagnostic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskWriteExceptionDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiskWriteExceptionDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskWriteExceptionDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiskWriteExceptionDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskWriteExceptionDiagnostic~1totalWritesCaused/title",
          "value": "totalWritesCaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskWriteExceptionDiagnostic~1totalWritesCaused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalWritesCaused"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxdiskwriteexceptiondiagnostic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxdiskwriteexceptiondiagnostic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
