{
  "abstract": [
    {
      "text": "An object representing metrics about the use of location-tracking features of a device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXLocationActivityMetric",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MXLocationActivityMetric"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MXLocationActivityMetric"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MXLocationActivityMetric"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MXLocationActivityMetric"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCPUExceptionDiagnostic": {
      "abstract": [
        {
          "text": "An object representing a diagnostic report for a fatal or nonfatal CPU exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCPUExceptionDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCPUExceptionDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCPUExceptionDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "MXCPUExceptionDiagnostic",
      "type": "topic",
      "url": "/documentation/metrickit/mxcpuexceptiondiagnostic"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCPUMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the use of the CPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCPUMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCPUMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCPUMetric"
        }
      ],
      "role": "symbol",
      "title": "MXCPUMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxcpumetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCellularConditionMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the condition of the cellular network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCellularConditionMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCellularConditionMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCellularConditionMetric"
        }
      ],
      "role": "symbol",
      "title": "MXCellularConditionMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxcellularconditionmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDisplayMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the power used to display the app on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDisplayMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDisplayMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDisplayMetric"
        }
      ],
      "role": "symbol",
      "title": "MXDisplayMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxdisplaymetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXGPUMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the use of the GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXGPUMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXGPUMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXGPUMetric"
        }
      ],
      "role": "symbol",
      "title": "MXGPUMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxgpumetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the use of location-tracking features of a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXLocationActivityMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXLocationActivityMetric"
        }
      ],
      "role": "symbol",
      "title": "MXLocationActivityMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyForNavigationTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location at the best accuracy for navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeBestAccuracyForNavigationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyForNavigationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeBestAccuracyForNavigationTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeBestAccuracyForNavigationTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativebestaccuracyfornavigationtime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location at the best accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeBestAccuracyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeBestAccuracyTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeBestAccuracyTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativebestaccuracytime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeHundredMetersAccuracyTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location to an accuracy of 100 meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeHundredMetersAccuracyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeHundredMetersAccuracyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeHundredMetersAccuracyTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeHundredMetersAccuracyTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativehundredmetersaccuracytime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeKilometerAccuracyTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location to an accuracy of 1 kilometer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeKilometerAccuracyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeKilometerAccuracyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeKilometerAccuracyTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeKilometerAccuracyTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativekilometeraccuracytime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeNearestTenMetersAccuracyTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location to an accuracy of 10 meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeNearestTenMetersAccuracyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeNearestTenMetersAccuracyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeNearestTenMetersAccuracyTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeNearestTenMetersAccuracyTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativenearesttenmetersaccuracytime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeThreeKilometersAccuracyTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location to an accuracy of 3 kilometers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeThreeKilometersAccuracyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeThreeKilometersAccuracyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeThreeKilometersAccuracyTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeThreeKilometersAccuracyTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativethreekilometersaccuracytime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetric": {
      "abstract": [
        {
          "text": "An abstract data class for a metric.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetric"
        }
      ],
      "role": "symbol",
      "title": "MXMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXNetworkTransferMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about network transfers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXNetworkTransferMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXNetworkTransferMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXNetworkTransferMetric"
        }
      ],
      "role": "symbol",
      "title": "MXNetworkTransferMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxnetworktransfermetric"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetric"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Battery-metrics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXCellularConditionMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCPUMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDisplayMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXGPUMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXNetworkTransferMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCPUExceptionDiagnostic"
      ],
      "title": "Battery metrics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reading-location-services-use",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyForNavigationTime",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyTime",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeNearestTenMetersAccuracyTime",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeHundredMetersAccuracyTime",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeKilometerAccuracyTime",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeThreeKilometersAccuracyTime"
      ],
      "title": "Reading location services use"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MXLocationActivityMetric"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXLocationActivityMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXLocationActivityMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reading-location-services-use",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyForNavigationTime",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyTime",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeNearestTenMetersAccuracyTime",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeHundredMetersAccuracyTime",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeKilometerAccuracyTime",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeThreeKilometersAccuracyTime"
              ],
              "title": "Reading location services use"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetric"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Battery-metrics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXCellularConditionMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCPUMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDisplayMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXGPUMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXNetworkTransferMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCPUExceptionDiagnostic"
              ],
              "title": "Battery metrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MXLocationActivityMetric"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetric",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MXMetric",
                    "text": "MXMetric"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeNearestTenMetersAccuracyTime/title",
          "value": "cumulativeNearestTenMetersAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeNearestTenMetersAccuracyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeNearestTenMetersAccuracyTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeBestAccuracyTime/title",
          "value": "cumulativeBestAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeBestAccuracyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeBestAccuracyTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric/title",
          "value": "MXMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeKilometerAccuracyTime/title",
          "value": "cumulativeKilometerAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeKilometerAccuracyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeKilometerAccuracyTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeThreeKilometersAccuracyTime/title",
          "value": "cumulativeThreeKilometersAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeThreeKilometersAccuracyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeThreeKilometersAccuracyTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDisplayMetric/title",
          "value": "MXDisplayMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDisplayMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDisplayMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDisplayMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDisplayMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXGPUMetric/title",
          "value": "MXGPUMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXGPUMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXGPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXGPUMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXGPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeHundredMetersAccuracyTime/title",
          "value": "cumulativeHundredMetersAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeHundredMetersAccuracyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeHundredMetersAccuracyTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeBestAccuracyForNavigationTime/title",
          "value": "cumulativeBestAccuracyForNavigationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeBestAccuracyForNavigationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeBestAccuracyForNavigationTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCellularConditionMetric/title",
          "value": "MXCellularConditionMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCellularConditionMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCellularConditionMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCellularConditionMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCellularConditionMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric/title",
          "value": "MXLocationActivityMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXLocationActivityMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXLocationActivityMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCPUMetric/title",
          "value": "MXCPUMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCPUMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCPUMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCPUExceptionDiagnostic/title",
          "value": "MXCPUExceptionDiagnostic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCPUExceptionDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCPUExceptionDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCPUExceptionDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCPUExceptionDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXNetworkTransferMetric/title",
          "value": "MXNetworkTransferMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXNetworkTransferMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXNetworkTransferMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXNetworkTransferMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXNetworkTransferMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxlocationactivitymetric"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxlocationactivitymetric"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
