{
  "abstract": [
    {
      "text": "The shared object that registers you to receive metrics, creates logs for custom metrics, and gives access to past reports.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXMetricManager",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MXMetricManager"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MXMetricManager"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MXMetricManager"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MXMetricManager"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "MXMetricManager",
              "type": "codeVoice"
            },
            {
              "text": " shared object manages your subscription for receiving on-device daily metrics.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "MetricKit starts accumulating reports for your app after calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/shared",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the first time. To receive the reports, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/add(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with an object that adopts the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. The system then delivers metric reports at most once per day, and diagnostic reports immediately in iOS 15 and later and macOS 12 and later. The reports contain the metrics from the past 24 hours and any previously undelivered daily reports. To pause receiving reports, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/remove(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The calls to add a subscriber and for receiving reports are safe to use in performance-sensitive code, such as app launch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The snippet below shows a simple class for using MetricKit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class AppMetrics: NSObject, MXMetricManagerSubscriber {",
            "    func receiveReports() {",
            "       let shared = MXMetricManager.shared",
            "       shared.add(self)",
            "    }",
            "",
            "    func pauseReports() {",
            "       let shared = MXMetricManager.shared",
            "       shared.remove(self)",
            "    }",
            "",
            "    // Receive daily metrics.",
            "    func didReceive(_ payloads: [MXMetricPayload]) {",
            "       // Process metrics.",
            "    }",
            "",
            "    // Receive diagnostics immediately when available.",
            "    func didReceive(_ payloads: [MXDiagnosticPayload]) {",
            "       // Process diagnostics.",
            "    }",
            "}",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload": {
      "abstract": [
        {
          "text": "An object that encapsulates a diagnostic report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiagnosticPayload"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiagnosticPayload"
        }
      ],
      "role": "symbol",
      "title": "MXDiagnosticPayload",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLaunchTaskID": {
      "abstract": [
        {
          "text": "The task identifier to track launch measurements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXLaunchTaskID"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLaunchTaskID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXLaunchTaskID"
        }
      ],
      "role": "symbol",
      "title": "MXLaunchTaskID",
      "type": "topic",
      "url": "/documentation/metrickit/mxlaunchtaskid"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager": {
      "abstract": [
        {
          "text": "The shared object that registers you to receive metrics, creates logs for custom metrics, and gives access to past reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetricManager"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetricManager"
        }
      ],
      "role": "symbol",
      "title": "MXMetricManager",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/add(_:)": {
      "abstract": [
        {
          "text": "Registers to receive a daily report of app metrics from the metrics manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MXMetricManagerSubscriber",
          "text": "MXMetricManagerSubscriber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/add(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSubscriber:"
        }
      ],
      "role": "symbol",
      "title": "add(_:)",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager/add(_:)"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/extendLaunchMeasurement(forTaskID:)": {
      "abstract": [
        {
          "text": "Starts to measure an extended launch task with the given task identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendLaunchMeasurement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTaskID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MXLaunchTaskID",
          "text": "MXLaunchTaskID"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/extendLaunchMeasurement(forTaskID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendLaunchMeasurementForTaskID:error:"
        }
      ],
      "role": "symbol",
      "title": "extendLaunchMeasurement(forTaskID:)",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager/extendlaunchmeasurement(fortaskid:)"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/finishExtendedLaunchMeasurement(forTaskID:)": {
      "abstract": [
        {
          "text": "Signals the end of an extended launch task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishExtendedLaunchMeasurement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTaskID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MXLaunchTaskID",
          "text": "MXLaunchTaskID"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/finishExtendedLaunchMeasurement(forTaskID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishExtendedLaunchMeasurementForTaskID:error:"
        }
      ],
      "role": "symbol",
      "title": "finishExtendedLaunchMeasurement(forTaskID:)",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager/finishextendedlaunchmeasurement(fortaskid:)"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/makeLogHandle(category:)": {
      "abstract": [
        {
          "text": "Returns a log handle used for writing custom metric events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeLogHandle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "category"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_os_log",
          "text": "OSLog"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/makeLogHandle(category:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeLogHandleWithCategory:"
        }
      ],
      "role": "symbol",
      "title": "makeLogHandle(category:)",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager/makeloghandle(category:)"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/pastDiagnosticPayloads": {
      "abstract": [
        {
          "text": "Returns an array of the diagnostic reports generated since the last allocation of the shared manager instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pastDiagnosticPayloads"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXDiagnosticPayload",
          "text": "MXDiagnosticPayload"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/pastDiagnosticPayloads",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pastDiagnosticPayloads"
        }
      ],
      "role": "symbol",
      "title": "pastDiagnosticPayloads",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager/pastdiagnosticpayloads"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/pastPayloads": {
      "abstract": [
        {
          "text": "Returns an array of the daily metrics reports generated since the last allocation of the shared manager instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pastPayloads"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXMetricPayload",
          "text": "MXMetricPayload"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/pastPayloads",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pastPayloads"
        }
      ],
      "role": "symbol",
      "title": "pastPayloads",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager/pastpayloads"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/remove(_:)": {
      "abstract": [
        {
          "text": "Unsubscribes from daily reports of app metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MXMetricManagerSubscriber",
          "text": "MXMetricManagerSubscriber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/remove(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSubscriber:"
        }
      ],
      "role": "symbol",
      "title": "remove(_:)",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager/remove(_:)"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/shared": {
      "abstract": [
        {
          "text": "An object that returns the shared metrics manager instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXMetricManager",
          "text": "MXMetricManager"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/shared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedManager"
        }
      ],
      "role": "symbol",
      "title": "shared",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager/shared"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber": {
      "abstract": [
        {
          "text": "A protocol defining a method for receiving a daily metrics report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetricManagerSubscriber"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetricManagerSubscriber"
        }
      ],
      "role": "symbol",
      "title": "MXMetricManagerSubscriber",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanagersubscriber"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload": {
      "abstract": [
        {
          "text": "An object that encapsulates a daily metrics report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetricPayload"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetricPayload"
        }
      ],
      "role": "symbol",
      "title": "MXMetricPayload",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-shared-metrics-manager",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/shared"
      ],
      "title": "Getting the shared metrics manager"
    },
    {
      "anchor": "Subscribing-to-reports",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/add(_:)",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/remove(_:)"
      ],
      "title": "Subscribing to reports"
    },
    {
      "anchor": "Retrieving-previous-reports",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/pastPayloads",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/pastDiagnosticPayloads"
      ],
      "title": "Retrieving previous reports"
    },
    {
      "anchor": "Creating-custom-metric-logs",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/makeLogHandle(category:)"
      ],
      "title": "Creating custom metric logs"
    },
    {
      "anchor": "Measuring-an-extended-launch",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/extendLaunchMeasurement(forTaskID:)",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/finishExtendedLaunchMeasurement(forTaskID:)",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLaunchTaskID"
      ],
      "title": "Measuring an extended launch"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MXMetricManager"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-shared-metrics-manager",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/shared"
              ],
              "title": "Getting the shared metrics manager"
            },
            {
              "anchor": "Subscribing-to-reports",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/add(_:)",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/remove(_:)"
              ],
              "title": "Subscribing to reports"
            },
            {
              "anchor": "Retrieving-previous-reports",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/pastPayloads",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/pastDiagnosticPayloads"
              ],
              "title": "Retrieving previous reports"
            },
            {
              "anchor": "Creating-custom-metric-logs",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/makeLogHandle(category:)"
              ],
              "title": "Creating custom metric logs"
            },
            {
              "anchor": "Measuring-an-extended-launch",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/extendLaunchMeasurement(forTaskID:)",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager/finishExtendedLaunchMeasurement(forTaskID:)",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLaunchTaskID"
              ],
              "title": "Measuring an extended launch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MXMetricManager"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/title",
          "value": "MXMetricPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1makeLogHandle(category:)/title",
          "value": "makeLogHandleWithCategory:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1makeLogHandle(category:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "makeLogHandleWithCategory:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager/title",
          "value": "MXMetricManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1pastDiagnosticPayloads/title",
          "value": "pastDiagnosticPayloads"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1pastDiagnosticPayloads/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pastDiagnosticPayloads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1remove(_:)/title",
          "value": "removeSubscriber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1remove(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeSubscriber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/title",
          "value": "MXDiagnosticPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLaunchTaskID/title",
          "value": "MXLaunchTaskID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLaunchTaskID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXLaunchTaskID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLaunchTaskID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXLaunchTaskID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1extendLaunchMeasurement(forTaskID:)/title",
          "value": "extendLaunchMeasurementForTaskID:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1extendLaunchMeasurement(forTaskID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "extendLaunchMeasurementForTaskID:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1finishExtendedLaunchMeasurement(forTaskID:)/title",
          "value": "finishExtendedLaunchMeasurementForTaskID:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1finishExtendedLaunchMeasurement(forTaskID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "finishExtendedLaunchMeasurementForTaskID:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1pastPayloads/title",
          "value": "pastPayloads"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1pastPayloads/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pastPayloads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManagerSubscriber/title",
          "value": "MXMetricManagerSubscriber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManagerSubscriber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManagerSubscriber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManagerSubscriber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManagerSubscriber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1add(_:)/title",
          "value": "addSubscriber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1add(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addSubscriber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1shared/title",
          "value": "sharedManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager~1shared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxmetricmanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxmetricmanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
