{
  "abstract": [
    {
      "text": "An object that encapsulates a daily metrics report.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXMetricPayload",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MXMetricPayload"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MXMetricPayload"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MXMetricPayload"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload": {
      "abstract": [
        {
          "text": "An object that encapsulates a diagnostic report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiagnosticPayload"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiagnosticPayload"
        }
      ],
      "role": "symbol",
      "title": "MXDiagnosticPayload",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager": {
      "abstract": [
        {
          "text": "The shared object that registers you to receive metrics, creates logs for custom metrics, and gives access to past reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetricManager"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetricManager"
        }
      ],
      "role": "symbol",
      "title": "MXMetricManager",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanager"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber": {
      "abstract": [
        {
          "text": "A protocol defining a method for receiving a daily metrics report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetricManagerSubscriber"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetricManagerSubscriber"
        }
      ],
      "role": "symbol",
      "title": "MXMetricManagerSubscriber",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricmanagersubscriber"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload": {
      "abstract": [
        {
          "text": "An object that encapsulates a daily metrics report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetricPayload"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetricPayload"
        }
      ],
      "role": "symbol",
      "title": "MXMetricPayload",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/animationMetrics": {
      "abstract": [
        {
          "text": "The metrics for the responsiveness of app animations for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animationMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXAnimationMetric",
          "text": "MXAnimationMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/animationMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animationMetrics"
        }
      ],
      "role": "symbol",
      "title": "animationMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/animationmetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationExitMetrics": {
      "abstract": [
        {
          "text": "The app foreground and background exit metrics for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationExitMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXAppExitMetric",
          "text": "MXAppExitMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationExitMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationExitMetrics"
        }
      ],
      "role": "symbol",
      "title": "applicationExitMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/applicationexitmetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationLaunchMetrics": {
      "abstract": [
        {
          "text": "The app launch and resume metrics for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationLaunchMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXAppLaunchMetric",
          "text": "MXAppLaunchMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationLaunchMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationLaunchMetrics"
        }
      ],
      "role": "symbol",
      "title": "applicationLaunchMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/applicationlaunchmetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationResponsivenessMetrics": {
      "abstract": [
        {
          "text": "The metrics indicating an app’s responsiveness to user interaction for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationResponsivenessMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXAppResponsivenessMetric",
          "text": "MXAppResponsivenessMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationResponsivenessMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationResponsivenessMetrics"
        }
      ],
      "role": "symbol",
      "title": "applicationResponsivenessMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/applicationresponsivenessmetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationTimeMetrics": {
      "abstract": [
        {
          "text": "The app foreground and background time metrics for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationTimeMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXAppRunTimeMetric",
          "text": "MXAppRunTimeMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationTimeMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationTimeMetrics"
        }
      ],
      "role": "symbol",
      "title": "applicationTimeMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/applicationtimemetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/cellularConditionMetrics": {
      "abstract": [
        {
          "text": "The cellular condition measurements for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cellularConditionMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXCellularConditionMetric",
          "text": "MXCellularConditionMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/cellularConditionMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cellularConditionMetrics"
        }
      ],
      "role": "symbol",
      "title": "cellularConditionMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/cellularconditionmetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/cpuMetrics": {
      "abstract": [
        {
          "text": "The CPU metrics for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cpuMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXCPUMetric",
          "text": "MXCPUMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/cpuMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cpuMetrics"
        }
      ],
      "role": "symbol",
      "title": "cpuMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/cpumetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/dictionaryRepresentation()": {
      "abstract": [
        {
          "text": "Returns the results of the payload as a dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dictionaryRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/dictionaryRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DictionaryRepresentation"
        }
      ],
      "role": "symbol",
      "title": "dictionaryRepresentation()",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/dictionaryrepresentation()"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/dictionaryRepresentation-1xkxj": {
      "abstract": [
        {
          "text": "Returns the results of the payload as a dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "dictionaryRepresentation"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/dictionaryRepresentation-1xkxj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dictionaryRepresentation"
        }
      ],
      "role": "symbol",
      "title": "dictionaryRepresentation",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/dictionaryrepresentation-1xkxj"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/diskIOMetrics": {
      "abstract": [
        {
          "text": "The storage metrics for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diskIOMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXDiskIOMetric",
          "text": "MXDiskIOMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/diskIOMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "diskIOMetrics"
        }
      ],
      "role": "symbol",
      "title": "diskIOMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/diskiometrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/displayMetrics": {
      "abstract": [
        {
          "text": "The display metrics for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXDisplayMetric",
          "text": "MXDisplayMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/displayMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayMetrics"
        }
      ],
      "role": "symbol",
      "title": "displayMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/displaymetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/gpuMetrics": {
      "abstract": [
        {
          "text": "The GPU metrics for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gpuMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXGPUMetric",
          "text": "MXGPUMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/gpuMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gpuMetrics"
        }
      ],
      "role": "symbol",
      "title": "gpuMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/gpumetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/includesMultipleApplicationVersions": {
      "abstract": [
        {
          "text": "A Boolean indicating if the version of the app changed at least once during the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includesMultipleApplicationVersions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/includesMultipleApplicationVersions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "includesMultipleApplicationVersions"
        }
      ],
      "role": "symbol",
      "title": "includesMultipleApplicationVersions",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/includesmultipleapplicationversions"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/jsonRepresentation()": {
      "abstract": [
        {
          "text": "Returns the contents of the payload in JSON format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jsonRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/jsonRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSONRepresentation"
        }
      ],
      "role": "symbol",
      "title": "jsonRepresentation()",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/jsonrepresentation()"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/latestApplicationVersion": {
      "abstract": [
        {
          "text": "The version of the app on the device at the end of the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latestApplicationVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/latestApplicationVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "latestApplicationVersion"
        }
      ],
      "role": "symbol",
      "title": "latestApplicationVersion",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/latestapplicationversion"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/locationActivityMetrics": {
      "abstract": [
        {
          "text": "The location-tracking activity for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationActivityMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXLocationActivityMetric",
          "text": "MXLocationActivityMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/locationActivityMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationActivityMetrics"
        }
      ],
      "role": "symbol",
      "title": "locationActivityMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/locationactivitymetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/memoryMetrics": {
      "abstract": [
        {
          "text": "The memory metrics for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memoryMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXMemoryMetric",
          "text": "MXMemoryMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/memoryMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "memoryMetrics"
        }
      ],
      "role": "symbol",
      "title": "memoryMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/memorymetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/metaData": {
      "abstract": [
        {
          "text": "A set of system-level information for the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metaData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXMetaData",
          "text": "MXMetaData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/metaData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metaData"
        }
      ],
      "role": "symbol",
      "title": "metaData",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/metadata"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/networkTransferMetrics": {
      "abstract": [
        {
          "text": "The network-transfer activity for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkTransferMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXNetworkTransferMetric",
          "text": "MXNetworkTransferMetric"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/networkTransferMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkTransferMetrics"
        }
      ],
      "role": "symbol",
      "title": "networkTransferMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/networktransfermetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/signpostMetrics": {
      "abstract": [
        {
          "text": "An array of the custom metrics for the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signpostMetrics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXSignpostMetric",
          "text": "MXSignpostMetric"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/signpostMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signpostMetrics"
        }
      ],
      "role": "symbol",
      "title": "signpostMetrics",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/signpostmetrics"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampBegin": {
      "abstract": [
        {
          "text": "The starting time of the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStampBegin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampBegin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeStampBegin"
        }
      ],
      "role": "symbol",
      "title": "timeStampBegin",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/timestampbegin"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampEnd": {
      "abstract": [
        {
          "text": "The ending time of the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStampEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeStampEnd"
        }
      ],
      "role": "symbol",
      "title": "timeStampEnd",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/timestampend"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reading-battery-metrics",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/cellularConditionMetrics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/cpuMetrics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/displayMetrics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/gpuMetrics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/locationActivityMetrics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/networkTransferMetrics"
      ],
      "title": "Reading battery metrics"
    },
    {
      "anchor": "Reading-performance-metrics",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationExitMetrics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationTimeMetrics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/memoryMetrics"
      ],
      "title": "Reading performance metrics"
    },
    {
      "anchor": "Reading-responsiveness-metrics",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationLaunchMetrics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/animationMetrics",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationResponsivenessMetrics"
      ],
      "title": "Reading responsiveness metrics"
    },
    {
      "anchor": "Reading-disk-access-metrics",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/diskIOMetrics"
      ],
      "title": "Reading disk access metrics"
    },
    {
      "anchor": "Reading-custom-metrics",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/signpostMetrics"
      ],
      "title": "Reading custom metrics"
    },
    {
      "anchor": "Generating-a-report",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/jsonRepresentation()",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/dictionaryRepresentation()"
      ],
      "title": "Generating a report"
    },
    {
      "anchor": "Reading-information-about-the-payload",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampBegin",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampEnd",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/includesMultipleApplicationVersions",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/latestApplicationVersion",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/metaData"
      ],
      "title": "Reading information about the payload"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MXMetricPayload"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reading-battery-metrics",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/cellularConditionMetrics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/cpuMetrics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/displayMetrics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/gpuMetrics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/locationActivityMetrics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/networkTransferMetrics"
              ],
              "title": "Reading battery metrics"
            },
            {
              "anchor": "Reading-performance-metrics",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationExitMetrics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationTimeMetrics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/memoryMetrics"
              ],
              "title": "Reading performance metrics"
            },
            {
              "anchor": "Reading-responsiveness-metrics",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationLaunchMetrics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/animationMetrics",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/applicationResponsivenessMetrics"
              ],
              "title": "Reading responsiveness metrics"
            },
            {
              "anchor": "Reading-disk-access-metrics",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/diskIOMetrics"
              ],
              "title": "Reading disk access metrics"
            },
            {
              "anchor": "Reading-custom-metrics",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/signpostMetrics"
              ],
              "title": "Reading custom metrics"
            },
            {
              "anchor": "Generating-a-report",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/jsonRepresentation()",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/dictionaryRepresentation-1xkxj",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/dictionaryRepresentation()"
              ],
              "title": "Generating a report"
            },
            {
              "anchor": "Reading-information-about-the-payload",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampBegin",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampEnd",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/includesMultipleApplicationVersions",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/latestApplicationVersion",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/metaData"
              ],
              "title": "Reading information about the payload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManager",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricManagerSubscriber"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MXMetricPayload"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1cellularConditionMetrics/title",
          "value": "cellularConditionMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1cellularConditionMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cellularConditionMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1timeStampEnd/title",
          "value": "timeStampEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1timeStampEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStampEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager/title",
          "value": "MXMetricManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1timeStampBegin/title",
          "value": "timeStampBegin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1timeStampBegin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStampBegin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1includesMultipleApplicationVersions/title",
          "value": "includesMultipleApplicationVersions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1includesMultipleApplicationVersions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includesMultipleApplicationVersions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1dictionaryRepresentation()/title",
          "value": "DictionaryRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1dictionaryRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "DictionaryRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1displayMetrics/title",
          "value": "displayMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1displayMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1latestApplicationVersion/title",
          "value": "latestApplicationVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1latestApplicationVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "latestApplicationVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1cpuMetrics/title",
          "value": "cpuMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1cpuMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cpuMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1applicationTimeMetrics/title",
          "value": "applicationTimeMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1applicationTimeMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationTimeMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1gpuMetrics/title",
          "value": "gpuMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1gpuMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gpuMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/title",
          "value": "MXDiagnosticPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1applicationLaunchMetrics/title",
          "value": "applicationLaunchMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1applicationLaunchMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationLaunchMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1diskIOMetrics/title",
          "value": "diskIOMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1diskIOMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "diskIOMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/title",
          "value": "MXMetricPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1animationMetrics/title",
          "value": "animationMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1animationMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "animationMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1applicationResponsivenessMetrics/title",
          "value": "applicationResponsivenessMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1applicationResponsivenessMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationResponsivenessMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1locationActivityMetrics/title",
          "value": "locationActivityMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1locationActivityMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locationActivityMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1metaData/title",
          "value": "metaData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1metaData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metaData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1signpostMetrics/title",
          "value": "signpostMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1signpostMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signpostMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1applicationExitMetrics/title",
          "value": "applicationExitMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1applicationExitMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationExitMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1memoryMetrics/title",
          "value": "memoryMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1memoryMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "memoryMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManagerSubscriber/title",
          "value": "MXMetricManagerSubscriber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManagerSubscriber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManagerSubscriber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricManagerSubscriber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricManagerSubscriber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1jsonRepresentation()/title",
          "value": "JSONRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1jsonRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "JSONRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1networkTransferMetrics/title",
          "value": "networkTransferMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1networkTransferMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkTransferMetrics"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxmetricpayload"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxmetricpayload"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
