{
  "abstract": [
    {
      "text": "An abstract data class for a metric.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXMetric"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXMetric",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MXMetric"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MXMetric"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MXMetric"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MXMetric"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAnimationMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the responsiveness of animation in the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXAnimationMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAnimationMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXAnimationMetric"
        }
      ],
      "role": "symbol",
      "title": "MXAnimationMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxanimationmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the types of foreground and background app exits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXAppExitMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXAppExitMetric"
        }
      ],
      "role": "symbol",
      "title": "MXAppExitMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxappexitmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAppLaunchMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about app launch time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXAppLaunchMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAppLaunchMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXAppLaunchMetric"
        }
      ],
      "role": "symbol",
      "title": "MXAppLaunchMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxapplaunchmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAppResponsivenessMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the responsiveness of the app to user interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXAppResponsivenessMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAppResponsivenessMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXAppResponsivenessMetric"
        }
      ],
      "role": "symbol",
      "title": "MXAppResponsivenessMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxappresponsivenessmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAppRunTimeMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the amount of time the app is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXAppRunTimeMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAppRunTimeMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXAppRunTimeMetric"
        }
      ],
      "role": "symbol",
      "title": "MXAppRunTimeMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxappruntimemetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAverage": {
      "abstract": [
        {
          "text": "A unit of measure for an average.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXAverage"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAverage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXAverage"
        }
      ],
      "role": "symbol",
      "title": "MXAverage",
      "type": "topic",
      "url": "/documentation/metrickit/mxaverage"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCPUMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the use of the CPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCPUMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCPUMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCPUMetric"
        }
      ],
      "role": "symbol",
      "title": "MXCPUMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxcpumetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCallStackTree": {
      "abstract": [
        {
          "text": "An object representing the call stack for an exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCallStackTree"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCallStackTree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCallStackTree"
        }
      ],
      "role": "symbol",
      "title": "MXCallStackTree",
      "type": "topic",
      "url": "/documentation/metrickit/mxcallstacktree"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCellularConditionMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the condition of the cellular network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCellularConditionMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCellularConditionMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCellularConditionMetric"
        }
      ],
      "role": "symbol",
      "title": "MXCellularConditionMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxcellularconditionmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnosticObjectiveCExceptionReason": {
      "abstract": [
        {
          "text": "An object that represents the exception reason for an uncaught ObjC exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCrashDiagnosticObjectiveCExceptionReason"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnosticObjectiveCExceptionReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCrashDiagnosticObjectiveCExceptionReason"
        }
      ],
      "role": "symbol",
      "title": "MXCrashDiagnosticObjectiveCExceptionReason",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnosticobjectivecexceptionreason"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic": {
      "abstract": [
        {
          "text": "An abstract data class for a diagnostic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "MXDiagnostic",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnostic"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiskIOMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about disk usage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiskIOMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiskIOMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiskIOMetric"
        }
      ],
      "role": "symbol",
      "title": "MXDiskIOMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiskiometric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDisplayMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the power used to display the app on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDisplayMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDisplayMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDisplayMetric"
        }
      ],
      "role": "symbol",
      "title": "MXDisplayMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxdisplaymetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError": {
      "abstract": [
        {
          "text": "Error domain for error handling of app metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXError"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXError"
        }
      ],
      "role": "symbol",
      "title": "MXError",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code": {
      "abstract": [
        {
          "text": "Error codes for error values from app metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MXError.Code",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/code"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain": {
      "abstract": [
        {
          "text": "Error domain for error values from app metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MXErrorDomain",
      "type": "topic",
      "url": "/documentation/metrickit/mxerrordomain"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXGPUMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the use of the GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXGPUMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXGPUMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXGPUMetric"
        }
      ],
      "role": "symbol",
      "title": "MXGPUMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxgpumetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXHistogram": {
      "abstract": [
        {
          "text": "An object representing a histogram of data values of the same type of unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXHistogram"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXHistogram",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXHistogram"
        }
      ],
      "role": "symbol",
      "title": "MXHistogram",
      "type": "topic",
      "url": "/documentation/metrickit/mxhistogram"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the use of location-tracking features of a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXLocationActivityMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXLocationActivityMetric"
        }
      ],
      "role": "symbol",
      "title": "MXLocationActivityMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMemoryMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the app’s memory use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMemoryMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMemoryMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMemoryMetric"
        }
      ],
      "role": "symbol",
      "title": "MXMemoryMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxmemorymetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetaData": {
      "abstract": [
        {
          "text": "An object containing system-level information about the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetaData"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetaData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetaData"
        }
      ],
      "role": "symbol",
      "title": "MXMetaData",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetadata"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetric": {
      "abstract": [
        {
          "text": "An abstract data class for a metric.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetric"
        }
      ],
      "role": "symbol",
      "title": "MXMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/dictionaryRepresentation()": {
      "abstract": [
        {
          "text": "Returns the contents of a metric as a Dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dictionaryRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/dictionaryRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DictionaryRepresentation"
        }
      ],
      "role": "symbol",
      "title": "dictionaryRepresentation()",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetric/dictionaryrepresentation()"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/dictionaryRepresentation-7zeik": {
      "abstract": [
        {
          "text": "Returns the contents of a metric as a Dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "dictionaryRepresentation"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/dictionaryRepresentation-7zeik",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dictionaryRepresentation"
        }
      ],
      "role": "symbol",
      "title": "dictionaryRepresentation",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetric/dictionaryrepresentation-7zeik"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/jsonRepresentation()": {
      "abstract": [
        {
          "text": "Returns the contents of the metric in JSON format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jsonRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/jsonRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSONRepresentation"
        }
      ],
      "role": "symbol",
      "title": "jsonRepresentation()",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetric/jsonrepresentation()"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXNetworkTransferMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about network transfers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXNetworkTransferMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXNetworkTransferMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXNetworkTransferMetric"
        }
      ],
      "role": "symbol",
      "title": "MXNetworkTransferMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxnetworktransfermetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostMetric": {
      "abstract": [
        {
          "text": "An object representing a custom metric.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXSignpostMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXSignpostMetric"
        }
      ],
      "role": "symbol",
      "title": "MXSignpostMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxsignpostmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostRecord": {
      "abstract": [
        {
          "text": "An object representing the record for a signpost interval or event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXSignpostRecord"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXSignpostRecord"
        }
      ],
      "role": "symbol",
      "title": "MXSignpostRecord",
      "type": "topic",
      "url": "/documentation/metrickit/mxsignpostrecord"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXAnimationMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXAppLaunchMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXAppResponsivenessMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXAppRunTimeMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCPUMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCellularConditionMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiskIOMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDisplayMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXGPUMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMemoryMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXNetworkTransferMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostMetric"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXCallStackTree",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetaData",
        "doc://com.apple.metrickit/documentation/MetricKit/MXAverage",
        "doc://com.apple.metrickit/documentation/MetricKit/MXHistogram",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code",
        "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnosticObjectiveCExceptionReason",
        "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostRecord"
      ],
      "title": "Data types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Generate-a-report",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/jsonRepresentation()",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/dictionaryRepresentation()"
      ],
      "title": "Generate a report"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MXMetric"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Generate-a-report",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/dictionaryRepresentation-7zeik",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/jsonRepresentation()",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetric/dictionaryRepresentation()"
              ],
              "title": "Generate a report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXAnimationMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXAppExitMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXAppLaunchMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXAppResponsivenessMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXAppRunTimeMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCPUMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCellularConditionMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiskIOMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDisplayMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXGPUMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMemoryMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXNetworkTransferMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostMetric"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXCallStackTree",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetaData",
                "doc://com.apple.metrickit/documentation/MetricKit/MXAverage",
                "doc://com.apple.metrickit/documentation/MetricKit/MXHistogram",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic",
                "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code",
                "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnosticObjectiveCExceptionReason",
                "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostRecord"
              ],
              "title": "Data types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MXMetric"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCallStackTree/title",
          "value": "MXCallStackTree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCallStackTree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCallStackTree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCallStackTree/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCallStackTree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppExitMetric/title",
          "value": "MXAppExitMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppExitMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppExitMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppExitMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppExitMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCPUMetric/title",
          "value": "MXCPUMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCPUMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCPUMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric/title",
          "value": "MXMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskIOMetric/title",
          "value": "MXDiskIOMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskIOMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiskIOMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiskIOMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiskIOMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMemoryMetric/title",
          "value": "MXMemoryMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMemoryMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMemoryMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMemoryMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMemoryMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppRunTimeMetric/title",
          "value": "MXAppRunTimeMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppRunTimeMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppRunTimeMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppRunTimeMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppRunTimeMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/title",
          "value": "MXDiagnostic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAnimationMetric/title",
          "value": "MXAnimationMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAnimationMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAnimationMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAnimationMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAnimationMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXSignpostMetric/title",
          "value": "MXSignpostMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXSignpostMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXSignpostMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXSignpostMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXSignpostMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXErrorDomain/title",
          "value": "MXErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric/title",
          "value": "MXLocationActivityMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXLocationActivityMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXLocationActivityMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXSignpostRecord/title",
          "value": "MXSignpostRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXSignpostRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXSignpostRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXSignpostRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXSignpostRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric~1dictionaryRepresentation()/title",
          "value": "DictionaryRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric~1dictionaryRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "DictionaryRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnosticObjectiveCExceptionReason/title",
          "value": "MXCrashDiagnosticObjectiveCExceptionReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnosticObjectiveCExceptionReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCrashDiagnosticObjectiveCExceptionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnosticObjectiveCExceptionReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCrashDiagnosticObjectiveCExceptionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXHistogram/title",
          "value": "MXHistogram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXHistogram/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXHistogram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXHistogram/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXHistogram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetaData/title",
          "value": "MXMetaData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetaData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetaData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetaData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetaData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDisplayMetric/title",
          "value": "MXDisplayMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDisplayMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDisplayMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDisplayMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDisplayMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCellularConditionMetric/title",
          "value": "MXCellularConditionMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCellularConditionMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCellularConditionMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCellularConditionMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCellularConditionMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppResponsivenessMetric/title",
          "value": "MXAppResponsivenessMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppResponsivenessMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppResponsivenessMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppResponsivenessMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppResponsivenessMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXNetworkTransferMetric/title",
          "value": "MXNetworkTransferMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXNetworkTransferMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXNetworkTransferMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXNetworkTransferMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXNetworkTransferMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXGPUMetric/title",
          "value": "MXGPUMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXGPUMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXGPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXGPUMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXGPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code/title",
          "value": "MXErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric~1jsonRepresentation()/title",
          "value": "JSONRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric~1jsonRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "JSONRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAverage/title",
          "value": "MXAverage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAverage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAverage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAverage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAverage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppLaunchMetric/title",
          "value": "MXAppLaunchMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppLaunchMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppLaunchMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAppLaunchMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAppLaunchMetric"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxmetric"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxmetric"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
