{
  "abstract": [
    {
      "text": "The type of alert that the app may display when the device is unlocked.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/alertStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UNNotificationSettings(py)alertStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "alertStyle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UNAlertStyle",
        "text": "UNAlertStyle"
      }
    ],
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "alertStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "alertStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "alertStyle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAlertStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UNAlertStyle",
              "text": "UNAlertStyle"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When alerts are authorized, this property specifies the presentation style for alerts when the device is unlocked. The user may choose to display alerts as automatically disappearing banners or as modal windows that require explicit dismissal. The user may also choose not to display alerts at all.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAlertStyle": {
      "abstract": [
        {
          "text": "Constants indicating the presentation styles for alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNAlertStyle"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAlertStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAlertStyle"
        }
      ],
      "role": "symbol",
      "title": "UNAlertStyle",
      "type": "topic",
      "url": "/documentation/usernotifications/unalertstyle"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings": {
      "abstract": [
        {
          "text": "The object for managing notification-related settings and the authorization status of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationSettings"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationSettings"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationSettings",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsettings"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/alertStyle": {
      "abstract": [
        {
          "text": "The type of alert that the app may display when the device is unlocked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alertStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAlertStyle",
          "text": "UNAlertStyle"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/alertStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alertStyle"
        }
      ],
      "role": "symbol",
      "title": "alertStyle",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsettings/alertstyle"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/providesAppNotificationSettings": {
      "abstract": [
        {
          "text": "A Boolean value indicating the system displays a button for in-app notification settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providesAppNotificationSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/providesAppNotificationSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "providesAppNotificationSettings"
        }
      ],
      "role": "symbol",
      "title": "providesAppNotificationSettings",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsettings/providesappnotificationsettings"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/showPreviewsSetting": {
      "abstract": [
        {
          "text": "The setting that indicates whether the app shows a preview of the notification’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showPreviewsSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNShowPreviewsSetting",
          "text": "UNShowPreviewsSetting"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/showPreviewsSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showPreviewsSetting"
        }
      ],
      "role": "symbol",
      "title": "showPreviewsSetting",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsettings/showpreviewssetting"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNShowPreviewsSetting": {
      "abstract": [
        {
          "text": "Constants indicating the style previewing a notification’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNShowPreviewsSetting"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNShowPreviewsSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNShowPreviewsSetting"
        }
      ],
      "role": "symbol",
      "title": "UNShowPreviewsSetting",
      "type": "topic",
      "url": "/documentation/usernotifications/unshowpreviewssetting"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Interface-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNAlertStyle",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/showPreviewsSetting",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNShowPreviewsSetting",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/providesAppNotificationSettings"
      ],
      "title": "Getting Interface Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "alertStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alertStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.usernotifications/documentation/UserNotifications",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Interface-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNAlertStyle",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/showPreviewsSetting",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNShowPreviewsSetting",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/providesAppNotificationSettings"
              ],
              "title": "Getting Interface Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAlertStyle",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UNAlertStyle",
                    "text": "UNAlertStyle"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "alertStyle"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAlertStyle",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UNAlertStyle",
                    "text": "UNAlertStyle"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "alertStyle"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings~1alertStyle/title",
          "value": "alertStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings~1alertStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alertStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAlertStyle/title",
          "value": "UNAlertStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAlertStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAlertStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAlertStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAlertStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings/title",
          "value": "UNNotificationSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNShowPreviewsSetting/title",
          "value": "UNShowPreviewsSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNShowPreviewsSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNShowPreviewsSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNShowPreviewsSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNShowPreviewsSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings~1providesAppNotificationSettings/title",
          "value": "providesAppNotificationSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings~1providesAppNotificationSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "providesAppNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings~1showPreviewsSetting/title",
          "value": "showPreviewsSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings~1showPreviewsSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showPreviewsSetting"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/unnotificationsettings/alertstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotifications/unnotificationsettings/alertstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
