{
  "abstract": [
    {
      "text": "An array of values for additional axes for the data point.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint/additionalValues"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AXDataPoint(py)additionalValues",
    "fragments": [
      {
        "kind": "identifier",
        "text": "additionalValues"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "additionalValues"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "additionalValues"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<AXDataPointValue *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "additionalValues"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Provide these values in the same order as their corresponding ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXDataAxisDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "objects in ",
              "type": "text"
            },
            {
              "code": "Accessibility/AXChartDescriptor/additionalAxes",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXDataAxisDescriptor": {
      "abstract": [
        {
          "text": "The basic interface for a data axis in a chart.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXDataAxisDescriptor"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXDataAxisDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXDataAxisDescriptor"
        }
      ],
      "role": "symbol",
      "title": "AXDataAxisDescriptor",
      "type": "topic",
      "url": "/documentation/accessibility/axdataaxisdescriptor"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint": {
      "abstract": [
        {
          "text": "An object that represents a single data point in a chart.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXDataPoint"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXDataPoint"
        }
      ],
      "role": "symbol",
      "title": "AXDataPoint",
      "type": "topic",
      "url": "/documentation/accessibility/axdatapoint"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint/additionalValues": {
      "abstract": [
        {
          "text": "An array of values for additional axes for the data point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "additionalValues"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint/additionalValues",
      "kind": "symbol",
      "role": "symbol",
      "title": "additionalValues",
      "type": "topic",
      "url": "/documentation/accessibility/axdatapoint/additionalvalues"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint/xValue": {
      "abstract": [
        {
          "text": "The value of the x-axis for the data point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXDataPointValue",
          "text": "AXDataPointValue"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint/xValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xValue"
        }
      ],
      "role": "symbol",
      "title": "xValue",
      "type": "topic",
      "url": "/documentation/accessibility/axdatapoint/xvalue"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint/yValue": {
      "abstract": [
        {
          "text": "The value of the y-axis for the data point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXDataPointValue",
          "text": "AXDataPointValue"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint/yValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "yValue"
        }
      ],
      "role": "symbol",
      "title": "yValue",
      "type": "topic",
      "url": "/documentation/accessibility/axdatapoint/yvalue"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPointValue": {
      "abstract": [
        {
          "text": "A single data value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXDataPointValue"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPointValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXDataPointValue"
        }
      ],
      "role": "symbol",
      "title": "AXDataPointValue",
      "type": "topic",
      "url": "/documentation/accessibility/axdatapointvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-data-value",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint/xValue",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPoint/yValue",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXDataPointValue"
      ],
      "title": "Specifying the data value"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataPoint/title",
          "value": "AXDataPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXDataPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXDataPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataPointValue/title",
          "value": "AXDataPointValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataPointValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXDataPointValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataPointValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXDataPointValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataPoint~1xValue/title",
          "value": "xValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataPoint~1xValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataPoint~1yValue/title",
          "value": "yValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataPoint~1yValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "yValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataAxisDescriptor/title",
          "value": "AXDataAxisDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataAxisDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataAxisDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXDataAxisDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/axdatapoint/additionalvalues"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
