{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropSession"]]},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"loadObjectsOfClass:completion:"}],"modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadObjects"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofClass"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)NSItemProviderReading","kind":"typeIdentifier","text":"NSItemProviderReading"},{"kind":"text","text":".Type, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ([any "},{"preciseIdentifier":"c:objc(pl)NSItemProviderReading","kind":"typeIdentifier","text":"NSItemProviderReading"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSProgress","kind":"typeIdentifier","text":"Progress"}],"role":"symbol","symbolKind":"method","required":true,"platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"11.0"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"11.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1"},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0"}],"roleHeading":"Instance Method","title":"loadObjects(ofClass:completion:)","externalID":"c:objc(pl)UIDropSession(im)loadObjectsOfClass:completion:"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadObjects"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofClass"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aClass"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)NSItemProviderReading","kind":"typeIdentifier","text":"NSItemProviderReading","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading"},{"kind":"text","text":".Type, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ([any "},{"preciseIdentifier":"c:objc(pl)NSItemProviderReading","kind":"typeIdentifier","text":"NSItemProviderReading","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void","identifier":"doc://com.externally.resolved.symbol/s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSProgress","text":"Progress","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSProgress"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A class conforming to the ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading","isActive":true,"type":"reference"},{"text":" protocol.","type":"text"}]}],"name":"aClass"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block that is executed after all objects are loaded."}]}],"name":"completion"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An aggregate of the load progress for each object that is loaded."}]}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination"]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"You can use this method only in the drop interaction delegate’s implementation of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)"},{"text":" method. This method is called after the user drops the items into the destination view.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The completion handler is called on the main queue. It provides an array of all objects created, in the same order that the drag items were added to the drag session."}],"type":"paragraph"}]}],"defaultImplementationsSections":[{"title":"UIDropSession Implementations","anchor":"UIDropSession-Implementations","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)-3ab01"]}],"abstract":[{"text":"Creates and loads a new instance of the specified class for each drag item in the session.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/uikit/uidropsession/loadobjects(ofclass:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uidropsession/loadobjects(ofclass:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.externally.resolved.symbol/s:s4Voida":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Void"},{"kind":"text","text":" = ()"}],"abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}],"title":"Void","url":"/documentation/Swift/Void","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s4Voida"},"doc://com.externally.resolved.symbol/c:objc(cs)NSProgress":{"kind":"symbol","abstract":[{"text":"An object that conveys ongoing progress to the user for a specified task.","type":"text"}],"url":"/documentation/foundation/progress","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSProgress","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"Progress","kind":"identifier"}],"title":"Progress"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)":{"navigatorTitle":[{"kind":"identifier","text":"dropInteraction:performDrop:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"performDrop"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDropSession","text":"UIDropSession"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)","abstract":[{"type":"text","text":"Tells the delegate it can request the item provider data from the session’s drag items."}],"title":"dropInteraction(_:performDrop:)","url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:performdrop:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)-3ab01":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadObjects","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"ofClass","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":".Type, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Progress","preciseIdentifier":"c:objc(cs)NSProgress"}],"url":"/documentation/uikit/uidropsession/loadobjects(ofclass:completion:)-3ab01","abstract":[],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)-3ab01","title":"loadObjects(ofClass:completion:)","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading":{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading","type":"topic","role":"symbol","url":"/documentation/foundation/nsitemproviderreading","kind":"symbol","title":"NSItemProviderReading","abstract":[{"type":"text","text":"The protocol for implementing a class to allow an item provider to create an instance of the class."}],"fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSItemProviderReading"}]},"doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)":{"url":"/documentation/uikit/uidropsession/loadobjects(ofclass:completion:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)","abstract":[{"type":"text","text":"Creates and loads a new instance of the specified class for each drag item in the session."}],"title":"loadObjects(ofClass:completion:)","required":true,"navigatorTitle":[{"text":"loadObjectsOfClass:completion:","kind":"identifier"}],"role":"symbol","defaultImplementations":1,"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ofClass","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"NSItemProviderReading","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSItemProviderReading"},{"kind":"text","text":".Type, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ([any "},{"preciseIdentifier":"c:objc(pl)NSItemProviderReading","kind":"typeIdentifier","text":"NSItemProviderReading"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSProgress","kind":"typeIdentifier","text":"Progress"}]},"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading":{"fragments":[{"text":"protocol ","kind":"text"},{"text":"NSItemProviderReading","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The protocol for implementing a class to allow an item provider to create an instance of the class."}],"role":"symbol","kind":"symbol","url":"/documentation/foundation/nsitemproviderreading","identifier":"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading","title":"NSItemProviderReading"},"doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination":{"role":"article","title":"Making a view into a drop destination","url":"/documentation/uikit/making-a-view-into-a-drop-destination","identifier":"doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination","type":"topic","kind":"article","abstract":[{"text":"Adopt drop interaction APIs to selectively consume dragged content.","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDropSession":{"abstract":[{"type":"text","text":"The interface for querying a drop session about its state and associated drag items."}],"url":"/documentation/uikit/uidropsession","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","title":"UIDropSession","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIDropSession","kind":"identifier"}],"navigatorTitle":[{"text":"UIDropSession","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"11.0"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"11.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1"},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"loadObjectsOfClass:completion:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"loadObjectsOfClass:completion:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropSession"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSProgress","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSProgress","text":"NSProgress"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"loadObjectsOfClass:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:QOobjc(pl)NSItemProviderReading","text":"Class<NSItemProviderReading>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aClass"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<__kindof id<NSItemProviderReading>>"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"objects"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"name":"aClass","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A class conforming to the "},{"identifier":"doc://com.apple.documentation/documentation/foundation/nsitemproviderreading","type":"reference","isActive":true},{"type":"text","text":" protocol."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The block that is executed after all objects are loaded."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An aggregate of the load progress for each object that is loaded."}]}]},"path":"/primaryContentSections/2"},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSProgress/title","value":"NSProgress"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:performDrop:)/title","value":"dropInteraction:performDrop:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:performDrop:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:performDrop:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1loadObjects(ofClass:completion:)/title","value":"loadObjectsOfClass:completion:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1loadObjects(ofClass:completion:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadObjectsOfClass:completion:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/title","value":"UIDropSession"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/fragments","value":[{"text":"UIDropSession","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/navigatorTitle","value":[{"text":"UIDropSession","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}