{
  "abstract": [
    {
      "text": "The start and end points of a route, along with the planned mode of transportation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MapKit",
    "externalID": "c:objc(cs)MKDirectionsRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Request"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Request"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MKDirections.Request"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Request"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object when requesting or providing directions. If your app provides directions, use this class to decode the URL that the Maps app sends to you. If you need to request directions from Apple, pass an instance of this class to an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. For example, an app that provides subway directions might request walking directions to and from relevant subway stations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Prior to iOS 14, for apps that provide directions, you receive direction-related URLs in your app delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:open:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "method. Upon receiving a URL, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/isDirectionsRequest(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of this class to determine whether the URL relates to routing directions. If it does, create an instance of this class using the provided URL and extract the map items associated with the start and end points.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Prior to iOS 14, to provide routing directions, your app needs to include special keys in its ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file and be able to handle URLs that the Maps app sends to it. These keys indicate a special URL type that you app needs to handle. For information about how to implement this support, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:open:options:)": {
      "abstract": [
        {
          "text": "Asks the delegate to open a resource specified by a URL, and provides a dictionary of launch options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "app"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "open"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIApplicationOpenURLOptionsKey",
          "text": "OpenURLOptionsKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "] = [:]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:open:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:open:options:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:open:options:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections": {
      "abstract": [
        {
          "text": "A utility object that computes directions and travel-time information based on the route information you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKDirections"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDirections"
        }
      ],
      "role": "symbol",
      "title": "MKDirections",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/ETAResponse": {
      "abstract": [
        {
          "text": "The travel-time information that Apple servers return.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ETAResponse"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/ETAResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ETAResponse"
        }
      ],
      "role": "symbol",
      "title": "MKDirections.ETAResponse",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/etaresponse"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request": {
      "abstract": [
        {
          "text": "The start and end points of a route, along with the planned mode of transportation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Request"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Request"
        }
      ],
      "role": "symbol",
      "title": "MKDirections.Request",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/arrivalDate": {
      "abstract": [
        {
          "text": "The arrival date for the trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrivalDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/arrivalDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrivalDate"
        }
      ],
      "role": "symbol",
      "title": "arrivalDate",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request/arrivaldate"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/departureDate": {
      "abstract": [
        {
          "text": "The departure date for the trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "departureDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/departureDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "departureDate"
        }
      ],
      "role": "symbol",
      "title": "departureDate",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request/departuredate"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/destination": {
      "abstract": [
        {
          "text": "The end point for routing directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/destination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destination"
        }
      ],
      "role": "symbol",
      "title": "destination",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request/destination"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/highwayPreference": {
      "abstract": [
        {
          "text": "The value that indicates whether the framework uses or avoids highways when providing directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highwayPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKDirections",
          "text": "MKDirections"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKDirectionsRoutePreference",
          "text": "RoutePreference"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/highwayPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highwayPreference"
        }
      ],
      "role": "symbol",
      "title": "highwayPreference",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request/highwaypreference"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/init(contentsOfURL:)": {
      "abstract": [
        {
          "text": "Creates and returns a directions request object using the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentsOfURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/init(contentsOfURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentsOfURL:"
        }
      ],
      "role": "symbol",
      "title": "init(contentsOfURL:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request/init(contentsofurl:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/isDirectionsRequest(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the specified URL contains a directions request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDirectionsRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/isDirectionsRequest(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isDirectionsRequestURL:"
        }
      ],
      "role": "symbol",
      "title": "isDirectionsRequest(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request/isdirectionsrequest(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/requestsAlternateRoutes": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app requests multiple routes when they’re available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestsAlternateRoutes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/requestsAlternateRoutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestsAlternateRoutes"
        }
      ],
      "role": "symbol",
      "title": "requestsAlternateRoutes",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request/requestsalternateroutes"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/source": {
      "abstract": [
        {
          "text": "The starting point for routing directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/source",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "source"
        }
      ],
      "role": "symbol",
      "title": "source",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request/source"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/tollPreference": {
      "abstract": [
        {
          "text": "The value that indicates whether the framework avoids routes that have tolls when providing directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tollPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKDirections",
          "text": "MKDirections"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKDirectionsRoutePreference",
          "text": "RoutePreference"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/tollPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tollPreference"
        }
      ],
      "role": "symbol",
      "title": "tollPreference",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request/tollpreference"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/transportType": {
      "abstract": [
        {
          "text": "The type of conveyance that the directions apply to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKDirectionsTransportType",
          "text": "MKDirectionsTransportType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/transportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transportType"
        }
      ],
      "role": "symbol",
      "title": "transportType",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/request/transporttype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Response": {
      "abstract": [
        {
          "text": "The route information that Apple servers return in response to your request for directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Response"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Response",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Response"
        }
      ],
      "role": "symbol",
      "title": "MKDirections.Response",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/response"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections/RoutePreference": {
      "abstract": [
        {
          "text": "Options that modify how the framework selects routes when calculating directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoutePreference"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections/RoutePreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoutePreference"
        }
      ],
      "role": "symbol",
      "title": "MKDirections.RoutePreference",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections/routepreference"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirectionsTransportType": {
      "abstract": [
        {
          "text": "Constants that specify the type of conveyance to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKDirectionsTransportType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirectionsTransportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDirectionsTransportType"
        }
      ],
      "role": "symbol",
      "title": "MKDirectionsTransportType",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirectionstransporttype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey": {
      "abstract": [
        {
          "text": "The virtual camera to use for viewing the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsCameraKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsCameraKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsCameraKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionscamerakey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault": {
      "abstract": [
        {
          "text": "Directions that match the user’s preferred transportation type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDefault"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeDefault",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodedefault"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving": {
      "abstract": [
        {
          "text": "Driving directions between the specified start and end points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDriving"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDriving"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeDriving",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodedriving"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey": {
      "abstract": [
        {
          "text": "The mode of transportation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodekey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit": {
      "abstract": [
        {
          "text": "Public transit directions between the specified start and end points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeTransit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeTransit"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeTransit",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodetransit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking": {
      "abstract": [
        {
          "text": "Walking directions between the specified start and end points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeWalking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeWalking"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeWalking",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodewalking"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey": {
      "abstract": [
        {
          "text": "The coordinate value on which to center the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapCenterKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapCenterKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsMapCenterKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsmapcenterkey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey": {
      "abstract": [
        {
          "text": "The amount of the map to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapSpanKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapSpanKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsMapSpanKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsmapspankey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey": {
      "abstract": [
        {
          "text": "The type of map (standard, satellite, or hybrid) to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapTypeKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsMapTypeKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsmaptypekey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to display traffic information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsShowsTrafficKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsShowsTrafficKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsShowsTrafficKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsshowstraffickey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKRoute": {
      "abstract": [
        {
          "text": "A single route between a requested start and end point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKRoute"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKRoute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKRoute"
        }
      ],
      "role": "symbol",
      "title": "MKRoute",
      "type": "topic",
      "url": "/documentation/mapkit/mkroute"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKRoute/Step": {
      "abstract": [
        {
          "text": "One portion of an overall route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Step"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKRoute/Step",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Step"
        }
      ],
      "role": "symbol",
      "title": "MKRoute.Step",
      "type": "topic",
      "url": "/documentation/mapkit/mkroute/step"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497": {
      "identifier": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497",
      "title": "Location and Maps Programming Guide",
      "titleInlineContent": [
        {
          "text": "Location and Maps Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Directions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Response",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/ETAResponse",
        "doc://com.apple.mapkit/documentation/MapKit/MKRoute",
        "doc://com.apple.mapkit/documentation/MapKit/MKRoute/Step"
      ],
      "title": "Directions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-directions-request-object",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/isDirectionsRequest(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/init(contentsOfURL:)"
      ],
      "title": "Creating a directions request object"
    },
    {
      "anchor": "Accessing-the-start-and-end-points",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/source",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/destination"
      ],
      "title": "Accessing the start and end points"
    },
    {
      "anchor": "Specifying-transportation-options",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/transportType",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/highwayPreference",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/tollPreference",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/RoutePreference",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/requestsAlternateRoutes",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/departureDate",
        "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/arrivalDate"
      ],
      "title": "Specifying transportation options"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKDirectionsTransportType"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Launch-options",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey"
      ],
      "title": "Launch options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKDirectionsRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirectionsRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirectionsRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-directions-request-object",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/isDirectionsRequest(_:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/init(contentsOfURL:)"
              ],
              "title": "Creating a directions request object"
            },
            {
              "anchor": "Accessing-the-start-and-end-points",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/source",
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/destination"
              ],
              "title": "Accessing the start and end points"
            },
            {
              "anchor": "Specifying-transportation-options",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/transportType",
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/highwayPreference",
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/tollPreference",
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/RoutePreference",
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/requestsAlternateRoutes",
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/departureDate",
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request/arrivalDate"
              ],
              "title": "Specifying transportation options"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKDirectionsTransportType"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Launch-options",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey"
              ],
              "title": "Launch options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Directions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections",
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/Response",
                "doc://com.apple.mapkit/documentation/MapKit/MKDirections/ETAResponse",
                "doc://com.apple.mapkit/documentation/MapKit/MKRoute",
                "doc://com.apple.mapkit/documentation/MapKit/MKRoute/Step"
              ],
              "title": "Directions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKDirectionsRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDriving/title",
          "value": "MKLaunchOptionsDirectionsModeDriving"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDriving/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeDriving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1isDirectionsRequest(_:)/title",
          "value": "isDirectionsRequestURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1isDirectionsRequest(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "isDirectionsRequestURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1arrivalDate/title",
          "value": "arrivalDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1arrivalDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arrivalDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeWalking/title",
          "value": "MKLaunchOptionsDirectionsModeWalking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeWalking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeWalking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapSpanKey/title",
          "value": "MKLaunchOptionsMapSpanKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapSpanKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsMapSpanKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1source/title",
          "value": "source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1source/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirectionsTransportType/title",
          "value": "MKDirectionsTransportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirectionsTransportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirectionsTransportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirectionsTransportType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirectionsTransportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1highwayPreference/title",
          "value": "highwayPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1highwayPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highwayPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeTransit/title",
          "value": "MKLaunchOptionsDirectionsModeTransit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeTransit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeTransit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute~1Step/title",
          "value": "MKRouteStep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute~1Step/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKRouteStep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute~1Step/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKRouteStep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeKey/title",
          "value": "MKLaunchOptionsDirectionsModeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1destination/title",
          "value": "destination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1destination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapCenterKey/title",
          "value": "MKLaunchOptionsMapCenterKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapCenterKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsMapCenterKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1ETAResponse/title",
          "value": "MKETAResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1ETAResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKETAResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1ETAResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKETAResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request/title",
          "value": "MKDirectionsRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirectionsRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirectionsRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections/title",
          "value": "MKDirections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsCameraKey/title",
          "value": "MKLaunchOptionsCameraKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsCameraKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsCameraKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsShowsTrafficKey/title",
          "value": "MKLaunchOptionsShowsTrafficKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsShowsTrafficKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsShowsTrafficKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1transportType/title",
          "value": "transportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1transportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute/title",
          "value": "MKRoute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1RoutePreference/title",
          "value": "MKDirectionsRoutePreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1RoutePreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirectionsRoutePreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1RoutePreference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirectionsRoutePreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDefault/title",
          "value": "MKLaunchOptionsDirectionsModeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1requestsAlternateRoutes/title",
          "value": "requestsAlternateRoutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1requestsAlternateRoutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestsAlternateRoutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1tollPreference/title",
          "value": "tollPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1tollPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tollPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapTypeKey/title",
          "value": "MKLaunchOptionsMapTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsMapTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1departureDate/title",
          "value": "departureDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1departureDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "departureDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:open:options:)/title",
          "value": "application:openURL:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:open:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "app"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "openURL:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURL",
              "text": "NSURL"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "url"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1init(contentsOfURL:)/title",
          "value": "initWithContentsOfURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request~1init(contentsOfURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithContentsOfURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Response/title",
          "value": "MKDirectionsResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Response/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirectionsResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Response/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirectionsResponse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkdirections/request"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkdirections/request"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
