{
  "abstract": [
    {
      "text": "Alerts the user to an arrived notification when the Watch app is not running in the foreground.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/notification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKHapticType@WKHapticTypeNotification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notification"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKHapticTypeNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKHapticType.notification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notification"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType": {
      "abstract": [
        {
          "text": "Constant indicating the style of feedback to deliver using haptics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKHapticType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticType"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/click": {
      "abstract": [
        {
          "text": "Indicates a simple click type of feedback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "click"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/click",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeClick"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.click",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/click"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/directionDown": {
      "abstract": [
        {
          "text": "Indicates a decrease in a specific value or when a value has gone below a certain threshold.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directionDown"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/directionDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeDirectionDown"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.directionDown",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/directiondown"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/directionUp": {
      "abstract": [
        {
          "text": "Indicates an increase in a specific value or when a value has gone above a certain threshold.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directionUp"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/directionUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeDirectionUp"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.directionUp",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/directionup"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/failure": {
      "abstract": [
        {
          "text": "Indicates the failed completion of a task or answering of a question.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeFailure"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.failure",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/failure"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationGenericManeuver": {
      "abstract": [
        {
          "text": "Indicates a new navigation step.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationGenericManeuver"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationGenericManeuver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeNavigationGenericManeuver"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.navigationGenericManeuver",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/navigationgenericmaneuver"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationLeftTurn": {
      "abstract": [
        {
          "text": "Indicates that the user should turn left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationLeftTurn"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationLeftTurn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeNavigationLeftTurn"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.navigationLeftTurn",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/navigationleftturn"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationRightTurn": {
      "abstract": [
        {
          "text": "Indicates that the user should turn right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationRightTurn"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationRightTurn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeNavigationRightTurn"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.navigationRightTurn",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/navigationrightturn"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/notification": {
      "abstract": [
        {
          "text": "Alerts the user to an arrived notification when the Watch app is not running in the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notification"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/notification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeNotification"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.notification",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/notification"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/retry": {
      "abstract": [
        {
          "text": "Indicates that the user should retry a task that temporarily failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retry"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/retry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeRetry"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.retry",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/retry"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/start": {
      "abstract": [
        {
          "text": "Indicates the beginning of an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/start",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeStart"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.start",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/start"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/stop": {
      "abstract": [
        {
          "text": "Indicates the end of an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/stop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeStop"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.stop",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/stop"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/success": {
      "abstract": [
        {
          "text": "Indicates the successful completion of a task or the answering of a question.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKHapticTypeSuccess"
        }
      ],
      "role": "symbol",
      "title": "WKHapticType.success",
      "type": "topic",
      "url": "/documentation/watchkit/wkhaptictype/success"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/directionUp",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/directionDown",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/success",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/failure",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/retry",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/start",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/stop",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/click",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationGenericManeuver",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationLeftTurn",
        "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationRightTurn"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKHapticTypeNotification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/directionUp",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/directionDown",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/success",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/failure",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/retry",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/start",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/stop",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/click",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationGenericManeuver",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationLeftTurn",
                "doc://com.apple.watchkit/documentation/WatchKit/WKHapticType/navigationRightTurn"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKHapticTypeNotification"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1stop/title",
          "value": "WKHapticTypeStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1stop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1click/title",
          "value": "WKHapticTypeClick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1click/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeClick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1success/title",
          "value": "WKHapticTypeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1navigationRightTurn/title",
          "value": "WKHapticTypeNavigationRightTurn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1navigationRightTurn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeNavigationRightTurn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType/title",
          "value": "WKHapticType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1start/title",
          "value": "WKHapticTypeStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1start/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1failure/title",
          "value": "WKHapticTypeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1retry/title",
          "value": "WKHapticTypeRetry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1retry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeRetry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1notification/title",
          "value": "WKHapticTypeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1notification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1directionUp/title",
          "value": "WKHapticTypeDirectionUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1directionUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeDirectionUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1navigationLeftTurn/title",
          "value": "WKHapticTypeNavigationLeftTurn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1navigationLeftTurn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeNavigationLeftTurn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1directionDown/title",
          "value": "WKHapticTypeDirectionDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1directionDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeDirectionDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1navigationGenericManeuver/title",
          "value": "WKHapticTypeNavigationGenericManeuver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKHapticType~1navigationGenericManeuver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKHapticTypeNavigationGenericManeuver"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkhaptictype/notification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkhaptictype/notification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
