{
  "abstract": [
    {
      "text": "Sends an input/output request on the stream.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/sendIORequestWithData:bytesTransferred:error:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOUSBHostStream(im)sendIORequestWithData:bytesTransferred:error:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "sendIORequestWithData:bytesTransferred:error:"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sendIORequestWithData:bytesTransferred:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "sendIORequestWithData:bytesTransferred:error:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "sendIORequestWithData:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSMutableData",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSMutableData",
              "text": "NSMutableData"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "data"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bytesTransferred:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "bytesTransferred"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * *) "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutabledata",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object defining the memory to use for the transfer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "data"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/objectivec/nsuinteger",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " reference that updates with the byte count of the completed data phase.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bytesTransferred"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that contains an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/iokit/ioreturn",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " value on failure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": " if the request completes successfully; otherwise, ",
              "type": "text"
            },
            {
              "code": "NO",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method sends a synchronous request on the stream, and won’t return until the request completes",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Completion timeouts aren’t applicable to streams.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/foundation/nsmutabledata": {
      "abstract": [
        {
          "text": "A dynamic byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSMutableData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutabledata",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableData",
      "type": "topic",
      "url": "/documentation/foundation/nsmutabledata"
    },
    "doc://com.apple.documentation/documentation/iokit/ioreturn": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "IOReturn"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/ioreturn",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOReturn",
      "type": "topic",
      "url": "/documentation/iokit/ioreturn"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsuinteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsuinteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCompletionHandler": {
      "abstract": [
        {
          "text": "The completion handler for asynchronous control, bulk, and interrupt transfers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCompletionHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcompletionhandler"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream": {
      "abstract": [
        {
          "text": "The class responsible for sending stream data for function drivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostStream"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostStream"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostStream",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhoststream"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/abort()": {
      "abstract": [
        {
          "text": "Aborts pending input/output requests synchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "abort"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/abort()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "abortWithError:"
        }
      ],
      "role": "symbol",
      "title": "abort()",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhoststream/abort()"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/abort(with:)": {
      "abstract": [
        {
          "text": "Aborts pending input/output requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "abort"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOUSBHostAbortOption",
          "text": "IOUSBHostAbortOption"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/abort(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "abortWithOption:error:"
        }
      ],
      "role": "symbol",
      "title": "abort(with:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhoststream/abort(with:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/enqueueIORequest(with:completionHandler:)": {
      "abstract": [
        {
          "text": "Enqueues an input/output request on the stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueueIORequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostCompletionHandler",
          "text": "IOUSBHostCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/enqueueIORequest(with:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueIORequestWithData:error:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enqueueIORequest(with:completionHandler:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhoststream/enqueueiorequest(with:completionhandler:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/sendIORequestWithData:bytesTransferred:error:": {
      "abstract": [
        {
          "text": "Sends an input/output request on the stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "sendIORequestWithData:bytesTransferred:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/sendIORequestWithData:bytesTransferred:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendIORequestWithData:bytesTransferred:error:"
        }
      ],
      "role": "symbol",
      "title": "sendIORequestWithData:bytesTransferred:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhoststream/sendiorequestwithdata:bytestransferred:error:"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSMutableData": {
      "abstract": [
        {
          "text": "A dynamic byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSMutableData"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSMutableData",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableData",
      "type": "topic",
      "url": "/documentation/foundation/nsmutabledata"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sending-IO",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCompletionHandler",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/enqueueIORequest(with:completionHandler:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/abort(with:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream/abort()"
      ],
      "title": "Sending I/O"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream~1abort()/title",
          "value": "abortWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream~1abort()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "abortWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream/title",
          "value": "IOUSBHostStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCompletionHandler/title",
          "value": "IOUSBHostCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream~1abort(with:)/title",
          "value": "abortWithOption:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream~1abort(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "abortWithOption:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSMutableData/abstract",
          "value": [
            {
              "text": "An object representing a dynamic byte buffer in memory.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsmutabledata/abstract",
          "value": [
            {
              "text": "An object representing a dynamic byte buffer in memory.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream~1enqueueIORequest(with:completionHandler:)/title",
          "value": "enqueueIORequestWithData:error:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream~1enqueueIORequest(with:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enqueueIORequestWithData:error:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhoststream/sendiorequestwithdata:bytestransferred:error:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
