{"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior/init(handler:)"],"generated":true,"anchor":"Initializers","title":"Initializers"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior/init(target:action:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsslideraccessorybehavior/init(target:action:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsslideraccessorybehavior/init(target:action:)"]}],"metadata":{"role":"symbol","platforms":[{"name":"iOS","introducedAt":"13.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"13.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"deprecated":false,"unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"10.12","name":"macOS","unavailable":false}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":")"}],"roleHeading":"Initializer","externalID":"c:objc(cs)NSSliderAccessoryBehavior(cm)behaviorWithTarget:action:","navigatorTitle":[{"kind":"identifier","text":"behaviorWithTarget:action:"}],"title":"init(target:action:)","modules":[{"name":"AppKit"}]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSliderAccessoryBehavior","kind":"identifier"}],"title":"NSSliderAccessoryBehavior","role":"symbol","url":"/documentation/appkit/nsslideraccessorybehavior","abstract":[],"type":"topic","navigatorTitle":[{"text":"NSSliderAccessoryBehavior","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior/init(target:action:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior/init(target:action:)","url":"/documentation/appkit/nsslideraccessorybehavior/init(target:action:)","navigatorTitle":[{"kind":"identifier","text":"behaviorWithTarget:action:"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier","text":"Selector"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"title":"init(target:action:)"},"doc://com.externally.resolved.symbol/c:@T@SEL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","type":"topic","abstract":[{"type":"text","text":"Defines an opaque type that represents a method selector."}],"url":"/documentation/objectivec/sel","title":"SEL","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior/init(handler:)":{"url":"/documentation/appkit/nsslideraccessorybehavior/init(handler:)","title":"init(handler:)","navigatorTitle":[{"kind":"identifier","text":"behaviorWithHandler:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSliderAccessory","text":"NSSliderAccessory"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior/init(handler:)","type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV":{"type":"topic","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Selector"}],"url":"/documentation/objectivec/selector","title":"Selector","abstract":[{"type":"text","text":""}],"identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"deprecated":false,"beta":false},{"name":"macOS","introducedAt":"10.12","unavailable":false,"deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Type Method"},{"path":"/metadata/title","op":"replace","value":"behaviorWithTarget:action:"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"+ ","kind":"text"},{"text":"behaviorWithTarget:action:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior/init(handler:)"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSliderAccessoryBehavior","text":"NSSliderAccessoryBehavior","preciseIdentifier":"c:objc(cs)NSSliderAccessoryBehavior"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"behaviorWithTarget:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"target"},{"kind":"text","text":" "},{"kind":"identifier","text":"action:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","text":"SEL","preciseIdentifier":"c:@T@SEL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"action"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderAccessoryBehavior/title","value":"NSSliderAccessoryBehavior","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderAccessoryBehavior/fragments","value":[{"text":"NSSliderAccessoryBehavior","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderAccessoryBehavior/navigatorTitle","value":[{"text":"NSSliderAccessoryBehavior","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderAccessoryBehavior~1init(target:action:)/title","value":"behaviorWithTarget:action:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderAccessoryBehavior~1init(target:action:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"behaviorWithTarget:action:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderAccessoryBehavior~1init(handler:)/title","value":"behaviorWithHandler:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderAccessoryBehavior~1init(handler:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"behaviorWithHandler:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}