{
  "abstract": [
    {
      "text": "The context’s universal URL link.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit",
        "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/universalLinkURL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ClassKit",
    "externalID": "c:@CLSPredicateKeyPathUniversalLinkURL",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "universalLinkURL"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CLSPredicateKeyPath",
        "text": "CLSPredicateKeyPath"
      }
    ],
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLSPredicateKeyPathUniversalLinkURL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "universalLinkURL"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "universalLinkURL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CLSPredicateKeyPath",
              "text": "CLSPredicateKeyPath"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath": {
      "abstract": [
        {
          "text": "The set of possible key paths you use to search for contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSPredicateKeyPath"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSPredicateKeyPath"
        }
      ],
      "role": "symbol",
      "title": "CLSPredicateKeyPath",
      "type": "topic",
      "url": "/documentation/classkit/clspredicatekeypath"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/dateCreated": {
      "abstract": [
        {
          "text": "The date on which the context was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSPredicateKeyPath",
          "text": "CLSPredicateKeyPath"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/dateCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSPredicateKeyPathDateCreated"
        }
      ],
      "role": "symbol",
      "title": "dateCreated",
      "type": "topic",
      "url": "/documentation/classkit/clspredicatekeypath/datecreated"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/identifier": {
      "abstract": [
        {
          "text": "The context’s identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSPredicateKeyPath",
          "text": "CLSPredicateKeyPath"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSPredicateKeyPathIdentifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/classkit/clspredicatekeypath/identifier"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/parent": {
      "abstract": [
        {
          "text": "The context’s direct ancestor in the context hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSPredicateKeyPath",
          "text": "CLSPredicateKeyPath"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/parent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSPredicateKeyPathParent"
        }
      ],
      "role": "symbol",
      "title": "parent",
      "type": "topic",
      "url": "/documentation/classkit/clspredicatekeypath/parent"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/title": {
      "abstract": [
        {
          "text": "The human readable name of the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSPredicateKeyPath",
          "text": "CLSPredicateKeyPath"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSPredicateKeyPathTitle"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/classkit/clspredicatekeypath/title"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/topic": {
      "abstract": [
        {
          "text": "The context’s topic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSPredicateKeyPath",
          "text": "CLSPredicateKeyPath"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/topic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSPredicateKeyPathTopic"
        }
      ],
      "role": "symbol",
      "title": "topic",
      "type": "topic",
      "url": "/documentation/classkit/clspredicatekeypath/topic"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/universalLinkURL": {
      "abstract": [
        {
          "text": "The context’s universal URL link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "universalLinkURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLSPredicateKeyPath",
          "text": "CLSPredicateKeyPath"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/universalLinkURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSPredicateKeyPathUniversalLinkURL"
        }
      ],
      "role": "symbol",
      "title": "universalLinkURL",
      "type": "topic",
      "url": "/documentation/classkit/clspredicatekeypath/universallinkurl"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Predicate-Key-Paths",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/dateCreated",
        "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/identifier",
        "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/parent",
        "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/title",
        "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/topic"
      ],
      "title": "Predicate Key Paths"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLSPredicateKeyPathUniversalLinkURL"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSPredicateKeyPathUniversalLinkURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.classkit/documentation/ClassKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Predicate-Key-Paths",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/dateCreated",
                "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/identifier",
                "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/parent",
                "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/title",
                "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath/topic"
              ],
              "title": "Predicate Key Paths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSPredicateKeyPath",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CLSPredicateKeyPath",
                    "text": "CLSPredicateKeyPath"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLSPredicateKeyPathUniversalLinkURL"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1title/title",
          "value": "CLSPredicateKeyPathTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSPredicateKeyPathTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath/title",
          "value": "CLSPredicateKeyPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSPredicateKeyPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSPredicateKeyPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1dateCreated/title",
          "value": "CLSPredicateKeyPathDateCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1dateCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSPredicateKeyPathDateCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1universalLinkURL/title",
          "value": "CLSPredicateKeyPathUniversalLinkURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1universalLinkURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSPredicateKeyPathUniversalLinkURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1topic/title",
          "value": "CLSPredicateKeyPathTopic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1topic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSPredicateKeyPathTopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1identifier/title",
          "value": "CLSPredicateKeyPathIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSPredicateKeyPathIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1parent/title",
          "value": "CLSPredicateKeyPathParent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSPredicateKeyPath~1parent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSPredicateKeyPathParent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/clspredicatekeypath/universallinkurl"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/clspredicatekeypath/universallinkurl"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
