{
  "abstract": [
    {
      "text": "Asks the user to allow your app to perform speech recognition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.speech/documentation/Speech",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer/requestAuthorization(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFSpeechRecognizer(cm)requestAuthorization:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "requestAuthorization"
      },
      {
        "kind": "text",
        "text": "(("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SFSpeechRecognizerAuthorizationStatus",
        "text": "SFSpeechRecognizerAuthorizationStatus"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Speech"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "requestAuthorization:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "requestAuthorization(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "requestAuthorization"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SFSpeechRecognizerAuthorizationStatus",
              "text": "SFSpeechRecognizerAuthorizationStatus"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block to execute when your app’s authorization status is known. The status parameter of the block contains your app’s authorization status. The system does not guarantee the execution of this block on your app’s main dispatch queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "handler"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.speech/documentation/Speech/asking-permission-to-use-speech-recognition"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this method before performing any other tasks associated with speech recognition. This method executes asynchronously, returning shortly after you call it. At some point later, the system calls the provided ",
              "type": "text"
            },
            {
              "code": "handler",
              "type": "codeVoice"
            },
            {
              "text": " block with the results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When your app’s authorization status is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/notDetermined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", this method causes the system to prompt the user to grant or deny permission for your app to use speech recognition. The prompt includes the custom message you specify in the ",
              "type": "text"
            },
            {
              "code": "NSSpeechRecognitionUsageDescription",
              "type": "codeVoice"
            },
            {
              "text": " key of your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file. The user’s response is saved so that future calls to this method do not prompt the user again.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Your app’s ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file must contain the ",
                  "type": "text"
                },
                {
                  "code": "NSSpeechRecognitionUsageDescription",
                  "type": "codeVoice"
                },
                {
                  "text": " key with a valid usage description. If this key is not present, your app will crash when you call this method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about requesting authorization, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/asking-permission-to-use-speech-recognition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.speech/documentation/Speech": {
      "abstract": [
        {
          "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech",
      "kind": "symbol",
      "role": "collection",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/speech"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer": {
      "abstract": [
        {
          "text": "An object you use to check for the availability of the speech recognition service, and to initiate the speech recognition process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizer"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizer"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognizer",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizer"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer/authorizationStatus()": {
      "abstract": [
        {
          "text": "Returns your app’s current authorization to perform speech recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SFSpeechRecognizerAuthorizationStatus",
          "text": "SFSpeechRecognizerAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer/authorizationStatus()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus()",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizer/authorizationstatus()"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer/requestAuthorization(_:)": {
      "abstract": [
        {
          "text": "Asks the user to allow your app to perform speech recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAuthorization"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SFSpeechRecognizerAuthorizationStatus",
          "text": "SFSpeechRecognizerAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer/requestAuthorization(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAuthorization:"
        }
      ],
      "role": "symbol",
      "title": "requestAuthorization(_:)",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizer/requestauthorization(_:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus": {
      "abstract": [
        {
          "text": "The app’s authorization to perform speech recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizerAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizerAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognizerAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizerauthorizationstatus"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/notDetermined": {
      "abstract": [
        {
          "text": "The app’s authorization status has not yet been determined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizerAuthorizationStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognizerAuthorizationStatus.notDetermined",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizerauthorizationstatus/notdetermined"
    },
    "doc://com.apple.speech/documentation/Speech/asking-permission-to-use-speech-recognition": {
      "abstract": [
        {
          "text": "Ask the user’s permission to perform speech recognition using Apple’s servers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/asking-permission-to-use-speech-recognition",
      "kind": "article",
      "role": "article",
      "title": "Asking Permission to Use Speech Recognition",
      "type": "topic",
      "url": "/documentation/speech/asking-permission-to-use-speech-recognition"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Requesting-Authorization-from-the-User",
      "generated": true,
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer/authorizationStatus()",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus"
      ],
      "title": "Requesting Authorization from the User"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "requestAuthorization:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestAuthorization:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.speech/documentation/Speech",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Requesting-Authorization-from-the-User",
              "generated": true,
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer/authorizationStatus()",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus"
              ],
              "title": "Requesting Authorization from the User"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "requestAuthorization:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@SFSpeechRecognizerAuthorizationStatus",
                    "text": "SFSpeechRecognizerAuthorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "status"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "handler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The block to execute when your app’s authorization status is known. The status parameter of the block contains your app’s authorization status. The system does not guarantee the execution of this block on your app’s main dispatch queue.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "handler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus~1notDetermined/title",
          "value": "SFSpeechRecognizerAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizerAuthorizationStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizer/title",
          "value": "SFSpeechRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizer~1requestAuthorization(_:)/title",
          "value": "requestAuthorization:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizer~1requestAuthorization(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestAuthorization:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizer~1authorizationStatus()/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizer~1authorizationStatus()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus/title",
          "value": "SFSpeechRecognizerAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizerAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizerAuthorizationStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/speech/sfspeechrecognizer/requestauthorization(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/speech/sfspeechrecognizer/requestauthorization(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
