{
  "abstract": [
    {
      "text": "Fetches an item’s content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/contentFetch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFileProviderTestingOperationType@NSFileProviderTestingOperationTypeContentFetch",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "contentFetch"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderTestingOperationTypeContentFetch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSFileProviderTestingOperationType.contentFetch"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "contentFetch"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType": {
      "abstract": [
        {
          "text": "The action that an operation performs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationType"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationType"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/childrenEnumeration": {
      "abstract": [
        {
          "text": "Lists an item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "childrenEnumeration"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/childrenEnumeration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeChildrenEnumeration"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.childrenEnumeration",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/childrenenumeration"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/collisionResolution": {
      "abstract": [
        {
          "text": "Resolves a collision by renaming the new item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionResolution"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/collisionResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeCollisionResolution"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.collisionResolution",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/collisionresolution"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/contentFetch": {
      "abstract": [
        {
          "text": "Fetches an item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentFetch"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/contentFetch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeContentFetch"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.contentFetch",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/contentfetch"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/creation": {
      "abstract": [
        {
          "text": "Propagates the creation of a source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creation"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/creation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeCreation"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.creation",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/creation"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/deletion": {
      "abstract": [
        {
          "text": "Propagates the deletion of the source item from the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/deletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeDeletion"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.deletion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/deletion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/ingestion": {
      "abstract": [
        {
          "text": "Alerts the system to changes to either the local or remote storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ingestion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/ingestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeIngestion"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.ingestion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/ingestion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/lookup": {
      "abstract": [
        {
          "text": "Looks up an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookup"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/lookup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeLookup"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.lookup",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/lookup"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/modification": {
      "abstract": [
        {
          "text": "Propagates a change from the source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modification"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/modification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeModification"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.modification",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/modification"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/childrenEnumeration",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/collisionResolution",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/creation",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/deletion",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/ingestion",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/lookup",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/modification"
      ],
      "title": "Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFileProviderTestingOperationTypeContentFetch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeContentFetch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/childrenEnumeration",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/collisionResolution",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/creation",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/deletion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/ingestion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/lookup",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/modification"
              ],
              "title": "Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSFileProviderTestingOperationTypeContentFetch"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1creation/title",
          "value": "NSFileProviderTestingOperationTypeCreation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1creation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeCreation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/title",
          "value": "NSFileProviderTestingOperationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1childrenEnumeration/title",
          "value": "NSFileProviderTestingOperationTypeChildrenEnumeration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1childrenEnumeration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeChildrenEnumeration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1modification/title",
          "value": "NSFileProviderTestingOperationTypeModification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1modification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeModification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1contentFetch/title",
          "value": "NSFileProviderTestingOperationTypeContentFetch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1contentFetch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeContentFetch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1collisionResolution/title",
          "value": "NSFileProviderTestingOperationTypeCollisionResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1collisionResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeCollisionResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1lookup/title",
          "value": "NSFileProviderTestingOperationTypeLookup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1lookup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeLookup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1ingestion/title",
          "value": "NSFileProviderTestingOperationTypeIngestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1ingestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeIngestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1deletion/title",
          "value": "NSFileProviderTestingOperationTypeDeletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1deletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeDeletion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidertestingoperationtype/contentfetch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidertestingoperationtype/contentfetch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
