{
  "abstract": [
    {
      "text": "Starts the provisioning process for a specified eSIM.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/addPlan(with:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CTCellularPlanProvisioning(im)addPlanWith:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "addPlan"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CTCellularPlanProvisioningRequest",
        "text": "CTCellularPlanProvisioningRequest"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTCellularPlanProvisioningAddPlanResult",
        "text": "CTCellularPlanProvisioningAddPlanResult"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "addPlanWith:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "addPlan(with:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "addPlan"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "request"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CTCellularPlanProvisioningRequest",
              "text": "CTCellularPlanProvisioningRequest"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTCellularPlanProvisioningAddPlanResult",
              "text": "CTCellularPlanProvisioningAddPlanResult"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "addPlan"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "request"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CTCellularPlanProvisioningRequest",
              "text": "CTCellularPlanProvisioningRequest"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTCellularPlanProvisioningAddPlanResult",
              "text": "CTCellularPlanProvisioningAddPlanResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that identifies the eSIM to download.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "request"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A completion handler that executes after processing the request. The parameter passed to the completion handler indicates whether the request succeeded, failed, or ended in an unknown state.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Once your app calls this method, an iOS wizard guides the user through the process of installing and configuration an eSIM.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Installing-an-eSIM-in-the-Background",
          "level": 3,
          "text": "Installing an eSIM in the Background",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The user may send your app to the background prior to completing eSIM installation. To ensure your app has an opportunity to execute the completion handler and get the result of the installation, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/beginBackgroundTask(expirationHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to perform the eSIM installation as a background task.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning": {
      "abstract": [
        {
          "text": "An object you use to download and install a carrier eSIM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioning"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioning"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioning",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioning"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/addPlan(with:completionHandler:)": {
      "abstract": [
        {
          "text": "Starts the provisioning process for a specified eSIM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPlan"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCellularPlanProvisioningRequest",
          "text": "CTCellularPlanProvisioningRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCellularPlanProvisioningAddPlanResult",
          "text": "CTCellularPlanProvisioningAddPlanResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/addPlan(with:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPlanWith:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "addPlan(with:completionHandler:)",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioning/addplan(with:completionhandler:)"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsCellularPlan()": {
      "abstract": [
        {
          "text": "Indicates whether the device supports eSIM and the activation policy allows eSIM installation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsCellularPlan"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsCellularPlan()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsCellularPlan"
        }
      ],
      "role": "symbol",
      "title": "supportsCellularPlan()",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioning/supportscellularplan()"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsEmbeddedSIM": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device has hardware eSIM support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsEmbeddedSIM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsEmbeddedSIM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsEmbeddedSIM"
        }
      ],
      "role": "symbol",
      "title": "supportsEmbeddedSIM",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioning/supportsembeddedsim"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult": {
      "abstract": [
        {
          "text": "The result from attempting to provision an eSIM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningAddPlanResult"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningAddPlanResult"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioningAddPlanResult",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioningaddplanresult"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest": {
      "abstract": [
        {
          "text": "A request specifying an eSIM to download and install.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningRequest"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningRequest"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioningRequest",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioningrequest"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplication/beginBackgroundTask(expirationHandler:)": {
      "abstract": [
        {
          "text": "Marks the start of a task that should continue if the app enters the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginBackgroundTask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "expirationHandler"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (@"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")? = nil) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIBackgroundTaskIdentifier",
          "text": "UIBackgroundTaskIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/beginBackgroundTask(expirationHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "beginBackgroundTask(expirationHandler:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplication/beginBackgroundTask(expirationHandler:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Provisioning-an-eSIM",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsCellularPlan()",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsEmbeddedSIM",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult"
      ],
      "title": "Provisioning an eSIM"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "addPlanWith:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPlanWith:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretelephony/documentation/CoreTelephony",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Provisioning-an-eSIM",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsCellularPlan()",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsEmbeddedSIM",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult"
              ],
              "title": "Provisioning an eSIM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "addPlanWith:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CTCellularPlanProvisioningRequest",
                    "text": "CTCellularPlanProvisioningRequest"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "request"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CTCellularPlanProvisioningAddPlanResult",
                    "text": "CTCellularPlanProvisioningAddPlanResult"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "result"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that identifies the eSIM to download.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "request"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A completion handler that executes after processing the request. The parameter passed to the completion handler indicates whether the request succeeded, failed, or ended in an unknown state.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning/title",
          "value": "CTCellularPlanProvisioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplication~1beginBackgroundTask(expirationHandler:)/title",
          "value": "beginBackgroundTaskWithExpirationHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplication~1beginBackgroundTask(expirationHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UIBackgroundTaskIdentifier",
              "text": "UIBackgroundTaskIdentifier"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "beginBackgroundTaskWithExpirationHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:BFv()",
              "text": "void (^)(void)"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningRequest/title",
          "value": "CTCellularPlanProvisioningRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult/title",
          "value": "CTCellularPlanProvisioningAddPlanResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1supportsEmbeddedSIM/title",
          "value": "supportsEmbeddedSIM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1supportsEmbeddedSIM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsEmbeddedSIM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1addPlan(with:completionHandler:)/title",
          "value": "addPlanWith:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1addPlan(with:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPlanWith:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1supportsCellularPlan()/title",
          "value": "supportsCellularPlan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1supportsCellularPlan()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsCellularPlan"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/ctcellularplanprovisioning/addplan(with:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/ctcellularplanprovisioning/addplan(with:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
