{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/stopStream()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopStream","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}]}]}],"seeAlsoSections":[{"anchor":"Managing-a-Stream","title":"Managing a Stream","identifiers":["doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/authorizedToStartStream(for:)","doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/startStream()"],"generated":true}],"abstract":[{"type":"text","text":"Stops the stream of media data."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coremediaio/cmioextensionstreamsource/stopstream()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coremediaio/cmioextensionstreamsource/stopstream()"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremediaio/documentation/CoreMediaIO","doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource"]]},"sections":[],"metadata":{"role":"symbol","title":"stopStream()","roleHeading":"Instance Method","symbolKind":"method","required":true,"platforms":[{"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"15.4","deprecated":false},{"introducedAt":"12.3","deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"externalID":"c:objc(pl)CMIOExtensionStreamSource(im)stopStreamAndReturnError:","navigatorTitle":[{"kind":"identifier","text":"stopStreamAndReturnError:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopStream","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"modules":[{"name":"Core Media I/O"}]},"references":{"doc://com.apple.coremediaio/documentation/CoreMediaIO":{"role":"collection","title":"Core Media I/O","type":"topic","abstract":[{"type":"text","text":"Securely support custom camera devices in macOS."}],"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO","url":"/documentation/coremediaio","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","type":"topic","url":"/documentation/objectivec/bool","kind":"symbol","title":"BOOL","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","title":"Technologies","type":"topic","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/stopStream()":{"type":"topic","required":true,"title":"stopStream()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopStream","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","url":"/documentation/coremediaio/cmioextensionstreamsource/stopstream()","navigatorTitle":[{"text":"stopStreamAndReturnError:","kind":"identifier"}],"abstract":[{"type":"text","text":"Stops the stream of media data."}],"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/stopStream()"},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource":{"abstract":[{"type":"text","text":"A protocol for objects that act as stream sources."}],"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource","type":"topic","url":"/documentation/coremediaio/cmioextensionstreamsource","kind":"symbol","navigatorTitle":[{"text":"CMIOExtensionStreamSource","kind":"identifier"}],"title":"CMIOExtensionStreamSource","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMIOExtensionStreamSource","kind":"identifier"}]},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/startStream()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startStream","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"required":true,"title":"startStream()","type":"topic","abstract":[{"type":"text","text":"Starts the stream of media data."}],"navigatorTitle":[{"text":"startStreamAndReturnError:","kind":"identifier"}],"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/startStream()","url":"/documentation/coremediaio/cmioextensionstreamsource/startstream()","kind":"symbol"},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/authorizedToStartStream(for:)":{"type":"topic","required":true,"title":"authorizedToStartStream(for:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizedToStartStream"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMIOExtensionClient","preciseIdentifier":"c:objc(cs)CMIOExtensionClient","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/coremediaio/cmioextensionstreamsource/authorizedtostartstream(for:)","navigatorTitle":[{"text":"authorizedToStartStreamForClient:","kind":"identifier"}],"abstract":[{"type":"text","text":"Determines whether to authorize an app to use this stream."}],"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/authorizedToStartStream(for:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"15.4","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"12.3","unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"stopStreamAndReturnError:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopStreamAndReturnError:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremediaio/documentation/CoreMediaIO","doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Managing-a-Stream","title":"Managing a Stream","identifiers":["doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/authorizedToStartStream(for:)","doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource/startStream()"],"generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"stopStreamAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"outError","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]}},{"op":"replace","value":"stopStreamAndReturnError:","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource~1stopStream()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopStreamAndReturnError:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource~1stopStream()/fragments"},{"op":"replace","value":"CMIOExtensionStreamSource","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource/title"},{"op":"replace","value":[{"kind":"identifier","text":"CMIOExtensionStreamSource"}],"path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CMIOExtensionStreamSource"}],"path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource/navigatorTitle"},{"op":"replace","value":"startStreamAndReturnError:","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource~1startStream()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startStreamAndReturnError:"}],"path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource~1startStream()/fragments"},{"op":"replace","value":"authorizedToStartStreamForClient:","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource~1authorizedToStartStream(for:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"authorizedToStartStreamForClient:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource~1authorizedToStartStream(for:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}