{
  "abstract": [
    {
      "text": "Merchant failed to authorize the transaction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/failure"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKPaymentAuthorizationStatus@PKPaymentAuthorizationStatusFailure",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failure"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentAuthorizationStatusFailure"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKPaymentAuthorizationStatus.failure"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failure"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this value for all failures other than PIN-related failures (which have their own status constants), such as for an invalid address, contact, or unknown error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "List the specific errors in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequestShippingContactUpdate/errors",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus": {
      "abstract": [
        {
          "text": "General success and failure status for payment authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationstatus"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/failure": {
      "abstract": [
        {
          "text": "Merchant failed to authorize the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationStatusFailure"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationStatus.failure",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationstatus/failure"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidBillingPostalAddress": {
      "abstract": [
        {
          "text": "Invalid or unusable billing address.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidBillingPostalAddress"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidBillingPostalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationStatusInvalidBillingPostalAddress"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationStatus.invalidBillingPostalAddress",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationstatus/invalidbillingpostaladdress"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidShippingContact": {
      "abstract": [
        {
          "text": "Invalid or incomplete shipping contact.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidShippingContact"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidShippingContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationStatusInvalidShippingContact"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationStatus.invalidShippingContact",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationstatus/invalidshippingcontact"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidShippingPostalAddress": {
      "abstract": [
        {
          "text": "Invalid or unusable shipping address.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidShippingPostalAddress"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidShippingPostalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationStatusInvalidShippingPostalAddress"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationStatus.invalidShippingPostalAddress",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationstatus/invalidshippingpostaladdress"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinIncorrect": {
      "abstract": [
        {
          "text": "Incorrect PIN entered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pinIncorrect"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinIncorrect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationStatusPINIncorrect"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationStatus.pinIncorrect",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationstatus/pinincorrect"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinLockout": {
      "abstract": [
        {
          "text": "PIN retry limit exceeded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pinLockout"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinLockout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationStatusPINLockout"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationStatus.pinLockout",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationstatus/pinlockout"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinRequired": {
      "abstract": [
        {
          "text": "Transaction requires PIN entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pinRequired"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationStatusPINRequired"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationStatus.pinRequired",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationstatus/pinrequired"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/success": {
      "abstract": [
        {
          "text": "Merchant successfully authorized the transaction, or the transaction is expected to succeed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationStatusSuccess"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationStatus.success",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationstatus/success"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequestShippingContactUpdate/errors": {
      "abstract": [
        {
          "text": "An array of shipping contact information errors that the user must resolve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errors"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequestShippingContactUpdate/errors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errors"
        }
      ],
      "role": "symbol",
      "title": "errors",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequestshippingcontactupdate/errors"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Payment-authorization-status-constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/success",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidBillingPostalAddress",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidShippingPostalAddress",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidShippingContact",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinRequired",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinIncorrect",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinLockout"
      ],
      "title": "Payment authorization status constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentAuthorizationStatusFailure"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatusFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Payment-authorization-status-constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/success",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidBillingPostalAddress",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidShippingPostalAddress",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/invalidShippingContact",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinRequired",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinIncorrect",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationStatus/pinLockout"
              ],
              "title": "Payment authorization status constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKPaymentAuthorizationStatusFailure"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1success/title",
          "value": "PKPaymentAuthorizationStatusSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatusSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequestShippingContactUpdate~1errors/title",
          "value": "errors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequestShippingContactUpdate~1errors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1invalidShippingPostalAddress/title",
          "value": "PKPaymentAuthorizationStatusInvalidShippingPostalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1invalidShippingPostalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatusInvalidShippingPostalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1invalidShippingContact/title",
          "value": "PKPaymentAuthorizationStatusInvalidShippingContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1invalidShippingContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatusInvalidShippingContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1pinLockout/title",
          "value": "PKPaymentAuthorizationStatusPINLockout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1pinLockout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatusPINLockout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1pinRequired/title",
          "value": "PKPaymentAuthorizationStatusPINRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1pinRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatusPINRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1failure/title",
          "value": "PKPaymentAuthorizationStatusFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatusFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1invalidBillingPostalAddress/title",
          "value": "PKPaymentAuthorizationStatusInvalidBillingPostalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1invalidBillingPostalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatusInvalidBillingPostalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1pinIncorrect/title",
          "value": "PKPaymentAuthorizationStatusPINIncorrect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus~1pinIncorrect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatusPINIncorrect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus/title",
          "value": "PKPaymentAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentauthorizationstatus/failure"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentauthorizationstatus/failure"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
