{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsaccessibilitynavigablestatictext/accessibilityframe(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsaccessibilitynavigablestatictext/accessibilityframe(for:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"range","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"}],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The range of characters.","type":"text"}],"type":"paragraph"}],"name":"range"}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"The rectangle that encloses the specified characters.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"If the range crosses a line boundary, the returned rectangle will fully enclose all the lines of characters.","type":"text"}]}]}],"kind":"symbol","seeAlsoSections":[{"title":"Supporting Accessibility","generated":true,"anchor":"Supporting-Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityLine(for:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityRange(forLine:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityString(for:)"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityFrame(for:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText"]]},"metadata":{"required":true,"platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"title":"accessibilityFrame(for:)","modules":[{"name":"AppKit"}],"symbolKind":"method","externalID":"c:objc(pl)NSAccessibilityNavigableStaticText(im)accessibilityFrameForRange:","roleHeading":"Instance Method","navigatorTitle":[{"text":"accessibilityFrameForRange:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Returns the rectangle that encloses the specified range of characters.","type":"text"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityFrame(for:)":{"type":"topic","url":"/documentation/appkit/nsaccessibilitynavigablestatictext/accessibilityframe(for:)","role":"symbol","abstract":[{"text":"Returns the rectangle that encloses the specified range of characters.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityFrameForRange:"}],"title":"accessibilityFrame(for:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityFrame(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"}],"required":true},"doc://com.externally.resolved.symbol/c:@S@_NSRange":{"role":"symbol","type":"topic","abstract":[{"text":"A Swift-only concrete structure that backs the range type alias.","type":"text"}],"url":"/documentation/foundation/nsrange-jio","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"_NSRange"}],"identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","title":"_NSRange"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText":{"url":"/documentation/appkit/nsaccessibilitynavigablestatictext","title":"NSAccessibilityNavigableStaticText","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityNavigableStaticText"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityNavigableStaticText"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as navigable static text."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityString(for:)":{"url":"/documentation/appkit/nsaccessibilitynavigablestatictext/accessibilitystring(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the substring for the specified range."}],"type":"topic","required":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityString(for:)","title":"accessibilityString(for:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityStringForRange:"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityLine(for:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityLine(for:)","abstract":[{"type":"text","text":"Returns the line number for the line that contains the specified character index."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityLineForIndex:"}],"title":"accessibilityLine(for:)","kind":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityLine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"/documentation/appkit/nsaccessibilitynavigablestatictext/accessibilityline(for:)"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityRange(forLine:)":{"url":"/documentation/appkit/nsaccessibilitynavigablestatictext/accessibilityrange(forline:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityRange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSRange"}],"abstract":[{"type":"text","text":"Returns the range of characters in the specified line."}],"type":"topic","required":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityRange(forLine:)","title":"accessibilityRange(forLine:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityRangeForLine:"}]},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"path":"/metadata/platforms"},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"accessibilityFrameForRange:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accessibilityFrameForRange:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Supporting Accessibility","generated":true,"anchor":"Supporting-Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityLine(for:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityRange(forLine:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText/accessibilityString(for:)"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"text":") ","kind":"text"},{"text":"accessibilityFrameForRange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSRange","identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange"},{"text":") ","kind":"text"},{"text":"range","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The range of characters."}]}],"name":"range"}]}},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"The rectangle that encloses the specified characters.","type":"text"}],"type":"paragraph"}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText~1accessibilityFrame(for:)/title","value":"accessibilityFrameForRange:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText~1accessibilityFrame(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityFrameForRange:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/title","value":"NSAccessibilityNavigableStaticText"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/fragments","value":[{"text":"NSAccessibilityNavigableStaticText","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityNavigableStaticText"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText~1accessibilityString(for:)/title","value":"accessibilityStringForRange:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText~1accessibilityString(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityStringForRange:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText~1accessibilityLine(for:)/title","value":"accessibilityLineForIndex:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityLineForIndex:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText~1accessibilityLine(for:)/fragments"},{"op":"replace","value":"accessibilityRangeForLine:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText~1accessibilityRange(forLine:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityRangeForLine:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText~1accessibilityRange(forLine:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}