{
  "abstract": [
    {
      "text": "A state that indicates speech started.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent/hasStarted"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUVoiceIOSpeechActivityEvent@kAUVoiceIOSpeechActivityHasStarted",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hasStarted"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAUVoiceIOSpeechActivityHasStarted"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AUVoiceIOSpeechActivityEvent.hasStarted"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hasStarted"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent": {
      "abstract": [
        {
          "text": "Constants that indicate the state of muted speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUVoiceIOSpeechActivityEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUVoiceIOSpeechActivityEvent"
        }
      ],
      "role": "symbol",
      "title": "AUVoiceIOSpeechActivityEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiospeechactivityevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent/hasEnded": {
      "abstract": [
        {
          "text": "A state that indicates speech ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasEnded"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent/hasEnded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUVoiceIOSpeechActivityHasEnded"
        }
      ],
      "role": "symbol",
      "title": "AUVoiceIOSpeechActivityEvent.hasEnded",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiospeechactivityevent/hasended"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent/hasStarted": {
      "abstract": [
        {
          "text": "A state that indicates speech started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasStarted"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent/hasStarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAUVoiceIOSpeechActivityHasStarted"
        }
      ],
      "role": "symbol",
      "title": "AUVoiceIOSpeechActivityEvent.hasStarted",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auvoiceiospeechactivityevent/hasstarted"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-when-muted-speech-starts-and-stops",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent/hasEnded"
      ],
      "title": "Determining when muted speech starts and stops"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAUVoiceIOSpeechActivityHasStarted"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUVoiceIOSpeechActivityHasStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-when-muted-speech-starts-and-stops",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUVoiceIOSpeechActivityEvent/hasEnded"
              ],
              "title": "Determining when muted speech starts and stops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAUVoiceIOSpeechActivityHasStarted"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOSpeechActivityEvent~1hasEnded/title",
          "value": "kAUVoiceIOSpeechActivityHasEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOSpeechActivityEvent~1hasEnded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUVoiceIOSpeechActivityHasEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOSpeechActivityEvent/title",
          "value": "AUVoiceIOSpeechActivityEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOSpeechActivityEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOSpeechActivityEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOSpeechActivityEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUVoiceIOSpeechActivityEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOSpeechActivityEvent~1hasStarted/title",
          "value": "kAUVoiceIOSpeechActivityHasStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUVoiceIOSpeechActivityEvent~1hasStarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAUVoiceIOSpeechActivityHasStarted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auvoiceiospeechactivityevent/hasstarted"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auvoiceiospeechactivityevent/hasstarted"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
