{"variants":[{"paths":["/documentation/appkit/nsstackview/distribution-swift.enum/fillequally"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsstackview/distribution-swift.enum/fillequally"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"AppKit"}],"externalID":"c:@E@NSStackViewDistribution@NSStackViewDistributionFillEqually","platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","introducedAt":"10.11","beta":false}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillEqually","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"NSStackViewDistributionFillEqually","kind":"identifier"}],"title":"NSStackView.Distribution.fillEqually","roleHeading":"Case","symbolKind":"case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"]]},"seeAlsoSections":[{"anchor":"Constants","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalCentering","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fill","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillProportionally","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/gravityAreas"],"title":"Constants"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fillEqually"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillEqually","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalCentering":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"equalCentering"}],"abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalCentering","navigatorTitle":[{"kind":"identifier","text":"NSStackViewDistributionEqualCentering"}],"title":"NSStackView.Distribution.equalCentering","url":"/documentation/appkit/nsstackview/distribution-swift.enum/equalcentering","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum":{"role":"symbol","abstract":[],"title":"NSStackView.Distribution","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Distribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.enum","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Distribution"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalSpacing":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSStackViewDistributionEqualSpacing"}],"url":"/documentation/appkit/nsstackview/distribution-swift.enum/equalspacing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"equalSpacing"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalSpacing","title":"NSStackView.Distribution.equalSpacing","abstract":[],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/gravityAreas":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gravityAreas"}],"title":"NSStackView.Distribution.gravityAreas","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/gravityAreas","abstract":[],"role":"symbol","url":"/documentation/appkit/nsstackview/distribution-swift.enum/gravityareas","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSStackViewDistributionGravityAreas"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fill":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"}],"title":"NSStackView.Distribution.fill","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fill","abstract":[],"role":"symbol","url":"/documentation/appkit/nsstackview/distribution-swift.enum/fill","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSStackViewDistributionFill"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillProportionally":{"url":"/documentation/appkit/nsstackview/distribution-swift.enum/fillproportionally","title":"NSStackView.Distribution.fillProportionally","kind":"symbol","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillProportionally","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillProportionally","kind":"identifier"}],"navigatorTitle":[{"text":"NSStackViewDistributionFillProportionally","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillEqually":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSStackViewDistributionFillEqually","kind":"identifier"}],"url":"/documentation/appkit/nsstackview/distribution-swift.enum/fillequally","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillEqually","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillEqually","title":"NSStackView.Distribution.fillEqually","abstract":[],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.11"}],"path":"/metadata/platforms"},{"op":"replace","value":"Enumeration Case","path":"/metadata/roleHeading"},{"op":"replace","path":"/metadata/title","value":"NSStackViewDistributionFillEqually"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"NSStackViewDistributionFillEqually"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalCentering","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fill","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillProportionally","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/gravityAreas"],"generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"NSStackViewDistributionFillEqually"}],"platforms":["Mac Catalyst","macOS"]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1equalCentering/title","value":"NSStackViewDistributionEqualCentering","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1equalCentering/fragments","value":[{"kind":"identifier","text":"NSStackViewDistributionEqualCentering"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","value":"NSStackView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","value":[{"kind":"identifier","text":"NSStackView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","value":[{"kind":"identifier","text":"NSStackView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/title","value":"NSStackViewDistribution","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/fragments","value":[{"kind":"identifier","text":"NSStackViewDistribution"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/navigatorTitle","value":[{"text":"NSStackViewDistribution","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1equalSpacing/title","value":"NSStackViewDistributionEqualSpacing","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1equalSpacing/fragments","value":[{"text":"NSStackViewDistributionEqualSpacing","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"NSStackViewDistributionGravityAreas","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1gravityAreas/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1gravityAreas/fragments","value":[{"kind":"identifier","text":"NSStackViewDistributionGravityAreas"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fill/title","value":"NSStackViewDistributionFill"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fill/fragments","value":[{"kind":"identifier","text":"NSStackViewDistributionFill"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fillProportionally/title","value":"NSStackViewDistributionFillProportionally"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fillProportionally/fragments","value":[{"text":"NSStackViewDistributionFillProportionally","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fillEqually/title","value":"NSStackViewDistributionFillEqually"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fillEqually/fragments","value":[{"kind":"identifier","text":"NSStackViewDistributionFillEqually"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}