{
  "abstract": [
    {
      "text": "Error codes the location manager returns if starting to monitor for location push notifications fails.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLLocationPushServiceError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CLLocationPushServiceError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These error codes are returned from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoringLocationPushes(completion:)",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoringLocationPushes(completion:)": {
      "abstract": [
        {
          "text": "Starts monitoring for the delivery of Apple Push Notification service (APNs) location pushes, and provides a device-specific token for sending pushes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMonitoringLocationPushes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoringLocationPushes(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startMonitoringLocationPushesWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "startMonitoringLocationPushes(completion:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/startmonitoringlocationpushes(completion:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct": {
      "abstract": [
        {
          "text": "Error codes the location manager returns if starting to monitor for location push notifications fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceError"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceError"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceError",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes the location manager returns if starting to monitor for location push notifications fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceError.Code",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/code"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingEntitlement": {
      "abstract": [
        {
          "text": "An error code that indicates the app is missing the entitlement it needs to use the location push service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingEntitlement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceErrorMissingEntitlement"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceError.Code.missingEntitlement",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/code/missingentitlement"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingPushExtension": {
      "abstract": [
        {
          "text": "An error code that indicates the app is missing a Location Push Service Extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPushExtension"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingPushExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceErrorMissingPushExtension"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceError.Code.missingPushExtension",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/code/missingpushextension"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingPushServerEnvironment": {
      "abstract": [
        {
          "text": "An error code that indicates the app is missing an Apple Push Notification service (APNs) environment entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPushServerEnvironment"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingPushServerEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceErrorMissingPushServerEnvironment"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceError.Code.missingPushServerEnvironment",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/code/missingpushserverenvironment"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An error code that indicates the app was unable to start the location push service for an unknown reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceError.Code.unknown",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/code/unknown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/unsupportedPlatform": {
      "abstract": [
        {
          "text": "An error code that indicates the location push service isn’t available on this platform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedPlatform"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/unsupportedPlatform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceErrorUnsupportedPlatform"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceError.Code.unsupportedPlatform",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/code/unsupportedplatform"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Location Push Service Extension errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceErrorDomain",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerrordomain"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceExtension": {
      "abstract": [
        {
          "text": "The interface you adopt in the type that acts as the main entry point for a Location Push Service Extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceExtension"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceExtension"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceExtension",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceextension"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.location.push": {
      "abstract": [
        {
          "text": "An entitlement to enable a location-sharing app to query someone’s location in response to a push notification.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.location.push",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.location.push",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.location.push"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Location-push-service-extension",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.location.push",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceExtension",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceErrorDomain"
      ],
      "title": "Location push service extension"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-error-code",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/unknown",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingPushExtension",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingPushServerEnvironment",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingEntitlement",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/unsupportedPlatform"
      ],
      "title": "Getting the error code"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLLocationPushServiceError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-error-code",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/unknown",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingPushExtension",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingPushServerEnvironment",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/missingEntitlement",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code/unsupportedPlatform"
              ],
              "title": "Getting the error code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Location-push-service-extension",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.location.push",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceExtension",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceErrorDomain"
              ],
              "title": "Location push service extension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLLocationPushServiceError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code~1missingPushServerEnvironment/title",
          "value": "CLLocationPushServiceErrorMissingPushServerEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code~1missingPushServerEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceErrorMissingPushServerEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code~1missingPushExtension/title",
          "value": "CLLocationPushServiceErrorMissingPushExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code~1missingPushExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceErrorMissingPushExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceErrorDomain/title",
          "value": "CLLocationPushServiceErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code~1missingEntitlement/title",
          "value": "CLLocationPushServiceErrorMissingEntitlement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code~1missingEntitlement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceErrorMissingEntitlement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code/title",
          "value": "CLLocationPushServiceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceExtension/title",
          "value": "CLLocationPushServiceExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code~1unsupportedPlatform/title",
          "value": "CLLocationPushServiceErrorUnsupportedPlatform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code~1unsupportedPlatform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceErrorUnsupportedPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code~1unknown/title",
          "value": "CLLocationPushServiceErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startMonitoringLocationPushes(completion:)/title",
          "value": "startMonitoringLocationPushesWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startMonitoringLocationPushes(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMonitoringLocationPushesWithCompletion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/cllocationpushserviceerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/cllocationpushserviceerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
