{
  "abstract": [
    {
      "text": "An error code that indicates the app is missing a Location Push Service Extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/missingPushExtension"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC26CLLocationPushServiceErrorLeV07missingB9ExtensionSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "missingPushExtension"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC26CLLocationPushServiceErrorLeV",
        "text": "CLLocationPushServiceError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CLLocationPushServiceError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "missingPushExtension"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "missingPushExtension"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC26CLLocationPushServiceErrorLeV",
              "text": "CLLocationPushServiceError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CLLocationPushServiceError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct": {
      "abstract": [
        {
          "text": "Error codes the location manager returns if starting to monitor for location push notifications fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceError"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationPushServiceError"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceError",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes the location manager returns if starting to monitor for location push notifications fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CLLocationPushServiceError.Code",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/code"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/missingEntitlement": {
      "abstract": [
        {
          "text": "An error code that indicates the app is missing the entitlement it needs to use the location push service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26CLLocationPushServiceErrorLeV",
          "text": "CLLocationPushServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLLocationPushServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/missingEntitlement",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingEntitlement",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/missingentitlement"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/missingPushExtension": {
      "abstract": [
        {
          "text": "An error code that indicates the app is missing a Location Push Service Extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPushExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26CLLocationPushServiceErrorLeV",
          "text": "CLLocationPushServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLLocationPushServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/missingPushExtension",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingPushExtension",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/missingpushextension"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/missingPushServerEnvironment": {
      "abstract": [
        {
          "text": "An error code that indicates the app is missing an Apple Push Notification service (APNs) environment entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPushServerEnvironment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26CLLocationPushServiceErrorLeV",
          "text": "CLLocationPushServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLLocationPushServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/missingPushServerEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingPushServerEnvironment",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/missingpushserverenvironment"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "An error code that indicates the app was unable to start the location push service for an unknown reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26CLLocationPushServiceErrorLeV",
          "text": "CLLocationPushServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLLocationPushServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/unknown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/unsupportedPlatform": {
      "abstract": [
        {
          "text": "An error code that indicates the location push service isn’t available on this platform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedPlatform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26CLLocationPushServiceErrorLeV",
          "text": "CLLocationPushServiceError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLLocationPushServiceError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/unsupportedPlatform",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedPlatform",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationpushserviceerror-swift.struct/unsupportedplatform"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-error-code",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/unknown",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/missingPushServerEnvironment",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/missingEntitlement",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/unsupportedPlatform",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationPushServiceError-swift.struct/Code"
      ],
      "title": "Getting the error code"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code/title",
          "value": "CLLocationPushServiceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationPushServiceError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationPushServiceError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/cllocationpushserviceerror-swift.struct/missingpushextension"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
