{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem/additionalOverflowItems"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationItem"]]},"seeAlsoSections":[{"generated":true,"title":"Working with the overflow menu","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationItem/overflowPresentationSource"],"anchor":"Working-with-the-overflow-menu"}],"metadata":{"externalID":"c:objc(cs)UINavigationItem(py)additionalOverflowItems","title":"additionalOverflowItems","roleHeading":"Instance Property","navigatorTitle":[{"text":"additionalOverflowItems","kind":"identifier"}],"modules":[{"name":"UIKit"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalOverflowItems","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIDeferredMenuElement","preciseIdentifier":"c:objc(cs)UIDeferredMenuElement","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":[{"name":"iOS","introducedAt":"16.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"16.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"16.0","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false}],"role":"symbol"},"abstract":[{"text":"Additional items to present in the overflow menu.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalOverflowItems","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIDeferredMenuElement","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDeferredMenuElement","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDeferredMenuElement"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you assign a non-"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" value to this property, the overflow menu button appears on the trailing edge of the navigation bar. This button appears regardless of whether you provide menu elements in the callback for the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDeferredMenuElement","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The system presents any menu elements you return in the callback for "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDeferredMenuElement","type":"reference","isActive":true},{"type":"text","text":" in the overflow menu. The system also populates the overflow menu with any items that can’t fit in the navigation bar due to layout space constraints."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uinavigationitem/additionaloverflowitems"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uinavigationitem/additionaloverflowitems"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit/UIDeferredMenuElement":{"title":"UIDeferredMenuElement","kind":"symbol","navigatorTitle":[{"text":"UIDeferredMenuElement","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDeferredMenuElement","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDeferredMenuElement","kind":"identifier"}],"abstract":[{"text":"A placeholder menu element that the system replaces with the result of the block’s completion handler.","type":"text"}],"url":"/documentation/uikit/uideferredmenuelement"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationItem/additionalOverflowItems":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem/additionalOverflowItems","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalOverflowItems","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDeferredMenuElement","text":"UIDeferredMenuElement","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uinavigationitem/additionaloverflowitems","navigatorTitle":[{"text":"additionalOverflowItems","kind":"identifier"}],"title":"additionalOverflowItems","abstract":[{"type":"text","text":"Additional items to present in the overflow menu."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationItem/overflowPresentationSource":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem/overflowPresentationSource","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overflowPresentationSource","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIPopoverPresentationControllerSourceItem","text":"UIPopoverPresentationControllerSourceItem","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"/documentation/uikit/uinavigationitem/overflowpresentationsource","navigatorTitle":[{"text":"overflowPresentationSource","kind":"identifier"}],"title":"overflowPresentationSource","abstract":[{"type":"text","text":"The item you can use as an anchor to present a custom UI from the overflow menu button."}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationItem":{"title":"UINavigationItem","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem","abstract":[{"text":"The items that a navigation bar displays when the associated view controller is visible.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UINavigationItem","kind":"identifier"}],"url":"/documentation/uikit/uinavigationitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UINavigationItem","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","introducedAt":"16.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"16.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"16.0","deprecated":false,"unavailable":false,"beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"additionalOverflowItems","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"additionalOverflowItems","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationItem"]]}},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationItem/overflowPresentationSource"],"title":"Working with the overflow menu","anchor":"Working-with-the-overflow-menu"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIDeferredMenuElement","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDeferredMenuElement","preciseIdentifier":"c:objc(cs)UIDeferredMenuElement","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"additionalOverflowItems","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"UIDeferredMenuElement","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeferredMenuElement/title"},{"value":[{"kind":"identifier","text":"UIDeferredMenuElement"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeferredMenuElement/fragments"},{"value":[{"kind":"identifier","text":"UIDeferredMenuElement"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeferredMenuElement/navigatorTitle"},{"value":"additionalOverflowItems","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1additionalOverflowItems/title"},{"value":[{"kind":"identifier","text":"additionalOverflowItems"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1additionalOverflowItems/fragments"},{"value":"overflowPresentationSource","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1overflowPresentationSource/title"},{"value":[{"text":"overflowPresentationSource","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1overflowPresentationSource/fragments"},{"value":"UINavigationItem","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/title"},{"value":[{"kind":"identifier","text":"UINavigationItem"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/fragments"},{"value":[{"text":"UINavigationItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}