{
  "abstract": [
    {
      "text": "The search controller to integrate into your navigation interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/searchController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UINavigationItem(py)searchController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "searchController"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UISearchController",
        "text": "UISearchController"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "searchController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "searchController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "searchController"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UISearchController",
              "text": "UISearchController"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a view controller in your navigation interface supports search, assign the corresponding search controller to this property. The navigation controller integrates the search bar from your search controller into the navigation bar interface, presenting a single bar for both search and navigation. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/hidesSearchBarWhenScrolling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to control the visibility of the search bar when scrolling.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem": {
      "abstract": [
        {
          "text": "The items that a navigation bar displays when the associated view controller is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UINavigationItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINavigationItem"
        }
      ],
      "role": "symbol",
      "title": "UINavigationItem",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/SearchBarPlacement-swift.enum": {
      "abstract": [
        {
          "text": "Constants that determine where the search bar appears in the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SearchBarPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/SearchBarPlacement-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SearchBarPlacement"
        }
      ],
      "role": "symbol",
      "title": "UINavigationItem.SearchBarPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/searchbarplacement-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/hidesSearchBarWhenScrolling": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app hides the integrated search bar when scrolling any underlying content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hidesSearchBarWhenScrolling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/hidesSearchBarWhenScrolling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidesSearchBarWhenScrolling"
        }
      ],
      "role": "symbol",
      "title": "hidesSearchBarWhenScrolling",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/hidessearchbarwhenscrolling"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/preferredSearchBarPlacement": {
      "abstract": [
        {
          "text": "The preferred placement of the search bar in the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredSearchBarPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationItem",
          "text": "UINavigationItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UINavigationItemSearchBarPlacement",
          "text": "SearchBarPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/preferredSearchBarPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredSearchBarPlacement"
        }
      ],
      "role": "symbol",
      "title": "preferredSearchBarPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/preferredsearchbarplacement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/searchBarPlacement-swift.property": {
      "abstract": [
        {
          "text": "The placement of the search bar in the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBarPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationItem",
          "text": "UINavigationItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UINavigationItemSearchBarPlacement",
          "text": "SearchBarPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/searchBarPlacement-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBarPlacement"
        }
      ],
      "role": "symbol",
      "title": "searchBarPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/searchbarplacement-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/searchController": {
      "abstract": [
        {
          "text": "The search controller to integrate into your navigation interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchController",
          "text": "UISearchController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/searchController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchController"
        }
      ],
      "role": "symbol",
      "title": "searchController",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/searchcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController": {
      "abstract": [
        {
          "text": "A view controller that manages the display of search results based on interactions with a search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchController"
        }
      ],
      "role": "symbol",
      "title": "UISearchController",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Integrating-search-into-your-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/hidesSearchBarWhenScrolling",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/searchBarPlacement-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/preferredSearchBarPlacement",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/SearchBarPlacement-swift.enum"
      ],
      "title": "Integrating search into your interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "searchController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Integrating-search-into-your-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/hidesSearchBarWhenScrolling",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/searchBarPlacement-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/preferredSearchBarPlacement",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/SearchBarPlacement-swift.enum"
              ],
              "title": "Integrating search into your interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UISearchController",
                    "text": "UISearchController"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "searchController"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/title",
          "value": "UISearchController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/title",
          "value": "UINavigationItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1hidesSearchBarWhenScrolling/title",
          "value": "hidesSearchBarWhenScrolling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1hidesSearchBarWhenScrolling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidesSearchBarWhenScrolling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1searchBarPlacement-swift.property/title",
          "value": "searchBarPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1searchBarPlacement-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchBarPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1searchController/title",
          "value": "searchController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1searchController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1preferredSearchBarPlacement/title",
          "value": "preferredSearchBarPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1preferredSearchBarPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredSearchBarPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1SearchBarPlacement-swift.enum/title",
          "value": "UINavigationItemSearchBarPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1SearchBarPlacement-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationItemSearchBarPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1SearchBarPlacement-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationItemSearchBarPlacement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uinavigationitem/searchcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uinavigationitem/searchcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
