{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://FSKit/documentation/FSKit/FSItemDeactivationOptions/FSItemDeactivationNever"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@FSItemDeactivationOptions@FSItemDeactivationNever",
    "fragments": [
      {
        "kind": "identifier",
        "text": "FSItemDeactivationNever"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FSItemDeactivationNever"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "FSItemDeactivationNever"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationNever"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSItemDeactivationOptions/FSItemDeactivationNever": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FSItemDeactivationNever"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItemDeactivationOptions/FSItemDeactivationNever",
      "kind": "symbol",
      "role": "symbol",
      "title": "FSItemDeactivationNever",
      "type": "topic",
      "url": "/documentation/fskit/fsitemdeactivationoptions/fsitemdeactivationnever"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ItemDeactivationOptions"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ItemDeactivationOptions"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.ItemDeactivationOptions",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/title",
          "value": "FSItemDeactivationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsitemdeactivationoptions/fsitemdeactivationnever"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
