{
  "abstract": [
    {
      "text": "Initializes a submesh with an index buffer and the specified properties.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(indexBuffer:indexCount:indexType:geometryType:material:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLSubmesh(im)initWithIndexBuffer:indexCount:indexType:geometryType:material:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "indexBuffer"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MDLMeshBuffer",
        "text": "MDLMeshBuffer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "indexCount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "indexType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MDLIndexBitDepth",
        "text": "MDLIndexBitDepth"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "geometryType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MDLGeometryType",
        "text": "MDLGeometryType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "material"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MDLMaterial",
        "text": "MDLMaterial"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithIndexBuffer:indexCount:indexType:geometryType:material:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(indexBuffer:indexCount:indexType:geometryType:material:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "indexBuffer"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MDLMeshBuffer",
              "text": "MDLMeshBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "indexCount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "indexType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MDLIndexBitDepth",
              "text": "MDLIndexBitDepth"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "geometryType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MDLGeometryType",
              "text": "MDLGeometryType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "material"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MDLMaterial",
              "text": "MDLMaterial"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object that provides index data for the submesh.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "indexBuffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of indices in the index buffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "indexCount"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The data type of each index in the index buffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "indexType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of geometric primitives described by the index buffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "geometryType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A description of the intended surface appearance for rendering the submesh.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "material"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new submesh object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, a submesh is imported from an asset file as a member of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, but you can also use this method to create a submesh programmatically.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType": {
      "abstract": [
        {
          "text": "Types of geometric primitives for rendering a submesh, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/geometryType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLGeometryType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLGeometryType"
        }
      ],
      "role": "symbol",
      "title": "MDLGeometryType",
      "type": "topic",
      "url": "/documentation/modelio/mdlgeometrytype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth": {
      "abstract": [
        {
          "text": "Options for the size of integer data in a submesh’s index buffer, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/indexType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLIndexBitDepth"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLIndexBitDepth"
        }
      ],
      "role": "symbol",
      "title": "MDLIndexBitDepth",
      "type": "topic",
      "url": "/documentation/modelio/mdlindexbitdepth"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial": {
      "abstract": [
        {
          "text": "A collection of material properties that together describe the intended surface appearance for rendering a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterial"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterial"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterial",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterial"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh": {
      "abstract": [
        {
          "text": "A container for vertex buffer data to be used in rendering a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "role": "symbol",
      "title": "MDLMesh",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer": {
      "abstract": [
        {
          "text": "The general interface for managing storage of vertex and index data used in loading, processing, and rendering meshes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBuffer"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMeshBuffer"
        }
      ],
      "role": "symbol",
      "title": "MDLMeshBuffer",
      "type": "topic",
      "url": "/documentation/modelio/mdlmeshbuffer"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh": {
      "abstract": [
        {
          "text": "A container for index buffer data and material information to be used in rendering all or part of a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLSubmesh"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLSubmesh"
        }
      ],
      "role": "symbol",
      "title": "MDLSubmesh",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/geometryType": {
      "abstract": [
        {
          "text": "The type of geometric primitives described by the submesh’s index buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLGeometryType",
          "text": "MDLGeometryType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/geometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "geometryType"
        }
      ],
      "role": "symbol",
      "title": "geometryType",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh/geometrytype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/indexType": {
      "abstract": [
        {
          "text": "The data type for each element in the submesh’s index buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLIndexBitDepth",
          "text": "MDLIndexBitDepth"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/indexType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexType"
        }
      ],
      "role": "symbol",
      "title": "indexType",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh/indextype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(indexBuffer:indexCount:indexType:geometryType:material:)": {
      "abstract": [
        {
          "text": "Initializes a submesh with an index buffer and the specified properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "indexBuffer"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MDLMeshBuffer",
          "text": "MDLMeshBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLIndexBitDepth",
          "text": "MDLIndexBitDepth"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "geometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLGeometryType",
          "text": "MDLGeometryType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "material"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterial",
          "text": "MDLMaterial"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(indexBuffer:indexCount:indexType:geometryType:material:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIndexBuffer:indexCount:indexType:geometryType:material:"
        }
      ],
      "role": "symbol",
      "title": "init(indexBuffer:indexCount:indexType:geometryType:material:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh/init(indexbuffer:indexcount:indextype:geometrytype:material:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(mdlSubmesh:indexType:geometryType:)": {
      "abstract": [
        {
          "text": "Initializes a submesh by copying or converting another submesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "mdlSubmesh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLSubmesh",
          "text": "MDLSubmesh"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLIndexBitDepth",
          "text": "MDLIndexBitDepth"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "geometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLGeometryType",
          "text": "MDLGeometryType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(mdlSubmesh:indexType:geometryType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithMDLSubmesh:indexType:geometryType:"
        }
      ],
      "role": "symbol",
      "title": "init(mdlSubmesh:indexType:geometryType:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh/init(mdlsubmesh:indextype:geometrytype:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(name:indexBuffer:indexCount:indexType:geometryType:material:)": {
      "abstract": [
        {
          "text": "Initializes a named submesh with an index buffer and the specified properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexBuffer"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MDLMeshBuffer",
          "text": "MDLMeshBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLIndexBitDepth",
          "text": "MDLIndexBitDepth"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "geometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLGeometryType",
          "text": "MDLGeometryType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "material"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterial",
          "text": "MDLMaterial"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(name:indexBuffer:indexCount:indexType:geometryType:material:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:indexBuffer:indexCount:indexType:geometryType:material:"
        }
      ],
      "role": "symbol",
      "title": "init(name:indexBuffer:indexCount:indexType:geometryType:material:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh/init(name:indexbuffer:indexcount:indextype:geometrytype:material:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(name:indexBuffer:indexCount:indexType:geometryType:material:topology:)": {
      "abstract": [
        {
          "text": "Initializes a named submesh with a specific topology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexBuffer"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MDLMeshBuffer",
          "text": "MDLMeshBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLIndexBitDepth",
          "text": "MDLIndexBitDepth"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "geometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLGeometryType",
          "text": "MDLGeometryType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "material"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLMaterial",
          "text": "MDLMaterial"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "topology"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLSubmeshTopology",
          "text": "MDLSubmeshTopology"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(name:indexBuffer:indexCount:indexType:geometryType:material:topology:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:indexBuffer:indexCount:indexType:geometryType:material:topology:"
        }
      ],
      "role": "symbol",
      "title": "init(name:indexBuffer:indexCount:indexType:geometryType:material:topology:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh/init(name:indexbuffer:indexcount:indextype:geometrytype:material:topology:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Submesh",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(name:indexBuffer:indexCount:indexType:geometryType:material:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(name:indexBuffer:indexCount:indexType:geometryType:material:topology:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(mdlSubmesh:indexType:geometryType:)"
      ],
      "title": "Creating a Submesh"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithIndexBuffer:indexCount:indexType:geometryType:material:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithIndexBuffer:indexCount:indexType:geometryType:material:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Submesh",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(name:indexBuffer:indexCount:indexType:geometryType:material:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(name:indexBuffer:indexCount:indexType:geometryType:material:topology:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/init(mdlSubmesh:indexType:geometryType:)"
              ],
              "title": "Creating a Submesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithIndexBuffer:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)MDLMeshBuffer",
                    "text": "id<MDLMeshBuffer>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "indexBuffer"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "indexCount:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "indexCount"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "indexType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLIndexBitDepth",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MDLIndexBitDepth",
                    "text": "MDLIndexBitDepth"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "indexType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "geometryType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MDLGeometryType",
                    "text": "MDLGeometryType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "geometryType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "material:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterial",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MDLMaterial",
                    "text": "MDLMaterial"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "material"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An object that provides index data for the submesh.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "indexBuffer"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of indices in the index buffer.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "indexCount"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The data type of each index in the index buffer.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "indexType"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type of geometric primitives described by the index buffer.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "geometryType"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A description of the intended surface appearance for rendering the submesh.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "material"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new submesh object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/title",
          "value": "MDLSubmesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1init(indexBuffer:indexCount:indexType:geometryType:material:)/title",
          "value": "initWithIndexBuffer:indexCount:indexType:geometryType:material:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1init(indexBuffer:indexCount:indexType:geometryType:material:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithIndexBuffer:indexCount:indexType:geometryType:material:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1geometryType/title",
          "value": "geometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1geometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "geometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1init(name:indexBuffer:indexCount:indexType:geometryType:material:topology:)/title",
          "value": "initWithName:indexBuffer:indexCount:indexType:geometryType:material:topology:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1init(name:indexBuffer:indexCount:indexType:geometryType:material:topology:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:indexBuffer:indexCount:indexType:geometryType:material:topology:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth/title",
          "value": "MDLIndexBitDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLIndexBitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLIndexBitDepth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLIndexBitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/title",
          "value": "MDLMeshBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1init(name:indexBuffer:indexCount:indexType:geometryType:material:)/title",
          "value": "initWithName:indexBuffer:indexCount:indexType:geometryType:material:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1init(name:indexBuffer:indexCount:indexType:geometryType:material:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:indexBuffer:indexCount:indexType:geometryType:material:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/title",
          "value": "MDLMesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/title",
          "value": "MDLMaterial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterial/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType/title",
          "value": "MDLGeometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1init(mdlSubmesh:indexType:geometryType:)/title",
          "value": "initWithMDLSubmesh:indexType:geometryType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1init(mdlSubmesh:indexType:geometryType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithMDLSubmesh:indexType:geometryType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1indexType/title",
          "value": "indexType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1indexType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indexType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlsubmesh/init(indexbuffer:indexcount:indextype:geometrytype:material:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlsubmesh/init(indexbuffer:indexcount:indextype:geometrytype:material:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
