{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unsupportedTextureTarget"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GLKTextureLoaderError@GLKTextureLoaderErrorUnsupportedTextureTarget",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unsupportedTextureTarget"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKTextureLoaderErrorUnsupportedTextureTarget"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GLKTextureLoaderError.Code.unsupportedTextureTarget"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unsupportedTextureTarget"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderError"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderError"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Values to be returned when a texture loader encounters an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/alphaPremultiplicationFailure": {
      "abstract": [
        {
          "text": "The texture source data does not allow the alpha to be premultiplied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaPremultiplicationFailure"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/alphaPremultiplicationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorAlphaPremultiplicationFailure"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.alphaPremultiplicationFailure",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/alphapremultiplicationfailure"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/compressedTextureUpload": {
      "abstract": [
        {
          "text": "A compressed texture could not be uploaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compressedTextureUpload"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/compressedTextureUpload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorCompressedTextureUpload"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.compressedTextureUpload",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/compressedtextureupload"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/cubeMapInvalidNumFiles": {
      "abstract": [
        {
          "text": "The incorrect number of files were specified for the cube map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cubeMapInvalidNumFiles"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/cubeMapInvalidNumFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorCubeMapInvalidNumFiles"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.cubeMapInvalidNumFiles",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/cubemapinvalidnumfiles"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/dataPreprocessingFailure": {
      "abstract": [
        {
          "text": "The data could not be preprocessed correctly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataPreprocessingFailure"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/dataPreprocessingFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorDataPreprocessingFailure"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.dataPreprocessingFailure",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/datapreprocessingfailure"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/fileOrURLNotFound": {
      "abstract": [
        {
          "text": "A file could not be found at the path provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileOrURLNotFound"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/fileOrURLNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorFileOrURLNotFound"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.fileOrURLNotFound",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/fileorurlnotfound"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/incompatibleFormatSRGB": {
      "abstract": [
        {
          "text": "The decoded data was in an incompatible format for an sRGB texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatibleFormatSRGB"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/incompatibleFormatSRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorIncompatibleFormatSRGB"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.incompatibleFormatSRGB",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/incompatibleformatsrgb"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidCGImage": {
      "abstract": [
        {
          "text": "The image provided was invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCGImage"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidCGImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorInvalidCGImage"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.invalidCGImage",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/invalidcgimage"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidEAGLContext": {
      "abstract": [
        {
          "text": "The EAGL context was not a valid context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEAGLContext"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidEAGLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorInvalidEAGLContext"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.invalidEAGLContext",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/invalideaglcontext"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidNSData": {
      "abstract": [
        {
          "text": "The data provided is not in a recognized image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNSData"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidNSData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorInvalidNSData"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.invalidNSData",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/invalidnsdata"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/mipmapUnsupported": {
      "abstract": [
        {
          "text": "The texture source data does not allow mipmaps to be generated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mipmapUnsupported"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/mipmapUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorMipmapUnsupported"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.mipmapUnsupported",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/mipmapunsupported"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/pvrAtlasUnsupported": {
      "abstract": [
        {
          "text": "Cube maps may not be compressed in PVRTC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pvrAtlasUnsupported"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/pvrAtlasUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorPVRAtlasUnsupported"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.pvrAtlasUnsupported",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/pvratlasunsupported"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/reorientationFailure": {
      "abstract": [
        {
          "text": "The texture source data does not allow the image to be reoriented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reorientationFailure"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/reorientationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorReorientationFailure"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.reorientationFailure",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/reorientationfailure"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/uncompressedTextureUpload": {
      "abstract": [
        {
          "text": "An uncompressed texture could not be uploaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uncompressedTextureUpload"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/uncompressedTextureUpload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorUncompressedTextureUpload"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.uncompressedTextureUpload",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/uncompressedtextureupload"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unknownFileType": {
      "abstract": [
        {
          "text": "The file was in an unrecognized format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownFileType"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unknownFileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorUnknownFileType"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.unknownFileType",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/unknownfiletype"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unknownPathType": {
      "abstract": [
        {
          "text": "The path type was unrecognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownPathType"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unknownPathType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorUnknownPathType"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.unknownPathType",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/unknownpathtype"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unsupportedTextureTarget": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedTextureTarget"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unsupportedTextureTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureLoaderErrorUnsupportedTextureTarget"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureLoaderError.Code.unsupportedTextureTarget",
      "type": "topic",
      "url": "/documentation/glkit/glktextureloadererror-swift.struct/code/unsupportedtexturetarget"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/alphaPremultiplicationFailure",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/compressedTextureUpload",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/cubeMapInvalidNumFiles",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/dataPreprocessingFailure",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/fileOrURLNotFound",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/incompatibleFormatSRGB",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidCGImage",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidEAGLContext",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidNSData",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/mipmapUnsupported",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/pvrAtlasUnsupported",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/reorientationFailure",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/uncompressedTextureUpload",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unknownFileType",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unknownPathType"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKTextureLoaderErrorUnsupportedTextureTarget"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorUnsupportedTextureTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/alphaPremultiplicationFailure",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/compressedTextureUpload",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/cubeMapInvalidNumFiles",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/dataPreprocessingFailure",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/fileOrURLNotFound",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/incompatibleFormatSRGB",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidCGImage",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidEAGLContext",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/invalidNSData",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/mipmapUnsupported",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/pvrAtlasUnsupported",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/reorientationFailure",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/uncompressedTextureUpload",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unknownFileType",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureLoaderError-swift.struct/Code/unknownPathType"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GLKTextureLoaderErrorUnsupportedTextureTarget"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1compressedTextureUpload/title",
          "value": "GLKTextureLoaderErrorCompressedTextureUpload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1compressedTextureUpload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorCompressedTextureUpload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1cubeMapInvalidNumFiles/title",
          "value": "GLKTextureLoaderErrorCubeMapInvalidNumFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1cubeMapInvalidNumFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorCubeMapInvalidNumFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1invalidEAGLContext/title",
          "value": "GLKTextureLoaderErrorInvalidEAGLContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1invalidEAGLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorInvalidEAGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1invalidCGImage/title",
          "value": "GLKTextureLoaderErrorInvalidCGImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1invalidCGImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorInvalidCGImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1alphaPremultiplicationFailure/title",
          "value": "GLKTextureLoaderErrorAlphaPremultiplicationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1alphaPremultiplicationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorAlphaPremultiplicationFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1mipmapUnsupported/title",
          "value": "GLKTextureLoaderErrorMipmapUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1mipmapUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorMipmapUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1invalidNSData/title",
          "value": "GLKTextureLoaderErrorInvalidNSData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1invalidNSData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorInvalidNSData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1unsupportedTextureTarget/title",
          "value": "GLKTextureLoaderErrorUnsupportedTextureTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1unsupportedTextureTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorUnsupportedTextureTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1unknownFileType/title",
          "value": "GLKTextureLoaderErrorUnknownFileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1unknownFileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorUnknownFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1uncompressedTextureUpload/title",
          "value": "GLKTextureLoaderErrorUncompressedTextureUpload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1uncompressedTextureUpload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorUncompressedTextureUpload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1reorientationFailure/title",
          "value": "GLKTextureLoaderErrorReorientationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1reorientationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorReorientationFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1dataPreprocessingFailure/title",
          "value": "GLKTextureLoaderErrorDataPreprocessingFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1dataPreprocessingFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorDataPreprocessingFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1unknownPathType/title",
          "value": "GLKTextureLoaderErrorUnknownPathType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1unknownPathType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorUnknownPathType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1fileOrURLNotFound/title",
          "value": "GLKTextureLoaderErrorFileOrURLNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1fileOrURLNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorFileOrURLNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1incompatibleFormatSRGB/title",
          "value": "GLKTextureLoaderErrorIncompatibleFormatSRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1incompatibleFormatSRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorIncompatibleFormatSRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/title",
          "value": "GLKTextureLoaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1pvrAtlasUnsupported/title",
          "value": "GLKTextureLoaderErrorPVRAtlasUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureLoaderError-swift.struct~1Code~1pvrAtlasUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureLoaderErrorPVRAtlasUnsupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glktextureloadererror-swift.struct/code/unsupportedtexturetarget"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glktextureloadererror-swift.struct/code/unsupportedtexturetarget"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
