{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression/tgaCompressionRLE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CGImagePropertyTGACompression@kCGImageTGACompressionRLE",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tgaCompressionRLE"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImageTGACompressionRLE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CGImagePropertyTGACompression.tgaCompressionRLE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tgaCompressionRLE"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImagePropertyTGACompression"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImagePropertyTGACompression"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyTGACompression",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertytgacompression"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression/tgaCompressionNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tgaCompressionNone"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression/tgaCompressionNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageTGACompressionNone"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyTGACompression.tgaCompressionNone",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertytgacompression/tgacompressionnone"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression/tgaCompressionRLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tgaCompressionRLE"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression/tgaCompressionRLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageTGACompressionRLE"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyTGACompression.tgaCompressionRLE",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertytgacompression/tgacompressionrle"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compression-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression/tgaCompressionNone"
      ],
      "title": "Compression Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImageTGACompressionRLE"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageTGACompressionRLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Compression-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyTGACompression/tgaCompressionNone"
              ],
              "title": "Compression Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCGImageTGACompressionRLE"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyTGACompression/title",
          "value": "CGImagePropertyTGACompression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyTGACompression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyTGACompression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyTGACompression/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyTGACompression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyTGACompression~1tgaCompressionNone/title",
          "value": "kCGImageTGACompressionNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyTGACompression~1tgaCompressionNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageTGACompressionNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyTGACompression~1tgaCompressionRLE/title",
          "value": "kCGImageTGACompressionRLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyTGACompression~1tgaCompressionRLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageTGACompressionRLE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimagepropertytgacompression/tgacompressionrle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimagepropertytgacompression/tgacompressionrle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
