{
  "abstract": [
    {
      "text": "The start time of the segment in the processed audio stream.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.speech/documentation/Speech",
        "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment/timestamp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFTranscriptionSegment(py)timestamp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "timestamp"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTimeInterval",
        "text": "TimeInterval"
      }
    ],
    "modules": [
      {
        "name": "Speech"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "timestamp"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "timestamp"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "timestamp"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTimeInterval",
              "text": "TimeInterval"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment/timestamp",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is the number of seconds between the beginning of the audio content and when the user spoke the word represented by the segment. For example, if the user said the word “time” one second into the transcription “What time is it”, the timestamp would be equal to ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.speech/documentation/Speech": {
      "abstract": [
        {
          "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech",
      "kind": "symbol",
      "role": "collection",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/speech"
    },
    "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment": {
      "abstract": [
        {
          "text": "A discrete part of an entire transcription, as identified by the speech recognizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFTranscriptionSegment"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFTranscriptionSegment"
        }
      ],
      "role": "symbol",
      "title": "SFTranscriptionSegment",
      "type": "topic",
      "url": "/documentation/speech/sftranscriptionsegment"
    },
    "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment/duration": {
      "abstract": [
        {
          "text": "The number of seconds it took for the user to speak the utterance represented by the segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/speech/sftranscriptionsegment/duration"
    },
    "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment/timestamp": {
      "abstract": [
        {
          "text": "The start time of the segment in the processed audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment/timestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timestamp"
        }
      ],
      "role": "symbol",
      "title": "timestamp",
      "type": "topic",
      "url": "/documentation/speech/sftranscriptionsegment/timestamp"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "TimeInterval",
      "type": "topic",
      "url": "/documentation/foundation/timeinterval"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Audio-Timing-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment/duration"
      ],
      "title": "Getting the Audio Timing Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "timestamp"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.speech/documentation/Speech",
                "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Audio-Timing-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment/duration"
              ],
              "title": "Getting the Audio Timing Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSTimeInterval",
                    "text": "NSTimeInterval"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "timestamp"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscriptionSegment~1timestamp/title",
          "value": "timestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscriptionSegment~1timestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title",
          "value": "NSTimeInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscriptionSegment/title",
          "value": "SFTranscriptionSegment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscriptionSegment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFTranscriptionSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscriptionSegment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFTranscriptionSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscriptionSegment~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscriptionSegment~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/speech/sftranscriptionsegment/timestamp"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/speech/sftranscriptionsegment/timestamp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
