{
  "abstract": [
    {
      "text": "The type of argument that corresponds to the placeholder.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.oslog/documentation/OSLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argumentCategory-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)OSLogMessageComponent(py)argumentCategory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "argumentCategory"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)OSLogMessageComponent",
        "text": "OSLogMessageComponent"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OSLogMessageComponentArgumentCategory",
        "text": "ArgumentCategory"
      }
    ],
    "modules": [
      {
        "name": "OSLog"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "argumentCategory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "argumentCategory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "argumentCategory"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)OSLogMessageComponent",
              "text": "OSLogMessageComponent"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OSLogMessageComponentArgumentCategory",
              "text": "ArgumentCategory"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.oslog/documentation/OSLog": {
      "abstract": [
        {
          "text": "A unified logging system for the reading of historical data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog",
      "kind": "symbol",
      "role": "collection",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/oslog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent": {
      "abstract": [
        {
          "text": "The message arguments for a particular entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogMessageComponent"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogMessageComponent"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum": {
      "abstract": [
        {
          "text": "An object representing data that corresponds to an argument in a message payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Argument"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Argument"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.Argument",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.enum"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum": {
      "abstract": [
        {
          "text": "The data type corresponding to the argument provided in a message payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArgumentCategory"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArgumentCategory"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.ArgumentCategory",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argument-swift.property": {
      "abstract": [
        {
          "text": "The argument passed into the message component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OSLogMessageComponent",
          "text": "OSLogMessageComponent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So21OSLogMessageComponentC0A0E8ArgumentO",
          "text": "Argument"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argument-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "argument",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.property"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argumentCategory-swift.property": {
      "abstract": [
        {
          "text": "The type of argument that corresponds to the placeholder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argumentCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OSLogMessageComponent",
          "text": "OSLogMessageComponent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSLogMessageComponentArgumentCategory",
          "text": "ArgumentCategory"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argumentCategory-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "argumentCategory"
        }
      ],
      "role": "symbol",
      "title": "argumentCategory",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.property"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-the-Argument",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argument-swift.property",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum"
      ],
      "title": "Reading the Argument"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "argumentCategory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "argumentCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.oslog/documentation/OSLog",
                "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-the-Argument",
              "generated": true,
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum"
              ],
              "title": "Reading the Argument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@OSLogMessageComponentArgumentCategory",
                    "text": "OSLogMessageComponentArgumentCategory"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "argumentCategory"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum/title",
          "value": "OSLogMessageComponentArgumentCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1argumentCategory-swift.property/title",
          "value": "argumentCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1argumentCategory-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "argumentCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/title",
          "value": "OSLogMessageComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
