{
  "abstract": [
    {
      "text": "The data type corresponding to the argument provided in a message payload.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.oslog/documentation/OSLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "OSLog",
    "externalID": "c:@E@OSLogMessageComponentArgumentCategory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ArgumentCategory"
      }
    ],
    "modules": [
      {
        "name": "OSLog"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ArgumentCategory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "OSLogMessageComponent.ArgumentCategory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ArgumentCategory"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For example, ",
              "type": "text"
            },
            {
              "code": "OSLogMessageComponent",
              "type": "codeVoice"
            },
            {
              "text": " can represent the number associated with a ",
              "type": "text"
            },
            {
              "code": "%d",
              "type": "codeVoice"
            },
            {
              "text": " placeholder. This value can be undefined if the argument data cann’t be decoded, for example if it were redacted.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsdata": {
      "abstract": [
        {
          "text": "A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSData",
      "type": "topic",
      "url": "/documentation/foundation/nsdata"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.oslog/documentation/OSLog": {
      "abstract": [
        {
          "text": "A unified logging system for the reading of historical data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog",
      "kind": "symbol",
      "role": "collection",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/oslog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent": {
      "abstract": [
        {
          "text": "The message arguments for a particular entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogMessageComponent"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogMessageComponent"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum": {
      "abstract": [
        {
          "text": "An object representing data that corresponds to an argument in a message payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Argument"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Argument"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.Argument",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.enum"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum": {
      "abstract": [
        {
          "text": "The data type corresponding to the argument provided in a message payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArgumentCategory"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArgumentCategory"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.ArgumentCategory",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/data": {
      "abstract": [
        {
          "text": "The argument is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogMessageComponentArgumentCategoryData"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.ArgumentCategory.data",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum/data"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/double": {
      "abstract": [
        {
          "text": "The argument is a double.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogMessageComponentArgumentCategoryDouble"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.ArgumentCategory.double",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum/double"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/int64": {
      "abstract": [
        {
          "text": "The argument is a 64-bit signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int64"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/int64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogMessageComponentArgumentCategoryInt64"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.ArgumentCategory.int64",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum/int64"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/string": {
      "abstract": [
        {
          "text": "The argument is a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/string",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogMessageComponentArgumentCategoryString"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.ArgumentCategory.string",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum/string"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/uInt64": {
      "abstract": [
        {
          "text": "The argument is a 64-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uInt64"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/uInt64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogMessageComponentArgumentCategoryUInt64"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.ArgumentCategory.uInt64",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum/uint64"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/undefined": {
      "abstract": [
        {
          "text": "The argument’s type is not defined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogMessageComponentArgumentCategoryUndefined"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent.ArgumentCategory.undefined",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum/undefined"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argument-swift.property": {
      "abstract": [
        {
          "text": "The argument passed into the message component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OSLogMessageComponent",
          "text": "OSLogMessageComponent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So21OSLogMessageComponentC0A0E8ArgumentO",
          "text": "Argument"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argument-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "argument",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argument-swift.property"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argumentCategory-swift.property": {
      "abstract": [
        {
          "text": "The type of argument that corresponds to the placeholder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argumentCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OSLogMessageComponent",
          "text": "OSLogMessageComponent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSLogMessageComponentArgumentCategory",
          "text": "ArgumentCategory"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argumentCategory-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "argumentCategory"
        }
      ],
      "role": "symbol",
      "title": "argumentCategory",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-the-Argument",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argument-swift.property",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/Argument-swift.enum",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argumentCategory-swift.property"
      ],
      "title": "Reading the Argument"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/data",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/double",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/int64",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/string",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/uInt64",
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/undefined"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OSLogMessageComponentArgumentCategory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.oslog/documentation/OSLog"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/data",
                "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/double",
                "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/int64",
                "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/string",
                "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/uInt64",
                "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/ArgumentCategory-swift.enum/undefined"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-the-Argument",
              "generated": true,
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent/argumentCategory-swift.property"
              ],
              "title": "Reading the Argument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OSLogMessageComponentArgumentCategory"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1data/title",
          "value": "OSLogMessageComponentArgumentCategoryData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategoryData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/title",
          "value": "OSLogMessageComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1string/title",
          "value": "OSLogMessageComponentArgumentCategoryString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1string/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategoryString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1int64/title",
          "value": "OSLogMessageComponentArgumentCategoryInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1int64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategoryInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1double/title",
          "value": "OSLogMessageComponentArgumentCategoryDouble"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategoryDouble"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdata/abstract",
          "value": [
            {
              "text": "A static byte buffer in memory.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1argumentCategory-swift.property/title",
          "value": "argumentCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1argumentCategory-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "argumentCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1undefined/title",
          "value": "OSLogMessageComponentArgumentCategoryUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategoryUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1uInt64/title",
          "value": "OSLogMessageComponentArgumentCategoryUInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum~1uInt64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategoryUInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum/title",
          "value": "OSLogMessageComponentArgumentCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent~1ArgumentCategory-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponentArgumentCategory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/oslog/oslogmessagecomponent/argumentcategory-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
