{
  "abstract": [
    {
      "text": "Message identifier for joining.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use MusicSubscriptionOffer.MessageIdentifier.join from MusicKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/join"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "StoreKit",
    "externalID": "c:@SKCloudServiceSetupMessageIdentifierJoin",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "join"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SKCloudServiceSetupMessageIdentifier",
        "text": "SKCloudServiceSetupMessageIdentifier"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKCloudServiceSetupMessageIdentifierJoin"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.0",
        "message": "Use MusicSubscriptionOffer.MessageIdentifier.join from MusicKit",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.0",
        "message": "Use MusicSubscriptionOffer.MessageIdentifier.join from MusicKit",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "Use MusicSubscriptionOffer.MessageIdentifier.join from MusicKit",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.0",
        "message": "Use MusicSubscriptionOffer.MessageIdentifier.join from MusicKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "join"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "join"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SKCloudServiceSetupMessageIdentifier",
              "text": "SKCloudServiceSetupMessageIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.storekit/documentation/StoreKit/offering-apple-music-subscription-in-your-app"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier": {
      "abstract": [
        {
          "text": "Identifiers for the available messages the setup view can present to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceSetupMessageIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceSetupMessageIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceSetupMessageIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicesetupmessageidentifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/addMusic": {
      "abstract": [
        {
          "text": "Message identifier for adding music.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addMusic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKCloudServiceSetupMessageIdentifier",
          "text": "SKCloudServiceSetupMessageIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/addMusic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceSetupMessageIdentifierAddMusic"
        }
      ],
      "role": "symbol",
      "title": "addMusic",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicesetupmessageidentifier/addmusic"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/connect": {
      "abstract": [
        {
          "text": "Message identifier for connecting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKCloudServiceSetupMessageIdentifier",
          "text": "SKCloudServiceSetupMessageIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/connect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceSetupMessageIdentifierConnect"
        }
      ],
      "role": "symbol",
      "title": "connect",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicesetupmessageidentifier/connect"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/join": {
      "abstract": [
        {
          "text": "Message identifier for joining.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "join"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKCloudServiceSetupMessageIdentifier",
          "text": "SKCloudServiceSetupMessageIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/join",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceSetupMessageIdentifierJoin"
        }
      ],
      "role": "symbol",
      "title": "join",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicesetupmessageidentifier/join"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/playMusic": {
      "abstract": [
        {
          "text": "Message identifier for playing music.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playMusic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKCloudServiceSetupMessageIdentifier",
          "text": "SKCloudServiceSetupMessageIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/playMusic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceSetupMessageIdentifierPlayMusic"
        }
      ],
      "role": "symbol",
      "title": "playMusic",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicesetupmessageidentifier/playmusic"
    },
    "doc://com.apple.storekit/documentation/StoreKit/offering-apple-music-subscription-in-your-app": {
      "abstract": [
        {
          "text": "Allow eligible customers to subscribe to Apple Music.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/offering-apple-music-subscription-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Offering Apple Music Subscription in Your App",
      "type": "topic",
      "url": "/documentation/storekit/offering-apple-music-subscription-in-your-app"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Message-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/addMusic",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/connect",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/playMusic"
      ],
      "title": "Message Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKCloudServiceSetupMessageIdentifierJoin"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupMessageIdentifierJoin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Message-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/addMusic",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/connect",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier/playMusic"
              ],
              "title": "Message Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupMessageIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SKCloudServiceSetupMessageIdentifier",
                    "text": "SKCloudServiceSetupMessageIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKCloudServiceSetupMessageIdentifierJoin"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use MusicSubscriptionOffer.MessageIdentifier.join from MusicKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier~1playMusic/title",
          "value": "SKCloudServiceSetupMessageIdentifierPlayMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier~1playMusic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupMessageIdentifierPlayMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier/title",
          "value": "SKCloudServiceSetupMessageIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupMessageIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupMessageIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier~1addMusic/title",
          "value": "SKCloudServiceSetupMessageIdentifierAddMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier~1addMusic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupMessageIdentifierAddMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier~1join/title",
          "value": "SKCloudServiceSetupMessageIdentifierJoin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier~1join/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupMessageIdentifierJoin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier~1connect/title",
          "value": "SKCloudServiceSetupMessageIdentifierConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupMessageIdentifier~1connect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupMessageIdentifierConnect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skcloudservicesetupmessageidentifier/join"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skcloudservicesetupmessageidentifier/join"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
