{
  "abstract": [
    {
      "text": "Constants that specify whether the orthogonal scrolling section bounces past the edge of content and back again.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UICollectionLayoutSectionOrthogonalScrollingBounce",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Bounce"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Bounce"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UICollectionLayoutSectionOrthogonalScrollingProperties.Bounce"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Bounce"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties": {
      "abstract": [
        {
          "text": "An object that specifies properties for a layout section that scrolls orthogonally in relation to the main layout axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify whether the orthogonal scrolling section bounces past the edge of content and back again.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bounce"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Bounce"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingProperties.Bounce",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/bounce-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/always": {
      "abstract": [
        {
          "text": "The orthogonal scroll view bounces even if the content is smaller than its bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "always"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/always",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBounceAlways"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingProperties.Bounce.always",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/bounce-swift.enum/always"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/automatic": {
      "abstract": [
        {
          "text": "The orthogonal scroll view bounces when it encounters a content boundary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBounceAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingProperties.Bounce.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/bounce-swift.enum/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/bounce-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/never": {
      "abstract": [
        {
          "text": "The orthogonal scroll view stops scrolling immediately when it encounters a content boundary without bouncing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "never"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/never",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBounceNever"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingProperties.Bounce.never",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/bounce-swift.enum/never"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/bounce-swift.property": {
      "abstract": [
        {
          "text": "A value that specifies whether the orthogonal scrolling section bounces past the edge of content and back again.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bounce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionLayoutSectionOrthogonalScrollingProperties",
          "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UICollectionLayoutSectionOrthogonalScrollingBounce",
          "text": "Bounce"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/bounce-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bounce"
        }
      ],
      "role": "symbol",
      "title": "bounce",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/bounce-swift.property"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-bounce-behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/bounce-swift.property"
      ],
      "title": "Specifying the bounce behavior"
    }
  ],
  "topicSections": [
    {
      "anchor": "Selecting-bounce-options",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/always",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/never"
      ],
      "title": "Selecting bounce options"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBounce"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBounce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBounce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Selecting-bounce-options",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/always",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/Bounce-swift.enum/never"
              ],
              "title": "Selecting bounce options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-the-bounce-behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/bounce-swift.property"
              ],
              "title": "Specifying the bounce behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UICollectionLayoutSectionOrthogonalScrollingBounce"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1Bounce-swift.enum~1never/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBounceNever"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1Bounce-swift.enum~1never/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBounceNever"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1Bounce-swift.enum/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBounce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1Bounce-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBounce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1Bounce-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBounce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1bounce-swift.property/title",
          "value": "bounce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1bounce-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bounce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1Bounce-swift.enum~1automatic/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBounceAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1Bounce-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBounceAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1Bounce-swift.enum~1always/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBounceAlways"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1Bounce-swift.enum~1always/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBounceAlways"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/bounce-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/bounce-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
