{
  "abstract": [
    {
      "text": "Constants that specify the rate of deceleration in the orthogonal scrolling section after the scrolling pan gesture ends.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@T@UICollectionLayoutSectionOrthogonalScrollingDecelerationRate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DecelerationRate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DecelerationRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UICollectionLayoutSectionOrthogonalScrollingProperties.DecelerationRate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DecelerationRate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties": {
      "abstract": [
        {
          "text": "An object that specifies properties for a layout section that scrolls orthogonally in relation to the main layout axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify the rate of deceleration in the orthogonal scrolling section after the scrolling pan gesture ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DecelerationRate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DecelerationRate"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingProperties.DecelerationRate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/decelerationrate-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/automatic": {
      "abstract": [
        {
          "text": "A deceleration rate that matches the parent scroll view’s deceleration rate for the orthogonal scrolling section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionLayoutSectionOrthogonalScrollingProperties",
          "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UICollectionLayoutSectionOrthogonalScrollingDecelerationRate",
          "text": "DecelerationRate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRateAutomatic"
        }
      ],
      "role": "symbol",
      "title": "automatic",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/decelerationrate-swift.struct/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/fast": {
      "abstract": [
        {
          "text": "A rapid deceleration rate for the orthogonal scrolling section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionLayoutSectionOrthogonalScrollingProperties",
          "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UICollectionLayoutSectionOrthogonalScrollingDecelerationRate",
          "text": "DecelerationRate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/fast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRateFast"
        }
      ],
      "role": "symbol",
      "title": "fast",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/decelerationrate-swift.struct/fast"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a deceleration rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/decelerationrate-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/normal": {
      "abstract": [
        {
          "text": "The default deceleration rate for the orthogonal scrolling section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionLayoutSectionOrthogonalScrollingProperties",
          "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UICollectionLayoutSectionOrthogonalScrollingDecelerationRate",
          "text": "DecelerationRate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRateNormal"
        }
      ],
      "role": "symbol",
      "title": "normal",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/decelerationrate-swift.struct/normal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/decelerationRate-swift.property": {
      "abstract": [
        {
          "text": "A value that specifies the rate of deceleration in the orthogonal scrolling section after the scrolling pan gesture ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decelerationRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionLayoutSectionOrthogonalScrollingProperties",
          "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UICollectionLayoutSectionOrthogonalScrollingDecelerationRate",
          "text": "DecelerationRate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/decelerationRate-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decelerationRate"
        }
      ],
      "role": "symbol",
      "title": "decelerationRate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/decelerationrate-swift.property"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-rate-of-deceleration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/decelerationRate-swift.property"
      ],
      "title": "Specifying the rate of deceleration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Selecting-deceleration-rates",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/fast",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/normal"
      ],
      "title": "Selecting deceleration rates"
    },
    {
      "anchor": "Creating-a-deceleration-rate",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/init(rawValue:)"
      ],
      "title": "Creating a deceleration rate"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Selecting-deceleration-rates",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/fast",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/DecelerationRate-swift.struct/normal"
              ],
              "title": "Selecting deceleration rates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-the-rate-of-deceleration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingProperties/decelerationRate-swift.property"
              ],
              "title": "Specifying the rate of deceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1DecelerationRate-swift.struct~1normal/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRateNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1DecelerationRate-swift.struct~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRateNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1decelerationRate-swift.property/title",
          "value": "decelerationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1decelerationRate-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "decelerationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1DecelerationRate-swift.struct~1automatic/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRateAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1DecelerationRate-swift.struct~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRateAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1DecelerationRate-swift.struct~1fast/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRateFast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1DecelerationRate-swift.struct~1fast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRateFast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1DecelerationRate-swift.struct/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1DecelerationRate-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties~1DecelerationRate-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingDecelerationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingProperties"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/decelerationrate-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingproperties/decelerationrate-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
