{
  "abstract": [
    {
      "text": "A configuration that describes the launch scene’s background.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewControllerLaunchOptions/background"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIDocumentViewControllerLaunchOptions(py)background",
    "fragments": [
      {
        "kind": "identifier",
        "text": "background"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "background"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "background"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-c.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIBackgroundConfiguration",
              "text": "UIBackgroundConfiguration"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "background"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/customizing-a-document-based-app-s-launch-experience"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-c.class": {
      "abstract": [
        {
          "text": "A configuration that describes a specific background appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIBackgroundConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class": {
      "abstract": [
        {
          "text": "Options for customizing the document launch view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LaunchOptions"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentViewController.LaunchOptions",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontroller/launchoptions-swift.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/browserViewController": {
      "abstract": [
        {
          "text": "The document browser view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "browserViewController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentBrowserViewController",
          "text": "UIDocumentBrowserViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/browserViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "browserViewController"
        }
      ],
      "role": "symbol",
      "title": "browserViewController",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontroller/launchoptions-swift.class/browserviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/documentTargetView": {
      "abstract": [
        {
          "text": "The document target view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentTargetView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/documentTargetView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentTargetView"
        }
      ],
      "role": "symbol",
      "title": "documentTargetView",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontroller/launchoptions-swift.class/documenttargetview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/title": {
      "abstract": [
        {
          "text": "The title that appears in the title view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontroller/launchoptions-swift.class/title"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewControllerLaunchOptions/background": {
      "abstract": [
        {
          "text": "A configuration that describes the launch scene’s background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "background"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewControllerLaunchOptions/background",
      "kind": "symbol",
      "role": "symbol",
      "title": "background",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontrollerlaunchoptions/background"
    },
    "doc://com.apple.uikit/documentation/UIKit/customizing-a-document-based-app-s-launch-experience": {
      "abstract": [
        {
          "text": "Add unique elements to your app’s document launch scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/customizing-a-document-based-app-s-launch-experience",
      "kind": "article",
      "role": "article",
      "title": "Customizing a document-based app’s launch experience",
      "type": "topic",
      "url": "/documentation/uikit/customizing-a-document-based-app-s-launch-experience"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/title",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/documentTargetView",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/browserViewController"
      ],
      "title": "Configuring the appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class/title",
          "value": "UIDocumentViewControllerLaunchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentViewControllerLaunchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentViewControllerLaunchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1browserViewController/title",
          "value": "browserViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1browserViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "browserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1documentTargetView/title",
          "value": "documentTargetView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1documentTargetView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentTargetView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidocumentviewcontrollerlaunchoptions/background"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
