{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITextContentType/password"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextContentType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"password","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextContentType","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextContentType","preciseIdentifier":"c:@T@UITextContentType","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}],"variants":[{"paths":["/documentation/uikit/uitextcontenttype/password"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitextcontenttype/password"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"extendedModule":"UIKit","role":"symbol","title":"password","externalID":"c:@UITextContentTypePassword","navigatorTitle":[{"text":"UITextContentTypePassword","kind":"identifier"}],"roleHeading":"Type Property","modules":[{"name":"UIKit"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"password","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextContentType","preciseIdentifier":"c:@T@UITextContentType","kind":"typeIdentifier"}],"platforms":[{"deprecated":false,"name":"iOS","introducedAt":"11.0","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","introducedAt":"11.0","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","introducedAt":"11.0","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false}]},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextContentType/username","doc://com.apple.uikit/documentation/UIKit/UITextContentType/newPassword"],"generated":true,"title":"Managing accounts","anchor":"Managing-accounts"}],"kind":"symbol","abstract":[{"text":"A property that defines the content in a text input area as a password.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.apple.uikit/documentation/UIKit/UITextContentType/password":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextContentType/password","kind":"symbol","url":"/documentation/uikit/uitextcontenttype/password","navigatorTitle":[{"kind":"identifier","text":"UITextContentTypePassword"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"password"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UITextContentType","kind":"typeIdentifier","text":"UITextContentType"}],"role":"symbol","type":"topic","title":"password","abstract":[{"type":"text","text":"A property that defines the content in a text input area as a password."}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextContentType":{"title":"UITextContentType","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextContentType","abstract":[{"text":"Constants that identify the semantic meaning for a text-entry area.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UITextContentType","kind":"identifier"}],"url":"/documentation/uikit/uitextcontenttype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextContentType","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextContentType/newPassword":{"url":"/documentation/uikit/uitextcontenttype/newpassword","navigatorTitle":[{"text":"UITextContentTypeNewPassword","kind":"identifier"}],"abstract":[{"type":"text","text":"A property that defines the content in a text input area as a new password."}],"type":"topic","title":"newPassword","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextContentType/newPassword","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"newPassword"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UITextContentType","text":"UITextContentType","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITextContentType/username":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextContentType/username","kind":"symbol","url":"/documentation/uikit/uitextcontenttype/username","navigatorTitle":[{"text":"UITextContentTypeUsername","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"username"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UITextContentType","text":"UITextContentType","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"username","abstract":[{"type":"text","text":"A property that defines the content in a text input area as an account or login name."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","unavailable":false,"introducedAt":"11.0","beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"introducedAt":"11.0","beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","beta":false,"deprecated":false},{"name":"tvOS","unavailable":false,"introducedAt":"11.0","beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","value":"UITextContentTypePassword","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"UITextContentTypePassword"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Managing accounts","anchor":"Managing-accounts","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextContentType/username","doc://com.apple.uikit/documentation/UIKit/UITextContentType/newPassword"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextContentType","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextContentType","preciseIdentifier":"c:@T@UITextContentType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextContentTypePassword","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType~1password/title","value":"UITextContentTypePassword"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType~1password/fragments","value":[{"kind":"identifier","text":"UITextContentTypePassword"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/title","value":"UITextContentType"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/fragments","value":[{"kind":"identifier","text":"UITextContentType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/navigatorTitle","value":[{"text":"UITextContentType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType~1newPassword/title","value":"UITextContentTypeNewPassword"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType~1newPassword/fragments","value":[{"kind":"identifier","text":"UITextContentTypeNewPassword"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType~1username/title","value":"UITextContentTypeUsername"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType~1username/fragments","value":[{"text":"UITextContentTypeUsername","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}