{"abstract":[{"type":"text","text":"Constants describing the types of events possible for controls."}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["/documentation/uikit/uicontrol/event"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uicontrol/event"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Event","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/responding-to-control-based-events-using-target-action"]},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"You set up a control so that it sends an action message to a target object by associating both target and action with one or more control events. To do this, send ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/addTarget(_:action:for:)","type":"reference"},{"text":" to the control for each target-action pair you want to specify.","type":"text"}]}]}],"metadata":{"symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Event","kind":"identifier"}],"extendedModule":"UIKit","externalID":"c:@E@UIControlEvents","roleHeading":"Structure","title":"UIControl.Event","role":"symbol","modules":[{"name":"UIKit"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false}],"navigatorTitle":[{"text":"Event","kind":"identifier"}]},"sections":[],"topicSections":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEndOnExit","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allTouchEvents","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allEditingEvents","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/applicationReserved","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/systemReserved","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allEvents"]},{"title":"Initializers","anchor":"Initializers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/Event/init(rawValue:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP","doc://com.externally.resolved.symbol/s:s9OptionSetP","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP","doc://com.externally.resolved.symbol/s:s10SetAlgebraP"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/responding-to-control-based-events-using-target-action":{"identifier":"doc://com.apple.uikit/documentation/UIKit/responding-to-control-based-events-using-target-action","url":"/documentation/uikit/responding-to-control-based-events-using-target-action","abstract":[{"type":"text","text":"Handle user input by connecting buttons, sliders, and other controls to your app’s code using the target-action design pattern."}],"title":"Responding to control-based events using target-action","type":"topic","role":"article","kind":"article"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered":{"url":"/documentation/uikit/uicontrol/event/menuactiontriggered","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"menuActionTriggered","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventMenuActionTriggered","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered","kind":"symbol","abstract":[{"text":"A menu action has triggered prior to the menu being presented.","type":"text"}],"role":"symbol","type":"topic","title":"menuActionTriggered"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allEditingEvents":{"type":"topic","abstract":[{"text":"All editing touches for text fields.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allEditingEvents","kind":"symbol","role":"symbol","url":"/documentation/uikit/uicontrol/event/alleditingevents","title":"allEditingEvents","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allEditingEvents","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventAllEditingEvents","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allEvents":{"role":"symbol","url":"/documentation/uikit/uicontrol/event/allevents","title":"allEvents","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allEvents","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier","text":"UIControl"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier","text":"Event"}],"navigatorTitle":[{"kind":"identifier","text":"UIControlEventAllEvents"}],"type":"topic","abstract":[{"text":"All events, including system events.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allEvents"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin":{"url":"/documentation/uikit/uicontrol/event/editingdidbegin","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editingDidBegin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventEditingDidBegin","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin","kind":"symbol","abstract":[{"type":"text","text":"A touch initiating an editing session in a text field by entering its bounds."}],"role":"symbol","type":"topic","title":"editingDidBegin"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside","title":"touchUpOutside","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchUpOutside","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"url":"/documentation/uikit/uicontrol/event/touchupoutside","abstract":[{"text":"A touch-up event in the control where the finger is outside the bounds of the control.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"UIControlEventTouchUpOutside","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","role":"symbol","url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered":{"url":"/documentation/uikit/uicontrol/event/primaryactiontriggered","abstract":[{"type":"text","text":"A semantic action triggered by buttons."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered","navigatorTitle":[{"text":"UIControlEventPrimaryActionTriggered","kind":"identifier"}],"title":"primaryActionTriggered","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryActionTriggered"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"c:@E@UIControlEvents"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged":{"kind":"symbol","title":"valueChanged","navigatorTitle":[{"text":"UIControlEventValueChanged","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valueChanged","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlEvents","text":"Event","kind":"typeIdentifier"}],"abstract":[{"text":"A touch dragging or otherwise manipulating a control, causing it to emit a series of different values.","type":"text"}],"url":"/documentation/uikit/uicontrol/event/valuechanged","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEndOnExit":{"type":"topic","title":"editingDidEndOnExit","abstract":[{"text":"A touch ending an editing session in a text field.","type":"text"}],"url":"/documentation/uikit/uicontrol/event/editingdidendonexit","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editingDidEndOnExit","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents","text":"Event"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEndOnExit","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIControlEventEditingDidEndOnExit"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside":{"role":"symbol","title":"touchUpInside","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside","type":"topic","url":"/documentation/uikit/uicontrol/event/touchupinside","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchUpInside","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"A touch-up event in the control where the finger is inside the bounds of the control.","type":"text"}],"navigatorTitle":[{"text":"UIControlEventTouchUpInside","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event":{"url":"/documentation/uikit/uicontrol/event","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Event","kind":"identifier"}],"navigatorTitle":[{"text":"Event","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event","kind":"symbol","abstract":[{"type":"text","text":"Constants describing the types of events possible for controls."}],"role":"symbol","type":"topic","title":"UIControl.Event"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"text":"Describes an unsigned integer.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","role":"symbol","url":"/documentation/objectivec/nsuinteger","kind":"symbol","type":"topic","title":"NSUInteger"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside":{"role":"symbol","title":"touchDragInside","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside","type":"topic","url":"/documentation/uikit/uicontrol/event/touchdraginside","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"touchDragInside","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"Event","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents"}],"kind":"symbol","abstract":[{"text":"An event where a finger is dragged inside the bounds of the control.","type":"text"}],"navigatorTitle":[{"text":"UIControlEventTouchDragInside","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter":{"type":"topic","title":"touchDragEnter","kind":"symbol","navigatorTitle":[{"text":"UIControlEventTouchDragEnter","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchDragEnter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"abstract":[{"text":"An event where a finger is dragged into the bounds of the control.","type":"text"}],"url":"/documentation/uikit/uicontrol/event/touchdragenter"},"doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP":{"kind":"symbol","abstract":[{"text":"A type that can be initialized using an array literal.","type":"text"}],"url":"/documentation/Swift/ExpressibleByArrayLiteral","identifier":"doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP","title":"ExpressibleByArrayLiteral","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressibleByArrayLiteral"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel":{"role":"symbol","title":"touchCancel","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel","type":"topic","url":"/documentation/uikit/uicontrol/event/touchcancel","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchCancel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"A system event canceling the current touches for the control.","type":"text"}],"navigatorTitle":[{"text":"UIControlEventTouchCancel","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SY":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY"},"doc://com.apple.uikit/documentation/UIKit/UIControl":{"navigatorTitle":[{"text":"UIControl","kind":"identifier"}],"title":"UIControl","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControl","kind":"identifier"}],"abstract":[{"type":"text","text":"The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions."}],"url":"/documentation/uikit/uicontrol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside":{"type":"topic","title":"touchDragOutside","kind":"symbol","navigatorTitle":[{"text":"UIControlEventTouchDragOutside","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchDragOutside","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"Event","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents"}],"abstract":[{"type":"text","text":"An event where a finger is dragged just outside the bounds of the control."}],"url":"/documentation/uikit/uicontrol/event/touchdragoutside"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged":{"url":"/documentation/uikit/uicontrol/event/editingchanged","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editingChanged","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlEvents","text":"Event","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventEditingChanged","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged","kind":"symbol","abstract":[{"type":"text","text":"A touch making an editing change in a text field."}],"role":"symbol","type":"topic","title":"editingChanged"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat":{"url":"/documentation/uikit/uicontrol/event/touchdownrepeat","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchDownRepeat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventTouchDownRepeat","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat","kind":"symbol","abstract":[{"text":"A repeated touch-down event in the control; for this event the value of the UITouch ","type":"text"},{"type":"codeVoice","code":"tapCount"},{"text":" method is greater than one.","type":"text"}],"role":"symbol","type":"topic","title":"touchDownRepeat"},"doc://com.apple.uikit/documentation/UIKit/UIControl/addTarget(_:action:for:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/addTarget(_:action:for:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addTarget:action:forControlEvents:"}],"url":"/documentation/uikit/uicontrol/addtarget(_:action:for:)","title":"addTarget(_:action:for:)","abstract":[{"text":"Associates a target object and action method with the control.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTarget"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents","text":"Event"},{"kind":"text","text":")"}]},"doc://com.externally.resolved.symbol/s:s9OptionSetP":{"role":"symbol","url":"/documentation/Swift/OptionSet","abstract":[{"text":"A type that presents a mathematical set interface to a bit set.","type":"text"}],"type":"topic","title":"OptionSet","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionSet","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SY","text":"RawRepresentable","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s10SetAlgebraP","text":"SetAlgebra","kind":"typeIdentifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s9OptionSetP","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/init(rawValue:)","abstract":[{"type":"text","text":"Creates a control event with the specified raw value."}],"type":"topic","url":"/documentation/uikit/uicontrol/event/init(rawvalue:)","kind":"symbol","role":"symbol","title":"init(rawValue:)"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/applicationReserved":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationReserved"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier","text":"UIControl"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier","text":"Event"}],"url":"/documentation/uikit/uicontrol/event/applicationreserved","navigatorTitle":[{"kind":"identifier","text":"UIControlEventApplicationReserved"}],"abstract":[{"type":"text","text":"A range of control-event values available for app use."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/applicationReserved","role":"symbol","title":"applicationReserved","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allTouchEvents":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allTouchEvents","role":"symbol","kind":"symbol","url":"/documentation/uikit/uicontrol/event/alltouchevents","title":"allTouchEvents","type":"topic","abstract":[{"type":"text","text":"All touch events."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allTouchEvents","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlEvents","text":"Event","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventAllTouchEvents","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown":{"url":"/documentation/uikit/uicontrol/event/touchdown","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchDown","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventTouchDown","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown","kind":"symbol","abstract":[{"type":"text","text":"A touch-down event in the control."}],"role":"symbol","type":"topic","title":"touchDown"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/systemReserved":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/systemReserved","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemReserved"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"text":"Event","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents"}],"title":"systemReserved","abstract":[{"type":"text","text":"A range of control-event values reserved for internal framework use."}],"navigatorTitle":[{"text":"UIControlEventSystemReserved","kind":"identifier"}],"url":"/documentation/uikit/uicontrol/event/systemreserved"},"doc://com.externally.resolved.symbol/s:s10SetAlgebraP":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SetAlgebra"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Element","preciseIdentifier":"s:s10SetAlgebraP7ElementQa"},{"kind":"text","text":"> : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s25ExpressibleByArrayLiteralP","text":"ExpressibleByArrayLiteral"}],"identifier":"doc://com.externally.resolved.symbol/s:s10SetAlgebraP","role":"symbol","title":"SetAlgebra","url":"/documentation/Swift/SetAlgebra","abstract":[{"type":"text","text":"A type that provides mathematical set operations."}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit":{"url":"/documentation/uikit/uicontrol/event/touchdragexit","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchDragExit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventTouchDragExit","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit","kind":"symbol","abstract":[{"type":"text","text":"An event where a finger is dragged from within a control to outside its bounds."}],"role":"symbol","type":"topic","title":"touchDragExit"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd":{"url":"/documentation/uikit/uicontrol/event/editingdidend","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editingDidEnd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventEditingDidEnd","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd","kind":"symbol","abstract":[{"text":"A touch ending an editing session in a text field by leaving its bounds.","type":"text"}],"role":"symbol","type":"topic","title":"editingDidEnd"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration","path":"/metadata/roleHeading","op":"replace"},{"value":"UIControlEvents","path":"/metadata/title","op":"replace"},{"value":"enum","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"UIControlEvents"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"UIControlEvents","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy","op":"replace"},{"value":[{"title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEndOnExit","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allTouchEvents","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allEditingEvents","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/applicationReserved","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/systemReserved","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allEvents"],"anchor":"Constants"}],"path":"/topicSections","op":"replace"},{"value":null,"path":"/relationshipsSections","op":"replace"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControlEvents","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1menuActionTriggered/title","value":"UIControlEventMenuActionTriggered","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1menuActionTriggered/fragments","value":[{"text":"UIControlEventMenuActionTriggered","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1allEditingEvents/title","value":"UIControlEventAllEditingEvents","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1allEditingEvents/fragments","value":[{"text":"UIControlEventAllEditingEvents","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"UIControlEventAllEvents","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1allEvents/title"},{"op":"replace","value":[{"text":"UIControlEventAllEvents","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1allEvents/fragments"},{"op":"replace","value":"UIControlEventEditingDidBegin","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidBegin/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlEventEditingDidBegin"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidBegin/fragments"},{"op":"replace","value":"UIControlEventTouchUpOutside","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpOutside/title"},{"op":"replace","value":[{"text":"UIControlEventTouchUpOutside","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpOutside/fragments"},{"op":"replace","value":"UIControlEventPrimaryActionTriggered","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1primaryActionTriggered/title"},{"op":"replace","value":[{"text":"UIControlEventPrimaryActionTriggered","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1primaryActionTriggered/fragments"},{"op":"replace","value":"UIControlEventValueChanged","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1valueChanged/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlEventValueChanged"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1valueChanged/fragments"},{"op":"replace","value":"UIControlEventEditingDidEndOnExit","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidEndOnExit/title"},{"op":"replace","value":[{"text":"UIControlEventEditingDidEndOnExit","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidEndOnExit/fragments"},{"op":"replace","value":"UIControlEventTouchUpInside","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpInside/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlEventTouchUpInside"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpInside/fragments"},{"op":"replace","value":"UIControlEvents","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlEvents"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/fragments"},{"op":"replace","value":[{"text":"UIControlEvents","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/navigatorTitle"},{"op":"replace","value":"UIControlEventTouchDragInside","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragInside/title"},{"op":"replace","value":[{"text":"UIControlEventTouchDragInside","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragInside/fragments"},{"op":"replace","value":"UIControlEventTouchDragEnter","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragEnter/title"},{"op":"replace","value":[{"text":"UIControlEventTouchDragEnter","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragEnter/fragments"},{"op":"replace","value":"UIControlEventTouchCancel","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchCancel/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlEventTouchCancel"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchCancel/fragments"},{"op":"replace","value":"UIControl","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControl"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIControl"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle"},{"op":"replace","value":"UIControlEventTouchDragOutside","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragOutside/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlEventTouchDragOutside"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragOutside/fragments"},{"op":"replace","value":"UIControlEventEditingChanged","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingChanged/title"},{"op":"replace","value":[{"text":"UIControlEventEditingChanged","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingChanged/fragments"},{"op":"replace","value":"UIControlEventTouchDownRepeat","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDownRepeat/title"},{"op":"replace","value":[{"text":"UIControlEventTouchDownRepeat","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDownRepeat/fragments"},{"op":"replace","value":"addTarget:action:forControlEvents:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1addTarget(_:action:for:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addTarget:action:forControlEvents:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1addTarget(_:action:for:)/fragments"},{"op":"replace","value":"UIControlEventApplicationReserved","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1applicationReserved/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlEventApplicationReserved"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1applicationReserved/fragments"},{"op":"replace","value":"UIControlEventAllTouchEvents","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1allTouchEvents/title"},{"op":"replace","value":[{"text":"UIControlEventAllTouchEvents","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1allTouchEvents/fragments"},{"op":"replace","value":"UIControlEventTouchDown","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDown/title"},{"op":"replace","value":[{"text":"UIControlEventTouchDown","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDown/fragments"},{"op":"replace","value":"UIControlEventSystemReserved","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1systemReserved/title"},{"op":"replace","value":[{"text":"UIControlEventSystemReserved","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1systemReserved/fragments"},{"op":"replace","value":"UIControlEventTouchDragExit","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragExit/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlEventTouchDragExit"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragExit/fragments"},{"op":"replace","value":"UIControlEventEditingDidEnd","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidEnd/title"},{"op":"replace","value":[{"text":"UIControlEventEditingDidEnd","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidEnd/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}