{"variants":[{"paths":["/documentation/uikit/uicontrol/isenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uicontrol/isenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIControl/isEnabled"},"sections":[],"seeAlsoSections":[{"title":"Managing state","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/state-swift.property","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIControl/isSelected","doc://com.apple.uikit/documentation/UIKit/UIControl/isHighlighted"],"anchor":"Managing-state","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Set the value of this property to "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":" to enable the control or "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":" to disable it. An enabled control is capable of responding to user interactions, whereas a disabled control ignores touch events and may draw itself differently. Setting this property to "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":" adds the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled"},{"type":"text","text":" flag to the control’s "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/state-swift.property"},{"type":"text","text":" bitmask; enabling the control again removes that flag."}]},{"type":"paragraph","inlineContent":[{"text":"The default value of this property is ","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"text":" for a newly created control. You can set a control’s initial enabled state in your storyboard file.","type":"text"}]}],"kind":"content"}],"kind":"symbol","abstract":[{"text":"A Boolean value indicating whether the control is in the enabled state.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"enabled"}],"title":"isEnabled","platforms":[{"name":"iOS","beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false},{"deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false,"name":"visionOS"}],"modules":[{"name":"UIKit"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)UIControl(py)enabled","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"references":{"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"State"}],"title":"UIControl.State","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/state-swift.struct","abstract":[{"type":"text","text":"Constants describing the state of a control."}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled":{"abstract":[{"text":"The disabled state of a control.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled","kind":"symbol","url":"/documentation/uikit/uicontrol/state-swift.struct/disabled","title":"disabled","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState"}],"type":"topic","navigatorTitle":[{"text":"UIControlStateDisabled","kind":"identifier"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/isHighlighted":{"navigatorTitle":[{"kind":"identifier","text":"highlighted"}],"title":"isHighlighted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHighlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/isHighlighted","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/ishighlighted","abstract":[{"type":"text","text":"A Boolean value indicating whether the control draws a highlight."}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/isSelected":{"navigatorTitle":[{"kind":"identifier","text":"selected"}],"title":"isSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/isSelected","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/isselected","abstract":[{"type":"text","text":"A Boolean value indicating whether the control is in the selected state."}]},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.uikit/documentation/UIKit/UIControl/isEnabled":{"navigatorTitle":[{"kind":"identifier","text":"enabled"}],"title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/isEnabled","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/isenabled","abstract":[{"type":"text","text":"A Boolean value indicating whether the control is in the enabled state."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl":{"navigatorTitle":[{"text":"UIControl","kind":"identifier"}],"title":"UIControl","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControl","kind":"identifier"}],"abstract":[{"type":"text","text":"The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions."}],"url":"/documentation/uikit/uicontrol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/state-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"state"}],"title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/state-swift.property","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/state-swift.property","abstract":[{"type":"text","text":"The state of the control, specified as a bit mask value."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"iOS","introducedAt":"2.0","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","introducedAt":"2.0","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"enabled","path":"/metadata/title","op":"replace"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"enabled","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl"]]}},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/state-swift.property","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIControl/isSelected","doc://com.apple.uikit/documentation/UIKit/UIControl/isHighlighted"],"title":"Managing state","anchor":"Managing-state"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"text":"isEnabled","kind":"identifier"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":"UIControlState","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlState"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/fragments"},{"op":"replace","value":[{"text":"UIControlState","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/navigatorTitle"},{"op":"replace","value":"UIControlStateDisabled","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1disabled/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlStateDisabled"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1disabled/fragments"},{"op":"replace","value":"highlighted","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isHighlighted/title"},{"op":"replace","value":[{"text":"highlighted","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isHighlighted/fragments"},{"op":"replace","value":"selected","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isSelected/title"},{"op":"replace","value":[{"text":"selected","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isSelected/fragments"},{"op":"replace","value":"enabled","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isEnabled/title"},{"op":"replace","value":[{"text":"enabled","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isEnabled/fragments"},{"op":"replace","value":"UIControl","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIControl"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments"},{"op":"replace","value":[{"text":"UIControl","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle"},{"op":"replace","value":"state","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1state-swift.property/title"},{"op":"replace","value":[{"text":"state","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1state-swift.property/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}