{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/addTarget(_:action:for:)","doc://com.apple.uikit/documentation/UIKit/UIControl/removeTarget(_:action:for:)","doc://com.apple.uikit/documentation/UIKit/UIControl/allTargets","doc://com.apple.uikit/documentation/UIKit/UIControl/addAction(_:for:)","doc://com.apple.uikit/documentation/UIKit/UIControl/removeAction(_:for:)","doc://com.apple.uikit/documentation/UIKit/UIControl/actions(forTarget:forControlEvent:)","doc://com.apple.uikit/documentation/UIKit/UIControl/allControlEvents","doc://com.apple.uikit/documentation/UIKit/UIControl/enumerateEventHandlers(_:)"],"title":"Managing the control’s targets and actions","anchor":"Managing-the-controls-targets-and-actions","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifiedBy","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"actionIdentifier","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIAction","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAction","preciseIdentifier":"c:objc(cs)UIAction"},{"text":".","kind":"text"},{"text":"Identifier","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAction/Identifier-swift.struct","preciseIdentifier":"c:@T@UIActionIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controlEvents","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"Event","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event","preciseIdentifier":"c:@E@UIControlEvents"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}],"kind":"symbol","metadata":{"externalID":"c:objc(cs)UIControl(im)removeActionForIdentifier:forControlEvents:","roleHeading":"Instance Method","platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"tvOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false}],"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifiedBy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIAction","text":"UIAction","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIActionIdentifier","text":"Identifier","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlEvents","text":"Event","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"removeAction(identifiedBy:for:)","navigatorTitle":[{"text":"removeActionForIdentifier:forControlEvents:","kind":"identifier"}],"modules":[{"name":"UIKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIControl/removeAction(identifiedBy:for:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicontrol/removeaction(identifiedby:for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicontrol/removeaction(identifiedby:for:)"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIControl/actions(forTarget:forControlEvent:)":{"abstract":[{"type":"text","text":"Returns the actions performed on a target object when the specified event occurs."}],"navigatorTitle":[{"text":"actionsForTarget:forControlEvent:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/actions(forTarget:forControlEvent:)","type":"topic","title":"actions(forTarget:forControlEvent:)","url":"/documentation/uikit/uicontrol/actions(fortarget:forcontrolevent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"actions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTarget"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"forControlEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/allControlEvents":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allControlEvents"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/allControlEvents","title":"allControlEvents","url":"/documentation/uikit/uicontrol/allcontrolevents","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allControlEvents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents","text":"Event"}],"abstract":[{"type":"text","text":"Returns the events for which the control has associated actions."}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/removeAction(identifiedBy:for:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/removeAction(identifiedBy:for:)","navigatorTitle":[{"kind":"identifier","text":"removeActionForIdentifier:forControlEvents:"}],"role":"symbol","url":"/documentation/uikit/uicontrol/removeaction(identifiedby:for:)","title":"removeAction(identifiedBy:for:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiedBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIAction","preciseIdentifier":"c:objc(cs)UIAction"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Identifier","preciseIdentifier":"c:@T@UIActionIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"c:@E@UIControlEvents"},{"kind":"text","text":")"}],"type":"topic","abstract":[]},"doc://com.apple.uikit/documentation/UIKit/UIControl":{"navigatorTitle":[{"text":"UIControl","kind":"identifier"}],"title":"UIControl","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControl","kind":"identifier"}],"abstract":[{"type":"text","text":"The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions."}],"url":"/documentation/uikit/uicontrol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event":{"url":"/documentation/uikit/uicontrol/event","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Event","kind":"identifier"}],"navigatorTitle":[{"text":"Event","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event","kind":"symbol","abstract":[{"type":"text","text":"Constants describing the types of events possible for controls."}],"role":"symbol","type":"topic","title":"UIControl.Event"},"doc://com.apple.uikit/documentation/UIKit/UIAction/Identifier-swift.struct":{"role":"symbol","title":"UIAction.Identifier","navigatorTitle":[{"kind":"identifier","text":"Identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A type that represents an action identifier."}],"url":"/documentation/uikit/uiaction/identifier-swift.struct","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAction/Identifier-swift.struct"},"doc://com.apple.uikit/documentation/UIKit/UIControl/removeAction(_:for:)":{"abstract":[],"navigatorTitle":[{"text":"removeAction:forControlEvents:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/removeAction(_:for:)","type":"topic","title":"removeAction(_:for:)","url":"/documentation/uikit/uicontrol/removeaction(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIAction","text":"UIAction"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/addTarget(_:action:for:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/addTarget(_:action:for:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addTarget:action:forControlEvents:"}],"url":"/documentation/uikit/uicontrol/addtarget(_:action:for:)","title":"addTarget(_:action:for:)","abstract":[{"text":"Associates a target object and action method with the control.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTarget"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents","text":"Event"},{"kind":"text","text":")"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/enumerateEventHandlers:":{"navigatorTitle":[{"kind":"identifier","text":"enumerateEventHandlers:"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/enumerateEventHandlers:","url":"/documentation/uikit/uicontrol/enumerateeventhandlers:","abstract":[],"title":"enumerateEventHandlers:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enumerateEventHandlers:"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/enumerateEventHandlers(_:)":{"role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/enumerateEventHandlers(_:)","title":"enumerateEventHandlers(_:)","url":"/documentation/uikit/uicontrol/enumerateeventhandlers(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enumerateEventHandlers"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIAction","text":"UIAction"},{"kind":"text","text":"?, ("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":")?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents","text":"Event"},{"kind":"text","text":", "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[]},"doc://com.apple.uikit/documentation/UIKit/UIControl/addAction(_:for:)":{"navigatorTitle":[{"kind":"identifier","text":"addAction:forControlEvents:"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/addAction(_:for:)","url":"/documentation/uikit/uicontrol/addaction(_:for:)","abstract":[],"title":"addAction(_:for:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAction"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIAction","kind":"typeIdentifier","text":"UIAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier","text":"UIControl"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier","text":"Event"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/removeTarget(_:action:for:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/removeTarget(_:action:for:)","navigatorTitle":[{"kind":"identifier","text":"removeTarget:action:forControlEvents:"}],"role":"symbol","url":"/documentation/uikit/uicontrol/removetarget(_:action:for:)","title":"removeTarget(_:action:for:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTarget"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents","text":"Event"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Stops the delivery of events to the specified target object."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/allTargets":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allTargets"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/allTargets","title":"allTargets","url":"/documentation/uikit/uicontrol/alltargets","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allTargets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Returns all target objects associated with the control."}]},"doc://com.apple.uikit/documentation/UIKit/UIAction":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIAction"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIAction"}],"title":"UIAction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAction","type":"topic","url":"/documentation/uikit/uiaction","abstract":[{"type":"text","text":"A menu element that performs its action in a closure."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"removeActionForIdentifier:forControlEvents:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"removeActionForIdentifier:forControlEvents:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Managing the control’s targets and actions","anchor":"Managing-the-controls-targets-and-actions","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/addTarget(_:action:for:)","doc://com.apple.uikit/documentation/UIKit/UIControl/removeTarget(_:action:for:)","doc://com.apple.uikit/documentation/UIKit/UIControl/allTargets","doc://com.apple.uikit/documentation/UIKit/UIControl/addAction(_:for:)","doc://com.apple.uikit/documentation/UIKit/UIControl/removeAction(_:for:)","doc://com.apple.uikit/documentation/UIKit/UIControl/actions(forTarget:forControlEvent:)","doc://com.apple.uikit/documentation/UIKit/UIControl/allControlEvents","doc://com.apple.uikit/documentation/UIKit/UIControl/enumerateEventHandlers:"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"removeActionForIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIActionIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIActionIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAction/Identifier-swift.struct"},{"text":") ","kind":"text"},{"text":"actionIdentifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forControlEvents:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIControlEvents","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event","preciseIdentifier":"c:@E@UIControlEvents"},{"text":") ","kind":"text"},{"text":"controlEvents","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1actions(forTarget:forControlEvent:)/title","op":"replace","value":"actionsForTarget:forControlEvent:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1actions(forTarget:forControlEvent:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"actionsForTarget:forControlEvent:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1allControlEvents/title","op":"replace","value":"allControlEvents"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1allControlEvents/fragments","op":"replace","value":[{"kind":"identifier","text":"allControlEvents"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1removeAction(identifiedBy:for:)/title","op":"replace","value":"removeActionForIdentifier:forControlEvents:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1removeAction(identifiedBy:for:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeActionForIdentifier:forControlEvents:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title","op":"replace","value":"UIControl"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments","op":"replace","value":[{"text":"UIControl","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIControl"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/title","op":"replace","value":"UIControlEvents"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/fragments","op":"replace","value":[{"text":"UIControlEvents","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/navigatorTitle","op":"replace","value":[{"text":"UIControlEvents","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction~1Identifier-swift.struct/title","op":"replace","value":"UIActionIdentifier"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction~1Identifier-swift.struct/fragments","op":"replace","value":[{"text":"UIActionIdentifier","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction~1Identifier-swift.struct/navigatorTitle","op":"replace","value":[{"text":"UIActionIdentifier","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1removeAction(_:for:)/title","op":"replace","value":"removeAction:forControlEvents:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1removeAction(_:for:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAction:forControlEvents:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1addTarget(_:action:for:)/title","op":"replace","value":"addTarget:action:forControlEvents:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1addTarget(_:action:for:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTarget:action:forControlEvents:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1addAction(_:for:)/title","op":"replace","value":"addAction:forControlEvents:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1addAction(_:for:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addAction:forControlEvents:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1removeTarget(_:action:for:)/title","op":"replace","value":"removeTarget:action:forControlEvents:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1removeTarget(_:action:for:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeTarget:action:forControlEvents:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1allTargets/title","op":"replace","value":"allTargets"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1allTargets/fragments","op":"replace","value":[{"kind":"identifier","text":"allTargets"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/title","op":"replace","value":"UIAction"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/fragments","op":"replace","value":[{"text":"UIAction","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/navigatorTitle","op":"replace","value":[{"text":"UIAction","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}