{"metadata":{"title":"UIControl.State","externalID":"c:@E@UIControlState","symbolKind":"struct","roleHeading":"Structure","modules":[{"name":"UIKit"}],"navigatorTitle":[{"text":"State","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"State","kind":"identifier"}],"role":"symbol","extendedModule":"UIKit","platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false}]},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP","doc://com.externally.resolved.symbol/s:s9OptionSetP","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP","doc://com.externally.resolved.symbol/s:s10SetAlgebraP"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicontrol/state-swift.struct"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicontrol/state-swift.struct"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved"],"anchor":"Constants"},{"title":"Initializers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/init(rawValue:)"],"anchor":"Initializers"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"A control can have more than one state at a time. Controls can have different configurations according to their state. For example, a "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton"},{"type":"text","text":" object can display one image when it’s in its normal state and a different image when it’s highlighted."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Constants describing the state of a control."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct"},"sections":[],"seeAlsoSections":[{"title":"Managing state","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/state-swift.property","doc://com.apple.uikit/documentation/UIKit/UIControl/isEnabled","doc://com.apple.uikit/documentation/UIKit/UIControl/isSelected","doc://com.apple.uikit/documentation/UIKit/UIControl/isHighlighted"],"generated":true,"anchor":"Managing-state"}],"references":{"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","role":"symbol","url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"State"}],"title":"UIControl.State","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/state-swift.struct","abstract":[{"type":"text","text":"Constants describing the state of a control."}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application":{"type":"topic","title":"application","abstract":[{"type":"text","text":"Additional control-state flags available for app use."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/application","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIControlStateApplication"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/init(rawValue:)":{"kind":"symbol","type":"topic","title":"init(rawValue:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/init(rawValue:)","abstract":[{"type":"text","text":"Creates a control state with the specified raw value."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved":{"type":"topic","title":"reserved","abstract":[{"type":"text","text":"Control-state flags reserved for internal framework use."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/reserved","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reserved"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIControlStateReserved"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected":{"type":"topic","url":"/documentation/uikit/uicontrol/state-swift.struct/selected","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected","kind":"symbol","navigatorTitle":[{"text":"UIControlStateSelected","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"}],"title":"selected","abstract":[{"type":"text","text":"The selected state of a control."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted":{"type":"topic","title":"highlighted","abstract":[{"type":"text","text":"The highlighted state of a control."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/highlighted","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIControlStateHighlighted"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted"},"doc://com.apple.uikit/documentation/UIKit/UIControl/isSelected":{"navigatorTitle":[{"kind":"identifier","text":"selected"}],"title":"isSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/isSelected","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/isselected","abstract":[{"type":"text","text":"A Boolean value indicating whether the control is in the selected state."}]},"doc://com.apple.uikit/documentation/UIKit/UIControl":{"navigatorTitle":[{"text":"UIControl","kind":"identifier"}],"title":"UIControl","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControl","kind":"identifier"}],"abstract":[{"type":"text","text":"The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions."}],"url":"/documentation/uikit/uicontrol","type":"topic"},"doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP":{"kind":"symbol","abstract":[{"text":"A type that can be initialized using an array literal.","type":"text"}],"url":"/documentation/Swift/ExpressibleByArrayLiteral","identifier":"doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP","title":"ExpressibleByArrayLiteral","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressibleByArrayLiteral"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled":{"abstract":[{"text":"The disabled state of a control.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled","kind":"symbol","url":"/documentation/uikit/uicontrol/state-swift.struct/disabled","title":"disabled","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState"}],"type":"topic","navigatorTitle":[{"text":"UIControlStateDisabled","kind":"identifier"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIButton":{"role":"symbol","abstract":[{"type":"text","text":"A control that executes your custom code in response to user interactions."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIButton"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton","title":"UIButton","navigatorTitle":[{"kind":"identifier","text":"UIButton"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uibutton"},"doc://com.apple.uikit/documentation/UIKit/UIControl/isEnabled":{"navigatorTitle":[{"kind":"identifier","text":"enabled"}],"title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/isEnabled","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/isenabled","abstract":[{"type":"text","text":"A Boolean value indicating whether the control is in the enabled state."}]},"doc://com.externally.resolved.symbol/s:s9OptionSetP":{"role":"symbol","url":"/documentation/Swift/OptionSet","abstract":[{"text":"A type that presents a mathematical set interface to a bit set.","type":"text"}],"type":"topic","title":"OptionSet","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionSet","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SY","text":"RawRepresentable","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s10SetAlgebraP","text":"SetAlgebra","kind":"typeIdentifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s9OptionSetP","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/isHighlighted":{"navigatorTitle":[{"kind":"identifier","text":"highlighted"}],"title":"isHighlighted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHighlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/isHighlighted","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/ishighlighted","abstract":[{"type":"text","text":"A Boolean value indicating whether the control draws a highlight."}]},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"text":"Describes an unsigned integer.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","role":"symbol","url":"/documentation/objectivec/nsuinteger","kind":"symbol","type":"topic","title":"NSUInteger"},"doc://com.externally.resolved.symbol/s:SY":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused":{"type":"topic","title":"focused","abstract":[{"type":"text","text":"The focused state of a control."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/focused","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"UIControlStateFocused","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused"},"doc://com.apple.uikit/documentation/UIKit/UIControl/state-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"state"}],"title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/state-swift.property","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/state-swift.property","abstract":[{"type":"text","text":"The state of the control, specified as a bit mask value."}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal":{"title":"normal","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState","text":"State"}],"navigatorTitle":[{"kind":"identifier","text":"UIControlStateNormal"}],"url":"/documentation/uikit/uicontrol/state-swift.struct/normal","abstract":[{"type":"text","text":"The normal, or default, state of a control where the control is enabled but neither selected nor highlighted."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s10SetAlgebraP":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SetAlgebra"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Element","preciseIdentifier":"s:s10SetAlgebraP7ElementQa"},{"kind":"text","text":"> : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s25ExpressibleByArrayLiteralP","text":"ExpressibleByArrayLiteral"}],"identifier":"doc://com.externally.resolved.symbol/s:s10SetAlgebraP","role":"symbol","title":"SetAlgebra","url":"/documentation/Swift/SetAlgebra","abstract":[{"type":"text","text":"A type that provides mathematical set operations."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration","path":"/metadata/roleHeading","op":"replace"},{"value":"UIControlState","path":"/metadata/title","op":"replace"},{"value":"enum","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"UIControlState"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UIControlState"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy","op":"replace"},{"value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved"],"title":"Constants","anchor":"Constants"}],"path":"/topicSections","op":"replace"},{"value":null,"path":"/relationshipsSections","op":"replace"},{"value":[{"title":"Managing state","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/state-swift.property","doc://com.apple.uikit/documentation/UIKit/UIControl/isEnabled","doc://com.apple.uikit/documentation/UIKit/UIControl/isSelected","doc://com.apple.uikit/documentation/UIKit/UIControl/isHighlighted"],"anchor":"Managing-state","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControlState","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/title","op":"replace","value":"UIControlState"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/fragments","op":"replace","value":[{"kind":"identifier","text":"UIControlState"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIControlState"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1application/title","op":"replace","value":"UIControlStateApplication"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1application/fragments","op":"replace","value":[{"text":"UIControlStateApplication","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1reserved/title","op":"replace","value":"UIControlStateReserved"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1reserved/fragments","op":"replace","value":[{"text":"UIControlStateReserved","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1selected/title","op":"replace","value":"UIControlStateSelected"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1selected/fragments","op":"replace","value":[{"text":"UIControlStateSelected","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1highlighted/title","op":"replace","value":"UIControlStateHighlighted"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1highlighted/fragments","op":"replace","value":[{"kind":"identifier","text":"UIControlStateHighlighted"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isSelected/title","op":"replace","value":"selected"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isSelected/fragments","op":"replace","value":[{"kind":"identifier","text":"selected"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title","op":"replace","value":"UIControl"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments","op":"replace","value":[{"text":"UIControl","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIControl"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1disabled/title","op":"replace","value":"UIControlStateDisabled"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1disabled/fragments","op":"replace","value":[{"text":"UIControlStateDisabled","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title","op":"replace","value":"UIButton"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments","op":"replace","value":[{"kind":"identifier","text":"UIButton"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle","op":"replace","value":[{"text":"UIButton","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isEnabled/title","op":"replace","value":"enabled"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isEnabled/fragments","op":"replace","value":[{"text":"enabled","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isHighlighted/title","op":"replace","value":"highlighted"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isHighlighted/fragments","op":"replace","value":[{"kind":"identifier","text":"highlighted"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1focused/title","op":"replace","value":"UIControlStateFocused"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1focused/fragments","op":"replace","value":[{"text":"UIControlStateFocused","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1state-swift.property/title","op":"replace","value":"state"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1state-swift.property/fragments","op":"replace","value":[{"text":"state","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1normal/title","op":"replace","value":"UIControlStateNormal"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1normal/fragments","op":"replace","value":[{"text":"UIControlStateNormal","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}