{
  "abstract": [
    {
      "text": "The action that an operation performs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFileProviderTestingOperationType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFileProviderTestingOperationType"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderTestingOperationType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSFileProviderTestingOperationType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.fileprovider.testing-mode": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can place domains in testing mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.fileprovider.testing-mode",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.fileprovider.testing-mode",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.fileprovider.testing-mode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingChildrenEnumeration": {
      "abstract": [
        {
          "text": "An operation that lists a directory’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingChildrenEnumeration"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingChildrenEnumeration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingChildrenEnumeration"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingChildrenEnumeration",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingchildrenenumeration"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCollisionResolution": {
      "abstract": [
        {
          "text": "An operation that resolves a collision by renaming the new item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingCollisionResolution"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCollisionResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingCollisionResolution"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingCollisionResolution",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingcollisionresolution"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingContentFetch": {
      "abstract": [
        {
          "text": "An operation that fetches an item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingContentFetch"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingContentFetch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingContentFetch"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingContentFetch",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingcontentfetch"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCreation": {
      "abstract": [
        {
          "text": "An operation that syncs the creation of the source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingCreation"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCreation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingCreation"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingCreation",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingcreation"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion": {
      "abstract": [
        {
          "text": "An operation that syncs the deletion of the source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingDeletion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingDeletion"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingDeletion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingdeletion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingIngestion": {
      "abstract": [
        {
          "text": "An operation that alerts the system to either local or remote storage changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingIngestion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingIngestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingIngestion"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingIngestion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingingestion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingLookup": {
      "abstract": [
        {
          "text": "An operation that looks up an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingLookup"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingLookup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingLookup"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingLookup",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestinglookup"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingModification": {
      "abstract": [
        {
          "text": "An operation that syncs the modification of the source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingModification"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingModification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingModification"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingModification",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingmodification"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation": {
      "abstract": [
        {
          "text": "An operation that the system can schedule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperation"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperation"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperation",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationSide": {
      "abstract": [
        {
          "text": "The location where the operation takes place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationSide"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationSide"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationSide",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationside"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType": {
      "abstract": [
        {
          "text": "The action that an operation performs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationType"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationType"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/childrenEnumeration": {
      "abstract": [
        {
          "text": "Lists an item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "childrenEnumeration"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/childrenEnumeration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeChildrenEnumeration"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.childrenEnumeration",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/childrenenumeration"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/collisionResolution": {
      "abstract": [
        {
          "text": "Resolves a collision by renaming the new item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionResolution"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/collisionResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeCollisionResolution"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.collisionResolution",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/collisionresolution"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/contentFetch": {
      "abstract": [
        {
          "text": "Fetches an item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentFetch"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/contentFetch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeContentFetch"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.contentFetch",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/contentfetch"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/creation": {
      "abstract": [
        {
          "text": "Propagates the creation of a source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creation"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/creation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeCreation"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.creation",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/creation"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/deletion": {
      "abstract": [
        {
          "text": "Propagates the deletion of the source item from the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/deletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeDeletion"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.deletion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/deletion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/ingestion": {
      "abstract": [
        {
          "text": "Alerts the system to changes to either the local or remote storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ingestion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/ingestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeIngestion"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.ingestion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/ingestion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/init(rawvalue:)"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/lookup": {
      "abstract": [
        {
          "text": "Looks up an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookup"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/lookup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeLookup"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.lookup",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/lookup"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/modification": {
      "abstract": [
        {
          "text": "Propagates a change from the source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modification"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/modification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationTypeModification"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType.modification",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype/modification"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderUserInteractionSuppressing": {
      "abstract": [
        {
          "text": "Support for suppressing user-interaction alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderUserInteractionSuppressing"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderUserInteractionSuppressing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderUserInteractionSuppressing"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderUserInteractionSuppressing",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideruserinteractionsuppressing"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Testing-protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingChildrenEnumeration",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCollisionResolution",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingContentFetch",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCreation",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingIngestion",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingLookup",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingModification",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderUserInteractionSuppressing",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationSide",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.fileprovider.testing-mode"
      ],
      "title": "Testing protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Types",
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/childrenEnumeration",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/collisionResolution",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/contentFetch",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/creation",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/deletion",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/ingestion",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/lookup",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/modification"
      ],
      "title": "Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFileProviderTestingOperationType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Types",
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/childrenEnumeration",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/collisionResolution",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/contentFetch",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/creation",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/deletion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/ingestion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/lookup",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType/modification"
              ],
              "title": "Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Testing-protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingChildrenEnumeration",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCollisionResolution",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingContentFetch",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCreation",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingIngestion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingLookup",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingModification",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderUserInteractionSuppressing",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationSide",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.fileprovider.testing-mode"
              ],
              "title": "Testing protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFileProviderTestingOperationType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingContentFetch/title",
          "value": "NSFileProviderTestingContentFetch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingContentFetch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingContentFetch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingContentFetch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingContentFetch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1deletion/title",
          "value": "NSFileProviderTestingOperationTypeDeletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1deletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeDeletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationSide/title",
          "value": "NSFileProviderTestingOperationSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationSide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCreation/title",
          "value": "NSFileProviderTestingCreation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCreation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingCreation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCreation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingCreation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingLookup/title",
          "value": "NSFileProviderTestingLookup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingLookup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingLookup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingLookup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingLookup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1collisionResolution/title",
          "value": "NSFileProviderTestingOperationTypeCollisionResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1collisionResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeCollisionResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/title",
          "value": "NSFileProviderTestingOperationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1modification/title",
          "value": "NSFileProviderTestingOperationTypeModification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1modification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeModification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingModification/title",
          "value": "NSFileProviderTestingModification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingModification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingModification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingModification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingModification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion/title",
          "value": "NSFileProviderTestingDeletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingDeletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingDeletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1childrenEnumeration/title",
          "value": "NSFileProviderTestingOperationTypeChildrenEnumeration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1childrenEnumeration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeChildrenEnumeration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1contentFetch/title",
          "value": "NSFileProviderTestingOperationTypeContentFetch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1contentFetch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeContentFetch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1creation/title",
          "value": "NSFileProviderTestingOperationTypeCreation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1creation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeCreation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1lookup/title",
          "value": "NSFileProviderTestingOperationTypeLookup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1lookup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeLookup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingIngestion/title",
          "value": "NSFileProviderTestingIngestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingIngestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingIngestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingIngestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingIngestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCollisionResolution/title",
          "value": "NSFileProviderTestingCollisionResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCollisionResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingCollisionResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCollisionResolution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingCollisionResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation/title",
          "value": "NSFileProviderTestingOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingChildrenEnumeration/title",
          "value": "NSFileProviderTestingChildrenEnumeration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingChildrenEnumeration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingChildrenEnumeration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingChildrenEnumeration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingChildrenEnumeration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1ingestion/title",
          "value": "NSFileProviderTestingOperationTypeIngestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType~1ingestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationTypeIngestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderUserInteractionSuppressing/title",
          "value": "NSFileProviderUserInteractionSuppressing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderUserInteractionSuppressing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderUserInteractionSuppressing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderUserInteractionSuppressing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderUserInteractionSuppressing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidertestingoperationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidertestingoperationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
