{
  "abstract": [
    {
      "text": "An operation that the system can schedule.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSFileProviderTestingOperation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFileProviderTestingOperation"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderTestingOperation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSFileProviderTestingOperation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperation"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.fileprovider.testing-mode": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can place domains in testing mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.fileprovider.testing-mode",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.fileprovider.testing-mode",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.fileprovider.testing-mode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingChildrenEnumeration": {
      "abstract": [
        {
          "text": "An operation that lists a directory’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingChildrenEnumeration"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingChildrenEnumeration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingChildrenEnumeration"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingChildrenEnumeration",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingchildrenenumeration"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCollisionResolution": {
      "abstract": [
        {
          "text": "An operation that resolves a collision by renaming the new item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingCollisionResolution"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCollisionResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingCollisionResolution"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingCollisionResolution",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingcollisionresolution"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingContentFetch": {
      "abstract": [
        {
          "text": "An operation that fetches an item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingContentFetch"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingContentFetch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingContentFetch"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingContentFetch",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingcontentfetch"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCreation": {
      "abstract": [
        {
          "text": "An operation that syncs the creation of the source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingCreation"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCreation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingCreation"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingCreation",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingcreation"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion": {
      "abstract": [
        {
          "text": "An operation that syncs the deletion of the source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingDeletion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingDeletion"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingDeletion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingdeletion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingIngestion": {
      "abstract": [
        {
          "text": "An operation that alerts the system to either local or remote storage changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingIngestion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingIngestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingIngestion"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingIngestion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingingestion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingLookup": {
      "abstract": [
        {
          "text": "An operation that looks up an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingLookup"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingLookup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingLookup"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingLookup",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestinglookup"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingModification": {
      "abstract": [
        {
          "text": "An operation that syncs the modification of the source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingModification"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingModification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingModification"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingModification",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingmodification"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation": {
      "abstract": [
        {
          "text": "An operation that the system can schedule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperation"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperation"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperation",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asChildrenEnumeration": {
      "abstract": [
        {
          "text": "Returns the operation if it enumerates contained items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asChildrenEnumeration"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asChildrenEnumeration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asChildrenEnumeration"
        }
      ],
      "role": "symbol",
      "title": "asChildrenEnumeration",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/aschildrenenumeration"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCollisionResolution": {
      "abstract": [
        {
          "text": "Returns the operation if it resolves a collision by renaming the new item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asCollisionResolution"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCollisionResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asCollisionResolution"
        }
      ],
      "role": "symbol",
      "title": "asCollisionResolution",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/ascollisionresolution"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asContentFetch": {
      "abstract": [
        {
          "text": "Returns the operation if it fetches an item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asContentFetch"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asContentFetch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asContentFetch"
        }
      ],
      "role": "symbol",
      "title": "asContentFetch",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/ascontentfetch"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCreation": {
      "abstract": [
        {
          "text": "Returns the operation if it propagates the creation of an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asCreation"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCreation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asCreation"
        }
      ],
      "role": "symbol",
      "title": "asCreation",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/ascreation"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asDeletion": {
      "abstract": [
        {
          "text": "Returns the operation if it propagates the deletion of an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asDeletion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asDeletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asDeletion"
        }
      ],
      "role": "symbol",
      "title": "asDeletion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/asdeletion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asIngestion": {
      "abstract": [
        {
          "text": "Returns the operation if it alerts the system to changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asIngestion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asIngestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asIngestion"
        }
      ],
      "role": "symbol",
      "title": "asIngestion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/asingestion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asLookup": {
      "abstract": [
        {
          "text": "Returns the operation if it looks up an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asLookup"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asLookup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asLookup"
        }
      ],
      "role": "symbol",
      "title": "asLookup",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/aslookup"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asModification": {
      "abstract": [
        {
          "text": "Returns the operation if it propagates a change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asModification"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asModification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asModification"
        }
      ],
      "role": "symbol",
      "title": "asModification",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/asmodification"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/type": {
      "abstract": [
        {
          "text": "The operation’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderTestingOperationType",
          "text": "NSFileProviderTestingOperationType"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/type"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationSide": {
      "abstract": [
        {
          "text": "The location where the operation takes place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationSide"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationSide"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationSide",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationside"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType": {
      "abstract": [
        {
          "text": "The action that an operation performs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationType"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationType"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderUserInteractionSuppressing": {
      "abstract": [
        {
          "text": "Support for suppressing user-interaction alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderUserInteractionSuppressing"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderUserInteractionSuppressing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderUserInteractionSuppressing"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderUserInteractionSuppressing",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideruserinteractionsuppressing"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingChildrenEnumeration",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCollisionResolution",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingContentFetch",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCreation",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingIngestion",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingLookup",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingModification"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Testing-protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingChildrenEnumeration",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCollisionResolution",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingContentFetch",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCreation",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingIngestion",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingLookup",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingModification",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderUserInteractionSuppressing",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationSide",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.fileprovider.testing-mode"
      ],
      "title": "Testing protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Access-the-Operation-Type",
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/type"
      ],
      "title": "Access the Operation Type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFileProviderTestingOperation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Access-the-Operation-Type",
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/type",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asChildrenEnumeration",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCollisionResolution",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asContentFetch",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCreation",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asDeletion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asIngestion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asLookup",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asModification"
              ],
              "title": "Access the Operation Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingChildrenEnumeration",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCollisionResolution",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingContentFetch",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCreation",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingIngestion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingLookup",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingModification"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Testing-protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingChildrenEnumeration",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCollisionResolution",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingContentFetch",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingCreation",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingIngestion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingLookup",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingModification",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderUserInteractionSuppressing",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationSide",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.fileprovider.testing-mode"
              ],
              "title": "Testing protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFileProviderTestingOperation"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingIngestion/title",
          "value": "NSFileProviderTestingIngestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingIngestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingIngestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingIngestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingIngestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingContentFetch/title",
          "value": "NSFileProviderTestingContentFetch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingContentFetch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingContentFetch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingContentFetch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingContentFetch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingModification/title",
          "value": "NSFileProviderTestingModification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingModification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingModification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingModification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingModification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/title",
          "value": "NSFileProviderTestingOperationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCreation/title",
          "value": "NSFileProviderTestingCreation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCreation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingCreation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCreation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingCreation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion/title",
          "value": "NSFileProviderTestingDeletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingDeletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingDeletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCollisionResolution/title",
          "value": "NSFileProviderTestingCollisionResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCollisionResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingCollisionResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingCollisionResolution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingCollisionResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation/title",
          "value": "NSFileProviderTestingOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderUserInteractionSuppressing/title",
          "value": "NSFileProviderUserInteractionSuppressing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderUserInteractionSuppressing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderUserInteractionSuppressing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderUserInteractionSuppressing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderUserInteractionSuppressing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationSide/title",
          "value": "NSFileProviderTestingOperationSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationSide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingLookup/title",
          "value": "NSFileProviderTestingLookup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingLookup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingLookup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingLookup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingLookup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingChildrenEnumeration/title",
          "value": "NSFileProviderTestingChildrenEnumeration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingChildrenEnumeration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingChildrenEnumeration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingChildrenEnumeration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingChildrenEnumeration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidertestingoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidertestingoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
