{
  "abstract": [
    {
      "text": "An identifier for custom actions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderExtensionActionIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSFileProviderExtensionActionIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFileProviderExtensionActionIdentifier"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderExtensionActionIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSFileProviderExtensionActionIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFileProviderExtensionActionIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderCustomAction": {
      "abstract": [
        {
          "text": "Support for custom actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderCustomAction"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderCustomAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderCustomAction"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderCustomAction",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidercustomaction"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderEnumerating": {
      "abstract": [
        {
          "text": "Support for enumerating the file provider’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderEnumerating"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderEnumerating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderEnumerating"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderEnumerating",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderenumerating"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderExtensionActionIdentifier": {
      "abstract": [
        {
          "text": "An identifier for custom actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderExtensionActionIdentifier"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderExtensionActionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderExtensionActionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderExtensionActionIdentifier",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderextensionactionidentifier"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderExtensionActionIdentifier/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new identifier from the provided string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderExtensionActionIdentifier/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderextensionactionidentifier/init(_:)"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderExtensionActionIdentifier/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new identifier from the provided value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderExtensionActionIdentifier/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderextensionactionidentifier/init(rawvalue:)"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderIncrementalContentFetching": {
      "abstract": [
        {
          "text": "Support for fetching changes to the item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderIncrementalContentFetching"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderIncrementalContentFetching",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderIncrementalContentFetching"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderIncrementalContentFetching",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderincrementalcontentfetching"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderPartialContentFetching": {
      "abstract": [
        {
          "text": "Support for fetching part of a file’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderPartialContentFetching"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderPartialContentFetching",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderPartialContentFetching"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderPartialContentFetching",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderpartialcontentfetching"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderPendingSetEnumerator": {
      "abstract": [
        {
          "text": "A protocol for enumerating pending items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderPendingSetEnumerator"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderPendingSetEnumerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderPendingSetEnumerator"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderPendingSetEnumerator",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderpendingsetenumerator"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension": {
      "abstract": [
        {
          "text": "A File Provider extension in which the system replicates the contents on disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderReplicatedExtension"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderReplicatedExtension"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderReplicatedExtension",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderreplicatedextension"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderServicing": {
      "abstract": [
        {
          "text": "Support for providing a custom service source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderServicing"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderServicing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderServicing"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderServicing",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderservicing"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderThumbnailing": {
      "abstract": [
        {
          "text": "Support for item thumbnails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderThumbnailing"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderThumbnailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderThumbnailing"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderThumbnailing",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderthumbnailing"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-Provider-protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderEnumerating",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderIncrementalContentFetching",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderPartialContentFetching",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderServicing",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderCustomAction",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderThumbnailing",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderPendingSetEnumerator"
      ],
      "title": "File Provider protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Identifiers",
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderExtensionActionIdentifier/init(_:)",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderExtensionActionIdentifier/init(rawValue:)"
      ],
      "title": "Creating Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFileProviderExtensionActionIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderExtensionActionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderExtensionActionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-Provider-protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderEnumerating",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderIncrementalContentFetching",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderPartialContentFetching",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderServicing",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderCustomAction",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderThumbnailing",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderPendingSetEnumerator"
              ],
              "title": "File Provider protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFileProviderExtensionActionIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderIncrementalContentFetching/title",
          "value": "NSFileProviderIncrementalContentFetching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderIncrementalContentFetching/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderIncrementalContentFetching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderIncrementalContentFetching/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderIncrementalContentFetching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderThumbnailing/title",
          "value": "NSFileProviderThumbnailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderThumbnailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderThumbnailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderThumbnailing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderThumbnailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderEnumerating/title",
          "value": "NSFileProviderEnumerating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderEnumerating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderEnumerating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderEnumerating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderEnumerating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderPartialContentFetching/title",
          "value": "NSFileProviderPartialContentFetching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderPartialContentFetching/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderPartialContentFetching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderPartialContentFetching/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderPartialContentFetching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderPendingSetEnumerator/title",
          "value": "NSFileProviderPendingSetEnumerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderPendingSetEnumerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderPendingSetEnumerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderPendingSetEnumerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderPendingSetEnumerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderExtensionActionIdentifier/title",
          "value": "NSFileProviderExtensionActionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderExtensionActionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderExtensionActionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderExtensionActionIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderExtensionActionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension/title",
          "value": "NSFileProviderReplicatedExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderReplicatedExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderReplicatedExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderServicing/title",
          "value": "NSFileProviderServicing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderServicing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderServicing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderServicing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderServicing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderCustomAction/title",
          "value": "NSFileProviderCustomAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderCustomAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderCustomAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderCustomAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderCustomAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileproviderextensionactionidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileproviderextensionactionidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
