{
  "abstract": [
    {
      "text": "A unique identifier for an item managed by the File Provider extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSFileProviderItemIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFileProviderItemIdentifier"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderItemIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSFileProviderItemIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFileProviderItemIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItem-swift.typealias": {
      "abstract": [
        {
          "text": "An item the File Provider extension manages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderItem"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItem-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItem"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderItem",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritem-swift.typealias"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities": {
      "abstract": [
        {
          "text": "An item’s capabilities, which define the actions that the user can perform in the document browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderItemCapabilities",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for an item managed by the File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderItemIdentifier"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderItemIdentifier",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemidentifier"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/init(_:)": {
      "abstract": [
        {
          "text": "Returns a newly instantiated persistent identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemidentifier/init(_:)"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/init(rawValue:)": {
      "abstract": [
        {
          "text": "Returns a newly instantiated persistent identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemidentifier/init(rawvalue:)"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/rootContainer": {
      "abstract": [
        {
          "text": "The persistent identifier for the root directory of the file provider’s shared file hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rootContainer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItemIdentifier",
          "text": "NSFileProviderItemIdentifier"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/rootContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderRootContainerItemIdentifier"
        }
      ],
      "role": "symbol",
      "title": "rootContainer",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemidentifier/rootcontainer"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/trashContainer": {
      "abstract": [
        {
          "text": "The persistent identifier for the parent of all trashed items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trashContainer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItemIdentifier",
          "text": "NSFileProviderItemIdentifier"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/trashContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTrashContainerItemIdentifier"
        }
      ],
      "role": "symbol",
      "title": "trashContainer",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemidentifier/trashcontainer"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/workingSet": {
      "abstract": [
        {
          "text": "The persistent identifier representing the working set of documents and directories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workingSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItemIdentifier",
          "text": "NSFileProviderItemIdentifier"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/workingSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderWorkingSetContainerItemIdentifier"
        }
      ],
      "role": "symbol",
      "title": "workingSet",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemidentifier/workingset"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol": {
      "abstract": [
        {
          "text": "A protocol that defines the properties of an item managed by the File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderItemProtocol"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderItemProtocol",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemprotocol"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTypeAndCreator": {
      "abstract": [
        {
          "text": "A structure that contains the file type and file creator codes for an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTypeAndCreator"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTypeAndCreator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTypeAndCreator"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTypeAndCreator",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertypeandcreator"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Provided-items",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItem-swift.typealias",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTypeAndCreator"
      ],
      "title": "Provided items"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/rootContainer",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/workingSet",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/trashContainer"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/init(_:)",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFileProviderItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/rootContainer",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/workingSet",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemIdentifier/trashContainer"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Provided-items",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItem-swift.typealias",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTypeAndCreator"
              ],
              "title": "Provided items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFileProviderItemIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemIdentifier~1trashContainer/title",
          "value": "NSFileProviderTrashContainerItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemIdentifier~1trashContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTrashContainerItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemIdentifier~1workingSet/title",
          "value": "NSFileProviderWorkingSetContainerItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemIdentifier~1workingSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderWorkingSetContainerItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol/title",
          "value": "NSFileProviderItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTypeAndCreator/title",
          "value": "NSFileProviderTypeAndCreator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTypeAndCreator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTypeAndCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTypeAndCreator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTypeAndCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities/title",
          "value": "NSFileProviderItemCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemIdentifier~1rootContainer/title",
          "value": "NSFileProviderRootContainerItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemIdentifier~1rootContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderRootContainerItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemIdentifier/title",
          "value": "NSFileProviderItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItem-swift.typealias/title",
          "value": "NSFileProviderItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItem-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItem-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovideritemidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovideritemidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
