{
  "abstract": [
    {
      "text": "A structure that contains information about File Provider extension errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC23NSFileProviderErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFileProviderError"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSFileProviderError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFileProviderError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError": {
      "abstract": [
        {
          "text": "A structure that contains information about File Provider extension errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderError"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderError"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code": {
      "abstract": [
        {
          "text": "The error codes for the File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/applicationExtensionNotFound": {
      "abstract": [
        {
          "text": "An error indicating that there isn’t an app extension within the app bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationExtensionNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/applicationExtensionNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "applicationExtensionNotFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/applicationextensionnotfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/cannotSynchronize": {
      "abstract": [
        {
          "text": "An error indicating a failed sync attempt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotSynchronize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/cannotSynchronize",
      "kind": "symbol",
      "role": "symbol",
      "title": "cannotSynchronize",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/cannotsynchronize"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/deletionRejected": {
      "abstract": [
        {
          "text": "An error indicating a failed deletion action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletionRejected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/deletionRejected",
      "kind": "symbol",
      "role": "symbol",
      "title": "deletionRejected",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/deletionrejected"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/directoryNotEmpty": {
      "abstract": [
        {
          "text": "An error indicating an attempt to nonrecursively delete a directory that isn’t empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directoryNotEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/directoryNotEmpty",
      "kind": "symbol",
      "role": "symbol",
      "title": "directoryNotEmpty",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/directorynotempty"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/domainDisabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "domainDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/domainDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "domainDisabled",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/domaindisabled"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/errordomain"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/excludedFromSync": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excludedFromSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/excludedFromSync",
      "kind": "symbol",
      "role": "symbol",
      "title": "excludedFromSync",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/excludedfromsync"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/filenameCollision": {
      "abstract": [
        {
          "text": "An error indicating that an item with the same name already exists in the same directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filenameCollision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/filenameCollision",
      "kind": "symbol",
      "role": "symbol",
      "title": "filenameCollision",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/filenamecollision"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/insufficientQuota": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t upload the item because it would push the account over its quota.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientQuota"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/insufficientQuota",
      "kind": "symbol",
      "role": "symbol",
      "title": "insufficientQuota",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/insufficientquota"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/newerExtensionVersionFound": {
      "abstract": [
        {
          "text": "An error indicating that the registered provider in the system is a newer version than the one the app uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newerExtensionVersionFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/newerExtensionVersionFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "newerExtensionVersionFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/newerextensionversionfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/noSuchItem": {
      "abstract": [
        {
          "text": "An error indicating that the specified item doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuchItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/noSuchItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "noSuchItem",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/nosuchitem"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictable": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t evict an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonEvictable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictable",
      "kind": "symbol",
      "role": "symbol",
      "title": "nonEvictable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/nonevictable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictableChildren": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t evict a directory because it contains nonevictable items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonEvictableChildren"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictableChildren",
      "kind": "symbol",
      "role": "symbol",
      "title": "nonEvictableChildren",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/nonevictablechildren"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/notAuthenticated": {
      "abstract": [
        {
          "text": "An error indicating that you can’t verify the user’s credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthenticated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/notAuthenticated",
      "kind": "symbol",
      "role": "symbol",
      "title": "notAuthenticated",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/notauthenticated"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/olderExtensionVersionRunning": {
      "abstract": [
        {
          "text": "An error indicating that the registered provider in the system is an older version than the one the app uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "olderExtensionVersionRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/olderExtensionVersionRunning",
      "kind": "symbol",
      "role": "symbol",
      "title": "olderExtensionVersionRunning",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/olderextensionversionrunning"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/pageExpired": {
      "abstract": [
        {
          "text": "An error indicating that the page is too old, and that the system must restart the enumeration operation from the beginning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/pageExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "pageExpired",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/pageexpired"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerDomainNotFound": {
      "abstract": [
        {
          "text": "An error indicating that there isn’t a registered domain for the corresponding identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerDomainNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerDomainNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "providerDomainNotFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/providerdomainnotfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerDomainTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "An error indicating that the system is unable to service requests for the domain temporarily, and you can try again later.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerDomainTemporarilyUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerDomainTemporarilyUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "providerDomainTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/providerdomaintemporarilyunavailable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerNotFound": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider manager can’t find the specified provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "providerNotFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/providernotfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerTranslocated": {
      "abstract": [
        {
          "text": "An error indicating the File Provider extension is in a disabled state due to Gatekeeper’s restrictions for apps from outside the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerTranslocated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerTranslocated",
      "kind": "symbol",
      "role": "symbol",
      "title": "providerTranslocated",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/providertranslocated"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/serverUnreachable": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t reach the remote server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverUnreachable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/serverUnreachable",
      "kind": "symbol",
      "role": "symbol",
      "title": "serverUnreachable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/serverunreachable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/syncAnchorExpired": {
      "abstract": [
        {
          "text": "An error indicating that the sync anchor is too old, and that the system must restart the sync operation from the beginning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "syncAnchorExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/syncAnchorExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "syncAnchorExpired",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/syncanchorexpired"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/unsyncedEdits": {
      "abstract": [
        {
          "text": "An error indicating that the item contains unsynced changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsyncedEdits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/unsyncedEdits",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsyncedEdits",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/unsyncededits"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/versionNoLongerAvailable": {
      "abstract": [
        {
          "text": "An error that indicates whether the specified version is no longer available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "versionNoLongerAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/versionNoLongerAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "versionNoLongerAvailable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/versionnolongeravailable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorCollidingItemKey": {
      "abstract": [
        {
          "text": "The key for accessing the existing item from a filename collision error’s user info dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorCollidingItemKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorCollidingItemKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorCollidingItemKey"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderErrorCollidingItemKey",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererrorcollidingitemkey"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for the File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderErrorDomain",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererrordomain"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorItemKey": {
      "abstract": [
        {
          "text": "The key for accessing information about sync-related errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorItemKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorItemKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorItemKey"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderErrorItemKey",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererroritemkey"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorNonExistentItemIdentifierKey": {
      "abstract": [
        {
          "text": "The key for accessing the specified item’s identifier when the item doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNonExistentItemIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorNonExistentItemIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNonExistentItemIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderErrorNonExistentItemIdentifierKey",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererrornonexistentitemidentifierkey"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorDomain",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorItemKey",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorNonExistentItemIdentifierKey",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorCollidingItemKey"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-error-codes",
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/filenameCollision",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/insufficientQuota",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/noSuchItem",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/notAuthenticated",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/pageExpired",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/serverUnreachable",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/syncAnchorExpired",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/directoryNotEmpty",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerNotFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerTranslocated",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/olderExtensionVersionRunning",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/newerExtensionVersionFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictable",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictableChildren",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/unsyncedEdits",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/cannotSynchronize",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/deletionRejected",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/versionNoLongerAvailable",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/domainDisabled",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/excludedFromSync",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/applicationExtensionNotFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerDomainNotFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerDomainTemporarilyUnavailable"
      ],
      "title": "Accessing error codes"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/title",
          "value": "NSFileProviderErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorCollidingItemKey/title",
          "value": "NSFileProviderErrorCollidingItemKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorCollidingItemKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCollidingItemKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorNonExistentItemIdentifierKey/title",
          "value": "NSFileProviderErrorNonExistentItemIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorNonExistentItemIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNonExistentItemIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorItemKey/title",
          "value": "NSFileProviderErrorItemKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorItemKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorItemKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorDomain/title",
          "value": "NSFileProviderErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidererror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
