{
  "abstract": [
    {
      "text": "Track and report changes to open documents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/nonreplicated-file-provider-extension",
        "doc://com.apple.fileprovider/documentation/FileProvider/content-and-change-tracking",
        "doc://com.apple.fileprovider/documentation/FileProvider/tracking-your-file-provider-s-changes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/tracking-changes-to-documents"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Tracking Changes to Documents"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The File Provider extension must report any  changes to a document’s content while the user is viewing the document.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2943054",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When an app opens a document managed by your File Provider extension (using either an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilepresenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object), the system requests an enumerator for that document. This enumerator is used only for tracking changes to the document from other processes (for example, updates from another device).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The document enumerator remains active as long as the document is open. Any calls to its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderEnumerator/enumerateChanges(for:from:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method should return only information about the specified document.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "These changes are forwarded to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilepresenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that is monitoring the document. The app then updates its user interface as needed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UIDocument": {
      "abstract": [
        {
          "text": "An abstract base class for managing discrete portions of your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDocument",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIDocument",
      "type": "topic",
      "url": "/documentation/UIKit/UIDocument"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilepresenter": {
      "abstract": [
        {
          "text": "The interface a file coordinator uses to inform an object presenting a file about changes to that file made elsewhere in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSFilePresenter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilepresenter",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFilePresenter",
      "type": "topic",
      "url": "/documentation/foundation/nsfilepresenter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderEnumerator/enumerateChanges(for:from:)": {
      "abstract": [
        {
          "text": "Requests the next batch of changes after the specified sync anchor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFileProviderChangeObserver",
          "text": "NSFileProviderChangeObserver"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderSyncAnchor",
          "text": "NSFileProviderSyncAnchor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderEnumerator/enumerateChanges(for:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateChangesForObserver:fromSyncAnchor:"
        }
      ],
      "role": "symbol",
      "title": "enumerateChanges(for:from:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderenumerator/enumeratechanges(for:from:)"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/content-and-change-tracking": {
      "abstract": [
        {
          "text": "Create enumerators to specify your file provider’s content, and track changes to that content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/content-and-change-tracking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Content and Change Tracking",
      "type": "topic",
      "url": "/documentation/fileprovider/content-and-change-tracking"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/nonreplicated-file-provider-extension": {
      "abstract": [
        {
          "text": "Build a File Provider extension that hosts and manages the user’s local files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/nonreplicated-file-provider-extension",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nonreplicated File Provider extension",
      "type": "topic",
      "url": "/documentation/fileprovider/nonreplicated-file-provider-extension"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/tracking-your-file-provider-s-changes": {
      "abstract": [
        {
          "text": "Create an enumerator to track changes to your file provider’s content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/tracking-your-file-provider-s-changes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Tracking Your File Provider’s Changes",
      "type": "topic",
      "url": "/documentation/fileprovider/tracking-your-file-provider-s-changes"
    },
    "media-2943054": {
      "alt": "An illustration showing an external update to a document.",
      "identifier": "media-2943054",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/eb519e045a72c884dbf536193712b123/media-2943054@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIDocument/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIDocument"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderEnumerator~1enumerateChanges(for:from:)/title",
          "value": "enumerateChangesForObserver:fromSyncAnchor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderEnumerator~1enumerateChanges(for:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateChangesForObserver:fromSyncAnchor:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/tracking-changes-to-documents"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/tracking-changes-to-documents"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
