{
  "abstract": [
    {
      "text": "Send push notifications to a device to signal changes from your server.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/nonreplicated-file-provider-extension",
        "doc://com.apple.fileprovider/documentation/FileProvider/content-and-change-tracking",
        "doc://com.apple.fileprovider/documentation/FileProvider/tracking-your-file-provider-s-changes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/using-push-notifications-to-signal-changes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Using push notifications to signal changes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can signal changes by sending push notifications from a remote server, using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PushKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushType/fileProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " push type. When the system receives the notification, it automatically calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderManager/signalEnumerator(for:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method with the specified identifier. It also delivers the notification to any ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To use push notifications, you start by generating the signing key for your app. Next, you configure your app to receive push notifications. Finally, you send the notifications from your server. The following sections describe each step.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Avoid sending unnecessary push notifications. If you send too many, Apple Push Notification service (APNs) throttles your requests.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "For open files and directories, try to send push notifications only when your File Provider extension has an active enumerator for that item. This means your extension must update your server whenever an enumerator is created or invalidated. Additionally, this coordination must gracefully degrade when an internet connection is unavailable or fails.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "For items in the working set, the server should always send push notifications.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Generate-the-signing-key",
          "level": 3,
          "text": "Generate the signing key",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To signal changes from a remote server, you use provider authentication tokens (not provider certificates). To create an APNs key for your app, see ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/xcode/mac/current/#/dev54d690a66",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Use the APNs key to sign your JSON Web Tokens (JWT) when sending notifications from your server.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-and-register-for-push-notifications",
          "level": 3,
          "text": "Enable and register for push notifications",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To receive notifications, you first enable push notifications in your app. You can register to receive push notifications in either your app delegate or in your file provider extension. Finally, you send the device token to your server.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "First, enable push notifications in your iOS app (not your File Provider extension). For details, see ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Open the Capabilities pane for your app target.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Turn on push notifications.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Then, register for push notifications. You can register in your app delegate, your File Provider extension, or both.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you only register for push notifications in your app delegate and the device token changes, your app won’t receive notifications until someone launches the app. Registering in the File Provider extension means your app can update the device token the next time anyone interacts with the File Provider extension’s content.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "In your ",
              "type": "text"
            },
            {
              "code": "AppDelegate",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "FileProviderExtension",
              "type": "codeVoice"
            },
            {
              "text": " classes, adopt the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import PushKit",
            "",
            "@UIApplicationMain",
            "class AppDelegate: UIResponder, UIApplicationDelegate, PKPushRegistryDelegate {",
            "    // ...",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "code": [
            "import PushKit",
            "",
            "class FileProviderExtension: NSFileProviderExtension, PKPushRegistryDelegate {",
            "    // ...",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Also, create a ",
              "type": "text"
            },
            {
              "code": "pushRegistry",
              "type": "codeVoice"
            },
            {
              "text": " instance variable in each class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var pushRegistry: PKPushRegistry!"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In your AppDelegate class’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, register for push notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func application(",
            "    _ application: UIApplication, ",
            "    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?",
            ") -> Bool {",
            "    pushRegistry = PKPushRegistry(queue: nil)",
            "    pushRegistry.delegate = self",
            "    pushRegistry.desiredPushTypes = [.fileProvider]",
            "    return true",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Similarly, in your FileProvider class’s ",
              "type": "text"
            },
            {
              "code": "init()",
              "type": "codeVoice"
            },
            {
              "text": " method, register for push notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override init() {",
            "    super.init()",
            "    pushRegistry = PKPushRegistry(queue: nil)",
            "    pushRegistry.delegate = self",
            "    pushRegistry.desiredPushTypes = [.fileProvider]",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didUpdate:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " delegate method in both your ",
              "type": "text"
            },
            {
              "code": "AppDelegate",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "FileProvider",
              "type": "codeVoice"
            },
            {
              "text": " classes. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didInvalidatePushTokenFor:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method is optional.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method is never called for ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushType/fileProvider",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " type pushes. These notifications are automatically handled by the system instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "In both your ",
              "type": "text"
            },
            {
              "code": "AppDelegate",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "FileProvider",
              "type": "codeVoice"
            },
            {
              "text": " classes’ ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didUpdate:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods, when you receive a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushCredentials",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance, extract the value of its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushCredentials/token",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, and send it to your server. This value is an app-specific device token. Your server uses the device token to request push notifications for this device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func pushRegistry(",
            "    _ registry: PKPushRegistry, ",
            "    didUpdate credentials: PKPushCredentials, ",
            "    forType type: PKPushType",
            ") {",
            "    let deviceToken = credentials.token",
            "    // Send the device token to your server here.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Send-push-notifications",
          "level": 3,
          "text": "Send push notifications",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You’re now ready to send a push notification. Start by creating a JWT; for details, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW3",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can reuse the JWT as long as it remains valid.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Then send a POST request to the APNs server with the following values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": ":path",
                      "type": "codeVoice"
                    },
                    {
                      "text": " value is ",
                      "type": "text"
                    },
                    {
                      "code": "/3/device/<device-token>",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". This token is the device token you sent to your server from your ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didUpdate:for:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "authorization",
                      "type": "codeVoice"
                    },
                    {
                      "text": " value is ",
                      "type": "text"
                    },
                    {
                      "code": "bearer <provider token>",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". This token is your JWT.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "apns-topic",
                      "type": "codeVoice"
                    },
                    {
                      "text": " value is ",
                      "type": "text"
                    },
                    {
                      "code": "<bundle identifier>.pushkit.fileprovider",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". The bundle identifier is your app’s bundle identifier.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The POST request’s content is a JSON dictionary that specifies the container and domain for the updated content. Set the container identifier to the unique string used in the container’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/itemIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. You can also use ",
              "type": "text"
            },
            {
              "code": "NSFileProviderRootContainerItemIdentifier",
              "type": "codeVoice"
            },
            {
              "text": " to update the root container, or ",
              "type": "text"
            },
            {
              "code": "NSFileProviderWorkingSetContainerItemIdentifier",
              "type": "codeVoice"
            },
            {
              "text": " to update the working set.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "When using an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", always set the container identifier to ",
                  "type": "text"
                },
                {
                  "code": "NSFileProviderWorkingSetContainerItemIdentifier",
                  "type": "codeVoice"
                },
                {
                  "text": ". The system automatically propagates any working set changes to the user interface, without requiring you to signal individual containers. It ignores any other identifiers.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Set the domain identifier to the unique string used in the domain’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDomain/identifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            " {",
            "     \"container-identifier\": \"<your-container-identifier>\"",
            "     \"domain\": \"<your-domain-identifier>\"",
            " }",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW10",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/PushKit": {
      "abstract": [
        {
          "text": "Respond to push notifications related to your app’s complications, file providers, and VoIP services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PushKit",
      "type": "topic",
      "url": "/documentation/PushKit"
    },
    "doc://com.apple.documentation/documentation/PushKit/PKPushCredentials": {
      "abstract": [
        {
          "text": "An object that encapsulates the device token you use to deliver push notifications to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPushCredentials"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushCredentials",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKPushCredentials",
      "type": "topic",
      "url": "/documentation/PushKit/PKPushCredentials"
    },
    "doc://com.apple.documentation/documentation/PushKit/PKPushCredentials/token": {
      "abstract": [
        {
          "text": "A unique device token to use when sending push notifications to the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushCredentials/token",
      "kind": "symbol",
      "role": "symbol",
      "title": "token",
      "type": "topic",
      "url": "/documentation/PushKit/PKPushCredentials/token"
    },
    "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate": {
      "abstract": [
        {
          "text": "The methods that you use to handle incoming PushKit notifications and registration events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPushRegistryDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKPushRegistryDelegate",
      "type": "topic",
      "url": "/documentation/PushKit/PKPushRegistryDelegate"
    },
    "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didInvalidatePushTokenFor:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system invalidated the push token for the specified type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushRegistry"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "registry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPushRegistry",
          "text": "PKPushRegistry"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didInvalidatePushTokenFor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPushType",
          "text": "PKPushType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didInvalidatePushTokenFor:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "pushRegistry(_:didInvalidatePushTokenFor:)",
      "type": "topic",
      "url": "/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didInvalidatePushTokenFor:)"
    },
    "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a remote push notification arrived.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushRegistry"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "registry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPushRegistry",
          "text": "PKPushRegistry"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveIncomingPushWith"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "payload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPushPayload",
          "text": "PKPushPayload"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPushType",
          "text": "PKPushType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "pushRegistry(_:didReceiveIncomingPushWith:for:completion:)",
      "type": "topic",
      "url": "/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)"
    },
    "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didUpdate:for:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system updated the credentials for the specified type of push notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushRegistry"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "registry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPushRegistry",
          "text": "PKPushRegistry"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "pushCredentials"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPushCredentials",
          "text": "PKPushCredentials"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPushType",
          "text": "PKPushType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didUpdate:for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "pushRegistry(_:didUpdate:for:)",
      "type": "topic",
      "url": "/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didUpdate:for:)"
    },
    "doc://com.apple.documentation/documentation/PushKit/PKPushType/fileProvider": {
      "abstract": [
        {
          "text": "A push type for file provider updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPushType",
          "text": "PKPushType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit/PKPushType/fileProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "fileProvider",
      "type": "topic",
      "url": "/documentation/PushKit/PKPushType/fileProvider"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the launch process is almost done and the app is almost ready to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishLaunchingWithOptions"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIApplicationLaunchOptionsKey",
          "text": "LaunchOptionsKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]? = nil) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:didFinishLaunchingWithOptions:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDomain/identifier": {
      "abstract": [
        {
          "text": "The domain’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderDomainIdentifier",
          "text": "NSFileProviderDomainIdentifier"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDomain/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderdomain/identifier"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/itemIdentifier": {
      "abstract": [
        {
          "text": "The item’s persistent identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItemIdentifier",
          "text": "NSFileProviderItemIdentifier"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemProtocol/itemIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemIdentifier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "itemIdentifier",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemprotocol/itemidentifier"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderManager/signalEnumerator(for:completionHandler:)": {
      "abstract": [
        {
          "text": "Alerts the system to changes in the specified folder’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signalEnumerator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItemIdentifier",
          "text": "NSFileProviderItemIdentifier"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderManager/signalEnumerator(for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signalEnumeratorForContainerItemIdentifier:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "signalEnumerator(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidermanager/signalenumerator(for:completionhandler:)"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension": {
      "abstract": [
        {
          "text": "A File Provider extension in which the system replicates the contents on disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderReplicatedExtension"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderReplicatedExtension"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderReplicatedExtension",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderreplicatedextension"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/content-and-change-tracking": {
      "abstract": [
        {
          "text": "Create enumerators to specify your file provider’s content, and track changes to that content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/content-and-change-tracking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Content and Change Tracking",
      "type": "topic",
      "url": "/documentation/fileprovider/content-and-change-tracking"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/nonreplicated-file-provider-extension": {
      "abstract": [
        {
          "text": "Build a File Provider extension that hosts and manages the user’s local files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/nonreplicated-file-provider-extension",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nonreplicated File Provider extension",
      "type": "topic",
      "url": "/documentation/fileprovider/nonreplicated-file-provider-extension"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/tracking-your-file-provider-s-changes": {
      "abstract": [
        {
          "text": "Create an enumerator to track changes to your file provider’s content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/tracking-your-file-provider-s-changes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Tracking Your File Provider’s Changes",
      "type": "topic",
      "url": "/documentation/fileprovider/tracking-your-file-provider-s-changes"
    },
    "https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW10": {
      "identifier": "https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW10",
      "title": "APNs Notification API",
      "titleInlineContent": [
        {
          "text": "APNs Notification API",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW10"
    },
    "https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW3": {
      "identifier": "https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW3",
      "title": "Provider Authentication Tokens",
      "titleInlineContent": [
        {
          "text": "Provider Authentication Tokens",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW3"
    },
    "https://help.apple.com/xcode/mac/current/#/dev54d690a66": {
      "identifier": "https://help.apple.com/xcode/mac/current/#/dev54d690a66",
      "title": "Communicate with APNs using authentication tokens",
      "titleInlineContent": [
        {
          "text": "Communicate with APNs using authentication tokens",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/xcode/mac/current/#/dev54d690a66"
    },
    "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1": {
      "identifier": "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1",
      "title": "Communicate with APNs using authentication tokens",
      "titleInlineContent": [
        {
          "text": "Communicate with APNs using authentication tokens",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushRegistryDelegate~1pushRegistry(_:didInvalidatePushTokenFor:)/title",
          "value": "pushRegistry:didInvalidatePushTokenForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushRegistryDelegate~1pushRegistry(_:didInvalidatePushTokenFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "pushRegistry:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKPushRegistry",
              "text": "PKPushRegistry"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "registry"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didInvalidatePushTokenForType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PKPushType",
              "text": "PKPushType"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushRegistryDelegate~1pushRegistry(_:didUpdate:for:)/title",
          "value": "pushRegistry:didUpdatePushCredentials:forType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushRegistryDelegate~1pushRegistry(_:didUpdate:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "pushRegistry:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKPushRegistry",
              "text": "PKPushRegistry"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "registry"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didUpdatePushCredentials:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKPushCredentials",
              "text": "PKPushCredentials"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "pushCredentials"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "forType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PKPushType",
              "text": "PKPushType"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushRegistryDelegate~1pushRegistry(_:didReceiveIncomingPushWith:for:completion:)/title",
          "value": "pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushRegistryDelegate~1pushRegistry(_:didReceiveIncomingPushWith:for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "pushRegistry:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKPushRegistry",
              "text": "PKPushRegistry"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "registry"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didReceiveIncomingPushWithPayload:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKPushPayload",
              "text": "PKPushPayload"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "payload"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "forType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PKPushType",
              "text": "PKPushType"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withCompletionHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)()) "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderDomain~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderDomain~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushCredentials/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPushCredentials"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderManager~1signalEnumerator(for:completionHandler:)/title",
          "value": "signalEnumeratorForContainerItemIdentifier:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderManager~1signalEnumerator(for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "signalEnumeratorForContainerItemIdentifier:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFinishLaunchingWithOptions:)/title",
          "value": "application:didFinishLaunchingWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFinishLaunchingWithOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didFinishLaunchingWithOptions:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "launchOptions"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushRegistryDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPushRegistryDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension/title",
          "value": "NSFileProviderReplicatedExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderReplicatedExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderReplicatedExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1itemIdentifier/title",
          "value": "itemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemProtocol~1itemIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushCredentials~1token/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSData",
              "text": "NSData"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "token"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushType~1fileProvider/title",
          "value": "PKPushTypeFileProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PushKit~1PKPushType~1fileProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PKPushType",
              "text": "PKPushType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPushTypeFileProvider"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/using-push-notifications-to-signal-changes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/using-push-notifications-to-signal-changes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
