{
  "abstract": [
    {
      "text": "This property indicates whether the media item’s album is gapless.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumIsGapless"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@ITLibMediaItemPropertyAlbumIsGapless",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ITLibMediaItemPropertyAlbumIsGapless"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibMediaItemPropertyAlbumIsGapless"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "ITLibMediaItemPropertyAlbumIsGapless"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumIsGapless"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntityPropertyPersistentID": {
      "abstract": [
        {
          "text": "The unique identifier of the media entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaEntityPropertyPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntityPropertyPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaEntityPropertyPersistentID"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaEntityPropertyPersistentID",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaentitypropertypersistentid"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAddedDate": {
      "abstract": [
        {
          "text": "The date and time the user added the media item to the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAddedDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAddedDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAddedDate"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyAddedDate",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyaddeddate"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumArtist": {
      "abstract": [
        {
          "text": "The name of the artist that iTunes associates with the media item’s album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumArtist"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyAlbumArtist",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyalbumartist"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumDiscCount": {
      "abstract": [
        {
          "text": "The number of discs in the media item’s album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumDiscCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumDiscCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumDiscCount"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyAlbumDiscCount",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyalbumdisccount"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumDiscNumber": {
      "abstract": [
        {
          "text": "The disc number in the media item’s album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumDiscNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumDiscNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumDiscNumber"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyAlbumDiscNumber",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyalbumdiscnumber"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumIsCompilation": {
      "abstract": [
        {
          "text": "This property indicates whether the album of the media item is a compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumIsCompilation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumIsCompilation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumIsCompilation"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyAlbumIsCompilation",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyalbumiscompilation"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumIsGapless": {
      "abstract": [
        {
          "text": "This property indicates whether the media item’s album is gapless.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumIsGapless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumIsGapless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumIsGapless"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyAlbumIsGapless",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyalbumisgapless"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumRating": {
      "abstract": [
        {
          "text": "The rating of the media item’s album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumRating"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyAlbumRating",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyalbumrating"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumRatingComputed": {
      "abstract": [
        {
          "text": "This property indicates whether iTunes computes the rating of the media item’s album from the ratings of individual tracks in the album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumRatingComputed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumRatingComputed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumRatingComputed"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyAlbumRatingComputed",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyalbumratingcomputed"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumTitle": {
      "abstract": [
        {
          "text": "The title of the media item’s album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumTitle"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyAlbumTitle",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyalbumtitle"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumTrackCount": {
      "abstract": [
        {
          "text": "The track count of the media item’s album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumTrackCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumTrackCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyAlbumTrackCount"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyAlbumTrackCount",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyalbumtrackcount"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyArtistName": {
      "abstract": [
        {
          "text": "The name of the artist that iTunes associates with the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyArtistName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyArtistName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyArtistName"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyArtistName",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyartistname"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyArtwork": {
      "abstract": [
        {
          "text": "The artwork for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyArtwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyArtwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyArtwork"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyArtwork",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertyartwork"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyBeatsPerMinute": {
      "abstract": [
        {
          "text": "The beats-per-minute (BPM) of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyBeatsPerMinute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyBeatsPerMinute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyBeatsPerMinute"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyBeatsPerMinute",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertybeatsperminute"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyBitRate": {
      "abstract": [
        {
          "text": "The bitrate of the media item in kbit/s.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyBitRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyBitRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyBitRate"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyBitRate",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertybitrate"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyCategory": {
      "abstract": [
        {
          "text": "The podcast category of the media item, if the media item is a podcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPropertyCategory"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPropertyCategory",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitempropertycategory"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-Item-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntityPropertyPersistentID",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAddedDate",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumArtist",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumDiscCount",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumDiscNumber",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumIsCompilation",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumRating",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumRatingComputed",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumTitle",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumTrackCount",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyArtistName",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyArtwork",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyBeatsPerMinute",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyBitRate",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyCategory"
      ],
      "title": "Media Item Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibMediaItemPropertyAlbumIsGapless"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumIsGapless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-Item-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntityPropertyPersistentID",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAddedDate",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumArtist",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumDiscCount",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumDiscNumber",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumIsCompilation",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumRating",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumRatingComputed",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumTitle",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyAlbumTrackCount",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyArtistName",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyArtwork",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyBeatsPerMinute",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyBitRate",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPropertyCategory"
              ],
              "title": "Media Item Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ITLibMediaItemPropertyAlbumIsGapless"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumTrackCount/title",
          "value": "ITLibMediaItemPropertyAlbumTrackCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumTrackCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumTrackCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumRating/title",
          "value": "ITLibMediaItemPropertyAlbumRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyCategory/title",
          "value": "ITLibMediaItemPropertyCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumDiscNumber/title",
          "value": "ITLibMediaItemPropertyAlbumDiscNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumDiscNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumDiscNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumArtist/title",
          "value": "ITLibMediaItemPropertyAlbumArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyArtistName/title",
          "value": "ITLibMediaItemPropertyArtistName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyArtistName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyArtistName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumIsCompilation/title",
          "value": "ITLibMediaItemPropertyAlbumIsCompilation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumIsCompilation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumIsCompilation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyBitRate/title",
          "value": "ITLibMediaItemPropertyBitRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyBitRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyBitRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyBeatsPerMinute/title",
          "value": "ITLibMediaItemPropertyBeatsPerMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyBeatsPerMinute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyBeatsPerMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaEntityPropertyPersistentID/title",
          "value": "ITLibMediaEntityPropertyPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaEntityPropertyPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaEntityPropertyPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumTitle/title",
          "value": "ITLibMediaItemPropertyAlbumTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyArtwork/title",
          "value": "ITLibMediaItemPropertyArtwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyArtwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyArtwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumRatingComputed/title",
          "value": "ITLibMediaItemPropertyAlbumRatingComputed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumRatingComputed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumRatingComputed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumIsGapless/title",
          "value": "ITLibMediaItemPropertyAlbumIsGapless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumIsGapless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumIsGapless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAddedDate/title",
          "value": "ITLibMediaItemPropertyAddedDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAddedDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAddedDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumDiscCount/title",
          "value": "ITLibMediaItemPropertyAlbumDiscCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPropertyAlbumDiscCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPropertyAlbumDiscCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitempropertyalbumisgapless"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitempropertyalbumisgapless"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
