{
  "abstract": [
    {
      "text": "These constants specify the possible kinds of playlists.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ITLibPlaylistKind",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ITLibPlaylistKind"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibPlaylistKind"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ITLibPlaylistKind"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind": {
      "abstract": [
        {
          "text": "These constants specify the possible kinds of distinguished playlists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind": {
      "abstract": [
        {
          "text": "An indication of whether the playlist has a special distinction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distinguishedKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibDistinguishedPlaylistKind",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distinguishedKind"
        }
      ],
      "role": "symbol",
      "title": "distinguishedKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/distinguishedkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the playlist is the primary playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPrimary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primary"
        }
      ],
      "role": "symbol",
      "title": "isPrimary",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/isprimary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the playlist is visible to the user in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visible"
        }
      ],
      "role": "symbol",
      "title": "isVisible",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/isvisible"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items": {
      "abstract": [
        {
          "text": "The media items (tracks) in the playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "items"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ITLibMediaItem",
          "text": "ITLibMediaItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "items"
        }
      ],
      "role": "symbol",
      "title": "items",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/items"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind": {
      "abstract": [
        {
          "text": "An indication of the type of playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibPlaylistKind",
          "text": "ITLibPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kind"
        }
      ],
      "role": "symbol",
      "title": "kind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/kind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name": {
      "abstract": [
        {
          "text": "The name or title of the playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/name"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID": {
      "abstract": [
        {
          "text": "The unique persistent identifier of the playlist’s parent playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parentID"
        }
      ],
      "role": "symbol",
      "title": "parentID",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/parentid"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind": {
      "abstract": [
        {
          "text": "These constants specify the possible kinds of playlists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/folder": {
      "abstract": [
        {
          "text": "A playlist folder that the user or iTunes creates, such as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "My Playlist Folder",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Genius Mixes",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "folder"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/folder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKindFolder"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind.folder",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/folder"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/genius": {
      "abstract": [
        {
          "text": "A playlist iTunes creates of songs that go well with a song the user specifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genius"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/genius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKindGenius"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind.genius",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/genius"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/geniusMix": {
      "abstract": [
        {
          "text": "An ongoing playlist in a particular genre—like a commercial-free radio station playing the user’s favorite songs—that iTunes creates from music in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geniusMix"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/geniusMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKindGeniusMix"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind.geniusMix",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/geniusmix"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/init(rawvalue:)"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/regular": {
      "abstract": [
        {
          "text": "A standard playlist that the user or iTunes creates, such as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Music",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Movies",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Pop Mix",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "My Awesome Playlist",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regular"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/regular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKindRegular"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind.regular",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/regular"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/smart": {
      "abstract": [
        {
          "text": "A playlist with contents that iTunes generates by evaluating a set of rules, such as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "90s Music",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Songs from 1999",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smart"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/smart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKindSmart"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind.smart",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind/smart"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Playlist-Info",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind"
      ],
      "title": "Getting Playlist Info"
    }
  ],
  "topicSections": [
    {
      "anchor": "Playlist-Kinds",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/regular",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/smart",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/genius",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/folder",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/geniusMix"
      ],
      "title": "Playlist Kinds"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibPlaylistKind"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Playlist-Kinds",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/regular",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/smart",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/genius",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/folder",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind/geniusMix"
              ],
              "title": "Playlist Kinds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Playlist-Info",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind"
              ],
              "title": "Getting Playlist Info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ITLibPlaylistKind"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1smart/title",
          "value": "ITLibPlaylistKindSmart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1smart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindSmart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isVisible/title",
          "value": "visible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1parentID/title",
          "value": "parentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1parentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/title",
          "value": "ITLibDistinguishedPlaylistKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1items/title",
          "value": "items"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1items/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1distinguishedKind/title",
          "value": "distinguishedKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1distinguishedKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "distinguishedKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/title",
          "value": "ITLibPlaylistKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1geniusMix/title",
          "value": "ITLibPlaylistKindGeniusMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1geniusMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindGeniusMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1folder/title",
          "value": "ITLibPlaylistKindFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1folder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1genius/title",
          "value": "ITLibPlaylistKindGenius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1genius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindGenius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1kind/title",
          "value": "kind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1kind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isPrimary/title",
          "value": "primary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isPrimary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1regular/title",
          "value": "ITLibPlaylistKindRegular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind~1regular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKindRegular"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibplaylistkind"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibplaylistkind"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
