{
  "abstract": [
    {
      "text": "These constants specify the possible kinds of distinguished playlists.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ITLibDistinguishedPlaylistKind",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ITLibDistinguishedPlaylistKind"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibDistinguishedPlaylistKind"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ITLibDistinguishedPlaylistKind"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind": {
      "abstract": [
        {
          "text": "These constants specify the possible kinds of distinguished playlists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/init(rawvalue:)"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kind90sMusic": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s music from the 1990s.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kind90sMusic"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kind90sMusic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKind90sMusic"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kind90sMusic",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kind90smusic"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindApplications": {
      "abstract": [
        {
          "text": "The playlist contains all the user’s iOS apps in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindApplications"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindApplications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindApplications"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindApplications",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindapplications"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindAudiobooks": {
      "abstract": [
        {
          "text": "The playlist contains all the audiobooks in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindAudiobooks"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindAudiobooks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindAudiobooks"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindAudiobooks",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindaudiobooks"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindBooks": {
      "abstract": [
        {
          "text": "The playlist contains all the audiobooks in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindBooks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibDistinguishedPlaylistKind",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindBooks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindBooks"
        }
      ],
      "role": "symbol",
      "title": "kindBooks",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindbooks"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindClassicalMusic": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s classical music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindClassicalMusic"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindClassicalMusic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindClassicalMusic"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindClassicalMusic",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindclassicalmusic"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindHomeVideos": {
      "abstract": [
        {
          "text": "The playlist contains all the user’s home videos in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindHomeVideos"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindHomeVideos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindHomeVideos"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindHomeVideos",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindhomevideos"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindLibraryMusicVideos": {
      "abstract": [
        {
          "text": "The playlist contains all the music videos in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindLibraryMusicVideos"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindLibraryMusicVideos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindLibraryMusicVideos"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindLibraryMusicVideos",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindlibrarymusicvideos"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindLovedSongs": {
      "abstract": [
        {
          "text": "The playlist contains all the user’s loved music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindLovedSongs"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindLovedSongs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindLovedSongs"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindLovedSongs",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindlovedsongs"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMovies": {
      "abstract": [
        {
          "text": "The playlist contains all the movies in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMovies"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMovies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindMovies"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindMovies",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmovies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusic": {
      "abstract": [
        {
          "text": "The playlist contains all the music items in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMusic"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindMusic"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindMusic",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmusic"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicShowsAndMovies": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s music shows and movies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMusicShowsAndMovies"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicShowsAndMovies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindMusicShowsAndMovies"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindMusicShowsAndMovies",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmusicshowsandmovies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicVideos": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s music videos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMusicVideos"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicVideos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindMusicVideos"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindMusicVideos",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmusicvideos"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMyTopRated": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s top rated media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMyTopRated"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMyTopRated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindMyTopRated"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindMyTopRated",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmytoprated"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindNone": {
      "abstract": [
        {
          "text": "The playlist isn’t a distinguished playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindNone"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindNone"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindNone",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindnone"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPodcasts": {
      "abstract": [
        {
          "text": "The playlist contains all the podcasts in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindPodcasts"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPodcasts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindPodcasts"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindPodcasts",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindpodcasts"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPurchases": {
      "abstract": [
        {
          "text": "The playlist contains all the user’s purchases from the iTunes Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindPurchases"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPurchases",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindPurchases"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindPurchases",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindpurchases"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyAdded": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s most recently added media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindRecentlyAdded"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyAdded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindRecentlyAdded"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindRecentlyAdded",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindrecentlyadded"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyPlayed": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s most recently played media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindRecentlyPlayed"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyPlayed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindRecentlyPlayed"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindRecentlyPlayed",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindrecentlyplayed"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRingtones": {
      "abstract": [
        {
          "text": "The playlist contains all the iOS ringtones in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindRingtones"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRingtones",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindRingtones"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindRingtones",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindringtones"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTVShows": {
      "abstract": [
        {
          "text": "The playlist contains all the TV shows in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindTVShows"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTVShows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindTVShows"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindTVShows",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindtvshows"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTop25MostPlayed": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s 25 most played media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindTop25MostPlayed"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTop25MostPlayed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindTop25MostPlayed"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindTop25MostPlayed",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindtop25mostplayed"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindVoiceMemos": {
      "abstract": [
        {
          "text": "The playlist contains all the voice memos in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindVoiceMemos"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindVoiceMemos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindVoiceMemos"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindVoiceMemos",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindvoicememos"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindiTunesU": {
      "abstract": [
        {
          "text": "The playlist contains all the user’s iTunes U items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindiTunesU"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindiTunesU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindiTunesU"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindiTunesU",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kinditunesu"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind": {
      "abstract": [
        {
          "text": "An indication of whether the playlist has a special distinction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distinguishedKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibDistinguishedPlaylistKind",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distinguishedKind"
        }
      ],
      "role": "symbol",
      "title": "distinguishedKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/distinguishedkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the playlist is the primary playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPrimary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primary"
        }
      ],
      "role": "symbol",
      "title": "isPrimary",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/isprimary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the playlist is visible to the user in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visible"
        }
      ],
      "role": "symbol",
      "title": "isVisible",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/isvisible"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items": {
      "abstract": [
        {
          "text": "The media items (tracks) in the playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "items"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ITLibMediaItem",
          "text": "ITLibMediaItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "items"
        }
      ],
      "role": "symbol",
      "title": "items",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/items"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind": {
      "abstract": [
        {
          "text": "An indication of the type of playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibPlaylistKind",
          "text": "ITLibPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kind"
        }
      ],
      "role": "symbol",
      "title": "kind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/kind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name": {
      "abstract": [
        {
          "text": "The name or title of the playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/name"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID": {
      "abstract": [
        {
          "text": "The unique persistent identifier of the playlist’s parent playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parentID"
        }
      ],
      "role": "symbol",
      "title": "parentID",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/parentid"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind": {
      "abstract": [
        {
          "text": "These constants specify the possible kinds of playlists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Playlist-Info",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind"
      ],
      "title": "Getting Playlist Info"
    }
  ],
  "topicSections": [
    {
      "anchor": "Distinguished-Playlist-Kinds",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindNone",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMovies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTVShows",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusic",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindAudiobooks",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindBooks",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRingtones",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPodcasts",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindVoiceMemos",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPurchases",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindiTunesU",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kind90sMusic",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMyTopRated",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTop25MostPlayed",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyPlayed",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyAdded",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicVideos",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindClassicalMusic",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindLibraryMusicVideos",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindHomeVideos",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindApplications",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindLovedSongs",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicShowsAndMovies"
      ],
      "title": "Distinguished Playlist Kinds"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibDistinguishedPlaylistKind"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Distinguished-Playlist-Kinds",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindNone",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMovies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTVShows",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusic",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindAudiobooks",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindBooks",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRingtones",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPodcasts",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindVoiceMemos",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPurchases",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindiTunesU",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kind90sMusic",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMyTopRated",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTop25MostPlayed",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyPlayed",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyAdded",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicVideos",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindClassicalMusic",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindLibraryMusicVideos",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindHomeVideos",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindApplications",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindLovedSongs",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicShowsAndMovies"
              ],
              "title": "Distinguished Playlist Kinds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Playlist-Info",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind"
              ],
              "title": "Getting Playlist Info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ITLibDistinguishedPlaylistKind"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindApplications/title",
          "value": "ITLibDistinguishedPlaylistKindApplications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindApplications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindApplications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindPodcasts/title",
          "value": "ITLibDistinguishedPlaylistKindPodcasts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindPodcasts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindPodcasts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMusicVideos/title",
          "value": "ITLibDistinguishedPlaylistKindMusicVideos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMusicVideos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindMusicVideos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindTop25MostPlayed/title",
          "value": "ITLibDistinguishedPlaylistKindTop25MostPlayed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindTop25MostPlayed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindTop25MostPlayed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindNone/title",
          "value": "ITLibDistinguishedPlaylistKindNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1distinguishedKind/title",
          "value": "distinguishedKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1distinguishedKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "distinguishedKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isVisible/title",
          "value": "visible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindClassicalMusic/title",
          "value": "ITLibDistinguishedPlaylistKindClassicalMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindClassicalMusic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindClassicalMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindBooks/title",
          "value": "ITLibDistinguishedPlaylistKindBooks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindBooks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindBooks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindLibraryMusicVideos/title",
          "value": "ITLibDistinguishedPlaylistKindLibraryMusicVideos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindLibraryMusicVideos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindLibraryMusicVideos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/title",
          "value": "ITLibPlaylistKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindRecentlyAdded/title",
          "value": "ITLibDistinguishedPlaylistKindRecentlyAdded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindRecentlyAdded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindRecentlyAdded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMovies/title",
          "value": "ITLibDistinguishedPlaylistKindMovies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMovies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindMovies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindVoiceMemos/title",
          "value": "ITLibDistinguishedPlaylistKindVoiceMemos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindVoiceMemos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindVoiceMemos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindHomeVideos/title",
          "value": "ITLibDistinguishedPlaylistKindHomeVideos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindHomeVideos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindHomeVideos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindPurchases/title",
          "value": "ITLibDistinguishedPlaylistKindPurchases"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindPurchases/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindPurchases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindiTunesU/title",
          "value": "ITLibDistinguishedPlaylistKindiTunesU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindiTunesU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindiTunesU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/title",
          "value": "ITLibDistinguishedPlaylistKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindTVShows/title",
          "value": "ITLibDistinguishedPlaylistKindTVShows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindTVShows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindTVShows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1kind/title",
          "value": "kind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1kind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindRecentlyPlayed/title",
          "value": "ITLibDistinguishedPlaylistKindRecentlyPlayed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindRecentlyPlayed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindRecentlyPlayed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindAudiobooks/title",
          "value": "ITLibDistinguishedPlaylistKindAudiobooks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindAudiobooks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindAudiobooks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1parentID/title",
          "value": "parentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1parentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kind90sMusic/title",
          "value": "ITLibDistinguishedPlaylistKind90sMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kind90sMusic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind90sMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMusicShowsAndMovies/title",
          "value": "ITLibDistinguishedPlaylistKindMusicShowsAndMovies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMusicShowsAndMovies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindMusicShowsAndMovies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1items/title",
          "value": "items"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1items/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isPrimary/title",
          "value": "primary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isPrimary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindLovedSongs/title",
          "value": "ITLibDistinguishedPlaylistKindLovedSongs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindLovedSongs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindLovedSongs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMusic/title",
          "value": "ITLibDistinguishedPlaylistKindMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMusic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMyTopRated/title",
          "value": "ITLibDistinguishedPlaylistKindMyTopRated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMyTopRated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindMyTopRated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindRingtones/title",
          "value": "ITLibDistinguishedPlaylistKindRingtones"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindRingtones/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindRingtones"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibdistinguishedplaylistkind"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibdistinguishedplaylistkind"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
