{
  "abstract": [
    {
      "text": "These constants specify the possible media kinds of a media item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ITLibMediaItemMediaKind",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ITLibMediaItemMediaKind"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibMediaItemMediaKind"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ITLibMediaItemMediaKind"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKind"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/album": {
      "abstract": [
        {
          "text": "The album of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "album"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ITLibAlbum",
          "text": "ITLibAlbum"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/album",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "album"
        }
      ],
      "role": "symbol",
      "title": "album",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/album"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/artist": {
      "abstract": [
        {
          "text": "Information about the artist that iTunes associates with the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ITLibArtist",
          "text": "ITLibArtist"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "artist"
        }
      ],
      "role": "symbol",
      "title": "artist",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/artist"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/composer": {
      "abstract": [
        {
          "text": "The name of the composer that iTunes associates with the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/composer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "composer"
        }
      ],
      "role": "symbol",
      "title": "composer",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/composer"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/genre": {
      "abstract": [
        {
          "text": "The genre of the media item, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genre"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/genre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genre"
        }
      ],
      "role": "symbol",
      "title": "genre",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/genre"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/isRatingComputed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether iTunes computes the media item’s rating from its album rating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRatingComputed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/isRatingComputed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ratingComputed"
        }
      ],
      "role": "symbol",
      "title": "isRatingComputed",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/isratingcomputed"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/kind": {
      "abstract": [
        {
          "text": "The kind of media item file, such as an MPEG audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/kind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kind"
        }
      ],
      "role": "symbol",
      "title": "kind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/kind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/mediaKind": {
      "abstract": [
        {
          "text": "The kind of media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibMediaItemMediaKind",
          "text": "ITLibMediaItemMediaKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/mediaKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaKind"
        }
      ],
      "role": "symbol",
      "title": "mediaKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/mediakind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/rating": {
      "abstract": [
        {
          "text": "The rating of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/rating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rating"
        }
      ],
      "role": "symbol",
      "title": "rating",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/rating"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortComposer": {
      "abstract": [
        {
          "text": "The name to use when sorting by composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sortComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sortComposer"
        }
      ],
      "role": "symbol",
      "title": "sortComposer",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/sortcomposer"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortTitle": {
      "abstract": [
        {
          "text": "The title of the media item to use when sorting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sortTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sortTitle"
        }
      ],
      "role": "symbol",
      "title": "sortTitle",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/sorttitle"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/startTime": {
      "abstract": [
        {
          "text": "If nonzero, the actual time playback of the media item starts instead of 0:00 (in milliseconds).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/startTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTime"
        }
      ],
      "role": "symbol",
      "title": "startTime",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/starttime"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/stopTime": {
      "abstract": [
        {
          "text": "If nonzero, the actual time playback of the media item stops versus the total time (in milliseconds).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/stopTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopTime"
        }
      ],
      "role": "symbol",
      "title": "stopTime",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/stoptime"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/title": {
      "abstract": [
        {
          "text": "The title of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/title"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/totalTime": {
      "abstract": [
        {
          "text": "The length of the media item in milliseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/totalTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalTime"
        }
      ],
      "role": "symbol",
      "title": "totalTime",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/totaltime"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/trackNumber": {
      "abstract": [
        {
          "text": "The position of the media item within its album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/trackNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackNumber"
        }
      ],
      "role": "symbol",
      "title": "trackNumber",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/tracknumber"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind": {
      "abstract": [
        {
          "text": "These constants specify the possible media kinds of a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/init(rawvalue:)"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAlertTone": {
      "abstract": [
        {
          "text": "The media item is an audio tone that’s not a protected ringtone on an iOS device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindAlertTone"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAlertTone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindAlertTone"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindAlertTone",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindalerttone"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAudiobook": {
      "abstract": [
        {
          "text": "The media item is an audiobook.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindAudiobook"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAudiobook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindAudiobook"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindAudiobook",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindaudiobook"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindBook": {
      "abstract": [
        {
          "text": "The media item is an EPUB file or an iBooks Author book.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindBook"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindBook"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindBook",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindbook"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindDigitalBooklet": {
      "abstract": [
        {
          "text": "The media item is an iTunes Extra or an iTunes LP item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindDigitalBooklet"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindDigitalBooklet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindDigitalBooklet"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindDigitalBooklet",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kinddigitalbooklet"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindHomeVideo": {
      "abstract": [
        {
          "text": "The media item is a non-iTunes Store movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindHomeVideo"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindHomeVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindHomeVideo"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindHomeVideo",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindhomevideo"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindIOSApplication": {
      "abstract": [
        {
          "text": "The media item is an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindIOSApplication"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindIOSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindIOSApplication"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindIOSApplication",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindiosapplication"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindInteractiveBooklet": {
      "abstract": [
        {
          "text": "The media item is a QuickTime movie with embedded Flash.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindInteractiveBooklet"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindInteractiveBooklet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindInteractiveBooklet"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindInteractiveBooklet",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindinteractivebooklet"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMovie": {
      "abstract": [
        {
          "text": "The media item is a movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMovie"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMovie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindMovie"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindMovie",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindmovie"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMusicVideo": {
      "abstract": [
        {
          "text": "The media item is a music video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMusicVideo"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMusicVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindMusicVideo"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindMusicVideo",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindmusicvideo"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBook": {
      "abstract": [
        {
          "text": "The media item is a PDF file that iTunes treats as a book unless the user overrides it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindPDFBook"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindPDFBook"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindPDFBook",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindpdfbook"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBooklet": {
      "abstract": [
        {
          "text": "The media item is an unwrapped PDF file that’s part of a music album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindPDFBooklet"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBooklet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindPDFBooklet"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindPDFBooklet",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindpdfbooklet"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPodcast": {
      "abstract": [
        {
          "text": "The media item is an audio or a video podcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindPodcast"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPodcast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindPodcast"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindPodcast",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindpodcast"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindRingtone": {
      "abstract": [
        {
          "text": "The media item is an iOS ringtone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindRingtone"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindRingtone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindRingtone"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindRingtone",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindringtone"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindSong": {
      "abstract": [
        {
          "text": "The media item is a song.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindSong"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindSong",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindSong"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindSong",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindsong"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindTVShow": {
      "abstract": [
        {
          "text": "The media item is a TV show.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindTVShow"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindTVShow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindTVShow"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindTVShow",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindtvshow"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindUnknown": {
      "abstract": [
        {
          "text": "The media item kind is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindUnknown"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindUnknown"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindUnknown",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindunknown"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindVoiceMemo": {
      "abstract": [
        {
          "text": "The media item is a recorded voice memo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindVoiceMemo"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindVoiceMemo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindVoiceMemo"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindVoiceMemo",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindvoicememo"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindiTunesU": {
      "abstract": [
        {
          "text": "The media item is an iTunes U audio or video file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindiTunesU"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindiTunesU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindiTunesU"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindiTunesU",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kinditunesu"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Media-Item-Info",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/title",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortTitle",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/artist",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/composer",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortComposer",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/rating",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/isRatingComputed",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/startTime",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/stopTime",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/album",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/genre",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/kind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/mediaKind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/totalTime",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/trackNumber"
      ],
      "title": "Getting Media Item Info"
    }
  ],
  "topicSections": [
    {
      "anchor": "Media-Kinds",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindUnknown",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindSong",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMovie",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPodcast",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAudiobook",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBooklet",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMusicVideo",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindTVShow",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindInteractiveBooklet",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindHomeVideo",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindRingtone",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindDigitalBooklet",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindIOSApplication",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindVoiceMemo",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindiTunesU",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindBook",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBook",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAlertTone"
      ],
      "title": "Media Kinds"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibMediaItemMediaKind"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Media-Kinds",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindUnknown",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindSong",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMovie",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPodcast",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAudiobook",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBooklet",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMusicVideo",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindTVShow",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindInteractiveBooklet",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindHomeVideo",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindRingtone",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindDigitalBooklet",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindIOSApplication",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindVoiceMemo",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindiTunesU",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindBook",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBook",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAlertTone"
              ],
              "title": "Media Kinds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Media-Item-Info",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/title",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortTitle",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/artist",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/composer",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortComposer",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/rating",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/isRatingComputed",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/startTime",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/stopTime",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/album",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/genre",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/kind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/mediaKind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/totalTime",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/trackNumber"
              ],
              "title": "Getting Media Item Info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ITLibMediaItemMediaKind"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindiTunesU/title",
          "value": "ITLibMediaItemMediaKindiTunesU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindiTunesU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindiTunesU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindMovie/title",
          "value": "ITLibMediaItemMediaKindMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindMovie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind/title",
          "value": "ITLibMediaItemMediaKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindPDFBooklet/title",
          "value": "ITLibMediaItemMediaKindPDFBooklet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindPDFBooklet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindPDFBooklet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1totalTime/title",
          "value": "totalTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1totalTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindMusicVideo/title",
          "value": "ITLibMediaItemMediaKindMusicVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindMusicVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindMusicVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1rating/title",
          "value": "rating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1rating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindUnknown/title",
          "value": "ITLibMediaItemMediaKindUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindVoiceMemo/title",
          "value": "ITLibMediaItemMediaKindVoiceMemo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindVoiceMemo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindVoiceMemo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindIOSApplication/title",
          "value": "ITLibMediaItemMediaKindIOSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindIOSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindIOSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindHomeVideo/title",
          "value": "ITLibMediaItemMediaKindHomeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindHomeVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindHomeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1sortComposer/title",
          "value": "sortComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1sortComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sortComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1sortTitle/title",
          "value": "sortTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1sortTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sortTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1album/title",
          "value": "album"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1album/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "album"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1startTime/title",
          "value": "startTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1startTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1trackNumber/title",
          "value": "trackNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1trackNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindTVShow/title",
          "value": "ITLibMediaItemMediaKindTVShow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindTVShow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindTVShow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindAlertTone/title",
          "value": "ITLibMediaItemMediaKindAlertTone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindAlertTone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindAlertTone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1stopTime/title",
          "value": "stopTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1stopTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stopTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindSong/title",
          "value": "ITLibMediaItemMediaKindSong"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindSong/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindSong"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1genre/title",
          "value": "genre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1genre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindAudiobook/title",
          "value": "ITLibMediaItemMediaKindAudiobook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindAudiobook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindAudiobook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1composer/title",
          "value": "composer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1composer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "composer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1kind/title",
          "value": "kind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1kind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindPodcast/title",
          "value": "ITLibMediaItemMediaKindPodcast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindPodcast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindPodcast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1isRatingComputed/title",
          "value": "ratingComputed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1isRatingComputed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ratingComputed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindPDFBook/title",
          "value": "ITLibMediaItemMediaKindPDFBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindPDFBook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindPDFBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1mediaKind/title",
          "value": "mediaKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1mediaKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindDigitalBooklet/title",
          "value": "ITLibMediaItemMediaKindDigitalBooklet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindDigitalBooklet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindDigitalBooklet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindInteractiveBooklet/title",
          "value": "ITLibMediaItemMediaKindInteractiveBooklet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindInteractiveBooklet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindInteractiveBooklet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1artist/title",
          "value": "artist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "artist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindRingtone/title",
          "value": "ITLibMediaItemMediaKindRingtone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindRingtone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindRingtone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindBook/title",
          "value": "ITLibMediaItemMediaKindBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindBook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindBook"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitemmediakind"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitemmediakind"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
