{
  "abstract": [
    {
      "text": "This class serves as the entry point to the iTunesLibrary framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ITLibrary",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ITLibrary"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibrary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ITLibrary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties and methods to retrieve media items (tracks) and playlists from the user’s iTunes library. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " also provides methods for extracting artwork from a media file that may or may not be in the iTunes library. Sandboxed and nonsandboxed apps can also use iTunes’ ability to extract artwork.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A person needs to grant your app permission before it can access their iTunes library. Add the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppleMusicUsageDescription",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " key to your app’s ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file, and include a description of how you intend to use their library. If this key isn’t present, the system terminates your app when it tries to access the library.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppleMusicUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s media library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppleMusicUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppleMusicUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSAppleMusicUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibExportFeature": {
      "abstract": [
        {
          "text": "These constants describe the features that an iTunes library supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibExportFeature"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibExportFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibExportFeature"
        }
      ],
      "role": "symbol",
      "title": "ITLibExportFeature",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibexportfeature"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibInitOptions": {
      "abstract": [
        {
          "text": "These constants describe initialization options for an iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibInitOptions"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibInitOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibInitOptions"
        }
      ],
      "role": "symbol",
      "title": "ITLibInitOptions",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibinitoptions"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary": {
      "abstract": [
        {
          "text": "This class serves as the entry point to the iTunesLibrary framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibrary"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibrary"
        }
      ],
      "role": "symbol",
      "title": "ITLibrary",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/allMediaItems": {
      "abstract": [
        {
          "text": "All the media items (tracks) in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allMediaItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ITLibMediaItem",
          "text": "ITLibMediaItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/allMediaItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allMediaItems"
        }
      ],
      "role": "symbol",
      "title": "allMediaItems",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/allmediaitems"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/allPlaylists": {
      "abstract": [
        {
          "text": "All the playlists in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allPlaylists"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ITLibPlaylist",
          "text": "ITLibPlaylist"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/allPlaylists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allPlaylists"
        }
      ],
      "role": "symbol",
      "title": "allPlaylists",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/allplaylists"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/apiMajorVersion": {
      "abstract": [
        {
          "text": "The major version number of the API the iTunesLibrary framework exposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiMajorVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/apiMajorVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "apiMajorVersion"
        }
      ],
      "role": "symbol",
      "title": "apiMajorVersion",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/apimajorversion"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/apiMinorVersion": {
      "abstract": [
        {
          "text": "The minor version number of the API the iTunesLibrary framework exposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiMinorVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/apiMinorVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "apiMinorVersion"
        }
      ],
      "role": "symbol",
      "title": "apiMinorVersion",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/apiminorversion"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/applicationVersion": {
      "abstract": [
        {
          "text": "The version of iTunes that created or modified the iTunes library you’re accessing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/applicationVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationVersion"
        }
      ],
      "role": "symbol",
      "title": "applicationVersion",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/applicationversion"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/artwork(forMediaFile:)": {
      "abstract": [
        {
          "text": "Retrieves the artwork from a media file that may or may not be in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artwork"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forMediaFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ITLibArtwork",
          "text": "ITLibArtwork"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/artwork(forMediaFile:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "artworkForMediaFile:"
        }
      ],
      "role": "symbol",
      "title": "artwork(forMediaFile:)",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/artwork(formediafile:)"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/features": {
      "abstract": [
        {
          "text": "A bitwise OR combination of the features of this library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "features"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibExportFeature",
          "text": "ITLibExportFeature"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/features",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "features"
        }
      ],
      "role": "symbol",
      "title": "features",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/features"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:)": {
      "abstract": [
        {
          "text": "Initializes an instance of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that can retrieve media entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "apiVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAPIVersion:error:"
        }
      ],
      "role": "symbol",
      "title": "init(apiVersion:)",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/init(apiversion:)"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:options:)": {
      "abstract": [
        {
          "text": "Initializes an instance of ",
          "type": "text"
        },
        {
          "code": "ITLibrary",
          "type": "codeVoice"
        },
        {
          "text": " that can retrieve media entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "apiVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibInitOptions",
          "text": "ITLibInitOptions"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAPIVersion:options:error:"
        }
      ],
      "role": "symbol",
      "title": "init(apiVersion:options:)",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/init(apiversion:options:)"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:error:": {
      "abstract": [
        {
          "text": "Creates and initializes an instance of ",
          "type": "text"
        },
        {
          "code": "ITLibrary",
          "type": "codeVoice"
        },
        {
          "text": " that can retrieve media entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "libraryWithAPIVersion:error:"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "libraryWithAPIVersion:error:"
        }
      ],
      "role": "symbol",
      "title": "libraryWithAPIVersion:error:",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/librarywithapiversion:error:"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:options:error:": {
      "abstract": [
        {
          "text": "Creates and initializes an instance of ITLibrary that can retrieve media entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "libraryWithAPIVersion:options:error:"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:options:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "libraryWithAPIVersion:options:error:"
        }
      ],
      "role": "symbol",
      "title": "libraryWithAPIVersion:options:error:",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/librarywithapiversion:options:error:"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/mediaFolderLocation": {
      "abstract": [
        {
          "text": "The location of the iTunes music folder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaFolderLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/mediaFolderLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaFolderLocation"
        }
      ],
      "role": "symbol",
      "title": "mediaFolderLocation",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/mediafolderlocation"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/musicFolderLocation": {
      "abstract": [
        {
          "text": "The location of the iTunes music folder.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicFolderLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/musicFolderLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "musicFolderLocation"
        }
      ],
      "role": "symbol",
      "title": "musicFolderLocation",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/musicfolderlocation"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/reloadData()": {
      "abstract": [
        {
          "text": "Refreshes the data that the framework uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reloadData"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/reloadData()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reloadData"
        }
      ],
      "role": "symbol",
      "title": "reloadData()",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/reloaddata()"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/shouldShowContentRating": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to show content rating labels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldShowContentRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/shouldShowContentRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showContentRating"
        }
      ],
      "role": "symbol",
      "title": "shouldShowContentRating",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/shouldshowcontentrating"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/unloadData()": {
      "abstract": [
        {
          "text": "Unloads the data that the framework uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unloadData"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/unloadData()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unloadData"
        }
      ],
      "role": "symbol",
      "title": "unloadData()",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/unloaddata()"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:)",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:options:)",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibInitOptions"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Getting-iTunes-Library-Info",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/allMediaItems",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/allPlaylists",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/apiMajorVersion",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/apiMinorVersion",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/applicationVersion",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/mediaFolderLocation",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/shouldShowContentRating"
      ],
      "title": "Getting iTunes Library Info"
    },
    {
      "anchor": "Loading-and-Unloading-Data",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/reloadData()",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/unloadData()"
      ],
      "title": "Loading and Unloading Data"
    },
    {
      "anchor": "Accessing-Artwork",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/artwork(forMediaFile:)"
      ],
      "title": "Accessing Artwork"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/features",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibExportFeature",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/musicFolderLocation"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibrary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:)",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:options:)",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:error:",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:options:error:",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibInitOptions"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Getting-iTunes-Library-Info",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/allMediaItems",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/allPlaylists",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/apiMajorVersion",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/apiMinorVersion",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/applicationVersion",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/mediaFolderLocation",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/shouldShowContentRating"
              ],
              "title": "Getting iTunes Library Info"
            },
            {
              "anchor": "Loading-and-Unloading-Data",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/reloadData()",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/unloadData()"
              ],
              "title": "Loading and Unloading Data"
            },
            {
              "anchor": "Accessing-Artwork",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/artwork(forMediaFile:)"
              ],
              "title": "Accessing Artwork"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/features",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibExportFeature",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/musicFolderLocation"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ITLibrary"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1artwork(forMediaFile:)/title",
          "value": "artworkForMediaFile:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1artwork(forMediaFile:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "artworkForMediaFile:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1allMediaItems/title",
          "value": "allMediaItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1allMediaItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allMediaItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1reloadData()/title",
          "value": "reloadData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1reloadData()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reloadData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1shouldShowContentRating/title",
          "value": "showContentRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1shouldShowContentRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showContentRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1init(apiVersion:options:)/title",
          "value": "initWithAPIVersion:options:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1init(apiVersion:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAPIVersion:options:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1unloadData()/title",
          "value": "unloadData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1unloadData()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unloadData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibExportFeature/title",
          "value": "ITLibExportFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibExportFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibExportFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibExportFeature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibExportFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1applicationVersion/title",
          "value": "applicationVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1applicationVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1allPlaylists/title",
          "value": "allPlaylists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1allPlaylists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allPlaylists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1musicFolderLocation/title",
          "value": "musicFolderLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1musicFolderLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "musicFolderLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/title",
          "value": "ITLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1apiMajorVersion/title",
          "value": "apiMajorVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1apiMajorVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "apiMajorVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1apiMinorVersion/title",
          "value": "apiMinorVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1apiMinorVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "apiMinorVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1mediaFolderLocation/title",
          "value": "mediaFolderLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1mediaFolderLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaFolderLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1features/title",
          "value": "features"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1features/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "features"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibInitOptions/title",
          "value": "ITLibInitOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibInitOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibInitOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibInitOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibInitOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1init(apiVersion:)/title",
          "value": "initWithAPIVersion:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1init(apiVersion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAPIVersion:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibrary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibrary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
