{
  "abstract": [
    {
      "text": "This class describes a playlist in the iTunes library.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ITLibPlaylist",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ITLibPlaylist"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibPlaylist"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ITLibPlaylist"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ITLibPlaylist"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "playlist",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is a collection of media items (tracks). The user creates and organizes playlists manually, or iTunes automatically generates them. Playlists are media entities. Each contains a unique identifier and a set of properties. Playlists can form a hierarchical structure. In those cases, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns the persistent ID of the parent playlist.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibAlbum": {
      "abstract": [
        {
          "text": "This class provides information about an album in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibAlbum"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibAlbum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibAlbum"
        }
      ],
      "role": "symbol",
      "title": "ITLibAlbum",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibalbum"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind": {
      "abstract": [
        {
          "text": "These constants specify the possible kinds of distinguished playlists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntity": {
      "abstract": [
        {
          "text": "This class describes a media entity, which can be a media item, such as an audio track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaEntity"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaEntity"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaEntity",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaentity"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist": {
      "abstract": [
        {
          "text": "This class describes a playlist in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylist"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylist"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylist",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind": {
      "abstract": [
        {
          "text": "An indication of whether the playlist has a special distinction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distinguishedKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibDistinguishedPlaylistKind",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distinguishedKind"
        }
      ],
      "role": "symbol",
      "title": "distinguishedKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/distinguishedkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isAllItemsPlaylist": {
      "abstract": [
        {
          "text": "Indicates whether the API exposes every item in the playlist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAllItemsPlaylist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isAllItemsPlaylist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allItemsPlaylist"
        }
      ],
      "role": "symbol",
      "title": "isAllItemsPlaylist",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/isallitemsplaylist"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isMaster": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the playlist represents the entire iTunes library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isMaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isMaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "master"
        }
      ],
      "role": "symbol",
      "title": "isMaster",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/ismaster"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the playlist is the primary playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPrimary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primary"
        }
      ],
      "role": "symbol",
      "title": "isPrimary",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/isprimary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the playlist is visible to the user in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visible"
        }
      ],
      "role": "symbol",
      "title": "isVisible",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/isvisible"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items": {
      "abstract": [
        {
          "text": "The media items (tracks) in the playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "items"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ITLibMediaItem",
          "text": "ITLibMediaItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "items"
        }
      ],
      "role": "symbol",
      "title": "items",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/items"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind": {
      "abstract": [
        {
          "text": "An indication of the type of playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibPlaylistKind",
          "text": "ITLibPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kind"
        }
      ],
      "role": "symbol",
      "title": "kind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/kind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name": {
      "abstract": [
        {
          "text": "The name or title of the playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/name"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID": {
      "abstract": [
        {
          "text": "The unique persistent identifier of the playlist’s parent playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parentID"
        }
      ],
      "role": "symbol",
      "title": "parentID",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist/parentid"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind": {
      "abstract": [
        {
          "text": "These constants specify the possible kinds of playlists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyAllItemsPlaylist": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the API exposes every item in the playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyAllItemsPlaylist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyAllItemsPlaylist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyAllItemsPlaylist"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistPropertyAllItemsPlaylist",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistpropertyallitemsplaylist"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyDistinguisedKind": {
      "abstract": [
        {
          "text": "An indication of whether the playlist has a special distinction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyDistinguisedKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyDistinguisedKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyDistinguisedKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistPropertyDistinguisedKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistpropertydistinguisedkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyItems": {
      "abstract": [
        {
          "text": "The media items (tracks) in the playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyItems"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistPropertyItems",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistpropertyitems"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyKind": {
      "abstract": [
        {
          "text": "An indication of the type of playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistPropertyKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistpropertykind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyMaster": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the playlist represents the entire iTunes library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyMaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyMaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyMaster"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistPropertyMaster",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistpropertymaster"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyName": {
      "abstract": [
        {
          "text": "The name or title of the playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyName"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistPropertyName",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistpropertyname"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyParentPersistentID": {
      "abstract": [
        {
          "text": "The unique persistent identifier of the playlist’s parent playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyParentPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyParentPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyParentPersistentID"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistPropertyParentPersistentID",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistpropertyparentpersistentid"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyPrimary": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the playlist is the primary playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyPrimary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyPrimary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyPrimary"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistPropertyPrimary",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistpropertyprimary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyVisible": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the playlist is visible to the user in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylistPropertyVisible"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylistPropertyVisible",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylistpropertyvisible"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntity"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Albums-and-Playlists",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibAlbum"
      ],
      "title": "Albums and Playlists"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Playlist-Info",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind"
      ],
      "title": "Getting Playlist Info"
    },
    {
      "anchor": "Playlist-Properties",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyAllItemsPlaylist",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyDistinguisedKind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyItems",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyKind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyPrimary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyName",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyParentPersistentID",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyVisible"
      ],
      "title": "Playlist Properties"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isAllItemsPlaylist",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isMaster",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyMaster"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibPlaylist"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Playlist-Info",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/name",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/items",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/parentID",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isPrimary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isVisible",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/distinguishedKind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/kind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistKind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind"
              ],
              "title": "Getting Playlist Info"
            },
            {
              "anchor": "Playlist-Properties",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyAllItemsPlaylist",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyDistinguisedKind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyItems",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyKind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyPrimary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyName",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyParentPersistentID",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyVisible"
              ],
              "title": "Playlist Properties"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isAllItemsPlaylist",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist/isMaster",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylistPropertyMaster"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntity"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Albums-and-Playlists",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibAlbum"
              ],
              "title": "Albums and Playlists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ITLibPlaylist"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntity",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ITLibMediaEntity",
                    "text": "ITLibMediaEntity"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyMaster/title",
          "value": "ITLibPlaylistPropertyMaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyMaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistPropertyMaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibAlbum/title",
          "value": "ITLibAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibAlbum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibAlbum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyVisible/title",
          "value": "ITLibPlaylistPropertyVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistPropertyVisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyItems/title",
          "value": "ITLibPlaylistPropertyItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistPropertyItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyName/title",
          "value": "ITLibPlaylistPropertyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistPropertyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1parentID/title",
          "value": "parentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1parentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isVisible/title",
          "value": "visible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyDistinguisedKind/title",
          "value": "ITLibPlaylistPropertyDistinguisedKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyDistinguisedKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistPropertyDistinguisedKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1kind/title",
          "value": "kind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1kind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaEntity/title",
          "value": "ITLibMediaEntity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaEntity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaEntity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaEntity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaEntity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1items/title",
          "value": "items"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1items/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyAllItemsPlaylist/title",
          "value": "ITLibPlaylistPropertyAllItemsPlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyAllItemsPlaylist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistPropertyAllItemsPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/title",
          "value": "ITLibDistinguishedPlaylistKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyParentPersistentID/title",
          "value": "ITLibPlaylistPropertyParentPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyParentPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistPropertyParentPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isPrimary/title",
          "value": "primary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isPrimary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyPrimary/title",
          "value": "ITLibPlaylistPropertyPrimary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyPrimary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistPropertyPrimary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isAllItemsPlaylist/title",
          "value": "allItemsPlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isAllItemsPlaylist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allItemsPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyKind/title",
          "value": "ITLibPlaylistPropertyKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistPropertyKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistPropertyKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isMaster/title",
          "value": "master"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1isMaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "master"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/title",
          "value": "ITLibPlaylistKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylistKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist/title",
          "value": "ITLibPlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1distinguishedKind/title",
          "value": "distinguishedKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1distinguishedKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "distinguishedKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibplaylist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibplaylist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
