{
  "abstract": [
    {
      "text": "Tells the delegate the system is about to restore the central manager, as part of relaunching the app into the background.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:willRestoreState:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CBCentralManagerDelegate(im)centralManager:willRestoreState:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "centralManager"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CBCentralManager",
        "text": "CBCentralManager"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "willRestoreState"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "centralManager:willRestoreState:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "centralManager(_:willRestoreState:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "centralManager"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "central"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CBCentralManager",
              "text": "CBCentralManager"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "willRestoreState"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "dict"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The central manager that provides this information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "central"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A dictionary that contains information about the central manager preserved by the system when it terminated the app. For the available keys to this dictionary, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/central-manager-state-restoration-options",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "dict"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method only applies to apps that opt in to the state preservation and restoration feature of Core Bluetooth. The system invokes this method when relaunching your app into the background to complete some Bluetooth-related task. Use this method to synchronize the state of your app with the state of the Bluetooth system.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager": {
      "abstract": [
        {
          "text": "An object that scans for, discovers, connects to, and manages peripherals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBCentralManager"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBCentralManager"
        }
      ],
      "role": "symbol",
      "title": "CBCentralManager",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanager"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate": {
      "abstract": [
        {
          "text": "A protocol that provides updates for the discovery and management of peripheral devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBCentralManagerDelegate"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBCentralManagerDelegate"
        }
      ],
      "role": "symbol",
      "title": "CBCentralManagerDelegate",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanagerdelegate"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:willRestoreState:)": {
      "abstract": [
        {
          "text": "Tells the delegate the system is about to restore the central manager, as part of relaunching the app into the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centralManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBCentralManager",
          "text": "CBCentralManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willRestoreState"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:willRestoreState:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centralManager:willRestoreState:"
        }
      ],
      "role": "symbol",
      "title": "centralManager(_:willRestoreState:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:willrestorestate:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManagerDidUpdateState(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate the central manager’s state updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centralManagerDidUpdateState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBCentralManager",
          "text": "CBCentralManager"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManagerDidUpdateState(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centralManagerDidUpdateState:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "centralManagerDidUpdateState(_:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanagerdidupdatestate(_:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/central-manager-state-restoration-options": {
      "abstract": [
        {
          "text": "Keys used to pass state restoration options to the central manager initializer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/central-manager-state-restoration-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Central Manager State Restoration Options",
      "type": "topic",
      "url": "/documentation/corebluetooth/central-manager-state-restoration-options"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Monitoring-the-Central-Managers-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManagerDidUpdateState(_:)"
      ],
      "title": "Monitoring the Central Manager’s State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "centralManager:willRestoreState:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "centralManager:willRestoreState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Monitoring-the-Central-Managers-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManagerDidUpdateState(_:)"
              ],
              "title": "Monitoring the Central Manager’s State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "centralManager:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CBCentralManager",
                    "text": "CBCentralManager"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "central"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "willRestoreState:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
                    "text": "NSDictionary<NSString *,id>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "dict"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The central manager that provides this information.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "central"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary that contains information about the central manager preserved by the system when it terminated the app. For the available keys to this dictionary, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/central-manager-state-restoration-options",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "dict"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/title",
          "value": "CBCentralManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCentralManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCentralManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate/title",
          "value": "CBCentralManagerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCentralManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCentralManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:willRestoreState:)/title",
          "value": "centralManager:willRestoreState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:willRestoreState:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "centralManager:willRestoreState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManagerDidUpdateState(_:)/title",
          "value": "centralManagerDidUpdateState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManagerDidUpdateState(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "centralManagerDidUpdateState:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:willrestorestate:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:willrestorestate:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
