{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CBCentralManager","text":"CBCentralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"connectionEventDidOccur","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@CBConnectionEvent","text":"CBConnectionEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CBPeripheral","text":"CBPeripheral","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"centralManager(_:connectionEventDidOccur:for:)","platforms":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"13.0","deprecated":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"13.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.1"},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false,"introducedAt":"13.0"},{"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"6.0","name":"watchOS","unavailable":false,"deprecated":false}],"role":"symbol","externalID":"c:objc(pl)CBCentralManagerDelegate(im)centralManager:connectionEventDidOccur:forPeripheral:","navigatorTitle":[{"text":"centralManager:connectionEventDidOccur:forPeripheral:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"Core Bluetooth"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"anchor":"Monitoring-Connections-with-Peripherals","identifiers":["doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didConnect:)","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDisconnectPeripheral:error:)","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didFailToConnect:error:)"],"title":"Monitoring Connections with Peripherals"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate"]]},"abstract":[{"text":"Tells the delegate that a connection event occurred which matches the registered options.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"central","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CBCentralManager","kind":"typeIdentifier","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager","preciseIdentifier":"c:objc(cs)CBCentralManager"},{"text":", ","kind":"text"},{"text":"connectionEventDidOccur","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CBConnectionEvent","kind":"typeIdentifier","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEvent","preciseIdentifier":"c:@E@CBConnectionEvent"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"peripheral","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral","kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"The manager calls this method when it observes a connection event that matches the options provided to "},{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/registerForConnectionEvents(options:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:connectioneventdidoccur:for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:connectioneventdidoccur:for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:connectionEventDidOccur:for:)"},"references":{"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","title":"Technologies","role":"overview","url":"/documentation/technologies"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/registerForConnectionEvents(options:)":{"type":"topic","url":"/documentation/corebluetooth/cbcentralmanager/registerforconnectionevents(options:)","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/registerForConnectionEvents(options:)","navigatorTitle":[{"text":"registerForConnectionEventsWithOptions:","kind":"identifier"}],"title":"registerForConnectionEvents(options:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForConnectionEvents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CBConnectionEventMatchingOption","text":"CBConnectionEventMatchingOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a connection matching the given options."}],"role":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth":{"title":"Core Bluetooth","abstract":[{"text":"Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.","type":"text"}],"url":"/documentation/corebluetooth","kind":"symbol","type":"topic","role":"collection","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral":{"url":"/documentation/corebluetooth/cbperipheral","abstract":[{"text":"A remote peripheral device.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBPeripheral","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"CBPeripheral","navigatorTitle":[{"text":"CBPeripheral","kind":"identifier"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager":{"title":"CBCentralManager","type":"topic","kind":"symbol","navigatorTitle":[{"text":"CBCentralManager","kind":"identifier"}],"url":"/documentation/corebluetooth/cbcentralmanager","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager","abstract":[{"text":"An object that scans for, discovers, connects to, and manages peripherals.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBCentralManager","kind":"identifier"}],"role":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate":{"type":"topic","abstract":[{"text":"A protocol that provides updates for the discovery and management of peripheral devices.","type":"text"}],"kind":"symbol","title":"CBCentralManagerDelegate","role":"symbol","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate","navigatorTitle":[{"text":"CBCentralManagerDelegate","kind":"identifier"}],"url":"/documentation/corebluetooth/cbcentralmanagerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBCentralManagerDelegate","kind":"identifier"}]},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didFailToConnect:error:)":{"type":"topic","role":"symbol","title":"centralManager(_:didFailToConnect:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBCentralManager","text":"CBCentralManager"},{"kind":"text","text":", "},{"text":"didFailToConnect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CBPeripheral","text":"CBPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didFailToConnect:error:)","url":"/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:didfailtoconnect:error:)","navigatorTitle":[{"text":"centralManager:didFailToConnectPeripheral:error:","kind":"identifier"}],"abstract":[{"text":"Tells the delegate the central manager failed to create a connection with a peripheral.","type":"text"}],"kind":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:connectionEventDidOccur:for:)":{"type":"topic","url":"/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:connectioneventdidoccur:for:)","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:connectionEventDidOccur:for:)","navigatorTitle":[{"text":"centralManager:connectionEventDidOccur:forPeripheral:","kind":"identifier"}],"title":"centralManager(_:connectionEventDidOccur:for:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBCentralManager","text":"CBCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionEventDidOccur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@CBConnectionEvent","text":"CBConnectionEvent"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that a connection event occurred which matches the registered options."}],"role":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEvent":{"navigatorTitle":[{"kind":"identifier","text":"CBConnectionEvent"}],"role":"symbol","url":"/documentation/corebluetooth/cbconnectionevent","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEvent","abstract":[{"type":"text","text":"A change to the connection state of a peer."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBConnectionEvent"}],"title":"CBConnectionEvent","type":"topic"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDisconnectPeripheral:error:)":{"url":"/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:diddisconnectperipheral:error:)","type":"topic","title":"centralManager(_:didDisconnectPeripheral:error:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"centralManager:didDisconnectPeripheral:error:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CBCentralManager","preciseIdentifier":"c:objc(cs)CBCentralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didDisconnectPeripheral","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that the central manager disconnected from a peripheral."}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDisconnectPeripheral:error:)"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didConnect:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"centralManager:didConnectPeripheral:"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didConnect:)","url":"/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:didconnect:)","title":"centralManager(_:didConnect:)","kind":"symbol","abstract":[{"text":"Tells the delegate that the central manager connected to a peripheral.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"centralManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CBCentralManager","text":"CBCentralManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didConnect","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBPeripheral","text":"CBPeripheral"},{"kind":"text","text":")"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"13.0","deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"13.0","deprecated":false},{"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"13.0","name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"6.0","name":"watchOS","unavailable":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"centralManager:connectionEventDidOccur:forPeripheral:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"centralManager:connectionEventDidOccur:forPeripheral:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didConnect:)","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDisconnectPeripheral:error:)","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didFailToConnect:error:)"],"title":"Monitoring Connections with Peripherals","anchor":"Monitoring-Connections-with-Peripherals"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"centralManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBCentralManager","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager","preciseIdentifier":"c:objc(cs)CBCentralManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"central"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionEventDidOccur:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBConnectionEvent","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEvent","preciseIdentifier":"c:@E@CBConnectionEvent"},{"kind":"text","text":") "},{"kind":"internalParam","text":"event"},{"kind":"text","text":" "},{"kind":"identifier","text":"forPeripheral:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBPeripheral","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1registerForConnectionEvents(options:)/title","value":"registerForConnectionEventsWithOptions:"},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1registerForConnectionEvents(options:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerForConnectionEventsWithOptions:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheral/title","value":"CBPeripheral"},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheral/fragments","value":[{"text":"CBPeripheral","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheral/navigatorTitle","value":[{"text":"CBPeripheral","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/title","value":"CBCentralManager"},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/fragments","value":[{"kind":"identifier","text":"CBCentralManager"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/navigatorTitle","value":[{"kind":"identifier","text":"CBCentralManager"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate/title","value":"CBCentralManagerDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate/fragments","value":[{"text":"CBCentralManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate/navigatorTitle","value":[{"kind":"identifier","text":"CBCentralManagerDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:didFailToConnect:error:)/title","value":"centralManager:didFailToConnectPeripheral:error:"},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:didFailToConnect:error:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"centralManager:didFailToConnectPeripheral:error:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:connectionEventDidOccur:for:)/title","value":"centralManager:connectionEventDidOccur:forPeripheral:"},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:connectionEventDidOccur:for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centralManager:connectionEventDidOccur:forPeripheral:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectionEvent/title","value":"CBConnectionEvent"},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectionEvent/fragments","value":[{"kind":"identifier","text":"CBConnectionEvent"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectionEvent/navigatorTitle","value":[{"text":"CBConnectionEvent","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:didDisconnectPeripheral:error:)/title","value":"centralManager:didDisconnectPeripheral:error:"},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:didDisconnectPeripheral:error:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"centralManager:didDisconnectPeripheral:error:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:didConnect:)/title","value":"centralManager:didConnectPeripheral:"},{"op":"replace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:didConnect:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"centralManager:didConnectPeripheral:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}