{
  "abstract": [
    {
      "text": "The top-left corner is light gray, and the bottom-right corner is dark gray, so the button appears to be pushed in.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSButton",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/concaveWeak"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSGradientType@NSGradientConcaveWeak",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "concaveWeak"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSGradientConcaveWeak"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSButton.GradientType.concaveWeak"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "concaveWeak"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton": {
      "abstract": [
        {
          "text": "A control that defines an area on the screen that a user clicks to trigger an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "role": "symbol",
      "title": "NSButton",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType": {
      "abstract": [
        {
          "text": "Specify the gradients used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/gradientType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GradientType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GradientType"
        }
      ],
      "role": "symbol",
      "title": "NSButton.GradientType",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/gradienttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/concaveStrong": {
      "abstract": [
        {
          "text": "As with ",
          "type": "text"
        },
        {
          "code": "NSGradientConcaveWeak",
          "type": "codeVoice"
        },
        {
          "text": ", the top-left corner is light gray, and the bottom-right corner is dark gray, but the difference between the grays is greater, so the appearance of being pushed in is stronger.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "concaveStrong"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/concaveStrong",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGradientConcaveStrong"
        }
      ],
      "role": "symbol",
      "title": "NSButton.GradientType.concaveStrong",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/gradienttype/concavestrong"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/concaveWeak": {
      "abstract": [
        {
          "text": "The top-left corner is light gray, and the bottom-right corner is dark gray, so the button appears to be pushed in.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "concaveWeak"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/concaveWeak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGradientConcaveWeak"
        }
      ],
      "role": "symbol",
      "title": "NSButton.GradientType.concaveWeak",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/gradienttype/concaveweak"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/convexStrong": {
      "abstract": [
        {
          "text": "As with ",
          "type": "text"
        },
        {
          "code": "NSGradientConvexWeak",
          "type": "codeVoice"
        },
        {
          "text": ", the top-left corner is dark gray, and the bottom-right corner is light gray, but the difference between the grays is greater, so the appearance of sticking out is stronger.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convexStrong"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/convexStrong",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGradientConvexStrong"
        }
      ],
      "role": "symbol",
      "title": "NSButton.GradientType.convexStrong",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/gradienttype/convexstrong"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/convexWeak": {
      "abstract": [
        {
          "text": "The top-left corner is dark gray, and the bottom-right corner is light gray, so the button appears to be sticking out.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convexWeak"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/convexWeak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGradientConvexWeak"
        }
      ],
      "role": "symbol",
      "title": "NSButton.GradientType.convexWeak",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/gradienttype/convexweak"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/none": {
      "abstract": [
        {
          "text": "There is no gradient, so the button looks flat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGradientNone"
        }
      ],
      "role": "symbol",
      "title": "NSButton.GradientType.none",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/gradienttype/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/gradientType": {
      "abstract": [
        {
          "text": "The gradient of the button’s border.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGradientType",
          "text": "GradientType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/gradientType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientType"
        }
      ],
      "role": "symbol",
      "title": "gradientType",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttoncell/gradienttype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/none",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/concaveStrong",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/convexWeak",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/convexStrong"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.12",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSGradientConcaveWeak"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientConcaveWeak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/none",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/concaveStrong",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/convexWeak",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType/convexStrong"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSGradientConcaveWeak"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType~1convexStrong/title",
          "value": "NSGradientConvexStrong"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType~1convexStrong/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientConvexStrong"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType~1none/title",
          "value": "NSGradientNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType~1concaveWeak/title",
          "value": "NSGradientConcaveWeak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType~1concaveWeak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientConcaveWeak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/title",
          "value": "NSButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType~1concaveStrong/title",
          "value": "NSGradientConcaveStrong"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType~1concaveStrong/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientConcaveStrong"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1gradientType/title",
          "value": "gradientType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1gradientType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType~1convexWeak/title",
          "value": "NSGradientConvexWeak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType~1convexWeak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientConvexWeak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType/title",
          "value": "NSGradientType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbutton/gradienttype/concaveweak"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbutton/gradienttype/concaveweak"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
