{
  "abstract": [
    {
      "text": "Notifies the observer immediately before a test suite begins executing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteWillStart(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)XCTestObservation(im)testSuiteWillStart:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "testSuiteWillStart"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCTestSuite",
        "text": "XCTestSuite"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "testSuiteWillStart:"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "testSuiteWillStart(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "testSuiteWillStart"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "testSuite"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestSuite",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTestSuite",
              "text": "XCTestSuite"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The test suite that is about to start. Additional information about the suite can be retrieved from the test suite’s associated ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "testSuite"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation": {
      "abstract": [
        {
          "text": "A protocol that defines methods the test runner calls in response to significant events during test runs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestObservation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestObservation"
        }
      ],
      "role": "symbol",
      "title": "XCTestObservation",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleDidFinish(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately after all tests in a test bundle finish executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testBundleDidFinish"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleDidFinish(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testBundleDidFinish:"
        }
      ],
      "role": "symbol",
      "title": "testBundleDidFinish(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testbundledidfinish(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleWillStart(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately before any tests in a test bundle begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testBundleWillStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleWillStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testBundleWillStart:"
        }
      ],
      "role": "symbol",
      "title": "testBundleWillStart(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testbundlewillstart(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didFailWithDescription:inFile:atLine:)": {
      "abstract": [
        {
          "text": "Notifies the observer when a test case reports a failure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCase"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestCase",
          "text": "XCTestCase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailWithDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "atLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didFailWithDescription:inFile:atLine:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCase:didFailWithDescription:inFile:atLine:"
        }
      ],
      "role": "symbol",
      "title": "testCase(_:didFailWithDescription:inFile:atLine:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testcase(_:didfailwithdescription:infile:atline:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-4cou6": {
      "abstract": [
        {
          "text": "Notifies the observer when a test case reports an issue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCase"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestCase",
          "text": "XCTestCase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6XCTest8XCTIssueV",
          "text": "XCTIssue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-4cou6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCase:didRecordIssue:"
        }
      ],
      "role": "symbol",
      "title": "testCase(_:didRecord:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testcase(_:didrecord:)-4cou6"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-8k955": {
      "abstract": [
        {
          "text": "Notifies the observer when a test case records an expected failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCase"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestCase",
          "text": "XCTestCase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTExpectedFailure",
          "text": "XCTExpectedFailure"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-8k955",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCase:didRecordExpectedFailure:"
        }
      ],
      "role": "symbol",
      "title": "testCase(_:didRecord:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testcase(_:didrecord:)-8k955"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseDidFinish(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately after a test case finishes executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCaseDidFinish"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestCase",
          "text": "XCTestCase"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseDidFinish(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCaseDidFinish:"
        }
      ],
      "role": "symbol",
      "title": "testCaseDidFinish(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testcasedidfinish(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseWillStart(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately before a test case begins executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCaseWillStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestCase",
          "text": "XCTestCase"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseWillStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCaseWillStart:"
        }
      ],
      "role": "symbol",
      "title": "testCaseWillStart(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testcasewillstart(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didFailWithDescription:inFile:atLine:)": {
      "abstract": [
        {
          "text": "Notifies the observer when a test suite reports a failure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testSuite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailWithDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "atLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didFailWithDescription:inFile:atLine:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testSuite:didFailWithDescription:inFile:atLine:"
        }
      ],
      "role": "symbol",
      "title": "testSuite(_:didFailWithDescription:inFile:atLine:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testsuite(_:didfailwithdescription:infile:atline:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-1xjkv": {
      "abstract": [
        {
          "text": "Notifies the observer when a test suite records an expected failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testSuite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTExpectedFailure",
          "text": "XCTExpectedFailure"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-1xjkv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testSuite:didRecordExpectedFailure:"
        }
      ],
      "role": "symbol",
      "title": "testSuite(_:didRecord:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testsuite(_:didrecord:)-1xjkv"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-3rk9k": {
      "abstract": [
        {
          "text": "Notifies the observer when a test suite reports an issue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testSuite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6XCTest8XCTIssueV",
          "text": "XCTIssue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-3rk9k",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testSuite:didRecordIssue:"
        }
      ],
      "role": "symbol",
      "title": "testSuite(_:didRecord:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testsuite(_:didrecord:)-3rk9k"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteDidFinish(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately after a test suite finishes executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testSuiteDidFinish"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteDidFinish(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testSuiteDidFinish:"
        }
      ],
      "role": "symbol",
      "title": "testSuiteDidFinish(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testsuitedidfinish(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteWillStart(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately before a test suite begins executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testSuiteWillStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteWillStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testSuiteWillStart:"
        }
      ],
      "role": "symbol",
      "title": "testSuiteWillStart(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testsuitewillstart(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun": {
      "abstract": [
        {
          "text": "A base class for collecting information about a specific execution of a test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestRun"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestRun"
        }
      ],
      "role": "symbol",
      "title": "XCTestRun",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestSuite": {
      "abstract": [
        {
          "text": "A collection of test cases to manage as a test suite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestSuite"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestSuite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestSuite"
        }
      ],
      "role": "symbol",
      "title": "XCTestSuite",
      "type": "topic",
      "url": "/documentation/xctest/xctestsuite"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Observation-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleWillStart(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseWillStart(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-4cou6",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-8k955",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didFailWithDescription:inFile:atLine:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseDidFinish(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-3rk9k",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-1xjkv",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didFailWithDescription:inFile:atLine:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteDidFinish(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleDidFinish(_:)"
      ],
      "title": "Observation Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "testSuiteWillStart:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuiteWillStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Observation-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleWillStart(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseWillStart(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-4cou6",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-8k955",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didFailWithDescription:inFile:atLine:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseDidFinish(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-3rk9k",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-1xjkv",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didFailWithDescription:inFile:atLine:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteDidFinish(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleDidFinish(_:)"
              ],
              "title": "Observation Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "testSuiteWillStart:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestSuite",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)XCTestSuite",
                    "text": "XCTestSuite"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "testSuite"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The test suite that is about to start. Additional information about the suite can be retrieved from the test suite’s associated ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "testSuite"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didFailWithDescription:inFile:atLine:)/title",
          "value": "testSuite:didFailWithDescription:inFile:atLine:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didFailWithDescription:inFile:atLine:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuite:didFailWithDescription:inFile:atLine:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didRecord:)-1xjkv/title",
          "value": "testSuite:didRecordExpectedFailure:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didRecord:)-1xjkv/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuite:didRecordExpectedFailure:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuiteWillStart(_:)/title",
          "value": "testSuiteWillStart:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuiteWillStart(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuiteWillStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testBundleWillStart(_:)/title",
          "value": "testBundleWillStart:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testBundleWillStart(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testBundleWillStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCaseWillStart(_:)/title",
          "value": "testCaseWillStart:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCaseWillStart(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testCaseWillStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didRecord:)-3rk9k/title",
          "value": "testSuite:didRecordIssue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didRecord:)-3rk9k/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuite:didRecordIssue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didFailWithDescription:inFile:atLine:)/title",
          "value": "testCase:didFailWithDescription:inFile:atLine:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didFailWithDescription:inFile:atLine:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testCase:didFailWithDescription:inFile:atLine:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didRecord:)-8k955/title",
          "value": "testCase:didRecordExpectedFailure:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didRecord:)-8k955/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testCase:didRecordExpectedFailure:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuite/title",
          "value": "XCTestSuite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestSuite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuite/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestSuite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation/title",
          "value": "XCTestObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuiteDidFinish(_:)/title",
          "value": "testSuiteDidFinish:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuiteDidFinish(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuiteDidFinish:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCaseDidFinish(_:)/title",
          "value": "testCaseDidFinish:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCaseDidFinish(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testCaseDidFinish:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didRecord:)-4cou6/title",
          "value": "testCase:didRecordIssue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didRecord:)-4cou6/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testCase:didRecordIssue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/title",
          "value": "XCTestRun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testBundleDidFinish(_:)/title",
          "value": "testBundleDidFinish:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testBundleDidFinish(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testBundleDidFinish:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctestobservation/testsuitewillstart(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctestobservation/testsuitewillstart(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
