{"identifier":{"url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialDescriptor","doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"}]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"This class ties together a credential and its corresponding transport types (USB, NFC, Bluetooth, or all of them).","type":"text"}]}]}],"abstract":[{"text":"An object that holds public key credential transport information.","type":"text"}],"seeAlsoSections":[{"generated":true,"anchor":"Request-configuration","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredential","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEAlgorithmIdentifier","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEEllipticCurveIdentifier","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialAttestationKind","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialDescriptor","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialDescriptor","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport/allSupported"],"title":"Request configuration"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices"]]},"metadata":{"role":"symbol","modules":[{"name":"Authentication Services"}],"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"15.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"15.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"15.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"12.0"}],"roleHeading":"Class","title":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","externalID":"c:objc(cs)ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"}],"navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"}],"symbolKind":"class"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialdescriptor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialdescriptor"]}],"topicSections":[{"anchor":"Creating-the-descriptor","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/init(credentialID:transports:)","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/transports","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport"],"title":"Creating the descriptor"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredential":{"title":"ASPublicKeyCredential","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASPublicKeyCredential","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredential","abstract":[{"type":"text","text":"An interface that defines the properties of the public key."}],"role":"symbol","url":"/documentation/authenticationservices/aspublickeycredential","navigatorTitle":[{"text":"ASPublicKeyCredential","kind":"identifier"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"url":"/documentation/objectivec/nsobject","role":"symbol","kind":"symbol","type":"topic","title":"NSObject","abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}],"fragments":[{"text":"class ","kind":"text"},{"text":"NSObject","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport/allSupported":{"url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialdescriptor/transport/allsupported","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allSupported"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@ASAuthorizationSecurityKeyPublicKeyCredentialDescriptorTransport","text":"Transport"},{"kind":"text","text":"]"}],"title":"allSupported","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport/allSupported","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationAllSupportedPublicKeyCredentialDescriptorTransports"}],"abstract":[{"text":"An array of currently supported transport types.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference":{"type":"topic","navigatorTitle":[{"text":"ASAuthorizationPublicKeyCredentialUserVerificationPreference","kind":"identifier"}],"url":"/documentation/authenticationservices/asauthorizationpublickeycredentialuserverificationpreference","kind":"symbol","abstract":[{"text":"A structure that defines the relying party’s user verification preference.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPublicKeyCredentialUserVerificationPreference","kind":"identifier"}],"title":"ASAuthorizationPublicKeyCredentialUserVerificationPreference","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference","role":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport":{"url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialdescriptor/transport","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Transport"}],"kind":"symbol","abstract":[{"text":"A structure that defines the security key credential transport type.","type":"text"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Transport"}],"title":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor.Transport"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialResidentKeyPreference"}],"type":"topic","abstract":[{"text":"A structure that specifies the relying party’s preference for resident key storage.","type":"text"}],"title":"ASAuthorizationPublicKeyCredentialResidentKeyPreference","url":"/documentation/authenticationservices/asauthorizationpublickeycredentialresidentkeypreference","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialResidentKeyPreference"}],"kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"type":"topic","url":"/documentation/Swift/CustomDebugStringConvertible","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"title":"CustomDebugStringConvertible"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialDescriptor":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPublicKeyCredentialDescriptor","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ASAuthorizationPublicKeyCredentialDescriptor","kind":"identifier"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialDescriptor","role":"symbol","title":"ASAuthorizationPublicKeyCredentialDescriptor","url":"/documentation/authenticationservices/asauthorizationpublickeycredentialdescriptor","abstract":[{"text":"An interface that defines the credential identifier.","type":"text"}],"kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/transports":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/transports","kind":"symbol","title":"transports","abstract":[{"type":"text","text":"The array of transport types."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transports"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@ASAuthorizationSecurityKeyPublicKeyCredentialDescriptorTransport","text":"Transport"},{"kind":"text","text":"]"}],"url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialdescriptor/transports","navigatorTitle":[{"text":"transports","kind":"identifier"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEEllipticCurveIdentifier":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASCOSEEllipticCurveIdentifier"}],"abstract":[{"type":"text","text":"A structure that contains the elliptic curve identifier."}],"type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEEllipticCurveIdentifier","url":"/documentation/authenticationservices/ascoseellipticcurveidentifier","role":"symbol","title":"ASCOSEEllipticCurveIdentifier","navigatorTitle":[{"kind":"identifier","text":"ASCOSEEllipticCurveIdentifier"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/init(credentialID:transports:)":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/init(credentialID:transports:)","kind":"symbol","title":"init(credentialID:transports:)","abstract":[{"type":"text","text":"Creates the object with the credential ID and the array of transports."}],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"credentialID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transports"},{"kind":"text","text":": ["},{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"},{"text":".","kind":"text"},{"text":"Transport","kind":"typeIdentifier","preciseIdentifier":"c:@T@ASAuthorizationSecurityKeyPublicKeyCredentialDescriptorTransport"},{"text":"])","kind":"text"}],"url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialdescriptor/init(credentialid:transports:)","navigatorTitle":[{"text":"initWithCredentialID:transports:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"url":"/documentation/Swift/CustomStringConvertible","abstract":[{"type":"text","text":"A type with a customized textual representation."}],"title":"CustomStringConvertible","type":"topic","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"role":"symbol","kind":"symbol","title":"NSObjectProtocol","url":"/documentation/objectivec/nsobjectprotocol","abstract":[{"type":"text","text":"The group of methods that are fundamental to all Objective-C objects."}],"type":"topic","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSObjectProtocol"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEAlgorithmIdentifier":{"abstract":[{"text":"An identifier for the algorithm that a credential’s key pair uses.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASCOSEAlgorithmIdentifier","kind":"identifier"}],"navigatorTitle":[{"text":"ASCOSEAlgorithmIdentifier","kind":"identifier"}],"title":"ASCOSEAlgorithmIdentifier","kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEAlgorithmIdentifier","url":"/documentation/authenticationservices/ascosealgorithmidentifier"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"abstract":[{"text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.","type":"text"}],"title":"CVarArg","url":"/documentation/Swift/CVarArg","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialAttestationKind":{"abstract":[{"type":"text","text":"A structure that defines the types of attestations a developer can request."}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialAttestationKind","title":"ASAuthorizationPublicKeyCredentialAttestationKind","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/authenticationservices/asauthorizationpublickeycredentialattestationkind","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPublicKeyCredentialAttestationKind","kind":"identifier"}],"navigatorTitle":[{"text":"ASAuthorizationPublicKeyCredentialAttestationKind","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"type":"topic","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","url":"/documentation/Swift/Sendable","kind":"symbol","title":"Sendable","role":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialDescriptor":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialDescriptor"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialDescriptor"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialDescriptor","role":"symbol","title":"ASAuthorizationPlatformPublicKeyCredentialDescriptor","url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialdescriptor","abstract":[{"type":"text","text":"An object that holds the credential."}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding":{"role":"symbol","url":"/documentation/foundation/nssecurecoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","type":"topic","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSSecureCoding"}],"title":"NSSecureCoding","kind":"symbol","abstract":[{"type":"text","text":"A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks."}]},"doc://com.externally.resolved.symbol/s:SH":{"role":"symbol","title":"Hashable","url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCopying"}],"title":"NSCopying","url":"/documentation/foundation/nscopying","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"role":"symbol","type":"topic","abstract":[{"text":"A protocol that enables an object to be encoded and decoded for archiving and distribution.","type":"text"}],"title":"NSCoding","url":"/documentation/foundation/nscoding","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","kind":"identifier"}],"title":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialdescriptor","abstract":[{"text":"An object that holds public key credential transport information.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"},"doc://com.externally.resolved.symbol/s:SQ":{"url":"/documentation/Swift/Equatable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","type":"topic","title":"Equatable"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPublicKeyCredentialParameters","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ASAuthorizationPublicKeyCredentialParameters","kind":"identifier"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters","role":"symbol","title":"ASAuthorizationPublicKeyCredentialParameters","url":"/documentation/authenticationservices/asauthorizationpublickeycredentialparameters","abstract":[{"text":"An object that provides required parameters for the credential during registration.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"15.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"introducedAt":"15.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"15.0","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"unavailable":false,"beta":false,"introducedAt":"12.0","deprecated":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Class"},{"path":"/metadata/title","op":"replace","value":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"},{"path":"/metadata/symbolKind","op":"replace","value":"class"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","kind":"identifier"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices"]]}},{"path":"/topicSections","op":"replace","value":[{"anchor":"Creating-the-descriptor","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/init(credentialID:transports:)","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/transports","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport"],"title":"Creating the descriptor"}]},{"path":"/relationshipsSections","op":"replace","value":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialDescriptor"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}]},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Request configuration","anchor":"Request-configuration","generated":true,"identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredential","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEAlgorithmIdentifier","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEEllipticCurveIdentifier","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialAttestationKind","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialDescriptor","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialDescriptor","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport/allSupported"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPublicKeyCredential/title","value":"ASPublicKeyCredential"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPublicKeyCredential/fragments","value":[{"kind":"identifier","text":"ASPublicKeyCredential"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPublicKeyCredential/navigatorTitle","value":[{"text":"ASPublicKeyCredential","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1Transport~1allSupported/title","value":"ASAuthorizationAllSupportedPublicKeyCredentialDescriptorTransports"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1Transport~1allSupported/fragments","value":[{"text":"ASAuthorizationAllSupportedPublicKeyCredentialDescriptorTransports","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialUserVerificationPreference/title","value":"ASAuthorizationPublicKeyCredentialUserVerificationPreference"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialUserVerificationPreference/fragments","value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialUserVerificationPreference"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialUserVerificationPreference/navigatorTitle","value":[{"text":"ASAuthorizationPublicKeyCredentialUserVerificationPreference","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1Transport/title","value":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptorTransport"},{"value":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptorTransport"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1Transport/fragments"},{"value":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptorTransport"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1Transport/navigatorTitle"},{"value":"ASAuthorizationPublicKeyCredentialResidentKeyPreference","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference/title"},{"value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialResidentKeyPreference"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference/fragments"},{"value":[{"text":"ASAuthorizationPublicKeyCredentialResidentKeyPreference","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference/navigatorTitle"},{"value":"ASAuthorizationPublicKeyCredentialDescriptor","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialDescriptor/title"},{"value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialDescriptor"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialDescriptor/fragments"},{"value":[{"text":"ASAuthorizationPublicKeyCredentialDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialDescriptor/navigatorTitle"},{"value":"transports","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1transports/title"},{"value":[{"text":"transports","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1transports/fragments"},{"value":"ASCOSEEllipticCurveIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEEllipticCurveIdentifier/title"},{"value":[{"text":"ASCOSEEllipticCurveIdentifier","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEEllipticCurveIdentifier/fragments"},{"value":[{"kind":"identifier","text":"ASCOSEEllipticCurveIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEEllipticCurveIdentifier/navigatorTitle"},{"value":"initWithCredentialID:transports:","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1init(credentialID:transports:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCredentialID:transports:"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1init(credentialID:transports:)/fragments"},{"value":"NSObject","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"value":"ASCOSEAlgorithmIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEAlgorithmIdentifier/title"},{"value":[{"kind":"identifier","text":"ASCOSEAlgorithmIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEAlgorithmIdentifier/fragments"},{"value":[{"kind":"identifier","text":"ASCOSEAlgorithmIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEAlgorithmIdentifier/navigatorTitle"},{"value":"ASAuthorizationPublicKeyCredentialAttestationKind","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialAttestationKind/title"},{"value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialAttestationKind"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialAttestationKind/fragments"},{"value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialAttestationKind"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialAttestationKind/navigatorTitle"},{"value":"ASAuthorizationPlatformPublicKeyCredentialDescriptor","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialDescriptor/title"},{"value":[{"text":"ASAuthorizationPlatformPublicKeyCredentialDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialDescriptor/fragments"},{"value":[{"text":"ASAuthorizationPlatformPublicKeyCredentialDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialDescriptor/navigatorTitle"},{"value":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/title"},{"value":[{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/fragments"},{"value":[{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/navigatorTitle"},{"value":"ASAuthorizationPublicKeyCredentialParameters","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialParameters/title"},{"value":[{"text":"ASAuthorizationPublicKeyCredentialParameters","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialParameters/fragments"},{"value":[{"text":"ASAuthorizationPublicKeyCredentialParameters","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialParameters/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}