{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"conformingTypes","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"],"kind":"relationships","title":"Conforming Types"}],"variants":[{"paths":["/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Protocol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"}],"modules":[{"name":"Authentication Services"}],"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"17.4"},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"17.4"},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"16.6"},{"name":"macOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.5"}],"externalID":"c:objc(pl)ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","title":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"},"abstract":[{"type":"text","text":"An interface you use to respond to passkey-creation challenges in a web browser."}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserExternallyAuthenticatableRequest","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"],"title":"Website authentication requests","anchor":"Website-authentication-requests"}],"identifier":{"url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/clientData-5dk66","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/excludedCredentials","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/shouldShowHybridTransport"],"title":"Information about the assertion","anchor":"Information-about-the-assertion"}],"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest","abstract":[{"text":"The object for registering a new platform public key credential.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"title":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/excludedCredentials":{"url":"/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest/excludedcredentials","navigatorTitle":[{"kind":"identifier","text":"excludedCredentials"}],"title":"excludedCredentials","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"excludedCredentials"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ASAuthorizationPlatformPublicKeyCredentialDescriptor","preciseIdentifier":"c:objc(cs)ASAuthorizationPlatformPublicKeyCredentialDescriptor"},{"kind":"text","text":"]?"}],"required":true,"role":"symbol","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/excludedCredentials","type":"topic","abstract":[{"type":"text","text":"A list of passkeys that the relying party doesn’t accept for resolving the challenge."}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/clientData-7scep":{"url":"/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest/clientdata-7scep","title":"clientData","fragments":[{"kind":"identifier","text":"clientData"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/clientData-7scep","type":"topic","abstract":[{"type":"text","text":"The client data to supply to the relying party."}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/shouldShowHybridTransport":{"url":"/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest/shouldshowhybridtransport","navigatorTitle":[{"kind":"identifier","text":"shouldShowHybridTransport"}],"title":"shouldShowHybridTransport","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldShowHybridTransport"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"required":true,"role":"symbol","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/shouldShowHybridTransport","type":"topic","abstract":[{"type":"text","text":"Whether a remote authenticator that communicates with the operating system using Bluetooth can resolve the challenge."}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/clientData-5dk66":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientData"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22AuthenticationServices31ASPublicKeyCredentialClientDataV","kind":"typeIdentifier","text":"ASPublicKeyCredentialClientData"},{"kind":"text","text":"?"}],"abstract":[{"text":"The client data to supply to the relying party.","type":"text"}],"type":"topic","role":"symbol","title":"clientData","url":"/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest/clientdata-5dk66","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/clientData-5dk66"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest":{"navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"}],"title":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","kind":"symbol","abstract":[{"type":"text","text":"An interface you use to respond to passkey-creation challenges in a web browser."}],"url":"/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserExternallyAuthenticatableRequest":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserExternallyAuthenticatableRequest","role":"symbol","navigatorTitle":[{"text":"ASAuthorizationWebBrowserExternallyAuthenticatableRequest","kind":"identifier"}],"title":"ASAuthorizationWebBrowserExternallyAuthenticatableRequest","type":"topic","url":"/documentation/authenticationservices/asauthorizationwebbrowserexternallyauthenticatablerequest","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationWebBrowserExternallyAuthenticatableRequest","kind":"identifier"}],"abstract":[{"text":"An authorization request for which a web browser can retrieve credentials.","type":"text"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest","abstract":[{"type":"text","text":"An interface you use to respond to authentication challenges in a web browser."}],"role":"symbol","type":"topic","title":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest","url":"/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialassertionrequest","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"introducedAt":"17.4","unavailable":false,"name":"iOS","beta":false},{"introducedAt":"17.4","beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"16.6","beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"13.5","beta":false,"deprecated":false,"unavailable":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Protocol"},{"op":"replace","path":"/metadata/title","value":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"},{"op":"replace","path":"/metadata/symbolKind","value":"protocol"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices"]]}},{"op":"replace","path":"/topicSections","value":[{"title":"Information about the assertion","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/clientData-7scep","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/excludedCredentials","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/shouldShowHybridTransport"],"anchor":"Information-about-the-assertion"}]},{"value":[{"type":"conformingTypes","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"],"kind":"relationships","title":"Conforming Types"}],"path":"/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserExternallyAuthenticatableRequest","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"],"anchor":"Website-authentication-requests","generated":true,"title":"Website authentication requests"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/title","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/fragments","value":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/navigatorTitle","value":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest~1excludedCredentials/title","value":"excludedCredentials"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest~1excludedCredentials/fragments","value":[{"text":"excludedCredentials","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest~1shouldShowHybridTransport/title","value":"shouldShowHybridTransport"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest~1shouldShowHybridTransport/fragments","value":[{"text":"shouldShowHybridTransport","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/title","value":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/fragments","value":[{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/navigatorTitle","value":[{"text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserExternallyAuthenticatableRequest/title","value":"ASAuthorizationWebBrowserExternallyAuthenticatableRequest"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserExternallyAuthenticatableRequest/fragments","value":[{"kind":"identifier","text":"ASAuthorizationWebBrowserExternallyAuthenticatableRequest"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserExternallyAuthenticatableRequest/navigatorTitle","value":[{"text":"ASAuthorizationWebBrowserExternallyAuthenticatableRequest","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/title","value":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/fragments","value":[{"text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/navigatorTitle","value":[{"text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}