{"seeAlsoSections":[{"generated":true,"title":"Account registration","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistration","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistration","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistration","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistrationRequest","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"],"anchor":"Account-registration"}],"variants":[{"paths":["/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialregistrationrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialregistrationrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Create an instance of this class when registering for a new credential using security key authorization.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The object for registering a new security key credential."}],"sections":[],"metadata":{"role":"symbol","title":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest","modules":[{"name":"Authentication Services"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"platforms":[{"deprecated":false,"introducedAt":"15.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"15.0","name":"iPadOS","unavailable":false,"beta":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"15.0","deprecated":false,"unavailable":false},{"beta":false,"name":"macOS","introducedAt":"12.0","deprecated":false,"unavailable":false}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"}],"symbolKind":"class","externalID":"c:objc(cs)ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationRequest"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistrationRequest","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest","doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s8CopyableP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo","kind":"relationships"}],"topicSections":[{"title":"Getting the properties","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/credentialParameters","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/excludedCredentials","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/residentKeyPreference"],"anchor":"Getting-the-properties"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices"]]},"references":{"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"role":"symbol","title":"Hashable","url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistration":{"role":"symbol","navigatorTitle":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistration","kind":"identifier"}],"type":"topic","abstract":[{"text":"A newly created platform credential that results from a credential registration request.","type":"text"}],"title":"ASAuthorizationPlatformPublicKeyCredentialRegistration","url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistration"}],"kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistration"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistrationRequest":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialRegistrationRequest"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistrationRequest","abstract":[{"type":"text","text":"An interface that defines properties for a credential registration request."}],"url":"/documentation/authenticationservices/asauthorizationpublickeycredentialregistrationrequest","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialRegistrationRequest"}],"title":"ASAuthorizationPublicKeyCredentialRegistrationRequest"},"doc://com.externally.resolved.symbol/s:s8CopyableP":{"abstract":[{"type":"text","text":"A type whose values can be implicitly or explicitly copied."}],"identifier":"doc://com.externally.resolved.symbol/s:s8CopyableP","title":"Copyable","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/Swift/Copyable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Copyable","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCopying"}],"title":"NSCopying","url":"/documentation/foundation/nscopying","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding":{"role":"symbol","url":"/documentation/foundation/nssecurecoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","type":"topic","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSSecureCoding"}],"title":"NSSecureCoding","kind":"symbol","abstract":[{"type":"text","text":"A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks."}]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationRequest":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationRequest"}],"type":"topic","abstract":[{"text":"A base class for different kinds of authorization requests.","type":"text"}],"title":"ASAuthorizationRequest","url":"/documentation/authenticationservices/asauthorizationrequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationRequest"}],"kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationRequest"},"doc://com.externally.resolved.symbol/s:SQ":{"url":"/documentation/Swift/Equatable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","type":"topic","title":"Equatable"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"type":"topic","url":"/documentation/Swift/CustomDebugStringConvertible","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"title":"CustomDebugStringConvertible"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest":{"abstract":[],"type":"topic","role":"symbol","title":"ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest","url":"/documentation/authenticationservices/asauthorizationwebbrowsersecuritykeypublickeycredentialregistrationrequest","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"url":"/documentation/Swift/CustomStringConvertible","abstract":[{"type":"text","text":"A type with a customized textual representation."}],"title":"CustomStringConvertible","type":"topic","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"role":"symbol","type":"topic","abstract":[{"text":"A protocol that enables an object to be encoded and decoded for archiving and distribution.","type":"text"}],"title":"NSCoding","url":"/documentation/foundation/nscoding","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/excludedCredentials":{"abstract":[{"type":"text","text":"An array of excluded parameters for the credential."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"excludedCredentials","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"},{"kind":"text","text":"]"}],"role":"symbol","type":"topic","title":"excludedCredentials","url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialregistrationrequest/excludedcredentials","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/excludedCredentials","navigatorTitle":[{"kind":"identifier","text":"excludedCredentials"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistrationrequest","abstract":[{"text":"The object for registering a new platform public key credential.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"title":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/residentKeyPreference":{"abstract":[{"type":"text","text":"The preference that indicates where the resident key resides."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"residentKeyPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationPublicKeyCredentialResidentKeyPreference","preciseIdentifier":"c:@T@ASAuthorizationPublicKeyCredentialResidentKeyPreference"}],"role":"symbol","type":"topic","title":"residentKeyPreference","url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialregistrationrequest/residentkeypreference","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/residentKeyPreference","navigatorTitle":[{"kind":"identifier","text":"residentKeyPreference"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistration":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialRegistration"}],"title":"ASAuthorizationPublicKeyCredentialRegistration","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialRegistration"}],"url":"/documentation/authenticationservices/asauthorizationpublickeycredentialregistration","role":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistration","abstract":[{"type":"text","text":"An interface that credential registration requests adhere to."}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistration":{"url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialregistration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistration"}],"kind":"symbol","type":"topic","title":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistration","abstract":[{"type":"text","text":"A newly created security key credential that results from a credential registration request."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistration"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistration"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"abstract":[{"text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.","type":"text"}],"title":"CVarArg","url":"/documentation/Swift/CVarArg","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest":{"abstract":[{"text":"The object for registering a new security key credential.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"}],"type":"topic","url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialregistrationrequest","role":"symbol","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"}],"title":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"role":"symbol","kind":"symbol","title":"NSObjectProtocol","url":"/documentation/objectivec/nsobjectprotocol","abstract":[{"type":"text","text":"The group of methods that are fundamental to all Objective-C objects."}],"type":"topic","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSObjectProtocol"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/credentialParameters":{"abstract":[{"type":"text","text":"An array of parameters for the credential."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"credentialParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ASAuthorizationPublicKeyCredentialParameters","preciseIdentifier":"c:objc(cs)ASAuthorizationPublicKeyCredentialParameters"},{"kind":"text","text":"]"}],"role":"symbol","type":"topic","title":"credentialParameters","url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialregistrationrequest/credentialparameters","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/credentialParameters","navigatorTitle":[{"kind":"identifier","text":"credentialParameters"}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"type":"topic","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","url":"/documentation/Swift/Sendable","kind":"symbol","title":"Sendable","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"15.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"15.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"introducedAt":"15.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"name":"macOS","introducedAt":"12.0","beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Class","op":"replace","path":"/metadata/roleHeading"},{"value":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest","op":"replace","path":"/metadata/title"},{"value":"class","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices"]]},"op":"replace","path":"/hierarchy"},{"value":[{"title":"Getting the properties","anchor":"Getting-the-properties","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/credentialParameters","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/excludedCredentials","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/residentKeyPreference"]}],"op":"replace","path":"/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationRequest"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistrationRequest","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"],"type":"conformsTo"}],"op":"replace","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistration","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistration","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistration","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistrationRequest","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"],"anchor":"Account-registration","title":"Account registration"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"ASAuthorizationRequest","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationRequest"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":"ASAuthorizationPlatformPublicKeyCredentialRegistration","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistration/title"},{"op":"replace","value":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistration/fragments"},{"op":"replace","value":[{"text":"ASAuthorizationPlatformPublicKeyCredentialRegistration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistration/navigatorTitle"},{"op":"replace","value":"ASAuthorizationPublicKeyCredentialRegistrationRequest","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialRegistrationRequest/title"},{"op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialRegistrationRequest"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialRegistrationRequest/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialRegistrationRequest"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialRegistrationRequest/navigatorTitle"},{"op":"replace","value":"ASAuthorizationRequest","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationRequest/title"},{"op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationRequest"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationRequest/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationRequest"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationRequest/navigatorTitle"},{"value":"ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/title"},{"value":[{"kind":"identifier","text":"ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/fragments"},{"value":[{"text":"ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/navigatorTitle"},{"value":"excludedCredentials","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest~1excludedCredentials/title"},{"value":[{"text":"excludedCredentials","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest~1excludedCredentials/fragments"},{"value":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/title"},{"value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/fragments"},{"value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest/navigatorTitle"},{"value":"residentKeyPreference","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest~1residentKeyPreference/title"},{"value":[{"text":"residentKeyPreference","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest~1residentKeyPreference/fragments"},{"value":"ASAuthorizationPublicKeyCredentialRegistration","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialRegistration/title"},{"value":[{"text":"ASAuthorizationPublicKeyCredentialRegistration","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialRegistration/fragments"},{"value":[{"text":"ASAuthorizationPublicKeyCredentialRegistration","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialRegistration/navigatorTitle"},{"value":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistration","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistration/title"},{"value":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistration"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistration/fragments"},{"value":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistration"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistration/navigatorTitle"},{"value":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/title"},{"value":[{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/fragments"},{"value":[{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/navigatorTitle"},{"value":"NSObject","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"value":"credentialParameters","op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest~1credentialParameters/title"},{"value":[{"kind":"identifier","text":"credentialParameters"}],"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest~1credentialParameters/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}