{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest": {
      "abstract": [
        {
          "text": "The object for registering a new security key credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialregistrationrequest"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowsersecuritykeypublickeycredentialregistrationrequest"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/clientData-3hz81": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22AuthenticationServices31ASPublicKeyCredentialClientDataV",
          "text": "ASPublicKeyCredentialClientData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/clientData-3hz81",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientData",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowsersecuritykeypublickeycredentialregistrationrequest/clientdata-3hz81"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/clientData-t1ze": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "clientData"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/clientData-t1ze",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientData",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowsersecuritykeypublickeycredentialregistrationrequest/clientdata-t1ze"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/clientData-3hz81"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/clientData-t1ze"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/title",
          "value": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/title",
          "value": "ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationwebbrowsersecuritykeypublickeycredentialregistrationrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationwebbrowsersecuritykeypublickeycredentialregistrationrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
