{
  "abstract": [
    {
      "text": "An interface through which a single sign-on (SSO) authentication provider extension handles authentication requests.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ASAuthorizationProviderExtensionAuthorizationRequestHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationController/RequestOptions": {
      "abstract": [
        {
          "text": "Options that modify how a controller performs authorization requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RequestOptions"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationController/RequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RequestOptions"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationController.RequestOptions",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationcontroller/requestoptions"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequest": {
      "abstract": [
        {
          "text": "An authorization request that your provider extension handles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationProviderExtensionAuthorizationRequest"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationProviderExtensionAuthorizationRequest"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationProviderExtensionAuthorizationRequest",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionauthorizationrequest"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler": {
      "abstract": [
        {
          "text": "An interface through which a single sign-on (SSO) authentication provider extension handles authentication requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationProviderExtensionAuthorizationRequestHandler",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionauthorizationrequesthandler"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler/beginAuthorization(with:)": {
      "abstract": [
        {
          "text": "Tells your request handler to authorize the given request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASAuthorizationProviderExtensionAuthorizationRequest",
          "text": "ASAuthorizationProviderExtensionAuthorizationRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler/beginAuthorization(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginAuthorizationWithRequest:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "beginAuthorization(with:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionauthorizationrequesthandler/beginauthorization(with:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler/cancelAuthorization(with:)": {
      "abstract": [
        {
          "text": "Tells your request handler to cancel the authorization of the given request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASAuthorizationProviderExtensionAuthorizationRequest",
          "text": "ASAuthorizationProviderExtensionAuthorizationRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler/cancelAuthorization(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelAuthorizationWithRequest:"
        }
      ],
      "role": "symbol",
      "title": "cancelAuthorization(with:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionauthorizationrequesthandler/cancelauthorization(with:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationResult": {
      "abstract": [
        {
          "text": "The result of an authorization request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationProviderExtensionAuthorizationResult"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationProviderExtensionAuthorizationResult"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationProviderExtensionAuthorizationResult",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionauthorizationresult"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSingleSignOnCredential": {
      "abstract": [
        {
          "text": "A credential that results from a successful single sign-on (SSO) authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationSingleSignOnCredential"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSingleSignOnCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationSingleSignOnCredential"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationSingleSignOnCredential",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationsinglesignoncredential"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSingleSignOnProvider": {
      "abstract": [
        {
          "text": "A mechanism for generating requests to authenticate users with third-party providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationSingleSignOnProvider"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSingleSignOnProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationSingleSignOnProvider"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationSingleSignOnProvider",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationsinglesignonprovider"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performing-enterprise-single-sign-on",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSingleSignOnProvider",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSingleSignOnCredential",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationResult",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationController/RequestOptions"
      ],
      "title": "Performing enterprise single sign-on"
    }
  ],
  "topicSections": [
    {
      "anchor": "Starting-or-Canceling-a-Request",
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler/beginAuthorization(with:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler/cancelAuthorization(with:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequest"
      ],
      "title": "Starting or Canceling a Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Starting-or-Canceling-a-Request",
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler/beginAuthorization(with:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequestHandler/cancelAuthorization(with:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationRequest"
              ],
              "title": "Starting or Canceling a Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Performing-enterprise-single-sign-on",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSingleSignOnProvider",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSingleSignOnCredential",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionAuthorizationResult",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationController/RequestOptions"
              ],
              "title": "Performing enterprise single sign-on"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSingleSignOnProvider/title",
          "value": "ASAuthorizationSingleSignOnProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSingleSignOnProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationSingleSignOnProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSingleSignOnProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationSingleSignOnProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSingleSignOnCredential/title",
          "value": "ASAuthorizationSingleSignOnCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSingleSignOnCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationSingleSignOnCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSingleSignOnCredential/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationSingleSignOnCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationRequestHandler/title",
          "value": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationRequestHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationRequestHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionAuthorizationRequestHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationResult/title",
          "value": "ASAuthorizationProviderExtensionAuthorizationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionAuthorizationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionAuthorizationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationController~1RequestOptions/title",
          "value": "ASAuthorizationControllerRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationController~1RequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationControllerRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationController~1RequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationControllerRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationRequestHandler~1cancelAuthorization(with:)/title",
          "value": "cancelAuthorizationWithRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationRequestHandler~1cancelAuthorization(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelAuthorizationWithRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationRequest/title",
          "value": "ASAuthorizationProviderExtensionAuthorizationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionAuthorizationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionAuthorizationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationRequestHandler~1beginAuthorization(with:)/title",
          "value": "beginAuthorizationWithRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionAuthorizationRequestHandler~1beginAuthorization(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginAuthorizationWithRequest:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationproviderextensionauthorizationrequesthandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationproviderextensionauthorizationrequesthandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
