{"seeAlsoSections":[{"generated":true,"title":"Request configuration","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredential","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEAlgorithmIdentifier","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEEllipticCurveIdentifier","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialAttestationKind","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialDescriptor","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialDescriptor","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport/allSupported"],"anchor":"Request-configuration"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialParameters"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This object is mainly for signing algorithm negotiation, and is only relevant for physical security keys.","type":"text"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters"},"metadata":{"title":"ASAuthorizationPublicKeyCredentialParameters","roleHeading":"Class","symbolKind":"class","role":"symbol","externalID":"c:objc(cs)ASAuthorizationPublicKeyCredentialParameters","modules":[{"name":"Authentication Services"}],"platforms":[{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"12.0","beta":false,"unavailable":false,"deprecated":false,"name":"macOS"},{"introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialParameters"}],"navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialParameters"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/authenticationservices/asauthorizationpublickeycredentialparameters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/authenticationservices/asauthorizationpublickeycredentialparameters"]}],"topicSections":[{"title":"Getting the parameters","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters/init(algorithm:)","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters/algorithm"],"anchor":"Getting-the-parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"An object that provides required parameters for the credential during registration.","type":"text"}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo"}],"references":{"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredential":{"title":"ASPublicKeyCredential","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASPublicKeyCredential","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredential","abstract":[{"type":"text","text":"An interface that defines the properties of the public key."}],"role":"symbol","url":"/documentation/authenticationservices/aspublickeycredential","navigatorTitle":[{"text":"ASPublicKeyCredential","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPublicKeyCredentialParameters","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ASAuthorizationPublicKeyCredentialParameters","kind":"identifier"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters","role":"symbol","title":"ASAuthorizationPublicKeyCredentialParameters","url":"/documentation/authenticationservices/asauthorizationpublickeycredentialparameters","abstract":[{"text":"An object that provides required parameters for the credential during registration.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding":{"role":"symbol","url":"/documentation/foundation/nssecurecoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","type":"topic","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSSecureCoding"}],"title":"NSSecureCoding","kind":"symbol","abstract":[{"type":"text","text":"A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks."}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialAttestationKind":{"abstract":[{"type":"text","text":"A structure that defines the types of attestations a developer can request."}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialAttestationKind","title":"ASAuthorizationPublicKeyCredentialAttestationKind","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/authenticationservices/asauthorizationpublickeycredentialattestationkind","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPublicKeyCredentialAttestationKind","kind":"identifier"}],"navigatorTitle":[{"text":"ASAuthorizationPublicKeyCredentialAttestationKind","kind":"identifier"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEAlgorithmIdentifier":{"abstract":[{"text":"An identifier for the algorithm that a credential’s key pair uses.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASCOSEAlgorithmIdentifier","kind":"identifier"}],"navigatorTitle":[{"text":"ASCOSEAlgorithmIdentifier","kind":"identifier"}],"title":"ASCOSEAlgorithmIdentifier","kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEAlgorithmIdentifier","url":"/documentation/authenticationservices/ascosealgorithmidentifier"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialResidentKeyPreference"}],"type":"topic","abstract":[{"text":"A structure that specifies the relying party’s preference for resident key storage.","type":"text"}],"title":"ASAuthorizationPublicKeyCredentialResidentKeyPreference","url":"/documentation/authenticationservices/asauthorizationpublickeycredentialresidentkeypreference","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialResidentKeyPreference"}],"kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters/algorithm":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"algorithm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ASCOSEAlgorithmIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@T@ASCOSEAlgorithmIdentifier"}],"type":"topic","navigatorTitle":[{"text":"algorithm","kind":"identifier"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters/algorithm","role":"symbol","title":"algorithm","url":"/documentation/authenticationservices/asauthorizationpublickeycredentialparameters/algorithm","abstract":[{"text":"The algorithm to use for negitation between the authenticator and the relying party.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"role":"symbol","kind":"symbol","title":"NSObjectProtocol","url":"/documentation/objectivec/nsobjectprotocol","abstract":[{"type":"text","text":"The group of methods that are fundamental to all Objective-C objects."}],"type":"topic","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSObjectProtocol"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEEllipticCurveIdentifier":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASCOSEEllipticCurveIdentifier"}],"abstract":[{"type":"text","text":"A structure that contains the elliptic curve identifier."}],"type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEEllipticCurveIdentifier","url":"/documentation/authenticationservices/ascoseellipticcurveidentifier","role":"symbol","title":"ASCOSEEllipticCurveIdentifier","navigatorTitle":[{"kind":"identifier","text":"ASCOSEEllipticCurveIdentifier"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters/init(algorithm:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"algorithm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ASCOSEAlgorithmIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@T@ASCOSEAlgorithmIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithAlgorithm:","kind":"identifier"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters/init(algorithm:)","role":"symbol","title":"init(algorithm:)","url":"/documentation/authenticationservices/asauthorizationpublickeycredentialparameters/init(algorithm:)","abstract":[{"text":"Creates the object with an algorithm.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCopying"}],"title":"NSCopying","url":"/documentation/foundation/nscopying","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialDescriptor":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPublicKeyCredentialDescriptor","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ASAuthorizationPublicKeyCredentialDescriptor","kind":"identifier"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialDescriptor","role":"symbol","title":"ASAuthorizationPublicKeyCredentialDescriptor","url":"/documentation/authenticationservices/asauthorizationpublickeycredentialdescriptor","abstract":[{"text":"An interface that defines the credential identifier.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:SQ":{"url":"/documentation/Swift/Equatable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","type":"topic","title":"Equatable"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport/allSupported":{"url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialdescriptor/transport/allsupported","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allSupported"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@ASAuthorizationSecurityKeyPublicKeyCredentialDescriptorTransport","text":"Transport"},{"kind":"text","text":"]"}],"title":"allSupported","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport/allSupported","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationAllSupportedPublicKeyCredentialDescriptorTransports"}],"abstract":[{"text":"An array of currently supported transport types.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"type":"topic","url":"/documentation/Swift/CustomDebugStringConvertible","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"title":"CustomDebugStringConvertible"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialDescriptor":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialDescriptor"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialDescriptor"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialDescriptor","role":"symbol","title":"ASAuthorizationPlatformPublicKeyCredentialDescriptor","url":"/documentation/authenticationservices/asauthorizationplatformpublickeycredentialdescriptor","abstract":[{"type":"text","text":"An object that holds the credential."}],"kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport":{"url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialdescriptor/transport","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Transport"}],"kind":"symbol","abstract":[{"text":"A structure that defines the security key credential transport type.","type":"text"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Transport"}],"title":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor.Transport"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"url":"/documentation/Swift/CustomStringConvertible","abstract":[{"type":"text","text":"A type with a customized textual representation."}],"title":"CustomStringConvertible","type":"topic","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}]},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"abstract":[{"text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.","type":"text"}],"title":"CVarArg","url":"/documentation/Swift/CVarArg","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"role":"symbol","type":"topic","abstract":[{"text":"A protocol that enables an object to be encoded and decoded for archiving and distribution.","type":"text"}],"title":"NSCoding","url":"/documentation/foundation/nscoding","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"type":"topic","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","url":"/documentation/Swift/Sendable","kind":"symbol","title":"Sendable","role":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","kind":"identifier"}],"title":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","url":"/documentation/authenticationservices/asauthorizationsecuritykeypublickeycredentialdescriptor","abstract":[{"text":"An object that holds public key credential transport information.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"url":"/documentation/objectivec/nsobject","role":"symbol","kind":"symbol","type":"topic","title":"NSObject","abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}],"fragments":[{"text":"class ","kind":"text"},{"text":"NSObject","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference":{"type":"topic","navigatorTitle":[{"text":"ASAuthorizationPublicKeyCredentialUserVerificationPreference","kind":"identifier"}],"url":"/documentation/authenticationservices/asauthorizationpublickeycredentialuserverificationpreference","kind":"symbol","abstract":[{"text":"A structure that defines the relying party’s user verification preference.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationPublicKeyCredentialUserVerificationPreference","kind":"identifier"}],"title":"ASAuthorizationPublicKeyCredentialUserVerificationPreference","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference","role":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"role":"symbol","title":"Hashable","url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"12.0","beta":false,"unavailable":false,"deprecated":false,"name":"macOS"},{"introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Class"},{"op":"replace","path":"/metadata/title","value":"ASAuthorizationPublicKeyCredentialParameters"},{"op":"replace","path":"/metadata/symbolKind","value":"class"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"ASAuthorizationPublicKeyCredentialParameters","kind":"identifier"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"text":"ASAuthorizationPublicKeyCredentialParameters","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices"]]}},{"op":"replace","path":"/topicSections","value":[{"title":"Getting the parameters","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters/init(algorithm:)","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialParameters/algorithm"],"anchor":"Getting-the-parameters"}]},{"op":"replace","path":"/relationshipsSections","value":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Request configuration","anchor":"Request-configuration","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredential","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEAlgorithmIdentifier","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCOSEEllipticCurveIdentifier","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialAttestationKind","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialResidentKeyPreference","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialUserVerificationPreference","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialDescriptor","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialDescriptor","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/Transport/allSupported"],"generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialParameters"},{"kind":"text","text":" : "},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}},{"value":"ASPublicKeyCredential","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPublicKeyCredential/title","op":"replace"},{"value":[{"kind":"identifier","text":"ASPublicKeyCredential"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPublicKeyCredential/fragments","op":"replace"},{"value":[{"text":"ASPublicKeyCredential","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPublicKeyCredential/navigatorTitle","op":"replace"},{"value":"ASAuthorizationPublicKeyCredentialParameters","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialParameters/title","op":"replace"},{"value":[{"text":"ASAuthorizationPublicKeyCredentialParameters","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialParameters/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialParameters"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialParameters/navigatorTitle","op":"replace"},{"value":"ASAuthorizationPublicKeyCredentialAttestationKind","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialAttestationKind/title","op":"replace"},{"value":[{"text":"ASAuthorizationPublicKeyCredentialAttestationKind","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialAttestationKind/fragments","op":"replace"},{"value":[{"text":"ASAuthorizationPublicKeyCredentialAttestationKind","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialAttestationKind/navigatorTitle","op":"replace"},{"op":"replace","value":"ASCOSEAlgorithmIdentifier","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEAlgorithmIdentifier/title"},{"op":"replace","value":[{"kind":"identifier","text":"ASCOSEAlgorithmIdentifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEAlgorithmIdentifier/fragments"},{"op":"replace","value":[{"text":"ASCOSEAlgorithmIdentifier","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEAlgorithmIdentifier/navigatorTitle"},{"op":"replace","value":"ASAuthorizationPublicKeyCredentialResidentKeyPreference","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference/title"},{"op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialResidentKeyPreference"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialResidentKeyPreference"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialResidentKeyPreference/navigatorTitle"},{"op":"replace","value":"algorithm","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialParameters~1algorithm/title"},{"op":"replace","value":[{"kind":"identifier","text":"algorithm"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialParameters~1algorithm/fragments"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"op":"replace","value":"ASCOSEEllipticCurveIdentifier","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEEllipticCurveIdentifier/title"},{"op":"replace","value":[{"kind":"identifier","text":"ASCOSEEllipticCurveIdentifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEEllipticCurveIdentifier/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ASCOSEEllipticCurveIdentifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCOSEEllipticCurveIdentifier/navigatorTitle"},{"op":"replace","value":"initWithAlgorithm:","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialParameters~1init(algorithm:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAlgorithm:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialParameters~1init(algorithm:)/fragments"},{"op":"replace","value":"ASAuthorizationPublicKeyCredentialDescriptor","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialDescriptor/title"},{"op":"replace","value":[{"text":"ASAuthorizationPublicKeyCredentialDescriptor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialDescriptor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationPublicKeyCredentialDescriptor"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialDescriptor/navigatorTitle"},{"op":"replace","value":"ASAuthorizationAllSupportedPublicKeyCredentialDescriptorTransports","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1Transport~1allSupported/title"},{"op":"replace","value":[{"text":"ASAuthorizationAllSupportedPublicKeyCredentialDescriptorTransports","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1Transport~1allSupported/fragments"},{"op":"replace","value":"ASAuthorizationPlatformPublicKeyCredentialDescriptor","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialDescriptor/title"},{"op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialDescriptor"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialDescriptor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationPlatformPublicKeyCredentialDescriptor"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialDescriptor/navigatorTitle"},{"op":"replace","value":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptorTransport","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1Transport/title"},{"op":"replace","value":[{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptorTransport","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1Transport/fragments"},{"op":"replace","value":[{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptorTransport","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor~1Transport/navigatorTitle"},{"op":"replace","value":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/title"},{"op":"replace","value":[{"text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor/navigatorTitle"},{"op":"replace","value":"ASAuthorizationPublicKeyCredentialUserVerificationPreference","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialUserVerificationPreference/title"},{"op":"replace","value":[{"text":"ASAuthorizationPublicKeyCredentialUserVerificationPreference","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialUserVerificationPreference/fragments"},{"op":"replace","value":[{"text":"ASAuthorizationPublicKeyCredentialUserVerificationPreference","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialUserVerificationPreference/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}