{
  "abstract": [
    {
      "text": "A class to manage exporting credentials.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:22AuthenticationServices25ASCredentialExportManagerC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ASCredentialExportManager"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ASCredentialExportManager"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.2",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ASCredentialExportManager"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASCredentialExportManager"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "ASCredentialExportManager",
              "type": "codeVoice"
            },
            {
              "text": " allows your app to exchange authentication credentials like passwords and passkeys with other apps. Participating apps such as password managers can receive your exported credentials by using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialImportManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-your-app",
          "level": 3,
          "text": "Configure your app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To participate in credential exchange, edit your credential provider extension’s Info.plist and add the following key with a Boolean value of ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "NSExtension > NSExtensionAttributes > ASCredentialProviderExtensionCapabilities > SupportsCredentialExchange",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For iOS 18.2, visionOS 2.2, and macOS 15.2, you also need to explicitly enable credential exchange, like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In iOS or visionOS, open the Settings app and enable the Settings > Developer > Credential Exchange switch.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In macOS, enter the following command in Terminal:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "code": "defaults write com.apple.AuthenticationServices.Developer CredentialExchangeEnabled -bool YES",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Export-credentials",
          "level": 3,
          "text": "Export credentials",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To export credentials, your app’s interface needs to allow the person using it to select the credentials they want to export.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To begin the process, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager/exportCredentials(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on an instance of this class.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Calling this method brings up an out-of-process system UI that guides the person through the export procedure.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The system UI explains the risks of exporting credentials, and then allows them to choose an app to export to.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The operating system acts as an intermediary to establish the identities of the password manager apps involved and performs the exchange; this process doesn’t write any data to the file system.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When a person chooses an importer app, the system launches it, sending the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "ASCredentialExchangeActivity",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The importing app responds to the launch activity by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialImportManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialImportManager/importCredentials(token:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to receive the exported credentials.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example shows how to perform an export from a SwiftUI view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct CredentialExportManagerExample: View {",
            "    @Environment(\\.credentialExportManager) private var credentialExportManager",
            "",
            "    var body: some View {",
            "        Button(\"Export Credentials\") {",
            "            Task {",
            "                do {",
            "                    let credentialData = getCredentialData() // defined elsewhere",
            "                    try await credentialExportManager.exportCredentials(credentialData)",
            "                } catch {",
            "                    // Handle the export error.",
            "                }",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For a corresponding import code example, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialImportManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager": {
      "abstract": [
        {
          "text": "A class to manage exporting credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASCredentialExportManager"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASCredentialExportManager"
        }
      ],
      "role": "symbol",
      "title": "ASCredentialExportManager",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialexportmanager"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager/exportCredentials(_:)": {
      "abstract": [
        {
          "text": "Begins the credential export process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exportCredentials"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22AuthenticationServices24ASExportedCredentialDataV",
          "text": "ASExportedCredentialData"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager/exportCredentials(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "exportCredentials(_:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialexportmanager/exportcredentials(_:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager/init(presentationAnchor:)-56ki6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "presentationAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASPresentationAnchor",
          "text": "ASPresentationAnchor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager/init(presentationAnchor:)-56ki6",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(presentationAnchor:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialexportmanager/init(presentationanchor:)-56ki6"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager/init(presentationAnchor:)-904gt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "presentationAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASPresentationAnchor",
          "text": "ASPresentationAnchor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager/init(presentationAnchor:)-904gt",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(presentationAnchor:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialexportmanager/init(presentationanchor:)-904gt"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialImportManager": {
      "abstract": [
        {
          "text": "A class to manage importing credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASCredentialImportManager"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialImportManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASCredentialImportManager"
        }
      ],
      "role": "symbol",
      "title": "ASCredentialImportManager",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialimportmanager"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialImportManager/importCredentials(token:)": {
      "abstract": [
        {
          "text": "Begins the credential import process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "importCredentials"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22AuthenticationServices24ASExportedCredentialDataV",
          "text": "ASExportedCredentialData"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialImportManager/importCredentials(token:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "importCredentials(token:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialimportmanager/importcredentials(token:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExportedCredentialData": {
      "abstract": [
        {
          "text": "A container for credential data that your app provides to an exporter or receives from an importer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASExportedCredentialData"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExportedCredentialData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASExportedCredentialData"
        }
      ],
      "role": "symbol",
      "title": "ASExportedCredentialData",
      "type": "topic",
      "url": "/documentation/authenticationservices/asexportedcredentialdata"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPresentationAnchor": {
      "abstract": [
        {
          "text": "A platform-specific type that indicates the kind of user interface element to use as a presentation anchor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASPresentationAnchor"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPresentationAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASPresentationAnchor"
        }
      ],
      "role": "symbol",
      "title": "ASPresentationAnchor",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspresentationanchor"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity": {
      "abstract": [
        {
          "text": "A representation of the state of your app at a moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivity",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Credential-migration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialImportManager"
      ],
      "title": "Credential migration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-export-manager",
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPresentationAnchor"
      ],
      "title": "Creating an export manager"
    },
    {
      "anchor": "Exporting-credentials",
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager/exportCredentials(_:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExportedCredentialData"
      ],
      "title": "Exporting credentials"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager/init(presentationAnchor:)-56ki6",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialExportManager/init(presentationAnchor:)-904gt"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPresentationAnchor/title",
          "value": "ASPresentationAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPresentationAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPresentationAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPresentationAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPresentationAnchor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/ascredentialexportmanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
