{
  "abstract": [
    {
      "text": "A passkey assertion credential.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ASPasskeyAssertionCredential",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ASPasskeyAssertionCredential"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ASPasskeyAssertionCredential"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ASPasskeyAssertionCredential"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASPasskeyAssertionCredential"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create a passkey assertion credential to provide a response to a passkey authentication challenge from your credential provider extension. Call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeAssertionRequest(using:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", passing your passkey assertion credential.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationCredential": {
      "abstract": [
        {
          "text": "An interface that all credentials share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationCredential"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationCredential"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationCredential",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationcredential"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeAssertionRequest(using:completionHandler:)": {
      "abstract": [
        {
          "text": "Complete the passkey assertion request by providing the user-selected passkey credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completeAssertionRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasskeyAssertionCredential",
          "text": "ASPasskeyAssertionCredential"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeAssertionRequest(using:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completeAssertionRequestWithSelectedPasskeyCredential:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "completeAssertionRequest(using:completionHandler:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderextensioncontext/completeassertionrequest(using:completionhandler:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeOneTimeCodeRequest(using:completionHandler:)": {
      "abstract": [
        {
          "text": "Provides the user-selected one-time passcode (OTP).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completeOneTimeCodeRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASOneTimeCodeCredential",
          "text": "ASOneTimeCodeCredential"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeOneTimeCodeRequest(using:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completeOneTimeCodeRequestWithSelectedCredential:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "completeOneTimeCodeRequest(using:completionHandler:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderextensioncontext/completeonetimecoderequest(using:completionhandler:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRegistrationRequest(using:completionHandler:)": {
      "abstract": [
        {
          "text": "Complete the registration request by providing the newly-created passkey credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completeRegistrationRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasskeyRegistrationCredential",
          "text": "ASPasskeyRegistrationCredential"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRegistrationRequest(using:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completeRegistrationRequestWithSelectedPasskeyCredential:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "completeRegistrationRequest(using:completionHandler:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderextensioncontext/completeregistrationrequest(using:completionhandler:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRequest(withSelectedCredential:completionHandler:)": {
      "abstract": [
        {
          "text": "Provides the user-selected credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completeRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withSelectedCredential"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasswordCredential",
          "text": "ASPasswordCredential"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRequest(withSelectedCredential:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completeRequestWithSelectedCredential:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "completeRequest(withSelectedCredential:completionHandler:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderextensioncontext/completerequest(withselectedcredential:completionhandler:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASOneTimeCodeCredential": {
      "abstract": [
        {
          "text": "A one-time passcode (OTP) credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASOneTimeCodeCredential"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASOneTimeCodeCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASOneTimeCodeCredential"
        }
      ],
      "role": "symbol",
      "title": "ASOneTimeCodeCredential",
      "type": "topic",
      "url": "/documentation/authenticationservices/asonetimecodecredential"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential": {
      "abstract": [
        {
          "text": "A passkey assertion credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASPasskeyAssertionCredential"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASPasskeyAssertionCredential"
        }
      ],
      "role": "symbol",
      "title": "ASPasskeyAssertionCredential",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/authenticatorData": {
      "abstract": [
        {
          "text": "The authenticator data of the application that created this passkey assertion credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticatorData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/authenticatorData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authenticatorData"
        }
      ],
      "role": "symbol",
      "title": "authenticatorData",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/authenticatordata"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/clientDataHash": {
      "abstract": [
        {
          "text": "A hash of the client data for this credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/clientDataHash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientDataHash"
        }
      ],
      "role": "symbol",
      "title": "clientDataHash",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/clientdatahash"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/credentialID": {
      "abstract": [
        {
          "text": "The identifier for this credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credentialID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/credentialID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "credentialID"
        }
      ],
      "role": "symbol",
      "title": "credentialID",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/credentialid"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/credentialWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:": {
      "abstract": [
        {
          "text": "Creates and initializes a new passkey assertion credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "credentialWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/credentialWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "credentialWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:"
        }
      ],
      "role": "symbol",
      "title": "credentialWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/credentialwithuserhandle:relyingparty:signature:clientdatahash:authenticatordata:credentialid:"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/extensionOutput-46ib3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "extensionOutput"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/extensionOutput-46ib3",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensionOutput",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/extensionoutput-46ib3"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/extensionOutput-7t6rn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22AuthenticationServices43ASPasskeyAssertionCredentialExtensionOutputV",
          "text": "ASPasskeyAssertionCredentialExtensionOutput"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/extensionOutput-7t6rn",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensionOutput",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/extensionoutput-7t6rn"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:)": {
      "abstract": [
        {
          "text": "Initializes a passkey assertion credential object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "userHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relyingParty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "signature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "authenticatorData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "credentialID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:"
        }
      ],
      "role": "symbol",
      "title": "init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/init(userhandle:relyingparty:signature:clientdatahash:authenticatordata:credentialid:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:extensionOutput:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "userHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relyingParty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "signature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "authenticatorData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "credentialID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "extensionOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22AuthenticationServices43ASPasskeyAssertionCredentialExtensionOutputV",
          "text": "ASPasskeyAssertionCredentialExtensionOutput"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:extensionOutput:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:extensionOutput:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/init(userhandle:relyingparty:signature:clientdatahash:authenticatordata:credentialid:extensionoutput:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/initWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:extensionOutput:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:extensionOutput:"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/initWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:extensionOutput:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:extensionOutput:"
        }
      ],
      "role": "symbol",
      "title": "initWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:extensionOutput:",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/initwithuserhandle:relyingparty:signature:clientdatahash:authenticatordata:credentialid:extensionoutput:"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/relyingParty": {
      "abstract": [
        {
          "text": "The relying party associated with this passkey.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relyingParty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/relyingParty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "relyingParty"
        }
      ],
      "role": "symbol",
      "title": "relyingParty",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/relyingparty"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/signature": {
      "abstract": [
        {
          "text": "The cryptographic signature of this credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/signature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signature"
        }
      ],
      "role": "symbol",
      "title": "signature",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/signature"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/userHandle": {
      "abstract": [
        {
          "text": "The user handle of this passkey.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/userHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userHandle"
        }
      ],
      "role": "symbol",
      "title": "userHandle",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyassertioncredential/userhandle"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyRegistrationCredential": {
      "abstract": [
        {
          "text": "A passkey registration credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASPasskeyRegistrationCredential"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyRegistrationCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASPasskeyRegistrationCredential"
        }
      ],
      "role": "symbol",
      "title": "ASPasskeyRegistrationCredential",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeyregistrationcredential"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredential": {
      "abstract": [
        {
          "text": "A password credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASPasswordCredential"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASPasswordCredential"
        }
      ],
      "role": "symbol",
      "title": "ASPasswordCredential",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasswordcredential"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationCredential",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-credentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRequest(withSelectedCredential:completionHandler:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeAssertionRequest(using:completionHandler:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRegistrationRequest(using:completionHandler:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeOneTimeCodeRequest(using:completionHandler:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredential",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyRegistrationCredential",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASOneTimeCodeCredential"
      ],
      "title": "Providing credentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-passkey-assertion-credential",
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:)"
      ],
      "title": "Creating a passkey assertion credential"
    },
    {
      "anchor": "Accessing-credential-information",
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/authenticatorData",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/clientDataHash",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/credentialID",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/relyingParty",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/signature",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/userHandle"
      ],
      "title": "Accessing credential information"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:extensionOutput:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/extensionOutput-7t6rn"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ASPasskeyAssertionCredential"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyAssertionCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyAssertionCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-passkey-assertion-credential",
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/credentialWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:)"
              ],
              "title": "Creating a passkey assertion credential"
            },
            {
              "anchor": "Accessing-credential-information",
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/authenticatorData",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/clientDataHash",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/credentialID",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/relyingParty",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/signature",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/userHandle"
              ],
              "title": "Accessing credential information"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/extensionOutput-46ib3"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyAssertionCredential/initWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:extensionOutput:"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationCredential"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-credentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRequest(withSelectedCredential:completionHandler:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeAssertionRequest(using:completionHandler:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRegistrationRequest(using:completionHandler:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeOneTimeCodeRequest(using:completionHandler:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredential",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyRegistrationCredential",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASOneTimeCodeCredential"
              ],
              "title": "Providing credentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ASPasskeyAssertionCredential"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASOneTimeCodeCredential/title",
          "value": "ASOneTimeCodeCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASOneTimeCodeCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASOneTimeCodeCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASOneTimeCodeCredential/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASOneTimeCodeCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationCredential/title",
          "value": "ASAuthorizationCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationCredential/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1signature/title",
          "value": "signature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1signature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyRegistrationCredential/title",
          "value": "ASPasskeyRegistrationCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyRegistrationCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyRegistrationCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyRegistrationCredential/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyRegistrationCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1clientDataHash/title",
          "value": "clientDataHash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1clientDataHash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clientDataHash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1relyingParty/title",
          "value": "relyingParty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1relyingParty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relyingParty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeRequest(withSelectedCredential:completionHandler:)/title",
          "value": "completeRequestWithSelectedCredential:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeRequest(withSelectedCredential:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "completeRequestWithSelectedCredential:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1userHandle/title",
          "value": "userHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1userHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1authenticatorData/title",
          "value": "authenticatorData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1authenticatorData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authenticatorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeRegistrationRequest(using:completionHandler:)/title",
          "value": "completeRegistrationRequestWithSelectedPasskeyCredential:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeRegistrationRequest(using:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "completeRegistrationRequestWithSelectedPasskeyCredential:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential/title",
          "value": "ASPasskeyAssertionCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyAssertionCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyAssertionCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeOneTimeCodeRequest(using:completionHandler:)/title",
          "value": "completeOneTimeCodeRequestWithSelectedCredential:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeOneTimeCodeRequest(using:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "completeOneTimeCodeRequestWithSelectedCredential:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:)/title",
          "value": "initWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1init(userHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithUserHandle:relyingParty:signature:clientDataHash:authenticatorData:credentialID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasswordCredential/title",
          "value": "ASPasswordCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasswordCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasswordCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasswordCredential/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasswordCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeAssertionRequest(using:completionHandler:)/title",
          "value": "completeAssertionRequestWithSelectedPasskeyCredential:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeAssertionRequest(using:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "completeAssertionRequestWithSelectedPasskeyCredential:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1credentialID/title",
          "value": "credentialID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyAssertionCredential~1credentialID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "credentialID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/aspasskeyassertioncredential"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/aspasskeyassertioncredential"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
