{
  "abstract": [
    {
      "text": "A class that represents a request to supply a passkey credential.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ASPasskeyCredentialRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ASPasskeyCredentialRequest"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ASPasskeyCredentialRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ASPasskeyCredentialRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistrationRequest": {
      "abstract": [
        {
          "text": "An interface that defines properties for a credential registration request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialRegistrationRequest"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistrationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialRegistrationRequest"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationPublicKeyCredentialRegistrationRequest",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationpublickeycredentialregistrationrequest"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/performWithoutUserInteractionIfPossible(passkeyRegistration:)": {
      "abstract": [
        {
          "text": "Perform a conditional passkey registration, if possible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performWithoutUserInteractionIfPossible"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "passkeyRegistration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialRequest",
          "text": "ASPasskeyCredentialRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/performWithoutUserInteractionIfPossible(passkeyRegistration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performPasskeyRegistrationWithoutUserInteractionIfPossible:"
        }
      ],
      "role": "symbol",
      "title": "performWithoutUserInteractionIfPossible(passkeyRegistration:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller/performwithoutuserinteractionifpossible(passkeyregistration:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareCredentialList(for:)": {
      "abstract": [
        {
          "text": "Prepares the interface to display a list of credentials from which the user can select.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareCredentialList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASCredentialServiceIdentifier",
          "text": "ASCredentialServiceIdentifier"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareCredentialList(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareCredentialListForServiceIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "prepareCredentialList(for:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller/preparecredentiallist(for:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareCredentialList(for:requestParameters:)": {
      "abstract": [
        {
          "text": "Prepares the interface to display a list of passkey and password credentials from which the user can select.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareCredentialList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASCredentialServiceIdentifier",
          "text": "ASCredentialServiceIdentifier"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "requestParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialRequestParameters",
          "text": "ASPasskeyCredentialRequestParameters"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareCredentialList(for:requestParameters:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareCredentialListForServiceIdentifiers:requestParameters:"
        }
      ],
      "role": "symbol",
      "title": "prepareCredentialList(for:requestParameters:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller/preparecredentiallist(for:requestparameters:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterface(forPasskeyRegistration:)": {
      "abstract": [
        {
          "text": "Prepare the view controller to show user interface for registering a new passkey.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forPasskeyRegistration"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)ASCredentialRequest",
          "text": "ASCredentialRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterface(forPasskeyRegistration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareInterfaceForPasskeyRegistration:"
        }
      ],
      "role": "symbol",
      "title": "prepareInterface(forPasskeyRegistration:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller/prepareinterface(forpasskeyregistration:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterfaceToProvideCredential(for:)-68qpo": {
      "abstract": [
        {
          "text": "Prepare the view controller to show user interface for providing the requested credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareInterfaceToProvideCredential"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)ASCredentialRequest",
          "text": "ASCredentialRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterfaceToProvideCredential(for:)-68qpo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareInterfaceToProvideCredentialForRequest:"
        }
      ],
      "role": "symbol",
      "title": "prepareInterfaceToProvideCredential(for:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller/prepareinterfacetoprovidecredential(for:)-68qpo"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareOneTimeCodeCredentialList(for:)": {
      "abstract": [
        {
          "text": "Prepares the interface to display a list of one-time passcodes (OTPs) that people can select from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareOneTimeCodeCredentialList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASCredentialServiceIdentifier",
          "text": "ASCredentialServiceIdentifier"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareOneTimeCodeCredentialList(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareOneTimeCodeCredentialListForServiceIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "prepareOneTimeCodeCredentialList(for:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller/prepareonetimecodecredentiallist(for:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/provideCredentialWithoutUserInteraction(for:)-3mo23": {
      "abstract": [
        {
          "text": "Attempts to provide the user-requested credential with no further user interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provideCredentialWithoutUserInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)ASCredentialRequest",
          "text": "ASCredentialRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/provideCredentialWithoutUserInteraction(for:)-3mo23",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provideCredentialWithoutUserInteractionForRequest:"
        }
      ],
      "role": "symbol",
      "title": "provideCredentialWithoutUserInteraction(for:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller/providecredentialwithoutuserinteraction(for:)-3mo23"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialRequest": {
      "abstract": [
        {
          "text": "A protocol that describes a request from the user for your extension to provide a credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASCredentialRequest"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASCredentialRequest"
        }
      ],
      "role": "symbol",
      "title": "ASCredentialRequest",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialrequest"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialServiceIdentifier": {
      "abstract": [
        {
          "text": "An identifier representing a particular service for which the user needs a credential, like a web site.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASCredentialServiceIdentifier"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialServiceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASCredentialServiceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "ASCredentialServiceIdentifier",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialserviceidentifier"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASOneTimeCodeCredentialRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASOneTimeCodeCredentialRequest"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASOneTimeCodeCredentialRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASOneTimeCodeCredentialRequest"
        }
      ],
      "role": "symbol",
      "title": "ASOneTimeCodeCredentialRequest",
      "type": "topic",
      "url": "/documentation/authenticationservices/asonetimecodecredentialrequest"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest": {
      "abstract": [
        {
          "text": "A class that represents a request to supply a passkey credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASPasskeyCredentialRequest"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASPasskeyCredentialRequest"
        }
      ],
      "role": "symbol",
      "title": "ASPasskeyCredentialRequest",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/assertionExtensionInput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "assertionExtensionInput"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/assertionExtensionInput",
      "kind": "symbol",
      "role": "symbol",
      "title": "assertionExtensionInput",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/assertionextensioninput"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/clientDataHash": {
      "abstract": [
        {
          "text": "The hash of the client data for this assertion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/clientDataHash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientDataHash"
        }
      ],
      "role": "symbol",
      "title": "clientDataHash",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/clientdatahash"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/excludedCredentials": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excludedCredentials"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASAuthorizationPlatformPublicKeyCredentialDescriptor",
          "text": "ASAuthorizationPlatformPublicKeyCredentialDescriptor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/excludedCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "excludedCredentials"
        }
      ],
      "role": "symbol",
      "title": "excludedCredentials",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/excludedcredentials"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/extensionInput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22AuthenticationServices33ASPasskeyCredentialExtensionInputO",
          "text": "ASPasskeyCredentialExtensionInput"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/extensionInput",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensionInput",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/extensioninput"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy": {
      "abstract": [
        {
          "text": "Initializes a passkey credential request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "credentialIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialIdentity",
          "text": "ASPasskeyCredentialIdentity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userVerificationPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialUserVerificationPreference",
          "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "supportedAlgorithms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
        }
      ],
      "role": "symbol",
      "title": "init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/init(credentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:)-1jihy"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-52txr": {
      "abstract": [
        {
          "text": "Initializes a passkey credential request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "credentialIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialIdentity",
          "text": "ASPasskeyCredentialIdentity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userVerificationPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialUserVerificationPreference",
          "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "supportedAlgorithms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASCOSEAlgorithmIdentifier",
          "text": "ASCOSEAlgorithmIdentifier"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-52txr",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/init(credentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:)-52txr"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:extensionInput:)-1258o": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "credentialIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialIdentity",
          "text": "ASPasskeyCredentialIdentity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userVerificationPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialUserVerificationPreference",
          "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "supportedAlgorithms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASCOSEAlgorithmIdentifier",
          "text": "ASCOSEAlgorithmIdentifier"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "extensionInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22AuthenticationServices45ASPasskeyRegistrationCredentialExtensionInputV",
          "text": "ASPasskeyRegistrationCredentialExtensionInput"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:extensionInput:)-1258o",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:extensionInput:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/init(credentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:extensioninput:)-1258o"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:extensionInput:)-9hsyv": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "credentialIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASPasskeyCredentialIdentity",
          "text": "ASPasskeyCredentialIdentity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userVerificationPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialUserVerificationPreference",
          "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "supportedAlgorithms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASCOSEAlgorithmIdentifier",
          "text": "ASCOSEAlgorithmIdentifier"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "extensionInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22AuthenticationServices42ASPasskeyAssertionCredentialExtensionInputV",
          "text": "ASPasskeyAssertionCredentialExtensionInput"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:extensionInput:)-9hsyv",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:extensionInput:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/init(credentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:extensioninput:)-9hsyv"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:": {
      "abstract": [
        {
          "text": "Initializes a passkey credential request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
        }
      ],
      "role": "symbol",
      "title": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/initwithcredentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:assertionExtensionInput:": {
      "abstract": [
        {
          "text": "Initializes an instance of ASPasskeyCredentialRequest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:assertionExtensionInput:"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:assertionExtensionInput:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:assertionExtensionInput:"
        }
      ],
      "role": "symbol",
      "title": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:assertionExtensionInput:",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/initwithcredentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:assertionextensioninput:"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:registrationExtensionInput:": {
      "abstract": [
        {
          "text": "Initializes an instance of ASPasskeyCredentialRequest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:registrationExtensionInput:"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:registrationExtensionInput:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:registrationExtensionInput:"
        }
      ],
      "role": "symbol",
      "title": "initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:registrationExtensionInput:",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/initwithcredentialidentity:clientdatahash:userverificationpreference:supportedalgorithms:registrationextensioninput:"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/registrationExtensionInput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "registrationExtensionInput"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/registrationExtensionInput",
      "kind": "symbol",
      "role": "symbol",
      "title": "registrationExtensionInput",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/registrationextensioninput"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/supportedAlgorithms-27z68": {
      "abstract": [
        {
          "text": "A list of cryptographic signature algorithms that the relying party supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "supportedAlgorithms"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/supportedAlgorithms-27z68",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedAlgorithms",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/supportedalgorithms-27z68"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/supportedAlgorithms-74mad": {
      "abstract": [
        {
          "text": "A list of cryptographic signature algorithms that the relying party supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedAlgorithms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASCOSEAlgorithmIdentifier",
          "text": "ASCOSEAlgorithmIdentifier"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/supportedAlgorithms-74mad",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedAlgorithms",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/supportedalgorithms-74mad"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/userVerificationPreference": {
      "abstract": [
        {
          "text": "The relying party’s user verification preference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userVerificationPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASAuthorizationPublicKeyCredentialUserVerificationPreference",
          "text": "ASAuthorizationPublicKeyCredentialUserVerificationPreference"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/userVerificationPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userVerificationPreference"
        }
      ],
      "role": "symbol",
      "title": "userVerificationPreference",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequest/userverificationpreference"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequestParameters": {
      "abstract": [
        {
          "text": "A class that represents information about a passkey credential request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASPasskeyCredentialRequestParameters"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequestParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASPasskeyCredentialRequestParameters"
        }
      ],
      "role": "symbol",
      "title": "ASPasskeyCredentialRequestParameters",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasskeycredentialrequestparameters"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredentialRequest": {
      "abstract": [
        {
          "text": "A class that represents a request to supply a password credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASPasswordCredentialRequest"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredentialRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASPasswordCredentialRequest"
        }
      ],
      "role": "symbol",
      "title": "ASPasswordCredentialRequest",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspasswordcredentialrequest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialRequest",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selecting-a-credential",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareCredentialList(for:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareCredentialList(for:requestParameters:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareOneTimeCodeCredentialList(for:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterface(forPasskeyRegistration:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterfaceToProvideCredential(for:)-68qpo",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/provideCredentialWithoutUserInteraction(for:)-3mo23",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/performWithoutUserInteractionIfPossible(passkeyRegistration:)",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialServiceIdentifier",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialRequest",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredentialRequest",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASOneTimeCodeCredentialRequest",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistrationRequest",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequestParameters"
      ],
      "title": "Selecting a credential"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-passkey-credential-requests",
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-52txr"
      ],
      "title": "Creating passkey credential requests"
    },
    {
      "anchor": "Viewing-passkey-challenge-information",
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/clientDataHash",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/userVerificationPreference",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/supportedAlgorithms-74mad"
      ],
      "title": "Viewing passkey challenge information"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:extensionInput:)-1258o",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:extensionInput:)-9hsyv"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/excludedCredentials",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/extensionInput"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ASPasskeyCredentialRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-passkey-credential-requests",
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
              ],
              "title": "Creating passkey credential requests"
            },
            {
              "anchor": "Viewing-passkey-challenge-information",
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/clientDataHash",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/userVerificationPreference",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/supportedAlgorithms-27z68"
              ],
              "title": "Viewing passkey challenge information"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/assertionExtensionInput",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/excludedCredentials",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/registrationExtensionInput"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:assertionExtensionInput:",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequest/initWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:registrationExtensionInput:"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialRequest"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selecting-a-credential",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareCredentialList(for:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareCredentialList(for:requestParameters:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareOneTimeCodeCredentialList(for:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterface(forPasskeyRegistration:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterfaceToProvideCredential(for:)-68qpo",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/provideCredentialWithoutUserInteraction(for:)-3mo23",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/performWithoutUserInteractionIfPossible(passkeyRegistration:)",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialServiceIdentifier",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialRequest",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredentialRequest",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASOneTimeCodeCredentialRequest",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialRegistrationRequest",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialRequestParameters"
              ],
              "title": "Selecting a credential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ASPasskeyCredentialRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialServiceIdentifier/title",
          "value": "ASCredentialServiceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialServiceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASCredentialServiceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialServiceIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASCredentialServiceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasswordCredentialRequest/title",
          "value": "ASPasswordCredentialRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasswordCredentialRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasswordCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasswordCredentialRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasswordCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequestParameters/title",
          "value": "ASPasskeyCredentialRequestParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequestParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialRequestParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequestParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialRequestParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1performWithoutUserInteractionIfPossible(passkeyRegistration:)/title",
          "value": "performPasskeyRegistrationWithoutUserInteractionIfPossible:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1performWithoutUserInteractionIfPossible(passkeyRegistration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performPasskeyRegistrationWithoutUserInteractionIfPossible:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareOneTimeCodeCredentialList(for:)/title",
          "value": "prepareOneTimeCodeCredentialListForServiceIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareOneTimeCodeCredentialList(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareOneTimeCodeCredentialListForServiceIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASOneTimeCodeCredentialRequest/title",
          "value": "ASOneTimeCodeCredentialRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASOneTimeCodeCredentialRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASOneTimeCodeCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASOneTimeCodeCredentialRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASOneTimeCodeCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareCredentialList(for:requestParameters:)/title",
          "value": "prepareCredentialListForServiceIdentifiers:requestParameters:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareCredentialList(for:requestParameters:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareCredentialListForServiceIdentifiers:requestParameters:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest~1excludedCredentials/title",
          "value": "excludedCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest~1excludedCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "excludedCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareCredentialList(for:)/title",
          "value": "prepareCredentialListForServiceIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareCredentialList(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareCredentialListForServiceIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialRegistrationRequest/title",
          "value": "ASAuthorizationPublicKeyCredentialRegistrationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialRegistrationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPublicKeyCredentialRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPublicKeyCredentialRegistrationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPublicKeyCredentialRegistrationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest~1init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy/title",
          "value": "requestWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest~1init(credentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:)-1jihy/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestWithCredentialIdentity:clientDataHash:userVerificationPreference:supportedAlgorithms:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest~1userVerificationPreference/title",
          "value": "userVerificationPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest~1userVerificationPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userVerificationPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialRequest/title",
          "value": "ASCredentialRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest~1clientDataHash/title",
          "value": "clientDataHash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest~1clientDataHash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clientDataHash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1provideCredentialWithoutUserInteraction(for:)-3mo23/title",
          "value": "provideCredentialWithoutUserInteractionForRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1provideCredentialWithoutUserInteraction(for:)-3mo23/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provideCredentialWithoutUserInteractionForRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareInterfaceToProvideCredential(for:)-68qpo/title",
          "value": "prepareInterfaceToProvideCredentialForRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareInterfaceToProvideCredential(for:)-68qpo/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareInterfaceToProvideCredentialForRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareInterface(forPasskeyRegistration:)/title",
          "value": "prepareInterfaceForPasskeyRegistration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareInterface(forPasskeyRegistration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareInterfaceForPasskeyRegistration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest/title",
          "value": "ASPasskeyCredentialRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASPasskeyCredentialRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/aspasskeycredentialrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/aspasskeycredentialrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
