{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authenticationservices-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AuthenticationServices Data Types"
  },
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ASImage"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASImage",
      "type": "topic",
      "url": "/documentation/authenticationservices/asimage"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ASViewController"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASViewController",
      "type": "topic",
      "url": "/documentation/authenticationservices/asviewcontroller"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authenticationservices-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authenticationservices-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AuthenticationServices Enumerations",
      "type": "topic",
      "url": "/documentation/authenticationservices/authenticationservices-enumerations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authenticationservices-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASImage",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASViewController"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authenticationservices-enumerations"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/authenticationservices-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/authenticationservices-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
