{
  "abstract": [
    {
      "text": "Request and process a server nonce to verify communication and detect replays.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/platform-single-sign-on-sso",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authentication-process"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/obtaining-a-server-nonce"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Obtaining a server nonce"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The login request, refresh request, and key requests use the server nonce so the identity provider (IdP) can verify it’s communicating to a live client. The IdP can also use the server nonce for replay detection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-the-server-nonce-network-request",
          "level": 3,
          "text": "Create the server nonce network request",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following table specifies the header parameters that the system uses to create a server nonce request:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Key",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Notes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "grant_type",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "srv_challenge",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Required.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionLoginConfiguration/customNonceRequestValues",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Optional. If present, adds the key value pairs to the request.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "client-request-id",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "UUID",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Required. A unique identifier for the request.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "The server nonce request is an HTTP POST to the login configuration ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionLoginConfiguration/nonceEndpointURL",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", as shown in the following example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "POST /oauth2/token HTTP/1.1",
            "Host: auth.example.com",
            "Accept: application/json",
            "Content-Type: application/x-www-form-urlencoded",
            "client-request-id: DCAB01D3-B1FE-4E1C-802F-B3EBDCDF9E67",
            "grant_type=srv_challenge"
          ],
          "syntax": "http",
          "type": "codeListing"
        },
        {
          "anchor": "Receive-the-server-nonce-network-response",
          "level": 3,
          "text": "Receive the server nonce network response",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the http status is ",
              "type": "text"
            },
            {
              "code": "200",
              "type": "codeVoice"
            },
            {
              "text": ", the response body loads as JSON. If the body is valid JSON, the system pulls the server nonce from the response using the login configuration ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionLoginConfiguration/nonceResponseKeypath",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or the default value ",
              "type": "text"
            },
            {
              "code": "Nonce",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Platform SSO doesn’t validate the token and treats it as an opaque value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionLoginConfiguration/customNonceRequestValues": {
      "abstract": [
        {
          "text": "Custom values to add to the server nonce POST request body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customNonceRequestValues"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12URLQueryItemV",
          "text": "URLQueryItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionLoginConfiguration/customNonceRequestValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customNonceRequestValues"
        }
      ],
      "role": "symbol",
      "title": "customNonceRequestValues",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionloginconfiguration/customnoncerequestvalues"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionLoginConfiguration/nonceEndpointURL": {
      "abstract": [
        {
          "text": "The URL to retrieve a one-time use value from the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonceEndpointURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionLoginConfiguration/nonceEndpointURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nonceEndpointURL"
        }
      ],
      "role": "symbol",
      "title": "nonceEndpointURL",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionloginconfiguration/nonceendpointurl"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionLoginConfiguration/nonceResponseKeypath": {
      "abstract": [
        {
          "text": "The keypath in the response that contains the one-time use value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonceResponseKeypath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionLoginConfiguration/nonceResponseKeypath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nonceResponseKeypath"
        }
      ],
      "role": "symbol",
      "title": "nonceResponseKeypath",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionloginconfiguration/nonceresponsekeypath"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authentication-process": {
      "abstract": [
        {
          "text": "Use a system-supported method to authenticate with an identity provider.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authentication-process",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Authentication process",
      "type": "topic",
      "url": "/documentation/authenticationservices/authentication-process"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/performing-a-preauthentication-request": {
      "abstract": [
        {
          "text": "Request and process a preauthentication for dynamic WS-Trust authentication.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/performing-a-preauthentication-request",
      "kind": "article",
      "role": "article",
      "title": "Performing a preauthentication request",
      "type": "topic",
      "url": "/documentation/authenticationservices/performing-a-preauthentication-request"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/performing-a-ws-trust-metadata-exchange-data-mex-request": {
      "abstract": [
        {
          "text": "Send and process a WS-Trust MEX request to determine the version and URLs for authentication.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/performing-a-ws-trust-metadata-exchange-data-mex-request",
      "kind": "article",
      "role": "article",
      "title": "Performing a WS-Trust metadata exchange data (MEX) request",
      "type": "topic",
      "url": "/documentation/authenticationservices/performing-a-ws-trust-metadata-exchange-data-mex-request"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/platform-single-sign-on-sso": {
      "abstract": [
        {
          "text": "Use credentials from macOS login to perform single sign-on with an identity provider.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/platform-single-sign-on-sso",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Platform single sign-on (SSO)",
      "type": "topic",
      "url": "/documentation/authenticationservices/platform-single-sign-on-sso"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pre-login",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/performing-a-preauthentication-request",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/performing-a-ws-trust-metadata-exchange-data-mex-request"
      ],
      "title": "Pre-login"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Pre-login",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/performing-a-preauthentication-request",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/performing-a-ws-trust-metadata-exchange-data-mex-request"
              ],
              "title": "Pre-login"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionLoginConfiguration~1nonceResponseKeypath/title",
          "value": "nonceResponseKeypath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionLoginConfiguration~1nonceResponseKeypath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nonceResponseKeypath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionLoginConfiguration~1customNonceRequestValues/title",
          "value": "customNonceRequestValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionLoginConfiguration~1customNonceRequestValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customNonceRequestValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionLoginConfiguration~1nonceEndpointURL/title",
          "value": "nonceEndpointURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionLoginConfiguration~1nonceEndpointURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nonceEndpointURL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/obtaining-a-server-nonce"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/obtaining-a-server-nonce"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
