{
  "abstract": [
    {
      "text": "Help people efficiently perform multifactor authentication.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/providing-one-time-passcodes-to-autofill"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Providing one-time passcodes to AutoFill"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Many online services rely on one-time passcodes (OTPs), particularly time-based one-time passcodes (TOTP), as an additional factor when someone authenticates with the service.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, a website might ask someone to provide their username, a password which the person knows, and a TOTP generated by the person’s authenticator app to enter the site.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your credential provider extension can supply OTPs to AutoFill so that people can automatically fill out passcodes in apps and on websites.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Someone can configure multiple credential providers in Settings so that different apps supply their passwords and OTPs in AutoFill.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Indicate-that-your-extension-provides-OTPs",
          "level": 3,
          "text": "Indicate that your extension provides OTPs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Open your credential provider extension’s information property list file in Xcode and add a key to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ASCredentialProviderExtensionCapabilities",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " dictionary.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Set the key’s name to ",
              "type": "text"
            },
            {
              "code": "ProvidesOneTimeCodes",
              "type": "codeVoice"
            },
            {
              "text": ", and its value to the Boolean ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Respond-to-system-requests-for-OTP-AutoFill",
          "level": 3,
          "text": "Respond to system requests for OTP AutoFill",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system calls your credential provider view controller’s  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/provideCredentialWithoutUserInteraction(for:)-3mo23",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method with a request type of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialRequestType/oneTimeCode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to request an OTP.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If your credential provider extension can provide the code without presenting UI, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeOneTimeCodeRequest(using:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to supply the text to the system.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Otherwise, if your credential provider extension needs to present UI to provide the OTP, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/cancelRequest(withError:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use the error domain ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionErrorDomain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and the code ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userInteractionRequired",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The system calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterfaceToProvideCredential(for:)-68qpo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In your implementation, present the UI you need for someone to choose the OTP for the request.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeOneTimeCodeRequest(using:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to supply the text to the system, or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/cancelRequest(withError:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to inform the system if an error occurs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Provide-a-list-of-available-OTPs",
          "level": 3,
          "text": "Provide a list of available OTPs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When someone uses a text field to complete an OTP using AutoFill, they can tap a button to see a list of all available OTPs.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The system calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareOneTimeCodeCredentialList(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to get the list of OTPs from your extension, then presents your controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/cancelRequest(withError:)": {
      "abstract": [
        {
          "text": "Cancels the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/cancelRequest(withError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelRequestWithError:"
        }
      ],
      "role": "symbol",
      "title": "cancelRequest(withError:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderextensioncontext/cancelrequest(witherror:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeOneTimeCodeRequest(using:completionHandler:)": {
      "abstract": [
        {
          "text": "Provides the user-selected one-time passcode (OTP).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completeOneTimeCodeRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASOneTimeCodeCredential",
          "text": "ASOneTimeCodeCredential"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeOneTimeCodeRequest(using:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completeOneTimeCodeRequestWithSelectedCredential:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "completeOneTimeCodeRequest(using:completionHandler:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderextensioncontext/completeonetimecoderequest(using:completionhandler:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController": {
      "abstract": [
        {
          "text": "A view controller that a password manager app uses to extend AutoFill.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASCredentialProviderViewController"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASCredentialProviderViewController"
        }
      ],
      "role": "symbol",
      "title": "ASCredentialProviderViewController",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterfaceToProvideCredential(for:)-68qpo": {
      "abstract": [
        {
          "text": "Prepare the view controller to show user interface for providing the requested credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareInterfaceToProvideCredential"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)ASCredentialRequest",
          "text": "ASCredentialRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareInterfaceToProvideCredential(for:)-68qpo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareInterfaceToProvideCredentialForRequest:"
        }
      ],
      "role": "symbol",
      "title": "prepareInterfaceToProvideCredential(for:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller/prepareinterfacetoprovidecredential(for:)-68qpo"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareOneTimeCodeCredentialList(for:)": {
      "abstract": [
        {
          "text": "Prepares the interface to display a list of one-time passcodes (OTPs) that people can select from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareOneTimeCodeCredentialList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASCredentialServiceIdentifier",
          "text": "ASCredentialServiceIdentifier"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/prepareOneTimeCodeCredentialList(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareOneTimeCodeCredentialListForServiceIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "prepareOneTimeCodeCredentialList(for:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller/prepareonetimecodecredentiallist(for:)"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/provideCredentialWithoutUserInteraction(for:)-3mo23": {
      "abstract": [
        {
          "text": "Attempts to provide the user-requested credential with no further user interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provideCredentialWithoutUserInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)ASCredentialRequest",
          "text": "ASCredentialRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController/provideCredentialWithoutUserInteraction(for:)-3mo23",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provideCredentialWithoutUserInteractionForRequest:"
        }
      ],
      "role": "symbol",
      "title": "provideCredentialWithoutUserInteraction(for:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialproviderviewcontroller/providecredentialwithoutuserinteraction(for:)-3mo23"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialRequestType/oneTimeCode": {
      "abstract": [
        {
          "text": "The app or website is requesting a one-time passcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneTimeCode"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialRequestType/oneTimeCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASCredentialRequestTypeOneTimeCode"
        }
      ],
      "role": "symbol",
      "title": "ASCredentialRequestType.oneTimeCode",
      "type": "topic",
      "url": "/documentation/authenticationservices/ascredentialrequesttype/onetimecode"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userInteractionRequired": {
      "abstract": [
        {
          "text": "User interaction is required.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInteractionRequired"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userInteractionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASExtensionErrorCodeUserInteractionRequired"
        }
      ],
      "role": "symbol",
      "title": "ASExtensionError.Code.userInteractionRequired",
      "type": "topic",
      "url": "/documentation/authenticationservices/asextensionerror/code/userinteractionrequired"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionErrorDomain": {
      "abstract": [
        {
          "text": "The domain for a credential provider extension error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASExtensionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASExtensionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ASExtensionErrorDomain",
      "type": "topic",
      "url": "/documentation/authenticationservices/asextensionerrordomain"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.authentication-services.autofill-credential-provider": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may, with user permission, provide user names and passwords for AutoFill in Safari and other apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.authentication-services.autofill-credential-provider",
      "kind": "symbol",
      "role": "symbol",
      "title": "AutoFill Credential Provider Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.authentication-services.autofill-credential-provider"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ASCredentialProviderExtensionCapabilities": {
      "abstract": [
        {
          "text": "The credential types supported by a credential provider extension, and whether it presents a user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ASCredentialProviderExtensionCapabilities",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASCredentialProviderExtensionCapabilities",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ASCredentialProviderExtensionCapabilities"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "AutoFill-credentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.authentication-services.autofill-credential-provider",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController"
      ],
      "title": "AutoFill credentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "AutoFill-credentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.authentication-services.autofill-credential-provider",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderViewController"
              ],
              "title": "AutoFill credentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController/title",
          "value": "ASCredentialProviderViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASCredentialProviderViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASCredentialProviderViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1cancelRequest(withError:)/title",
          "value": "cancelRequestWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1cancelRequest(withError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelRequestWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareInterfaceToProvideCredential(for:)-68qpo/title",
          "value": "prepareInterfaceToProvideCredentialForRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareInterfaceToProvideCredential(for:)-68qpo/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareInterfaceToProvideCredentialForRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialRequestType~1oneTimeCode/title",
          "value": "ASCredentialRequestTypeOneTimeCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialRequestType~1oneTimeCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASCredentialRequestTypeOneTimeCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionErrorDomain/title",
          "value": "ASExtensionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASExtensionErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1provideCredentialWithoutUserInteraction(for:)-3mo23/title",
          "value": "provideCredentialWithoutUserInteractionForRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1provideCredentialWithoutUserInteraction(for:)-3mo23/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provideCredentialWithoutUserInteractionForRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareOneTimeCodeCredentialList(for:)/title",
          "value": "prepareOneTimeCodeCredentialListForServiceIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderViewController~1prepareOneTimeCodeCredentialList(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareOneTimeCodeCredentialListForServiceIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code~1userInteractionRequired/title",
          "value": "ASExtensionErrorCodeUserInteractionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code~1userInteractionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASExtensionErrorCodeUserInteractionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeOneTimeCodeRequest(using:completionHandler:)/title",
          "value": "completeOneTimeCodeRequestWithSelectedCredential:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeOneTimeCodeRequest(using:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "completeOneTimeCodeRequestWithSelectedCredential:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/providing-one-time-passcodes-to-autofill"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/providing-one-time-passcodes-to-autofill"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
