{
  "abstract": [
    {
      "text": "Creates a duration event with the specified time duration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent/init(duration:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HMDurationEvent(im)initWithDuration:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "duration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTimeInterval",
        "text": "TimeInterval"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithDuration:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(duration:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "duration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTimeInterval",
              "text": "TimeInterval"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The duration before the event ends, specified in seconds.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "duration"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An initialized duration event.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent": {
      "abstract": [
        {
          "text": "An event that ends after the specified time duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMDurationEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMDurationEvent"
        }
      ],
      "role": "symbol",
      "title": "HMDurationEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmdurationevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent/init(duration:)": {
      "abstract": [
        {
          "text": "Creates a duration event with the specified time duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent/init(duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDuration:"
        }
      ],
      "role": "symbol",
      "title": "init(duration:)",
      "type": "topic",
      "url": "/documentation/homekit/hmdurationevent/init(duration:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "TimeInterval",
      "type": "topic",
      "url": "/documentation/foundation/timeinterval"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithDuration:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithDuration:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSTimeInterval",
                    "text": "NSTimeInterval"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "duration"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The duration before the event ends, specified in seconds.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "duration"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An initialized duration event.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title",
          "value": "NSTimeInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMDurationEvent~1init(duration:)/title",
          "value": "initWithDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMDurationEvent~1init(duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMDurationEvent/title",
          "value": "HMDurationEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMDurationEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMDurationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMDurationEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMDurationEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmdurationevent/init(duration:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmdurationevent/init(duration:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
