{
  "abstract": [
    {
      "text": "The label for an Action extension’s toolbar item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarPaletteLabel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.NSExtensionAttributes.NSExtensionServiceToolbarPaletteLabel",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSExtensionServiceToolbarPaletteLabel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSExtensionServiceToolbarPaletteLabel"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSExtensionServiceToolbarPaletteLabel",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes": {
      "abstract": [
        {
          "text": "Properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes",
      "kind": "symbol",
      "name": "NSExtensionAttributes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionAttributes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsToolbarItem": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether an Action extension displays an item in a window’s toolbar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsToolbarItem",
      "kind": "symbol",
      "name": "NSExtensionServiceAllowsToolbarItem",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceAllowsToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceAllowsToolbarItem",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionserviceallowstoolbaritem"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarIconFile": {
      "abstract": [
        {
          "text": "The image for an Action extension’s toolbar item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarIconFile",
      "kind": "symbol",
      "name": "NSExtensionServiceToolbarIconFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceToolbarIconFile"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceToolbarIconFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetoolbariconfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarPaletteLabel": {
      "abstract": [
        {
          "text": "The label for an Action extension’s toolbar item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarPaletteLabel",
      "kind": "symbol",
      "name": "NSExtensionServiceToolbarPaletteLabel",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceToolbarPaletteLabel"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceToolbarPaletteLabel",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetoolbarpalettelabel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Toolbar",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsToolbarItem",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarIconFile"
      ],
      "title": "Toolbar"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSExtensionServiceToolbarPaletteLabel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceToolbarPaletteLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Toolbar",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsToolbarItem",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarIconFile"
              ],
              "title": "Toolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/title",
          "value": "NSExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceToolbarPaletteLabel/title",
          "value": "NSExtensionServiceToolbarPaletteLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceToolbarPaletteLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceToolbarPaletteLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceToolbarIconFile/title",
          "value": "NSExtensionServiceToolbarIconFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceToolbarIconFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceToolbarIconFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceAllowsToolbarItem/title",
          "value": "NSExtensionServiceAllowsToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceAllowsToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceAllowsToolbarItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetoolbarpalettelabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetoolbarpalettelabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
