{
  "abstract": [
    {
      "text": "The semantic data types that a Share or Action extension supports.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.NSExtensionAttributes.NSExtensionActivationRule",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSExtensionActivationRule"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "NSExtensionActivationRule"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSExtensionActivationRule",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the Action extension is presented in full screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
      "kind": "symbol",
      "name": "NSExtensionActionWantsFullScreenPresentation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActionWantsFullScreenPresentation"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActionWantsFullScreenPresentation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionactionwantsfullscreenpresentation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes": {
      "abstract": [
        {
          "text": "Properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes",
      "kind": "symbol",
      "name": "NSExtensionAttributes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionAttributes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule": {
      "abstract": [
        {
          "text": "The semantic data types that a Share or Action extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule",
      "kind": "symbol",
      "name": "NSExtensionActivationRule",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationRule"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationRule",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationDictionaryVersion": {
      "abstract": [
        {
          "text": "The version of the parent extension-activation rule dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationDictionaryVersion",
      "kind": "symbol",
      "name": "NSExtensionActivationDictionaryVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationDictionaryVersion"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationDictionaryVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationdictionaryversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsAttachmentsWithMaxCount": {
      "abstract": [
        {
          "text": "The maximum number of attachments that the app extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsAttachmentsWithMaxCount",
      "kind": "symbol",
      "name": "NSExtensionActivationSupportsAttachmentsWithMaxCount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationSupportsAttachmentsWithMaxCount"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationSupportsAttachmentsWithMaxCount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationsupportsattachmentswithmaxcount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsAttachmentsWithMinCount": {
      "abstract": [
        {
          "text": "The minimum number of attachments that the app extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsAttachmentsWithMinCount",
      "kind": "symbol",
      "name": "NSExtensionActivationSupportsAttachmentsWithMinCount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationSupportsAttachmentsWithMinCount"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationSupportsAttachmentsWithMinCount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationsupportsattachmentswithmincount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsFileWithMaxCount": {
      "abstract": [
        {
          "text": "The maximum number of all types of files that the app extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsFileWithMaxCount",
      "kind": "symbol",
      "name": "NSExtensionActivationSupportsFileWithMaxCount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationSupportsFileWithMaxCount"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationSupportsFileWithMaxCount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationsupportsfilewithmaxcount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsImageWithMaxCount": {
      "abstract": [
        {
          "text": "The maximum number of image files that the app extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsImageWithMaxCount",
      "kind": "symbol",
      "name": "NSExtensionActivationSupportsImageWithMaxCount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationSupportsImageWithMaxCount"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationSupportsImageWithMaxCount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationsupportsimagewithmaxcount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsMovieWithMaxCount": {
      "abstract": [
        {
          "text": "The maximum number of movie files that the app extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsMovieWithMaxCount",
      "kind": "symbol",
      "name": "NSExtensionActivationSupportsMovieWithMaxCount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationSupportsMovieWithMaxCount"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationSupportsMovieWithMaxCount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationsupportsmoviewithmaxcount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsText": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app extension supports text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsText",
      "kind": "symbol",
      "name": "NSExtensionActivationSupportsText",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationSupportsText"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationSupportsText",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationsupportstext"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsWebPageWithMaxCount": {
      "abstract": [
        {
          "text": "The maximum number of webpages that the app extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsWebPageWithMaxCount",
      "kind": "symbol",
      "name": "NSExtensionActivationSupportsWebPageWithMaxCount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationSupportsWebPageWithMaxCount"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationSupportsWebPageWithMaxCount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationsupportswebpagewithmaxcount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsWebURLWithMaxCount": {
      "abstract": [
        {
          "text": "The maximum number of HTTP URLs that the app extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsWebURLWithMaxCount",
      "kind": "symbol",
      "name": "NSExtensionActivationSupportsWebURLWithMaxCount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationSupportsWebURLWithMaxCount"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationSupportsWebURLWithMaxCount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationsupportsweburlwithmaxcount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationUsesStrictMatching": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether strict or fuzzy matching is used when determining the asset types an app extension handles.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationUsesStrictMatching",
      "kind": "symbol",
      "name": "NSExtensionActivationUsesStrictMatching",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationUsesStrictMatching"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationUsesStrictMatching",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationusesstrictmatching"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionJavaScriptPreprocessingFile": {
      "abstract": [
        {
          "text": "The name of a JavaScript file supplied by a Share or Action extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionJavaScriptPreprocessingFile",
      "kind": "symbol",
      "name": "NSExtensionJavaScriptPreprocessingFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionJavaScriptPreprocessingFile"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionJavaScriptPreprocessingFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionjavascriptpreprocessingfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard": {
      "abstract": [
        {
          "text": "The name of the app extension’s main storyboard file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
      "kind": "symbol",
      "name": "NSExtensionMainStoryboard",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionMainStoryboard"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionMainStoryboard",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionmainstoryboard"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app extension ignores appearance changes made by the host app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
      "kind": "symbol",
      "name": "NSExtensionOverridesHostUIAppearance",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionOverridesHostUIAppearance"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionOverridesHostUIAppearance",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionoverrideshostuiappearance"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier": {
      "abstract": [
        {
          "text": "The extension point that supports an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier",
      "kind": "symbol",
      "name": "NSExtensionPointIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionPointIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionPointIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionpointidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass": {
      "abstract": [
        {
          "text": "The custom class that implements an app extension’s primary view or functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass",
      "kind": "symbol",
      "name": "NSExtensionPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionprincipalclass"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Appearance-and-Presentation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionJavaScriptPreprocessingFile"
      ],
      "title": "Appearance and Presentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuration",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationUsesStrictMatching",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationDictionaryVersion"
      ],
      "title": "Configuration"
    },
    {
      "anchor": "Attachments",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsAttachmentsWithMinCount",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsAttachmentsWithMaxCount"
      ],
      "title": "Attachments"
    },
    {
      "anchor": "Files",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsFileWithMaxCount",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsImageWithMaxCount",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsMovieWithMaxCount"
      ],
      "title": "Files"
    },
    {
      "anchor": "Text",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsText"
      ],
      "title": "Text"
    },
    {
      "anchor": "Web-Content",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsWebPageWithMaxCount",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsWebURLWithMaxCount"
      ],
      "title": "Web Content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSExtensionActivationRule"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuration",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationUsesStrictMatching",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationDictionaryVersion"
              ],
              "title": "Configuration"
            },
            {
              "anchor": "Attachments",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsAttachmentsWithMinCount",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsAttachmentsWithMaxCount"
              ],
              "title": "Attachments"
            },
            {
              "anchor": "Files",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsFileWithMaxCount",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsImageWithMaxCount",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsMovieWithMaxCount"
              ],
              "title": "Files"
            },
            {
              "anchor": "Text",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsText"
              ],
              "title": "Text"
            },
            {
              "anchor": "Web-Content",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsWebPageWithMaxCount",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule/NSExtensionActivationSupportsWebURLWithMaxCount"
              ],
              "title": "Web Content"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Appearance-and-Presentation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionJavaScriptPreprocessingFile"
              ],
              "title": "Appearance and Presentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule/title",
          "value": "NSExtensionActivationRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsFileWithMaxCount/title",
          "value": "NSExtensionActivationSupportsFileWithMaxCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsFileWithMaxCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationSupportsFileWithMaxCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsWebPageWithMaxCount/title",
          "value": "NSExtensionActivationSupportsWebPageWithMaxCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsWebPageWithMaxCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationSupportsWebPageWithMaxCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsMovieWithMaxCount/title",
          "value": "NSExtensionActivationSupportsMovieWithMaxCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsMovieWithMaxCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationSupportsMovieWithMaxCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationUsesStrictMatching/title",
          "value": "NSExtensionActivationUsesStrictMatching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationUsesStrictMatching/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationUsesStrictMatching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsImageWithMaxCount/title",
          "value": "NSExtensionActivationSupportsImageWithMaxCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsImageWithMaxCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationSupportsImageWithMaxCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionActionWantsFullScreenPresentation/title",
          "value": "NSExtensionActionWantsFullScreenPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionActionWantsFullScreenPresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActionWantsFullScreenPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsWebURLWithMaxCount/title",
          "value": "NSExtensionActivationSupportsWebURLWithMaxCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsWebURLWithMaxCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationSupportsWebURLWithMaxCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPrincipalClass/title",
          "value": "NSExtensionPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionPrincipalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsText/title",
          "value": "NSExtensionActivationSupportsText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationSupportsText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPointIdentifier/title",
          "value": "NSExtensionPointIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPointIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionPointIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsAttachmentsWithMinCount/title",
          "value": "NSExtensionActivationSupportsAttachmentsWithMinCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsAttachmentsWithMinCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationSupportsAttachmentsWithMinCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationDictionaryVersion/title",
          "value": "NSExtensionActivationDictionaryVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationDictionaryVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationDictionaryVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionOverridesHostUIAppearance/title",
          "value": "NSExtensionOverridesHostUIAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionOverridesHostUIAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionOverridesHostUIAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionJavaScriptPreprocessingFile/title",
          "value": "NSExtensionJavaScriptPreprocessingFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionJavaScriptPreprocessingFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionJavaScriptPreprocessingFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionMainStoryboard/title",
          "value": "NSExtensionMainStoryboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionMainStoryboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionMainStoryboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsAttachmentsWithMaxCount/title",
          "value": "NSExtensionActivationSupportsAttachmentsWithMaxCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule~1NSExtensionActivationSupportsAttachmentsWithMaxCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationSupportsAttachmentsWithMaxCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/title",
          "value": "NSExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionAttributes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
