{
  "abstract": [
    {
      "text": "A name for display when the extension appears as a Quick Action in the Touch Bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.NSExtensionAttributes.NSExtensionServiceTouchBarLabel",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSExtensionServiceTouchBarLabel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSExtensionServiceTouchBarLabel"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSExtensionServiceTouchBarLabel",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key is used in conjunction with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key isn’t provided, the extension’s display name is used.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes": {
      "abstract": [
        {
          "text": "Properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes",
      "kind": "symbol",
      "name": "NSExtensionAttributes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionAttributes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the extension appears as a Quick Action in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem",
      "kind": "symbol",
      "name": "NSExtensionServiceAllowsTouchBarItem",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceAllowsTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceAllowsTouchBarItem",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionserviceallowstouchbaritem"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName": {
      "abstract": [
        {
          "text": "The color to use for the bezel around the extension when it appears as a Quick Action in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName",
      "kind": "symbol",
      "name": "NSExtensionServiceTouchBarBezelColorName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceTouchBarBezelColorName"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceTouchBarBezelColorName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetouchbarbezelcolorname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName": {
      "abstract": [
        {
          "text": "The name of an icon for display when the extension appears as a Quick Action in the Touch Bar",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName",
      "kind": "symbol",
      "name": "NSExtensionServiceTouchBarIconName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceTouchBarIconName"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceTouchBarIconName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetouchbariconname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel": {
      "abstract": [
        {
          "text": "A name for display when the extension appears as a Quick Action in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel",
      "kind": "symbol",
      "name": "NSExtensionServiceTouchBarLabel",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceTouchBarLabel"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceTouchBarLabel",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetouchbarlabel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Touch-Bar",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName"
      ],
      "title": "Touch Bar"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSExtensionServiceTouchBarLabel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceTouchBarLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Touch-Bar",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName"
              ],
              "title": "Touch Bar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarBezelColorName/title",
          "value": "NSExtensionServiceTouchBarBezelColorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarBezelColorName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceTouchBarBezelColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarLabel/title",
          "value": "NSExtensionServiceTouchBarLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceTouchBarLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceAllowsTouchBarItem/title",
          "value": "NSExtensionServiceAllowsTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceAllowsTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceAllowsTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/title",
          "value": "NSExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarIconName/title",
          "value": "NSExtensionServiceTouchBarIconName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarIconName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceTouchBarIconName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetouchbarlabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetouchbarlabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
