{
  "abstract": [
    {
      "text": "The types of assets a Photo Editing extension can edit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHSupportedMediaTypes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.NSExtensionAttributes.PHSupportedMediaTypes",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHSupportedMediaTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "PHSupportedMediaTypes"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "PHSupportedMediaTypes",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [],
          "name": "Image"
        },
        {
          "content": [],
          "name": "Video"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes": {
      "abstract": [
        {
          "text": "Properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes",
      "kind": "symbol",
      "name": "NSExtensionAttributes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionAttributes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHProjectExtensionDefinesProjectTypes": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the Photos app gets a list of supported project types from an extension.",
          "type": "text"
        }
      ],
      "ideTitle": "Extension defines custom project types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHProjectExtensionDefinesProjectTypes",
      "kind": "symbol",
      "name": "PHProjectExtensionDefinesProjectTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectExtensionDefinesProjectTypes"
        }
      ],
      "role": "symbol",
      "title": "PHProjectExtensionDefinesProjectTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/phprojectextensiondefinesprojecttypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHSupportedMediaTypes": {
      "abstract": [
        {
          "text": "The types of assets a Photo Editing extension can edit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHSupportedMediaTypes",
      "kind": "symbol",
      "name": "PHSupportedMediaTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHSupportedMediaTypes"
        }
      ],
      "role": "symbol",
      "title": "PHSupportedMediaTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/phsupportedmediatypes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Photos",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHProjectExtensionDefinesProjectTypes"
      ],
      "title": "Photos"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHSupportedMediaTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHSupportedMediaTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Photos",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHProjectExtensionDefinesProjectTypes"
              ],
              "title": "Photos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PHSupportedMediaTypes/title",
          "value": "PHSupportedMediaTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PHSupportedMediaTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHSupportedMediaTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PHProjectExtensionDefinesProjectTypes/title",
          "value": "PHProjectExtensionDefinesProjectTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PHProjectExtensionDefinesProjectTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionDefinesProjectTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/title",
          "value": "NSExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionAttributes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/phsupportedmediatypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/phsupportedmediatypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
