{
  "abstract": [
    {
      "text": "A Boolean value indicating whether a custom keyboard uses a shared container and accesses the network.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/RequestsOpenAccess"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.NSExtensionAttributes.RequestsOpenAccess",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RequestsOpenAccess"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "RequestsOpenAccess"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "RequestsOpenAccess",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes": {
      "abstract": [
        {
          "text": "Properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes",
      "kind": "symbol",
      "name": "NSExtensionAttributes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionAttributes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IDMessageFilterExtensionNetworkURL": {
      "abstract": [
        {
          "text": "The server that a Message Filter app extension may defer a query to.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IDMessageFilterExtensionNetworkURL",
      "kind": "symbol",
      "name": "IDMessageFilterExtensionNetworkURL",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IDMessageFilterExtensionNetworkURL"
        }
      ],
      "role": "symbol",
      "title": "IDMessageFilterExtensionNetworkURL",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/idmessagefilterextensionnetworkurl"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ILClassificationExtensionSMSReportDestination": {
      "abstract": [
        {
          "text": "The phone number that receives SMS messages when the user reports an SMS message or a call.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ILClassificationExtensionSMSReportDestination",
      "kind": "symbol",
      "name": "ILClassificationExtensionSMSReportDestination",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationExtensionSMSReportDestination"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationExtensionSMSReportDestination",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/ilclassificationextensionsmsreportdestination"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IsASCIICapable": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a custom keyboard displays standard ASCII characters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IsASCIICapable",
      "kind": "symbol",
      "name": "IsASCIICapable",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IsASCIICapable"
        }
      ],
      "role": "symbol",
      "title": "IsASCIICapable",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/isasciicapable"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MSMessagesAppPresentationContextMessages": {
      "abstract": [
        {
          "text": "The contexts that an iMessage app or sticker pack supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MSMessagesAppPresentationContextMessages",
      "kind": "symbol",
      "name": "MSMessagesAppPresentationContextMessages",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationContextMessages"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationContextMessages",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/msmessagesapppresentationcontextmessages"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrefersRightToLeft": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a keyboard extension supports right-to-left languages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrefersRightToLeft",
      "kind": "symbol",
      "name": "PrefersRightToLeft",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PrefersRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "PrefersRightToLeft",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/prefersrighttoleft"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrimaryLanguage": {
      "abstract": [
        {
          "text": "The primary language for a keyboard extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrimaryLanguage",
      "kind": "symbol",
      "name": "PrimaryLanguage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PrimaryLanguage"
        }
      ],
      "role": "symbol",
      "title": "PrimaryLanguage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/primarylanguage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/RequestsOpenAccess": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a custom keyboard uses a shared container and accesses the network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/RequestsOpenAccess",
      "kind": "symbol",
      "name": "RequestsOpenAccess",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RequestsOpenAccess"
        }
      ],
      "role": "symbol",
      "title": "RequestsOpenAccess",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/requestsopenaccess"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerModes": {
      "abstract": [
        {
          "text": "The modes that a Document Picker extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerModes",
      "kind": "symbol",
      "name": "UIDocumentPickerModes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentPickerModes"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentPickerModes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/uidocumentpickermodes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerSupportedFileTypes": {
      "abstract": [
        {
          "text": "The Uniform Type Identifiers that a document picker extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerSupportedFileTypes",
      "kind": "symbol",
      "name": "UIDocumentPickerSupportedFileTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentPickerSupportedFileTypes"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentPickerSupportedFileTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/uidocumentpickersupportedfiletypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionCategory": {
      "abstract": [
        {
          "text": "The identifier of a category declared by the app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionCategory",
      "kind": "symbol",
      "name": "UNNotificationExtensionCategory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationExtensionCategory"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationExtensionCategory",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/unnotificationextensioncategory"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionDefaultContentHidden": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether only the app extension’s custom view controller is displayed in the notification interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionDefaultContentHidden",
      "kind": "symbol",
      "name": "UNNotificationExtensionDefaultContentHidden",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationExtensionDefaultContentHidden"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationExtensionDefaultContentHidden",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/unnotificationextensiondefaultcontenthidden"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionInitialContentSizeRatio": {
      "abstract": [
        {
          "text": "The initial size of the view controller’s view for an app extension, expressed as a ratio of its height to its width.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionInitialContentSizeRatio",
      "kind": "symbol",
      "name": "UNNotificationExtensionInitialContentSizeRatio",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationExtensionInitialContentSizeRatio"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationExtensionInitialContentSizeRatio",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/unnotificationextensioninitialcontentsizeratio"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionOverridesDefaultTitle": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the title of the app extension’s view controller is used as the title of the notification.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionOverridesDefaultTitle",
      "kind": "symbol",
      "name": "UNNotificationExtensionOverridesDefaultTitle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationExtensionOverridesDefaultTitle"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationExtensionOverridesDefaultTitle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/unnotificationextensionoverridesdefaulttitle"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionUserInteractionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether user interactions in a custom notification are enabled.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionUserInteractionEnabled",
      "kind": "symbol",
      "name": "UNNotificationExtensionUserInteractionEnabled",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationExtensionUserInteractionEnabled"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationExtensionUserInteractionEnabled",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/unnotificationextensionuserinteractionenabled"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "UIKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IDMessageFilterExtensionNetworkURL",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ILClassificationExtensionSMSReportDestination",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IsASCIICapable",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MSMessagesAppPresentationContextMessages",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrefersRightToLeft",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrimaryLanguage",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerModes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerSupportedFileTypes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionCategory",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionDefaultContentHidden",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionInitialContentSizeRatio",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionOverridesDefaultTitle",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionUserInteractionEnabled"
      ],
      "title": "UIKit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "RequestsOpenAccess"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RequestsOpenAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "UIKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IDMessageFilterExtensionNetworkURL",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ILClassificationExtensionSMSReportDestination",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IsASCIICapable",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MSMessagesAppPresentationContextMessages",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrefersRightToLeft",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrimaryLanguage",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerModes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerSupportedFileTypes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionCategory",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionDefaultContentHidden",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionInitialContentSizeRatio",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionOverridesDefaultTitle",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionUserInteractionEnabled"
              ],
              "title": "UIKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionDefaultContentHidden/title",
          "value": "UNNotificationExtensionDefaultContentHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionDefaultContentHidden/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationExtensionDefaultContentHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionUserInteractionEnabled/title",
          "value": "UNNotificationExtensionUserInteractionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionUserInteractionEnabled/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationExtensionUserInteractionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionInitialContentSizeRatio/title",
          "value": "UNNotificationExtensionInitialContentSizeRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionInitialContentSizeRatio/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationExtensionInitialContentSizeRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1IsASCIICapable/title",
          "value": "IsASCIICapable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1IsASCIICapable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IsASCIICapable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PrefersRightToLeft/title",
          "value": "PrefersRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PrefersRightToLeft/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PrefersRightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UIDocumentPickerSupportedFileTypes/title",
          "value": "UIDocumentPickerSupportedFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UIDocumentPickerSupportedFileTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentPickerSupportedFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionCategory/title",
          "value": "UNNotificationExtensionCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationExtensionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionOverridesDefaultTitle/title",
          "value": "UNNotificationExtensionOverridesDefaultTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionOverridesDefaultTitle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationExtensionOverridesDefaultTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1IDMessageFilterExtensionNetworkURL/title",
          "value": "IDMessageFilterExtensionNetworkURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1IDMessageFilterExtensionNetworkURL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IDMessageFilterExtensionNetworkURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/title",
          "value": "NSExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PrimaryLanguage/title",
          "value": "PrimaryLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PrimaryLanguage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PrimaryLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UIDocumentPickerModes/title",
          "value": "UIDocumentPickerModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UIDocumentPickerModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentPickerModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1MSMessagesAppPresentationContextMessages/title",
          "value": "MSMessagesAppPresentationContextMessages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1MSMessagesAppPresentationContextMessages/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationContextMessages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1ILClassificationExtensionSMSReportDestination/title",
          "value": "ILClassificationExtensionSMSReportDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1ILClassificationExtensionSMSReportDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationExtensionSMSReportDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1RequestsOpenAccess/title",
          "value": "RequestsOpenAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1RequestsOpenAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RequestsOpenAccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/requestsopenaccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/requestsopenaccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
