{
  "abstract": [
    {
      "text": "A calculation that estimates VO2 max rate based on low-intensity exercise.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/predictionSubMaxExercise"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKVO2MaxTestType@HKVO2MaxTestTypePredictionSubMaxExercise",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "predictionSubMaxExercise"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKVO2MaxTestTypePredictionSubMaxExercise"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKVO2MaxTestType.predictionSubMaxExercise"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "predictionSubMaxExercise"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType": {
      "abstract": [
        {
          "text": "Methods for calculating the user’s VO2 max rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKVO2MaxTestType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVO2MaxTestType"
        }
      ],
      "role": "symbol",
      "title": "HKVO2MaxTestType",
      "type": "topic",
      "url": "/documentation/healthkit/hkvo2maxtesttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/maxExercise": {
      "abstract": [
        {
          "text": "A test that measures VO2 max rate by monitoring exercise to the user’s physical limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxExercise"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/maxExercise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVO2MaxTestTypeMaxExercise"
        }
      ],
      "role": "symbol",
      "title": "HKVO2MaxTestType.maxExercise",
      "type": "topic",
      "url": "/documentation/healthkit/hkvo2maxtesttype/maxexercise"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/predictionNonExercise": {
      "abstract": [
        {
          "text": "A calculation that estimates VO2 max rate without any exercise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictionNonExercise"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/predictionNonExercise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVO2MaxTestTypePredictionNonExercise"
        }
      ],
      "role": "symbol",
      "title": "HKVO2MaxTestType.predictionNonExercise",
      "type": "topic",
      "url": "/documentation/healthkit/hkvo2maxtesttype/predictionnonexercise"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/predictionSubMaxExercise": {
      "abstract": [
        {
          "text": "A calculation that estimates VO2 max rate based on low-intensity exercise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictionSubMaxExercise"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/predictionSubMaxExercise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVO2MaxTestTypePredictionSubMaxExercise"
        }
      ],
      "role": "symbol",
      "title": "HKVO2MaxTestType.predictionSubMaxExercise",
      "type": "topic",
      "url": "/documentation/healthkit/hkvo2maxtesttype/predictionsubmaxexercise"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Test-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/maxExercise",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/predictionNonExercise"
      ],
      "title": "Test Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKVO2MaxTestTypePredictionSubMaxExercise"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVO2MaxTestTypePredictionSubMaxExercise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Test-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/maxExercise",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVO2MaxTestType/predictionNonExercise"
              ],
              "title": "Test Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKVO2MaxTestTypePredictionSubMaxExercise"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVO2MaxTestType~1predictionSubMaxExercise/title",
          "value": "HKVO2MaxTestTypePredictionSubMaxExercise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVO2MaxTestType~1predictionSubMaxExercise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVO2MaxTestTypePredictionSubMaxExercise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVO2MaxTestType~1maxExercise/title",
          "value": "HKVO2MaxTestTypeMaxExercise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVO2MaxTestType~1maxExercise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVO2MaxTestTypeMaxExercise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVO2MaxTestType~1predictionNonExercise/title",
          "value": "HKVO2MaxTestTypePredictionNonExercise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVO2MaxTestType~1predictionNonExercise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVO2MaxTestTypePredictionNonExercise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVO2MaxTestType/title",
          "value": "HKVO2MaxTestType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVO2MaxTestType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVO2MaxTestType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVO2MaxTestType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVO2MaxTestType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkvo2maxtesttype/predictionsubmaxexercise"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkvo2maxtesttype/predictionsubmaxexercise"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
