{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the GPU is removable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDevice/isRemovable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLDevice(py)removable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isRemovable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "removable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "isRemovable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isRemovable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can respond to GPU removal notifications by registering with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver(handler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function in Swift,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function in Objective-C,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and responding to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName/removalRequested",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName/wasRemoved",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " device notification names.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If a person removes a GPU without warning, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " APIs may fail even before your app receives a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName/wasRemoved",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " notification.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArchitecture": {
      "abstract": [
        {
          "text": "A class that contains the architectural details of a GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArchitecture"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArchitecture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArchitecture"
        }
      ],
      "role": "symbol",
      "title": "MTLArchitecture",
      "type": "topic",
      "url": "/documentation/metal/mtlarchitecture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver": {
      "abstract": [
        {
          "text": "Returns an array of all the Metal GPU devices in the system and registers a notification handler that Metal calls when the device list changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLCopyAllDevicesWithObserver"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCopyAllDevicesWithObserver",
      "type": "topic",
      "url": "/documentation/metal/mtlcopyalldeviceswithobserver"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver(handler:)": {
      "abstract": [
        {
          "text": "Returns an array of all the Metal GPU devices in the system and registers a notification handler that Metal calls when the device list changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCopyAllDevicesWithObserver"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLDeviceNotificationHandler",
          "text": "MTLDeviceNotificationHandler"
        },
        {
          "kind": "text",
          "text": ") -> (devices"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": "], observer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver(handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCopyAllDevicesWithObserver(handler:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcopyalldeviceswithobserver(handler:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/architecture": {
      "abstract": [
        {
          "text": "The architectural details of the GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "architecture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLArchitecture",
          "text": "MTLArchitecture"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/architecture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "architecture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "architecture",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/architecture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/isHeadless": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a GPU device doesn’t have a connection to a display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHeadless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/isHeadless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headless"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isHeadless",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/isheadless"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/isLowPower": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU lowers its performance to conserve energy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLowPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/isLowPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lowPower"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isLowPower",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/islowpower"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/isRemovable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU is removable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRemovable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/isRemovable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removable"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isRemovable",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/isremovable"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/location": {
      "abstract": [
        {
          "text": "The physical location of the GPU relative to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDeviceLocation",
          "text": "MTLDeviceLocation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/location"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/locationNumber": {
      "abstract": [
        {
          "text": "A specific GPU position based on its general location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/locationNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationNumber"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "locationNumber",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/locationnumber"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/name": {
      "abstract": [
        {
          "text": "The full name of the GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/name"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/peerCount": {
      "abstract": [
        {
          "text": "The total number of GPUs in the peer group, if applicable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/peerCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peerCount"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "peerCount",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/peercount"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/peerGroupID": {
      "abstract": [
        {
          "text": "The peer group ID the GPU belongs to, if applicable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerGroupID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/peerGroupID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peerGroupID"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "peerGroupID",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/peergroupid"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/peerIndex": {
      "abstract": [
        {
          "text": "The unique identifier for a GPU in a peer group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/peerIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peerIndex"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "peerIndex",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/peerindex"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/registryID": {
      "abstract": [
        {
          "text": "The GPU device’s registry identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/registryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registryID"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "registryID",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/registryid"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation": {
      "abstract": [
        {
          "text": "Indicates the location of the GPU relative to the system it’s connect to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDeviceLocation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceLocation"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceLocation",
      "type": "topic",
      "url": "/documentation/metal/mtldevicelocation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName/removalRequested": {
      "abstract": [
        {
          "text": "A notification that Metal sends to observers when a person requests to remove a GPU device from the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removalRequested"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLDeviceNotificationName",
          "text": "MTLDeviceNotificationName"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName/removalRequested",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceRemovalRequestedNotification"
        }
      ],
      "role": "symbol",
      "title": "removalRequested",
      "type": "topic",
      "url": "/documentation/metal/mtldevicenotificationname/removalrequested"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName/wasRemoved": {
      "abstract": [
        {
          "text": "A notification that Metal sends to observers when the system removes a GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wasRemoved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLDeviceNotificationName",
          "text": "MTLDeviceNotificationName"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName/wasRemoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceWasRemovedNotification"
        }
      ],
      "role": "symbol",
      "title": "wasRemoved",
      "type": "topic",
      "url": "/documentation/metal/mtldevicenotificationname/wasremoved"
    },
    "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac": {
      "abstract": [
        {
          "text": "Locate, identify, and choose suitable GPUs for your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac",
      "kind": "article",
      "role": "article",
      "title": "Finding Multiple GPUs on an Intel-based Mac",
      "type": "topic",
      "url": "/documentation/metal/finding-multiple-gpus-on-an-intel-based-mac"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-a-GPU-Device",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/name",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/architecture",
        "doc://com.apple.metal/documentation/Metal/MTLArchitecture",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/registryID",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/location",
        "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/locationNumber",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/isLowPower",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/isHeadless",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/peerGroupID",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/peerCount",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/peerIndex"
      ],
      "title": "Identifying a GPU Device"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "removable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "removable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLDevice"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-a-GPU-Device",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/name",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/architecture",
                "doc://com.apple.metal/documentation/Metal/MTLArchitecture",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/registryID",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/location",
                "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/locationNumber",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/isLowPower",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/isHeadless",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/peerGroupID",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/peerCount",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/peerIndex"
              ],
              "title": "Identifying a GPU Device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "getter"
                  },
                  {
                    "kind": "text",
                    "text": "="
                  },
                  {
                    "kind": "identifier",
                    "text": "isRemovable"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "removable"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isHeadless/title",
          "value": "headless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isHeadless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1location/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1locationNumber/title",
          "value": "locationNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1locationNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locationNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArchitecture/title",
          "value": "MTLArchitecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArchitecture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArchitecture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isLowPower/title",
          "value": "lowPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isLowPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lowPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationName~1removalRequested/title",
          "value": "MTLDeviceRemovalRequestedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationName~1removalRequested/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceRemovalRequestedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation/title",
          "value": "MTLDeviceLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerCount/title",
          "value": "peerCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "peerCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationName~1wasRemoved/title",
          "value": "MTLDeviceWasRemovedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationName~1wasRemoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceWasRemovedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1architecture/title",
          "value": "architecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1architecture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "architecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerGroupID/title",
          "value": "peerGroupID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerGroupID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "peerGroupID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerIndex/title",
          "value": "peerIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "peerIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isRemovable/title",
          "value": "removable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isRemovable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "removable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1registryID/title",
          "value": "registryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1registryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "registryID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldevice/isremovable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtldevice/isremovable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
