{
  "abstract": [
    {
      "text": "Returns the dimensions of a sparse tile for a texture that has a specific sparse page size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSize(textureType:pixelFormat:sampleCount:sparsePageSize:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLDevice(im)sparseTileSizeWithTextureType:pixelFormat:sampleCount:sparsePageSize:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sparseTileSize"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "textureType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MTLTextureType",
        "text": "MTLTextureType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "pixelFormat"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MTLPixelFormat",
        "text": "MTLPixelFormat"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "sampleCount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "sparsePageSize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MTLSparsePageSize",
        "text": "MTLSparsePageSize"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@MTLSize",
        "text": "MTLSize"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sparseTileSizeWithTextureType:pixelFormat:sampleCount:sparsePageSize:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "sparseTileSize(textureType:pixelFormat:sampleCount:sparsePageSize:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sparseTileSize"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "textureType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLTextureType",
              "text": "MTLTextureType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "pixelFormat"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLPixelFormat",
              "text": "MTLPixelFormat"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "sampleCount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "sparsePageSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLSparsePageSize",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLSparsePageSize",
              "text": "MTLSparsePageSize"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLSize",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@MTLSize",
              "text": "MTLSize"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "textureType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pixelFormat"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of samples for each pixel.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sampleCount"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLSparsePageSize",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sparsePageSize"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLSize",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/convertSparsePixelRegions(_:toTileRegions:withTileSize:alignmentMode:numRegions:)": {
      "abstract": [
        {
          "text": "Converts a list of sparse pixel regions to tile regions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertSparsePixelRegions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLRegion",
          "text": "MTLRegion"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "toTileRegions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLRegion",
          "text": "MTLRegion"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "withTileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLSize",
          "text": "MTLSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alignmentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSparseTextureRegionAlignmentMode",
          "text": "MTLSparseTextureRegionAlignmentMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numRegions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/convertSparsePixelRegions(_:toTileRegions:withTileSize:alignmentMode:numRegions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertSparsePixelRegions:toTileRegions:withTileSize:alignmentMode:numRegions:"
        }
      ],
      "role": "symbol",
      "title": "convertSparsePixelRegions(_:toTileRegions:withTileSize:alignmentMode:numRegions:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/convertsparsepixelregions(_:totileregions:withtilesize:alignmentmode:numregions:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/convertSparseTileRegions(_:toPixelRegions:withTileSize:numRegions:)": {
      "abstract": [
        {
          "text": "Converts a list of sparse tile regions to pixel regions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertSparseTileRegions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLRegion",
          "text": "MTLRegion"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "toPixelRegions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLRegion",
          "text": "MTLRegion"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "withTileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLSize",
          "text": "MTLSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numRegions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/convertSparseTileRegions(_:toPixelRegions:withTileSize:numRegions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertSparseTileRegions:toPixelRegions:withTileSize:numRegions:"
        }
      ],
      "role": "symbol",
      "title": "convertSparseTileRegions(_:toPixelRegions:withTileSize:numRegions:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/convertsparsetileregions(_:topixelregions:withtilesize:numregions:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSize(textureType:pixelFormat:sampleCount:sparsePageSize:)": {
      "abstract": [
        {
          "text": "Returns the dimensions of a sparse tile for a texture that has a specific sparse page size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparseTileSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "textureType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureType",
          "text": "MTLTextureType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sampleCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sparsePageSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSparsePageSize",
          "text": "MTLSparsePageSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLSize",
          "text": "MTLSize"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSize(textureType:pixelFormat:sampleCount:sparsePageSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparseTileSizeWithTextureType:pixelFormat:sampleCount:sparsePageSize:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sparseTileSize(textureType:pixelFormat:sampleCount:sparsePageSize:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/sparsetilesize(texturetype:pixelformat:samplecount:sparsepagesize:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSize(with:pixelFormat:sampleCount:)": {
      "abstract": [
        {
          "text": "Returns the dimensions of a sparse tile for a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparseTileSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureType",
          "text": "MTLTextureType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sampleCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLSize",
          "text": "MTLSize"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSize(with:pixelFormat:sampleCount:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparseTileSizeWithTextureType:pixelFormat:sampleCount:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sparseTileSize(with:pixelFormat:sampleCount:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/sparsetilesize(with:pixelformat:samplecount:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSizeInBytes": {
      "abstract": [
        {
          "text": "Returns the size, in bytes, of a sparse tile the GPU device creates using a default page size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparseTileSizeInBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSizeInBytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparseTileSizeInBytes"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sparseTileSizeInBytes",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/sparsetilesizeinbytes"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSizeInBytes(sparsePageSize:)": {
      "abstract": [
        {
          "text": "Returns the size, in bytes, of a sparse tile the GPU device creates with a specific page size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparseTileSizeInBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "sparsePageSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSparsePageSize",
          "text": "MTLSparsePageSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSizeInBytes(sparsePageSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparseTileSizeInBytesForSparsePageSize:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sparseTileSizeInBytes(sparsePageSize:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/sparsetilesizeinbytes(sparsepagesize:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat": {
      "abstract": [
        {
          "text": "The data formats that describe the organization and characteristics of individual pixels in a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSize": {
      "abstract": [
        {
          "text": "The dimensions of an object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSize"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSize"
        }
      ],
      "role": "symbol",
      "title": "MTLSize",
      "type": "topic",
      "url": "/documentation/metal/mtlsize"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSparsePageSize": {
      "abstract": [
        {
          "text": "The page size options, in kilobytes, for sparse textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSparsePageSize"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSparsePageSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSparsePageSize"
        }
      ],
      "role": "symbol",
      "title": "MTLSparsePageSize",
      "type": "topic",
      "url": "/documentation/metal/mtlsparsepagesize"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSparseTextureRegionAlignmentMode": {
      "abstract": [
        {
          "text": "Options used when converting between a pixel-based region within a texture to a tile-based region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSparseTextureRegionAlignmentMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSparseTextureRegionAlignmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSparseTextureRegionAlignmentMode"
        }
      ],
      "role": "symbol",
      "title": "MTLSparseTextureRegionAlignmentMode",
      "type": "topic",
      "url": "/documentation/metal/mtlsparsetextureregionalignmentmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureType": {
      "abstract": [
        {
          "text": "The dimension of each image, including whether multiple images are arranged into an array or a cube.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTextureType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureType"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureType",
      "type": "topic",
      "url": "/documentation/metal/mtltexturetype"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Sparse-Textures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSize(with:pixelFormat:sampleCount:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSizeInBytes(sparsePageSize:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSizeInBytes",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/convertSparsePixelRegions(_:toTileRegions:withTileSize:alignmentMode:numRegions:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/convertSparseTileRegions(_:toPixelRegions:withTileSize:numRegions:)",
        "doc://com.apple.metal/documentation/Metal/MTLSparsePageSize",
        "doc://com.apple.metal/documentation/Metal/MTLSparseTextureRegionAlignmentMode"
      ],
      "title": "Working with Sparse Textures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sparseTileSizeWithTextureType:pixelFormat:sampleCount:sparsePageSize:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sparseTileSizeWithTextureType:pixelFormat:sampleCount:sparsePageSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLDevice"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Sparse-Textures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSize(with:pixelFormat:sampleCount:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSizeInBytes(sparsePageSize:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/sparseTileSizeInBytes",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/convertSparsePixelRegions(_:toTileRegions:withTileSize:alignmentMode:numRegions:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/convertSparseTileRegions(_:toPixelRegions:withTileSize:numRegions:)",
                "doc://com.apple.metal/documentation/Metal/MTLSparsePageSize",
                "doc://com.apple.metal/documentation/Metal/MTLSparseTextureRegionAlignmentMode"
              ],
              "title": "Working with Sparse Textures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLSize",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@MTLSize",
                    "text": "MTLSize"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "sparseTileSizeWithTextureType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MTLTextureType",
                    "text": "MTLTextureType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "textureType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "pixelFormat:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MTLPixelFormat",
                    "text": "MTLPixelFormat"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "pixelFormat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sampleCount:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sampleCount"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sparsePageSize:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLSparsePageSize",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MTLSparsePageSize",
                    "text": "MTLSparsePageSize"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sparsePageSize"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " instance.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "textureType"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " instance.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "pixelFormat"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of samples for each pixel.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sampleCount"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.metal/documentation/Metal/MTLSparsePageSize",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " instance.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sparsePageSize"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLSize",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " instance.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1sparseTileSize(with:pixelFormat:sampleCount:)/title",
          "value": "sparseTileSizeWithTextureType:pixelFormat:sampleCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1sparseTileSize(with:pixelFormat:sampleCount:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sparseTileSizeWithTextureType:pixelFormat:sampleCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSize/title",
          "value": "MTLSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1sparseTileSize(textureType:pixelFormat:sampleCount:sparsePageSize:)/title",
          "value": "sparseTileSizeWithTextureType:pixelFormat:sampleCount:sparsePageSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1sparseTileSize(textureType:pixelFormat:sampleCount:sparsePageSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sparseTileSizeWithTextureType:pixelFormat:sampleCount:sparsePageSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1convertSparseTileRegions(_:toPixelRegions:withTileSize:numRegions:)/title",
          "value": "convertSparseTileRegions:toPixelRegions:withTileSize:numRegions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1convertSparseTileRegions(_:toPixelRegions:withTileSize:numRegions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertSparseTileRegions:toPixelRegions:withTileSize:numRegions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSparsePageSize/title",
          "value": "MTLSparsePageSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSparsePageSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSparsePageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSparsePageSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSparsePageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1convertSparsePixelRegions(_:toTileRegions:withTileSize:alignmentMode:numRegions:)/title",
          "value": "convertSparsePixelRegions:toTileRegions:withTileSize:alignmentMode:numRegions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1convertSparsePixelRegions(_:toTileRegions:withTileSize:alignmentMode:numRegions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertSparsePixelRegions:toTileRegions:withTileSize:alignmentMode:numRegions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1sparseTileSizeInBytes/title",
          "value": "sparseTileSizeInBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1sparseTileSizeInBytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparseTileSizeInBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSparseTextureRegionAlignmentMode/title",
          "value": "MTLSparseTextureRegionAlignmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSparseTextureRegionAlignmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSparseTextureRegionAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSparseTextureRegionAlignmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSparseTextureRegionAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1sparseTileSizeInBytes(sparsePageSize:)/title",
          "value": "sparseTileSizeInBytesForSparsePageSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1sparseTileSizeInBytes(sparsePageSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sparseTileSizeInBytesForSparsePageSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType/title",
          "value": "MTLTextureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title",
          "value": "MTLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldevice/sparsetilesize(texturetype:pixelformat:samplecount:sparsepagesize:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtldevice/sparsetilesize(texturetype:pixelformat:samplecount:sparsepagesize:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
