{
  "abstract": [
    {
      "text": "The UUID that is specific to a device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport",
        "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ASIdentifierManager(py)advertisingIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "advertisingIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4UUIDV",
        "text": "UUID"
      }
    ],
    "modules": [
      {
        "name": "AdSupport"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "advertisingIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "advertisingIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "advertisingIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4UUIDV",
              "text": "UUID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is an alphanumeric string",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that’s unique to each device, and which you only use for advertising. Use",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "this string for frequency capping, attribution, conversion events,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "estimating the number of unique users, advertising fraud detection, and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "debugging. On devices running iOS 14.5 and later and iPadOS 14.5 and later,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app must request tracking authorization before it can get the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "advertising identifier. For more information on getting the advertising",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "identifier, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The advertising identifier returns either a unique UUID, or all zeros. It",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "returns a unique UUID in the following cases:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If Settings > Privacy > Tracking > Allow Apps to Request to Track",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "is On, you’ve requested tracking authorization from the user by calling the",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " APIs,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "and received authorization, indicated by",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/authorized",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the user changes Settings > Privacy > Tracking > Allow Apps to",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Request to Track to Off after authorizing your app, and leaves the",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "permissions On for your app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The advertising identifier returns all zeros",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "(",
              "type": "text"
            },
            {
              "code": "00000000-0000-0000-0000-000000000000",
              "type": "codeVoice"
            },
            {
              "text": ") in the following cases:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In Simulator, regardless of any settings.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When you call this API on a device running macOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When you call this API in a compatible iPad or iPhone app running in visionOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On devices running iOS 14.5 and later and iPadOS 14.5 and later, if you haven’t requested authorization using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " framework.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you’ve requested authorization using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " framework and the user declines, which results in an authorization status of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/denied",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When a profile or configuration restricts access to the advertising identifier. For more information about restrictions, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/restricted",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "As a best practice, don’t store the advertising identifier value; access",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead. Users can change",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "their authorization for tracking at any time in Settings > Privacy >",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Tracking. Check your app’s authorization using the App Tracking Transparency",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "API",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/trackingAuthorizationStatus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to determine the user’s intent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about asking users for permission to track, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/app-store/user-privacy-and-data-use/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport": {
      "abstract": [
        {
          "text": "Provide apps with access to an advertising identifier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport",
      "kind": "symbol",
      "role": "collection",
      "title": "AdSupport",
      "type": "topic",
      "url": "/documentation/adsupport"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager": {
      "abstract": [
        {
          "text": "The object that contains the advertising identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASIdentifierManager"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASIdentifierManager"
        }
      ],
      "role": "symbol",
      "title": "ASIdentifierManager",
      "type": "topic",
      "url": "/documentation/adsupport/asidentifiermanager"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier": {
      "abstract": [
        {
          "text": "The UUID that is specific to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "advertisingIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "advertisingIdentifier"
        }
      ],
      "role": "symbol",
      "title": "advertisingIdentifier",
      "type": "topic",
      "url": "/documentation/adsupport/asidentifiermanager/advertisingidentifier"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/shared()": {
      "abstract": [
        {
          "text": "The shared instance of the identifier manager class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASIdentifierManager",
          "text": "ASIdentifierManager"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/shared()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedManager"
        }
      ],
      "role": "symbol",
      "title": "shared()",
      "type": "topic",
      "url": "/documentation/adsupport/asidentifiermanager/shared()"
    },
    "doc://com.apple.documentation/documentation/AppTrackingTransparency": {
      "abstract": [
        {
          "text": "Request user authorization to access app-related data for tracking the user or the device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency",
      "kind": "symbol",
      "role": "collection",
      "title": "App Tracking Transparency",
      "type": "topic",
      "url": "/documentation/AppTrackingTransparency"
    },
    "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/authorized": {
      "abstract": [
        {
          "text": "The value that returns if the user authorizes access to app-related data for tracking the user or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/authorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus.authorized",
      "type": "topic",
      "url": "/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/authorized"
    },
    "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/denied": {
      "abstract": [
        {
          "text": "The value that returns if the user denies authorization to access app-related data for tracking the user or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/denied",
      "kind": "symbol",
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus.denied",
      "type": "topic",
      "url": "/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/denied"
    },
    "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/restricted": {
      "abstract": [
        {
          "text": "The value that returns if authorization to access app-related data for tracking the user or the device has a restricted status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/restricted",
      "kind": "symbol",
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus.restricted",
      "type": "topic",
      "url": "/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus/restricted"
    },
    "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/trackingAuthorizationStatus": {
      "abstract": [
        {
          "text": "The authorization status that is current for the calling application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ATTrackingManager",
          "text": "ATTrackingManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
          "text": "AuthorizationStatus"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppTrackingTransparency/ATTrackingManager/trackingAuthorizationStatus",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackingAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/AppTrackingTransparency/ATTrackingManager/trackingAuthorizationStatus"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV": {
      "abstract": [
        {
          "text": "A universally unique value to identify types, interfaces, and other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UUID",
      "type": "topic",
      "url": "/documentation/foundation/uuid"
    },
    "https://developer.apple.com/app-store/user-privacy-and-data-use/": {
      "identifier": "https://developer.apple.com/app-store/user-privacy-and-data-use/",
      "title": "User Privacy and Data Use",
      "titleInlineContent": [
        {
          "text": "User",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Privacy and Data",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Use",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/app-store/user-privacy-and-data-use/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Advertising-Identifier",
      "generated": true,
      "identifiers": [
        "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/shared()"
      ],
      "title": "Getting the Advertising Identifier"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "advertisingIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "advertisingIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport",
                "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Advertising-Identifier",
              "generated": true,
              "identifiers": [
                "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/shared()"
              ],
              "title": "Getting the Advertising Identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSUUID",
                    "text": "NSUUID"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "advertisingIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1denied/title",
          "value": "ATTrackingManagerAuthorizationStatusDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager/title",
          "value": "ASIdentifierManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASIdentifierManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASIdentifierManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager~1advertisingIdentifier/title",
          "value": "advertisingIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager~1advertisingIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "advertisingIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppTrackingTransparency~1ATTrackingManager~1trackingAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
              "text": "ATTrackingManagerAuthorizationStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "trackingAuthorizationStatus"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager~1shared()/title",
          "value": "sharedManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager~1shared()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1authorized/title",
          "value": "ATTrackingManagerAuthorizationStatusAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatusAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1restricted/title",
          "value": "ATTrackingManagerAuthorizationStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatusRestricted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/adsupport/asidentifiermanager/advertisingidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/adsupport/asidentifiermanager/advertisingidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
