{
  "abstract": [
    {
      "text": "The shared instance of the identifier manager class.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport",
        "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/shared()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ASIdentifierManager(cm)sharedManager",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shared"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ASIdentifierManager",
        "text": "ASIdentifierManager"
      }
    ],
    "modules": [
      {
        "name": "AdSupport"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sharedManager"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "shared()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shared"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ASIdentifierManager",
              "text": "ASIdentifierManager"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns the shared instance of the AdSupport identifier manager",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport": {
      "abstract": [
        {
          "text": "Provide apps with access to an advertising identifier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport",
      "kind": "symbol",
      "role": "collection",
      "title": "AdSupport",
      "type": "topic",
      "url": "/documentation/adsupport"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager": {
      "abstract": [
        {
          "text": "The object that contains the advertising identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASIdentifierManager"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASIdentifierManager"
        }
      ],
      "role": "symbol",
      "title": "ASIdentifierManager",
      "type": "topic",
      "url": "/documentation/adsupport/asidentifiermanager"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier": {
      "abstract": [
        {
          "text": "The UUID that is specific to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "advertisingIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "advertisingIdentifier"
        }
      ],
      "role": "symbol",
      "title": "advertisingIdentifier",
      "type": "topic",
      "url": "/documentation/adsupport/asidentifiermanager/advertisingidentifier"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/shared()": {
      "abstract": [
        {
          "text": "The shared instance of the identifier manager class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASIdentifierManager",
          "text": "ASIdentifierManager"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/shared()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedManager"
        }
      ],
      "role": "symbol",
      "title": "shared()",
      "type": "topic",
      "url": "/documentation/adsupport/asidentifiermanager/shared()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Advertising-Identifier",
      "generated": true,
      "identifiers": [
        "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier"
      ],
      "title": "Getting the Advertising Identifier"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sharedManager"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport",
                "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Advertising-Identifier",
              "generated": true,
              "identifiers": [
                "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier"
              ],
              "title": "Getting the Advertising Identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AdSupport/ASIdentifierManager",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ASIdentifierManager",
                    "text": "ASIdentifierManager"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "sharedManager"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Returns the shared instance of the AdSupport identifier manager",
                    "type": "text"
                  },
                  {
                    "text": " ",
                    "type": "text"
                  },
                  {
                    "text": "class.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager/title",
          "value": "ASIdentifierManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASIdentifierManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASIdentifierManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager~1advertisingIdentifier/title",
          "value": "advertisingIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager~1advertisingIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "advertisingIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager~1shared()/title",
          "value": "sharedManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AdSupport~1ASIdentifierManager~1shared()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/adsupport/asidentifiermanager/shared()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/adsupport/asidentifiermanager/shared()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
