{
  "abstract": [
    {
      "text": "Implement a configurable virtual MIDI driver as a driver extension that runs in user space in macOS and iPadOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mididriverkit/documentation/MIDIDriverKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mididriverkit/documentation/MIDIDriverKit/creating-a-midi-device-driver"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MIDIDriverKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "24.0",
        "name": "DriverKit"
      },
      {
        "beta": false,
        "introducedAt": "18.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "18.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Creating a MIDI device driver"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample code project shows how to create a MIDI driver extension using the MIDIDriverKit framework. It provides a C++ DriverKit implementation that allows you to publish a single MIDI device with one port that contains a MIDI source and a MIDI destination, as well as a Swift client app that installs and configures the drivers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample implements a dynamic environment that can support multiple MIDI devices and any other MIDI objects the MIDIDriverKit framework provides. The MIDI device provides the following features:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A port",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A virtual MIDI source",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A virtual MIDI destination",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A toggle for the offline property",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The possibility to add or remove a port",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "MIDIDriverKit is available in macOS, and in iPadOS 18 and later when running on an iPad device with an M-series chip. This sample code project supports both platforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample app connects to the MIDI driver extension through a custom user client connection. The custom user client shows an example of how to toggle the offline property and add or remove a port on the MIDI driver extension. In macOS, the sample app also provides the installer for the driver. In iPadOS, you install the driver by enabling it in Settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, the sample code project uses manual code signing. If you just want to run the app to see how it works, select “Automatically manage signing” for each of the targets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to run the app with manual signing, do the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create new bundle identifiers for the app and driver. The bundle identifiers in the project already have App IDs associated with them, so you need unique identifiers to create your own App IDs. Use a reverse-DNS format for your identifiers, as described in ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/xcode/preparing-your-app-for-distribution",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Additionally, iPadOS requires that your driver’s bundle identifier begin with the host app’s bundle identifier. For example, the default bundle identifiers are ",
                      "type": "text"
                    },
                    {
                      "code": "com.example.apple-samplecode.CreatingMIDIDriverSampleApp",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for the app and ",
                      "type": "text"
                    },
                    {
                      "code": "com.example.apple-samplecode.ExampleDriver.Driver",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for the driver.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the Xcode project, click the Signing & Capabilities tab for each of the two targets — the driver and the macOS/iOS app — and set the respective bundle identifier.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the driver’s ",
                      "type": "text"
                    },
                    {
                      "code": "Info.plist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file, set the value of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserservername?language=objc",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to the driver bundle identifier.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In ",
                      "type": "text"
                    },
                    {
                      "code": "CreatingMIDIDriverSampleAppViewModel.swift",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", make sure the string concatentation that initializes ",
                      "type": "text"
                    },
                    {
                      "code": "dextIdentifier",
                      "type": "codeVoice"
                    },
                    {
                      "text": " matches the bundle identifier for the driver.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create an explicit App ID and provisioning profile for the sample app with the entitlements ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_system-extension_install?language=objc",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit_communicates-with-drivers?language=objc",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". For information about how to request entitlements, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/driverkit/requesting_entitlements_for_driverkit_development",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create an explicit App ID and provisioning profile for the sample driver with the following entitlements: ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit?language=objc",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "com.apple.developer.driverkit.family.midi",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "code": "com.apple.developer.driverkit.allow-any-userclient-access",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". This latter macOS-only entitlement allows any app to connect to the driver as a user client. Although this simplifies running the sample code, in your own apps you may prefer to use ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit_userclient-access?language=objc",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". This entitlement goes on the app rather than the driver, and lists bundle identifiers of drivers it can connect to. If you don’t intend for your driver to allow user client connections, just use the ",
                      "type": "text"
                    },
                    {
                      "code": "com.apple.developer.driverkit.family.midi",
                      "type": "codeVoice"
                    },
                    {
                      "text": " entitlement.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For each of the App IDs you create in the previous steps, select Profiles to create a new provisioning profile. You need one for the macOS app, one for the iPadOS app, and one for the driver, which supports both macOS and iPadOS. When creating the driver’s profile, be sure to select DriverKit App Development as the profile type.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Download each profile and add it to Xcode.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Signing & Capabilities tab, set each target to manual code signing, and select its new profile.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Run-the-sample-app-in-macOS",
          "level": 3,
          "text": "Run the sample app in macOS",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To run the sample app in macOS, use the scheme selector to select the CreatingMIDIDriverSampleApp scheme and the My Mac destination. Build the target, then copy the app to the Applications folder and launch the app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "You can run the app directly from Xcode, without moving the app bundle to ",
                  "type": "text"
                },
                {
                  "code": "/Applications",
                  "type": "codeVoice"
                },
                {
                  "text": " each time, by using the ",
                  "type": "text"
                },
                {
                  "code": "systemextensionsctl",
                  "type": "codeVoice"
                },
                {
                  "text": " command to enable system extensions developer mode, as explained in ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/documentation//driverkit/debugging_and_testing_system_extensions",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS, the CreatingMIDIDriverSampleApp app has two sections: Driver Manager, which installs the app, and User Client Manager, which interacts with the running driver. Under Driver Manager, click Install Driver. If a System Extension Blocked dialog appears, open System Settings and navigate to the Login Items & Extensions pane. Unlock the pane, if necessary, and click Allow to complete the installation. When installation completes, the Driver Manager status in the app displays the message “CreatingMIDIDriverSampleAppDriver has been activated and is ready to use.”",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "At this point, the sample’s MIDI device is available to CoreMIDI. To inspect the newly installed device, use the Audio MIDI Setup app (",
              "type": "text"
            },
            {
              "code": "Applications/Utilities",
              "type": "codeVoice"
            },
            {
              "text": "), which shows the CreatingMIDIDriverSampleAppDevice on the MIDI pane with one port. You can change the number of ports and toggle the offline property there, or in the CreatingMIDIDriverSampleApp app’s User Client Manager section. Click Open User Client to open a connection from the app to the driver. Then you can use the other buttons in this section to toggle the offline property and to add or remove ports.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To use the driver, you can use any app that supports MIDI input and output, and select CreatingMIDIDriverSampleAppDevice’s sources or destinations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To uninstall the driver, delete the sample app, which also stops and removes the driver extension (dext). You can also use ",
              "type": "text"
            },
            {
              "code": "systemextensionsctl",
              "type": "codeVoice"
            },
            {
              "text": " from the command line to list and selectively uninstall system extensions like ",
              "type": "text"
            },
            {
              "code": "com.example.apple-samplecode.ExampleDriver.Driver",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Run-the-sample-app-in-iPadOS",
          "level": 3,
          "text": "Run the sample app in iPadOS",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To run the sample app in iPadOS, connect an iPad device with an M-series chip to your Mac. Use the scheme selector to select the CreatingMIDIDriverSampleApp scheme and the name of your iPad as the destination. Run the app directly from Xcode to launch it on your iPad.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In iPadOS, the CreatingMIDIDriverSampleApp app doesn’t show the Driver Manager section because the app isn’t responsible for installing the driver like it is in macOS. Instead, choose Settings > Privacy & Security > Drivers, and enable the driver there.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After enabling the driver, return to the CreatingMIDIDriverSampleApp app to open a user client connection and modify the device’s offline property or change the number of ports.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you finish using the driver, delete the app, which deletes the driver as well.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-driver-and-device-classes",
          "level": 3,
          "text": "Create driver and device classes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To create a MIDIDriverKit driver, the sample creates a driver that subclasses ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididriver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and a device that subclasses ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The dext’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file contains entries that identify the driver class to MIDIDriverKit, which instantiates and initializes the driver. The sample’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file shows how this works: the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserclass?language=objc",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key maps to the class name string ",
              "type": "text"
            },
            {
              "code": "CreatingMIDIDriverSampleAppDriver",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserservername?language=objc",
              "isActive": true,
              "overridingTitle": "IOUserServerName",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserServerName",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " contains the bundle ID.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The driver subclass is the entry point into the dext, while the device subclass handles start and stop I/O-related messages and configuration messages. The device also owns various ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermidiobject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances for things like timer dispatch sources. In an actual hardware driver, the device class is also responsible for communication with the hardware over USB or PCI, and requires appropriate DriverKit entitlements for those transports. The sample doesn’t actually connect to hardware, and instead provides a virtual device with virtual MIDI sources and MIDI destinations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After initialization, DriverKit calls the driver’s ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/kernel/ioservice/3180710-start",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. The implementation in ",
              "type": "text"
            },
            {
              "code": "CreatingMIDIDriverSampleAppDriver",
              "type": "codeVoice"
            },
            {
              "text": " creates and configures the ",
              "type": "text"
            },
            {
              "code": "CreatingMIDIDriverSampleAppDevice",
              "type": "codeVoice"
            },
            {
              "text": " instance and, if successful, calls ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/kernel/ioservice/3180701-registerservice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to let the system know the driver is running.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "kern_return_t IMPL(CreatingMIDIDriverSampleAppDriver, Start)",
            "{",
            "\tDebugMsg(\"+\");",
            "\tbool success = true;",
            "",
            "\tOSSharedPtr<OSString> deviceName(OSString::withCString(\"CreatingMIDIDriverSampleAppDevice\"), OSNoRetain);",
            "\tOSSharedPtr<OSString> modelUID(OSString::withCString(\"CreatingMIDIDriverSampleAppDevice-Model\"), OSNoRetain);",
            "\tOSSharedPtr<OSString> manufacturerUID(OSString::withCString(\"Apple Inc.\"), OSNoRetain);",
            "",
            "\tkern_return_t error = Start(provider, SUPERDISPATCH);",
            "\tif (error)",
            "\t{",
            "\t\tDebugMsg(\"Failed to start Super\");",
            "\t\tgoto Failure;",
            "\t}",
            "",
            "\t// Get the service's default dispatch queue from the driver object.",
            "\tivars->mWorkQueue = GetWorkQueue();",
            "\tif (ivars->mWorkQueue.get() == nullptr)",
            "\t{",
            "\t\tDebugMsg(\"Failed to get default work queue\");",
            "\t\terror = kIOReturnInvalid;",
            "\t\tgoto Failure;",
            "\t}",
            "",
            "\tivars->mCreatingMIDIDriverSampleAppDevice = OSSharedPtr(OSTypeAlloc(CreatingMIDIDriverSampleAppDevice), OSNoRetain);",
            "\tif (ivars->mCreatingMIDIDriverSampleAppDevice.get() == nullptr)",
            "\t{",
            "\t\tDebugMsg(\"Failed to allocate CreatingMIDIDriverSampleAppDevice\");",
            "\t\terror = kIOReturnNoMemory;",
            "\t\tgoto Failure;",
            "\t}",
            "",
            "\tsuccess = ivars->mCreatingMIDIDriverSampleAppDevice->init(this, deviceName.get(), modelUID.get(), manufacturerUID.get());",
            "\tif (!success)",
            "\t{",
            "\t\tDebugMsg(\"Failed to init CreatingMIDIDriverSampleAppDevice\");",
            "\t\terror = kIOReturnNoMemory;",
            "\t\tgoto Failure;",
            "\t}",
            "",
            "\tAddObject(ivars->mCreatingMIDIDriverSampleAppDevice.get());",
            "",
            "\t// Register the service",
            "\terror = RegisterService();",
            "\tif (error)",
            "\t{",
            "\t\tDebugMsg(\"Failed to register service\");",
            "\t\tgoto Failure;",
            "\t}",
            "",
            "\treturn kIOReturnSuccess;",
            "",
            "Failure:",
            "",
            "\tivars->mCreatingMIDIDriverSampleAppDevice.reset();",
            "\treturn error;",
            "}"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "anchor": "Implement-a-user-client-interface",
          "level": 3,
          "text": "Implement a user client interface",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There are two dictionaries in the ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file that define how the driver acts as a user client to CoreMIDI and to other apps. The first dictionary, ",
              "type": "text"
            },
            {
              "code": "IOUserMIDIDriverUserClientProperties",
              "type": "codeVoice"
            },
            {
              "text": ", maps ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/ioclass?language=objc",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "IOUserUserClient",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserclass?language=objc",
              "isActive": true,
              "overridingTitle": "IOUserClass",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserClass",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "IOUserMIDIDriverUserClient",
              "type": "codeVoice"
            },
            {
              "text": ". This allows CoreMIDI to connect to the driver. To support user client connections from apps, the sample also defines a custom user client class. The dictionary for the custom user client has the key ",
              "type": "text"
            },
            {
              "code": "CreatingMIDIDriverSampleAppUserClientProperties",
              "type": "codeVoice"
            },
            {
              "text": ", and its ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserclass?language=objc",
              "isActive": true,
              "overridingTitle": "IOUserClass",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserClass",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " has the value ",
              "type": "text"
            },
            {
              "code": "CreatingMIDIDriverSampleAppDriverUserClient",
              "type": "codeVoice"
            },
            {
              "text": ", a custom subclass of ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/driverkit/iouserclient",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Drivers that don’t accept user client connections from apps don’t need this second dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When CoreMIDI requires a new user client connection to the dext, it calls the driver’s ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/driverkit/ioservice/3325581-newuserclient",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. In the sample, the implementation of this method serves two purposes. If the incoming client type is ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/mididriverkit_kiousermidiobjectiddriver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", this is a request from CoreMIDI. In this case, the driver just forwards the call to the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididriver",
              "isActive": true,
              "overridingTitle": "IOUserMIDIDriver",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserMIDIDriver",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " superclass. For other client types, such as apps connecting to the driver, it uses the ",
              "type": "text"
            },
            {
              "code": "CreatingMIDIDriverSampleAppUserClientProperties",
              "type": "codeVoice"
            },
            {
              "text": " values from the ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file to create an instance of the custom ",
              "type": "text"
            },
            {
              "code": "CreatingMIDIDriverSampleAppDriverUserClient",
              "type": "codeVoice"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "kern_return_t IMPL(CreatingMIDIDriverSampleAppDriver, NewUserClient)",
            "{",
            "\tDebugMsg(\"type: %u out_user-client: %p\", type, userClient);",
            "\tkern_return_t error = kIOReturnSuccess;",
            "",
            "\t//\tHave the superclass create the `IOUserMIDIDriverUserClient` object if the type is",
            "\t//\tkIOUserMIDIDriverUserClientType.",
            "\tif (type == kIOUserMIDIDriverUserClientType)",
            "\t{",
            "\t\terror = super::NewUserClient(type, userClient, SUPERDISPATCH);",
            "\t\tif (error)",
            "\t\t{",
            "\t\t\tDebugMsg(\"Failed to create user client\");",
            "\t\t\tgoto Failure;",
            "\t\t}",
            "\t\tif (*userClient == nullptr)",
            "\t\t{",
            "\t\t\tDebugMsg(\"Failed to create user client\");",
            "\t\t\terror = kIOReturnNoMemory;",
            "\t\t\tgoto Failure;",
            "\t\t}",
            "\t}",
            "\telse",
            "\t{",
            "\t\tIOService* userClientService = nullptr;",
            "\t\terror = Create(this, \"CreatingMIDIDriverSampleAppUserClientProperties\", &userClientService);",
            "\t\tif (error != kIOReturnSuccess)",
            "\t\t{",
            "\t\t\tDebugMsg(\"failed to create the CreatingMIDIDriverSampleAppDriver user-client\");",
            "\t\t\tgoto Failure;",
            "",
            "\t\t}",
            "\t\t*userClient = OSDynamicCast(IOUserClient, userClientService);",
            "\t}",
            "",
            "Failure:",
            "\treturn error;",
            "}"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "anchor": "Create-MIDI-objects-and-set-properties-in-the-device-initializer",
          "level": 3,
          "text": "Create MIDI objects and set properties in the device initializer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The device class manages the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermidientity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " interfaces containing ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermidisource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididestination",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects that perform MIDI I/O.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the sample, the ",
              "type": "text"
            },
            {
              "code": "CreatingMIDIDriverSampleAppDevice",
              "type": "codeVoice"
            },
            {
              "text": " initializer method declares one instance of ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermidientity",
              "isActive": true,
              "overridingTitle": "IOUserMIDIEntity",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserMIDIEntity",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": ", including one of each ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermidisource",
              "isActive": true,
              "overridingTitle": "IOUserMIDISource",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserMIDISource",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididestination",
              "isActive": true,
              "overridingTitle": "IOUserMIDIDestination",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserMIDIDestination",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " objects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "\tauto entityName = CreateEntityName(1);",
            "\tauto entity = IOUserMIDIEntity::Create(driver,",
            "\t\t\t\t\t\t\t\t\t\t   this,",
            "\t\t\t\t\t\t\t\t\t\t   entityName.get(),",
            "\t\t\t\t\t\t\t\t\t\t   IOUserMIDIProtocolID::MIDIProtocol_2_0,",
            "\t\t\t\t\t\t\t\t\t\t   1, 1);",
            "\tAddEntity(entity.get());",
            "",
            "\tSetupEntities();",
            "\t",
            "\tSetProperty(IOUserMIDIProperty::Offline, offline.get());"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "anchor": "Set-up-IO-for-MIDI-sources-and-MIDI-destinations",
          "level": 3,
          "text": "Set up I/O for MIDI sources and MIDI destinations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To receive MIDI data coming from CoreMIDI, each destination needs to set the I/O block. The sample routes each destination to its corresponding source to implement a virtual driver.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "void CreatingMIDIDriverSampleAppDevice::SetupEntities()",
            "{",
            "\tivars->mDestinations = OSSharedPtr(OSArray::withCapacity(1), OSNoRetain);",
            "",
            "\tGetEntities()->iterateObjects(^bool(OSObject* object){",
            "\t\tauto e = OSDynamicCast(IOUserMIDIEntity, object);",
            "\t\tif (e != nullptr)",
            "\t\t{",
            "\t\t\tauto source = e->GetSource(0);",
            "\t\t\tauto destination = e->GetDestination(0);",
            "\t\t\tauto ioBlock = ^kern_return_t(IOUserMIDIUMPWord const* umpWords, size_t numWords) {",
            "\t\t\t\treturn source->Send(umpWords, numWords);",
            "\t\t\t};",
            "\t\t\tdestination->SetIOBlock(ioBlock);",
            "\t\t}",
            "\t\treturn false;",
            "\t});",
            "}"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "anchor": "Start-device-IO",
          "level": 3,
          "text": "Start device I/O",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When CoreMIDI attempts to start I/O on the device, it calls ",
              "type": "text"
            },
            {
              "code": "CreatingMIDIDriverSampleAppDevice::StartIO",
              "type": "codeVoice"
            },
            {
              "text": ". MIDIDriverKit provides this method to signal the driver to perform any necessary calls to start I/O on the device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "kern_return_t CreatingMIDIDriverSampleAppDevice::StartIO()",
            "{",
            "\tDebugMsg(\"StartIO: device %u\", GetObjectID());",
            "",
            "\t__block kern_return_t error = kIOReturnSuccess;",
            "",
            "\tivars->mWorkQueue->DispatchSync(^{",
            "\t\t// Tell IOUserMIDIObject base class to start I/O for the device.",
            "\t\terror = super::StartIO();",
            "\t\tif (error) {",
            "\t\t\tDebugMsg(\"Failed to start I/O, error %d\", error);",
            "\t\t\tsuper::StopIO();",
            "\t\t}",
            "\t});",
            "",
            "\tif (error == kIOReturnSuccess) {",
            "\t\tauto offline = OSSharedPtr(OSNumber::withNumber(uint64_t{0}, 32), OSNoRetain);",
            "\t\tSetProperty(IOUserMIDIProperty::Offline, offline.get());",
            "\t}",
            "\t\t",
            "\treturn error;",
            "}"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "anchor": "Handle-configuration-changes",
          "level": 3,
          "text": "Handle configuration changes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "At this point, the driver and device can supply a MIDI port with one source and one destination as if it’s coming from an external device. One other task a driver needs to support is handling configuration changes from the device. Three methods from ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice",
              "isActive": true,
              "overridingTitle": "IOUserMIDIDevice",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserMIDIDevice",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " support this ability:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407883-requestdeviceconfigurationchange",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — A driver calls this method on the device prior to any configuration action. MIDIDriverKit temporarily shuts down ports — calling the device’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4337352-stopio",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " callback — so that the device class can perform the configuration change.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407882-performdeviceconfigurationchange",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — MIDIDriverKit calls this method after stopping any running I/O, signaling to the device class that it can perform its configuration change. This is where the device can change the number of ports, source, and destination, or perform other changes that are only safe while I/O isn’t occurring. After this method returns, MIDIDriverKit restarts I/O, if necessary, calling the device’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4337351-startio",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " callback.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407881-abortdeviceconfigurationchange",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — A driver calls this method to stop a change from a request to ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407883-requestdeviceconfigurationchange",
                      "isActive": true,
                      "overridingTitle": "RequestDeviceConfigurationChange",
                      "overridingTitleInlineContent": [
                        {
                          "code": "RequestDeviceConfigurationChange",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": ". The sample doesn’t need to perform any additional work to implement this method, so it just calls its superclass’s implementation.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "In the sample code project, changing the number of ports provides an example of how to perform a configuration change. When a person taps the Add Port button, the app makes a user client call to the driver’s ",
              "type": "text"
            },
            {
              "code": "HandleAddPort",
              "type": "codeVoice"
            },
            {
              "text": " method. The driver calls into the device’s ",
              "type": "text"
            },
            {
              "code": "AddPort",
              "type": "codeVoice"
            },
            {
              "text": " method, which calls ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407883-requestdeviceconfigurationchange",
              "isActive": true,
              "overridingTitle": "RequestDeviceConfigurationChange",
              "overridingTitleInlineContent": [
                {
                  "code": "RequestDeviceConfigurationChange",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": ". The latter tells MIDIDriverKit to shut down I/O and then make a callback to ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407882-performdeviceconfigurationchange",
              "isActive": true,
              "overridingTitle": "PerformDeviceConfigurationChange",
              "overridingTitleInlineContent": [
                {
                  "code": "PerformDeviceConfigurationChange",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "kern_return_t CreatingMIDIDriverSampleAppDriver::HandleAddPort()",
            "{",
            "\t__block kern_return_t ret = kIOReturnSuccess;",
            "\tivars->mWorkQueue->DispatchSync(^(){",
            "\t\tret = ivars->mCreatingMIDIDriverSampleAppDevice->AddPort();",
            "\t});",
            "\treturn ret;",
            "}"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "code": [
            "kern_return_t CreatingMIDIDriverSampleAppDevice::AddPort()",
            "{",
            "\tauto changeInfo = OSSharedPtr(OSString::withCString(\"Add Port\"), OSNoRetain);",
            "\tif (GetDeviceIsRunning())",
            "\t{",
            "\t\treturn RequestDeviceConfigurationChange(kAddPortConfigChangeAction, changeInfo.get());",
            "\t}",
            "\telse",
            "\t{",
            "\t\treturn PerformDeviceConfigurationChange(kAddPortConfigChangeAction, changeInfo.get());",
            "\t}",
            "}"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The implementation of ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407882-performdeviceconfigurationchange",
              "isActive": true,
              "overridingTitle": "PerformDeviceConfigurationChange",
              "overridingTitleInlineContent": [
                {
                  "code": "PerformDeviceConfigurationChange",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " starts by logging a string it receives from the initial callback in the app. Then it adds the new ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermidientity",
              "isActive": true,
              "overridingTitle": "IOUserMIDIEntity",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserMIDIEntity",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " with each ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermidisource",
              "isActive": true,
              "overridingTitle": "IOUserMIDISource",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserMIDISource",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididestination",
              "isActive": true,
              "overridingTitle": "IOUserMIDIDestination",
              "overridingTitleInlineContent": [
                {
                  "code": "IOUserMIDIDestination",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": ". Assuming this succeeds, it sets up the callback blocks for I/O. Finally, it calls the superclass’s implementation of ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407882-performdeviceconfigurationchange",
              "isActive": true,
              "overridingTitle": "PerformDeviceConfigurationChange",
              "overridingTitleInlineContent": [
                {
                  "code": "PerformDeviceConfigurationChange",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "kern_return_t CreatingMIDIDriverSampleAppDevice::PerformDeviceConfigurationChange(",
            "\t\tuint64_t changeAction, OSObject* changeInfo)",
            "{",
            "",
            "\tDebugMsg(\"change action %llu\", changeAction);",
            "\tkern_return_t ret = kIOReturnSuccess;",
            "\tswitch (changeAction) {",
            "\t\t// Add custom configuration change handlers.",
            "\t\tcase kAddPortConfigChangeAction:",
            "\t\t{",
            "\t\t\tif (changeInfo)",
            "\t\t\t{",
            "\t\t\t\tauto changeInfoString = OSDynamicCast(OSString, changeInfo);",
            "\t\t\t\tDebugMsg(\"%s\", changeInfoString->getCStringNoCopy());",
            "\t\t\t}",
            "\t\t\tauto entities = GetEntities();",
            "\t\t\tif (entities.get() != nullptr) {",
            "\t\t\t\tauto index = entities->getCount() + 1;",
            "\t\t\t\tauto entityName = CreateEntityName(index);",
            "\t\t\t\tauto entity = IOUserMIDIEntity::Create(ivars->mDriver.get(),",
            "\t\t\t\t\t\t\t\t\t\t\t\t\t   this,",
            "\t\t\t\t\t\t\t\t\t\t\t\t\t   entityName.get(),",
            "\t\t\t\t\t\t\t\t\t\t\t\t\t   IOUserMIDIProtocolID::MIDIProtocol_2_0,",
            "\t\t\t\t\t\t\t\t\t\t\t\t\t   1, 1);",
            "\t\t\t\tAddEntity(entity.get());",
            "\t\t\t\tSetupEntities();",
            "\t\t\t}",
            "\t\t\tbreak;",
            "\t\t}",
            "",
            "\t\tdefault:",
            "\t\t\tret = super::PerformDeviceConfigurationChange(changeAction, changeInfo);",
            "\t\t\tbreak;",
            "\t}",
            "\treturn ret;",
            "}"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When this method returns, the configuration change is complete, and the system resumes I/O with the device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "3da01fc79284/CreatingAMIDIDeviceDriver.zip": {
      "checksum": "3da01fc7928426e2e19f701e494e69e4fb63ac23e585157c7011c1d36e4b62135c636bbd329e7fb0d99cdcba50d9d7de8a5506dcbccfc2e3a8641f71417e8657",
      "identifier": "3da01fc79284/CreatingAMIDIDeviceDriver.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/3da01fc79284/CreatingAMIDIDeviceDriver.zip"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against devices that support MIDI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.midi",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mididriverkit/documentation/MIDIDriverKit": {
      "abstract": [
        {
          "text": "Develop drivers for MIDI devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mididriverkit/documentation/MIDIDriverKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MIDIDriverKit",
      "type": "topic",
      "url": "/documentation/mididriverkit"
    },
    "https://developer.apple.com/documentation//driverkit/debugging_and_testing_system_extensions": {
      "identifier": "https://developer.apple.com/documentation//driverkit/debugging_and_testing_system_extensions",
      "title": "Debugging and testing system extensions",
      "titleInlineContent": [
        {
          "text": "Debugging and testing system extensions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation//driverkit/debugging_and_testing_system_extensions"
    },
    "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit?language=objc": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit?language=objc",
      "title": "com.apple.developer.driverkit",
      "titleInlineContent": [
        {
          "code": "com.apple.developer.driverkit",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit?language=objc"
    },
    "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit_communicates-with-drivers?language=objc": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit_communicates-with-drivers?language=objc",
      "title": "Communicates with Drivers",
      "titleInlineContent": [
        {
          "text": "Communicates with Drivers",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit_communicates-with-drivers?language=objc"
    },
    "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit_userclient-access?language=objc": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit_userclient-access?language=objc",
      "title": "com.apple.developer.driverkit.userclient-access",
      "titleInlineContent": [
        {
          "code": "com.apple.developer.driverkit.userclient-access",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit_userclient-access?language=objc"
    },
    "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_system-extension_install?language=objc": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_system-extension_install?language=objc",
      "title": "System Extension",
      "titleInlineContent": [
        {
          "text": "System Extension",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_system-extension_install?language=objc"
    },
    "https://developer.apple.com/documentation/bundleresources/information_property_list/ioclass?language=objc": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/ioclass?language=objc",
      "title": "IOClass",
      "titleInlineContent": [
        {
          "code": "IOClass",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/information_property_list/ioclass?language=objc"
    },
    "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserclass?language=objc": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserclass?language=objc",
      "title": "IOUserClass",
      "titleInlineContent": [
        {
          "code": "IOUserClass",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserclass?language=objc"
    },
    "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserservername?language=objc": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserservername?language=objc",
      "title": "IOUserServerName",
      "titleInlineContent": [
        {
          "code": "IOUserServerName",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/information_property_list/iouserservername?language=objc"
    },
    "https://developer.apple.com/documentation/driverkit/ioservice/3325581-newuserclient": {
      "identifier": "https://developer.apple.com/documentation/driverkit/ioservice/3325581-newuserclient",
      "title": "NewUserClient",
      "titleInlineContent": [
        {
          "code": "NewUserClient",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/driverkit/ioservice/3325581-newuserclient"
    },
    "https://developer.apple.com/documentation/driverkit/iouserclient": {
      "identifier": "https://developer.apple.com/documentation/driverkit/iouserclient",
      "title": "IOUserClient",
      "titleInlineContent": [
        {
          "code": "IOUserClient",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/driverkit/iouserclient"
    },
    "https://developer.apple.com/documentation/driverkit/requesting_entitlements_for_driverkit_development": {
      "identifier": "https://developer.apple.com/documentation/driverkit/requesting_entitlements_for_driverkit_development",
      "title": "Requesting Entitlements for DriverKit Development",
      "titleInlineContent": [
        {
          "text": "Requesting Entitlements for DriverKit Development",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/driverkit/requesting_entitlements_for_driverkit_development"
    },
    "https://developer.apple.com/documentation/kernel/ioservice/3180701-registerservice": {
      "identifier": "https://developer.apple.com/documentation/kernel/ioservice/3180701-registerservice",
      "title": "RegisterService",
      "titleInlineContent": [
        {
          "code": "RegisterService",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/kernel/ioservice/3180701-registerservice"
    },
    "https://developer.apple.com/documentation/kernel/ioservice/3180710-start": {
      "identifier": "https://developer.apple.com/documentation/kernel/ioservice/3180710-start",
      "title": "Start",
      "titleInlineContent": [
        {
          "code": "Start",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/kernel/ioservice/3180710-start"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermididestination": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididestination",
      "title": "IOUserMIDIDestination",
      "titleInlineContent": [
        {
          "code": "IOUserMIDIDestination",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermididestination"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermididevice": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice",
      "title": "IOUserMIDIDevice",
      "titleInlineContent": [
        {
          "code": "IOUserMIDIDevice",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermididevice"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4337351-startio": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4337351-startio",
      "title": "StartIO",
      "titleInlineContent": [
        {
          "code": "StartIO",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4337351-startio"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4337352-stopio": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4337352-stopio",
      "title": "StopIO",
      "titleInlineContent": [
        {
          "code": "StopIO",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4337352-stopio"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407881-abortdeviceconfigurationchange": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407881-abortdeviceconfigurationchange",
      "title": "AbortDeviceConfigurationChange",
      "titleInlineContent": [
        {
          "code": "AbortDeviceConfigurationChange",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407881-abortdeviceconfigurationchange"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407882-performdeviceconfigurationchange": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407882-performdeviceconfigurationchange",
      "title": "PerformDeviceConfigurationChange",
      "titleInlineContent": [
        {
          "code": "PerformDeviceConfigurationChange",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407882-performdeviceconfigurationchange"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407883-requestdeviceconfigurationchange": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407883-requestdeviceconfigurationchange",
      "title": "RequestDeviceConfigurationChange",
      "titleInlineContent": [
        {
          "code": "RequestDeviceConfigurationChange",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermididevice/4407883-requestdeviceconfigurationchange"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermididriver": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermididriver",
      "title": "IOUserMIDIDriver",
      "titleInlineContent": [
        {
          "code": "IOUserMIDIDriver",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermididriver"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermidientity": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermidientity",
      "title": "IOUserMIDIEntity",
      "titleInlineContent": [
        {
          "code": "IOUserMIDIEntity",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermidientity"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermidiobject": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermidiobject",
      "title": "IOUserMIDIObject",
      "titleInlineContent": [
        {
          "code": "IOUserMIDIObject",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermidiobject"
    },
    "https://developer.apple.com/documentation/mididriverkit/iousermidisource": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/iousermidisource",
      "title": "IOUserMIDISource",
      "titleInlineContent": [
        {
          "code": "IOUserMIDISource",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/iousermidisource"
    },
    "https://developer.apple.com/documentation/mididriverkit/mididriverkit_kiousermidiobjectiddriver": {
      "identifier": "https://developer.apple.com/documentation/mididriverkit/mididriverkit_kiousermidiobjectiddriver",
      "title": "kIOUserMIDIDriverUserClientType",
      "titleInlineContent": [
        {
          "code": "kIOUserMIDIDriverUserClientType",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mididriverkit/mididriverkit_kiousermidiobjectiddriver"
    },
    "https://developer.apple.com/documentation/xcode/preparing-your-app-for-distribution": {
      "identifier": "https://developer.apple.com/documentation/xcode/preparing-your-app-for-distribution",
      "title": "Preparing Your App For Distribution",
      "titleInlineContent": [
        {
          "text": "Preparing Your App For Distribution",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/xcode/preparing-your-app-for-distribution"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "3da01fc79284/CreatingAMIDIDeviceDriver.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi"
              ],
              "title": "Essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mididriverkit/creating-a-midi-device-driver"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mididriverkit/creating-a-midi-device-driver"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
