{
  "abstract": [
    {
      "text": "Returns a font that matches the specified font descriptor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIFont"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIFont/init(descriptor:size:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIFont(cm)fontWithDescriptor:size:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "descriptor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIFontDescriptor",
        "text": "UIFontDescriptor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "size"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "fontWithDescriptor:size:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(descriptor:size:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "descriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIFontDescriptor",
              "text": "UIFontDescriptor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "size"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pointSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The font descriptor to match.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "descriptor"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The size in points to which the font is scaled. If greater than 0.0, it has precedence over ",
                  "type": "text"
                },
                {
                  "code": "UIFontDescriptorSizeAttribute",
                  "type": "codeVoice"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "descriptor",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pointSize"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A font object for the specified descriptor and size.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In most cases, you can simply use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont/init(name:size:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to create standard scaled fonts.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFont": {
      "abstract": [
        {
          "text": "An object that provides access to the font’s characteristics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFont"
        }
      ],
      "role": "symbol",
      "title": "UIFont",
      "type": "topic",
      "url": "/documentation/uikit/uifont"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFont/TextStyle": {
      "abstract": [
        {
          "text": "Constants that describe the preferred styles for fonts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont/TextStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextStyle"
        }
      ],
      "role": "symbol",
      "title": "UIFont.TextStyle",
      "type": "topic",
      "url": "/documentation/uikit/uifont/textstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFont/init(descriptor:size:)": {
      "abstract": [
        {
          "text": "Returns a font that matches the specified font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFontDescriptor",
          "text": "UIFontDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont/init(descriptor:size:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontWithDescriptor:size:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:size:)",
      "type": "topic",
      "url": "/documentation/uikit/uifont/init(descriptor:size:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFont/init(name:size:)": {
      "abstract": [
        {
          "text": "Creates and returns a font object for the specified font name and size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont/init(name:size:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontWithName:size:"
        }
      ],
      "role": "symbol",
      "title": "init(name:size:)",
      "type": "topic",
      "url": "/documentation/uikit/uifont/init(name:size:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFont/preferredFont(forTextStyle:)": {
      "abstract": [
        {
          "text": "Returns an instance of the system font for the specified text style with scaling for the user’s selected content size category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTextStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIFontTextStyle",
          "text": "TextStyle"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont/preferredFont(forTextStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredFontForTextStyle:"
        }
      ],
      "role": "symbol",
      "title": "preferredFont(forTextStyle:)",
      "type": "topic",
      "url": "/documentation/uikit/uifont/preferredfont(fortextstyle:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFont/preferredFont(forTextStyle:compatibleWith:)": {
      "abstract": [
        {
          "text": "Returns an instance of the system font for the appropriate text style and traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTextStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIFontTextStyle",
          "text": "TextStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "compatibleWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont/preferredFont(forTextStyle:compatibleWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredFontForTextStyle:compatibleWithTraitCollection:"
        }
      ],
      "role": "symbol",
      "title": "preferredFont(forTextStyle:compatibleWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uifont/preferredfont(fortextstyle:compatiblewith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFont/withSize(_:)": {
      "abstract": [
        {
          "text": "Returns a font object that is the same as the font, but has the specified size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont/withSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontWithSize:"
        }
      ],
      "role": "symbol",
      "title": "withSize(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uifont/withsize(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor": {
      "abstract": [
        {
          "text": "A collection of attributes that describes a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "UIFontDescriptor",
      "type": "topic",
      "url": "/documentation/uikit/uifontdescriptor"
    },
    "doc://com.apple.uikit/documentation/UIKit/creating-self-sizing-table-view-cells": {
      "abstract": [
        {
          "text": "Create table view cells that support Dynamic Type and use system spacing constraints to adjust the spacing surrounding text labels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/creating-self-sizing-table-view-cells",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating self-sizing table view cells",
      "type": "topic",
      "url": "/documentation/uikit/creating-self-sizing-table-view-cells"
    },
    "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically": {
      "abstract": [
        {
          "text": "Scale text in your interface automatically using Dynamic Type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically",
      "kind": "article",
      "role": "article",
      "title": "Scaling Fonts Automatically",
      "type": "topic",
      "url": "/documentation/uikit/scaling-fonts-automatically"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Fonts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically",
        "doc://com.apple.uikit/documentation/UIKit/creating-self-sizing-table-view-cells",
        "doc://com.apple.uikit/documentation/UIKit/UIFont/preferredFont(forTextStyle:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFont/preferredFont(forTextStyle:compatibleWith:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFont/TextStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIFont/init(name:size:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFont/withSize(_:)"
      ],
      "title": "Creating Fonts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "fontWithDescriptor:size:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fontWithDescriptor:size:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIFont"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Fonts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically",
                "doc://com.apple.uikit/documentation/UIKit/creating-self-sizing-table-view-cells",
                "doc://com.apple.uikit/documentation/UIKit/UIFont/preferredFont(forTextStyle:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFont/preferredFont(forTextStyle:compatibleWith:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFont/TextStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIFont/init(name:size:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFont/withSize(_:)"
              ],
              "title": "Creating Fonts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIFont",
                    "text": "UIFont"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "fontWithDescriptor:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIFontDescriptor",
                    "text": "UIFontDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "descriptor"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "size:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "pointSize"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The font descriptor to match.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "descriptor"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The size in points to which the font is scaled. If greater than 0.0, it has precedence over ",
                        "type": "text"
                      },
                      {
                        "code": "UIFontDescriptorSizeAttribute",
                        "type": "codeVoice"
                      },
                      {
                        "text": " in ",
                        "type": "text"
                      },
                      {
                        "code": "descriptor",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "pointSize"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A font object for the specified descriptor and size.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1init(name:size:)/title",
          "value": "fontWithName:size:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1init(name:size:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fontWithName:size:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1preferredFont(forTextStyle:)/title",
          "value": "preferredFontForTextStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1preferredFont(forTextStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "preferredFontForTextStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1TextStyle/title",
          "value": "UIFontTextStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1TextStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1TextStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1withSize(_:)/title",
          "value": "fontWithSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1withSize(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fontWithSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1init(descriptor:size:)/title",
          "value": "fontWithDescriptor:size:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1init(descriptor:size:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fontWithDescriptor:size:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1preferredFont(forTextStyle:compatibleWith:)/title",
          "value": "preferredFontForTextStyle:compatibleWithTraitCollection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1preferredFont(forTextStyle:compatibleWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "preferredFontForTextStyle:compatibleWithTraitCollection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/title",
          "value": "UIFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontDescriptor/title",
          "value": "UIFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uifont/init(descriptor:size:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uifont/init(descriptor:size:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
