{
  "abstract": [
    {
      "text": "Creates a new workout with a single goal.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.workoutkit/documentation/WorkoutKit",
        "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout/init(activity:location:swimmingLocation:goal:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:10WorkoutKit010SingleGoalA0V8activity8location16swimmingLocation4goalACSo21HKWorkoutActivityTypeV_So0j7SessionhL0VSo0j8SwimminghL0VAA0aD0Otcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "activity"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@HKWorkoutActivityType",
        "text": "HKWorkoutActivityType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "location"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@HKWorkoutSessionLocationType",
        "text": "HKWorkoutSessionLocationType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "swimmingLocation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@HKWorkoutSwimmingLocationType",
        "text": "HKWorkoutSwimmingLocationType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "goal"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10WorkoutKit0A4GoalO",
        "text": "WorkoutGoal"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "WorkoutKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(activity:location:swimmingLocation:goal:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "activity"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@HKWorkoutActivityType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@HKWorkoutActivityType",
              "text": "HKWorkoutActivityType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "location"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@HKWorkoutSessionLocationType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@HKWorkoutSessionLocationType",
              "text": "HKWorkoutSessionLocationType"
            },
            {
              "kind": "text",
              "text": " = .unknown, "
            },
            {
              "kind": "externalParam",
              "text": "swimmingLocation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@HKWorkoutSwimmingLocationType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@HKWorkoutSwimmingLocationType",
              "text": "HKWorkoutSwimmingLocationType"
            },
            {
              "kind": "text",
              "text": " = .unknown, "
            },
            {
              "kind": "externalParam",
              "text": "goal"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.workoutkit/documentation/WorkoutKit/WorkoutGoal",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10WorkoutKit0A4GoalO",
              "text": "WorkoutGoal"
            },
            {
              "kind": "text",
              "text": " = .open)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The workout activity type.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "activity"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The workout location.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "location"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "For swimming workouts, the workout’s swimming location.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "swimmingLocation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The goal for the workout.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "goal"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.workoutkit/documentation/WorkoutKit": {
      "abstract": [
        {
          "text": "Create, preview, and sync workout compositions to the Workout app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.workoutkit/documentation/WorkoutKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WorkoutKit",
      "type": "topic",
      "url": "/documentation/workoutkit"
    },
    "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout": {
      "abstract": [
        {
          "text": "A workout with a single goal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SingleGoalWorkout"
        }
      ],
      "identifier": "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SingleGoalWorkout"
        }
      ],
      "role": "symbol",
      "title": "SingleGoalWorkout",
      "type": "topic",
      "url": "/documentation/workoutkit/singlegoalworkout"
    },
    "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout/init(activity:location:swimmingLocation:goal:)": {
      "abstract": [
        {
          "text": "Creates a new workout with a single goal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "activity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKWorkoutActivityType",
          "text": "HKWorkoutActivityType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKWorkoutSessionLocationType",
          "text": "HKWorkoutSessionLocationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "swimmingLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKWorkoutSwimmingLocationType",
          "text": "HKWorkoutSwimmingLocationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "goal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10WorkoutKit0A4GoalO",
          "text": "WorkoutGoal"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout/init(activity:location:swimmingLocation:goal:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(activity:location:swimmingLocation:goal:)",
      "type": "topic",
      "url": "/documentation/workoutkit/singlegoalworkout/init(activity:location:swimminglocation:goal:)"
    },
    "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout/supportsActivity(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the system supports the provided workout activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsActivity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKWorkoutActivityType",
          "text": "HKWorkoutActivityType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout/supportsActivity(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportsActivity(_:)",
      "type": "topic",
      "url": "/documentation/workoutkit/singlegoalworkout/supportsactivity(_:)"
    },
    "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout/supportsGoal(_:activity:location:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that determines whether the system supports the provided goal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsGoal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10WorkoutKit0A4GoalO",
          "text": "WorkoutGoal"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "activity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKWorkoutActivityType",
          "text": "HKWorkoutActivityType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKWorkoutSessionLocationType",
          "text": "HKWorkoutSessionLocationType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout/supportsGoal(_:activity:location:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportsGoal(_:activity:location:)",
      "type": "topic",
      "url": "/documentation/workoutkit/singlegoalworkout/supportsgoal(_:activity:location:)"
    },
    "doc://com.apple.workoutkit/documentation/WorkoutKit/WorkoutGoal": {
      "abstract": [
        {
          "text": "A value that specifies the goal for a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WorkoutGoal"
        }
      ],
      "identifier": "doc://com.apple.workoutkit/documentation/WorkoutKit/WorkoutGoal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WorkoutGoal"
        }
      ],
      "role": "symbol",
      "title": "WorkoutGoal",
      "type": "topic",
      "url": "/documentation/workoutkit/workoutgoal"
    },
    "doc://com.externally.resolved.symbol/c:@E@HKWorkoutActivityType": {
      "abstract": [
        {
          "text": "The type of activity performed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@HKWorkoutActivityType",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKWorkoutActivityType",
      "type": "topic",
      "url": "/documentation/HealthKit/HKWorkoutActivityType"
    },
    "doc://com.externally.resolved.symbol/c:@E@HKWorkoutSessionLocationType": {
      "abstract": [
        {
          "text": "A constant indicating whether the workout session takes place indoors or outdoors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionLocationType"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@HKWorkoutSessionLocationType",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKWorkoutSessionLocationType",
      "type": "topic",
      "url": "/documentation/HealthKit/HKWorkoutSessionLocationType"
    },
    "doc://com.externally.resolved.symbol/c:@E@HKWorkoutSwimmingLocationType": {
      "abstract": [
        {
          "text": "The possible locations for swimming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSwimmingLocationType"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@HKWorkoutSwimmingLocationType",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKWorkoutSwimmingLocationType",
      "type": "topic",
      "url": "/documentation/HealthKit/HKWorkoutSwimmingLocationType"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-single-goal-workouts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout/supportsActivity(_:)",
        "doc://com.apple.workoutkit/documentation/WorkoutKit/SingleGoalWorkout/supportsGoal(_:activity:location:)"
      ],
      "title": "Creating single goal workouts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@HKWorkoutActivityType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@HKWorkoutSessionLocationType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionLocationType"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@HKWorkoutSwimmingLocationType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKWorkoutSwimmingLocationType"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/workoutkit/singlegoalworkout/init(activity:location:swimminglocation:goal:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
