{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/RunLoopType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.XPCService.RunLoopType",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RunLoopType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "RunLoopType"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "RunLoopType",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [],
          "name": "dispatch_main"
        },
        {
          "content": [],
          "name": "NSRunLoop"
        }
      ]
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "dispatch_main"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService",
      "kind": "symbol",
      "name": "XPCService",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XPCService"
        }
      ],
      "role": "symbol",
      "title": "XPCService",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/xpcservice"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/EnvironmentVariables": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/EnvironmentVariables",
      "kind": "symbol",
      "name": "EnvironmentVariables",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EnvironmentVariables"
        }
      ],
      "role": "symbol",
      "title": "EnvironmentVariables",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/xpcservice/environmentvariables"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/JoinExistingSession": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/JoinExistingSession",
      "kind": "symbol",
      "name": "JoinExistingSession",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JoinExistingSession"
        }
      ],
      "role": "symbol",
      "title": "JoinExistingSession",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/xpcservice/joinexistingsession"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/RunLoopType": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/RunLoopType",
      "kind": "symbol",
      "name": "RunLoopType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RunLoopType"
        }
      ],
      "role": "symbol",
      "title": "RunLoopType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/xpcservice/runlooptype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/ServiceType": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/ServiceType",
      "kind": "symbol",
      "name": "ServiceType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ServiceType"
        }
      ],
      "role": "symbol",
      "title": "ServiceType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/xpcservice/servicetype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Property-List-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/EnvironmentVariables",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/JoinExistingSession",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/ServiceType"
      ],
      "title": "Property List Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "RunLoopType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RunLoopType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Property-List-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/EnvironmentVariables",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/JoinExistingSession",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/XPCService/ServiceType"
              ],
              "title": "Property List Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1XPCService~1JoinExistingSession/title",
          "value": "JoinExistingSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1XPCService~1JoinExistingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JoinExistingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1XPCService~1ServiceType/title",
          "value": "ServiceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1XPCService~1ServiceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ServiceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1XPCService/title",
          "value": "XPCService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1XPCService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XPCService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1XPCService~1RunLoopType/title",
          "value": "RunLoopType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1XPCService~1RunLoopType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RunLoopType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1XPCService~1EnvironmentVariables/title",
          "value": "EnvironmentVariables"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1XPCService~1EnvironmentVariables/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EnvironmentVariables"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/xpcservice/runlooptype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/xpcservice/runlooptype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
