{
  "abstract": [
    {
      "text": "An icon for a quick action that adds an item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/add"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIApplicationShortcutIconType@UIApplicationShortcutIconTypeAdd",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "add"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIApplicationShortcutIconTypeAdd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIApplicationShortcutIcon.IconType.add"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "add"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2934512",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon": {
      "abstract": [
        {
          "text": "An image you can optionally associate with a Home Screen quick action to improve its appearance and usability.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIcon"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIcon"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType": {
      "abstract": [
        {
          "text": "Constants for system-provided icons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IconType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IconType"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/add": {
      "abstract": [
        {
          "text": "An icon for a quick action that adds an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeAdd"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.add",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/add"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/cloud": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers cloud access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloud"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/cloud",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeCloud"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.cloud",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/cloud"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/compose": {
      "abstract": [
        {
          "text": "An icon for a quick action that lets a user compose new content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compose"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/compose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeCompose"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.compose",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/compose"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/confirmation": {
      "abstract": [
        {
          "text": "An icon for a quick action that indicates confirmation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirmation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/confirmation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeConfirmation"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.confirmation",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/confirmation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/contact": {
      "abstract": [
        {
          "text": "An icon for a quick action that chooses a generic contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contact"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/contact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeContact"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.contact",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/contact"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/favorite": {
      "abstract": [
        {
          "text": "An icon for a quick action that lets a user designate a favorite item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "favorite"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/favorite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeFavorite"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.favorite",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/favorite"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/home": {
      "abstract": [
        {
          "text": "An icon for a quick action that indicates home.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/home",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeHome"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.home",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/home"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/invitation": {
      "abstract": [
        {
          "text": "An icon for a quick action that indicates an invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invitation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/invitation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeInvitation"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.invitation",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/invitation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/location": {
      "abstract": [
        {
          "text": "An icon for a quick action that accesses the user’s current location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeLocation"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.location",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/location"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/love": {
      "abstract": [
        {
          "text": "An icon for a quick action that lets a user designate a loved item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "love"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/love",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeLove"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.love",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/love"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/markLocation": {
      "abstract": [
        {
          "text": "An icon for a quick action that lets a user mark a location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markLocation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/markLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeMarkLocation"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.markLocation",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/marklocation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/pause": {
      "abstract": [
        {
          "text": "An icon for  a quick action that pauses media playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/pause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypePause"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.pause",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/pause"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/play": {
      "abstract": [
        {
          "text": "An icon for a quick action that plays media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/play",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypePlay"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.play",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/play"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/prohibit": {
      "abstract": [
        {
          "text": "An icon for a quick action that disallows something.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prohibit"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/prohibit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeProhibit"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.prohibit",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/prohibit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/search": {
      "abstract": [
        {
          "text": "An icon a quick action that offers search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeSearch"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.search",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/search"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/share": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers content sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "share"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/share",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeShare"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.share",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/share"
    },
    "media-2934512": {
      "alt": null,
      "identifier": "media-2934512",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/21485e633ff9bd98868ad097220ef8eb/media-2934512@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7ce1e323668f1fef9c23c76260726042/media-2934512~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/compose",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/play",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/pause",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/location",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/search",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/share",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/prohibit",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/contact",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/home",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/markLocation",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/favorite",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/love",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/cloud",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/invitation",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/confirmation"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIApplicationShortcutIconTypeAdd"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/compose",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/play",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/pause",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/location",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/search",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/share",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/prohibit",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/contact",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/home",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/markLocation",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/favorite",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/love",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/cloud",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/invitation",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/confirmation"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIApplicationShortcutIconTypeAdd"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1confirmation/title",
          "value": "UIApplicationShortcutIconTypeConfirmation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1confirmation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeConfirmation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType/title",
          "value": "UIApplicationShortcutIconType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1love/title",
          "value": "UIApplicationShortcutIconTypeLove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1love/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeLove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1play/title",
          "value": "UIApplicationShortcutIconTypePlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1play/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypePlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1location/title",
          "value": "UIApplicationShortcutIconTypeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1prohibit/title",
          "value": "UIApplicationShortcutIconTypeProhibit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1prohibit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeProhibit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1markLocation/title",
          "value": "UIApplicationShortcutIconTypeMarkLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1markLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeMarkLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1search/title",
          "value": "UIApplicationShortcutIconTypeSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1compose/title",
          "value": "UIApplicationShortcutIconTypeCompose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1compose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeCompose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1share/title",
          "value": "UIApplicationShortcutIconTypeShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1share/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1pause/title",
          "value": "UIApplicationShortcutIconTypePause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1pause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypePause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1add/title",
          "value": "UIApplicationShortcutIconTypeAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon/title",
          "value": "UIApplicationShortcutIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1home/title",
          "value": "UIApplicationShortcutIconTypeHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1home/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1contact/title",
          "value": "UIApplicationShortcutIconTypeContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1contact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1invitation/title",
          "value": "UIApplicationShortcutIconTypeInvitation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1invitation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeInvitation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1favorite/title",
          "value": "UIApplicationShortcutIconTypeFavorite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1favorite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeFavorite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1cloud/title",
          "value": "UIApplicationShortcutIconTypeCloud"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1cloud/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeCloud"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiapplicationshortcuticon/icontype/add"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiapplicationshortcuticon/icontype/add"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
