{
  "abstract": [
    {
      "text": "The payment currency is not supported by your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsCurrencyUnsupported"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INRequestPaymentCurrencyAmountUnsupportedReason@INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsCurrencyUnsupported",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "paymentsCurrencyUnsupported"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsCurrencyUnsupported"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INRequestPaymentCurrencyAmountUnsupportedReason.paymentsCurrencyUnsupported"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "paymentsCurrencyUnsupported"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason": {
      "abstract": [
        {
          "text": "Constants indicating the reason for being unable to resolve the currency amount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRequestPaymentCurrencyAmountUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestPaymentCurrencyAmountUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INRequestPaymentCurrencyAmountUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/inrequestpaymentcurrencyamountunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsAmountAboveMaximum": {
      "abstract": [
        {
          "text": "The payment amount exceeds the maximum transfer amount allowed by your app for the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentsAmountAboveMaximum"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsAmountAboveMaximum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsAmountAboveMaximum"
        }
      ],
      "role": "symbol",
      "title": "INRequestPaymentCurrencyAmountUnsupportedReason.paymentsAmountAboveMaximum",
      "type": "topic",
      "url": "/documentation/intents/inrequestpaymentcurrencyamountunsupportedreason/paymentsamountabovemaximum"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsAmountBelowMinimum": {
      "abstract": [
        {
          "text": "The payment amount is below the minimum transfer amount established by your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentsAmountBelowMinimum"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsAmountBelowMinimum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsAmountBelowMinimum"
        }
      ],
      "role": "symbol",
      "title": "INRequestPaymentCurrencyAmountUnsupportedReason.paymentsAmountBelowMinimum",
      "type": "topic",
      "url": "/documentation/intents/inrequestpaymentcurrencyamountunsupportedreason/paymentsamountbelowminimum"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsCurrencyUnsupported": {
      "abstract": [
        {
          "text": "The payment currency is not supported by your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentsCurrencyUnsupported"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsCurrencyUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsCurrencyUnsupported"
        }
      ],
      "role": "symbol",
      "title": "INRequestPaymentCurrencyAmountUnsupportedReason.paymentsCurrencyUnsupported",
      "type": "topic",
      "url": "/documentation/intents/inrequestpaymentcurrencyamountunsupportedreason/paymentscurrencyunsupported"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsAmountBelowMinimum",
        "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsAmountAboveMaximum"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsCurrencyUnsupported"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsCurrencyUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsAmountBelowMinimum",
                "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountUnsupportedReason/paymentsAmountAboveMaximum"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsCurrencyUnsupported"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountUnsupportedReason~1paymentsCurrencyUnsupported/title",
          "value": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsCurrencyUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountUnsupportedReason~1paymentsCurrencyUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsCurrencyUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountUnsupportedReason~1paymentsAmountAboveMaximum/title",
          "value": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsAmountAboveMaximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountUnsupportedReason~1paymentsAmountAboveMaximum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsAmountAboveMaximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountUnsupportedReason~1paymentsAmountBelowMinimum/title",
          "value": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsAmountBelowMinimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountUnsupportedReason~1paymentsAmountBelowMinimum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestPaymentCurrencyAmountUnsupportedReasonPaymentsAmountBelowMinimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountUnsupportedReason/title",
          "value": "INRequestPaymentCurrencyAmountUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestPaymentCurrencyAmountUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestPaymentCurrencyAmountUnsupportedReason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inrequestpaymentcurrencyamountunsupportedreason/paymentscurrencyunsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inrequestpaymentcurrencyamountunsupportedreason/paymentscurrencyunsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
