{
  "abstract": [
    {
      "text": "The user must have a subscription to the app’s service.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/subscriptionRequired"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INUpdateMediaAffinityMediaItemUnsupportedReason@INUpdateMediaAffinityMediaItemUnsupportedReasonSubscriptionRequired",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "subscriptionRequired"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonSubscriptionRequired"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INUpdateMediaAffinityMediaItemUnsupportedReason.subscriptionRequired"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "subscriptionRequired"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason": {
      "abstract": [
        {
          "text": "Reasons the app can’t update the user’s affinity for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityMediaItemUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/cellularDataSettings": {
      "abstract": [
        {
          "text": "The cellular data settings don’t allow the user to update the media item’s affinity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cellularDataSettings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/cellularDataSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonCellularDataSettings"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityMediaItemUnsupportedReason.cellularDataSettings",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason/cellulardatasettings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/explicitContentSettings": {
      "abstract": [
        {
          "text": "The explicit content settings don’t allow the user to update the media item’s affinity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "explicitContentSettings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/explicitContentSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonExplicitContentSettings"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityMediaItemUnsupportedReason.explicitContentSettings",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason/explicitcontentsettings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/loginRequired": {
      "abstract": [
        {
          "text": "The user must log in to the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loginRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/loginRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonLoginRequired"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityMediaItemUnsupportedReason.loginRequired",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason/loginrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/regionRestriction": {
      "abstract": [
        {
          "text": "The app can’t update the user’s affinity for the media because the media isn’t available in the user’s geographic location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionRestriction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/regionRestriction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonRegionRestriction"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityMediaItemUnsupportedReason.regionRestriction",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason/regionrestriction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/restrictedContent": {
      "abstract": [
        {
          "text": "The media item is restricted content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictedContent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/restrictedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonRestrictedContent"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityMediaItemUnsupportedReason.restrictedContent",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason/restrictedcontent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/serviceUnavailable": {
      "abstract": [
        {
          "text": "The app can’t update the user’s affinity because the media service is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/serviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonServiceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityMediaItemUnsupportedReason.serviceUnavailable",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason/serviceunavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/subscriptionRequired": {
      "abstract": [
        {
          "text": "The user must have a subscription to the app’s service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/subscriptionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonSubscriptionRequired"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityMediaItemUnsupportedReason.subscriptionRequired",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason/subscriptionrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/unsupportedMediaType": {
      "abstract": [
        {
          "text": "The media’s type is unsupported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedMediaType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/unsupportedMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonUnsupportedMediaType"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityMediaItemUnsupportedReason.unsupportedMediaType",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason/unsupportedmediatype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Limitations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/loginRequired",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/unsupportedMediaType",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/explicitContentSettings",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/cellularDataSettings",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/restrictedContent",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/regionRestriction",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/serviceUnavailable"
      ],
      "title": "Limitations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INUpdateMediaAffinityMediaItemUnsupportedReasonSubscriptionRequired"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonSubscriptionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Limitations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/loginRequired",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/unsupportedMediaType",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/explicitContentSettings",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/cellularDataSettings",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/restrictedContent",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/regionRestriction",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityMediaItemUnsupportedReason/serviceUnavailable"
              ],
              "title": "Limitations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonSubscriptionRequired"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason/title",
          "value": "INUpdateMediaAffinityMediaItemUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1explicitContentSettings/title",
          "value": "INUpdateMediaAffinityMediaItemUnsupportedReasonExplicitContentSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1explicitContentSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonExplicitContentSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1regionRestriction/title",
          "value": "INUpdateMediaAffinityMediaItemUnsupportedReasonRegionRestriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1regionRestriction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonRegionRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1subscriptionRequired/title",
          "value": "INUpdateMediaAffinityMediaItemUnsupportedReasonSubscriptionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1subscriptionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonSubscriptionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1restrictedContent/title",
          "value": "INUpdateMediaAffinityMediaItemUnsupportedReasonRestrictedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1restrictedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonRestrictedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1unsupportedMediaType/title",
          "value": "INUpdateMediaAffinityMediaItemUnsupportedReasonUnsupportedMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1unsupportedMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonUnsupportedMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1loginRequired/title",
          "value": "INUpdateMediaAffinityMediaItemUnsupportedReasonLoginRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1loginRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonLoginRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1cellularDataSettings/title",
          "value": "INUpdateMediaAffinityMediaItemUnsupportedReasonCellularDataSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1cellularDataSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonCellularDataSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1serviceUnavailable/title",
          "value": "INUpdateMediaAffinityMediaItemUnsupportedReasonServiceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityMediaItemUnsupportedReason~1serviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityMediaItemUnsupportedReasonServiceUnavailable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason/subscriptionrequired"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inupdatemediaaffinitymediaitemunsupportedreason/subscriptionrequired"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
