{
  "abstract": [
    {
      "text": "The object’s baseline.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSLayoutAttribute/NSLayoutAttributeBaseline"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSLayoutAttribute@NSLayoutAttributeBaseline",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSLayoutAttributeBaseline"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLayoutAttributeBaseline"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NSLayoutAttributeBaseline"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeBaseline"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutAttribute/NSLayoutAttributeBaseline": {
      "abstract": [
        {
          "text": "The object’s baseline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeBaseline"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutAttribute/NSLayoutAttributeBaseline",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLayoutAttributeBaseline",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutattribute/nslayoutattributebaseline"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute": {
      "abstract": [
        {
          "text": "The part of the object’s visual representation that should be used to get the value for the constraint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottom": {
      "abstract": [
        {
          "text": "The bottom of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeBottom"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.bottom",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/bottom"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerX": {
      "abstract": [
        {
          "text": "The center along the x-axis of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerX"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeCenterX"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.centerX",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/centerx"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerY": {
      "abstract": [
        {
          "text": "The center along the y-axis of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeCenterY"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.centerY",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/centery"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/firstBaseline": {
      "abstract": [
        {
          "text": "The object’s baseline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstBaseline"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/firstBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeFirstBaseline"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.firstBaseline",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/firstbaseline"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/height": {
      "abstract": [
        {
          "text": "The height of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "height"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/height",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeHeight"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.height",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/height"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/lastBaseline": {
      "abstract": [
        {
          "text": "The object’s baseline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastBaseline"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/lastBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeLastBaseline"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.lastBaseline",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/lastbaseline"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leading": {
      "abstract": [
        {
          "text": "The leading edge of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeLeading"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.leading",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/leading"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/left": {
      "abstract": [
        {
          "text": "The left side of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeLeft"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.left",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/left"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leftMargin": {
      "abstract": [
        {
          "text": "The object’s left margin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMargin"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leftMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeLeftMargin"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.leftMargin",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/leftmargin"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/right": {
      "abstract": [
        {
          "text": "The right side of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeRight"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.right",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/right"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/rightMargin": {
      "abstract": [
        {
          "text": "The object’s right margin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMargin"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/rightMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeRightMargin"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.rightMargin",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/rightmargin"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/top": {
      "abstract": [
        {
          "text": "The top of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeTop"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.top",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/top"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/topMargin": {
      "abstract": [
        {
          "text": "The object’s top margin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topMargin"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/topMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeTopMargin"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.topMargin",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/topmargin"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/trailing": {
      "abstract": [
        {
          "text": "The trailing edge of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.trailing",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/trailing"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/width": {
      "abstract": [
        {
          "text": "The width of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/width",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeWidth"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.width",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/width"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/left",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/right",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/top",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottom",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leading",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/trailing",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/width",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/height",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerX",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerY",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/lastBaseline",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/firstBaseline",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leftMargin",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/rightMargin",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/topMargin"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1rightMargin/title",
          "value": "NSLayoutAttributeRightMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1rightMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeRightMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerY/title",
          "value": "NSLayoutAttributeCenterY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeCenterY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1leading/title",
          "value": "NSLayoutAttributeLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1topMargin/title",
          "value": "NSLayoutAttributeTopMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1topMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeTopMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1width/title",
          "value": "NSLayoutAttributeWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1width/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1top/title",
          "value": "NSLayoutAttributeTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute/title",
          "value": "NSLayoutAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1trailing/title",
          "value": "NSLayoutAttributeTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerX/title",
          "value": "NSLayoutAttributeCenterX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeCenterX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1leftMargin/title",
          "value": "NSLayoutAttributeLeftMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1leftMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeLeftMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1height/title",
          "value": "NSLayoutAttributeHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1height/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1lastBaseline/title",
          "value": "NSLayoutAttributeLastBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1lastBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeLastBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1firstBaseline/title",
          "value": "NSLayoutAttributeFirstBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1firstBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeFirstBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1bottom/title",
          "value": "NSLayoutAttributeBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1left/title",
          "value": "NSLayoutAttributeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1right/title",
          "value": "NSLayoutAttributeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeRight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nslayoutattribute/nslayoutattributebaseline"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
