{
  "abstract": [
    {
      "text": "Indicates your input and output textures use a high dynamic range color space.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalfx/documentation/MetalFX",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/hdr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLFXSpatialScalerColorProcessingMode@MTLFXSpatialScalerColorProcessingModeHDR",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hdr"
      }
    ],
    "modules": [
      {
        "name": "MetalFX"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLFXSpatialScalerColorProcessingModeHDR"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLFXSpatialScalerColorProcessingMode.hdr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hdr"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalfx/documentation/MetalFX": {
      "abstract": [
        {
          "text": "Boost your Metal app’s performance by upscaling lower-resolution content to save GPU time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalFX",
      "type": "topic",
      "url": "/documentation/metalfx"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode": {
      "abstract": [
        {
          "text": "The color space modes for the input and output textures you use with a spatial scaling effect instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerColorProcessingMode"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerColorProcessingMode"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScalerColorProcessingMode",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalercolorprocessingmode"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/hdr": {
      "abstract": [
        {
          "text": "Indicates your input and output textures use a high dynamic range color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hdr"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/hdr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerColorProcessingModeHDR"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScalerColorProcessingMode.hdr",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalercolorprocessingmode/hdr"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/linear": {
      "abstract": [
        {
          "text": "Indicates your input and output textures use a linear color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerColorProcessingModeLinear"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScalerColorProcessingMode.linear",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalercolorprocessingmode/linear"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/perceptual": {
      "abstract": [
        {
          "text": "Indicates your input and output textures use a perceptual color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perceptual"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/perceptual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScalerColorProcessingModePerceptual"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScalerColorProcessingMode.perceptual",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscalercolorprocessingmode/perceptual"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Color-space-modes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/linear",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/perceptual"
      ],
      "title": "Color space modes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLFXSpatialScalerColorProcessingModeHDR"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerColorProcessingModeHDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalfx/documentation/MetalFX",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Color-space-modes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/linear",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScalerColorProcessingMode/perceptual"
              ],
              "title": "Color space modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLFXSpatialScalerColorProcessingModeHDR"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode/title",
          "value": "MTLFXSpatialScalerColorProcessingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerColorProcessingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerColorProcessingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode~1perceptual/title",
          "value": "MTLFXSpatialScalerColorProcessingModePerceptual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode~1perceptual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerColorProcessingModePerceptual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode~1hdr/title",
          "value": "MTLFXSpatialScalerColorProcessingModeHDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode~1hdr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerColorProcessingModeHDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode~1linear/title",
          "value": "MTLFXSpatialScalerColorProcessingModeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScalerColorProcessingMode~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScalerColorProcessingModeLinear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalfx/mtlfxspatialscalercolorprocessingmode/hdr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalfx/mtlfxspatialscalercolorprocessingmode/hdr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
