{
  "abstract": [
    {
      "text": "Constants that specify the text of the button label.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLLocationButtonLabel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLLocationButtonLabel"
      }
    ],
    "modules": [
      {
        "name": "CoreLocationUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLLocationButtonLabel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CLLocationButtonLabel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabel"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI": {
      "abstract": [
        {
          "text": "Streamline access to users’ location data through a standard, secure UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI",
      "kind": "symbol",
      "role": "collection",
      "title": "CoreLocationUI",
      "type": "topic",
      "url": "/documentation/corelocationui"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonIcon": {
      "abstract": [
        {
          "text": "Constants that specify styles for the location arrow icon on the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationButtonIcon"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonIcon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonIcon"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonIcon",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonicon"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel": {
      "abstract": [
        {
          "text": "Constants that specify the text of the button label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabel"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/currentLocation": {
      "abstract": [
        {
          "text": "A button label with the text ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Current Location",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentLocation"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/currentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.currentLocation",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/currentlocation"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/init(rawvalue:)"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/none": {
      "abstract": [
        {
          "text": "A style that doesn’t display a text label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelNone"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.none",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/none"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendCurrentLocation": {
      "abstract": [
        {
          "text": "A button label with the text ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Send Current Location",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendCurrentLocation"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendCurrentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelSendCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.sendCurrentLocation",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/sendcurrentlocation"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendMyCurrentLocation": {
      "abstract": [
        {
          "text": "A button label with the text ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Send My Current Location",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendMyCurrentLocation"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendMyCurrentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelSendMyCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.sendMyCurrentLocation",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/sendmycurrentlocation"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareCurrentLocation": {
      "abstract": [
        {
          "text": "A button label with the text ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Share Current Location",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shareCurrentLocation"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareCurrentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelShareCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.shareCurrentLocation",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/sharecurrentlocation"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareMyCurrentLocation": {
      "abstract": [
        {
          "text": "A button label with the text ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Share My Current Location",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shareMyCurrentLocation"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareMyCurrentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelShareMyCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.shareMyCurrentLocation",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/sharemycurrentlocation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Button-customization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonIcon"
      ],
      "title": "Button customization"
    }
  ],
  "topicSections": [
    {
      "anchor": "Customizing-label-styles",
      "identifiers": [
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/none",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/currentLocation",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendCurrentLocation",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendMyCurrentLocation",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareCurrentLocation",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareMyCurrentLocation"
      ],
      "title": "Customizing label styles"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLLocationButtonLabel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Customizing-label-styles",
              "identifiers": [
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/none",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/currentLocation",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendCurrentLocation",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendMyCurrentLocation",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareCurrentLocation",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareMyCurrentLocation"
              ],
              "title": "Customizing label styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Button-customization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonIcon"
              ],
              "title": "Button customization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLLocationButtonLabel"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1currentLocation/title",
          "value": "CLLocationButtonLabelCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1currentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1shareCurrentLocation/title",
          "value": "CLLocationButtonLabelShareCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1shareCurrentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelShareCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1none/title",
          "value": "CLLocationButtonLabelNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1sendMyCurrentLocation/title",
          "value": "CLLocationButtonLabelSendMyCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1sendMyCurrentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelSendMyCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1sendCurrentLocation/title",
          "value": "CLLocationButtonLabelSendCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1sendCurrentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelSendCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1shareMyCurrentLocation/title",
          "value": "CLLocationButtonLabelShareMyCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1shareMyCurrentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelShareMyCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonIcon/title",
          "value": "CLLocationButtonIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonIcon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel/title",
          "value": "CLLocationButtonLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocationui/cllocationbuttonlabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocationui/cllocationbuttonlabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
