{
  "abstract": [
    {
      "text": "A button that grants one-time location authorization.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLLocationButton",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLLocationButton"
      }
    ],
    "modules": [
      {
        "name": "CoreLocationUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLLocationButton"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CLLocationButton"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLLocationButton"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "CLLocationButton",
              "type": "codeVoice"
            },
            {
              "text": " simplifies requesting one-time authorization to access",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "location data. Add this button to your user interface in situations when",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "users may want to grant temporary access to their location data each time",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "they use a particular feature of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "cllocationbutton-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The first time a user taps this button,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreLocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " asks the user to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "confirm that they’re comfortable using this UI element when they want to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "grant temporary access to their location data. If the user agrees, the app",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "receives temporary",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreLocation/CLAuthorizationStatus/authorizedWhenInUse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "authorization, like when the user chooses ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Allow Once",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " in response to your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app’s standard location authorization request. This temporary authorization",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "expires when your app is no longer in use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After the user agrees to using ",
              "type": "text"
            },
            {
              "code": "CLLocationButton",
              "type": "codeVoice"
            },
            {
              "text": ", the button becomes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "approved to request future authorizations without displaying an additional",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "alert to the user. The next time the user taps it, this button simply grants",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "one-time authorization without requiring confirmation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After you receive this temporary authorization, fetch the user’s location",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreLocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " API and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "perform any app-specific tasks related to that location data. Connect the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "button to initiate the tasks you want to perform after getting authorization",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "by adding a target and action to the button. Keep in mind that this action",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "activates every time the user taps this button, regardless of whether the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app already has location authorization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create a ",
              "type": "text"
            },
            {
              "code": "CLLocationButton",
              "type": "codeVoice"
            },
            {
              "text": " in Interface Builder or in code, like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let locationButton = CLLocationButton()",
            "locationButton.icon = .arrowFilled",
            "locationButton.label = .currentLocation",
            "locationButton.cornerRadius = 25.0",
            "locationButton.addTarget(self, action: #selector(userPressedLocationButton), for: .touchUpInside)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "When a user taps the button, it only provides one-time",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "authorization to fetch location data — not the location data itself. For",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "more details about fetching location data, see",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreLocation/configuring-your-app-to-use-location-services",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Configure the button’s content by specifying its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/icon",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/label",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " styles. Customize its appearance using the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/cornerRadius",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/fontSize",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "properties, or the standard view appearance properties",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/backgroundColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/tintColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/accessing-user-data/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "cllocationbutton-1": {
      "alt": "Screenshot of the location button with an icon that uses the filled arrow",
      "identifier": "cllocationbutton-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d9ccebc87fa27074b42df3d0e9a3e263/cllocationbutton-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1736f8280311161eb34c692241ba7ae7/cllocationbutton-1~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI": {
      "abstract": [
        {
          "text": "Streamline access to users’ location data through a standard, secure UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI",
      "kind": "symbol",
      "role": "collection",
      "title": "CoreLocationUI",
      "type": "topic",
      "url": "/documentation/corelocationui"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton": {
      "abstract": [
        {
          "text": "A button that grants one-time location authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationButton"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButton"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButton",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbutton"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/cornerRadius": {
      "abstract": [
        {
          "text": "The corner radius of the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cornerRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/cornerRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cornerRadius"
        }
      ],
      "role": "symbol",
      "title": "cornerRadius",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbutton/cornerradius"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/fontSize": {
      "abstract": [
        {
          "text": "The font size of the text on the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/fontSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontSize"
        }
      ],
      "role": "symbol",
      "title": "fontSize",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbutton/fontsize"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/icon": {
      "abstract": [
        {
          "text": "The style of the location arrow icon on the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "icon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLLocationButtonIcon",
          "text": "CLLocationButtonIcon"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/icon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "icon"
        }
      ],
      "role": "symbol",
      "title": "icon",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbutton/icon"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/label": {
      "abstract": [
        {
          "text": "The text of the button label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLLocationButtonLabel",
          "text": "CLLocationButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "label"
        }
      ],
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbutton/label"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/LocationButton": {
      "abstract": [
        {
          "text": "A SwiftUI button that grants one-time location authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocationButton"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/LocationButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocationButton"
        }
      ],
      "role": "symbol",
      "title": "LocationButton",
      "type": "topic",
      "url": "/documentation/corelocationui/locationbutton"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/sharing-your-location-to-find-a-park": {
      "abstract": [
        {
          "text": "Ask for location access using a customizable location button.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/sharing-your-location-to-find-a-park",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing Your Location to Find a Park",
      "type": "topic",
      "url": "/documentation/corelocationui/sharing-your-location-to-find-a-park"
    },
    "doc://com.apple.documentation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/CoreLocation"
    },
    "doc://com.apple.documentation/documentation/CoreLocation/CLAuthorizationStatus/authorizedWhenInUse": {
      "abstract": [
        {
          "text": "The user authorized the app to start location services while it is in use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizedWhenInUse"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreLocation/CLAuthorizationStatus/authorizedWhenInUse",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLAuthorizationStatus.authorizedWhenInUse",
      "type": "topic",
      "url": "/documentation/CoreLocation/CLAuthorizationStatus/authorizedWhenInUse"
    },
    "doc://com.apple.documentation/documentation/CoreLocation/configuring-your-app-to-use-location-services": {
      "abstract": [
        {
          "text": "Prepare your app to start collecting location data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreLocation/configuring-your-app-to-use-location-services",
      "kind": "article",
      "role": "article",
      "title": "Configuring your app to use location services",
      "type": "topic",
      "url": "/documentation/CoreLocation/configuring-your-app-to-use-location-services"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIView/backgroundColor": {
      "abstract": [
        {
          "text": "The view’s background color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@NSCopying"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/backgroundColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/UIKit/UIView/backgroundColor"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIView/tintColor": {
      "abstract": [
        {
          "text": "The first nondefault tint color value in the view’s hierarchy, ascending from and starting with the view itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "! { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/tintColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "tintColor",
      "type": "topic",
      "url": "/documentation/UIKit/UIView/tintColor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIControl": {
      "abstract": [
        {
          "text": "The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIControl"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIControl",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIControl",
      "type": "topic",
      "url": "/documentation/UIKit/UIControl"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)CALayerDelegate": {
      "abstract": [
        {
          "text": "Methods your app can implement to respond to layer-related events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)CALayerDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CALayerDelegate",
      "type": "topic",
      "url": "/documentation/QuartzCore/CALayerDelegate"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/AppKit/NSTouchBarProvider"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIAccessibilityIdentification": {
      "abstract": [
        {
          "text": "Methods that associate a unique identifier with elements in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityIdentification"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIAccessibilityIdentification",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilityIdentification",
      "type": "topic",
      "url": "/documentation/UIKit/UIAccessibilityIdentification"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding": {
      "abstract": [
        {
          "text": "An interface that provides a source for shareable content to fulfill user requests to share current content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationProviding"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIActivityItemsConfigurationProviding",
      "type": "topic",
      "url": "/documentation/UIKit/UIActivityItemsConfigurationProviding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearance": {
      "abstract": [
        {
          "text": "A collection of methods that gives you access to the appearance proxy for a class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearance"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearance",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAppearance",
      "type": "topic",
      "url": "/documentation/UIKit/UIAppearance"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer": {
      "abstract": [
        {
          "text": "A protocol that a class must adopt to allow appearance customization using the [`UIAppearance`](doc://com.apple.uikit/documentation/UIKit/UIAppearance) API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAppearanceContainer",
      "type": "topic",
      "url": "/documentation/UIKit/UIAppearanceContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIContextMenuInteractionDelegate": {
      "abstract": [
        {
          "text": "The methods for providing the set of actions to perform on your content, and for customizing the preview of that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContextMenuInteractionDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIContextMenuInteractionDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContextMenuInteractionDelegate",
      "type": "topic",
      "url": "/documentation/UIKit/UIContextMenuInteractionDelegate"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UICoordinateSpace": {
      "abstract": [
        {
          "text": "A set of methods for converting between different frames of reference on a screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICoordinateSpace"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UICoordinateSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICoordinateSpace",
      "type": "topic",
      "url": "/documentation/UIKit/UICoordinateSpace"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIDynamicItem": {
      "abstract": [
        {
          "text": "A set of methods that can make a custom object eligible to participate in UIKit Dynamics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicItem"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIDynamicItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIDynamicItem",
      "type": "topic",
      "url": "/documentation/UIKit/UIDynamicItem"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that define the focus behavior for a branch of the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIFocusEnvironment",
      "type": "topic",
      "url": "/documentation/UIKit/UIFocusEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusItem": {
      "abstract": [
        {
          "text": "An object that can become focused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusItem"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIFocusEnvironment",
          "text": "UIFocusEnvironment"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIFocusItem",
      "type": "topic",
      "url": "/documentation/UIKit/UIFocusItem"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusItemContainer": {
      "abstract": [
        {
          "text": "The container responsible for providing geometric context to focus items within a given focus environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusItemContainer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusItemContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIFocusItemContainer",
      "type": "topic",
      "url": "/documentation/UIKit/UIFocusItemContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UILargeContentViewerItem": {
      "abstract": [
        {
          "text": "Methods that provide details about how to display your custom content in the large content viewer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILargeContentViewerItem"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UILargeContentViewerItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILargeContentViewerItem",
      "type": "topic",
      "url": "/documentation/UIKit/UILargeContentViewerItem"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting": {
      "abstract": [
        {
          "text": "The interface that determines whether a responder object supports paste configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteConfigurationSupporting",
      "type": "topic",
      "url": "/documentation/UIKit/UIPasteConfigurationSupporting"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIPopoverPresentationControllerSourceItem": {
      "abstract": [
        {
          "text": "A type that can be an anchor for a popover presentation controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationControllerSourceItem"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIPopoverPresentationControllerSourceItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPopoverPresentationControllerSourceItem",
      "type": "topic",
      "url": "/documentation/UIKit/UIPopoverPresentationControllerSourceItem"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions": {
      "abstract": [
        {
          "text": "A set of standard methods that apps can adopt to support editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIResponderStandardEditActions"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIResponderStandardEditActions",
      "type": "topic",
      "url": "/documentation/UIKit/UIResponderStandardEditActions"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring": {
      "abstract": [
        {
          "text": "The protocol you adopt to restore an object’s state from a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/UIKit/UIUserActivityRestoring"
    },
    "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitChangeObservable-67e94"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/accessing-user-data/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/accessing-user-data/",
      "title": "Human Interface Guidelines",
      "titleInlineContent": [
        {
          "text": "Human Interface",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Guidelines",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/accessing-user-data/"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)UIControl"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)CALayerDelegate",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIAccessibilityIdentification",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearance",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIContextMenuInteractionDelegate",
        "doc://com.externally.resolved.symbol/c:objc(pl)UICoordinateSpace",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIDynamicItem",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusItem",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusItemContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)UILargeContentViewerItem",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIPopoverPresentationControllerSourceItem",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions",
        "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP",
        "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Location-authorization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/sharing-your-location-to-find-a-park",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/LocationButton"
      ],
      "title": "Location authorization"
    }
  ],
  "topicSections": [
    {
      "anchor": "Customizing-the-icon-style",
      "identifiers": [
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/icon"
      ],
      "title": "Customizing the icon style"
    },
    {
      "anchor": "Customizing-the-label-text",
      "identifiers": [
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/label"
      ],
      "title": "Customizing the label text"
    },
    {
      "anchor": "Customizing-the-button-appearance",
      "identifiers": [
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/cornerRadius",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/fontSize"
      ],
      "title": "Customizing the button appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLLocationButton"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Customizing-the-icon-style",
              "identifiers": [
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/icon"
              ],
              "title": "Customizing the icon style"
            },
            {
              "anchor": "Customizing-the-label-text",
              "identifiers": [
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/label"
              ],
              "title": "Customizing the label text"
            },
            {
              "anchor": "Customizing-the-button-appearance",
              "identifiers": [
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/cornerRadius",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton/fontSize"
              ],
              "title": "Customizing the button appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)UIControl"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Location-authorization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/sharing-your-location-to-find-a-park"
              ],
              "title": "Location authorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLLocationButton"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIControl",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIControl",
                    "text": "UIControl"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIAccessibilityIdentification/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAccessibilityIdentification"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)CALayerDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CALayerDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIActivityItemsConfigurationProviding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationProviding"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton~1cornerRadius/title",
          "value": "cornerRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton~1cornerRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cornerRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UILargeContentViewerItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UILargeContentViewerItem"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIControl/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIControl"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIPopoverPresentationControllerSourceItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationControllerSourceItem"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIPasteConfigurationSupporting/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIFocusItemContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFocusItemContainer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1backgroundColor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIColor",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "backgroundColor"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIAppearanceContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreLocation~1CLAuthorizationStatus~1authorizedWhenInUse/title",
          "value": "kCLAuthorizationStatusAuthorizedWhenInUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreLocation~1CLAuthorizationStatus~1authorizedWhenInUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLAuthorizationStatusAuthorizedWhenInUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIFocusItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFocusItem"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIFocusEnvironment",
              "text": "UIFocusEnvironment"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton~1fontSize/title",
          "value": "fontSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton~1fontSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fontSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIResponderStandardEditActions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIResponderStandardEditActions"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIDynamicItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIDynamicItem"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1tintColor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIColor",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "tintColor"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIAppearance/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAppearance"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton~1icon/title",
          "value": "icon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton~1icon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "icon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton/title",
          "value": "CLLocationButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIFocusEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIContextMenuInteractionDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContextMenuInteractionDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UICoordinateSpace/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICoordinateSpace"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton~1label/title",
          "value": "label"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "label"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocationui/cllocationbutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocationui/cllocationbutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
