{
  "abstract": [
    {
      "text": "The font weight for system thin font.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSFont",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/thin"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSFontWeightThin",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "thin"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSFont",
        "text": "NSFont"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSFontWeight",
        "text": "Weight"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontWeightThin"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "thin"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "thin"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSFont",
              "text": "NSFont"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSFontWeight",
              "text": "Weight"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont": {
      "abstract": [
        {
          "text": "The representation of a font in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "role": "symbol",
      "title": "NSFont",
      "type": "topic",
      "url": "/documentation/appkit/nsfont"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight": {
      "abstract": [
        {
          "text": "System-defined font-weight values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Weight"
        }
      ],
      "role": "symbol",
      "title": "NSFont.Weight",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/black": {
      "abstract": [
        {
          "text": "The font weight for system black font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "black"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/black",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWeightBlack"
        }
      ],
      "role": "symbol",
      "title": "black",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight/black"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/bold": {
      "abstract": [
        {
          "text": "The font weight for system bold font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/bold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWeightBold"
        }
      ],
      "role": "symbol",
      "title": "bold",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight/bold"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/heavy": {
      "abstract": [
        {
          "text": "The font weight for system heavy font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heavy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/heavy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWeightHeavy"
        }
      ],
      "role": "symbol",
      "title": "heavy",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight/heavy"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/light": {
      "abstract": [
        {
          "text": "The font weight for system light font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "light"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/light",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWeightLight"
        }
      ],
      "role": "symbol",
      "title": "light",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight/light"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/medium": {
      "abstract": [
        {
          "text": "The font weight for system medium font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWeightMedium"
        }
      ],
      "role": "symbol",
      "title": "medium",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight/medium"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/regular": {
      "abstract": [
        {
          "text": "The font weight for system regular font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regular"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/regular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWeightRegular"
        }
      ],
      "role": "symbol",
      "title": "regular",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight/regular"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/semibold": {
      "abstract": [
        {
          "text": "The font weight for system semibold font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "semibold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/semibold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWeightSemibold"
        }
      ],
      "role": "symbol",
      "title": "semibold",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight/semibold"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/thin": {
      "abstract": [
        {
          "text": "The font weight for system thin font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/thin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWeightThin"
        }
      ],
      "role": "symbol",
      "title": "thin",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight/thin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/ultraLight": {
      "abstract": [
        {
          "text": "The font weight for system ultra light font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ultraLight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/ultraLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWeightUltraLight"
        }
      ],
      "role": "symbol",
      "title": "ultraLight",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight/ultralight"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Font-Weights",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/ultraLight",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/light",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/regular",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/medium",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/semibold",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/bold",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/heavy",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/black"
      ],
      "title": "Font Weights"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontWeightThin"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightThin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Font-Weights",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/ultraLight",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/light",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/regular",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/medium",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/semibold",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/bold",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/heavy",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight/black"
              ],
              "title": "Font Weights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSFontWeight",
                    "text": "NSFontWeight"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFontWeightThin"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title",
          "value": "NSFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1bold/title",
          "value": "NSFontWeightBold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1bold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightBold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1medium/title",
          "value": "NSFontWeightMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1light/title",
          "value": "NSFontWeightLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1light/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1heavy/title",
          "value": "NSFontWeightHeavy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1heavy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightHeavy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1thin/title",
          "value": "NSFontWeightThin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1thin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightThin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1ultraLight/title",
          "value": "NSFontWeightUltraLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1ultraLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightUltraLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1black/title",
          "value": "NSFontWeightBlack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1black/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightBlack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight/title",
          "value": "NSFontWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1semibold/title",
          "value": "NSFontWeightSemibold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1semibold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightSemibold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1regular/title",
          "value": "NSFontWeightRegular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight~1regular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightRegular"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfont/weight/thin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfont/weight/thin"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
