{
  "abstract": [
    {
      "text": "A key that represents the comments.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/comments"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFAudio",
    "externalID": "c:@AVAudioSequencerInfoDictionaryKeyComments",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "comments"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
        "text": "AVAudioSequencer"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
        "text": "InfoDictionaryKey"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSequencerInfoDictionaryKeyComments"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "comments"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "comments"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
              "text": "AVAudioSequencer"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
              "text": "InfoDictionaryKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer": {
      "abstract": [
        {
          "text": "An object that plays audio from a collection of MIDI events the system organizes into music tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSequencer"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencer"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSequencer",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey": {
      "abstract": [
        {
          "text": "Constants that defines metadata keys for a sequencer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InfoDictionaryKey"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSequencer.InfoDictionaryKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/album": {
      "abstract": [
        {
          "text": "A key that represents the album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "album"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/album",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyAlbum"
        }
      ],
      "role": "symbol",
      "title": "album",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/album"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/artist": {
      "abstract": [
        {
          "text": "A key that represents the artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyArtist"
        }
      ],
      "role": "symbol",
      "title": "artist",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/artist"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/comments": {
      "abstract": [
        {
          "text": "A key that represents the comments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/comments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyComments"
        }
      ],
      "role": "symbol",
      "title": "comments",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/comments"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/composer": {
      "abstract": [
        {
          "text": "A key that represents the composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/composer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyComposer"
        }
      ],
      "role": "symbol",
      "title": "composer",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/composer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/copyright": {
      "abstract": [
        {
          "text": "A key that represents the copyright statement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/copyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyCopyright"
        }
      ],
      "role": "symbol",
      "title": "copyright",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/copyright"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/genre": {
      "abstract": [
        {
          "text": "A key that represents the genre.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genre"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/genre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyGenre"
        }
      ],
      "role": "symbol",
      "title": "genre",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/genre"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/lyricist": {
      "abstract": [
        {
          "text": "A key that represents the lyricist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lyricist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/lyricist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyLyricist"
        }
      ],
      "role": "symbol",
      "title": "lyricist",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/lyricist"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/subTitle": {
      "abstract": [
        {
          "text": "A key that represents the subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/subTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeySubTitle"
        }
      ],
      "role": "symbol",
      "title": "subTitle",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/subtitle"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/title": {
      "abstract": [
        {
          "text": "A key that represents the title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyTitle"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/title"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/trackNumber": {
      "abstract": [
        {
          "text": "A key that represents the track number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/trackNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyTrackNumber"
        }
      ],
      "role": "symbol",
      "title": "trackNumber",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/tracknumber"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/year": {
      "abstract": [
        {
          "text": "A key that represents the year.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "year"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSequencer",
          "text": "AVAudioSequencer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
          "text": "InfoDictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/year",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSequencerInfoDictionaryKeyYear"
        }
      ],
      "role": "symbol",
      "title": "year",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosequencer/infodictionarykey/year"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Album-Details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/album",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/artist",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/composer",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/copyright",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/genre",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/lyricist",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/title",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/trackNumber",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/subTitle",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/year"
      ],
      "title": "Getting Album Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSequencerInfoDictionaryKeyComments"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyComments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Album-Details",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/album",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/artist",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/composer",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/copyright",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/genre",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/lyricist",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/title",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/trackNumber",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/subTitle",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey/year"
              ],
              "title": "Getting Album Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSequencer/InfoDictionaryKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVAudioSequencerInfoDictionaryKey",
                    "text": "AVAudioSequencerInfoDictionaryKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioSequencerInfoDictionaryKeyComments"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1genre/title",
          "value": "AVAudioSequencerInfoDictionaryKeyGenre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1genre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyGenre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey/title",
          "value": "AVAudioSequencerInfoDictionaryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1subTitle/title",
          "value": "AVAudioSequencerInfoDictionaryKeySubTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1subTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeySubTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1lyricist/title",
          "value": "AVAudioSequencerInfoDictionaryKeyLyricist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1lyricist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyLyricist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1comments/title",
          "value": "AVAudioSequencerInfoDictionaryKeyComments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1comments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyComments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1artist/title",
          "value": "AVAudioSequencerInfoDictionaryKeyArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1composer/title",
          "value": "AVAudioSequencerInfoDictionaryKeyComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1composer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1trackNumber/title",
          "value": "AVAudioSequencerInfoDictionaryKeyTrackNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1trackNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyTrackNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1year/title",
          "value": "AVAudioSequencerInfoDictionaryKeyYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1year/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyYear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1title/title",
          "value": "AVAudioSequencerInfoDictionaryKeyTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer/title",
          "value": "AVAudioSequencer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1album/title",
          "value": "AVAudioSequencerInfoDictionaryKeyAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1album/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1copyright/title",
          "value": "AVAudioSequencerInfoDictionaryKeyCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSequencer~1InfoDictionaryKey~1copyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSequencerInfoDictionaryKeyCopyright"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosequencer/infodictionarykey/comments"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosequencer/infodictionarykey/comments"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
