{
  "abstract": [
    {
      "text": "Constants that indicate the type of event that generates the push notification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CloudKit",
    "externalID": "c:@E@CKNotificationType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NotificationType"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NotificationType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CKNotification.NotificationType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NotificationType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification": {
      "abstract": [
        {
          "text": "The abstract base class for CloudKit notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKNotification"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotification"
        }
      ],
      "role": "symbol",
      "title": "CKNotification",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/ID": {
      "abstract": [
        {
          "text": "An object that uniquely identifies a push notification that a container sends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.ID",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/id"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the type of event that generates the push notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NotificationType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NotificationType"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/database": {
      "abstract": [
        {
          "text": "A notification that CloudKit generates when the contents of a database change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "database"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/database",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotificationTypeDatabase"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType.database",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum/database"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/query": {
      "abstract": [
        {
          "text": "A notification that CloudKit generates from a query subscription’s predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "query"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/query",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotificationTypeQuery"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType.query",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum/query"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/readNotification": {
      "abstract": [
        {
          "text": "A notification that your app marks as read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readNotification"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/readNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotificationTypeReadNotification"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType.readNotification",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum/readnotification"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/recordZone": {
      "abstract": [
        {
          "text": "A notification that CloudKit generates when the contents of a record zone change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordZone"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/recordZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotificationTypeRecordZone"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType.recordZone",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum/recordzone"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/containerIdentifier": {
      "abstract": [
        {
          "text": "The ID of the container with the content that triggers the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containerIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/containerIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containerIdentifier"
        }
      ],
      "role": "symbol",
      "title": "containerIdentifier",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/containeridentifier"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationID": {
      "abstract": [
        {
          "text": "The notification’s ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKNotification",
          "text": "CKNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKNotificationID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationID"
        }
      ],
      "role": "symbol",
      "title": "notificationID",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationid"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationType-swift.property": {
      "abstract": [
        {
          "text": "The type of event that generates the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKNotification",
          "text": "CKNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKNotificationType",
          "text": "NotificationType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationType"
        }
      ],
      "role": "symbol",
      "title": "notificationType",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-the-Notification",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationID",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/ID",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationType-swift.property",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/containerIdentifier"
      ],
      "title": "Identifying the Notification"
    }
  ],
  "topicSections": [
    {
      "anchor": "Notification-Types",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/query",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/database",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/recordZone",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/readNotification"
      ],
      "title": "Notification Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKNotificationType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Notification-Types",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/query",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/database",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/recordZone",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/readNotification"
              ],
              "title": "Notification Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-the-Notification",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationID",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/ID",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationType-swift.property",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/containerIdentifier"
              ],
              "title": "Identifying the Notification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKNotificationType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification/title",
          "value": "CKNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum/title",
          "value": "CKNotificationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1query/title",
          "value": "CKNotificationTypeQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1query/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationTypeQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1containerIdentifier/title",
          "value": "containerIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1containerIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "containerIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1notificationType-swift.property/title",
          "value": "notificationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1notificationType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1recordZone/title",
          "value": "CKNotificationTypeRecordZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1recordZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationTypeRecordZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1ID/title",
          "value": "CKNotificationID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1ID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1database/title",
          "value": "CKNotificationTypeDatabase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1database/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationTypeDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1notificationID/title",
          "value": "notificationID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1notificationID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1readNotification/title",
          "value": "CKNotificationTypeReadNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1readNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationTypeReadNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cknotification/notificationtype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/cknotification/notificationtype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
