{
  "abstract": [
    {
      "text": "A mode that represents Dolby Atmos.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/dolbyAtmos"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioSessionRenderingMode@AVAudioSessionRenderingModeDolbyAtmos",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dolbyAtmos"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionRenderingModeDolbyAtmos"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVAudioSession.RenderingMode.dolbyAtmos"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dolbyAtmos"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum": {
      "abstract": [
        {
          "text": "Audio session rendering mode identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RenderingMode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RenderingMode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RenderingMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/renderingmode-swift.enum"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/dolbyAtmos": {
      "abstract": [
        {
          "text": "A mode that represents Dolby Atmos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dolbyAtmos"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/dolbyAtmos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRenderingModeDolbyAtmos"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RenderingMode.dolbyAtmos",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/renderingmode-swift.enum/dolbyatmos"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/dolbyAudio": {
      "abstract": [
        {
          "text": "A mode that represents Dolby audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dolbyAudio"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/dolbyAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRenderingModeDolbyAudio"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RenderingMode.dolbyAudio",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/renderingmode-swift.enum/dolbyaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/monoStereo": {
      "abstract": [
        {
          "text": "A mode that represents non multi-channel audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoStereo"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/monoStereo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRenderingModeMonoStereo"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RenderingMode.monoStereo",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/renderingmode-swift.enum/monostereo"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/notApplicable": {
      "abstract": [
        {
          "text": "A mode that represents there’s no asset in a loading or playing state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notApplicable"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/notApplicable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRenderingModeNotApplicable"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RenderingMode.notApplicable",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/renderingmode-swift.enum/notapplicable"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/spatialAudio": {
      "abstract": [
        {
          "text": "A mode that represents a fallback for when hardware capabilities don’t support Dolby.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatialAudio"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/spatialAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRenderingModeSpatialAudio"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RenderingMode.spatialAudio",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/renderingmode-swift.enum/spatialaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/surround": {
      "abstract": [
        {
          "text": "A mode that represents general multi-channel audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "surround"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/surround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRenderingModeSurround"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RenderingMode.surround",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/renderingmode-swift.enum/surround"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-rendering-modes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/monoStereo",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/surround",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/spatialAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/dolbyAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/notApplicable"
      ],
      "title": "Getting the rendering modes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSessionRenderingModeDolbyAtmos"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRenderingModeDolbyAtmos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-rendering-modes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/monoStereo",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/surround",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/spatialAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/dolbyAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RenderingMode-swift.enum/notApplicable"
              ],
              "title": "Getting the rendering modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAudioSessionRenderingModeDolbyAtmos"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1surround/title",
          "value": "AVAudioSessionRenderingModeSurround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1surround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRenderingModeSurround"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1dolbyAudio/title",
          "value": "AVAudioSessionRenderingModeDolbyAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1dolbyAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRenderingModeDolbyAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1spatialAudio/title",
          "value": "AVAudioSessionRenderingModeSpatialAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1spatialAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRenderingModeSpatialAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1monoStereo/title",
          "value": "AVAudioSessionRenderingModeMonoStereo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1monoStereo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRenderingModeMonoStereo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum/title",
          "value": "AVAudioSessionRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1notApplicable/title",
          "value": "AVAudioSessionRenderingModeNotApplicable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1notApplicable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRenderingModeNotApplicable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1dolbyAtmos/title",
          "value": "AVAudioSessionRenderingModeDolbyAtmos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RenderingMode-swift.enum~1dolbyAtmos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRenderingModeDolbyAtmos"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/renderingmode-swift.enum/dolbyatmos"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/renderingmode-swift.enum/dolbyatmos"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
