{"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"AppKit"}],"title":"findIndicatorNeedsUpdate","platforms":[{"introducedAt":"10.7","deprecated":false,"name":"macOS","beta":false,"unavailable":false}],"navigatorTitle":[{"text":"findIndicatorNeedsUpdate","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)NSTextFinder(py)findIndicatorNeedsUpdate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"findIndicatorNeedsUpdate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"abstract":[{"text":"Invoke to specify that the find indicator needs updating when not contained within a scroll view.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"findIndicatorNeedsUpdate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"If the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFinder/client"},{"text":" object’s document is not scrolled by an instance of ","type":"text"},{"code":"NSScrollView","type":"codeVoice"},{"text":", then set this property to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":" when scrolling occurs to cause the find indicator to be updated appropriately.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nstextfinder/findindicatorneedsupdate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nstextfinder/findindicatorneedsupdate"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSTextFinder/findIndicatorNeedsUpdate","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextFinder"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSTextFinder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTextFinder","kind":"identifier"}],"title":"NSTextFinder","url":"/documentation/appkit/nstextfinder","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFinder","type":"topic","abstract":[{"type":"text","text":"An optional search-and-replace find interface inside a view, usually a scroll view."}],"kind":"symbol","navigatorTitle":[{"text":"NSTextFinder","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSTextFinder/client":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"client","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSTextFinderClient","text":"NSTextFinderClient","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"/documentation/appkit/nstextfinder/client","type":"topic","title":"client","role":"symbol","abstract":[{"text":"The object that provides the target search string, find bar location, and feedback methods.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFinder/client","navigatorTitle":[{"text":"client","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTextFinder/findIndicatorNeedsUpdate":{"role":"symbol","abstract":[{"type":"text","text":"Invoke to specify that the find indicator needs updating when not contained within a scroll view."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"findIndicatorNeedsUpdate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFinder/findIndicatorNeedsUpdate","title":"findIndicatorNeedsUpdate","type":"topic","kind":"symbol","navigatorTitle":[{"text":"findIndicatorNeedsUpdate","kind":"identifier"}],"url":"/documentation/appkit/nstextfinder/findindicatorneedsupdate"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"10.7","deprecated":false,"name":"macOS","beta":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"findIndicatorNeedsUpdate","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"findIndicatorNeedsUpdate","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextFinder"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"findIndicatorNeedsUpdate"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder/title","value":"NSTextFinder","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder/fragments","value":[{"text":"NSTextFinder","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder/navigatorTitle","value":[{"text":"NSTextFinder","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1client/title","value":"client","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1client/fragments","value":[{"text":"client","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1findIndicatorNeedsUpdate/title","value":"findIndicatorNeedsUpdate","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1findIndicatorNeedsUpdate/fragments","value":[{"text":"findIndicatorNeedsUpdate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}