{
  "abstract": [
    {
      "text": "The supported joint group names for the body pose.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JointsGroupName"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JointsGroupName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "VNHumanBodyPoseObservation.JointsGroupName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JointsGroupName"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-images"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation": {
      "abstract": [
        {
          "text": "An observation that provides the body points the analysis recognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPoseObservation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointName": {
      "abstract": [
        {
          "text": "The supported joint names for the body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPoseObservation.JointName",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointname"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName": {
      "abstract": [
        {
          "text": "The supported joint group names for the body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointsGroupName"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPoseObservation.JointsGroupName",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/all": {
      "abstract": [
        {
          "text": "All body point groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservationJointsGroupNameAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname/all"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/face": {
      "abstract": [
        {
          "text": "The face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "face"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/face",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservationJointsGroupNameFace"
        }
      ],
      "role": "symbol",
      "title": "face",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname/face"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a joint group name with a recognized point group key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname/init(rawvalue:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/leftArm": {
      "abstract": [
        {
          "text": "The left arm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftArm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/leftArm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservationJointsGroupNameLeftArm"
        }
      ],
      "role": "symbol",
      "title": "leftArm",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname/leftarm"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/leftLeg": {
      "abstract": [
        {
          "text": "The left leg.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftLeg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/leftLeg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservationJointsGroupNameLeftLeg"
        }
      ],
      "role": "symbol",
      "title": "leftLeg",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname/leftleg"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/rightArm": {
      "abstract": [
        {
          "text": "The right arm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightArm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/rightArm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservationJointsGroupNameRightArm"
        }
      ],
      "role": "symbol",
      "title": "rightArm",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname/rightarm"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/rightLeg": {
      "abstract": [
        {
          "text": "The right leg.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightLeg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/rightLeg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservationJointsGroupNameRightLeg"
        }
      ],
      "role": "symbol",
      "title": "rightLeg",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname/rightleg"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/torso": {
      "abstract": [
        {
          "text": "The torso.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "torso"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/torso",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPoseObservationJointsGroupNameTorso"
        }
      ],
      "role": "symbol",
      "title": "torso",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname/torso"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointNames": {
      "abstract": [
        {
          "text": "The names of the available joints in the observation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableJointNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableJointNames"
        }
      ],
      "role": "symbol",
      "title": "availableJointNames",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/availablejointnames"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointsGroupNames": {
      "abstract": [
        {
          "text": "The available joint group names in the observation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableJointsGroupNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointsGroupNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableJointsGroupNames"
        }
      ],
      "role": "symbol",
      "title": "availableJointsGroupNames",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/availablejointsgroupnames"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoint(_:)": {
      "abstract": [
        {
          "text": "Retrieves the recognized point for a joint name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognizedPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNRecognizedPoint",
          "text": "VNRecognizedPoint"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recognizedPointForJointName:error:"
        }
      ],
      "role": "symbol",
      "title": "recognizedPoint(_:)",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/recognizedpoint(_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoints(_:)": {
      "abstract": [
        {
          "text": "Retrieves the recognized points associated with the joint group name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognizedPoints"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointsGroupName",
          "text": "JointsGroupName"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPoseObservation",
          "text": "VNHumanBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNHumanBodyPoseObservationJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNRecognizedPoint",
          "text": "VNRecognizedPoint"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoints(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recognizedPointsForJointsGroupName:error:"
        }
      ],
      "role": "symbol",
      "title": "recognizedPoints(_:)",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodyposeobservation/recognizedpoints(_:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey": {
      "abstract": [
        {
          "text": "The data type for all recognized-point group keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPointGroupKey",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey"
    },
    "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-images": {
      "abstract": [
        {
          "text": "Add the capability to detect human body poses to your app using the Vision framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/detecting-human-body-poses-in-images",
      "kind": "article",
      "role": "article",
      "title": "Detecting Human Body Poses in Images",
      "type": "topic",
      "url": "/documentation/vision/detecting-human-body-poses-in-images"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Points",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointNames",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointName",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointsGroupNames",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoint(_:)",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoints(_:)"
      ],
      "title": "Accessing Points"
    }
  ],
  "topicSections": [
    {
      "anchor": "Head",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/face"
      ],
      "title": "Head"
    },
    {
      "anchor": "Body",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/torso"
      ],
      "title": "Body"
    },
    {
      "anchor": "Arms",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/leftArm",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/rightArm"
      ],
      "title": "Arms"
    },
    {
      "anchor": "Legs",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/leftLeg",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/rightLeg"
      ],
      "title": "Legs"
    },
    {
      "anchor": "All",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/all"
      ],
      "title": "All"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNHumanBodyPoseObservationJointsGroupName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Head",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/face"
              ],
              "title": "Head"
            },
            {
              "anchor": "Body",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/torso"
              ],
              "title": "Body"
            },
            {
              "anchor": "Arms",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/leftArm",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/rightArm"
              ],
              "title": "Arms"
            },
            {
              "anchor": "Legs",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/leftLeg",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/rightLeg"
              ],
              "title": "Legs"
            },
            {
              "anchor": "All",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointsGroupName/all"
              ],
              "title": "All"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Points",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointNames",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/JointName",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/availableJointsGroupNames",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoint(_:)",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPoseObservation/recognizedPoints(_:)"
              ],
              "title": "Accessing Points"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
                    "text": "VNRecognizedPointGroupKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNHumanBodyPoseObservationJointsGroupName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1availableJointsGroupNames/title",
          "value": "availableJointsGroupNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1availableJointsGroupNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableJointsGroupNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1recognizedPoints(_:)/title",
          "value": "recognizedPointsForJointsGroupName:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1recognizedPoints(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recognizedPointsForJointsGroupName:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation/title",
          "value": "VNHumanBodyPoseObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1leftArm/title",
          "value": "VNHumanBodyPoseObservationJointsGroupNameLeftArm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1leftArm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupNameLeftArm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1rightArm/title",
          "value": "VNHumanBodyPoseObservationJointsGroupNameRightArm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1rightArm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupNameRightArm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1leftLeg/title",
          "value": "VNHumanBodyPoseObservationJointsGroupNameLeftLeg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1leftLeg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupNameLeftLeg"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointName/title",
          "value": "VNHumanBodyPoseObservationJointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1all/title",
          "value": "VNHumanBodyPoseObservationJointsGroupNameAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupNameAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1face/title",
          "value": "VNHumanBodyPoseObservationJointsGroupNameFace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1face/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupNameFace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1rightLeg/title",
          "value": "VNHumanBodyPoseObservationJointsGroupNameRightLeg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1rightLeg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupNameRightLeg"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1availableJointNames/title",
          "value": "availableJointNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1availableJointNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableJointNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName/title",
          "value": "VNHumanBodyPoseObservationJointsGroupName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/title",
          "value": "VNRecognizedPointGroupKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointGroupKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointGroupKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1recognizedPoint(_:)/title",
          "value": "recognizedPointForJointName:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1recognizedPoint(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recognizedPointForJointName:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1torso/title",
          "value": "VNHumanBodyPoseObservationJointsGroupNameTorso"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPoseObservation~1JointsGroupName~1torso/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPoseObservationJointsGroupNameTorso"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnhumanbodyposeobservation/jointsgroupname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
