{
  "abstract": [
    {
      "text": "An array of child sound event nodes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE",
        "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition/children"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHASESoundEventNodeDefinition(py)children",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "children"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeDefinition",
        "text": "PHASESoundEventNodeDefinition"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "children"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "children"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "children"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeDefinition",
              "text": "PHASESoundEventNodeDefinition"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To add children, use the add subtree functions of the derived class. For example, add children to a container node using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition/addSubtree(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition/addSubtree(_:)": {
      "abstract": [
        {
          "text": "Adds a sound event node as a child.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSubtree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeDefinition",
          "text": "PHASESoundEventNodeDefinition"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEContainerNodeDefinition/addSubtree(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSubtree:"
        }
      ],
      "role": "symbol",
      "title": "addSubtree(_:)",
      "type": "topic",
      "url": "/documentation/phase/phasecontainernodedefinition/addsubtree(_:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition": {
      "abstract": [
        {
          "text": "A base class for sound event nodes that connect to form a node hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESoundEventNodeDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESoundEventNodeDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventnodedefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition/children": {
      "abstract": [
        {
          "text": "An array of child sound event nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "children"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESoundEventNodeDefinition",
          "text": "PHASESoundEventNodeDefinition"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition/children",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "children"
        }
      ],
      "role": "symbol",
      "title": "children",
      "type": "topic",
      "url": "/documentation/phase/phasesoundeventnodedefinition/children"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "children"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "children"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE",
                "doc://com.apple.phase/documentation/PHASE/PHASESoundEventNodeDefinition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<PHASESoundEventNodeDefinition *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "children"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition~1children/title",
          "value": "children"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition~1children/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "children"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/title",
          "value": "PHASESoundEventNodeDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESoundEventNodeDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESoundEventNodeDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition~1addSubtree(_:)/title",
          "value": "addSubtree:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEContainerNodeDefinition~1addSubtree(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addSubtree:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasesoundeventnodedefinition/children"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phasesoundeventnodedefinition/children"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
