{
  "abstract": [
    {
      "text": "Enumerations in the xcselect framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcselect/documentation/xcselect"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcselect/documentation/xcselect/enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "xcselect"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcselect/documentation/xcselect": {
      "abstract": [
        {
          "text": "Access the path of the macOS SDK available on the host system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect",
      "kind": "symbol",
      "role": "collection",
      "title": "xcselect",
      "type": "topic",
      "url": "/documentation/xcselect"
    },
    "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy": {
      "abstract": [
        {
          "text": "Describe the preferred policy for locating an SDK appropriate for building host content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostSDKPolicy"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostSDKPolicy"
        }
      ],
      "role": "symbol",
      "title": "HostSDKPolicy",
      "type": "topic",
      "url": "/documentation/xcselect/hostsdkpolicy"
    },
    "doc://com.apple.xcselect/documentation/xcselect/macros": {
      "abstract": [
        {
          "text": "Macros in the xcselect framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/xcselect/macros"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Topics",
      "identifiers": [
        "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy"
      ]
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Topics",
              "identifiers": [
                "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy"
              ]
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcselect/documentation/xcselect/macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/title",
          "value": "xcselect_host_sdk_policy_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_policy_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_policy_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcselect/enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcselect/enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
