{
  "abstract": [
    {
      "text": "Describe the preferred policy for locating an SDK appropriate for building host content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcselect/documentation/xcselect"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@xcselect_host_sdk_policy_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HostSDKPolicy"
      }
    ],
    "modules": [
      {
        "name": "xcselect"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HostSDKPolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "HostSDKPolicy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HostSDKPolicy"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcselect/documentation/xcselect": {
      "abstract": [
        {
          "text": "Access the path of the macOS SDK available on the host system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect",
      "kind": "symbol",
      "role": "collection",
      "title": "xcselect",
      "type": "topic",
      "url": "/documentation/xcselect"
    },
    "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy": {
      "abstract": [
        {
          "text": "Describe the preferred policy for locating an SDK appropriate for building host content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostSDKPolicy"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostSDKPolicy"
        }
      ],
      "role": "symbol",
      "title": "HostSDKPolicy",
      "type": "topic",
      "url": "/documentation/xcselect/hostsdkpolicy"
    },
    "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/xcselect/hostsdkpolicy/init(rawvalue:)"
    },
    "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/latest": {
      "abstract": [
        {
          "text": "Return the latest macOS SDK available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latest"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/latest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSELECT_HOST_SDK_POLICY_LATEST"
        }
      ],
      "role": "symbol",
      "title": "HostSDKPolicy.latest",
      "type": "topic",
      "url": "/documentation/xcselect/hostsdkpolicy/latest"
    },
    "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingOnly": {
      "abstract": [
        {
          "text": "Return an SDK that matches the host’s major OS version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchingOnly"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY"
        }
      ],
      "role": "symbol",
      "title": "HostSDKPolicy.matchingOnly",
      "type": "topic",
      "url": "/documentation/xcselect/hostsdkpolicy/matchingonly"
    },
    "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingPreferred": {
      "abstract": [
        {
          "text": "Return an SDK that matches the host’s major OS version if it is available, otherwise return the latest macOS SDK available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchingPreferred"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingPreferred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSELECT_HOST_SDK_POLICY_MATCHING_PREFERRED"
        }
      ],
      "role": "symbol",
      "title": "HostSDKPolicy.matchingPreferred",
      "type": "topic",
      "url": "/documentation/xcselect/hostsdkpolicy/matchingpreferred"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/latest",
        "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingOnly",
        "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingPreferred"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "xcselect_host_sdk_policy_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_policy_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_policy_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcselect/documentation/xcselect"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/latest",
                "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingOnly",
                "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy/matchingPreferred"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "xcselect_host_sdk_policy_t"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/title",
          "value": "xcselect_host_sdk_policy_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_policy_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_policy_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy~1latest/title",
          "value": "XCSELECT_HOST_SDK_POLICY_LATEST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy~1latest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSELECT_HOST_SDK_POLICY_LATEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy~1matchingOnly/title",
          "value": "XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy~1matchingOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSELECT_HOST_SDK_POLICY_MATCHING_ONLY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy~1matchingPreferred/title",
          "value": "XCSELECT_HOST_SDK_POLICY_MATCHING_PREFERRED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy~1matchingPreferred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSELECT_HOST_SDK_POLICY_MATCHING_PREFERRED"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcselect/hostsdkpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcselect/hostsdkpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
