{
  "abstract": [
    {
      "text": "Macros in the xcselect framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcselect/documentation/xcselect"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcselect/documentation/xcselect/macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "xcselect"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Macros"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcselect/documentation/xcselect": {
      "abstract": [
        {
          "text": "Access the path of the macOS SDK available on the host system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect",
      "kind": "symbol",
      "role": "collection",
      "title": "xcselect",
      "type": "topic",
      "url": "/documentation/xcselect"
    },
    "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_ASSUME_NONNULL_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCSELECT_ASSUME_NONNULL_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_ASSUME_NONNULL_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCSELECT_ASSUME_NONNULL_BEGIN",
      "type": "topic",
      "url": "/documentation/xcselect/xcselect_assume_nonnull_begin"
    },
    "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_ASSUME_NONNULL_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCSELECT_ASSUME_NONNULL_END"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_ASSUME_NONNULL_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCSELECT_ASSUME_NONNULL_END",
      "type": "topic",
      "url": "/documentation/xcselect/xcselect_assume_nonnull_end"
    },
    "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_BEGIN_DECLS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCSELECT_BEGIN_DECLS"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_BEGIN_DECLS",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCSELECT_BEGIN_DECLS",
      "type": "topic",
      "url": "/documentation/xcselect/xcselect_begin_decls"
    },
    "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_END_DECLS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCSELECT_END_DECLS"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_END_DECLS",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCSELECT_END_DECLS",
      "type": "topic",
      "url": "/documentation/xcselect/xcselect_end_decls"
    },
    "doc://com.apple.xcselect/documentation/xcselect/enumerations": {
      "abstract": [
        {
          "text": "Enumerations in the xcselect framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Enumerations",
      "type": "topic",
      "url": "/documentation/xcselect/enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Topics",
              "identifiers": [
                "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_ASSUME_NONNULL_BEGIN",
                "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_ASSUME_NONNULL_END",
                "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_BEGIN_DECLS",
                "doc://com.apple.xcselect/documentation/xcselect/XCSELECT_END_DECLS"
              ]
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcselect/documentation/xcselect/enumerations"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcselect/macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcselect/macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
