{
  "abstract": [
    {
      "text": "Returns the path to a version of the macOS SDK for building executables, libraries, and other content that run on the local Mac.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcselect/documentation/xcselect"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.xcselect/documentation/xcselect/xcselect_host_sdk_path"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@xcselect_host_sdk_path",
    "fragments": [
      {
        "kind": "identifier",
        "text": "xcselect_host_sdk_path"
      }
    ],
    "modules": [
      {
        "name": "xcselect"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "xcselect_host_sdk_path"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "xcselect_host_sdk_path"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@errno_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@errno_t",
              "text": "errno_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_path"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@xcselect_host_sdk_policy_t",
              "text": "xcselect_host_sdk_policy_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sdk_policy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * * "
            },
            {
              "kind": "internalParam",
              "text": "path"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If successful, the path to the specified SDK version as a C string; otherwise, the value is unchanged.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "If successful, this method allocates the C string from the heap and it’s your responsibility to free the string later using ",
                      "type": "text"
                    },
                    {
                      "code": "free(3)",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". See ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/free.3.html#//apple_ref/doc/man/3/free",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              "name": "Important",
              "style": "important",
              "type": "aside"
            }
          ],
          "name": "path"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The return value is ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " if successful; otherwise, it returns ",
              "type": "text"
            },
            {
              "code": "EINVAL",
              "type": "codeVoice"
            },
            {
              "text": " if the parameters are invalid or ",
              "type": "text"
            },
            {
              "code": "ENOENT",
              "type": "codeVoice"
            },
            {
              "text": " if the function can’t find the SDK using the specified criteria.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcselect/documentation/xcselect": {
      "abstract": [
        {
          "text": "Access the path of the macOS SDK available on the host system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect",
      "kind": "symbol",
      "role": "collection",
      "title": "xcselect",
      "type": "topic",
      "url": "/documentation/xcselect"
    },
    "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy": {
      "abstract": [
        {
          "text": "Describe the preferred policy for locating an SDK appropriate for building host content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostSDKPolicy"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/HostSDKPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostSDKPolicy"
        }
      ],
      "role": "symbol",
      "title": "HostSDKPolicy",
      "type": "topic",
      "url": "/documentation/xcselect/hostsdkpolicy"
    },
    "doc://com.apple.xcselect/documentation/xcselect/xcselect_host_sdk_path": {
      "abstract": [
        {
          "text": "Returns the path to a version of the macOS SDK for building executables, libraries, and other content that run on the local Mac.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xcselect_host_sdk_path"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/xcselect_host_sdk_path",
      "kind": "symbol",
      "role": "symbol",
      "title": "xcselect_host_sdk_path",
      "type": "topic",
      "url": "/documentation/xcselect/xcselect_host_sdk_path"
    },
    "doc://com.externally.resolved.symbol/c:@T@errno_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@errno_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "errno_t",
      "type": "topic",
      "url": "/documentation/kernel/errno_t"
    },
    "https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/free.3.html#//apple_ref/doc/man/3/free": {
      "identifier": "https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/free.3.html#//apple_ref/doc/man/3/free",
      "title": "Mac OS X Manual Page for free(3)",
      "titleInlineContent": [
        {
          "text": "Mac OS X Manual Page for free(3)",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/free.3.html#//apple_ref/doc/man/3/free"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/title",
          "value": "xcselect_host_sdk_policy_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_policy_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcselect~1documentation~1xcselect~1HostSDKPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "xcselect_host_sdk_policy_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcselect/xcselect_host_sdk_path"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
