{
  "abstract": [
    {
      "text": "The empirical throughput, in bits per second, across all media downloaded.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVPlayerItemAccessLogEvent(py)observedBitrate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "observedBitrate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "observedBitrate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "observedBitrate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "observedBitrate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The property corresponds to “c-observed-bitrate”.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property is negative if unknown.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This property is not compatible with key-value observing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent": {
      "abstract": [
        {
          "text": "A single entry in a player item’s access log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemAccessLogEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemAccessLogEvent"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemAccessLogEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageAudioBitrate": {
      "abstract": [
        {
          "text": "The audio track’s average bit rate, in bits per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "averageAudioBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageAudioBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "averageAudioBitrate"
        }
      ],
      "role": "symbol",
      "title": "averageAudioBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/averageaudiobitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageVideoBitrate": {
      "abstract": [
        {
          "text": "The video track’s average bit rate, in bits per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "averageVideoBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageVideoBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "averageVideoBitrate"
        }
      ],
      "role": "symbol",
      "title": "averageVideoBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/averagevideobitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedAverageBitrate": {
      "abstract": [
        {
          "text": "The average throughput, in bits per second, required to play the stream, as advertised by the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indicatedAverageBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedAverageBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indicatedAverageBitrate"
        }
      ],
      "role": "symbol",
      "title": "indicatedAverageBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/indicatedaveragebitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedBitrate": {
      "abstract": [
        {
          "text": "The throughput, in bits per second, required to play the stream, as advertised by the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indicatedBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indicatedBitrate"
        }
      ],
      "role": "symbol",
      "title": "indicatedBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/indicatedbitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrate": {
      "abstract": [
        {
          "text": "The empirical throughput, in bits per second, across all media downloaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedBitrate"
        }
      ],
      "role": "symbol",
      "title": "observedBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/observedbitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrateStandardDeviation": {
      "abstract": [
        {
          "text": "The standard deviation of the observed segment download bit rates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedBitrateStandardDeviation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrateStandardDeviation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedBitrateStandardDeviation"
        }
      ],
      "role": "symbol",
      "title": "observedBitrateStandardDeviation",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/observedbitratestandarddeviation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMaxBitrate": {
      "abstract": [
        {
          "text": "The maximum observed segment download bit rate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedMaxBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMaxBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedMaxBitrate"
        }
      ],
      "role": "symbol",
      "title": "observedMaxBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/observedmaxbitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMinBitrate": {
      "abstract": [
        {
          "text": "The minimum observed segment download bit rate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedMinBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMinBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedMinBitrate"
        }
      ],
      "role": "symbol",
      "title": "observedMinBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/observedminbitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/switchBitrate": {
      "abstract": [
        {
          "text": "The bandwidth value that causes a switch, up or down, in the item’s quality being played.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "switchBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/switchBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "switchBitrate"
        }
      ],
      "role": "symbol",
      "title": "switchBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/switchbitrate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Bit-Rate-Log-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrateStandardDeviation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMaxBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMinBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/switchBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageAudioBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageVideoBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedAverageBitrate"
      ],
      "title": "Getting Bit Rate Log Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "observedBitrate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Bit-Rate-Log-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrateStandardDeviation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMaxBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMinBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/switchBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageAudioBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageVideoBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedAverageBitrate"
              ],
              "title": "Getting Bit Rate Log Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "observedBitrate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedBitrate/title",
          "value": "observedBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1averageAudioBitrate/title",
          "value": "averageAudioBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1averageAudioBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "averageAudioBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedMaxBitrate/title",
          "value": "observedMaxBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedMaxBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedMaxBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1indicatedAverageBitrate/title",
          "value": "indicatedAverageBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1indicatedAverageBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indicatedAverageBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/title",
          "value": "AVPlayerItemAccessLogEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedBitrateStandardDeviation/title",
          "value": "observedBitrateStandardDeviation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedBitrateStandardDeviation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedBitrateStandardDeviation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1averageVideoBitrate/title",
          "value": "averageVideoBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1averageVideoBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "averageVideoBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1indicatedBitrate/title",
          "value": "indicatedBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1indicatedBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indicatedBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedMinBitrate/title",
          "value": "observedMinBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedMinBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedMinBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1switchBitrate/title",
          "value": "switchBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1switchBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "switchBitrate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avplayeritemaccesslogevent/observedbitrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avplayeritemaccesslogevent/observedbitrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
