{
  "abstract": [
    {
      "text": "An array that contains the lengths of each split section.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use Metal Performance Shaders Graph or BNNS instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer/splitSectionLengths-5abch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MLCompute",
    "externalID": "s:So13MLCSplitLayerC9MLComputeE19splitSectionLengthsSaySiGSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "splitSectionLengths"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "11.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "splitSectionLengths"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "splitSectionLengths"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The layer splits the tensor into chunks along dimensions with sizes given in ",
              "type": "text"
            },
            {
              "code": "splitSectionLengths",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer": {
      "abstract": [
        {
          "text": "A layer that splits a tensor value into a list of subtensors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSplitLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSplitLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCSplitLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsplitlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer/dimension": {
      "abstract": [
        {
          "text": "The dimension or axis along which to split the tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dimension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer/dimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dimension"
        }
      ],
      "role": "symbol",
      "title": "dimension",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsplitlayer/dimension"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer/splitCount": {
      "abstract": [
        {
          "text": "The number of splits.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer/splitCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitCount"
        }
      ],
      "role": "symbol",
      "title": "splitCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsplitlayer/splitcount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer/splitSectionLengths-5abch": {
      "abstract": [
        {
          "text": "An array that contains the lengths of each split section.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitSectionLengths"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer/splitSectionLengths-5abch",
      "kind": "symbol",
      "role": "symbol",
      "title": "splitSectionLengths",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsplitlayer/splitsectionlengths-5abch"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Split-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer/dimension",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer/splitCount"
      ],
      "title": "Inspecting Split Layers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer/title",
          "value": "MLCSplitLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSplitLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSplitLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer~1dimension/title",
          "value": "dimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer~1dimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer~1splitCount/title",
          "value": "splitCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer~1splitCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "splitCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcsplitlayer/splitsectionlengths-5abch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
