{
  "abstract": [
    {
      "text": "Computational accuracy options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@E@VNTrackOpticalFlowRequestComputationAccuracy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ComputationAccuracy"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ComputationAccuracy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VNTrackOpticalFlowRequest.ComputationAccuracy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ComputationAccuracy"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest": {
      "abstract": [
        {
          "text": "An object that determines the direction change of vectors for each pixel from a previous to current image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNTrackOpticalFlowRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackOpticalFlowRequest"
        }
      ],
      "role": "symbol",
      "title": "VNTrackOpticalFlowRequest",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum": {
      "abstract": [
        {
          "text": "Computational accuracy options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComputationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComputationAccuracy"
        }
      ],
      "role": "symbol",
      "title": "VNTrackOpticalFlowRequest.ComputationAccuracy",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest/computationaccuracy-swift.enum"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/high": {
      "abstract": [
        {
          "text": "An option that indicates a high level of computational accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackOpticalFlowRequestComputationAccuracyHigh"
        }
      ],
      "role": "symbol",
      "title": "VNTrackOpticalFlowRequest.ComputationAccuracy.high",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest/computationaccuracy-swift.enum/high"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest/computationaccuracy-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/low": {
      "abstract": [
        {
          "text": "An option that indicates a low level of computational accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackOpticalFlowRequestComputationAccuracyLow"
        }
      ],
      "role": "symbol",
      "title": "VNTrackOpticalFlowRequest.ComputationAccuracy.low",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest/computationaccuracy-swift.enum/low"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/medium": {
      "abstract": [
        {
          "text": "An option that indicates a moderate level of computational accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackOpticalFlowRequestComputationAccuracyMedium"
        }
      ],
      "role": "symbol",
      "title": "VNTrackOpticalFlowRequest.ComputationAccuracy.medium",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest/computationaccuracy-swift.enum/medium"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/veryHigh": {
      "abstract": [
        {
          "text": "An option that indicates a very high level of computational accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "veryHigh"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/veryHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNTrackOpticalFlowRequestComputationAccuracyVeryHigh"
        }
      ],
      "role": "symbol",
      "title": "VNTrackOpticalFlowRequest.ComputationAccuracy.veryHigh",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest/computationaccuracy-swift.enum/veryhigh"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/computationAccuracy-swift.property": {
      "abstract": [
        {
          "text": "The level of accuracy to compute the optical flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "computationAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNTrackOpticalFlowRequest",
          "text": "VNTrackOpticalFlowRequest"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VNTrackOpticalFlowRequestComputationAccuracy",
          "text": "ComputationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/computationAccuracy-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "computationAccuracy"
        }
      ],
      "role": "symbol",
      "title": "computationAccuracy",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest/computationaccuracy-swift.property"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/keepNetworkOutput": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the raw pixel buffer continues to emit from the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keepNetworkOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/keepNetworkOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keepNetworkOutput"
        }
      ],
      "role": "symbol",
      "title": "keepNetworkOutput",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest/keepnetworkoutput"
    },
    "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/outputPixelFormat": {
      "abstract": [
        {
          "text": "The pixel format type of the output value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputPixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/outputPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "outputPixelFormat",
      "type": "topic",
      "url": "/documentation/vision/vntrackopticalflowrequest/outputpixelformat"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Request",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/computationAccuracy-swift.property",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/keepNetworkOutput",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/outputPixelFormat"
      ],
      "title": "Configuring the Request"
    }
  ],
  "topicSections": [
    {
      "anchor": "Options",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/low",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/medium",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/high",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/veryHigh",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/low",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/medium",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/high",
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/veryHigh"
      ],
      "title": "Options"
    },
    {
      "anchor": "Creating-an-Accuracy-Option",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/init(rawValue:)"
      ],
      "title": "Creating an Accuracy Option"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNTrackOpticalFlowRequestComputationAccuracy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequestComputationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequestComputationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Options",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/low",
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/medium",
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/high",
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/veryHigh",
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/low",
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/medium",
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/high",
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/ComputationAccuracy-swift.enum/veryHigh"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Request",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/computationAccuracy-swift.property",
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/keepNetworkOutput",
                "doc://com.apple.vision/documentation/Vision/VNTrackOpticalFlowRequest/outputPixelFormat"
              ],
              "title": "Configuring the Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNTrackOpticalFlowRequestComputationAccuracy"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum~1high/title",
          "value": "VNTrackOpticalFlowRequestComputationAccuracyHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequestComputationAccuracyHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1outputPixelFormat/title",
          "value": "outputPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1outputPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum~1low/title",
          "value": "VNTrackOpticalFlowRequestComputationAccuracyLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequestComputationAccuracyLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1keepNetworkOutput/title",
          "value": "keepNetworkOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1keepNetworkOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keepNetworkOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum/title",
          "value": "VNTrackOpticalFlowRequestComputationAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequestComputationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequestComputationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest/title",
          "value": "VNTrackOpticalFlowRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum~1veryHigh/title",
          "value": "VNTrackOpticalFlowRequestComputationAccuracyVeryHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum~1veryHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequestComputationAccuracyVeryHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum~1medium/title",
          "value": "VNTrackOpticalFlowRequestComputationAccuracyMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1ComputationAccuracy-swift.enum~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNTrackOpticalFlowRequestComputationAccuracyMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1computationAccuracy-swift.property/title",
          "value": "computationAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNTrackOpticalFlowRequest~1computationAccuracy-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "computationAccuracy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vntrackopticalflowrequest/computationaccuracy-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vntrackopticalflowrequest/computationaccuracy-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
