{
  "abstract": [
    {
      "text": "A value indicating that the delete operation removes the item and all of its children.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDeleteItemOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDeleteItemOptions/recursive"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFileProviderDeleteItemOptions@NSFileProviderDeleteItemRecursive",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "recursive"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSFileProviderDeleteItemOptions",
        "text": "NSFileProviderDeleteItemOptions"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderDeleteItemRecursive"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "recursive"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "recursive"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDeleteItemOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSFileProviderDeleteItemOptions",
              "text": "NSFileProviderDeleteItemOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDeleteItemOptions": {
      "abstract": [
        {
          "text": "Options for deleting items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderDeleteItemOptions"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDeleteItemOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderDeleteItemOptions"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderDeleteItemOptions",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderdeleteitemoptions"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDeleteItemOptions/recursive": {
      "abstract": [
        {
          "text": "A value indicating that the delete operation removes the item and all of its children.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recursive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderDeleteItemOptions",
          "text": "NSFileProviderDeleteItemOptions"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDeleteItemOptions/recursive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderDeleteItemRecursive"
        }
      ],
      "role": "symbol",
      "title": "recursive",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderdeleteitemoptions/recursive"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFileProviderDeleteItemRecursive"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderDeleteItemRecursive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDeleteItemOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSFileProviderDeleteItemRecursive"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderDeleteItemOptions~1recursive/title",
          "value": "NSFileProviderDeleteItemRecursive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderDeleteItemOptions~1recursive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderDeleteItemRecursive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderDeleteItemOptions/title",
          "value": "NSFileProviderDeleteItemOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderDeleteItemOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderDeleteItemOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderDeleteItemOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderDeleteItemOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileproviderdeleteitemoptions/recursive"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileproviderdeleteitemoptions/recursive"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
