{
  "abstract": [
    {
      "text": "The whole face expressions that the algorithm detects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/wholeFaceExpressions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SRFaceMetrics(py)wholeFaceExpressions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "wholeFaceExpressions"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRFaceMetricsExpression",
        "text": "SRFaceMetricsExpression"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "wholeFaceExpressions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "wholeFaceExpressions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "wholeFaceExpressions"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetricsExpression",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRFaceMetricsExpression",
              "text": "SRFaceMetricsExpression"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics": {
      "abstract": [
        {
          "text": "An object that represents metrics about the user’s face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRFaceMetrics"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRFaceMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRFaceMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srfacemetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/faceAnchor": {
      "abstract": [
        {
          "text": "The anchor for the face that the sensor detects in front of the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFaceAnchor",
          "text": "ARFaceAnchor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/faceAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "faceAnchor"
        }
      ],
      "role": "symbol",
      "title": "faceAnchor",
      "type": "topic",
      "url": "/documentation/sensorkit/srfacemetrics/faceanchor"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/partialFaceExpressions": {
      "abstract": [
        {
          "text": "The partial face expressions that the algorithm detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partialFaceExpressions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFaceMetricsExpression",
          "text": "SRFaceMetricsExpression"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/partialFaceExpressions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "partialFaceExpressions"
        }
      ],
      "role": "symbol",
      "title": "partialFaceExpressions",
      "type": "topic",
      "url": "/documentation/sensorkit/srfacemetrics/partialfaceexpressions"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/wholeFaceExpressions": {
      "abstract": [
        {
          "text": "The whole face expressions that the algorithm detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wholeFaceExpressions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFaceMetricsExpression",
          "text": "SRFaceMetricsExpression"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/wholeFaceExpressions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wholeFaceExpressions"
        }
      ],
      "role": "symbol",
      "title": "wholeFaceExpressions",
      "type": "topic",
      "url": "/documentation/sensorkit/srfacemetrics/wholefaceexpressions"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetricsExpression": {
      "abstract": [
        {
          "text": "An object that represents a facial expression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRFaceMetricsExpression"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetricsExpression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRFaceMetricsExpression"
        }
      ],
      "role": "symbol",
      "title": "SRFaceMetricsExpression",
      "type": "topic",
      "url": "/documentation/sensorkit/srfacemetricsexpression"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-face-analytics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/faceAnchor",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/partialFaceExpressions",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetricsExpression"
      ],
      "title": "Getting face analytics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "wholeFaceExpressions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wholeFaceExpressions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-face-analytics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/faceAnchor",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics/partialFaceExpressions",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetricsExpression"
              ],
              "title": "Getting face analytics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<SRFaceMetricsExpression *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "wholeFaceExpressions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics/title",
          "value": "SRFaceMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFaceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFaceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics~1faceAnchor/title",
          "value": "faceAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics~1faceAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "faceAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics~1partialFaceExpressions/title",
          "value": "partialFaceExpressions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics~1partialFaceExpressions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "partialFaceExpressions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics~1wholeFaceExpressions/title",
          "value": "wholeFaceExpressions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics~1wholeFaceExpressions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wholeFaceExpressions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetricsExpression/title",
          "value": "SRFaceMetricsExpression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetricsExpression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFaceMetricsExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetricsExpression/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFaceMetricsExpression"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srfacemetrics/wholefaceexpressions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srfacemetrics/wholefaceexpressions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
