{
  "abstract": [
    {
      "text": "The key you use to access the optimizer’s learning rate parameter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML",
        "doc://com.apple.coreml/documentation/CoreML/MLParameterKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/learningRate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLParameterKey(cpy)learningRate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "learningRate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MLParameterKey",
        "text": "MLParameterKey"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "learningRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "learningRate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "learningRate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLParameterKey",
              "text": "MLParameterKey"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value type for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/learningRate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key is a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/Double",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To modify a model’s learning rate midway through an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", use its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/resume(withParameters:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to set a new value for the model’s learning rate. You do this in the progress handler that you specified in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateProgressHandlers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance when you created the update task using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:progressHandlers:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/personalizing-a-model-with-on-device-updates",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey": {
      "abstract": [
        {
          "text": "The keys for the parameter dictionary in a model configuration or a model update context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLParameterKey"
        }
      ],
      "role": "symbol",
      "title": "MLParameterKey",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/beta1": {
      "abstract": [
        {
          "text": "The key you use to access the Adam optimizer’s first beta parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beta1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/beta1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beta1"
        }
      ],
      "role": "symbol",
      "title": "beta1",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey/beta1"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/beta2": {
      "abstract": [
        {
          "text": "The key you use to access the Adam optimizer’s second beta parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beta2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/beta2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beta2"
        }
      ],
      "role": "symbol",
      "title": "beta2",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey/beta2"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/epochs": {
      "abstract": [
        {
          "text": "The key you use to access the optimizer’s epochs parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "epochs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/epochs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "epochs"
        }
      ],
      "role": "symbol",
      "title": "epochs",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey/epochs"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/eps": {
      "abstract": [
        {
          "text": "The key you use to access the Adam optimizer’s epsilon parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eps"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/eps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eps"
        }
      ],
      "role": "symbol",
      "title": "eps",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey/eps"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/learningRate": {
      "abstract": [
        {
          "text": "The key you use to access the optimizer’s learning rate parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "learningRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/learningRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "learningRate"
        }
      ],
      "role": "symbol",
      "title": "learningRate",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey/learningrate"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/miniBatchSize": {
      "abstract": [
        {
          "text": "The key you use to access the optimizer’s mini batch-size parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miniBatchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/miniBatchSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "miniBatchSize"
        }
      ],
      "role": "symbol",
      "title": "miniBatchSize",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey/minibatchsize"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/momentum": {
      "abstract": [
        {
          "text": "The key you use to access the stochastic gradient descent (SGD) optimizer’s momentum parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/momentum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "momentum"
        }
      ],
      "role": "symbol",
      "title": "momentum",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey/momentum"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/seed": {
      "abstract": [
        {
          "text": "The key you use to access the seed parameter that initializes the random number generator for the shuffle option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/seed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "seed"
        }
      ],
      "role": "symbol",
      "title": "seed",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey/seed"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/shuffle": {
      "abstract": [
        {
          "text": "The key you use to access the shuffle parameter, a Boolean value that determines whether the model randomizes the data between epochs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shuffle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/shuffle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shuffle"
        }
      ],
      "role": "symbol",
      "title": "shuffle",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey/shuffle"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateProgressHandlers": {
      "abstract": [
        {
          "text": "A collection of closures an update task uses to notify your app of its progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLUpdateProgressHandlers"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateProgressHandlers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLUpdateProgressHandlers"
        }
      ],
      "role": "symbol",
      "title": "MLUpdateProgressHandlers",
      "type": "topic",
      "url": "/documentation/coreml/mlupdateprogresshandlers"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask": {
      "abstract": [
        {
          "text": "A task that updates a model with additional training data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLUpdateTask"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLUpdateTask"
        }
      ],
      "role": "symbol",
      "title": "MLUpdateTask",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:progressHandlers:)": {
      "abstract": [
        {
          "text": "Creates a task that updates the model at the URL with the training data and configuration, and calls the progress handlers during and after the update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forModelAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MLBatchProvider",
          "text": "MLBatchProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelConfiguration",
          "text": "MLModelConfiguration"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "progressHandlers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLUpdateProgressHandlers",
          "text": "MLUpdateProgressHandlers"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:progressHandlers:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateTaskForModelAtURL:trainingData:configuration:progressHandlers:error:"
        }
      ],
      "role": "symbol",
      "title": "init(forModelAt:trainingData:configuration:progressHandlers:)",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask/init(formodelat:trainingdata:configuration:progresshandlers:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/resume(withParameters:)": {
      "abstract": [
        {
          "text": "Resumes a model update with updated parameter values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resume"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/resume(withParameters:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resumeWithParameters:"
        }
      ],
      "role": "symbol",
      "title": "resume(withParameters:)",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask/resume(withparameters:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/personalizing-a-model-with-on-device-updates": {
      "abstract": [
        {
          "text": "Modify an updatable Core ML model by running an update task with labeled data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/personalizing-a-model-with-on-device-updates",
      "kind": "article",
      "role": "sampleCode",
      "title": "Personalizing a Model with On-Device Updates",
      "type": "topic",
      "url": "/documentation/coreml/personalizing-a-model-with-on-device-updates"
    },
    "doc://com.apple.documentation/documentation/Swift/Double": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Double",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Model-Update-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/momentum",
        "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/miniBatchSize",
        "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/beta1",
        "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/beta2",
        "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/eps",
        "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/epochs",
        "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/shuffle",
        "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/seed"
      ],
      "title": "Accessing Model Update Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "learningRate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "learningRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML",
                "doc://com.apple.coreml/documentation/CoreML/MLParameterKey"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Model-Update-Parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/momentum",
                "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/miniBatchSize",
                "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/beta1",
                "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/beta2",
                "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/eps",
                "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/epochs",
                "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/shuffle",
                "doc://com.apple.coreml/documentation/CoreML/MLParameterKey/seed"
              ],
              "title": "Accessing Model Update Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MLParameterKey",
                    "text": "MLParameterKey"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "learningRate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1eps/title",
          "value": "eps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1eps/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask/title",
          "value": "MLUpdateTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1learningRate/title",
          "value": "learningRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1learningRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "learningRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1beta1/title",
          "value": "beta1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1beta1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beta1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1miniBatchSize/title",
          "value": "miniBatchSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1miniBatchSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "miniBatchSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1seed/title",
          "value": "seed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1seed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "seed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1beta2/title",
          "value": "beta2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1beta2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beta2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1epochs/title",
          "value": "epochs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1epochs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "epochs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1momentum/title",
          "value": "momentum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1momentum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "momentum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1shuffle/title",
          "value": "shuffle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey~1shuffle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shuffle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey/title",
          "value": "MLParameterKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLParameterKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLParameterKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1resume(withParameters:)/title",
          "value": "resumeWithParameters:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1resume(withParameters:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resumeWithParameters:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1init(forModelAt:trainingData:configuration:progressHandlers:)/title",
          "value": "updateTaskForModelAtURL:trainingData:configuration:progressHandlers:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1init(forModelAt:trainingData:configuration:progressHandlers:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "updateTaskForModelAtURL:trainingData:configuration:progressHandlers:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateProgressHandlers/title",
          "value": "MLUpdateProgressHandlers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateProgressHandlers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateProgressHandlers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateProgressHandlers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateProgressHandlers"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlparameterkey/learningrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlparameterkey/learningrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
