{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/paravirtualizedgraphics-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Paravirtualized Graphics"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ParavirtualizedGraphics Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics": {
      "abstract": [
        {
          "text": "Add graphics acceleration to your guest driver stack.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
      "kind": "symbol",
      "role": "collection",
      "title": "Paravirtualized Graphics",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_CURSOR_GLYPH_HANDLER2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_CURSOR_GLYPH_HANDLER2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_CURSOR_GLYPH_HANDLER2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_CURSOR_GLYPH_HANDLER2"
        }
      ],
      "role": "symbol",
      "title": "PG_SUPPORT_CURSOR_GLYPH_HANDLER2",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pg_support_cursor_glyph_handler2"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_PORT_COUNT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_DISPLAY_PORT_COUNT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_PORT_COUNT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_DISPLAY_PORT_COUNT"
        }
      ],
      "role": "symbol",
      "title": "PG_SUPPORT_DISPLAY_PORT_COUNT",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pg_support_display_port_count"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_SLEEP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_DISPLAY_SLEEP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_SLEEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_DISPLAY_SLEEP"
        }
      ],
      "role": "symbol",
      "title": "PG_SUPPORT_DISPLAY_SLEEP",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pg_support_display_sleep"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_SLEEP_HANDLER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_DISPLAY_SLEEP_HANDLER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_SLEEP_HANDLER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_DISPLAY_SLEEP_HANDLER"
        }
      ],
      "role": "symbol",
      "title": "PG_SUPPORT_DISPLAY_SLEEP_HANDLER",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pg_support_display_sleep_handler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_EFI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_EFI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_EFI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_EFI"
        }
      ],
      "role": "symbol",
      "title": "PG_SUPPORT_EFI",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pg_support_efi"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER"
        }
      ],
      "role": "symbol",
      "title": "PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pg_support_modelist_responsiveness_handler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_PAUSE_UNPAUSE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_PAUSE_UNPAUSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_PAUSE_UNPAUSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_PAUSE_UNPAUSE"
        }
      ],
      "role": "symbol",
      "title": "PG_SUPPORT_PAUSE_UNPAUSE",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pg_support_pause_unpause"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_RESET": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_RESET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_RESET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PG_SUPPORT_RESET"
        }
      ],
      "role": "symbol",
      "title": "PG_SUPPORT_RESET",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pg_support_reset"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/paravirtualizedgraphics-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/paravirtualizedgraphics-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ParavirtualizedGraphics Data Types",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/paravirtualizedgraphics-data-types"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/paravirtualizedgraphics-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/paravirtualizedgraphics-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ParavirtualizedGraphics Functions",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/paravirtualizedgraphics-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/paravirtualizedgraphics-functions",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/paravirtualizedgraphics-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_CURSOR_GLYPH_HANDLER2",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_PORT_COUNT",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_SLEEP",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_SLEEP_HANDLER",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_PAUSE_UNPAUSE",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_RESET",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_EFI"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_CURSOR_GLYPH_HANDLER2",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_PORT_COUNT",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_SLEEP",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_DISPLAY_SLEEP_HANDLER",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_PAUSE_UNPAUSE",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_RESET",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PG_SUPPORT_EFI"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/paravirtualizedgraphics-functions",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/paravirtualizedgraphics-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_EFI/title",
          "value": "PG_SUPPORT_EFI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_EFI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PG_SUPPORT_EFI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_DISPLAY_PORT_COUNT/title",
          "value": "PG_SUPPORT_DISPLAY_PORT_COUNT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_DISPLAY_PORT_COUNT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PG_SUPPORT_DISPLAY_PORT_COUNT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_RESET/title",
          "value": "PG_SUPPORT_RESET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_RESET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PG_SUPPORT_RESET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_DISPLAY_SLEEP_HANDLER/title",
          "value": "PG_SUPPORT_DISPLAY_SLEEP_HANDLER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_DISPLAY_SLEEP_HANDLER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PG_SUPPORT_DISPLAY_SLEEP_HANDLER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_DISPLAY_SLEEP/title",
          "value": "PG_SUPPORT_DISPLAY_SLEEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_DISPLAY_SLEEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PG_SUPPORT_DISPLAY_SLEEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER/title",
          "value": "PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PG_SUPPORT_MODELIST_RESPONSIVENESS_HANDLER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_PAUSE_UNPAUSE/title",
          "value": "PG_SUPPORT_PAUSE_UNPAUSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_PAUSE_UNPAUSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PG_SUPPORT_PAUSE_UNPAUSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_CURSOR_GLYPH_HANDLER2/title",
          "value": "PG_SUPPORT_CURSOR_GLYPH_HANDLER2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PG_SUPPORT_CURSOR_GLYPH_HANDLER2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PG_SUPPORT_CURSOR_GLYPH_HANDLER2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/paravirtualizedgraphics-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/paravirtualizedgraphics-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
