{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGCreateDeviceWithDescriptor(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@PGCreateDeviceWithDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PGCreateDeviceWithDescriptor"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PGDeviceDescriptor",
        "text": "PGDeviceDescriptor"
      },
      {
        "kind": "text",
        "text": ") -> (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)PGDevice",
        "text": "PGDevice"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "Paravirtualized Graphics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PGCreateDeviceWithDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "PGCreateDeviceWithDescriptor(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PGCreateDeviceWithDescriptor"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "descriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PGDeviceDescriptor",
              "text": "PGDeviceDescriptor"
            },
            {
              "kind": "text",
              "text": ") -> (any "
            },
            {
              "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)PGDevice",
              "text": "PGDevice"
            },
            {
              "kind": "text",
              "text": ")?"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics": {
      "abstract": [
        {
          "text": "Add graphics acceleration to your guest driver stack.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
      "kind": "symbol",
      "role": "collection",
      "title": "Paravirtualized Graphics",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGCreateDeviceWithDescriptor(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGCreateDeviceWithDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PGDeviceDescriptor",
          "text": "PGDeviceDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PGDevice",
          "text": "PGDevice"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGCreateDeviceWithDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGCreateDeviceWithDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PGCreateDeviceWithDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgcreatedevicewithdescriptor(_:)"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice": {
      "abstract": [
        {
          "text": "A paravirtualized GPU device object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDevice"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDevice"
        }
      ],
      "role": "symbol",
      "title": "PGDevice",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor": {
      "abstract": [
        {
          "text": "A description of the paravirtualized graphics device to create.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDeviceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDeviceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PGDeviceDescriptor",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PGCreateDeviceWithDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGCreateDeviceWithDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)PGDevice",
                    "text": "id<PGDevice>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PGCreateDeviceWithDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PGDeviceDescriptor",
                    "text": "PGDeviceDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "descriptor"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGCreateDeviceWithDescriptor(_:)/title",
          "value": "PGCreateDeviceWithDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGCreateDeviceWithDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGCreateDeviceWithDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor/title",
          "value": "PGDeviceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDeviceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDeviceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice/title",
          "value": "PGDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDevice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgcreatedevicewithdescriptor(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgcreatedevicewithdescriptor(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
