{
  "abstract": [
    {
      "text": "A description of the paravirtualized graphics device to create.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PGDeviceDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PGDeviceDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Paravirtualized Graphics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PGDeviceDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PGDeviceDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PGDeviceDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics": {
      "abstract": [
        {
          "text": "Add graphics acceleration to your guest driver stack.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
      "kind": "symbol",
      "role": "collection",
      "title": "Paravirtualized Graphics",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGAddTraceRange": {
      "abstract": [
        {
          "text": "The block signature for a routine that adds a trace range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGAddTraceRange"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGAddTraceRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGAddTraceRange"
        }
      ],
      "role": "symbol",
      "title": "PGAddTraceRange",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgaddtracerange"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGCreateTask": {
      "abstract": [
        {
          "text": "The block signature for a routine that creates a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGCreateTask"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGCreateTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGCreateTask"
        }
      ],
      "role": "symbol",
      "title": "PGCreateTask",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgcreatetask"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDestroyTask": {
      "abstract": [
        {
          "text": "The block signature for a routine that destroys a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDestroyTask"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDestroyTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDestroyTask"
        }
      ],
      "role": "symbol",
      "title": "PGDestroyTask",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdestroytask"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice": {
      "abstract": [
        {
          "text": "A paravirtualized GPU device object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDevice"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDevice"
        }
      ],
      "role": "symbol",
      "title": "PGDevice",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor": {
      "abstract": [
        {
          "text": "A description of the paravirtualized graphics device to create.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDeviceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDeviceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PGDeviceDescriptor",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/addTraceRange": {
      "abstract": [
        {
          "text": "A handler that the framework calls to add a trace range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTraceRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGAddTraceRange",
          "text": "PGAddTraceRange"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/addTraceRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addTraceRange"
        }
      ],
      "role": "symbol",
      "title": "addTraceRange",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/addtracerange"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/createTask": {
      "abstract": [
        {
          "text": "A handler that the framework calls to create a task object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createTask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGCreateTask",
          "text": "PGCreateTask"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/createTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createTask"
        }
      ],
      "role": "symbol",
      "title": "createTask",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/createtask"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/destroyTask": {
      "abstract": [
        {
          "text": "A handler that the framework calls to destroy a task object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destroyTask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGDestroyTask",
          "text": "PGDestroyTask"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/destroyTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destroyTask"
        }
      ],
      "role": "symbol",
      "title": "destroyTask",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/destroytask"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/device": {
      "abstract": [
        {
          "text": "The Metal device object to use to back the virtual graphics device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/device",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "device"
        }
      ],
      "role": "symbol",
      "title": "device",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/device"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/displayPortCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayPortCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/displayPortCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayPortCount"
        }
      ],
      "role": "symbol",
      "title": "displayPortCount",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/displayportcount"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/mapMemory": {
      "abstract": [
        {
          "text": "A handler that the framework calls to map memory into the virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapMemory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGMapMemory",
          "text": "PGMapMemory"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/mapMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapMemory"
        }
      ],
      "role": "symbol",
      "title": "mapMemory",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/mapmemory"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/mmioLength": {
      "abstract": [
        {
          "text": "The length in bytes of the memory-mapped IO section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mmioLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/mmioLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mmioLength"
        }
      ],
      "role": "symbol",
      "title": "mmioLength",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/mmiolength"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/raiseInterrupt": {
      "abstract": [
        {
          "text": "A handler that the system calls to raise an interrupt in the guest environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "raiseInterrupt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGRaiseInterrupt",
          "text": "PGRaiseInterrupt"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/raiseInterrupt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "raiseInterrupt"
        }
      ],
      "role": "symbol",
      "title": "raiseInterrupt",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/raiseinterrupt"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/readMemory": {
      "abstract": [
        {
          "text": "A handler that the framework calls to read data from the guest’s memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readMemory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGReadMemory",
          "text": "PGReadMemory"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/readMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readMemory"
        }
      ],
      "role": "symbol",
      "title": "readMemory",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/readmemory"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/removeTraceRange": {
      "abstract": [
        {
          "text": "A handler that the framework calls to remove a trace range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTraceRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGRemoveTraceRange",
          "text": "PGRemoveTraceRange"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/removeTraceRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeTraceRange"
        }
      ],
      "role": "symbol",
      "title": "removeTraceRange",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/removetracerange"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/unmapMemory": {
      "abstract": [
        {
          "text": "A handler that the framework calls to unmap memory from the virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unmapMemory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGUnmapMemory",
          "text": "PGUnmapMemory"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/unmapMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unmapMemory"
        }
      ],
      "role": "symbol",
      "title": "unmapMemory",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor/unmapmemory"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGMapMemory": {
      "abstract": [
        {
          "text": "The block signature for a routine that maps guest physical memory into a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGMapMemory"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGMapMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGMapMemory"
        }
      ],
      "role": "symbol",
      "title": "PGMapMemory",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgmapmemory"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGNewDeviceWithDescriptor(_:)": {
      "abstract": [
        {
          "text": "Creates a new paravirtualized graphics device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGNewDeviceWithDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PGDeviceDescriptor",
          "text": "PGDeviceDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PGDevice",
          "text": "PGDevice"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGNewDeviceWithDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGNewDeviceWithDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PGNewDeviceWithDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgnewdevicewithdescriptor(_:)"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGPhysicalMemoryRange_s": {
      "abstract": [
        {
          "text": "A range in the guest virtual machine’s physical memory address space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGPhysicalMemoryRange_s"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGPhysicalMemoryRange_s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGPhysicalMemoryRange_s"
        }
      ],
      "role": "symbol",
      "title": "PGPhysicalMemoryRange_s",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgphysicalmemoryrange_s"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGRaiseInterrupt": {
      "abstract": [
        {
          "text": "The block signature for a routine that raises interrupts in the guest environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGRaiseInterrupt"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGRaiseInterrupt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGRaiseInterrupt"
        }
      ],
      "role": "symbol",
      "title": "PGRaiseInterrupt",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgraiseinterrupt"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGReadMemory": {
      "abstract": [
        {
          "text": "The block signature for a routine that copies data from guest physical memory into host memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGReadMemory"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGReadMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGReadMemory"
        }
      ],
      "role": "symbol",
      "title": "PGReadMemory",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgreadmemory"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGRemoveTraceRange": {
      "abstract": [
        {
          "text": "The block signature for a routine that removes a trace range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGRemoveTraceRange"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGRemoveTraceRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGRemoveTraceRange"
        }
      ],
      "role": "symbol",
      "title": "PGRemoveTraceRange",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgremovetracerange"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGTask_t": {
      "abstract": [
        {
          "text": "An opaque data pointer representing a specific virtual task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PGTask_t"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGTask_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "PGTask_t",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgtask_t"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGTraceRangeHandler": {
      "abstract": [
        {
          "text": "The block signature for a routine that handles trace requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGTraceRangeHandler"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGTraceRangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGTraceRangeHandler"
        }
      ],
      "role": "symbol",
      "title": "PGTraceRangeHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgtracerangehandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGTraceRange_t": {
      "abstract": [
        {
          "text": "An opaque data pointer representing a specific trace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PGTraceRange_t"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGTraceRange_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "PGTraceRange_t",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgtracerange_t"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGUnmapMemory": {
      "abstract": [
        {
          "text": "The block signature for a routine that unmaps guest physical memory from a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGUnmapMemory"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGUnmapMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGUnmapMemory"
        }
      ],
      "role": "symbol",
      "title": "PGUnmapMemory",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgunmapmemory"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGNewDeviceWithDescriptor(_:)",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice"
      ],
      "title": "Devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-the-GPU",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/device"
      ],
      "title": "Specifying the GPU"
    },
    {
      "anchor": "Managing-Tasks",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/createTask",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/destroyTask",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGCreateTask",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDestroyTask"
      ],
      "title": "Managing Tasks"
    },
    {
      "anchor": "Managing-Memory-Operations",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/mapMemory",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/unmapMemory",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/readMemory",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGMapMemory",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGUnmapMemory",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGReadMemory",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGPhysicalMemoryRange_s"
      ],
      "title": "Managing Memory Operations"
    },
    {
      "anchor": "Specifying-Trace-Behavior",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/addTraceRange",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/removeTraceRange",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGAddTraceRange",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGRemoveTraceRange",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGTraceRangeHandler"
      ],
      "title": "Specifying Trace Behavior"
    },
    {
      "anchor": "Handling-Interrupts",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/raiseInterrupt",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGRaiseInterrupt"
      ],
      "title": "Handling Interrupts"
    },
    {
      "anchor": "Specifying-Virtual-Device-Properties",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/mmioLength"
      ],
      "title": "Specifying Virtual Device Properties"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/displayPortCount"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PGDeviceDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDeviceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDeviceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-the-GPU",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/device"
              ],
              "title": "Specifying the GPU"
            },
            {
              "anchor": "Managing-Tasks",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/createTask",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/destroyTask",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGCreateTask",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDestroyTask",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGTask_t"
              ],
              "title": "Managing Tasks"
            },
            {
              "anchor": "Managing-Memory-Operations",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/mapMemory",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/unmapMemory",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/readMemory",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGMapMemory",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGUnmapMemory",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGReadMemory",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGPhysicalMemoryRange_s"
              ],
              "title": "Managing Memory Operations"
            },
            {
              "anchor": "Specifying-Trace-Behavior",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/addTraceRange",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/removeTraceRange",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGAddTraceRange",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGRemoveTraceRange",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGTraceRangeHandler",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGTraceRange_t"
              ],
              "title": "Specifying Trace Behavior"
            },
            {
              "anchor": "Handling-Interrupts",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/raiseInterrupt",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGRaiseInterrupt"
              ],
              "title": "Handling Interrupts"
            },
            {
              "anchor": "Specifying-Virtual-Device-Properties",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/mmioLength"
              ],
              "title": "Specifying Virtual Device Properties"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor/displayPortCount"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGNewDeviceWithDescriptor(_:)",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice"
              ],
              "title": "Devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PGDeviceDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice/title",
          "value": "PGDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGUnmapMemory/title",
          "value": "PGUnmapMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGUnmapMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGUnmapMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGUnmapMemory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGUnmapMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDestroyTask/title",
          "value": "PGDestroyTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDestroyTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDestroyTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDestroyTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDestroyTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor/title",
          "value": "PGDeviceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDeviceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDeviceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGMapMemory/title",
          "value": "PGMapMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGMapMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGMapMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGMapMemory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGMapMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1device/title",
          "value": "device"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1device/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGCreateTask/title",
          "value": "PGCreateTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGCreateTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGCreateTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGCreateTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGCreateTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGRemoveTraceRange/title",
          "value": "PGRemoveTraceRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGRemoveTraceRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGRemoveTraceRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGRemoveTraceRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGRemoveTraceRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGReadMemory/title",
          "value": "PGReadMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGReadMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGReadMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGReadMemory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGReadMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGTraceRangeHandler/title",
          "value": "PGTraceRangeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGTraceRangeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGTraceRangeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGTraceRangeHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGTraceRangeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1raiseInterrupt/title",
          "value": "raiseInterrupt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1raiseInterrupt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "raiseInterrupt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGAddTraceRange/title",
          "value": "PGAddTraceRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGAddTraceRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGAddTraceRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGAddTraceRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGAddTraceRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGNewDeviceWithDescriptor(_:)/title",
          "value": "PGNewDeviceWithDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGNewDeviceWithDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGNewDeviceWithDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1addTraceRange/title",
          "value": "addTraceRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1addTraceRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addTraceRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1mapMemory/title",
          "value": "mapMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1mapMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mapMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGPhysicalMemoryRange_s/title",
          "value": "PGPhysicalMemoryRange_s"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGPhysicalMemoryRange_s/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGPhysicalMemoryRange_s"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGPhysicalMemoryRange_s/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGPhysicalMemoryRange_s"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1createTask/title",
          "value": "createTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1createTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "createTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGRaiseInterrupt/title",
          "value": "PGRaiseInterrupt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGRaiseInterrupt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGRaiseInterrupt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGRaiseInterrupt/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGRaiseInterrupt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1removeTraceRange/title",
          "value": "removeTraceRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1removeTraceRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "removeTraceRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1readMemory/title",
          "value": "readMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1readMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1unmapMemory/title",
          "value": "unmapMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1unmapMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unmapMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1displayPortCount/title",
          "value": "displayPortCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1displayPortCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayPortCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1destroyTask/title",
          "value": "destroyTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1destroyTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destroyTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1mmioLength/title",
          "value": "mmioLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor~1mmioLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mmioLength"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgdevicedescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgdevicedescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
