{
  "abstract": [
    {
      "text": "A paravirtualized GPU device object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PGDevice",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PGDevice"
      }
    ],
    "modules": [
      {
        "name": "Paravirtualized Graphics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PGDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PGDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PGDevice"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics": {
      "abstract": [
        {
          "text": "Add graphics acceleration to your guest driver stack.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
      "kind": "symbol",
      "role": "collection",
      "title": "Paravirtualized Graphics",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice": {
      "abstract": [
        {
          "text": "A paravirtualized GPU device object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDevice"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDevice"
        }
      ],
      "role": "symbol",
      "title": "PGDevice",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/didResume()": {
      "abstract": [
        {
          "text": "Tells the device object to finish any remaining work to resume processing of a previously saved device’s suspend state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didResume"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/didResume()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didResume"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "didResume()",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/didresume()"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/finishSuspend()": {
      "abstract": [
        {
          "text": "Notifies the virtualized graphics device to finish suspending graphics activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishSuspend"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/finishSuspend()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishSuspend"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "finishSuspend()",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/finishsuspend()"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/mmioRead(atOffset:)": {
      "abstract": [
        {
          "text": "Reads data from the virtual graphics device’s memory-mapped I/O region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mmioRead"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/mmioRead(atOffset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mmioReadAtOffset:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "mmioRead(atOffset:)",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/mmioread(atoffset:)"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/mmioWrite(atOffset:value:)": {
      "abstract": [
        {
          "text": "Writes data to the virtual graphics device’s memory-mapped I/O region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mmioWrite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/mmioWrite(atOffset:value:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mmioWriteAtOffset:value:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "mmioWrite(atOffset:value:)",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/mmiowrite(atoffset:value:)"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/newDisplay(with:port:serialNum:)": {
      "abstract": [
        {
          "text": "Create a display from the specified descriptor and uniquifying parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newDisplay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PGDisplayDescriptor",
          "text": "PGDisplayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "port"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "serialNum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PGDisplay",
          "text": "PGDisplay"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/newDisplay(with:port:serialNum:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newDisplayWithDescriptor:port:serialNum:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "newDisplay(with:port:serialNum:)",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/newdisplay(with:port:serialnum:)"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/pause()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/pause()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pause()",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/pause()"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/reset()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reset"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/reset()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reset"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "reset()",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/reset()"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/stop()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/stop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stop"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "stop()",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/stop()"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/unpause()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unpause"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/unpause()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unpause"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "unpause()",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/unpause()"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/willResume(withSuspendState:error:)": {
      "abstract": [
        {
          "text": "Tells a new device object to load a previously saved device’s suspend state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willResume"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withSuspendState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14NSErrorPointera",
          "text": "NSErrorPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/willResume(withSuspendState:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willResumeWithSuspendState:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "willResume(withSuspendState:error:)",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/willresume(withsuspendstate:error:)"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/willSuspend()": {
      "abstract": [
        {
          "text": "Notifies the virtual graphics device to start suspending graphics activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willSuspend"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/willSuspend()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willSuspend"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "willSuspend()",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevice/willsuspend()"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor": {
      "abstract": [
        {
          "text": "A description of the paravirtualized graphics device to create.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDeviceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDeviceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PGDeviceDescriptor",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdevicedescriptor"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGNewDeviceWithDescriptor(_:)": {
      "abstract": [
        {
          "text": "Creates a new paravirtualized graphics device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGNewDeviceWithDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PGDeviceDescriptor",
          "text": "PGDeviceDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PGDevice",
          "text": "PGDevice"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGNewDeviceWithDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGNewDeviceWithDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PGNewDeviceWithDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgnewdevicewithdescriptor(_:)"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode": {
      "abstract": [
        {
          "text": "Error codes for suspend-resume actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGResumeErrorCode"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGResumeErrorCode"
        }
      ],
      "role": "symbol",
      "title": "PGResumeErrorCode",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgresumeerrorcode"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for suspend-resume actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGResumeErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGResumeErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PGResumeErrorDomain",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgresumeerrordomain"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGNewDeviceWithDescriptor(_:)",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor"
      ],
      "title": "Devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-Memory-Mapped-IO",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/mmioRead(atOffset:)",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/mmioWrite(atOffset:value:)"
      ],
      "title": "Handling Memory-Mapped I/O"
    },
    {
      "anchor": "Suspending-and-Resuming-Graphics-Processing",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/willSuspend()",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/finishSuspend()",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/willResume(withSuspendState:error:)",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/didResume()",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorDomain",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode"
      ],
      "title": "Suspending and Resuming Graphics Processing"
    },
    {
      "anchor": "Managing-Displays",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/newDisplay(with:port:serialNum:)"
      ],
      "title": "Managing Displays"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/pause()",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/reset()",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/stop()",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/unpause()"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PGDevice"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-Memory-Mapped-IO",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/mmioRead(atOffset:)",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/mmioWrite(atOffset:value:)"
              ],
              "title": "Handling Memory-Mapped I/O"
            },
            {
              "anchor": "Suspending-and-Resuming-Graphics-Processing",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/willSuspend()",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/finishSuspend()",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/willResume(withSuspendState:error:)",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/didResume()",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorDomain",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGResumeErrorCode"
              ],
              "title": "Suspending and Resuming Graphics Processing"
            },
            {
              "anchor": "Managing-Displays",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/newDisplay(with:port:serialNum:)"
              ],
              "title": "Managing Displays"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/pause()",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/reset()",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/stop()",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDevice/unpause()"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGNewDeviceWithDescriptor(_:)",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDeviceDescriptor"
              ],
              "title": "Devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PGDevice"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1willResume(withSuspendState:error:)/title",
          "value": "willResumeWithSuspendState:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1willResume(withSuspendState:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willResumeWithSuspendState:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1stop()/title",
          "value": "stop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1stop()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorDomain/title",
          "value": "PGResumeErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1mmioRead(atOffset:)/title",
          "value": "mmioReadAtOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1mmioRead(atOffset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mmioReadAtOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode/title",
          "value": "PGResumeErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGResumeErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGResumeErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor/title",
          "value": "PGDeviceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDeviceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDeviceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDeviceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1newDisplay(with:port:serialNum:)/title",
          "value": "newDisplayWithDescriptor:port:serialNum:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1newDisplay(with:port:serialNum:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newDisplayWithDescriptor:port:serialNum:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1willSuspend()/title",
          "value": "willSuspend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1willSuspend()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willSuspend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGNewDeviceWithDescriptor(_:)/title",
          "value": "PGNewDeviceWithDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGNewDeviceWithDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGNewDeviceWithDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1pause()/title",
          "value": "pause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1pause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1unpause()/title",
          "value": "unpause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1unpause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unpause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice/title",
          "value": "PGDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1didResume()/title",
          "value": "didResume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1didResume()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didResume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1reset()/title",
          "value": "reset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1reset()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1mmioWrite(atOffset:value:)/title",
          "value": "mmioWriteAtOffset:value:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1mmioWrite(atOffset:value:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mmioWriteAtOffset:value:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1finishSuspend()/title",
          "value": "finishSuspend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDevice~1finishSuspend()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishSuspend"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgdevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgdevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
