{
  "abstract": [
    {
      "text": "A descriptor for a virtual display.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PGDisplayDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PGDisplayDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Paravirtualized Graphics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PGDisplayDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PGDisplayDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PGDisplayDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics": {
      "abstract": [
        {
          "text": "Add graphics acceleration to your guest driver stack.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics",
      "kind": "symbol",
      "role": "collection",
      "title": "Paravirtualized Graphics",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay": {
      "abstract": [
        {
          "text": "An object that provides display functionality to the guest operating system in a way that the host-side virtual machine app can intercept.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDisplay"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDisplay"
        }
      ],
      "role": "symbol",
      "title": "PGDisplay",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplay"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCoord_t": {
      "abstract": [
        {
          "text": "Coordinates that describe sizes or offsets within a 2D array of pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDisplayCoord_t"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCoord_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDisplayCoord_t"
        }
      ],
      "role": "symbol",
      "title": "PGDisplayCoord_t",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaycoord_t"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCursorGlyphHandler": {
      "abstract": [
        {
          "text": "The block signature for a routine that handles changes to the cursor’s appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDisplayCursorGlyphHandler"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCursorGlyphHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDisplayCursorGlyphHandler"
        }
      ],
      "role": "symbol",
      "title": "PGDisplayCursorGlyphHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaycursorglyphhandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCursorShowHandler": {
      "abstract": [
        {
          "text": "The block signature for a routine that handles changes to the cursor’s visibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDisplayCursorShowHandler"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCursorShowHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDisplayCursorShowHandler"
        }
      ],
      "role": "symbol",
      "title": "PGDisplayCursorShowHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaycursorshowhandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor": {
      "abstract": [
        {
          "text": "A descriptor for a virtual display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDisplayDescriptor"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDisplayDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PGDisplayDescriptor",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaydescriptor"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorGlyphHandler": {
      "abstract": [
        {
          "text": "A handler that the framework calls to change the cursor’s appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursorGlyphHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGDisplayCursorGlyphHandler",
          "text": "PGDisplayCursorGlyphHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorGlyphHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cursorGlyphHandler"
        }
      ],
      "role": "symbol",
      "title": "cursorGlyphHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaydescriptor/cursorglyphhandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorMoveHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursorMoveHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGDisplayCursorMoveHandler",
          "text": "PGDisplayCursorMoveHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorMoveHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cursorMoveHandler"
        }
      ],
      "role": "symbol",
      "title": "cursorMoveHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaydescriptor/cursormovehandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorShowHandler": {
      "abstract": [
        {
          "text": "A handler that the framework calls to change the cursor’s visibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursorShowHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGDisplayCursorShowHandler",
          "text": "PGDisplayCursorShowHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorShowHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cursorShowHandler"
        }
      ],
      "role": "symbol",
      "title": "cursorShowHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaydescriptor/cursorshowhandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/modeChangeHandler": {
      "abstract": [
        {
          "text": "A handler that the framework calls to change the virtual display’s graphics mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modeChangeHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGDisplayModeChangeHandler",
          "text": "PGDisplayModeChangeHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/modeChangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modeChangeHandler"
        }
      ],
      "role": "symbol",
      "title": "modeChangeHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaydescriptor/modechangehandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/name": {
      "abstract": [
        {
          "text": "The display’s name as seen in the guest operating environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaydescriptor/name"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/newFrameEventHandler": {
      "abstract": [
        {
          "text": "A handler that the framework calls when the guest environment has a new frame to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newFrameEventHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PGDisplayNewFrameEventHandler",
          "text": "PGDisplayNewFrameEventHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/newFrameEventHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newFrameEventHandler"
        }
      ],
      "role": "symbol",
      "title": "newFrameEventHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaydescriptor/newframeeventhandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/queue": {
      "abstract": [
        {
          "text": "The queue that the framework uses when dispatching messages to any of the display’s registered handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/queue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queue"
        }
      ],
      "role": "symbol",
      "title": "queue",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaydescriptor/queue"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/sizeInMillimeters": {
      "abstract": [
        {
          "text": "The size in millimeters of the virtual display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeInMillimeters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/sizeInMillimeters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sizeInMillimeters"
        }
      ],
      "role": "symbol",
      "title": "sizeInMillimeters",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaydescriptor/sizeinmillimeters"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayMode": {
      "abstract": [
        {
          "text": "A description of a supported display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "PGDisplayMode",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaymode"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayModeChangeHandler": {
      "abstract": [
        {
          "text": "The block signature for a routine that handles changes to the display’s graphics mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDisplayModeChangeHandler"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayModeChangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDisplayModeChangeHandler"
        }
      ],
      "role": "symbol",
      "title": "PGDisplayModeChangeHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaymodechangehandler"
    },
    "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayNewFrameEventHandler": {
      "abstract": [
        {
          "text": "The block signature for a routine that handles frame updates from the guest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PGDisplayNewFrameEventHandler"
        }
      ],
      "identifier": "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayNewFrameEventHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PGDisplayNewFrameEventHandler"
        }
      ],
      "role": "symbol",
      "title": "PGDisplayNewFrameEventHandler",
      "type": "topic",
      "url": "/documentation/paravirtualizedgraphics/pgdisplaynewframeeventhandler"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Displays",
      "generated": true,
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayMode",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCoord_t"
      ],
      "title": "Displays"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-the-Display-Properties",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/name",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/sizeInMillimeters"
      ],
      "title": "Specifying the Display Properties"
    },
    {
      "anchor": "Setting-the-Dispatch-Queue",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/queue"
      ],
      "title": "Setting the Dispatch Queue"
    },
    {
      "anchor": "Managing-Cursor-Events",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorGlyphHandler",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorShowHandler",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCursorGlyphHandler",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCursorShowHandler"
      ],
      "title": "Managing Cursor Events"
    },
    {
      "anchor": "Handling-Mode-Changes",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/modeChangeHandler",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayModeChangeHandler"
      ],
      "title": "Handling Mode Changes"
    },
    {
      "anchor": "Handling-Frame-Events",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/newFrameEventHandler",
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayNewFrameEventHandler"
      ],
      "title": "Handling Frame Events"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorMoveHandler"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PGDisplayDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-the-Display-Properties",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/name",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/sizeInMillimeters"
              ],
              "title": "Specifying the Display Properties"
            },
            {
              "anchor": "Setting-the-Dispatch-Queue",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/queue"
              ],
              "title": "Setting the Dispatch Queue"
            },
            {
              "anchor": "Managing-Cursor-Events",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorGlyphHandler",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorShowHandler",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCursorGlyphHandler",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCursorShowHandler"
              ],
              "title": "Managing Cursor Events"
            },
            {
              "anchor": "Handling-Mode-Changes",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/modeChangeHandler",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayModeChangeHandler"
              ],
              "title": "Handling Mode Changes"
            },
            {
              "anchor": "Handling-Frame-Events",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/newFrameEventHandler",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayNewFrameEventHandler"
              ],
              "title": "Handling Frame Events"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayDescriptor/cursorMoveHandler"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Displays",
              "generated": true,
              "identifiers": [
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplay",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayMode",
                "doc://com.apple.paravirtualizedgraphics/documentation/ParavirtualizedGraphics/PGDisplayCoord_t"
              ],
              "title": "Displays"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PGDisplayDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1cursorGlyphHandler/title",
          "value": "cursorGlyphHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1cursorGlyphHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cursorGlyphHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor/title",
          "value": "PGDisplayDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1modeChangeHandler/title",
          "value": "modeChangeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1modeChangeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "modeChangeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayNewFrameEventHandler/title",
          "value": "PGDisplayNewFrameEventHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayNewFrameEventHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayNewFrameEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayNewFrameEventHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayNewFrameEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1queue/title",
          "value": "queue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1queue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayCursorGlyphHandler/title",
          "value": "PGDisplayCursorGlyphHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayCursorGlyphHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayCursorGlyphHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayCursorGlyphHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayCursorGlyphHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayMode/title",
          "value": "PGDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayCursorShowHandler/title",
          "value": "PGDisplayCursorShowHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayCursorShowHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayCursorShowHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayCursorShowHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayCursorShowHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1newFrameEventHandler/title",
          "value": "newFrameEventHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1newFrameEventHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "newFrameEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayCoord_t/title",
          "value": "PGDisplayCoord_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayCoord_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayCoord_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayCoord_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayCoord_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayModeChangeHandler/title",
          "value": "PGDisplayModeChangeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayModeChangeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayModeChangeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayModeChangeHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplayModeChangeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1cursorMoveHandler/title",
          "value": "cursorMoveHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1cursorMoveHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cursorMoveHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay/title",
          "value": "PGDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PGDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1cursorShowHandler/title",
          "value": "cursorShowHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1cursorShowHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cursorShowHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1sizeInMillimeters/title",
          "value": "sizeInMillimeters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.paravirtualizedgraphics~1documentation~1ParavirtualizedGraphics~1PGDisplayDescriptor~1sizeInMillimeters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sizeInMillimeters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgdisplaydescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/paravirtualizedgraphics/pgdisplaydescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
