{
  "abstract": [
    {
      "text": "Describes a screen’s reference display mode status.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIScreenReferenceDisplayModeStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ReferenceDisplayModeStatus"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ReferenceDisplayModeStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIScreen.ReferenceDisplayModeStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ReferenceDisplayModeStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen": {
      "abstract": [
        {
          "text": "An object that defines the properties associated with a hardware-based display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScreen"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreen"
        }
      ],
      "role": "symbol",
      "title": "UIScreen",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum": {
      "abstract": [
        {
          "text": "Describes a screen’s reference display mode status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReferenceDisplayModeStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReferenceDisplayModeStatus"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/enabled": {
      "abstract": [
        {
          "text": "A status that indicates the screen’s in an accurate reference display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/enabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenReferenceDisplayModeStatusEnabled"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus.enabled",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/enabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/limited": {
      "abstract": [
        {
          "text": "A status that indicates the screen’s in a limited reference display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limited"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/limited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenReferenceDisplayModeStatusLimited"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus.limited",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/limited"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notEnabled": {
      "abstract": [
        {
          "text": "A status that indicates the screen provides a reference display mode but it’s in a disabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEnabled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenReferenceDisplayModeStatusNotEnabled"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus.notEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/notenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notSupported": {
      "abstract": [
        {
          "text": "A status that indicates the screen doesn’t provide a reference display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenReferenceDisplayModeStatusNotSupported"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus.notSupported",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum/notsupported"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentEDRHeadroom": {
      "abstract": [
        {
          "text": "The screen’s current headroom when displaying extended dynamic range content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentEDRHeadroom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentEDRHeadroom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentEDRHeadroom"
        }
      ],
      "role": "symbol",
      "title": "currentEDRHeadroom",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/currentedrheadroom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/potentialEDRHeadroom": {
      "abstract": [
        {
          "text": "The screen’s maximum headroom when displaying extended dynamic range content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "potentialEDRHeadroom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/potentialEDRHeadroom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "potentialEDRHeadroom"
        }
      ],
      "role": "symbol",
      "title": "potentialEDRHeadroom",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/potentialedrheadroom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatus-swift.property": {
      "abstract": [
        {
          "text": "The status of the screen’s reference display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "referenceDisplayModeStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScreen",
          "text": "UIScreen"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIScreenReferenceDisplayModeStatus",
          "text": "ReferenceDisplayModeStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatus-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "referenceDisplayModeStatus"
        }
      ],
      "role": "symbol",
      "title": "referenceDisplayModeStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.property"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-reference-display-mode-status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatus-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentEDRHeadroom",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/potentialEDRHeadroom"
      ],
      "title": "Getting the reference display mode status"
    }
  ],
  "topicSections": [
    {
      "anchor": "Statuses",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notSupported",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/limited",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/enabled"
      ],
      "title": "Statuses"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIScreenReferenceDisplayModeStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Statuses",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notSupported",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/notEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/limited",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum/enabled"
              ],
              "title": "Statuses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-reference-display-mode-status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatus-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentEDRHeadroom",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/potentialEDRHeadroom"
              ],
              "title": "Getting the reference display mode status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIScreenReferenceDisplayModeStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1notSupported/title",
          "value": "UIScreenReferenceDisplayModeStatusNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatusNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum/title",
          "value": "UIScreenReferenceDisplayModeStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1potentialEDRHeadroom/title",
          "value": "potentialEDRHeadroom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1potentialEDRHeadroom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "potentialEDRHeadroom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1currentEDRHeadroom/title",
          "value": "currentEDRHeadroom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1currentEDRHeadroom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentEDRHeadroom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1referenceDisplayModeStatus-swift.property/title",
          "value": "referenceDisplayModeStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1referenceDisplayModeStatus-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "referenceDisplayModeStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/title",
          "value": "UIScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1enabled/title",
          "value": "UIScreenReferenceDisplayModeStatusEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1enabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatusEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1limited/title",
          "value": "UIScreenReferenceDisplayModeStatusLimited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1limited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatusLimited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1notEnabled/title",
          "value": "UIScreenReferenceDisplayModeStatusNotEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum~1notEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatusNotEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
