{
  "abstract": [
    {
      "text": "The visibility of the assistant cell in the list template.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/visibility"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPAssistantCellConfiguration(py)visibility",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "visibility"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPListItem",
        "text": "CPListItem"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CPAssistantCellVisibility",
        "text": "AssistantCellVisibility"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "visibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "visibility"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "visibility"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPListItem",
              "text": "CPListItem"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellVisibility",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CPAssistantCellVisibility",
              "text": "AssistantCellVisibility"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellActionType": {
      "abstract": [
        {
          "text": "The supported Siri actions of the assistant cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPAssistantCellActionType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellActionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPAssistantCellActionType"
        }
      ],
      "role": "symbol",
      "title": "CPAssistantCellActionType",
      "type": "topic",
      "url": "/documentation/carplay/cpassistantcellactiontype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration": {
      "abstract": [
        {
          "text": "An object that provides the configuration attributes for the assistant cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPAssistantCellConfiguration"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPAssistantCellConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CPAssistantCellConfiguration",
      "type": "topic",
      "url": "/documentation/carplay/cpassistantcellconfiguration"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/assistantAction": {
      "abstract": [
        {
          "text": "The action that Siri performs when the user selects the assistant cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assistantAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPAssistantCellActionType",
          "text": "CPAssistantCellActionType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/assistantAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assistantAction"
        }
      ],
      "role": "symbol",
      "title": "assistantAction",
      "type": "topic",
      "url": "/documentation/carplay/cpassistantcellconfiguration/assistantaction"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/position": {
      "abstract": [
        {
          "text": "The position of the assistant cell in the list template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "position"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPListItem",
          "text": "CPListItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPAssistantCellPosition",
          "text": "AssistantCellPosition"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/position",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "position"
        }
      ],
      "role": "symbol",
      "title": "position",
      "type": "topic",
      "url": "/documentation/carplay/cpassistantcellconfiguration/position"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/visibility": {
      "abstract": [
        {
          "text": "The visibility of the assistant cell in the list template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPListItem",
          "text": "CPListItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPAssistantCellVisibility",
          "text": "AssistantCellVisibility"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/visibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visibility"
        }
      ],
      "role": "symbol",
      "title": "visibility",
      "type": "topic",
      "url": "/documentation/carplay/cpassistantcellconfiguration/visibility"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem": {
      "abstract": [
        {
          "text": "A selectable row in a list template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListItem"
        }
      ],
      "role": "symbol",
      "title": "CPListItem",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellVisibility": {
      "abstract": [
        {
          "text": "Constants to specify the visibility of the assistant cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AssistantCellVisibility"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellVisibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AssistantCellVisibility"
        }
      ],
      "role": "symbol",
      "title": "CPListItem.AssistantCellVisibility",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem/assistantcellvisibility"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Configuration-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/position",
        "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/assistantAction",
        "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellActionType"
      ],
      "title": "Getting the Configuration Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "visibility"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Configuration-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/position",
                "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellConfiguration/assistantAction",
                "doc://com.apple.carplay/documentation/CarPlay/CPAssistantCellActionType"
              ],
              "title": "Getting the Configuration Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/AssistantCellVisibility",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CPAssistantCellVisibility",
                    "text": "CPAssistantCellVisibility"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "visibility"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellActionType/title",
          "value": "CPAssistantCellActionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellActionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellActionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellActionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellActionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellConfiguration~1assistantAction/title",
          "value": "assistantAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellConfiguration~1assistantAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "assistantAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellConfiguration~1position/title",
          "value": "position"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellConfiguration~1position/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellConfiguration/title",
          "value": "CPAssistantCellConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/title",
          "value": "CPListItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1AssistantCellVisibility/title",
          "value": "CPAssistantCellVisibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1AssistantCellVisibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1AssistantCellVisibility/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAssistantCellVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellConfiguration~1visibility/title",
          "value": "visibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAssistantCellConfiguration~1visibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visibility"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpassistantcellconfiguration/visibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpassistantcellconfiguration/visibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
