{
  "abstract": [
    {
      "text": "A fractional even partitioning mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/fractionalEven"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLTessellationPartitionMode@MTLTessellationPartitionModeFractionalEven",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fractionalEven"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLTessellationPartitionModeFractionalEven"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLTessellationPartitionMode.fractionalEven"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fractionalEven"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode": {
      "abstract": [
        {
          "text": "Options for choosing the partition mode that the tessellator applies when deriving",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the number and spacing of segments for subdividing a corresponding edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTessellationPartitionMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationPartitionMode"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationPartitionMode",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationpartitionmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/fractionalEven": {
      "abstract": [
        {
          "text": "A fractional even partitioning mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fractionalEven"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/fractionalEven",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationPartitionModeFractionalEven"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationPartitionMode.fractionalEven",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationpartitionmode/fractionaleven"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/fractionalOdd": {
      "abstract": [
        {
          "text": "A fractional odd partitioning mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fractionalOdd"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/fractionalOdd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationPartitionModeFractionalOdd"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationPartitionMode.fractionalOdd",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationpartitionmode/fractionalodd"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/integer": {
      "abstract": [
        {
          "text": "An integer partitioning mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/integer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationPartitionModeInteger"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationPartitionMode.integer",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationpartitionmode/integer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/pow2": {
      "abstract": [
        {
          "text": "A power of two partitioning mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pow2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/pow2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationPartitionModePow2"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationPartitionMode.pow2",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationpartitionmode/pow2"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/pow2",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/integer",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/fractionalOdd"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLTessellationPartitionModeFractionalEven"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionModeFractionalEven"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/pow2",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/integer",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode/fractionalOdd"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLTessellationPartitionModeFractionalEven"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode~1pow2/title",
          "value": "MTLTessellationPartitionModePow2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode~1pow2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionModePow2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode~1integer/title",
          "value": "MTLTessellationPartitionModeInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode~1integer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionModeInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode/title",
          "value": "MTLTessellationPartitionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode~1fractionalOdd/title",
          "value": "MTLTessellationPartitionModeFractionalOdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode~1fractionalOdd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionModeFractionalOdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode~1fractionalEven/title",
          "value": "MTLTessellationPartitionModeFractionalEven"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode~1fractionalEven/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionModeFractionalEven"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtltessellationpartitionmode/fractionaleven"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtltessellationpartitionmode/fractionaleven"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
