{
  "abstract": [
    {
      "text": "Lens stabilization was active for the full duration of the photo capture.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/active"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVCaptureLensStabilizationStatus@AVCaptureLensStabilizationStatusActive",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "active"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCaptureLensStabilizationStatusActive"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVCaptureDevice.LensStabilizationStatus.active"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "active"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus": {
      "abstract": [
        {
          "text": "Constants that indicate the status of optical image stabilization hardware during a bracketed photo capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LensStabilizationStatus"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LensStabilizationStatus"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.LensStabilizationStatus",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/lensstabilizationstatus"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/active": {
      "abstract": [
        {
          "text": "Lens stabilization was active for the full duration of the photo capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "active"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/active",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureLensStabilizationStatusActive"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.LensStabilizationStatus.active",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/lensstabilizationstatus/active"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/off": {
      "abstract": [
        {
          "text": "Lens stabilization isn’t specified for this photo capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "off"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/off",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureLensStabilizationStatusOff"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.LensStabilizationStatus.off",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/lensstabilizationstatus/off"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/outOfRange": {
      "abstract": [
        {
          "text": "Lens stabilization was enabled for the photo capture, but device motion or capture duration exceeded the stabilization module’s correction limits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/outOfRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureLensStabilizationStatusOutOfRange"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.LensStabilizationStatus.outOfRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/lensstabilizationstatus/outofrange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/unavailable": {
      "abstract": [
        {
          "text": "Lens stabilization was temporarily unavailable during the photo capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unavailable"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/unavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureLensStabilizationStatusUnavailable"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.LensStabilizationStatus.unavailable",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/lensstabilizationstatus/unavailable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/unsupported": {
      "abstract": [
        {
          "text": "Lens stabilization isn’t available on the device or device configuration that captured this photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/unsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureLensStabilizationStatusUnsupported"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.LensStabilizationStatus.unsupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/lensstabilizationstatus/unsupported"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Lens-Stabilization-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/unsupported",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/off",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/outOfRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/unavailable"
      ],
      "title": "Lens Stabilization Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCaptureLensStabilizationStatusActive"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureLensStabilizationStatusActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Lens-Stabilization-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/unsupported",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/off",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/outOfRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/LensStabilizationStatus/unavailable"
              ],
              "title": "Lens Stabilization Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVCaptureLensStabilizationStatusActive"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus~1unavailable/title",
          "value": "AVCaptureLensStabilizationStatusUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus~1unavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureLensStabilizationStatusUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus~1outOfRange/title",
          "value": "AVCaptureLensStabilizationStatusOutOfRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus~1outOfRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureLensStabilizationStatusOutOfRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus~1active/title",
          "value": "AVCaptureLensStabilizationStatusActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus~1active/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureLensStabilizationStatusActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus~1unsupported/title",
          "value": "AVCaptureLensStabilizationStatusUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureLensStabilizationStatusUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus/title",
          "value": "AVCaptureLensStabilizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureLensStabilizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureLensStabilizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title",
          "value": "AVCaptureDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus~1off/title",
          "value": "AVCaptureLensStabilizationStatusOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1LensStabilizationStatus~1off/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureLensStabilizationStatusOff"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/lensstabilizationstatus/active"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturedevice/lensstabilizationstatus/active"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
