{"metadata":{"title":"tableView(_:updateDraggingItemsForDrag:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"updateDraggingItemsForDrag","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"NSDraggingInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":")","kind":"text"}],"modules":[{"name":"AppKit"}],"externalID":"c:objc(pl)NSTableViewDataSource(im)tableView:updateDraggingItemsForDrag:","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"tableView:updateDraggingItemsForDrag:","kind":"identifier"}],"roleHeading":"Instance Method","platforms":[{"introducedAt":"10.7","unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableView"},{"text":", ","kind":"text"},{"text":"updateDraggingItemsForDrag","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"draggingInfo","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"tableView","content":[{"inlineContent":[{"type":"text","text":"The table view."}],"type":"paragraph"}]},{"name":"draggingInfo","content":[{"type":"paragraph","inlineContent":[{"text":"The dragging information.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Required for multi-image dragging. Typically this will involve invoking "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/enumerateDraggingItems(options:for:classes:searchOptions:using:)","type":"reference"},{"type":"text","text":" on the "},{"type":"codeVoice","code":"draggingInfo"},{"type":"text","text":" parameter value and setting the "},{"type":"codeVoice","code":"draggingItem"},{"type":"text","text":" object’s "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/imageComponentsProvider","type":"reference"},{"type":"text","text":" to a proper image based on the content."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For view-based table views, you can use the "},{"code":"NSTableCellView","type":"codeVoice"},{"type":"text","text":" method "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableCellView/draggingImageComponents","isActive":true},{"type":"text","text":". For cell-based tables, use the "},{"code":"NSCell","type":"codeVoice"},{"type":"text","text":" method "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/draggingImageComponents(withFrame:in:)","isActive":true},{"type":"text","text":"."}]}],"kind":"content"}],"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:validateDrop:proposedRow:proposedDropOperation:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:writeRowsWith:to:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:willBeginAt:forRowIndexes:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:endedAt:operation:)"],"title":"Drag and Drop","anchor":"Drag-and-Drop","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:updateDraggingItemsForDrag:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Implement this method to allow the table to update dragging items as they are dragged over a view."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nstableviewdatasource/tableview(_:updatedraggingitemsfordrag:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nstableviewdatasource/tableview(_:updatedraggingitemsfordrag:)"]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSTableCellView/draggingImageComponents":{"url":"/documentation/appkit/nstablecellview/draggingimagecomponents","navigatorTitle":[{"kind":"identifier","text":"draggingImageComponents"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableCellView/draggingImageComponents","type":"topic","abstract":[{"type":"text","text":"Returns dragging images for the cell."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"draggingImageComponents","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSDraggingImageComponent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDraggingImageComponent"},{"kind":"text","text":"]"}],"title":"draggingImageComponents","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCell/draggingImageComponents(withFrame:in:)":{"navigatorTitle":[{"kind":"identifier","text":"draggingImageComponentsWithFrame:inView:"}],"title":"draggingImageComponents(withFrame:in:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/draggingImageComponents(withFrame:in:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draggingImageComponents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSView","preciseIdentifier":"c:objc(cs)NSView"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSDraggingImageComponent","preciseIdentifier":"c:objc(cs)NSDraggingImageComponent"},{"kind":"text","text":"]"}],"url":"/documentation/appkit/nscell/draggingimagecomponents(withframe:in:)","role":"symbol","abstract":[{"text":"Generates dragging image components with the specified frame in the view.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSDraggingInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of methods that supply information about a dragging session."}],"url":"/documentation/appkit/nsdragginginfo","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDraggingInfo","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo","title":"NSDraggingInfo"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:willBeginAt:forRowIndexes:)":{"role":"symbol","title":"tableView(_:draggingSession:willBeginAt:forRowIndexes:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"draggingSession","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSDraggingSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDraggingSession"},{"text":", ","kind":"text"},{"text":"willBeginAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"forRowIndexes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:willBeginAt:forRowIndexes:)","url":"/documentation/appkit/nstableviewdatasource/tableview(_:draggingsession:willbeginat:forrowindexes:)","abstract":[{"text":"Implement this method to determine when a dragging session will begin.","type":"text"}],"navigatorTitle":[{"text":"tableView:draggingSession:willBeginAtPoint:forRowIndexes:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:endedAt:operation:)":{"url":"/documentation/appkit/nstableviewdatasource/tableview(_:draggingsession:endedat:operation:)","type":"topic","abstract":[{"type":"text","text":"Implement this method to determine when a dragging session has ended."}],"kind":"symbol","title":"tableView(_:draggingSession:endedAt:operation:)","navigatorTitle":[{"text":"tableView:draggingSession:endedAtPoint:operation:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:endedAt:operation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","text":"NSTableView"},{"text":", ","kind":"text"},{"text":"draggingSession","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSDraggingSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDraggingSession"},{"text":", ","kind":"text"},{"text":"endedAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSDragOperation","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDragOperation"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/enumerateDraggingItems(options:for:classes:searchOptions:using:)":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Enumerates through each dragging item."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/enumerateDraggingItems(options:for:classes:searchOptions:using:)","title":"enumerateDraggingItems(options:for:classes:searchOptions:using:)","url":"/documentation/appkit/nsdragginginfo/enumeratedraggingitems(options:for:classes:searchoptions:using:)","navigatorTitle":[{"text":"enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"enumerateDraggingItems","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSDraggingItemEnumerationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDraggingItemEnumerationOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSView","preciseIdentifier":"c:objc(cs)NSView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"classes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa","text":"AnyClass"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"searchOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardReadingOptionKey","text":"ReadingOptionKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"using","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"NSDraggingItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDraggingItem"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"ObjCBool","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8ObjCBoolV"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)":{"deprecated":true,"role":"symbol","title":"tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"namesOfPromisedFilesDroppedAtDestination","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"forDraggedRowsWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":") -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)","url":"/documentation/appkit/nstableviewdatasource/tableview(_:namesofpromisedfilesdroppedatdestination:fordraggedrowswith:)","abstract":[{"type":"text","text":"Returns an array of filenames that represent the "},{"type":"codeVoice","code":"indexSet"},{"type":"text","text":" rows for a drag to "},{"code":"dropDestination","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"tableView:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWithIndexes:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:updateDraggingItemsForDrag:)":{"url":"/documentation/appkit/nstableviewdatasource/tableview(_:updatedraggingitemsfordrag:)","type":"topic","abstract":[{"type":"text","text":"Implement this method to allow the table to update dragging items as they are dragged over a view."}],"kind":"symbol","title":"tableView(_:updateDraggingItemsForDrag:)","navigatorTitle":[{"text":"tableView:updateDraggingItemsForDrag:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:updateDraggingItemsForDrag:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"text":", ","kind":"text"},{"text":"updateDraggingItemsForDrag","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"NSDraggingInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:writeRowsWith:to:)":{"url":"/documentation/appkit/nstableviewdatasource/tableview(_:writerowswith:to:)","type":"topic","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether a drag operation is allowed."}],"kind":"symbol","title":"tableView(_:writeRowsWith:to:)","deprecated":true,"navigatorTitle":[{"text":"tableView:writeRowsWithIndexes:toPasteboard:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:writeRowsWith:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","text":"NSTableView"},{"text":", ","kind":"text"},{"text":"writeRowsWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:acceptDrop:row:dropOperation:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"acceptDrop"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"NSDraggingInfo","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dropOperation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"DropOperation","preciseIdentifier":"c:@E@NSTableViewDropOperation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"/documentation/appkit/nstableviewdatasource/tableview(_:acceptdrop:row:dropoperation:)","abstract":[{"text":"Called by ","type":"text"},{"code":"aTableView","type":"codeVoice"},{"text":" when the mouse button is released over a table view that previously decided to allow a drop.","type":"text"}],"title":"tableView(_:acceptDrop:row:dropOperation:)"},"doc://com.apple.appkit/documentation/AppKit/NSTableView":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSTableView","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records."}],"url":"/documentation/appkit/nstableview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTableView","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableView","title":"NSTableView"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource":{"abstract":[{"type":"text","text":"A set of methods that a table view uses to provide data to a table view and to allow the editing of the table view’s data source object."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTableViewDataSource","kind":"identifier"}],"url":"/documentation/appkit/nstableviewdatasource","navigatorTitle":[{"kind":"identifier","text":"NSTableViewDataSource"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource","kind":"symbol","role":"symbol","type":"topic","title":"NSTableViewDataSource"},"doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises":{"type":"topic","title":"Supporting Table View Drag and Drop Through File Promises","abstract":[{"type":"text","text":"Share data between macOS apps during drag and drop by using an item provider."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises","url":"/documentation/appkit/supporting-table-view-drag-and-drop-through-file-promises","kind":"article","role":"sampleCode"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:validateDrop:proposedRow:proposedDropOperation:)":{"url":"/documentation/appkit/nstableviewdatasource/tableview(_:validatedrop:proposedrow:proposeddropoperation:)","type":"topic","abstract":[{"type":"text","text":"Used by "},{"code":"aTableView","type":"codeVoice"},{"type":"text","text":" to determine a valid drop target."}],"kind":"symbol","title":"tableView(_:validateDrop:proposedRow:proposedDropOperation:)","navigatorTitle":[{"text":"tableView:validateDrop:proposedRow:proposedDropOperation:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:validateDrop:proposedRow:proposedDropOperation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"validateDrop","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"NSDraggingInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":", ","kind":"text"},{"text":"proposedRow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"proposedDropOperation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":".","kind":"text"},{"text":"DropOperation","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTableViewDropOperation"},{"text":") -> ","kind":"text"},{"text":"NSDragOperation","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDragOperation"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/imageComponentsProvider":{"url":"/documentation/appkit/nsdraggingitem/imagecomponentsprovider","navigatorTitle":[{"kind":"identifier","text":"imageComponentsProvider"}],"abstract":[{"type":"text","text":"An array of blocks that provide the dragging image components."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageComponentsProvider"},{"kind":"text","text":": (() -> ["},{"preciseIdentifier":"c:objc(cs)NSDraggingImageComponent","kind":"typeIdentifier","text":"NSDraggingImageComponent"},{"kind":"text","text":"])?"}],"title":"imageComponentsProvider","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/imageComponentsProvider","type":"topic","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"name":"macOS","introducedAt":"10.7","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"tableView:updateDraggingItemsForDrag:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:updateDraggingItemsForDrag:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:validateDrop:proposedRow:proposedDropOperation:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:writeRowsWith:to:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:willBeginAt:forRowIndexes:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:endedAt:operation:)"],"title":"Drag and Drop","anchor":"Drag-and-Drop"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"tableView:"},{"text":"(","kind":"text"},{"text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"updateDraggingItemsForDrag:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<NSDraggingInfo>","preciseIdentifier":"c:Qoobjc(pl)NSDraggingInfo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"draggingInfo","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The table view."}]}],"name":"tableView"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The dragging information."}]}],"name":"draggingInfo"}]},"path":"/primaryContentSections/1","op":"replace"},{"op":"replace","value":"draggingImageComponents","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableCellView~1draggingImageComponents/title"},{"op":"replace","value":[{"text":"draggingImageComponents","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableCellView~1draggingImageComponents/fragments"},{"op":"replace","value":"draggingImageComponentsWithFrame:inView:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1draggingImageComponents(withFrame:in:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"draggingImageComponentsWithFrame:inView:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1draggingImageComponents(withFrame:in:)/fragments"},{"op":"replace","value":"NSDraggingInfo","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/title"},{"op":"replace","value":[{"text":"NSDraggingInfo","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSDraggingInfo"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/navigatorTitle"},{"op":"replace","value":"tableView:draggingSession:willBeginAtPoint:forRowIndexes:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:draggingSession:willBeginAt:forRowIndexes:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:draggingSession:willBeginAtPoint:forRowIndexes:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:draggingSession:willBeginAt:forRowIndexes:)/fragments"},{"op":"replace","value":"tableView:draggingSession:endedAtPoint:operation:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:draggingSession:endedAt:operation:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:draggingSession:endedAtPoint:operation:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:draggingSession:endedAt:operation:)/fragments"},{"op":"replace","value":"enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1enumerateDraggingItems(options:for:classes:searchOptions:using:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1enumerateDraggingItems(options:for:classes:searchOptions:using:)/fragments"},{"op":"replace","value":"tableView:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWithIndexes:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWithIndexes:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)/fragments"},{"op":"replace","value":"tableView:updateDraggingItemsForDrag:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:updateDraggingItemsForDrag:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:updateDraggingItemsForDrag:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:updateDraggingItemsForDrag:)/fragments"},{"op":"replace","value":"tableView:writeRowsWithIndexes:toPasteboard:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:writeRowsWith:to:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:writeRowsWithIndexes:toPasteboard:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:writeRowsWith:to:)/fragments"},{"op":"replace","value":"tableView:acceptDrop:row:dropOperation:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:acceptDrop:row:dropOperation:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:acceptDrop:row:dropOperation:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:acceptDrop:row:dropOperation:)/fragments"},{"op":"replace","value":"NSTableView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSTableView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments"},{"op":"replace","value":[{"text":"NSTableView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle"},{"op":"replace","value":"NSTableViewDataSource","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/title"},{"op":"replace","value":[{"text":"NSTableViewDataSource","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/fragments"},{"op":"replace","value":[{"text":"NSTableViewDataSource","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/navigatorTitle"},{"op":"replace","value":"tableView:validateDrop:proposedRow:proposedDropOperation:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:validateDrop:proposedRow:proposedDropOperation:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:validateDrop:proposedRow:proposedDropOperation:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:validateDrop:proposedRow:proposedDropOperation:)/fragments"},{"op":"replace","value":"imageComponentsProvider","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1imageComponentsProvider/title"},{"op":"replace","value":[{"text":"imageComponentsProvider","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1imageComponentsProvider/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}