{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nstableviewdatasource/tableview(_:draggingsession:endedat:operation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nstableviewdatasource/tableview(_:draggingsession:endedat:operation:)"]}],"abstract":[{"type":"text","text":"Implement this method to determine when a dragging session has ended."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:validateDrop:proposedRow:proposedDropOperation:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:writeRowsWith:to:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:willBeginAt:forRowIndexes:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:updateDraggingItemsForDrag:)"],"anchor":"Drag-and-Drop","title":"Drag and Drop"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"tableView:draggingSession:endedAtPoint:operation:"}],"modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","platforms":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.7"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"draggingSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDraggingSession","text":"NSDraggingSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDragOperation","text":"NSDragOperation"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"method","title":"tableView(_:draggingSession:endedAt:operation:)","externalID":"c:objc(pl)NSTableViewDataSource(im)tableView:draggingSession:endedAtPoint:operation:"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableView","text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"draggingSession","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingSession","text":"NSDraggingSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDraggingSession"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"endedAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"screenPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDragOperation","text":"NSDragOperation","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDragOperation"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]},{"parameters":[{"name":"tableView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The table view."}]}]},{"name":"session","content":[{"inlineContent":[{"type":"text","text":"The dragging session."}],"type":"paragraph"}]},{"name":"screenPoint","content":[{"type":"paragraph","inlineContent":[{"text":"The ending drag location in screen coordinates.","type":"text"}]}]},{"name":"operation","content":[{"type":"paragraph","inlineContent":[{"text":"The drag operation. See ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDragOperation","isActive":true,"type":"reference"},{"text":" for supported values.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"This delegate method can be used to determine when the dragging source operation ended at a specific location, such as the trash, by checking for an operation of ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDragOperation/delete","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:endedAt:operation:)"},"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:updateDraggingItemsForDrag:)":{"url":"/documentation/appkit/nstableviewdatasource/tableview(_:updatedraggingitemsfordrag:)","type":"topic","abstract":[{"type":"text","text":"Implement this method to allow the table to update dragging items as they are dragged over a view."}],"kind":"symbol","title":"tableView(_:updateDraggingItemsForDrag:)","navigatorTitle":[{"text":"tableView:updateDraggingItemsForDrag:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:updateDraggingItemsForDrag:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"text":", ","kind":"text"},{"text":"updateDraggingItemsForDrag","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"NSDraggingInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises":{"type":"topic","title":"Supporting Table View Drag and Drop Through File Promises","abstract":[{"type":"text","text":"Share data between macOS apps during drag and drop by using an item provider."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises","url":"/documentation/appkit/supporting-table-view-drag-and-drop-through-file-promises","kind":"article","role":"sampleCode"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:acceptDrop:row:dropOperation:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"acceptDrop"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"NSDraggingInfo","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dropOperation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"DropOperation","preciseIdentifier":"c:@E@NSTableViewDropOperation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"/documentation/appkit/nstableviewdatasource/tableview(_:acceptdrop:row:dropoperation:)","abstract":[{"text":"Called by ","type":"text"},{"code":"aTableView","type":"codeVoice"},{"text":" when the mouse button is released over a table view that previously decided to allow a drop.","type":"text"}],"title":"tableView(_:acceptDrop:row:dropOperation:)"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:validateDrop:proposedRow:proposedDropOperation:)":{"url":"/documentation/appkit/nstableviewdatasource/tableview(_:validatedrop:proposedrow:proposeddropoperation:)","type":"topic","abstract":[{"type":"text","text":"Used by "},{"code":"aTableView","type":"codeVoice"},{"type":"text","text":" to determine a valid drop target."}],"kind":"symbol","title":"tableView(_:validateDrop:proposedRow:proposedDropOperation:)","navigatorTitle":[{"text":"tableView:validateDrop:proposedRow:proposedDropOperation:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:validateDrop:proposedRow:proposedDropOperation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"validateDrop","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"NSDraggingInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":", ","kind":"text"},{"text":"proposedRow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"proposedDropOperation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":".","kind":"text"},{"text":"DropOperation","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTableViewDropOperation"},{"text":") -> ","kind":"text"},{"text":"NSDragOperation","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDragOperation"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)":{"deprecated":true,"role":"symbol","title":"tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"namesOfPromisedFilesDroppedAtDestination","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"forDraggedRowsWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":") -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)","url":"/documentation/appkit/nstableviewdatasource/tableview(_:namesofpromisedfilesdroppedatdestination:fordraggedrowswith:)","abstract":[{"type":"text","text":"Returns an array of filenames that represent the "},{"type":"codeVoice","code":"indexSet"},{"type":"text","text":" rows for a drag to "},{"code":"dropDestination","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"tableView:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWithIndexes:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:endedAt:operation:)":{"url":"/documentation/appkit/nstableviewdatasource/tableview(_:draggingsession:endedat:operation:)","type":"topic","abstract":[{"type":"text","text":"Implement this method to determine when a dragging session has ended."}],"kind":"symbol","title":"tableView(_:draggingSession:endedAt:operation:)","navigatorTitle":[{"text":"tableView:draggingSession:endedAtPoint:operation:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:endedAt:operation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","text":"NSTableView"},{"text":", ","kind":"text"},{"text":"draggingSession","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSDraggingSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDraggingSession"},{"text":", ","kind":"text"},{"text":"endedAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSDragOperation","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDragOperation"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableView":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSTableView","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records."}],"url":"/documentation/appkit/nstableview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTableView","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableView","title":"NSTableView"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingSession":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDraggingSession"}],"type":"topic","abstract":[{"text":"The encapsulation of a drag-and-drop action that supports modification of the drag while in progress.","type":"text"}],"url":"/documentation/appkit/nsdraggingsession","title":"NSDraggingSession","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSDraggingSession"}]},"doc://com.apple.appkit/documentation/AppKit/NSDragOperation/delete":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delete"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSDragOperation","preciseIdentifier":"c:@E@NSDragOperation"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDragOperation/delete","abstract":[{"type":"text","text":"A constant that indicates the drag can delete the data."}],"type":"topic","title":"delete","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSDragOperationDelete"}],"url":"/documentation/appkit/nsdragoperation/delete","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:writeRowsWith:to:)":{"url":"/documentation/appkit/nstableviewdatasource/tableview(_:writerowswith:to:)","type":"topic","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether a drag operation is allowed."}],"kind":"symbol","title":"tableView(_:writeRowsWith:to:)","deprecated":true,"navigatorTitle":[{"text":"tableView:writeRowsWithIndexes:toPasteboard:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:writeRowsWith:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","text":"NSTableView"},{"text":", ","kind":"text"},{"text":"writeRowsWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:willBeginAt:forRowIndexes:)":{"role":"symbol","title":"tableView(_:draggingSession:willBeginAt:forRowIndexes:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"draggingSession","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSDraggingSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDraggingSession"},{"text":", ","kind":"text"},{"text":"willBeginAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"forRowIndexes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:willBeginAt:forRowIndexes:)","url":"/documentation/appkit/nstableviewdatasource/tableview(_:draggingsession:willbeginat:forrowindexes:)","abstract":[{"text":"Implement this method to determine when a dragging session will begin.","type":"text"}],"navigatorTitle":[{"text":"tableView:draggingSession:willBeginAtPoint:forRowIndexes:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@NSPoint":{"abstract":[{"text":"A point in a Cartesian coordinate system.","type":"text"}],"url":"/documentation/foundation/nspoint","kind":"symbol","role":"symbol","title":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","type":"topic","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSPoint","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource":{"abstract":[{"type":"text","text":"A set of methods that a table view uses to provide data to a table view and to allow the editing of the table view’s data source object."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTableViewDataSource","kind":"identifier"}],"url":"/documentation/appkit/nstableviewdatasource","navigatorTitle":[{"kind":"identifier","text":"NSTableViewDataSource"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource","kind":"symbol","role":"symbol","type":"topic","title":"NSTableViewDataSource"},"doc://com.apple.appkit/documentation/AppKit/NSDragOperation":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSDragOperation","kind":"identifier"}],"url":"/documentation/appkit/nsdragoperation","title":"NSDragOperation","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDragOperation","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDragOperation","kind":"identifier"}],"abstract":[{"text":"A group of constants that represent which operations the dragging source can perform on dragging items.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"10.7","name":"macOS","beta":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"tableView:draggingSession:endedAtPoint:operation:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:draggingSession:endedAtPoint:operation:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"title":"Drag and Drop","anchor":"Drag-and-Drop","identifiers":["doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:validateDrop:proposedRow:proposedDropOperation:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:writeRowsWith:to:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:draggingSession:willBeginAt:forRowIndexes:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:updateDraggingItemsForDrag:)"]}],"op":"replace","path":"/seeAlsoSections"},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"tableView:"},{"text":"(","kind":"text"},{"text":"NSTableView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableView","preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"draggingSession:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDraggingSession","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingSession","text":"NSDraggingSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"endedAtPoint:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"screenPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"operation:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@NSDragOperation","text":"NSDragOperation","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDragOperation"},{"text":") ","kind":"text"},{"text":"operation","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The table view."}]}],"name":"tableView"},{"content":[{"inlineContent":[{"type":"text","text":"The dragging session."}],"type":"paragraph"}],"name":"session"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ending drag location in screen coordinates.","type":"text"}]}],"name":"screenPoint"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The drag operation. See "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDragOperation","type":"reference","isActive":true},{"type":"text","text":" for supported values."}]}],"name":"operation"}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:updateDraggingItemsForDrag:)/title","op":"replace","value":"tableView:updateDraggingItemsForDrag:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:updateDraggingItemsForDrag:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:updateDraggingItemsForDrag:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:acceptDrop:row:dropOperation:)/title","op":"replace","value":"tableView:acceptDrop:row:dropOperation:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:acceptDrop:row:dropOperation:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:acceptDrop:row:dropOperation:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:validateDrop:proposedRow:proposedDropOperation:)/title","op":"replace","value":"tableView:validateDrop:proposedRow:proposedDropOperation:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:validateDrop:proposedRow:proposedDropOperation:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:validateDrop:proposedRow:proposedDropOperation:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)/title","op":"replace","value":"tableView:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWithIndexes:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWith:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:namesOfPromisedFilesDroppedAtDestination:forDraggedRowsWithIndexes:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:draggingSession:endedAt:operation:)/title","op":"replace","value":"tableView:draggingSession:endedAtPoint:operation:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:draggingSession:endedAt:operation:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:draggingSession:endedAtPoint:operation:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title","op":"replace","value":"NSTableView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments","op":"replace","value":[{"kind":"identifier","text":"NSTableView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSTableView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession/title","op":"replace","value":"NSDraggingSession"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession/fragments","op":"replace","value":[{"text":"NSDraggingSession","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession/navigatorTitle","op":"replace","value":[{"text":"NSDraggingSession","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDragOperation~1delete/title","op":"replace","value":"NSDragOperationDelete"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDragOperation~1delete/fragments","op":"replace","value":[{"text":"NSDragOperationDelete","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:writeRowsWith:to:)/title","op":"replace","value":"tableView:writeRowsWithIndexes:toPasteboard:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:writeRowsWith:to:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:writeRowsWithIndexes:toPasteboard:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:draggingSession:willBeginAt:forRowIndexes:)/title","op":"replace","value":"tableView:draggingSession:willBeginAtPoint:forRowIndexes:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:draggingSession:willBeginAt:forRowIndexes:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:draggingSession:willBeginAtPoint:forRowIndexes:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/title","op":"replace","value":"NSTableViewDataSource"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/fragments","op":"replace","value":[{"text":"NSTableViewDataSource","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/navigatorTitle","op":"replace","value":[{"text":"NSTableViewDataSource","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDragOperation/title","op":"replace","value":"NSDragOperation"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDragOperation/fragments","op":"replace","value":[{"kind":"identifier","text":"NSDragOperation"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDragOperation/navigatorTitle","op":"replace","value":[{"text":"NSDragOperation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}