{
  "abstract": [
    {
      "text": "Make a request to modify and save a photo or video asset.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotoKit",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHAsset"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotoKit/editing-asset-content"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Editing Asset Content"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For each photo asset, Photos keeps a previous and a current version of its image data, as well as a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAdjustmentData",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that describes the last edit the user made to each asset’s content. Your app uses this information to support ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "resumable editing",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you begin editing an asset, Photos first asks whether your app can interpret the adjustment data from the most recent edit. If so, Photos provides the previous version of the asset as input for your editing session. After you read the adjustment data and reconstruct the edit it describes, your app might let the user alter or revert the last edit or make further changes. For example, adjustment data may describe filters applied to a photo. Your app reapplies those filters and allows the user to change filter parameters, add new filters, or remove filters.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app doesn’t support an asset’s adjustment data, Photos provides the current version of the asset as input to your editing session. The current version contains the rendered output of all past edits, so your app can further edit the asset but cannot alter or revert most recent edit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To support continuity of editing between different apps and extensions, Photos keeps the current and previous versions of each asset, along with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAdjustmentData",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that describes the last edit. If your app supports the adjustment data from a previous edit, you can allow the user to revert or alter the edit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For video assets, Photos doesn’t store a previous version. If your app cannot read a video asset’s adjustment data, you must work with the current version of the video. Future versions won’t be able to make use of your app’s adjustment data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Request-a-Content-Editing-Input",
          "level": 3,
          "text": "Request a Content Editing Input",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call the asset’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/requestContentEditingInput(with:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestOptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object you provide for the ",
              "type": "text"
            },
            {
              "code": "options",
              "type": "codeVoice"
            },
            {
              "text": " parameter controls whether your app can handle the asset’s adjustment data. Photos calls your ",
              "type": "text"
            },
            {
              "code": "completionHandler",
              "type": "codeVoice"
            },
            {
              "text": " block, providing a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object you can use for retrieving the image or video data to be edited.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Apply-Your-Edits-Through-a-Content-Editing-Output",
          "level": 3,
          "text": "Apply Your Edits Through a Content Editing Output",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apply your edits to the asset. To allow a user to continue working with your edits later, create a new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAdjustmentData",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object describing the changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-Content-Editing-Output",
          "level": 3,
          "text": "Create a Content Editing Output",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Initialize a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingOutput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. For photo- or video-only assets, use the editing output’s properties to provide edited asset data. For Live Photo assets, create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to edit the Live Photo content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Commit-Your-Completed-Edits",
          "level": 3,
          "text": "Commit Your Completed Edits",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Commit your edits to the photo library by posting a change block to the shared ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. In the block, create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and set its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/contentEditingOutput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to the editing output that you created.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "performChanges",
              "type": "codeVoice"
            },
            {
              "text": " call prompts the user for permission to edit the contents of the photo library. To edit multiple assets in one batch, create multiple ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects within the same change block, each with its own corresponding ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingOutput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit",
      "kind": "article",
      "role": "collection",
      "title": "PhotoKit",
      "type": "topic",
      "url": "/documentation/photokit"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/editing-request-info-keys": {
      "abstract": [
        {
          "text": "Keys indicating the status of an asset content editing request, used in the completion handler of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/requestContentEditingInput(with:completionHandler:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/editing-request-info-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Editing Request Info Keys",
      "type": "topic",
      "url": "/documentation/photokit/editing-request-info-keys"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAdjustmentData": {
      "abstract": [
        {
          "text": "A description of the edits made to an asset’s photo, video, or Live Photo content, which allows your app to reconstruct or revert the effects of prior editing sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAdjustmentData"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAdjustmentData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAdjustmentData"
        }
      ],
      "role": "symbol",
      "title": "PHAdjustmentData",
      "type": "topic",
      "url": "/documentation/photos/phadjustmentdata"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset": {
      "abstract": [
        {
          "text": "A representation of an image, video, or Live Photo in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "role": "symbol",
      "title": "PHAsset",
      "type": "topic",
      "url": "/documentation/photos/phasset"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/canPerform(_:)": {
      "abstract": [
        {
          "text": "Returns whether the asset supports the specified editing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetEditOperation",
          "text": "PHAssetEditOperation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/canPerform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformEditOperation:"
        }
      ],
      "role": "symbol",
      "title": "canPerform(_:)",
      "type": "topic",
      "url": "/documentation/photos/phasset/canperform(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/cancelContentEditingInputRequest(_:)": {
      "abstract": [
        {
          "text": "Cancels a request for editing the asset’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelContentEditingInputRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHContentEditingInputRequestID",
          "text": "PHContentEditingInputRequestID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/cancelContentEditingInputRequest(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelContentEditingInputRequest:"
        }
      ],
      "role": "symbol",
      "title": "cancelContentEditingInputRequest(_:)",
      "type": "topic",
      "url": "/documentation/photos/phasset/cancelcontenteditinginputrequest(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/requestContentEditingInput(with:completionHandler:)": {
      "abstract": [
        {
          "text": "Requests asset information for beginning a content editing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestContentEditingInput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHContentEditingInputRequestOptions",
          "text": "PHContentEditingInputRequestOptions"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHContentEditingInput",
          "text": "PHContentEditingInput"
        },
        {
          "kind": "text",
          "text": "?, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHContentEditingInputRequestID",
          "text": "PHContentEditingInputRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/requestContentEditingInput(with:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestContentEditingInputWithOptions:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestContentEditingInput(with:completionHandler:)",
      "type": "topic",
      "url": "/documentation/photos/phasset/requestcontenteditinginput(with:completionhandler:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest": {
      "abstract": [
        {
          "text": "A request to create, delete, change metadata for, or edit the content of a Photos asset, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHAssetChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/contentEditingOutput": {
      "abstract": [
        {
          "text": "The output of an asset content editing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentEditingOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHContentEditingOutput",
          "text": "PHContentEditingOutput"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/contentEditingOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentEditingOutput"
        }
      ],
      "role": "symbol",
      "title": "contentEditingOutput",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/contenteditingoutput"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetEditOperation": {
      "abstract": [
        {
          "text": "Values identifying possible actions an asset can support, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/canPerform(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetEditOperation"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetEditOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetEditOperation"
        }
      ],
      "role": "symbol",
      "title": "PHAssetEditOperation",
      "type": "topic",
      "url": "/documentation/photos/phasseteditoperation"
    },
    "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput": {
      "abstract": [
        {
          "text": "A container that provides information about and access to the image, video, or Live Photo content of an asset to be edited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHContentEditingInput"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHContentEditingInput"
        }
      ],
      "role": "symbol",
      "title": "PHContentEditingInput",
      "type": "topic",
      "url": "/documentation/photos/phcontenteditinginput"
    },
    "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestID": {
      "abstract": [
        {
          "text": "An identifier for an asset content editing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHContentEditingInputRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHContentEditingInputRequestID"
        }
      ],
      "role": "symbol",
      "title": "PHContentEditingInputRequestID",
      "type": "topic",
      "url": "/documentation/photos/phcontenteditinginputrequestid"
    },
    "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of image or video data when you request to edit the content of a Photos asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHContentEditingInputRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHContentEditingInputRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHContentEditingInputRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phcontenteditinginputrequestoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHContentEditingOutput": {
      "abstract": [
        {
          "text": "A container to which you provide the results of editing the photo, video, or Live Photo content of a Photos asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHContentEditingOutput"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHContentEditingOutput"
        }
      ],
      "role": "symbol",
      "title": "PHContentEditingOutput",
      "type": "topic",
      "url": "/documentation/photos/phcontenteditingoutput"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext": {
      "abstract": [
        {
          "text": "An editing session for modifying the photo, video, and audio content of a Live Photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoEditingContext"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoEditingContext"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoEditingContext",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoeditingcontext"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame": {
      "abstract": [
        {
          "text": "A container that provides image content for a single frame of a Live Photo in an editing context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoFrame"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoFrame"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoFrame",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoframe"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary": {
      "abstract": [
        {
          "text": "An object that manages access and changes to the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "role": "symbol",
      "title": "PHPhotoLibrary",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing-an-Asset",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput",
        "doc://com.apple.photokit/documentation/Photos/PHContentEditingOutput",
        "doc://com.apple.photokit/documentation/Photos/PHAdjustmentData",
        "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestOptions",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/canPerform(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetEditOperation",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/requestContentEditingInput(with:completionHandler:)",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/cancelContentEditingInputRequest(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestID",
        "doc://com.apple.photokit/documentation/PhotoKit/editing-request-info-keys"
      ],
      "title": "Editing an Asset"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title",
          "value": "PHAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1cancelContentEditingInputRequest(_:)/title",
          "value": "cancelContentEditingInputRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1cancelContentEditingInputRequest(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelContentEditingInputRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAdjustmentData/title",
          "value": "PHAdjustmentData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAdjustmentData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAdjustmentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAdjustmentData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAdjustmentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestOptions/title",
          "value": "PHContentEditingInputRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInputRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInputRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1requestContentEditingInput(with:completionHandler:)/title",
          "value": "requestContentEditingInputWithOptions:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1requestContentEditingInput(with:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestContentEditingInputWithOptions:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest/title",
          "value": "PHAssetChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame/title",
          "value": "PHLivePhotoFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInput/title",
          "value": "PHContentEditingInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1canPerform(_:)/title",
          "value": "canPerformEditOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1canPerform(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canPerformEditOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetEditOperation/title",
          "value": "PHAssetEditOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetEditOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetEditOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetEditOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetEditOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestID/title",
          "value": "PHContentEditingInputRequestID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInputRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInputRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingOutput/title",
          "value": "PHContentEditingOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/title",
          "value": "PHPhotoLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1contentEditingOutput/title",
          "value": "contentEditingOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1contentEditingOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentEditingOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingContext/title",
          "value": "PHLivePhotoEditingContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoEditingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoEditingContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
