{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.photokit/documentation/PhotoKit/fetching-assets"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/PhotoKit","doc://com.apple.photokit/documentation/Photos","doc://com.apple.photokit/documentation/Photos/PHAsset"]]},"abstract":[{"text":"Retrieve asset metadata or request full asset content.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(in:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withLocalIdentifiers:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchKeyAssets(in:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withBurstIdentifier:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withALAssetURLs:options:)"],"generated":true,"title":"Fetching Assets","anchor":"Fetching-Assets"}],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"You fetch assets to begin working with them. Use the class methods listed in Fetching Assets to retrieve one or more "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset"},{"type":"text","text":" instances representing the assets you want to display or edit. For example, to fetch all the assets in an asset collection (such as an album or moment), use the "},{"isActive":true,"identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(in:options:)","type":"reference"},{"text":" method. Each fetch method takes a ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchOptions","type":"reference"},{"text":" parameter that you use to specify the assets to retrieve and how to sort them.","type":"text"}],"type":"paragraph"},{"style":"important","type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Accessing or modifying the Photos library requires explicit authorization from the user. The first time you call one of the methods listed in Fetching Assets, Photos automatically prompts the user for authorization. Alternatively, you can use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(_:)"},{"text":" method to prompt the user at a time of your choosing. For more information, see ","type":"text"},{"code":"Requesting Authorization to Access Photos","type":"codeVoice"},{"text":".","type":"text"}]}]}]}],"kind":"article","metadata":{"title":"Fetching Assets","roleHeading":"Article","role":"article","modules":[{"name":"Photos"}]},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(_:)":{"title":"requestAuthorization(_:)","type":"topic","role":"symbol","deprecated":true,"url":"/documentation/photos/phphotolibrary/requestauthorization(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestAuthorization","kind":"identifier"},{"text":"((","kind":"text"},{"preciseIdentifier":"c:@E@PHAuthorizationStatus","text":"PHAuthorizationStatus","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"requestAuthorization:","kind":"identifier"}],"abstract":[{"text":"Requests the user’s permission, if needed, to access the photo library.","type":"text"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(_:)","kind":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withBurstIdentifier:options:)":{"title":"fetchAssets(withBurstIdentifier:options:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchAssets"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBurstIdentifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHFetchOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions"},{"text":"?) -> ","kind":"text"},{"text":"PHFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult"},{"text":"<","kind":"text"},{"text":"PHAsset","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHAsset"},{"text":">","kind":"text"}],"type":"topic","abstract":[{"text":"Retrieves assets with the specified burst photo sequence identifier.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withBurstIdentifier:options:)","role":"symbol","navigatorTitle":[{"text":"fetchAssetsWithBurstIdentifier:options:","kind":"identifier"}],"url":"/documentation/photos/phasset/fetchassets(withburstidentifier:options:)"},"doc://com.apple.photokit/documentation/PhotoKit":{"identifier":"doc://com.apple.photokit/documentation/PhotoKit","title":"PhotoKit","url":"/documentation/photokit","type":"topic","abstract":[{"type":"text","text":"Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos."}],"kind":"article","role":"collection"},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(in:options:)":{"kind":"symbol","role":"symbol","title":"fetchAssets(in:options:)","url":"/documentation/photos/phasset/fetchassets(in:options:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAssets"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PHAssetCollection","kind":"typeIdentifier","text":"PHAssetCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PHFetchOptions","kind":"typeIdentifier","text":"PHFetchOptions"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)PHFetchResult","kind":"typeIdentifier","text":"PHFetchResult"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)PHAsset","kind":"typeIdentifier","text":"PHAsset"},{"kind":"text","text":">"}],"type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(in:options:)","abstract":[{"text":"Retrieves assets from the specified asset collection.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fetchAssetsInAssetCollection:options:"}]},"doc://com.apple.photokit/documentation/Photos":{"title":"Photos","role":"collection","kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos","abstract":[{"type":"text","text":"Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos."}],"type":"topic","url":"/documentation/photos"},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchKeyAssets(in:options:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchKeyAssets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHAssetCollection","text":"PHAssetCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions","text":"PHFetchOptions"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"navigatorTitle":[{"text":"fetchKeyAssetsInAssetCollection:options:","kind":"identifier"}],"role":"symbol","url":"/documentation/photos/phasset/fetchkeyassets(in:options:)","abstract":[{"text":"Retrieves assets marked as key assets in the specified asset collection.","type":"text"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchKeyAssets(in:options:)","kind":"symbol","type":"topic","title":"fetchKeyAssets(in:options:)"},"doc://com.apple.photokit/documentation/Photos/PHFetchOptions":{"navigatorTitle":[{"kind":"identifier","text":"PHFetchOptions"}],"url":"/documentation/photos/phfetchoptions","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHFetchOptions"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchOptions","role":"symbol","abstract":[{"type":"text","text":"A set of options that affect the filtering, sorting, and management of results that Photos returns when you fetch asset or collection objects."}],"title":"PHFetchOptions"},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:options:)":{"abstract":[{"text":"Retrieves assets with the specified media type.","type":"text"}],"type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:options:)","role":"symbol","navigatorTitle":[{"text":"fetchAssetsWithMediaType:options:","kind":"identifier"}],"title":"fetchAssets(with:options:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchAssets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHAssetMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@E@PHAssetMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions","text":"PHFetchOptions"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","url":"/documentation/photos/phasset/fetchassets(with:options:)"},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:)":{"abstract":[{"text":"Retrieves all assets matching the specified options.","type":"text"}],"type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:)","role":"symbol","navigatorTitle":[{"text":"fetchAssetsWithOptions:","kind":"identifier"}],"title":"fetchAssets(with:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchAssets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHFetchOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset"},{"kind":"text","text":">"}],"kind":"symbol","url":"/documentation/photos/phasset/fetchassets(with:)"},"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary":{"title":"PHPhotoLibrary","navigatorTitle":[{"text":"PHPhotoLibrary","kind":"identifier"}],"url":"/documentation/photos/phphotolibrary","type":"topic","abstract":[{"text":"An object that manages access and changes to the user’s photo library.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PHPhotoLibrary","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary"},"doc://com.apple.photokit/documentation/Photos/PHAsset":{"abstract":[{"text":"A representation of an image, video, or Live Photo in the Photos library.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHAsset"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset","url":"/documentation/photos/phasset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PHAsset"}],"type":"topic","title":"PHAsset","kind":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withALAssetURLs:options:)":{"deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Retrieves assets using URLs provided by the Assets Library framework."}],"kind":"symbol","title":"fetchAssets(withALAssetURLs:options:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAssets"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withALAssetURLs"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"], ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHFetchOptions","text":"PHFetchOptions","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"/documentation/photos/phasset/fetchassets(withalasseturls:options:)","type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withALAssetURLs:options:)","navigatorTitle":[{"text":"fetchAssetsWithALAssetURLs:options:","kind":"identifier"}]},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withLocalIdentifiers:options:)":{"type":"topic","kind":"symbol","role":"symbol","title":"fetchAssets(withLocalIdentifiers:options:)","abstract":[{"type":"text","text":"Retrieves assets with the specified local-device-specific unique identifiers."}],"url":"/documentation/photos/phasset/fetchassets(withlocalidentifiers:options:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchAssets","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withLocalIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHFetchOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions"},{"text":"?) -> ","kind":"text"},{"text":"PHFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withLocalIdentifiers:options:)","navigatorTitle":[{"text":"fetchAssetsWithLocalIdentifiers:options:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1requestAuthorization(_:)/title","op":"replace","value":"requestAuthorization:"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1requestAuthorization(_:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"requestAuthorization:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withBurstIdentifier:options:)/title","op":"replace","value":"fetchAssetsWithBurstIdentifier:options:"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withBurstIdentifier:options:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fetchAssetsWithBurstIdentifier:options:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(in:options:)/title","op":"replace","value":"fetchAssetsInAssetCollection:options:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchAssetsInAssetCollection:options:"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(in:options:)/fragments"},{"value":"fetchKeyAssetsInAssetCollection:options:","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchKeyAssets(in:options:)/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchKeyAssetsInAssetCollection:options:"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchKeyAssets(in:options:)/fragments"},{"value":"PHFetchOptions","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchOptions/title"},{"value":[{"text":"PHFetchOptions","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchOptions/fragments"},{"value":[{"text":"PHFetchOptions","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchOptions/navigatorTitle"},{"value":"fetchAssetsWithMediaType:options:","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(with:options:)/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchAssetsWithMediaType:options:"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(with:options:)/fragments"},{"value":"fetchAssetsWithOptions:","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(with:)/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"fetchAssetsWithOptions:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(with:)/fragments"},{"value":"PHPhotoLibrary","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/title"},{"value":[{"text":"PHPhotoLibrary","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/fragments"},{"value":[{"text":"PHPhotoLibrary","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/navigatorTitle"},{"value":"PHAsset","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title"},{"value":[{"kind":"identifier","text":"PHAsset"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments"},{"value":[{"kind":"identifier","text":"PHAsset"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle"},{"value":"fetchAssetsWithALAssetURLs:options:","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withALAssetURLs:options:)/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"fetchAssetsWithALAssetURLs:options:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withALAssetURLs:options:)/fragments"},{"value":"fetchAssetsWithLocalIdentifiers:options:","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withLocalIdentifiers:options:)/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"fetchAssetsWithLocalIdentifiers:options:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withLocalIdentifiers:options:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}