{
  "abstract": [
    {
      "text": "Special values for the Live Photo request ID that are returned by asynchronous requests.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotoKit",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhoto"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotoKit/image-request-identifiers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Image Request Identifiers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit",
      "kind": "article",
      "role": "collection",
      "title": "PhotoKit",
      "type": "topic",
      "url": "/documentation/photokit"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/result-handler-info-dictionary-keys": {
      "abstract": [
        {
          "text": "Info describing an attempt to load a Live Photo.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/result-handler-info-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Result Handler Info Dictionary Keys",
      "type": "topic",
      "url": "/documentation/photokit/result-handler-info-dictionary-keys"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhoto": {
      "abstract": [
        {
          "text": "A displayable representation of a Live Photo—a picture that includes motion and sound from the moments just before and after its capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhoto"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhoto",
      "type": "topic",
      "url": "/documentation/photos/phlivephoto"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestID": {
      "abstract": [
        {
          "text": "A numeric identifier for an asynchronous Live Photo loading request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoRequestID"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoRequestID",
      "type": "topic",
      "url": "/documentation/photos/phlivephotorequestid"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestIDInvalid": {
      "abstract": [
        {
          "text": "The asynchronous Live Photo loading request cannot be canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoRequestIDInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHLivePhotoRequestID",
          "text": "PHLivePhotoRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestIDInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoRequestIDInvalid"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoRequestIDInvalid",
      "type": "topic",
      "url": "/documentation/photos/phlivephotorequestidinvalid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestID",
        "doc://com.apple.photokit/documentation/PhotoKit/result-handler-info-dictionary-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestIDInvalid"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestIDInvalid/title",
          "value": "PHLivePhotoRequestIDInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestIDInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoRequestIDInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestID/title",
          "value": "PHLivePhotoRequestID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/title",
          "value": "PHLivePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhoto"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
