{"metadata":{"modules":[{"name":"Photos"}],"roleHeading":"Article","title":"Observing Changes in the Photo Library","role":"article"},"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"To be notified of changes to the photo library, use the ","type":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/register(_:)-6y3b9","type":"reference","isActive":true},{"text":" method to designate an observer object. Whenever you use a fetch method, such as ","type":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:)","type":"reference","isActive":true},{"text":", to retrieve assets or collections, Photos automatically registers your interest in observing changes to those items. After you perform a fetch, Photos sends messages to your observer through the ","type":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver","type":"reference","isActive":true},{"text":" protocol whenever the items in the resulting fetch request change. For example, you’ll get notified when changes add items, remove items, or reorder the list of items in the fetch result. Update your user interface based on the details you receive from ","type":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHChange","type":"reference","isActive":true},{"text":" objects.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Use the shared "},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary","isActive":true,"type":"reference"},{"type":"text","text":" object to register a change handler for the assets and collections you fetch. Photos tells your app whenever another app or device changes the content or metadata of an asset or the list of assets in a collection. "},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHChange","isActive":true,"type":"reference"},{"type":"text","text":" objects provide information about object state before and after each change with semantics that make it easy to update a collection view or similar interface."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For information about handling changes, see the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver"},{"type":"text","text":" protocol."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc://com.apple.photokit/documentation/PhotoKit/observing-changes-in-the-photo-library","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/register(_:)-6y3b9","doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/unregisterChangeObserver(_:)","doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver","doc://com.apple.photokit/documentation/Photos/PHChange","doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails"],"anchor":"Observing-Library-Changes","generated":true,"title":"Observing Library Changes"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/PhotoKit","doc://com.apple.photokit/documentation/Photos","doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary"]]},"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Register an observer to be notified of changes to the photo library."}],"sections":[],"references":{"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary":{"title":"PHPhotoLibrary","navigatorTitle":[{"text":"PHPhotoLibrary","kind":"identifier"}],"url":"/documentation/photos/phphotolibrary","type":"topic","abstract":[{"text":"An object that manages access and changes to the user’s photo library.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PHPhotoLibrary","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary"},"doc://com.apple.photokit/documentation/Photos/PHChange":{"type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHChange","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHChange"}],"role":"symbol","title":"PHChange","abstract":[{"type":"text","text":"A description of a change that occurred in the photo library."}],"url":"/documentation/photos/phchange","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PHChange"}]},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:)":{"abstract":[{"text":"Retrieves all assets matching the specified options.","type":"text"}],"type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:)","role":"symbol","navigatorTitle":[{"text":"fetchAssetsWithOptions:","kind":"identifier"}],"title":"fetchAssets(with:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchAssets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHFetchOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset"},{"kind":"text","text":">"}],"kind":"symbol","url":"/documentation/photos/phasset/fetchassets(with:)"},"doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PHPhotoLibraryChangeObserver"}],"url":"/documentation/photos/phphotolibrarychangeobserver","abstract":[{"type":"text","text":"A protocol to adopt to have the system notify your app of changes to the photo library."}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver","role":"symbol","type":"topic","title":"PHPhotoLibraryChangeObserver","navigatorTitle":[{"kind":"identifier","text":"PHPhotoLibraryChangeObserver"}],"kind":"symbol"},"doc://com.apple.photokit/documentation/PhotoKit":{"identifier":"doc://com.apple.photokit/documentation/PhotoKit","title":"PhotoKit","url":"/documentation/photokit","type":"topic","abstract":[{"type":"text","text":"Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos."}],"kind":"article","role":"collection"},"doc://com.apple.photokit/documentation/Photos":{"title":"Photos","role":"collection","kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos","abstract":[{"type":"text","text":"Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos."}],"type":"topic","url":"/documentation/photos"},"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/unregisterChangeObserver(_:)":{"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/unregisterChangeObserver(_:)","url":"/documentation/photos/phphotolibrary/unregisterchangeobserver(_:)","title":"unregisterChangeObserver(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterChangeObserver"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)PHPhotoLibraryChangeObserver","kind":"typeIdentifier","text":"PHPhotoLibraryChangeObserver"},{"kind":"text","text":")"}],"abstract":[{"text":"Unregisters an object so that it no longer receives change messages.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"unregisterChangeObserver:"}]},"doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails":{"url":"/documentation/photos/phobjectchangedetails","identifier":"doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails","abstract":[{"type":"text","text":"A description of changes that occurred in an asset or collection object."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHObjectChangeDetails"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PHObjectChangeDetails"}],"kind":"symbol","role":"symbol","title":"PHObjectChangeDetails"},"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/register(_:)-6y3b9":{"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/register(_:)-6y3b9","url":"/documentation/photos/phphotolibrary/register(_:)-6y3b9","title":"register(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)PHPhotoLibraryChangeObserver","kind":"typeIdentifier","text":"PHPhotoLibraryChangeObserver"},{"kind":"text","text":")"}],"abstract":[{"text":"Registers an object to receive messages when objects in the photo library change.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerChangeObserver:"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails":{"title":"PHFetchResultChangeDetails","identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails","abstract":[{"text":"A description of changes that occurred in the set of asset or collection objects listed in a fetch result.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PHFetchResultChangeDetails","kind":"identifier"}],"navigatorTitle":[{"text":"PHFetchResultChangeDetails","kind":"identifier"}],"url":"/documentation/photos/phfetchresultchangedetails","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":"PHPhotoLibrary","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/title"},{"op":"replace","value":[{"kind":"identifier","text":"PHPhotoLibrary"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PHPhotoLibrary"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/navigatorTitle"},{"op":"replace","value":"PHChange","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChange/title"},{"op":"replace","value":[{"text":"PHChange","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChange/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PHChange"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChange/navigatorTitle"},{"op":"replace","value":"fetchAssetsWithOptions:","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(with:)/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fetchAssetsWithOptions:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(with:)/fragments"},{"op":"replace","value":"PHPhotoLibraryChangeObserver","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibraryChangeObserver/title"},{"op":"replace","value":[{"kind":"identifier","text":"PHPhotoLibraryChangeObserver"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibraryChangeObserver/fragments"},{"op":"replace","value":[{"text":"PHPhotoLibraryChangeObserver","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibraryChangeObserver/navigatorTitle"},{"op":"replace","value":"unregisterChangeObserver:","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1unregisterChangeObserver(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unregisterChangeObserver:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1unregisterChangeObserver(_:)/fragments"},{"op":"replace","value":"PHObjectChangeDetails","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectChangeDetails/title"},{"op":"replace","value":[{"text":"PHObjectChangeDetails","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectChangeDetails/fragments"},{"op":"replace","value":[{"text":"PHObjectChangeDetails","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectChangeDetails/navigatorTitle"},{"op":"replace","value":"registerChangeObserver:","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1register(_:)-6y3b9/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"registerChangeObserver:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1register(_:)-6y3b9/fragments"},{"op":"replace","value":"PHFetchResultChangeDetails","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails/title"},{"op":"replace","value":[{"text":"PHFetchResultChangeDetails","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails/fragments"},{"value":[{"text":"PHFetchResultChangeDetails","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}