{
  "abstract": [
    {
      "text": "Special values for the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceDataRequestID",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " identifier that are returned by asynchronous requests.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotoKit",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotoKit/resource-loading-request-identifiers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Resource Loading Request Identifiers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit",
      "kind": "article",
      "role": "collection",
      "title": "PhotoKit",
      "type": "topic",
      "url": "/documentation/photokit"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceDataRequestID": {
      "abstract": [
        {
          "text": "A numeric identifier for an asynchronous asset resource loading request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceDataRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceDataRequestID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceDataRequestID"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceDataRequestID",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcedatarequestid"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager": {
      "abstract": [
        {
          "text": "A resource manager for the data storage underlying a Photos asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceManager"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceManager"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceManager",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcemanager"
    },
    "doc://com.apple.photokit/documentation/Photos/PHInvalidAssetResourceDataRequestID": {
      "abstract": [
        {
          "text": "The asynchronous resource loading request cannot be canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHInvalidAssetResourceDataRequestID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHAssetResourceDataRequestID",
          "text": "PHAssetResourceDataRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHInvalidAssetResourceDataRequestID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHInvalidAssetResourceDataRequestID"
        }
      ],
      "role": "symbol",
      "title": "PHInvalidAssetResourceDataRequestID",
      "type": "topic",
      "url": "/documentation/photos/phinvalidassetresourcedatarequestid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceDataRequestID"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHInvalidAssetResourceDataRequestID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceDataRequestID/title",
          "value": "PHAssetResourceDataRequestID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceDataRequestID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceDataRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceDataRequestID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceDataRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHInvalidAssetResourceDataRequestID/title",
          "value": "PHInvalidAssetResourceDataRequestID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHInvalidAssetResourceDataRequestID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHInvalidAssetResourceDataRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager/title",
          "value": "PHAssetResourceManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
