{
  "abstract": [
    {
      "text": "Info describing an attempt to load a Live Photo.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotoKit",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhoto"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotoKit/result-handler-info-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Result Handler Info Dictionary Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These keys are in the ",
              "type": "text"
            },
            {
              "code": "info",
              "type": "codeVoice"
            },
            {
              "text": " dictionary of the result handler you provide for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhoto/request(withResourceFileURLs:placeholderImage:targetSize:contentMode:resultHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit",
      "kind": "article",
      "role": "collection",
      "title": "PhotoKit",
      "type": "topic",
      "url": "/documentation/photokit"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/image-request-identifiers": {
      "abstract": [
        {
          "text": "Special values for the Live Photo request ID that are returned by asynchronous requests.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/image-request-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Request Identifiers",
      "type": "topic",
      "url": "/documentation/photokit/image-request-identifiers"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhoto": {
      "abstract": [
        {
          "text": "A displayable representation of a Live Photo—a picture that includes motion and sound from the moments just before and after its capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhoto"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhoto",
      "type": "topic",
      "url": "/documentation/photos/phlivephoto"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhoto/request(withResourceFileURLs:placeholderImage:targetSize:contentMode:resultHandler:)": {
      "abstract": [
        {
          "text": "Asynchronously loads a Live Photo from the specified resource files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "request"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withResourceFileURLs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "placeholderImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "targetSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHImageContentMode",
          "text": "PHImageContentMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHLivePhoto",
          "text": "PHLivePhoto"
        },
        {
          "kind": "text",
          "text": "?, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHLivePhotoRequestID",
          "text": "PHLivePhotoRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhoto/request(withResourceFileURLs:placeholderImage:targetSize:contentMode:resultHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestLivePhotoWithResourceFileURLs:placeholderImage:targetSize:contentMode:resultHandler:"
        }
      ],
      "role": "symbol",
      "title": "request(withResourceFileURLs:placeholderImage:targetSize:contentMode:resultHandler:)",
      "type": "topic",
      "url": "/documentation/photos/phlivephoto/request(withresourcefileurls:placeholderimage:targetsize:contentmode:resulthandler:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoInfoCancelledKey": {
      "abstract": [
        {
          "text": "A Boolean (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ") value indicating whether the Live Photo loading request was canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoInfoCancelledKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoInfoCancelledKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoInfoCancelledKey"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoInfoCancelledKey",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoinfocancelledkey"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoInfoErrorKey": {
      "abstract": [
        {
          "text": "An error that occurred while attempting to load the requested Live Photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoInfoErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoInfoErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoInfoErrorKey"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoInfoErrorKey",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoinfoerrorkey"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoInfoIsDegradedKey": {
      "abstract": [
        {
          "text": "A Boolean (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ") value indicating whether the result Live Photo is a low-quality substitute for the requested Live Photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoInfoIsDegradedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoInfoIsDegradedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoInfoIsDegradedKey"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoInfoIsDegradedKey",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoinfoisdegradedkey"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestID": {
      "abstract": [
        {
          "text": "A numeric identifier for an asynchronous Live Photo loading request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoRequestID"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoRequestID",
      "type": "topic",
      "url": "/documentation/photos/phlivephotorequestid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestID",
        "doc://com.apple.photokit/documentation/PhotoKit/image-request-identifiers"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoInfoErrorKey",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoInfoIsDegradedKey",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoInfoCancelledKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoInfoCancelledKey/title",
          "value": "PHLivePhotoInfoCancelledKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoInfoCancelledKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoInfoCancelledKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoInfoIsDegradedKey/title",
          "value": "PHLivePhotoInfoIsDegradedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoInfoIsDegradedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoInfoIsDegradedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto~1request(withResourceFileURLs:placeholderImage:targetSize:contentMode:resultHandler:)/title",
          "value": "requestLivePhotoWithResourceFileURLs:placeholderImage:targetSize:contentMode:resultHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto~1request(withResourceFileURLs:placeholderImage:targetSize:contentMode:resultHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestLivePhotoWithResourceFileURLs:placeholderImage:targetSize:contentMode:resultHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/title",
          "value": "PHLivePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoInfoErrorKey/title",
          "value": "PHLivePhotoInfoErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoInfoErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoInfoErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestID/title",
          "value": "PHLivePhotoRequestID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoRequestID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
