{
  "abstract": [
    {
      "text": "Measures the performance of a block of code, optionally deferring the starting point for measurement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "XCTest",
    "externalID": "c:objc(cs)XCTestCase(im)measureMetrics:automaticallyStartMeasuring:forBlock:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "measureMetrics"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@XCTPerformanceMetric",
        "text": "XCTPerformanceMetric"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "automaticallyStartMeasuring"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": () -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "measureMetrics:automaticallyStartMeasuring:forBlock:"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "measureMetrics(_:automaticallyStartMeasuring:for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "measureMetrics"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "metrics"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@XCTPerformanceMetric",
              "text": "XCTPerformanceMetric"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "automaticallyStartMeasuring"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ": () -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of performance metrics to measure. Each metric is measured across calls to the block. Pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/wallClockTime",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to measure the number of seconds taken to execute the  block of code.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "metrics"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", measurements will not be taken until ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " is called inside the block.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "automaticallyStartMeasuring"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block whose performance is measured.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "block"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this method from within a test method to measure the performance of a block of code. This method provides more granular control over performance measurement than the  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, and should be used when you need to customize the points at which measurement starts and ends within the block, or wish to measure multiple metrics for the block.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Performance measurement must be started and stopped exactly once within the block. As a result:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If ",
                      "type": "text"
                    },
                    {
                      "code": "automaticallyStartMeasuring",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/swift/true",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is called inside the block, the test will fail.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If ",
                      "type": "text"
                    },
                    {
                      "code": "automaticallyStartMeasuring",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/swift/false",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " must be called once and only once before the end of the block, or the test will fail.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/stopMeasuring()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is called multiple times during the block the test will fail.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric": {
      "abstract": [
        {
          "text": "Performance metrics that the test records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTPerformanceMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/wallClockTime": {
      "abstract": [
        {
          "text": "A performance metric that records the time in seconds to execute a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wallClockTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCTPerformanceMetric",
          "text": "XCTPerformanceMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/wallClockTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMetric_WallClockTime"
        }
      ],
      "role": "symbol",
      "title": "wallClockTime",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemetric/wallclocktime"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase": {
      "abstract": [
        {
          "text": "The primary class for defining test cases, test methods, and performance tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "role": "symbol",
      "title": "XCTestCase",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMeasureOptions": {
      "abstract": [
        {
          "text": "The default measurement options the test uses to record performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultMeasureOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
          "text": "XCTMeasureOptions"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMeasureOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultMeasureOptions"
        }
      ],
      "role": "symbol",
      "title": "defaultMeasureOptions",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/defaultmeasureoptions"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMetrics": {
      "abstract": [
        {
          "text": "An array of default metrics the test uses to record performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultMetrics"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultMetrics"
        }
      ],
      "role": "symbol",
      "title": "defaultMetrics",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/defaultmetrics"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultPerformanceMetrics": {
      "abstract": [
        {
          "text": "An array of default performance metrics the test records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultPerformanceMetrics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCTPerformanceMetric",
          "text": "XCTPerformanceMetric"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultPerformanceMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultPerformanceMetrics"
        }
      ],
      "role": "symbol",
      "title": "defaultPerformanceMetrics",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/defaultperformancemetrics"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(_:)": {
      "abstract": [
        {
          "text": "Measures the performance of a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "(() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measureBlock:"
        }
      ],
      "role": "symbol",
      "title": "measure(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/measure(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:block:)": {
      "abstract": [
        {
          "text": "Records the selected metrics for a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "metrics"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:block:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measureWithMetrics:block:"
        }
      ],
      "role": "symbol",
      "title": "measure(metrics:block:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/measure(metrics:block:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:options:block:)": {
      "abstract": [
        {
          "text": "Records the selected metrics, using the specified measurement options, for a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "metrics"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
          "text": "XCTMeasureOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:options:block:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measureWithMetrics:options:block:"
        }
      ],
      "role": "symbol",
      "title": "measure(metrics:options:block:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/measure(metrics:options:block:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(options:block:)": {
      "abstract": [
        {
          "text": "Records the performance, using the specified measurement options, for a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
          "text": "XCTMeasureOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(options:block:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measureWithOptions:block:"
        }
      ],
      "role": "symbol",
      "title": "measure(options:block:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/measure(options:block:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)": {
      "abstract": [
        {
          "text": "Measures the performance of a block of code, optionally deferring the starting point for measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measureMetrics"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCTPerformanceMetric",
          "text": "XCTPerformanceMetric"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "automaticallyStartMeasuring"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measureMetrics:automaticallyStartMeasuring:forBlock:"
        }
      ],
      "role": "symbol",
      "title": "measureMetrics(_:automaticallyStartMeasuring:for:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/measuremetrics(_:automaticallystartmeasuring:for:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()": {
      "abstract": [
        {
          "text": "Starts recording performance metrics within a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMeasuring"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startMeasuring"
        }
      ],
      "role": "symbol",
      "title": "startMeasuring()",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/startmeasuring()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/stopMeasuring()": {
      "abstract": [
        {
          "text": "Ends recording performance metrics within a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopMeasuring"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/stopMeasuring()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopMeasuring"
        }
      ],
      "role": "symbol",
      "title": "stopMeasuring()",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/stopmeasuring()"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/wallClockTime"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Measuring-Performance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:block:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:options:block:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(options:block:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/stopMeasuring()",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultPerformanceMetrics",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMetrics",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMeasureOptions",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric"
      ],
      "title": "Measuring Performance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "measureMetrics:automaticallyStartMeasuring:forBlock:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureMetrics:automaticallyStartMeasuring:forBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/wallClockTime"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Measuring-Performance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:block:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:options:block:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(options:block:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/stopMeasuring()",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultPerformanceMetrics",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMetrics",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMeasureOptions",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric"
              ],
              "title": "Measuring Performance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "measureMetrics:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSString *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "metrics"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "automaticallyStartMeasuring:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "automaticallyStartMeasuring"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forBlock:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)()) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "block"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of performance metrics to measure. Each metric is measured across calls to the block. Pass ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/wallClockTime",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to measure the number of seconds taken to execute the  block of code.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "metrics"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", measurements will not be taken until ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " is called inside the block.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "automaticallyStartMeasuring"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block whose performance is measured.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "block"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(metrics:options:block:)/title",
          "value": "measureWithMetrics:options:block:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(metrics:options:block:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureWithMetrics:options:block:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(options:block:)/title",
          "value": "measureWithOptions:block:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(options:block:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureWithOptions:block:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultPerformanceMetrics/title",
          "value": "defaultPerformanceMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultPerformanceMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultPerformanceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMetric~1wallClockTime/title",
          "value": "XCTPerformanceMetric_WallClockTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMetric~1wallClockTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMetric_WallClockTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1startMeasuring()/title",
          "value": "startMeasuring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1startMeasuring()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMeasuring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1stopMeasuring()/title",
          "value": "stopMeasuring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1stopMeasuring()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopMeasuring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultMeasureOptions/title",
          "value": "defaultMeasureOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultMeasureOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultMeasureOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measureMetrics(_:automaticallyStartMeasuring:for:)/title",
          "value": "measureMetrics:automaticallyStartMeasuring:forBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measureMetrics(_:automaticallyStartMeasuring:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureMetrics:automaticallyStartMeasuring:forBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(metrics:block:)/title",
          "value": "measureWithMetrics:block:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(metrics:block:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureWithMetrics:block:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMetric/title",
          "value": "XCTPerformanceMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(_:)/title",
          "value": "measureBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/title",
          "value": "XCTestCase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultMetrics/title",
          "value": "defaultMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultMetrics"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctestcase/measuremetrics(_:automaticallystartmeasuring:for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctestcase/measuremetrics(_:automaticallystartmeasuring:for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
