{
  "abstract": [
    {
      "text": "Creates a test case with an invocation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/testCaseWithInvocation:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTestCase(cm)testCaseWithInvocation:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "testCaseWithInvocation:"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "testCaseWithInvocation:"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "testCaseWithInvocation:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "testCaseWithInvocation:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSInvocation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSInvocation",
              "text": "NSInvocation"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "invocation"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An invocation to use when running this test.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "invocation"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A test case with an invocation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase": {
      "abstract": [
        {
          "text": "The primary class for defining test cases, test methods, and performance tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "role": "symbol",
      "title": "XCTestCase",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultTestSuite": {
      "abstract": [
        {
          "text": "A test suite that contains test cases for all of the tests in the class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultTestSuite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultTestSuite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultTestSuite"
        }
      ],
      "role": "symbol",
      "title": "defaultTestSuite",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/defaulttestsuite"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/init(invocation:)": {
      "abstract": [
        {
          "text": "Initializes a test case with an invocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "invocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSInvocation",
          "text": "NSInvocation"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/init(invocation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithInvocation:"
        }
      ],
      "role": "symbol",
      "title": "init(invocation:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/init(invocation:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/init(selector:)": {
      "abstract": [
        {
          "text": "Initializes a test case with a selector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "selector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/init(selector:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSelector:"
        }
      ],
      "role": "symbol",
      "title": "init(selector:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/init(selector:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/invocation": {
      "abstract": [
        {
          "text": "The invocation for running the test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSInvocation",
          "text": "NSInvocation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/invocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invocation"
        }
      ],
      "role": "symbol",
      "title": "invocation",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/invocation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/invokeTest()": {
      "abstract": [
        {
          "text": "Invokes the test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invokeTest"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/invokeTest()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invokeTest"
        }
      ],
      "role": "symbol",
      "title": "invokeTest()",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/invoketest()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/record(_:)": {
      "abstract": [
        {
          "text": "Records an issue during test execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6XCTest8XCTIssueV",
          "text": "XCTIssue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/record(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordIssue:"
        }
      ],
      "role": "symbol",
      "title": "record(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/record(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/recordFailure(withDescription:inFile:atLine:expected:)": {
      "abstract": [
        {
          "text": "Records a failure during text execution.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordFailure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "expected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/recordFailure(withDescription:inFile:atLine:expected:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordFailureWithDescription:inFile:atLine:expected:"
        }
      ],
      "role": "symbol",
      "title": "recordFailure(withDescription:inFile:atLine:expected:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/recordfailure(withdescription:infile:atline:expected:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/testCaseWithInvocation:": {
      "abstract": [
        {
          "text": "Creates a test case with an invocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "testCaseWithInvocation:"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/testCaseWithInvocation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCaseWithInvocation:"
        }
      ],
      "role": "symbol",
      "title": "testCaseWithInvocation:",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/testcasewithinvocation:"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/testCaseWithSelector:": {
      "abstract": [
        {
          "text": "Creates a test case with a selector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "testCaseWithSelector:"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/testCaseWithSelector:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCaseWithSelector:"
        }
      ],
      "role": "symbol",
      "title": "testCaseWithSelector:",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/testcasewithselector:"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/testInvocations": {
      "abstract": [
        {
          "text": "An array of invocations that represents each test method in the test case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testInvocations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSInvocation",
          "text": "NSInvocation"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/testInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testInvocations"
        }
      ],
      "role": "symbol",
      "title": "testInvocations",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/testinvocations"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSInvocation": {
      "abstract": [
        {
          "text": "An Objective-C message rendered as an object.  ",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSInvocation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInvocation",
      "type": "topic",
      "url": "/documentation/foundation/nsinvocation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Tests-Programmatically",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/init(invocation:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/init(selector:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/testCaseWithSelector:",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/testInvocations",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/invocation",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/invokeTest()",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/record(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/recordFailure(withDescription:inFile:atLine:expected:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultTestSuite"
      ],
      "title": "Creating Tests Programmatically"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1init(invocation:)/title",
          "value": "initWithInvocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1init(invocation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithInvocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1testInvocations/title",
          "value": "testInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1testInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "testInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1invokeTest()/title",
          "value": "invokeTest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1invokeTest()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invokeTest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/title",
          "value": "XCTestCase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1record(_:)/title",
          "value": "recordIssue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1record(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordIssue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1recordFailure(withDescription:inFile:atLine:expected:)/title",
          "value": "recordFailureWithDescription:inFile:atLine:expected:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1recordFailure(withDescription:inFile:atLine:expected:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordFailureWithDescription:inFile:atLine:expected:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1init(selector:)/title",
          "value": "initWithSelector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1init(selector:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSelector:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1invocation/title",
          "value": "invocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1invocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "invocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultTestSuite/title",
          "value": "defaultTestSuite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultTestSuite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultTestSuite"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctestcase/testcasewithinvocation:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
